### ISSUE TITLE
firebase as module

### ISSUE THREAD

**Issue by dominik0711** [firebase/firebase-tools#100]
Hi. I would like to use `firebase list` as a module to retrieve a list/array of database ids. Could someone give me a hint how to do that?

Thanks in advance!
dominik

**Comment by mbleigh** [comment]
Hey Dominik, check out [this section of the README](https://github.com/firebase/firebase-tools#using-as-a-module) :smile:

**Comment by dominik0711** [comment]
Hi Michael. Thanks for your comment. I have already read the section but I'll get the following error:
```Error: TypeError: Cannot set property 'user' of undefined```
I've tried to use the sample code described in the readme:
```
'use strict';

var dbList = function (options) {
  console.log("Start DbList...");
  var client = require('firebase-tools');
  client.list().then(function(data) {
    console.log(data);
  }).catch(function(err) {
    // handle error
    console.log("Error: " + err);
  });
};

module.exports = dbList;
```

**Comment by canhnht** [comment]
I got the same error. :( Please re-open this issue.
