### ISSUE TITLE
setup:web INVALID_ARGUMENT status code 400

### ISSUE THREAD

**Issue by shaunc869** [firebase/firebase-tools#1015]
Version info: 6.1.0
Platform Information: OSX
### Steps to reproduce

cd dir
firebase init (hosting only)
select existing project
firebase serve --only hosting --debug

It runs the site locally.

[2018-11-15T17:12:15.331Z] <<< HTTP RESPONSE 400 vary=X-Origin, Referer, Origin,Accept-Encoding, content-type=application/json; charset=UTF-8, date=Thu, 15 Nov 2018 17:12:15 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="44,43,39,35", accept-ranges=none, connection=close
[2018-11-15T17:12:15.331Z] <<< HTTP RESPONSE BODY code=400, message=Request contains an invalid argument., status=INVALID_ARGUMENT

Error: HTTP Error: 400, Request contains an invalid argument.
[2018-11-15T17:12:15.532Z] Error Context: {
  "body": {
    "error": {
      "code": 400,
      "message": "Request contains an invalid argument.",
      "status": "INVALID_ARGUMENT"
    }
  },
  "response": {
    "statusCode": 400,
    "body": {
      "error": {
        "code": 400,
        "message": "Request contains an invalid argument.",
        "status": "INVALID_ARGUMENT"
      }
    },
    "headers": {
      "vary": "X-Origin, Referer, Origin,Accept-Encoding",
      "content-type": "application/json; charset=UTF-8",
      "date": "Thu, 15 Nov 2018 17:12:15 GMT",
      "server": "ESF",
      "cache-control": "private",
      "x-xss-protection": "1; mode=block",
      "x-frame-options": "SAMEORIGIN",
      "x-content-type-options": "nosniff",
      "alt-svc": "quic=\":443\"; ma=2592000; v=\"44,43,39,35\"",
      "accept-ranges": "none",
      "connection": "close"
    },
    "request": {
      "uri": {
        "protocol": "https:",
        "slashes": true,
        "auth": null,
        "host": "mobilesdk-pa.googleapis.com",
        "port": 443,
        "hostname": "mobilesdk-pa.googleapis.com",
        "hash": null,
        "search": null,
        "query": null,
        "pathname": "/v1/projects/540833485883/clients/_:getWebAppConfig",
        "path": "/v1/projects/540833485883/clients/_:getWebAppConfig",
        "href": "https://mobilesdk-pa.googleapis.com/v1/projects/540833485883/clients/_:getWebAppConfig"
      },
      "method": "GET"
    }
  }
}

**Comment by rodrigodutraoliveira** [comment]
Same here:

```
Error: HTTP Error: 400, Request contains an invalid argument.
[2018-11-15T17:40:46.943Z] Error Context: {
  "body": {
    "error": {
      "code": 400,
      "message": "Request contains an invalid argument.",
      "status": "INVALID_ARGUMENT"
    }
  },
  "response": {
    "statusCode": 400,
    "body": {
      "error": {
        "code": 400,
        "message": "Request contains an invalid argument.",
        "status": "INVALID_ARGUMENT"
      }
    },
    "headers": {
      "vary": "X-Origin, Referer, Origin,Accept-Encoding",
      "content-type": "application/json; charset=UTF-8",
      "date": "Thu, 15 Nov 2018 17:40:46 GMT",
      "server": "ESF",
      "cache-control": "private",
      "x-xss-protection": "1; mode=block",
      "x-frame-options": "SAMEORIGIN",
      "x-content-type-options": "nosniff",
      "alt-svc": "quic=\":443\"; ma=2592000; v=\"44,43,39,35\"",
      "accept-ranges": "none",
      "connection": "close"
    },
    "request": {
      "uri": {
        "protocol": "https:",
        "slashes": true,
        "auth": null,
        "host": "mobilesdk-pa.googleapis.com",
        "port": 443,
        "hostname": "mobilesdk-pa.googleapis.com",
        "hash": null,
        "search": null,
        "query": null,
        "pathname": "/v1/projects/128559963708/clients/_:getWebAppConfig",
        "path": "/v1/projects/128559963708/clients/_:getWebAppConfig",
        "href": "https://mobilesdk-pa.googleapis.com/v1/projects/128559963708/clients/_:getWebAppConfig"
      },
      "method": "GET"
    }
  }
}```

**Comment by ricardoaaf** [comment]
I´m having exactly the same problem. I just tested the same project without any changes on another machine, and even another project that is running fine about 3 months, and the problem is the same. Deploying its normal, but localhost (_firebase serve --only functions,hosting --debug_) just stop working with this anoing error... 
I don´t think the problem is the app (mine or yours).
Everything was working fine about 2 hours ago!

**Comment by laurentpayot** [comment]
+1 for me

**Comment by rilian** [comment]
same issue. yesterday everything worked fine
```
[2018-11-15T17:22:20.885Z] >>> HTTP REQUEST GET https://mobilesdk-pa.googleapis.com/v1/projects/xxx/clients/_:getWebAppConfig

[2018-11-15T17:22:21.179Z] <<< HTTP RESPONSE BODY code=400, message=Request contains an invalid argument., status=INVALID_ARGUMENT
```

**Comment by goggledefogger** [comment]
+1 for me, and for a friend too, stopped working this morning when it was working fine yesterday. I don't see anything about it on https://status.firebase.google.com, is there anyone from Firebase who can comment?

**Comment by alexplumb** [comment]
+1 for me - everything stopped working all of a sudden. Upgrading to 6.1.0 also gives me this message: 

```
 functions: Preparing to emulate functions.
⚠  Setup required, please run: firebase setup:emulators:firestore
```

When I run that command, I get:

```
i  functions: Preparing to emulate functions.
✔  firestore: started on http://localhost:8080
⚠  firestore: Error: Invalid or corrupt jarfile /home/alex/.cache/firebase/emulators/cloud-firestore-emulator-v1.2.1.jar
```

Looking up the command I just ran, I found this page: https://firebase.google.com/docs/firestore/security/test-rules-emulator

I tried running ` firebase --open-sesame emulators` thinking it was an issue with 6.1.0 and got this error:
```
Error: Did not recognize preview feature
```

**Comment by gabergg** [comment]
+1 Same issue, started this morning

**Comment by keeganbrown** [comment]
+1

**Comment by zebralight** [comment]
Just wanted to add that I too am having this issue. firebase serve was working just fine yesterday.  This is on both firebase 6.0.1 and 6.1.0

**Comment by ameer1234567890** [comment]
I have the exact same issue.

**Comment by Neilpoulin** [comment]
same. I can't deploy now

**Comment by AskYous** [comment]
Me too:

![image](https://user-images.githubusercontent.com/791996/48573807-485aa680-e8c2-11e8-8b84-a04ddd9de404.png)

**Comment by bkendall** [comment]
Thank you all for bringing this to our attention. We are actively looking into this issue right now.

(Internal tracking number: 119615185)

**Comment by mbleigh** [comment]
@Neilpoulin you can't deploy? What version of the CLI are you using and what error are you getting?

**Comment by Neilpoulin** [comment]
Sorry- it’s not directly related to the fire base deploy command. my build
process includes a step that grabs these configs, and since it fails I
can’t deploy.

**Comment by DM87** [comment]
In the meantime until Firebase solves the issue you can force the port. Example: 
**sudo firebase serve --only functions --port=9000**

**Comment by onlyafly** [comment]
> In the meantime until Firebase solves the issue you can force the port. Example:
> **sudo firebase serve --only functions --port=9000**

At least for me, this does not fix the problem

**Comment by anantanandgupta** [comment]
Same Issue ... our development is on halt because of this issue. We have an angular application hosted with the firebase functions serving the content. I guess this is something to do with the firebase services but their status dashboard is showing all green. It was all working fine till yesterday.

**Comment by rodrigodutraoliveira** [comment]
It's working now, but with warnings...

```
⚠  database: WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.netty.util.internal.ReflectionUtil (file:/Users/rodrigodutra/.cache/firebase/emulators/firebase-database-emulator-v3.5.0.jar) to field sun.nio.ch.SelectorImpl.selectedKeys
WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
⚠  database:
...
```

**Comment by rodrigodutraoliveira** [comment]
> I'm no longer getting the illegal argument 400 error but another one in its place now and still not running:
> 
> ```
> 2018-11-15T20:01:14.098Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 15 Nov 2018 20:01:22 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="44,43,39,35", accept-ranges=none, connection=close
> [2018-11-15T20:01:14.098Z] Starting @google-cloud/functions-emulator
> [2018-11-15T20:01:14.115Z] Parsing function triggers
> Warning: You're using Node.js v10.13.0 but Google Cloud Functions only supports v6.11.5.
> [2018-11-15T20:01:14.238Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 15 Nov 2018 20:01:22 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="44,43,39,35", accept-ranges=none, connection=close
> i  hosting: Serving hosting files from: public
> ✔  hosting: Local server: http://localhost:5000
> ⚠  database: WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by io.netty.util.internal.ReflectionUtil (file:/home/qkay/.cache/firebase/emulators/firebase-database-emulator-v3.5.0.jar) to field sun.nio.ch.SelectorImpl.selectedKeys
> WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.ReflectionUtil
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release
> ⚠  database: 
> 
> error: SUPERVISOR error Error: listen EADDRINUSE 127.0.0.1:5001
>     at Server.setupListenHandle [as _listen2] (net.js:1286:14)
>     at listenInCluster (net.js:1334:12)
>     at GetAddrInfoReqWrap.doListen [as callback] (net.js:1460:7)
>     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:62:10)
> error: supervisorPort (5001) is already in use
> error: restPort (5002) is already in use
> 12:01:15.254 [NamespaceSystem-akka.actor.default-dispatcher-3] INFO akka.event.slf4j.Slf4jLogger - Slf4jLogger started
> 
> 12:01:15.408 [main] INFO com.firebase.server.forge.App$ - Listening on port 9000
> 
> 12:01:15.438 [main] ERROR com.firebase.server.forge.App$ - Error initializing Netty Listener
> java.net.BindException: Address already in use
> 	at java.base/sun.nio.ch.Net.bind0(Native Method)
> 	at java.base/sun.nio.ch.Net.bind(Net.java:461)
> 	at java.base/sun.nio.ch.Net.bind(Net.java:453)
> 	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227)
> 	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:128)
> 	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:500)
> 	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1226)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:495)
> 	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:480)
> 	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:973)
> 	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:209)
> 	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:355)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:399)
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:464)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
> 	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
> 	at java.base/java.lang.Thread.run(Thread.java:834)
> 
> 12:01:15.440 [Thread-1] INFO com.firebase.server.forge.App$ - Attempting graceful shutdown.
> 
> 12:01:15.444 [NamespaceSystem-akka.actor.default-dispatcher-4] INFO akka.actor.CoordinatedShutdown - Starting coordinated shutdown from JVM shutdown hook
> 
> 12:01:15.448 [Thread-1] INFO com.firebase.server.forge.App$ - Graceful shutdown complete.
> 
> 
> Error: database: emulator has exited with code: 1
> ```

Reboot your Mac...

**Comment by ryanpbrewster** [comment]
Try `firebase serve --only hosting` or `firebase serve --only functions` to get around this issue. Looking into a fix for that now.

**Comment by marcamos** [comment]
I had the problem as well; just now rebooted my computer and it works again.

**Comment by Neilpoulin** [comment]
> @Neilpoulin you can't deploy? What version of the CLI are you using and what error are you getting?

@mbleigh  Wanted to give you more details now that I'm back on my comptuer:

Specifically, I'm running `firebase-tools` in node. The command that fails is this:

When I first encountered this error, `firbase-tools` was at version `6.0.1`. I then upgraded it to `6.1.0` but the error was the same. 


```
const fbcli = require("firebase-tools");
const opts = {"project": "stage} //this is an active alias for my firebase setup
return fbcli.setup
    .web(opts)
    .then(firebaseConfig => { 
        // some config setup stuff for webpack
    }.catch(error => {
        //This gets called rigt away, see error object below
        console.error(error);
    })

```

where the caught error looks like:
```
{
  "name": "FirebaseError",
  "message": "HTTP Error: 400, Request contains an invalid argument.",
  "children": [],
  "status": 500,
  "exit": 1,
  "stack": "Error\n    at new FirebaseError (/Users/myrepo/node_modules/firebase-tools/src/error.js:11:16)\n    at module.exports (/Users/myrepo/node_modules/firebase-tools/src/responseToError.js:46:10)\n    at Request._callback (/Users/myrepo/node_modules/firebase-tools/src/api.js:50:25)\n    at Request.self.callback (/Users/myrepo/node_modules/request/request.js:185:22)\n    at emitTwo (events.js:126:13)\n    at Request.emit (events.js:214:7)\n    at Request.<anonymous> (/Users/myrepo/node_modules/request/request.js:1161:10)\n    at emitOne (events.js:116:13)\n    at Request.emit (events.js:211:7)\n    at IncomingMessage.<anonymous> (/Users/myrepo/node_modules/request/request.js:1083:12)",
  "context": {
    "body": {
      "error": {
        "code": 400,
        "message": "Request contains an invalid argument.",
        "status": "INVALID_ARGUMENT"
      }
    },
    "response": {
      "statusCode": 400,
      "body": {
        "error": {
          "code": 400,
          "message": "Request contains an invalid argument.",
          "status": "INVALID_ARGUMENT"
        }
      },
      "headers": {
        "vary": "X-Origin, Referer, Origin,Accept-Encoding",
        "content-type": "application/json; charset=UTF-8",
        "date": "Thu, 15 Nov 2018 18:33:41 GMT",
        "server": "ESF",
        "cache-control": "private",
        "x-xss-protection": "1; mode=block",
        "x-frame-options": "SAMEORIGIN",
        "x-content-type-options": "nosniff",
        "alt-svc": "quic=\":443\"; ma=2592000; v=\"44,43,39,35\"",
        "accept-ranges": "none",
        "connection": "close"
      },
      "request": {
        "uri": {
          "protocol": "https:",
          "slashes": true,
          "auth": null,
          "host": "mobilesdk-pa.googleapis.com",
          "port": 443,
          "hostname": "mobilesdk-pa.googleapis.com",
          "hash": null,
          "search": null,
          "query": null,
          "pathname": "/v1/projects/465836249868/clients/_:getWebAppConfig",
          "path": "/v1/projects/465836249868/clients/_:getWebAppConfig",
          "href": "https://mobilesdk-pa.googleapis.com/v1/projects/465836249868/clients/_:getWebAppConfig"
        },
        "method": "GET"
      }
    }
  }
}
```

**Comment by ryanpbrewster** [comment]
We've rolled back a backend build that was causing this issue. Can you try this now and see if it's still broken?

**Comment by alexplumb** [comment]
Worked for me

**Comment by kclay** [comment]
+1 working now. thanks

**Comment by Neilpoulin** [comment]
+1 confirmed working for me, too.

**Comment by zebralight** [comment]
even after rebooting, I still had running processes from previous deploy attempts. I just went into top and killed them manually and now firebase tools is working just fine for me.

**Comment by ricardoaaf** [comment]
+1 all set! Tks a lot.

**Comment by bkendall** [comment]
Thank you all for your patience. The invalid argument error has been resolved.

**Comment by nicoara** [comment]
having this problem right now, at 'firebase deploy'.

cloud functions logs show:
{"@type":"type.googleapis.com/google.cloud.audit.AuditLog","status":{"code":3,"message":"INVALID_ARGUMENT"},"authenticationInfo":...


what is the solution?
thanks

**Comment by bkendall** [comment]
@nicoara please open a new issue with the required information. Thank you.

**Comment by soclbz** [comment]
> trying to solve problem for 5 hours now, at 'firebase deploy'.
> 
> function is:
> 
> ```
> exports.makeUppercase = functions.database.ref('/userfollowers/{pushId}/followers')
>     .onWrite((change, context) => {
>       // Only edit data when it is first created.
>       if (change.before.exists()) {
>         return null;
>       }
>       // Exit when the data is deleted.
>       if (!change.after.exists()) {
>         return null;
>       }
>       // Grab the current value of what was written to the Realtime Database.
>       const original = change.after.val();
>       console.log('Uppercasing', context.params.pushId, original);
>       const uppercase = original.toUpperCase();
>       // You must return a Promise when performing asynchronous tasks inside a Functions such as
>       // writing to the Firebase Realtime Database.
>       // Setting an "uppercase" sibling in the Realtime Database returns a Promise.
>       return change.after.ref.parent.child('uppercase').set(uppercase);
>     });
> ```
> 
> which is straight out of documentation.
> 
> the terminal shows:
> 
> ```
> ⚠  functions: failed to create function makeUppercase
> HTTP Error: 400, The request has errors
> ```
> 
> cloud functions logs show:
> `{"@type":"type.googleapis.com/google.cloud.audit.AuditLog","status":{"code":3,"message":"INVALID_ARGUMENT"},"authenticationInfo":{"principalEmail":"nicoaratalpes@gmail.com"},"requestMetadata":{"callerIp":"86.120.235.246","callerSuppliedUserAgent":"FirebaseCLI/3.19.0,gzip(gfe),gzip(gfe)","requestAttributes":{"time":"2019-05-14T08:34:18.563Z","auth":{}},"destinationAttributes":{}},"serviceName":"cloudfunctions.googleapis.com","methodName":"google.cloud.functions.v1.CloudFunctionsService.CreateFunction","authorizationInfo":[{"resource":"projects/parkour-9136c/locations/us-central1/functions/makeUppercase","permission":"cloudfunctions.functions.create","granted":true,"resourceAttributes":{}},{"permission":"cloudfunctions.functions.create","granted":true,"resourceAttributes":{}}],"resourceName":"projects/parkour-9136c/locations/us-central1/functions/makeUppercase","request":{"location":"projects/parkour-9136c/locations/us-central1","@type":"type.googleapis.com/google.cloud.functions.v1.CreateFunctionRequest","function":{"labels":{"deployment-tool":"cli-firebase"},"entryPoint":"makeUppercase","eventTrigger":{"eventType":"providers/google.firebase.database/eventTypes/ref.write","resource":"projects/_/instances/parkour-9136c/refs/userfollowers/{pushId}/followers","service":"firebaseio.com"},"sourceUploadUrl":"https://storage.googleapis.com/gcf-upload-us-central1-f5adb7fe-7321-4f3c-8fe0-2b2307d26138/5b099ea8-161b-44a7-a3bd-18ce75c64859.zip?GoogleAccessId=service-807137615499@gcf-admin-robot.iam.gserviceaccount.com&Expires=1557824657&Signature=PJKzJsZtHWO1kIkmrSojpdgvb0jRzV91eNC9rZc4j%2FMcoHjILGm36FKCt6qQ2fxeAUu1%2FbrxpagdI7fHmUUUrDdTmnTNISr7FiN61sifUI%2B%2FGnUwo8SguzvrA7kADFqu8nD05FAo7BvG7biUrHmLgISlwo5dTKqcTSmExnaICA1tHYxjz%2Fk0RbmdGkcQ5HdeCKBnW0R7wQPsxswQyvR4cAU4WD2m3PPM9lncVr7pB%2Fh77FboGLi3sq%2FGHyEwUtjfUmyN9d%2FYUpKs48TMsGPknAGIvaFFUWQR23YCDUcrPipq1nW2W1JUdf5nGylYmVEeyF3jLrm%2BsOIcXiZ6LCRhpg%3D%3D","name":"projects/parkour-9136c/locations/us-central1/functions/makeUppercase"}}}`
> 
> what is the solution?
> thanks



> trying to solve problem for 5 hours now, at 'firebase deploy'.
> 
> function is:
> 
> ```
> exports.makeUppercase = functions.database.ref('/userfollowers/{pushId}/followers')
>     .onWrite((change, context) => {
>       // Only edit data when it is first created.
>       if (change.before.exists()) {
>         return null;
>       }
>       // Exit when the data is deleted.
>       if (!change.after.exists()) {
>         return null;
>       }
>       // Grab the current value of what was written to the Realtime Database.
>       const original = change.after.val();
>       console.log('Uppercasing', context.params.pushId, original);
>       const uppercase = original.toUpperCase();
>       // You must return a Promise when performing asynchronous tasks inside a Functions such as
>       // writing to the Firebase Realtime Database.
>       // Setting an "uppercase" sibling in the Realtime Database returns a Promise.
>       return change.after.ref.parent.child('uppercase').set(uppercase);
>     });
> ```
> 
> which is straight out of documentation.
> 
> the terminal shows:
> 
> ```
> ⚠  functions: failed to create function makeUppercase
> HTTP Error: 400, The request has errors
> ```
> 
> cloud functions logs show:
> `{"@type":"type.googleapis.com/google.cloud.audit.AuditLog","status":{"code":3,"message":"INVALID_ARGUMENT"},"authenticationInfo":{"principalEmail":"nicoaratalpes@gmail.com"},"requestMetadata":{"callerIp":"86.120.235.246","callerSuppliedUserAgent":"FirebaseCLI/3.19.0,gzip(gfe),gzip(gfe)","requestAttributes":{"time":"2019-05-14T08:34:18.563Z","auth":{}},"destinationAttributes":{}},"serviceName":"cloudfunctions.googleapis.com","methodName":"google.cloud.functions.v1.CloudFunctionsService.CreateFunction","authorizationInfo":[{"resource":"projects/parkour-9136c/locations/us-central1/functions/makeUppercase","permission":"cloudfunctions.functions.create","granted":true,"resourceAttributes":{}},{"permission":"cloudfunctions.functions.create","granted":true,"resourceAttributes":{}}],"resourceName":"projects/parkour-9136c/locations/us-central1/functions/makeUppercase","request":{"location":"projects/parkour-9136c/locations/us-central1","@type":"type.googleapis.com/google.cloud.functions.v1.CreateFunctionRequest","function":{"labels":{"deployment-tool":"cli-firebase"},"entryPoint":"makeUppercase","eventTrigger":{"eventType":"providers/google.firebase.database/eventTypes/ref.write","resource":"projects/_/instances/parkour-9136c/refs/userfollowers/{pushId}/followers","service":"firebaseio.com"},"sourceUploadUrl":"https://storage.googleapis.com/gcf-upload-us-central1-f5adb7fe-7321-4f3c-8fe0-2b2307d26138/5b099ea8-161b-44a7-a3bd-18ce75c64859.zip?GoogleAccessId=service-807137615499@gcf-admin-robot.iam.gserviceaccount.com&Expires=1557824657&Signature=PJKzJsZtHWO1kIkmrSojpdgvb0jRzV91eNC9rZc4j%2FMcoHjILGm36FKCt6qQ2fxeAUu1%2FbrxpagdI7fHmUUUrDdTmnTNISr7FiN61sifUI%2B%2FGnUwo8SguzvrA7kADFqu8nD05FAo7BvG7biUrHmLgISlwo5dTKqcTSmExnaICA1tHYxjz%2Fk0RbmdGkcQ5HdeCKBnW0R7wQPsxswQyvR4cAU4WD2m3PPM9lncVr7pB%2Fh77FboGLi3sq%2FGHyEwUtjfUmyN9d%2FYUpKs48TMsGPknAGIvaFFUWQR23YCDUcrPipq1nW2W1JUdf5nGylYmVEeyF3jLrm%2BsOIcXiZ6LCRhpg%3D%3D","name":"projects/parkour-9136c/locations/us-central1/functions/makeUppercase"}}}`
> 
> what is the solution?
> thanks

try adding document at the end of db ref path.  e.g /userfollowers/{pushId}/followers/{follower}

**Comment by nicoara** [comment]
@bkendall I started a new thread: https://github.com/firebase/firebase-tools/issues/1317 

I ran 'firebase deploy --debug' and found a new message.

@soclbz the change does not make a difference.

Thank you

**Comment by stpch** [comment]
Getting the same _"Runtime field cannot be empty"_ error:

> [2019-06-06T18:51:31.127Z] <<< HTTP RESPONSE 400 vary=X-Origin, Referer, Origin,Accept-Encoding, content-type=application/json; charset=UTF-8, date=Thu, 06 Jun 2019 18:51:30 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-
options=nosniff, alt-svc=quic=":443"; ma=2592000; v="46,44,43,39", accept-ranges=none, connection=close
> [2019-06-06T18:51:31.128Z] <<< HTTP RESPONSE BODY code=400, message=The request has errors, status=INVALID_ARGUMENT, details=[@type=type.googleapis.com/google.rpc.BadRequest, fieldViolations=[field=runtime, description=Runtime field cannot be empty.]]

This also happens for newly created projects using `npx firebase init` when trying to deploy the hello world example function.

**Comment by mbleigh** [comment]
@stpch are you on an old version of the CLI? Please look at #1317

**Comment by stpch** [comment]
> @stpch are you on an old version of the CLI? Please look at #1317

I'm using the latest versions:
- `firebase-tools@6.11.0`
- `firebase-functions@2.3.1`
- `firebase-admin@8.0.0`

**Comment by stpch** [comment]
My bad, there was an old `firebase-tools` version installed through `yarn` that took precedence over `npx`. It's working now with the latest version.
