### ISSUE TITLE
Retrieve application secret of new created firebase

### ISSUE THREAD

**Issue by dominik0711** [firebase/firebase-tools#102]
Is it possible to retrieve the **application secret** after creating a new firebase via `firebase init` as a return value? We need to store the application secret in another database without a manual copy step from the Web page.
Or is it possible to set or get the **application secret** programmatically?

Thanks

**Comment by drtriumph** [comment]
It's not currently possible to retrieve the secret through `firebase-tools`. Currently the only officially supported way to get the secret is through the website, as you mentioned. I'll track this as a vote for the feature internally
