### ISSUE TITLE
firebase deploy show wrong percentage number (version 6.1.0)

### ISSUE THREAD

**Issue by rainstormza** [firebase/firebase-tools#1020]
### Version info

6.1.0

### Platform Information

 OS X

### Steps to reproduce

firebase deploy

### Expected behavior

Uploading a new file should show the correct percentage number.
It works fine in version 6.0.1

### Actual behavior

![image](https://user-images.githubusercontent.com/4003032/48668471-ec418d80-eb20-11e8-8d71-b265b05d10c3.png)

**Comment by wongcode** [comment]
Experiencing the same issue.

**Comment by dtomasbar** [comment]
Same heare. And have and unexpected error that prevents the deploy

![image](https://user-images.githubusercontent.com/34484450/48680072-c0152380-eb97-11e8-8d0a-409223474a8f.png)

**Comment by bkendall** [comment]
Neat! I can reproduce the `NaN%` issue locally. I'll take a look and see what I can do.

@dtomasbar if you're having an unexpected error, please create a new issue and include the relevant parts of `firebase-debug.log`

**Comment by glenndevenish** [comment]
I'm still getting this error...

Firebase version: 6.1.0
Node version: v8.11.2
Platform: Windows 10

**Comment by glenndevenish** [comment]
@bkendall Thanks a lot, should have noticed!
