### ISSUE TITLE
Export firestore indexes in alphabetical order

### ISSUE THREAD

**Issue by compojoom** [firebase/firebase-tools#1023]
@samtstern asked me to post this here, so here I am following orders :)

We have a production and dev. project. We keep our rules in git repository. I was hoping to be able to sync the rules by doing
firebase firestore:indexex > firestore.indexes.json

then compare the changes, approve and deploy. 

However when I export the rules they seem to be ordered by I don't know what. Maybe the creation time of each rule. So I end up with a json file that is impossible to compare. 

Is it possible to sort the rules alphabetically based on the collection name and then on the fieldPath - I'm not sure if the ordering in the field path is important, but if it is, then sorting only on collection name should do it.

**Comment by samtstern** [comment]
I'll probably add this as part of #1014 (once we get that API locked down)

**Comment by samtstern** [comment]
Changed the title of this issue to reflect that it's talking about **indexes** not **rules**

**Comment by samtstern** [comment]
I did not do this in #1014 but it should be much easier now, since it's just creating a sorting algorithm for the index spec objet.

**Comment by samtstern** [comment]
Specifically we want to be able to sort the `Index` object here:
https://github.com/firebase/firebase-tools/blob/master/src/firestore/indexes-spec.ts#L6
