### ISSUE TITLE
firebase serve unable to No Java runtime present, requesting install

### ISSUE THREAD

**Issue by Rootjang92** [firebase/firebase-tools#1027]
### Version info
firebase-tools 6.1.0
npm 6.4.1
node v10.4.1

### Platform Information

Mac Os Mojave 10.14

### Steps to reproduce

I want to firebase serve in my-project (firebase tutorial) but not working firebase serve.
**I Installed Java oracle latest version,** but same error message and firebase serve not working

### Expected behavior

I want to test firebase serve,  browser will same work localhost but firebase serve not working

### Actual behavior

=== Serving from '/Users/mac/Documents/dev/TIL/memoWeb'...

✔  database: started on http://localhost:9000
⚠  database: No Java runtime present, requesting install.

Error: database: emulator has exited with code: 1

--------

I'm front-end developer, I want hosting my project for firebase. Somebody Help me. plz TT

**Comment by ryanpbrewster** [comment]
Try `firebase serve --only hosting`

**Comment by ryanpbrewster** [comment]
I'm going to close this issue as it has a relatively simple workaround. Feel free to re-open if you run into any more problems.

**Comment by anandvip** [comment]
No Java runtime present, requesting install.
after `Which Firebase emulators do you want to set up? Press Space to select emulators, then Enter to confirm your choices.` 
`Functions, Firestore, Database, Hosting, Pubsub` 
`?Which port do you want to use for the functions emulator? 5001`
`? Which port do you want to use for the firestore emulator? 8080`
`? Which port do you want to use for the database emulator? 9000`
`? Which port do you want to use for the hosting emulator? 5000`
`? Which port do you want to use for the pubsub emulator? 8085`
`? Would you like to enable the Emulator UI? Yes`
`? Which port do you want to use for the Emulator UI (leave empty to use any available port)?` 
`? Would you like to download the emulators now? Yes`
