### ISSUE TITLE
Support SemVer Node versions in package.json engines field

### ISSUE THREAD

**Issue by jthegedus** [firebase/firebase-tools#1038]
### Version info

firebase-tools v6.1.1

### Platform Information

Ubuntu 18.10

### Steps to reproduce

Use a SemVer range in your `package.json` file.

### Expected behavior

```json
// package.json
{
  ...
  "engines": {
    "node": ">=6.14.0"
  }
}
```

I expect to be able to use SemVer ranges in my `package.json` `engines` field.

More details:

`firebase-tools` expects `"node" : "6"`
`@grpc/grpc-js` expected `"node" : ">=8.4"`

I expect to be able to use Node `8.13.0` on my machine, compile to Node `6.14.0` and deploy to Cloud Functions with Node `6.14.0` runtime. My compilation tool uses the `engines` field to set the compilation target.

Using Node `8.13.0` with a `package.json` `engines` range of `>=6.14.0` achieves this, but I cannot use ranges in my engines field as `firebase-tools` fails on deployment.

### Actual behavior

The `firebase deploy` commands fails with the error:

```shell
Error: package.json in functions directory has an
  engines field which is unsupported. The only valid
  choices are: {"node": "8"} and {"node": "6"}.
```

![firebase-tools-error](https://user-images.githubusercontent.com/20798510/49059254-13ecd000-f25c-11e8-8fd6-7601f83862e0.png)

### Proposed Solution

Instead of [doing a direct comparison with single char strings](https://github.com/firebase/firebase-tools/blob/78f11b62ab658a5a59b291daad7ea5ee08b2bc34/src/prepareFunctionsUpload.js#L120), I propose the use of calculating a minimum semver range with a floor for the current Cloud Function runtimes.

This would remove the conflicting, non-standard use of this field, and potentially solve some issues related to deps and their miniumum engines as seen here https://github.com/firebase/firebase-tools/issues/1018

Here is an example of this method in use for anyone who may want to tackle this: https://github.com/parcel-bundler/parcel/blob/master/packages/core/parcel-bundler/src/utils/getTargetEngines.js

**Comment by bkendall** [comment]
Thanks for the feedback. To clarify one thing: which `package.json` are you referring to? The one in the root of your `functions` directory? or one at a higher level?

**Comment by jthegedus** [comment]
This is in a folder with a flat structure:

```
+- dist/
|  |
|  +- index.js
|  +- index.js.map
+- src/
|  |
|  +- index.ts
+- tsconfig.json
+- .firebaserc
+- firebase.json
+- package.json
```

where firebase.json deploy the current folder:

```json
{
  "functions": {
    "source": "."
  }
}
```

I realise I can do what I want with a different folder structure.

This is just a suggestion how `firebase-tools` could be more intelligent at determining what runtime to target, be more flexible to allow users choices and function more in line with how people expect the `engines` field to function.

**Comment by jthegedus** [comment]
Thanks for responding to this. If the implementation is ever reevaluated here are some requests to keep in mind:

1. Firebase only sees my compiled code, so it shouldn't restrict the Node version I used to dev with. As long as I compile to Firebase compat code it should not care.
2. Yarn adheres to the `engines` fields which will throw the aforementioned `"node" is incompat...` error if the local version of Node is not the same as engines.
3. Enforcing devs to use specific Node versions gets in the way of any compile to JS tooling

P.S.
Are you able to share why a unique key in the `engines` obj or adding this value to `firebase.json` `functions` field is not ideal?
