### ISSUE TITLE
How to store result of data:get inside javascript variable

### ISSUE THREAD

**Issue by dominik0711** [firebase/firebase-tools#104]
Using `firebase-tools data:get` the result is being printed out to the console or to a given file. I would like to use this command as a module inside javascript and to store the result in a variable. Is this possible? If yes, how?

Thanks in advance

**Comment by katowulf** [comment]
Dominik, any reason not to just use rest api or sdk? Both are available ( and simpler) in js. 

To directly answer your question, try the [exec() command](http://stackoverflow.com/questions/20643470/execute-a-command-line-binary-with-node-js). If that's not working, share a minimal repro and I'll reopen.

**Comment by zarko-tg** [comment]
The answer is missing the point. firebase-tools specifies that it can also be used as a library in a Node.js project. I believe the description of this problem is that firebase.data.get(...) is not able to return a string programatically if you don't use the **output** parameter to write to file.
What happens is that it just outputs in the console.

```
firebase_cli.data.get( path, {
  token    : secret,
  firebase : app,
  output   : filename
})
```
writes to file as expected.

```
firebase_cli.data.get( path, {
  token    : secret,
  firebase : app
})
```
prints to console instead of returning the result when the promise resolves.

**Comment by drtriumph** [comment]
What's your use-case where you're trying to get data from a Firebase database but can't or don't want to use the [SDK](https://www.npmjs.com/package/firebase)? The CLI really is just a wrapper around the SDK for this call, with some round-the-houses auth. The SDK is a much easier and more efficient way to get data from the database, I really would recommend starting there

**Comment by zarko-tg** [comment]
Just building a command line tool in Node.js, say an internal projects which is supposed to be used by a number of people and I want to avoid the global dependency and setup of firebase-tools.

If firebase-tools is meant to be used as a globally installed package, has some issues when used as a module and the 'firebase' package as a module is the way to go then you might want to revisit what your strategy is with 'firebase-tools' and clear up any related instructions and docs.

https://github.com/firebase/firebase-tools#using-as-a-module led me to believe that using this as a module is ok. As things are now I'm starting to backtrack back to the 'firebase' package.

Cheers
