### ISSUE TITLE
Bug Add Project 

### ISSUE THREAD

**Issue by cristianizzo** [firebase/firebase-tools#1043]
Hi guys, I am not able to create a new project, please check the screenshot.
<img width="1456" alt="screenshot 2018-11-28 at 12 32 54" src="https://user-images.githubusercontent.com/5518760/49149225-d777ad80-f309-11e8-900c-f04884772f22.png">

**Comment by thechenky** [comment]
Hi @cristianizzo can you try again and let us know if you're still seeing this issue?

**Comment by cristianizzo** [comment]
i use another account and works
