### ISSUE TITLE
Specify multiple groups when deploying functions

### ISSUE THREAD

**Issue by villeodell** [firebase/firebase-tools#1054]
Right now you can [deploy specific functions](https://firebase.google.com/docs/cli/#deploy_specific_functions) via groups like this:
`deploy --only functions:groupA` (works)

It would seem natural to be able to specify multiple groups, e.g.:
`deploy --only functions:groupA groupC` (doesn't work)
 
As a feature request, support for specifying multiple groups when deploying functions would be much appreciated and a big help.

**Comment by rilian** [comment]
probably you should use `deploy --only functions:groupA,groupC`

**Comment by bkendall** [comment]
@rilian is correct.

From the `firebase help deploy` command:

>  ``` --only <targets>         only deploy to specified, comma-separated targets (e.g. "hosting,storage"). For functions, can specify filters with colons to scope function deploys to only those functions (e.g. "--only functions:func1,functions:func2"). When filtering based on export groups (the exported module object keys), use dots to specify group names (e.g. "--only functions:group1.subgroup1,functions:group2)"```

**Comment by villeodell** [comment]
Ah, great! In fact I tried comma separated, but missed the fact that ‘functions:’ must be repeated with each group. 

Very happy to discover this. Thanks for the reference — next time I’ll be sure to check the help command!

**Comment by villeodell** [comment]
Might be helpful it could be added to the documentation/example here as well: https://firebase.google.com/docs/cli/#deploy_specific_functions

**Comment by bkendall** [comment]
It is.

![image](https://user-images.githubusercontent.com/160236/49532293-0a252700-f871-11e8-8d79-fbc8c1fd365b.png)
