### ISSUE TITLE
Path must be a string error from firebase - firebase-tools

### ISSUE THREAD

**Issue by fabienthiombiano** [firebase/firebase-tools#1056]
version info 
`firebase --version
6.1.1`

index.js file in functions folder

    const functions = require('firebase-functions');
    const os = require('os');
    const path = require('path');
    const { Storage } = require('@google-cloud/storage');

    const gcs = new Storage ({

    });
    exports.onImageUpload = functions.storage.object().onFinalize(event => {
    console.log(event);

    const fileBucket = event.bucket;
    const contentType = event.ContentType;
    const filePath = event.filePath;
    console.log('file changes detected!');

    const destBucket = gcs.bucket(fileBucket);
    const tmpFilePath = path.join(os.tmpdir(), path.basename(filePath)); 
    filename
    const metaData = {
        contentType: contentType
    };

    return destBucket.file(filePath).download({
        destination : tmpFilePath, 
    }).then(() => {
        console.log("Image downloaded to the local destination");
        destBucket.file(filePath).upload({
            destination: "renamed-" + path.basename(filePath), 
            metaData: metaData
        });
    });
    });

error code firebase 

      `TypeError: Path must be a string. Received undefined
        at assertPath (path.js:7:11)
        at Object.basename (path.js:1361:5)
        at exports.onImageUpload.functions.storage.bucket.object.onFinalize.event           (/user_code/index.js:30:53)
        at cloudFunctionNewSignature (/user_code/node_modules/firebase-functions/lib/cloud-functions.js:105:23)
        at cloudFunction (/user_code/node_modules/firebase-functions/lib/cloud-functions.js:135:20)
        at /var/tmp/worker/worker.js:768:24
       at process._tickDomainCallback (internal/process/next_tick.js:135:7)`

_Originally posted by @fabienthiombiano in https://github.com/firebase/firebase-tools/issue_comments#issuecomment-444669275_

**Comment by bkendall** [comment]
This error looks like it's coming from `firebase-functions`, not `firebase-tools`. Please make an issue in that repository: https://github.com/firebase/firebase-functions
