### ISSUE TITLE
How to use firebase-tools as module to create a new database programmatically

### ISSUE THREAD

**Issue by dominik0711** [firebase/firebase-tools#106]
Is it possible to use `firebase-tools init` as a module to create a new database in nodejs (pure JavaScript) programmatically? I have to do multiple steps/updates/inserts into multiple firebases.
See [SO](http://stackoverflow.com/questions/33983534/how-to-create-new-firebase-db-programmatically-through-api)

**Comment by katowulf** [comment]
There is no programmatic way to create an app. There is also a limit on the
number of free apps you can create.

**Comment by dominik0711** [comment]
Hi @katowulf . First of all thanks for the quick answer. With `firebase init` it is for sure possible to create a new database and these firebase utils are written in JavaScript. So why shouldn't this be possible? What is the limit for free apps/databases?  

Thanks!

**Comment by puf** [comment]
The limit is 10 free apps per account. Can we keep the discussion in one
place. Either here or on StackOverflow is fine, but not on both please.

**Comment by dominik0711** [comment]
Sure. I wanted to get as many answers as possible. Sorry!
