### ISSUE TITLE
TypeError: Cannot read property 'map' of undefined when deploying indexes

### ISSUE THREAD

**Issue by samtstern** [firebase/firebase-tools#1069]
This is a bug that occurs in version `6.2.1` of the Firebase CLI reported by @vsimon in #495

It comes from this code:
```ts
async listIndexes(project: string): Promise<API.Index[]> {
    const url = `projects/${project}/databases/(default)/collectionGroups/-/indexes`;

    const res = await api.request("GET", `/v1beta2/${url}`, {
      auth: true,
      origin: api.firestoreOrigin,
    });

    const indexes = res.body.indexes;
    return indexes.map(
```

It seems that if there are no indexes in the project, there will be no indexes in the response at all (not an empty array)

**Comment by samtstern** [comment]
Confirmed, the API response is empty (GAH):

![image](https://user-images.githubusercontent.com/8466666/50367551-e848c700-0535-11e9-9f51-97c7a8264c99.png)

**Comment by samtstern** [comment]
@vsimon note that you can "work around" this by creating ANY index in the Firebase console for Firestore.  Like an index of fields "foo" and "bar" in collection "baz".  It won't cost you any money since there's no real data being indexed.

**Comment by samtstern** [comment]
The fix for this was **merged** in #1070 but has not been released.  We already did one release today for my screwups so two is too many.

This issue only impacts people who try to deploy firestore indexes from the command line, but have no indexes in the console.

There are two workarounds:

- Go to the console and create **any** index.
- Remove the reference to firestore indexes from your `firebase.json` file

**Comment by samtstern** [comment]
cc @laurenzlong sorry about all the churn!  If anyone is in the office next week we can release then but the workarounds above should make sure nobody is forever-broken on this.

**Comment by vsimon** [comment]
Thanks @samtstern for merging a fix so quickly. FWIW I wouldn't mind multiple releases in one day :smile:

**Comment by samtstern** [comment]
Did the workaround work for you?

**Comment by vsimon** [comment]
I'm sure the workarounds will work. I would just like to avoid making console one-offs in a project environment where things have been scripted to be as identical as possible with other projects.

**Comment by vsimon** [comment]
Thanks @samtstern awesome! 6.2.2. "Just works"!

**Comment by samtstern** [comment]
Phew!  Merry Christmas to me haha I don't have to go on vacation with
broken code guilt!

**Comment by bkendall** [comment]
Since this has been merged, closing.
