### ISSUE TITLE
Earlier progress notification

### ISSUE THREAD

**Issue by scottmas** [firebase/firebase-tools#107]
So I recently upgraded to 2.0 and now I can't deploy my app! My node version is v0.12.7 and I have successfully authenticated into my account scottmortonashton@gmail.com on an account that has a spark plan.

Here's my firebase.json file
```
{
  "firebase": "easy-pledge",
  "public": ".",
  "ignore": [
    "firebase.json",
    "**/.*",
    "**/node_modules/**",
    "*.iml",
    "__excluded"
  ],
  "redirects":[{
    "source": "/",
    "destination": "/landing/",
    "type": 301
  }]
}
```

and here's the console output when I run firebase deploy --debug

```
----------------------------------------------------------------------
Command:      node /usr/local/bin/firebase deploy --debug
Platform:     darwin
Node Version: v0.12.7
Time:         Tue Dec 01 2015 17:45:35 GMT-0700 (MST)
----------------------------------------------------------------------

>>> HTTP REQUEST GET https://admin.firebase.com/firebase/easy-pledge/token?token=XXX 
<<< HTTP RESPONSE 200 server=nginx, date=Wed, 02 Dec 2015 00:45:35 GMT, content-type=application/json; charset=utf-8, content-length=471, connection=close, access-control-allow-origin=*, access-control-allow-methods=GET, PUT, POST, DELETE, OPTIONS, x-content-type-options=nosniff, strict-transport-security=max-age=31536000; includeSubdomains, cache-control=no-cache, no-store
>>> HTTP REQUEST GET https://admin.firebase.com/firebase/easy-pledge/token?token=XXX 
<<< HTTP RESPONSE 200 server=nginx, date=Wed, 02 Dec 2015 00:45:35 GMT, content-type=application/json; charset=utf-8, content-length=471, connection=close, access-control-allow-origin=*, access-control-allow-methods=GET, PUT, POST, DELETE, OPTIONS, x-content-type-options=nosniff, strict-transport-security=max-age=31536000; includeSubdomains, cache-control=no-cache, no-store

=== Deploying to 'easy-pledge'...

i  deploying hosting
i  preparing . directory for upload...
>>> HTTP REQUEST PUT https://deploy.firebase.com/firebase/easy-pledge/uploads/-K4V8hKHCSWh44IVAIt9?token=XXX&fileCount=168&message= 
```
Once it gets to this point it just hangs, forcing me to cmd + c to escape.

Help! What's going wrong?

**Comment by scottmas** [comment]
Okay, so it turns out the internet I was using at the time had an excellent download speed (making me think all was well), but a horrible upload speed (causing the upload to take forever). The basic problem is that the CLI needs some sort of progress notification. What about a progress percentage on the command line notifying the user what percent of their files have been uploaded?

**Comment by drtriumph** [comment]
We output information at the start of the preparation step, and then progress of files upload down to 1% granularity. On larger deploys, I believe there's also a warning about file size & number of files being deployed at the end of the preparation step right as the sending phase begins, but 'large' is a relative term and we have to make some assumptions about the developer's environment.

If it simply takes a long time to upload 1% of files then there's not a whole lot we can do to notify the user of this because of the way uploads currently work, and that's not likely to change in the near- to medium-term.
