### ISSUE TITLE
firestore:indexed Error: An unexpected error has occurred.

### ISSUE THREAD

**Issue by Thaina** [firebase/firebase-tools#1075]
I think the new exemption field index cause a problem with tools exporting command

The problem arise when there was an exemption that was disable every indexing

like this

![image](https://user-images.githubusercontent.com/1042507/50413272-9dce8f80-0840-11e9-82ea-c64b2995b48d.png)

Will cause error like this

![image](https://user-images.githubusercontent.com/1042507/50413299-c9517a00-0840-11e9-886c-c3ce24f7bb26.png)

**Comment by bkendall** [comment]
What is the version of your `firebase` installation? `firebase --version`

**Comment by samtstern** [comment]
Confirmed this bug and identified a fix.
