### ISSUE TITLE
Bad validation for firebase.config() keys

### ISSUE THREAD

**Issue by kyasbal** [firebase/firebase-tools#1078]
https://github.com/firebase/firebase-tools/blob/78f11b62ab658a5a59b291daad7ea5ee08b2bc34/src/functionsConfig.js#L139

This validation is wrong.  Firebase functions won't accept `_` also. And I guess this validation will accept many unintended strings like Chinese alphabets or something other unicode.

**Comment by rilian** [comment]
also word `firebase` in the beginning of key is not allowed

**Comment by thechenky** [comment]
@rilian you're right, configs starting with `firebase` are not allowed as user supplied keys. @kyasbal-1994 thanks for bringing this to our attention. We likely will not get to this for a while as it's a minor issue. Having said that, PRs are very welcome!

**Comment by kyasbal-1994** [comment]
@thechenky I can make PR for this. This seems good issue to start contribution. But, I want to know what kind of string are accepted or not.

**Comment by thechenky** [comment]
Hi @kyasbal-1994 thanks for the offer! Runtime config allows strings that match \[0-9A-Za-z](?:[_.A-Za-z0-9-]{0,62}[_.A-Za-z0-9])? regex (see [documentation](https://cloud.google.com/deployment-manager/runtime-configurator/reference/rest/v1beta1/projects.configs#RuntimeConfig)). Any other restrictions that are put on the config name would be inside this repo (things like configs starting with `firebase` are not allowed, etc).

**Comment by kyasbal-1994** [comment]
@thechenky Thank you for the information. I will solve this issue when I am free.
(Maybe a month later)
