### ISSUE TITLE
Document the --firebase option

### ISSUE THREAD

**Issue by michaek** [firebase/firebase-tools#108]
The `-f` / `--firebase` option is mentioned in some articles about firebase-tools, but it's not in the documentation or output in the `--help` from the CLI. Should it be?

**Comment by drtriumph** [comment]
The `-f` (or `--firebase`) flag is not a global option, but instead specified on the sub-commands that support it. For example, it doesn't really make sense to run `firebase login -f myapp`, but it does make sense to run `firebase deploy -f myapp`.

As such, it isn't listed when you just run `firebase --help`, but if you run `firebase deploy --help` it will show you specific help for `deploy`, including the `-f` command.

**Comment by michaek** [comment]
Thanks for clarifying!
