### ISSUE TITLE
Need to call several times: firebase deploy --only firestore:indexes  to get all indexes created

### ISSUE THREAD

**Issue by sperochon** [firebase/firebase-tools#1080]
### Version info
6.2.2

### Platform Information
OS X 10.14.2

### Steps to reproduce
delete all the firestore indexes manually through Firebase UI
then call:
firebase deploy --only firestore:indexes
with a file containing lot of indexes (mine's got 64 indexes)

### Expected behavior
create all the indexes (64) described inside my file firestore.indexes.json

### Actual behavior
It creates only the first 7 indexes. I need to call several times the same command:
"firebase deploy --only firestore:indexes"
to create some new indexes on each command
second time added 8 indexes...
(can't know how make it worked with the  "--debug flag")

If this is normal behaviour, maybe I missed the explanation inside the doc?

And happy new year ;-) !

**Comment by blaneyneil** [comment]
i can't get it to create indexes at all.  ever since upgrading to 6.2.2 - i've never had problem before that - i get the message: 

> firestore: your indexes indexes are specified in the v1beta1 API format. Please upgrade to the new index API format by running firebase firestore:indexes again and saving the result.

ok, so i do that.  i get the normal success message and then...nothing.  no errors, but zero indexes created.

**Comment by samtstern** [comment]
@sperochon would you mind attaching your `firestore.indexes.json` file so I can try to reproduce this?
@blaneyneil that message is just a warning about a change that may break you in the future, but it shouldn't break you now.  Would you mind opening a new issue with your details?

**Comment by sperochon** [comment]
I've change the extension since github doesn't accept .json files

[firestore.indexes.json.txt](https://github.com/firebase/firebase-tools/files/2721439/firestore.indexes.json.txt)

**Comment by blaneyneil** [comment]
@samtstern i created a new issue at #1081
