### ISSUE TITLE
firebase functions:log "--open" opens wrong URL (Invalid request: Field not found: 'serviceName'. )

### ISSUE THREAD

**Issue by anishkny** [firebase/firebase-tools#1100]
### Version info
6.2.2

### Platform Information
OS X

### Steps to reproduce
firebase functions:log "--open"

### Expected behavior
Should open URL with logs for functions.

### Actual behavior
Filter has value: `metadata.serviceName:"cloudfunctions.googleapis.com"`
No entries found, with yellow text in logs: `Invalid request: Field not found: 'serviceName'. `

**Comment by bkendall** [comment]
To be clear, you're seeing this `Invalid request` error message Google Cloud Console (_not_ in your terminal)?

**Comment by anishkny** [comment]
Yes. The error is observed in the browser tab thats opens up. The URL navigated to is:

https://console.cloud.google.com/logs/viewer?project=****&pli=1&minLogLevel=0&expandAll=false&timestamp=2019-01-11T00:15:25.779000000Z&customFacets=&limitCustomFacetWidth=true&dateRangeStart=2019-01-10T23:15:26.242Z&dateRangeEnd=2019-01-11T00:15:26.242Z&interval=PT1H&advancedFilter=metadata.serviceName:%22cloudfunctions.googleapis.com%22

Looks like its caused by presence of this URL param: **advancedFilter=metadata.serviceName:%22cloudfunctions.googleapis.com%22**

![firebase-functions-logs-open-bug](https://user-images.githubusercontent.com/357499/51005359-72b89100-150c-11e9-953a-c69eaafff542.png)

**Comment by bkendall** [comment]
Yup. I don't know quite enough to know what that filter _should_ be. I see your PR addressing this, thanks! I'll make sure someone sees it today 😄

**Comment by anishkny** [comment]
thanks @bkendall! I back-calculated the URL param `protoPayload.serviceName` from manually trying it out in the browser. Seems to work tho 😃
