### ISSUE TITLE
Documentation contradiction: This module can/cannot be used in a cloud function

### ISSUE THREAD

**Issue by buzzware** [firebase/firebase-tools#1102]
This page recommends using this module in a cloud function https://firebase.google.com/docs/firestore/solutions/delete-collections

while the readme says 

"The Firebase CLI can also be used programmatically as a standard Node module. This can only be done on your machine, and cannot be done within Cloud Functions."

**Comment by thechenky** [comment]
@buzzware please follow the issue template next time. But yes, you're right about the contradiction and we are in the process of revamping our github resources to be more in line with the general Firebase documentation. The documentation is correct, the README is not. PR for this quick fix is more than welcome :)

**Comment by samtstern** [comment]
Cleaning up some old issues, we've recently cleaned up this part of the docs:
https://github.com/firebase/firebase-tools#using-as-a-module
