### ISSUE TITLE
Deploying storage rules per project

### ISSUE THREAD

**Issue by alexlouden** [firebase/firebase-tools#1108]
### Version info
6.2.2

### Platform Information
OS X locally, linux on CI

### Steps to reproduce

I've got a staging and production environment, and each has two storage buckets - for project A and B (e.g. `prod-bucket-a`, `prod-bucket-b`, `staging-bucket-a`, `staging-bucket-b`). 

I've set up continuous deployment for cloud functions, firebase & rtdb rules, but I don't think there's currently a way to set up a set of rules for `bucket-a` or `bucket-b` so that on deploy to staging or prod the rules for each type of bucket are deployed.

I'm currently using targets:

```bash
firebase target:apply storage bucket-a prod-bucket-a
firebase target:apply storage bucket-a staging-bucket-a
```

And in my `firebase.json`:

```json
"storage": [
    {
      "target": "bucket-a",
      "rules": "bucket-a.rules"
    },
```

However this means when our CI deploys to staging:

```bash
firebase deploy --non-interactive --token=$FIREBASE_CI_TOKEN --project staging
...
✔  storage: released rules bucket-a.rules to firebase.storage/prod-bucket-a
✔  storage: released rules bucket-a.rules to firebase.storage/staging-bucket-a
```

Obviously this is not good - we don't want our staging branch touching production config! I expected that the `--project` flag would be respected, and the deploy would only affect staging project buckets.

I could set up `prod-bucket-a.rules` and `staging-bucket-a.rules` but that defeats the purpose of continuous deployment and kind of breaks our workflow.

Any ideas?

**Comment by mbleigh** [comment]
Hi, targets are stored per-project, so you should be using the `--project` flag while running `target:apply`. Take a look at your `.firebaserc` file. It should look something like this:

```js
{
  "projects": {
    "staging": "my-staging-project",
    "prod": "my-prod-project"
  },
  {
    "targets": {
      "my-staging-project": {"storage":{"bucket-a": ["staging-bucket-a"]}},
      "my-prod-project": {"storage":{"bucket-a": ["prod-bucket-a"]}},
    }
  }
}
```

The reason your deployments aren't changing the rules in both projects is that rules only apply to buckets in their own project. So when you deploy the rules for "prod-bucket-a" to your staging project, they just sit there unused.

Hopefully this gives you enough to work through your setup. Cheers!

**Comment by alexlouden** [comment]
Thanks @mbleigh! I had all my targets under my staging project. I've moved them as per your example, and now the output matches what I expect.
