### ISSUE TITLE
Firebase CLI deploy functions HTTP Error: 404 Not Found

### ISSUE THREAD

**Issue by srenbo** [firebase/firebase-tools#1109]
### Version info

6.2.2

### Platform Information

Windows, 

### Steps to reproduce

```
firebase deploy --only functions

=== Deploying to 'vagtplan-1e00d'...

i  deploying functions
Running command: npm --prefix "functions" run lint

> functions@ lint C:\Users\srenb\Documents\Arbejde\skemadoktor.dk\cfunctions\functions
> tslint --project tsconfig.json

Running command: npm --prefix "functions" run build

> functions@ build C:\Users\srenb\Documents\Arbejde\skemadoktor.dk\cfunctions\functions
> tsc

+  functions: Finished running predeploy script.
i  functions: ensuring necessary APIs are enabled...
+  functions: all necessary APIs are enabled
i  functions: preparing functions directory for uploading...
i  functions: packaged functions (48.09 KB) for uploading
!  functions: Upload Error: HTTP Error: 404, Not Found

Error: HTTP Error: 404, Not Found
```
Debug shows that it cannot find the required bucket: 
```
Error: HTTP Error: 404, Not Found
[2019-01-15T11:17:12.995Z] Error Context: {
  "body": {
    "error": {
      "message": "Not Found"
    }
  },
  "response": {
    "statusCode": 404,
    "body": "<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist.</Message></Error>",
```
### Expected behavior

It should upload no problem

### Actual behavior

Fails because it can't find the bucket returned from 
```
 HTTP REQUEST POST https://cloudfunctions.googleapis.com/v1/projects/vagtplan-1e00d/locations/us-central1/functions:generateUploadUrl
```

**Comment by mbleigh** [comment]
This error looks project-specific. Please reach out to [Firebase support](https://firebase.google.com/support) for help, as the issue likely lies with the backend servers and not the Firebase CLI.

Thanks!

**Comment by RobSteward** [comment]
@mbleigh Was this project-specific? I am running into the same issue. ? Opened a case (2-2819000025743) as recommended by you, but could be a mistake that I am making?

**Comment by oshalygin** [comment]
Having the same issue, its a CLI issue.

There's no way that the CLI should return `Error: HTTP Error: 404, Requested entity was not found.` on a `firebase deploy` command.

There's obviously some other error going on but its not being surfaced.

Anyone know where to even look on this?

**Comment by bkendall** [comment]
@oshalygin please open a new issue with the requested information (including parts of the `--debug` output or `firebase-debug.log` file)

**Comment by amouly** [comment]
I have the exact same error.

Any clue?

**Comment by amouly** [comment]
Well, apparently it's an issue with my internet connection.

I kept getting 404. But then I uploaded my IPA file to Drive and delivered to a friend in other country.

He uploaded the file really fast and successfully.

**Comment by eddiejaoude** [comment]
I have been deploying from TravisCI and have experienced a similar error `Error: HTTP Error: 404, Requested entity was not found.`...

```bash
> tslint --project tsconfig.json
1477
1478 no-unused-variable is deprecated. Since TypeScript 2.9. Please use the built-in compiler checks instead.
1479 Running command: npm --prefix "$RESOURCE_DIR" run build
1480
1481 > functions@ build /home/travis/build/DashboardHub/PipelineDashboard/functions
1482 > tsc
1483
1484 ✔  functions: Finished running predeploy script.
1485 i  firestore: checking firestore.rules for compilation errors...
1486 i  firestore: reading indexes from firestore.indexes.json...
1487 ✔  firestore: rules file firestore.rules compiled successfully
1488 i  functions: ensuring necessary APIs are enabled...
1489 ✔  functions: all necessary APIs are enabled
1490
1491 Error: HTTP Error: 404, Requested entity was not found.
```

**Comment by DevThoughts3** [comment]
I have also the same problem: Error: HTTP Error: 404, Requested entity was not found.

**Comment by daohoangson** [comment]
I ran into this error today. Went to https://console.firebase.google.com/ and created a Firebase project for my Google Cloud project and it started working.

**Comment by adteague** [comment]
I came across this same error and resolved it by making sure the site name in Firebase matched what I had in my `firebase.json` file.

<img width="985" alt="Screen Shot 2020-03-19 at 6 42 03 PM" src="https://user-images.githubusercontent.com/13558763/77124672-7ea5ba00-6a11-11ea-926f-7d3a89034f68.png">

![Screen Shot 2020-03-19 at 6 41 10 PM](https://user-images.githubusercontent.com/13558763/77124705-a09f3c80-6a11-11ea-8c5b-5fbcfa63c437.png)

**Comment by nicoqh** [comment]
Ideally, the site names shouldn't be added to `firebase.json`. If you use different Firebase projects for staging and production (as recommended by Firebase), having the site names hardcoded in `firebase.json` poses a problem when you switch between projects with `firebase use <projectName>`. Site names are unique across projects; no matter which project you `use`, deploys are made to the same site.

Instead, set up deploy targets in `.firebaserc`. Here's an example of an app that has two Firebase projects (dev and prod), with two sites:

.firebaserc:
```
{
  "projects": {
    "dev": "myapp-staging", // alias "dev" to the project "myapp-staging"
    "prod": "myapp-prod"  // alias "prod" to the project "myapp-prod"
  },
  "targets": {
    "myapp-staging": { // project ID
      "hosting": {
        "adminpanel": [ // user-defined identifier for the Hosting site, call it whatever you'd like
          "myapp-staging-adminpanel" // name of the Hosting site as listed in your Firebase project
        ],
        "catalog": [
          "myapp-staging-catalog"
        ]
      }
    }
  }
}
```

firebase.json:
```
{
  "hosting": [
    {
      "target": "adminpanel",
      "public": "adminpanel-app/dist",
    },
    {
      "target": "catalog",
      "public": "catalog-app/dist"
    }
  ]
}
```

This way you can switch between, and deploy to, different Firebase projects without having to change your `firebase.json`.

```
firebase use dev
firebase deploy --only hosting:adminpanel

firebase use prod
firebase deploy --only hosting:adminpanel
```

**Comment by manwithsteelnerves** [comment]
If you add a new target to firebaserc file, make sure you add the same site in the firebase hosting in firebase console too.

**Comment by ronkot** [comment]
For me updating the `firebase-tools` package from version 6.12 to the latest one (8.9) fixed this problem.

**Comment by SystemDZ** [comment]
Had same issue and finally solved it.

**

firebase login
firebase use --add (Choose the right Project ID)
firebase init (select hosting, than correct Project ID)
if needed (npm run build)
firebase deploy**
Solution was number 2 Choosing the right Project ID Because some how firebase commands was refering automatically to a wrong Project ID

Good Luck

**Comment by aroshasum** [comment]
It was `npm i -g firebase-tools` which resolved the issue for me. Hope this helps to someone.

**Comment by tiagoit** [comment]
On the bottom of "Firebase Console > Hosting Page" click on "Add another site" and create them with the same name you used for target.

**Comment by nathikazad** [comment]
So silly, install firebase tools again.

**Comment by NerdGr8** [comment]
The issue can also occur when you have an outdated version of Node.js

**Comment by maxwell-oroark** [comment]
I am still having this issue after trying everything above in the comments.

**Comment by nilsreichardt** [comment]
@maxwell-oroark Did you solve it? I have the exact same problem. I can deploy the same function to all our projects, except our production project.

**Comment by srenbo** [comment]
Nah I created a new project

søn. 26. sep. 2021 22.06 skrev Nils Reichardt ***@***.***>:

**Comment by samrezikram** [comment]
Firebase doesn't accept `groups` name with white spaces. e.g:- iOS

[![enter image description here][1]][1]


  [1]: https://i.stack.imgur.com/lCDyM.png

iOS SIT Tester always get failed on

> Error: failed to distribute to testers/groups: HTTP Error: 404,
> Requested entity was not found.


*wheres JinglePayTesters succeed without any problem.*


        # Deploy on Firebase 
      - task: Bash@3
        displayName: "Upload to firebase app distribution"
        inputs:
          targetType: "inline"
          script: |
              npm i -g firebase-tools
              ls -la $(Build.BinariesDirectory)/output/
              firebase appdistribution:distribute  *.ipa \
                --app "$(app_id)" \
                --token "$(firebasetoken)" \
                --groups "JinglePayTesters" \
                --release-notes "From Azure Devops" \
                --debug	\
          workingDirectory: '$(Build.BinariesDirectory)/output/'

**Comment by jayasanka-sack** [comment]
> Firebase doesn't accept `groups` name with white spaces. e.g:- iOS

This helped me! Thanks, @samrezikram! 😊

**Comment by goofballLogic** [comment]
For me, this was resolved by setting the "Default GCP resource location" under Project settings.

**Comment by HusakOleh** [comment]
`    "frameworksBackend": {
      "region": "us-central1",
      "minInstances": 0,
      "maxInstances": 5,
      "memory": "1GiB"
    }`
    
    I change region to us-central1, and it's working

**Comment by HusakOleh** [comment]
```javascript
    "frameworksBackend": {
      "region": "us-central1",
      "minInstances": 0,
      "maxInstances": 5,
      "memory": "1GiB"
    }
``` 

I change region to us-central1, and it's working
