### ISSUE TITLE
Unknow Option -f

### ISSUE THREAD

**Issue by ShagunParikh** [firebase/firebase-tools#1118]
I have integrated CI/CD to deploy functions in a non-interactive pipeline.

Now i do not want to manually delete the functions for every deploy.  So i am trying to run the below command:

`firebase deploy -f --token my_token --non-interactive`

But it is giving me below error:

**unknown option `-f'**

The firebase-tools version is 6.3.0

Any help would be appreciated! :)

**Comment by bkendall** [comment]
If I recall correctly, `-f` _is_ a relatively new flag so if your installation is out of date in any way, you'd see this error. I'd recommend doing `npm i -g firebase-tools@v6.3.0` to re-install the global version (assuming that's how you have it installed) at the latest version and verify the version before and after with `firebase --version`.

I just ran the commands you've provided successfully on `6.3.0`, so we'd need more information (maybe your `firebase-debug.log`) or run the command with `--debug` to make sure the correct version is being run (it's in the first block of printed information).

**Comment by ShagunParikh** [comment]
Re-installing firebase tools worked. Thanks!
