### ISSUE TITLE
Firebase deploy Upload HTTP Unknown Error 400 

### ISSUE THREAD

**Issue by ziyafenn** [firebase/firebase-tools#1123]
### [REQUIRED] Environment info

**firebase-tools: 6.3.0**

**Platform: macOS**

Hello everyone. I'm getting weird HTTP 400 Error while trying to deploy the functions to firebase.

For instance, deploying exactly the same functions to my other test project works completely fine!

I can't understand what's the problem is. I tried also to do `firebase init`. 

Weirdly enough, removing the function works just fine! Only problem is with `deploy`

Including logs.

Thanks!

### Log

```
[debug] [2019-01-24T20:53:52.701Z] ----------------------------------------------------------------------
[debug] [2019-01-24T20:53:52.704Z] Command:       /usr/local/bin/node /usr/local/bin/firebase deploy --only functions --debug
[debug] [2019-01-24T20:53:52.704Z] CLI Version:   6.3.0
[debug] [2019-01-24T20:53:52.704Z] Platform:      darwin
[debug] [2019-01-24T20:53:52.704Z] Node Version:  v8.12.0
[debug] [2019-01-24T20:53:52.705Z] Time:          Thu Jan 24 2019 21:53:52 GMT+0100 (CET)
[debug] [2019-01-24T20:53:52.705Z] ----------------------------------------------------------------------
[debug] 
[debug] [2019-01-24T20:53:52.714Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2019-01-24T20:53:52.715Z] > authorizing via signed-in user
[debug] [2019-01-24T20:53:52.715Z] [iam] checking project proclubs-c0955 for permissions ["cloudfunctions.functions.create","cloudfunctions.functions.delete","cloudfunctions.functions.get","cloudfunctions.functions.list","cloudfunctions.functions.update","cloudfunctions.operations.get","firebase.projects.get"]
[debug] [2019-01-24T20:53:52.717Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects/proclubs-c0955:testIamPermissions  

[debug] [2019-01-24T20:53:53.593Z] <<< HTTP RESPONSE 200
[info] 
[info] === Deploying to 'proclubs-c0955'...
[info] 
[info] i  deploying functions
[info] Running command: npm --prefix "$RESOURCE_DIR" run build
[info] ✔  functions: Finished running predeploy script.
[debug] [2019-01-24T20:53:58.072Z] > [functions] package.json contents: {
  "name": "functions",
  "scripts": {
    "lint": "tslint --project tsconfig.json",
    "build": "tsc",
    "serve": "npm run build && firebase serve --only functions",
    "shell": "npm run build && firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "main": "lib/index.js",
  "dependencies": {
    "@google-cloud/storage": "^2.3.1",
    "@sendgrid/mail": "^6.3.1",
    "@types/moment-timezone": "^0.5.8",
    "@types/uuid": "^3.4.3",
    "body-parser": "^1.18.3",
    "cron": "^1.4.1",
    "express": "^4.16.3",
    "express-basic-auth": "^1.1.5",
    "firebase-admin": "~5.13.0",
    "firebase-functions": "^2.0.0",
    "he": "^1.2.0",
    "moment": "^2.22.2",
    "moment-timezone": "^0.5.21",
    "node-fetch": "^2.3.0",
    "sendgrid": "^5.2.3",
    "uuid": "^3.3.2"
  },
  "devDependencies": {
    "@types/node": "^10.12.10",
    "tslint": "~5.8.0",
    "typescript": "~3.1.0"
  },
  "private": true
}
[info] i  functions: ensuring necessary APIs are enabled...
[debug] [2019-01-24T20:53:58.073Z] >>> HTTP REQUEST GET https://servicemanagement.googleapis.com/v1/services/cloudfunctions.googleapis.com/projectSettings/proclubs-c0955?view=CONSUMER_VIEW  
 
[debug] [2019-01-24T20:53:58.074Z] >>> HTTP REQUEST GET https://servicemanagement.googleapis.com/v1/services/runtimeconfig.googleapis.com/projectSettings/proclubs-c0955?view=CONSUMER_VIEW  
 
[debug] [2019-01-24T20:53:59.578Z] <<< HTTP RESPONSE 200
[info] ✔  functions: all necessary APIs are enabled
[debug] [2019-01-24T20:53:59.950Z] <<< HTTP RESPONSE 200
[debug] [2019-01-24T20:53:59.950Z] >>> HTTP REQUEST GET https://cloudresourcemanager.googleapis.com/v1/projects/proclubs-c0955  
 
[debug] [2019-01-24T20:54:00.974Z] <<< HTTP RESPONSE 200
[debug] [2019-01-24T20:54:00.974Z] >>> HTTP REQUEST GET https://mobilesdk-pa.googleapis.com/v1/projects/610036645559:getServerAppConfig  
 
[debug] [2019-01-24T20:54:01.211Z] <<< HTTP RESPONSE 200
[info] i  functions: preparing functions directory for uploading...
[debug] [2019-01-24T20:54:01.213Z] >>> HTTP REQUEST GET https://runtimeconfig.googleapis.com/v1beta1/projects/proclubs-c0955/configs  
 
[debug] [2019-01-24T20:54:01.557Z] <<< HTTP RESPONSE 200
[info] i  functions: packaged functions (175.4 KB) for uploading
[debug] [2019-01-24T20:54:02.145Z] >>> HTTP REQUEST POST https://cloudfunctions.googleapis.com/v1/projects/proclubs-c0955/locations/us-central1/functions:generateUploadUrl  
 
[debug] [2019-01-24T20:54:02.613Z] <<< HTTP RESPONSE 200
[debug] [2019-01-24T20:54:02.614Z] >>> HTTP REQUEST PUT https://storage.googleapis.com/gcf-upload-us-central1-cb0f36f8-0c1b-42b0-aded-c432f3572975/b6afd2e6-0ff6-4956-9813-c280a9f3b825.zip?GoogleAccessId=service-610036645559@gcf-admin-robot.iam.gserviceaccount.com&Expires=1548365042&Signature=ZwDRZ4YF10QImYNMumXt184vS2J0wn4dOwEkU%2BalopAjIXe3qReabol4tTF6VYqwdcCWfZWFpIauGFzGN6cNbp1lp1MLZA6h4s5iAxP%2BlKjEONc8VaeSIX3wJsBtAVI7nKgTTP%2BOUZM0hf3BnjzDuXCaYXEiOUwdYCeN7psr1dEvyitwo80lvn8oYkbIn6Wus6xLlK2e%2Bzo6d5oGtQt8W95Iaax1Oxx08JPyvxoc31b3Bnc6e%2ByJsVw9yPNBdnGo4cA53jRhDj9xzzManAndRouXNM5dcKFGAb%2BSZsZga5D4uOVGqWNICtMgpcYFELxhLe1mXFgV1BTl8sAtJOjRnA%3D%3D  

[debug] [2019-01-24T20:54:03.319Z] <<< HTTP RESPONSE 400
[debug] [2019-01-24T20:54:03.319Z] <<< HTTP RESPONSE BODY <?xml version='1.0' encoding='UTF-8'?><Error><Code>InvalidArgument</Code><Message>Invalid argument.</Message></Error>
[warn] ⚠  functions: Upload Error: HTTP Error: 400, Unknown Error
[error] 
[error] Error: HTTP Error: 400, Unknown Error
[debug] [2019-01-24T20:54:03.322Z] Error Context: {
  "body": {
    "error": {
      "message": "Unknown Error"
    }
  },
  "response": {
    "statusCode": 400,
    "body": "<?xml version='1.0' encoding='UTF-8'?><Error><Code>InvalidArgument</Code><Message>Invalid argument.</Message></Error>",
    "headers": {
      "x-guploader-uploadid": "AEnB2UqmpphQkiGf-amlEWdNJTeaBqT0fu-iNYpuk74pPX-FcaWyDIICLee9ovPJwWL5zPYeGbjBpGPtDcDVwC-2zaTxCMjN9Q",
      "content-type": "application/xml; charset=UTF-8",
      "content-length": "117",
      "vary": "Origin",
      "date": "Thu, 24 Jan 2019 20:54:03 GMT",
      "server": "UploadServer",
      "alt-svc": "quic=\":443\"; ma=2592000; v=\"44,43,39\""
    },
    "request": {
      "uri": {
        "protocol": "https:",
        "slashes": true,
        "auth": null,
        "host": "storage.googleapis.com",
        "port": 443,
        "hostname": "storage.googleapis.com",
        "hash": null,
        "search": "?GoogleAccessId=service-610036645559@gcf-admin-robot.iam.gserviceaccount.com&Expires=1548365042&Signature=ZwDRZ4YF10QImYNMumXt184vS2J0wn4dOwEkU%2BalopAjIXe3qReabol4tTF6VYqwdcCWfZWFpIauGFzGN6cNbp1lp1MLZA6h4s5iAxP%2BlKjEONc8VaeSIX3wJsBtAVI7nKgTTP%2BOUZM0hf3BnjzDuXCaYXEiOUwdYCeN7psr1dEvyitwo80lvn8oYkbIn6Wus6xLlK2e%2Bzo6d5oGtQt8W95Iaax1Oxx08JPyvxoc31b3Bnc6e%2ByJsVw9yPNBdnGo4cA53jRhDj9xzzManAndRouXNM5dcKFGAb%2BSZsZga5D4uOVGqWNICtMgpcYFELxhLe1mXFgV1BTl8sAtJOjRnA%3D%3D",
        "query": "GoogleAccessId=service-610036645559@gcf-admin-robot.iam.gserviceaccount.com&Expires=1548365042&Signature=ZwDRZ4YF10QImYNMumXt184vS2J0wn4dOwEkU%2BalopAjIXe3qReabol4tTF6VYqwdcCWfZWFpIauGFzGN6cNbp1lp1MLZA6h4s5iAxP%2BlKjEONc8VaeSIX3wJsBtAVI7nKgTTP%2BOUZM0hf3BnjzDuXCaYXEiOUwdYCeN7psr1dEvyitwo80lvn8oYkbIn6Wus6xLlK2e%2Bzo6d5oGtQt8W95Iaax1Oxx08JPyvxoc31b3Bnc6e%2ByJsVw9yPNBdnGo4cA53jRhDj9xzzManAndRouXNM5dcKFGAb%2BSZsZga5D4uOVGqWNICtMgpcYFELxhLe1mXFgV1BTl8sAtJOjRnA%3D%3D",
        "pathname": "/gcf-upload-us-central1-cb0f36f8-0c1b-42b0-aded-c432f3572975/b6afd2e6-0ff6-4956-9813-c280a9f3b825.zip",
        "path": "/gcf-upload-us-central1-cb0f36f8-0c1b-42b0-aded-c432f3572975/b6afd2e6-0ff6-4956-9813-c280a9f3b825.zip?GoogleAccessId=service-610036645559@gcf-admin-robot.iam.gserviceaccount.com&Expires=1548365042&Signature=ZwDRZ4YF10QImYNMumXt184vS2J0wn4dOwEkU%2BalopAjIXe3qReabol4tTF6VYqwdcCWfZWFpIauGFzGN6cNbp1lp1MLZA6h4s5iAxP%2BlKjEONc8VaeSIX3wJsBtAVI7nKgTTP%2BOUZM0hf3BnjzDuXCaYXEiOUwdYCeN7psr1dEvyitwo80lvn8oYkbIn6Wus6xLlK2e%2Bzo6d5oGtQt8W95Iaax1Oxx08JPyvxoc31b3Bnc6e%2ByJsVw9yPNBdnGo4cA53jRhDj9xzzManAndRouXNM5dcKFGAb%2BSZsZga5D4uOVGqWNICtMgpcYFELxhLe1mXFgV1BTl8sAtJOjRnA%3D%3D",
        "href": "https://storage.googleapis.com/gcf-upload-us-central1-cb0f36f8-0c1b-42b0-aded-c432f3572975/b6afd2e6-0ff6-4956-9813-c280a9f3b825.zip?GoogleAccessId=service-610036645559@gcf-admin-robot.iam.gserviceaccount.com&Expires=1548365042&Signature=ZwDRZ4YF10QImYNMumXt184vS2J0wn4dOwEkU%2BalopAjIXe3qReabol4tTF6VYqwdcCWfZWFpIauGFzGN6cNbp1lp1MLZA6h4s5iAxP%2BlKjEONc8VaeSIX3wJsBtAVI7nKgTTP%2BOUZM0hf3BnjzDuXCaYXEiOUwdYCeN7psr1dEvyitwo80lvn8oYkbIn6Wus6xLlK2e%2Bzo6d5oGtQt8W95Iaax1Oxx08JPyvxoc31b3Bnc6e%2ByJsVw9yPNBdnGo4cA53jRhDj9xzzManAndRouXNM5dcKFGAb%2BSZsZga5D4uOVGqWNICtMgpcYFELxhLe1mXFgV1BTl8sAtJOjRnA%3D%3D"
      },
      "method": "PUT"
    }
  }
}
```

**Comment by bkendall** [comment]
what do you mean by "removing the function"? Can you deploy any function successfully? Or do any attempts fail. If any attempts fail, can you tell us more about how you've written your functions?

**Comment by ziyafenn** [comment]
@bkendall  By removing i meant deleting function with `firebase functions:delete function1-name`.

No, i can't deploy any function. Here is the screenshot of CLI
https://www.dropbox.com/s/1vr2bbfplfzjbl8/Screenshot%202019-01-24%2022.31.50.png?dl=0

The thing is, i don't have any problem of deploying same functions to my clone/test project (i use it for testing). But with my primary project, i have this problem and can't figure out why.

Based on log, i can guess that something is wrong with the service account? No idea...

**Comment by bkendall** [comment]
I'd check to make sure that service account (`service-610036645559@`?) exists in your project. This is going to be an issue for which you should reach out to [Firebase Support](https://firebase.google.com/support) as this is more account related than CLI related.

**Comment by dcts** [comment]
having the same issue. Unknown error is not very helpfull as a log here unfortunately.

**Comment by doorwarpranjal** [comment]
Is this solved now because i am also facing same issue

**Comment by dcts** [comment]
Maybe helpfull to someone: check if you have a `node_modules` folder inside the main directory, and if yes, chances are that it does not belong there and can be deleted. (I accidentally run `npm install <any-package>` inside the main folder, and my codeeditor does not show the `node_modules` folder so I was not aware that I am uploading a ton of data 😅)

We need to always remember:

<img width=400 src="https://user-images.githubusercontent.com/44790691/114205341-7e4cc980-995a-11eb-8af8-f80c46e12e1a.png">

**Comment by samrat2825** [comment]
Hey, I am new to this so please stick with me. I am trying to host my Nextjs app using firebase functions. I was working perfectly previously but after some minor changes to the code I am getting 400 error. Below is the debug log:

And I know the problem is my size of upload is greater than permitted but I didn't add any new npm package and as I said it was working perfectly previously. I have added my code structure and firebase.json file.

**Firebase.json**
![image](https://user-images.githubusercontent.com/44095348/144547696-6cf9a871-31db-407c-b43e-1c5a5edbb9fc.png)

**Project Structure**
![image](https://user-images.githubusercontent.com/44095348/144547793-a0f56ef9-8876-46cb-a829-79c75777c93a.png)

**Log**
`Error: HTTP Error: 400, Unknown Error
[2021-12-03T04:49:49.176Z] Error Context: {
  "body": {
    "error": {
      "message": "Unknown Error"
    }
  },
  "response": {
    "statusCode": 400,
    "body": "<?xml version='1.0' encoding='UTF-8'?><Error><Code>EntityTooLarge</Code><Message>Your proposed upload is larger than the maximum object size specified in your Policy Document.</Message><Details>Content-length exceeds upper bound on range</Details></Error>",
    "headers": {
      "x-guploader-uploadid": "ADPycdvsHgZ5HePYPEDJQU3S8jF8nZjSAH3j-5kibbJMIc1feR1fNBsnUJa73ac8ZtdWwS4GgCkDLPI-fXRpIuxx6F4",
      "content-type": "application/xml; charset=UTF-8",
      "content-length": "255",
      "vary": "Origin",
      "date": "Fri, 03 Dec 2021 04:49:49 GMT",
      "server": "UploadServer",
      "alt-svc": "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\""
    },
    "request": {
      "uri": {
        "protocol": "https:",
        "slashes": true,
        "auth": null,
        "host": "storage.googleapis.com",
        "port": 443,
        "hostname": "storage.googleapis.com",
        "hash": null,
        "search": "?GoogleAccessId=service-477293540165@gcf-admin-robot.iam.gserviceaccount.com&Expires=1638508769&Signature=Jedj9pxY0EA87uN2R4rGCoc21Q4yE16qRrhq0q8w1Hy7wHoIeUiPF6CJgWEPzdItASHr61bKfKr8XVrdu9ELn1WQf0TtFugjRSKvqVWw0C2lWEWcaHpx8m%2FQYRj8vMbU4Ar3NbMgIqwOLXs%2F4IKXjOevTr0R8JRigd%2F65JoyTRyG%2Fn9i%2B8unrQ0yVzjDIDtiJdNqgSKYgXxkBitwWvYkoSY6dJz89HOU7rMOlQPSHBRE1vklpwFFDwZjnR1Nwk0sZSxextPEJwK6rzTXWdKzsaxky3yXSqTV2Yt%2BGA1AB9fZh%2BRJOVV81bApVbWB5rbZoOqv7ZQKfxFD1sHUFpf70Q%3D%3D",
        "query": "GoogleAccessId=service-477293540165@gcf-admin-robot.iam.gserviceaccount.com&Expires=1638508769&Signature=Jedj9pxY0EA87uN2R4rGCoc21Q4yE16qRrhq0q8w1Hy7wHoIeUiPF6CJgWEPzdItASHr61bKfKr8XVrdu9ELn1WQf0TtFugjRSKvqVWw0C2lWEWcaHpx8m%2FQYRj8vMbU4Ar3NbMgIqwOLXs%2F4IKXjOevTr0R8JRigd%2F65JoyTRyG%2Fn9i%2B8unrQ0yVzjDIDtiJdNqgSKYgXxkBitwWvYkoSY6dJz89HOU7rMOlQPSHBRE1vklpwFFDwZjnR1Nwk0sZSxextPEJwK6rzTXWdKzsaxky3yXSqTV2Yt%2BGA1AB9fZh%2BRJOVV81bApVbWB5rbZoOqv7ZQKfxFD1sHUFpf70Q%3D%3D",
        "pathname": "/gcf-upload-us-central1-4bb093fc-8602-449d-9e8c-ea7f61220235/db0d02de-af8f-49d3-909e-c5d29ffb5d9a.zip",
        "path": "/gcf-upload-us-central1-4bb093fc-8602-449d-9e8c-ea7f61220235/db0d02de-af8f-49d3-909e-c5d29ffb5d9a.zip?GoogleAccessId=service-477293540165@gcf-admin-robot.iam.gserviceaccount.com&Expires=1638508769&Signature=Jedj9pxY0EA87uN2R4rGCoc21Q4yE16qRrhq0q8w1Hy7wHoIeUiPF6CJgWEPzdItASHr61bKfKr8XVrdu9ELn1WQf0TtFugjRSKvqVWw0C2lWEWcaHpx8m%2FQYRj8vMbU4Ar3NbMgIqwOLXs%2F4IKXjOevTr0R8JRigd%2F65JoyTRyG%2Fn9i%2B8unrQ0yVzjDIDtiJdNqgSKYgXxkBitwWvYkoSY6dJz89HOU7rMOlQPSHBRE1vklpwFFDwZjnR1Nwk0sZSxextPEJwK6rzTXWdKzsaxky3yXSqTV2Yt%2BGA1AB9fZh%2BRJOVV81bApVbWB5rbZoOqv7ZQKfxFD1sHUFpf70Q%3D%3D",
        "href": "https://storage.googleapis.com/gcf-upload-us-central1-4bb093fc-8602-449d-9e8c-ea7f61220235/db0d02de-af8f-49d3-909e-c5d29ffb5d9a.zip?GoogleAccessId=service-477293540165@gcf-admin-robot.iam.gserviceaccount.com&Expires=1638508769&Signature=Jedj9pxY0EA87uN2R4rGCoc21Q4yE16qRrhq0q8w1Hy7wHoIeUiPF6CJgWEPzdItASHr61bKfKr8XVrdu9ELn1WQf0TtFugjRSKvqVWw0C2lWEWcaHpx8m%2FQYRj8vMbU4Ar3NbMgIqwOLXs%2F4IKXjOevTr0R8JRigd%2F65JoyTRyG%2Fn9i%2B8unrQ0yVzjDIDtiJdNqgSKYgXxkBitwWvYkoSY6dJz89HOU7rMOlQPSHBRE1vklpwFFDwZjnR1Nwk0sZSxextPEJwK6rzTXWdKzsaxky3yXSqTV2Yt%2BGA1AB9fZh%2BRJOVV81bApVbWB5rbZoOqv7ZQKfxFD1sHUFpf70Q%3D%3D"
      },
      "method": "PUT"
    }
  }
}`

How do I resolve this?
