### ISSUE TITLE
Able to specify which functions should be deployed from firebase.json

### ISSUE THREAD

**Issue by lazreg87** [firebase/firebase-tools#1125]
Be able to specify which functions should be deployed in the firebase.json config. Basically allowing the same functionality that already exists with the command ```firebase deploy --only functions:function1,functions:function2``` but from the config file instead

Example firebase.json:
```
{
  “functions”: {
    “only”: [“function1”, “function2”]
  }
} 
```

**Comment by mbleigh** [comment]
I've been thinking of something a little different, but along these lines to make it easier to manage multiple repos that deploy functions to the same project. I'll leave this open as a tracking bug for that effort 😄

**Comment by lazreg87** [comment]
@mbleigh, let me know if you want a PR on this issue with your approach. Happy to contribute

**Comment by joehan** [comment]
https://firebase.google.com/docs/functions/organize-functions#organize_functions_in_codebases seems to solve the core ask here of making it easier to deploy functions from multiple repos to the same project
