### ISSUE TITLE
Support index deletion during deployment

### ISSUE THREAD

**Issue by samtstern** [firebase/firebase-tools#1127]
Currently if you `firebase deploy` indexes, it is append-only.  Indexes in your `indexes.json` file that to not exist will be created, but indexes that only exist on the server will not be deleted.

We should add a `--force` flag or similar (whatever Cloud Functions does) to do a strict deployment where the end result is 1:1 server to local matching.

This would mean that deploying `indexes: []` would be equivalent to deleting all compound indexes.

**Comment by ashking** [comment]
Is this feature being developed?

**Comment by samtstern** [comment]
No, not actively being worked on at the moment.  If you think you can do it, pull requests welcome!

**Comment by samtstern** [comment]
Fixed in #2327
