### ISSUE TITLE
not work hosting.stop() function

### ISSUE THREAD

**Issue by k2wanko** [firebase/firebase-tools#1134]
### [REQUIRED] Environment info

**firebase-tools:** 6.1.1

**Platform:** macos

### [REQUIRED] Test case

```js
const Config = require('firebase-tools/lib/config');
const requirePermissions = require('firebase-tools/lib/requirePermissions');
const hosting = require('firebase-tools/lib/serve/hosting');

const config = Config.load({}, true);
const rcfile = config.readProjectFile('.firebaserc', {
  json: true,
  fallback: {},
});
const options = {
  port: 55000,
  project: rcfile.projects.default,
  config,
};

await requirePermissions(options);

await hosting.start()

// e2e test

await hosting.stop() // <-- not work hosting.stop() function!
```

https://github.com/firebase/firebase-tools/blob/3fc972f054768b43927d3d762c226b03d8d9501b/src/serve/hosting.js#L67-L69

I'm in trouble that jest has not finish. 
Please fix it.

Probably like this
```js
var server;

function _startServer(options, config, port, init) {
  server = superstatic({
  ...
}

function _stop() {
  if (server) {
    server.close()
  }
  return Promise.resolve();
}
```

**Comment by joehan** [comment]
Hey @k2wanko, thanks for reporting this. I chatted with some devs on the Firebase hosting team, and they think that the fix you implemented on your branch looks good. Could you open a PR onto this repo for it?

**Comment by k2wanko** [comment]
Hi @joehan 
I was PR created. Please check.
