### ISSUE TITLE
Firebase deploy fails with "Error: HTTP Error: 500, Internal error encountered."

### ISSUE THREAD

**Issue by nobuta0613** [firebase/firebase-tools#1138]
Our deployment fails with following error:HTTP Error: 500, Internal error encountered.
###  Environment info

node:v10.15.1
npm:6.4.1
firebase-tools:6.3.1

Platform:macOS

### **Log** 

[debug] [2019-02-06T14:34:13.343Z] ----------------------------------------------------------------------
[debug] [2019-02-06T14:34:13.345Z] Command:       /usr/local/bin/node /usr/local/bin/firebase deploy
[debug] [2019-02-06T14:34:13.346Z] CLI Version:   6.3.1
[debug] [2019-02-06T14:34:13.346Z] Platform:      darwin
[debug] [2019-02-06T14:34:13.346Z] Node Version:  v10.15.1
[debug] [2019-02-06T14:34:13.346Z] Time:          Wed Feb 06 2019 23:34:13 GMT+0900 (GMT+09:00)
[debug] [2019-02-06T14:34:13.346Z] ----------------------------------------------------------------------
[debug] 
[debug] [2019-02-06T14:34:13.357Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2019-02-06T14:34:13.358Z] > authorizing via signed-in user
[debug] [2019-02-06T14:34:13.358Z] [iam] checking project myportfolioproject-1b568 for permissions ["firebase.projects.get","firebasehosting.sites.update"]
[debug] [2019-02-06T14:34:13.360Z] > refreshing access token with scopes: ["email","https://www.googleapis.com/auth/cloud-platform","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","openid"]
[debug] [2019-02-06T14:34:13.360Z] >>> HTTP REQUEST POST https://www.googleapis.com/oauth2/v3/token  
 <request body omitted>
[debug] [2019-02-06T14:34:13.855Z] <<< HTTP RESPONSE 200
[debug] [2019-02-06T14:34:13.878Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects/myportfolioproject-1b568:testIamPermissions  

[debug] [2019-02-06T14:34:14.803Z] <<< HTTP RESPONSE 200
[debug] [2019-02-06T14:34:14.806Z] >>> HTTP REQUEST GET https://firebase.googleapis.com/v1beta1/projects/myportfolioproject-1b568  
 
[debug] [2019-02-06T14:34:15.773Z] <<< HTTP RESPONSE 200
[info] 
[info] === Deploying to 'myportfolioproject-1b568'...
[info] 
[info] i  deploying hosting
[debug] [2019-02-06T14:34:15.781Z] >>> HTTP REQUEST POST https://firebasehosting.googleapis.com/v1beta1/sites/myportfolioproject-1b568/versions  

[debug] [2019-02-06T14:34:17.075Z] <<< HTTP RESPONSE 500
[debug] [2019-02-06T14:34:17.075Z] <<< HTTP RESPONSE BODY
[error] 
[error] Error: HTTP Error: 500, Internal error encountered.
[debug] [2019-02-06T14:34:17.453Z] Error Context: {
  "body": {
    "error": {
      "code": 500,
      "message": "Internal error encountered.",
      "status": "INTERNAL"
    }
  },
  "response": {
    "statusCode": 500,
    "body": {
      "error": {
        "code": 500,
        "message": "Internal error encountered.",
        "status": "INTERNAL"
      }
    },
    "headers": {
      "vary": "X-Origin, Referer, Origin,Accept-Encoding",
      "content-type": "application/json; charset=UTF-8",
      "date": "Wed, 06 Feb 2019 14:34:16 GMT",
      "server": "ESF",
      "cache-control": "private",
      "x-xss-protection": "1; mode=block",
      "x-frame-options": "SAMEORIGIN",
      "x-content-type-options": "nosniff",
      "alt-svc": "quic=\":443\"; ma=2592000; v=\"44,43,39\"",
      "accept-ranges": "none",
      "transfer-encoding": "chunked"
    },
    "request": {
      "uri": {
        "protocol": "https:",
        "slashes": true,
        "auth": null,
        "host": "firebasehosting.googleapis.com",
        "port": 443,
        "hostname": "firebasehosting.googleapis.com",
        "hash": null,
        "search": null,
        "query": null,
        "pathname": "/v1beta1/sites/myportfolioproject-1b568/versions",
        "path": "/v1beta1/sites/myportfolioproject-1b568/versions",
        "href": "https://firebasehosting.googleapis.com/v1beta1/sites/myportfolioproject-1b568/versions"
      },
      "method": "POST"
    }
  }
}

**Comment by gootyfer** [comment]
Same error here, but the error arose when deploying hosting. Deploying security rules, functions was OK.

**Comment by mbleigh** [comment]
Things should be back to normal now. Sorry for the inconvenience!

https://status.firebase.google.com/incident/Hosting/19006
