### ISSUE TITLE
firebase serve not triggering firestore events on localhost

### ISSUE THREAD

**Issue by lambasoft** [firebase/firebase-tools#1140]
`firebase serve` does not trigger events onWrite, onCreate, .. on a firestore database.

But if I `firebase deploy` and test it on my online url, the events get triggered.

Is this normal behavior?

**Comment by GitTom** [comment]
Yes, I think that is normal.  `Firebase serve` only emulates the HTTP functions, but you can invoke the others manually for local testing via the firebase shell.  See [the docs here](https://firebase.google.com/docs/functions/local-emulator#invoke_firestore_functions) for more.

**Comment by lambasoft** [comment]
@GitTom Thank you very much
