### ISSUE TITLE
Error: HTTP Error: 503, The service is currently unavailable.

### ISSUE THREAD

**Issue by thedigglemister** [firebase/firebase-tools#1143]
Trying to deploy a single function using "firebase deploy --only functions:myFunction and getting 503 error

### Environment info

**firebase-tools:** 6.3.1

**Platform:** macOS

**Comment by lambasoft** [comment]
Having the same issue on my linux ubuntu

**Comment by thedigglemister** [comment]
https://status.firebase.google.com/ now shows that the issue is being investigated

**Comment by kevinajian** [comment]
Yes this is currently being investigated. Thanks for filing and updates will be posted on the status page.

**Comment by acaciomartins** [comment]
I got it the second time!!!
