### ISSUE TITLE
firebase.json - Ability to specify per function include/exclude

### ISSUE THREAD

**Issue by wootencl** [firebase/firebase-tools#1163]
Quick feature request that I'd be happy to take a stab at implementing if there's interest:

 It would be helpful if it was possible to specify a per function include/exclude for packaging. So, for example, if I had `handler1`, `handler2`, and `handler3` in my `index.js` I could then add the following to my `firebase.json` (or something similar);
```
{
    <hosting_config>,
    "functions": {
        "source": <functions_source>,
        "handler1": {
            "include": "path/to/handler1/files",
            "exclude": "path/**" 
        },
        etc.
    }
}
```

I'll admit that my need/reasoning for this is probably in the edge of what most typical user's would experience in regards to firebase. The issue I'm facing at the moment though is that I have a fairly large amount of heavy handlers and when I deploy `handler1` it gets packaged with the code for `handler2` and `handler3` when there's _zero_ need for that code from the perspective of `handler1`. This is beginning to mean that my functions package size is nearing the allotted limit of 100MB (seen [here](https://cloud.google.com/functions/quotas)). With the addition of a per function include/exclude I could then specify what exact files (outside of the `index.js` which should remain required) should be packaged and deployed for a corresponding function.

Hopefully all that makes sense. Happy to expand further if not!

**Comment by mbleigh** [comment]
Thanks for the request...I'm a little curious how you're getting close to 100MB, honestly :smile: 

I don't think this is something we're likely to do as the Firebase CLI really aims to deploy functions as a package, and per-function include/exclude rules would mean a ton of duplicative packaging and would also potentially undermine some future performance improvements we're working on.

What I'd recommend for the time being is to split into multiple working directories of related functions with each group, and then use `--only` when deploying to avoid overwrite issues.

```js
// dir1/functions/index.js
exports.dir1 = {
  myfunc: functions.https.onRequest(...)
}

// dir2/functions/index.js
exports.dir2 = {
  anotherfunc: functions.https.onRequest(...)
}
```

Then, when deploying:

```
# in dir1
$ firebase deploy --only dir1
# in dir2
$ firebase deploy --only dir2
```

**Comment by wootencl** [comment]
@mbleigh Totally understand and thanks for getting back to me! Was thinking I might have to go that direction if this wasn't something of interest so much appreciated as your suggestion provides further validation for making a shift that way.

Happy to satisfy your curiosity though and explain how I'll be able to get to the 100MB: I'm using [Next.js](https://github.com/zeit/next.js) with their serverless target in combination with google cloud functions. Works really well in all honesty, but  _each_ page of the app is bundled with all of it's dependencies inline (so there's no need for node_modules, requires, etc.). This translates to the handlers (or pages) being pretty heavy (~2MB). As my number of pages grows so does my zip size. 

Admittedly I'm not entirely positive my usage is in line with the typical use cases so I'll more than likely shift away when the time comes.

**Comment by johnapost** [comment]
I would also like support for bundling cloud functions separately.

I don't think my little toy apps will run into the 100mb limit, but I would prefer not to shift away from the Firebase platform if I try to build something meatier.

**Comment by thefliik** [comment]
Perhaps this could be handled by allowing the main functions entry point to export "getter functions" which return a promise resolving to a firebase function.

For example, using typescript:

```ts
// functions/index.ts
export const myfunc = () => import('./myfunc.ts').then(m => m.myfunc);

// functions/myfunc.ts
import * as functions from 'firebase-functions';
export const myfunc = functions.https.onRequest(...)
```

This way, loading a given function would only load the dependencies for that function. I imagine the call to `functions.https.onRequest(...)` would need to return a function containing a special property (e.g. `fn.firbaseFn = true`) to indicate which functions are firebase functions vs anonymous resolution functions.
