### ISSUE TITLE
Valid DynamicLink contains no preview in messengers and FB claims its status code is 400

### ISSUE THREAD

**Issue by AndriyGo** [firebase/firebase-tools#1172]
Long story short - I successfully generated a DynamicLink programmatically on my iOS device. Here it is [https://theorytestrev.com/car_moto/ooYdwRr3iVPEVSTC6](https://theorytestrev.com/car_moto/ooYdwRr3iVPEVSTC6).

This link works on my phone/laptop. However, as soon as I add it to any messenger there is no preview. And Facebook's Sharing Debugger even tells me that the status code returned is "Error 400 (Not Found)!!1": [https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Ftheorytestrev.com%2Fcar_moto%2FooYdwRr3iVPEVSTC6](https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Ftheorytestrev.com%2Fcar_moto%2FooYdwRr3iVPEVSTC6).

Is it a bug?

P.S. This link is obviously shortened. However, unshortened version produces the same result.

**Comment by mh6o** [comment]
It's not related to apple-app-site-association. The link https://theorytestrev.com/car_moto/ooYdwRr3iVPEVSTC6 correctly has social meta tags (sd=, st=, si=), but FDL failed to render these when requested via social containers (unlike page.link).

**Comment by flyersea** [comment]
I had the same issue, links not working for custom domains when sharing with facebook, always 400 not found 1. But page.link works. Not just links from API, links from console give the same error. I sent a email to firebase support last week, and still waiting for response.

**Comment by samtstern** [comment]
Just going through some old issues and I don't think this one has anything to do with the Firebase CLI so I am going to close it.  I'm sorry we never responded to this issue earlier!  Hopefully you were able to resolve it elsewhere.  If not, please reach out to Firebase support.
