### ISSUE TITLE
Save data to firestore from google cloud function

### ISSUE THREAD

**Issue by thakurankesh** [firebase/firebase-tools#1181]
I am trying to save data to firestore using cloud function (MQTT).

Following is the code:

```
exports.helloPubSub = (event, callback) => {

const functions = require('firebase-functions');
const admin = require('firebase-admin');
admin.initializeApp(functions.config().firestore);

const db = admin.firestore()
//admin.initializeApp();
console.log("Start");

  var docRef = db.collection('users').doc('alovelace');

var setAda = docRef.set({
  first: 'Ada',
  last: 'Lovelace',
  born: 1815
});
};
```

I am getting following errors in view logs :

"Function execution took 22 ms, finished with status: 'error'"

Any suggestion

Also after some changes I am getting error - Error: Firebase config variables are not available. Please use the latest version of the Firebase CLI to deploy this function

My package.json is

```
{
"name": "functions",
"description": "Cloud Functions for Firebase",
"dependencies": {
"@google-cloud/vision": "^0.12.0",
"async": "^2.5.0",
"consolidate": "^0.14.5",
"express": "^4.15.4",
"firebase-admin": "^7.2.0",
"firebase-functions": "^2.2.1",
"handlebars": "^4.0.10",
"jquery": "^3.2.1",
"js-levenshtein": "^1.1.3",
"json-query": "^2.2.2"
},
"private": true
}
```

**Comment by joehan** [comment]
Hi @thakurankesh, thanks for filing this! From looking at your code, it seems like you are using a vanilla cloud function. Are you deploying this via 'firebase deploy'? If not, you won't be able to use functions.config(), as it pulls from a config file that Firebase creates at deployment time.

Does your code work as you intended if you change this line
```admin.initializeApp(functions.config().firestore);```
 to 
```admin.initializeApp();```?
