### ISSUE TITLE
Dynamic Link with custom domain not opening App Store

### ISSUE THREAD

**Issue by AndriyGo** [firebase/firebase-tools#1184]
I have generated the following dynamic link: [https://theorytestrev.com/car_moto/CBV9](https://theorytestrev.com/car_moto/CBV9). This link works if my app is installed.

However, if I paste it to Safari and open the preview page there are two problems. If my app is not installed on the device, after I click Open I get redirected to the 404 page of Firebase hosting. The same actually happens when my app is installed.

Is this a bug? Or do I need to upload some content to my Firebase hosting? When I use `page.link` domain, clicking the Open button presents a prompt which wants to open my app (if installed) or App Store (if not installed). I would like to have the same behaviour with my custom domain.

**Comment by bkendall** [comment]
This is a question better suited to [StackOverflow](https://stackoverflow.com/questions/tagged/firebase-dynamic-links) or the [Firebase Community](https://firebase.community)

That said, @Memeriaj might be able to help you out here.

**Comment by AndriyGo** [comment]
@bkendall I thought this was a bug as I configured the link following the docs. And there is no mentioning that links using custom domains would perform differently :)

**Comment by bkendall** [comment]
Sure, sure. I personally don't know the answer to this though. 🙂 If it is indeed a bug, it might be one in the backend of things rather than a bug in the CLI, so I tend to avoid putting `bug` as a label until we know if it is and where it is. @Memeriaj should have better answers for you (and he has this on his radar for today... as far as I know... but can't give an exact promise haha)

**Comment by AndriyGo** [comment]
@bkendall I was simply explaining why I decided to post my question here rather than SO :) Seems like a better place for bug reporting :)

**Comment by Memeriaj** [comment]
That seems like a reasonable thing to expect.  Just off the top of my head I'm thinking that you're getting redirected to another URL on your Site that isn't covered by your rewrite to Firebase Dynamic Links (what that URL would be I have no idea) and thus you get the normal static 404 page.  Let me try digging into it and see what I can find.

**Comment by Memeriaj** [comment]
In the browser (Chrome) on my desktop (Linux) when I go to https://theorytestrev.com/car_moto/CBV9 I end up getting redirected to https://www.theorytestrevolution.com/apps/driving-theory-test-uk-iphone-mac-android?referrer=x1XcymXzKggTwvISQ6h9Ztw3eHi1/ which then serves up an actual page.

As I played around with this someone walked up and told me about the [FDL debug page][0] which you can see by just appending the query parameter `d=1`.  [That page][1] is making me think that is has something to do with the [App preview page][2] because all of the other links in the debug page appear like they should work fine.

Let me see if I can hunt down what the URL of that App Preview page actually is.

[0]: https://firebase.google.com/docs/dynamic-links/debug
[1]: https://theorytestrev.com/car_moto/CBV9?d=1
[2]: https://firebase.google.com/docs/dynamic-links/link-previews#app_preview_pages

**Comment by Memeriaj** [comment]
After some sleuthing (and getting someone with an iPhone to go to that link) I might know what is going on.  The preview page itself seems to load fine it is the open button causing problems (which you said before, `after I click Open I get redirected to the 404 page of Firebase hosting`, and I didn't understand).  The URL from that button is [this long form link][0] which without all of the query strings is https://theorytestrev.com/car_moto.  

What is the glob pattern for your rewrite?  If it is `/car_moto/**` then we should change it to `/car_moto**` and I believe that it should work (but please verify in case I'm wrong about any of this).

[0]: https://theorytestrev.com/car_moto?link=https://www.theorytestrevolution.com/apps/driving-theory-test-uk-iphone-mac-android?referrer%3Dx1XcymXzKggTwvISQ6h9Ztw3eHi1&apn=com.glenmax.theorytest&isi=1078352542&ibi=uk.co.glenmax.iOS.carTest&at=1000lcoL&ct=Referral&pt=118067910&cid=8081707430219691051&_osl=https://theorytestrev.com/car_moto/CBV9

**Comment by mrezk** [comment]
I am having the same exact issue.

- Long link (as generated by link builder, works if I force redirect from app preview):

https://thecountdown.app/share/?link=https%3A%2F%2Fthecountdown%2Eapp%2Fto%3Ftitle%3DNot%2520Working%26emoji%3D%25F0%259F%2598%2594%26hexColor%3D12115%26repeatFrequency%3D0%26dueDate%3D2019%2D04%2D13T00%3A00%3A00%2E000000%252B1000&ibi=com%2Evacation%2Ecountdown%2Eapp&isi=1403367428

- Short link (works if I force redirect from app preview):
https://thecountdown.app/share/C1G2

- Link in "OPEN" button from preview.page.link (note it's missing the slash, so returns 404 from Firebase Hosting):
https://thecountdown.app/share?link=https://thecountdown.app/to?title%3DNot%2520Working%26emoji%3D%25F0%259F%2598%2594%26hexColor%3D12115%26repeatFrequency%3D0%26dueDate%3D2019-04-13T00:00:00.000000%252B1000&isi=1403367428&ibi=com.vacation.countdown.app&cid=8028704955692230782&_osl=https://thecountdown.app/share/C1G2

My rewrite rule is (as instructed in docs)

```json
"rewrites": [
      {
        "source": "/share/**",
        "dynamicLinks": true
      }
]
```

So the Firebase Hosting link is expected to return 404.

Any clues on this? I feel that preview.page.link has a bug generating the link. Any ideas on workarounds?

Cheers!

**Comment by Memeriaj** [comment]
For now you should change your rewrite source to be `"/share**"` instead.  Tomorrow I'll see if we can make any changes on the App Preview page side (because that seems like it would be cleaner overall).

**Comment by AndriyGo** [comment]
@Memeriaj thank you for the suggestion. Changing the rewrite of `source` to `/carMoto**` doesn't work because the preview page is not loading then :)

I think that it is a bug because there is an easy fix. Here is the full URL attached to the Open button:

https://theorytestrev.com/car_moto?link=......

If I manually add a slash after `carMoto` everything works as expected!

I have also double checked which URL my Link Builder returns. For example, here is the long URL:

[https://theorytestrev.com/car_moto/?isi=1078352542&ibi=uk%2Eco%2Eglenmax%2EiOS%2EcarTest&ct=Referral&pt=118067910&link=https%3A%2F%2Fwww%2Etheorytestrevolution%2Ecom%2Fapps%2Fdriving%2Dtheory%2Dtest%2Duk%2Diphone%2Dmac%2Dandroid%3Freferrer%3DwHhwmo1LPvOR4NINeNK6DoJk4MA3&at=1000lcoL&apn=com%2Eglenmax%2Etheorytest](https://theorytestrev.com/car_moto/?isi=1078352542&ibi=uk%2Eco%2Eglenmax%2EiOS%2EcarTest&ct=Referral&pt=118067910&link=https%3A%2F%2Fwww%2Etheorytestrevolution%2Ecom%2Fapps%2Fdriving%2Dtheory%2Dtest%2Duk%2Diphone%2Dmac%2Dandroid%3Freferrer%3DwHhwmo1LPvOR4NINeNK6DoJk4MA3&at=1000lcoL&apn=com%2Eglenmax%2Etheorytest)

As you can see, the slash after `car_moto` is present. However, if the app is not installed and you open this link, the Open button has the URL without a slash attached to it:

[https://theorytestrev.com/car_moto?link=https://www.theorytestrevolution.com/apps/driving-theory-test-uk-iphone-mac-android?referrer%3DwHhwmo1LPvOR4NINeNK6DoJk4MA3&apn=com.glenmax.theorytest&isi=1078352542&ibi=uk.co.glenmax.iOS.carTest&at=1000lcoL&ct=Referral&pt=118067910&cid=8735112480386478123&_fpb=CIAHEJ4DGgVlbi1HQg==&_cpt=cpit&_iumenbl=1&_iumchkactval=1&_plt=323&_uit=90408&_cpb=1](https://theorytestrev.com/car_moto?link=https://www.theorytestrevolution.com/apps/driving-theory-test-uk-iphone-mac-android?referrer%3DwHhwmo1LPvOR4NINeNK6DoJk4MA3&apn=com.glenmax.theorytest&isi=1078352542&ibi=uk.co.glenmax.iOS.carTest&at=1000lcoL&ct=Referral&pt=118067910&cid=8735112480386478123&_fpb=CIAHEJ4DGgVlbi1HQg==&_cpt=cpit&_iumenbl=1&_iumchkactval=1&_plt=323&_uit=90408&_cpb=1)

**Comment by Memeriaj** [comment]
@AndriyGo Not `/carMoto**`, try `/car_moto**`.  It should be almost identical to your original rewrite but with the `/` removed.

I'm asking around to see if I can change the App Preview page, and I'll let you know if I make any progress.

**Comment by AndriyGo** [comment]
@Memeriaj sorry I made a typo. Obviously I tried `/car_moto**`. The preview page is not loading then.

**Comment by mrezk** [comment]
@AndriyGo add both rules, one with a slash and one without one, in my case:
```
"rewrites": [
      {
        "source": "/share/**",
        "dynamicLinks": true
      },
      {
        "source": "/share**",
        "dynamicLinks": true
      }
]
```

This works for me.

**Comment by AndriyGo** [comment]
@mrezk YES! Thank you! :)

**Comment by mrezk** [comment]
@AndriyGo thanks to you for reporting the issue! I was banging my head against the wall trying to figure out if there was something wrong with my configuration. When I found your post it was kind of relieving to know it wasn't just me haha.

Cheers 🍻!

**Comment by Memeriaj** [comment]
I believe that this is fixed on the backend now, the open link path should end with a `/` (before the query string).  You should only need the one Dynamic Links rewrite now and everything should work.  If this isn't the case please let me know and I'll dig into it.

**Comment by rromanchuk** [comment]
I just recently started using https://firebase.google.com/docs/dynamic-links/create-manually for some less important links in emails that i wanted to lazily construct  instead of using the API (lots of different UTMs etc), and was getting strange behavior (would only load static), but it looks like because i was using `https://links.mycustomdomain.com/?link=`  which is a dedicated domain for my dynamic links.  Is it a requirement to build off `myproject.page.link`? ....which if fine, these are all buried hrefs anyways.  I just want to be sure i didnt misconfigure something, everything is working fine with the REST API
