### ISSUE TITLE
firebase.json - ignore doesn't work

### ISSUE THREAD

**Issue by boredelf** [firebase/firebase-tools#119]
Hi, guys! :smile: 

I'm trying to get Firebase to ignore a list of files on deploy, but to no avail. My `firebase.json` is as follow:

```json
{
   "firebase": "randomsite",
   "public": "./",
   "ignore": [
      "firebase.json",
      "**/.*",
      "src/**",
      "node_modules/**",
      "jspm_modules/**"
   ]
}
```

From the documentation, I understood the glob patterns are relative to the `public` property, so as far as I know, this configuration looks correct. :(

To be clear: **the deploy is working**, the issue is the non-functioning ignore. I tried changing the patterns, and every time, the files count was too high to be ignoring. And sometimes the deploy would fail, and the error message would display a file from the `jspm_modules` folder, which was supposed to be ignored.

Think you could give a hand? Appreciate it! By the way, Happy New Year!

**Comment by drtriumph** [comment]
Hey, try this out and let me know what happens:
```json
{
   "firebase": "randomsite",
   "public": "./",
   "ignore": [
      "firebase.json",
      "**/.*",
      "src/**/*",
      "node_modules/**/*",
      "jspm_modules/**/*"
   ]
}
```

**Comment by boredelf** [comment]
It seems I had a bad start of year. :sob: 

As often happens with these issues, I didn't pay enough attention. Working long hours, sleepy and tired.
**I do apologize**, I ended up opening this for naught. I didn't realize it's `jspm_packages`, not `jspm_modules`, and so, judging by the files amount, misunderstood, thinking both (jspm and node dirs) were being uploaded.

Again, I'm very sorry and appreciate the quick reply. I'm gonna save you the trouble of closing this. :smile:

**Comment by drtriumph** [comment]
Glad you got it sorted, thanks for reporting back!
