### ISSUE TITLE
order of fields for an index shouldn't be reordered in alphabetical order

### ISSUE THREAD

**Issue by masatomo** [firebase/firebase-tools#1195]
### [REQUIRED] Environment info

All versions, all platforms.

**firebase-tools:**

6.6.0

**Platform:**

macOS

### [REQUIRED] Test case

With https://github.com/firebase/firebase-tools/pull/1168 this patch, fields of indexes is reordered in alphabetical order. 

we can't do this kind of operation properly now as index ordered is changed.

```
firebase firestore:indexes -P staging > firestore.indexes.json
firebase deploy --only firestore:indexes -P production
```

for example, when there is an index "last_name" ascending, "first_name". ascending, it'll be outputted as "first_name" ascending, "last_name" ascending. 

### [REQUIRED] Steps to reproduce

run `firebase firestore:indexes` 

### [REQUIRED] Expected behavior

fields of an index shouldn't be reordered in alphabetical order.

### [REQUIRED] Actual behavior

fields of an index is reordered in alphabetical order

**Comment by samtstern** [comment]
@masatomo yikes good catch!  Will fix ASAP

**Comment by masatomo** [comment]
thanks!
