### ISSUE TITLE
programatically delete all collections

### ISSUE THREAD

**Issue by hclivess** [firebase/firebase-tools#1198]
No way to programatically delete all collections

**Comment by bkendall** [comment]
From where?

Realtime Database? https://stackoverflow.com/questions/42182389/how-to-remove-all-data-from-a-firebase-database

Firestore? https://firebase.google.com/docs/firestore/solutions/delete-collections

This is a good question for the [Firebase Slack Community](https://firebase.community) if you would like to join the conversations there! Hop into the appropriate room and folks there should be able to help you out.

**Comment by hclivess** [comment]
Firestore, do you have a python version? Why is this so difficult? Why is it not in GUI? I don't use node.js

**Comment by bkendall** [comment]
There is a Python client: https://googleapis.github.io/google-cloud-python/latest/firestore/client.html

There is also a way to delete collections via the UI (though it does not do multiple collections):
![image](https://user-images.githubusercontent.com/160236/56391067-741be880-61e2-11e9-8d58-188019f99860.png)

Does that help?

**Comment by hclivess** [comment]
Thanks, I know you can do it manually, but I have 400 collections... previously it was possible to delete / easily, not it's not... Reason to hate cloud - no way to directly control the data with any reasonable easy

**Comment by hclivess** [comment]
It can be done using this
https://github.com/abehaskins/firepit/releases/tag/0.1.0
it supports ```firebase firestore:delete --all-collections -y```

**Comment by bkendall** [comment]
Ah, sure, that will work. That uses normal `firebase-tools`, so you can do that with the normal CLI installed as well. Glad you found a solution that works for you!

**Comment by hclivess** [comment]
I am still not happy, because this installed npm somewhere on my system. I do not want to install anything or configure a whole environment just to delete a database (in batches anyway). That's a horrible approach and very historically un-Googly. Although I see Google is becoming something very different in the last years.

**Comment by laurenzlong** [comment]
@hclivess Unfortunately since the Firebase CLI is written with Node, there is no way to install it without having npm on your system. Sorry for the inconvenience.
