### ISSUE TITLE
Improve error message when port is in use (or choose a different port)

### ISSUE THREAD

**Issue by mikelehen** [firebase/firebase-tools#120]
Currently you get:

    $ firebase serve
    Listening at http://localhost:5000

    Error: An unexpected error has occurred.

For comparison, "python -mSimpleHTTPServer" gives you "socket.error: [Errno 48] Address already in use" and ["http-server"](https://www.npmjs.com/package/http-server) just chooses a new port.

**Comment by brendanlim** [comment]
Since v3.0.0, we now automatically try another port if 5000 is currently in use.
