### ISSUE TITLE
firebase login throw authentication error

### ISSUE THREAD

**Issue by huiyifyj** [firebase/firebase-tools#1206]
### Environment info
 
- **firebase-tools:** 6.7.0
- **Platform:** Windows10, PowerShell 5.1

### Expected behavior
Run `firebase login --no-localhost` always throw error.
![login-error](https://user-images.githubusercontent.com/32027253/56467342-38865600-6450-11e9-857c-71105eb42682.PNG)

Then `firebase login --no-localhost --reauth`, it still throw same error.
![reauth-error](https://user-images.githubusercontent.com/32027253/56467375-8a2ee080-6450-11e9-85a2-b9d2cc911958.PNG)

The error information:
```
Error: Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth
For CI servers and headless environments, generate a new token with firebase login:ci 
```

**Comment by laurenzlong** [comment]
Hi, can you try `firebase login --reauth`, and after that succeeds try `firebase login --localhost`?

**Comment by laurenzlong** [comment]
We've also historically had issues with PowerShell, can you try using cmd.exe?

**Comment by huiyifyj** [comment]
> Hi, can you try `firebase login --reauth`, and after that succeeds try `firebase login --localhost`?

Do as you recommend, it still cloud not login successfully.
And same error occurred while using `cmd.exe`.
I think that may be proxy protocol (like `sock5 http`) is not allowed in the process of connecting with google oauth server, but I'm not sure if this is the reason.
I must use proxy to connect with google for GFW in China.

**Comment by tinaliang** [comment]
Hi, which proxy protocol are you using? We currently have HTTP/S proxy support (see issue #155), but not socks proxy support so that could be your issue. If you need socks proxy support, please upvote issue #883. Hope this helps!

**Comment by huiyifyj** [comment]
@tinaliang 
It seems that it is really sock5 proxy problem.
Thanks for your reply.
