### ISSUE TITLE
Remove `@google-cloud/functions-emulator`

### ISSUE THREAD

**Issue by grant** [firebase/firebase-tools#1214]
### Environment info

`firebase-tools@6.7.1` has an [optional dependency](https://github.com/firebase/firebase-tools/blob/master/package.json#L139) on [`@google-cloud/functions-emulator`](https://www.npmjs.com/package/@google-cloud/functions-emulator).
This should be removed and optionally be replaced with [`@google-cloud/functions-framework`](https://www.npmjs.com/package/@google-cloud/functions-framework).

This should be done by [Node 6 EOL: `2019-04-30`](https://github.com/nodejs/Release).

**firebase-tools:** `master`: (d67ecfadcc024763ea4efcba87849e6af7064d38)

**Platform:** All platforms

### Steps to reproduce

- View `package.json`: https://github.com/firebase/firebase-tools/blob/master/package.json#L139
- Observe a dependency on `@google-cloud/functions-emulator`.

### Expected behavior

- There should be no references to `@google-cloud/functions-emulator` in this codebase on `master`.
- Optionally, a replacement could be made, an internal fork of the repo, or other.

### Actual behavior

- [`package.json`](https://github.com/firebase/firebase-tools/blob/master/package.json#L139) has a dependency on this npm module.

CC: @thechenky, @abehaskins

**Comment by abehaskins** [comment]
This will be addressed when the new emulator tooling is merged in.
