### ISSUE TITLE
Functions not created or updated when using "deploy --only functions:funcName"

### ISSUE THREAD

**Issue by apphost-plugins** [firebase/firebase-tools#1219]
### Environment info

**firebase-tools:** 6.7.1

**Platform:** Windows

### Test case

Create a project with Firebase functions myFunc1, myFunc2, and myFunc3 in TypeScript.

### Steps to reproduce

Running `firebase deploy --only functions:myFunc1` does not build the TypeScript function source files. Instead, it only uploads `myFunc1` from the last time a build happened. Because of this, you can't create a new function or update an existing one by using the `--only functions:myFunc` syntax.

### Expected behavior

Running `firebase deploy --only functions` works as expected:
```=== Deploying to 'xxxxxxxxx'...

i  deploying functions
Running command: npm --prefix "%RESOURCE_DIR%" run lint

> functions@ lint C:\Users\xxxxxxxxxxx\functions
> tslint --project tsconfig.json

Running command: npm --prefix "%RESOURCE_DIR%" run build

> functions@ build C:\Users\xxxxxxxxxxx\functions
> tsc

+  functions: Finished running predeploy script.
i  functions: ensuring necessary APIs are enabled...
+  functions: all necessary APIs are enabled
i  functions: preparing functions directory for uploading...
i  functions: packaged functions (113.73 KB) for uploading
+  functions: functions folder uploaded successfully
i  functions: updating Node.js 8 function myFunc1(us-central1)...
i  functions: updating Node.js 8 function myFunc2(us-central1)...
i  functions: updating Node.js 8 function myFunc3(us-central1)...
+  functions[myFunc1(us-central1)]: Successful update operation.
+  functions[myFunc2(us-central1)]: Successful update operation.
+  functions[myFunc3(us-central1)]: Successful update operation.
```

The expected behavior for `firebase deploy --only functions:myFunc1` should include the same lint and build steps as above.

###  Actual behavior

Output of `firebase deploy --only functions:myFunc1`:

```
=== Deploying to 'xxxxxxxx'...

i  deploying functions
i  functions: ensuring necessary APIs are enabled...
+  functions: all necessary APIs are enabled
i  functions: preparing functions directory for uploading...
i  functions: packaged functions (113.73 KB) for uploading
+  functions: functions folder uploaded successfully
i  functions: current functions in project: MyFunc1(us-central1), MyFunc2(us-central1), MyFunc3(us-central1)
i  functions: uploading functions in project: MyFunc1(us-central1)
i  functions: updating Node.js 8 function MyFunc1(us-central1)...
+  functions[MyFunc1(us-central1)]: Successful update operation.
```

Note that it skips the pre-deploy steps specified in `firebase.json`. Because of this, the new version of `myFunc1` is not compiled, and only the previous version gets uploaded.

This issue might be related to #1210 . IMO, the bug is that the pre-deploy scripts in `firebase.json` aren't being triggered when using `firebase deploy --only functions:someFunc`

**Comment by p-barri** [comment]
+1

**Comment by bkendall** [comment]
First, Google OSS Bot, I've seen you yelling at everyone recently - I think you might need to be looked at.

Second - I think your intuition could be right on the money. And I think this should be fixed by #1217.

**Comment by Memeriaj** [comment]
Yep @bkendall is correct, #1217 should indeed fix this.  That will go out with our next release of the CLI.  I'm not exactly sure when that will be but at the very least I'll try to make sure that we do within a week.

**Comment by bkendall** [comment]
Version `v6.7.2` has been released with the fix!

**Comment by apphost-plugins** [comment]
Thanks! You guys do a great job with this repo
