### ISSUE TITLE
Command to create new Realtime Database instances

### ISSUE THREAD

**Issue by ryanpbrewster** [firebase/firebase-tools#1227]
Right now the recommended way of creating new Realtime Database instances is to manually navigate through the Firebase Console (https://firebase.google.com/docs/database/usage/sharding#create_multiple_instances). Can we add a command to the CLI tool to make this easier to automate?

**Comment by ryanpbrewster** [comment]
Rolled out as of v6.10.0

**Comment by govindrai** [comment]
@ryanpbrewster that command doesn't work. Throws an error such as: `Error: HTTP Error: 403, Mobile SDK API has not been used in project xyz before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/mobilesdk-pa.googleapis.com/overview?project=xyz then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.` There is no Mobile SDK API to enable.

**Comment by ryanpbrewster** [comment]
I'd double-check that your credentials are valid. Can you create Realtime Database instances through the console?

If none of that works, I'd suggest contacting Firebase support.

**Comment by govindrai** [comment]
@ryanpbrewster Contacted firebase support. It's a bug. There is a private API (the Mobile SDK API) exposed that users cannot get past. There is no timeline for the fix.
