### ISSUE TITLE
Attempting to deploy to unauthorized firebase gives unclear error

### ISSUE THREAD

**Issue by jeffbcross** [firebase/firebase-tools#123]
`$ firebase deploy some-app-i-am-not-authorized`

Causes an error `Error: Authentication required.`

The client is authenticated, but the logged-in user is not authorized on the target Firebase.

I know the issue seems like nit-picking, but we'd been re-arranging collaborators on projects, and had recently logged out of one account and in with another account in the CLI. The `Authentication required` message led us to believe the problem was that the login hadn't persisted, while the real problem was authorization.

**Comment by jwngr** [comment]
Thanks Jeff. You've got a fair nit-pick here. There should probably be different errors for users who are logged out versus users who do not have authorization for the resource. We will work on improving the error messaging here.

**Comment by paulirish** [comment]
I hit this same thing too. Was crazy confused.

**Comment by jwngr** [comment]
Gah, sorry! I took a crack at fixing it with #128.

**Comment by paulirish** [comment]
Nice! PR lgtm
