### ISSUE TITLE
ERROR : setup a Firebase project in the current directory

### ISSUE THREAD

**Issue by vasu096** [firebase/firebase-tools#1231]
Error: There was an error loading firebase.json:

Unexpected end of input at 19:23
      "**/node_modules
                                  ^
how to solve this firebase cli deployment error !!

**Comment by thechenky** [comment]
@vasu096 Please follow the template for the bug report. What you have right now makes it very difficult to debug.

**Comment by thechenky** [comment]
Please open a new issue and follow the template.
