### ISSUE TITLE
npm error on firebase deploy

### ISSUE THREAD

**Issue by Mark-Ammari** [firebase/firebase-tools#1235]
`npm ERR! code EPIPE
npm ERR! errno EPIPE
npm ERR! syscall write
npm ERR! EPIPE: broken pipe, write

npm ERR! A complete log of this run can be found in:
npm ERR! `

`0 info it worked if it ends with ok

1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',

1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',

1 verbose cli   'prefix',

1 verbose cli   '-g' ]

2 info using npm@6.4.1

3 info using node@v10.15.3

4 verbose exit [ 0, true ]

5 verbose stack Error: EPIPE: broken pipe, write

5 verbose stack     at Socket._write (internal/net.js:58:25)

5 verbose stack     at doWrite (_stream_writable.js:410:12)

5 verbose stack     at writeOrBuffer (_stream_writable.js:394:5)

5 verbose stack     at Socket.Writable.write (_stream_writable.js:294:11)

5 verbose stack     at reallyExit (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:138:20)

5 verbose stack     at exit (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:125:5)

5 verbose stack     at EventEmitter.errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:157:19)

5 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js:150:20)

5 verbose stack     at process._tickCallback (internal/process/next_tick.js:61:11)

6 verbose cwd C:\Users\MarkPC\Desktop\react-native-places-project\functions

7 verbose Windows_NT 10.0.17134

8 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program 
Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "prefix" "-g"

9 verbose node v10.15.3

10 verbose npm  v6.4.1

11 error code EPIPE

12 error errno EPIPE

13 error syscall write

14 error EPIPE: broken pipe, write

15 verbose exit [ 1, true ]
`

**Comment by bkendall** [comment]
Please open a new issue and follow the issue template.
