### ISSUE TITLE
Http Error 503

### ISSUE THREAD

**Issue by arivas191** [firebase/firebase-tools#1245]
I use Firebase to sign in with Google or Microsoft to my web app but right now, if I try to use either for the sign in, I get an Http Error 503 (Backend is unhealthy) from Firebase, which has never happened before. From what I've been reading, this occurs when there's a problem with one of Firebase's servers, but I checked the firebase status page and no outages are reported.

Does anyone have any information regarding if Firebase is experiencing some outages right now? I assume the status page isn't always up to date. Since this is only happening for the sign in, I guess this will be an outage in the Authentication section on Firebase.

**Comment by bkendall** [comment]
If you're still seeing these issues, I would recommend reaching out to [Firebase Support](https://firebase.google.com/support) as they'll be able to help get you the information you're looking for. If I find out anything in particular, I'll follow up here, but Firebase Support is going to be the place to go for questions like this. :)

Thanks!
