### ISSUE TITLE
firebase login --help doesn't mention the `login:ci` API

### ISSUE THREAD

**Issue by jelbourn** [firebase/firebase-tools#126]
You can run `firebase login:ci` to generate a CLI auth token, but the `--help` doesn't mention this.

(it's also not mentioned in the [docs](https://www.firebase.com/docs/hosting/command-line-tool.html))

**Comment by brendanlim** [comment]
This is fixed in the 3.0.0 release and the [documentation](https://firebase.google.com/docs/cli/#source_control_and_project_aliases) has been updated.
