### ISSUE TITLE
Bug/question: Could not parse auth token when package used as a module

### ISSUE THREAD

**Issue by zarko-tg** [firebase/firebase-tools#127]
Here's the thing:

I've obtained a token once using a globally installed firebase-tools using
```
$ firebase login:ci
```
that I would like to use in a small Node.js command line app on my own.
This app in question is installing a local firebase-tools requiring the package and going straight to get some data from my remote Firebase. As in:
```
var firebase = require( 'firebase-tools' );

firebase.data.get( 'some_path', {
  token    : 'MY-PREGENERATED TOKEN',
  firebase : 'some-firebase-app',
  output   : 'some-output.json'
}
```

This fails with a "FirebaseError: Could not parse auth token."

Is this a misuse / uninformed use of the package/tool API, or a bug?
Do I need to log in using the module programmatically or something before making any database calls?

**Comment by mbleigh** [comment]
Ah, I see what's happening here. The `token` in `data:*` commands is actually a Firebase Database authorization token. You should be able to call the above code by going to your Firebase project console and pasting in one of the Database secrets.

**Comment by sethladd** [comment]
Curious, why is the token that comes from `login:ci` different than what the `auth` parameter expects?

I admit, I lost a lot of time until I found this post. I kept trying to use the token from `login:ci`. We might want to update the Firebase docs to specify what a "Firebase Database authorization token" is, and link/refer to "Database secrets" as being the same thing.

Thanks for the note here. Solved my problem! :)

**Comment by jwngr** [comment]
The token returned from `login:ci` is used to interact with the Firebase website / CLI backend. It is a completely separate system from the Firebase realtime database. The realtime database speaks in database secrets and JWTs. The Firebase website / CLI backend speaks in the tokens returned by like `login:ci`. We all realize this is kinda confusing and it's unfortunately just a historical idiosyncrasy of our architecture. This is really the only place where Firebase developers interact with these tokens directly. Everywhere else they are considered internal workings of our system and you never see them. Some day they will go away, but that day is unfortunately not today.

Hopefully that clears things up a bit more. Sorry you lost some time on this. We can see what we can do to improve the docs. What docs exactly are you referring to with the phrase "Firebase Database authorization token"? I wasn't able to find them in this repo's README, so I assume it is somewhere in our website, maybe?

**Comment by sethladd** [comment]
> It is a completely separate system from the Firebase realtime database

Ah, ok. I think we're overloading "token" too much, then :)  Thanks for the clarification.

> What docs exactly are you referring to

Wrapper APIs (ruby, dart, e.g.) that take an `auth` param in their constructors. I will update the Dart wrapper with more API docs to clarify what `auth` is.

Someone might want to update the docs for https://github.com/oscardelben/firebase-ruby and add some API docs for Client's auth param (https://github.com/oscardelben/firebase-ruby/blob/master/lib/firebase.rb)

At https://github.com/oscardelben/firebase-ruby/blob/master/README.md it's called "secret_key", but still doesn't seem to be clearly defined (not sure what "secret key" is).

Thanks!

**Comment by jwngr** [comment]
Thanks @sethladd. Both of those projects are third party libs which probably explains the non-standard terminology they use. FYI that `secret_key` refers to the secrets in the **Secrets** tab of your Firebase app dashboard.
