### ISSUE TITLE
Problem getting data from firebase

### ISSUE THREAD

**Issue by tiagosk81989** [firebase/firebase-tools#1271]
I'm having problem getting boolean value from firebase database to my esp8266, that change the relay state. 

I think the problem is in this section of loop ()

  bool lampValue2 = Firebase.getBool(firebaseData, "/lampada2");
  digitalWrite(LAMP_PIN2, lampValue2 ? LOW : HIGH);
  
  bool lampValue3 = Firebase.getBool(firebaseData, "/lampada3");
  digitalWrite(LAMP_PIN3, lampValue3 ? LOW : HIGH);

  bool lampValue4 = Firebase.getBool(firebaseData, "/lampada4");
  digitalWrite(LAMP_PIN4, lampValue4 ? LOW : HIGH);

Relay stays in 0 state. 
Sending data to firebase works fine, the problem is about getting data

**Comment by abeisgoat** [comment]
This is an issue for [firebase-arduino](https://github.com/FirebaseExtended/firebase-arduino) or StackOverflow :)
