### ISSUE TITLE
Invalid value for config firebase.databaseURL: undefined

### ISSUE THREAD

**Issue by AmichayMiara** [firebase/firebase-tools#1276]
### [REQUIRED] Environment info

new version didn't help.

**firebase-tools:**

![1 1](https://user-images.githubusercontent.com/44358624/57581978-048ad780-74c8-11e9-8837-626ff8d0365a.png)

**Platform:** Windows

### [REQUIRED] Test case
want to run firebase deploy functions
this solution didn't help: https://stackoverflow.com/questions/55767623/why-is-google-cloud-functions-throwing-a-invalid-value-for-config-firebase-data

### [REQUIRED] Steps to reproduce

run firebase deploy  --only=functions:myFunction

`import 'firebase-functions';
import * as admin from "firebase-admin";

const serviceAccount = require('../../service-account.json');

admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
  databaseURL: 'https://myProject.firebaseio.com'
});

export const ref = admin.database().ref();`

### [REQUIRED] Expected behavior

successful deploy of firebase functions.

### [REQUIRED] Actual behavior

![2](https://user-images.githubusercontent.com/44358624/57580816-1fa11b80-74b7-11e9-92a0-fbd8bff39b84.png)

**Comment by thechenky** [comment]
Can you run `firebase deploy --only=functions:myFunction --debug` and paste the output?

**Comment by thechenky** [comment]
@AmichayMiara great, happy to see it's working for you now! Would you mind posting the output that led you to deduce it was a typescript update issue to help anyone else having the same issue?

**Comment by AmichayMiara** [comment]
Just colleague good advice

**Comment by AmichayMiara** [comment]
even in latest version.
Solution: it's because of **bad internet connection**. :)
