### ISSUE TITLE
Emulator fails on "firebase init" template with firebase-admin error. 

### ISSUE THREAD

**Issue by CodingDoug** [firebase/firebase-tools#1278]
### [REQUIRED] Environment info

Firebase CLI: 6.9.2
Platform: macos, Windows

(Problem does not exist with CLI 6.8.0.)

### [REQUIRED] Test case

Emulating the given HTTP trigger in a new project.

### [REQUIRED] Steps to reproduce

1. `firebase init` a new project space for Functions
1. Take all the defaults, choose JavaScript
1. Uncomment the code in index.js
1. Emulate with either `firebase emulators:start --only functions` or `firebase serve --only functions`
1. Access the given URL

### [REQUIRED] Expected behavior

"Hello from Firebase!"

### [REQUIRED] Actual behavior

See the message on emulator output:
```
⚠  The Firebase Admin module has not been initialized early enough. Make sure you run "admin.initializeApp()" outside of any function and at the top of your code
```

The function will time out and disconnect as well.  E.g:

```
curl: (52) Empty reply from server
```

**Comment by ZangievM** [comment]
same issue

**Comment by jgutierro** [comment]
same here

**Comment by lionel95200x** [comment]
Add this in your index.ts file

```
      const admin = require('firebase-admin')

    try {
       admin.initializeApp()
     } catch (error) {
       //TODO: ignoring until firebase-functions fix released
    }

```

**Comment by abeisgoat** [comment]
For everyone on this thread, are you all experiencing this on Windows or on other platforms as well?

**Comment by ZangievM** [comment]
Windows for me

**Comment by CodingDoug** [comment]
Original issue states macos, Windows.

**Comment by abeisgoat** [comment]
Gotcha, thanks missed that!

**Comment by MateusZitelli** [comment]
I am facing that on Linux.
```
uname -a 
Linux onda 5.0.9-2-MANJARO #1 SMP PREEMPT Sun Apr 21 07:11:08 UTC 2019 x86_64 GNU/Linux
```

**Comment by JorgeReyniers** [comment]
Windows

**Comment by jbraithwaite** [comment]
Firebase: 6.9.2
OS: macOS 10.14.3

**Comment by clm-a** [comment]
Same here with Linux (Debian Stretch)
Firebase: 6.9.2
OS: Linux 4.19.26 x86_64

(setup is OK with @lionel95200x workaround)

**Comment by abeisgoat** [comment]
Thanks for the help, working on a fix which should be merged in today.
