### ISSUE TITLE
HTTP request with Express app fails GET

### ISSUE THREAD

**Issue by codeekage** [firebase/firebase-tools#1281]
### [REQUIRED] Environment info

**firebase-tools:** v 6.9.2
**nodejs** v10.15.3
**npm** v6.9.0

**Platform:** Ubuntu

### [REQUIRED] Test case

**index.ts**
```javascript
import * as functions from 'firebase-functions';
import { app } from './api/hello.api';

export const api = functions.https.onRequest(app)
```
**./api/app.ts**

```javascript
import * as cors from 'cors'
import * as express from 'express'

export const app = express()
app.use(cors())
app.get('/', (req, res)=> {
    try{
        res.send("Hello")
    }catch(error){
        res.send(error)
    }
})
```
### [REQUIRED] Steps to reproduce

```shell
npm run serve
```

### [REQUIRED] Expected behaviour

- Execute GET request successfully

### [REQUIRED] Actual behavior

- Fails on `localhost` results to:
   - `Cannot GET /<firebase-app-name>/us-central1/api`
- no ERROR in console and debug file.
- Works perfectly on deployment

**Comment by abeisgoat** [comment]
Hmm, I wonder if this has to do with stacking multiple `cors()` (we pull it in already for Callable requests). I'll investigate today, thanks for the well written report!

**Comment by samtstern** [comment]
@abeisgoat I bet we just have not done a good job routing requests to function subpaths

**Comment by abeisgoat** [comment]
Fix is merged in, please re-open if you're still experiencing this once `6.9.3` is out.
