### ISSUE TITLE
Firestore emulator download often fails in travis-ci

### ISSUE THREAD

**Issue by JakeHedman** [firebase/firebase-tools#1282]
Not sure if this is a problem with travis-ci or with firebase-tools, but installing the firestore emulator in travis-ci often fails.

Travis config: https://github.com/JakeHedman/firestore-emulator-travis/blob/master/.travis.yml
Travis logs: (8/11 failed) https://travis-ci.org/JakeHedman/firestore-emulator-travis/builds/531687641

### [REQUIRED] Environment info

**firebase-tools:** 6.9.2

**Platform:** Ubuntu 14.04.5 LTS (travis ci)

### [REQUIRED] Test case

In .travis.yml:
```
script:
  firebase setup:emulators:firestore
```

### [REQUIRED] Steps to reproduce
Try to install the firestore emulator in travis

### [REQUIRED] Expected behavior
It should download

### [REQUIRED] Actual behavior
Fails with "Error: download failed, expected 56840576 bytes but got 56836096"

**Comment by JakeHedman** [comment]
Workaround:
```yaml
  - until firebase setup:emulators:firestore; do echo Retrying firestore setup...; done
```

**Comment by abeisgoat** [comment]
Huh strange, thanks for the report.

**Comment by toddpi314** [comment]
Retry on travis almost always fixes, but man, it takes 4 or 5 tries.

**Comment by ryanpbrewster** [comment]
Version 6.10.0 just released and should be much more reliable. Let me know if you still get flaky downloads on the latest release.

**Comment by waltz** [comment]
I'm still seeing this issue on CircleCI with package version 8.7.0. Any ideas why I might be seeing this?
