### ISSUE TITLE
Firestore emulator sending incorrect event payloads to Functions emulator

### ISSUE THREAD

**Issue by samtstern** [firebase/firebase-tools#1288]
I just ran a real Cloud Function (non-Firebase) triggered on `onWrite` for the document `foo/bar`.  

I created the document (no previous data) and logged out the two arguments to the function and got this:

**context**
```js
{
    eventId: "6e7a9aae-5e22-4414-abaf-cb6b0a3363a2-0",
    eventType: "providers/cloud.firestore/eventTypes/document.write",
    notSupported: {},
    resource: "projects/fir-dumpster/databases/(default)/documents/foo/bar",
    timestamp: "2019-05-14T01:49:26.587519Z",
}
```

**data**
```js
{
    oldValue: {},
    updateMask: {},
    value: {
      createTime: "2019-05-14T01:49:26.587519Z",
      fields: {
        hey: {
          stringValue: "now",
        },
      },
      name: "projects/fir-dumpster/databases/(default)/documents/foo/bar",
      updateTime: "2019-05-14T01:49:26.587519Z",
    },
}
```

However if I do the same thing in the emulator suite I get:

**context**
```js
{
  "eventId": "68ded781-de59-4adb-aff2-a8b6597a9725",
  "timestamp": "2019-05-14T01:59:17.900Z",
  "eventType": "providers/cloud.firestore/eventTypes/document.write",
  "resource": {
    "name": "projects/fir-dumpster/databases/(default)/documents/foo/bar",
    "service": "firestore.googleapis.com"
  }
}
```

**data** 
```js
{
  "value": {
    "name": "projects/fir-dumpster/databases/(default)/documents/foo/bar",
    "fields": {
      "hello": {
        "stringValue": "world"
      }
    },
    "createTime": "2019-05-14T01:59:17.900Z",
    "updateTime": "2019-05-14T01:59:17.900Z"
  },
  "updateMask": {}
}
```

The difference is that in the emulator we get `context.resource` is an Object and in prod we get `context.resource` is a String.

**Comment by samtstern** [comment]
cc @abeisgoat

**Comment by samtstern** [comment]
Note that I am working around this in https://github.com/firebase/firebase-tools/pull/1260

**Comment by samtstern** [comment]
I think there is something really funky going on here ... I can't find a single solution for `resource` assumptions that works for both RTDB and Firestore.

**Comment by samtstern** [comment]
I checked for RTDB in prod and I got:

**context**
```
{"eventType":"providers/google.firebase.database/eventTypes/ref.write","params":{},"auth":{"admin":true},"resource":"projects/_/instances/fir-dumpster/refs/foo/bar","timestamp":"2019-05-14T18:49:56.923Z","eventId":"BK6VnFw4oWjclYm+dJ1BE528dak="}
```
**data** 
```
{"data":null,"delta":{"hello":"world"}}
```

So it seems like `resource` should definitely be a `string`

**Comment by samtstern** [comment]
https://github.com/firebase/firebase-functions/blob/18c01cbdc25d8f4fccb8847f6a4be86b6c7d4960/src/cloud-functions.ts#L47
```ts
/** Wire format for an event
 * @internal
 */
export interface Event {
  context: {
    eventId: string;
    timestamp: string;
    eventType: string;
    resource: Resource;
  };
  data: any;
}
```

https://github.com/firebase/firebase-functions/blob/18c01cbdc25d8f4fccb8847f6a4be86b6c7d4960/src/cloud-functions.ts#L160
```
/** Resource is a standard format for defining a resource (google.rpc.context.AttributeContext.Resource).
 * In Cloud Functions, it is the resource that triggered the function - such as a storage bucket.
 */
export interface Resource {
  service: string;
  name: string;
  type?: string;
  labels?: { [tag: string]: string };
}
```

**Comment by samtstern** [comment]
Ah this line is interesting:
https://github.com/firebase/firebase-functions/blob/18c01cbdc25d8f4fccb8847f6a4be86b6c7d4960/src/cloud-functions.ts#L257

```
    if (legacyEventType && context.eventType === legacyEventType) {
      // v1beta1 event flow has different format for context, transform them to new format.
      context.eventType = provider + '.' + eventType;
      context.resource = {
        service: service,
        name: context.resource,
      };
    }
```

**Comment by abeisgoat** [comment]
Yeah I think there's definitely multiple formats going around, I guess we just adhere to the newest?

**Comment by samtstern** [comment]
Ok I have this in a place where everything works, but I feel like it *shouldnt* work and that's what scares me.

**Comment by samtstern** [comment]
Here's what a Firestore update data payload looks like:
```js
 {
  "oldValue": {},
  "updateMask": {},
  "value": {
    "createTime": "2019-05-14T23:04:30.459119Z",
    "fields": {
      "new": {
        "stringValue": "doc"
      }
    },
    "name": "projects/fir-dumpster/databases/(default)/documents/foo/bar",
    "updateTime": "2019-05-14T23:04:30.459119Z"
  }
}
```

**Comment by laurenzlong** [comment]
Basically there are 2 versions of EventFlow: the event delivery system, some event providers have migrate and others have not, that's why there are inconsistencies in "resource" format. 

To make things easier for our customers, the firebase-functions SDK converts everything into the new format. However if you create functions without the firebase-functions SDK, there are variations.

**Comment by laurenzlong** [comment]
The firebase-functions SDK also does transformations on the data payload of Firestore-triggered functions and turns raw JSON payload (which includes fields like `oldValue` and `updateMask`) into an easier to use Firestore snapshot. See https://github.com/firebase/firebase-functions/blob/master/src/providers/firestore.ts#L145-L180

**Comment by abeisgoat** [comment]
@samtstern Is this still relevant after your merge yesterday?

**Comment by samtstern** [comment]
@abeisgoat yes this will be fixed when @yuchenshi moves the emulator to `v1beta1` protos.

**Comment by mhuebert** [comment]
I found this issue via https://stackoverflow.com/questions/56587770/firebase-functionsshell-onwrite-property-undefined - but I'm not sure if it is precisely the same issue, or not, so making a quick note here.

I am not able to run RTDB functions in the shell, `context` is undefined on this line:
```
if (legacyEventType && context.eventType === legacyEventType) {
```
(see https://github.com/firebase/firebase-functions/blob/v3.0.1/src/cloud-functions.ts#L243)

**Comment by samtstern** [comment]
@mhuebert if you're using firebase-tools 7+ and firebase-functions 3+ that is a known issue at the moment.  Downloading either the CLI to 6.11.0 or firebase-functions to 2.3.1 will solve your issue for now.
