### ISSUE TITLE
Can't update to firebase-tools v2.0.0

### ISSUE THREAD

**Issue by chetstone** [firebase/firebase-tools#129]
When I run firebase deploy it tells me to upgrade to v2 by running: `npm update -g firebase-tools`. When I do that it doesn't really update:
```
$ firebase --version

Firebase Command Line Tools
Version 1.1.5
https://www.firebase.com
```
I've also tried `npm uninstall -g firebase-tools; npm install -g firebase-tools@v2.0.0`
and other combinations of invocations. No matter what I do I still end up with v 1.1.5

I'm using npm version 3.8.2. Any suggestions?

**Comment by mbleigh** [comment]
Can you try running:

```
which firebase
which npm
which node
npm install -g firebase-tools@^2.2.1
firebase --version
```

And paste the entire output of all of those commands? It seems likely that the `firebase` command is being picked up from a `$PATH` that isn't where your NPM is installing things.

**Comment by chetstone** [comment]
Thanks. It seems the shell is not using the version it says it is.. After doing that sequence of commands which seem to be installing the new version (full report below) I get:

$ firebase --version

Firebase Command Line Tools
Version 1.1.5
https://www.firebase.com

$ which firebase
/Users/chet/.nvm/versions/node/v4.3.1/bin/firebase
$ /Users/chet/.nvm/versions/node/v4.3.1/bin/firebase --version
2.2.1

Really weird. When I invoke it with the full path it is the correct version. Never seen anything like that before. 

It seems the shell is somehow "stuck" on the old version. Starting up a new shell fixes it. 




--------

(15:09:33)[kurukulle: firebase]$ which firebase
/Users/chet/.nvm/versions/node/v4.3.1/bin/firebase
(16:35:41)[kurukulle: firebase]$ which npm
/Users/chet/.nvm/versions/node/v4.3.1/bin/npm
(16:35:49)[kurukulle: firebase]$ which node
/Users/chet/.nvm/versions/node/v4.3.1/bin/node
(16:35:52)[kurukulle: firebase]$ npm install -g firebase-tools@^2.2.1
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
/Users/chet/.nvm/versions/node/v4.3.1/bin/firebase -> /Users/chet/.nvm/versions/node/v4.3.1/lib/node_modules/firebase-tools/bin/firebase
- abbrev@1.0.7 node_modules/firebase-tools/node_modules/abbrev
- amp-is-object@1.0.1 node_modules/firebase-tools/node_modules/amp-is-object
- amp-is-string@1.0.1 node_modules/firebase-tools/node_modules/amp-is-string
- arr-flatten@1.0.1 node_modules/firebase-tools/node_modules/arr-flatten
- arr-diff@2.0.0 node_modules/firebase-tools/node_modules/arr-diff
- array-unique@0.2.1 node_modules/firebase-tools/node_modules/array-unique
- arrify@1.0.1 node_modules/firebase-tools/node_modules/arrify
- async-each@1.0.0 node_modules/firebase-tools/node_modules/async-each
- binary-extensions@1.4.0 node_modules/firebase-tools/node_modules/binary-extensions
- bytes@1.0.0 node_modules/firebase-tools/node_modules/body-parser/node_modules/bytes
- depd@0.4.5 node_modules/firebase-tools/node_modules/body-parser/node_modules/depd
- ee-first@1.0.5 node_modules/firebase-tools/node_modules/body-parser/node_modules/ee-first
- mime-db@1.12.0 node_modules/firebase-tools/node_modules/body-parser/node_modules/mime-db
- mime-types@2.0.14 node_modules/firebase-tools/node_modules/body-parser/node_modules/mime-types
- on-finished@2.1.0 node_modules/firebase-tools/node_modules/body-parser/node_modules/on-finished
- qs@2.2.4 node_modules/firebase-tools/node_modules/body-parser/node_modules/qs
- async@0.9.2 node_modules/firebase-tools/node_modules/bundles/node_modules/async
- bundles@2.0.0 node_modules/firebase-tools/node_modules/bundles
- callsites@0.2.0 node_modules/firebase-tools/node_modules/callsites
- caller-path@0.1.0 node_modules/firebase-tools/node_modules/caller-path
- connect-livereload@0.5.4 node_modules/firebase-tools/node_modules/connect-livereload
- content-disposition@0.5.1 node_modules/firebase-tools/node_modules/content-disposition
- content-type@1.0.1 node_modules/firebase-tools/node_modules/content-type
- cookie@0.1.5 node_modules/firebase-tools/node_modules/cookie
- cookie-signature@1.0.6 node_modules/firebase-tools/node_modules/cookie-signature
- etag@1.7.0 node_modules/firebase-tools/node_modules/etag
- negotiator@0.5.3 node_modules/firebase-tools/node_modules/express/node_modules/negotiator
- accepts@1.2.13 node_modules/firebase-tools/node_modules/express/node_modules/accepts
- path-to-regexp@0.1.7 node_modules/firebase-tools/node_modules/express/node_modules/path-to-regexp
- qs@4.0.0 node_modules/firebase-tools/node_modules/express/node_modules/qs
- vary@1.0.1 node_modules/firebase-tools/node_modules/express/node_modules/vary
- ansi-styles@0.2.0 node_modules/firebase-tools/node_modules/feedback/node_modules/ansi-styles
- filename-regex@2.0.0 node_modules/firebase-tools/node_modules/filename-regex
- firstkey@0.1.0 node_modules/firebase-tools/node_modules/firstkey
- for-in@0.1.5 node_modules/firebase-tools/node_modules/for-in
- for-own@0.1.4 node_modules/firebase-tools/node_modules/for-own
- forwarded@0.1.0 node_modules/firebase-tools/node_modules/forwarded
- fresh@0.3.0 node_modules/firebase-tools/node_modules/fresh
- ansi@0.3.1 node_modules/firebase-tools/node_modules/fsevents/node_modules/ansi
- ansi-regex@2.0.0 node_modules/firebase-tools/node_modules/fsevents/node_modules/ansi-regex
- ansi-styles@2.2.1 node_modules/firebase-tools/node_modules/fsevents/node_modules/ansi-styles
- asn1@0.2.3 node_modules/firebase-tools/node_modules/fsevents/node_modules/asn1
- assert-plus@0.2.0 node_modules/firebase-tools/node_modules/fsevents/node_modules/assert-plus
- async@1.5.2 node_modules/firebase-tools/node_modules/fsevents/node_modules/async
- aws-sign2@0.6.0 node_modules/firebase-tools/node_modules/fsevents/node_modules/aws-sign2
- pseudomap@1.0.2 node_modules/firebase-tools/node_modules/fsevents/node_modules/aws4/node_modules/lru-cache/node_modules/pseudomap
- yallist@2.0.0 node_modules/firebase-tools/node_modules/fsevents/node_modules/aws4/node_modules/lru-cache/node_modules/yallist
- lru-cache@4.0.1 node_modules/firebase-tools/node_modules/fsevents/node_modules/aws4/node_modules/lru-cache
- aws4@1.3.2 node_modules/firebase-tools/node_modules/fsevents/node_modules/aws4
- caseless@0.11.0 node_modules/firebase-tools/node_modules/fsevents/node_modules/caseless
- core-util-is@1.0.2 node_modules/firebase-tools/node_modules/fsevents/node_modules/core-util-is
- assert-plus@1.0.0 node_modules/firebase-tools/node_modules/fsevents/node_modules/dashdash/node_modules/assert-plus
- dashdash@1.13.0 node_modules/firebase-tools/node_modules/fsevents/node_modules/dashdash
- deep-extend@0.4.1 node_modules/firebase-tools/node_modules/fsevents/node_modules/deep-extend
- delayed-stream@1.0.0 node_modules/firebase-tools/node_modules/fsevents/node_modules/delayed-stream
- combined-stream@1.0.5 node_modules/firebase-tools/node_modules/fsevents/node_modules/combined-stream
- delegates@1.0.0 node_modules/firebase-tools/node_modules/fsevents/node_modules/delegates
- escape-string-regexp@1.0.5 node_modules/firebase-tools/node_modules/fsevents/node_modules/escape-string-regexp
- extend@3.0.0 node_modules/firebase-tools/node_modules/fsevents/node_modules/extend
- extsprintf@1.0.2 node_modules/firebase-tools/node_modules/fsevents/node_modules/extsprintf
- forever-agent@0.6.1 node_modules/firebase-tools/node_modules/fsevents/node_modules/forever-agent
- balanced-match@0.3.0 node_modules/firebase-tools/node_modules/fsevents/node_modules/fstream-ignore/node_modules/minimatch/node_modules/brace-expansion/node_modules/balanced-match
- concat-map@0.0.1 node_modules/firebase-tools/node_modules/fsevents/node_modules/fstream-ignore/node_modules/minimatch/node_modules/brace-expansion/node_modules/concat-map
- brace-expansion@1.1.3 node_modules/firebase-tools/node_modules/fsevents/node_modules/fstream-ignore/node_modules/minimatch/node_modules/brace-expansion
- minimatch@3.0.0 node_modules/firebase-tools/node_modules/fsevents/node_modules/fstream-ignore/node_modules/minimatch
- generate-function@2.0.0 node_modules/firebase-tools/node_modules/fsevents/node_modules/generate-function
- graceful-fs@4.1.3 node_modules/firebase-tools/node_modules/fsevents/node_modules/graceful-fs
- graceful-readlink@1.0.1 node_modules/firebase-tools/node_modules/fsevents/node_modules/graceful-readlink
- commander@2.9.0 node_modules/firebase-tools/node_modules/fsevents/node_modules/commander
- has-ansi@2.0.0 node_modules/firebase-tools/node_modules/fsevents/node_modules/has-ansi
- has-unicode@2.0.0 node_modules/firebase-tools/node_modules/fsevents/node_modules/has-unicode
- hoek@2.16.3 node_modules/firebase-tools/node_modules/fsevents/node_modules/hoek
- boom@2.10.1 node_modules/firebase-tools/node_modules/fsevents/node_modules/boom
- cryptiles@2.0.5 node_modules/firebase-tools/node_modules/fsevents/node_modules/cryptiles
- inherits@2.0.1 node_modules/firebase-tools/node_modules/fsevents/node_modules/inherits
- block-stream@0.0.8 node_modules/firebase-tools/node_modules/fsevents/node_modules/block-stream
- ini@1.3.4 node_modules/firebase-tools/node_modules/fsevents/node_modules/ini
- is-property@1.0.2 node_modules/firebase-tools/node_modules/fsevents/node_modules/is-property
- generate-object-property@1.2.0 node_modules/firebase-tools/node_modules/fsevents/node_modules/generate-object-property
- is-typedarray@1.0.0 node_modules/firebase-tools/node_modules/fsevents/node_modules/is-typedarray
- isarray@1.0.0 node_modules/firebase-tools/node_modules/fsevents/node_modules/isarray
- isstream@0.1.2 node_modules/firebase-tools/node_modules/fsevents/node_modules/isstream
- jsbn@0.1.0 node_modules/firebase-tools/node_modules/fsevents/node_modules/jsbn
- jodid25519@1.0.2 node_modules/firebase-tools/node_modules/fsevents/node_modules/jodid25519
- ecc-jsbn@0.1.1 node_modules/firebase-tools/node_modules/fsevents/node_modules/ecc-jsbn
- json-schema@0.2.2 node_modules/firebase-tools/node_modules/fsevents/node_modules/json-schema
- json-stringify-safe@5.0.1 node_modules/firebase-tools/node_modules/fsevents/node_modules/json-stringify-safe
- jsonpointer@2.0.0 node_modules/firebase-tools/node_modules/fsevents/node_modules/jsonpointer
- lodash.tostring@4.1.2 node_modules/firebase-tools/node_modules/fsevents/node_modules/lodash.tostring
- lodash.repeat@4.0.0 node_modules/firebase-tools/node_modules/fsevents/node_modules/lodash.repeat
- lodash.padstart@4.2.0 node_modules/firebase-tools/node_modules/fsevents/node_modules/lodash.padstart
- lodash.padend@4.2.0 node_modules/firebase-tools/node_modules/fsevents/node_modules/lodash.padend
- lodash.pad@4.1.0 node_modules/firebase-tools/node_modules/fsevents/node_modules/lodash.pad
- gauge@1.2.7 node_modules/firebase-tools/node_modules/fsevents/node_modules/gauge
- mime-db@1.22.0 node_modules/firebase-tools/node_modules/fsevents/node_modules/mime-db
- mime-types@2.1.10 node_modules/firebase-tools/node_modules/fsevents/node_modules/mime-types
- form-data@1.0.0-rc4 node_modules/firebase-tools/node_modules/fsevents/node_modules/form-data
- minimist@0.0.8 node_modules/firebase-tools/node_modules/fsevents/node_modules/minimist
- mkdirp@0.5.1 node_modules/firebase-tools/node_modules/fsevents/node_modules/mkdirp
- ms@0.7.1 node_modules/firebase-tools/node_modules/fsevents/node_modules/ms
- debug@2.2.0 node_modules/firebase-tools/node_modules/fsevents/node_modules/debug
- abbrev@1.0.7 node_modules/firebase-tools/node_modules/fsevents/node_modules/node-pre-gyp/node_modules/nopt/node_modules/abbrev
- nopt@3.0.6 node_modules/firebase-tools/node_modules/fsevents/node_modules/node-pre-gyp/node_modules/nopt
- node-uuid@1.4.7 node_modules/firebase-tools/node_modules/fsevents/node_modules/node-uuid
- oauth-sign@0.8.1 node_modules/firebase-tools/node_modules/fsevents/node_modules/oauth-sign
- pinkie@2.0.4 node_modules/firebase-tools/node_modules/fsevents/node_modules/pinkie
- pinkie-promise@2.0.0 node_modules/firebase-tools/node_modules/fsevents/node_modules/pinkie-promise
- process-nextick-args@1.0.6 node_modules/firebase-tools/node_modules/fsevents/node_modules/process-nextick-args
- qs@6.0.2 node_modules/firebase-tools/node_modules/fsevents/node_modules/qs
- minimist@1.2.0 node_modules/firebase-tools/node_modules/fsevents/node_modules/rc/node_modules/minimist
- wrappy@1.0.1 node_modules/firebase-tools/node_modules/fsevents/node_modules/rimraf/node_modules/glob/node_modules/inflight/node_modules/wrappy
- inherits@2.0.1 node_modules/firebase-tools/node_modules/fsevents/node_modules/rimraf/node_modules/glob/node_modules/inherits
- balanced-match@0.3.0 node_modules/firebase-tools/node_modules/fsevents/node_modules/rimraf/node_modules/glob/node_modules/minimatch/node_modules/brace-expansion/node_modules/balanced-match
- concat-map@0.0.1 node_modules/firebase-tools/node_modules/fsevents/node_modules/rimraf/node_modules/glob/node_modules/minimatch/node_modules/brace-expansion/node_modules/concat-map
- brace-expansion@1.1.3 node_modules/firebase-tools/node_modules/fsevents/node_modules/rimraf/node_modules/glob/node_modules/minimatch/node_modules/brace-expansion
- minimatch@3.0.0 node_modules/firebase-tools/node_modules/fsevents/node_modules/rimraf/node_modules/glob/node_modules/minimatch
- wrappy@1.0.1 node_modules/firebase-tools/node_modules/fsevents/node_modules/rimraf/node_modules/glob/node_modules/once/node_modules/wrappy
- once@1.3.3 node_modules/firebase-tools/node_modules/fsevents/node_modules/rimraf/node_modules/glob/node_modules/once
- inflight@1.0.4 node_modules/firebase-tools/node_modules/fsevents/node_modules/rimraf/node_modules/glob/node_modules/inflight
- path-is-absolute@1.0.0 node_modules/firebase-tools/node_modules/fsevents/node_modules/rimraf/node_modules/glob/node_modules/path-is-absolute
- glob@7.0.3 node_modules/firebase-tools/node_modules/fsevents/node_modules/rimraf/node_modules/glob
- rimraf@2.5.2 node_modules/firebase-tools/node_modules/fsevents/node_modules/rimraf
- fstream@1.0.8 node_modules/firebase-tools/node_modules/fsevents/node_modules/fstream
- fstream-ignore@1.0.3 node_modules/firebase-tools/node_modules/fsevents/node_modules/fstream-ignore
- semver@5.1.0 node_modules/firebase-tools/node_modules/fsevents/node_modules/semver
- sntp@1.0.9 node_modules/firebase-tools/node_modules/fsevents/node_modules/sntp
- hawk@3.1.3 node_modules/firebase-tools/node_modules/fsevents/node_modules/hawk
- string_decoder@0.10.31 node_modules/firebase-tools/node_modules/fsevents/node_modules/string_decoder
- stringstream@0.0.5 node_modules/firebase-tools/node_modules/fsevents/node_modules/stringstream
- strip-ansi@3.0.1 node_modules/firebase-tools/node_modules/fsevents/node_modules/strip-ansi
- strip-json-comments@1.0.4 node_modules/firebase-tools/node_modules/fsevents/node_modules/strip-json-comments
- rc@1.1.6 node_modules/firebase-tools/node_modules/fsevents/node_modules/rc
- supports-color@2.0.0 node_modules/firebase-tools/node_modules/fsevents/node_modules/supports-color
- chalk@1.1.3 node_modules/firebase-tools/node_modules/fsevents/node_modules/chalk
- tar@2.2.1 node_modules/firebase-tools/node_modules/fsevents/node_modules/tar
- tough-cookie@2.2.2 node_modules/firebase-tools/node_modules/fsevents/node_modules/tough-cookie
- tunnel-agent@0.4.2 node_modules/firebase-tools/node_modules/fsevents/node_modules/tunnel-agent
- tweetnacl@0.14.3 node_modules/firebase-tools/node_modules/fsevents/node_modules/tweetnacl
- sshpk@1.7.4 node_modules/firebase-tools/node_modules/fsevents/node_modules/sshpk
- uid-number@0.0.6 node_modules/firebase-tools/node_modules/fsevents/node_modules/uid-number
- util-deprecate@1.0.2 node_modules/firebase-tools/node_modules/fsevents/node_modules/util-deprecate
- readable-stream@2.0.6 node_modules/firebase-tools/node_modules/fsevents/node_modules/readable-stream
- bl@1.0.3 node_modules/firebase-tools/node_modules/fsevents/node_modules/bl
- are-we-there-yet@1.1.2 node_modules/firebase-tools/node_modules/fsevents/node_modules/are-we-there-yet
- npmlog@2.0.3 node_modules/firebase-tools/node_modules/fsevents/node_modules/npmlog
- verror@1.3.6 node_modules/firebase-tools/node_modules/fsevents/node_modules/verror
- jsprim@1.2.2 node_modules/firebase-tools/node_modules/fsevents/node_modules/jsprim
- http-signature@1.1.1 node_modules/firebase-tools/node_modules/fsevents/node_modules/http-signature
- wrappy@1.0.1 node_modules/firebase-tools/node_modules/fsevents/node_modules/wrappy
- once@1.3.3 node_modules/firebase-tools/node_modules/fsevents/node_modules/once
- tar-pack@3.1.3 node_modules/firebase-tools/node_modules/fsevents/node_modules/tar-pack
- xtend@4.0.1 node_modules/firebase-tools/node_modules/fsevents/node_modules/xtend
- is-my-json-valid@2.13.1 node_modules/firebase-tools/node_modules/fsevents/node_modules/is-my-json-valid
- har-validator@2.0.6 node_modules/firebase-tools/node_modules/fsevents/node_modules/har-validator
- request@2.69.0 node_modules/firebase-tools/node_modules/fsevents/node_modules/request
- node-pre-gyp@0.6.25 node_modules/firebase-tools/node_modules/fsevents/node_modules/node-pre-gyp
- minimatch@2.0.10 node_modules/firebase-tools/node_modules/globject/node_modules/minimatch
- globject@1.0.1 node_modules/firebase-tools/node_modules/globject
- has-color@0.1.7 node_modules/firebase-tools/node_modules/has-color
- chalk@0.3.0 node_modules/firebase-tools/node_modules/feedback/node_modules/chalk
- feedback@0.3.2 node_modules/firebase-tools/node_modules/feedback
- iconv-lite@0.4.4 node_modules/firebase-tools/node_modules/iconv-lite
- install@0.1.8 node_modules/firebase-tools/node_modules/install
- ipaddr.js@1.0.5 node_modules/firebase-tools/node_modules/ipaddr.js
- is-binary-path@1.0.1 node_modules/firebase-tools/node_modules/is-binary-path
- is-buffer@1.1.3 node_modules/firebase-tools/node_modules/is-buffer
- is-dotfile@1.0.2 node_modules/firebase-tools/node_modules/is-dotfile
- is-extendable@0.1.1 node_modules/firebase-tools/node_modules/is-extendable
- is-extglob@1.0.0 node_modules/firebase-tools/node_modules/is-extglob
- extglob@0.3.2 node_modules/firebase-tools/node_modules/extglob
- is-glob@2.0.1 node_modules/firebase-tools/node_modules/is-glob
- glob-parent@2.0.0 node_modules/firebase-tools/node_modules/glob-parent
- glob-base@0.3.0 node_modules/firebase-tools/node_modules/glob-base
- is-number@0.1.1 node_modules/firebase-tools/node_modules/is-number
- booly@1.0.2 node_modules/firebase-tools/node_modules/booly
- is-posix-bracket@0.1.1 node_modules/firebase-tools/node_modules/is-posix-bracket
- expand-brackets@0.1.5 node_modules/firebase-tools/node_modules/expand-brackets
- is-primitive@2.0.0 node_modules/firebase-tools/node_modules/is-primitive
- is-equal-shallow@0.1.3 node_modules/firebase-tools/node_modules/is-equal-shallow
- isarray@0.0.1 node_modules/firebase-tools/node_modules/isobject/node_modules/isarray
- isobject@2.0.0 node_modules/firebase-tools/node_modules/isobject
- kind-of@3.0.2 node_modules/firebase-tools/node_modules/kind-of
- is-number@2.1.0 node_modules/firebase-tools/node_modules/fill-range/node_modules/is-number
- livereload-js@2.2.2 node_modules/firebase-tools/node_modules/livereload-js
- lodash._arraypool@2.4.1 node_modules/firebase-tools/node_modules/lodash._arraypool
- lodash.isarguments@3.0.8 node_modules/firebase-tools/node_modules/lodash._baseassign/node_modules/lodash.isarguments
- lodash._basecopy@3.0.1 node_modules/firebase-tools/node_modules/lodash._basecopy
- lodash.isarguments@3.0.8 node_modules/firebase-tools/node_modules/lodash._baseeach/node_modules/lodash.isarguments
- lodash.isarguments@3.0.8 node_modules/firebase-tools/node_modules/lodash._baseisequal/node_modules/lodash.isarguments
- lodash._basereduce@3.0.2 node_modules/firebase-tools/node_modules/lodash._basereduce
- lodash._bindcallback@3.0.1 node_modules/firebase-tools/node_modules/lodash._bindcallback
- lodash._getarray@2.4.1 node_modules/firebase-tools/node_modules/lodash._getarray
- lodash._getnative@3.9.1 node_modules/firebase-tools/node_modules/lodash._getnative
- lodash._isiterateecall@3.0.9 node_modules/firebase-tools/node_modules/lodash._isiterateecall
- lodash._maxpoolsize@2.4.1 node_modules/firebase-tools/node_modules/lodash._maxpoolsize
- lodash._releasearray@2.4.1 node_modules/firebase-tools/node_modules/lodash._releasearray
- lodash._slice@2.4.1 node_modules/firebase-tools/node_modules/lodash._slice
- lodash.isarguments@3.0.8 node_modules/firebase-tools/node_modules/lodash.assign/node_modules/lodash.isarguments
- lodash.identity@2.4.1 node_modules/firebase-tools/node_modules/lodash.identity
- lodash.isarray@3.0.4 node_modules/firebase-tools/node_modules/lodash.isarray
- lodash.keys@3.1.2 node_modules/firebase-tools/node_modules/lodash.assign/node_modules/lodash.keys
- lodash.keys@3.1.2 node_modules/firebase-tools/node_modules/lodash._baseisequal/node_modules/lodash.keys
- lodash.keys@3.1.2 node_modules/firebase-tools/node_modules/lodash._baseeach/node_modules/lodash.keys
- lodash._baseeach@3.0.4 node_modules/firebase-tools/node_modules/lodash._baseeach
- lodash.keys@3.1.2 node_modules/firebase-tools/node_modules/lodash._baseassign/node_modules/lodash.keys
- lodash._baseassign@3.2.0 node_modules/firebase-tools/node_modules/lodash._baseassign
- lodash.isfunction@2.4.1 node_modules/firebase-tools/node_modules/lodash.isfunction
- lodash.isnumber@2.4.1 node_modules/firebase-tools/node_modules/lodash.isnumber
- lodash.isstring@2.4.1 node_modules/firebase-tools/node_modules/lodash.isstring
- lodash.istypedarray@3.0.6 node_modules/firebase-tools/node_modules/lodash.istypedarray
- lodash._baseisequal@3.0.7 node_modules/firebase-tools/node_modules/lodash._baseisequal
- lodash.noop@2.4.1 node_modules/firebase-tools/node_modules/lodash.noop
- lodash._setbinddata@2.4.1 node_modules/firebase-tools/node_modules/lodash._setbinddata
- lodash._basecreate@2.4.1 node_modules/firebase-tools/node_modules/lodash._basecreate
- lodash._basecreatewrapper@2.4.1 node_modules/firebase-tools/node_modules/lodash._basecreatewrapper
- lodash._basebind@2.4.1 node_modules/firebase-tools/node_modules/lodash._basebind
- lodash._createwrapper@2.4.1 node_modules/firebase-tools/node_modules/lodash._createwrapper
- lodash.bind@2.4.1 node_modules/firebase-tools/node_modules/lodash.bind
- lodash.isarguments@3.0.8 node_modules/firebase-tools/node_modules/lodash.pairs/node_modules/lodash.isarguments
- lodash.keys@3.1.2 node_modules/firebase-tools/node_modules/lodash.pairs/node_modules/lodash.keys
- lodash.pairs@3.0.1 node_modules/firebase-tools/node_modules/lodash.pairs
- lodash._basecallback@3.3.1 node_modules/firebase-tools/node_modules/lodash._basecallback
- lodash.property@2.4.1 node_modules/firebase-tools/node_modules/lodash.property
- lodash.isarguments@3.0.8 node_modules/firebase-tools/node_modules/lodash.reduce/node_modules/lodash.isarguments
- lodash.keys@3.1.2 node_modules/firebase-tools/node_modules/lodash.reduce/node_modules/lodash.keys
- lodash.reduce@3.1.2 node_modules/firebase-tools/node_modules/lodash.reduce
- lodash.restparam@3.6.1 node_modules/firebase-tools/node_modules/lodash.restparam
- lodash._createassigner@3.1.1 node_modules/firebase-tools/node_modules/lodash._createassigner
- lodash.assign@3.2.0 node_modules/firebase-tools/node_modules/lodash.assign
- flatten-to-object@1.0.0 node_modules/firebase-tools/node_modules/flatten-to-object
- lodash.support@2.4.1 node_modules/firebase-tools/node_modules/lodash.support
- lodash._basecreatecallback@2.4.1 node_modules/firebase-tools/node_modules/lodash._basecreatecallback
- lodash.forown@2.4.1 node_modules/firebase-tools/node_modules/lodash.forown
- lodash.forin@2.4.1 node_modules/firebase-tools/node_modules/lodash.forin
- lodash._baseisequal@2.4.1 node_modules/firebase-tools/node_modules/lodash.createcallback/node_modules/lodash._baseisequal
- lodash.createcallback@2.4.4 node_modules/firebase-tools/node_modules/lodash.createcallback
- lodash.find@2.4.1 node_modules/firebase-tools/node_modules/lodash.find
- media-typer@0.3.0 node_modules/firebase-tools/node_modules/media-typer
- type-is@1.5.7 node_modules/firebase-tools/node_modules/body-parser/node_modules/type-is
- merge-descriptors@1.0.1 node_modules/firebase-tools/node_modules/merge-descriptors
- mime@1.3.4 node_modules/firebase-tools/node_modules/mime
- nan@2.2.1 node_modules/firebase-tools/node_modules/nan
- fsevents@1.0.11 node_modules/firebase-tools/node_modules/fsevents
- nopt@3.0.6 node_modules/firebase-tools/node_modules/nopt
- normalize-path@2.0.1 node_modules/firebase-tools/node_modules/normalize-path
- semver@4.3.6 node_modules/firebase-tools/node_modules/npmconf/node_modules/semver
- object.omit@2.0.0 node_modules/firebase-tools/node_modules/object.omit
- parse-glob@3.0.4 node_modules/firebase-tools/node_modules/parse-glob
- preserve@0.2.0 node_modules/firebase-tools/node_modules/preserve
- ansi-styles@0.2.0 node_modules/firebase-tools/node_modules/pretty-print/node_modules/ansi-styles
- as-array@2.0.0 node_modules/firebase-tools/node_modules/pretty-print/node_modules/as-array
- chalk@0.3.0 node_modules/firebase-tools/node_modules/pretty-print/node_modules/chalk
- lodash@2.2.1 node_modules/firebase-tools/node_modules/pretty-print/node_modules/lodash
- pretty-print@1.1.0 node_modules/firebase-tools/node_modules/pretty-print
- proto-list@1.2.4 node_modules/firebase-tools/node_modules/proto-list
- config-chain@1.1.10 node_modules/firebase-tools/node_modules/config-chain
- proxy-addr@1.0.10 node_modules/firebase-tools/node_modules/proxy-addr
- is-number@2.1.0 node_modules/firebase-tools/node_modules/randomatic/node_modules/is-number
- randomatic@1.1.5 node_modules/firebase-tools/node_modules/randomatic
- range-parser@1.0.3 node_modules/firebase-tools/node_modules/range-parser
- bytes@1.0.0 node_modules/firebase-tools/node_modules/raw-body/node_modules/bytes
- raw-body@1.3.0 node_modules/firebase-tools/node_modules/raw-body
- body-parser@1.8.4 node_modules/firebase-tools/node_modules/body-parser
- minimatch@2.0.10 node_modules/firebase-tools/node_modules/readdirp/node_modules/minimatch
- readdirp@2.0.0 node_modules/firebase-tools/node_modules/readdirp
- regex-cache@0.4.3 node_modules/firebase-tools/node_modules/regex-cache
- regular@0.1.6 node_modules/firebase-tools/node_modules/regular
- cache-header@1.0.3 node_modules/firebase-tools/node_modules/cache-header
- cache-control@1.0.3 node_modules/firebase-tools/node_modules/cache-control
- repeat-element@1.1.2 node_modules/firebase-tools/node_modules/repeat-element
- repeat-string@1.5.4 node_modules/firebase-tools/node_modules/repeat-string
- fill-range@2.2.3 node_modules/firebase-tools/node_modules/fill-range
- expand-range@1.8.1 node_modules/firebase-tools/node_modules/expand-range
- braces@1.8.3 node_modules/firebase-tools/node_modules/braces
- micromatch@2.3.7 node_modules/firebase-tools/node_modules/micromatch
- anymatch@1.3.0 node_modules/firebase-tools/node_modules/anymatch
- chokidar@1.4.3 node_modules/firebase-tools/node_modules/chokidar
- resolve-from@1.0.1 node_modules/firebase-tools/node_modules/resolve-from
- clear-require@1.0.1 node_modules/firebase-tools/node_modules/clear-require
- jfig@1.2.0 node_modules/firebase-tools/node_modules/jfig
- serve-favicon@2.3.0 node_modules/firebase-tools/node_modules/serve-favicon
- statuses@1.2.1 node_modules/firebase-tools/node_modules/statuses
- http-errors@1.3.1 node_modules/firebase-tools/node_modules/http-errors
- send@0.13.1 node_modules/firebase-tools/node_modules/serve-static/node_modules/send
- serve-static@1.10.2 node_modules/firebase-tools/node_modules/serve-static
- send@0.13.2 node_modules/firebase-tools/node_modules/send
- send@0.13.1 node_modules/firebase-tools/node_modules/express/node_modules/send
- caseless@0.10.0 node_modules/firebase-tools/node_modules/superstatic/node_modules/caseless
- qs@3.1.0 node_modules/firebase-tools/node_modules/superstatic/node_modules/qs
- through2@2.0.1 node_modules/firebase-tools/node_modules/through2
- ms@0.6.2 node_modules/firebase-tools/node_modules/tiny-lr/node_modules/ms
- debug@2.0.0 node_modules/firebase-tools/node_modules/tiny-lr/node_modules/debug
- qs@2.2.5 node_modules/firebase-tools/node_modules/tiny-lr/node_modules/qs
- type-is@1.6.12 node_modules/firebase-tools/node_modules/type-is
- express@4.13.4 node_modules/firebase-tools/node_modules/express
- uid-number@0.0.5 node_modules/firebase-tools/node_modules/uid-number
- npmconf@2.1.2 node_modules/firebase-tools/node_modules/npmconf
- websocket-extensions@0.1.1 node_modules/firebase-tools/node_modules/websocket-extensions
- websocket-driver@0.6.4 node_modules/firebase-tools/node_modules/websocket-driver
- faye-websocket@0.7.3 node_modules/firebase-tools/node_modules/faye-websocket
- tiny-lr@0.1.7 node_modules/firebase-tools/node_modules/tiny-lr
/Users/chet/.nvm/versions/node/v4.3.1/lib
└─┬ firebase-tools@2.2.1 
  └── superstatic@4.0.2 

(16:36:49)[kurukulle: firebase]$ firebase --version

Firebase Command Line Tools
Version 1.1.5
https://www.firebase.com

$ which firebase
/Users/chet/.nvm/versions/node/v4.3.1/bin/firebase

**Comment by mbleigh** [comment]
:+1: glad you got it sorted
