### ISSUE TITLE
Deploy succeeds for Hosting project but cloud server does not update html

### ISSUE THREAD

**Issue by hamdanspam** [firebase/firebase-tools#1290]
When I deploy my project from the CLI, it appears to work based on the readout. However, when I go to my webpage (both the firebase one and the custom domain), the page does not update. It's all static content, just HTML and CSS. I tried making a new Hosting project to see if I could host my page elsewhere, which worked. But I'd like to use my original project to host my website, and I'd like to understand why it happened so I can avoid it if it happens again.

**Comment by abeisgoat** [comment]
Make sure to [hard refresh](https://refreshyourcache.com/en/cache/) or try loading the page on your phone. It's likely that it's just cached in your browser.

Also ensure that you're not using a ServiceWorker on your page.

**Comment by hamdanspam** [comment]
Hi @abeisgoat thanks a bunch for your reply. I don't know how to tell if there is a ServiceWorker on my page, but there isn't any javascript, only HTML, CSS, and JSON files. How would I tell if there is a ServiceWorker?

It's not cached, I forgot to mention that above. I look in incognito, on my phone, after a hard refresh. It's definitely not deploying.

So, as an update, my new website doesn't properly deploy my new html either. The first deploy was fine, and the second deploy was "successful" (CLI tells me "deploy complete!"), but the website doesn't update its static content.

I added some folders to the directory, I changed the owner of the files (I'm using Linux), and I changed the permissions. Would that do it?

**Comment by abeisgoat** [comment]
Hmm, I'm not sure what's up but it doesn't sound like a bug (and we can only really help with things that are definitely bugs here) I would recommend asking on StackOverflow with a minimal example case and getting help there!

Sorry I can't do more!
