### ISSUE TITLE
Firestore emulator doesn't recognise rules flag

### ISSUE THREAD

**Issue by Yuripetusko** [firebase/firebase-tools#1303]
### [REQUIRED] Environment info

**firebase-tools: 6.9.2**

**Platform: macOS**

### [REQUIRED] Test case

According to docs

```The emulator supports an optional --rules CLI flag. It expects the name of a local file containing your Cloud Firestore Security Rules and applies those rules to all projects. If you don't provide the local file path or use the loadFirestoreRules method as described below, the emulator treats all projects as having open rules.```

### [REQUIRED] Steps to reproduce

`firestore (master) $ firebase emulators:start --only firestore --rules firestore.stable.rules`

### [REQUIRED] Expected behavior

`--rules` flag to be recognised as per Documentation

### [REQUIRED] Actual behavior

`error: unknown option `--rules'`

**Comment by samtstern** [comment]
That's a good point and it's a documentation error.  The firestore emulator
automatically uses the rules file specified in your firebase.json , are you
trying to use a different file?

**Comment by abeisgoat** [comment]
This is definitely a documentation error, I believe we're having some conversations about docs today so I'll make sure to bring this up as a point of confusion!

**Comment by Yuripetusko** [comment]
Yes I tried 3 different ways:

1 --rules flag as above
2 `await firebase.loadFirestoreRules()` - doesn't work
3

```
"emulators": {
    "firestore": {
      "port": "5002",
      "rules": "firestore/firestore.stable.rules"
    }
  }
```

in firebase.json which also doesn't work

It always just use default one from this

```
"firestore": {
    "rules": "firestore/firestore.rules",
    "indexes": "firestore/firestore.indexes.json"
  },
```

**Comment by Yuripetusko** [comment]
So I guess it now turned into feature request

**Comment by samtstern** [comment]
@Yuripetusko yeah this is a FR not a bug since right now we only look for what's in `firestore.rules` not `emulators.firestore.rules`.

Could you explain your use case a bit more?  What is the meaning of `.stable.rules` for your project?

**Comment by Yuripetusko** [comment]
@samtstern I guess it's not a big deal, just for few days we had multiple generated rules as we were testing some security rules and didn't want to deploy them straight away but wanted to use them in our jest tests

**Comment by samtstern** [comment]
@Yuripetusko FYI we provide a way to load rules files from inside your tests using the `@firebase/testing` library:
https://github.com/firebase/quickstart-nodejs/blob/master/firestore-emulator/javascript-quickstart/test/test.js#L37

That's probably your best bet if you want to use a different rule set only in tests.

**Comment by Yuripetusko** [comment]
@samtstern I actually already do this, but it doesn't work, looks like emulator still overwrites rules that it finds in firebase.json

**Comment by ryanpbrewster** [comment]
That's surprising, could you provide a snippet showing how you're using the `loadFirestoreRules` function from `@firebase/testing`?

**Comment by Yuripetusko** [comment]
this is how I do it

```
const projectId = 'firestore-migration-test';
const coverageUrl = `http://${process.env.FIREBASE_FIRESTORE_EMULATOR_ADDRESS}/emulator/v1/projects/${projectId}:ruleCoverage.html`;
const rules = fs.readFileSync('firestore.stable.rules', 'utf8');

...


const setup = async () => {
  const app = await firebase.initializeTestApp({ projectId, auth: { uid: 'D4iD36vNgNPAbpg7oKYscJxazyI3' } });

  const db = app.firestore();

  // Apply rules
  await firebase.loadFirestoreRules({ projectId, rules });

  return db;
};
```

And I am sure that file is loaded as if I change path it complains that fs cannot find a file

**Comment by Yuripetusko** [comment]
The only thing I do differently is I don't use firebase/testing asserts, and use jest instead, but setup is using firebase/test..

**Comment by ryanpbrewster** [comment]
That code looks correct, and when I try it it works.

Can you provide a short repro of the issue you're running into (i.e., your rules, a test script, and the command you use to execute them)?

**Comment by Yuripetusko** [comment]
@ryanpbrewster Indeed while I was creating a reproducible repository this morning it worked using `loadFirestoreRules`, must be some other issue why it didn't work for me before which I will investigate. Thanks for going through it with me

**Comment by samtstern** [comment]
@Yuripetusko thanks for following up!

**Comment by therefromhere** [comment]
@abeisgoat Could this be reopened since the documentation is still incorrect?

https://firebase.google.com/docs/firestore/security/test-rules-emulator#before_you_run_the_emulator

**Comment by samtstern** [comment]
@therefromhere good call, I will have to get those docs fixed.

**Comment by matheo** [comment]
@samtstern It would be good to add a configuration schema for the `firebase.json` so we know which options are supported and the IDE can autocomplete too:
https://github.com/SirWindfield/vscode-firebase-configuration-schema-plugin/blob/master/schemas/firebase.schema.json

**Comment by samtstern** [comment]
@therefromhere I have submitted a docs change, it will go live probably tomorrow.
@matheo that's a great idea, let me file a new issue for that.
