### ISSUE TITLE
“Error: Server Error. socket hang up” whenever I do “firebase deploy --only hosting, database, storage”

### ISSUE THREAD

**Issue by dreamhigh0822** [firebase/firebase-tools#1309]
### [REQUIRED] Environment info
I am using the latest version of firebase-tools. 

**firebase-tools:** v6.9.2

**Platform:** Ubuntu 18.04

### [REQUIRED] Test case
I am sure that firebase.json is in a good condition.
### [REQUIRED] Steps to reproduce

firebase login
firebase list
firebase use 'myprojectid'
firebase deploy --only database, functions, storage, hosting
### [REQUIRED] Expected behavior
 it must be done successfully.

### [REQUIRED] Actual behavior
It always ends up with reporting “Error: Server Error. socket hang up” error.

**Comment by bkendall** [comment]
If you are still seeing this error, can you provide contents of `firebase-debug.log` or the output of running this command with `--debug`? Sometimes these issues are temporary, but it's difficult to know what in particular is failing without more details.

**Comment by dreamhigh0822** [comment]
OK, This is the snippet of firebase-debug.log when I execute the "firebase deploy --only database,storage"
```
[debug] [2019-05-17T18:18:52.268Z] Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1135:19)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at TLSSocket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
[error] 
[error] Error: Server Error. socket hang up
```

**Comment by bkendall** [comment]
That's not quite enough to know what it's failing on. Before this part of the log, you should see some kind of URL with a method in front of it. Hopefully that will tell us what call is failing - this is only telling us that _a_ call is failing (which is what we knew).

It may also be worth checking your environment to see if you have any `PROXY` settings that might effect this. You can check by doing `env | grep PROXY` and looking through any remaining environment variables.

**Comment by dreamhigh0822** [comment]
Thanks for your attention.
Fortunately, I solved this problem by myself. I just appended ":projectID" to the last of the deploy command. But I am still feeling strange about this. Since that I used the "firebase use" command, doesn't it contain the default "projectID"?

**Comment by bkendall** [comment]
Can you clarify what you mean by "appended :projectID"? Can you give the specific example? I think folks will want to look into this, but I'm not entirely sure I have enough context yet 🙂

**Comment by tohagan** [comment]
Hitting the same issue. Just submitted a support ticket with my firebase-debug.log attached.

**Comment by tohagan** [comment]
I also noticed that it attempts to upload files it will display 
   `hosting: uploading new files [0/9] 0%` 
Then timeout and FAIL.

Next ... when I retry this it thinks the last file succeeded so it now displays
   `hosting: uploading new files [0/8] 0%`     - decrements the number of files to upload to 8
Next when i retry this again it thinks the last file succeeded so it now displays
   `hosting: uploading new files [0/7] 0%`     - decrements the number of files to upload to 7

Which I suspect is incorrect since I really doubt that it succeeded to upload any files.

**Comment by thechenky** [comment]
@tohagan @dreamhigh0822 Problems like this are typically caused by poor internet connectivity. Do you have issues running commands like `firebase list`?

**Comment by dreamhigh0822** [comment]
Thanks for your attention.
@thechenky  No, I don't have any internet connectivity. ```firebase list``` is rather working properly.

This is the error case I have met.
```
dreamhigh@ubuntu:~/workspace/Gobot/gobot$ firebase deploy --only database,storage

=== Deploying to 'gobot-dev'...

i  deploying database, storage
i  database: checking rules syntax...
✔  database: rules syntax for database gobot-dev is valid
i  storage: checking storageRules.rules for compilation errors...
✔  storage: rules file storageRules.rules compiled successfully
i  storage: uploading rules storageRules.rules...
i  database: releasing rules...

Error: Server Error. socket hang up
```
The following is the case I have solved by myself. 
```
dreamhigh@ubuntu:~/workspace/Gobot/gobot$ firebase deploy --only database,storage:gobot-dev

=== Deploying to 'gobot-dev'...

i  deploying database, storage
i  database: checking rules syntax...
✔  database: rules syntax for database gobot-dev is valid
i  storage: checking storageRules.rules for compilation errors...
✔  storage: rules file storageRules.rules compiled successfully
i  storage: uploading rules storageRules.rules...
i  database: releasing rules...
✔  database: rules for database gobot-dev released successfully
✔  storage: released rules storageRules.rules to firebase.storage/gobot-dev.appspot.com

✔  Deploy complete!

Project Console: https://console.firebase.google.com/project/gobot-dev/overview
```

As you can see the code snippet,  I appended ```:projectID``` to the deploy command.

**Comment by thechenky** [comment]
Thanks for the reply @dreamhigh0822 it's still a bit odd to me that you had to do that. When you did not supply the project id the command still knew which project to deploy to. Do you have a lot of projects?

**Comment by thechenky** [comment]
@dreamhigh0822 can you attach a debug log as @bkendall suggested? It would help us figure out why adding `:projectId` makes the command succeed.

**Comment by dreamhigh0822** [comment]
@thechenky No, I only have a project. So, I thought that if I used ```firebase use```command, then it would use the project. But it didn't. Unless I didn't specify the id of the project explicitly, no matter what, it failed.
Sorry but for now I don't have the log file, since that I got my hand of that project.

**Comment by thechenky** [comment]
@dreamhigh0822 can you paste your `.firebaserc` here? I think it has your information there - the deploy without adding `:projectId` was still finding the project, so that's the part I'm confused about. If it was able to find the project, it should be able to deploy to it.

**Comment by dreamhigh0822** [comment]
@thechenky 
I think you are right. The problem is this file configuration for the project.
There is already the default projectID in the file so that I have to provide my projectID to deploy it.
This is the ```.firebaserc``` content.
```
{
  "projects": {
    "default": "gobot-a5af4",
    "dev": "gobot-a5af4",
    "prod": "gobot-3e82e",
    "mu": "gobot-multiuser"
  }
}
```
Thanks.
