### ISSUE TITLE
NPM graceful-fs

### ISSUE THREAD

**Issue by darkmorpher** [firebase/firebase-tools#131]
>npm install -g firebase-tools

**npm WARN deprecated** graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

>npm ls -g graceful-fs
>..\Documents\node
+-- firebase-tools@2.2.1
| +-- configstore@1.4.0
| | -- graceful-fs@4.1.4
| -- superstatic@4.0.2
| --- fs-extra@0.20.1
| ---- **graceful-fs@3.0.8**

**Comment by drtriumph** [comment]
This is an upstream dependency - we need the npm package [mocha](https://github.com/mochajs/mocha/commit/c9bcfc1b015c8d15d5fe5159e30818cd02f6a098) to release a new patch version
