### ISSUE TITLE
Emulator Suite should have more helper warnings / errors

### ISSUE THREAD

**Issue by abeisgoat** [firebase/firebase-tools#1310]
Currently we know of two situations which could be improved with better helper logs...

- [x] Detecting uncompiled TS from #1304

- [ ] Explaining `serve` vs `emulators:start` and specifically auth errors from #1299 

>There is a split in functionality, between running your code via serve and emulators:start which isn't well documented. If you want to simply invoke your code and with it, access production APIs and services, similar to the classic Google Cloud Function emulator, then your code should be invoked with serve. When you invoke your functions via emulators:start we do everything we can to prevent you from accidentally contacting production services. As we flesh out the emulator functionality, this mode will become more and more powerful, but right now it can look broken (we're planning on adding more helpful errors soon). For the current releases our focus is on maintaining backwards compatibility with the old GCF emulator via serve and all the cool things we're planning for emulators:start are largely still WIP.

There's more situations for sure, but let's get started here.

**Comment by joehan** [comment]
Another place for better error messaging that we found - if you set process.env.CLOUD_RUNTIME_CONFIG to a JSON file or stringified JSON that doesn't follow service.field format, the error message is:
```
TypeError: Cannot create proxy with a non-object as target or handler
    at new Proxied (/Users/joehanley/Workspace/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:32:22)
    at Proxied.InitializeFunctionsConfigHelper.Proxied.any [as anyValue] (/Users/joehanley/Workspace/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:313:16)
    at Object.get (/Users/joehanley/Workspace/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:39:33)....
```

To recreate this, run
``` CLOUD_RUNTIME_CONFIG="{\"hello\":\"world\"}"  firebase emulators:start```

**Comment by abeisgoat** [comment]
Thank you @joehan whoever told you to comment that on this bug was very intelligent and probably handsome.

**Comment by thefliik** [comment]
#1304 is a very helpful issue. I was running into a hard-to-diagnose `Error: Cannot find module` error and it turned out my problem was that I had mistakenly pointed my `package.json` "main" entry at the uncompiled `index.ts` rather than `dist/index.js`. Learning that the issue was probably caused by uncompiled typescript was enough to put me on the right track. Still, it might be helpful to also suggest that it could be an issue with `package.json#main`.

Part of what made it hard to diagnose for me, was the that it says `Cannot find module` and then it pointed to the correct module path. So my initial reaction was "well...clearly you can find the module". Obviously this is user error, but, so long as we're talking about improving error messages, here's another possibility.

**Comment by abeisgoat** [comment]
That's not a bad idea, I already did a pass on improved errors for Typescript, but that seems like a cheap / easy fix, so I'll probably drop it in in my next set of logging improvements.

**Comment by szeitlin** [comment]
Here's another one, maybe a real error but needs better documentation on the expected configuration if that's the case: 

I have keys.json stored in a place that works with GCP (e.g., real Firestore). However, when I try to use it with the emulator, I get an error.

so I'm running: `firebase emulators:exec --only firestore "nosetests tests/"`

and I get back: 
`google.auth.exceptions.DefaultCredentialsError: File keys.json was not found.`

It looks like it's looking here:
```
/google/auth/_default.py", line 165, in _get_explicit_environ_credentials
    os.environ[environment_vars.CREDENTIALS])
```
so I'm trying to understand, the gcloud cli uses the environment variable GOOGLE_APPLICATION_CREDENTIALS but the firebase emulator wants to use a different environment variable, i.e. CREDENTIALS, for the same keys-? Is that correct?

**Comment by samtstern** [comment]
@szeitlin I am not sure where this comes from:
```
/google/auth/_default.py", line 165, in _get_explicit_environ_credentials
    os.environ[environment_vars.CREDENTIALS])
```

The whole Firebase CLI is JavaScript (or native extensions) so anything coming from python code is not coming from `firebase-tools`.

**Comment by szeitlin** [comment]
I think it's coming from the python `google.cloud.firestore` library. Anyway I figured it out... Thanks for responding.

**Comment by FredyC** [comment]
And one from me. Took me quite a while to find out I should be running `emulators:start` instead of `serve`.

```
i  functions: Beginning execution of "myFunc"
>  Unhandled error Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
>      at GoogleAuth.getApplicationDefaultAsync (/mnt/d/workspace/app/functions/node_modules/google-auth-library/build/src/auth/googleauth.js:161:19)
>      at process._tickCallback (internal/process/next_tick.js:68:7)
i  functions: Finished "myFunc" in ~1s
```

**Comment by thefliik** [comment]
I must admit, I still have no idea what the difference is between `emulators:start` and `serve`. I often use them interchangeably and if I run into a problem, I inevitably need to try debugging using each in case one works.

**Comment by samtstern** [comment]
`serve` exists for purely historical reasons.  It existed when all the emulators were isolated from each other and we didn't want to break people.

You should always use `emulators:start` unless you for some reason really need the old behavior.

**Comment by FredyC** [comment]
@samtstern Perhaps it might be a good idea to notify about that when `serve` is used. There is still couple of places in docs with it so there isn't really a clear path to realize there is something new.

**Comment by samtstern** [comment]
Version `8.0` will reduce most of the `serve` vs `emulators:start` confusion.

@abeisgoat is there anything else you wanted to track here?

**Comment by abeisgoat** [comment]
I don't think so, I believe this was wrapped up in 8.0.0
