### ISSUE TITLE
Firebase login authorization code no longer valid

### ISSUE THREAD

**Issue by Galantryas** [firebase/firebase-tools#1315]
C:\xampp\htdocs\portofolio>firebase login --no-localhost
? Allow Firebase to collect anonymous CLI usage and error reporting information? Yes

Visit this URL on any device to log in:
https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=982883067&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob

? Paste authorization code here: 4/UAFKE-rCjdIpF61jC4xcALMQgGp89q7MLraRNdp8ED0Ipg5edn5msdg

Error: Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci

Having trouble? Try firebase login --help

C:\xampp\htdocs\portofolio>firebase login --help
Usage: login [options]

log the CLI into Firebase

Options:
  --no-localhost  copy and paste a code instead of starting a local server for authentication
  --reauth        force reauthentication even if already logged in
  -h, --help      output usage information

C:\xampp\htdocs\portofolio>

**Comment by abeisgoat** [comment]
Please follow the issue template.
