### ISSUE TITLE
INVALID_ARGUMENT at firebase deploy

### ISSUE THREAD

**Issue by nicoara** [firebase/firebase-tools#1317]
### [REQUIRED] Environment info

firebase --version: 3.19.0

OS: macOS 10.13.6

### [REQUIRED] Test case

trying to solve problem for 5 hours now, at 'firebase deploy'.

function is: 
```
exports.makeUppercase = functions.database.ref('/userfollowers/{pushId}/followers')
    .onWrite((change, context) => {
      // Only edit data when it is first created.
      if (change.before.exists()) {
        return null;
      }
      // Exit when the data is deleted.
      if (!change.after.exists()) {
        return null;
      }
      // Grab the current value of what was written to the Realtime Database.
      const original = change.after.val();
      console.log('Uppercasing', context.params.pushId, original);
      const uppercase = original.toUpperCase();
      // You must return a Promise when performing asynchronous tasks inside a Functions such as
      // writing to the Firebase Realtime Database.
      // Setting an "uppercase" sibling in the Realtime Database returns a Promise.
      return change.after.ref.parent.child('uppercase').set(uppercase);
    });
```
which is straight out of documentation.

same with: '/userfollowers/{pushId}/followers/{follower}'

### [REQUIRED] Steps to reproduce

above

### [REQUIRED] Expected behavior

should have been deployed with no error.

### [REQUIRED] Actual behavior

the terminal shows:
```
⚠  functions: failed to create function makeUppercase
HTTP Error: 400, The request has errors

```
cloud functions logs show:
`{"@type":"type.googleapis.com/google.cloud.audit.AuditLog","status":{"code":3,"message":"INVALID_ARGUMENT"},"authenticationInfo":{"principalEmail":"nicoaratalpes@gmail.com"},"requestMetadata":{"callerIp":"86.120.235.246","callerSuppliedUserAgent":"FirebaseCLI/3.19.0,gzip(gfe),gzip(gfe)","requestAttributes":{"time":"2019-05-14T08:34:18.563Z","auth":{}},"destinationAttributes":{}},"serviceName":"cloudfunctions.googleapis.com","methodName":"google.cloud.functions.v1.CloudFunctionsService.CreateFunction","authorizationInfo":[{"resource":"projects/parkour-9136c/locations/us-central1/functions/makeUppercase","permission":"cloudfunctions.functions.create","granted":true,"resourceAttributes":{}},{"permission":"cloudfunctions.functions.create","granted":true,"resourceAttributes":{}}],"resourceName":"projects/parkour-9136c/locations/us-central1/functions/makeUppercase","request":{"location":"projects/parkour-9136c/locations/us-central1","@type":"type.googleapis.com/google.cloud.functions.v1.CreateFunctionRequest","function":{"labels":{"deployment-tool":"cli-firebase"},"entryPoint":"makeUppercase","eventTrigger":{"eventType":"providers/google.firebase.database/eventTypes/ref.write","resource":"projects/_/instances/parkour-9136c/refs/userfollowers/{pushId}/followers","service":"firebaseio.com"},"sourceUploadUrl":"https://storage.googleapis.com/gcf-upload-us-central1-f5adb7fe-7321-4f3c-8fe0-2b2307d26138/5b099ea8-161b-44a7-a3bd-18ce75c64859.zip?GoogleAccessId=service-807137615499@gcf-admin-robot.iam.gserviceaccount.com&Expires=1557824657&Signature=PJKzJsZtHWO1kIkmrSojpdgvb0jRzV91eNC9rZc4j%2FMcoHjILGm36FKCt6qQ2fxeAUu1%2FbrxpagdI7fHmUUUrDdTmnTNISr7FiN61sifUI%2B%2FGnUwo8SguzvrA7kADFqu8nD05FAo7BvG7biUrHmLgISlwo5dTKqcTSmExnaICA1tHYxjz%2Fk0RbmdGkcQ5HdeCKBnW0R7wQPsxswQyvR4cAU4WD2m3PPM9lncVr7pB%2Fh77FboGLi3sq%2FGHyEwUtjfUmyN9d%2FYUpKs48TMsGPknAGIvaFFUWQR23YCDUcrPipq1nW2W1JUdf5nGylYmVEeyF3jLrm%2BsOIcXiZ6LCRhpg%3D%3D","name":"projects/parkour-9136c/locations/us-central1/functions/makeUppercase"}}}`

**and most importantly, here is a more explicit reason:**
firebase deploy --debug shows:
```
[2019-05-20T14:43:23.358Z] >>> HTTP REQUEST POST https://cloudfunctions.googleapis.com/v1/projects/parkour-9136c/locations/us-central1/functions  
 { sourceUploadUrl: 'https://storage.googleapis.com/gcf-upload-us-central1-f5adb7fe-7321-4f3c-8fe0-2b2307d26138/ceae3b1e-137b-4a1b-996c-21ba50170e47.zip?GoogleAccessId=...@gcf-admin-robot.iam.gserviceaccount.com&Expires=1558365202&Signature=...',
  name: 'projects/parkour-9136c/locations/us-central1/functions/makeUppercase',
  entryPoint: 'makeUppercase',
  labels: { 'deployment-tool': 'cli-firebase' },
  eventTrigger: 
   { resource: 'projects/_/instances/parkour-9136c/refs/userfollowers/{pushId}/followers/{follower}',
     eventType: 'providers/google.firebase.database/eventTypes/ref.write',
     service: 'firebaseio.com' } } 
 Mon May 20 2019 17:43:23 GMT+0300 (EEST)
[2019-05-20T14:43:23.863Z] <<< HTTP RESPONSE 400 vary=X-Origin, Referer, Origin,Accept-Encoding, content-type=application/json; charset=UTF-8, date=Mon, 20 May 2019 14:43:23 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="46,44,43,39", accept-ranges=none, connection=close
[2019-05-20T14:43:23.863Z] <<< HTTP RESPONSE BODY code=400, message=The request has errors, status=INVALID_ARGUMENT, details=[@type=type.googleapis.com/google.rpc.BadRequest, ****fieldViolations=[field=runtime, description=Runtime field cannot be empty.]]****
⚠  functions: failed to create function makeUppercase
HTTP Error: 400, The request has errors
```

How to solve this?

**Comment by bkendall** [comment]
`v3.19.0` is a very, very old version of the Firebase CLI. I was able to deploy that function successfully using `v6.10.0`. Please update your CLI (`npm i -g firebase-tools`) and retry the deploy.

**Comment by nicoara** [comment]
@bkendall  wow, thank you for the extremely fast help.
Did not know it was so old until today.
This solved it!!

**Comment by JayPerfetto** [comment]
I did this and am still getting this error even on the latest version of all firebase packages

**Comment by SilentByte** [comment]
I started getting this error out of nowhere last night. After some digging around, the cause might have been a mismatch in the versions of node. I got it working again by removing package-lock.json.

Alternatively, ensure that you are running the same node version. In my case, I downgraded from 12 to 10 locally and set "engines" in package.json to 10 as well.

**Comment by samtstern** [comment]
I recently got this error once as well but I ran `firebase deploy` a second time and it went away ...

**Comment by SimonKomlos** [comment]
Had this exact same problem for **weeks (!)**

What finally worked for me: 

- `npm i -g firebase-tools@latest`
- Deleted `package-lock.json` file
- Deleted `node_modules` folder
- `npm install`
- `firebase deploy`

Hope that can help someone in the same position!!

**Comment by ryanlangton** [comment]
I have this error, followed the steps listed in the response above mine, and still get the same error :(

**Comment by acco** [comment]
For posterity to future wanderers...

Per the comment that @ryanlangton made above, if you're receiving this error double check that your query syntax inside all of your `document()` calls are valid.

I was getting the same error. In order to add hooks like `onCreate()`, `onWrite()`, etc, you need to add these hooks on a specific document (as opposed to a broader collection). So adding the `/{docId}` to everything helped.

eg if you're seeing this anywhere:

```
functions.firestore.document('beacons').onCreate((snap) => {
  // do something
})
```

It won't work. Needs to be:

```
functions.firestore.document('beacons/{beaconId}').onCreate((snap) => {
  // do something
})
```

Just expanding on @ryanlangton's comment, as it wasn't immediately obvious that his issue applied to me.

**Comment by Schwoebel** [comment]
> Had this exact same problem for **weeks (!)**
> 
> What finally worked for me:
> 
>     * `npm i -g firebase-tools@latest`
> 
>     * Deleted `package-lock.json` file
> 
>     * Deleted `node_modules` folder
> 
>     * `npm install`
> 
>     * `firebase deploy`
> 
> 
> Hope that can help someone in the same position!!

This is the npm version of "Have you tried turning it off and back on again?"....but it works....:)

**Comment by sonuKumar03** [comment]
I solved this by 
1. rm -rf node_modules/
2. npm install 
3. firebase init
4. firebase deploy
