### ISSUE TITLE
verifyDeveloperNodeModules() does not properly detected uninstalled modules

### ISSUE THREAD

**Issue by MatteoGioioso** [firebase/firebase-tools#1320]
### [REQUIRED] Environment info

firebase-tools: 6.10.0
Ubuntu 18.04.2 LTS

### [REQUIRED] Steps to reproduce

I just upgrade from `firebase-tools 6.8.0` to `6.10.0`
and when try to run `firebase serve --only functions,hosting`
I get this error
```
Error: Cannot find module 'package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at verifyDeveloperNodeModules (/usr/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:120:32)
    at /usr/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:435:26
    at Generator.next (<anonymous>)
    at /usr/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:3:12)

```
### [REQUIRED] Expected behavior
It should run normally
**This is not happening with version `6.8.0`**

### [REQUIRED] Actual behavior
It throws an error

For now I just downgraded back to `6.8.0`

**Comment by bkendall** [comment]
Can you provide a bit more about your setup? We need enough information so we can fully replicate your issue. Do you have customization in `firebase.json`? Where do your functions and hosting code live relative to where you're running the `firebase` command?

**Comment by abeisgoat** [comment]
This regression was caused in the change from `require.resolve` to `slowRequireResolve` in the [`functionsEmulatorRuntime`](https://github.com/firebase/firebase-tools/blob/master/src/emulator/functionsEmulatorRuntime.ts). Specifically, on line [#198](https://github.com/firebase/firebase-tools/blob/master/src/emulator/functionsEmulatorRuntime.ts#L198) there is no situation where `slowRequireResolve` will throw an error whereas `require.resolve` will throw when a module isn't resolvable. 

To fix this, we should make `slowRequireResolve` throw when it is incapable of resolution. 

I will get a fix in for the next release.

**Comment by bkendall** [comment]
Thanks for taking this on @abeisgoat

**Comment by MatteoGioioso** [comment]
@bkendall Ugh, sorry for the late replay. If still needed I can get small repo and try to reproduce the error. Let me know thanks!

**Comment by abeisgoat** [comment]
No repro needed, thanks, fix coming soon.

**Comment by abeisgoat** [comment]
Fix has been merged into `next` branch so it'll go out with the `firebase-tools@7.0.0` release
