### ISSUE TITLE
firebase deploy --only functions Error parsing triggers: Cannot find module 'cors'

### ISSUE THREAD

**Issue by orlandomendozagarrido** [firebase/firebase-tools#1329]
im trying to deploy my functions folder , but I get this error in my console . I tried npm install in root and folder , I upgraded node to current .

✔  functions: Finished running predeploy script.
i  functions: ensuring necessary APIs are enabled...
✔  functions: all necessary APIs are enabled
i  functions: preparing functions directory for uploading...

Error: Error parsing triggers: Cannot find module 'cors'
Require stack:
- /home/hc-06/Documents/ReactMLFireBaseApp-/MLReactapp/functions/index.js
- /home/hc-06/.nvm/versions/node/v12.2.0/lib/node_modules/firebase-tools/lib/triggerParser.js

Try running "npm install" in your functions directory before deploying.

**Comment by thechenky** [comment]
@orlandomendozagarrido please follow the issue template. The required fields are required :)

**Comment by abeisgoat** [comment]
This is most likely a bug in your code @orlandomendozagarrido (but it's impossible to tell without the rest of the issue template).  

Your code definitely either has `require("cors")` or `import * from "cors"` and you don't have that module installed into your functions directory (and it's associated `package.json`)

**Comment by abeisgoat** [comment]
Closing due to lack of author response.

**Comment by pelx** [comment]
same problem persists. suggestions are not helpful

**Comment by immunity20** [comment]
Try to delete `package-lock.json` file and `node_modules` folder and run again `npm install`
