### ISSUE TITLE
firebase functions deploy error

### ISSUE THREAD

**Issue by ShaMan123** [firebase/firebase-tools#1333]
### [REQUIRED] Environment info

**firebase-tools:** 6.10.0

**Platform:** Windows

### [REQUIRED] Test case

`firebase deploy --only functions`

Running `firebase deploy --only database` completes successfully and swiftly.
### [REQUIRED] Steps to reproduce

`firebase deploy --only functions`
I suspected this might be an issue with `node10` so I downgraded to `node8` because I'm experiencing some trouble with `npm` too. Still the same problem.
- Reauthenticated.
- Reinstalled/downgraded `firebase-tools`, reinstalled `firebase-functions`.
- Reinstalled `node_modules` after deleting lock file
- Will try to reinstalled `node-gyp`  `node-pre-gyp` .

This is very frustrating.

### [REQUIRED] Expected behavior

deploy properly

### [REQUIRED] Actual behavior

execution lags for a while and eventually exits.
The end of cli output:
```
175, 65512=148, 65513=143, 65514=215, 65515=133, 65516=74, 65517=64, 65518=48, 65519=205, 65520=165, 65521=108, 65522=219, 65523=48, 65524=4, 65525=240, 65526=231, 65527=82, 65528=222, 65529=224, 65530=87, 65531=58, 65532=42, 65533=250, 65534=229, 65535=183, next=null, $ref=$["_readableState"]["buffer"]["head"], length=1, length=65536, pipes=null, pipesCount=0, flowing=null, ended=false, endEmitted=false, reading=false, sync=false, needReadable=false, emittedReadable=true, readableListening=false, resumeScheduled=false, destroyed=false, defaultEncoding=utf8, awaitDrain=0, readingMore=false, decoder=null, encoding=null, readable=true, domain=null, end=function () {
    if (this.autoClose) {
      this.destroy();
    }
  }, _eventsCount=1, _maxListeners=undefined, path=C:\Users\DELL\AppData\Local\Temp\firebase-functions-81448AHG3rjFmyJc.zip, fd=5, flags=r, mode=438, start=undefined, end=Infinity, autoClose=true, pos=undefined, bytesRead=65536
```

`firebase-debug` file:
```

[info] i  functions: packaged functions (176.41 MB) for uploading
[debug] [2019-05-23T06:49:41.276Z] >>> HTTP REQUEST POST https://cloudfunctions.googleapis.com/v1/projects/autodidact-mvp/locations/us-central1/functions:generateUploadUrl  
 
[debug] [2019-05-23T06:49:45.951Z] <<< HTTP RESPONSE 200
[debug] [2019-05-23T06:49:45.957Z] >>> HTTP REQUEST PUT https://storage.googleapis.com/gcf-upload-us-central1-b13388b9-f955-4e90-af3b-7c094b5c822c/77b3d591-3221-4468-bc13-d0be51b68003.zip?GoogleAccessId=service-873554313394@gcf-admin-robot.iam.gserviceaccount.com&Expires=1558595983&Signature=R4IQTzgrO5CEPMha4czYWvnbM2w17417k1%2BEjoM8bVjNkA6cPIJjgJbMsj1VoccotntDjsN6bIpUPXTTn6fvRlCtynJZz%2Bmaw20RTW3doCGvVM6C99CwC6bofei13XgrsjtIxr4t4DwHLiOxNXIHgkCcS0MkaTRyFc%2B3xfYVlTx4WKg9wC%2BmdVE2i5RAr9n5oAUIvVZjZDspXqVjOakkYs7Dtz0Rmp2Vgkf6t9O3RpZgKh3tDCPa2Eqbf25BSRzHCfIUnVlJg%2Fi9kiRaMKQ6pB9q98ZAAcjVB7KFHLj3Dsa8fGKfAPoFmITZttvS01Zr6m4tcifTsM%2FW3h%2FArYPxsw%3D%3D  


```

In another run it threw a different error regrading `cjs`

**Comment by ShaMan123** [comment]
can't say if this is related to `node-gyp`

**Comment by ShaMan123** [comment]
After a few nerve wrecking hours I managed to deploy after reinstalling `npm`.
Tried again to make sure it is stable and ran into the problem.
I did find a bug in `node-gyp` pointing to a wrong bin file but can't say if it's related.

**Could this be related to connection problems?**

**Comment by ShaMan123** [comment]
update:
```
[2019-05-23T13:41:53.042Z] FirebaseError: HTTP Error: 503, The service is currently unavailable.

Error: Cloud Runtime Config is currently experiencing issues, which is preventing your functions from being deployed. Please wait a few minutes and then try to deploy your functions again.
Run `firebase deploy --except functions` if you want to continue deploying the rest of your project.

```

**Comment by thechenky** [comment]
Hi @ShaMan123 sorry you're experiencing these issues. From your last comment it seems there were issues connecting to Runtime Config - these are usually transient. Can you try to deploy again to see if you're getting the same error?

**Comment by henrylearn2rock** [comment]
**Node 10 still fails**

C:\Users...> firebase deploy --only functions

=== Deploying to 'xxxxxxx'...

i  deploying functions
i  functions: ensuring necessary APIs are enabled...
+  functions: all necessary APIs are enabled
i  functions: preparing functions directory for uploading...

Error: package.json in functions directory has an engines field which is unsupported. The only valid choices are: {"node": "8"} and {"node": "6"}.

C:\Users...> firebase -V
6.5.0
C:\Users...> node --version
v10.15.3

**Comment by thechenky** [comment]
Update firebase-tools

**Comment by ShaMan123** [comment]
I managed to deploy.
Thanks for the rapid response!

**Comment by thechenky** [comment]
Awesome, glad it's working now! Will close this out. Please open up new issue if you have any other problems.

**Comment by lotsinsights** [comment]
Error: Cloud Runtime Config is currently experiencing issues, which is preventing your functions from being deployed. Please wait a few minutes and then try to deploy your functions again.
Run `firebase deploy --except functions` if you want to continue deploying the rest of your project.


I am getting this error try to deploy firebase cloud functions.

**Comment by hadm1993** [comment]
@lotsinsights Same here. I got the same issue. I used `firebase-tools@13.11.2`

```
Error: Cloud Runtime Config is currently experiencing issues, which is preventing your functions from being deployed. Please wait a few minutes and then try to deploy your functions again.
Run `firebase deploy --except functions` if you want to continue deploying the rest of your project.
```

**Comment by YoucefSFPlus** [comment]
@lotsinsights  Same Issue for me !
