### ISSUE TITLE
Functions Runtime process hangs when invoked for an RTDB emulator trigger

### ISSUE THREAD

**Issue by IanWyszynski** [firebase/firebase-tools#1346]
### [REQUIRED] Environment info

6.10.0

**firebase-tools:**

6.10.0

**Platform:**

Debian (glinux)

### Test case/Steps to Reproduce

I started a functions emulator with the following function:

```
const functions = require('firebase-functions');
const admin = require('firebase-admin');
const firebase = require('firebase');

admin.initializeApp();

exports.helloWorld = functions.database.instance('fake-server').ref('/hello').onWrite((snapshot, context) => {
  console.log("snapshot: " + require('util').inspect(snapshot));
  console.log("context: " + require('util').inspect(context));
  return Promise.resolve();
});
```

And sent the following event to it with curl:
```
curl -X POST http://localhost:5001/functions/prver/triggers/helloWorld -d '{"name":"projects/wyszynski-test/locations/_/functions/helloWorld","eventType":"providers/google.firebase.database/eventTypes/ref.write","params":{},"auth":{"admin":true},"data":{"data":{"hello":"other"},"delta":{"hello":"oth"}},"resource":"projects/_/instances/fake-server/refs/hello","timestamp":"2019-05-30T00:45:48.069Z","eventId":"pXCmJp0rxL7JunkX0TxdAGoiiHQ="}'
```

This mocks the request that the RTDB emulators and results in the emulator blocking [here](https://github.com/firebase/firebase-tools/blob/master/src/emulator/functionsEmulator.ts#L133). It appears that something is causes the runtime's event loop to stall, which prevents the runtime process from exiting.

### Expected behavior

I think the expected behavior is that the runtime process exits and an acknowledgement is sent from the functions emulator hub to the client.

### Actual behavior

The runtime process stalls and the client hangs.

**Comment by samtstern** [comment]
Since this was an RTDB trigger I'm not entirely surprised, it's not currently in the list of "supported" trigger types in functionsEmulator.  So I bet we take the request and then do nothing. 

We should 400 faster, but also we need to add RTDB as supported.

**Comment by samtstern** [comment]
@IanWyszynski do you still see this behavior with #1347?
