### ISSUE TITLE
firebase use --add should show more user friendly names

### ISSUE THREAD

**Issue by tamalsaha** [firebase/firebase-tools#135]
I am using the new 3.0 cli. `firebase use --add` command shows the cryptic GCP project names. It will be great if cli displays more recognizable Firebase app names.

**Comment by mbleigh** [comment]
Yeah, we should definitely be showing both the GCP project name and project id. Good suggestion.

**Comment by Memeriaj** [comment]
This still only shows the project ID, but I believe that the information is actually being requested.
