### ISSUE TITLE
Firebase login Error 400

### ISSUE THREAD

**Issue by BenoitPingris** [firebase/firebase-tools#1350]
### [REQUIRED] Environment info

**firebase-tools:** 6.10

**Platform:** Arch Linux

**node** 11.15
### [REQUIRED] Test case
I enter `firebase login`, it opens an URL on my browser, I have an error 400

### [REQUIRED] Steps to reproduce
- `firebase login`

### [REQUIRED] Expected behavior
I should get a token from the URL

I get an error 400
### [REQUIRED] Actual behavior

![Screenshot_20190530_214915](https://user-images.githubusercontent.com/29386109/58660367-8fbbf800-8325-11e9-915d-5ea6647de657.png)
![Screenshot_20190530_214958](https://user-images.githubusercontent.com/29386109/58660370-8fbbf800-8325-11e9-9194-a987a4b1f354.png)

**Comment by mbleigh** [comment]
Did you try copy and pasting the full URL? The error message indicates that `response_type` wasn't provided, but it's clearly visible in the URL. I wasn't able to reproduce the issue myself just now, so I think the problem may lie elsewhere...

**Comment by bkendall** [comment]
I can replicate this exactly by deleting basically the last line of the URL (`type=code...`) in the screenshot from the browser's URL bar.

Can you confirm that the _entire_ URL is correct in the browser? Specifically, look for `response_type` (or `response_`, if it's broken, or the lack of `response` at all, etc.)

**Comment by bkendall** [comment]
hehe hi @mbleigh

**Comment by BenoitPingris** [comment]
I copied and pasted the URL directly in the browser and it worked, thanks !

The URL was automatically opened by `firebase login` and I had this error, even when I `control click` on the URL on my terminal I had the error but not when I copy it, that's weird.

**Comment by bkendall** [comment]
Strange. Well, if you see it again let us know. Without being able to replicate it easily it's hard to debug. Glad you got it working!

**Comment by saarangbond** [comment]
Copying and pasting the full url from the console worked for me.

**Comment by egranato** [comment]
I'm having the same issue but copying the url does not help... I've tried this on a mac and on windows and I get the same error.

the url i coppied for reference:
`https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=855321154&redirect_uri=http%3A%2F%2Flocalhost%3A9005`
