### ISSUE TITLE
running npm install results in the following error, npm ERR! Unexpected end of JSON input while parsing near '...":"sha512-IxInm1vKWBg'

### ISSUE THREAD

**Issue by bishoplee** [firebase/firebase-tools#1351]
### [REQUIRED] Environment info

**firebase-tools:**

**Platform:**

**Comment by samtstern** [comment]
@bishoplee there's not enough information here to help you.  In fact it's not even clear this is related to the Firebase CLI at all.  Please fill out the issue template when filing an issue.
