### ISSUE TITLE
Firebase deploy getting  HTTP Error: 400, Request contains an invalid argument.

### ISSUE THREAD

**Issue by rodelrebucas** [firebase/firebase-tools#1352]
### [REQUIRED] Environment info

**firebase-tools:**
6.10.0

!-- e.g. macOS, Windows, Ubuntu -->
**Platform:**
macOs

### [REQUIRED] Test case

I just trying to deploy everything from my firebase.json

```
{
  "firestore": {
    "rules": "firestore.rules",
    "indexes": "firestore.indexes.json"
  },
  "storage": {
    "rules": "storage.rules"
  }
}
```

### [REQUIRED] Steps to reproduce

firebase deploy

### [REQUIRED] Expected behavior

Should deploy successfully. And gives me a link or success response.

### [REQUIRED] Actual behavior

Returns:

 `HTTP Error: 400, Request contains an invalid argument.`

[debug] [2019-05-31T05:24:48.230Z] ----------------------------------------------------------------------
[debug] [2019-05-31T05:24:48.233Z] Command:       /Users/rodel/.nvm/versions/node/v10.15.3/bin/node /Users/rodel/.nvm/versions/node/v10.15.3/bin/firebase deploy --debug
[debug] [2019-05-31T05:24:48.233Z] CLI Version:   6.10.0
[debug] [2019-05-31T05:24:48.234Z] Platform:      darwin
[debug] [2019-05-31T05:24:48.234Z] Node Version:  v10.15.3
[debug] [2019-05-31T05:24:48.234Z] Time:          Fri May 31 2019 13:24:48 GMT+0800 (Philippine Standard Time)
[debug] [2019-05-31T05:24:48.235Z] ----------------------------------------------------------------------
[debug] 
[debug] [2019-05-31T05:24:48.247Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2019-05-31T05:24:48.248Z] > authorizing via signed-in user
[debug] [2019-05-31T05:24:48.249Z] [iam] checking project <replace-with-user-firebase-project> for permissions ["cloudfunctions.functions.create","cloudfunctions.functions.delete","cloudfunctions.functions.get","cloudfunctions.functions.list","cloudfunctions.functions.update","cloudfunctions.operations.get","datastore.indexes.create","datastore.indexes.delete","datastore.indexes.list","datastore.indexes.update","firebase.projects.get","firebaserules.releases.create","firebaserules.releases.update","firebaserules.rulesets.create"]
[debug] [2019-05-31T05:24:48.250Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects/<replace-with-user-firebase-project>:testIamPermissions  

[debug] [2019-05-31T05:24:49.705Z] <<< HTTP RESPONSE 400
[debug] [2019-05-31T05:24:49.705Z] <<< HTTP RESPONSE BODY
[error] 
[error] Error: HTTP Error: 400, Request contains an invalid argument.
[debug] [2019-05-31T05:24:49.710Z] Error Context: {
  "body": {
    "error": {
      "code": 400,
      "message": "Request contains an invalid argument.",
      "status": "INVALID_ARGUMENT"
    }
  },
  "response": {
    "statusCode": 400,
    "body": {
      "error": {
        "code": 400,
        "message": "Request contains an invalid argument.",
        "status": "INVALID_ARGUMENT"
      }
    },
    "headers": {
      "vary": "X-Origin, Referer, Origin,Accept-Encoding",
      "content-type": "application/json; charset=UTF-8",
      "date": "Fri, 31 May 2019 05:24:49 GMT",
      "server": "ESF",
      "cache-control": "private",
      "x-xss-protection": "0",
      "x-frame-options": "SAMEORIGIN",
      "x-content-type-options": "nosniff",
      "server-timing": "gfet4t7; dur=931",
      "alt-svc": "quic=\":443\"; ma=2592000; v=\"46,44,43,39\"",
      "accept-ranges": "none",
      "transfer-encoding": "chunked"
    },
    "request": {
      "uri": {
        "protocol": "https:",
        "slashes": true,
        "auth": null,
        "host": "cloudresourcemanager.googleapis.com",
        "port": 443,
        "hostname": "cloudresourcemanager.googleapis.com",
        "hash": null,
        "search": null,
        "query": null,
        "pathname": "/v1/projects/%3Creplace-with-user-firebase-project%3E:testIamPermissions",
        "path": "/v1/projects/%3Creplace-with-user-firebase-project%3E:testIamPermissions",
        "href": "https://cloudresourcemanager.googleapis.com/v1/projects/%3Creplace-with-user-firebase-project%3E:testIamPermissions"
      },
      "method": "POST"
    }
  }
}

**Comment by rodelrebucas** [comment]
Resolved , forgot to update my `.firebaserc`, it contains an invalid character: 

> "<>"

**Comment by jojonarte** [comment]
@rodelrebucas nice

**Comment by tomasatisocco** [comment]
@ryrebs Where is the .firebaserc?
