### ISSUE TITLE
Unable to deploy callable function when exported alongside trigger functions

### ISSUE THREAD

**Issue by inorganik** [firebase/firebase-tools#1357]
### [REQUIRED] Environment info

**firebase-tools:** 6.4.0

**Platform:** macOS

### [REQUIRED] Test case

I recently added a new callable function to my project. When I tried

```firebase deploy --only functions:stripeOperation```

It resulted in

> ⚠  functions: the following filters were specified but do not match
> any functions in the project: stripeOperation

The file structure is like this:
```
    functions/
    ├── src/
    │   ├── stripe
    │   │    ├── index.ts
    │   │    ├── myTrigger.ts
    │   │    ├── anotherTrigger.ts
    │   │    └── stripeOperation.ts
    │   ├── index.ts
```
`functions/src/stripe/index` exported all 3 of the functions in the stripe folder:
```
export { stripeOperation } from './stripeOperation';
export { myTrigger } from './myTrigger';
export { anotherTrigger } from './anotherTrigger';
```
`functions/src/index` exported them from the stripe folder:
```
export { stripeOperation, myTrigger, anotherTrigger } from './stripe';
```

I discovered I could only deploy my callable function if it was exported _separately_ from the trigger functions, otherwise I would get the "filters do not match" warning and it wouldn't get deployed.

`functions/src/index`:
```
export { stripeOperation } from './stripe/stripeOperation';
export { myTrigger, anotherTrigger } from './stripe';
```

### [REQUIRED] Steps to reproduce

Create a trigger function and a callable function in a sub folder, and export them together, then try to deploy the callable function.

### [REQUIRED] Expected behavior

You should be able to deploy callable and trigger functions that are exported together.

### [REQUIRED] Actual behavior

You have to export them separately, or the callable function will get skipped.

**Comment by thechenky** [comment]
Hi @inorganik please specify what version of Node you're using to run the `firebase` command, in addition to the versions of Node you're using for your functions. Also, please provide the output of running `firebase deploy --debug`. Without this information it's difficult to diagnose what may be happening.

**Comment by inorganik** [comment]
Hi @thechenky, I am running node 8.15 (I have .nvmrc in functions folder so that I can run the same version of node that firebase does). I also specify in my package.json inside functions folder: 

```
  "engines": {
    "node": "8"
  }
```

Running with `--debug` flag, my console is mostly filled up with file map code, e.g.:
```
65454=112, 65455=33, 65456=4, 65457=163, 65458=93, 65459=11, 65460=137, 65461=82, 65462=233, 65463=142, 65464=59, 65465=176, 65466=168, 65467=90, 65468=225, 65469=159, 65470=1, 65471=49, 65472=149, 65473=7, 65474=255, 65475=23, 65476=168, 65477=167, 65478=29, 65479=137, 65480=77, 65481=1, 65482=104, 65483=146, 65484=144, 65485=75, 65486=240, 65487=44, 65488=183, 65489=107, 65490=113, 65491=152, 65492=153, 65493=191, 65494=19, 65495=100, 65496=154, 65497=211, 65498=167, 65499=163, 65500=225, 65501=106, 65502=64, 65503=37, 65504=7, 65505=107, 65506=48, 65507=138, 65508=165, 65509=136, 65510=54, 65511=152, 65512=5, 65513=222, 65514=120, 65515=136, 65516=160, 65517=214, 65518=206, 65519=6, 65520=55, 65521=6, 65522=133, 65523=101, 65524=6, 65525=229, 65526=137, 65527=176, 65528=207, 65529=224, 65530=105
``` 
but I can tell you when I tried again to export them together, as described in my issue, it prompted me if I wanted to delete my callable function `stripeOperation` because it could not be found. This is just because I exported them together:
```
export { stripeOperation, myTrigger, anotherTrigger } from './stripe';
```
As long as I export them separately the bug does not occur:
```
export { myTrigger, anotherTrigger } from './stripe';
export { stripeOperation } from './stripe/stripeOperation';
```

So I know the debug flag was not much help but this is very easy to reproduce - simply create a callable function and a trigger function in a folder, create an index file to export them together and you should run into this.

**Comment by inorganik** [comment]
@thechenky I see I ended up with a .log file from the --debug file, I can email it to you if you like but I'd rather not post it publicly.

**Comment by thechenky** [comment]
Hi @inorganik, the `--debug` should have more than just the mappings as you posted. I would just want to see the last lines near when the parsing of the functions fails, which I don't believe should have much sensitive information. If you're still not comfortable pasting that here, you can go through our support channel: https://firebase.google.com/support

**Comment by inorganik** [comment]
Here's everything that's after the mappings:

> $ref=$["_readableState"]["buffer"]["head"], length=1, length=65536, pipes=null, pipesCount=0, flowing=null, ended=false, endEmitted=false, reading=false, sync=false, needReadable=false, emittedReadable=true, readableListening=false, resumeScheduled=false, destroyed=false, defaultEncoding=utf8, awaitDrain=0, readingMore=false, decoder=null, encoding=null, readable=true, domain=null, end=function () {
>     if (this.autoClose) {
>       this.destroy();
>     }
>   }, _eventsCount=1, _maxListeners=undefined, path=/var/folders/wg/3c_22ndx2fl8dw3dr64q7fxr0000gn/T/firebase-functions-9984Q5mofFXvnD72.zip, fd=18, flags=r, mode=438, start=undefined, end=Infinity, autoClose=true, pos=undefined, bytesRead=65536
> [2019-06-04T12:42:15.224Z] <<< HTTP RESPONSE 200 x-guploader-uploadid=AEnB2Uq7HRzqlGUcsU1-7-pJXoXlvWjhUSAvSYw8ZHPP1KJqnsZwfDx-8krETYyPEW-nyKRoproE4fMtG9iUo7kmGxigKNyfx2viWbvls3kWFbc5jvVg4Fg, etag="eac7665bf43285ab30b378b657b40478", x-goog-generation=1559652139994912, x-goog-metageneration=1, x-goog-hash=crc32c=4p+6XA==, md5=6sdmW/Qyhasws3i2V7QEeA==, x-goog-stored-content-length=3855738, x-goog-stored-content-encoding=identity, vary=Origin, content-length=0, date=Tue, 04 Jun 2019 12:42:20 GMT, server=UploadServer, content-type=text/html; charset=UTF-8, alt-svc=quic=":443"; ma=2592000; v="46,44,43,39"
> ✔  functions: functions folder uploaded successfully
> [2019-06-04T12:42:15.227Z] >>> HTTP REQUEST GET https://cloudfunctions.googleapis.com/v1/projects/XXXXXXX/locations/-/functions  
>  
> [2019-06-04T12:42:15.674Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Tue, 04 Jun 2019 12:42:20 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="46,44,43,39", accept-ranges=none, transfer-encoding=chunked
> [2019-06-04T12:42:15.677Z] > [functions] filtering triggers to: [
>   "projects/XXXXXXX/locations/us-central1/functions/stripeOperation"
> ]
> i  functions: current functions in project: <list of functions here, I removed for privacy. It includes stripeOperation because I was able to previously deploy it with my workaround>
> i  functions: uploading functions in project: stripeOperation(us-central1)
> 
> The following functions are found in your project but do not exist in your local source code:
>         stripeOperation(us-central1)
> 
> If you are renaming a function or changing its region, it is recommended that you create the new function first before deleting the old one to prevent event loss. For more info, visit https://firebase.google.com/docs/functions/manage-functions#modify
> 
> ? Would you like to proceed with deletion? Selecting no will continue the rest of the deployments. (y/N) 

I selected `N` and that ended the script. As I mentioned I found a workaround so I have deployed the function before, but this is what happens when you try to deploy it exported with trigger functions.

**Comment by thechenky** [comment]
@inorganik - curious if this still happens if you upgrade to CLI v.6.12.0? Also, which version of firebase-functions are you using?

**Comment by mbleigh** [comment]
Can you share the compiled `.js` code that is created from the TypeScript? That seems like the most likely culprit for the problem.

**Comment by inorganik** [comment]
@thechenky unfortunately I just updated to 6.12 and the same problem occurred.

@mbleigh I'd rather not, but it should help to know that when exported separately, each one deploys just fine. The only difference is the compiled index files, in the root and in the stripe directory. They look as you would expect:

/stripe:
```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var onMemberCreate_1 = require("./onMemberCreate");
exports.onMemberCreate = onMemberCreate_1.onMemberCreate;
var onMemberRemove_1 = require("./onMemberRemove");
exports.onMemberRemove = onMemberRemove_1.onMemberRemove;
var stripeOperation_1 = require("./stripeOperation");
exports.stripeOperation = stripeOperation_1.stripeOperation;
//# sourceMappingURL=index.js.map
```

index in root (the section containing the stripe exports):
```
var stripe_1 = require("./stripe");
exports.onMemberCreate = stripe_1.onMemberCreate;
exports.onMemberRemove = stripe_1.onMemberRemove;
exports.stripeOperation = stripe_1.stripeOperation;
```
Since I've found a workaround for this (exporting separately), I'm really not concerned about this issue. I just thought I should open this issue because it doesn't jive with a standard node workflow.

However, there are 2 other issues that are currently blocking the deployment of my app and these are much, much more concerning to me (I believe they are related).
 
- https://github.com/angular/angularfire2/issues/2107
- https://github.com/firebase/firebase-js-sdk/issues/1696

I've gone to the trouble of creating a repo that repoduces the problem - it only happens in prod,  and have not heard back from anyone - I'd really appreciate a response. Thanks.

**Comment by bkendall** [comment]
@inorganik I've been following along on this issue and took the time to make a sample repository that's structured as you suggested: https://github.com/bkendall/studious-succotash

In that directory, I can deploy to my project using both:

```
firebase deploy --project <id>
firebase deploy --project <id> --only functions:nestedOperation
```

I am unable to replicate the behavior you are seeing.

To be able to debug this further, we need to be able to reliably reproduce the issue. If you have a moment, give the `studious-succotash` repository a look and try it out on your machine. If I've set it up incorrectly, please make a PR against that repo and respond respond back to this issue.

Unfortunately, without more information, we're going to be unable to help out much more on this particular issue. Thanks for the bug report - we will keep our eyes open for any other occurrences of this problem.

**Comment by inorganik** [comment]
@bkendall thanks Bryan but that isn't correctly reproduced. The issue occurs when you export **_a callable function alongside a trigger function_**. You are exporting two callable functions and as you mentioned that doesn't reproduce the problem.

**Comment by bkendall** [comment]
Ah. Got it. I updated the repository with a [Firebase-triggered function](https://github.com/bkendall/studious-succotash/blob/master/functions/src/stripe/other.ts#L6-L8)

Still, `deploy` works, `deploy --only functions:<name>` works. I'm still unable to reproduce this behavior.

If you can make a PR against that [sample repo](https://github.com/bkendall/studious-succotash) that actually breaks the deploy, it would help a lot.

There must be something subtle that's happening that we're not catching. In your `firebase.json`, do you have any `predeploy` commands in place? (There are some by default in the typescript setup)

**Comment by inorganik** [comment]
Thanks Bryan, I appreciate your efforts. I'm not doing any predeploy commands. Just curious, when you tried the `deploy --only`, which function did you try it with? I found that only the callable function had the issue.

**Comment by bkendall** [comment]
> I'm not doing any predeploy commands.

So, to be very clear, your `firebase.json` does not have [a predeploy block](https://github.com/bkendall/studious-succotash/blob/master/firebase.json#L3)?

> which function did you try it with?

Both `other` and `nestedOperation`. Both succeeded.

**Comment by inorganik** [comment]
I'm surprised they both succeeded. I was looking at your tsconfig and saw one difference. You might try adding `"lib": ["es2017", "dom"],` under `compilerOptions` and see if you can still deploy the callable.

Looks like I do have some predeploy commands, just lint and build.

```
"predeploy": [
  "npm --prefix \"$RESOURCE_DIR\" run lint",
  "npm --prefix \"$RESOURCE_DIR\" run build"
],
```

**Comment by bkendall** [comment]
Adding those `lib` arguments did not cause the issue. It's possible that there's some file conflicting in the output directory (`lib/`) that could be causing the issue? I assume you've removed the `lib/` folder, re-created it, and deployed?

I'm running pretty thin on ideas. Without sitting at the same terminal and debugging (or a reliable repro), it's pretty hard to nail this one down. If you have any other ideas to try, do let me know...

**Comment by inorganik** [comment]
Yea. The only other thing is the callable function imports functions from other files in the same folder. It's ok if you want to close this, as I have a workaround (export separately).

**Comment by inorganik** [comment]
nevermind, already closed ;)
