### ISSUE TITLE
URGENT: Auth error:Error: internal_failure, error: The service is currently unavailable

### ISSUE THREAD

**Issue by Dara-To** [firebase/firebase-tools#1361]
My Firebase project's functions stops running since 2:46PM Eastern time. At the same time, I was developing and running test functions in shell and got these errors since then:

```
error: Auth error:Error: internal_failure
error: Auth error:Error: The service is currently unavailable.
info: Execution took 24791 ms, finished with status: 'crash' 
```

At first, CLI asked me to do `firebase login --reauth` and it crashed a few time with server response code of 500.

This is URGENT as some users reported that they cannot use our website! Please help! !! Thanks!
 
### [REQUIRED] Environment info

**firebase-tools:**

**Platform:** macOS

These are the dependencies in my package.json

"dependencies": {
    "@google-cloud/storage": "^2.5.0",
    "@types/intercom-client": "^2.9.4",
    "@types/stripe": "^6.0.3",
    "child-process-promise": "^2.2.1",
    "cors": "^2.8.4",
    "firebase-admin": "^5.13.1",
    "firebase-functions": "^2.0.5",
    "firebase-tools": "^4.2.1",
    "intercom-client": "^2.10.3",
    "mailgun-js": "^0.20.0",
    "node-fetch": "^2.2.0",
    "secure-compare": "^3.0.1",
    "stripe": "^6.8.0"
  },
  "devDependencies": {
    "tslint": "^5.11.0",
    "typescript": "^3.4.5"
  },
  "private": true,
  "engines": {
     "node": "8"
  }

I migrated the functions from node.js runtime `6` to `8` and es from `es6` to `es2017` yesterday and there was no problem since then until now. I followed the steps from this Firebase bog: https://firebase.googleblog.com/2018/08/cloud-functions-for-firebase-config-node-8-timeout-memory-region.html

### [REQUIRED] Test case

None. If required, let me know.

### [REQUIRED] Steps to reproduce

While testing functions locally.

->`sudo npm run-script shell`

`Error: Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth
`

->`firebase login --reauth`

> 500. That’s an error.
> There was an error. Please try again later. That’s all we know.
> 

I then tried to do `firebase logout` then `firebase login`. Login was successful.

> Woohoo!
> Firebase CLI Login Successful
> You are logged in to the Firebase Command-Line interface. You can immediately close this window and continue using the CLI.

If and when the shell worked and tired running my local functions by sending an http request, I got this:

```
error: Auth error:Error: internal_failure
error: Auth error:Error: The service is currently unavailable.
info: Execution took 24791 ms, finished with status: 'crash' 
```

### [REQUIRED] Expected behavior

The very least is to see my functions logs running in firebase console.

### [REQUIRED] Actual behavior

No more functions logs since an hour ago.

```
Error: Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! functions@ shell: `NODE_ENV=development npm run build && firebase functions:shell`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the functions@ shell script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/darato/.npm/_logs/2019-06-02T19_50_01_211Z-debug.log
```

**Comment by thechenky** [comment]
Hi @Dara-To there is an ongoing incident right now with Cloud Function deployments: https://cloud-status.googleplex.com/firebase/incident/Functions/19016.

**Comment by thechenky** [comment]
@Dara-To Ah, sorry I misread your issue - however, I think it's still coming from the same upstream outage that is affecting function deployments. Many of the Firebase services are affected. Can you paste the debug log of when you run `firebase login --reauth`?

**Comment by Dara-To** [comment]
Thanks for the quick response! That explains it.

But when I tried to go to your link, I got this:
<img width="250" alt="Screen Shot 2019-06-02 at 4 10 31 PM" src="https://user-images.githubusercontent.com/33760969/58766817-2a4c4f00-8551-11e9-990d-eac2eec4a6be.png">

**Comment by rockwotj** [comment]
@Dara-To wrong link, see: https://status.firebase.google.com/incident/Functions/19016

**Comment by thechenky** [comment]
Apologies, I accidentally gave you an internal link - thanks @rockwotj for the correction!

**Comment by Dara-To** [comment]
There is no debug log after I type `firebase login --reauth`. I already gave the error before I type that command though. Here is the print screen when I tried to re-authenticate.

<img width="300" alt="Screen Shot 2019-06-02 at 3 53 08 PM" src="https://user-images.githubusercontent.com/33760969/58766843-ac3c7800-8551-11e9-9ccc-428493040ee0.png">

**Comment by rockwotj** [comment]
Yes, you'll likely see errors until the incident is over.

**Comment by Dara-To** [comment]
The status page says that **Cloud Functions deployments failing**. Is it only for trying to deploy functions locally or to prod? Or it affects also the functions already deployed? Since I have no more logs from 1.5 hour ago, it seems it's the latter case.

**Comment by thechenky** [comment]
@Dara-To there are several Firebase services affected. The outage I posted here was relating to failures when trying to deploy cloud functions to production. Local emulation should not be affected to my understanding. I'm not sure whether running functions are affected, but that could be a possibility since the upstream outage is related to networking: https://status.cloud.google.com/incident/cloud-networking/19009

**Comment by Dara-To** [comment]
Thanks for the clarification. It seems the outage affects more than that. I cannot read my Firestore data anymore at the moment.

<img width="150" alt="Screen Shot 2019-06-02 at 4 47 19 PM" src="https://user-images.githubusercontent.com/33760969/58767253-8e254680-8556-11e9-952c-55fa01ec8572.png">

**Comment by Dara-To** [comment]
All is back to normal. My functions in prod are running but are on backlogs since the issue was resolved. Thanks for keeping me in the loop.

**Comment by thechenky** [comment]
Yes, things should be back to normal now! Thanks @Dara-To and please don't hesitate to post again should you encounter any other issues.

**Comment by samtstern** [comment]
@Dara-To just FYI, if you ever have an urgent issue in the future where you're seeing service issues you'll want to contact [firebase support](https://firebase.google.com/support) rather than going to GitHub as they will be much better equipped to help (although in this case @thechenky did a great job on a weekend).
