### ISSUE TITLE
Some HTTP methods are not allowed

### ISSUE THREAD

**Issue by notapineapple** [firebase/firebase-tools#1365]
### [REQUIRED] Environment info

**firebase-tools:** 6.10.0 (latest)

**Platform:** macOS Mojave

### [REQUIRED] Test case

I'm just trying to use DELETE method over an express app and a express-like function and it gives me "Cannot [method] [path]" like "Cannot DELETE /i/am/a/url".

### [REQUIRED] Steps to reproduce

This is my testing snippet i'm using to trying figure out the error. I just bind this express app to an HTTP function.

```
import express from 'express'
import asyncHandler from 'express-async-handler'
import cors from 'cors'

const app = express()

app.use(cors({ origin: true }))

app.delete('/:id?', asyncHandler(async (req, res) => {
  const { params } = req
  res.send('hello')
}))

app.all('/*', (req, res) => {
  res.status(403).send('Not allowed')
})

export default app
```

### [REQUIRED] Expected behavior

Work with all HTTP methods like firebase-tools versions from past.

### [REQUIRED] Actual behavior

<img width="720" alt="Screen Shot 2019-06-03 at 5 13 29 PM" src="https://user-images.githubusercontent.com/3385668/58838053-1c66fe80-8623-11e9-822d-a55be6b06c52.png">

**Comment by samtstern** [comment]
@notapineapple nice try, obvious pineapple.

This was fixed by https://github.com/firebase/firebase-tools/pull/1332 and will be included in the next release.  Thanks for reporting!
