### ISSUE TITLE
firebase list gives refresh token revoked error

### ISSUE THREAD

**Issue by brianneisler** [firebase/firebase-tools#137]
When running `firebase list` i'm given the error 
```
Error: Your refresh token has been revoked, please run firebase login to obtain a new one.
```
I then logout using `firebase logout` and log back in via `firebase login`

Still get the same error afterward.

**Comment by mbleigh** [comment]
Are you trying to share your credentials between multiple computers? Does this happen every time after you run a command? Are you doing any kind of credential or access management on your Firebase project in between commands?

Typically tokens are only revoked on explicit logout. Not quite sure what's happening here...

**Comment by drtriumph** [comment]
It's also possible if you have too many machines logging in as the same user, old refresh tokens will be expired. It looks like the current limit is 25: http://stackoverflow.com/a/26136111/937583

**Comment by mbleigh** [comment]
Without more info, I'm not able to reproduce. Please feel free to reopen if you're still having trouble and have some more data for us :smile:

**Comment by brianneisler** [comment]
Hi @mbleigh, sorry been busy with work and gave up on this. I got the error after trying to upgrade my library to the 3.0 tools library. I think the problem may have been that I haven't migrated my database to the new 3.0 FB console. Once i downgraded the tools everything works fine again.
