### ISSUE TITLE
Error deploying cloud functions with region europe-west2 (London)

### ISSUE THREAD

**Issue by BarNiedzielski** [firebase/firebase-tools#1382]
### [REQUIRED] Environment info

**firebase-tools:** 6.11.0

**Platform:** Windows

### [REQUIRED] Test case

I'm trying to deploy functions with selected region europe-west2.
According to [documentation](https://cloud.google.com/functions/docs/locations)  it should work.
`const functions = require('firebase-functions');
exports.fun= functions.region('europe-west2').https.onRequest((res) => res.ok());`

### [REQUIRED] Steps to reproduce

`firebase deploy --only functions`

### [REQUIRED] Expected behavior

Function should deploy.
### [REQUIRED] Actual behavior

I'm getting error:
> Error: The only valid regions are 'us-central1', 'us-east1', 'europe-west1', and 'asia-northeast1'

**Comment by thechenky** [comment]
It looks like you probably need to update your firebase-functions SDK, can you try that and see if it helps?

**Comment by BarNiedzielski** [comment]
You're right. I have outdated SDK. After update everything works. Thanks for your help.
