### ISSUE TITLE
firebase emulators:exec status code is 0 even when command fails

### ISSUE THREAD

**Issue by therefromhere** [firebase/firebase-tools#1385]
### [REQUIRED] Environment info

**firebase-tools:**
6.11.0

**Platform:**
Ubuntu 18.04

### [REQUIRED] Test case

I would expect emulators:exec to return non-zero if the exec'd command returns non-zero, but it doesn't.

This is a problem in a CI context where I expected non-zero status to indicate test failure.

### [REQUIRED] Steps to reproduce

```
firebase emulators:exec "false"
echo $?
```

### [REQUIRED] Expected behavior

I'd expect status (`$?`) to be 1

### [REQUIRED] Actual behavior

```
$ firebase emulators:exec "false"
i  Starting emulators: ["firestore"]
i  firestore: Logging to firestore-debug.log
✔  firestore: Emulator started at http://localhost:8080
i  firestore: For testing set FIREBASE_FIRESTORE_EMULATOR_ADDRESS=localhost:8080
i  Running script: false
⚠  Script exited unsuccessfully (code 1)
i  Shutting down emulators.
i  Stopping firestore emulator
$ echo $?
0
```

**Comment by samtstern** [comment]
@therefromhere thanks for reporting this!  You're right, this is something we should change.
