### ISSUE TITLE
Accessing Firestore emulator from the Functions emulator crashes

### ISSUE THREAD

**Issue by aputinski** [firebase/firebase-tools#1404]
### [REQUIRED] Environment info
**firebase-tools:** 7.0.0
**Platform:** macOS 10.14.6
**Node.js** 10.15.3

### [REQUIRED]  Test case

https://github.com/aputinski/firebase-tools-test-case

### [REQUIRED]  Expected behavior

Accessing Firestore emulator from the Functions emulator should not crash.

### [REQUIRED] Actual behavior

Function crashes with the following error message:

```
Error: Getting metadata from plugin failed with error: this.channel.credentials._getCallCredentials is not a function
```

**Comment by samtstern** [comment]
@aputinski thanks for filing the issue with a detailed test case!  Let me see if I can figure out what's going on.

**Comment by ryanmtaylor** [comment]
From what I noticed, this happens in firebase-admin@8.1.0 but not firebase-admin@7.4.1 and it has to do with the `@grpc/grpc-js` module

**Comment by samtstern** [comment]
@ryanmtaylor thanks that makes sense actually.  We have code to try and detect your dependencies and stub out some grpc code, I guess we got it wrong for `grpc-js`.

**Comment by samtstern** [comment]
This turned out to be a simple fix, thanks for making it so clear!

**Comment by aputinski** [comment]
Thanks for the quick fix! Any idea when this fix will be published?

**Comment by samtstern** [comment]
@aputinski it's merged and will be part of the next patch release. No promises on timeline but we seem to do one of those almost every week.
