### ISSUE TITLE
Document complete schema for `firebase.json`

### ISSUE THREAD

**Issue by samtstern** [firebase/firebase-tools#1409]
Originally suggested by @matheo here:
https://github.com/firebase/firebase-tools/issues/1303#issuecomment-502407506

We should document the complete schema of `firebase.json` in both human-readable and machine-readable formats.  This file has expanded a lot and it's not always clear what's there and what the defaults are.

**Comment by bkendall** [comment]
Related: https://firebase.google.com/docs/cli/#the_firebasejson_file

**Comment by long1eu** [comment]
Any news on this?

**Comment by johnnyasantoss** [comment]
Any updates?

The provided link has a section called "The firebase.json file" that is not helpful. I still think that a json schema (like [these ones](http://schemastore.org/json/)) would be a better way to add documentation to this mysterious file.

**Comment by george43g** [comment]
so this repo: https://github.com/SirWindfield/vscode-firebase-configuration-schema-plugin

Is a plugin for Vscode that supplies it with a schema for firebase.json

I agree that a schema is needed, at least for autocomplete benefits. That repo is outdated and archived, I do not believe it's maintained. However, it contains a valid and working schema for firebase.json.

PS: I'm tempted to fork the repo and update it... does anyone else want to help out?

**Comment by samtstern** [comment]
@george43g if you do decide to contribute to that repo I would be happy to review your pull requests (I can't approve them, but I can at least give a Firebase stamp of approval).

We actually have a few different needs around documenting the firebase.json schema:

1. It would be great to have a TypeScript definition for use within this repository, right now it's all a lot of `any` when dealing with `firebase.json`
2. We need some way to generate reference documentation for this file to host on firebase.google.com ... we use `externs.js` files in a lot of places now because our tooling supports it but I don't want to double down on that.
3. We need to give developers like all of you autocomplete support in your editors.  I assume JSON Schema is the most standardized way to do this?  But maybe not ...

**Comment by jthegedus** [comment]
>We need to give developers like all of you autocomplete support in your editors. I assume JSON Schema is the most standardized way to do this?

@samtstern Yes, JSON Schema is the most standard way to support autocomplete in editors. IntelliJ uses this by default and VSCode can have support added by individual extensions as @george43g shows or by using popular plugins like the [RedHat YAML](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml) plugin which pulls from JSON Schema store and provides both YAML and JSON autocomplete for all available schemas.

**Comment by sshquack** [comment]
Came here form https://github.com/firebase/firebase-tools/issues/2233#issuecomment-627323850 Currently it very confusing to piece together globs of json from multiple locations without knowing the source of truth. Here are some of the scattered configs from the docs for reference:

https://firebase.google.com/docs/cli#the_firebasejson_file
https://firebase.google.com/docs/hosting/full-config#firebase-json_example
https://firebase.google.com/docs/hosting/full-config
https://firebase.google.com/docs/functions/manage-functions
https://firebase.google.com/docs/hosting/test-preview-deploy
<and a bunch more links>

Also as @jthegedus pointed out JSON schemas for popular plugins are embedded in IntelliJ (see https://www.jetbrains.com/help/idea/json.html#ws_json_using_schemas) using SchemaStore (see https://www.schemastore.org/json/)
![Screen Shot 2021-02-08 at 4 30 14 PM](https://user-images.githubusercontent.com/5678459/107298936-37f6ef00-6a2b-11eb-815e-46fdf107f0c2.png)
It would be very beneficial to have the full firebase.json schema documented for developer productivity.

**Comment by jthegedus** [comment]
I'd like to add, having a utility function that validates a Firebase configuration would also be helpful (whether by the json schema or otherwise). I implemented a tool recently that reads a provided Firebase config and needed to implement a large Joi validation to check to ensure when Firebase rewrites to a Cloud Funtion that the `functions` config exists and is valid. It was painful and probably full of bugs.

**Comment by samtstern** [comment]
If anyone is still waiting on this, you can check out a JSON Schema for `firebase.json` here:
https://github.com/firebase/firebase-tools/blob/master/schema/firebase-config.json

This is just our first attempt to define the schema officially so it's possible that there are some configurations allowed in the real world that disagree with that file, please let me know if you find anything like that!

Right now if we find JSON schema errors it's only exposed in `firebase-debug.log` but in a future CLI version we will make those more visible.

**Comment by jthegedus** [comment]
This is a great step @samtstern cheers!

A use case that I am not sure JSON Schemas can cover is when a rewrite rule is defined to rewrite to a function, but the `functions` field is missing. I guess the default values for the `functions` object would be used :thinking: So I guess the request would be to the ability to parse a config that:

1. validates a provided config against the JSON schema
2. returned the computed config. That is, the config combined with the defaults.

Currently even if I were to use this JSON Schema (and I will) to validate a config, I still have to hardcode the default values in my tool, like `config.functions.source = "functions"`.

**Comment by samtstern** [comment]
@jthegedus yeah the implicit defaults for products like Functions are definitely a bit of a problem here.

Can you explain why you'd need to hardcode `config.functions.source = "functions"`? The config is valid without that.

**Comment by jthegedus** [comment]
Sorry, that example goes back to my prior comments above.

I've built [`svelte-adapter-firebase`](https://github.com/jthegedus/svelte-adapter-firebase) which parses a users `firebase.json` file. If they define a rewrite rule to a function, I need to then parse their `functions` entrypoint, which requires knowing `functions.source` or fallback to the default value defined in `firebase-tools`. So my tool hardcodes the default location of `./functions/`.

`firebase-tools` CLI is run after my tool. As a plugin for [`SvelteKit`](https://kit.svelte.dev) it runs during app build, so I have to parse the config myself to ensure it has a valid configuration before this tool is even executed. It would be great if this tool provided a parser, similar to other IaC CLIs/APIs/Packages like https://github.com/architect/parser , that not only validated, but returned the computed final config with the defaults and all if omitted in the input config.

**Comment by jthegedus** [comment]
An alternative to my above suggestiong would be to have all the default config values defined in a single JS object. Last I checked the defaults are spread throughout the source code and difficult to find. As are the validation checks.

**Comment by samtstern** [comment]
@jthegedus wow good eye! If you want to update the schema, you could send a PR here. The TypeScript is the source of truth:
https://github.com/firebase/firebase-tools/blob/master/src/firebaseConfig.ts

I agree we need to centralize the defaults. One of the issues is that they're a bit context dependent! For instance it's not true to say that the default for `functions` is `{ source: "functions" }` because actually we only consider that default _if_ you run a functions-specific command and we detect a `functions/package.json` file. So it's a bit of a mess!

**Comment by jthegedus** [comment]
>For instance it's not true to say that the default for `functions` is `{ source: "functions" }` because actually we only consider that default if you run a functions-specific command and we detect a `functions/package.json` file. So it's a bit of a mess!

In the context of my usage I only look for `functions` if I first detect a Hosting Rewrite Rule that rewrites to a function, then I perform the lookup of `functions.source` or fallback.

The context-dependent implementation does make this difficult.

**Comment by zanona** [comment]
It would be great if you could allow the `$schema` field on the JSON, so we could do this:

firebase.json
```jsonc
{
  "$schema": "./node_modules/firebase-tools/schema/firebase-config.json",
  "hosting": [...]
}
``` 

similar to what [turborepo does](https://turborepo.org/docs/reference/configuration#globaldependencies), as it's great for validation.

**Comment by junaga** [comment]
why is my VS Code complaining?

![image](https://github.com/firebase/firebase-tools/assets/35770913/dd4de1c2-d60b-4ba5-8bd8-43b9cab8afd1)

**Comment by o-az** [comment]
Pointing to the schema file from [`firebase-tools`](https://github.com/firebase/firebase-tools/blob/master/schema/firebase-config.json) repo directly is the most convenient

```json
{
  "$schema": "https://raw.githubusercontent.com/firebase/firebase-tools/master/schema/firebase-config.json",
  "functions": {
    "source": "./"
  },
  // ...
}
```

**Comment by Goldziher** [comment]
can you guys publish this?
