### ISSUE TITLE
Firestore triggers broken in emulator

### ISSUE THREAD

**Issue by aputinski** [firebase/firebase-tools#1417]
### [REQUIRED] Version info

**node:** 10.15.3

**firebase-functions:** 3.0.0

**firebase-tools:** 7.0.0

**firebase-admin:** 8.0.0

### [REQUIRED] Test case

https://github.com/aputinski/firebase-functions-test-case

### [REQUIRED] Steps to reproduce

See README in repo above

### [REQUIRED] Expected behavior

```
functions: Beginning execution of "onWrite"
functions: Finished "onWrite" in ~1s
```

### [REQUIRED] Actual behavior

```
TypeError: Cannot read property 'eventType' of undefined
```

It looks like the data and context are being combined into the first argument

https://github.com/firebase/firebase-functions/blob/master/src/cloud-functions.ts#L242

### Were you able to successfully deploy your functions?

N/A

**Comment by aputinski** [comment]
Thanks!

**Comment by thechenky** [comment]
@samtstern FYI, I think this is similar to the issue with RTDB triggers in emulation we discussed yesterday. Let me know how I can help!

**Comment by samtstern** [comment]
@aputinski this comes from using `firebase-functions` 3.x with the current emulators.  We're working on a fix already, thank you for reporting!

**Comment by aputinski** [comment]
So if I use `firebase-functions@2.3.1` with `firebase-tools@7.0.0` everything will work?

**Comment by samtstern** [comment]
@aputinski yes I think it would.

**Comment by abeisgoat** [comment]
@aputinski I have nothing to contribute, but hi Adam! Glad to see you're still using Firebase after all these years :)

**Comment by aputinski** [comment]
@abeisgoat I'll always be a Firebaser 🔥
