### ISSUE TITLE
can't select default project.

### ISSUE THREAD

**Issue by lzl124631x** [firebase/firebase-tools#1418]
### [REQUIRED] Environment info

**firebase-tools:**
```
$ firebase --version
7.0.0
```

**Platform:** macOS

```
firebase init
```
I'm stuck at "Select a default Firebase project for this directory". I can't press any key, even `ctrl+c` doesn't work.

```
$ node -v
v12.2.0
$ npm -v
6.9.0
```

**Comment by rumaan** [comment]
Yeah, same here. The CLI just freezes.

**Comment by OhkuboSGMS** [comment]
win10 node v8.16.0 npm 6.4.1

Same here, and I test  `firebase init`  some version .

v.7.0.0 v6.12.0  not work.
but v.6.11.0 work.


I hope this information helps

**Comment by rumaan** [comment]
@OhkuboSGMS Thanks! **v6.11** worked for me. 👍

**Comment by skyfe79** [comment]
@OhkuboSGMS Thanks! v6.11 works!
```
npm install firebase-tools@6.11.0 -g
```

**Comment by samtstern** [comment]
@lzl124631x thanks for raising this!  Let's use #1420 to track this issue.
