### ISSUE TITLE
unclear error message "Provided code is not a loadable module"

### ISSUE THREAD

**Issue by xxyyzz2050** [firebase/firebase-tools#1419]
when I deploy my project to firebase using firebase-tools CLI, I got the following unclear error message

```
functions[hello(us-central1)]: Deployment error.
Function failed on loading user code. Error message: Provided code is not a loadable module.
Could not load the function, shutting down.
```

what does this error message mean, and how to fix it?

**function**
functions/index.js
```
export const hello= functions.https.onRequest((request, response) => {
  response.send('firebase function works');
});
```
repo: https://github.com/xxyyzz2050/eldeebCMS
script: `npm run start:firebase` = `npm run build:firebase` + `npm run serve:firebase`

**note** 
`firebase serve` works fine

**edit**
I fixed the issue, but please provide us clear error messages

**Comment by samtstern** [comment]
@xxyyzz2050 can you explain what you did to fix this issue?

**Comment by abeisgoat** [comment]
Doing a bit of Googling, I can't find any reference to this error anywhere on the internet, which means it's probably from an internal Google service. That's definitely outside my area, but I get the feeling this isn't something easily fixed. If the code isn't a module, we can't really tell you why, we just know it isn't.

**Comment by samtstern** [comment]
I am pretty sure this error comes from here:
https://github.com/GoogleCloudPlatform/functions-framework-nodejs/blob/2dcb838175c228da2b8ae8f652708a717c6e2f12/src/invoker.ts#L155

But AFAIK the framework is only use in Node 10+ which is why I asked about the node version.

**Comment by xxyyzz2050** [comment]
also this error appears when you specify a sub-dir in functions.source in firebase.json
example:
```
{ 
  "functions": {
    "predeploy": "",
    "source": "firebase/functions"
  },
....
}
```

**Comment by abeisgoat** [comment]
So this isn't an issue for `firebase-tools` really because if anything, it's a `functions-framework` bug. Regardless, @xxyyzz2050 says it was user error and since they haven't responded to explain what they did to fix it, i can't really help to improve the error because a module could be invalid for many specific reasons. So I'm gonna close this, but feel free to reopen @xxyyzz2050 if you feel like providing more info.

**Comment by ashwingattani** [comment]
@xxyyzz2050 can you elaborate on how you fixed the issue?
