### ISSUE TITLE
Firebase login failed

### ISSUE THREAD

**Issue by iderasllc** [firebase/firebase-tools#142]
The Firebase CLI login request was rejected or an error occurred. Please run firebase login again or contact support if you continue to have difficulty logging in.

env: windows10 + nodejs6 + msys2

**Comment by iderasllc** [comment]
my work env is behind lattern proxy that's why it not work, so i tried the `firebase login` in my server , it works, great google

**Comment by ishowman** [comment]
> my work env is behind lattern proxy that's why it not work, so i tried the `firebase login` in my server , it works, great google

Do you means it works when you close Lattern? But in China, i can not visit google unless i open the proxy. Any solutions to make `firebase login` works?
