### ISSUE TITLE
 Could not find trigger a function even it exists

### ISSUE THREAD

**Issue by xxyyzz2050** [firebase/firebase-tools#1421]
I managed my project structure to combine all firebase files into one directory called firebase, except firebase.json
so my firebase.json is look like:
```
{
  "database": {
    "rules": "firebase/database-rules.json"
  },
  "firestore": {
    "rules": "firebase/firestone-rules.txt",
    "indexes": "firebase/firestone-indexes.json"
  },
  "functions": {
    "predeploy": "",
    "source": "firebase"
  },
  "hosting": {
    "public": "./dist/browser",
    "ignore": ["firebase.json", "**/.*", "**/node_modules/**"],
    "rewrites": [
      {
        "source": "**",
        "function": "ssr"
      }
    ]
  },
  "storage": {
    "rules": "firebase/storage-rules.txt"
  }
}

```

and my functions are in `firebase/functions/index.ts`
but, when I run `firebase serve` it works fine and I can see my index.html, but with an error: Could not find trigger "test" in your functions directory.

when I change functions.source in firebase.json to "firebase/functions" `firebase serve` fails

**Comment by abeisgoat** [comment]
Can you provide the full output you see when running `firebase serve`?

**Comment by xxyyzz2050** [comment]
> Can you provide the full output you see when running `firebase serve`?

repo: https://github.com/xxyyzz2050/eldeebCMS
script:  `npm run serve:firebase`

`firebase serve` itself works fine, but the problem is that when I route to /articles it should send an http request to the expressjs server via the function `ssr`.
it works outside firebase serving (i.e: `npm run serve:server`) and can response with the correct data.

![image](https://user-images.githubusercontent.com/35532104/59962076-35a7f000-94e9-11e9-94f4-499f551c39ad.png)

**Comment by abeisgoat** [comment]
Gotcha, so to be clear, you're hitting a `:5000` URL and expecting your `ssr` function to be triggered, but not seeing that happen?

**Comment by bhekanik** [comment]
If I understand you correctly then this will help you.

First run `npm run lint` then run `npm run build` this will lint and then compile your typescript into JS in the lib folder then you can `firebase serve`.

**Comment by bhekanik** [comment]
If I understand you correctly then this error is because you're not compiling your typescript to JavaScript first.

So first run `npm run build` this will compile your typescript into JS then you can `firebase serve`. Make sure that you're pointing to the correct source and target in your `tsconfig.json` file.

**Comment by xxyyzz2050** [comment]
there is a predeploy property witch runs `tsc` before deploying the project, and the 'main' property in package.json already mention the output index.js file @bhekanik

**Comment by abeisgoat** [comment]
The predeploy hook does not run when emulating the functions, you'll need to manually invoke your build script with [`npm run build`

**Comment by bhekanik** [comment]
@abeisgoat I agree with you that you have to run it manually when emulating the functions. I encountered a similar issue some time ago and on inspecting, I realised that the `lib/index.js` was not being updated unless I run `npm run build` manually (in my case I was also running `npm run lint` before `npm run build`). So to save myself the pain of running all those steps one by one I changed the serve script in the `package.json` file to 
`"serve": "tslint --project tsconfig.json && npm run build && firebase serve --only functions"`

**Comment by abeisgoat** [comment]
I would recommend using `tsc -w` which automatically watches your Typescript for changes. That way you will not need to restart `serve` on each change.

**Comment by bhekanik** [comment]
> I would recommend using `tsc -w` which automatically watches your Typescript for changes. That way you will not need to restart `serve` on each change.

Yeah, good idea. Might be a good idea to also include this in the docs, I didn't find anything in there to suggest that when you're emulating you need to compile the typescript manually (my search wasn't very thorough).

**Comment by samtstern** [comment]
@bhekanik yes that's a good idea, something we should mention in the docs. 
@xxyyzz2050 is your issue now resolved by the advice in this thread or are you still encountering issues?

**Comment by Krucial92** [comment]
I have just spent hours crawling Google for similar problems, and scratching my head as to why I was getting this same issue.

After staring at my bundle (don't know how I glazed over this so many times) I finally realised that my webpack bundle was stripping out the `export` on my firebase function export:

`export const client = functions.https.onRequest(app);` was getting transformed to `const client = functions.https.onRequest(app);`

Replacing this with `exports.client = functions.https.onRequest(app);` stops webpack from stripping the "un-used" export.

Hope this helps someone 👍

**Comment by samtstern** [comment]
@Krucial92 thank you for following up!  That's an interesting note about Webpack behavior and will definitely be helpful to people who land here in the future.
