### ISSUE TITLE
functions:shell command does not starts Firestore Emulator with specified port

### ISSUE THREAD

**Issue by kanaksinghal** [firebase/firebase-tools#1426]
No matter what port is been set by `--port` argument (even default 5000), the emulator always starts with **given port number plus one**

### [REQUIRED] Environment info

**firebase-tools:** v7.0.1

**Platform:** macOS v10.14.4

### [REQUIRED] Test case

`firebase functions:shell --port 4999`

### [REQUIRED] Steps to reproduce

`firebase functions:shell --port 4999`

### [REQUIRED] Expected behavior

`✔  functions: Emulator started at http://localhost:4999`

### [REQUIRED] Actual behavior

`✔  functions: Emulator started at http://localhost:5000`

**Comment by kanaksinghal** [comment]
> This issue does not have all the information required by the template. Looks like you forgot to fill out some sections. Please update the issue with more information.

Added info

**Comment by samtstern** [comment]
@kanaksinghal did this work in a previous version of `firebase-tools` and stopped working recently?  Also can you explain why you need to set the port of the emulator in `functions:shell`?  We intend for that to be an implementation detail.

**Comment by kanaksinghal** [comment]
I tested it in previous versions, and found it was working correctly until `v6.8.0`.
I do not want to explicitly set the port; we were expecting the emulator to run on default port 5000 (as it shows in `--help`) but then it started running on 5001.
So we tried to explicitly specify the port by `--port 5000` but still emulator was using 5001 then we tried setting 5050 and it started on 5051

**Comment by samtstern** [comment]
Ok good to know, we can fix this.  Just curious, what do you use the port for while using the shell?  I would expect people only to care about the port when using `firebase serve` or `firebase emulators:start`

**Comment by kanaksinghal** [comment]
Oh, we could do `firebase serve` but we just like to have a shell open too, just in case, so we majorly do `functions:sell` instead

**Comment by samtstern** [comment]
@kanaksinghal that's really interesting, I never thought of using `functions shell` as a superset of `serve`.  This will be fixed by #1428
