### ISSUE TITLE
Getting error in login to Firebase

### ISSUE THREAD

**Issue by vaibhavgehani** [firebase/firebase-tools#1430]
`[debug] [2019-06-22T06:28:48.075Z] ----------------------------------------------------------------------
[debug] [2019-06-22T06:28:48.079Z] Command:       C:\Program Files (x86)\nodejs\node.exe C:\Users\intel\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js login
[debug] [2019-06-22T06:28:48.079Z] CLI Version:   7.0.1
[debug] [2019-06-22T06:28:48.079Z] Platform:      win32
[debug] [2019-06-22T06:28:48.079Z] Node Version:  v10.15.3
[debug] [2019-06-22T06:28:48.081Z] Time:          Sat Jun 22 2019 11:58:48 GMT+0530 (India Standard Time)
[debug] [2019-06-22T06:28:48.081Z] ----------------------------------------------------------------------
[debug] 
[info] 
[info] Visit this URL on any device to log in:
[info] https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=468103980&redirect_uri=http%3A%2F%2Flocalhost%3A9005
[info] 
[info] Waiting for authentication...
[debug] [2019-06-22T06:28:50.860Z] Error: spawn cmd ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[error] 
[error] Error: An unexpected error has occurred.

`

**Comment by abeisgoat** [comment]
Please follow the issue report format.

**Comment by nasro13** [comment]
i have the exact same error please help us :(

**Comment by nasro13** [comment]
i fixed it here is whats i did : i added this to my variable path >>> C:\Program Files;C:\Winnt;C:\Winnt\System32;C:\Windows\System32
