### ISSUE TITLE
Firestore emulator crashes 

### ISSUE THREAD

**Issue by olaven** [firebase/firebase-tools#1432]
Hi, 

After updating to version `7.0.1`, the emulator crashes when I try to start Firestore. 

Reproducing: 
`npm i -g firebase-tools@7.0.1`
`firebase serve --only firestore`
Error: 
`Error: firestore: emulator has exited with code: 1`

Any help would be greatly valued😄

Olav

**Comment by samtstern** [comment]
@olaven can you run the command with `--debug` and show the output?

**Comment by olaven** [comment]
Thank you for replying. 

I ran with `--debug` and from the logging, I realised that I was running something on the port already. Sorry about that. 

However, perhaps this should be reflected in the error?

**Comment by samtstern** [comment]
@olaven ah this is an issue where `firebase emulators:start` has a nice error but `firebase serve` does not.  Here's a comparison:

emulators:start
```
$ firebase emulators:start --only firestore
i  Starting emulators: ["firestore"]
i  Shutting down emulators.
⚠  Port 8080 is not open, could not start firestore emulator.
i  To select a different port for the emulator, update your "firebase.json":
    {
      // ...
      "emulators": {
        "firestore": {
          "port": "PORT"
        }
      }
    }
i  Shutting down emulators.

Error: Could not start firestore emulator, port taken.
```

serve
```
$ firebase serve --only firestore
i  firestore: Logging to firestore-debug.log
✔  firestore: Emulator started at http://localhost:8080

Error: firestore: emulator has exited with code: 1
```

I will try and make this better, thanks for noticing!

**Comment by olaven** [comment]
Thank you! 😄
