### ISSUE TITLE
command firebase login doesn´t work

### ISSUE THREAD

**Issue by cristiaan05** [firebase/firebase-tools#1435]
<!--
Thank you for contributing to the Firebase community!

Think you found a bug?
=======================
Yeah, we're definitely not perfect! Please use this template and include a minimal repro when opening the issue. If you know how to solve the issue, please create a Pull Request, and we'd be happy to review it!

Have a feature request?
========================
Great, we love hearing how we can improve our products! However, do not use this template to submit a feature request. Please submit your feature requests to: https://firebase.google.com/support/contact/bugs-fe

**Comment by bkendall** [comment]
Please open a new issue with all the required information.
