### ISSUE TITLE
Functions emulator does not print updated HTTPS urls on region change

### ISSUE THREAD

**Issue by abeisgoat** [firebase/firebase-tools#1436]
1. Make an HTTPS function with no region
2. See the URL default to "us-central1"
3. Change the code to have `functions.region("asia-northeast1").https.onRequest`
4. The new URL is never printed.

**Comment by samtstern** [comment]
@abeisgoat do regions besides `us-central1` ever work?

**Comment by abeisgoat** [comment]
Yes they do, we completely drop the region from our routing, so any region will work

**Comment by akauppi** [comment]
I recently noticed that if I want to have Cloud Functions work both online, and during emulation, I must do this:

```
const fns = window.LOCAL ? firebase.app().functions(/*functionsRegion*/) :
  firebase.app().functions(functionsRegion);
```

If I mention the region when the back-end is emulated, nothing happens. Commenting it out (as above) makes the functions work. Naturally, I would like to have the same code base, regardless whether the back end is emulated, or not.

Is this connected to the current issue? Should I enter a new one?

**Comment by samtstern** [comment]
@akauppi that sounds like a separate issue, please file a new one!

**Comment by samtstern** [comment]
I believe this should be fixed by https://github.com/firebase/firebase-tools/pull/3364 which adds better support for multiple regions.
