### ISSUE TITLE
Improvements to emulator JAR management

### ISSUE THREAD

**Issue by samtstern** [firebase/firebase-tools#1439]
This is a follow up to https://github.com/firebase/firebase-tools/pull/1434

Once we auto-download JARs we make it easier to download them on every run without realizing you're doing it (in a CI system).  There are some QoL things we should do:

1) Clean up old JARs since we don't allow them to be used
2) If we can detect that you're in CI (like by `process.env.TRAVIS`) maybe print a loud warning saying you should cache the JARs
3) Make the JAR caching location part of our public API and tell people how to cache it on popular CI providers

**Comment by merlinnot** [comment]
`process.env.CI` is usually present in CIs. Please make it possible to skip installation of JARs, as some of us out there use Docker containers for it (downloading and running JAR files directly).

**Comment by samtstern** [comment]
@merlinnot can you explain the pattern you're using a bit more?
