### ISSUE TITLE
Functions emulator does not initialize HTTPS functions

### ISSUE THREAD

**Issue by johnmartel** [firebase/firebase-tools#1443]
### [REQUIRED] Environment info

**firebase-tools:** `7.0.2`

I am using nvm to run on node `8.15.0`.

**Platform:** `macOS 10.14.5`

### [REQUIRED] Test case

My `package.json` has these:
```json
"scripts": {
    "build": "babel src --out-dir dist --copy-files",
    "preserve": "yarn build",
    "serve": "firebase emulators:start --only functions",
  },
  "main": "dist/index.js",
  "engines": {
    "node": "8"
  },
  "dependencies": {
    "firebase": "6.2.3",
    "firebase-admin": "8.2.0",
    "firebase-functions": "3.0.2"
}
```

in `src/index.js` (which babel transforms into `dist/index.js`). I have the following:
```javascript
export { organizations } from './organizations/organizationFunction';
export { currentUser } from './currentUserDetails/currentUserFunction';
```
and both functions are pretty similar:
```javascript
export const currentUser = functions.region(config.adminFunctionsRegion).https.onRequest(app);
```
where `app` is simply an initialized Express app with a single `/` GET route.

Of course, I have a fully configured `.runtimeconfig.json` that has all the required configuration for my functions to be able to initialize firebase-admin.

Prior to updating my `firebase-tools` and libs, I had a working setup using `firebase serve --only functions` using the following:
`firebase-tools@6.4.0`, `firebase@5.9.0`, `firebase-admin@7.0.0` and `firebase-functions@2.2.0`

### [REQUIRED] Steps to reproduce

Simply GET `http://localhost:5001/<project-id>/us-central1/currentUser/` using Postman.

### [REQUIRED] Expected behavior

Cloud function is initialized when starting emulator and can be successfully called with an HTTP request.

### [REQUIRED] Actual behavior

Function does not seem to be loaded on emulator start and does not execute when sending an HTTP request: no response is ever received and the request simply times out. In the emulator logs, I get the following:
```
i  Starting emulators: ["functions"]
✔  functions: Using node@8 from host.
✔  functions: Emulator started at http://localhost:5001
i  functions: Watching "[...]/functions" for Cloud Functions...
[debug] [2019-06-27T02:08:49.147Z] Accepted request GET /<project-id>/us-central1/currentUser/ --> currentUser
[debug] [2019-06-27T02:08:49.401Z] Functions runtime initialized.
[info] i  functions: Beginning execution of "currentUser"
[debug] [2019-06-27T02:08:49.401Z] Disabled runtime features: undefined
[debug] [2019-06-27T02:08:49.546Z] Found google-gax at [...]/functions/node_modules/@google-cloud/firestore/node_modules/google-gax/build/src/index.js
[debug] [2019-06-27T02:08:49.547Z] Outgoing network have been stubbed.
[debug] [2019-06-27T02:08:49.580Z] Checked functions.config()
[debug] [2019-06-27T02:08:49.581Z] firebase-admin has been stubbed.
[debug] [2019-06-27T02:08:49.648Z] config() parent accessed!
[debug] [2019-06-27T02:08:49.648Z] config() parent accessed!
[debug] [2019-06-27T02:08:49.649Z] config() parent accessed!
```
and it stops there.

If I send a request to a non-existing path, I get the following:
```
[debug] [2019-06-27T02:18:04.091Z] Accepted request GET /<project-id>/us-central1/gibberish --> gibberish
[debug] [2019-06-27T02:18:04.362Z] Functions runtime initialized.
[info] i  functions: Beginning execution of "gibberish"
[debug] [2019-06-27T02:18:04.363Z] Disabled runtime features: undefined
[debug] [2019-06-27T02:18:04.516Z] Found google-gax at [...]/functions/node_modules/@google-cloud/firestore/node_modules/google-gax/build/src/index.js
[debug] [2019-06-27T02:18:04.516Z] Outgoing network have been stubbed.
[debug] [2019-06-27T02:18:04.557Z] Checked functions.config()
[debug] [2019-06-27T02:18:04.558Z] firebase-admin has been stubbed.
[debug] [2019-06-27T02:18:04.631Z] config() parent accessed!
[debug] [2019-06-27T02:18:04.631Z] config() parent accessed!
[debug] [2019-06-27T02:18:04.631Z] config() parent accessed!
```
No response either.

Please note that using the same versions, I can successfully test my firestore rules using the emulator with `firebase emulators:exec --only firestore "jest --testRegex 'test/rules/.*\.spec\.js$' --no-coverage"`

**Comment by johnmartel** [comment]
I also tried setting `GOOGLE_APPLICATION_CREDENTIALS` with a path to my project's appengine default service account json key, without making a difference.

**Comment by samtstern** [comment]
@johnmartel thanks for filing this, sounds like a bug and I bet @abeisgoat can get to the root of it.

**Comment by johnmartel** [comment]
@samtstern @abeisgoat I have updated `firebase-tools` to 7.2.2 without changing my other dependencies and am now serving my HTTPS functions successfully with `firebase emulators:start --only functions`. Therefore, I consider this as closed :)

**Comment by samtstern** [comment]
@johnmartel thanks for following up!
