### ISSUE TITLE
local emulation of functions reimports entire index.js on every call

### ISSUE THREAD

**Issue by alex-hioperator** [firebase/firebase-tools#1445]
### [REQUIRED] Environment info

**firebase-tools:** 7.0.1

**Platform:** macOS

### [REQUIRED] Test case

To test my cloud functions locally, I run the following command:

`firebase serve --only functions`

This works great, but I'm noticing one odd behaviour: Every time I do an HTTP call to any of the cloud functions running locally, the entire index.js file is reimported. This makes execution really slow (its like I've always got a cold start penalty to pay). When I deploy the functions to firebase, however, this behaviour does not occur.

### [REQUIRED] Steps to reproduce

Add a console.log("I'm importing the index.js!") anywhere in the index.js file.

### [REQUIRED] Expected behavior

The index.js import only happens once at start of the local emulation.

### [REQUIRED] Actual behavior

Index.js is imported every time a cloud function is called through an HTTPS request.

**Comment by samtstern** [comment]
@alex-hioperstor thanks for the feedback, we're already discussing this in #1353 so I'm going to close this issue as a duplicate.
