### ISSUE TITLE
Rollback feature for Security Rules that have been set/configure by the CLI

### ISSUE THREAD

**Issue by jobsamuel** [firebase/firebase-tools#145]
It would be awesome to have this feature; I believe it would prevent a lot of headaches :relieved:

**Comment by mbleigh** [comment]
We heartily agree, and it's on the roadmap. I can't comment as to the specifics of when it will be available, but we're definitely thinking about it.

**Comment by mbrevda** [comment]
Until then, if you have daily backups, these will include the rules so you can always rollback to yesterday.

**Comment by joehan** [comment]
This was such a good suggestion that we implemented it as version history 5 years ago: https://firebase.blog/posts/2018/04/firestore-rules-management
