### ISSUE TITLE
Cannot call admin.firestore().getCollections()

### ISSUE THREAD

**Issue by morgs32** [firebase/firebase-tools#1453]
### [REQUIRED] Environment info

**firebase-tools:** 7.0.2

**Platform:** macOS

### [REQUIRED] Test case

```
// repro.js
const firebase = require('@firebase/testing');
const fs = require('fs');

const admin = firebase.initializeAdminApp({
  projectId: 'example',
});

console.log('admin.firestore().getCollections', admin.firestore().getCollections);
```

### [REQUIRED] Steps to reproduce

1. Install `@firebase/testing`
2. Run `node repro.js` (the file snippet above)

### [REQUIRED] Expected behavior

`admin.firestore().getCollections` should be a function

### [REQUIRED] Actual behavior

`admin.firestore().getCollections undefined`

**Comment by samtstern** [comment]
@morgs32 does this only happen to you in the emulator or does it also happen to you in production?

Also it looks like that method is deprecated:
https://cloud.google.com/nodejs/docs/reference/firestore/1.3.x/Firestore#getCollections

Does `listCollections()` work?

**Comment by ryanpbrewster** [comment]
This happens because the `initializeAdminApp` method in `@firebase/testing` returns a client app that has admin credentials, rather than returning an actual admin app.

You can work around this by using `firebase-admin` or `@google-cloud/firestore` directly. Both modules should respect the `FIRESTORE_EMULATOR_HOST` environment variable that the emulator prints out on startup.

**Comment by morgs32** [comment]
Ahh gotcha @ryanpbrewster . I'll use `firebase-admin` and will presumably use `listCollections` instead. Thanks @samtstern.

**Comment by morgs32** [comment]
@ryanpbrewster actually how do I specify the `projectId` with `firebase-admin`?

**Comment by ryanpbrewster** [comment]
```
const admin = require("firebase-admin");
const db = admin.initializeApp({ projectId: 'foo' }).firestore();
```
works for me

**Comment by morgs32** [comment]
👍 Got it!
