### ISSUE TITLE
Why can't we use the CLI as a module in Cloud Functions?

### ISSUE THREAD

**Issue by ollietreend** [firebase/firebase-tools#1462]
The project README states:

> The Firebase CLI can also be used programmatically as a standard Node module. This can only be done on your machine, and cannot be done within Cloud Functions.

My question is – why can't it be used as a standard Node module from within a Cloud Function?

An example where this would be useful:

To be able to execute the `auth:export` command from within a [scheduled Cloud Function](https://firebase.google.com/docs/functions/schedule-functions) to take a regular backup of the user authentication database.

**Comment by samtstern** [comment]
@ollietreend you definitely can use the CLI as a module inside a Cloud Function, that warning is a little harsh.  The reason for that warning is that sometimes the CLI requires access to a file system and that will not work reliably on a Cloud Function.

Here's a guide about deleting data from Firestore where we use the CLI as a module in a Cloud Function:
https://firebase.google.com/docs/firestore/solutions/delete-collections

**Comment by ollietreend** [comment]
Got it. Thanks for clarifying, @samtstern! 🙂
