### ISSUE TITLE
firebase deploy not working after npm update

### ISSUE THREAD

**Issue by stevendyk** [firebase/firebase-tools#1471]
### [REQUIRED] Environment info

**firebase-tools:**

**Platform:**

**Comment by dfchaves17** [comment]
I have this problem, you have downgrade version of npm. 
https://stackoverflow.com/a/56885970

**Comment by ajurcevic** [comment]
another band-aid option was to edit the checkFirebaseSDKVersion.js file:
https://stackoverflow.com/a/56876897/1775964

**Comment by bkendall** [comment]
Downgrading `npm` to `6.9` from `6.10` seems to be the best option for now (as described in the first SO link here).

I'm going to close this for now as downgrading is the current fix, but we'll have to take a look into this a little more closely...

Also, please fill out the bug template completely, as it's impossible to know what exactly was happening on your machine (I don't even know what version of `npm` you were running, as an example).
