### ISSUE TITLE
Your path does not contain an even number of components.

### ISSUE THREAD

**Issue by Karman40** [firebase/firebase-tools#1476]
Full error message:
`Unhandled error Error: Value for argument "documentPath" must point to a document, but was "teams/". Your path does not contain an even number of components.`

Versions:
- firebase-admin: `7.0.0`
- firebase-functions: `2.2.0`
- firebase-tools: `6.5.0`

data structure:
- teams
   - teamID - results subcollections
   - teamID - results subcollections
   - teamID - results subcollections

I want to delete all teams. I use the following code for this:
[https://github.com/firebase/snippets-node/blob/9ae3a00985b53025fdc82716046882af71b6009d/firestore/solution-deletes/functions/index.js#L29-L74](https://github.com/firebase/snippets-node/blob/9ae3a00985b53025fdc82716046882af71b6009d/firestore/solution-deletes/functions/index.js#L29-L74)

**Comment by samtstern** [comment]
@Karman40 if you want to delete everything in the root-level collection called "teams" try using `teams` as your argument rather than `teams/`.

The extra slash at the end is causing the issue.

**Comment by Karman40** [comment]
Thank you, I'm not stupid, but it's the same error.

Unhandled error Error: Value for argument "documentPath" must point to a document, but was "teams". Your path does not contain an even number of components.

**Comment by samtstern** [comment]
@Karman40 thanks for clarifying. Also please be respectful when asking for help on GitHub.
