### ISSUE TITLE
firebase list does not show my apps

### ISSUE THREAD

**Issue by jrock2004** [firebase/firebase-tools#148]
I have upgrade an old firebase app to the new console but now I cannot deploy my app anymore. I have run firebase login and I have successfully logged in. But now for some reason when I run firebase list, I do not see my app anymore. I am running firebase tools 2.2.1. Thoughts?

**Comment by drtriumph** [comment]
In order to deploy to an app that has been imported into the new console you are required to upgrade firebase-tools to `3.0.0` - it now uses OAuth refresh / access tokens under the hood and so is more secure

**Comment by jrock2004** [comment]
Yep, I misread the error message when I had 3.0 installed
