### ISSUE TITLE
Write to and read from firebase DB emulators (rtdb & firestore) for testing purposes

### ISSUE THREAD

**Issue by skalashnyk** [firebase/firebase-tools#1485]
Hi there!

Is there a way to write to and read from firebase DB emulators (rtdb & firestore) for local testing purposes. If so, where can I read an example?
I could read from & write to RTDB emulator, using postman (simple REST api), but not with nodejs admin sdk (`"firebase-admin"`).

Step to reproduce
1. `$ firebase emulators: start`
Output:
```
i  Starting emulators: ["firestore","database"]
i  firestore: Logging to firestore-debug.log
✔  firestore: Emulator started at http://localhost:8080
i  firestore: For testing set FIRESTORE_EMULATOR_HOST=localhost:8080
i  database: Logging to database-debug.log
✔  database: Emulator started at http://localhost:9000
```
2.  Write data to RTDB using postman:
`POST http://localhost:9000/users.json`, json request body:  `{ "age": 22, "name": "John" }`, json response body:  `{ "name": "-LjQYbG5j5Qy0_l6BJ9a" }`;

3. Then I can fetch data, e.g.:
- `GET http://localhost:9000/users.json` =>  `{ "-LjQYbG5j5Qy0_l6BJ9a": { "age": 22, "name": "John" } }`;
- `GET http://localhost:9000/users/-LjQYbG5j5Qy0_l6BJ9a.json` =>  `{ "age": 22, "name": "John" }`;
- `GET http://localhost:9000/users.json?shallow=true` => `{ "-LjQYbG5j5Qy0_l6BJ9a": true}`

BUT, when I tried to fetch data (using `.once()` or `.on()` method) with nodejs admin SDK (`"firebase-admin"`) I don't get any data (even `null`), looks like nothing happens.

My config
`"firebase-tools" : "7.0.2"`
`"firebase-admin": "^8.2.0"`

Please, help.

**UPD**. Firestore emulator works fine from SDK, but RTDB one doesn't.

**Comment by samtstern** [comment]
@skalashnyk thanks for asking!  This is a key question and we're working on documentation to clarify all of this.

**Realtime Database + Admin SDK**
Right now this is only possible through hacks, however there is a Pull Request in flight that will make this easy:
https://github.com/firebase/firebase-admin-node/pull/589

Once that PR is merged and released, you will just set the `FIREBASE_DATABASE_EMULATOR_HOST` environment variable and the Admin SDK will connect automatically.

**Firestore + Admin SDK**
This is possible today by setting the `FIRESTORE_EMULATOR_HOST` environment variable.  You can also configure the SDK to talk to the emulator when initializing the settings in code:

```js
admin.firestore().settings({
        projectId: frb.projectId,
        host: "localhost:8080",
        ssl: false,
        // ...
});
```

**Comment by skalashnyk** [comment]
@samtstern, thank you for reply and your efforts to clarify documentation.
Looking forward to hearing from you!
