### ISSUE TITLE
Firestore emulator: startAfter doesn't works

### ISSUE THREAD

**Issue by ybourgery** [firebase/firebase-tools#1486]
### Environment info

**firebase-tools:** 7.0.2

**Platform:** macOS

### Test case

```go
func main() {
        ctx := context.Background()
	client, err := firestore.NewClient(ctx, "my-gcp-project")
	if err != nil {
		panic(err)
	}
        coll := client.Collection("myCollection")
        docs := []string {
		"id1", "id2", "id3", "id4",
	}
	batch := client.Batch()
	for _, doc := range docs {
		batch.Create(coll.NewDoc(),  map[string]string{
			"id": doc,
		})
	}
	if _, err := batch.Commit(ctx); err != nil {
		panic(err.Error())
	}
        q := coll.OrderBy("id", firestore.Asc).StartAfter( "id2")
	docs := q.Documents(ctx).GetAll()
        if len(docs) != 2 {
              fmt.Println("failure")
        } else {
              fmt.Println("success")
        }
}
```

### [REQUIRED] Steps to reproduce

1. Start the emulator.
2. Run the test case.

### Expected behavior

The query filter `startAfter` should not contain the document specified as a parameter of `startAfter`.

### Actual behavior

The query filter `startAfter` contains the document which is the expected behavior of `startAt`.

**Comment by samtstern** [comment]
@ybourgery thanks for the report!  Seems like a straightforward bug.

**Comment by ryanpbrewster** [comment]
Sweet, nice find!

Fix submitted, will close this issue once it's released.

**Comment by ybourgery** [comment]
Thanks @ryanpbrewster for the quick fix.
