### ISSUE TITLE
Requested Node 8 does not match with my Node 12

### ISSUE THREAD

**Issue by hpoit** [firebase/firebase-tools#1489]
### [REQUIRED] Environment info

 

**firebase-tools:** 7.0.2

**Platform:** macOS

### [REQUIRED] Test case: 
run `firebase serve` on terminal 

### [REQUIRED] Steps to reproduce: 
1. use the source code from https://angulardart.dev/guide/forms#give-visual-feedback-based-on-control-state

2. follow steps on https://console.firebase.google.com/u/0/project/icasaa-d46fe/overview up to `firebase init`, then do `firebase serve`

### [REQUIRED] Expected behavior: 
no issues

### [REQUIRED] Actual behavior: 
Your requested "node" version "8" doesn't match your global version "12"

**Comment by abeisgoat** [comment]
This is expected and just a warning to let you know that you've set `{engines: {node: 8}}` in `functions/package.json`. If you're concerned, you can use `nvm` to install an older version of Node, but realistically it probably wont matter.

**Comment by hpoit** [comment]
Thanks for the tip, Abe! I made the change to `"node": "12"`, however, I still get:
```
Daves-MBP:forms dave$ firebase serve

=== Serving from '/Users/dave/WebstormProjects/forms'...

✔  functions: Using node@12 from host.
i  hosting: Serving hosting files from: build/web
✔  hosting: Local server: http://localhost:5000
✔  functions: Emulator started at http://localhost:5001
i  functions: Watching "/Users/dave/WebstormProjects/forms/functions" for Cloud Functions...

Error: An unexpected error has occurred.

Having trouble? Try again or contact support with contents of firebase-debug.log
Daves-MBP:forms dave$ 
```

**Comment by samtstern** [comment]
Sorry I think Abe meant for you to downgrade to either Node 8 or 10 not
upgrade to 12.   Firebase does not yet support Node 12.

**Comment by joaoeudes7** [comment]
Using Nvm to change the version of node has a solution

**Comment by AAverin** [comment]
I am using `n` and have node set to 8. Still, I get this warning message

**Comment by fahadtahir226** [comment]
i explicitly changed node version from 8 to 12 in package.json and it worked for me

**Comment by Norfeldt** [comment]
@abeisgoat I'm having the same issue trying to run version 10 inside a docker container with only node 10. It throws this at me

```
Your requested "node" version "10" doesn't match your global version "12"
```


My package.json looks like:

```
{
  "name": "functions",
  "description": "Cloud Functions for Firebase",
  "engines": {
    "node": "10"
  },
  ...
}

The project currently is running on node 8 - I had to give up trying to upgrade to node 10 since I thought that my `nvm` wasn't working. Now I decided to try to do it in a node 10 container and I see that it's not my `nvm` that was playing with me.

**Comment by jthegedus** [comment]
I am also getting this warning with the Firebase Emulator. I have a reproduction at https://github.com/jthegedus/firebase-emulator-warning-reproduction
