### ISSUE TITLE
"firebase login" doesn't work with Git-Bash

### ISSUE THREAD

**Issue by kilna** [firebase/firebase-tools#149]
Git-Bash is incorrectly identified as non-interactive mode by the firebase command line tool. As a result, "firebase login" works from cmd.exe, but not from git-bash.exe.

**Comment by mbleigh** [comment]
You can run with --interactive to force interactive mode

**Comment by kilna** [comment]
Thanks for the work-around. Is the root cause necessitating the work-around solvable?

**Comment by mbleigh** [comment]
I'm not sure that it is -- we rely on Node's `process` to tell us whether or not a shell is interactive. Frankly I'm looking forward to bash coming to Windows this summer, as existing Windows shells have some really inconsistent and hard-to-support behavior.

**Comment by kilna** [comment]
The following nodejs issue seems to describe the root cause in excruciating detail:

https://github.com/nodejs/node/issues/3006

**Comment by mbleigh** [comment]
:fearful: yeah, cygwin is scary

**Comment by fpilee** [comment]
and firebase init doesn't work neither with git-bash for windows

**Comment by pevargasg** [comment]
@fpilee  it works for me :/ maybe you environment variables en you windows machine aren't set properly

**Comment by Joxxinton** [comment]
> You can run with --interactive to force interactive mode
> 
> On Mon, May 23, 2016, 9:00 PM Kilna notifications@github.com wrote:
> 
> > Git-Bash is incorrectly identified as non-interactive mode by the firebase
> > command line tool. As a result, "firebase login" works from cmd.exe, but
> > not from git-bash.exe.
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > https://github.com/firebase/firebase-tools/issues/149
> 

Brilliant I love you man
