### ISSUE TITLE
login:ci requests / inclusion of firebase use

### ISSUE THREAD

**Issue by gauntface** [firebase/firebase-tools#150]
Just tried to set up deploying on travis.

With `firebase login:ci` I get the following note:

    firebase deploy --token "$FIREBASE_TOKEN"

That doesn't work out of the box, I've ended up having to run:

    firebase use default --token "$FIREBASE_TOKEN"

1. It would be good to add this to login:ci
1. Even better would be to not require the `use default` unless it's needed. The .firebaserc file exists with only one entry and it's called default. That seems like a safe assumption for firebase deploy (and probably other commands) to use that project.

**Comment by mbleigh** [comment]
In a CI environment you can pass `--project <alias_or_project_id>` to do a per-command switching of aliases. So in this case you can just do:

    firebase deploy --token "$FIREBASE_TOKEN" --project default

**Comment by gauntface** [comment]
Couldn't that be the default project value if nothing is defined?

**Comment by mbleigh** [comment]
We're discussing that change now. We wanted to avoid people accidentally triggering commands against production, but the ergonomics are proving frustrating so we're re-evaluating.
