### ISSUE TITLE
Can't deploy rules from build server

### ISSUE THREAD

**Issue by scriby** [firebase/firebase-tools#153]
Our build server was setup to deploy rules to firebase, and it worked without issue until we upgraded the app to the new Google-integrated version.

We receive the error "Your refresh token has been revoked, please run firebase login to obtain a new one." when running "firebase deploy". I did obtain a new login token, and the exact same deployment command works correctly from my local computer.

Here is the command:

`firebase deploy  -P "<redacted>" --token '<redacted>'`

Any ideas what could be going on?

Also looks like I'm not the only one: http://stackoverflow.com/questions/37447223/jenkins-deploy-to-firebase-your-refresh-token-has-been-revoked

**Comment by scriby** [comment]
I was able to get this working using the module from node instead of on the command line.

**Comment by scriby** [comment]
Well, that worked for one of my projects. The other one errors with this output:

```
Error: Unable to authorize access to project digby-test

Note: This version of the Firebase CLI is only compatible with projects upgraded
to the new Firebase Console. To access firebase.com apps, you will need to
use a previous version: npm install -g firebase-tools@^2.1

To access the Firebase Console, visit https://console.firebase.google.com/
```

(That project has been upgraded to the new console)

**Comment by mbleigh** [comment]
Your project id might have changed with the migration. Please do a `firebase list` and make sure that the project id (*not* the instance name) is what you're passing to `--project`. Let me know if that doesn't solve the issue for you.

Also note that you will need to generate a new token for the new CLI, existing ones will not work.

**Comment by scriby** [comment]
Thanks, that was it. The project name was prepended with "firebase-".
