### ISSUE TITLE
delete require.cache not working in firebase shell.

### ISSUE THREAD

**Issue by umarhussain15** [firebase/firebase-tools#1536]
### [REQUIRED] Environment info

**firebase-tools:** 6.8.0

**Platform:** Windows

### [REQUIRED] Test case

- firebase functions:shell (wait for functions to load)
- let options = require('path to context options json')
- let data = require('path to data json')
- delete require.cache
- options = require('path to context options json')

### [REQUIRED] Steps to reproduce

Same as test case.
### [REQUIRED] Expected behavior

The call to `delete require.cache` should clear the loaded json data and on next require it should load data from file.
### [REQUIRED] Actual behavior

the command `delete require.cache` returns true in shell but the content in options remains cached. I changed data in json file after first require but it still not refreshing the content.

**Comment by umarhussain15** [comment]
updated

**Comment by samtstern** [comment]
@abeisgoat I am scared of the require cache.

**Comment by samtstern** [comment]
Thanks @umarhussain15 for filing this!

**Comment by abeisgoat** [comment]
I believe you may be mistaken @umarhussain15, can you try...

```js
delete require.cache[require.resolve('path to data json')]
```

I've never seen someone attempt to delete the entire cache and afaik it's not possible in any environment.

**Comment by umarhussain15** [comment]
@abeisgoat thanks for the correct command.
I tried the above command earlier but I was not using `require.resolve` so there was no change in cache. I then tried to delete the whole cache.

Using the above command I'm able to delete items from require cache. Thanks again.
