### ISSUE TITLE
InternalError when deploying Firestore function: "Cannot allocate memory. rm_node_modules is likely not on the path"

### ISSUE THREAD

**Issue by MrAlek** [firebase/firebase-tools#1548]
### [REQUIRED] Environment info

**firebase-tools:** 7.2.0

**Platform:** macOS

### [REQUIRED] Test case

No test case.

Issue suddenly started appearing ~a week ago and has gone progressively worse.

### [REQUIRED] Steps to reproduce

Deploy a cloud function on a Firestore trigger using `firebase deploy --only functions:functionName`.

Function definition:
```
functions
  .region('europe-west1')
  .firestore.document('X/{Xid}')
  .onCreate(async (snapshot, context) => {})
```

### [REQUIRED] Expected behavior

Successful deployment.

### [REQUIRED] Actual behavior

```
=== Deploying to 'done-50549'...

i  deploying functions
i  functions: ensuring necessary APIs are enabled...
✔  functions: all necessary APIs are enabled
i  functions: preparing functions directory for uploading...
i  functions: packaged functions (901.17 KB) for uploading
✔  functions: functions folder uploaded successfully
i  functions: current functions in project: *masked*
i  functions: uploading functions in project: functionName(europe-west1)
i  functions: updating Node.js 8 function functionName(europe-west1)...
✔  scheduler: all necessary APIs are enabled
functions[functionName(europe-west1)]: Deployment error.
Build failed: {"error": {"canonicalCode": "INTERNAL", "errorMessage": "rm_node_modules rm -rf /workspace/node_modules\nexited with error [Errno 12] Cannot allocate memory\nrm_node_modules is likely not on the path", "errorType": "InternalError", "errorId": "B59E88C1"}}
```

Deployment gets stuck after `all necessary APIs are enabled` and polls `https://cloudfunctions.googleapis.com/v1/operations/ZG9uZS01MDU0OS9ldXJvcGUtd2VzdDEvY2FsbE5vdGlmaWNhdGlvbi9oUzVyb2JnT0RXRQ` for a while until finally receiving the error.

Also, in the Firebase console function logs, this appears:

```
{"@type":"type.googleapis.com/google.cloud.audit.AuditLog","status":{"code":3,"message":"INVALID_ARGUMENT"},"authenticationInfo":{"principalEmail":"my@emailAddress.com"},"requestMetadata":{"requestAttributes":{},"destinationAttributes":{}},"serviceName":"cloudfunctions.googleapis.com","methodName":"google.cloud.functions.v1.CloudFunctionsService.UpdateFunction","resourceName":"projects/XXX/locations/europe-west1/functions/functionName"}
```

### Tried mitigations

- Rebuilding `node_modules` with `yarn`
- `firebase logout && firebase login`

**Comment by MrAlek** [comment]
Seems like I finally was able to solve the issue by updating `yarn` and rebuilding `node_modules` again.

This took me quite some time to get around, especially since the console output said `InternalError` I assumed it was some kind of outage and retried during a period of hours.

Is there a way of detecting these `node_modules` related issues and provide a more helpful error message?

> This might be related to your `node_modules`. Try upgrading `npm`/`yarn` and rebuild your `node_modules`

**Comment by samtstern** [comment]
As far as I know @MrAlek this is a somewhat uncommon backend issue that is normally fixed by running `firebase deploy` again.  When you deploy Cloud Functions we actually build the `node_modules` folder ourselves so your local modules are not part of the deployment.  It's likely a coincidence that it was fixed for you just after you did a local upgrade/rebuild.

We have some big backend improvements coming to how we build/deploy functions that we hope will eliminate this and other errors while also making deploys faster.

If you experience issues like this again feel free to respond on this thread or write in to Firebase Support.  Thanks for the feedback and the investigation!

**Comment by rubenjose** [comment]
Similar issue going on here.  

deployment hangs at the "all necessary API's are enabled".  Except I have never gotten it to return control from here and have to kill deployment and the console just states "aborted".  

Start with deployment of single function:
`$ firebase deploy --only functions:checkArrayUnion`

Everything fine till it just stops for no reason:
`i  functions: uploading functions in project: checkArrayUnion(us-central1)
i  functions: updating Node.js 8 function checkArrayUnion(us-central1)...
✔  scheduler: all necessary APIs are enabled`

**Comment by rubenjose** [comment]
let it run and 20 minutes later it quit.  gave me this:

`⚠  functions[checkArrayUnion(us-central1)]: Deployment error.
Operation interrupted.


Functions deploy had errors with the following functions:
	checkArrayUnion


To try redeploying those functions, run:
    firebase deploy --only functions:checkArrayUnion


To continue deploying other features (such as database), run:
    firebase deploy --except functions

Error: Functions did not deploy properly.`

The function is fine code wise.  We have deployed it in the past and nothing is changed except that I am trying it on my mac now.  The operation shows as an abort in the logs as a code 10 aborted.  Though I didn't abort (this time).
