### ISSUE TITLE
I am having trouble with installing firebase tools

### ISSUE THREAD

**Issue by AKASHHJOSEPH** [firebase/firebase-tools#1558]
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/firebase-tools/node_modules/grpc
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/firebase-tools
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/firebase-tools/node_modules
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm WARN marked-terminal@3.2.0 requires a peer of marked@^0.4.0 || ^0.5.0 || ^0.6.0 but none is installed. You must install peer dependencies yourself.

npm ERR! path /usr/local/lib/node_modules/firebase-tools/node_modules/grpc
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules/firebase-tools/node_modules/grpc'
npm ERR!  [Error: EACCES: permission denied, access '/usr/local/lib/node_modules/firebase-tools/node_modules/grpc'] {
npm ERR!   stack: "Error: EACCES: permission denied, access '/usr/local/lib/node_modules/firebase-tools/node_modules/grpc'",
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules/firebase-tools/node_modules/grpc'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:

**Comment by JottaPereira** [comment]
Hi, I had the same issue.
Here what I did and work for me:
https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

**Comment by bkendall** [comment]
yup, @AKASHHJOSEPH, see the docs that @JottaPereira directed you towards - that looks like a permissions issue on your local machine.

**Comment by saifbinabdulkareem** [comment]
@AKASHHJOSEPH  run "sudo npm install -g firebase-tools" . I did not update anything except this package. I am also able to install other global npm packages without any issue. Now its work perfectly.

**Comment by AKASHHJOSEPH** [comment]
Ok thanks

**Comment by jerinho** [comment]
> 

if root access is the solution, then why installation instructions [here](https://firebase.google.com/docs/cli?authuser=0#setup_update_cli) didn't ask us to use it?

**Comment by rumon5h** [comment]
First go to the home directory.

    mkdir ~/.npm-global

    npm config set prefix '~/.npm-global'

In your preferred text editor, open or create a ~/.profile file and add this line:

    export PATH=~/.npm-global/bin:$PATH

On the command line, update your system variables:

    source ~/.profile

To test your new configuration, install a package globally without using sudo:

npm install -g firebase-tools
