### ISSUE TITLE
firebase login cli error

### ISSUE THREAD

**Issue by gurubastade** [firebase/firebase-tools#1559]
`C:\myAngular\gurus-application>firebase login
? Allow Firebase to collect anonymous CLI usage and error reporting information? Yes

Visit this URL on any device to log in:
https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=854954875&redirect_uri=http%3A%2F%2Flocalhost%3A9005

Waiting for authentication...

Error: An unexpected error has occurred.`

After clicking on above link and granting account permissions, it redirects to "http://localhost:9005/?state=854954875&code=4/jwFslVpNwUN69pE23CDm-0PXLSxMsaXWxwxItVZiYmp2XcBfQO-SuP2Vw5M6v2RIwwUDBUMl0H0sP3GLgbpHFCE&scope=email%20https://www.googleapis.com/auth/userinfo.email%20openid%20https://www.googleapis.com/auth/cloudplatformprojects.readonly%20https://www.googleapis.com/auth/firebase%20https://www.googleapis.com/auth/cloud-platform&authuser=0&session_state=3c218571679fb5168ada533bddf5502392385300..5d7c&prompt=consent"

This site can’t be reached localhost refused to connect.
Search Google for localhost 9005
ERR_CONNECTION_REFUSED

----------------
tried firebase login --no-localhost also, same error...

**Comment by kevinajian** [comment]
Hi @gurubastade,

Sorry to hear you're having issues. This seems related to https://github.com/firebase/firebase-tools/issues/1442. Can you try the suggestion that Sam says here: https://github.com/firebase/firebase-tools/issues/1442#issuecomment-505970176? If it's the same issue, I'll close this duplicate and we can track it there.

**Comment by gurubastade** [comment]
thanks...
