### ISSUE TITLE
Firebase init Creates new Project in directory does not bring existing project back.

### ISSUE THREAD

**Issue by Sanunez** [firebase/firebase-tools#1563]
When running ``` firebase init ``` and following the prompts a new firebase project is created in the directory instead of fetching existing files.
![2019-07-29 at 3 54 PM](https://user-images.githubusercontent.com/11667825/62081907-384ce200-b219-11e9-8c3f-c7d2616870da.png)

The deployed content should look more like this.
![2019-07-29 at 3 59 PM](https://user-images.githubusercontent.com/11667825/62082414-59620280-b21a-11e9-8768-acd5f39aaf98.png)

**Comment by bkendall** [comment]
This is working as intended. `firebase init` will initialize a directory for new projects, but it does _not_ download/fetch anything from the current project (so, in your example, it does not download all the files in the Hosting site to the local directory).

If you're looking to maintain your source code, I'd recommend using some flavor of source control. If you've lost your files and are trying to get them back, reach out to [support](https://firebase.google.com/support) and they may be able to help you out.
