### ISSUE TITLE
Can't make external http call when testing locally using request-promise or socket.io

### ISSUE THREAD

**Issue by cspecter** [firebase/firebase-tools#1569]
### [REQUIRED] Environment info

**firebase-tools:** 7.2.0

**Platform:** macOS

### [REQUIRED] Test case

I am trying to test a function that makes a call to an external URL using wither request-promise or socket.io-client. When running `firebase serve` or `firebase functions:shell` or `firebase emulators:start` it never makes the call to that url (or any external url). My account is on a paid plan (Blaze) and the call works when deploying, but it refuses to work when testing locally. Is there some setup set I am missing?

### [REQUIRED] Steps to reproduce

The easiest way to test:

```
// Install the request package
npm i --save request
```

```js
//Add the following to index.js
const functions = require('firebase-functions');

// The following code is just to text an external request, it should fire no matter what.
const request = require('request');
request('https://www.google.com', function (error, response, body) {
    console.error('error:', error); // Print the error if one occurred
    console.log('statusCode:', response && response.statusCode); // Print the response status code if a response was received
    console.log('body:', body); // Print the HTML for the Google homepage.
});

const koaFirebase = require('koa-firebase-functions');
const Koa = require('koa');
const Router = require('koa-router');
const koaBody = require('koa-body');
const app = new Koa();
const cors = require('@koa/cors');
const router = new Router();

router
    .get('/', (ctx, next) => {
        console.log("ROOT PATH");
// This could be any http request that grabs data from an external URL.
 request('https://www.google.com', function (error, response, body) {
    if (body) {
ctx.body = {
            status: 'success',
            json: {"message": "YOU DID IT!"}
        }
}
});
    }));

app
    .use(router.routes())
    .use(router.allowedMethods())
    .use(cors({origin: true}));

exports.api = functions.https.onRequest(koaFirebase(app));
```

### [REQUIRED] Expected behavior

It should log something, even an error. 

### [REQUIRED] Actual behavior

Currently, when running locally it it not logging anything at all, like Request is just failing altogether.

**Comment by samtstern** [comment]
@cspecter can you add a but more context here?

- Where in your `index.js` file is that code?
- What `firebase` command are you running?  What output do you get?  What do you expect?

**Comment by cspecter** [comment]
It is the main entry point file. Mine is in `/functions/src/index.js`. If I run `firebase serve` I expect to see some log in the terminal that says "body" with a bunch of markup or "error" with an error message. Currently I see nothing at all. 

In my function I use request-promise to get some data from an external URL. It works when I deploy, but not if I use serve, shell or emulate.

**Comment by samtstern** [comment]
Can you show all of `functions/src/index.js`?  There should be some function definitions, like `exports.myFunction = functions....`

**Comment by cspecter** [comment]
Sure, I updated the original post. I am running my functions via KOA. I have another server with that is acting as a cache. I am trying to make a function that will grab some data from that server, then return it via the firebase cloud function. All I want to do is test this locally. If I deploy the function it works properly. But if I try to run it locally, either with `firebase serve` or `functions:shell` then it will never connect to this external server. It will just fail. 

Is there some setting I am missing or is this just not possible when testing Firebase functions locally? I have tried several http libraries including request, request-promise and axios to no avail.

**Comment by yeahse** [comment]
same issue damn.. what`s the wrong with all of the latest version of firebase things? so many errors out there I can`t do working at all since few days ago, I shouldn`t have updated these damn things. It`s so annoying

**Comment by samtstern** [comment]
@cspecter ok I took your code and messed with it a little bit. See below for the code I was working with.  I ran `firebase emulators:start` and was able to observe the following.

Based on all of the below, everything is working as expected on our side and you just need to update how you handle async operations in your code.  I have never heard of Koa before so apologies if this is not how things are done there.

### 1 - Async Operations

When I try to request your main function you are right I get an issue:
```bash
$ http http://localhost:5002/fir-dumpster/us-central1/api
HTTP/1.1 404 Not Found
connection: keep-alive
content-length: 9
content-type: text/plain; charset=utf-8
date: Thu, 01 Aug 2019 16:30:05 GMT
x-powered-by: Express

Not Found
```

I believe this is because of how you're handling async operations.  If I return a promise from the handler everything works fine. This is me using the `/promise` endpoint I added:

```bash
$ http http://localhost:5002/fir-dumpster/us-central1/api/promise
HTTP/1.1 200 OK
connection: keep-alive
content-length: 53
content-type: application/json; charset=utf-8
date: Thu, 01 Aug 2019 16:31:03 GMT
x-powered-by: Express

{
    "json": {
        "message": "YOU DID IT!"
    },
    "status": "success"
}
```

### 2 - Code in the Global Scope

When I start the emulators I can immediately see that the code in the global scope runs while the emulator parses the code looking for functions triggers:

```bash
$ npx firebase emulators:start 
i  Starting emulators: ["functions","firestore"]
⚠  Your requested "node" version "8" doesn't match your global version "10"
✔  functions: Emulator started at http://localhost:5002
i  firestore: Emulator logging to firestore-debug.log
✔  firestore: Emulator started at http://localhost:8080
i  firestore: For testing set FIRESTORE_EMULATOR_HOST=localhost:8080
i  functions: Watching "/tmp/tmp.j7dq65Weid/functions" for Cloud Functions...
✔  functions[api]: http function initialized (http://localhost:5002/fir-dumpster/us-central1/api).
✔  All emulators started, it is now safe to connect.
⚠  Unknown network resource requested!
   - URL: "http://example.org/"
```

The reason the request does not finish is, again, because of how the async operations are handled.  The runtime does not "know" that it needs to wait for your outstanding request to finish so it just shuts down as soon as it's done the job of parsing function triggers or running the function.

Actually while I run the `/promise` endpoint I can see that the global request *does* have enough time to finish since the runtime is waiting for the other promise!

<hr />

### Full Code

```js
const functions = require('firebase-functions');
const request = require('request');
const Koa = require('koa');
const Router = require('koa-router');
const koaBody = require('koa-body');
const koaFirebase = require('koa-firebase-functions');
const cors = require('@koa/cors');

function requestPromise(url) {
    return new Promise((resolve, reject) => {
        request(url, function(error, response, body) {
            if (error) {
                reject(error);
                return;
            }

            resolve(body);
        });
    });
}

request('http://example.org', function (error, response, body) {
    console.error('error:', error); // Print the error if one occurred
    console.log('statusCode:', response && response.statusCode); // Print the response status code if a response was received
    console.log('body:', body); // Print the HTML for the Google homepage.
});


const app = new Koa();
const router = new Router();

router
    .get('/', (ctx, next) => {
        console.log("ROOT PATH");
        // This could be any http request that grabs data from an external URL.
        request('http://example.org', function (error, response, body) {
            console.log('Inside');
            if (body) {
                ctx.body = {
                    status: 'success',
                    json: { "message": "YOU DID IT!" }
                }
            }
        });
    });

router
    .get('/promise', (ctx, next) => {
        console.log("Promise Path!");
        return requestPromise("http://example.org")
            .then(body => {
                ctx.body = {
                    status: 'success',
                    json: { "message": "YOU DID IT!" }
                }
            });
    });

app
    .use(router.routes())
    .use(router.allowedMethods())
    .use(cors({ origin: true }));

exports.api = functions.https.onRequest(koaFirebase(app));
```

**Comment by cspecter** [comment]
Ok, I moved all my called inside functions and it works. Thanks! Also, I had to move to regular http requests as Socket.io was being inconsistent. Otherwise all good.
