### ISSUE TITLE
Unable to use cloud storage without specifying storageBucket when initialising app with firebase-admin 

### ISSUE THREAD

**Issue by petertriho** [firebase/firebase-tools#1573]
Sorry if this does not belong here, I was not sure whether the issue is related to firebase-tools or firebase-admin-node

### [REQUIRED] Environment info

**firebase-tools:** 7.2.1 and 7.2.2

**Platform:** macOS 

### [REQUIRED] Test case

I am trying to set up an api endpoint which creates an empty folder in the default firebase storage bucket

Using `firebase serve` to emulate the function (expressjs), this works as expected but when deployed using `firebase deploy --project <projectId>` I get the following error:
```
Error: Bucket name not specified or invalid. Specify a valid bucket name via the storageBucket option when initializing the app, or specify the bucket name explicitly when calling the getBucket() method.
    at new FirebaseError (/srv/node_modules/firebase-admin/lib/utils/error.js:42:28)
    at Storage.bucket (/srv/node_modules/firebase-admin/lib/storage/storage.js:107:15)
    at router.post (/srv/api/organisations/document-library.js:6:28)
    at Layer.handle [as handle_request] (/srv/node_modules/express/lib/router/layer.js:95:5)
    at next (/srv/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/srv/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/srv/node_modules/express/lib/router/layer.js:95:5)
    at /srv/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/srv/node_modules/express/lib/router/index.js:335:12)
    at next (/srv/node_modules/express/lib/router/index.js:275:10)
```

### [REQUIRED] Steps to reproduce

1. Set up an expressjs (nodejs 8) cloud function and initialize the Firebase Admin SDK with no arguments.
```
const admin = require('firebase-admin');
admin.initializeApp();
```
2. Add endpoint that accesses the default bucket.
```
app.post('/', (req, res) => {
    const storage = admin.storage();
    const bucket = storage.bucket();
    // do stuff
    res.send('accessed bucket')
}
```

### [REQUIRED] Expected behavior

Because the firebase admin sdk is initialised with no arguments, process.env.FIREBASE_CONFIG should be applied automatically (including the storageBucket key)

### [REQUIRED] Actual behavior

When testing locally with `firebase serve` this works as expected but when deployed, I get error where bucket name is not specified 

I have checked `process.env.FIREBASE_CONFIG` in the deployed function's environment and it is correct: (I have removed the values for this bug report but they are correct)
```
{
  "projectId":<removed>,
  "databaseURL":<removed>,
  "storageBucket":<removed>,
  "locationId":<removed>
}
``` 
On the other hand, `storage.appInternal.options` is incorrect on the deployed function as it is missing all the `process.env.FIREBASE_CONFIG` key/values:
```
{ credential: 
   ApplicationDefaultCredential {
     credential_: MetadataServiceCredential { httpClient: [Object], httpAgent: undefined } } }
```
compared to locally emulated function:
```
{ 
  databaseURL: <removed>,
  storageBucket: <removed>,    
  projectId: <removed>,
  credential: 
     ApplicationDefaultCredential {
       credential_: 
        CertCredential {
          certificate: [Object],
          httpClient: [Object],
          httpAgent: undefined } } }
```

The reason I am checking storage.appInternal.options is because firebase-admin uses the default firebase storage bucket if none is specified as seen on lines 107-108
https://github.com/firebase/firebase-admin-node/blob/master/src/storage/storage.ts
```
const bucketName = (typeof name !== 'undefined')
      ? name :  this.appInternal.options.storageBucket; 
```

**Comment by samtstern** [comment]
@thechenky or @hiranya911 could you take a look at this one?

**Comment by kevinajian** [comment]
Hi @petertriho,

Sorry to hear you're running into this issue. I've tried to reproduce it on my end with a test project and deployed the following:
```
const admin = require('firebase-admin');
admin.initializeApp();

exports.storagePrint = functions.https.onRequest((req, resp) => {
  console.log(process.env.FIREBASE_CONFIG);
  const storage = admin.storage();
  console.log(JSON.stringify(storage.appInternal.options));
  resp.send('accessed bucket');
});
```
and both `FIREBASE_CONFIG` and `storage.appInternal.options` are printing out fine in the logs below:
![image](https://user-images.githubusercontent.com/1319317/62243128-7f5de300-b391-11e9-9dd6-0e4266d19472.png)

Can you share more of your setup so I can figure out what's going on?

**Comment by petertriho** [comment]
Hi @kevinajian,

Thank you for investigating my issue, I've been able to reproduce the issue in an isolated environment (should have done this earlier!). You should be able to deploy this to get the same errors: https://github.com/petertriho/firebase-storage-app

The issue seems to stem from how I'm importing/exporting my express function. As seen here:
https://github.com/petertriho/firebase-storage-app/blob/master/functions/index.js

```
const admin = require('firebase-admin');
admin.initializeApp();
module.exports = {
    express: require('./express')
};
```

vs

```
const admin = require('firebase-admin');
const express = require('./express');
admin.initializeApp();
module.exports = {
    express
};
```

**Comment by kevinajian** [comment]
I noticed in the one that works the difference is the express require comes before the `admin.initializeApp()`, and the one that does not work is the reverse.
I changed the one that does not work to
```
const admin = require('firebase-admin');
module.exports = {
    express: require('./express')
};
admin.initializeApp();
```
and this worked for me. 

I think the issue is `initializeApp()` was not being called before accessing the storage bucket. Let me know if it works for you.

**Comment by petertriho** [comment]
> I think the issue is `initializeApp()` was not being called before accessing the storage bucket. Let me know if it works for you.
I just tried your example and that works for me as well (I think you meant initializeApp after?)

The order of initializing the app definitely appears to be causing the issues but I'm confused on why both scenarios work fine for `firebase serve` and the issue only pops up when deployed

**Comment by kevinajian** [comment]
I believe what's happening is the firebase-functions sdk populates the FIREBASE_CONFIG variable, so it needs to be imported before running `admin.initializeApp()`. In your example admin was initialized first, while the config variable was still empty to be empty.
The emulator also populates the value, so in that case it's not empty when you're initializing.

**Comment by petertriho** [comment]
That makes sense, thank you
