### ISSUE TITLE
firebase-admin has been stubbed (main.dart.js is not found)

### ISSUE THREAD

**Issue by hpoit** [firebase/firebase-tools#1595]
### [REQUIRED] Environment info

**firebase-tools:** 7.0.2

**Platform:** macOS

### [REQUIRED] Test case
Copy the contents of https://github.com/angular-examples/lottery/tree/master/4-final and paste them into `public/`

### [REQUIRED] Steps to reproduce
After pasting the contents into `public/` and changing firebase.json's line to `"public": "public/4-final/web",`, run `firebase serve` under the app directory. 

### [REQUIRED] Expected behavior
To see the app running in https://lotterysimulator.web.app/

### [REQUIRED] Actual behavior
![image](https://user-images.githubusercontent.com/3711100/62896368-4de8fe00-bd27-11e9-9e2f-9eac1a590705.png)

**Comment by hpoit** [comment]
More details on the actual behavior:
![image](https://user-images.githubusercontent.com/3711100/62897487-c3ee6480-bd29-11e9-822f-28c58d2c1665.png)

**Comment by hpoit** [comment]
`firebase serve --debug`: https://gist.github.com/hpoit/76cf9851a4323da51fa7d44ccf3be667

**Comment by hpoit** [comment]
Might this be a build issue such that `main.dart.js` is not found?

**Comment by hpoit** [comment]
Inside `public/` I have:
![image](https://user-images.githubusercontent.com/3711100/62909052-6a9a2b80-bd51-11e9-9810-a5ff1824d402.png)

**Comment by hpoit** [comment]
How is `build/web/index.html` rewritten to link `main.dart.js` under the new Dart 2? 

I understand `dart_to_js_script_rewriter` was dropped. Where could I learn more about its replacement?

**Comment by hpoit** [comment]
Good morning. "For your new inquiry regarding "firebase-admin has been stubbed.", I suggest you file a new support ticket for this, as this seems to be an issue related to Cloud Functions. This way, we can track down requests and issues separately, and provide you a better support experience." (from Firebase Support this morning)

**Comment by hpoit** [comment]
Copy of email to Firebase Support this morning:

Good morning Yel. My `public/4-final/web/index.html` is exactly the same as https://github.com/angular-examples/lottery/blob/master/4-final/web/index.html. Also, I've pasted all the contents of https://github.com/angular-examples/lottery/tree/master/4-final under `public`. 

Additionally, my local implementation is perfectly working:
![image](https://user-images.githubusercontent.com/3711100/62941024-64d13400-bdab-11e9-8dbe-2f0a4843713c.png)


Do you still think this is an implementation issue? Thanks, Kevin

**Comment by hpoit** [comment]
My `firebase.json`: https://gist.github.com/hpoit/29731b5349d4fe9d349efccfa7e9f333

**Comment by hpoit** [comment]
Might `southamerica-east1` be the issue wrt Cloud Functions?:
![image](https://user-images.githubusercontent.com/3711100/62943629-4e2ddb80-bdb1-11e9-94d9-db55acc4856d.png)

**Comment by bkendall** [comment]
I am able to get the same initial behavior that you do. What is the build process for getting `web/main.dart` to produce a `web/main.dart.js` file? It seems like there's a build step missing somewhere...

**Comment by hpoit** [comment]
> What is the build process for getting `web/main.dart` to produce a `web/main.dart.js` file?

Hi Bryan, how do I provide you with that info? I've been asked that same question before, to which I didn't know how to answer. Also, I've re-formatted my macOS, so I'll reproduce it again based on the instructions above.

**Comment by bkendall** [comment]
Browsers are not able to interpret the dart file; it must be compiled to javascript so that the browser can understand it. According to the readme of the repo, using `webdev serve` probably does that build process under the hood. There's some "build" step missing for that `main.dart` file, but that is beyond the scope of my knowledge. I'd look for some assistance in the Angular community, or sometimes some folks in the [Firebase Slack Community](https://firebase.community) can help as well.

Since this isn't an issue with the CLI (this repo), I'm going to close this issue. I hope you're able to find the assistance you need!
