### ISSUE TITLE
cannot login from different device

### ISSUE THREAD

**Issue by iwikal** [firebase/firebase-tools#1596]
### [REQUIRED] Environment info

**firebase-tools:** 7.2.2

**Platform:** macOS and Ubuntu

### [REQUIRED] Test case

I use Ubuntu for most things at work, however, I have to ssh to a mac from time to time. If I try to login on the mac, and visit the URL provided in the browser on Ubuntu, it tells me localhost refused the connection.

### [REQUIRED] Steps to reproduce

 - invoke `firebase login`
 - the output tells you to "Visit this URL on any device to log in"
 - visit the url on a different device
 - connection refused

### [REQUIRED] Expected behavior

I expected to be able to visit the URL on any device to log in

### [REQUIRED] Actual behavior

```
[2019-08-13T14:05:25.254Z] ----------------------------------------------------------------------
[2019-08-13T14:05:25.258Z] Command:       /usr/local/Cellar/node/11.9.0/bin/node /usr/local/bin/firebase --debug login
[2019-08-13T14:05:25.258Z] CLI Version:   7.2.2
[2019-08-13T14:05:25.258Z] Platform:      darwin
[2019-08-13T14:05:25.258Z] Node Version:  v11.9.0
[2019-08-13T14:05:25.259Z] Time:          Tue Aug 13 2019 16:05:25 GMT+0200 (Central European Summer Time)
[2019-08-13T14:05:25.259Z] ----------------------------------------------------------------------

? Allow Firebase to collect anonymous CLI usage and error reporting information? Yes

Visit this URL on any device to log in:
https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=653572766&redirect_uri=http%3A%2F%2Flocalhost%3A9005

Waiting for authentication...
```
then nothing happens.

I was able to log in with the `--no-localhost` flag.

**Comment by abeisgoat** [comment]
This seems like expected behavior, in order for the CLI to recognize the auth it needs to redirect to `localhost` as long as you're able to use `--no-localhost` then this seems all correct to me!

**Comment by iwikal** [comment]
Sure, I definitely understand why it happens, but the message needs to be
fixed. It says "from any device".

**Comment by bkendall** [comment]
Fix in the above PR. Thanks for the feedback.
