### ISSUE TITLE
Add support for golang functions

### ISSUE THREAD

**Issue by lukepighetti** [firebase/firebase-tools#1598]
Allow us to select `golang` when initializing functions, as well as deploy them.

**Comment by bkendall** [comment]
Thank you for the wonderful feature request!

This request is better suited to go through our support channel, through the [feature request](https://firebase.google.com/support/troubleshooter/report/features/) form. Thanks!

**Comment by lukepighetti** [comment]
@bkendall I originally make this issue so I had something to close against if I was going to add golang support to firebase tooling. Is there appetite for a PR to resolve this issue?

**Comment by mbleigh** [comment]
To properly support Go (which I love working with, fwiw) for Cloud Functions for Firebase, it would require creating and maintaining an equivalent SDK to the `firebase-functions` Node.js SDK, including means of parsing triggers from code, defining exports, etc.

While generally "PRs welcome" is the case, the amount of design, code, and maintenance involved in providing first class Go support makes it something that is infeasible to support at present.
