### ISSUE TITLE
[error] Error: An unexpected error has occurred - firebase Login

### ISSUE THREAD

**Issue by mcollinar** [firebase/firebase-tools#1599]
Hi,

I'm working with Ionic 4  and install the Firebase Tolls and every thing gone well, after that i've try to run the Firebase login.
 On the Firebase Login, give me this issue:

[error] Error: An unexpected error has occurred

When I get the firebase debug, I tried to access the Login URL in chrome, after give all the user permission, the page stop respond, and went to localhost:8100

Can any one Help me?

**Comment by mcollinar** [comment]
firebase debug file

[debug] [2019-08-15T03:31:07.827Z] ----------------------------------------------------------------------
[debug] [2019-08-15T03:31:07.836Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\Marcelo\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js login
[debug] [2019-08-15T03:31:07.837Z] CLI Version:   7.2.2
[debug] [2019-08-15T03:31:07.837Z] Platform:      win32
[debug] [2019-08-15T03:31:07.837Z] Node Version:  v10.16.2
[debug] [2019-08-15T03:31:07.841Z] Time:          Thu Aug 15 2019 00:31:07 GMT-0300 (GMT-03:00)
[debug] [2019-08-15T03:31:07.841Z] ----------------------------------------------------------------------
[debug] 
[info] 
[info] Visit this URL on any device to log in:
[info] https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=653176544&redirect_uri=http%3A%2F%2Flocalhost%3A9005
[info] 
[info] Waiting for authentication...
[debug] [2019-08-15T03:31:17.129Z] Error: spawn cmd ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[error] 
[error] Error: An unexpected error has occurred.

**Comment by nasro13** [comment]
Hello i have the same exact error as you and i didn't find solution please help us

**Comment by nasro13** [comment]
i fixed it here is whats i did : i added this to my variable path >>> C:\Program Files;C:\Winnt;C:\Winnt\System32;C:\Windows\System32

**Comment by mcollinar** [comment]
Yes...we need to change the Variable system.... thank you...

**Comment by PratapTyagi** [comment]
i did not got it
