### ISSUE TITLE
Error: Authentication required

### ISSUE THREAD

**Issue by zosocanuck** [firebase/firebase-tools#160]
Hi,

I recently upgraded to the new Firebase console however when running firebase deploy I get

Error: Authentication required.

So I logout and then login again however still get the same results.

Any ideas?

**Comment by mbleigh** [comment]
Can you please run `firebase deploy --debug` and paste the output here? Also, what do you get when you run `firebase list`? Do you see the project there?

One final thing to check is to make sure that you are deploying to the **project id** not the **subdomain** of your app.

**Comment by zosocanuck** [comment]
Ok, I ended up upgrading nodejs on my windows laptop and firebase list did show my projects.  But when I run firebase deploy I get:

Error: Unable to authorize access to project milohas

Note: This version of the Firebase CLI is only compatible with projects upgraded
to the new Firebase Console. To access firebase.com apps, you will need to
use a previous version: npm install -g firebase-tools@^2.1

I do have permission to access this project as I am successfully able to run firebase deploy on a Fedora 23 VM.

**Comment by mbleigh** [comment]
When you run `firebase list`, do you see a different project id and instance name for this project? If so, make sure your `.firebaserc` file has the *project id* not the instance/subdomain name.

**Comment by hickford** [comment]
I have the same problem:

    $ firebase deploy
    Error: Authentication required.
    $ firebase login
    Already logged in as ****@gmail.com

This happened after 'upgrading' my app from the 'legacy console' at https://console.firebase.google.com/ to https://console.firebase.google.com/

**Comment by tavosansal** [comment]
Having the same issue here. When I do ```firebase list``` I do not see my project. I recently upgraded to the new Firebase and started getting these issues. Some help on this would be appreciated since I can no longer deploy my project. Is there a way to manually deploy stuff??

**Comment by tavosansal** [comment]
Any update on this? I literally cannot deploy any updated with a fix for this.

**Comment by hickford** [comment]
@tavosansal try `npm install -g firebase-tools@2`

**Comment by Lionardo** [comment]
I have the same issue for a while now. I tried a couple of things like downgrading firebase-tools@2, I have the project id on .firebaserc and no subdomain but nothing works. I get no project listed on firebase list but i clearly have a project on the dashboard. I also tried to deploy with a FIREBASE_TOKEN but without success. Here is my firebase --debug
```json
Error Context: {
  "requestOptions": {
    "method": "GET",
    "json": true,
    "url": "https://admin.firebase.com/firebase/talentmap/token?token=-KFQF7KUYFZ7AvBQG_FN%7Ca3600ce1d3feedf3bb38df18a5e3199f"
  },
  "body": {
    "error": {
      "code": "AUTHENTICATION_REQUIRED",
      "message": "Authentication required."
    }
  },
  "response": {
    "statusCode": 401,
    "body": {
      "error": {
        "code": "AUTHENTICATION_REQUIRED",
        "message": "Authentication required."
      }
    },
    "headers": {
      "server": "nginx",
      "date": "Sun, 27 Nov 2016 14:30:16 GMT",
      "content-type": "application/json; charset=utf-8",
      "content-length": "81",
      "connection": "close",
      "access-control-allow-origin": "*",
      "access-control-allow-methods": "GET, PUT, POST, DELETE, OPTIONS",
      "x-content-type-options": "nosniff"
    },
    "request": {
      "uri": {
        "protocol": "https:",
        "slashes": true,
        "auth": null,
        "host": "admin.firebase.com",
        "port": 443,
        "hostname": "admin.firebase.com",
        "hash": null,
        "search": "?token=-KFQF7KUYFZ7AvBQG_FN%7Ca3600ce1d3feedf3bb38df18a5e3199f",
        "query": "token=-KFQF7KUYFZ7AvBQG_FN%7Ca3600ce1d3feedf3bb38df18a5e3199f",
        "pathname": "/firebase/talentmap/token",
        "path": "/firebase/talentmap/token?token=-KFQF7KUYFZ7AvBQG_FN%7Ca3600ce1d3feedf3bb38df18a5e3199f",
        "href": "https://admin.firebase.com/firebase/talentmap/token?token=-KFQF7KUYFZ7AvBQG_FN%7Ca3600ce1d3feedf3bb38df18a5e3199f"
      },
      "method": "GET",
      "headers": {
        "accept": "application/json"
      }
    }
  }
}
```

**Comment by arangates** [comment]
i faced same issue ... i did `firebase logout `and then tried again.Everything worked out !

**Comment by ckunta** [comment]
I'm facing the same issue from last night. No change on the firebase-cli and I was able to deploy successfully earlier (about 3 hours prior).  I tried login/logout but still not working. I noticed that running curl I received 'AUTHENTICATION_REQUIRED' return. And running firebase deploy I received 'Auth token is expired', but I don't know how to renew it. I can still get into the Firebase console with the same account without any problem.
Here are the capture.

> curl https://admin.firebase.com/v1/database/fir-auth-a8de1/tokens
curl : {"error":{"code":"AUTHENTICATION_REQUIRED","message":"Authentication required."}}
At line:1 char:1
+ curl https://admin.firebase.com/v1/database/fir-auth-a8de1/tokens
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

> firebase deploy --debug
----------------------------------------------------------------------
Command:      C:\Program Files\nodejs\node.exe E:\AppData\Roaming\npm\node_modules\firebase-tools\bin\firebase deploy --debug
CLI Version:  3.2.1
Platform:     win32
Node Version: v4.4.4
Time:         Wed May 10 2017 07:05:35 GMT-0600 (Mountain Daylight Time)
----------------------------------------------------------------------

.....

> command requires scopes: >>> HTTP REQUEST GET https://admin.firebase.com/v1/database/fir-auth-a8de1/tokens
<<< HTTP RESPONSE 200 server=nginx, date=Wed, 10 May 2017 13:05:33 GMT, content-type=application/json; charset=utf-8, content-length=427, connection=close, x-content-type-options=nosniff, strict-transport-security=max-age=31536000; includeSubdomains, cache-control=no-cac
he, no-store

=== Deploying to 'fir-auth-a8de1'...

i  deploying database, hosting
+  database: rules ready to deploy.
i  hosting: preparing build/unbundled directory for upload...
>>> HTTP REQUEST PUT https://deploy.firebase.com/v1/hosting/fir-auth-a8de1/uploads/-KjmSjLly1XDXU2bv9tZ?fileCount=1630&message=
FIREBASE WARNING: auth() was canceled: Auth token is expired.

**Comment by saifalfalah** [comment]
I removed firebase.json and .firebaserc and ran firebase init again. It worked.

**Comment by ckunta** [comment]
Thank you. I'll keep that in mind if it happens again. I don't remember how I resolved it then.
