### ISSUE TITLE
New project outputs white text

### ISSUE THREAD

**Issue by briangriffey** [firebase/firebase-tools#161]
When starting a new firebase project I encountered text that was white on top of my white background. I'm on OSX El Capitain 10.11.4, using iTerm 2. A picture can be seen here: https://www.dropbox.com/s/15xend1poafgncm/CjvGLlWUgAE0tXe.jpg?dl=0. To reproduce, freshly install node, and firebase cli tools; then init a new project in a new directory.

**Comment by mbleigh** [comment]
@briangriffey quick question for you: what happens when you do `bower init` (`npm install -g bower` if you don't have it). We use the same prompt library as Bower, and I'm curious if the same problem shows up there since the prompts are totally blank in your screenshot.

**Comment by briangriffey** [comment]
It has the same problems. the prompts are white. https://www.dropbox.com/s/tjlp5h4oakn1jvq/Screen%20Shot%202016-06-01%20at%2011.31.43%20PM.png?dl=0

**Comment by mbleigh** [comment]
:angry: :open_mouth: hmm. I'm not really sure what to do here. I think there's quite a bit of utility in using bold fonts to call out identifiers, and I'm not at all sure why iTerm2 would default to showing bold as white on white.

Clearly the problem reaches beyond just the Firebase CLI, but I'm certainly open to ideas on how to address it...
