### ISSUE TITLE
Install new version of firebase-tools will corrupt firebase-admin

### ISSUE THREAD

**Issue by 25huizengek1** [firebase/firebase-tools#1611]
I saw a message that firebase-tools could be upgraded, so I did the following: `npm i -g firebase-tools@7.2.4`. But when i initialized a new project, Firebase asked me to install all of the npm dependencies, but that didn't work. 

Logs:
```
? Do you want to install dependencies with npm now? Yes
npm ERR! Unexpected end of JSON input while parsing near '...lKbOgz75+tsW7Pywr0hjv'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Gebruiker\AppData\Roaming\npm-cache\_logs\2019-08-20T12_21_57_235Z-debug.log
```
Sorry, but C:\Users\Gebruiker\AppData\Roaming\npm-cache\_logs\2019-08-20T12_21_57_235Z-debug.log is lost on my PC. (I actually don't know why, but it doesn't exist)

**Comment by bkendall** [comment]
Please follow the issue template. There's not enough information here to debug this, though it looks like `npm` failed in some way. If you can provide a case to reproduce this, please follow up, otherwise there's not much we can do.

**Comment by 25huizengek1** [comment]
I fixed it by myself now. It was the npm cache. I'll follow up the template next time. I did `npm cache clean --force` and it was fixed.
