### ISSUE TITLE
npm i -g firebase-tools leads to ...firebase.ps1 cannot be loaded because running scripts is disabled on this system

### ISSUE THREAD

**Issue by Mada75** [firebase/firebase-tools#1627]
I've come across the following error today after updating firebase-tools.
I use Visual Studio Code and after the latest firebase update I'm not able to run any firebase scripts in the PowerShell terminal.
I can run them in cmd and I can run other scripts still in PowerShell, eg npm and Netlify hosting.
I was using firebase in one project after deploying earlier today, got the prompt to update firebase-tools, did so, and now cant access firebase in any project from PowerShell. 
Been using without issue for 6+months.

### [REQUIRED] Environment info

+ firebase-tools@7.2.4

// Can't run this command but package.json says:
    "firebase": "^5.11.1",

**Platform:**
Windows 10 Home

### [REQUIRED] Test case
1. Install Visual Studio Code
2. Open a new file/folder
3. In terminal - 
npm install -g firebase-tools
4. In **PowerShell** terminal - 
firebase // followed by any command
leads to error : 
firebase : File C:\Users\mada7\AppData\Roaming\npm\firebase.ps1 cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at 
https:/go.microsoft.com/fwlink/?LinkID=135170.

### [REQUIRED] Steps to reproduce

As above

### [REQUIRED] Expected behavior
firebase to run scripts in powershell, which worked until updating firebase-tools to the latest version.

### [REQUIRED] Actual behavior
// can't run with --debug flag in Powershell
PS C:\web-dev\cv> firebase
firebase : File C:\Users\mada7\AppData\Roaming\npm\firebase.ps1 cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at 
https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ firebase
+ ~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

// running in cmd 
Microsoft Windows [Version 10.0.18362.295]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\web-dev\cv>firebase --debug
[2019-08-27T08:50:01.286Z] ----------------------------------------------------------------------
[2019-08-27T08:50:01.290Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\mada7\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js --debug
[2019-08-27T08:50:01.291Z] CLI Version:   7.2.4
[2019-08-27T08:50:01.291Z] Platform:      win32
[2019-08-27T08:50:01.292Z] Node Version:  v10.16.3
[2019-08-27T08:50:01.293Z] Time:          Tue Aug 27 2019 09:50:01 GMT+0100 (British Summer Time)
[2019-08-27T08:50:01.293Z] ----------------------------------------------------------------------

Usage: firebase [options] [command]

**Comment by jwv** [comment]
I have the same error.
Temp solution:
`Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope CurrentUser`

**Comment by HeatDaHpmepro** [comment]
> I have the same error.
> Temp solution:
> `Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope CurrentUser`

is it safe?

**Comment by jwv** [comment]
> > I have the same error.
> > Temp solution:
> > `Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope CurrentUser`
> 
> is it safe?

Unfortunately it's not safe. If you choose use this police very careful when use package manager like chocolatey.

**Comment by Mada75** [comment]
So, I updated vue.js later in that day and got errors running those scripts too.
Posted the problem on the Vue forum and got directed to Stackoverflow, a user on there replied with a similar workaround, which I've reluctantly done.
[https://stackoverflow.com/questions/57673913/vsc-powershell-after-npm-updating-packages-ps1-cannot-be-loaded-because-runnin](url)

**Comment by claytonsurgeon** [comment]
Ran into this issue updating from 7.3.1 to 7.3.2

**Comment by mohsinraza2223** [comment]
> I have the same error.
> Temp solution:
> `Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope CurrentUser`

It's a good solution and works for me.

**Comment by epebojot** [comment]
> > > I have the same error.
> > > Temp solution:
> > > `Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope CurrentUser`
> > 
> > 
> > is it safe?
> 
> Unfortunately it's not safe. If you choose use this police very careful when use package manager like chocolatey.

Well, try this:

> PS C:\> Set-ExecutionPolicy RemoteSigned 

Then run your chosen firebase syntax command.

**Comment by amit-kumar-dubey** [comment]
used this Set-ExecutionPolicy RemoteSigned that work for me.
thanks

**Comment by pritamshinde** [comment]
After the effort, I think Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope CurrentUser is good option to fix the issue.you can go with this it will not create issue.

**Comment by pritamshinde** [comment]
If you try to generate command on cmd it will be work instead of VS Code Terminal.

**Comment by rajachennupati** [comment]
Remove ng.ps1(respective ps1 file) from the directory C:\Users\< username >\AppData\Roaming\npm\ then try clearing the npm cache at C:\Users\< username >\AppData\Roaming\npm-cache\..

this worked for me

**Comment by saif01** [comment]
> Remove ng.ps1(respective ps1 file) from the directory C:\Users< username >\AppData\Roaming\npm\ then try clearing the npm cache at C:\Users< username >\AppData\Roaming\npm-cache..
> 
> this worked for me

**Comment by nvrr** [comment]
> > I have the same error.
> > Temp solution:
> > `Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope CurrentUser`
> 
> It's a good solution and works for me.

i think its slow downs ur system after that

**Comment by DavidHCox** [comment]
> Remove ng.ps1(respective ps1 file) from the directory C:\Users< username >\AppData\Roaming\npm\ then try clearing the npm cache at C:\Users< username >\AppData\Roaming\npm-cache..
> 
> this worked for me

This 100% works. Do what he said above and delete that .ps1 file (aka Windows Powershell Script) and then run the command `npm cache clean`.

**Comment by nvrr** [comment]
![Screenshot (63)](https://user-images.githubusercontent.com/57614350/70814030-a670fa80-1df0-11ea-8aa2-6ff519418a20.png)


> > Remove ng.ps1(respective ps1 file) from the directory C:\Users< username >\AppData\Roaming\npm\ then try clearing the npm cache at C:\Users< username >\AppData\Roaming\npm-cache..
> > this worked for me
> 
> @rajachennupati's way 100% works. Do what he said above and delete that .ps1 file (aka Windows Powershell Script) and then run the command `npm cache clean`.

![Screenshot (63)](https://user-images.githubusercontent.com/57614350/70814067-bbe62480-1df0-11ea-94ac-570d695606b9.png)
but its shows this ,how to fix

**Comment by nvrr** [comment]
> > Remove ng.ps1(respective ps1 file) from the directory C:\Users< username >\AppData\Roaming\npm\ then try clearing the npm cache at C:\Users< username >\AppData\Roaming\npm-cache..
> > this worked for me
> 
> @rajachennupati's way 100% works. Do what he said above and delete that .ps1 file (aka Windows Powershell Script) and then run the command `npm cache clean`.

![Screenshot (63)](https://user-images.githubusercontent.com/57614350/70814201-07003780-1df1-11ea-8508-6afc6a254239.png)
but its show this ,how to fix---i do all u said above

**Comment by DavidHCox** [comment]
@nvrr Do `npm cache clean --force` this will for sure remove everything from cache. If you are not comfortable with cleaning your entire cache. I suggest doing some research on how to do it more safely.

**Comment by nvrr** [comment]
> npm cache clean --force

i do it, but it shows this   

 C:\Users\NVRR\documents\cera\Bootstrap4\conFusion> npm cache clean --force
npm WARN using --force I sure hope you know what you are doing.
PS C:\Users\NVRR\documents\cera\Bootstrap4\conFusion> npm cache verify
Cache verified and compressed (~\AppData\Roaming\npm-cache\_cacache):
Content verified: 0 (0 bytes)
Index entries: 0
Finished in 0.03s
PS C:\Users\NVRR\documents\cera\Bootstrap4\conFusion> lessc styles.less styles.css
lessc: ENOENT: no such file or directory, open 'C:\Users\NVRR\documents\cera\Bootstrap4\conFusion\styles.less'

**Comment by nvrr** [comment]
> > npm cache clean --force
> 
> i do it, but it shows this
> 
> C:\Users\NVRR\documents\cera\Bootstrap4\conFusion> npm cache clean --force
> npm WARN using --force I sure hope you know what you are doing.
> PS C:\Users\NVRR\documents\cera\Bootstrap4\conFusion> npm cache verify
> Cache verified and compressed (~\AppData\Roaming\npm-cache_cacache):
> Content verified: 0 (0 bytes)
> Index entries: 0
> Finished in 0.03s
> PS C:\Users\NVRR\documents\cera\Bootstrap4\conFusion> lessc styles.less styles.css
> lessc: ENOENT: no such file or directory, open 'C:\Users\NVRR\documents\cera\Bootstrap4\conFusion\styles.less'

i think deleting npm-cache folder directly appdata/roaming/npm-cache
is it okkk to do?

**Comment by varun30300** [comment]
> 
> 
> I have the same error.
> Temp solution:
> `Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope CurrentUser`

it worked

**Comment by epebojot** [comment]
Can someone close this issue??

**Comment by Tin0** [comment]
> > I have the same error.
> > Temp solution:
> > `Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope CurrentUser`
> 
> It's a good solution and works for me.



> > I have the same error.
> > Temp solution:
> > `Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope CurrentUser`
> 
> it worked

this worked for me..thanks >>> Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope CurrentUser

**Comment by AshrafSada** [comment]
Allow remote signed scripts for current user:
`Set-ExecutionPolicy RemoteSigned -Scope CurrentUser`

**Comment by HeyAshh** [comment]
Could we get someone smart to explain why `Set-ExecutionPolicy RemoteSigned -Scope CurrentUser` solves the issue, and why so many of us are getting errors in the first place?

It worked for me too btw.

**Comment by ptoro** [comment]
@HeyAshh exactly. Feels like this issue hasn't actually been solved only a workaround provided. In that case, it should be reopened and fixed.

**Comment by samtstern** [comment]
The documentation from Microsoft is here:
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7

It seems that in some cases PowerShell blocks "scripts".  I am not sure what qualifies the Firebase CLI as a script under this policy or if we have done anything to change it recently but I don't think there is anything we can do to change this very system/shell specific behavior.  If anyone has an idea we'd love to hear it though!

Also for users having this issue: do you have the same issue with other node-based CLIs?  If you `npm install -g prettier` are you able to run` prettier` afterwards?

**Comment by shadabumer** [comment]
I was able to run the firebase command using **git bash** without any problem

**Comment by pemalodayx** [comment]
Hi i solved this error with change  of running Script terminal.
I run it on power Shell 1 terminal and then i switch to next

**Comment by k96white** [comment]
Hey Deleting the firebase.ps1 file at the mentioned location worked for me without compromising security, hope it helps

**Comment by DjangoOverloard** [comment]
it makes me wonder why this bug is still a thing

**Comment by Qasim505** [comment]
Set-ExecutionPolicy RemoteSigned -Scope CurrentUser
Use this one for same problem it is somehow safe

**Comment by 0racles** [comment]
@k96white Yes deleting firebase.ps1 file definitely helped

**Comment by LinzNT** [comment]
> If you try to generate command on cmd it will be work instead of VS Code Terminal.

It also works if you are in your git bash, haven't tried just Powershell, think it is a VS Code issue.

**Comment by anuj081098** [comment]
> I have the same error.
> Temp solution:
> `Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope CurrentUser`

yes it's working thanks

**Comment by HeyAshh** [comment]
hi

**Comment by Lokesh04** [comment]
> Remove ng.ps1(respective ps1 file) from the directory C:\Users< username >\AppData\Roaming\npm\ then try clearing the npm cache at C:\Users< username >\AppData\Roaming\npm-cache..
> 
> this worked for me

Works perfect without other issues.

**Comment by petrostriant** [comment]
make sure you use cmd bash instead of powershell in vscode , that worked for me;)

**Comment by Malsha6** [comment]
> > Remove ng.ps1(respective ps1 file) from the directory C:\Users< username >\AppData\Roaming\npm\ then try clearing the npm cache at C:\Users< username >\AppData\Roaming\npm-cache..
> > this worked for me
> 
> @rajachennupati's way 100% works. Do what he said above and delete that .ps1 file (aka Windows Powershell Script) and then run the command `npm cache clean`.

**Comment by Malsha6** [comment]
Worked for me

**Comment by hariprasath2603** [comment]
This is only on built-in VSCode terminal in windows default CMD it just works fine.

**Comment by asharuDheen-code** [comment]
"terminal.integrated.shellArgs.windows": ["-ExecutionPolicy", "Bypass"],
.
.
Try this one inside PREFERENCES settings -> Search Automation and  add inside this"Terminal › Integrated › Automation Shell: Linux" -> ADD NEW  "terminal.integrated.shellArgs.windows": ["-ExecutionPolicy", "Bypass"], THIS

**Comment by kamarulkhairi** [comment]
I used Powershell Integrated console for vscode and it seems to work perfectly fine

**Comment by malikwaqar** [comment]
C:\Users\{username}\AppData\Roaming\npm\firebase.ps1
I deleted this file and it works for me.

**Comment by SivaNagaRajuBits** [comment]
> The documentation from Microsoft is here:
> https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7
> 
> It seems that in some cases PowerShell blocks "scripts". I am not sure what qualifies the Firebase CLI as a script under this policy or if we have done anything to change it recently but I don't think there is anything we can do to change this very system/shell specific behavior. If anyone has an idea we'd love to hear it though!
> 
> Also for users having this issue: do you have the same issue with other node-based CLIs? If you `npm install -g prettier` are you able to run` prettier` afterwards?

Nope... Not able to run Prettier or ES7 snippets. Now it threw an exception to deploy the project on Firebase as well... Looking for a safe alternative.

**Comment by pooyaaf** [comment]
well I read something on StackOverflow and that worked for me 
and that's it :
"Just delete firebase.ps1 file"
---

**Comment by RahulBavaliya** [comment]
> I have the same error.
> Temp solution:
> `Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope CurrentUser`

its worked for me thanks...

**Comment by Yola21** [comment]
> Remove ng.ps1(respective ps1 file) from the directory C:\Users< username >\AppData\Roaming\npm\ then try clearing the npm cache at C:\Users< username >\AppData\Roaming\npm-cache..
> 
> this worked for me

It's 100% working. Thanks but still I didn't get it what just happened.

**Comment by fk5643** [comment]
> C:\Users{username}\AppData\Roaming\npm\firebase.ps1
> I deleted this file and it works for me.

Yes this worked for me too

**Comment by vule993** [comment]
Just delete the file

**Comment by samazon** [comment]
> > C:\Users{username}\AppData\Roaming\npm\firebase.ps1
> > I deleted this file and it works for me.
> 
> Yes this worked for me too

This solved the problem for me as well

**Comment by MousamBhalekar** [comment]
> > Remove firebase.ps1(respective ps1 file) from the directory C:\Users< username >\AppData\Roaming\npm\ then try clearing the npm cache at C:\Users< username >\AppData\Roaming\npm-cache..   ( npm cache clean --force )
> > this worked for me

this work for me!! thank you

**Comment by oktemerbay** [comment]
If you are on Windows Powershell , switch to Windows Command Line by typing cmd , and then firebase command should work.

**Comment by anikettari** [comment]
> used this Set-ExecutionPolicy RemoteSigned that work for me.
> thanks

Woaaahhhhh! working

**Comment by R2rit0** [comment]
For whoever is still facing this issue, and try everything and still face this problem. If you are trying to run the command in vs-code, don't. For some reason, the command does **work** in **Git Bash**.

**Comment by AnasMually** [comment]
> I have the same error.
> Temp solution:
> `Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope CurrentUser`

thank you

**Comment by mahin-hossen** [comment]
> Remove ng.ps1(respective ps1 file) from the directory C:\Users< username >\AppData\Roaming\npm\ then try clearing the npm cache at C:\Users< username >\AppData\Roaming\npm-cache..
> 
 >Removed ps1 file from that folder and used command npm-cache clean --force. thankfully it worked

**Comment by H4mxa** [comment]
> ## well I read something on StackOverflow and that worked for me
> and that's it :
> "Just delete firebase.ps1 file"

Wow work for me! you can find location of file using `npm list -g`.

**Comment by coder-kiran** [comment]
install this extension in vs code and it's DONE

PowerShell
ms-vscode.powershell

**Comment by dk1242** [comment]
> Remove ng.ps1(respective ps1 file) from the directory C:\Users< username >\AppData\Roaming\npm\ then try clearing the npm cache at C:\Users< username >\AppData\Roaming\npm-cache..
> 
> this worked for me

It worked for me.

**Comment by ahsanxhussain** [comment]
> I have the same error.
> Temp solution:
> `Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope CurrentUser`

well it works for me, cheers

**Comment by AndyJPG** [comment]
Instead of setting execution policy, I ran prompt as administrator and use firebase command without an issue.

**Comment by diannayanuaresta** [comment]
delete firebase.ps1 then clear cache in npm, work for me

**Comment by arslan2info** [comment]
upgrade your PowerShell in VS Code of you are using

**Comment by suthasp** [comment]
> Hey Deleting the firebase.ps1 file at the mentioned location worked for me without compromising security, hope it helps

Yes deleting firebase.ps1 work for me.

**Comment by suthasp** [comment]
> **[k96white](/k96white) ** commented [on 31 Mar 2020](#issuecomment-606656286)
Yes deleting firebase.ps1 work for me.

**Comment by JoeAlx** [comment]
> Remove ng.ps1(respective ps1 file) from the directory C:\Users< username >\AppData\Roaming\npm\ then try clearing the npm cache at C:\Users< username >\AppData\Roaming\npm-cache..
> 
> this worked for me

**Comment by JoeAlx** [comment]
That worked perfectly for me

**Comment by Emran12** [comment]
I have faced the same problem. I switched PowerShell to git bash and solve my problems.

**Comment by adelbenhamadi** [comment]
it's just a conflict of names just execute:
`firebase.cmd login` instead of  `firebase login`
this will resolve the conflict

**Comment by johnchristotle** [comment]
Remove ng.ps1(respective ps1 file) from the directory C:\Users< username >\AppData\Roaming\npm\ then try clearing the npm cache at C:\Users< username >\AppData\Roaming\npm-cache..

this worked for me. Let someone close this thread. Thanks

**Comment by guplem** [comment]
> > > C:\Users{username}\AppData\Roaming\npm\firebase.ps1
> > > I deleted this file and it works for me.
> > 
> > 
> > Yes this worked for me too
> 
> This solved the problem for me as well

This did the trick!

**Comment by michhub-dev** [comment]
> I have the same error. Temp solution: `Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope CurrentUser`

Worked for me. Thank you

**Comment by AliMasaoodi** [comment]
### Simply delete the firebase.ps1 file at the folder shown by the error message and try to run the command again.

> If the above does not work may require to clear your npm cache by running 

`npm cache clean --force`

**Comment by barzagli** [comment]
I ran through a similar issue using Windows, this might help somebody else.


Step 1 : open Windows PowerShell (Run as administrator)

Step 2 : Type in Get-ExecutionPolicy -List and hit Enter.

Step 3 : Type in Set-ExecutionPolicy Unrestricted and hit Enter again.

Step 4 : Type Y and hit Enter.

Step 5 : Type Set-ExecutionPolicy Unrestricted -Force and hit Enter.

**Comment by itsMHmoon** [comment]
You can just run it in cmd.

**Comment by Fariha1865** [comment]
> Remove ng.ps1(respective ps1 file) from the directory C:\Users< username >\AppData\Roaming\npm\ then try clearing the npm cache at C:\Users< username >\AppData\Roaming\npm-cache..
> 
> this worked for me thanks !!!

**Comment by codescarlett** [comment]
I removed C:\Users< username >\AppData\Roaming\npm\firebase.ps1

Then ran firebase login to confirm I was still logged in and deployed successfully.

**Comment by tanmai21** [comment]
used this: Set-ExecutionPolicy RemoteSigned -Scope CurrentUser that work for me.
thanks a lot

**Comment by savioqm** [comment]
> > ## well I read something on StackOverflow and that worked for me
> > and that's it :
> > "Just delete firebase.ps1 file"
> 
> Wow work for me! you can find location of file using `npm list -g`.

It worked for me, and it was very helpful to use the command `npm list -g` to locate the file. Thanks!
