### ISSUE TITLE
 auth:export write broken data

### ISSUE THREAD

**Issue by yehorh** [firebase/firebase-tools#1648]
### [REQUIRED] Environment info

**firebase-tools:7.3.1**

**Platform:Windows, Linux Ubuntu**

Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
5.0.0-27-generic

Windows Server 2016

### [REQUIRED] Test case
In project with multiple users export auth information.

### [REQUIRED] Steps to reproduce
```
> firebase.cmd --project project-name --token secret auth:export ./bak.csv
Exporting accounts to ./bak.csv
+  Exported 465 account(s) successfully.
> cat ./bak.csv
localId,mail@mail.com,false,8+AQew11O3AwZ4bBwlKhtzGiWnG35jB36LmSTG09dpblz6NRRw1jvTIXrRJ4ZGFv0u
ZrdnxTvx13Z987inNjkQ==,salt==,,,,,,,,,,,,,,,,,,,1508255889000,1525515073000,,
```

```
> firebase.cmd --project project-name --token secret auth:export ./bak.json
Exporting accounts to ./bak.json
+  Exported 465 account(s) successfully.
> cat ./bak.json
{"users": [
{
  "localId": "localId",
  "email": "mail@mail.com",
  "emailVerified": false,
  "passwordHash": "8+AQew11O3AwZ4bBwlKhtzGiWnG35jB36LmSTG09dpblz6NRRw1jvTIXrRJ4ZGFv0uZrdnxTvx13Z987inNjkQ==",
  "salt": "salt==",
  "lastSignedInAt": "1525515073000",
  "createdAt": "1508255889000",
  "providerUserInfo": []
}
```

### [REQUIRED] Expected behavior
Valid file with all users auth data

### [REQUIRED] Actual behavior
Broken `json` file or `csv` file with one row

**Comment by samtstern** [comment]
Thanks for reporting!  This will be fixed by #1642 and has already been reported, so going to close this as a duplicate.  Hopefully the fix will be released soon.
