### ISSUE TITLE
Firebase functions config set doesn't include $ present in my env data

### ISSUE THREAD

**Issue by IanMinash** [firebase/firebase-tools#1651]
Hi guys, whenever I add env data with a $ in it like the one below,

`firebase functions:config:set foo.bar="hellnoS$t%C"`

the $ and the character following it are not present the resulting value, which means that I instead get `hellnoS%C` when I access them from my cloud functions. Is $ not a valid symbol in the env data?

**Comment by bkendall** [comment]
It may be being interpreted by your shell as a variable. Try escaping the `$`:

```bash
firebase functions:config:set foo.bar="hellnoS\$t%C"
```

**Comment by IanMinash** [comment]
Thanks, that was it😅
