### ISSUE TITLE
Hosting rewrites disregards function region

### ISSUE THREAD

**Issue by Karasuni** [firebase/firebase-tools#1653]
### [REQUIRED] Environment info

**firebase-tools:** 7.3.1

### [REQUIRED] Test case

https://github.com/Karasuni/firebase-tools-20190911

### [REQUIRED] Steps to reproduce

1. Configure a function in any [region](https://firebase.google.com/docs/functions/locations) other than `us-central1`. E.g. `us-east1`.
This example will host a function at `us-east1-<project-id>.cloudfunctions.net/helloWorld`
```node
exports.helloWorld = functions
    .region('us-east1')
    .https.onRequest((request, response) => {
        response.send("Hello from Firebase!");
    });
```
2. Configure a rewrite to this function in `firebase.json`
```json
{
  "hosting": {
    "rewrites": [
      { "source": "/api/helloWorld", "function": "helloWorld" }
    ]
  }
}
```

### [REQUIRED] Expected behavior

The rewrite will direct `<project-id>.web.app/api/helloWorld` to the function at
`us-east1-<project-id>.cloudfunctions.net/helloWorld`.

### [REQUIRED] Actual behavior

The url is redirected to `us-central1-<project-id>.cloudfunctions.net/helloWorld/api/helloWorld`.

The rewrite will always direct to `us-central1` regardless of the actual hosted region. [Other regions](https://firebase.google.com/docs/functions/locations) like `us-east1`, `us-east4`, `europe-west1`, `europe-west2`, `asia-east2`, `asia-northeast1` are unavailable.

As a side node the rewrite also appears to paste the source URL after the actual function name. This is often unwanted behavior - do you want me to make a feature request to add a toggle for this behavior?

**Comment by mbleigh** [comment]
Firebase Hosting currently doesn't support rewriting to functions other than in `us-central1` (as documented [here](https://firebase.google.com/docs/hosting/functions)). This is a pretty common feature request and I'll consider this a +1 to that 😸 

As for the URL rewriting, we believe this is the correct behavior. When processing HTTP requests in a Cloud Function, `req.url` is set to the portion that appears after the function name. This allows for handling of Firebase Hosting requests using routers and other methods. In the function you can simply ignore `req.url` if you don't want to make use of it, so we don't anticipate making the behavior something that can be toggled.

Thanks for the feedback!

**Comment by mcarriere** [comment]
Being able to specify a region would be very useful. Is there a way to make an official feature request?

**Comment by okydk** [comment]
Where can we +1 this feature request? It's essential to protect EU functions with CORS, etc.
