### ISSUE TITLE
Accessing Firebase Projects from Firebase-CLI even after pass gets changed

### ISSUE THREAD

**Issue by darkie8** [firebase/firebase-tools#1657]
### [REQUIRED] Environment info

**firebase-tools:  7.3.1
**

**Platform: Windows**

### [REQUIRED] Test case

$ firebase init
$ firebase login
$ firebase list
$ firebase use --add
$ firebase deploy
#### in the terminal
$ firebase init
$ firebase login
#### in the termina
$ firebase list
#### AGAIN IN TERMINAL
$ firebase init
$ firebase list
### OR DEPLOYING
$ firebase use --add
$ firebase deploy
#### GIVES ME ACCESS TO PROJECTS INSTEAD OF THROWING CREDENTIAL MISMATCH ERROR.
![firebasebug](https://user-images.githubusercontent.com/39108053/64817411-6e76d300-d5c7-11e9-9f7d-55d52f038501.PNG)

**Comment by bkendall** [comment]
I am a bit out of my depth here, but if I recall correctly the access tokens are only good for an hour before they need to be refreshed (using the refresh token). I don't actually remember if changing your password invalidates any of the refresh tokens that have been generated - I'd have to go read some technical specifications, I think.

**Comment by mbleigh** [comment]
The Firebase CLI uses standard Google OAuth refresh tokens. Since refresh tokens don't rely on an account's password, I don't believe they are automatically invalidated when a password is changed -- Firebase unfortunately doesn't have any control to change this.

However, you can revoke all access granted to our app (or any other) by visiting [this Google account dashboard](https://myaccount.google.com/permissions) and searching for "Firebase CLI".

**Comment by darkie8** [comment]
> The Firebase CLI uses standard Google OAuth refresh tokens. Since refresh tokens don't rely on an account's password, I don't believe they are automatically invalidated when a password is changed -- Firebase unfortunately doesn't have any control to change this.
> 
> However, you can revoke all access granted to our app (or any other) by visiting [this Google account dashboard](https://myaccount.google.com/permissions) and searching for "Firebase CLI".

Revoking all access to any app from a certain account will make the account unusable for further use and will be a bad thing for me. So, is anybody working on the control to delete the refresh tokens whenever password gets changed ?

**Comment by y-71** [comment]
@mbleigh is it the same with custom tokens?
