### ISSUE TITLE
`firebase functions:config:get > .runtimeconfig.json` overwrites config file with empty JSON object

### ISSUE THREAD

**Issue by cgrennanTechtonic** [firebase/firebase-tools#1659]
### [REQUIRED] Environment info

**firebase-tools:** 7.3.0 (also tried with 7.3.2)

**Platform:** macOS Mojave 10.14.6 (18G87)

**Shell:** Z Shell (also tried with Bash)

### [REQUIRED] Test case

Clone the repo listed below, cd into functions, npm install, then follow Steps to Reproduce below.

https://github.com/CherryKatatonic/firebase-functions-config-bug

### [REQUIRED] Steps to reproduce

run `firebase functions:config:get > .runtimeconfig.json` from the `functions` directory and watch as the command erases all contents of `.runtimeconfig.json` and replaces them with an empty JSON object.

### [REQUIRED] Expected behavior

I expect this command to allow me to access custom environment variables from the `functions` folder when running `firebase serve` or `firebase serve --only functions` on my local machine.

I am trying to use this functionality to tell my functions to use the Firestore Emulator on `localhost` during development like so:
![Imgur](https://i.imgur.com/9PRA0j6.png)

### [REQUIRED] Actual behavior

Instead, when trying to access any environment variables from the `functions` folder such as `functions.config().VARIABLE`, VARIABLE is undefined because the command `firebase functions:config:get > .runtimeconfig.json` has overwritten the contents of the config file with an empty JSON object `{}`, but I've been told that this is the only way to define environment variables for Firebase Functions in a local dev environment.

I've spent hours troubleshooting this and scouring the web for answers. Any help would be greatly appreciated.

**Comment by joehan** [comment]
Hey @cgrennanTechtonic, sorry to hear that you've been having trouble. The firebase functions:config commands interact with (Firebase environment config)[https://firebase.google.com/docs/functions/config-env], not with local environment variables. The command you are using (```firebase functions:config:get > .runtimeconfig.json```) just pulls down the current config, and writes it to the runtimeconfig.json file, which the emulator references. To add a variable to the current config, use this command;```firebase functions:config:set yourservice.yourkey="blahblah" -P your-project```.

For example, to set the config value '''env.functionsPort''' to 8080, you would run ```firebase functions:config:set env.functionsPort=8080 -P you-project```. Then, you can pull that config to use locally with the emulator using ```firebase functions:config:get > .runtimeconfig.json```. Your variable will then be available at ```functions.config().env.functionsPort```.

Hope this helps!
