### ISSUE TITLE
How to locally debug the a project

### ISSUE THREAD

**Issue by vongohren** [firebase/firebase-tools#1667]
### [REQUIRED] Environment info

**firebase-tools:** 7.2.2

**Platform:** macOS

### [REQUIRED] Test case

Initiate a simple function setting some data to firestore, with typescript.
Then have some simple functions triggering on onCreate, onUpdate, logging the data coming in.

I have three criterias, related to this issue: https://github.com/GoogleCloudPlatform/functions-framework-nodejs/issues/101

1. I want to be able to develop on both functions in some kind of way.
2. I want to be able to run some kind of debugger towards the function being developed on.
3. I want to be able to watch the code for faster iterations.

What tool can be used?

### [REQUIRED] Steps to reproduce

Have these functions ready.
Try to run the `firebase emulator:start` function to get some sort of debuggin available.

Try to run `firebase emulatore:start --only firestore` and then run functions framework to have the flexibility needed. And then get that function to connect to the emulator.

### [REQUIRED] Expected behavior

I would love to have `firebase emulator:start` to have a flag for tapping into the inspect port made available by node.

### [REQUIRED] Actual behavior

There is no way to inspect!
It is not flexible enough to setup a proper dev environment

**Comment by samtstern** [comment]
@vongohren thanks for the detailed report.  As you've noticed, we can provide (1) and (3) but not (2) at the moment.

Adding debugging here is tracked in #1360 

Our position so far is that this would require a huge re-write of some code here.  But this morning I did some experiments and had a breakthrough so I think we can add debugging sooner than expected!  Can't promise anything though.

If you want your functions framework code to talk to the Firestore emulator, just set the environment variable `FIRESTORE_EMULATOR_HOST=locahost:$YOUR_FIRESTORE_PORT` and it will do the right thing.

**Comment by samtstern** [comment]
Closing this because we are tracking the debugging issue elsewhere.

**Comment by vongohren** [comment]
@samtstern coolio! Thanks for the feedback!
Yeah I did try the firestore emulator host variable, but was not able to make it trigger.
I run two different functions, one https and one onCreate firestore method.
Then I triggered the https, which triggers a put on firestore.
But I was not able to make the firestore onCreate method trigger.

But this should work? If I make sure I do it correctly 😄

**Comment by samtstern** [comment]
Yes that should work.  A common source of errors there is using a different
project ID or Firebase config in each emulator.

**Comment by vongohren** [comment]
Ok, thanks I will see what I figure out :)

**Comment by vongohren** [comment]
I appreciate good and quick feedback! Great stuff!

**Comment by vongohren** [comment]
@samtstern could you help out your collegue on this issue to understand what im trying to ask for? https://github.com/GoogleCloudPlatform/functions-framework-nodejs/issues/101#event-2687120898

It does not seem like grant see what im asking for. Its basically a statment from them that they are able to connect locally. You have said it works. Your collegue @grant says it does not work. Could some communication be done between you guys :D?

**Comment by samtstern** [comment]
@vongohren sorry about the confusion there.  I think this is my fault, but Grant is right: there's no way to run a firestore-triggered function (`onCreate`) inside the functions framework tool.

We're really trying to get debugging to work in this emulator, it's a hard problem to solve without giving up something else!

**Comment by vongohren** [comment]
Ok thanks for the answer
