### ISSUE TITLE
Firebase database emulators:exec doesn't respect database rules

### ISSUE THREAD

**Issue by audkar** [firebase/firebase-tools#1672]
### [REQUIRED] Environment info

**firebase-tools:**
7.3.2

**Platform:**
Linux

### [REQUIRED] Test case

Starting emulator with `firebase emulators:start --only database` and then running tests `yarn jest` works correctly, but executing `firebase emulators:exec --only database jest` fails with such test:
```typescript
it("write disabled", async () => {
  const app = firebase.initializeTestApp({
    databaseName: "my-database",
  })

  await firebase.loadDatabaseRules({
    databaseName: "my-database",
    rules: '{"rules": {".read": false, ".write": false} }',
  })

  await firebase.assertFails(
    app
      .database()
      .ref()
      .push({ a: "b" }),
  )
})
```

### [REQUIRED] Steps to reproduce

Execute any test with "firebase emulators:exec --only database jest"

### [REQUIRED] Expected behavior

Test passes

### [REQUIRED] Actual behavior

Tests fail (value is written to database)

Seems that rules are completely ignored when using `emulators:exec`.

**Comment by samtstern** [comment]
@audkar really sorry about the slow response here, I will take a look at this.

**Comment by samtstern** [comment]
This is a bug in the JS SDK and is being tracked here:
https://github.com/firebase/firebase-js-sdk/issues/2191

Closing this issue as there's no change needed in the CLI or emulators.
