### ISSUE TITLE
Transaction Failed and Network Timeout

### ISSUE THREAD

**Issue by ArcherEmiya05** [firebase/firebase-tools#1680]
### Related issues
No, I cant find exact similar case on SO.

### [REQUIRED] Version info

**node: 8**

**firebase-functions: 3.1.0 **

**firebase-tools: 7.3.2**

**firebase-admin: 8.0.0**

### [REQUIRED] Test case
Deploying function from CLI and it was successful but I am seeing this in firebase console log.
![image](https://user-images.githubusercontent.com/38008900/65585942-e2e14700-dfb5-11e9-99de-2d380dc52e32.png)

`Transaction failed { FetchError: Unexpected error determining execution environment: network timeout at: http://169.254.169.254/computeMetadata/v1/instance
    at Timeout.<anonymous> (/srv/node_modules/node-fetch/lib/index.js:1448:13)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
  message: 'Unexpected error determining execution environment: network timeout at: http://169.254.169.254/computeMetadata/v1/instance',
  type: 'request-timeout',
  config: 
   { url: 'http://169.254.169.254/computeMetadata/v1/instance',
     headers: { 'Metadata-Flavor': 'Google' },
     retryConfig: 
      { noResponseRetries: 0,
        currentRetryAttempt: 0,
        retry: 3,
        retryDelay: 100,
        httpMethodsToRetry: [Array],
        statusCodesToRetry: [Array] },
     responseType: 'text',
     timeout: 3000,
     params: {},
     paramsSerializer: [Function: paramsSerializer],
     validateStatus: [Function: validateStatus],
     method: 'GET' } }`

Another is when I tried to trigger one of my function it is getting executed but not work properly.
`Error getting documents. { FetchError: Unexpected error determining execution environment: network timeout at: http://169.254.169.254/computeMetadata/v1/instance
    at Timeout.<anonymous> (/srv/node_modules/node-fetch/lib/index.js:1448:13)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
  message: 'Unexpected error determining execution environment: network timeout at: http://169.254.169.254/computeMetadata/v1/instance',
  type: 'request-timeout',
  config: 
   { url: 'http://169.254.169.254/computeMetadata/v1/instance',
     headers: { 'Metadata-Flavor': 'Google' },
     retryConfig: 
      { noResponseRetries: 0,
        currentRetryAttempt: 0,
        retry: 3,
        retryDelay: 100,
        httpMethodsToRetry: [Array],
        statusCodesToRetry: [Array] },
     responseType: 'text',
     timeout: 3000,
     params: {},
     paramsSerializer: [Function: paramsSerializer],
     validateStatus: [Function: validateStatus],
     method: 'GET' } }`

And upon triggering the function I do get this error at some point on the log
`(node:2) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit`

### [REQUIRED] Steps to reproduce
Deploying function to cloud and triggering 

### [REQUIRED] Expected behavior
Before I have no issue at all and everything works fine. I also not seeing any kind of this logs before.

### [REQUIRED] Actual behavior
![image](https://user-images.githubusercontent.com/38008900/65568546-db597800-df8c-11e9-9650-f9feff7b235b.png)
![image](https://user-images.githubusercontent.com/38008900/65568565-f1ffcf00-df8c-11e9-9348-e85064592ed1.png)
![image](https://user-images.githubusercontent.com/38008900/65568600-0cd24380-df8d-11e9-8149-32ccc13b7d36.png)

I tried to delete all function in Google Cloud Console because I thought there is some error that stuck with my old functions and deploy it again but still no luck same result happens. 
![image](https://user-images.githubusercontent.com/38008900/65568616-1cea2300-df8d-11e9-803b-5e574e2f8b90.png)

### Were you able to successfully deploy your functions?
Yes yes

Is this a problem with my network and not in Firebase side?

**Comment by samtstern** [comment]
@ArcherEmiya05 thanks for reporting this and sorry that we never responded.  Are you still seeing this issue?  It's possible there was an issue with the Compute Metadata service that is now resolved.

This doesn't look like it was your fault but it also doesn't look like a Firebase CLI issue.

**Comment by ArcherEmiya05** [comment]
I think it has been fixed as I am no longer seeing it again anymore, I thought because I upgrade my plan to Blaze that solves the issue though. Anyway thanks and may I know what exactly happened or reason? What is Compute Metadata anyway?

**Comment by samtstern** [comment]
@ArcherEmiya05 it's a service that helps VMs get credentials they can use to access other Google APIs.  It's why you don't have to manually put a service account in your Cloud Functions, it just "knows".

Thanks for following up!
