### ISSUE TITLE
Hanging transactions in the Realtime DB.

### ISSUE THREAD

**Issue by larssn** [firebase/firebase-tools#1681]
I'm seeing transactions hanging in the realtime DB when using the emulator.
Test case below.

### [REQUIRED] Environment info

**firebase-tools:** 7.4.0

macOS

### [REQUIRED] Test case

```
import * as admin from 'firebase-admin';

export async function lockDocument(eventId: string) {
  const db = admin.database();

  const trx = await db.ref(`/events/${eventId}`).transaction(currentEvent => {
    console.log('Doing transaction');
    if (currentEvent === null) {
      return { timestamp: Date.now() };
    } else {
      return;
    }
  });

  console.log('Done transaction');

  return trx.committed;
}
```

When running via the emulator, "Done transaction" is never printed, leaving me to believe it hangs in there somewhere.

When deploying to the server, however, it works fine.

### [REQUIRED] Steps to reproduce

Just add it to a trigger:
```
functions.region('europe-west1').firestore
  .document('businesses/{businessId}/products/{productId}')
  .onCreate(async (snapshot, context) => {
    const lock = await lockDocument(context.eventId);
    if (!lock) {
      console.log('No lock could be gotten. Aborting');
      return;
    }
  }
```

### [REQUIRED] Expected behavior
I expect it to not hang in transactions.

### [REQUIRED] Actual behavior
It hangs in transactions.

**Comment by samtstern** [comment]
@larssn thanks for the simple test case!  Assuming it reproduces for us, sounds like a clear-cut bug.

@ryanpbrewster @scottcrossen PTAL

**Comment by ryanpbrewster** [comment]
I cannot reproduce this. When I try this (I used an HTTPS function) I get logs like:
```
i  functions: Beginning execution of "helloWorld"
>  Doing transaction
>  Doing transaction
>  Done transaction
>  No lock could be gotten. Aborting
```

The first run succeeded and acquired the lock, subsequent runs all fail to acquire a lock. I am not seeing the transaction hang.

**Comment by larssn** [comment]
I think I might have had the emulator misconfigured. Sam has been helping me today getting it working today. If you can't reproduce it, I would just close it tbh. I can reopen it if I run into it again.

**Comment by celesteking** [comment]
Not only I get this on local emulator, I get this hang in google prod as well.
