### ISSUE TITLE
Manage and upload multiple Storage rulesets

### ISSUE THREAD

**Issue by lukepighetti** [firebase/firebase-tools#1685]
I created a second storage bucket today and noticed that the Firebase Console shows different rules for each bucket (this was surprising, since we can match by bucket name in our rules). I then tried to `firebase-tools` to initialize storage a second time to add the new bucket, but it was not clear how to proceed. 

How do we manage rules for two different Storage buckets with `firebase-tools`? If we cannot, then this is a feature request.

**Comment by samtstern** [comment]
@mrschmidt @bleigh @codingdoug do any of you know the answer to this one?

**Comment by rachelmyers** [comment]
@lukepighetti, great question! You can control the rules for multiple Storage buckets via the CLI by setting up [deploy targets](https://firebase.google.com/docs/cli/targets#set-up-deploy-target-storage-database). 

To set multiple storage buckets to use the same local rules file, create a deploy target associated with multiple buckets.
 
```$ firebase target:apply storage main myproject.appspot.com bucket1 bucket2```

To set multiple storage buckets to use different local rules files, create separate deploy targets for each bucket. Then you can deploy them on the CLI individually. Check out the linked doc for more detail. 

I'm going to close this, but please reopen and comment if that doesn't work.
