### ISSUE TITLE
Google Cloud Functions emulator doesn't interact with @firebase/testing locally

### ISSUE THREAD

**Issue by danjenson** [firebase/firebase-tools#1693]
Firebase Version 7.4.0
Fedora 29

I am testing my firebase firestore security rules and cloud functions locally. In my test case, I am creating a user, and then again updating it. However, before updating, the cloud functions should have run and created a mapping used in the update security rule, but it doesn't seem to do this locally.

```
rules_version = '2';

service cloud.firestore {

  match /databases/{database}/documents {

    function userName() {
     return get(/databases/$(database)/documents/uid_to_user_name/$(request.auth.uid))
        .data
        .userName;
    }

    match /user/{userName} {
      allow read: if signedIn();
      allow create: if signedIn()
        && isValidUser(request.resource.data)
        && request.resource.data.uid == request.auth.uid
        && request.resource.data.name == userName;
      allow update: if signedIn()
        && isValidUser(request.resource.data)
        && request.resource.data.name == resource.data.name
        && request.resource.data.name == userName
        && request.resource.data.name == userName();
      allow delete: if false;
    }
  }
}
```

And I have a cloud function that triggers onWrite for /user/{userName} which creates a uid->userName lookup in a table called uid_to_user_name. The problem is when I use `@firebase/testing` and run `firebase emulators:start --only firestore,functions`, it appears as though the two services don't fully interact. For instance, when I create a user, it passes my security rules, and I see also that the onWrite trigger has been activated. However, when I sleep for 5 seconds and attempt to update that user, the security rule fails because the mapping in `uid_to_username` is `undefined`. Curiously, well within that time, I also store and retrieve the value from `uid_to_username` from within the cloud function and it is present. So, it seems as though cloud firestore write operations trigger cloud functions, but writes done in the cloud functions don't update the firestore emulator.

**Comment by samtstern** [comment]
> Curiously, well within that time, I also store and retrieve the value from uid_to_username from within the cloud function and it is present. So, it seems as though cloud firestore write operations trigger cloud functions, but writes done in the cloud functions don't update the firestore emulator.


This normally means some part of your code is pointing to a different project or project ID.  Can you show how where/how you call `admin.initializeApp()` in your functions?  And could you also show how you're performing the initial write to Cloud Firestore that triggers the function?

**Comment by danjenson** [comment]
Thank you, this has been resolved, the issue was twofold: first I was
defining my functions outside the first match but inside the service;
moving those functions inside the document database match worked. The
second thing was I was using a normal app not the firebase testing app
inside my cloud functions (I just assumed they would be intercepted when
the emulator was running).

**Comment by samtstern** [comment]
@danjenson glad it's resolved!
