### ISSUE TITLE
Firestore delete hitting Cloud Resource Manager API every call, exceeding quota limit

### ISSUE THREAD

**Issue by alexlouden** [firebase/firebase-tools#1695]
### [REQUIRED] Environment info

**firebase-tools:** v6.2.2
**Platform:** Cloud functions

### [REQUIRED] Test case

We're using firebase-tools's recursive firestore delete (from [this pattern](https://firebase.google.com/docs/firestore/solutions/delete-collections)) in a cloud function that runs quite often, and we've started to exceed the Cloud Resource Manager API's quota (currently our limit is 1000 calls in 100 seconds, or ~10 rps).

![Screen Shot 2019-10-07 at 3 09 41 pm](https://user-images.githubusercontent.com/1332954/66291559-c4177480-e914-11e9-89b8-020d3088c64e.png)

I think this must be due to the [`requirePermissions`](https://github.com/firebase/firebase-tools/blob/master/src/commands/firestore-delete.js#L73) call running before every recursive delete (which hits the Cloud Resource Manager `testIamPermissions` API).

I'm wondering if it'd be possible to optionally bypass this call? I could request a quota increase, but it feels a bit unnecessary to check that our token has permission before every query, at >10 rps.

### [REQUIRED] Steps to reproduce

Call firestore.delete > 1000 times in 100 seconds

### [REQUIRED] Expected behavior

Able to recursively delete collections without hitting a quota error

### [REQUIRED] Actual behavior

Cloud Resource Manager API quota error

**Comment by samtstern** [comment]
@alexlouden thanks for pointing this out!  I had not considered that someone would use this API at this volume.

Can you tell me a little more about your use case?

**Comment by alexlouden** [comment]
Hi, sorry for the delay - missed this notification! We're using this because there's no command to delete a document and all it's subcollections. This is used in a relatively popular application that needs to be able to recursively delete hundreds of documents per second. Happy to elaborate more via email if you like :)

I ended up forking the repo and swapping the `requirePermissions` call with a `requireAuth`, along with some changes to error handling/logging/deletion parameters: https://github.com/firebase/firebase-tools/compare/master...Bonobolabs:master

**Comment by samtstern** [comment]
@alexlouden thanks for sharing!  Looks like @mbleigh is going to at least mitigate this with #1791 

As an aside, I am curious why you also changed some of the constants:
```
var readBatchSize = 7500; // --> 1000
var deleteBatchSize = 250;  // --> 50
var maxPendingDeletes = 15; // --> 10
```

Did this improve your performance

**Comment by alexlouden** [comment]
> @alexlouden thanks for sharing! Looks like @mbleigh is going to at least mitigate this with #1791
Great, thank you! 

> As an aside, I am curious why you also changed some of the constants:
> Did this improve your performance?

Some of the documents in the query have a field that can be quite large (e.g. up to 1MB each), so I thought that reducing the read batch size would help prevent against the function running out of memory.

We were receiving a lot of 500 "An internal error occurred." errors from the API when trying to delete in batches, so dropping the delete batch size and max pending deletes parameters was my attempt to try and reduce the frequency of errors. I thought perhaps it was an issue deleting that quantity of data in parallel? 

I contacted support (case #20896001) and it sounds like the issue was we were exceeding the throughput limit of 10MB/s (which I didn't realise applied to deleting documents). I enabled retries for the cloud function, and set a concurrency limit of 15 which enabled us to get some decent deletion rates:

![Screen Shot 2019-10-17 at 11 12 13 am](https://user-images.githubusercontent.com/1332954/69021297-50c45080-09f2-11ea-8e33-93b9f760e27a.png)

Without concurrency limits and before I adjusted the parameters the cloud function performing the deletes was crashing about 70% of the time. This metric is cloud function executions grouped by status:
![image](https://user-images.githubusercontent.com/1332954/69021722-c54bbf00-09f3-11ea-9b72-2058c661ee53.png)

With retries, lower parameters and the function concurrency limit in place the API was still returning 500s about 5-10% of the time, which was a lot better:
![image](https://user-images.githubusercontent.com/1332954/69021573-3f2f7880-09f3-11ea-8a4d-980f4ed37227.png)

**Comment by samtstern** [comment]
@alexlouden wow thank you for all the data!  That's really interesting.  You're right it's very hard to get deletes working perfectly since the backend limit is defined in terms of how much data you're deleting (incl. indexes) but when you're just deleting by ID in batches its pretty much impossible to know how much that will be.
