### ISSUE TITLE
`firebase apps:sdkconfig WEB` should have valid JS output on stdout

### ISSUE THREAD

**Issue by blbradley** [firebase/firebase-tools#1707]
### [REQUIRED] Environment info

**firebase-tools: 7.5.0**

**Ubuntu 18.04 (WSL)**

### [REQUIRED] Steps to reproduce

```firebase apps:sdkconfig WEB someid```

### [REQUIRED] Expected behavior

Valid JS output from stdout

### [REQUIRED] Actual behavior

Extra line of `=== Your app configuration is ready ===` in stdout.

Redirect to file:
```
=== Your app configuration is ready ===

// Copy and paste this into your JavaScript code to initialize the Firebase SDK.
// You will also need to load the Firebase SDK.
// See https://firebase.google.com/docs/web/setup for more details.

firebase.initializeApp({
  "projectId": "foo",
  "appId": "foo",
  "databaseURL": "foo",
  "storageBucket": "foo",
  "locationId": "us-central",
  "apiKey": "foo",
  "authDomain": "foo",
  "messagingSenderId": "foo",
  "measurementId": "foo"
});
```

**Comment by samtstern** [comment]
@blbradley if you use the `-o` option to output to a file you can send just the JS part to a file.

However I agree with you I think there's no reason to keep that log line around.

**Comment by blbradley** [comment]
Speedy response and fix, thanks! I was thinking that this output could go to stderr; but this works.

We are experimenting with using the Hosted URL; so, we may not need such strict output from a command.
