### ISSUE TITLE
 Error: Failed to load gRPC binary module because it was not installed for the current system

### ISSUE THREAD

**Issue by TOMZACH** [firebase/firebase-tools#1719]
I follow the instructions here https://firebase.google.com/docs/cli#npm
I run `npm install -g firebase-tools` , login and then run `firebase serve` and receive the following error 

> Error: Failed to load gRPC binary module because it was not installed for the current system
> Expected directory: node-v57-darwin-x64-unknown
> Found: [node-v64-darwin-x64-unknown]

Ive tried running `npm rebuild` as suggested on other threads and on stack exchange but the error persists. Any ideas of what can be done to fix this. I've tried uninstalling and reinstalling the `node_modules` but still the problem persists. Any ideas of what can be done. 

I'm running 
npm version 6.9.0 
Firebase CLI version 7.5.0
MacOS Catalina 10.15

**Comment by bkendall** [comment]
ooo - I have weird hunches about this that aren't going to be fun related to Catalina...

Can you tell me where the following executable files live on your machine? `which` will probably be the best tools for this...
- `node`
- `npm`
- `firebase`

A quick-ish version of this question is: how did you install NodeJS on your machine?

**Comment by TOMZACH** [comment]
I downloaded node.js  from the node.js website using https://nodejs.org/en/
Im not sure if this helps but I also ran `which npm` and the below command to find where `npm` sits

> ls -al /usr/local/bin/npm
> lrwxr-xr-x  1 root  wheel  38 Oct 11 14:29 /usr/local/bin/npm -> ../lib/node_modules/npm/bin/npm-cli.js
> 
>

**Comment by bkendall** [comment]
So, I don't know all of the details I'm talking about here, but my understanding is that Catalina separated user and system space on the file system and things that attempt to cross those boundaries have some odd behaviors.

I don't have a setup to test this now myself, but I may be able to look into it later. What I would recommend for you:

1. Try: uninstall Node and reinstall it using a fresh download from nodejs.org - that may allow macOS to put the appropriate permissions in place for you to be able to run what you need. Try reinstalling `firebase-tools` and going about your workflow. (There's a second option here that you may need to give Node JS full access to your file system or something, but I'm not 100% sure how to advice this).
1. Workaround: use [nvm](https://github.com/nvm-sh/nvm). It installs node in your home directory which will have the correct permissions in your system. This should unblock you and allow you to install `firebase-tools` and go about your workflow.

Let me know if that works for you!

**Comment by TOMZACH** [comment]
Thank you for your continued help.

Its funny I uninstalled node.js manually and then installed using nvm everything seemed fine. I ran firebase serve and got a differnent error

`firebase serve`

> === Serving from '/Users/a123456/Desktop/Tile Cloud Functions copy/cloud-functions'...
> 
> ⚠  Your requested "node" version "8" doesn't match your global version "12"
> ✔  functions: Emulator started at http://localhost:5001
> i  functions: Watching "/Users/a123456/Desktop/Tile Cloud Functions copy/cloud-functions/functions" for Cloud Functions...
> i  hosting: Serving hosting files from: y
> ✔  hosting: Local server: http://localhost:5000
> ⚠  Error: Cannot find module '/Users/a123456/Desktop/Tile Cloud Functions copy/cloud-functions/functions/node_modules/@firebase/firestore/node_modules/grpc/src/node/extension_binary/node-v72-darwin-x64-unknown/grpc_node.node'
> Require stack:
> - /Users/a123456/Desktop/Tile Cloud Functions copy/cloud-functions/functions/node_modules/@firebase/firestore/node_modules/grpc/src/grpc_extension.js
> - /Users/a123456/Desktop/Tile Cloud Functions copy/cloud-functions/functions/node_modules/@firebase/firestore/node_modules/grpc/src/client_interceptors.js
> - /Users/a123456/Desktop/Tile Cloud Functions copy/cloud-functions/functions/node_modules/@firebase/firestore/node_modules/grpc/src/client.js
> - /Users/a123456/Desktop/Tile Cloud Functions copy/cloud-functions/functions/node_modules/@firebase/firestore/node_modules/grpc/index.js
> - /Users/a123456/Desktop/Tile Cloud Functions copy/cloud-functions/functions/node_modules/@firebase/firestore/dist/index.node.cjs.js
> - /Users/a123456/Desktop/Tile Cloud Functions copy/cloud-functions/functions/node_modules/firebase/dist/index.node.cjs.js
> - /Users/a123456/Desktop/Tile Cloud Functions copy/cloud-functions/functions/admin.js
> - /Users/a123456/Desktop/Tile Cloud Functions copy/cloud-functions/functions/index.js
> - /Users/a123456/.nvm/versions/node/v12.12.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:687:27)
>     at Module.require (internal/modules/cjs/loader.js:849:19)
>     at require (internal/modules/cjs/helpers.js:74:18)
>     at Object.<anonymous> (/Users/a123456/Desktop/Tile Cloud Functions copy/cloud-functions/functions/node_modules/@firebase/firestore/node_modules/grpc/src/grpc_extension.js:32:13)
>     at Module._compile (internal/modules/cjs/loader.js:956:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
>     at Module.load (internal/modules/cjs/loader.js:812:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:724:14)
>     at Module.require (internal/modules/cjs/loader.js:849:19)
> ⚠  We were unable to load your functions code. (see above)

so I googled the error and followed this advise https://github.com/firebase/firebase-tools/issues/442#issuecomment-328516130

which got me to this error 

`firebase serve`

> 
> === Serving from '/Users/a123456/Desktop/Tile Cloud Functions copy/cloud-functions'...
> 
> ⚠  Your requested "node" version "8" doesn't match your global version "12"
> ✔  functions: Emulator started at http://localhost:5001
> i  functions: Watching "/Users/a123456/Desktop/Tile Cloud Functions copy/cloud-functions/functions" for Cloud Functions...
> i  hosting: Serving hosting files from: y
> ✔  hosting: Local server: http://localhost:5000
> ⚠  Error: The gRPC binary module was not installed. This may be fixed by running "npm rebuild"
> Original error: Cannot find module '/Users/a123456/Desktop/Tile Cloud Functions copy/cloud-functions/functions/node_modules/grpc/src/node/extension_binary/node-v72-darwin-x64-unknown/grpc_node.node'
> Require stack:
> - /Users/a123456/Desktop/Tile Cloud Functions copy/cloud-functions/functions/node_modules/grpc/src/grpc_extension.js
> - /Users/a123456/Desktop/Tile Cloud Functions copy/cloud-functions/functions/node_modules/grpc/src/client_interceptors.js
> - /Users/a123456/Desktop/Tile Cloud Functions copy/cloud-functions/functions/node_modules/grpc/src/client.js
> - /Users/a123456/Desktop/Tile Cloud Functions copy/cloud-functions/functions/node_modules/grpc/index.js
> - /Users/a123456/Desktop/Tile Cloud Functions copy/cloud-functions/functions/admin.js
> - /Users/a123456/Desktop/Tile Cloud Functions copy/cloud-functions/functions/index.js
> - /Users/a123456/.nvm/versions/node/v12.12.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js
>     at Object.<anonymous> (/Users/a123456/Desktop/Tile Cloud Functions copy/cloud-functions/functions/node_modules/grpc/src/grpc_extension.js:43:17)
>     at Module._compile (internal/modules/cjs/loader.js:956:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
>     at Module.load (internal/modules/cjs/loader.js:812:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:724:14)
>     at Module.require (internal/modules/cjs/loader.js:849:19)
>     at require (internal/modules/cjs/helpers.js:74:18)
>     at Object.<anonymous> (/Users/a123456/Desktop/Tile Cloud Functions copy/cloud-functions/functions/node_modules/grpc/src/client_interceptors.js:144:12)
>     at Module._compile (internal/modules/cjs/loader.js:956:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
> ⚠  We were unable to load your functions code. (see above)

Any ideas of where to go from here?

**Comment by bkendall** [comment]
Try running `firebase serve` using Node 8 rather than node 12. The higher versions of node sometimes don't play nicely, so odd issues can appear like this.
