### ISSUE TITLE
Functions emulator not respecting the `host` argument

### ISSUE THREAD

**Issue by samtstern** [firebase/firebase-tools#1722]
### [REQUIRED] Environment info

I am filing this issue to escalate from a message on the `firebase-talk` mailing list:
https://groups.google.com/d/msgid/firebase-talk/b7f58e6c-12e1-4db9-9894-4db21c5fed7d%40googlegroups.com?utm_medium=email&utm_source=footer

### [REQUIRED] Test case

Need to make sure that we can support `host` with the functions emulator.

### [REQUIRED] Steps to reproduce

firebase.json
```
{
  "emulators": {
    "functions": {
      "host": "10.0.10.2",
      "port":5000
    },
  }
}
```

```
$ firebase emulators:start --only functions
```

### [REQUIRED] Expected behavior

Bind to correct host.

### [REQUIRED] Actual behavior

```
i  Starting emulators: ["functions"]
✔  functions: Using node@8 from host.
Error: TIMEOUT: Port 5000 was not active within 30000ms
```

**Comment by jorikvanveen** [comment]
I am still experiencing this exact same issue in 7.12.1.

**Comment by samtstern** [comment]
@jorikvanveen if you're seeing this on the latest version please file a new issue, it's likely something new since this issue was confirmed fixed.
