### ISSUE TITLE
New cloud function added is not loaded using firebase functions:shell

### ISSUE THREAD

**Issue by anuragd7** [firebase/firebase-tools#1729]
### [REQUIRED] Environment info

I am using` firebase-tools@7.6.0`
On  Mac OS High Sierra

### [REQUIRED] Steps to reproduce
I am importing my cloud functions into `index.ts`. as shown below

```
import { updateUser, getUserRights } from './claims';
export { updateUser, getUserRights };
```

I now create a new cloud function and import it into index.ts like so

```
import { updateUser, getUserRights } from './claims';
import { sendTestSubmitted } from './status/submit';
export { updateUser, getUserRights, sendTestSubmitted };
```
I find the when I run `firebase functions:shell` I get the following output

```
  Your requested "node" version "8" doesn't match your global version "10"
✔  functions: Emulator started at http://localhost:5000
⚠  functions: Your GOOGLE_APPLICATION_CREDENTIALS environment variable points to /Users/xxx/credentials.json. Non-emulated services will access production using these credentials. Be careful!
i  functions: Loaded functions: updateUser, getUserRights  <------- the new function is not loaded

```
The new function does not show up in the list of loaded functions.

### [REQUIRED] Expected behavior

The new function should show

### [REQUIRED] Actual behavior

As requested am including the code for the new function sendTestSubmitted which btw works perfectly on deployment. AM just not able to add it while trying to test locally using firebase functions:shell

Code for new function
```
import * as functions from "firebase-functions";
const nodemailer = require("nodemailer"); 

const gmailEmail = functions.config().gmail.email;
const gmailPassword = functions.config().gmail.password;

const mailTransport = nodemailer.createTransport({
  service: "gmail",
  auth: {
    user: gmailEmail,
    pass: gmailPassword
  }
});

// Sends an email confirmation .
export const sendTestSubmitted =
  functions.firestore.document("tests/{testId}").onWrite(change => {
    console.log("Gmail email is " + gmailEmail) ;
    console.log("Gmail password is " + gmailPassword) ;
    const data = change.after.data();
    if(data && data.status === "submitted"){
    const sendingTo = data.createdBy.email;
    console.log("email is " + sendingTo);
    const userName = data.createdBy.userName;
    const testName = data.testName;
    const mailSubject = "Thanks For Submitting " + testName;
    const emailBody =
      "Hi," +
      userName +
      "! <br><br>Great to see that you have submitted " + testName ;


    const mailOptions = {
      from: gmailEmail,
      to: sendingTo,
      subject: mailSubject,
      html: emailBody
    };

    return mailTransport
      .sendMail(mailOptions)
      .then(() =>
        console.log("email sent to " + sendingTo + "from" + gmailEmail)
      )
      .catch((error:any) =>
        console.error("There was an error while sending the email:", error)
      );
    }
    else {
      return "Not submitted"
    }
  });

```

**Comment by samtstern** [comment]
@anuragd7 have you definitely built TypeScript into JavaScript since you added the new function?  I was able to get this setup to work.

If you have done that, could you check what happens if you replace these lines:

```
// BEFORE
const gmailEmail = functions.config().gmail.email;
const gmailPassword = functions.config().gmail.password;

// AFTER
const gmailEmail = "";
const gmailPassword = "";
```

I just want to know if this has to do with `functions.config()`

**Comment by anuragd7** [comment]
@samtstern . Many thanks - that was indeed the problem. I was not building typescript to javascript!
For any others who face the problem - remember to run  `npm run build` .
Also If you're using custom functions configuration variables, run the following command in the functions directory of your project before running `firebase serve` or `firebase functions:shell` `firebase functions:config:get > .runtimeconfig.json` as mentioned [here](https://stackoverflow.com/a/42978220/6498594)
