### ISSUE TITLE
HTTP Error: 400, Location must equal europe-west2 because the App Engine app that is associated with this project is located in europe-west2

### ISSUE THREAD

**Issue by sunil-sandhu** [firebase/firebase-tools#1730]
### [REQUIRED] Environment info

**firebase-tools:** 7.6.0
**deps in package.json**     
    "firebase-admin": "^8.6.1",
    "firebase-functions": "^3.3.0",

**Platform:** macOS

### [REQUIRED] Test case

```
const functions = require("firebase-functions");
const admin = require("firebase-admin");
admin.initializeApp(functions.config().firebase);

exports.genericFunction = functions
  .region("europe-west2")
  .pubsub.schedule("every 6 hours")
  .onRun(async (context) => {
    return context
});
```

### [REQUIRED] Steps to reproduce

firebase deploy --only functions

### [REQUIRED] Expected behavior

Function should deploy

### [REQUIRED] Actual behavior

Error: HTTP Error: 400, Location must equal europe-west2 because the App Engine app that is associated with this project is located in europe-west2

**Comment by sunil-sandhu** [comment]
Nevermind, it turns out I needed to set the project location in Firebase as well as in GCP.

**Comment by kentcb** [comment]
Some further findings for others hitting this issue, which was me earlier today:

1. Enabling Firestore in the Firebase console sets the default location in both Firebase console _and_ GCP console
2. Enabling Firestore in the GCP console sets the default location in only GCP console
3. To set the default location in the Firebase console, go to the project settings and set this (I swear this setting wasn't there the first several times I checked, so you might have to wait a while...?):

    ![image](https://user-images.githubusercontent.com/1901832/94226288-9454e880-ff3a-11ea-979f-3ca41c254db7.png)

4. I have not a clue why these locations are different across consoles.
