### ISSUE TITLE
Add support for failure policies

### ISSUE THREAD

**Issue by mad-it** [firebase/firebase-tools#1734]
Currently its not supported to set retry policies in a firebase function. To enable retries, you have to go to the Google cloud console and enable retries. 

This manual step makes the deployment non-idempotent. 

There is an open issue + pull request for `firebase-functions` repository which add support for this feature on that side. 
Issue: https://github.com/firebase/firebase-functions/issues/425
Pull request: https://github.com/firebase/firebase-functions/pull/482

I am creating this issue in here as a way to track progress on the missing feature for `firebase-tools`.

**Comment by samtstern** [comment]
@mad-it thanks for filing this.

@merlinnot (based on https://github.com/firebase/firebase-functions/pull/482#issuecomment-530874660) or @joehan if you can lay out what needs doing in this repo I could contribute the missing CLI pieces.

**Comment by merlinnot** [comment]
Sure thing.

There's an API design for this feature approved by the API Council: https://github.com/firebase/firebase-functions/issues/425#issue-422405128 with small changes: https://github.com/firebase/firebase-functions/issues/425#issuecomment-485892911.

In short, I implemented everything that is needed to deliver this feature in `firebase-functions`, it was approved by @laurenzlong, but put on hold pending feature parity in `firebase-tools`. The implementation exposes `__trigger.failurePolicy`, which is equal to `{ retry: {} }` or is unset. This matches the API specification of Cloud Functions: https://cloud.google.com/functions/docs/reference/rpc/google.cloud.functions.v1#failurepolicy.

In the API design you can find an information that optionally a boolean value must be accepted by this property, but this is handled by `firebase-functions` already and transformed to a canonical representation `{ retry: {} }`, so you don't need to worry about it.

The most complex part seems to be user prompts when changing these policies. You'd need to compare existing deployment with a new one. All of the possibilities, both in interactive and non-interactive shells, with and without `--force` flag are described in the original design linked above.

Let me know if anything is unclear and thank you soooo so much for picking it up!

**Comment by laurenzlong** [comment]
Thanks for the helpful summary @merlinnot ! @samtstern happy to review the PR for CLI.

**Comment by samtstern** [comment]
I am working on this now, running into some strange issues with the Cloud Functions REST API but hoping to get them resolved soon

**Comment by samtstern** [comment]
Syntax support for this feature is included in `firebase-functions` version `3.10.0` and the next version of `firebase-tools` will contain the necessary deployment pieces.
