### ISSUE TITLE
Firestore's delete script's last line printed to stdout does not end in a newline character.

### ISSUE THREAD

**Issue by DCtheTall** [firebase/firebase-tools#1737]
### [REQUIRED] Environment info

**firebase-tools:** 7.6.1

**Platform:** Ubuntu

### [REQUIRED] Test case

Run `firebase firestore:delete` and observe that the last line printed to stdout does not end in a newline character, resulting in an awkward UX.

### [REQUIRED] Steps to reproduce

See "Test case".

### [REQUIRED] Expected behavior

This script should print a newline character after printing `Deleted N docs (X docs/s)`.

### [REQUIRED] Actual behavior

The last line does not end in a newline, which results in an awkward UX that looks like:

```
firebase firestore:delete ...
Deleted N docs (X docs/s)dcthetall@mymachine:~/some/dir$
```

**Comment by DCtheTall** [comment]
This is a pretty trivial fix and I'd be willing to supply a quick PR to address this if the owners of this repo are willing to accept it.

**Comment by samtstern** [comment]
@DCtheTall absolutely would accept a PR, thanks for the offer!  Just @-mention me when you send it.

**Comment by DCtheTall** [comment]
Is there development documentation for testing this script locally?

**Comment by samtstern** [comment]
@DCtheTall sorry for my late response.  I normally just create a disposable Firebase project for testing.  In fact I have a project called "DumpsterFire" that I use for all my testing :-)

**Comment by samtstern** [comment]
@DCtheTall thank you for your contribution!
