### ISSUE TITLE
FR: PubSub emulator support

### ISSUE THREAD

**Issue by rockyxcoded** [firebase/firebase-tools#1748]
I tried running cloud function locally using
Firebase emulators:start

the response i got

i  Starting emulators: ["functions","database","hosting"]
⚠  Your requested "node" version "8" doesn't match your global version "10"
✔  functions: Emulator started at http://localhost:5001
i  database: Emulator logging to database-debug.log
✔  database: Emulator started at http://localhost:9000
i  database: For testing set FIREBASE_DATABASE_EMULATOR_HOST=localhost:9000
i  hosting: Serving hosting files from: public
✔  hosting: Local server: http://localhost:5000
✔  hosting: Emulator started at http://localhost:5000
i  functions: Watching "/home/roc***/dev/vue/ev***/functions" for Cloud Functions...
i  functions[scheduledFunction]: function ignored because the pubsub.googleapis.com emulator does not exist or is not running.
✔  All emulators started, it is now safe to connect.

how do i get the pubsub emulator to work locally?

**Comment by samtstern** [comment]
@rockyxcoded currently we don't have a PubSub emulator as part of the Firebase Emulator Suite.  Even though there is a PubSub emulator as part of `gcloud`, it doesn't support Cloud Functions triggers so it wouldn't be very useful in this context.

I will mark this as a Feature Request for PubSub.

**Comment by ggirotto** [comment]
@samtstern What do you recommend to locally test PubSub functions?

**Comment by samtstern** [comment]
1) You could use firebase-functions-test:
https://firebase.google.com/docs/functions/unit-testing

2) You could make an HTTP function that acts like the PubSub function for
testing.  Something like this (excuse the pseudocode I'm on my phone)

exports.pubsubFn = functions.pubsub(() => {
   innerFunction()
})

exports.httpTestFn = functions.https(() => {
   innerFunction()
})

**Comment by ggirotto** [comment]
Thanks for the quick answer @samtstern!

**Comment by ErwinAI** [comment]
I'd like to +1 for this feature request. Unfortunately, some of my pubsub functions are triggered by my http functions. Because of this, the solution to place the pubsub function code in a http function would require me to implement changes in other existing functions.

Because scheduled functions also work with pubsub internally, could these also be within the scope? Or would that be a separate feature request?

**Comment by samtstern** [comment]
How would you expect scheduled functions to work in the emulator?  Let's
say you have a daily cleanup function, would you leave the emulator running
all day?  Or would you want to be able to force them to run somehow.

**Comment by ErwinAI** [comment]
@samtstern From my point of view, it would be best to only allow manual triggering somehow. To have the scheduled function run on localhost as configured wouldn't make sense; that would only really allow the developer to check if the function actually triggers as configured and that doesn't seem like something you'd want to do.

**Comment by matejcsok-istvan** [comment]
it is very simple to test schedule functions locally, it is just not clear how to do it
[follow the docs](https://firebase.google.com/docs/functions/local-shell#set_up_admin_credentials_optional)
- install firebase-tools
- run `export GOOGLE_APPLICATION_CREDENTIALS="path/to/key.json"`
- run `firebase functions:shell`
- than just call you schedule function in the same console window, like scheduleFunction(), it will trigger your schedule function

**Comment by deadsoul44** [comment]
@matejcsok-istvan I keep  getting the error below. Any idea how to solve it? Thank you.

```Error: Server Error. connect ECONNREFUSED 127.0.0.1:4400```

**Comment by matejcsok-istvan** [comment]
@

> @matejcsok-istvan I keep getting the error below when I run `firebase functions:shell`. Any idea how to solve it? Thank you.
> 
> `Error: Server Error. connect ECONNREFUSED 127.0.0.1:4400`

Did you follow the official docs?

**Comment by deadsoul44** [comment]
Yes, I am on windows. I followed the instructions for windows. Maybe, I am missing something very basic?

**Comment by rubenheymans** [comment]
> Yes, I am on windows. I followed the instructions for windows. Maybe, I am missing something very basic?

did you find a solution already? I'm facing the same issue

**Comment by rubenheymans** [comment]
`npm install --save firebase-functions@latest
npm install -g firebase-tools`

this fixed it for me

**Comment by ma-ruz** [comment]
> @matejcsok-istvan I keep getting the error below when I run `firebase functions:shell`. Any idea how to solve it? Thank you.
> 
> `Error: Server Error. connect ECONNREFUSED 127.0.0.1:4400`

This is probably caused by a firewall block. Maybe Windows Defender.

**Comment by dayadam** [comment]
wild that firebase doesn't support running time trigger functions locally.

**Comment by yuchenshi** [comment]
@dayadam See #2034
