### ISSUE TITLE
Can you use node's experimental-modules flag with firebase functions?

### ISSUE THREAD

**Issue by Dean-NC** [firebase/firebase-tools#1752]
I'm aware that you can use node's experimental-modules flag if you're running node from the command-line, but if you're using firebase "serve", how can you specify the experimental flag?
I've read all the documentation I can find for firebase, and searched the issues for the functions, tools, and js-sdk github sites, but I can't find any info on it.

Thanks.

**Comment by samtstern** [comment]
@Dean-NC I assume you're talking about serving cloud functions locally using `firebase serve`?  We don't allow passing any flags to the `node` command because we want the local serving environment to match the production serving environment as closely as possible.

**Comment by Dean-NC** [comment]
How can I use a node flag, even in production? I don't know where to put it...firebase.json?  functions\package.json?
Thanks.

**Comment by samtstern** [comment]
@Dean-NC yes sorry for being unclear.  This is a  "not supported at all" thing.

**Comment by Dean-NC** [comment]
@samtstern Thanks. At least I finally know. I'm wanting to use es6 modules with Node, and as of version 12 LTS and the latest version 13, you need to use the experimental flag. So it looks like until Node makes it final and the flag not necessary, I can't use them.
