### ISSUE TITLE
Firebase auth export Error " Error: connect ETIMEDOUT -.-.-.-:443" after few successful iterations

### ISSUE THREAD

**Issue by akashgangrade** [firebase/firebase-tools#1759]
### [REQUIRED] Environment info
CLI -7.6.2

node Version: 8.10.0

**firebase-tools:7.6.2**

**Platform:Linux**

### [REQUIRED] Test case
Export firebase authentication users data to csv using firebase auth export command.

### [REQUIRED] Steps to reproduce

- Run command  
   **firebase auth:export export_cli_user.csv --project projectId** 

- Few thousand records exported successfully then server timedout with the error message:
[debug] [2019-10-31T09:52:02.943Z] <<< HTTP RESPONSE 200
[info] ✔  Exported 500 account(s) successfully.
[debug] [2019-10-31T09:52:07.954Z] >>> HTTP REQUEST POST https://www.googleapis.com/identitytoolkit/v3/relyingparty/downloadAccount
[debug] [2019-10-31T09:54:18.312Z] Error: connect ETIMEDOUT -.-.-.-:443
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
[error]
[error] Error: Server Error. connect ETIMEDOUT -.-.-.-:443

### [REQUIRED] Expected behavior
All user records should be exported to the CSV.

### [REQUIRED] Actual behavior
The export command gets terminated after few successful iterations

**Comment by katowulf** [comment]
Likely not related to the CLI, but we should investigate a bit more. Can you rerun the export with `--debug` and either post the output or email it directly to me (katowulf@google.com) please? I'll have a look and confirm it's not a CLI issue.

**Comment by akashgangrade** [comment]
@katowulf - It has already been exported with --debug command. 
Seems issue with download account API(https://www.googleapis.com/identitytoolkit/v3/relyingparty/downloadAccount) as it is getting timed-out after few iterations. 

I cannot use listUsers here as my use case is different, I wanna find the duplicate users stored in Firebase authentication having same email address but different uid. And listUsers will only return one record of the duplicate user.
