### ISSUE TITLE
Firestore Emulator: Firestore rule is not correctly validated

### ISSUE THREAD

**Issue by leonardarnold** [firebase/firebase-tools#1760]
### [REQUIRED] Environment info

**firebase-tools:7.6.2

**Platform:macOS

### [REQUIRED] Test case

firestore emulator is not working as expected using this rule:
`allow update: if request.auth.uid == userId && resource.data.createdAt == request.resource.data.createdAt;`

### [REQUIRED] Steps to reproduce

I used the [javascript quickstart  guide](https://github.com/firebase/quickstart-nodejs/tree/master/firestore-emulator/javascript-quickstart) to test firestore rules.

I added an allow update rule:

```
match /users/{userId} {
      allow read;
      allow create: if request.auth.uid == userId && request.resource.data.createdAt == request.time;
      allow update: if request.auth.uid == userId && resource.data.createdAt == request.resource.data.createdAt;
    }
```

The added test is failing:
```
it("should not let edit users createdAt after document creation", async() =>{
    const db = authedApp({ uid: "alice" });
    const profile = db.collection("users").doc("alice");
    await firebase.assertSucceeds(
      profile.set({
        birthday: "January 1",
        createdAt: firebase.firestore.FieldValue.serverTimestamp()
      })
    );
    //should fail due to new createdAt value
    await firebase.assertFails(
      profile.set({
        birthday: "January 2",
        createdAt: firebase.firestore.FieldValue.serverTimestamp()
      })
    );
    //should not fail
    await firebase.assertSucceeds(
      profile.set({
        birthday: "January 3",
      })
    );
  });
```

### [REQUIRED] Expected behavior
The test should not fail `resource.data.createdAt == request.resource.data.createdAt` has not been modified.

### [REQUIRED] Actual behavior
The test above fails (on the last assertSucceeds).

I tested the behavior on the firestore production instance and it works for me as expected.

The output is:

```
  1) My app
       should not let edit users createdAt after document creation:
     FirebaseError: 7 PERMISSION_DENIED:
Property createdAt is undefined on object. for 'update' @ L6
```

**Comment by samtstern** [comment]
I think this failure is correct. When you call profile.set({ birthday:
"January 3" }) you are replacing the whole document and the only field that
will exist is "birthday".  So createdAt will be undefined.  Did you mean to
call update instead of set?

**Comment by leonardarnold** [comment]
Hi thanks for the quick response. Yes it is working with an update call!
This was confusing to me I use firebase with the dart package and I in our code we only use set (+merge) and the example has no tests for updates. Didn't even consider this option...
