### ISSUE TITLE
Firebase Tools broken on Intel Ice Lake (Assertion failed: new_time >= loop->time)

### ISSUE THREAD

**Issue by Yonom** [firebase/firebase-tools#1772]
### Environment info

7.6.2

**Platform:** Windows 10 Home 1903 Build 18362.356
**Processor:** i7-1065G7
**Node Version:** 10.16.3 LTS / 12.13.0 LTS

### Test case

**Problem only affects Intel Ice Lake processors on Windows.**
No setup needed.

### Steps to reproduce

Run any command. Example: `firebase login`

### Expected behavior

The command should work.

### Actual behavior

Before any user input can be entered, firebase cli crashes.

```
PS C:\Users\simon\Documents\GitHub\reado-fe> firebase login
i  Firebase optionally collects CLI usage and error reporting information to help improve our products. Data is collected in accordance with Google's privacy 
policy (https://policies.google.com/privacy) and is not used to identify you.

? Allow Firebase to collect CLI usage and error reporting information? (Y/n) Assertion failed: new_time >= loop->time, file c:\ws\deps\uv\src\win\core.c, line 309
```  

### See also

https://github.com/libuv/libuv/issues/1633

Problem reported on Sept 13th. No acknowledgement from the libuv team yet.

Similar projects affected:
Heroku https://github.com/heroku/cli/issues/1354
Github Actions virtual environments https://github.com/actions/virtual-environments/issues/67

**Comment by samtstern** [comment]
@Yonom thanks for all the details and related issues!  I won't pretend to understand the root cause here.  Is there something you think we could do in the Firebase CLI to prevent or mitigate this?

**Comment by Yonom** [comment]
I am just a user of your product, I do not understand the core issue either, so sadly I cannot help much. 
If firebase plans on supporting Intel Ice Lake processors, the team should do _something_ about it...

**Comment by abeisgoat** [comment]
Some quick snooping pulls up [this libuv issue](https://github.com/libuv/libuv/issues/1633) where the dev explains that this is a symptom of your system clock drifting in an unexpected way (I assume libuv relies on some form of constant tick which it's not getting). This library is used as part of the core Node.js runtime, so it's very unlikely there's anything we can possibly do to resolve this, it's either an issue with your system or an upstream (*way* upstream) issue in Node.

**Comment by stevead1** [comment]
same error here

**Comment by iceboss3d** [comment]
Was having same error, only to realize it was as a result of multiple apps in the project. I needed to specify which app I was deploying to firebase deploy --only hosting:theAppName

**Comment by soraryu** [comment]
@abeisgoat I'm curious, have you contacted the libuv people about this? As more and more 10th gen Intel procs are on the market, more people (like me!) are having this issue with random products using node.js.

**Comment by appdevworx** [comment]
I had this exact problem also, it was fixed as follows:
1- Uninstall Nodejs (latest version today 14.4.0 Current)
2- Install the stable recommended version (12.18.0 LTS)
3- reinstall firebase-tools again (npm install -g firebase-tools) 

I don't understand neither the root cause of the problem, nor, why exactly it was fixed. but this what happend and firebase login worked after this.

**Comment by Yonom** [comment]
A fix was made in libuv, updating nodejs will probably use the patched version which solved the issue.

@appdevworx

**Comment by KaterineMoon** [comment]
I tried all the solutions here and other found in other sites, and none of them works. Therefore, I should use WSL, install node and firebase on it, and finally I was able to run the firebase commands.

Hope this will be helpful for someone!

**Comment by SureshKrishnaaR** [comment]
(FIXED)
I had the same problem guys...!
What I did was I mentioned the firebase-tools version while installing them, that is
           𝐧𝐩𝐦 𝐢𝐧𝐬𝐭𝐚𝐥𝐥 -𝐠 𝐟𝐢𝐫𝐞𝐛𝐚𝐬𝐞-𝐭𝐨𝐨𝐥𝐬 𝟖
And after running this command this problem was resolved so go ahead and try out this!
This will work out for sure...!

**Comment by abeisgoat** [comment]
Thanks for everyone chiming in, as I suspected it's a bug in Node so seems like general solution is to update / reinstall Node and try again.

**Comment by ab07max** [comment]
> I tried all the solutions here and other found in other sites, and none of them works. Therefore, I should use WSL, install node and firebase on it, and finally I was able to run the firebase commands.
> 
> Hope this will be helpful for someone!

This fixed the issue for me. Cheers!

**Comment by ab07max** [comment]
> (FIXED)
> I had the same problem guys...!
> What I did was I mentioned the firebase-tools version while installing them, that is
> 𝐧𝐩𝐦 𝐢𝐧𝐬𝐭𝐚𝐥𝐥 -𝐠 𝐟𝐢𝐫𝐞𝐛𝐚𝐬𝐞-𝐭𝐨𝐨𝐥𝐬 𝟖

This solved my issue. Cheers!

**Comment by AndyKgotatso** [comment]
> I had this exact problem also, it was fixed as follows:
> 1- Uninstall Nodejs (latest version today 14.4.0 Current)
> 2- Install the stable recommended version (12.18.0 LTS)
> 3- reinstall firebase-tools again (npm install -g firebase-tools)
> 
> I don't understand neither the root cause of the problem, nor, why exactly it was fixed. but this what happend and firebase login worked after this.

Thanks you , this solved the problem for me

**Comment by Narsinhs** [comment]
didn't work for me :(
