### ISSUE TITLE
"]0;Firebase CLI" is automatically added to .runtimeconfig.json

### ISSUE THREAD

**Issue by DEV-MK-KIM** [firebase/firebase-tools#1774]
### [REQUIRED] Environment info

**firebase-tools: 7.6.2**

**Platform: MacOS Catalina**

### [REQUIRED] Steps to reproduce

After I set custom key:value in firebaseconfig.json using below command

```
firebase functions:config:set app.api_key=abcde12345
```

and run the command to update runtimeconfig 

```
firebase functions:config:get > .runtimeconfig.json
```

and in my actual runtimeconfig.json file, I see this line `1]0;Firebase CLI` added on top of json.
 
```JSON
]0;Firebase CLI{
  "a": {
    "id": {
      "seg": "abcde"
    },
    "api_key": "abcde"
}
```
### [REQUIRED] Expected behavior

I haven't seen this bug, until I set up `export GOOGLE_APPLICATION_CREDENTIALS=[path/json]`

### [REQUIRED] Actual behavior

This is what I see.

```JSON
]0;Firebase CLI{
  "a": {
    "id": {
      "seg": "abcde"
    },
    "api_key": "abcde"
}
```

**Comment by samtstern** [comment]
@DEV-MK-KIM huh that's really strange.  What terminal app are you using?

**Comment by DEV-MK-KIM** [comment]
i am using iTerm2

> @DEV-MK-KIM huh that's really strange. What terminal app are you using?

**Comment by bkendall** [comment]
I am unable to replicate this on `firebase-tools@7.6.2` or off of `master`. Can you update to latest (`npm i -g firebase-tools@latest`) and give it another try?

If that doesn't fix it, could you let me know how you're running these commands? Are you running them directly on the terminal, or through a script? (Sometimes there's a different version of `firebase-tools` that's installed and conflicting...)

**Comment by DEV-MK-KIM** [comment]
After updating firebase-tools 7.8.1 I don't see this bug anymore. Thanks for your feedback.
