### ISSUE TITLE
Auth export/import does not handle disabled property

### ISSUE THREAD

**Issue by dmartin35** [firebase/firebase-tools#1777]
### [REQUIRED] Environment info

**firebase-tools:** 7.6.2

**Platform:** macOS Mojave, version 10.14.6 

### [REQUIRED] Test case

*To give a bit of context of my use case. I'm trying to replicate a users list between two firebase projects, using the command line. I want to import all my users with their enabled/disabled state on the new project.*

### [REQUIRED] Steps to reproduce

Go to the Firebase console, then to the Developer > authentication page.
Add a new user, then disable it.

Go to a terminal, and export the users list.
`$ firebase auth:export --format csv --project <my-initial-project>  users.csv`

Import the list into another project:
`$ firebase auth:import --project <my-replicated-project> users.csv`

### [REQUIRED] Expected behavior

* The users list csv file contains the `disabled` property for each user.
* The import command can create users with disabled state as True

### [REQUIRED] Actual behavior

* The exported users list is missing the `disabled` state of the user.
* The newly imported user on the replicated project is not disabled.

**Comment by bkendall** [comment]
I am able to reproduce this. I started looking into it more and (a) I think the import/export files are a little scary and (b) the `disabled` field isn't even _documented_ on the corresponding [api documentation](https://developers.google.com/identity/toolkit/web/reference/relyingparty/downloadAccount)

That said, I'm gonna take on the fix - in theory it's easy - and come back around with some people internally to make sure it's okay to pass through that value.
