### ISSUE TITLE
Program not working when using -P with --token

### ISSUE THREAD

**Issue by olivierchatry** [firebase/firebase-tools#178]
Feeling a new bug, as I'm not sure a closed bug can be reopened.

When using `--token` with a valid token obtained with `login:ci`, all the `database:` commands are not working. 

If you look at the code of all these commands, `requireDatabaseAccess` is executed before. 
- If you do not use `--token` option, it calls `requireAccess` which setup everything correctly. 
- If you are using the `--token` option, then nothing is setup, and the commands fails.

What I did to make it works is :

``` js
// file: requireDatabaseAccess 
'use strict';
var utils = require('./utils');
var RSVP = require('rsvp');
var requireAccess = require('./requireAccess');
var getInstanceId = require('./getInstanceId');
var getProjectId = require('./getProjectId');
var requireAuth = require('./requireAuth');

module.exports = function(options, authScopes) {
  var token = utils.getInheritedOption(options, 'token');

  if (token) {
    var projectId = getProjectId(options);
    options.project = projectId;
    options.databaseAdminToken = token;
    return requireAuth(options, authScopes).then(function() {
      return getInstanceId(options);
    }).then(function(instance) {
      options.instance = instance;
    })
  }

  return requireAccess(options, authScopes);
};
```

And now everything is working correctly. Should I create a pull request ?

**Comment by olivierchatry** [comment]
Note that define FIREBASE_TOKEN works perfectly fine.

**Comment by mbleigh** [comment]
Thanks for the bug report and sample fix! I'm going to take a look at this today and see what's going on.

**Comment by mbleigh** [comment]
This bug is caused by the fact that `--token` on the database commands has a different meaning than for the rest of the commands. Your fix will work for some but not all scenarios we care about. This was actually already on our radar and we should have a fix soon, but it'll be a bit of a different flavor. Stay tuned!
