### ISSUE TITLE
Firebase init documentation

### ISSUE THREAD

**Issue by tomashejatko** [firebase/firebase-tools#1808]
### [REQUIRED] Environment info

**firebase-tools:**
7.7.0

**Platform:** All

### [REQUIRED] Steps to reproduce

firebase init --help

### [REQUIRED] Expected behavior

Any kind of documentation

### [REQUIRED] Actual behavior

```
$ firebase init --help
Usage: init [options] [feature]

setup a Firebase project in the current directory

Options:
  -h, --help  output usage information
```

Guys, is there any documentation for this, please?
Official page https://github.com/firebase/firebase-tools#configuration-commands suggets to use `--help` parameter, but outpu is useless.

Thanks for help

**Comment by samtstern** [comment]
@arteal I agree the documentation is not good enough here.  Can you tell me what you're trying to do?

Also it might be best if you just run `firebase init` with no arguments.  This will walk you through a "wizard" like flow where you can see a list of available features and initialize them.

**Comment by arteal** [comment]
Hello, we want to use `firebase init` as part of automatization. We know it can't be run with SA, so always human will run, but still we want have script that will always produce same results.

What we now need is to be able : 

- Turn on Firestore by parameter
- Turn on Functions by parameter
- Ideally do not run any "wizard parts"

Thanks for your help!

**Comment by gautamsingal** [comment]
@samtstern Is this still open?

**Comment by samtstern** [comment]
@gautamsingal yes this is still open, the docs could be improved.

We also have this related issue to make the command more automation friendly:
https://github.com/firebase/firebase-tools/issues/2333

**Comment by gautamsingal** [comment]
Thanks for the update @samtstern. Will pick this up and do

**Comment by gautamsingal** [comment]
Hi @samtstern. Can you guide a bit in this as I'm a bit lost on where to start from? 😁

**Comment by samtstern** [comment]
@gautamsingal the documentation would go here:
https://github.com/firebase/firebase-tools/blob/master/src/commands/init.js#L26

Some things you might want to mention:

- The `firebase init` command is an interactive setup command to build your `firebase.json` file and bootstrap Firebase services.
- You can use `firebase init` to add a new Firebase product to your project even if you have already run `init` before.  For example you could run `firebase init hosting` on a project that is already using Cloud Functions.
- You can initialize a single feature by running something like `firebase init firestore`
