### ISSUE TITLE
emulators:exec should wait until there are no more pending function executions

### ISSUE THREAD

**Issue by samtstern** [firebase/firebase-tools#1813]
### [REQUIRED] Environment info

**firebase-tools:** 7.8.0

**Platform:** Linux

### [REQUIRED] Test case

Two functions:

  * FunctionA has an HTTP trigger
  * FunctionB has a PubSub trigger on topic 'foo'

Let's say FunctionA looks like this:
```
for (let i = 0; i < 10; i++) {
  pubsub.send('foo', { data: i })
}
```

I would like to be able to wait until all 10 of the PubSub functions run but this is not captured by:

```
$ firebase emulators:exec "curl http://localhost:3001/my-project/us-central1/projectA
```

It would be nice if `emulators:exec` could ask the Functions emulator (and maybe all the others) if they're done.

Or this could also be implemented as having the Functions emulator's `stop()` function have a waiting option.

### [REQUIRED] Steps to reproduce

See above

### [REQUIRED] Expected behavior

See above

### [REQUIRED] Actual behavior

See above

**Comment by samtstern** [comment]
More discussion:
https://github.com/firebase/firebase-tools/issues/2129#issuecomment-613644766

**Comment by manwithsteelnerves** [comment]
Quote from your earlier comment
> 1. We could have the Functions emulator report whether there are any functions currently running.
> 2. We could ask all the other emulators whether they are still processing anything.

I think a function (in firebase-testing) to check if any emulators are still processing will be of great help. As we just wait for it(poll and sleep) until it's done and do the teardown of tests.
Or
clearFirestoreData method should internally poll(firestore emulator) and do the required action - As this is what everyone might be expecting too as they don't want to clear db before emulators finish processing.
