### ISSUE TITLE
firebase-tools serve makes an error

### ISSUE THREAD

**Issue by parsher** [firebase/firebase-tools#1815]
### [REQUIRED] Environment info

**firebase-tools: 7.8.0 (the latest)

**Platform: macOS

### [REQUIRED] Test case

firebase functions
> project
>> functions
>> index.js : exports.posts = functions.https.onRequest(require('./posts')); exports.posts = functions.https.onRequest(require('./accounts'));
>>> posts : index.js : const app = require('express')(); const cors = require('cors'); app.use(cors({ origin: true })); app.get('/', async (req, res) => { });
>>> accounts: index.js : const app = require('express')(); const cors = require('cors'); app.use(cors({ origin: true })); app.get('/', async (req, res) => { });

### [REQUIRED] Steps to reproduce

firebase functions + express get / post methods
request multiple get requests, it makes errors.
it is only made on firebase-tools 7.8.0.
if I run the same codes on firebase-tools 7.7.0., it works fine.

### [REQUIRED] Expected behavior

If I request multiple requests, it accepts well and perform.

### [REQUIRED] Actual behavior

it makes an error

```
i  functions: Beginning execution of "accounts"
[2019-11-19T10:17:42.957Z] [runtime-status]  {"httpsTrigger":{},"name":"accounts","entryPoint":"accounts"}
[2019-11-19T10:17:42.957Z] [runtime-status] Running accounts in mode HTTPS {}
[2019-11-19T10:17:42.962Z] [functions] Runtime ready! Sending request!
[2019-11-19T10:17:42.968Z] [runtime-status] Ephemeral server used! {}
[2019-11-19T10:17:43.003Z] [runtime-status] Ephemeral server survived. {}
[2019-11-19T10:17:43.339Z] Accepted request OPTIONS /~/posts/rT7UgEMG8KhTlLOADE3y/comments --> posts
[2019-11-19T10:17:43.339Z] [worker-posts-3a43686e-d66c-4835-a45e-b4be49366232]: Assigning socketPath: /var/folders/zp/903b9f055r1czvjktw3fg_7r0000gn/T/firebase_emulator_invocation_3a43686e-d66c-4835-a45e-b4be49366232.sock
[2019-11-19T10:17:43.339Z] [worker-posts-3a43686e-d66c-4835-a45e-b4be49366232]: BUSY
[2019-11-19T10:17:43.339Z] [runtime-status] Trigger "posts" has been found, beginning invocation! {}
i  functions: Beginning execution of "posts"
[2019-11-19T10:17:43.340Z] [runtime-status]  {"httpsTrigger":{},"name":"posts","entryPoint":"posts"}
[2019-11-19T10:17:43.340Z] [runtime-status] Running posts in mode HTTPS {}
>  events.js:174
>        throw er; // Unhandled 'error' event
>        ^
>  
>  Error: listen EADDRINUSE: address already in use /var/folders/zp/903b9f055r1czvjktw3fg_7r0000gn/T/firebase_emulator_invocation_3a43686e-d66c-4835-a45e-b4be49366232.sock
>      at Server.setupListenHandle [as _listen2] (net.js:1263:19)
>      at listenInCluster (net.js:1328:12)
>      at Server.listen (net.js:1426:5)
>      at Function.listen (/Users/mmj/.npm-global/lib/node_modules/firebase-tools/node_modules/express/lib/application.js:618:24)
>      at Promise (/Users/mmj/.npm-global/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:563:46)
>      at new Promise (<anonymous>)
>      at /Users/mmj/.npm-global/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:528:15
>      at Generator.next (<anonymous>)
>      at /Users/mmj/.npm-global/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:7:71
>      at new Promise (<anonymous>)
>  Emitted 'error' event at:
>      at emitErrorNT (net.js:1307:8)
>      at process._tickCallback (internal/process/next_tick.js:63:19)
[2019-11-19T10:17:43.352Z] [worker-posts-3a43686e-d66c-4835-a45e-b4be49366232]: exited
[2019-11-19T10:17:43.353Z] [worker-posts-3a43686e-d66c-4835-a45e-b4be49366232]: FINISHED
```

**Comment by samtstern** [comment]
Thanks for filing this!  Could you show the source code for the function
you're calling?

**Comment by osadchiynikita** [comment]
+1 Same issue with latest version (7.8.0). **Second** call to the function throws this error.

Just rolled back to 7.7.0 and it works fine.

**Comment by samtstern** [comment]
@osadchiynikita can you show me the simplest function you have that reproduces this error?

**Comment by osadchiynikita** [comment]
@samtstern I just started to set up new project, so I was testing with the simple hello function

```
import { https } from 'firebase-functions';

export const hello = https.onRequest((request, response) => {
  response.send('Hello from Firebase!\n\n');
});
```

With the next firebase.json config

```
{
  "functions": {
    "source": ".",
    "predeploy": "npm run build"
  },
  "hosting": {
    "rewrites": [
      {
        "source": "**/**",
        "function": "hello"
      }
    ]
  },
  "emulators": {
    "functions": {
      "port": "4001"
    },
    "hosting": {
      "port": "4002"
    }
  }
}
```

When I'm calling function first time (open in browser), it executes correctly, but for the next call (page reload) server throws "Address in use" error

**Comment by samtstern** [comment]
@osadchiynikita I was able to reproduce this, thank you for your help!  Definitely downgrade to `7.7.0` for now.

**Comment by osadchiynikita** [comment]
@samtstern Great! Thank you

**Comment by samtstern** [comment]
Ok it happened during this PR:
https://github.com/firebase/firebase-tools/pull/1778

So it's my fault (obviously).  Now need to dig.

**Comment by parsher** [comment]
@osadchiynikita @samtstern Thank you for all! I was worried about this, because I'm developing based on firebase.

**Comment by samtstern** [comment]
I figured this out and a fix will be merged soon.  In the meantime everyone
here should use 7.7.0.

**Comment by richard-mckenna** [comment]
omg @parsher this was driving me nuts all yesterday, I was convinced it was something I was doing while configuring my Vue project to use the emulators in dev and live in production. Downgraded to 7.7.0 and it works fine. I didn't twig that I had updated firebase-tools yesterday morning, just before I started having issues. :| @samtstern I'll only blame you for an hour or so ha ha.

**Comment by samtstern** [comment]
For everyone affected by this: version `7.8.1` was just released!

**Comment by parsher** [comment]
@samtstern Thank you for your fast release! 
@richard-mckenna Me too, I eased every code I had written when I face it. ha ha. I am using Vue too :)
