### ISSUE TITLE
FR: Simpler invocation of PubSub functions in `functions:shell`

### ISSUE THREAD

**Issue by samtstern** [firebase/firebase-tools#1827]
Right now if I want to invoke a PubSub function I have to do something like this:
```
SaveRepoSnapshot({ data: Buffer.from(JSON.stringify({ org: "firebase", repo: "firebaseui-android"}))})
```

In the simple case of a PubSub message with data only I would prefer to be able to do:
```
SaveRepoSnapshot({ org: "firebase", repo: "firebaseui-android" })
```

We could handle stringification and bufferizing.

**Comment by rgmvisser** [comment]
@samtstern this works for me for testing:
`SaveRepoSnapshot({json: { org: "firebase", repo: "firebaseui-android" }})`

**Comment by samtstern** [comment]
@rgmvisser oh wow I can't believe I never realized that!  Looks like we don't need to do anything then.
