### ISSUE TITLE
Error: failed to upload distribution. failed to find the uploaded release: HTTP Error: 404

### ISSUE THREAD

**Issue by claudioviola** [firebase/firebase-tools#1828]
### [REQUIRED] Environment info

**firebase-tools:** 7.7.0

**Platform:**macOS

### [REQUIRED] Test case
I've been trying to upload ipa via firebase tools with command
`firebase appdistribution:distribute` but I've been receiving 404 error.
I attached log file here
For security reason I removed a bit of sensible information in the log file
[firebase-debug.log](https://github.com/firebase/firebase-tools/files/3878785/firebase-debug.log)

### [REQUIRED] Steps to reproduce

Run via shell the command
`
GOOGLE_APPLICATION_CREDENTIALS=firebase-quality-admin-service-account-key.json firebase appdistribution:distribute myApp.ipa --app appid --debug
`

### [REQUIRED] Expected behavior

ipa is uploaded and visible in Firebase App Distribution

### [REQUIRED] Actual behavior

ipa is not uploaded in Firebase App Distribution

**Comment by pranavrajgopal** [comment]
@claudioviola  Hello! I am an engineer on the App Distribution team. We have been having issues with binary uploads in Europe mostly due to latency. We're working on improving the upload process to improve error handling and fix the latency issues. Meanwhile, could you check if you can see your IPA in the App Distribution dashboard in Firebase? One way to mitigate this issue is to the run the CLI command twice. Let me know!

**Comment by claudioviola** [comment]
@pranavrajgopal Hello! Thanks for the support
I tried to run the CLI command twice and didn't work.
I can't see any new IPA in the App Distribution Dashboard.
So it seems it's not an issue of firebase tools 7.7.0. Right?

Do you have idea when you can fix it?
Many thanks

**Comment by claudioviola** [comment]
@pranavrajgopal 
I tried to upload manually the IPA in the App Distribution  and it works.
Maybe this info it can help you to understand better the issue and why doesn't work with firebase tools CLI

Thanks again

**Comment by tonybaroneee** [comment]
@claudioviola thanks! The upload timeout is substantially shorter in the CLI than in the Firebase Console, which might explain why it worked manually. Along with improving the upload process, we'll be upping the timeout in the CLI so that it's less likely to fail. Thanks for your patience!

**Comment by claudioviola** [comment]
Hey guys
just to plan my activities...
Do you have any idea in terms of time when you will be able to fix the issue?

Thanks for the support.
Claudio

**Comment by tonybaroneee** [comment]
Hey Claudio, thanks for your patience. We've made some improvements to the uploading process in [v7.9.0](https://github.com/firebase/firebase-tools/releases/tag/v7.9.0). Would you mind updating to that version and seeing if your issue is resolved? Thanks!

**Comment by claudioviola** [comment]
Hey @tonybaroneee 
Thanks for support and sorry for not getting back to you sooner.
I've been trying with same command from my shell

`
GOOGLE_APPLICATION_CREDENTIALS=/Users/claudio/MyApp/firebase-quality-admin-service-account.json firebase appdistribution:distribute /Users/claudio/MyApp/ios/MyApp.ipa --app x:xxxxxxxxxxx:android:xxxxxxxxxx
`
but still doesn't work but 404 is gone now the error is 
`
Error: failed to upload distribution. error processing your binary: There was an error parsing your app's resources.arsc file. Ensure you are uploading a valid APK and try again. (Code: MISSING_RESOURCES)
`
I made sure `ipa` exist in file system and path was correct
I noted that tried to upload an IPA but the error complains about APK

Many thanks!

**Comment by tonybaroneee** [comment]
Thanks @claudioviola! That's really weird. I think the best next step would be for you to send us your IPA so we can investigate more. If you're in the Firebase Community slack, feel free to DM it to me (Anthony Barone), or you can reach out to Firebase support to send it through them. Thanks!

**Comment by tonybaroneee** [comment]
Customer was using the incorrect `appId`, this is resolved.
