### ISSUE TITLE
Flags being interepreted as files in predeploy hook 

### ISSUE THREAD

**Issue by ocBruno** [firebase/firebase-tools#1829]
<!-
### [REQUIRED] Environment info

firebase-tools@7.8.1

Windows 10

### [REQUIRED] Test case

https://github.com/williamchong007/nuxt-ssr-firebase

### [REQUIRED] Steps to reproduce

1) Download project https://github.com/williamchong007/nuxt-ssr-firebase

2) Follow setup instructions

3) Update and install dependencies

4) Replace functions predeploy hook in firebase.json with the following:

"functions": {
    "source": "functions",
    "predeploy": [
      "npm --prefix src run lint && npm --prefix src run build && rd /s /q functions\\nuxt"
    ]
  }

### [REQUIRED] Expected behavior

Deletion of the folder and subdirectories or atleast the 145 directory is not empty error to come before the other errors.

### [REQUIRED] Actual behavior

Output:
...
Running command: npm --prefix src run lint && npm --prefix src run build && rd /s /q functions\nuxt
..

                  Asset       Size  Chunks                         Chunk Names
a01bfe59ab91db95388c.js   1.53 KiB       1  [emitted] [immutable]  pages_index
              server.js     25 KiB       0  [emitted]              app
   server.manifest.json  145 bytes          [emitted]
Entrypoint app = server.js

The system cannot find the file specified. _This is /s flag ?_
The system cannot find the file specified. _This is /q flag ?_
The directory is not empty.  _functions\nuxt_

Error: functions predeploy error: Command terminated with non-zero exit code145

### Final Comments

I'm not certain this is a bug but windows has giving me quite some trouble lately so I thought I would post it here just in case. If there is insufficient info I would be happy to provide more. 
As a side note I was able to delete the folders using rimraf but I then have to copy folders and ROBOCOPY flags were giving me the same issue which I thought was very weird.

**Comment by laurenzlong** [comment]
If you simply ran `rd /s /q functions\nuxt` in the functions folder, does it do what you expect? Can you copy and paste the output here?

**Comment by ocBruno** [comment]
Running the code inside the functions folder it returns "The system cannot find the path specified".
 Running the command in the base directory successfully deletes the nuxt folder which is why I was confused. In the predeploy hook if I remove the flags it works but I need the flags to delete the entire directory tree. 

I went to reinstall dependencies and I got a missing package error which contained this log.

Debug log contained this

1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   '--prefix',
1 verbose cli   'functions',
1 verbose cli   'install'
1 verbose cli ]

 10 verbose stack Error: ENOENT: no such file or directory, open 'C:\Users\55419\Code\nuxt-ssr-firebase-master-ref\package.json'


**Thank you Lauren for helping me understand the problem! Although I prefixed the functions folder it tried installing in the current directory, I'm guessing this problem is not with firebase-tools so I will close this issue and debug my environment and npm but in case there might be something correlated feel free to reopen. **
