### ISSUE TITLE
rawBody is missing in firebase cloud functions emulator

### ISSUE THREAD

**Issue by astromme** [firebase/firebase-tools#1830]
### [REQUIRED] Environment info

**firebase-tools: 7.8.1**

**Platform: macOS**

### [REQUIRED] Test case

https://firebase.google.com/docs/functions/http-events indicates that a `rawBody` parameter should exist on `req`. However, it is `undefined` in my local emulator.

**What am I doing wrong?**

    $ firebase --version
    7.8.1

My client-side javascript code for POSTing the binary data:

    var buffer = new ArrayBuffer(4);
    var view = new DataView(buffer);

    function writeUTFBytes(view, offset, string) {
        var lng = string.length;
        for (var i = 0; i < lng; i++) {
            view.setUint8(offset + i, string.charCodeAt(i));
        }
    }

    writeUTFBytes(view, 0, 'RIFF');

    var blob = new Blob([view]);

    fetch('http://localhost:5001/firebase-project-name/us-central1/endpointName', {
      method: 'POST',
      body: blob
    })

My index.js firebase cloud functions code:

    const functions = require('firebase-functions');

    exports.endpointName = functions.https.onRequest((req, res) => {
      res.set('Access-Control-Allow-Origin', 'http://localhost:3000');
    
      console.log(req.rawBody);
      console.log(typeof req.rawBody);

      res.end();
    });

When I run the function, here's what I get:

    $ firebase emulators:start --only functions
    <snip>
    i  functions: Beginning execution of "endpointName"
    >  
    >  undefined

I've confirmed with HTTP Toolkit that the body is in fact sent from my browser:

[![HTTP Toolkit showing 'RIFF' as body][1]][1]

  [1]: https://i.stack.imgur.com/t3Q7w.png

Also see: https://stackoverflow.com/questions/58999654/rawbody-is-missing-in-firebase-cloud-functions-emulator

**Comment by astromme** [comment]
I have also verified that this problem also occurs in the prod environment after deploying my function.

**Comment by astromme** [comment]
I figured out that if I set a content-type to application/octet-stream or audio/wave then rawBody suddenly appears.

However! I had to modify my function to get the OPTIONS HTTP request to succeed for my browser to ask whether it was ok to include the Content-Type header, otherwise, the actual request was never sent:

```
  res.set('Access-Control-Allow-Origin', 'http://localhost:3000');

  if (req.method === 'OPTIONS') {
      // Send response to OPTIONS requests
      res.set('Access-Control-Allow-Methods', 'OPTIONS, POST');
      res.set('Access-Control-Allow-Headers', 'Content-Type, Content-Length');
      res.set('Access-Control-Max-Age', '3600');
      return res.status(204).send('');
  }
```

However, I'm still curious why no rawBody happens without a content-type header. At the very least, there could be some docs that walk through an end to end example of sending binary data and using rawBody.

**Comment by samtstern** [comment]
@astromme thanks for filing this. It does seem like the behavior is not matching the docs.  But to be clear, are you saying that this issue exists in both production and the emulators?  If so I believe the right thing to do is change the docs to match what happens in production, not change the emulators to match the docs.

**Comment by astromme** [comment]
Correct, I observe this behavior (and the content-type + OPTIONS workaround/fix) in both the emulator and the prod environment. 

Changing the docs is certainly one solution. I don't know enough about the firebase mental model to know if the current behavior is consistent with how things "should work" or not. 

You can imagine a world where the docs perfectly represent reality, but the reality is so confusing and full of gotchas that it makes firebase overall much worse than if the mental models are clean and consistent. 

I leave that determination up to you :D

**Comment by samtstern** [comment]
Turns out this is actually documented here:
https://cloud.google.com/functions/docs/writing/http#handling_content_types

I will update the Firebase docs to link to this.

**Comment by samtstern** [comment]
@jhuleatt and I did some tests in both the emulators and production and it seems like `rawBody` is present as a `Buffer` with or without `Content-Type`. It's only the `req.body` value that changes based on which body parser is triggered.

So it seems like this bug was fixed along the way.
