### ISSUE TITLE
Deploy with pubsub.schedule says success when failed to create Scheduler Job

### ISSUE THREAD

**Issue by stari4ek** [firebase/firebase-tools#1835]
### Related issues

https://github.com/firebase/firebase-functions/issues/578

### [REQUIRED] Version info

**node:** 

```
$ node --version
v12.4.0
```

**firebase-functions:**
```
$ npm list --depth 0 | grep firebase
├── firebase-admin@8.8.0
├── firebase-functions@3.3.0
├── firebase-functions-test@0.1.7
```

**firebase-admin:**
```
$ firebase --version
7.8.1
```

### [REQUIRED] Steps to reproduce

deploy function with `pubsub.schedule`

### [REQUIRED] Expected behavior

* pubsub topic and subscription are created
* scheduled job is created or error reported.
* firebase function is created

### [REQUIRED] Actual behavior

```
$ firebase deploy --only functions:auto_update_tick

=== Deploying to 'SOMEPROJ'...

i  deploying functions
Running command: npm --prefix "$RESOURCE_DIR" run lint

> functions@ lint /home/astar/dev/proj/develop/fb/functions
> tslint --project tsconfig.json

Running command: npm --prefix "$RESOURCE_DIR" run build

> functions@ build /home/astar/dev/proj/develop/fb/functions
> tsc

✔  functions: Finished running predeploy script.
i  functions: ensuring necessary APIs are enabled...
✔  functions: all necessary APIs are enabled
i  functions: preparing functions directory for uploading...
i  functions: packaged functions (133.62 KB) for uploading
✔  functions: functions folder uploaded successfully
i  functions: current functions in project: ...
i  functions: uploading functions in project: auto_update_tick(us-central1)
i  functions: creating Node.js 10 (Beta) function auto_update_tick(us-central1)...
i  scheduler: ensuring necessary APIs are enabled...
i  pubsub: ensuring necessary APIs are enabled...
✔  scheduler: all necessary APIs are enabled
✔  pubsub: all necessary APIs are enabled
✔  functions: created scheduler job firebase-schedule-auto_update_tick-us-central1
✔  functions[auto_update_tick(us-central1)]: Successful create operation. 

✔  Deploy complete!
```

While in `firebase-debug.log`:
```
[debug] [2019-11-26T18:50:36.724Z] >>> HTTP REQUEST GET https://cloudscheduler.googleapis.com/v1beta1/projects/SOMEPROJ/locations/us-central1/jobs/firebase-schedule-auto_update_tick2-us-central1  
 
[debug] [2019-11-26T18:50:37.759Z] <<< HTTP RESPONSE 404
[debug] [2019-11-26T18:50:37.759Z] <<< HTTP RESPONSE BODY
[debug] [2019-11-26T18:50:37.760Z] >>> HTTP REQUEST POST https://cloudscheduler.googleapis.com/v1beta1/projects/SOMEPROJ/locations/us-central1/jobs  

[debug] [2019-11-26T18:50:40.260Z] <<< HTTP RESPONSE 400
[debug] [2019-11-26T18:50:40.260Z] <<< HTTP RESPONSE BODY
```

When I check Cloud Scheduler in Console - there are no jobs created.
PubSub and functions are good.

### Were you able to successfully deploy your functions?

Function was deployed, but with missing dependent functionality

**Comment by stari4ek** [comment]
it was `every 0 minutes` (incorrectly dynamically resolved from config)

**Comment by samtstern** [comment]
Ah ok so hopefully you fixed the schedule and this is not blocking you?  We
still definitely need to fix the false success message on our end too but
glad it's not preventing you from deploying something valid.

**Comment by stari4ek** [comment]
yep. it's easy to fix, when you know that is failing.
thx

**Comment by ngburke** [comment]
Just got off a discussion with a Firebase support person who pointed me here. There does still seem to be an issue with the checking here, in my case when specifying an incorrect time zone (omitted the underscore). When the scheduled function is deployed and the timezone is incorrect, instead of failing the deployment, the function is created without a scheduled job. Here is an example from my `index.ts` that will replicate the issue:

```
export const clearWatchedStatus =
  Functions.pubsub.schedule('0 20 * * *').timeZone('America/NewYork').onRun(Watch.clearWatchedStatus)
```

Note that when changing the timezone from the above to `America/New_York` everything works as expected and the scheduled job is created. I'm not blocked by this now that I have the timezone correct. It would be good to flag some type of error if this mistake is made so the developer can easily fix it on their own without having to potentially contact support.
