### ISSUE TITLE
odd log format on Travis

### ISSUE THREAD

**Issue by rolandjitsu** [firebase/firebase-tools#184]
When using `ft.deploy()` API I get a very odd log format on Travis:

<img width="1440" alt="screenshot 2016-07-13 11 31 41" src="https://cloud.githubusercontent.com/assets/1479737/16798678/93b0f0ca-48ed-11e6-82bc-be0f473ebd92.png">

Could the logging be turned off?

**Comment by mbleigh** [comment]
Try `ft.deploy({nonInteractive: true});` (assuming ft is the CLI instance)

**Comment by rolandjitsu** [comment]
@mbleigh I will give that a try when I'm back from holiday, thanks.

**Comment by rolandjitsu** [comment]
This is a very late reply, but the output looks like [this](https://travis-ci.org/rolandjitsu/angular-lab#L473) now. I used `--non-interactive` as CLI arg, see [deploy.sh#L7](https://github.com/rolandjitsu/angular-lab/blob/master/scripts/ci/deploy.sh#L7).
