### ISSUE TITLE
firebase 

### ISSUE THREAD

**Issue by chanez-web** [firebase/firebase-tools#1840]
### [REQUIRED] Environment info

**firebase-tools:**
not yet  install

**Platform:**

### [REQUIRED] Test case
i have  probleme whene it came to copy the database configuration from firebase and use it in may angular project 
 

### [REQUIRED] Expected behavior

my be there is in a other way to copy configuration of database  from firebase

**Comment by samtstern** [comment]
@chanez-web it doesn't look like this is a problem with the Firebase CLI.  If you have a general Firebase + Angular question try asking on StackOverflow!
