### ISSUE TITLE
Cannot destructure property `env_key` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by SeanDez** [firebase/firebase-tools#1845]
From https://github.com/firebase/firebase-tools/issues/1659

> to set the config value '''env.functionsPort''' to 8080, you would run firebase functions:config:set env.functionsPort=8080 -P you-project. Then, you can pull that config to use locally with the emulator using firebase functions:config:get > .runtimeconfig.json. Your variable will then be available at functions.config().env.functionsPort.

Firebase emulator is throwing an error when I try to destructure `functions.config().env`. What is my error below?

```
const firebaseFunctions = require('firebase-functions');

firebaseAdmin.initializeApp({
 credential: firebaseAdmin.credential.applicationDefault(),
 databaseURL: 'https://removed.firebaseio.com'
});

// TypeError: Cannot destructure property `shopify_api_key` of 'undefined' or 'null'.
const {shopify_api_key, shopify_api_secret, scopes, client_app_url, GOOGLE_APPLICATION_CREDENTIALS } = firebaseFunctions.config().env;
```

```
// Terminal
$ firebase functions:config:get
{
  "env": {
    "google_application_credentials": "removed/firebase-adminsdk-serviceAccount.json",
    "test": "val",
    "shopify_api_secret": "4d6d2670eremoved",
    "client_app_url": "https://us-central1-buyusedshopify.cloudfunctions.net/buyUsedServer",
    "shopify_api_key": "d030d96fb2removed",
    "scopes": "read_products,removed"
  }
}

```

**Comment by samtstern** [comment]
@SeanDez sorry for the late response you need to put those values in a `.runtimeconfig.json` file for them to be seen by the emulator:

```bash
# Run this inside your `functions` folder
firebase functions:config:get > .runtimeconfig.json
```
