### ISSUE TITLE
File index.js that is expected to define function doesn't exist

### ISSUE THREAD

**Issue by eng-dibo** [firebase/firebase-tools#1850]
running `firebase deploy` causes an error:
File ../dist/functions/index.js that is expected to define function doesn't exist.

- ../dist/functions/index.js is existing and not ignored by .gitignore
- package.json inside functions folder including the property "main": "../dist/functions/index.js"

```
>firebase deploy

=== Deploying to 'fixawy2'...

i  deploying storage, functions, hosting
i  firebase.storage: checking storage.rules for compilation errors...
+  firebase.storage: rules file storage.rules compiled successfully
i  functions: ensuring necessary APIs are enabled...
+  functions: all necessary APIs are enabled
i  storage: latest version of storage.rules already up to date, skipping upload.
..
i  functions: preparing functions directory for uploading...
i  functions: packaged functions (28.2 KB) for uploading
+  functions: functions folder uploaded successfully
i  hosting[fixawy2]: beginning deploy...
i  hosting[fixawy2]: found 11 files in dist/browser
+  hosting[fixawy2]: file upload complete
+  storage: released rules storage.rules to firebase.storage
i  functions: updating Node.js 8 function test(us-central1)...
!  functions[test(us-central1)]: Deployment error.
Function failed on loading user code. Error message: 
 File ../dist/functions/index.js that is expected to define function doesn't exist.


Functions deploy had errors with the following functions:
        test


To try redeploying those functions, run:
    firebase deploy --only functions:test


To continue deploying other features (such as database), run:
    firebase deploy --except functions

Error: Functions did not deploy properly.
```

removing the function test() from index.js causes that firebase cli asking me to delete it.

```
The following functions are found in your project but do not exist in your local
 source code:
        test(us-central1)

If you are renaming a function or changing its region, it is recommended that you create the new function first before deleting the old one to prevent event loss. 
For more info, visit https://firebase.google.com/docs/functions/manage-functions#modify

? Would you like to proceed with deletion? Selecting no will continue the rest of the deployments. (y/N)
```

**Comment by samtstern** [comment]
@eng-dibo can you show your `firebase.json` file?  I would like to see how you have configured your functions.  I am actually not sure if it's allowed to have a `main` file that's outside of the `functions` directory.  @bkendall do you know?

**Comment by eng-dibo** [comment]
firebase.json 
```
{
  "functions": {
    "predeploy": ""
  },
  "hosting": {
    "public": "dist/browser",
    "ignore": ["firebase.json", "**/.*", "**/node_modules/**"],
    "rewrites": [
      {
        "source": "**",
        "destination": "/index.html"
      }
    ]
  },
  "storage": {
    "rules": "storage.rules"
  }
}
```

**Comment by samtstern** [comment]
Ah ok.  So you have not configured `functions.source` in `firebase.json` which means by default we assume all of your source is located in the `functions` directory. This is what we upload when we deploy your Cloud Functions.  But your main file is *above* that folder in `../dist` so it's not able to be found when uploaded.

I would suggest reconfiguring your build so that the `dist` folder containing your Cloud Functions is inside the `functions` folder.

**Comment by eng-dibo** [comment]
adding functions.source:"../dist", caused an error:
```
Error: ../dist is outside of project directory
```

**Comment by samtstern** [comment]
@eng-dibo that's correct, I would really recommend just moving `dist` into the `functions` folder.

**Comment by eng-dibo** [comment]
I modified my comment, please read i.

**Comment by eng-dibo** [comment]
it is difficult to compile firebase into function/dist, I tried this method but faild, why?
because index.js require files from `dist` (such as express server and @angular/core), so I have to copy all this files each deploy time into functions/dist, and also I have to reinstall each dependency again in function dir.

**Comment by samtstern** [comment]
@eng-dibo I totally understand that these things are really tricky (especially when sharing dependencies), however there is nothing we can do in this repository because this is the correct behavior from `firebase-tools`.

I would suggest asking for help with your build setup on StackOverflow.

**Comment by eng-dibo** [comment]
I fixed it by setting public:'dist' instead of public:'dist/browser'

**Comment by samtstern** [comment]
@eng-dibo thanks for following up!
