### ISSUE TITLE
Error: listen EACCES: permission denied in a new Koa server

### ISSUE THREAD

**Issue by anskydev** [firebase/firebase-tools#1857]
### [REQUIRED] Environment info

**firebase-tools:** 7.9.0

**Platform:** Linux

### [REQUIRED] Test case

Hello, I'm trying to deploy a node-koa-graphql server to cloud functions, there isn't much documentation about this but I'm making my way through.

Using the command `firebase serve --only functions` the server outputs that it was successfully started, but when I hit the endpoint of the function an error occurs:

```
Server running on http://localhost:4000
functions: Beginning execution of "api"
>  events.js:174
>        throw er; // Unhandled 'error' event
>        ^
>
>  Error: listen EACCES: permission denied 0.0.0.0:80
>      at Server.setupListenHandle [as _listen2] (net.js:1263:19)
>      at listenInCluster (net.js:1328:12)
>      at Server.listen (net.js:1415:7)
```

This is my entry functions file (the one ran by firebase is the transpiled version):

```
import {
  https
} from 'firebase-functions'
import admin from 'firebase-admin'
import startServer from '../server'

admin.initializeApp()
const fireStore = admin.firestore()
const server = startServer(fireStore)

export const api = https.onRequest(server)
```

And this is my server function:

```
const startServer = (fireStore) => {
  const app = new Koa()
  const router = new KoaRouter()
  const PORT = process.env.PORT || 4000

  app.use(koaBody())

  router.post('/graphql', graphqlHTTP({
    schema,
    context: {
      fireStore
    }
  }))

  router.all(
    '/playground',
    koaPlayground({
      endpoint: '/graphql'
    })
  )

  app.use(router.routes())
  app.use(router.allowedMethods())

  app.listen(PORT, () => console.log(`Server running on http://localhost:${PORT}`))

  return app
}
```

my firebase config: 

```
{
  "firestore": {
    "rules": "firestore.rules",
    "indexes": "firestore.indexes.json"
  },
  "functions": {
    "source": "functions/dist"
  },
  "hosting": {
    "rewrites": [{
      "source": "/api",
      "function": "api"
    }],
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ]
  },
  "emulators": {
    "functions": {
      "port": 4000
    },
    "firestore": {
      "port": 8080
    }
  }
}
```

### [REQUIRED] Steps to reproduce

`firebase serve --only functions`

### [REQUIRED] Expected behavior

/api endpoint should expose graphql server

### [REQUIRED] Actual behavior

`Error: listen EACCES: permission denied 0.0.0.0:80`

I found a related [bug](https://github.com/firebase/firebase-tools/issues/1280) but downgrading to version 6.8.0 didn't help.

I appreciate the help and guidance, also thanks for this tool.

**Comment by bkendall** [comment]
I'm not sure I can help much (as this doesn't seem like an issue with the CLI directly), but if your internal server is listening to a port, that sounds like what is trying to bind to port 80. I'd look to see if you have `PORT` set in your environment?

**Comment by anskydev** [comment]
> I'm not sure I can help much (as this doesn't seem like an issue with the CLI directly), but if your internal server is listening to a port, that sounds like what is trying to bind to port 80. I'd look to see if you have `PORT` set in your environment?

Yeah, I spotted something is trying to use port 80, if I force the server to listen to another port I get this:

```
> npx firebase-tools serve                                                                        

=== Serving from '/home/ansky/Workspace/somos-api'...

✔  functions: Using node@10 from host.
✔  functions: Emulator started at http://localhost:5001
i  functions: Watching "/home/ansky/Workspace/somos-api/functions/dist" for Cloud Functions...
✔  hosting: Local server: http://localhost:5000
✔  functions[api]: http function initialized (http://localhost:5001/somos-api/us-central1/api).
>  Server running on http://localhost:4000
i  functions: Beginning execution of "api"
>  Server running on http://localhost:4000
⚠  functions: TypeError: func is not a function
at runFunction (/home/ansky/.npm/_npx/15175/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:621:20)
at /home/ansky/.npm/_npx/15175/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:596:19
at Generator.next (<anonymous>)
at /home/ansky/.npm/_npx/15175/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:7:71
at new Promise (<anonymous>)
at __awaiter (/home/ansky/.npm/_npx/15175/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:3:12)
at runFunction (/home/ansky/.npm/_npx/15175/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:593:12)
at /home/ansky/.npm/_npx/15175/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:620:15
at Generator.next (<anonymous>)
at /home/ansky/.npm/_npx/15175/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:7:71
⚠  Your function was killed because it raised an unhandled error.
```
Maybe now that does has to do with the cli?

**Comment by bkendall** [comment]
Does the line `functions: TypeError: func is not a function` print when it's starting up or when you make a call to one of the endpoints? That looks more like a typical javascript-like error to me...

**Comment by shpionka** [comment]
It's happening for me as well, when I'm trying to make a call to any of my endpoints.

**Comment by shpionka** [comment]
The reason was not exported function handler.

**Comment by anskydev** [comment]
Hello, sorry I broke my arm and haven't been able to investigate this until now.

This is what I got so far:

As @shpionka pointed out `runFunction` is expecting a param `func` to be a function, and is the one you send trough `onRequest`.

I don't know if this is documented (thats why I am leaving the issue open until feedback) but `onRequest` expects a function with the same structure as Express uses for its server: `function (req, res, next) {}` and that is what you get from calling `express()` but no from `new Koa()`.

Unfortunately I couldn't find a solution using Koa and switching to Express fixed everything, thanks for the help.

**Comment by anskydev** [comment]
This is where Koa is different:

https://github.com/koajs/koa/blob/master/docs/api/context.md

And a possible solution: 

> To bypass Koa's built-in response handling, you may explicitly set ctx.respond = false;. Use this if you want to write to the raw res object instead of letting Koa handle the response for you.

**Comment by samtstern** [comment]
@anskydev thanks for following up (and sorry to hear about your arm!).  Sounds like we should close this issue since Koa is not meeting the required function contract.  If you still need help, just let me know.
