### ISSUE TITLE
$ firebase login:ci has same effect as $ firebase login

### ISSUE THREAD

**Issue by steren** [firebase/firebase-tools#1863]
7.10.0

The output of `firebase login:ci` is the same as `firebase login`, asking me to open an URL with a redirect to a local server.

I would expect `login:ci` to not expect a redirect to a local server but to ask for a token

**Comment by mbleigh** [comment]
`firebase login:ci` is a login process that *generates* a token which can be used in CI environments. So once you go through the setup process, you'll end up with a token that can then be passed via `firebase <some_command> --token $THE_TOKEN`

**Comment by steren** [comment]
Ah got it.

**Comment by wilk** [comment]
Is there a way to make it automatic without using a web browser to login?
I mean, this procedure requires once a while to refresh manually the token: if you don't remember to do it, your CD/CI will break eventually.

**Comment by mbleigh** [comment]
Refresh tokens don't expire unless they are evicted by having too many new ones (I think the number is ~25 but don't recall for sure). If you are regularly generating lots of refresh tokens on your account, that might be a security concern.

Another way to authenticate is with Service Accounts -- if you provide a service account key and set `GOOGLE_APPLICATION_CREDENTIALS` environment variable to point to it, you will be able to authorize the CLI that way, and it has an added bonus of only having permissions on the specific project.

**Comment by progvb** [comment]
@mbleigh 
> Another way to authenticate is with Service Accounts -- if you provide a service account key and set `GOOGLE_APPLICATION_CREDENTIALS` environment variable to point to it, you will be able to authorize the CLI that way, and it has an added bonus of only having permissions on the specific project.

This approach doesn't seem to work on my machine. I'm getting:
`Error: Command requires authentication, please run firebase login`

Could you point me to the documentation about how to use `GOOGLE_APPLICATION_CREDENTIALS` to deploy to Firebase?

**Comment by mbleigh** [comment]
@progvb we use this pattern: https://cloud.google.com/docs/authentication/production#finding_credentials_automatically

If you set it up and try to run a command with `--debug` it should print out some information about what it did and didn't detect credentials-wise.
