### ISSUE TITLE
firebase tool not working for me

### ISSUE THREAD

**Issue by vnathalye** [firebase/firebase-tools#188]
I'm trying to use firebase CLI tool. I installed it using 
`npm install -g firebase-tools` 
It completed without any error.

Then I tried running following commands. But for any of the commands it did not give any output nor did it give any error. Not sure what is the problem.

`firebase login`
`firebase init`
`firebase deploy`

`firebase serve`

Not sure what is the problem. Is there any log that I can check?

**Comment by lovebdsobuj** [comment]
Just command `firebase` or `firebase -h, --help`

Your CMD screen must say something.

**Comment by vnathalye** [comment]
@lovebdsobuj Thanks for responding.

I'm not sure what was the issue. But that day it was not giving any output / error what so ever. After couple of days when I tried executing `firebase serve` again, it was working fine.
I forgot to update it here.  Now I'll close this issue.
