### ISSUE TITLE
angular firebase:Deployment error.

### ISSUE THREAD

**Issue by sukrit786** [firebase/firebase-tools#1882]
PS C:\Sukrit's Workspace\me> firebase deploy

=== Deploying to 'automatic-opus-254806'...

i  deploying firestore, functions, hosting
Running command: npm --prefix "$RESOURCE_DIR" run lint

> functions@ lint C:\Sukrit's Workspace\me\functions
> tslint --project tsconfig.json

Running command: npm --prefix "$RESOURCE_DIR" run build

> functions@ build C:\Sukrit's Workspace\me\functions
> node cp-angular && tsc

+  functions: Finished running predeploy script.
i  firestore: reading indexes from firestore.indexes.json...
i  cloud.firestore: checking firestore.rules for compilation errors...
+  cloud.firestore: rules file firestore.rules compiled successfully
i  functions: ensuring necessary APIs are enabled...
+  functions: all necessary APIs are enabled
i  firestore: latest version of firestore.rules already up to date, skipping upload...
+  firestore: deployed indexes in firestore.indexes.json successfully
i  functions: preparing functions directory for uploading...
i  functions: packaged functions (43.18 MB) for uploading
+  functions: functions folder uploaded successfully
i  hosting[automatic-opus-254806]: beginning deploy...
i  hosting[automatic-opus-254806]: found 195 files in dist/browser
+  hosting[automatic-opus-254806]: file upload complete
+  firestore: released rules firestore.rules to cloud.firestore
i  functions: updating Node.js 8 function ssr(us-central1)...
!  functions[ssr(us-central1)]: Deployment error.
Function failed on loading user code. Error message: Code in file lib/index.js can't be loaded.
Did you list all required modules in the package.json dependencies?
Detailed stack trace: Error: Cannot find module '@angular/core'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.vOrQ (/srv/dist/server/main.js:3153:18)
    at __webpack_require__ (/srv/dist/server/main.js:20:30)
    at Object.V7fC (/srv/dist/server/main.js:1451:12)
    at __webpack_require__ (/srv/dist/server/main.js:20:30)
    at Object.K011 (/srv/dist/server/main.js:938:37)
    at __webpack_require__ (/srv/dist/server/main.js:20:30)

Functions deploy had errors with the following functions:
        ssr

To try redeploying those functions, run:
    firebase deploy --only functions:ssr

To continue deploying other features (such as database), run:
    firebase deploy --except functions

Error: Functions did not deploy properly.

### [REQUIRED] Environment info

**firebase-tools:**

**Platform:**

**Comment by sukrit786** [comment]
PS C:\Sukrit's Workspace\me> firebase deploy

=== Deploying to 'automatic-opus-254806'...

i  deploying firestore, functions, hosting
Running command: npm --prefix "$RESOURCE_DIR" run lint

> functions@ lint C:\Sukrit's Workspace\me\functions
> tslint --project tsconfig.json

Running command: npm --prefix "$RESOURCE_DIR" run build

> functions@ build C:\Sukrit's Workspace\me\functions
> node cp-angular && tsc

+  functions: Finished running predeploy script.
i  firestore: reading indexes from firestore.indexes.json...
i  cloud.firestore: checking firestore.rules for compilation errors...
+  cloud.firestore: rules file firestore.rules compiled successfully
i  functions: ensuring necessary APIs are enabled...
+  functions: all necessary APIs are enabled
i  firestore: latest version of firestore.rules already up to date, skipping upload...
+  firestore: deployed indexes in firestore.indexes.json successfully
i  functions: preparing functions directory for uploading...
i  functions: packaged functions (43.18 MB) for uploading
+  functions: functions folder uploaded successfully
i  hosting[automatic-opus-254806]: beginning deploy...
i  hosting[automatic-opus-254806]: found 195 files in dist/browser
+  hosting[automatic-opus-254806]: file upload complete
+  firestore: released rules firestore.rules to cloud.firestore
i  functions: updating Node.js 8 function ssr(us-central1)...
!  functions[ssr(us-central1)]: Deployment error.
Function failed on loading user code. Error message: Code in file lib/index.js can't be loaded.
Did you list all required modules in the package.json dependencies?
Detailed stack trace: Error: Cannot find module '@angular/core'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.vOrQ (/srv/dist/server/main.js:3153:18)
    at __webpack_require__ (/srv/dist/server/main.js:20:30)
    at Object.V7fC (/srv/dist/server/main.js:1451:12)
    at __webpack_require__ (/srv/dist/server/main.js:20:30)
    at Object.K011 (/srv/dist/server/main.js:938:37)
    at __webpack_require__ (/srv/dist/server/main.js:20:30)


Functions deploy had errors with the following functions:
        ssr


To try redeploying those functions, run:
    firebase deploy --only functions:ssr


To continue deploying other features (such as database), run:
    firebase deploy --except functions

Error: Functions did not deploy properly.

**Comment by samtstern** [comment]
@sukrit786 sorry for the late response, many of us were out for the holidays.

Looks like this is the key issue:
```
Function failed on loading user code. Error message: Code in file lib/index.js can't be loaded.
Did you list all required modules in the package.json dependencies?
Detailed stack trace: Error: Cannot find module '@angular/core'
```

Can you show your `package.json` file and your `firebase.json` file?

**Comment by sukrit786** [comment]
this is the new error am facing am able to deploy with success but firebase functions are not loading,
when i do firebase serve i face this error
functions: Beginning execution of "ssr"
>  ERROR { Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'rs-emicon-fn/us-central1/ssr'
>  Error: Cannot match any routes. URL Segment: 'rs-emicon-fn/us-central1/ssr'

**Comment by sukrit786** [comment]
package.json

`{
  "name": "universal-app",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "compile:server": "webpack --config webpack.server.config.js --progress --colors",
    "serve:ssr": "node dist/server",
    "build:ssr": "npm run build:client-and-server-bundles && npm run compile:server",
    "build:client-and-server-bundles": "ng build --prod && ng run universal-app:server:production --bundleDependencies all"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~8.2.14",
    "@angular/common": "~8.2.14",
    "@angular/compiler": "~8.2.14",
    "@angular/core": "~8.2.14",
    "@angular/fire": "^5.2.3",
    "@angular/forms": "~8.2.14",
    "@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/platform-server": "~8.2.14",
    "@angular/router": "~8.2.14",
    "@nguniversal/express-engine": "^8.2.6",
    "@nguniversal/module-map-ngfactory-loader": "v8.2.6",
    "animate.css": "^3.7.2",
    "bootstrap": "4.1.1",
    "cors": "^2.8.5",
    "express": "^4.15.2",
    "firebase": "^7.6.1",
    "ngx-bootstrap": "^5.2.0",
    "ngx-owl-carousel": "^2.0.7",
    "ngx-wow": "^2.0.1",
    "owl-carousel": "^1.0.0",
    "rxjs": "~6.4.0",
    "script-loader": "^0.7.2",
    "tslib": "^1.10.0",
    "wowjs": "^1.1.3",
    "ws": "^7.2.1",
    "xhr2": "^0.2.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.803.21",
    "@angular/cli": "~8.3.21",
    "@angular/compiler-cli": "~8.2.14",
    "@angular/language-service": "~8.2.14",
    "@types/express": "^4.17.0",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-loader": "^5.2.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.5.3",
    "webpack-cli": "^3.1.0"
  }
}
`
firebase.json
`{
  "functions": {
    "predeploy": [
      "npm --prefix \"$RESOURCE_DIR\" run lint",
      "npm --prefix \"$RESOURCE_DIR\" run build"
    ]
  },
  "hosting": {
    "public": "dist/browser",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "rewrites": [
      {
        "source": "**",
        "function": "ssr"
      }
    ]
  }
}
`

**Comment by sukrit786** [comment]
Github Repo: https://github.com/sukrit786/Repro-app

**Comment by samtstern** [comment]
@sukrit786 if you look inside `functions` these are all the dependencies you declare for your Cloud Functions:
https://github.com/sukrit786/Repro-app/blob/ec8b422fef01dc4466f08674cfa16e63c8b215d7/functions/package.json#L16-L19

However based on this error message, you're trying to bring in `@angular/core`:
```
Detailed stack trace: Error: Cannot find module '@angular/core'
```

I think this is an issue with how you're using Angular and Webpack, not an issue with Firebase or the Firebase CLI.  I would suggest moving your question to StackOverflow or another more general forum.
