### ISSUE TITLE
No way to silence hosting emulator logging, even with --json

### ISSUE THREAD

**Issue by filipesilva** [firebase/firebase-tools#1887]
Heya 👋 

I'm trying to use the emulator in a e2e environments and find the hosting emulator to log a lot of messages, making reading the CI logs hard.

I thought the `--json` flag might make it quiet since it suppresses all other logging, but that doesn't seem to be the case. If there's a better way to suppress the output I'm happy to use that instead!

### [REQUIRED] Environment info

**firebase-tools:** 7.11.0

**Platform:** Windows 10

### [REQUIRED] Test case

```
git clone https://github.com/filipesilva/firebase-emulator-test
cd firebase-emulator-test
```

### [REQUIRED] Steps to reproduce

```
yarn firebase emulators:start --json
```
Then open http://localhost:5000/

### [REQUIRED] Expected behavior

No logging from the hosting server.

### [REQUIRED] Actual behavior

The hosting server will still print logging messages:
```
kamik@RED-X1C6 MINGW64 /d/sandbox/firebase-emulator (master)
$ yarn firebase emulators:start --json
yarn run v1.17.3
$ D:\sandbox\firebase-emulator\node_modules\.bin\firebase emulators:start --json
127.0.0.1 - - [30/Dec/2019:14:30:20 +0000] "GET / HTTP/1.1" 200 4380 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safa
ri/537.36"
127.0.0.1 - - [30/Dec/2019:14:30:21 +0000] "GET /favicon.ico HTTP/1.1" 404 150 "http://localhost:5000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like 
Gecko) Chrome/79.0.3945.88 Safari/537.36"
```

**Comment by samtstern** [comment]
@filipesilva thanks for the feedback!  This looks like the same feature request as #1839 so I am going to close this one as a duplicate and we can keep discussing there.
