### ISSUE TITLE
[object Object] is not a Firebase command

### ISSUE THREAD

**Issue by timofeysie** [firebase/firebase-tools#1889]
### [REQUIRED] Environment info

**firebase-tools:**
[debug] [2019-12-29T20:25:09.572Z] Command:       /Users/tim/.nvm/versions/node/v12.9.1/bin/node /Users/tim/.nvm/versions/node/v12.9.1/bin/firebase deply
[debug] [2019-12-29T20:25:09.572Z] CLI Version:   7.11.0
[debug] [2019-12-29T20:25:09.572Z] Platform:      darwin
[debug] [2019-12-29T20:25:09.572Z] Node Version:  v12.9.1
[debug] [2019-12-29T20:25:09.741Z] Time:          Mon Dec 30 2019 07:25:09 GMT+1100 (Australian Eastern Daylight Time)

**Platform:**
Windows

### [REQUIRED] Test case
Deploy the master branch from this repo with the firebase deply commande:
https://github.com/timofeysie/khip

### [REQUIRED] Steps to reproduce
Deploy the master branch from this repo with the firebase deply commande:
https://github.com/timofeysie/khip

### [REQUIRED] Expected behavior
Site is deployed and hosted with no errors.

### [REQUIRED] Actual behavior
Error: [object Object] is not a Firebase command

Please see the firebase-debug.log from the linked project:
https://github.com/timofeysie/khipu/blob/master/firebase-debug.log

**Comment by samtstern** [comment]
@timofeysie looks like you're running `firebase deply` but you need to be running `firebase deploy` (note the missing "o").  That said I will leave this open because our error message for a misspelling is very bad:

```
$ firebase deply
Error: [object Object] is not a Firebase command

Error: An unexpected error has occurred.
```

**Comment by timofeysie** [comment]
Thanks @samtstern , I'm glad my typo can help others have a better experience with Firebase!
