### ISSUE TITLE
Firestore functions emulator does not work with @firebase/testing

### ISSUE THREAD

**Issue by uadarsh** [firebase/firebase-tools#1926]
### [REQUIRED] Environment info

**firebase-tools:**
7.9.0

**Platform:**
macOS
### [REQUIRED] Test case

```js
// This is an integration test.
const firebasetesting = require("@firebase/testing");
const rules = `service cloud.firestore {
    match /{anypath=**} {
      allow write: if true;
      allow read: if true;
    }
}`;
let firebase;
const projectId = "dummy";

beforeEach(async () => {
  firebase = await firebasetesting.initializeTestApp({
    databaseName: "dummydatabase",
    projectId
  });
  await firebasetesting.loadFirestoreRules({
    projectId,
    rules: rules
  });
  firebase.functions().useFunctionsEmulator("http://localhost:5001"); // Ideally this line should not be required.
});

it("Functions integration test", async () => {
  await firebase
    .firestore()
    .doc("collection/path")
    .set({ val: 1 }); // Writes to firestore.
  const fn = firebase.functions().httpsCallable("someFunction");
  await fn({});
});

```

### [REQUIRED] Steps to reproduce

* Start the emulator with some definition of "someFunction" 
    firebase emulators:start --only firestore,functions
* Run the test with jest (assuming, dependencies are installed through npm)
   npm run test

### [REQUIRED] Expected behavior

Firestore write should go to emulator db.
Functions call should go to emulator functions.

### [REQUIRED] Actual behavior

Firestore writes go to emulator.
However functions call throws an error -

   internal

      at new HttpsErrorImpl (node_modules/@firebase/testing/node_modules/@firebase/functions/src/api/error.ts:66:5)
      at _errorForResponse (node_modules/@firebase/testing/node_modules/@firebase/functions/src/api/error.ts:175:10)
      at Service.<anonymous> (node_modules/@firebase/testing/node_modules/@firebase/functions/src/api/service.ts:226:19)
      at step (node_modules/tslib/tslib.js:136:27)
      at Object.next (node_modules/tslib/tslib.js:117:57)
      at fulfilled (node_modules/tslib/tslib.js:107:62)

It seems like the emulator expects the projectId to be an existing real project.

**Comment by samtstern** [comment]
@uadarsh could you try using this command:

```
firebase emulators:exec "npm run jest"
```

That will do the following:
  * Start the emulators
  * Create a subprocess with `FIRESTORE_EMULATOR_HOST` set (which `@firebase/testing` will detect)
  * Run `npm run jest` in that subprocess
  * Wait for your tests to finish
  * Exit the emulators

**Comment by uadarsh** [comment]
@samtstern I have tried that but it did not help. The issue is not finding the correct host/port to connect to. If I change the projectId to a real projectId, then the function calls go to the emulator. So even with a dummy projectId the connection must have been made but the emulator seems to be ignoring the calls.

**Comment by samtstern** [comment]
@uadarsh functions can't be called with a random project ID (unlike the Firestore emulator).  When you start the functions emulator it emulates all the functions in a single project.  Then it assigns them a URL like this:

```
http://localhost:5001/{PROJECT}/us-central1/{FUNCTION_NAME}
```

So if you wanted `dummy` to work you'd have to do:
```
$ firebase --project=dummy emulators:start
```

**Comment by uadarsh** [comment]
@samtstern  Please consider this as a feature request then. Setting a fixed projectid defeats the purpose of the projectid being dummy.  Without this constraint, one could use the emulators for integration-testing where you may have more than one test isolated from each other.

**Comment by samtstern** [comment]
@uadarsh how would you expect it to work?  If you send a request to `/dummy/us-central1/functionName` should it run the function as if it was part of project `dummy`?  Should it accept anything at all for the projectId?

Emulating multiple DBs is easy because we can just assume they're all empty with no rules set, but emulating multiple functions projects is a different beast and has many more edge cases.
