### ISSUE TITLE
MacOS 7.12.1 - Port XXXX is not open, could not start functions emulator

### ISSUE THREAD

**Issue by TomKaltz** [firebase/firebase-tools#1935]
### [REQUIRED] Environment info

**firebase-tools: 7.12.1**

**Platform:macOS 10.15.2 Catalina**

### [REQUIRED] Test case

Run ```emulators:start --only functions``` on above environment

### [REQUIRED] Steps to reproduce

Run ```emulators:start --only functions```

### [REQUIRED] Expected behavior

Expected the emulator to start on port 5001.

### [REQUIRED] Actual behavior
Emulator does not start
```Thomas$ firebase emulators:start --only functions
i  emulators: Starting emulators: functions
i  Shutting down emulators.
⚠  Port 5001 is not open, could not start functions emulator.
i  To select a different port for the emulator, update your "firebase.json":
    {
      // ...
      "emulators": {
        "functions": {
          "port": "PORT"
        }
      }
    }
i  Shutting down emulators.

Error: Could not start functions emulator, port taken.

**Comment by samtstern** [comment]
@TomKaltz what happens if you try to see what's running on 5001:
```
curl -v localhost:5001
```

**Comment by TomKaltz** [comment]
@samtstern interesting....

```Thomas$ curl -v localhost:5001
* Could not resolve host: localhost
* Closing connection 0
curl: (6) Could not resolve host: localhost```

**Comment by samtstern** [comment]
@TomKaltz do things work better if you modify your `firebase.json` to set the emulators host to `0.0.0.0` like this:

```js
{
  // .. other stuff ...
  "emulators": {
    "functions": {
      "host": "0.0.0.0",
      "port": 5001
     }
  }
}
```

**Comment by TomKaltz** [comment]
@samtstern your fix worked!

**Comment by davidko604** [comment]
Also encountered the same issue.  In my terminal I first ran below command to see a list of processes running that that port.

> sudo lsof -i :5001

I then ran below command to kill the process by PID #.

> sudo kill -9 PID#

Will try the adjusting the host as above to potentially avoid this issue in the future.
