### ISSUE TITLE
3.0.5 Cant Deploy

### ISSUE THREAD

**Issue by neilcampbell** [firebase/firebase-tools#194]
Hi,
I just updated the firebase tools to 3.0.5 from 3.0.4 and I am now unable to deploy via `node ./node_modules/firebase-tools/bin/firebase deploy --token {FIREBASE_TOKEN}`. The following message is returned in the console.

> Error: HTTP Error: 400, hosting.version must be a valid deployed version

I have rolled back to 3.0.4 and everything is fine again, so it appears to be an issue with the latest update.

**Comment by mbleigh** [comment]
Can you run with `--debug` and paste the results here? Feel free to remove any identifying info.

**Comment by neilcampbell** [comment]
Sure can @mbleigh.
See https://gist.github.com/neilcampbell/d44b476357f264ab095f393356242991

All the auth stuff looks to be fine, so have not included that in the logs. {sitename} is the removed project name.

**Comment by mbleigh** [comment]
Ah, I see the issue. You'll need to make your `rules.json` file have a `rules` key:

```
{
  "rules": {
    ".read": true,
    ".write": true
  }
}
```

This wasn't the case in `3.0.4` (with or without were both acceptable). That should unblock you, but I'll keep this open as a tracking bug for handling that better.

**Comment by mbleigh** [comment]
@laurenzlong in previous versions of the CLI it was acceptable to have a rules file with no outer "rules" key -- now that we're passing it as a string, those are erroring. My suggestion is that we ought to go ahead and parse the rules string as JSON and simply error out with a friendly error message:

```
Error: <DATABASE_RULES_FILE> must have an outer "rules" key, for example:

{
  "rules": {".read": false, ".write": false}
}
```

**Comment by laurenzlong** [comment]
Okay sounds good @mbleigh

**Comment by mbleigh** [comment]
Clarification: parse the JSON just for validation, still send the string for the actual deploy.

**Comment by neilcampbell** [comment]
Thanks for your help @mbleigh.

Just to confirm in the main firebase.json
```json
{ 
  "database": {
    "rules": "database.rules.json"
  }
}
```
Then in database.rules.json
```json
{
  "rules": {
    ".read": false,
    ".write": false
  }
}
```

OR 

In main firebase.json
```json
{ 
  "database":  "database.rules.json"
}
```
Then in database.rules.json (which I would change to database.json)
```json
{
  "rules": {
    ".read": false,
    ".write": false
  }
}
```

The first option feels a little strange as the rules key is duplicated.

**Comment by mbleigh** [comment]
The first one is correct. Rules key is duplicated because the Database
rules schema requires the "rules" top-level key and we are now trying to
preserve formatting of your file (to keep comments etc).

**Comment by neilcampbell** [comment]
Ok cool thanks @mbleigh and @laurenzlong
