### ISSUE TITLE
Standalone CLI tools always run in an interactive mode ignoring options

### ISSUE THREAD

**Issue by radikpsb** [firebase/firebase-tools#1946]
### [REQUIRED] Environment info

**firebase-tools:** 7.12.1

**Platform:** Windows 10

### [REQUIRED] Test case
./firebase-tools-instant-win.exe login:ci --no-localhost

### [REQUIRED] Steps to reproduce
1. Download firebase-tools-instant-win.exe from releases page https://github.com/firebase/firebase-tools/releases
2. Run the above command from the PowerShell.

### [REQUIRED] Expected behavior
firebase-tools-instant-win.exe respects parameters passed to it. E.g. logins for CI with --no-localhost key.

### [REQUIRED] Actual behavior
firebase-tools-instant-win.exe doesn't respect parameters passed to it. E.g. logins as I called firebase with just "login" param.

**Comment by abeisgoat** [comment]
The instant build is not designed to be invoked from Powershell, try the `firebase-tools-win.exe` and reopen this if it's still happening.
