### ISSUE TITLE
Firebase hosting deploy out of memory

### ISSUE THREAD

**Issue by frederiksen** [firebase/firebase-tools#1952]
### Environment info

**firebase-tools:**

Windows

### Test case

Execute firebase deploy
In public folder there are ~ 3.500.000 files

In public folder there are ~3.500.000 files

Web site is deployed

`<--- Last few GCs --->

[4384:00000176A5F8F420]   252479 ms: Scavenge 1395.0 (1419.9) -> 1394.1 (1420.4) MB, 2.5 / 0.0 ms  (average mu = 0.160, current mu = 0.110) allocation failure
[4384:00000176A5F8F420]   252496 ms: Scavenge 1395.0 (1420.4) -> 1394.2 (1420.9) MB, 2.3 / 0.0 ms  (average mu = 0.160, current mu = 0.110) allocation failure
[4384:00000176A5F8F420]   252512 ms: Scavenge 1395.1 (1420.9) -> 1394.2 (1421.4) MB, 2.4 / 0.0 ms  (average mu = 0.160, current mu = 0.110) allocation failure

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0000039FEB05C5C1]
    1: StubFrame [pc: 0000039FEB05D970]
Security context: 0x00e29aa9e6e9 <JSObject>
    2: resolve [0000014C84082AC1] [path.js:~133] [pc=0000039FEB239762](this=0x027c724824a1 <Object map = 0000038CE42387B1>)
    3: arguments adaptor frame: 2->0
    4: mark [000000B7EFF494D9] [C:\Users\mrtnf\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\glob\common.js:~179] [pc=0000039FEB26E868](this=0...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF6883CC6AA v8::internal::GCIdleTimeHandler::GCIdleTimeHandler+4506
 2: 00007FF6883A7416 node::MakeCallback+4534
 3: 00007FF6883A7D90 node_module_register+2032
 4: 00007FF6886C189E v8::internal::FatalProcessOutOfMemory+846
 5: 00007FF6886C17CF v8::internal::FatalProcessOutOfMemory+639
 6: 00007FF6888A7F94 v8::internal::Heap::MaxHeapGrowingFactor+9620
 7: 00007FF68889EF76 v8::internal::ScavengeJob::operator=+24550
 8: 00007FF68889D5CC v8::internal::ScavengeJob::operator=+17980
 9: 00007FF6888A6317 v8::internal::Heap::MaxHeapGrowingFactor+2327
10: 00007FF6888A6396 v8::internal::Heap::MaxHeapGrowingFactor+2454
11: 00007FF6889D0637 v8::internal::Factory::NewFillerObject+55
12: 00007FF688A4D826 v8::internal::operator<<+73494
13: 0000039FEB05C5C1`

**Comment by mbleigh** [comment]
It is going to be extremely difficult to deploy 3.5M files to Firebase Hosting -- Firebase Hosting is optimized for web sites and applications and the CLI is built with this in mind. In this case, it looks like your computer is running out of memory from the `glob` library trying to create an array of all of the files to be deployed.

You're probably better off using something like Cloud Storage for Firebase to store millions of files, but if you do want to proceed you will likely need to build a toolchain for yourself using the [Firebase Hosting REST API](https://firebase.google.com/docs/hosting/api-deploy).
