### ISSUE TITLE
[distribution] Requested entity was not found

### ISSUE THREAD

**Issue by xalikoutis** [firebase/firebase-tools#1963]
### [REQUIRED] Environment info

**firebase-tools:**7.12.1

**Platform:**macOS

### [REQUIRED] Test case

When i try to upload my ipa using a specific appid i get an error although the appid exists
I run the following command
`firebase appdistribution:distribute --app "1:696982949839:ios:c587f53961ad2c1df64cba" --release-notes 'test 1' --testers 'me@gmail.com' Runner.ipa --debug`
and i get
`Error: App Distribution could not find your app 1:696982949839:ios:c587f53961ad2c1df64cba. Make sure to onboard your app by pressing the "Get started" button on the App Distribution page in the Firebase console: https://console.firebase.google.com/project/_/appdistribution`

### [REQUIRED] Steps to reproduce

As you can see i run a `firebase apps:list` and i get my 2 apps. Then i run `firebase appdistribution:distribute` with the exactly same appid for my ios app and i get the error. The android app uploads just fine.
![image](https://user-images.githubusercontent.com/847472/74032712-58760e80-49bd-11ea-846a-00f27a178ce9.png)

### [REQUIRED] Expected behavior

ipa should be uploaded to the firebase distribution

### [REQUIRED] Actual behavior

ipa should isn't uploaded to the firebase distribution and i get errors
[firebase-debug.log](https://github.com/firebase/firebase-tools/files/4170996/firebase-debug.log)

**Comment by mbleigh** [comment]
Did you follow the instructions in the error message? App Distribution must
be enabled before you can use the cli to upload builds.

**Comment by xalikoutis** [comment]
lots hours of continues working, so obvious

**Comment by ChristopherDrum** [comment]
@mbleigh Is there a CLI way to enable App Distribution?
Reading the docs for Firebase CLI it uses CLI for all steps *except* this one GUI button we have to click in the console to enable distribution. I'm trying to automate a prototyping workflow for my developers, and this step is hanging me up. Maybe Fastlane can upload and enable distribution? Not sure, but Fastlane is too heavy for what little I need to do (i.e. upload a single .ipa file). Fabric was relatively simple; as long as the app was launched and the bundle identifier registered with Fabric, an .ipa could be uploaded. Firebase lets me register the bundle ID programmatically, and upload programmatically, but this one in-between step (which seems kind of unnecessary to me) cannot be automated?

**Comment by xalikoutis** [comment]
Same for me i have a pipeline that using fastlane and bash commands that automates the builds, signing and distribution for every new app.

So there are 2-3 stoppers here
1. Enable distribution
2. Register SHA certificate for android
3. upload notifications certificates for IOS
4. connect google analytics

**Comment by Sega-Zero** [comment]
@alexsinger is there any way to automate enabling of App Distribution for now?

**Comment by alexsinger** [comment]
@Sega-Zero not yet

**Comment by jgreen210** [comment]
I also had this:

{"error":{"code":404,"message":"Requested entity was not found.","status":"NOT_FOUND"}}

...error from the firebase CLI when it was GETing the details of the appID. 

The: 

Make sure to onboard your app by pressing the "Get started" button on the App Distribution page in the Firebase console: https://console.firebase.google.com/project/_/appdistribution 

...message was confusing since I didn't have this button to press (I pressed it a while ago).

It turns out I got the error since I was using minimal "Advanced" permissions for the user doing the uploading, and I hadn't given it the "Firebase App Distribution Viewer" permission.

Could the CLI distinguish this situation from the not pressed "Get started" situation, and give a more specific error message? It looks like this might need extra support from the API.

**Comment by feharaujo** [comment]
For those that are facing this problem, a reminder: **You need to press the "Get started" button twice** (once for android and another time for iOS). I've spent a lot of time investigating this problem (because I did once for one platform) and figure out that I needed to do again for the other one ... terrible "UX" and for sure it needs improvements to avoid such silly error

**Comment by igtm** [comment]
@feharaujo
You're a lifesaver! I fell into the same pitfall.

**Comment by danielgomezrico** [comment]
@feharaujo I lived the same issue.

I have 2 apps with different packages inside of the same firebase project (two different flavours of the same app) and I lost a lot of time finding that theres a switch lust after `App Distribution` title where you change the registered apps and I needed to "accept" for each one.

**Comment by adrianestran** [comment]
I'm stuck on this same issue, and I'm sure I've clicked the "Get Started" button. I have an Android app that is configured and working, and I've added a new app with a different package ID. 

I'm using the CLI:

`firebase appdistribution:distribute "exampleApp-debug.apk" --app "1:XXXXX:android:XXXXX" --groups "all-testers" --debug`

Result:

`App Distribution could not find your app 1:XXXXX:android:XXXXX. Make sure to onboard your app by pressing the "Get started" button on the App Distribution page in the Firebase console: https://console.firebase.google.com/project/_/appdistribution`

This is really infuriating. What else might I be doing wrong here?

**Comment by logemann** [comment]
same error for me as @adrianestran posted. Dont have any clue....

**Comment by norealityagent** [comment]
Hey @logemann, just making sure, have you clicked the Console Get Started button for **every** app you want to test?
If you have, and it's still not working, I'd recommend you create a Firebase support ticket where you can share your actual app ID privately to debug in more depth. 

(@adrianestran as well, on the off chance you're still blocked?)

**Comment by turkcankeskin** [comment]
> For those that are facing this problem, a reminder: **You need to press the "Get started" button twice** (once for android and another time for iOS). I've spent a lot of time investigating this problem (because I did once for one platform) and figure out that I needed to do again for the other one ... terrible "UX" and for sure it needs improvements to avoid such silly error

The year is 2024 and your comment still works, thank you for your answer.

**Comment by alexsinger** [comment]
> [@alexsinger](https://github.com/alexsinger) - hi, it's been 4 years now, can we finally programmatically enable App Distribution?

I've shared with the team but no updates on this to share right now.

**Comment by Mako-L** [comment]
Thank you for all the comments guys! You are awesome.
