### ISSUE TITLE
Work with npm i -D

### ISSUE THREAD

**Issue by KimuraYu45z** [firebase/firebase-tools#1964]
It is inconvenient to do `npm i -g firebase-tools` in CI environment.
`npm i -D firebase-tools` should have to make the command `firebase` availavle.
If it does, we can do `firebase deploy` in CI environment only with writing `firebase-tools` in `devDependencies` in `package.json`.

**Comment by samtstern** [comment]
@KimuraYu45z as far as I understand this should work:

```
npm i -D firebase-tools
npx firebase deploy
```

Can you let me know if that works for you?
