### ISSUE TITLE
[Question] Update push notification certificate

### ISSUE THREAD

**Issue by bguidolim** [firebase/firebase-tools#1965]
Hi! I would like to know if is it possible to update push notification certificates for an existing app on Firebase using CLI tools.

**Comment by samtstern** [comment]
@bguidolim I assume you're talking about an APNS certificate?  Sorry that's not something you can do from the CLI.

**Comment by bguidolim** [comment]
Any plans to add it in the near future?

**Comment by samtstern** [comment]
@bguidolim no we don't have any current plans for this as it's not a feature request I've heard before.  Could you explain a little more about when you need to do this and how often it comes up?

**Comment by bguidolim** [comment]
Sure! We have some apps on our CI chain, and we use Fastlane to build and configure those apps. We are not able to use the Authentication Key, so we use the APNS certificates, which has expiration date.

With Fastlane we are able to generate new certificates when it is about to expire and then upload the new certificates to somewhere. Would be great if I can upload the new certificates to the Firebase app via CLI or REST API, but AFAIK it’s not possible now.

Some other platforms, like OneSignal, allows this kind of request on their API.

**Comment by samtstern** [comment]
@bguidolim thanks!  Since that's a relatively infrequent use case I don't see us adding it to the CLI but it does seem like a good candidate for the Firebase Management API (which you can access via REST).

To voice your support for adding that feature to the REST API, please file a feature request here:
https://firebase.google.com/support

Sorry to make you repeat yourself in a new form but it helps to when a "real developer" files a feature request versus if I did it on your behalf.

**Comment by xalikoutis** [comment]
Hi @bguidolim any news, cause it is a stopper for my CI pipeline

**Comment by bguidolim** [comment]
@xalikoutis no response until now. For now, my CI is uploading the new certs to a bucket and sending a notification to the team, so manually we update the projects.

**Comment by xalikoutis** [comment]
OMG...I ll create an selenium scrap bot to aytomate login, navigate and upload the APNs

**Comment by bguidolim** [comment]
@xalikoutis hehehe, good luck :)

**Comment by yacineblr** [comment]
Any news about this feature ?

**Comment by xalikoutis** [comment]
2025 up

**Comment by caio-pellegrini** [comment]
Hello everyone. Bumping this in late 2025, as it's still a critical blocker for automated CI/CD.

For teams like mine managing white-label apps at scale, the manual APNs .p8 upload is the only part of our new-app provisioning that cannot be scripted.

As the Firebase team is now tracking feature requests on their official support page, I've found the request for this feature here:

https://firebase.uservoice.com/forums/948424-general/suggestions/46562308-api-to-upload-apns-credentials

For everyone who finds this issue (including @bguidolim, @xalikoutis, @yacineblr, @kopino4), please add your vote and use case to that official page. Consolidating our feedback there is the best way to get this prioritized.
