### ISSUE TITLE
Question: Managing CI Login Tokens

### ISSUE THREAD

**Issue by neilcampbell** [firebase/firebase-tools#199]
Hi there,
I just wanted to clarify what the process is for revoking/logout of a generated CI login token. Is the old token revoked when a new token is generated (so there is only ever 1 active token), or does it require `firebase logout --token {token}` to be run. If so is there a way to list all active tokens or revoke all active tokens?

Thanks,
Neil

**Comment by drtriumph** [comment]
These tokens are Google OAuth2 refresh tokens (see bullet 4 [here](https://developers.google.com/identity/protocols/OAuth2#basicsteps)). Their number is limited, but that number is greater than 1 - the easiest way to explicitly render a token invalid is to use `firebase logout --token {token}` as you mentioned. I do not know of an API for listing outstanding refresh tokens, I'm not sure it exists

**Comment by neilcampbell** [comment]
Thanks for the clarification @drtriumph
