### ISSUE TITLE
[Feature Request] Breakpoint debugging for trigger functions

### ISSUE THREAD

**Issue by JerryGoyal** [firebase/firebase-tools#1990]
Recently firebase team made it possible to breakpoint debug firebase functions https://github.com/firebase/firebase-tools/issues/1360 (thank you for this).
 I was hoping now that if it could be extended to debug background (trigger) functions. For example putting breakpoint to user `onCreate` function.

**Comment by samtstern** [comment]
@JerryGoyal that is already supported in two ways!

1. You can breakpoint debug any function using `firebase functions:shell --inspect-functions`, you can call them interactively and your breakpoitnts will hit.
1. If the function has an associated emulator (Database, Firestore, PubSub at the moment) you can run that emulator alongside the Functions emulator and you will be able to breakpoint debug them as they fire.

If you want to debug `auth.onCreate` using the second method you'll have to wait for us to create an Authentication emulator.  This is a top priority for us, but we are tracking it elsewhere so I am going to close this bug.
