### ISSUE TITLE
Can I change Firebase Hosted Web App URL?

### ISSUE THREAD

**Issue by lovebdsobuj** [firebase/firebase-tools#200]
Example:
My Project name '**Hello World**'
and 
After deploying Web App
I got this url 
https://hello-world-6756a.firebaseapp.com

Can I change https://**hello-world-6756a**.firebaseapp.com to https://**hello-world**.firebaseapp.com (If available the sub domain name).

Thank you.

**Comment by mbleigh** [comment]
Unfortunately this is not possible. The subdomain you're assigned is permanent.

**Comment by lovebdsobuj** [comment]
So it's not own selection like appspot!
< hello-world-**6756a** > bold text is automated & randomly include every site?

**Comment by mbleigh** [comment]
We try to give you a friendly project id, but if one already exists with
your specified name we append the random characters.

**Comment by lovebdsobuj** [comment]
I didn't get friendly project id.
Yesterday, I create a new project.
Project name `"English Verbs"`
I got this URL https://english-verbs-6756a.firebaseapp.com
But this URL still not used.
https://english-verbs.firebaseapp.com

**Comment by mbleigh** [comment]
Its based on project id, which is a shared namespace with cloud. Not all
firebase projects deploy hosting, also.

**Comment by lovebdsobuj** [comment]
Oh!
Now I understand.

But if people can set own choices project id on first time.
Then may be it will be very good.
