### ISSUE TITLE
Unexpected JSON output with standalone binary

### ISSUE THREAD

**Issue by krohrer** [firebase/firebase-tools#2005]
### [REQUIRED] Environment info

**firebase-tools:** 7.14.0

**Platform:** macOS 10.14.6

### [REQUIRED] Test case

Run `./firebase-tools-macos projects:list -j >projects.json`
Inspect `projects.json` to see that there is some unexpected characters prepended to the actual json body.

### [REQUIRED] Steps to reproduce

* Download standalone binary from https://github.com/firebase/firebase-tools/releases/download/v7.14.0/firebase-tools-macos
* **This only works with the standalone binary, not when installed via `npm`**
* Log in with `./firebase-tools-macos`
* Run the above test case

### [REQUIRED] Expected behavior

JSON output should contain only JSON text.

### [REQUIRED] Actual behavior

Escape sequence to set window title is prepended to JSON body: "\e]0;Firebase CLI\a"

**Comment by abeisgoat** [comment]
hmm, fair yeah, that would def happen. Let me.... uh think about how to fix this.

**Comment by bkendall** [comment]
I've just double checked on this and it looks like it's not happening any more. If you see otherwise, let me know, otherwise I'll let this be closed.
