### ISSUE TITLE
Add debug option to `serve` command to show/hide network logs

### ISSUE THREAD

**Issue by ansballard** [firebase/firebase-tools#201]
One use case is for CLI tools wrapping firebase, since seemingly random console logs make for a difficult interface. Should be pretty simple, it looks like there's already [a debug option getting passed](https://github.com/firebase/firebase-tools/blob/master/commands/serve.js#L20) to `superstatic`, so all that needs to be added is an [arg to commander](https://github.com/firebase/firebase-tools/blob/master/commands/serve.js#L54) and pass it through to superstatic with port and host. Happy to make the changes and pull request if these seems like a reasonable change.

**Comment by bkendall** [comment]
(Work was done in #206 to do this but wasn't followed through.)

**Comment by abeisgoat** [comment]
You can now use the Firebase Emulator Suite with the Emulator UI log view to filter out traffic logs :)
