### ISSUE TITLE
Error from emulator. Error parsing triggers: Cannot find module 'http2'

### ISSUE THREAD

**Issue by cmaronchick** [firebase/firebase-tools#2012]
### [REQUIRED] Environment info

**firebase-tools:** 6.5

**Platform:** macOS 10.14

### [REQUIRED] Steps to reproduce

I'm not quite sure what happened. I restarted my mac, and the next time I tried to run firebase serve with firebase-tools@7.14, I ran into an issue with module http2. I didn't make any other changes.

### [REQUIRED] Expected behavior

firebase serve runs as expected

### [REQUIRED] Actual behavior

firebase serve throws the following error:
module.js:491
    throw err;
    ^

Error: Cannot find module 'http2'

**Comment by bkendall** [comment]
What version of Node are you running? Also, `firebase-tools` is up to `7.x`, if you would like to update

**Comment by samtstern** [comment]
Also could you please provide the full debug logs from `firebase --debug serve`?

**Comment by cmaronchick** [comment]
I upgraded to the latest stable node version and that seemed to fix it. Thanks.
