### ISSUE TITLE
Failure trying to install CLI tools

### ISSUE THREAD

**Issue by mieliespoor** [firebase/firebase-tools#2019]
### [REQUIRED] Environment info

Trying to install the latest version using `curl -sL https://firebase.tools | bash`

**firebase-tools:** N/A

**Platform:** Linux (CentOS (Amazon Linux 2)

### [REQUIRED] Test case

Run `curl -sL https://firebase.tools | bash`, see failure.

### [REQUIRED] Steps to reproduce

run `curl -sL https://firebase.tools | bash`

### [REQUIRED] Expected behavior

Tools install and working.

### [REQUIRED] Actual behavior

> -- Checking for existing firebase-tools on PATH...
which: no firebase in (/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/root/.dotnet/tools:/root/bin)
-- Checking your machine type...
[Binary URL] https://firebase.tools/bin/linux/latest
-- Downloading binary...
######################################################################## 100.0%#=#=#                                      ######################################################################## 100.0%##=#=-#                                    ######################################################################## 100.0%##-=#=-#                                   ######################################################################## 100.0%
-- Setting permissions on binary...
bash: line 213: firebase: command not found
Something went wrong, firebase has not been installed.
Please file a bug with your system information on Github.
https://github.com/firebase/firebase-tools/
-- All done!

**Comment by samtstern** [comment]
@mieliespoor thanks for filing this!  @abeisgoat will take a look.

**Comment by mieliespoor** [comment]
any update on this?

**Comment by samtstern** [comment]
@abeisgoat we now have two reports of this from different Windows users.

**Comment by abeisgoat** [comment]
Closing this to track in #2256 since it's the same issue.
