### ISSUE TITLE
Using google-auto-auth installs old versions of gcp-metadata with axios 0.18.0

### ISSUE THREAD

**Issue by Jony-Y** [firebase/firebase-tools#2023]
### [REQUIRED] Environment info
firebase-tools - latest (7.14.0)
node :11.15.0
os :mac - catalina
### [REQUIRED] Test case
Installing firebase-tools uses google-auto-auth which installs VERY old versions on gcp-metada and axios
### [REQUIRED] Steps to reproduce
see yarn.lock or package-json.lock

The issue here is axios 0.18.0 works in test env differently from 0.19.* which breaks tests.
Other firebase tools use the up to date gcp-metadata and are fine. just that auto-auto uses the very old version.

We can work around and install axios directly in our projects, but we have a large infra of our own and would prefer our resources from another package.

Please help

**Comment by samtstern** [comment]
@Jony-Y this was fixed in https://github.com/firebase/firebase-tools/pull/1973 which was part of the `7.13.1` release.  Are you sure you've got the latest version?  Maybe clearing `node_modules` or `package-lock.json` will help?

**Comment by Jony-Y** [comment]
we tested it with 7.14.0, basically also removed yarn.lock and node_modules and installed and it failed. I can retest with 7.15.0

**Comment by samtstern** [comment]
More confirmation of a bug in https://github.com/firebase/firebase-tools/issues/2030

**Comment by garyo** [comment]
Indeed, I think the fix in #1973 is not sufficient, because that PR doesn't _remove_ `google-auto-auth` but merely updates it to 0.10.0, the "latest" (2 years old and still deprecated) version. Thanks for looking into this!

**Comment by bkendall** [comment]
I've had this floating around for a while but never completed it: #1728.

That actually removes `google-auto-auth` from the codebase (and replaces it with `google-auth-library`). Since auth is a rather sensitive topic I've slated it into the next major release (coming Soon(tm)) and that should address this bug.

**Comment by samtstern** [comment]
#1728 was merged this should be fixed in version `8.0.0` and higher.
