### ISSUE TITLE
Prevent the delete function prompt, when deploying

### ISSUE THREAD

**Issue by ribomation** [firebase/firebase-tools#2025]
I have to git repos for cloud functions. The first one is tied to an Angular project and generates a SSR function (ngUniversal). The second repo has all API functions. I moved them out from the first repo, to have a separation of concern.

The problem arises when I deploy, it ask to delete the function(s) belonging to the other repo. I have tried several different variations, without any success. Such as the `--non-interactive` option, but it fails. Using export groups and option` --only functions:groupName`, still prompts for deletion.

According to https://github.com/firebase/firebase-tools/issues/488, the only solution is to list all functions after `--only functions:`, which seems a little bit unpractical.

So, it would be nice to have an option such as `--no-delete`, which will prevent the deletion prompt.

**Comment by bkendall** [comment]
I think what you're asking for is #999 - would that solution help you? (This reads like a similar request, but with a slightly different name)

**Comment by ribomation** [comment]
Yes, right on spot. 
I'm amazed nothing has happened regarding this since 5 Nov 2018, when https://github.com/firebase/firebase-tools/pull/999 was opened!
