### ISSUE TITLE
firebase-tools depends on old deprecated google-auto-auth & google-auth-library

### ISSUE THREAD

**Issue by garyo** [firebase/firebase-tools#2030]
Firebase-tools currently pulls in an ancient, deprecated library google-auto-auth (0.10.1) which hasn't been updated in 2 years. That then pulls in an old version of google-auth-library, v1.6.1. It's currently at 5.10.1. It also pulls in other old dependencies like `request@2.88.2` that could be security risks.

### [REQUIRED] Environment info

Linux Ubuntu 18.04, yarn 1.22.0, firebase-tools 7.15.1

### [REQUIRED] Test case

To repro, starting from scratch:
```bash
% mkdir proj1; cd proj1
% yarn init
...answer prompts, leave all blank
% yarn add firebase-tools
% yarn why google-auto-auth
% yarn why google-auto-auth
yarn why v1.22.0
[1/4] Why do we have the module "google-auto-auth"...?
=> Found "google-auto-auth@0.10.1"
info Reasons this module exists
   - "firebase-tools" depends on it
   - Hoisted from "firebase-tools#google-auto-auth"
% yarn why google-auth-library
yarn why v1.22.0
[1/4] Why do we have the module "google-auth-library"...?
=> Found "google-auth-library@5.10.1"
info Has been hoisted to "google-auth-library"
info Reasons this module exists
   - Hoisted from "firebase-tools#google-gax#google-auth-library"
   - Hoisted from "firebase-tools#@google-cloud#pubsub#google-auth-library"
   - Hoisted from "firebase-tools#@google-cloud#pubsub#google-gax#google-auth-library"
=> Found "google-auto-auth#google-auth-library@1.6.1"
info This module exists because "firebase-tools#google-auto-auth" depends on it.
# Just to confirm the two versions of google-auth-library:
% for d in $(find . -name google-auth-library -print); do echo $d; grep version $d/package.json; done   
./node_modules/google-auth-library
  "version": "5.10.1",
./node_modules/google-auto-auth/node_modules/google-auth-library
  "version": "1.6.1",
```
### [REQUIRED] Steps to reproduce

Follow steps above.

### [REQUIRED] Expected behavior

Only a recent (5.x) version of google-auth-library, and no `google-auto-auth` at all

### [REQUIRED] Actual behavior

See above; firebase-tools@7.15.1 pullls in google-auto-auth@0.10.1, which pulls in google-auth-library@1.6.1 (as well as the current version of google-auth-library)

Note: here's the `google-auto-auth` issue where deprecation is discussed: https://github.com/stephenplusplus/google-auto-auth/issues/39

**Comment by samtstern** [comment]
This looks like a dupe of #2023 which I thought was fixed in #1973 but apparently was not!   Let's track this there.
