### ISSUE TITLE
List of Current CLI sessions

### ISSUE THREAD

**Issue by ravishan110** [firebase/firebase-tools#204]
Is there any way, i can get list of current CLI sessions.

`firebase login:ci` creates new TOKEN every time without affecting the current ones. I wanted to know, is there any way i can get the list of all CLI sessions which are active? And, is there any command with which i can revoke them at one go?

**Comment by drtriumph** [comment]
See #199 - These are OAuth2 refresh tokens. First off, there are limits to how many you can have for the Firebase CLI, and there are limits to how many you as a user can have across all services that use Google Oauth2 refresh tokens - once you hit those limits (and they don't seem to be publicized anywhere, I don't know what they are) it's one-in-one-out and the oldest one gets revoked.

I don't know of a way to list outstanding refresh tokens from Google, but I do know that clicking 'Remove' on the `Firebase CLI` entry here: https://security.google.com/settings/security/permissions will revoke all of them. Logging back in will prompt you for permissions again and if you grant them your new token will be the only valid one.
