### ISSUE TITLE
firebase-bolt not found on Windows

### ISSUE THREAD

**Issue by oscar-b** [firebase/firebase-tools#205]
λ firebase deploy --only database
    Error: There was an error loading firebase.json:
    Bolt not installed, run npm install -g firebase-bolt

It's installed though, and works from the command line like it should. Using node v6.3.1 under Windows 10.

Seems related:
https://github.com/nodejs/node-v0.x-archive/issues/2318

**Comment by oscar-b** [comment]
I created a small test script, based on the code in firebase-tools:

	'use strict';
	var fs = require('fs');
	var spawnSync = require('child_process').spawnSync;
	var filename = 'firebase-rules.bolt';

	var ruleSrc = fs.readFileSync(filename);

	var result = spawnSync('firebase-bolt', {
		input: ruleSrc,
		timeout: 10000,
		encoding: 'utf-8',
	});

	if (result.error && result.error.code === 'ENOENT') {
		console.log('1', result.error);
		// throw new FirebaseError('Bolt not installed, run ' + chalk.bold('npm install -g firebase-bolt'), {exit: 1});
	} else if (result.error) {
		console.log('2', result.error);
		// throw new FirebaseError('Unexpected error parsing Bolt rules file', {exit: 2});
	} else if (result.status > 0) {
		console.log('3', result.status);
		// throw new FirebaseError(result.stderr, {exit: 1});
	}

	return result.stdout;


Gettings this when running it on Windows:

	1 { Error: spawnSync firebase-bolt ENOENT
		at exports._errnoException (util.js:1012:11)
		at spawnSync (child_process.js:453:20)
		at Object.<anonymous> (C:\Dev\cnc-booking\bolt.js:9:14)
		at Module._compile (module.js:541:32)
		at Object.Module._extensions..js (module.js:550:10)
		at Module.load (module.js:458:32)
		at tryModuleLoad (module.js:417:12)
		at Function.Module._load (module.js:409:3)
		at Module.runMain (module.js:575:10)
		at run (bootstrap_node.js:352:7)
	code: 'ENOENT',
	errno: 'ENOENT',
	syscall: 'spawnSync firebase-bolt',
	path: 'firebase-bolt',
	spawnargs: [] }

**Comment by oscar-b** [comment]
Using https://www.npmjs.com/package/cross-spawn works perfectly, do you want a PR?

**Comment by TheoMer** [comment]
@oscar-b I'm experiencing this very same said issue [Error: There was an error loading firebase.json: Bolt not installed](https://github.com/este/este/issues/1139#issuecomment-246844551)

What version of firebase-tools utilises cross-spawn?

**Comment by mbleigh** [comment]
We may not have cut a release with it yet, stay tuned!

**Comment by TheoMer** [comment]
@mbleigh Ok, sure. Thanks for the heads-up.

**Comment by oscar-b** [comment]
@TheoMer You could npm install from my branch, if you're in a rush.

**Comment by TheoMer** [comment]
@oscar-b Can you confirm with me what version of your branch is currently available? I'm receiving the following message, 'Update available: 3.0.8'.

**Comment by mbleigh** [comment]
We have since released a `cross-spawn` compatible version of the CLI.

**Comment by TheoMer** [comment]
@mbleigh Thanks for the update.
