### ISSUE TITLE
Ternary operator not working in firestore emulator

### ISSUE THREAD

**Issue by olivierkrener** [firebase/firebase-tools#2066]
### [REQUIRED] Environment info

**firebase-tools:** 7.16.1

**Platform:** Windows

### [REQUIRED] Test case

Just write any firestore security rule using the ternary operator, for instance:
  allow update: if request.resource.data.test ? 1 : 2;

### [REQUIRED] Steps to reproduce

See above

### [REQUIRED] Expected behavior

As per the doc the rernary operator should be supported! This is working in the online simulator

### [REQUIRED] Actual behavior

Compile error in the emulator
INVALID_ARGUMENT: Error compiling rules:
Use of ternary operator not allowed.

**Comment by samtstern** [comment]
@olivierkrener thanks for filing this, let me go ask about it.

**Comment by scottcrossen** [comment]
Thanks for bringing this to our attention! We omitted a flag in the emulators which I just turned on. It will go out with the next release of the emulators/CLI. I'll try pushing to get a faster release. In the meantime this feature is fully supported in the console Rules Playground and production if you want to try it out.

Again, thanks for catching this bug.
