### ISSUE TITLE
Dependency - tough-cookie deprecated version

### ISSUE THREAD

**Issue by darkmorpher** [firebase/firebase-tools#207]
> npm install -g firebase-tools

**npm WARN deprecated** tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130 _"Upgrade to at least version 2.3.0"_

> npm ls -g graceful-fs
> ..\Documents\node
> +-- firebase-tools@3.0.7
> | +-- googleapis@2.1.7
> | | -- request@2.65.0
> | | ------ **tough-cookie@2.2.2**
> | -- request@2.74.0
> | ------ **tough-cookie@2.3.1**

_"Versions 0.9.7 through 2.2.2 contain a vulnerable regular expression that, under certain conditions involving long strings of semicolons in the "Set-Cookie" header, causes the event loop to block for excessive amounts of time."_

**Comment by svincent** [comment]
Did some digging on this. Seems `googleapis@12.1.0` is the first version that has the fix.

For background, [request](https://github.com/request/request) updated to `"tough-cookie": "~2.3.0"` on in version [`request@2.73.1`](https://github.com/request/request/commit/bf9a8ef8c5b2d87899cfed30d31118f231c7fffe#diff-b9cfc7f2cdf78a7f4b91a753d10865a2) and [googleapis](https://github.com/google/google-api-nodejs-client) updated to a fixed request after the release of [12.0.0](https://github.com/google/google-api-nodejs-client/commit/1586e6f83545f5dc6c449c780791d40d6665a788#diff-b9cfc7f2cdf78a7f4b91a753d10865a2). Unfortunately they didn't bump the version then, so `12.1.0` is the first release that fixes this issue.

**Comment by darkmorpher** [comment]
Latest Firebase-tools v3.2.0 uses tough-cookie@2.3.2
