### ISSUE TITLE
"Memory limit exceeded." Error on functions deploy

### ISSUE THREAD

**Issue by TarikHuber** [firebase/firebase-tools#2073]
### [REQUIRED] Environment info

**firebase-tools:** 7.16.1

**Platform:** Windows 10

### [REQUIRED] Test case

Project specific issue with an random error for 90% of our firebase functions.
A similar project with less than 50 functions deploys without issues.

### [REQUIRED] Steps to reproduce

You probably can't reproduce it without adding more than 50 functions to a Firebase project.

### [REQUIRED] Expected behavior

The functions should be deployed. 
Note: no changes to the actual code of the functions was made. Since the last successfull deploy. Only some local and global dependencies have been updated. Including firebase-tools to the newest version.

### [REQUIRED] Actual behavior
About 90% of our functions fail to deploy with the error message:

```
!  functions[dbVehicleChecklistsOnCreate(europe-west1)]: Deployment error.
Function failed on loading user code. Error message: Error: memory limit exceeded.
```

That error message is shown for most of our functions. It also doesn't matter for what region they are.

I will try to install a older version of firebase-tools and check if it helps. 

**EDIT**
Reducing the `firebase-tools` version up to `7.14.0` did not help.
Also deploying the functions to another project on firebase resultet with the same error messages.

**Comment by TarikHuber** [comment]
Don't know why but updating the node version from 8 to 10 in the `package.json` file fixed this issue.

**Comment by spy4x** [comment]
I had same thing. It forced me to update to Node v10.
