### ISSUE TITLE
Firestore triggers of cloud functions in emulator are ignored

### ISSUE THREAD

**Issue by bumpmann** [firebase/firebase-tools#2078]
### [REQUIRED] Environment info

**firebase-tools:** 7.16.1

dependencies in functions:
"firebase-admin": "^8.10.0",
"firebase-functions": "^3.5.0",
"firebase-tools": "^7.16.1"

$ node --version
v12.16.1

**Platform:** Windows

### [REQUIRED] Test case

My test file:
```
const firebase = require('@firebase/testing');

//let app = firebase.initializeAdminApp({ projectId: "whatever" });
let app = firebase.initializeTestApp({ projectId: "whatever" });

test('Trigger', async () => {
    let docname = "/col/doc";
    await app.firestore().doc(docname).set({name:"Ifalnax"});
    await new Promise(resolve => setTimeout(resolve, 30000));
    expect((await app.firestore().doc(docname).get()).data().name).toBe("Ifalnax"); // pass
    expect((await app.firestore().doc(docname).get()).data().yolo).toBe("ok"); // Expected: "ok" Received: undefined
});
```

functions/index.js:
```
const admin = require('firebase-admin');
const functions = require('firebase-functions');

admin.initializeApp();
const db = admin.firestore();

exports.testtrigger = functions
    .firestore.document('col/doc')
    .onWrite((change, context) => {
        console.log("==== ? onWrite trigger ? ===="); // never found this log
        return db.doc("/col/doc").update({yolo:"ok"});
    })
```

### [REQUIRED] Steps to reproduce

Initialized with firebase init, updated dependencies (this does not changes the result with initial versions)

run with:
`firebase emulators:exec --only firestore,functions 'jest --testTimeout=50000 ./tests/trigger.test.js'`

I used firebase init with firestore, functions and emulator

### [REQUIRED] Expected behavior

The cloud function testtrigger should be triggered.

### [REQUIRED] Actual behavior

The cloud function `testtrigger` is never triggered, i don't see the the console log nor it updates the document in firestore.

```
$ ./node_modules/.bin/firebase emulators:exec --only firestore,functions 'jest --testTimeout=50000 ./tests/trigger.test.js'        
i  emulators: Starting emulators: functions, firestore
+  hub: emulator hub started at http://localhost:4400
!  Your requested "node" version "10" doesn't match your global version "12"
+  functions: functions emulator started at http://localhost:7895
i  firestore: firestore emulator logging to firestore-debug.log
+  firestore: firestore emulator started at http://localhost:7894
i  firestore: For testing set FIRESTORE_EMULATOR_HOST=localhost:7894
i  functions: Watching "C:\Users\bumpm\Desktop\chsynth\jdronline\firestore\functions" for Cloud Functions...
+  functions[testtrigger]: firestore function initialized.
i  Running script: jest --testTimeout=50000 ./tests/trigger.test.js
 FAIL  tests/trigger.test.js (11.235s)
  × Trigger (7438ms)

  ● Trigger

    expect(received).toBe(expected) // Object.is equality

    Expected: "ok"
    Received: undefined

       9 |     await new Promise(resolve => setTimeout(resolve, 5000));
      10 |     expect((await app.firestore().doc(docname).get()).data().name).toBe("Ifalnax"); // pass
    > 11 |     expect((await app.firestore().doc(docname).get()).data().yolo).toBe("ok"); // Expected: "ok" Received: undefined    
         |                                                                    ^
      12 | });

      at Object.<anonymous> (tests/trigger.test.js:11:68)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        12.214s
Ran all test suites matching /.\\tests\\trigger.test.js/i.
```

**Comment by bumpmann** [comment]
Ok i found my mistake, the project name was not the same than in firebase.json. my bad !

**Comment by benwinding** [comment]
@bumpmann, it seems this is still a big issue. Would be able to share anymore details on how you managed to get Firestore Triggers working locally? I can't seem to replicate what you have above

**Comment by bumpmann** [comment]
@benwinding 
here is my .firebaserc file:
```
{
  "projects": {
    "default": "jdr-online-dev"
  }
}
```

so initializeTestApp had to be initialized with projectId: "jdr-online-dev" and not "whatever". There was no log from the emulator saying it was listening only for this project so i just got confused.

**Comment by benwinding** [comment]
Wow thanks @bumpmann that was the problem. I checked the logs and it was logging against an old project _(would be great if they logged that on the terminal...)_. Anyway adding the `.firebaserc` didn't help, I needed to run `firebase use myproject` for it to switch.

![image](https://user-images.githubusercontent.com/11782590/79809577-fd469c00-83af-11ea-9719-720f1e50f795.png)

Now my triggers work!! Thanks mate!

**Comment by yaakov123** [comment]
None of the above solved it for me!
For the future reader, if you get stuck here, this is what you need to do (took me a good few hours to figure this one out)

If you are using Node version > 17.x you need to change the functions host in the firebase.json to use "127.0.0.1". So it would look something like this:

"emulators": {
    "functions": {
      "host": "127.0.0.1"
    },

There is some weird issue where localhost isn't resolving properly and this is necessary for now. Hope this helps someone out.

**Comment by mattematics9** [comment]
This works and you saved me so much time.  Thank you.

**Comment by soulcedric** [comment]
> None of the above solved it for me! For the future reader, if you get stuck here, this is what you need to do (took me a good few hours to figure this one out)
> 
> If you are using Node version > 17.x you need to change the functions host in the firebase.json to use "127.0.0.1". So it would look something like this:
> 
> "emulators": { "functions": { "host": "127.0.0.1" },
> 
> There is some weird issue where localhost isn't resolving properly and this is necessary for now. Hope this helps someone out.

Worked here as well! Was initially having trouble starting my emulator until I set host field under firestore emulator to "host": "127.0.0.1". Just changed this value under functions and I'm back in business.

**Comment by mojjjtaba** [comment]
I have the same problem but none of answers worked for me
