### ISSUE TITLE
firestore.delete hitting Cloud Resource Manager API. Exceeding quota limit. Does not report in  console quota reports.

### ISSUE THREAD

**Issue by Spencer-Easton** [firebase/firebase-tools#2083]
### [REQUIRED] Environment info

**firebase-tools:**
"firebase-tools": "7.6.0",

**Platform:**
Google Cloud Functions

### [REQUIRED] Test case
Call delete more then 1000 times under 100 seconds using the method described in 
https://firebase.google.com/docs/firestore/solutions/delete-collections.

Snippet of what is called.
```
  // Now clean up the batches node
    const batchPath = processRef.collection('batches').path;
    await firebase_tools.firestore
        .delete(batchPath, {
          project: process.env.GCLOUD_PROJECT,
          recursive: true,
          yes: true,
          token: env.fb.token
        });
```

You will get the following API error.
![crm-quota3](https://user-images.githubusercontent.com/9576580/77986026-0d54e980-72e4-11ea-9851-6effe1d11f3e.PNG)

### [REQUIRED] Steps to reproduce
Call firebase_tools.firestore.delete more then 1000 times in 100 seconds.  
Our use case:  We are using firestore for batch orchestration which leads to lots of document deletes. 

### [REQUIRED] Expected behavior
We were a bit blindsided by the API quota.  If you need to delete collections at a massive scale this is a solid limitation.  Though disappointed I'm not going to call this a bug (though is should be documented). The actual issue is that even though we are getting failure due to the API limit, this is not being reported in the console project.

### [REQUIRED] Actual behavior
I would expect the quota usage to be reported in the cloud console project. As of right now it is not,
![crm-quota](https://user-images.githubusercontent.com/9576580/77987270-63775c00-72e7-11ea-8f58-7edd6cc0510f.PNG)
![crm-quota2](https://user-images.githubusercontent.com/9576580/77987283-6a9e6a00-72e7-11ea-918f-c952d1488eb7.PNG)

With this data populated it would help us work with our case manager to get quota increase and allow us to set monitors on its consumption rate.

**Comment by Spencer-Easton** [comment]
Follow up. I have now realized that the project ID reported in the API error does not match any project I own. This would be why I don't see the quota consumption in the product I am running in.

HTTP Error: 429, Quota exceeded for quota group \'ReadGroup\' and limit \'cloudresourcemanager.PerUser.ReadGroup\' of service \'cloudresourcemanager.googleapis.com\' for consumer \'project_number:563584335869\'.'

I had our org GCP admin look and confirm 563584335869 is not our project. I not thinking this is a google owned project attached to firebase tools

**Comment by mbleigh** [comment]
@Spencer-Easton that's correct, the limitation is coming from the Firebase CLI consumer project. I assume you're using a `firebase login:ci` token when making calls? If you instead used [Application Default Credentials](https://cloud.google.com/docs/authentication/production) with a service account, it would consume your project's quota instead.

That being said, I'm surprised that this is actually causing the deletes to fail. The API call that is failing is likely `testIamPermissions`, a convenience that helps provide better error messages in case of command failure. When it fails, we [log the failure but continue anyway](https://github.com/firebase/firebase-tools/blob/master/src/requirePermissions.ts#L23-L32). Do you have any more detailed trace information?

I think it'd be reasonable to bypass the permissions check (since it's informational, not security-related)...we might be able to add a flag that makes that possible.

**Comment by mbleigh** [comment]
The next version of the CLI will skip this check if you set an `FIREBASE_SKIP_INFORMATIONAL_IAM` variable (to any value, but `true` should work fine).

**Comment by Spencer-Easton** [comment]
Thank you for the fast follow up. I was using the firebase login:ci per the docs. Will swap it over to the Default Creds for now and look forward to the next CLI version. Cheers!

**Comment by wimbledon** [comment]
@mbleigh How do you actually set the `FIREBASE_SKIP_INFORMATIONAL_IAM` environment variable?
I tried `firebase functions:config:set FIREBASE_SKIP_INFORMATIONAL_IAM=true` but to no avail.

Also, is there a better way to delete millions of firestore document by the document path without having to call `firebase firestore:delete` on each document? It's taking a very long time...

**Comment by samtstern** [comment]
@wimbledon see:
https://cloud.google.com/functions/docs/env-var

`functions:config` is not the same as environment variables, it uses the Cloud Runtime Config API.

**Comment by wimbledon** [comment]
Thank you, @samtstern.
So, what is the cloud function name in this case to call `firebase firestore:delete` on each Firestore document?
Are you able to successfully set the `FIREBASE_SKIP_INFORMATIONAL_IAM` variable?

**Comment by samtstern** [comment]
@wimbledon yes I am able to set the environment variable.  See this page for more documentation:
https://firebase.google.com/docs/firestore/solutions/delete-collections

You don't need to call it on every document, you can delete whole collections at once.

**Comment by wimbledon** [comment]
Thank you, @samtstern.

I don't want to delete the whole Firestore collection. Rather, I want to selectively delete certain documents in a collection.
I need to delete ~10 million documents from ~40 million documents collection.
Any good idea to accomplish this?

How did you set the `FIREBASE_SKIP_INFORMATIONAL_IAM` environment variable?

**Comment by samtstern** [comment]
@wimbledon there is no good way to do that besides doing 10 million separate operations.  I would strongly reconsider how you've structured your database if that's something you need to do regularly!
