### ISSUE TITLE
Migrating users to new Firebase database with hash-algo

### ISSUE THREAD

**Issue by morariu** [firebase/firebase-tools#2084]
### [REQUIRED] Environment info

7.16.2

Ubuntu
Node Version:  v10.15.3 (Have tried with several node versions)

### [REQUIRED] Steps to reproduce

Running the command below:

`firebase auth:import users.json --hash-algo=SCRYPT --rounds=8 --mem-cost=14 --hash-key=longstringofchars --salt-separator=longstringofchars --project project-123`

Returns the error:

`error: unknown option '--hash-algo'`

### [REQUIRED] Expected behavior

The command should import users.json to the new firebase

### [REQUIRED] Actual behavior

```
[2020-03-31T12:48:07.020Z] ----------------------------------------------------------------------
[2020-03-31T12:48:07.023Z] Command:       /home/laur/.nvm/versions/node/v10.15.3/bin/node /home/laur/.nvm/versions/node/v10.15.3/bin/firebase auth:import massage_users_auth.json --hash-algo=SCRYPT --rounds=8 --mem-cost=14 --hash-key=xxxxxxxxxxxxxxxxxxxxxx --salt-separator=xxxxxxxxxxxxxxxxxxxxx --project project-11111111222222222 --debug
[2020-03-31T12:48:07.023Z] CLI Version:   7.16.2
[2020-03-31T12:48:07.024Z] Platform:      linux
[2020-03-31T12:48:07.024Z] Node Version:  v10.15.3
[2020-03-31T12:48:07.024Z] Time:          Tue Mar 31 2020 20:48:07 GMT+0800 (Central Indonesia Time)
[2020-03-31T12:48:07.024Z] ----------------------------------------------------------------------
[2020-03-31T12:48:07.024Z] 
error: unknown option '--hash-algo'
```

**Comment by samtstern** [comment]
@morariu hmm I am not able to reproduce this:
```
$ firebase auth:import users.json --hash-algo=SCRYPT --rounds=8 --mem-cost=14 --hash-key=longstringofchars --salt-separator=longstringofchars
Processing users.json (3 bytes)
```

Are you having trouble with any other Firebase commands?

**Comment by morariu** [comment]
> @morariu hmm I am not able to reproduce this:
> 
> ```
> $ firebase auth:import users.json --hash-algo=SCRYPT --rounds=8 --mem-cost=14 --hash-key=longstringofchars --salt-separator=longstringofchars
> Processing users.json (3 bytes)
> ```
> 
> Are you having trouble with any other Firebase commands?

No other issues with the firebase cli. I don't know how else to debug - any way to verify system health for the firebase cli?
![screenshot1](https://user-images.githubusercontent.com/11760586/78031187-c8898b00-7395-11ea-88af-6bca577a32cc.png)

**Comment by samtstern** [comment]
@morariu sorry I really have no idea what could be different about your setup ... @bkendall any ideas about commander?

**Comment by bkendall** [comment]
I set up my linux environment to be just like yours and still am unable to replicate this issue.

@morariu - Could you uninstall and reinstall `firebase-tools`? My only guesses are that (1) maybe the source file has been corrupted, or (2) one of the characters in your "--hash-algo" is not actually the characters the option is expecting.

To (2), actually, if you move `--hash-algo` to the end, does it break in a different way?

**Comment by morariu** [comment]
> I set up my linux environment to be just like yours and still am unable to replicate this issue.
> 
> @morariu - Could you uninstall and reinstall `firebase-tools`? My only guesses are that (1) maybe the source file has been corrupted, or (2) one of the characters in your "--hash-algo" is not actually the characters the option is expecting.
> 
> To (2), actually, if you move `--hash-algo` to the end, does it break in a different way?

@bkendall Genius! It worked after reinstalling firebase-tools. Thank you for the help!
