### ISSUE TITLE
Permissions break when deploying functions

### ISSUE THREAD

**Issue by RWOverdijk** [firebase/firebase-tools#2104]
This template is madness! I get it, but still haha. Anyway, here goes nothing.

### [REQUIRED] Environment info

**firebase-tools:** 7.15.1

**Platform:** macOS (10.15.1)

### [REQUIRED] Test case

N/A.

### [REQUIRED] Steps to reproduce

Idk, it's random. Sometimes when I deploy a function setting the permissions on it properly fails.

I then have to go to https://console.cloud.google.com/functions/list?authuser=1&project=myproject and give the function the execute permission for allUsers manually.

This is pretty scary stuff because this happens in production and just breaks parts of the application. Imo this is pretty urgent stuff.

### [REQUIRED] Expected behavior

A normal deploy that doesn't break parts my application.

### [REQUIRED] Actual behavior

Some sort of Russian roulette of deploys. Maybe it does what I want, maybe it breaks my product.

>403 Error: Forbidden Your client does not have permission to get URL from this server.

**Update:** This has happened across multiple projects and multiple working machines (not just mine, also other devs in the team). This leads me to believe it's a bug, as it's not bound to my machine and not bound to my project.

**Comment by samtstern** [comment]
@RWOverdijk can you tell us a little more about this:

> Idk, it's random. Sometimes when I deploy a function setting the permissions on it properly fails.

Specifically can you provide the error log that comes with the failure?

Also this sounds like it's related to this issue:
https://github.com/firebase/firebase-tools/issues/2086

There was a recent change in Cloud Functions / IAM that means users with the Project Editor role can't currently create Public HTTPs functions.  You can use any of the following workarounds:

1. Have a project owner deploy.
2. Grant the specific IAM permission needed to the developers on the team who are not owners.
3. Create a service account with the needed permissions and use that to deploy (`GOOGLE_APPLICATION_CREDENTIALS=your-service-account.json firebase deploy ...`)

**Comment by RWOverdijk** [comment]
@samtstern There is no error. Everything seems successful, but it's an empty lie.

Also it's _sometimes_ so it's not a role issue. Not to sound annoyed, buy I clearly stated that in the issue I think.

As to the other issue, I also think it's not related. I am the owner, my role is owner and I have the proper permissions. If this were the issue I assume it wouldn't be random, because randomly declining a request based on failing permissions would be tragic. 😄

**Comment by RWOverdijk** [comment]
I'll make everyone owner and reopen this if it happens again.

**Comment by samtstern** [comment]
@RWOverdijk ok that makes sense I have some more questions:

  * What version of Node.js are you using in your functions, 8 or 10?
  * When it happens does it happen to all functions or just specific functions?

The next step is probably to have someone on the GCF backend team take a look at the deployment, which involves collecting some personal information.  Next time it happens can you please file a ticket with [Firebase support](https://firebase.google.com/support) and include:

- Your project ID
- The name of the specific function that had this problem
- A timestamp of the deployment

Alternatively If you look in your Cloud Functions logs you should see an audit log entry for each deploy, here's an example of one of mine:
<img width="1241" alt="Screen Shot 2020-04-06 at 10 17 47 AM" src="https://user-images.githubusercontent.com/8466666/78568311-eb7dca00-77ef-11ea-9d1e-4bab79a797e8.png">

If you could attach one of those log messages to your support ticket, that contains all of the information we would need to dig in.  Once you have a support ticket please reply here with the Case Number and I will make sure I get cc'ed on the case so I can follow along.

**Comment by RWOverdijk** [comment]
@samtstern Thanks, next time I'll know exactly what to provide. Fast response times, kudos. :)
