### ISSUE TITLE
deploy - Add a argument for forcing a browser ( Suggestion )

### ISSUE THREAD

**Issue by deadpanaden** [firebase/firebase-tools#211]
I have Firefox, Chromium and the default Ubuntu Browser all installed with Firefox being the default.

The problem is that Firefox (as great and powerful as it is) is very slow to boot and I prefer Chromium for quickly searching or doing something.

It would be a timesaver to include something along the lines of
`$ firebase deploy --openvia "chromium-browser $U"`
to force the firebase cli to use another browser.

**Comment by mbleigh** [comment]
Thanks for the suggestion -- unfortunately I think the complexity this adds outweighs the utility. If you prefer Chromium for quick open tasks, why not make Chromium your default browser? :)
