### ISSUE TITLE
All my projects are missing!

### ISSUE THREAD

**Issue by cheng-kang** [firebase/firebase-tools#2113]
firebase --version: 8.0.0

```

[debug] [2020-04-08T14:38:30.686Z] <<< HTTP RESPONSE 500 {"vary":"X-Origin, Referer, Origin,Accept-Encoding","content-type":"application/json; charset=UTF-8","date":"Wed, 08 Apr 2020 14:38:30 GMT","server":"ESF","cache-control":"private","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","alt-svc":"quic=\":443\"; ma=2592000; v=\"46,43\",h3-Q050=\":443\"; ma=2592000,h3-Q049=\":443\"; ma=2592000,h3-Q048=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,h3-T050=\":443\"; ma=2592000","accept-ranges":"none","transfer-encoding":"chunked"}
[debug] [2020-04-08T14:38:30.686Z] <<< HTTP RESPONSE BODY {"error":{"code":500,"message":"Internal error encountered.","status":"INTERNAL"}}
[debug] [2020-04-08T14:38:30.687Z] HTTP Error: 500, Internal error encountered.
[debug] [2020-04-08T14:38:30.869Z] FirebaseError: HTTP Error: 500, Internal error encountered.
    at module.exports (/usr/local/lib/node_modules/firebase-tools/lib/responseToError.js:38:12)
    at Request._callback (/usr/local/lib/node_modules/firebase-tools/lib/api.js:40:35)
    at Request.self.callback (/usr/local/lib/node_modules/firebase-tools/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/firebase-tools/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:182:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/firebase-tools/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:441:20)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[error] 
[error] Error: Failed to get Firebase project turnips-exchange. Please make sure the project exists and your account has permission to access it.
```

**Comment by samtstern** [comment]
@cheng-kang there's something going on right now preventing most people (including me) from loading Firebase projects or the Firebase console.  We're investigating and will post more on the status dashboard when we know more:
https://status.firebase.google.com/

Going to close this as this is not a CLI issue so we won't be able to address it here.  Thank you for your patience!

**Comment by bkendall** [comment]
Here's the Google Cloud dashboard page for the incident: https://status.cloud.google.com/incident/zall/20005

**Comment by bkendall** [comment]
Here's the Firebase Status dashboard page: https://status.firebase.google.com/incident/Console/20003

**Comment by gOzaru** [comment]
Well, this thing happened again on 21 July 2022. 
My previous Service Account of Firebase Admin SDK was missing and could not deploy any function. I didn't know anything about this, as I have checked the link above [https://status.firebase.google.com/](https://status.firebase.google.com/) and [https://status.cloud.google.com/](https://status.cloud.google.com/), and it said it is safe and no error at all. So I was forced to create a new Service Account for Firebase Admin SDK and generate a new Private Key to continue the project. After do the basic things, I still cannot deploy anything. 

Oh yeah, 3 hours ago, the previous Service Account that I thought was deleted is now there in [https://console.cloud.google.com/iam-admin/iam ](https://console.cloud.google.com/iam-admin/iam). 
Great.

**Comment by lisajian** [comment]
@gOzaru Would you mind reaching out to https://firebase.google.com/support so we can help you further? Thank you!
