### ISSUE TITLE
setup.web() doesn't work anymore in 8.*

### ISSUE THREAD

**Issue by jkarst** [firebase/firebase-tools#2119]
[This Firebase blog post](https://firebase.googleblog.com/2017/04/easier-configuration-for-firebase-on-web.html) no longer works because setup.web() function was removed in the 8.0.0 release

What is the correct way to get firebase config variables now that setup.web() has been removed?

### [REQUIRED] Environment info

**firebase-tools:**

8.0.2

**Platform:**

Windows

### [REQUIRED] Environment info

**firebase-tools:**

**Platform:**

**Comment by jkarst** [comment]
This isn't a bug.  You removed the functionality.

My suggestion is to remove the blog post referenced above.

**Comment by samtstern** [comment]
@jkarst the `firebase apps:sdkconfig` command is what you're looking for, thanks for calling this out!

**Comment by jkarst** [comment]
Hi @samtstern , thank you but I'm looking for the equivalent command in code, not the CLI command.

So, whatever is supposed to replace setup.web() 

Any ideas?

**Comment by samtstern** [comment]
@jkarst the commands are the same, when you import the CLI as a Node module you're just getting the same commands in a different form.

So:
```
fbcli.apps.sdkconfig({ ... }).then(...)
```

This guide will tell you a bit more about how to translate CLI commands to node:
https://github.com/firebase/firebase-tools#using-as-a-module

**Comment by julian-techzip** [comment]
Hi Sam, I don't think that's working right.

When I do:

```
var client = require("firebase-tools");
client
  .apps.sdkconfig()
  .then(function(data) {
    console.log(data);
  })
  .catch(function(err) {
    console.log(err)
  });
```

I get this:

```
TypeError: platform.toUpperCase is not a function
    at Object.getAppPlatform (C:\p\fates\node_modules\firebase-tools\lib\management\apps.js:31:22)

```
Which makes sense because I didn't specify the platform, as I would using the command line.

So if I try: 

`client.apps.sdkconfig('web')`

I get this:

```
TypeError: Cannot create property 'project' on string 'web'
    at Command.prepare (C:\p\fates\node_modules\firebase-tools\lib\command.js:104:25)

```

It looks like it's expecting an object.  When I try:

`client.apps.sdkconfig({ platform: 'web' })

`

I get this again:
```

TypeError: platform.toUpperCase is not a function
    at Object.getAppPlatform (C:\p\fates\node_modules\firebase-tools\lib\management\apps.js:31:22)
```

In app.js, the error is here:

```
function getAppPlatform(platform) {
    switch (platform.toUpperCase()) {

```
In lib/commands/apps-sdkconfig.js, I can't beyond this:
```

module.exports = new command_1.Command("apps:sdkconfig [platform] [appId]")
    .description("print the Google Services config of a Firebase app. " +
    "[platform] can be IOS, ANDROID or WEB (case insensitive)")
    .option("-o, --out [file]", "(optional) write config output to a file")
    .before(requireAuth_1.requireAuth)
    .action((platform = "", appId = "", options) => __awaiter(void 0, void 0, void 0, function* () {
    let appPlatform = apps_1.getAppPlatform(platform);
```
platform is an object.  Whatever I pass in the sdkadmin() function, the properties are added to the platform object.  

I don't see see how this could ever work.  But maybe I'm doing something obviously wrong.  Please advise?

**Comment by bkendall** [comment]
The signature of the function is: `sdkconfig(platform: string, appId: string, options: { project: string })` (roughly, you get the idea about options.

I added a test in commit c5ca576 (that I'm making a PR for, since it's written) that demonstrates this usage.

**Comment by samtstern** [comment]
Thanks @bkendall !

@jkarst check out the example here:
https://github.com/firebase/firebase-tools/pull/2130

**Comment by julian-techzip** [comment]
This is is great; thanks guys. 

I've been able to replicate my old workflow using this:

```
client.use(null, {projectRoot: __dirname})
.then(projectId  => client.apps.list('web', {project: projectId}))
.then(app => client.apps.sdkconfig('web', app[0].appId, { project: app[0].projectId}))
.then(config => {
    // do build stuff here
    console.log(config.sdkConfig)
})
.catch(error => console.log(error))

```

Basically, I just need a way to swap sdk config info in my pre-build code depending on what project alias I'm using.  This works with one registered app, but you get the idea.  Hopefully this helps someone else in the same situation.

Thanks again for your attention on this!

**Comment by jkarst** [comment]
Thanks guys!  I really appreciate the attention and effort here. 

I've been able to rebuild my old workflow using this (maybe it will help someone else):
```

client.use(null, {projectRoot: __dirname})
.then(projectId  => client.apps.list('web', {project: projectId}))
.then(apps => client.apps.sdkconfig('web', apps[0].appId, { project: apps[0].projectId}))
.then(config => {
    // do build stuff with this
    console.log(config.sdkConfig)
})
.catch(error => console.log(error))
```
