### ISSUE TITLE
Fail to deploy large/complex security rule file

### ISSUE THREAD

**Issue by olivierkrener** [firebase/firebase-tools#2127]
### [REQUIRED] Environment info

firebase-tools: 8.0.2 (same behavior on 7.16.1)

Platform: Windows 10

### [REQUIRED] Test case

SOMETIMES, deploying a large rule file will throw an exception

### [REQUIRED] Steps to reproduce

Take the attached security rule file and try deploying it
firebase deploy --only firestore:rules

### [REQUIRED] Expected behavior

Should deploy properly

### [REQUIRED] Actual behavior

The following exception is thrown:
Error: HTTP Error: 503, The service is currently unavailable.

Full log file attached
(output of firebase deploy --only firestore:rules --debug)
[firebase-debug.log](https://github.com/firebase/firebase-tools/files/4464503/firebase-debug.log)
[rules.txt](https://github.com/firebase/firebase-tools/files/4464507/rules.txt)

**Comment by olivierkrener** [comment]
Note: I sometimes get the error

> Error: HTTP Error: 409, Requested entity already exists

Have not found a way to reproduce this yet

**Comment by bkendall** [comment]
Interesting. The `503` was coming from the "check" portion of deploying. If that's gone, I'm not sure how best I can help. The `409` is a conflict, though I'm not sure off hand what the conflict is. Are you still getting that issue?

**Comment by olivierkrener** [comment]
You colleague @scottcrossen fixed the issue, wat more of an infrastructure issue apparently
