### ISSUE TITLE
Security rules emulator run report - fail for large report

### ISSUE THREAD

**Issue by olivierkrener** [firebase/firebase-tools#2128]
### [REQUIRED] Environment info

firebase-tools: 8.0.2 (same behavior on 7.16.1)

Platform: Windows 10

### [REQUIRED] Test case

For a complex rule set and many tests, run the tests via the Firestore emulator and view the test report

### [REQUIRED] Steps to reproduce

Take a large security rule file and run a bunch of tests
Try accessing the coverage report as specified at https://firebase.google.com/docs/firestore/security/test-rules-emulator#generate_test_reports

Report expected URL: http://localhost:8080/emulator/v1/projects/<project_id>:ruleCoverage.html

### [REQUIRED] Expected behavior

The report should be properly generated

### [REQUIRED] Actual behavior

Actual ouput:
HTML report:

> 429
> RESOURCE_EXHAUSTED
> gRPC message exceeds maximum size 4194304: 13443543

JSON report:

> {"error":{"code":429,"message":"gRPC message exceeds maximum size 4194304: 13443543","status":"RESOURCE_EXHAUSTED"}}

**Comment by samtstern** [comment]
@olivierkrener thanks for filing this!  That's a very clear bug, maybe @yuchenshi has an idea how to fix it (I don't know much about gRPC)

**Comment by yuchenshi** [comment]
Fix coming in the next release.

**Comment by yuchenshi** [comment]
Fixed with new emulator release, which is bundled in `firebase-tools@8.1.0`.
