### ISSUE TITLE
Execute clearFirestoreData only after all firestore triggers gets executed

### ISSUE THREAD

**Issue by manwithsteelnerves** [firebase/firebase-tools#2129]
Currently while testing(jest), we fire many requests consecutively to check if all functionalities are functioning properly. 

After calling all tests and once we enter teardown phase, we call clearFirestoreData to clean up the local emulator.

But...

Each test can in-turn call firestore trigger function and there is no defined time when it gets called. As per documentation it can take up to 10 secs and not guaranteed too. Because of this reason, we are at a point where we call clearFirestoreData way before even the triggers calls gets finished.

Currently we are solving it by clearing after a delay in teardown methods and its not consistent as triggers take more than several seconds.

The same problem happens with pubsub messages as well. When a message is fired from function, there is no way to find when the pubsub message reaches the subscribers.

Request : Execute clearFirestoreData only after all firestore triggers are called or an option to auto clean database on every launch.

**Comment by samtstern** [comment]
@manwithsteelnerves thanks for this feedback.  This feels similar to https://github.com/firebase/firebase-tools/issues/1813

We need a way to wait for all the emulators to stop being "busy".  There are two levels to this:

1. We could have the Functions emulator report whether there are any functions currently running. 
2. We could ask all the other emulators whether they are still processing anything.

(1) is pretty easy, (2) is pretty hard as it will require adding a new endpoint to each emulator.

I think that (1) + a few seconds of delay is going to solve 99.999% of use cases though.  The delay between an action and the function execution should be very small when using the emulators (it can be up to 10s in production but that's a different environment).

What do you think?

**Comment by samtstern** [comment]
Oh and I meant to say: let's close this issue and discuss on #1813
