### ISSUE TITLE
ERROR Rules content empty. Compilation aborted.

### ISSUE THREAD

**Issue by docotwuzif** [firebase/firebase-tools#2132]
### [REQUIRED] Environment info

**firebase-tools:** 8.0.3

**Platform:** Windows 10 Pro

node v10.16.0

Using VSCode (1.44.0) and Powershell, but error also happens with e.g. Notepad++ and cmd

### [REQUIRED] Test case

```
firestore.rules
rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if false;
    }
  }
}

```
### [REQUIRED] Steps to reproduce

1. Setup empty firebase project with only firestore.
2. run: firebase init
a. include firestore and emulators, choose default values
b. download firestore emulators
3. run: firebase emulators:start --debug (also happens without --debug)
4. change anything in firestore.rules and save
5. error below occurs

### [REQUIRED] Expected behavior

Changed rules are updated, as in log below.

i  firestore: Change detected, updating rules...
[2020-04-15T16:35:01.413Z] >>> HTTP REQUEST PUT http://localhost:8081/emulator/v1/projects/firestore-emulator-test-200415:securityRules  
 {"ignore_errors":true,"rules":{"files":[{"name":"security.rules","content":"rules_version = '2';\nservice cloud.firestore {\n  match /databases/{database}/documents {\n    match /{document=**} {\n      allow read, write: if false;\n    }\n  }\n}"}]}}
[2020-04-15T16:35:01.420Z] Apr 15, 2020 6:35:01 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected non-HTTP/2 connection.

[2020-04-15T16:35:01.445Z] <<< HTTP RESPONSE 200 {"content-type":"application/json","content-length":"4"}
+  firestore: Rules updated.

### [REQUIRED] Actual behavior

Emulator is recognizing update of file, but receiving an error and rules don't update.

i  firestore: Change detected, updating rules...
[2020-04-15T16:35:00.423Z] >>> HTTP REQUEST PUT http://localhost:8081/emulator/v1/projects/firestore-emulator-test-200415:securityRules  
 {"ignore_errors":true,"rules":{"files":[{"name":"security.rules","content":""}]}}
[2020-04-15T16:35:00.453Z] Apr 15, 2020 6:35:00 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected non-HTTP/2 connection.

[2020-04-15T16:35:00.548Z] <<< HTTP RESPONSE 200 {"content-type":"application/json","content-length":"178"}
!  firestore.rules:0:0 - ERROR Rules content empty. Compilation aborted.

I tried to fix the error myself and the following changes to @/emulator/firestoreEmulator.js removed the errors. (newContent was empty) 

OLD (lines 38-40)
```
                    const newContent = fs.readFileSync(rulesPath, "utf8").toString();
                    utils.logLabeledBullet("firestore", "Change detected, updating rules...");
                    const issues = yield this.updateRules(newContent);
```
NEW (lines 38-40)
```
                    // const newContent = fs.readFileSync(rulesPath, "utf8").toString();
                    utils.logLabeledBullet("firestore", "Change detected, updating rules...");
                    const issues = yield this.updateRules(fs.readFileSync(rulesPath, "utf8").toString());
```

I couldn't test it on other enviroments, but maybe it is helpful for others encountering this error for or for future updates.

**Comment by katowulf** [comment]
Thanks for reporting this and for the suggested workaround! Can you include the name of the security rules file and contents of your `firebase.json` for repro purposes?

**Comment by docotwuzif** [comment]
Rules file is named as default firestore.rules

firebase.json:
```
{
  "firestore": {
    "rules": "firestore.rules",
    "indexes": "firestore.indexes.json"
  },
  "emulators": {
    "firestore": {
      "port": "8081"
    }
  }
}

```

**Comment by samtstern** [comment]
@docotwuzif this looks very similar to https://github.com/firebase/firebase-tools/issues/1980

It seems we have some file-reading issues on Windows but to be honest none of us here has any idea when/why they happen...

**Comment by docotwuzif** [comment]
OK, thanks for info. Anyhow, just fyi: for me it still works perfectly fine now with the small change of code above... 
The interesting thing is, if you log newContent right after the readFileSync line, the variable appears to be empty, more often than not (sometimes it went through, especially on the first file update)

**Comment by nurilyas7** [comment]
Hi. I don't know why but when you run a statement that takes about 1ms before reading the file, the contents are read with no issue. So moving the print statement up worked for me.
```
utils.logLabeledBullet("firestore", "Change detected, updating rules...");
const newContent = fs.readFileSync(rulesPath, 'utf8').toString(); 
const issues = yield this.updateRules(newContent);
```
Saving the file continously by pressing down on the shortcut keys will cause intermittent failure. But likelihood of someone doing that is very low,  

![print_console](https://user-images.githubusercontent.com/14259666/79989863-ee143b00-84e2-11ea-842d-60dc338da799.PNG)

Also great work on the test suite! Makes development & testing a breeze!

**Comment by samtstern** [comment]
@nurilyas7 @docotwuzif this is evidence to my "race condition" hypothesis between Chokidar and fs.readFileSync.

Let me send a PR to add a 5ms pause.  Won't hurt anyone!
