### ISSUE TITLE
A lightweight version of this tool

### ISSUE THREAD

**Issue by Nowaker** [firebase/firebase-tools#214]
`firebase-tools` is a big toolkit with hundreds of dependencies which take very long to download & install. It can do a lot but all CI environments need is `firebase deploy`. Nothing more. There should be a separate version of this module, say `firebase-deploy`, that would have one command/binary `firebase-deploy`.

**Comment by mbleigh** [comment]
I don't have exact numbers, but a sizable chunk of the dependency graph is necessary just for `firebase deploy`. I don't think it would really save significant dependency to split this out, unfortunately.
