### ISSUE TITLE
Failed download Firebase CLI

### ISSUE THREAD

**Issue by arm-r** [firebase/firebase-tools#2141]
Failed download Firebase CLI
<img width="560" alt="Screen Shot 2020-04-17 at 22 48 34" src="https://user-images.githubusercontent.com/63866106/79588063-9ac67500-80fd-11ea-912d-56a838d99ba0.png">

### [REQUIRED] Environment info

**firebase-tools:**

macOS Mojave
**Platform:**

### [REQUIRED] Steps to reproduce
curl -sL https://firebase.tools | bash

### [REQUIRED] Expected behavior
Able to download firebase cli

### [REQUIRED] Actual behavior
Failed to download firebase cli

**Comment by samtstern** [comment]
@arm-r from some brief research it seems like there may be something wrong with your machine or internet connection.  Are you able to run just this command (without `|bash`):

```
curl -sL https://firebase.tools 
```
