### ISSUE TITLE
Firestore Emulator Batch Random Failures

### ISSUE THREAD

**Issue by elucidsoft** [firebase/firebase-tools#2146]
### [REQUIRED] Environment info

8.1.1

**firebase-tools:**
cloud-firestore-emulator-v1.11.3

**Platform:**
Ubuntu
### [REQUIRED] Steps to reproduce

1. Use a batch to write to multiple documents. Use update to update a single field on some documents.
2. In your unit test after batch.commit has finished read those documents back, and check values.

### [REQUIRED] Expected behavior

The expected behavior is to consistently return the same data after commit has finished.  

### [REQUIRED] Actual behavior

The data after commit has finished is inconsistent and changes randomly.  I can't figure out any cause for this behavior, it does not appear to do this when using the real firestore so I don't think it's my code.

**Comment by elucidsoft** [comment]
This can be closed, emulator had same behavior as real Firestore. I resolved these issues by using a Transaction.

**Comment by samtstern** [comment]
@elucidsoft thanks for following up with your solution!
