### ISSUE TITLE
existing firebase project directory

### ISSUE THREAD

**Issue by saimarshadsaim31** [firebase/firebase-tools#2148]
hi, 
whenever I start to do hosting it shows me following message:
"You're about to initialize a Firebase project in this directory:
  C:\Users\Grace
Before we get started, keep in mind:
  * You are initializing in an existing Firebase project directory"

and in the end it does not shows my projects can somebody explain how to correct this

### [REQUIRED] Environment info

**firebase-tools:**

**Platform:**

**Comment by bkendall** [comment]
It means you are running `firebase init` in a directory (or subdirectory) that has a `firebase.json` file in it (or in a parent directory). It's a situation that is hard for the CLI to make a concrete decision about, so it's printed as a warning.

Be cautious about overwriting any `firebase.json` file in that directory. To fix, you would have to look in the directory path to see if there are any `firebase.json` files the CLI could find.
