### ISSUE TITLE
Firestore Emulator doesn't authenticate Web SDK

### ISSUE THREAD

**Issue by patelnav** [firebase/firebase-tools#2155]
### [REQUIRED] Environment info

**firebase-tools:** 8.1.1

**Platform:** macOS

### [REQUIRED] Test case

- **Launch emulator:** firebase emulators:start --only functions,firestore
- Open Webapp that uses Web Javascript SDK

### [REQUIRED] Steps to reproduce

```

import firebase from 'firebase/app'
import 'firebase/firestore'
import 'firebase/auth'

const app = firebase.initializeApp({ projectId: "my-project-id", })

var db = app.firestore();
if (window.location.hostname === "localhost") {
    db.settings({
        host: "localhost:8080",
        ssl: false
    });
}

var docRef = db.collection('hello').doc('world')
docRef.set({ hello: "WORLD!" })

```

### [REQUIRED] Expected behavior

Document is written to firestore emulator

### [REQUIRED] Actual behavior

```
Uncaught (in promise) FirebaseError: PERMISSION_DENIED: false for 'create' @ L5
```

According to @samtstern [here](https://github.com/firebase/firebase-tools/issues/1001#issuecomment-605973969) this should just work? 
Perhaps hijacking Firebase SDK's auth is required as per @ryanpbrewster's [comment](https://github.com/firebase/firebase-tools/issues/1001#issuecomment-605412755) 

I can write to the emulator through Node.js SDK and curl commands without any issues.

**Comment by samtstern** [comment]
@patelnav yes this should just work.  Can you show me a few more things:

- Before you make the Firestore `set` call can you print out the current user?
- Can you show me your rules so we can see what the `create` rule is that's being denied?

**Comment by patelnav** [comment]
Your questions helped me figure it out:

I was launching the emulator from another dir and subsequently didn't pick up rules allowing anon-writes.

sorry for the trouble!

**Comment by samtstern** [comment]
@patelnav thanks for following up!
