### ISSUE TITLE
Revision Control for Deploying

### ISSUE THREAD

**Issue by mukilane** [firebase/firebase-tools#216]
**Issue**: 
When deploying, Firebase CLI uploads the whole project to the cloud. For bigger projects, involving numerous assets like images and scripts, it is pointless to upload any unchanged files. And changing the firebase.json everytime is not going to be feasible.

**Possible solutions:**
1. Implementing a revision control system, and uploading only the delta or atleast only the changed files.
2. Allowing to specify the 'ignore folders' as parameters to the deploy command.

**Comment by mbleigh** [comment]
This is on the roadmap, but since it's a product feature as opposed to a CLI feature I'm going to close this issue.
