### ISSUE TITLE
Cannot connect/execute queries using BigQuery when running functions locally.

### ISSUE THREAD

**Issue by Crymzix** [firebase/firebase-tools#2165]
###  Version info

**node:** 10.16.3

**firebase-functions:** 3.3.0

**firebase-tools:** 7.8.1

**firebase-admin:** 8.6.0

### Test case

```
import * as functions from 'firebase-functions'
import { BigQuery, TableMetadata } from '@google-cloud/bigquery'

const bigquery = new BigQuery({ projectId: process.env.GCLOUD_PROJECT, keyFilename: './lib/service-account-credentials-dev.json'})
test()

async function test() {
	const dataset = bigquery.dataset('dataset')
	const tableMetadataOptions = {
		schema: 'Name:string, Age:integer, Weight:float, IsMagic:boolean'
	} as TableMetadata
	const response = await dataset.createTable('test_table_1', tableMetadataOptions)
	console.log(response)
}

exports.event = functions.pubsub.topic('event').onPublish(message => {
	// TODO
})
```

### Steps to reproduce

Run `firebase serve` to have the function run locally.

### Expected behavior

`test_table_1` should be created in BigQuery and there should be a response that is logged in the console output once that has been completed.

### Actual behavior

Noting happens. Execution seem to hang when I call `await dataset.createTable(...)` and there is no error being thrown. The odd thing about this is that this code works perfectly fine when I do not use `firebase serve` and instead try to run this code via `node ./functions/lib/index.js` (the transpiled JS code) as a normal script.

**Comment by samtstern** [comment]
@Crymzix this is strange!  A few questions:

- Have you tried using `firebase emulators:start` instead of `firebase serve`?
- Can you try `emulators:start` with the `--debug` flag and show me the logs of an execution where this call hangs?
