### ISSUE TITLE
Improve error messaging around function dot-notation deploys

### ISSUE THREAD

**Issue by desduvauchelle** [firebase/firebase-tools#2166]
### Environment info

**firebase-tools:**  8.1.1 
**Platform:** MacOs

### Test case
```
$ firebase deploy --only functions:trig-users-onUserUpdate
```
### Steps to reproduce

1) Have a project setup
2) Create a cloud function
3) Try to deploy just that function, ex: 
```
$ firebase deploy --only functions:trig-users-onUserUpdate
```

### Expected behavior
```
...
✔  functions[trig-users-onUserUpdate(us-central1)]: Successful update operation.
...
```
Function deployed.

### Actual behavior
```
i  functions: current functions in project: trig-auth-createAuthUser(us-central1), trig-auth-onDeleteUser(us-central1), trig-users-onUserUpdate(us-central1)
⚠  functions: the following filters were specified but do not match any functions in the project: trig-users-onUserUpdate
```
Function wasn't deployed

**Comment by mbleigh** [comment]
What does your index.js look like?

You might want:

--only trig.users.onUserUpdate

**Comment by desduvauchelle** [comment]
```
const functions = require('firebase-functions')
const admin = require('firebase-admin')
admin.initializeApp()

const users = require('./triggers/users')
const posts = require('./triggers/posts')
const auth = require('./triggers/auth')
const comments = require('./triggers/comments')
const likes = require('./triggers/likes')
const following = require('./triggers/following')
const triggers = {
	users,
	posts,
	auth,
	comments,
	likes,
	following
}

exports.trig = triggers

const timelines = require('./queries/timelines')

const queries = {
	timelines
}
exports.queries = queries
```

**Comment by MichaelGradek** [comment]
The issue is that, for some reason, the deploy --only filter expects you to use dot notation to separate the modules / directories.

If you try this, it will work:

`$ firebase deploy --only functions:trig.users.onUserUpdate`

i.e. change the - for . 

I believe this is very counter intuitive, but it is what it is for now.

 ¯\_(ツ)_/¯

**Comment by desduvauchelle** [comment]
In agreement about the confusion. But works! Thanks. 

I don't know if the firebase team want to pursue this further or not, I'll leave it open for them to decide.

**Comment by mbleigh** [comment]
We use dot notation because we allow for exporting groups of functions and deploying them together, for instance:

```js
exports.myGroup = {fn1: functions.https.onRequest(), fn2: functions.https.onRequest()}
```

Where I can now deploy both functions with:

    firebase deploy --only functions:myGroup
    # or
    firebase deploy --only functions:myGroup.fn1

Function names cannot have periods in them, but the hierarchy makes dot-notation make more sense than dash notation.

I think the action here is probably to have a better error message before deploy if you include dashes (which are not allowed by our trigger parser), so I'll leave it open and edit the title to reflect.

**Comment by desduvauchelle** [comment]
It's a good reason to use dot, didn't know it was possible. 
In my case, I don't have any dashes in my names. They were added by the cli. 

Example of what I had
```js
// ---- triggers/user.js
exports.onUserUpdate = ....

// index.js
const users = require('./triggers/users')
const triggers = {
    users
}
exports.trig = triggers
```

So the solution for my issue is not be displaying errors for using `-` (but that might be useful if someone did), but instead list the function names with `.` in the console...example: 
```
1)
// FROM
 i  functions: updating Node.js 10 function trig-auth-createAuthUser(us-central1)..
// TO
i  functions: updating Node.js 10 function trig.auth.createAuthUser(us-central1)..

2) 
// FROM
✔  functions[trig-auth-onDeleteUser(us-central1)]: Successful update operation. 
// TO
✔  functions[trig.auth.onDeleteUser(us-central1)]: Successful update operation.

3)
// FROM
i  functions: current functions in project: trig-auth-createAuthUser(us-central1), trig-auth-onDeleteUser(us-central1)
// TO
i  functions: current functions in project: trig.auth.createAuthUser(us-central1), trig.auth.onDeleteUser(us-central1)
 
```

**Comment by crtl** [comment]
For me dashes do not work at all.
So when deploying the CLI lists all functions using dash-notation but when you want to provide a function name as an input argument you have to use dot-notation which is a bit akward, especially when multiple functions failed to deploy the very well intended hint to redeploy functions uses dash notation which makes it unusable.

**Comment by taeold** [comment]
Does https://github.com/firebase/firebase-tools/pull/2437 address the issue? If not, feel free to re-open this issue.
