### ISSUE TITLE
More permissive JSON parsing for rules

### ISSUE THREAD

**Issue by adelespinasse** [firebase/firebase-tools#217]
If I paste database rules into the firebase console at https://console.firebase.google.com/project/project-name/database/rules, it allows multiline rules with inline comments, as in:

```
      ".write": "
        // new comment
        (
          !data.exists() &&
          (
            // Team is public (but user is logged in)
            (auth != null && root.child('team/' + root.child('issues/' + $issueId + '/team').val() + '/public').val() == true)
            ||
            // User is member of team
            root.child('team/' + root.child('issues/' + $issueId + '/team').val() + '/members/' + auth.uid).exists()
          )
        )
        ||
        // User is the comment's creator
        data.child('creator').val() == auth.uid
        ||
        // User is a team admin
        (root.child('team/' + root.child('issues/' + $issueId + '/team').val() + '/admins/' + auth.uid).exists())
      "
```

This is very valuable for complex rules, since the above is pretty unreadable if compressed into one line. But I can't put that in my database.rules.json file, because `firebase deploy` does strict JSON parsing, which doesn't allow newlines inside quotes.

So `firebase deploy` should be less strict in its JSON parsing.

This might be made obsolete by Bolt.

Original groups thread [here](https://groups.google.com/forum/#!topic/firebase-talk/1bDG0iJc6HQ).

**Comment by mbleigh** [comment]
Yep, this is something we should fix.

**Comment by oodavid** [comment]
This was troublesome for me too; I initially added rules directly on the console with comments. Then after using `firebase init` the `database.rules.json` file contained said comments, but couldn't be deployed.

Furthermore, using `firebase deploy --only functions` would show the same errors, I wouldn't expect that to even parse the `database.rules.json` file.

**Comment by mbleigh** [comment]
I believe this should be working now, please re-open if it's not.
