### ISSUE TITLE
Cloud functions time out for project owner user using firebase emulator

### ISSUE THREAD

**Issue by Albertbol** [firebase/firebase-tools#2172]
* Operating System version: tested on windows and mac
  * Browser version: tested on chrome/safari/edge/firefox
  * Firebase SDK version backend: 
    "@google-cloud/firestore": "^3.7.4",
    "@google-cloud/storage": "^4.7.0",
    "@google-cloud/translate": "^5.3.0",
    "@google-cloud/vision": "^1.11.0",
    "firebase-admin": "^8.11.0",
    "firebase-functions": "^3.6.0",
    "firebase-tools": "^8.1.1"
    "firebase-functions-test": "^0.2.1"
  * Firebase SDK version front end: 
    "firebase": "^7.14.2",
  * Firebase Product: cloud-functions

#### Steps to reproduce:
My cloud functions are not changed for like a month, somewhere around 2 weeks ago, i started up functions locally and saw that all my cloud functions lead to time out (logged as a project owner), relogged to another user (no special rights) everything working fine. 
Checked production with both users, both working fine...
This problem i have for like 1 week.
Its very strange.
#### Relevant Code:

Cannot provide any code, and this is unnecessary, because its working and not working at the same time.
I have checked : https://cloud.google.com/functions/docs/concepts/iam Access Control, i have everything same.

Thanks

**Comment by samtstern** [comment]
@Albertbol we really need to see some code and logs from an execution that times out, otherwise we can't debug this effectively.

**Comment by samtstern** [comment]
@Albertbol it's been 10 days since the last response so I am going to close this issue.  If you're still having problems and have more information you can provide just let me know and re can re-open and discuss.

**Comment by Albertbol** [comment]
I have this issues still, its very weird and im not sure what information to provide, i am using nuxt project with firebase, as a back end i use cloud functions, performing same actions on my admin personal account (project owner) i am having time out on every cloud function, but using any other account everything is working good. 
Can you help me out how i can securely help you and provide not sensitive data from logs and in which code you are interested.

**Comment by samtstern** [comment]
@Albertbol that is just not enough information to go on, you'll need to provide logs at least and the code to match it.  If you consider logs/code too sensitive then unfortunately we can't help you in this public forum.
