### ISSUE TITLE
can't build project due to is-promise dependency

### ISSUE THREAD

**Issue by khaledosman** [firebase/firebase-tools#2179]
### [REQUIRED] Environment info

firebase-tools v8.1.1

**firebase-tools:**
Invalid "exports" main target "index.js" defined in the package config /Users/khaledosman/Documents/github/craftnote/node_modules/is-promise/package.json

**Platform:** macOS

### [REQUIRED] Test case
https://github.com/khaledosman/craftnote

### [REQUIRED] Steps to reproduce
`npm install && yarn start`

### [REQUIRED] Expected behavior
Project should build successfully

### [REQUIRED] Actual behavior
is-promise library breaks building of the project, due to misconfigured exports in package.json, this seems to be fixed in the latest version of the library according to that issue see https://github.com/then/is-promise/issues/20

### Additional Info
output of `npm list is-promise`
```
➜  craftnote git:(master) ✗ npm list is-promise
craftnote@0.0.0 /Users/khaledosman/Documents/github/craftnote
├─┬ firebase-tools@8.1.1
│ └─┬ cli-color@1.4.0
│   └─┬ memoizee@0.4.14
│     └── is-promise@2.2.0  deduped
└─┬ UNMET PEER DEPENDENCY inquirer@7.1.0
  └─┬ run-async@2.4.0
    └── is-promise@2.2.0

npm ERR! peer dep missing: inquirer@^5.0.0 || ^6.0.0, required by inquirer-autocomplete-prompt@1.0.2
```

**Comment by samtstern** [comment]
@khaledosman thanks for reporting this, there was a big issue with `is-promise` over the weekend:
https://github.com/then/is-promise/issues/20

This should be resolved now.
