### ISSUE TITLE
database:set fails to set data

### ISSUE THREAD

**Issue by snydersaurus** [firebase/firebase-tools#218]
Running **database:set** seems to work but doesn't really. Same with **database:update**

`$ firebase database:set / root.json`
`? You are about to overwrite all data at https://slick-61e41.firebaseio.com/. Are you sure? Yes`
`✔  Data persisted successfully`
`View data at: https://console.firebase.google.com/project/slick-61e41/database/data/`
`$ firebase database:get /`
`null`

root.json looks like this:
`{"users":{},"vehicles":{},"schedule":{}}`

**Comment by mbleigh** [comment]
Firebase treats empty objects as identical to null. You have to have values
somewhere in the data for it to set.

**Comment by snydersaurus** [comment]
Ok, I figured it was something easy. Thanks for clarifying that it ignores empty objects, nulls, etc.
