### ISSUE TITLE
Database rules are not loaded when it uses `target`

### ISSUE THREAD

**Issue by filipesilva** [firebase/firebase-tools#2184]
### [REQUIRED] Environment info

**firebase-tools:** 8.2.0

**Platform:** Windows

### [REQUIRED] Test case

`firebase.json`:
```
{
  "database": [
    {
      "target": "default",
      "rules": "database.rules.json"
    }
  ],
  "emulators": {
    "database": {
      "port": 9000
    }
  }
}
```
`database.rules.json`:
```
{
  "rules": {
    ".write": false,
    ".read": false
  }
}
```

### [REQUIRED] Steps to reproduce

When using multiple shards, the documentation in https://firebase.google.com/docs/database/usage/sharding suggests adding an alternate form of database configuration that specifies targets. The emulator does not seem to recognize this format.

Run `firebase emulators:start --only database` with the files above. You will see the following warning:
```
!  database: Did not find a Realtime Database rules file specified in a firebase.json config file.
!  database: The emulator will default to allowing all reads and writes. Learn more about this option: https://firebase.google.com/docs/emulator-suite/install_and_configure#security_rules_configuration.
```

If you change the format back to `"database": {"rules": "database.rules.json"},`, the warning goes away and the security rules are loaded.

### [REQUIRED] Expected behavior

Database rules are not loaded.

### [REQUIRED] Actual behavior

Database rules are loaded.

### Other information

I'm happy enough using some other way to load security rules to multiple databases that doesn't involve targets. But it's unfortunate that at the moment I have to choose between being able to deploy to multiple databases or use emulators for testing.

**Comment by bkendall** [comment]
Thank you for providing some good repro steps!

**Comment by filipesilva** [comment]
Thanks @samtstern and @bkendall!

**Comment by quantuminformation** [comment]
Mines are ignored in this case:

```
{

  "functions": {
    "predeploy": [
      "npm --prefix \"$RESOURCE_DIR\" run lint",
      "npm --prefix \"$RESOURCE_DIR\" run build"
    ]
  },
  "database": {
    "rules": "./database.rules.json"
  },
  "hosting": {
    "public": "public",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "rewrites": [
      {
        "source": "**",
        "destination": "/index.html"
      }
    ]
  },
  "emulators": {
    "functions": {
      "port": 5002
    },
    "firestore": {
      "port": 8080
    },
    "database": {
      "port": 9000
    },
    "hosting": {
      "port": 5000
    },
    "pubsub": {
      "port": 8085
    }
  }

}
```

**Comment by samtstern** [comment]
@quantuminformation this issue is about using `target` which your config does not.  If you're having an issue with database rules on the latest version of the CLI please open a new issue and show us the simplest possible reproduction you can find!
