### ISSUE TITLE
Cannot emulate httpsCallable function due to invalid character in header content ["x-callable-context-auth"]

### ISSUE THREAD

**Issue by boten** [firebase/firebase-tools#2185]
### [REQUIRED] Version info

**node:** 8

**firebase-functions:** 3.6.0

**firebase-tools:** 8.1.1

**firebase-admin:** 8.10.0

### [REQUIRED] Steps to reproduce

when i try to use httpsCallable **locally** i keep on getting the msg: 
"TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["x-callable-context-auth"] " :

[2020-04-25T13:11:36.080Z] [functions] Runtime ready! Sending request! 
[2020-04-25T13:11:36.080Z] TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["x-callable-context-auth"] 
[2020-04-25T13:11:36.080Z] [work-queue] {"queueLength":0,"workRunningCount":0}
[2020-04-25T13:11:36.162Z] [work-queue] {"queueLength":1,"workRunningCount":0}
[2020-04-25T13:11:36.162Z] [work-queue] {"queueLength":0,"workRunningCount":1}

and after 60 seconds my function timeout 

this bug suddenly appear and it only happens **locally** ?? 
when i deploy my functions to production every thing is working **OK** 
**locally** none of my Callable functions are working - when i put a console log in the beginning of the function i don't see anything - so the function wont event begin ?

p.s: my admin key has not changed for the past year - so i don't thing is has anything to do white my key.json

any idea what is this strange Invalid character in my header 
or how can i debug / reset it ?

p.s: tested on 3 browsers including incognito - same bug 

### [REQUIRED] Expected behavior

the function to start

### [REQUIRED] Actual behavior

the function code is never run - **locally** 

### Were you able to successfully deploy your functions?
yes

**Comment by bkendall** [comment]
Can you provide the relevant snippets of code? Ideally, the callable function as well as the code that is calling it? Thanks!

**Comment by takyam-git** [comment]
I got same problem.

I patched local `functionsEmulator.js`

maybe code is here
https://github.com/firebase/firebase-tools/blob/master/src/emulator/functionsEmulator.ts#L771-L777

```
        const contextAuth = {
          uid: token.uid,
          token: token,
        };

        delete req.headers["authorization"];
+       contextAuth.token.name = 'dummy ascii name';
        req.headers[HttpConstants.CALLABLE_AUTH_HEADER] = JSON.stringify(contextAuth);
```

my token like this

```
console.log(contextAuth)
{
  "uid": "xxxxxx",
  "token": {
    "name": "山田太郎", # my name is japanese multibyte character
    "picture": "https://xxx/photo.jpg",
      ....
      "sign_in_provider": "google.com" # sign in with google
    },
    "uid": "xxxx"
  }
}
```

I hope fix this 🙏
