### ISSUE TITLE
Command to install Firebase CLI fails on Windows WSL

### ISSUE THREAD

**Issue by jasenmoloy** [firebase/firebase-tools#2187]
### [REQUIRED] Environment info

**firebase-tools:** N/A

**Platform:** Ubuntu 18.04.4 LTS on Windows 10 x86_64 (using WSL)

### [REQUIRED] Test case

Run `curl -sL https://firebase.tools | bash`, see failure.

### [REQUIRED] Steps to reproduce

1. Open command prompt on Windows
2. Run `wsl` command
3. Run `curl -sL https://firebase.tools | bash` command
4. Enter password for sudo access
5. Observe output contains errors

### [REQUIRED] Expected behavior

Installed `firebase` tool

### [REQUIRED] Actual behavior

```
-- Checking for existing firebase-tools on PATH...
-- Checking your machine type...
[Binary URL] https://firebase.tools/bin/linux/latest
-- Downloading binary...
[sudo] password for jasen:
######################################################################## 100.0%#=#=#                                    ######################################################################## 100.0%##=#=-#                                  ######################################################################## 100.0%##-=#=-#                                 Warning: Failed to create the file /usr/local/bin/firebase: No such file or
Warning: directory
                                                                           0.0%
curl: (23) Failed writing body (0 != 16360)
-- Setting permissions on binary...
chmod: cannot operate on dangling symlink '/usr/local/bin/firebase'
bash: line 213: firebase: command not found
Something went wrong, firebase has not been installed.
Please file a bug with your system information on Github.
https://github.com/firebase/firebase-tools/
-- All done!
```

**Comment by samtstern** [comment]
@jasenmoloy what directory are you running the `curl ... | bash` command in and do you have permissions to create files there?

Seems like this is the heart of the issue:
```
curl: (23) Failed writing body (0 != 16360)
```

**Comment by jasenmoloy** [comment]
I was attempting to run this in the home directory (`~/`) and my project directory in Windows (`mnt/c/Users/<user>/development/...`) and get the same issue in both.

**Comment by mieliespoor** [comment]
This seems to be the same issue as in #2019

**Comment by samtstern** [comment]
@mieliespoor you're right they are the same issue, thank you for noticing!  Let's use #2019 since it was first.  Closing as a duplicate.
