### ISSUE TITLE
Failed to Deploy - events.js:180 ENOENT

### ISSUE THREAD

**Issue by digimbyte** [firebase/firebase-tools#2193]
### [REQUIRED] Environment info 
firebase-tools@8.2.0

Windows 10 64bit

Trying to use a callback on a function in a promise chain, may have broke tslint/cross-env

### [REQUIRED] Expected behavior

I expect firebase functions to deploy

### [REQUIRED] Actual behavior

instead, I get the following error
```
Running command: npm --prefix "%RESOURCE_DIR%" run build

> functions@ build X:\Development\Development\4L\4L Domains\dev\firebase\functions
> tsc


events.js:180
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm --prefix "X:\Development\Development\4L\4L Domains\dev\firebase\functions" run build ENOENT
    at notFoundError (C:\Users\digim\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (C:\Users\digim\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (C:\Users\digim\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
Emitted 'error' event at:
    at ChildProcess.cp.emit (C:\Users\digim\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:30:37)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn npm --prefix "X:\\Development\\Development\\4L\\4L Domains\\dev\\firebase\\functions" run build',
  path: 'npm --prefix "X:\\Development\\Development\\4L\\4L Domains\\dev\\firebase\\functions" run build',
  spawnargs: []
}
```
I have tried, clearing node_modules, npm install, npm update, re-affirming firebase.json predeploy to be windows compatible. manual predeploy, nothing.

was working before update, been working on this project for 2 months and now it doesn't work

**Comment by digimbyte** [comment]
> 
> 
> PS X:\Development\Development\4L\4L Domains\dev\firebase\functions> npm i -g firebase-tools
> npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
> C:\Users\digim\AppData\Roaming\npm\firebase -> C:\Users\digim\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules\firebase-tools\node_modules\chokidar\node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
> 
> + firebase-tools@8.2.0
> updated 1 package in 12.485s
> PS X:\Development\Development\4L\4L Domains\dev\firebase\functions> firebase --version
> 8.2.0
> PS X:\Development\Development\4L\4L Domains\dev\firebase\functions> firebase deploy --only functions --debug
> [2020-05-01T15:15:02.420Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
> [2020-05-01T15:15:02.422Z] > authorizing via signed-in user
> [2020-05-01T15:15:02.424Z] [iam] checking project l-ai-48b8e for permissions ["cloudfunctions.functions.create","cloudfunctions.functions.delete","cloudfunctions.functions.get","cloudfunctions.functions.list","cloudfunctions.functions.update","cloudfunctions.operations.get","firebase.projects.get"]
> [2020-05-01T15:15:02.436Z] > refreshing access token with scopes: ["email","https://www.googleapis.com/auth/cloud-platform","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","openid"]
> [2020-05-01T15:15:02.437Z] >>> HTTP REQUEST POST https://www.googleapis.com/oauth2/v3/token
>  <request body omitted>
> [2020-05-01T15:15:02.770Z] <<< HTTP RESPONSE 200 {"content-type":"application/json; charset=utf-8","vary":"X-Origin, Referer, Origin,Accept-Encoding","date":"Fri, 01 May 2020 15:15:02 GMT","server":"scaffolding on HTTPServer2","cache-control":"private","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","alt-svc":"h3-Q050=\":443\"; ma=2592000,h3-Q049=\":443\"; ma=2592000,h3-Q048=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","accept-ranges":"none","transfer-encoding":"chunked"}   
> [2020-05-01T15:15:02.780Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects/l-ai-48b8e:testIamPermissions  
>  {"permissions":["cloudfunctions.functions.create","cloudfunctions.functions.delete","cloudfunctions.functions.get","cloudfunctions.functions.list","cloudfunctions.functions.update","cloudfunctions.operations.get","firebase.projects.get"]}
> [2020-05-01T15:15:04.279Z] <<< HTTP RESPONSE 200 {"content-type":"application/json; charset=UTF-8","vary":"X-Origin, Referer, Origin,Accept-Encoding","date":"Fri, 01 May 2020 15:15:03 GMT","server":"ESF","cache-control":"private","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","server-timing":"gfet4t7; dur=1159","alt-svc":"h3-Q050=\":443\"; ma=2592000,h3-Q049=\":443\"; ma=2592000,h3-Q048=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","accept-ranges":"none","transfer-encoding":"chunked"}
> [2020-05-01T15:15:04.282Z] >>> HTTP REQUEST POST https://iam.googleapis.com/v1/projects/l-ai-48b8e/serviceAccounts/l-ai-48b8e@appspot.gserviceaccount.com:testIamPermissions
>  {"permissions":["iam.serviceAccounts.actAs"]}
> [2020-05-01T15:15:04.924Z] <<< HTTP RESPONSE 200 {"content-type":"application/json; charset=UTF-8","vary":"X-Origin, Referer, Origin,Accept-Encoding","date":"Fri, 01 May 2020 15:15:04 GMT","server":"ESF","cache-control":"private","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","alt-svc":"h3-Q050=\":443\"; ma=2592000,h3-Q049=\":443\"; ma=2592000,h3-Q048=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","accept-ranges":"none","transfer-encoding":"chunked"}
> 
> === Deploying to 'l-ai-48b8e'...
> 
> i  deploying functions
> Running command: npm --prefix "%RESOURCE_DIR%" run lint
> 
> > functions@ lint X:\Development\Development\4L\4L Domains\dev\firebase\functions
> > tslint --project tsconfig.json
> 
> 
> WARNING: X:/Development/Development/4L/4L Domains/dev/firebase/functions/src/index.ts:1335:154 - These overloads can be combined into one signature with an optional parameter.
> 
> Running command: npm --prefix "%RESOURCE_DIR%" run build
> 
> > functions@ build X:\Development\Development\4L\4L Domains\dev\firebase\functions
> > tsc
> 
> 
> events.js:180
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: spawn npm --prefix "X:\Development\Development\4L\4L Domains\dev\firebase\functions" run build ENOENT
>     at notFoundError (C:\Users\digim\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:6:26)
>     at verifyENOENT (C:\Users\digim\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:40:16)
>     at ChildProcess.cp.emit (C:\Users\digim\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:27:25)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
> Emitted 'error' event at:
>     at ChildProcess.cp.emit (C:\Users\digim\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:30:37)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12) {
>   code: 'ENOENT',
>   errno: 'ENOENT',
>   syscall: 'spawn npm --prefix "X:\\Development\\Development\\4L\\4L Domains\\dev\\firebase\\functions" run build',
>   path: 'npm --prefix "X:\\Development\\Development\\4L\\4L Domains\\dev\\firebase\\functions" run build',
>   spawnargs: []
> }
> 
> Error: functions predeploy error: Command terminated with non-zero exit code1
> PS X:\Development\Development\4L\4L Domains\dev\firebase\functions>

**Comment by digimbyte** [comment]
Found a solution: put my computer to sleep.
I stayed up until 2am debugging it, and put my computer to sleep to resume in the morning.
turn it back on, get some standard warnings and it deploys
/tableflip

**Comment by digimbyte** [comment]
Problem got worse, I now have EPERM errors on everything
node cannot create child processes or contact the npm repo

I have rolled back node/npm - updated to latest, fresh install, cleared by force everything.
I'm about ready to reinstall windows if some random folder has lost permissions

**Comment by samtstern** [comment]
@digimbyte I know this is incredibly frustrating but from what I can see here there's an issue with your system and this is not a bug in `firebase-tools` (or if it is, it will not be possible for us to reproduce and debug it).

The error is happening when we try to spawn a subprocess to do `npm run build` in your Cloud Functions directory as a `predeploy` step.

You can probably create a super-simple reproduction yourself by writing a short node script  that uses Node's [`child_process.spawn()`](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options) to spawn an `npm` subprocess.  Assuming you get the same error, I'd ask on StackOverflow about possible issues with your system/install.

If you don't get the same error let me know, then we can look deeper into the Firebase CLI.

**Comment by digimbyte** [comment]
it started with an error when doing firebase deploy.
I tried wrapping the realtime db inside a callback/promise which tslint did not like.
maybe it was a fault in cache when trying to redeploy
eventually it broke.

I dont think it's directly a firebase-tools issue, but it did start from there as that was the only thing I was working on at the time.

**Comment by BigBangKing** [comment]
I have this issue now and can not find a solution.
It deployed once but it did not after adding some files showing similar not found error.
And I think you guys need to look at it.

![image](https://user-images.githubusercontent.com/22196569/109394227-2335b900-7950-11eb-9fae-c91c7c795c6d.png)

**Comment by joseneto** [comment]
I am also having the same issue
 Using windows 10 64bits

![image](https://user-images.githubusercontent.com/5816648/109578304-b2200e00-7ad5-11eb-8f77-397cfba8b9cc.png)

**Comment by Kraakhoofd** [comment]
Identical issue here!

**Comment by dilshod1d** [comment]
same issue

**Comment by joseneto** [comment]
I fixed that change the package.json to something like:

` "scripts": {
    "build": "",
    "lint": "eslint .",
    "serve": "firebase emulators:start --only functions",
    "shell": "firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },`

**Comment by Vixxd** [comment]
As per a [StackOverflow post](https://stackoverflow.com/a/53225013/2129422) I found, changing `$RESOURCE_DIR` to `%RESOURCE_DIR%` in `firebase.json` worked for me. It had been deploying as expected up until I moved firebase.json from a parent folder into the root of the project.

**Comment by rendomnet** [comment]
Same issue HERE

**Comment by rendomnet** [comment]
@Vixxd what $RESOURCE_DIR ? I dont have this string in my firebase.json

**Comment by RohovDmytro** [comment]
Yeah, sadly same. Happens because of usage of `@vercel/ncc` lib.

**Comment by Megnatis** [comment]
same here

**Comment by digimbyte** [comment]
A solution in the end was a complete reinstall of Node and its globals, somehow the node folder was corrupted through a build process
