### ISSUE TITLE
Migrate to leven for finding the closest match

### ISSUE THREAD

**Issue by jamesgeorge007** [firebase/firebase-tools#2196]
As of now [didyoumean.js](https://github.com/dcporter/didyoumean.js/) matching engine is used to suggest matching commands if the user mistypes. But it is not longer actively maintained. Instead I would suggest switching over to [leven](https://github.com/sindresorhus/leven) which is the fastest JS implementation of the Levenshtein distance algorithm.

**Comment by jamesgeorge007** [comment]
I can work on a PR 👍

**Comment by samtstern** [comment]
@jamesgeorge007 thanks for the suggestion!  If you send a PR I am happy to review it, as long as @bkendall thinks this is OK?

**Comment by bkendall** [comment]
Sure - I think `didyoumean` has a bit of logic that actually returns the suggested word, so I would just be sure you encapsulate that as well.
