### ISSUE TITLE
HSTS preload support 

### ISSUE THREAD

**Issue by RoneyThomas** [firebase/firebase-tools#220]
I would really like firebase support HSTS preload for hosting rules. Currently firebase sets HSTS to strict-transport-security:max-age=31556926. I would like it be strict-transport-security:max-age=31536000; includeSubDomains; preload. So that i can add my domain to HSTS [preload list](https://hstspreload.appspot.com/). I tried to set it via hosting rules but got an error saying not supported.
```
      {
        "source": "**",
        "headers": [
          {
            "key": "strict-transport-security",
            "value": "max-age=31536000; includeSubDomains; preload"
          }
        ]
      }
```

**Comment by mbleigh** [comment]
Responded to mailing list version of this [here](https://groups.google.com/forum/#!topic/firebase-talk/S6XDEV6TVhk).

**Comment by leonelwilliams** [comment]
Any movement on this? I'd love to recommend a domain or two already preloaded with @lgarron's HSTS preload list be hosted with Google's firebase but if they were to move them now they'd be disqualified and removed from the list by some browsers.

**Comment by do-io** [comment]
@mbleigh has there been any movement on allowing hsts preload on firebase configs? Is it roadmapped?
