### ISSUE TITLE
can't get rid of "invalid project id" even with "firebase use --clear"

### ISSUE THREAD

**Issue by hlynbech** [firebase/firebase-tools#2203]
### [REQUIRED] Environment info

**firebase-tools:**
8.2.0

**Platform:**
MacOS 10.15.4
zsh 5.7.1 (x86_64-apple-darwin19.0)

### [REQUIRED] Test case

(fails on any project)

### [REQUIRED] Steps to reproduce

If accidentally running the `use` command with an invalid project id, like fx`firebase use .` then the CLI gets stuck with the error "Error: Invalid project id: .." even if I try to run the command `firebase use --clear`. I have to specify some valid project id with `--project=` for even getting  "--clear"  to work.

    $ firebase use .
    Now using project .
    
    $ firebase use --clear
    Error: Invalid project id: ..

### [REQUIRED] Expected behavior

`firebase use --clear` should not fail even if an invalid project id was (accidentally) specified previously with `firebase use`

Even better, `firebase use` should (maybe?) reject invalid project ids before making the id persistent. All commands seem to fail (even the ones that should alleviate this problem) if the project id is invalid.

### [REQUIRED] Actual behavior

    $ firebase use .
    Now using project .
    
    $ firebase --debug use --clear
    
    Error: Invalid project id: ..

**Comment by bkendall** [comment]
I've made a PR to prevent this in the future (I'm not 100% happy with the fix, but it'll fix it).

To fix your system, open the file `~/.config/configstore/firebase-tools.json` with your favorite editor. Look for the `activeProjects` key, then find the file path that has the invalid project identifier as the value in that collection. Remove it (making sure it remains valid JSON - check the ending commas) and that should remove the issue.

**Comment by supfam** [comment]
> I've made a PR to prevent this in the future (I'm not 100% happy with the fix, but it'll fix it).
> 
> To fix your system, open the file `~/.config/configstore/firebase-tools.json` with your favorite editor. Look for the `activeProjects` key, then find the file path that has the invalid project identifier as the value in that collection. Remove it (making sure it remains valid JSON - check the ending commas) and that should remove the issue.

can confirm, this is working ty

**Comment by 10eputzen** [comment]
2024 and still happening to me

**Comment by clementolive** [comment]
Same problem. 
I don't understand how to access the file ~/.config/configstore/firebase-tools.json
What does the first character represents ? 
I tried changing projet name, changing in angular.json, restarting everything...no luck.
