### ISSUE TITLE
firebase serve should assert node version

### ISSUE THREAD

**Issue by AAverin** [firebase/firebase-tools#2210]
### [REQUIRED] Environment info

**firebase-tools:** 8.2.0

**Platform:** MacOS

`firebase serve --only functions` should assert node version for local environment.
I have written a lot of code by mistake running node12. Now that I need to run it in node8, I have to fix a lot of issues.

**Comment by samtstern** [comment]
@AAverin `firebase emulators:start` will warn you about this difference and in general if you're doing Functions development it's better to use `emulators:start` than `serve`.

Does that work for you?  I think a hard assert is too harsh, in most cases the code will run fine on a different version.

**Comment by AAverin** [comment]
@samtstern I think it should be at least a warning then

**Comment by samtstern** [comment]
@AAverin here's what we show today when I am using Node v10 locally but my `package.json` requests Node 8 (the default):

```
$ firebase emulators:start
# ...
⚠  Your requested "node" version "8" doesn't match your global version "10"
```

Do you have any suggestions for how to improve the warning or should we close this issue?

**Comment by AAverin** [comment]
No, I was talking more about `firebase serve --only functions` that I was using before.
Probably I better switch to emulators
