### ISSUE TITLE
Integrate remote config actions upload/download/clone to cli 

### ISSUE THREAD

**Issue by xalikoutis** [firebase/firebase-tools#2212]
As  a mobile engineer, in many cases, i have to make lots of edits in remote config through firebase web app and in similar apps i have to renter the same remote configs.

So i order to automate the above i have created my own curl based bash scripts that download/ upload remote config and also clone them between projects.

I could make an API command proposal and implementation if you are interested.
What do think about it?

**Comment by samtstern** [comment]
@xalikoutis want to briefly sketch out the API here and we can discuss?

cc @kroikie

**Comment by xalikoutis** [comment]
```
# Global info
# file - remoteconfig local file
# 

         
#Print to cosnole or write remoteconfig to file
firebase projects:remoteconfig:get
Options
	-o, --out [file]  (optional) write remoteconfig output to a file

# Update remoteconfig from a file
firebase projects:remoteconfig:update  <file>

# Clone remoteconfig from current project to projectB
firebase projects:remoteconfig:clone <projectId]>

or

# Clone remoteconfig from projectA to projectB
firebase projects:remoteconfig:clone <projectIdA> <projectIdB>
```

**Comment by kroikie** [comment]
Hi @xalikoutis may I suggest the use the Admin SDK as a guide of some of the calls that we can make via the CLI. For example:
```
firebase remote-config:get --version <template_version>
firebase remote-config:publish <template_file>
```

WRT cloning to a different project I don't know if the CLI is setup to access multiple projects at once. If so then we can chat more about that. @samtstern Is this possible?

**Comment by samtstern** [comment]
@kroikie I agree the Admin SDK is a good "guide" but just want to clarify that we should not use the Admin SDK in the CLI (as we discussed earlier).

A `clone` command is possible and I think would be a really cool addition to the CLI.  The CLI authorizes as a user so if the user has access to both projects we could do it.

However I would suggest making it a two-phase operation:
  * `firebase --project projectIdA projects:remoteconfig:fetch`
  * `firebase --project projectIdB projects:remoteconfig:publish`

That makes it easier to script in cases where the user may need to actually change credentials during the command.

**Comment by kroikie** [comment]
@xalikoutis I think @samtstern suggestion of keeping the two operations separate is a good one. Devs will have the freedom to script it how they want with the `--project` flag.

I would suggest using `get` as opposed to `fetch` since `fetch` is what you would use for the client "fetching" a particular config values for a particular client instance, while `get` would retrieve the full template including all parameter variations.

Maybe:

- `firebase --project projectIdA remoteconfig:get --version templateVersion8`
- `firebase --project projectIdB remoteconfig:publish --path <template_file>`

**Comment by xalikoutis** [comment]
Thanks guys for your suggestions lets continue with two separate commands.

- `firebase remoteconfig:get --out <template_file> --version templateVersion8 --project projectIdA`  
`--out : optionally write remoteconfig output to a file or print it to stdout`
`--version : set optional the config version or use the latest`
`--project: set the projectid or use the default`

- `firebase  remoteconfig:publish <template_file> --project projectIdB` 
`<template_file>: set the template file path `
`--project: set the projectId or use the default`

**Comment by kroikie** [comment]
Hi @xalikoutis thanks for your suggestions. We have combined them with some additional features for API review. I'll update this issue once the API review is complete. Once approved we would welcome an implementation PR if you are still interested.

**Comment by samtstern** [comment]
I believe this is done and released!
```
$ firebase --help | grep remoteconfig
  remoteconfig:get [options]                                get a Firebase project's Remote Config template
  remoteconfig:rollback [options]                           roll back a project's published Remote Config template to the one specified by the provided version number
  remoteconfig:versions:list [options]                      get a list of Remote Config template versions that have been published for a Firebase project
```

**Comment by jkcdarunday** [comment]
Hi @samtstern, I'm trying to figure out how to update remote config as well for automated build the same way the original poster of the issue is looking for. However, the current implementation only supports retrieval and rollback without support for publishing/updating like the ones specified in the proposed solutions.

Should this ticket be reopened as the original issue hasn't been resolved or should I open a new feature request?

**Comment by samtstern** [comment]
@kroikie are there any plans for Remote Config upload support in the CLI?

**Comment by xalikoutis** [comment]
until the upload implementation in firebase-cli, do ti in bash
this is a script for cloning a remote config between two projects

`#!/bin/bash

set -e
#set -x
umask 0022

while getopts f:t: option; do
  case "${option}" in
    f) PROJECT_A=${OPTARG};;
    t) PROJECT_B=${OPTARG};;
  esac
done

TOKEN=`google_token.sh | jq -rM '.access_token'`
OUTPUTFOLDER="tmp_asset_data"


_tmp=$(mktemp response.XXXXXXXX)
trap "rm -f ${_tmp}" 0 1 9 15

curl -o ${_tmp} -s -H "Authorization: Bearer $TOKEN"  "https://firebaseremoteconfig.googleapis.com/v1/projects/$PROJECT_A/remoteConfig"

curl --compressed -H "Content-Type: application/json; UTF8" -H "Authorization: Bearer $TOKEN" -H "If-Match: *" -X PUT -d "$(jq -rcM '.' ${_tmp})"  "https://firebaseremoteconfig.googleapis.com/v1/projects/$PROJECT_B/remoteConfig?validateOnly=false"`

**Comment by xalikoutis** [comment]
I ll make a PR tomorrow with the upload feature

**Comment by samtstern** [comment]
Closing this because `firebase deploy` supports Remote Config, see #2899

**Comment by gregfenton** [comment]
Is it me, or is there a lack of documentation for `remoteconfig` in the CLI documentation, specifically as a `deploy` target?

https://firebase.google.com/docs/cli#partial_deploys

**Comment by biriukov-openpet** [comment]
@gregfenton , yeah, for me it shows only 3 commands available for remoteconfig.
Looks like something should be mentioned for deploy command but there is nothing
