### ISSUE TITLE
Firebase emulator export doesnt work

### ISSUE THREAD

**Issue by hoangofHUST** [firebase/firebase-tools#2218]
**firebase-tools:** 8.2.0
**Platform:** macOS, Ubuntu 19.10

### Step to reproduce
Following [that comment](https://github.com/firebase/firebase-tools/issues/1167#issuecomment-599410243). In `termial 1`, start firebase emulator with 
```
$ firebase emulators:start --only firestore --project default
``` 
Then use API connect to that firestore, add some docs. At first, firestore is empty, now it has some. In `terminal 2` call firebase emulator export with command
```
$ firebase emulators:export $[dir] --project default
```
Next, terminate emulator in `terminal 1` and start again with import
```
$ firebase emulators:start --only firestore --import $[dir] --project default
```
Finally, use API to see what is in firestore, but got empty.

[Here](https://github.com/hoangofHUST/firebase-emulator-export) is my code connect firestore and some detail descriptions. Please take a look and tell me any idea @samtstern

**Comment by samtstern** [comment]
@hoangofHUST thanks for the excellent steps to reproduce!  I cloned your repo and then ran this command:

```
firebase emulators:start --import=seed --only firestore
```

I was able to see some data in the `users` collection such as `/users/l.x.duy@azoom.jp` so it seems to be working for me. 

Does that fail for you?  Is there something I am missing?

**Comment by samtstern** [comment]
Ah I see here you are using the firebase testing SDK inside your express app:
https://github.com/hoangofHUST/firebase-emulator-export/blob/master/firestore.js#L1

This SDK is only recommended for unit tests.  Instead you want to connect your app to the emulator in one of two ways.

**1) Admin Node.js SDK**
If you're connecting from your server just use `firebase-admin` and make sure you set the `FIREBASE_EMULATOR_HOST=localhost:8080` environment variable.  Then when you run `admin.initializeApp()` we will automatically connect to the Firestore emulator.

**2) Web JavaScript SDK**
If you are connecting from a web app you need to point your code at the emulator:
```js
var db = firebaseApp.firestore();
if (location.hostname === "localhost") {
  db.settings({
    host: "localhost:8080",
    ssl: false
  });
}
```

I hope that helps!

**Comment by hoangofHUST** [comment]
@samtstern i wanna use emulator for unit test. I wanna start emulator with some data from the beginning like seed data not call api to create. Any idea?

**Comment by samtstern** [comment]
@hoangofHUST I see in your test code you're doing this:`{ projectId: "staging-bengal" }`

Are you starting the Firestore emulator with the same project?  See if adding `--project=staging-bengal` to your `emulators:start` command helps.

Each `projectId` is a separate database but import only supports a single projectId.

**Comment by samtstern** [comment]
Ah actually I can see here that `default` is a different project:
https://github.com/hoangofHUST/firebase-emulator-export/blob/master/.firebaserc

So that would explain it!

**Comment by azoom-n-d-hoang** [comment]
thank so much. that is it @samtstern

**Comment by hoangofHUST** [comment]
@samtstern thank you so much. That it is

**Comment by samtstern** [comment]
Glad we could solve it!  Thanks again for providing so much detailed information.
