### ISSUE TITLE
Error Upgrading to 3.x.x: Must run tools:migrate from a directory with a firebase.json

### ISSUE THREAD

**Issue by JimTheMan** [firebase/firebase-tools#222]
I am following this guide: https://firebase.google.com/support/guides/firebase-web
to upgrade this project: https://github.com/ng-nj/ng-nj.org
from angularfire 2.0.2 to 3.x.x

I installed the firebase-tools and successfully logged in, but when I run migrate I'm getting this error: 

```
Error: Must run tools:migrate from a directory with a firebase.json
```

The problem is, my project never had a firesbase.json file...

**Comment by JimTheMan** [comment]
Fixed by running `firebase init`, but after running `firebase tools:migrate` my package.json still has angularfire at 2.0.2 :/

**Comment by abehaskins** [comment]
Hey Jim

The migration tool here is unrelated to AngularFire and is specifically for upgrading your Firebase.json file, so if you're not using Firebase Hosting (or another service which requires the `firebase.json`) then you wont be able to run it. 

Check out the [AngularFire](https://github.com/firebase/angularfire/blob/master/docs/migration/1XX-to-2XX.md) migration guide for AngularFire specific migration info!

All the best,
abe
