### ISSUE TITLE
Firebase CLI Anonymous Login

### ISSUE THREAD

**Issue by adik69** [firebase/firebase-tools#2220]
Hey Firebase Team,

I searched all over the internet from past two Days . I still can't find Anonymous Login through Firebase CLI. 
This feature is used in other platforms
Authenticating with Anonymous login with javascript
Authenticating with Anonymous login with android
Authenticating with Anonymous login with ios

But I couldn't found anything about "Authenticating with Anonymous login with firebase cli"

It would be great if you update me with your knowledge.

**Comment by samtstern** [comment]
@adik69 anonymous login is part of Firebase Auth.  Firebase Auth is for **users** of Firebase applications.

The Firebase CLI is for **developers** of Firebase applications.  There is no concept of anonymous auth here.  You can only authenticate as the project developer (`firebase login`) or as a Google Cloud service account (with `GOOGLE_APPLICATION_CREDENTIALS`).
