### ISSUE TITLE
Allow emulators to export on exit

### ISSUE THREAD

**Issue by samtstern** [firebase/firebase-tools#2224]
Originally requested through FIrebase support, there is some demand for a flag like this:
```
firebase emulators:start --import=./seed --export-on-exit
```

This would import from a location but save any mutations made on exit.

**Comment by michi88** [comment]
I've requested this indeed! Great that it is actually picked up here :). I could try to make a PR if that is appreciated. Let me know.

**Comment by samtstern** [comment]
@michi88 if you're interested in sending a PR for this I'd be happy to accept it.  But we have to follow a bit of a process:

1. First you and I should work out the full API change here
2. Then I'll "sponsor" your internal API proposal, we have a group of Firebasers that reviews any API change to our SDKs or the CLI. 
3. Once it's approved we can merge and release your PR, along with any edits suggested by the API review process (2).

Sound like something you're up for?  I know it sounds slow and bureaucratic but I'll be handling the bad parts mostly.

**Comment by michi88** [comment]
Great, I’m up for giving that a try! So let’s settle on the API. What do you think about the `—export-on-exit` flag? Should it just be a flag or accept a path where to export the data to? Should it require the `—import` flag and take that folder to export to by default?

My general use case here is with :exec in the ‘default’ `npm serve` command that would start emulators but the data is not gone when you stop / reload. Of course you can do an export first and all but that is too much explaining for new developers coming to a project and expect things to just work with a single `npm serve` command.

What might make sense though is that the `—import` dir contains seed data (that you store in a repo) for new setups but that you can use a different dir as your local data dir where we would export and import to on subsequent runs. So maybe we would add another `—seed` flag that is only imported when the `—import` dir is empty.

Not sure what would be best here. Let me know what you think.

**Comment by samtstern** [comment]
@michi88 thanks for asking all the right questions.  My personal take:

- I like the name `--export-on-exit`
- I think it should take an optional path `--export-on-exit=./some-path`.  When unspecified it would use the same path as `--import`.  If you do a bare `--export-on-exit` with no `--import=something` flag that's an error. So:

  * ✅ VALID: `emulators:start --import=./foo --export-on-exit`
  * ✅ VALID: `emulators:start --import=./foo --export-on-exit=./bar`
  * ✅ VALID: `emulators:start --export-on-exit=./bar`
  * ❌ NOT VALID: `emulators:start --export-on-exit`

If that sounds good to you I'll propose it to the API people.

**Comment by michi88** [comment]
I'm leaning towards that indeed as we have this --import flag already to work with.

On the other hand something like a --data-dir would maybe also make sense where we import from and export to. It feels a bit cumbersome that we need to set 2 flags in order to get this behavior (importing and exporting). 

I'd say the --import flag is super useful for seeding data for tests and the --data-dir is what you want during development.

The downside of this is that we're actually not really using it as a persistent data dir but only export on exit (which is not guaranteed to succeed). Unless we can change that and use it like that (in the future) but that is doubtful.

I'm ok with --export-on-exit as well though :).

**Comment by samtstern** [comment]
@michi88 totally makes sense, although right now we do want import and export to feel explicit and separate for the reason you said: they're one-time expensive operations.  Something like `--data-dir` implies that these emulators have a persistence layer, which they do not.

I'll go ahead and kick this off.

**Comment by samtstern** [comment]
Alright I sent out the API proposal so we'll see how it goes.

For googlers: http://go/firebase-emulators-export-on-exit

**Comment by samtstern** [comment]
@michi88 thanks for your patience, the API proposal was approved today!  I think this is all stated above but here's a succinct version of the proposal you can use for your implementation guide:

```bash
# VALID: This would export to the same directory as import (./data)
$ firebase emulators:start --import=./data --export-on-exit

# VALID: This would export to a brand new directory
$ firebase emulators:start --import=./data --export-on-exit=./new-data

# VALID: No import is required to export
$ firebase emulators:start --export-on-exit=./new-data

# INVALID: In this case we don't have an --import flag to infer the directory
$ firebase emulators:start --export-on-exit
```

Of course if your circumstances have changed and you no longer want to implement this just let me know and I will happily do the PR myself.

**Comment by michi88** [comment]
I’ll have a look right now, keep you posted.

**Comment by quantuminformation** [comment]
Waiting with anticipation. I didn't realise that data was not saved automatically after restarting and was wondering what was wrong with my app until I checked the db, I'm glad I'm not crazy.

**Comment by quantuminformation** [comment]
Nice one, works a treat

![image](https://user-images.githubusercontent.com/216566/88459314-b4155500-ce94-11ea-905f-81c7ee9bdd6c.png)

**Comment by salaryazdjerdi** [comment]
So when we want to export the data from the emulator do we just exit (control c on mac) and it will be pulled to the same path we used in $ firebase emulators:start --import=./data --export-on-exit ?

**Comment by samtstern** [comment]
@salaryazdjerdi yes exactly!

**Comment by quantuminformation** [comment]
If I delete all my data in the UI by clicking x on the root node, then restart then I still see the old data

using `--import=./seed --export-on-exit`

**Comment by samtstern** [comment]
@quantuminformation we really appreciate all of your feedback but please don't comment on old closed issues with new bug reports.  If you have an issue to report, start a new issue and follow the template (or find an existing open issue that is a duplicate and add a comment)

**Comment by quantuminformation** [comment]
Ok, sometimes I am reluctant because I don't want to create a new issue in case it's already a known one or its a feature by design. Will create a new one .

**Comment by steveoh** [comment]
Should this export auth accounts as well?

**Comment by yuchenshi** [comment]
@steveoh Yes it does by default if the Auth emulator is started.

**Comment by steveoh** [comment]
What are the exit methods that trigger export?
