### ISSUE TITLE
Provide a way to uninstall when using automatic install script

### ISSUE THREAD

**Issue by long1eu** [firebase/firebase-tools#2234]
There should be a way to uninstall when installing using automatic install script.

**Comment by abeisgoat** [comment]
Agreed. It's on the list.

**Comment by abeisgoat** [comment]
We now support `curl -sL firebase.tools | uninstall=true bash`

**Comment by abbaseid** [comment]
> We now support `curl -sL firebase.tools | uninstall=true bash`

Please update firebase docs on this command.
As it's not mentioned in this page: https://firebase.google.com/docs/cli/#install-cli-mac-linux
