### ISSUE TITLE
URL for local debugging vs production

### ISSUE THREAD

**Issue by QuantumInformation** [firebase/firebase-tools#2235]
I am running the emulator successfully with `firebase emulators:start --only functions --inspect-functions` and have changed my base path

`https://us-central1-svelte-fullstack-starter.cloudfunctions.net`
into
`https://localhost:5002/svelte-fullstack-starter/us-central1`

but it fails with net::ERR_SSL_PROTOCOL_ERROR

![image](https://user-images.githubusercontent.com/216566/81662353-be02ec80-943d-11ea-9a69-678d29c24203.png)

https://github.com/QuantumInformation/svelte-firebase-starter/blob/master/src/api.js#L4

### [REQUIRED] Environment info
**firebase-tools:** 8.2.0

**Platform:** MacOS

**Comment by samtstern** [comment]
Emulator URLs are not `https` they're just `http`, so try changing that.

**Comment by QuantumInformation** [comment]
Thanks that worked, I have a new error which I will add to new question if I can't figure it out.
