### ISSUE TITLE
v8.2 cors error when accessing emulated function

### ISSUE THREAD

**Issue by QuantumInformation** [firebase/firebase-tools#2236]
### [REQUIRED] Environment info

8.2

**firebase-tools:**

**Platform:**
MacOS
### [REQUIRED] Test case

Run `firebase emulators:start --only functions --inspect-functions` on this project

https://github.com/QuantumInformation/svelte-firebase-starter/blob/master/functions/src/index.ts#L30

### [REQUIRED] Steps to reproduce

If I try to access this from my local app with function served by the emulator
```js
exports.listUsers = functions.https.onRequest(async (req, res) => {
    res.set("Access-Control-Allow-Origin", "*");
    const data = await users_1.getSomeUsers(10);
    res.json(data);
});
```

### [REQUIRED] Expected behavior

Function to behave same as prod

### [REQUIRED] Actual behavior

I end up with

Access to fetch at 'http://localhost:5002/svelte-fullstack-starter/us-central1/listUsers' from origin 'http://localhost:5001' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by samtstern** [comment]
@QuantumInformation I can't reproduce this.  I created a brand new project with the Firebase Hosting and Functions emulators and wrote these functions:

```js
const functions = require('firebase-functions');

exports.withCors = functions.https.onRequest((request, response) => {
  response.set("Access-Control-Allow-Origin", "*");
  response.json({
    name: "withCors",
    date: new Date()
  });
});

exports.withoutCors = functions.https.onRequest((request, response) => {
  response.json({
    name: "withoutCors",
    date: new Date()
  });
});
```

Then I wrote this code on the page:
```
      document.addEventListener('DOMContentLoaded', function() {
        fetch('http://localhost:5001/fir-dumpster/us-central1/withCors')
          .then(response => response.json())
          .then(data => console.log("withCors", JSON.stringify(data)))
          .catch(e => console.error("withCors", e));

        fetch('http://localhost:5001/fir-dumpster/us-central1/withoutCors')
          .then(response => response.json())
          .then(data => console.log("withoutCors", JSON.stringify(data)))
          .catch(e => console.error("withoutCors", e));
      });
```

When I run it I only get errors from `withoutCors` not `withCors` so this is not a bug in the emulators:
<img width="574" alt="Screen Shot 2020-05-13 at 3 20 35 PM" src="https://user-images.githubusercontent.com/8466666/81855512-72c80700-952d-11ea-85d7-394e2116dfa6.png">

**Comment by samtstern** [comment]
@QuantumInformation if you're able to reproduce this with an empty project let me know.

**Comment by QuantumInformation** [comment]
I was testing a different function on my project and I was getting no cors errors:

https://github.com/QuantumInformation/svelte-firebase-starter/blob/master/functions/src/index.ts#L16

I will keep testing my app.
