### ISSUE TITLE
firebase deploy painfully slow due to API cloudscheduler.googleapis.com which is not even required

### ISSUE THREAD

**Issue by JerryGoyal** [firebase/firebase-tools#2243]
There's no job scheduler in cloud scheduler then why firebase cli is showing `required API cloudscheduler.googleapis.com is enabled` whenever I deploy any function? And it's taking upto a minute to finish this required API..is enabled task.

![image](https://user-images.githubusercontent.com/7106086/82125775-de2c0600-97c5-11ea-9faf-0e11ed412dc0.png)

Command: `firebase deploy --only functions`

Output:

```
+  functions: Finished running predeploy script.
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
!  functions: missing required API cloudbuild.googleapis.com. Enabling now...
+  functions: required API cloudfunctions.googleapis.com is enabled
+  functions: required API cloudbuild.googleapis.com is enabled
i  functions: preparing functions directory for uploading...
i  functions: packaged functions (88.88 KB) for uploading
+  functions: functions folder uploaded successfully
i  functions: updating Node.js 10 function addUsertoDB(asia-east2)...
+  scheduler: required API cloudscheduler.googleapis.com is enabled
+  functions[addUsertoDB(asia-east2)]: Successful update operation. 
```

### [REQUIRED] Environment info

**firebase-tools:** 8.2.0

**Platform:** Windows

### [REQUIRED] Test case
Run this command to deploy function and observe the output: `firebase deploy --only functions`

### [REQUIRED] Steps to reproduce
1. make sure there's no google cloud scheduler task in your project.
2. Run this command to deploy function : `firebase deploy --only functions`
3.  observe the output.. it is showing `scheduler: required API cloudscheduler.googleapis.com is enabled`.

### [REQUIRED] Expected behavior
output of `firebase deploy --only functions` shouldn't contain `scheduler: required API cloudscheduler.googleapis.com is enabled` 

### [REQUIRED] Actual behavior
it is showing `scheduler: required API cloudscheduler.googleapis.com is enabled` 
```
+  functions: Finished running predeploy script.
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
!  functions: missing required API cloudbuild.googleapis.com. Enabling now...
+  functions: required API cloudfunctions.googleapis.com is enabled
+  functions: required API cloudbuild.googleapis.com is enabled
i  functions: preparing functions directory for uploading...
i  functions: packaged functions (88.88 KB) for uploading
+  functions: functions folder uploaded successfully
i  functions: updating Node.js 10 function addUsertoDB(asia-east2)...
+  scheduler: required API cloudscheduler.googleapis.com is enabled
+  functions[addUsertoDB(asia-east2)]: Successful update operation. 
```

**Comment by bkendall** [comment]
Thanks for the report.

I'm fairly certain that the CLI isn't waiting on the API to be enabled - that is a very fast endpoint and operation. The function being updated is the longer operation that is happening, it just happens to be that the cloud scheduler API line is the last one that's printed before the update of the actual function completes.

I'll triage this over to the Functions folks to take a look at - maybe they can improve the ui! @joehan

**Comment by JerryGoyal** [comment]
that could be the case but why cloud scheduler API is being enabled at the first place? I dont need it.

**Comment by bkendall** [comment]
Firebase Functions have a "scheduled function" feature which can be used to automatically run functions at intervals. Likely, the code is being broad about when it makes sure that API is enabled than it may need to be - unsure off the top of my head why that would be the case. Joe will be able to dig into it a bit and figure out if action needs to be taken.

Do you recall when the switch happened? If you know what previous version you were on, we might be able to diff back and see if something unintentionally changed.

**Comment by JerryGoyal** [comment]
I was in middle of enabling and implementing google scheduled functions for my project but couldn't figure out how to implement properly so I stopped. Later, when I started seeing the `Required API..` in logs I cross-verified that there's no left over scheduled function running in my project and there isn't (I attached the screenshot also in my post).

**Comment by bitttttten** [comment]
I had to upgrade to Blaze, and move off the free plan of Spark to enable Cloud Scheduling. It's mentioned [in the docs here](https://firebase.google.com/docs/functions/schedule-functions#before_you_begin).

I was planning on upgrading to Blaze anyway, but after I did this error went away.

**Comment by joehan** [comment]
Hey @JerryGoyal, thanks for pointing this out, there is definitely an easy UI improvement to be made here. To your original question, the message you are seeing isn't actually from trying to enable the Cloud Scheduler API, but rather from checking if it is already enabled - here's where it happens in the code: https://github.com/firebase/firebase-tools/blob/master/src/deploy/functions/createOrUpdateSchedulesAndTopics.ts#L27. 

The call to ```check(projectId, "cloudscheduler.googleapis.com", "scheduler", false);``` logs `scheduler: required API cloudscheduler.googleapis.com is enabled` if it the API is enabled, and nothing otherwise - that's why you suddenly started to see this line when you enabled the Cloud Scheduler API on your project. This call is super quick and shouldn't be slowing down your deploys in any meaningful way - however, we currently are making it in cases where we really don't need to. I'll follow up with a PR shortly to only make this check when its needed.

**Comment by ALEJANDROXGALLEGO** [comment]
Hello. My solution: Go to  path functions ( cd functions) then in the package.json change   node version 8 to 10.  "engines": {
    "node": "10"
  }.   And run NPM INSTALL. then cd .. and deploy again.

**Comment by Ashirkhan961** [comment]
> Hello. My solution: Go to path functions ( cd functions) then in the package.json change node version 8 to 10. "engines": {
> "node": "10"
> }. And run NPM INSTALL. then cd .. and deploy again.

Nothing is happening after try this method!

**Comment by ALEJANDROXGALLEGO** [comment]
In the path "funtions"

npm install --save firebase-functions@latest

**Comment by InfinityCoder88** [comment]
Hi guys, I have **Blaze** plan and I still get these errors:
`ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
+  functions: required API cloudbuild.googleapis.com is enabled
+  functions: required API cloudfunctions.googleapis.com is enabled
i  functions: preparing functions directory for uploading...`

On my second project on Firebase, any ideas why thanks in advance!
