### ISSUE TITLE
On firebase init - you only can choose projects where you are owner

### ISSUE THREAD

**Issue by pfiadDi** [firebase/firebase-tools#2255]
If I am Editor in a project I can't select the project when I init a new firebase project on my computer. I need to be an owner to select it from the list of existing projects.

Since the editor role has full access it doesn't make sense that an editor can't work on the project on his computer. 

Maybe it's on purpose but I thought it's not logical and considered it a bug.

### [REQUIRED] Environment info
**firebase-tools:**
firebase-tools 8.3.0

**Platform:**
Mac OS 10.12.16

### [REQUIRED] Steps to reproduce
- Create a new project 
- Add your colleague or a second Gmail user of yours as editor
- Run firebase init in your command line (logged in with the user which has the role "Editor") and choose to use an existing project => the project won't be in the list
- Change the editor to be an owner
- Run init again and the project appears now in the list

### [REQUIRED] Expected behavior

A list with all projects where my user has full access should appear

### [REQUIRED] Actual behavior

Only projects where my user is owner appear

### [REQUIRED] Test case
see above

And of course, if it's already clarified and I just missed, then I apologize for this ticket ;-)

**Comment by samtstern** [comment]
@pfiadDi that should not be the case, you should be able to init projects where you are Editor (as far as I know).

Can you try the API explorer for the REST API here and see if you are able to find the missing project in the REST API response (right side of the page):
https://firebase.google.com/docs/projects/api/reference/rest/v1beta1/projects/list?apix=true

That will help me determine if this is a Firebase CLI issue or an issue with the backend API.

**Comment by pfiadDi** [comment]
Hi @samtstern thank's for your quick response.
I just created a new project to reproduce it and I see it in the API AND the console.
Everything works as it should - sorry perhaps I made a mistake last week when I noticed it!
I'll close this ticket.
