### ISSUE TITLE
Firebase CLI installation fails if directory /usr/local/bin doesn't exist.

### ISSUE THREAD

**Issue by jotae85** [firebase/firebase-tools#2256]
### [REQUIRED] Environment info

**firebase-tools:** doesn't apply

**Platform:** macOS

### [REQUIRED] Test case

Installation of Firebase CLI fails on macOS if the directory `/usr/local/bin` doesn't exist. 

Workaround: create missing directory manually.
```
mkdir /usr/local/bin
curl -sL https://firebase.tools | bash
```

### [REQUIRED] Steps to reproduce

Make sure the the directory `/usr/local/bin` doesn't exist. 
Run `curl -sL https://firebase.tools | bash`

### [REQUIRED] Expected behavior

Firebase is installed successfully

### [REQUIRED] Actual behavior

Firebase installation fails. Output:
```
-- Checking for existing firebase-tools on PATH...
-- Checking your machine type...
[Binary URL] https://firebase.tools/bin/macos/latest
-- Downloading binary...
######################################################################## 100.0%#=#=#                                      ######################################################################## 100.0%#-#O=#  #                                  ######################################################################## 100.0% #-#O=#   #                                Warning: Failed to create the file /usr/local/bin/firebase: No such file or 
Warning: directory
                                                                           0.0%
curl: (23) Failed writing body (0 != 16360)
-- Setting permissions on binary...
chmod: /usr/local/bin/firebase: No such file or directory
bash: line 213: firebase: command not found
Something went wrong, firebase has not been installed.
Please file a bug with your system information on Github.
https://github.com/firebase/firebase-tools/
-- All done!
```

**Comment by mieliespoor** [comment]
Relates to: https://github.com/firebase/firebase-tools/issues/2019

**Comment by mieliespoor** [comment]
Some feedback from the situation in our case. We have the path `/usr/local/bin` existing, but the user don't have access to it. What we doing now is to install firebase as root and then run `chown` afterwards to ensure that our user will own the `/usr/local/bin/firebase`. This is working quite well and we are able to move forward with have firebase on our hosted build agents again.

**Comment by munjata** [comment]
Restarting my computer (Ubuntu) solved the issue.
