### ISSUE TITLE
firebase login is not working. 

### ISSUE THREAD

**Issue by bellyhold** [firebase/firebase-tools#226]
As soon as I click 'Allow' I get redirected and the page cannot be displayed. 

ERR_CONNECTION_CLOSED

Any ideas?

**Comment by mbleigh** [comment]
Try running `firebase login --no-localhost`

**Comment by stockholmux** [comment]
This really needs to be in the readme. I've been pulling my hair out trying to get this to work.

**Comment by bellyhold** [comment]
I actually got around this by opening the link in Edge instead of Chrome. I'm not 100% sure why it worked, but it may just be a Chrome specific issue.

**Comment by pgururaj** [comment]
firebase login --no-localhost - this really does the trick ! Thanks !

**Comment by Moonwalker7** [comment]
I tried firebase login --no-localhost, it asks for authorization code
