### ISSUE TITLE
Running multiple emulators with import/export

### ISSUE THREAD

**Issue by netbrain** [firebase/firebase-tools#2261]
I would like to run multiple firestore emulators, but as it is now it's not possible afaik. I'm capable of running the multiple instances of the emulator by executing the underlying jar file directly. However not in a way where i can use emulators:export functionality as well.

Is there any way i can run multiple emulators and still get the benefit of importing and exporting data from the emulator?

The reason I need this is for an event sourced application where I would like to compare the view/projections of the system before and after a full replay of the event log.

**Comment by samtstern** [comment]
> The reason I need this is for an event sourced application where I would like to compare the view/projections of the system before and after a full replay of the event log.

Can you explain this more?  Maybe there's some way we could support this better with a single Firestore emulator instance.

**Comment by netbrain** [comment]
I could use a single firestore instance yes. But then i would have to have
a multitenant structure in firestore. E.g a path prefix for each app.

However this would mean a change in the codebase. Which im not keen on
doing.

Why should I not be able to run multiple instances? And why is not import
and export a core functionality of the emulator itself? To me that seems
rather silly.

I would rather simply run the emulator jar file than have to rely on the
firebase cli utility. Running the emulator directly (jar) also has the
ability to seed it with a proper production export dump. Without the need
of handcrafting the metadata json file which the firebase cli utility
requires.  The differences between the tooling is also silly... So in
essence all that i require is that someone also implement a export function
in the emulator.

I'd be happy to do it, but i guess the emulator is closed source?

**Comment by samtstern** [comment]
@netbrain I am only trying to understand your use case so we can try and improve the emulators to make it work, I am not asking you to change your code.  I just don't yet understand from your original post what you are trying to achieve and how two emulators helps you do it.

Import/export *is* a core functionality of the emulator itself.  If you want you're welcome to read the source code for export and use the emulator REST API directly:
https://github.com/firebase/firebase-tools/blob/master/src/emulator/hubExport.ts#L60

Import is a command-line argument to the `jar` as you have already discovered.

**Comment by netbrain** [comment]
I didn't mean to come across as annoyed if that was your impression. Sorry,
if it was.

Im only starting a few facts I find peculiar as a design choice. Anyhoo the
Rest endpoint may prove to be my salvation. Good stuff.

Cheers.

**Comment by samtstern** [comment]
@netbrain if you do get a solution with the emulator REST API I'd like to see it.  Closing this for now.

**Comment by netbrain** [comment]
@samtstern this seems to work.

``` golang
func (f firebaseEmulator) Export(exportDir string) error {
	body := &bytes.Buffer{}
	jenc := json.NewEncoder(body)
	err := jenc.Encode(map[string]interface{}{
		"database":         fmt.Sprintf("projects/%s/databases/(default)", f.projectId),
		"export_directory": exportDir,
		"export_name":      time.Now().Format("2006-01-02T15:04:05.00000"),
	})
	if err != nil {
		return err
	}

	request, err := http.NewRequest(http.MethodPost, fmt.Sprintf("http://%s:%s/emulator/v1/projects/%s:export", f.host, f.port, f.projectId), body)
	if err != nil {
		log.Fatal(err)
	}
	request.Header.Set("Content-Type", "application/json")

	resp, err := http.DefaultClient.Do(request)
	if err != nil {
		return err
	}

	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("returned status not ok! got %d - %s", resp.StatusCode, resp.Status)
	}

	return nil
}
```

**Comment by NAllred91** [comment]
This would still be a nice feature to have. I'm running two instances of Firebase Emulator but I can't currently do an export of each one.  This seems like something that could be added to the UI though? Just a button to download an export would work.

Or if `--export-on-exit` worked when running two instances that would improve things as well.

As it is now, I can't seem to come up with a way to export my data from Firebase Emulator.
