### ISSUE TITLE
Firebase init issues for new project without location

### ISSUE THREAD

**Issue by ev45ive** [firebase/firebase-tools#2266]
### [REQUIRED] Environment info

firebase --version
8.3.0

**firebase-tools:**

Windows 10

**Platform:**

### [REQUIRED] Test case

firebase init fails with GCP location setting. 

### [REQUIRED] Steps to reproduce

firebase login
firebase init

### [REQUIRED] Expected behavior

firebase CLI tool should not fail
firebase CLI tool should not require user to stop mid process, google, figure out some settings in web console are missing (location) and restart whole proces

### [REQUIRED] Actual behavior

[error] Error: Failed to create Google Cloud project. See firebase-debug.log for more info.

Error: Cloud resource location is not set for this project but the operation you are attempting to perform in Cloud Firestore requires it. Please see this documentation for more details: https://firebase.google.com/docs/projects/locations

And its not documented 
https://github.com/firebase/firebase-tools/issues/1808#issuecomment-560403943
(https://firebase.google.com/docs/projects/locations), otherwise firebase init always fail for us with : Error: Cloud resource location is not set for this project but the operation you are attempting to perform in Cloud Firestore requires it. Please see this documentation for more details: https://firebase.google.com/docs/projects/locations

**Comment by ev45ive** [comment]
After manually fixing "location issue" it breaks again on indexes

> Firestore indexes allow you to perform complex queries while
> maintaining performance that scales with the size of the result
> set. You can keep index definitions in your project directory
> and publish them with firebase deploy.
> 
> ? What file should be used for Firestore indexes? firestore.indexes.json
> 
> Error: Error fetching Firestore indexes

**Comment by samtstern** [comment]
@ev45ive sorry you had such a bad experience.  So just so I can try to recreate and fix this: were you trying to initialize Firestore on a brand new project?  Anything else?

**Comment by ev45ive** [comment]
Yes. I managed through it finally, but I sometime do programming classes for folks to and those kind of pitfalls really demotivates people. If I can be in any assistance to make it better I gladly help @samtstern :-)

So to clarify:
- brand new project :
1. firebase login - went well
2. firebase init - selected all options, accepted all defaults

Failures:
- if I opt for new project and type name that already exits it fails moments later with cryptic 409 entity exists error. I figured it, but not before being confused and trying to google the error

- Then it fails because newly created project doesnt have location set (region) - would be perfect to choose if from CLI, but if that is not possible than pausing, showing explanation and link to web console settings would be much much better. Ideally pausing, and retrying - not exiting with error 

- then for new project there is no database so it fails to fetch indexes when creating indexes json. Again - if its not possible to create default firestore db from CLI then explanation + link to appropriate web console page would be very helpful.  Pause, wait for user do do step on web, then pres enter to retry - would be much better experience

Just think about someone who was promised that firebase would be much easier then full nodejs stack... and then they hit snug on "install" step. Not great customer experience ;-)

If I can help make it better in any way just let me know. :-)

**Comment by samtstern** [comment]
@ev45ive yeah that's really bad, I will try to fix this!  Thank you for all the steps.

**Comment by ev45ive** [comment]
I worked a lot with CLI tools like angular-cli, vue-cli create-react-app and those make it perfect for entry level people to get in, get some working results fast and keep going, not getting stuck frustrated. Developer experience is very important. :-) 

For more advanced dev / productivity would be great to provide answers as commandline arguments or save your choices to json and  use them as defaults. (its what vue-cli does - you step through your first project, save choices to json, and next time it ask - "hey I see those saved choices - do you want to use those or start over" :-) But this is just idea for future. Fixing the main flow is more important :-)

Thank you for so rapid response to this @samtstern BTW. Much appreciated! :-)

**Comment by samtstern** [comment]
@ev45ive take a look at #2271 I am trying to make the error messages much clearer.  The only one I am not addressing is "failed to fetch Firestore indexes" since that's a different issue that I am already working on elsewhere.
