### ISSUE TITLE
Option to persist firestore emulator data

### ISSUE THREAD

**Issue by arikanorh** [firebase/firebase-tools#2269]
We have already option to wipe data. I think persisting local data will be really cool for local test purposes

**Comment by samtstern** [comment]
@arikanorh the Firestore emulator can persist data using the `emulators:export` command!  And you can import it the next time using `emulators:start --import`.

We are working on bringing this functionality to the emulator UI in the future.

**Comment by sebolio** [comment]
> @arikanorh the Firestore emulator can persist data using the `emulators:export` command! And you can import it the next time using `emulators:start --import`.
> 
> We are working on bringing this functionality to the emulator UI in the future.

Thanks a lot for that! Just tested and it works great. Hopefully some day you add an option to run the export from inside the emulator, instead of requiring to open a new terminal.

**Comment by akbarbutt786** [comment]
> In case anybody comes along and wants a single command solution, try:
> 
> ```
> firebase emulators:start --import=./<dir-name> --export-on-exit
> ```
> 
> this will look in `./<dir-name>` for firebase's export information. When you exit it will save your data to `./<dir-name>`.
> 
> One command to rule them all 🍻

Thanks
