### ISSUE TITLE
Emulator doesnt update functions

### ISSUE THREAD

**Issue by arikanorh** [firebase/firebase-tools#2270]
### [REQUIRED] Environment info

**firebase-tools:** 8.4.0

**Platform:** Windows

### [REQUIRED] Steps to reproduce
1. Start emulator.
2. Make sure your functions are working
3. Make a change on a function

### [REQUIRED] Expected behavior
Function should be hot reloaded

### [REQUIRED] Actual behavior
It doesnt

I've started local emulator. I succesfuly launched hosting, firestore and functions. My functions are working correctly.

But when i changed my functions, it didnt hot reload even if the console says

`i  functions: Watching "D:\workspace\over-track\functions" for Cloud Functions...`

Does emulator supposed to hot reload changed functions or do i need to recompile them and restart emulator which wipes my firestore data etc.?

**Comment by samtstern** [comment]
@arikanorh if your functions are written in JavaScript then hot reload should just work.  If you're using TypeScript you'll need to compile them yourself, and then we will hot-reload the compiled results.

You can use `tsc -c` to run the TypeScript compiler automatically.

**Comment by arikanorh** [comment]
When i compiled it, it is hot reloading. Thanks. Would love to auto compile as well :)

**Comment by samtstern** [comment]
@arikanorh check out the npm package `concurrently`:
https://www.npmjs.com/package/concurrently

This will let you run `tsc -w` and `firebase emulators:start` at the same time.
