### ISSUE TITLE
Emulator UI not serving UI when open in port 6000

### ISSUE THREAD

**Issue by dutzi** [firebase/firebase-tools#2276]
### [REQUIRED] Environment info

**firebase-tools:** 8.4.0

**Platform:** macOS 10.15.4 (19E287)

### [REQUIRED] Test case

I just initialized a new project, chose port 6000 for the UI and started the emulators, I got the following in the console:

```

┌───────────┬────────────────┬─────────────────────────────────┐
│ Emulator  │ Host:Port      │ View in Emulator UI             │
├───────────┼────────────────┼─────────────────────────────────┤
│ Functions │ localhost:5011 │ http://localhost:6000/functions │
├───────────┼────────────────┼─────────────────────────────────┤
│ Firestore │ localhost:8100 │ http://localhost:6000/firestore │
├───────────┼────────────────┼─────────────────────────────────┤
│ Hosting   │ localhost:5010 │ n/a                             │
└───────────┴────────────────┴─────────────────────────────────┘
```

But when accessing http://localhost:6000/ I got a message from Chrome saying the site is offline:

```
This site can’t be reachedThe webpage at http://localhost:6000/functions might be temporarily down or it may have moved permanently to a new web address.
```

I tried running `lsof -i :6000` and found no process listening on that port.

But, when changing the port to 9292 the UI did load.

### [REQUIRED] Steps to reproduce

See above.

### [REQUIRED] Expected behavior

I see the UI

### [REQUIRED] Actual behavior

UI isn't loaded

See logs:

[firebase-debug.log](https://github.com/firebase/firebase-tools/files/4667844/firebase-debug.log)
[ui-debug.log](https://github.com/firebase/firebase-tools/files/4667845/ui-debug.log)
[firestore-debug.log](https://github.com/firebase/firebase-tools/files/4667846/firestore-debug.log)

**Comment by samtstern** [comment]
@dutzi you're right, I am able to reproduce this easily.  I have to look into why this port would be special.

**Comment by samtstern** [comment]
I see some references online for these ports being used for X Window:
http://www.networksorcery.com/enp/protocol/ip/ports06000.htm

However I am able to get ports like `6001` and `6060` to work ... only exactly `6000` is a problem!

**Comment by dutzi** [comment]
This does not seem like an issue with the UI, running `serve -p 6000` or `python -m SimpleHTTPServer 6000` doesn't work as well...

**Comment by dutzi** [comment]
This helps: https://stackoverflow.com/questions/4313403/why-do-browsers-block-some-ports/22622633#22622633

**Comment by samtstern** [comment]
@dutzi good find!  Maybe we can use that list to add a warning to the UI.
