### ISSUE TITLE
request is deprecated

### ISSUE THREAD

**Issue by aravindvnair99** [firebase/firebase-tools#2279]
Issue: https://github.com/request/request/issues/3142
Solution: https://github.com/request/request/issues/3143

**Comment by samtstern** [comment]
@aravindvnair99 thanks for filing this!  We are already working hard to remove all usage of `request` within `firebase-tools`.  @bkendall specifically has already made some good progress and has more to come. 

Going to close this issue since Bryan is already tracking this work elsewhere.
