### ISSUE TITLE
Add predeploy option for Firestore deployments

### ISSUE THREAD

**Issue by IchordeDionysos** [firebase/firebase-tools#2280]
Similar to the `predeploy` configuration for function deployments it could be helpful to have such a config also for Firestore deployments.

**Use Case:**
Once you use the [protobuf-rules-gen plugin](https://github.com/FirebaseExtended/protobuf-rules-gen) or you have a lot of rules, it makes sense to split the rules into separate files and generate one `firestore.rules` file out of it.

This is similar to writing your functions in Typescript, where you have to compile TS to JS first.
You have to generate the rules file before deployment.

**Suggestion:**

Allow this in the `firebase.json`:

```json
"firestore": {
  "rules": "firestore.rules",
  "indexes": "firestore.indexes.json",
  "predeploy": [
    "node generate_rules.js"
  ],
},
```

**Comment by IchordeDionysos** [comment]
For anyone wondering about this:

This is already supported out of the box for any target!

Just configure Firestore like this and it just works: :) 

```json
"firestore": {
    "rules": "firestore.rules",
    "indexes": "firestore.indexes.json",
    "predeploy": [
      "echo \"Pre Firestore deploy\""
    ]
  },
```

Should also work for Hosting, Storage and the Realtime database 😍💪

**Comment by samtstern** [comment]
@IchordeDionysos really glad this works!  I didn't know that either, but this is great for compiling rules.
