### ISSUE TITLE
Firebase cloud function deploy privately

### ISSUE THREAD

**Issue by mcappitelli** [firebase/firebase-tools#2285]
The current code only allows to deploy a cloud function with `members: ["allUsers"]` , which makes the function "public" by default.

This leads to a situation, if I deploy a "private" function, i need to run a script afterwards to remove the access right `allUsers` afterwards.

It would be nice to have this as variable available, to enable user group definition during deploy.

https://github.com/firebase/firebase-tools/blob/4824697ea6ce25b8d907212ff5b46dfbba4d63d0/src/deploy/functions/release.js#L26-L34

**Comment by mbleigh** [comment]
The Firebase CLI is intended to deploy publicly accessible Cloud Functions.
At present, the best way to deploy private functions with the gcloud CLI
instead.

Can you describe your use case a bit so we can understand why you are using
private http functions with Firebase?

**Comment by mcappitelli** [comment]
My intention is to create an additional endpoint for some backend servers to interact with the database. For this servers I would like to control access via service accounts. At the moment I change the access rights during deployment with some postdeploy scripts. But it would be more convenient to control access rights right away.
Of course, google cloud function would also work, but this would need to be handled with a separate dev/ops environment.
So the idea would be, the control the access rights as optional flag like the region parameter.

**Comment by mbleigh** [comment]
Understood. I'd encourage you to submit a [feature request](https://firebase.google.com/support/troubleshooter/report/features) in addition to this issue. There's a good bit of nuance in how this would need to be implemented, and it's not a request we've heard often so for the time being it's not super-likely to be prioritized. Nevertheless, thanks for the feedback!

**Comment by raiperez** [comment]
Hi @mbleigh, I'm facing the same situation. Has there been any change since this discussion - perhaps default role bindings are configurable now?


What I find interesting is that private cloud functions should not be deployed using firebase CLI. What is the recommended way for dealing with private admin functions that interact with firebase project databases / etc? Do you have any references to share? Thanks

**Comment by mbleigh** [comment]
Oh, this is actually possible now! If you use the `invoker` option you can set one or more service accounts that should have access, or you can set it to `private` to only allow project-wide access:

```ts
export const privateFunction = onRequest({
  invoker: 'private'
}, (req, res) => { /* your code here */ });
```

**Comment by Thaina** [comment]
@mbleigh Do we have any sample to use invoker with service account?

I wish I could have a function that only callable by authenticated user, without the need to check guard in the code directly

Also with the invoker, would it apply rate limit on the unauthorized failed call ?
