### ISSUE TITLE
Original 404 Page Showing Instead of Custom 404 Page

### ISSUE THREAD

**Issue by kidsonfilms-python-rules** [firebase/firebase-tools#2289]
### [REQUIRED] Environment info

**firebase-tools: 8.4.0**

**Platform: Windows**

### [REQUIRED] Test case

Index.html
```
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
</head>
<body>
	<p>this is the index page</p>
	<a href="ddddd">404 page</a>
</body>
```
404.html
```
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
</head>
<body>
	<p>this is the 404 page</p>
	<a href="index.html">home page</a>
</body>
</html>
```
### [REQUIRED] Steps to reproduce

   run `firebase init --hosting`
   replace the `index.html` with the first code and and `404.html` with the second code.
run `firebase serve`
### [REQUIRED] Expected behavior
   the 404 page we made shows up.

### [REQUIRED] Actual behavior
  the original 404 page made by firebase shows up.

**Comment by aravindvnair99** [comment]
@kidsonfilms-python-rules  Unable to reproduce your bug. I'm getting the correct pages just as configured. Also, `firebase init --hosting` is not a valid command. Make sure you have installed `firebase-tools` correctly.

**Comment by samtstern** [comment]
@kidsonfilms-python-rules can you show your `firebase.json` file?

**Comment by kidsonfilms-python-rules** [comment]
@aravindvnair99 use `firebase init` instead and choose hosting.

**Comment by kidsonfilms-python-rules** [comment]
@samtstern here is the firebase.json
[firebase.zip](https://github.com/firebase/firebase-tools/files/4698285/firebase.zip)

**Comment by aravindvnair99** [comment]
> @aravindvnair99 use `firebase init` instead and choose hosting.

@kidsonfilms-python-rules Yes, I did that. I initialised only hosting and added the files you gave.

> @samtstern here is the firebase.json
> [firebase.zip](https://github.com/firebase/firebase-tools/files/4698285/firebase.zip)

I added this as well and things seem to be working for me. I'm unable to reproduce your issue. Here is what I did: [sample.zip](https://github.com/firebase/firebase-tools/files/4699781/sample.zip) Is it the same as how you have configured?

**Comment by kidsonfilms-python-rules** [comment]
After getting rid of all deploys and deploying it, the 404 page is viewable.
