### ISSUE TITLE
App Distribution - Something went wrong. "my.apk" failed to upload.

### ISSUE THREAD

**Issue by Mustafax06** [firebase/firebase-tools#2299]
### Environment info

**Platform**
Mac OS Catalina V10.15.4 
Chrome V83.0.4103.61 (Official Build) (64-bit)

### Test case
N/A

### Steps to reproduce
Just tried to upload my APK. (Production APK and it's on the market now)

### Expected behaviour
APK should be uploaded to the App Distribution tool

### Actual behaviour
something went wrong. "my.apk" failed to upload.

**Comment by mbleigh** [comment]
We don't have enough information to help here, can you please run the command again with `--debug` and share detailed logs?

**Comment by Mustafax06** [comment]
I'm uploading my APK from the Firebase's interface and my app's signature was broken. So I fixed the signature problem and it worked.
