### ISSUE TITLE
firebase functions timing out: Server Error. connect ETIMEDOUT

### ISSUE THREAD

**Issue by yannicklaclau** [firebase/firebase-tools#2308]
### [REQUIRED] Environment info

**firebase-tools:**
8.4.1

**Platform:**
macOS
### [REQUIRED] Test case

running `firebase deploy --only functions:my-function-name` results in timeout server errors at least 9 out of 10 attempts
### [REQUIRED] Steps to reproduce

`firebase deploy --only functions`
on all functions or just one, same result - server errors, timeouts

### [REQUIRED] Expected behavior

successful deployment of functions!
### [REQUIRED] Actual behavior

ETIMEDOUT errors...

So, I receive an email saying that Node 10 is now in general availability and Node 8 functions will soon be deprecated.

I decide to act on this email and switch my functions to Node 10. And everything just hangs - whether deploying all, some, or single functions.

I switch back to Node 8, and everything works again...

For info, if perhaps this is relevant for the firebase team: all my functions are deployed to Frankfurt, europe-west3.

**Comment by samtstern** [comment]
@yannicklaclau sounds like there's something going on with the Cloud Functions backend and not the Firebase CLI.

Could you file an issue here:
https://issuetracker.google.com/issues?q=status:open%20componentid:187195

Make sure you include your project ID!
