### ISSUE TITLE
On database:set: Error: Path must begin with /

### ISSUE THREAD

**Issue by PAK90** [firebase/firebase-tools#231]
Running this command: `firebase database:set --project MyProject / myJsonData.json` gives me the error: `Path must begin with /`. Which it does. I want to erase existing data in the root of my project and upload my new json. Tried putting the `/` in quotes (" and ') but no luck.

**Comment by PAK90** [comment]
Turns out the answer is to put `//` as the path. Now I get an `Unexpected error while setting data`, but that's another issue.

**Comment by Capdt** [comment]
This worked for me.
`firebase database:set //new_node my-data.json`
This made a new node called **new_node** in the database for the project that I'm initialized too and uploaded the json data to it.
