### ISSUE TITLE
In some cases, reading a sub-collection will fail in Emulators, but work in production

### ISSUE THREAD

**Issue by dutzi** [firebase/firebase-tools#2313]
### [REQUIRED] Environment info

**firebase-tools:** 8.4.1

**Platform:** macOS 10.15.4 (19E287)

### [REQUIRED] Test case

Create a new Firebase project using the CLI tools (`firebase init`) and follow the STR below.

### [REQUIRED] Steps to reproduce

1. Using the web SDK run the following:

```
firebase.firestore().doc('/foo/bar/zoo/duck').set({wtf: true})
```

2. Open the Emulators UI.
3. Navigate to the Firestore Emulator

### [REQUIRED] Expected behavior

You should see the `foo` collection in the root level.

### [REQUIRED] Actual behavior

You can't see the `foo` collection in the root level.

`{wtf: true}` is only accessible when you type `/foo/bar/zoo/duck` in the breadcrumbs.

**Comment by dutzi** [comment]
**Update:** If I run the following I see `foo` in the UI:

```
firebase.firestore().doc('/foo/bar').set({something: true})
```

**Comment by 4mitabh** [comment]
The issue is a bit more serious than just collections not appearing in the UI.
Reads for '/foo/bar' will also fail. The same read succeeds on the real firestore.

**Comment by samtstern** [comment]
@dutzi @4mitabh this sounds like it's this issue:
https://github.com/firebase/firebase-tools-ui/issues/273

I would suggest continuing the discussion over there.
