### ISSUE TITLE
"firebase serve --only hosting,functions" command gives an errror: Cannot find what targets to deploy

### ISSUE THREAD

**Issue by nspeedzy** [firebase/firebase-tools#2315]
So i just created a project in firebase. I wanted to see how the project looked like in the browser. So i ran `firebase serve --only hosting,functions`, in order to see what is the result in the browser. But then i get an error.

### [REQUIRED] Environment info

**firebase-tools:** 8.4.1

**Platform:** Windows 10

### [REQUIRED] Test case

This issue occured when I used the Firebase CLI.

### [REQUIRED] Steps to reproduce

1. Ran `firebase init hosting`
2. Then i ran `firebase init functions`
3. Ran `firebase serve --only hosting,functions`
3. Bumped into the error

### [REQUIRED] Expected behavior

Firebase should have loaded the local client into my browser

### [REQUIRED] Actual behavior

Bumped into an error with the following log:
```
Error: Cannot understand what targets to deploy. Check that you specified valid targets if you used the --only or --except flag. Otherwise, check your firebase.json 
to ensure that your project is initialized for the desired features.
```

**Comment by samtstern** [comment]
@nspeedzy are you using Powershell? I think this may be this problem:
https://stackoverflow.com/questions/11990688/powershell-is-removing-comma-from-program-argument

The solution is to add quotes:
```
firebase serve --only "hosting,functions"
```

**Comment by nspeedzy** [comment]
Hey @samtstern thanks for giving me a solution! If you didn't know, I trust firebase and firebase only to host most of my nodejs apps.

**Comment by samtstern** [comment]
@nspeedzy so did the solution work for you?  If so we should close this issue.

**Comment by nspeedzy** [comment]
@samtstern Yes! You can close this issue now
