### ISSUE TITLE
Standalone firebase causing issues with emulator--inspect-functions option

### ISSUE THREAD

**Issue by mwarthen** [firebase/firebase-tools#2320]
firebase-tools:8.4.1 (actually using standalone)

Platform:macOS

### [REQUIRED] Test case
with standalone firebase installed:
running emulator for functions with --inspect-functions options yields node module loading error: Cannot find module '/Users/mwarthen/dev/projects/{repo}/functions/--inspect=localhost:9229

### [REQUIRED] Steps to reproduce
run emulators:start --only functions --inspect-functions

### [REQUIRED] Expected behavior
run emulator in debug mode for debugging

### [REQUIRED] Actual behavior
firebase exits worker processes and hangs in await state, error is,

Error: Cannot find module '/Users/mwarthen/dev/projects/{repo}/functions/--inspect=localhost:9229'
repo: actual name left out for privacy concerns, this happens for me with any functions project following the steps above.

Upon investigation is appears to have something to do with the embedded node/firepit implementation once the emulator "determines" the node binary to run (with standalone in my configuration it appears it likely that the node binary set as process.execPath resolves to the standalone firebase /usr/local/bin/firebase). this secondary execution from the emulator clobbers the config and option parameter behavior and instead treats all parameters as scripts to be loaded. In this case it attempts to load the (converted) -inspect parameter (functions emulator converts --inspect-functions to node's -inspect:port parameter) as a module reference, hence the above error.

**Comment by abeisgoat** [comment]
huh, interesting, thanks for the report, will take a look

**Comment by abeisgoat** [comment]
This an issue with this line https://github.com/firebase/firebase-tools/blob/1668f28c3973d58eb957ce51f2b05f7d7834674a/standalone/runtime.js#L27

When Firepit pretends to be Node it assumes that the first argument is always the name of the script to run. In this case we're passing extra arguments to the node runtime before the script, so we just need to sniff out the script name more intelligently then pass the node runtime args via `execArgv`.

**Comment by mrpoptart** [comment]
This bug is happening again. 
```
mkdir test && cd test
firebase init
#functions, existing, no eslint, js
firebase emulators:start --inspect-functions
```
output: `Error: Cannot find module '/Users/user1/test/functions/--inspect=localhost:9229'`

**Comment by samtstern** [comment]
@mrpoptart the fix for this has been merged but not yet released, it will be in the next version (either `8.14.2` or `8.15.0`)
