### ISSUE TITLE
"NOT FOUND" error when using Firebase Function Emulator with React Native ios app

### ISSUE THREAD

**Issue by aleksejkozin** [firebase/firebase-tools#2329]
Hi,

I have a React Native ios app that calls a Firebase function. When I use production environment everything works fine. However when I use the Firebase local emulator I get **"NOT FOUND"** error. I do use `useFunctionsEmulator` with the emulator endpoint `http://localhost:5001/` but it doesn't help.

What is more odd when I try to use the whole function address instead of the emulator endpoint:
`useFunctionsEmulator("http://localhost:5001/react-native-showcase-381f9/us-central1/helloWorld");`
Everything works fine.

### [REQUIRED] Environment info

**firebase-tools:** 8.4.1

**Platform:** macOS

React Native: 0.62.2

Running an app inside iPhone emulator

### [REQUIRED] Steps to reproduce

```
exports.helloWorld = functions.https.onCall(() => {
  return ['lol', 'internet'];
});
```

```
> firebase emulators:start
...
✔  functions[helloWorld]: http function initialized (http://localhost:5001/react-native-showcase-381f9/us-central1/helloWorld).
```

```
...
functions().useFunctionsEmulator('http://localhost:5001/');
functions()
        .httpsCallable('helloWorld')()
        .then(response => {
          console.log(response);
        });
...
```

<img width="532" alt="Screenshot 2020-06-04 at 21 38 09" src="https://user-images.githubusercontent.com/6328300/83797717-bb498f00-a6ab-11ea-89b5-2d312113fe32.png">

### [REQUIRED] Expected behavior

Log some data into the console.

### [REQUIRED] Actual behavior

Getting **"NOT FOUND"** error.

**Comment by samtstern** [comment]
@aleksejkozin there's really nothing here to suggest that this is an issue with the Functions Emulator or the Firebase CLI.  I would suggest filing this issue on the React Native SDK repository.

Also in general this is not enough information to debug.  You should at least `catch()`the error and show the output.  It may give you some clues as to what is going wrong.

**Comment by ciocan** [comment]
Same issue here. React Native has nothing to do with it.
When I get  the emulator functions address I get "Not found"

![Screenshot 2021-02-15 at 21 18 48](https://user-images.githubusercontent.com/4984377/107993969-97c53b00-6fd3-11eb-9421-52ad92e15bfa.png)

Firestore emulator address responds with "ok"

Is this normal?

**Comment by samtstern** [comment]
@ciocan accessing the `/` path on the Functions emulator will always produce a Not Found error because there is no function there. The only part of the Emulators you should try to access directly in your browser is the Emulators UI, which is normally at port `:4000`

**Comment by AyazAI** [comment]
Getting the same issue in Chrome
![image](https://user-images.githubusercontent.com/45338553/158981784-46433301-ecb0-41b8-bc92-22ed494667c8.png)

**Comment by RandomToni** [comment]
Hello,

After a while I manage to find a solution. It was weird because it was working but all of a sudden it did not. 

The issue was caused because I was pointing to the wrong project, my GoogleService-Info.plist file was from one project but firebase CLI was pointing to another. Please make sure to point to the same project using `firebase use <project-name>`.
