### ISSUE TITLE
Error: Cannot find module '/home/dev/functions', when emulators start

### ISSUE THREAD

**Issue by lalPratheesh** [firebase/firebase-tools#2331]
I recently getting this error when starting the emulators using the command `npm run serve`.Using the latest version of firebase-tools 8.4.1.
My package.json file is shown below

> {
  "name": "functions",
  "scripts": {
    "lint": "tslint --project tsconfig.json",
    "build": "tsc",
    "serve": "npm run build && firebase emulators:start --only functions",
    "shell": "npm run build && firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "engines": {
    "node": "10"
  },
  "main": "lib/index.js",
  "dependencies": {
    "cors": "^2.8.5",
    "express": "^4.17.1",
    "firebase-admin": "^8.10.0",
    "firebase-functions": "^3.6.2",
    "stripe": "^8.50.0"
  },
  "devDependencies": {
    "@types/cors": "^2.8.6",
    "dotenv": "^8.2.0",
    "firebase-functions-test": "^0.2.0",
    "tslint": "^5.12.0",
    "typescript": "^3.8.0"
  },
  "private": true
}

**Comment by samtstern** [comment]
@lalPratheesh this is not enough information to debug.  At a minimum please show debug logs, ideally you could provide a way for us to reproduce this issue.  Otherwise we have to assume it's an error with your environment.
