### ISSUE TITLE
After Run Firebase Emulator Not Show UI on Localhost

### ISSUE THREAD

**Issue by iamrampukar** [firebase/firebase-tools#2332]
{
  "emulators": {
    "pubsub": {
      "port": 8085
    },
    "ui": {
      "enabled": true
    }
  }
}

**Comment by samtstern** [comment]
@iamrampukar please don't file empty or near-empty issues, this is not enough information to debug.

See:
https://stackoverflow.com/help/minimal-reproducible-example
