### ISSUE TITLE
Error: Cannot find module 'semver'

### ISSUE THREAD

**Issue by bandwiches** [firebase/firebase-tools#2336]
### [REQUIRED] Environment info

**firebase-tools:**

```
> firebase --version
pkg/prelude/bootstrap.js:1244
      throw error;
      ^

Error: Cannot find module 'semver'
Require stack:
-...\firebase\tools\lib\node_modules\firebase-tools\lib\bin\firebase.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1346:46)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at Module.require (pkg/prelude/bootstrap.js:1225:31)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (...\firebase\tools\lib\node_modules\firebase-tools\lib\bin\firebase.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Module._compile (pkg/prelude/bootstrap.js:1281:32)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '...\\firebase\\tools\\lib\\node_modules\\firebase-tools\\lib\\bin\\firebase.js'
  ],
  pkg: true
}
```

**Platform:** Windows 10 19041.264

### [REQUIRED] Test case

See above

### [REQUIRED] Steps to reproduce

firebase --version
firebase login
firebase init
firebase anything

### [REQUIRED] Expected behavior

I believe it opens a new browser window for me to login with.

### [REQUIRED] Actual behavior

It fails to do anything at all.

```
> firebase login --debug
pkg/prelude/bootstrap.js:1244
      throw error;
      ^

Error: Cannot find module 'semver'
Require stack:
- ...\firebase\tools\lib\node_modules\firebase-tools\lib\bin\firebase.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1346:46)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at Module.require (pkg/prelude/bootstrap.js:1225:31)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (...\firebase\tools\lib\node_modules\firebase-tools\lib\bin\firebase.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Module._compile (pkg/prelude/bootstrap.js:1281:32)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '...\\firebase\\tools\\lib\\node_modules\\firebase-tools\\lib\\bin\\firebase.js'
  ],
  pkg: true
}
```

**Comment by bandwiches** [comment]
Fixed.

```
Error: Cannot find module 'semver'
Require stack:
- ...\firebase\tools\lib\node_modules\firebase-tools\lib\bin\firebase.js
```
Delete the folder referenced (above) and re-run firebase (below)
```
> firebase login
```
It will take a while to rebuild the directory, but let it go and it will work.

**Comment by samtstern** [comment]
@bandwiches glad you fixed it, sounds like there was something strange happening in your local setup.  Going to close this issue as I'm not sure what further action we could take.

**Comment by lucasbarrosomk6** [comment]
> Fixed.
> 
> ```
> Error: Cannot find module 'semver'
> Require stack:
> - ...\firebase\tools\lib\node_modules\firebase-tools\lib\bin\firebase.js
> ```
> 
> Delete the folder referenced (above) and re-run firebase (below)
> 
> ```
> > firebase login
> ```
> 
> It will take a while to rebuild the directory, but let it go and it will work.

I am having a similar issue whenever I run firebase commands. you say "delete the folder referenced (above)" but you mention a file. What folder needs to be deleted?

**Comment by sanathmittal** [comment]
> > Fixed.
> > ```
> > Error: Cannot find module 'semver'
> > Require stack:
> > - ...\firebase\tools\lib\node_modules\firebase-tools\lib\bin\firebase.js
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Delete the folder referenced (above) and re-run firebase (below)
> > ```
> > > firebase login
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It will take a while to rebuild the directory, but let it go and it will work.
> 
> I am having a similar issue whenever I run firebase commands. you say "delete the folder referenced (above)" but you mention a file. What folder needs to be deleted?

yes please i am having same problem

**Comment by sanathmittal** [comment]
> 

not working for me please tell me which folder to deletee

**Comment by ShaliniPerera** [comment]
> please someone help i am stuck on this problem for days . kindly hellp

copy the file name that is shown in the require stack and remove the file name at the end. This would open the folder that the file is in.
Eg - 
This is the require stack file
...\firebase\tools\lib\node_modules\firebase-tools\lib\bin\firebase.js
So you can remove the firebase.js part (which is the file name)

So search for this in the search bar and the folder will be opened.
...\firebase\tools\lib\node_modules\firebase-tools\lib\bin

and then open the firebase CLI again, it will take a little time for everything to work out
Hope this helps.

**Comment by ankyAgrawal** [comment]
For me, the oAuth access token was no more valid. I was able to resolve this issue by logging out and logging back into Firebase. 



```node
firebase logout

firebase login
```

**Comment by Fahmiin-Abdullah** [comment]
Alternative solution that works for me. Completely delete the `firebase-tools` from the global `node_modules` file (as stated in the above thread) and then reinstall it using `npm i firebase-tools`

**Comment by Phant0m-a** [comment]
> firebase login

C:\Users\<username>\.cache\firebase\tools\lib\node_modules\firebase-tools\lib\bin

**Comment by Phant0m-a** [comment]
it says already logged in and this error 
Error: An unexpected error has occurred.
>
im still in firebase
