### ISSUE TITLE
Firebase cloud function process.env variables can be set from GUI but not from CLI?

### ISSUE THREAD

**Issue by JerryGoyal** [firebase/firebase-tools#2339]
I can create process.env variables from https://console.cloud.google.com/functions but I've to create this variables for each and every firebase cloud functions which is inefficient.

How can I create these process.env variables from code? while deploying cloud functions from my machine? If I can set it up from GUI then there must be a way to set it up from CLI. I couldn't find any documentation for this.

![image](https://user-images.githubusercontent.com/7106086/83953590-08219700-a85f-11ea-88d1-b7b273569edf.png)

**Comment by samtstern** [comment]
@JerryGoyal that's why we have commands like `firebase functions:config:set` which help you set global config for your functions.

**Comment by JerryGoyal** [comment]
Thanks sam, figured it later.
