### ISSUE TITLE
firebase.tools can't provide binaries for ARM devices

### ISSUE THREAD

**Issue by msisimko** [firebase/firebase-tools#2341]
I get an error trying to install Firebase CLI using the auto install script.

The auto install script is available on the [Firebase CLI Reference](https://firebase.google.com/docs/cli#mac-linux-auto-script) docs page.

### Environment info

**firebase-tools:** Not yet installed. Trying to install the latest version which as of this posting is version 8.4.2

**Platform:** Ubuntu Server 20.04 LTS 64-bit on Raspberry Pi 3.

### Test case

```sh
curl -sL https://firebase.tools | bash
```

### Steps to reproduce

On a fresh install of Ubuntu Server 20.04 LTS 64-bit on Raspberry Pi 3:

1. Install NVM

```sh
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
```

2. Install Node

```sh
nvm install node
```

3. Install Firebase CLI (firebase-tools) using auto install script

```sh
curl -sL https://firebase.tools | bash
```

### Expected behavior

Successful installation of Firebase CLI i.e. on terminal print:

```sh
-- firebase-tools@8.4.2 is now installed
-- All Done!
```

### Actual behavior

On running the following command:

```sh
curl -sL https://firebase.tools | bash
```

I get the following error:

```sh
-- Checking for existing firebase-tools on PATH...
-- Checking your machine type...
-- Downloading binary from https://firebase.tools/bin/linux/latest
######################################################################## 100.0%######################################################################### 100.0% ######################################################################## 100.0% ######################################################################## 100.0%
-- Setting permissions on binary...
bash: line 255: /usr/local/bin/firebase: cannot execute binary file: Exec format error
bash: line 262: e: command not found
Something went wrong, firebase has not been installed.
Please file a bug with your system information on Github.
https://github.com/firebase/firebase-tools/
-- All done!
```

**Comment by mthuong** [comment]
For me, it looks like a binary file @abeisgoat

**Comment by msisimko** [comment]
> Can you run `head /usr/local/bin/firebase` and let me know if it looks like a Node script or a binary file?

On running the above, here's the result I get

```sh
ELF>��@`b�@8
@&%@@@@@0pp@p@@@�`)�`) xh)xh�xh��.0$  ~) ~� ~�P��@�@DDxh)xh�xhP�tdp�p�Ep�E�g�gQ�tdR�tdxh)xh�xh��'�'/lib64/ld-linux-x86-64.so.2GNUGNU��(�
                                                        oC��H����YWS-�'�� @P�A�!U!�0�`HB)�BQ�"$LI�#$�dH� �
�QBB           �(�4! @&(
    	�`�"0
             B �A0�	x�6AP��
                                3� $!a��<T(�I�0��D``B�h�$@��Љ @���8�
                                                                    8AJ!Q�@`�-�@:P0 BVH@��@@
            :?�@ 0��)HX�	���2e
��L�,��H��8@�$�D	@

�P�
S~&�@FE
PQ��`E
��"(@���B
)`
  B��P�d"@����"�"0
�@
  ! Q�
      �L"0�Ԉ�0�@�""�X��B,0�
                            xP�@"PP�P4$@
@B�������&8΀Pa�A	!�@��P *0�t

```

Looks like a binary file.

**Comment by abeisgoat** [comment]
Whoops, looks like I missed the "Raspberry Pi" part in the original post. Since Pis are `arm` based devices, I would not expect our binaries to work on them. We should probably make it more clear that our binaries are for x86_64 machines only

**Comment by msisimko** [comment]
Thank you for the clarification @abeisgoat

**Comment by yogendra** [comment]
Is there any plan on making this? On ARM (Raspberry PI, Linux ARM 64 containers). 

NPM option on ARM64v8 required lot of things. ([Look here](https://github.com/yogendra/yogendra.me-v2/blob/c13f0844820e25e374eb6150753c040e5856a23d/.devcontainer/Dockerfile#L36))
Basically it needs node, npm and chromium to install firebase-tools npm package on arm64.

**Comment by niraldmello** [comment]
Any update? Is it possible now to install firebase tools on aarch64 (ARM64) Linux?

**Comment by niraldmello** [comment]
@abeisgoat is it difficult to get it to run on ARM64 Linux? It is already running on ARM64 MacBooks right? Why are ARM64 Linux on Chromebooks being ignored?

**Comment by bkendall** [comment]
@niraldmello unfortunately we don't have the capacity to fully support providing arm builds. Macs should be using the x86_64 builds via rosetta. Thanks for raising this and showing interest - I'll bring it up with some other folks and see if this can get more funding.

**Comment by niraldmello** [comment]
@bkendall thanks for the clarification. Is there a cloud based work around that can be used?

**Comment by PureTryOut** [comment]
Running Linux on a Apple silicon Macbook I just found out the Firebase CLI is impossible to use for me. I'm +1'ing the interest in an ARM Linux build. In the meantime it would be nice if the install script could at least warn that it's an (as of yet) unsupported platform rather than just failing due to an exec format error.

**Comment by PureTryOut** [comment]
So, Firebase CLI actually works just fine on Linux ARM (of course, why wouldn't it? It's all Javascript anyway), just the provided download doesn't. If you clone this repository from source and build natively on a Linux ARM machine, things work just fine.

So a few steps to get this working:

```
git clone https://github.com/firebase/firebase-tools.git
cd firebase-tools
npm install
chmod +x lib/bin/firebase.js
ln -s $PWD/lib/bin/firebase.js ~/.local/bin/firebase
```

Still a compiled binary would be preferable of course.

**Comment by PureTryOut** [comment]
I mean, sure, but how is that any different from using the Google-pre-built everyone downloads?

I have no choice, I need the Firebase CLI and it's on Linux ARM.
