### ISSUE TITLE
Depreciated dependencies (NPM packages)

### ISSUE THREAD

**Issue by danielcobo** [firebase/firebase-tools#235]
Upon running install these prompts show up

```terminal
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130

```

**Comment by darkmorpher** [comment]
tough-cookie error could be from your NPM version. It was updated since Firebase-tools v3.1 I think.

Latest Firebase-tools v3.2.0 uses node-uuid@1.4.7

**Comment by danielcobo** [comment]
Thanks @darkmorpher you were right about the tough-cookie error, since I was using LTS which came with an older version of npm.

This still leaves the `npm WARN deprecated node-uuid@1.4.7` unresolved.

**Comment by psigen** [comment]
I think this might be the cause of your warning as well: #296.
