### ISSUE TITLE
Firestore emulators is saving data into a real Firestore

### ISSUE THREAD

**Issue by francisrod01** [firebase/firebase-tools#2357]
## Environments

- firebase-tools: `8.4.2`
- OS: `Debian 4.9.210-1+deb9u1 (2020-06-07) x86_64 GNU/Linux`

## Actual behaviour

Seems like Firebase emulators save data to a real Firestore database. I can't emulate a cloud function to write after saving data if it saves in my real database. How could I fix that?

### Steps to reproduce

![103494490_3010120162358233_2624041519966970540_n](https://user-images.githubusercontent.com/4691768/84444263-c2c2e800-ac17-11ea-9d66-98693e6e7e5d.jpg)

![image](https://user-images.githubusercontent.com/4691768/84446133-43cfae80-ac1b-11ea-856a-34fff75e33a6.png)

When I save data I can see it saving on my Cloud firestore.

![image](https://user-images.githubusercontent.com/4691768/84446275-87c2b380-ac1b-11ea-8874-41030f016508.png)

And nothing stored on Emulators Suite.

![102428356_3010120859024830_3356036651630253015_n](https://user-images.githubusercontent.com/4691768/84444265-c3f41500-ac17-11ea-8b1d-5a7a791acfd2.jpg)

Could it be documented on this project?

- [Firestore emulator's connection - part of implementation][1]
- [Firestore - Connect your app and start Prototyping][2]
- [Firestore - Connect Your App to Multiple Database instances][3]
- [The same talk on Spectrum chat][4]

[1]: https://github.com/firebase/snippets-web/blob/f003ef8c725f0039215badc00f888c41620bb8d2/firestore/emulator-suite.js#L5-L12
[2]: https://firebase.google.com/docs/database/usage/sharding#connect_your_app_to_multiple_database_instances
[3]: https://firebase.google.com/docs/emulator-suite/connect_and_prototype#locally_initialize_a_firebase_project
[4]: https://spectrum.chat/firebase/general/firestore-emulators-is-saving-data-into-a-real-firestore~88de42a5-1c91-4cfa-b304-07a1606d5dcd

**Comment by francisrod01** [comment]
This refactor solves the firebase app initialization using emulators and also helps to use mocks tests further.

```js
const firebaseConfig = require('./_config-object.json');
  const settingsObj = {};

  // Initialize Firebase
  if (!firebaseInstance.apps.length) {
    const firebaseServices = firebaseInstance.initializeApp(firebaseConfig);
    settingsObj.app = firebaseServices;

    if (typeof window !== 'undefined') {
      firebaseServices.analytics();
    }
  }

  const emulatorsStart = () => {
    const db = firebaseInstance.firestore(settingsObj.app);

    db.settings({
      host: 'localhost:8080',
      ssl: false,
    });

    return db;
  }

  if (process.env.RUNNING_AT === 'localhost') {
    const emulatedFirestore = emulatorsStart();
    settingsObj.firestore = emulatedFirestore;
  } else {
    settingsObj.firestore = firebaseInstance.firestore(settingsObj.app);
  }

  // const database = firebaseInstance.firestore();
  const database = settingsObj.firestore;
....
```

**Comment by samtstern** [comment]
@francisrod01 thanks for sharing your solution!

**Comment by francisrod01** [comment]
You're welcome! I think it could be integrated into `firebase-tools`, so someone can run `firebase emulators:start` and the Emulator's database will be connected automatically instead of ours.
