### ISSUE TITLE
function ignored because the database emulator does not exist or is not running

### ISSUE THREAD

**Issue by ahmadalibaloch** [firebase/firebase-tools#2363]
### [REQUIRED] Environment info
 Package.json:
  "firebase-admin": "^8.12.1",
   "firebase-functions": "^3.7.0",

**firebase-tools:**
    8.4.2

**Platform:**
Windows
### [REQUIRED] Test case
firebase emulators:start

### [REQUIRED] Steps to reproduce
0. https://github.com/firebase/functions-samples/tree/master/child-count
1. stat emulators
2. start serving functions with database triggers
3. you will get the problem "function ignored"

### [REQUIRED] Expected behavior

functions should should connect with the firestore emulator

### [REQUIRED] Actual behavior
```
!  Your requested "node" version "8" doesn't match your global version "10"
i  functions: Watching "D:\Workspace\a\Cloud Functions\project\functions" for Cloud Functions...
+  functions[helloWorld]: http function initialized (http://localhost:5000/[project-id]/us-central1/helloWorld).
i  functions[countentitities]: function ignored because the database emulator does not exist or is not running.
```

**Comment by samtstern** [comment]
@ahmadalibaloch this is working as intended.  You are only running the Functions emulator, not the Database emulator.

If you want to run both, first run `firebase init emulators` and set up the Database emulator then run `firebase emulators:start` again.

**Comment by ahmadalibaloch** [comment]
From the emulator's UI i can access Firestore emulator and make changes to DB, everything is working fine.
 I have setup emulators with the `firebase init emulators` but when I serve the functions after starting emulators, it gives me the message `function ignored bcause the database emulator does not exist....`

**Comment by samtstern** [comment]
@ahmadalibaloch this just is not enough information to debug.  Please at least show debug logs from `emulators:start` that show the database emulator running but the functions emulator not recognizing it.
