### ISSUE TITLE
Rewrite for Cloud-Run Anthos

### ISSUE THREAD

**Issue by dejecj** [firebase/firebase-tools#2364]
When I try to deploy my firebase hosting config with a rewrite for a cloud run for anthos service it tells me that the service doesn't exist. Is there a specific way to do this with an anthos service? I have like 20 others using cloud-run fully managed but this doesn't seem to work and I can't find any documentation about this specific use case.

This is the error I get on firebase deploy: HTTP Error: 400, Cloud Run service `***` does not exist in region `us-central1` in this project.

**Comment by joehan** [comment]
Hey @dejecj , unfortunately, we don't support rewrites to Cloud Run Anthos yet. I'd recommend filing a feature request on this repo to if you'd like to see this in the future.

**Comment by yeldarby** [comment]
Any idea if connecting a Cloud Run for Anthos to a Firebase Hosting rewrite is now possible?
