### ISSUE TITLE
"Firebase serve" isn't hot reloading in WSL2

### ISSUE THREAD

**Issue by kangbojk** [firebase/firebase-tools#2366]
### [REQUIRED] Environment info

**firebase-tools:** 8.4.2

**Platform:** WSL Ubuntu 20.04

### [REQUIRED] Test case
run on local machine `firebase serve`
modify some code in repository, save and reload chrome

### [REQUIRED] Steps to reproduce

Start a firebase project with `firebase init`, install express, try accessing an endpoint.
Cloud function hot reloading works on WSL1, but after upgrade to WSL2, save in code editor doesn't reload.

### [REQUIRED] Expected behavior
Cloud functions in WSL2 should be hot reloading as WSL1.

### [REQUIRED] Actual behavior

After modifying code and saved in WSL1, there would be a line  `⚠  functions: .......` indicates hot reloading, but after switching to WSL2, nothing happened after saving the modified code.

**Comment by samtstern** [comment]
@kangbojk a few questions:

- Is there any difference if you use `emulators:start` instead of `serve`?
- Are your Cloud Functions written in JavaScript or TypeScript?  If it's TypeScript, have you run your build script?
- We don't actually log anything on hot reload, can you share the full message you used to see on WSL1?
- Are there any errors in your `firebase-debug.log`?

**Comment by kangbojk** [comment]
1. `emulators:start` and `serve` act identical. Both have hot reload in WSL1, but not in WSL2.
2. JavaScript 
3. The message `⚠  functions: Your GOOGLE_APPLICATION_CREDENTIALS environment variable points to ...` shows after hot reloading (in WSL1) indicates I use an environment variable for initializing with firebase config.
4. I assume there's no error. The log in WSL1 and WSL2 is almost same, just that WSL2 not showing any message for re-initialize firebase, denote that WSL2 is not hot reloading.

I'm not sure whether this bug is in firebase or WSL. Hot reloading for cloud function works well for me in WSL1, but somehow it stops to watch modified file in WSL2.

**Comment by kangbojk** [comment]
Just figure out where's the bug.
As mentioned in **https://github.com/microsoft/WSL/issues/4739**
In order to have hot reloading in WSL2, one need to edit code in WSL environment, eg. use vim to edit code in WSL2, which will trigger hot reloading. If use vscode/other editor in Windows, it won't trigger hot reloading in WSL2.
