### ISSUE TITLE
The Cloud Firestore emulator is not running

### ISSUE THREAD

**Issue by iamandreadompe** [firebase/firebase-tools#2367]
### [REQUIRED] Environment info

**firebase-tools:** v8.4.2

**Platform:** macOS

### [REQUIRED] Steps to reproduce

After update firebase-admin from 8.6.0 to 8.12.1 and firebase-functions from 3.3.0 to 3.7.0
my application seems not to work anymore. Every request to my local function (firebase serve) not work

### [REQUIRED] Expected behavior

 run "firebase serve" without warning

### [REQUIRED] Actual behavior

firebase serve OR. firebase serve --only function
return The Cloud Firestore emulator is not running, so calls to Firestore will affect production.

**Comment by samtstern** [comment]
@iamandreadompe this is not enough information to debug.  Please provide some minimal code we could use to reproduce this issue.

**Comment by samtstern** [comment]
Also if you are running `firebase serve --only functions` then this warning is correct.  If you can reproduce this with `firebase emulators:start` and without the `--only` flag then please reopen this issue.
