### ISSUE TITLE
Database disappears after restart of emulator

### ISSUE THREAD

**Issue by dongido001** [firebase/firebase-tools#2370]
### [REQUIRED] Environment info

**firebase-tools:**

**Platform:**
MacOS

### [REQUIRED] Steps to reproduce
Upload data to your Firebase database emulated environment

### [REQUIRED] Expected behavior

The database should be persistent on first import.

### [REQUIRED] Actual behavior

Database disappears when I restart the emulator

**Comment by samtstern** [comment]
@dongido001 this is working as intended.  The database emulators clear on each start.  For Firestore we support import/export and for RTDB we're working on it.

See:
https://github.com/firebase/firebase-tools/issues/2297
https://github.com/firebase/firebase-tools/issues/2224
https://github.com/firebase/firebase-tools/issues/2079
