### ISSUE TITLE
"firebase emulators:start" is not working locally to test cloud functions

### ISSUE THREAD

**Issue by amansingh2604** [firebase/firebase-tools#2382]
I am trying to test my https trigger functions through postman locally but it is not working. I am not able to get the data from firestore or any related job regarding firestore.

First i tried **firebase serve** locally to run my cloud functions but it is not working.
Then i tried **firebase emulators:start** locally but this command is also not working.

**Comment by samtstern** [comment]
@amansingh2604 when filing an issue please use the template.  Saying something is "not working" does not give us any of the information we need to help you.

If you're still having this issue, please open a new issue and fill in all of the required information.
