### ISSUE TITLE
Update to 8.4.3 failed and corrupted existing version 

### ISSUE THREAD

**Issue by voiceactivity** [firebase/firebase-tools#2383]
**Platform:**OS X 10.9.5 (13F1911)

### [REQUIRED] Test case:
Been prompted by the npm to update the firebase-tools: npm install -g firebase-tools

### [REQUIRED] Steps to reproduce:
$sudo npm install -g firebase-tools

### [REQUIRED] Expected behavior:
the firebase-tools should be updated to the newest v8.4.3

### [REQUIRED] Actual behavior
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
/usr/local/bin/firebase -> /usr/local/lib/node_modules/firebase-tools/lib/bin/firebase.js

> protobufjs@6.9.0 postinstall /usr/local/lib/node_modules/firebase-tools/node_modules/protobufjs
> node scripts/postinstall
> storage-engine@3.0.7 postinstall /usr/local/lib/node_modules/firebase-tools/node_modules/storage-engine
> node ./compatibility/detect.js

fs.js:115
    throw err;
    ^

Error: EACCES: permission denied, open '/usr/local/lib/node_modules/firebase-tools/node_modules/storage-engine/lib/compatibility/index.js'
    at Object.openSync (fs.js:439:3)
    at Object.writeFileSync (fs.js:1190:35)
    at /usr/local/lib/node_modules/firebase-tools/node_modules/storage-engine/lib/compatibility/detect.js:35:15
    at Object.<anonymous> (/usr/local/lib/node_modules/firebase-tools/node_modules/storage-engine/lib/compatibility/detect.js:45:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
npm WARN ws@7.3.0 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.3.0 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! storage-engine@3.0.7 postinstall: `node ./compatibility/detect.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the storage-engine@3.0.7 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**After this error I've lost my previous firebase-tools setup completely:
$ firebase --version
bash: firebase: command not found**  

This is the log file:
...
14621 timing action:postinstall Completed in 610ms
14622 verbose unlock done using /Users/pavel/.npm/_locks/staging-3a08f0df5026584d.lock for /usr/local/lib/node_modules/.staging
14623 timing stage:rollbackFailedOptional Completed in 2406ms
14624 timing stage:runTopLevelLifecycles Completed in 34054ms
14625 warn ws@7.3.0 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
14626 warn ws@7.3.0 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
14627 verbose stack Error: storage-engine@3.0.7 postinstall: `node ./compatibility/detect.js`
14627 verbose stack Exit status 1
14627 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
14627 verbose stack     at EventEmitter.emit (events.js:189:13)
14627 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
14627 verbose stack     at ChildProcess.emit (events.js:189:13)
14627 verbose stack     at maybeClose (internal/child_process.js:970:16)
14627 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14628 verbose pkgid storage-engine@3.0.7
14629 verbose cwd /Users/pavel/IdeaProjects/AWS_CodeCommit/google-assistant-tasks
14630 verbose Darwin 13.4.0
14631 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "i" "-g" "firebase-tools"
14632 verbose node v10.15.1
14633 verbose npm  v6.14.5
14634 error code ELIFECYCLE
14635 error errno 1
14636 error storage-engine@3.0.7 postinstall: `node ./compatibility/detect.js`
14636 error Exit status 1
14637 error Failed at the storage-engine@3.0.7 postinstall script.
14637 error This is probably not a problem with npm. There is likely additional logging output above.
14638 verbose exit [ 1, true ]

**Comment by ridhianand16** [comment]
Have you tried to install firebase-tools with the following command? 

```
curl -sL https://firebase.tools | bash
```

**Comment by Jarvey** [comment]
Same issue here!

**Comment by voiceactivity** [comment]
Yes, I can confirm that as well. It doesn't work either ☹️

**Comment by slawtul** [comment]
Hi, I confirm this issue. **firebase** tool was removed after the latest update via npm.

**Comment by nuthinking** [comment]
The issue is with a dependency, even downgrading to 8.0.2 now fails. Which dependency is it? `firebase-action` looks like it solved it specifying a new node version but that didn't work for me. Ideas?

**Comment by kleiteimc** [comment]
Ran into the same problem too.  🙁

**Comment by anthonycollinnadeau** [comment]
Same here... We install firebase-tools in our ci for deployment I try to change node version 14.4 to 12.18 and change firebase-tools 8.4.3 to 8.4.2 and 8.3.0 they not seem to work either

**Comment by robyedlin** [comment]
👍 Same problem.

**Comment by vsaravind007** [comment]
Same issue on Node Version v12.14.1

**Comment by nuthinking** [comment]
Trying to use the CLI manually looks like firebase can't connect to a required endpoint. Could that be the real issue?

![Screenshot 2020-06-22 at 08 15 46](https://user-images.githubusercontent.com/163635/85254671-1d9edf80-b461-11ea-8584-4edc42ab5876.png)

**Comment by davidturtle** [comment]
Same.
8.4.2->8.4.3.

**Comment by Mistic92** [comment]
Same when running on CI where fresh build is done. 

```
 $ npm install -g firebase-tools
 npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/firebase-tools/node_modules/chokidar/node_modules/fsevents):
 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
 npm ERR! code ENOENT
 npm ERR! syscall spawn git
 npm ERR! path git
 npm ERR! errno ENOENT
 npm ERR! enoent Error while executing:
 npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/DABH/diagnostics.git
 npm ERR! enoent 
 npm ERR! enoent 
 npm ERR! enoent spawn git ENOENT
 npm ERR! enoent This is related to npm not being able to find a file.
 npm ERR! enoent 
 npm ERR! A complete log of this run can be found in:
 npm ERR!     /root/.npm/_logs/2020-06-22T12_04_00_184Z-debug.log
```

**Comment by samtstern** [comment]
Thanks everyone for the reports.  Looks like there's something seriously going wrong here although we don't quite know what yet.  Will look into it today.

**Comment by samtstern** [comment]
Clearly has something to do with this package:
https://www.npmjs.com/package/storage-engine

Last published 10 months ago so not a recent update issue.  But there's a big uptick in downloads recently:
<img width="385" alt="Screen Shot 2020-06-22 at 8 48 09 AM" src="https://user-images.githubusercontent.com/8466666/85289258-21346580-b465-11ea-8faa-e83f881335d2.png">

The only package that depends on it is this one:
https://www.npmjs.com/package/diagnostics

Running `npm ls storage-engine` gives me no results but I'm going to try removing my `package-lock.json` and `node_modules` to see if that changes.

**Comment by samtstern** [comment]
Ok we do have a dependency on diagnostics:
```
firebase-tools@8.4.3 /Users/samstern/Projects/firebase-tools
└─┬ winston@3.3.1
  └── diagnostics@2.0.2
```

Which means we're getting the `storage-engine` dep from here:
https://github.com/3rd-Eden/diagnostics/blob/master/package.json#L60

Now I just need to determine what changed recently and what to do about it.

**Comment by samtstern** [comment]
Ok here's the root cause;
https://github.com/winstonjs/winston/issues/1814

Looks like a dependency of winston now requires `git` to be installed.  The workaround is to make sure you have `git` on your machine although obviously we need to find a more permanent solution.

**Comment by nuthinking** [comment]
@samtstern what about the fact that even manual deployments don't work. See access to [admin.firebase.com](https://admin.firebase.com/v1/projects). Are these 2 different issues?

**Comment by samtstern** [comment]
@nuthinking I am not sure what "using the CLI manually" means but yes anything to do with `admin.firebase.com` is not related to this issue.

**Comment by nuthinking** [comment]
Fixing one of the two would be enough for me 😃  I will open an issue for the CLI. Thanks!

**Comment by samtstern** [comment]
Ok `winston` has released version `3.3.2` which I think should fix everything as long as you reinstall the Firebase CLI.  Thanks everyone for your patience, that was a wild ride!

**Comment by voiceactivity** [comment]
Fixed!
Thank you team for very quick action!

**Comment by davidturtle** [comment]
Thx!

**Comment by moryapant** [comment]
how it is fixed? can someone please explain?
