### ISSUE TITLE
First Time Setting up Firebase on CLI

### ISSUE THREAD

**Issue by JamesVanWaza** [firebase/firebase-tools#2384]
Please update the `firebase.storage` to use Rules Version 2 because it's still using version 1 and the following warning shows up even though I have the most current version of Firebase 

<img width="1182" alt="Screen Shot 2020-06-21 at 6 27 49 PM" src="https://user-images.githubusercontent.com/4000076/85236555-ebec3100-b3ec-11ea-8099-2232d68e018e.png">

 Firebase Version: *7.12.1*

To reproduce, run the steps firebase init then firebase deploy it shows up/

**Comment by samtstern** [comment]
@JamesVanWaza just add this line to the top of your `storage.rules` file:
```
rules_version = '2';
```

I'll send a PR to fix the template.
