### ISSUE TITLE
Firebase Functions deploy error, Node.js version 10

### ISSUE THREAD

**Issue by 345ml** [firebase/firebase-tools#2385]
I was trying to deploy Node.js version 10 on Firebase functions,  Then I get an error and I don't know the details of the error.
Does firebase-tools support Node.js version 10?

I currently have Node.js version 8 Function deployed and already in production.

### [REQUIRED] Environment info

**firebase-tools:**
8.4.3

**Platform:**
macOS version 10.15.4

### [REQUIRED] Test case

package.json
``` json
"engines": {
   "node": "10"
},
"dependencies": {
  "firebase-tools": "^8.4.3",
  "firebase-functions": "^3.7.0",
  more...
}
```

index.js
``` javascript
const functions = require('firebase-functions');

exports.test = functions.https.onCall((data, context) => {
  return { status: 'success' };
});
```
### [REQUIRED] Steps to reproduce

```
firebase deploy --only functions:test
```

### [REQUIRED] Expected behavior

Success deploy.

### [REQUIRED] Actual behavior

Error deploy.
```
i  deploying functions
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
✔  functions: required API cloudfunctions.googleapis.com is enabled
✔  functions: required API cloudbuild.googleapis.com is enabled
i  functions: preparing functions directory for uploading...
i  functions: packaged functions (539.65 KB) for uploading
✔  functions: functions folder uploaded successfully

i  functions: uploading functions in project: test(us-central1)
i  functions: creating Node.js 10 function test(us-central1)...
✔  scheduler: required API cloudscheduler.googleapis.com is enabled
⚠  functions[test(us-central1)]: Deployment error.
Build failed: Build error details not available.

```

**Comment by nuthinking** [comment]
might be related to #2383

**Comment by 345ml** [comment]
@nuthinking 
Thanks...!!!

**Comment by samtstern** [comment]
```
⚠  functions[test(us-central1)]: Deployment error.
Build failed: Build error details not available.
```

This means something went wrong in the Cloud Functions build, not in the Firebase CLI.  If you go into the console and check the logs you should be able to see the error.

**Comment by 345ml** [comment]
OK.
Let me check.

**Comment by 345ml** [comment]
@samtstern 
There is no useful information in the log.

```
status: {
  code: 13    
  message: "Build failed: Build error details not available."    
}
```

**Comment by samtstern** [comment]
@345ml thanks for getting back to me.  Sounds like there's something going wrong in the Cloud Functions backend that needs to be looked at by the engineering team.

You can file an issue here:
https://issuetracker.google.com/issues/new?component=187195&template=0

As you can see in the past, people have filed similar issues and they were handled and resolved:
https://issuetracker.google.com/113828148

**Comment by 345ml** [comment]
Thank you for taking the time to share this with us.
I'll take a look.

**Comment by kodai3** [comment]
I am experiencing same situation.
it seems like follows for me
↓ works (all functions)
```firebase deploy --only functions```
↓ not works (selected function(s))
```firebase deploy --only functions:test ```

@345ml 
Did you have any luck upgrading Node?
if so, I'd appreciate it if you could tell me your case.

**Comment by 345ml** [comment]
@kodai3 
So far, I haven't been able to solve the problem yet.

**Comment by 345ml** [comment]
I recently did a deployment and it seems to have updated successfully.
Maybe it was a problem on Google's side.

**Comment by lamiisy** [comment]
This worked for me
 I ran:
`firebase login:ci`

then ran: 
`firebase deploy`

**Comment by benbenzy** [comment]
my local hos is running well but the moment i try to deploy then it cant deploy

**Comment by yusuff122** [comment]
I have the same problem, how did you solve it?
