### ISSUE TITLE
CLI 6.4.0 can't set active project (access to admin.firebase.com)

### ISSUE THREAD

**Issue by nuthinking** [firebase/firebase-tools#2388]
### Environment info

**firebase-tools:** 6.4.0

**Platform:** MacOS 10.15.5 (latest Catalina)

### Test case

N/A

### Steps to reproduce

firebase use ...
firebase target:apply ...

### Expected behavior

Being able to select the active project (so that I can later deploy)

### Actual behavior

I get: Error: Server Error. connect ETIMEDOUT 104.197.85.31:443

Looks like behind the hood is trying to connect to [admin.firebase.com](https://admin.firebase.com/v1/projects) and cannot.

**Comment by mbleigh** [comment]
You need to update your CLI version, as that version tries to connect to a
backend that has been decommissioned.

**Comment by samtstern** [comment]
Yeah 6.4.0 is from February 2019 so it's about 18 months old:
https://github.com/firebase/firebase-tools/releases/tag/v6.4.0

You should be fine using a high `7.x` version but the latest `8.x` versions are better if you can upgrade all the way.

**Comment by nuthinking** [comment]
@samtstern if you can sort out 8.x, I would be happy to upgrade :D
