### ISSUE TITLE
Port 5001 is not open on localhost, could not start Functions Emulator

### ISSUE THREAD

**Issue by julianiaccopucci** [firebase/firebase-tools#2409]
### [REQUIRED] Environment info

npm 6.13.7
node v12.11.1

**firebase-tools:**
 8.4.3

**Platform:**
mac os Catalina 10.15.5
### [REQUIRED] Test case
- none

### [REQUIRED] Steps to reproduce
firebase init (install firestore and functions)
firebase emulators:start

### [REQUIRED] Expected behavior
Firestore and Functions emulators should start

### [REQUIRED] Actual behavior
Only Firestore starts, Functions emulator fails:

    `$ firebase emulators:start --debug
	[2020-06-28T17:43:53.149Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
	[2020-06-28T17:43:53.150Z] > authorizing via signed-in user
	i  emulators: Starting emulators: functions, firestore {"metadata":{"emulator":{"name":"hub"},"message":"Starting emulators: functions, firestore"}}
	⚠  hub: emulator hub unable to start on port 4400, starting on 4401 instead. {"metadata":{"emulator":{"name":"hub"},"message":"emulator hub unable to start on port 4400, starting on 4401 instead."}}
	[2020-06-28T17:43:53.173Z] [hub] writing locator at /var/folders/c1/vlr0jfwj3rn2rsfnp3ztlyjm0000gn/T/hub-practicelyapp.json
	i  emulators: Shutting down emulators. {"metadata":{"emulator":{"name":"hub"},"message":"Shutting down emulators."}}
	i  hub: Stopping emulator hub {"metadata":{"emulator":{"name":"hub"},"message":"Stopping emulator hub"}}
	⚠  functions: Port 5001 is not open on localhost, could not start Functions Emulator. {"metadata":{"emulator":{"name":"functions"},"message":"Port 5001 is not open on localhost, could not start Functions Emulator."}}
	⚠  functions: To select a different host/port, specify that host/port in a firebase.json config file:
	      {
	        // ...
	        "emulators": {
	          "functions": {
	            "host": "HOST",
	            "port": "PORT"
	          }
	        }
	      } {"metadata":{"emulator":{"name":"functions"},"message":"To select a different host/port, specify that host/port in a firebase.json config file:\n      {\n        // ...\n        \"emulators\": {\n          \"functions\": {\n            \"host\": \"\u001b[33mHOST\u001b[39m\",\n            \"port\": \"\u001b[33mPORT\u001b[39m\"\n          }\n        }\n      }"}}
	i  emulators: Shutting down emulators. {"metadata":{"emulator":{"name":"hub"},"message":"Shutting down emulators."}}

	Error: Could not start Functions Emulator, port taken.`

**Comment by samtstern** [comment]
@julianiaccopucci the problem and solution are both inside of the error message you posted.  Port 5001 is busy on your machine so you need to choose another port.  To do this, add an entry in your `firebase.json` like this:

```js
      {
        // ...
        "emulators": {
          "functions": {
            "port": "PORT"
          }
        }
      }
```

**Comment by pandapancake** [comment]
> @julianiaccopucci the problem and solution are both inside of the error message you posted. Port 5001 is busy on your machine so you need to choose another port. To do this, add an entry in your `firebase.json` like this:
> 
> ```js
>       {
>         // ...
>         "emulators": {
>           "functions": {
>             "port": "PORT"
>           }
>         }
>       }
> ```

I'm facing the same problem but tried what it suggest and didn't work. Any idea :/?

```
⚠  functions: Port NaN is not open on localhost, could not start Functions Emulator.
⚠  functions: To select a different host/port, specify that host/port in a firebase.json config file:
      {
        // ...
        "emulators": {
          "functions": {
            "host": "HOST",
            "port": "PORT"
          }
        }
      }

```

**Comment by jmeyers91** [comment]
I'm also seeing this error. It appears every time I run `firebase emulators:exec` but I can start the emulators with `firebase emulators:start` without a problem.

**Comment by sahani-ramprit** [comment]
"emulators": {
    "functions": {
      "port": 5000 // put your available port
    },
}

**Comment by jthetzel** [comment]
I encountered this error due to a `firebase` version mismatch. I inadvertedly called the global `firebase`, which was version 7, instead of the local `firebase`, which was version 9.

```
$ which firebase
                                                                                                                        
/home/jthetzel/n/bin/firebase
```

```
$ firebase --version      
                                                                                                                  
7.2.2
```

```
$ yarn firebase --version 

9.22.0
```

Calling `yarn firebase emulators:start` succeeded.

**Comment by quantuminformation** [comment]
just came across this after shutting down the emulators and restarting
