### ISSUE TITLE
`firebase deploy --only database` ignores .firebaserc

### ISSUE THREAD

**Issue by adelespinasse** [firebase/firebase-tools#241]
If you do `firebase deploy` with no other arguments, and there's a .firebaserc file in the current directory, it deploys both hosting and database rules to the project specified in the .firebaserc.

If you do `firebase deploy --only database`, it ignores .firebaserc and deploys database rules to the "active" project (I'm not even sure how this is determined). This took me by surprise when I finally noticed it; I've been running a deploy script that was deploying rules to the wrong project! (Fortunately it was an inactive project that I don't use anymore.)

`firebase use` also seems to ignore the .firebaserc and prints the "active" project. But, if you're not in a directory with a .firebaserc, `firebase use` gives an error message because it's "not a Firebase project directory" (or actually I think it might be the lack of firebase.json or database.rules.json, not .firebaserc).

Does this make sense? Is it intended behavior?

(I initially thought #180 looked like the same issue, but it's not.)

**Comment by mbleigh** [comment]
deploy --only doesn't have any special short-circuiting, so something else
must be going on here. The .firebaserc file does not determine your active
project, only defines your aliases. The "active" project is stored in
~/.config/configstore/firebase-tools.json and maps based on the absolute
project directory. The behavior of selecting a project works like this:

1. Check for --project flag and resolve either as project id or alias if
alias is defined with value of flag.
2. Check for active project in home directory config file. If present, use
it.
3. If there is only one project alias in .firebaserc, use it.
4. Error out, we don't know what project to use.

Does that clear anything up?

**Comment by ggranum** [comment]
@mbleigh It explains things (sort of - step 3 kind of contradicts your second sentence), but it's not how most tools use local default configuration files. Firebase has steps 2 and 3 reversed - the *local config* should override the more global version. Else, why have it?

The current behaviour is a bit scary, in that the project with the most recent successful '--use' will live on as the 'default' database to exec against, even for scripts in unrelated projects. That's not safe, and is why we have local configuration files that override globals. 

I'm curious, do you know when the alias is resolved? If I call 'firebase --use prod' in project Foo, and then CD into project Bar -  `cd ../bar` and run a firebase command, will that execute against the prod alias defined in `./bar/.firebaserc`, or `./foo/.firebaserc`?

**Comment by mbleigh** [comment]
@ggranum we store *directory-specific active projects* in the home directory. Running `firebase use` in one directory will not in any way affect any other project directory.

**Comment by alankent** [comment]
Just wanted to say this had me confused until I found this as well. I changed my project name, updated the .firebaserc file, deleted the old project in the console, and it kept coming up with 400 errors. It was not until I discovered I had to use "firebase list" and "firebase use" to change my current project (and forget about .firebaserc) that I managed to get things going again.
