### ISSUE TITLE
Cannot deploy function

### ISSUE THREAD

**Issue by mikquinlan** [firebase/firebase-tools#2413]
### [REQUIRED] Environment info

firebase-tools 8.4.3
gcloud 294.0.0

 ○ firebase --version
8.4.3
**firebase-tools:**

Occurs on OSX 10.15.5 and when running using this docker image: https://hub.docker.com/layers/google/cloud-sdk/294.0.0-slim/images/sha256-e8402d09d1e976d0f039e988856b17c8ee61fb7d1a7167ae3037f6b405f81655?context=explore

**Platform:**

### [REQUIRED] Test case

https://github.com/mikquinlan/firebase-deploy-test-case

### [REQUIRED] Steps to reproduce

1. Create a Firebase project and assign its name to `default` in firebase.json
2. Create a VPC connector called `default-connector`

`firebase functions:config:set analytics.mykey="env key value" -P default` <- works

`firebase deploy --only functions:helloWorld` <-- works

`gcloud functions deploy helloWorld --vpc-connector=default-connector --ingress-settings=all --egress-settings=all --region=us-central1 --project=<<your project name>>` <-- fails with:

```
ERROR: (gcloud.functions.deploy) OperationError: code=3, message=Function failed on loading user code. Error message: Code in file index.js can't be loaded.
Is there a syntax error in your code?
Detailed stack trace: TypeError: Cannot read property 'mykey' of undefined
    at Object.<anonymous> (/srv/index.js:3:43)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at getUserFunction (/worker/worker.js:439:24)
    at loadUserCode (/worker/worker.js:495:18)
```

Modify the failing command:

`gcloud functions deploy helloWorld --vpc-connector=default-connector --ingress-settings=all --egress-settings=all --region=us-central1 --project=pretzel-fb-dev --set-env-vars analytics.mykey="my value"` <-- fails with:

```
ERROR: (gcloud.functions.deploy) OperationError: code=3, message=Function failed on loading user code. Error message: Code in file index.js can't be loaded.
Is there a syntax error in your code?
Detailed stack trace: TypeError: Cannot read property 'mykey' of undefined
    at Object.<anonymous> (/srv/index.js:3:43)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at getUserFunction (/worker/worker.js:439:24)
    at loadUserCode (/worker/worker.js:495:18)
```

### [REQUIRED] Expected behavior

The `gcloud functions deploy` command successfully updates the existing function with the config specified.

There should be no need to specify  `--set-env-vars`. 

Until yesterday, these three commands in the above order worked successfully.

Perhaps there is a way to update the function with the vpc-connector settings using a firebase command? 

### [REQUIRED] Actual behavior

https://pastebin.com/1LkRNJNL

**Comment by mbleigh** [comment]
The "config" provided by Firebase is separate from env variables provided by `gcloud`. Environment variables are available in-function as `process.env.NAME_OF_VAR` and cannot contain periods.

If you are using a VPC connector the Firebase tooling will not currently support that use case. I'd recommend using `gcloud` and switching to environment variables instead of `firebase functions:config:set`.
