### ISSUE TITLE
database:get - syntax is not clear and error

### ISSUE THREAD

**Issue by mphasize** [firebase/firebase-tools#242]
I am trying to use the firebase-tools to retrieve data with the `database:get` command.

`firebase database:get --order-by "conversationId" --equal-to "-KYtlLFltw6ikLeqY7x7" /messages`

First, the documentation is not clear on whether or not values should be quoted or written as is.
Second, there seems to be a parsing error, possibly related to the `-` in the Firebase Push ID...

```
error: unknown option `-Y'
```

Or am I doing this wrong? Quick tip would be appreciated! Thanks

Firebase Tools Version: 3.2.0

**Comment by mbleigh** [comment]
Try `--equal-to='<id>'`
