### ISSUE TITLE
Firebase realtime database onDisconnect() not triggered on emulator

### ISSUE THREAD

**Issue by carrickpaul** [firebase/firebase-tools#2420]
### Environment info

**firebase-tools:**
8.4.3

**Platform:**
Windows 10

### Test case

```
  update() {
    const ref = firebase.database().ref(`status/${this.deviceId}`);

    ref.update({
      status: 'online',
    });

    ref.onDisconnect().update({
      status: 'offline',
    });
  }
```

###  Steps to reproduce
call this function against the firebase realtime emulator

###  Expected behavior
The update is processed after the application loses it reference to this node.

### Actual behavior
 doesn't get triggered on the emulator, works as advertised on the live database,

**Comment by yuchenshi** [comment]
What do you mean by "loses it reference to this node"? Could you please share more details of the exact steps to reproduce this in production and emulator?

As the name suggests, `onDisconnect` runs when a client is disconnected from the server (production / emulator). You may find your browser developer tools useful to simulate "Networking: Offline" in order to test that.

**Comment by carrickpaul** [comment]
If I run this code on the emulator the onDisconnect() is not called (or if it is called no update is made). If I run it against a normal online database the onDisconnect is called and the realtime database updates.

**Comment by yuchenshi** [comment]
While I appreciate your quick response, we really would need step-by-step instructions for what you are doing to trigger "onDisconnect". As mentioned above, how did you simulate "disconnecting" when testing against the emulator? Try using this format if it helps:

1. Open a page with the code snippet above in a browser
2. Wait for page to load
3. <fill in here about what to do to trigger the disconnection>
4. <and more...>
5. <how did you verify the data was updated or not updated? more details here...>

**Comment by carrickpaul** [comment]
closing the issue for the emulator, after writing a stand alone test for the onDisconnect() with a stand alone html page it works. It seems my complication is in the angular app.

Below the stand alone file for completion. Using the emulator or hosted app databaseURL works. 

1. use the html code below in a browser
2. wait for page to load and verify the  realtime db value 'status/woohoo' is set to 'online'
3. close the html page and see it set to 'offline'

```<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <title>Test</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
  <script src="https://www.gstatic.com/firebasejs/7.15.5/firebase-app.js"></script>
  <script src="https://www.gstatic.com/firebasejs/7.15.5/firebase-database.js"></script>

  <script>
    var config = {
      apiKey: 'XXXXXXXXXXXXXXXXXXXXX',
      authDomain: 'XXXXXXXXX.firebaseapp.com',
      // databaseURL: 'https://XXXXXXXXXX.firebaseio.com',
      databaseURL: 'http://localhost:9000/?ns=XXXXXXXXX',
      projectId: 'XXXXXXXXXXX',
      storageBucket: 'XXXXXXXXX.appspot.com',
      messagingSenderId: 'XXXXXXXXXXXXXX',
      appId: 'XXXXXXXXXXXXX',
      measurementId: 'XXXXXXXXXXXXX'
    }

    function updateOnDisconnect() {
      const ref = firebase.database().ref('status/woohoo');

      ref.update({
        status: 'online',
      });

      ref.onDisconnect().update({
        status: 'offline',
      });
    }

    firebase.initializeApp(config);
    updateOnDisconnect()

  </script>
</body>
</html>`
