### ISSUE TITLE
Firestore emulator does not import all collections/documents

### ISSUE THREAD

**Issue by catchshyam** [firebase/firebase-tools#2425]
### [REQUIRED] Environment info

**firebase-tools:** 8.4.3

**Platform:** Windows

### [REQUIRED] Test case

Please see steps to reproduce

### [REQUIRED] Steps to reproduce

Step 1: Took a backup of production firestore database with the command
gcloud firestore export gs://my_bucket_name

Step 2: Copied the backedup data to the local machine with the command
gsutil -m cp -R gs://my_bucket_name my_local_folder

Step 3: Edited the firebase-export-metadata.json to point the "metadata_file" to the copied path

Step 4: firebase emulators:start --import local_path

### [REQUIRED] Expected behavior

The imported databse in the emulator ui should be same as the one seen on the cloud

### [REQUIRED] Actual behavior

Only maximum of 10 collections are listed.
Some of the collections do not show all the documents. I don't believe this is caused due to limitations on the number of documents. One of my imported collections shows all of the documents (about 200) where as the problematic collection has only 3 of the 10 documents.

I am sorry I will not be able to share my production data as an attachment.

**Comment by samtstern** [comment]
@catchshyam thanks for reporting this.  I would like to find out if this is an issue with the Firestore Emulator or with the emulator UI. 

Could you pick a missing document (I'll call it `foo/bar` in my example) and try doing the following:

- Read the document using `firebase-admin` within the functions emulator while the Firestore emulator **is running** with your import.
- Read the document using `firebase-admin` within the functions emulator while the Firestore emulator **is not running** with your import.

For example you could use a Cloud Functions like this:

```js
const functions = require('firebase-functions');
const admin = require('firebase-admin');
admin.initializeApp();

exports.helloWorld = functions.https.onRequest(async (request, response) => {
  const snap = await admin.firestore().doc('/foo/bar').get();
  response.json(snap.data());
});
```

**Comment by catchshyam** [comment]
@samtstern thank you for the quick attention, appreciate it.

So I ran the following function with the two scenarios you defined,

exports.testEmulator = functions.https.onRequest(async (request, response) => {
    const snap = await admin.firestore().doc('foo/bar').get();
    console.log('@LOG document exists ', snap.exists);
    response.json(snap.data());
});

When the firebase simulator was **running**, the log output was,
@LOG document exists **false**

When the firebase simulator was **not running**, the log output was,
@LOG document exists **true**
and I was able to load the document from firebase admin.

Let me know if I can be of any more help.

**Comment by samtstern** [comment]
@catchshyam thanks for testing!  So now it seems likely there's an issue with the import flow in the emulator.  To set expectations: it's going to be really hard to reproduce this issue on our end and we can't fix something to we can't reproduce. 

If you ever see this issue and you feel comfortable sharing the exported data you can email it to me at samstern@google.com and I will do testing on it.

**Comment by catchshyam** [comment]
@samtstern thanks and I understand. I will try to setup a test database and reproduce the issue. If I succeed, I will share the project with you.

Thanks.

**Comment by samtstern** [comment]
@catchshyam were you ever able to reproduce this? Is this still a problem>
