### ISSUE TITLE
Can't access firebase following install on mac

### ISSUE THREAD

**Issue by SoniaQ** [firebase/firebase-tools#2426]
**firebase-tools: 6.4.1**

**Platform: macOS**

** After running npm install -g firebase I received an EACCES error, so I followed the instructions available here https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally to change the PATH. I ran <npm install -g firebase> again and it appeared to install but on running the commands <firebase -v> or <firebase login> I receive error firebase: command not found. However, if I run <npm firebase -v> the version of firebase is returned '6.4.1' - the version I installed. Putting npm in front of any other firebase commands does not work. How can I get firebase to run on my mac??? **

** Expected <firebase -v> to return 6.4.1 **

** Instead command not found as with firebase login/init etc. However <npm firebase -v> returns expected behaviour (6.4.1) **

**Comment by samtstern** [comment]
@SoniaQ unfortunately this sounds like an issue with `npm` or `node` on your Mac and not an issue with the Firebase CLI.  I know how frustrating this can be, I have been stuck in a situation like that before!

My advice would be to try and completely uninstall `npm` and `node` from anywhere they might exist on your computer and then start over using nvm:
https://github.com/nvm-sh/nvm

Also it's worth noting that `6.4.1` is a very old version of the Firebase CLI, please try using a later version once you get your system in a better place.

**Comment by bkendall** [comment]
It looks like you are doing `npm install -g firebase`, when you need to do `npm install -g firebase-tools`.

**Comment by SoniaQ** [comment]
@samtstern Interesting that an old version of firebase has been installed - I thought following the directions on firebase step-by-step when creating a project would install the latest version. Thanks for the advice, hoping these steps work!

**Comment by SoniaQ** [comment]
> It looks like you are doing `npm install -g firebase`, when you need to do `npm install -g firebase-tools`.

@bkendall Thanks for the tip - I'm a little confused though as I was following the steps as indicated by firebase when setting up a new project. The command it tells me to use is `npm install -g firebase`. It doesn't mention `npm install -g firebase-tools`. But then, I didn't get far enough with installation so if a prompt to use the latter command appears later, I never reached it. Should I be use one or the other or both?

**Comment by samtstern** [comment]
`npm install -g firebase` is almost never what you want, can you link me to the instructions that mentioned that?  I will update them.
