### ISSUE TITLE
All firebase commands throw an error

### ISSUE THREAD

**Issue by krittiyaclark** [firebase/firebase-tools#2430]
I installed `npm install -g firebase-tools` but every time I run any `firebase` commands it throws an error.

```
/Users/krittiyaclark/.nvm/versions/node/v13.6.0/lib/node_modules/firebase-tools/node_modules/universal-analytics/node_modules/uuid/dist/esm-browser/index.js:1
export { default as v1 } from './v1.js';
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1060:16)
    at Module._compile (internal/modules/cjs/loader.js:1108:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
    at Module.load (internal/modules/cjs/loader.js:993:32)
    at Function.Module._load (internal/modules/cjs/loader.js:892:14)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/krittiyaclark/.nvm/versions/node/v13.6.0/lib/node_modules/firebase-tools/node_modules/universal-analytics/lib/index.js:3:12)
```

If I commented these code from 
`/Users/krittiyaclark/.nvm/versions/node/v13.6.0/lib/node_modules/firebase-tools/node_modules/universal-analytics/node_modules/uuid/dist/esm-browser/index.js:1` 
out. I can run `firebase` commands

```
// export { default as v1 } from './v1.js';
// export { default as v3 } from './v3.js';
// export { default as v4 } from './v4.js';
// export { default as v5 } from './v5.js';
```

Please help. Thank you!

Please submit feature requests through our [support page](https://firebase.google.com/support/contact/bugs-features/).

**Comment by samtstern** [comment]
@krittiyaclark looks like this error:

- https://stackoverflow.com/questions/62618543/unexpected-token-export-in-sequelize-uuid
- https://github.com/uuidjs/uuid/issues/466

We depend on the `uuid` module which some people online claim does not work with Node 13.  Can you try using either Node 14 or Node 12?

We generally only test on event-numbered Node releases since those are LTS:
https://nodesource.com/blog/understanding-how-node-js-release-lines-work/

**Comment by krittiyaclark** [comment]
> @krittiyaclark looks like this error:
> 
> * https://stackoverflow.com/questions/62618543/unexpected-token-export-in-sequelize-uuid
> * [uuidjs/uuid#466](https://github.com/uuidjs/uuid/issues/466)
> 
> We depend on the `uuid` module which some people online claim does not work with Node 13. Can you try using either Node 14 or Node 12?
> 
> We generally only test on event-numbered Node releases since those are LTS:
> https://nodesource.com/blog/understanding-how-node-js-release-lines-work/

@samtstern Thank you! I updated node --version v14.5.0 and no ERRORs showing again.
