### ISSUE TITLE
Support functions.runtime detection in the emulator

### ISSUE THREAD

**Issue by samtstern** [firebase/firebase-tools#2442]
This PR recently added a new `functions.runtime` config to firebase.json:
https://github.com/firebase/firebase-tools/pull/2241

We rely on `package.engines` in a few places, such as here:
https://github.com/firebase/firebase-tools/blob/8e264db0540c0fca74645312d3a01fa255d06c33/src/emulator/functionsEmulator.ts#L560

We do a few things with the Node version:
- We warn the developer if their local Node version doesn't match what it will be in production
- We set different environment variables in the Functions emulator to match production

cc @quentinvernot

**Comment by quentinvernot** [comment]
Interesting, this seems to be doing the same kind of checks that are done before deployment. It looks like the fix would requires 2 changes:
* In `src/emulator/functionsEmulator.ts`, in `askInstallNodeVersion`, also load and parse the `runtime` field in firebase.json, if the value isn't there, try the package.json, warn if none are set
* In `src/emulator/functionsEmulatorRuntime.ts`, in `initializeEnvironmentalVariables`, same thing, except the package.json has to be loaded anyway to read the list of deps

That's all I could find, do you know if there are more?

It seems the first one can easily get access to the content of firebase.json from its callers, not sure about the second one.

**Comment by samtstern** [comment]
@quentinvernot that seems right!  The contents of `firebase.json` are easy to get when you're outside the Functions Runtime (which is a process we fork) and still inside the CLI code. 

The `FunctionsRuntimeBundle` already contains an optional `nodeMajorVersion` field.  I think we just need to make sure that it's set from `config.functions.runtime` and then rely on that field within the runtime rather than reading what's in `package.json`.

That fields was recently added to support the Extensions emulator, but it will work for us.  Are you interested in attempting a PR here?

**Comment by quentinvernot** [comment]
It looks like setting `nodeMajorVersion` in `FunctionsRuntime`'s constructor args would even set both, as it would be passed down to `FunctionsRuntimeBundle` as an argument when forking the process.

As for the PR, I can certainly try! I'm not sure what to test/QA here though, I don't use `firebase serve` for functions much.

**Comment by samtstern** [comment]
No worries I'm happy to put together a PR for this I just always like to
give other people the opportunity if the idea was theirs.  I have a good
sense of what needs testing here so won't be hard.

**Comment by quentinvernot** [comment]
It looks *way* too easy to be honest: https://github.com/firebase/firebase-tools/pull/2444
