### ISSUE TITLE
emulator and external requests empty via got

### ISSUE THREAD

**Issue by Hacksore** [firebase/firebase-tools#2445]
### [REQUIRED] Environment info

**firebase-tools:** 8.5.0

**Platform:** Windows

### [REQUIRED] Test case
I am running a simple REST function that uses `got` to fetch remote data. The request seems to not come back with data on Windows when I run locally but deployed works fine. I also noted that it did not happen on macOS.

I've included `request` in the demo app which seems it's not having the same issue so this could be specific to `got`. Nevertheless, I figured it's still helpful to see if others have experienced similar behavior. 

Deployed function for ref: https://us-central1-firebase-emulator-got.cloudfunctions.net/app

### [REQUIRED] Steps to reproduce

- Clone https://github.com/Hacksore/firebase-emulator-got
- Run project via `npm run serve` in the `functions` directory

### [REQUIRED] Expected behavior

- GET http://localhost:5001/firebase-emulator-got/us-central1/app
- Should give you back a list of open issues for my project under `got-lib`

### [REQUIRED] Actual behavior

- GET http://localhost:5001/firebase-emulator-got/us-central1/app
- `got-lib` has an empty string whereas `request-lib` is able to fetch the data

**Comment by samtstern** [comment]
@Hacksore I was not able to reproduce this issue on macOS.  Since it works on mac and in the deployed functions environment it seems highly likely that this is an issue with the `got` library on Windows and not an issue with the Firebase CLI.  I would suggest filing an issue with them!

**Comment by Hacksore** [comment]
@samtstern I agree. However, it's more likely we will have users that use the `got` lib here. Whereas going there it's not as common people would be using firebase.

Nevertheless, I will open an issue there to see if we have any helpful discussion/troubleshooting.

**Comment by samtstern** [comment]
Are you sure that this only happens in the Firebase emulator?  What if you
just run a plain node script with the same code on your machine?

**Comment by Hacksore** [comment]
You're right! The issue is seen standalone with got on node.js v14.0.0 my apologies for the inconvenience here.

**Comment by samtstern** [comment]
@Hacksore no worries, glad we could narrow it down.
