### ISSUE TITLE
Restart server everytime I modify the code

### ISSUE THREAD

**Issue by suyashbansal** [firebase/firebase-tools#245]
I was following the Polycast episodes 57 to 59 and while practising it, I had to restart the server every time I did some change in the code. In the video, I don't think Rob restarted the server every time. Can there be a debugging mode/flag to avoid restarting manually?

I am currently running Node v6.9.2 on Windows 10 (14393.576).

**Comment by mbleigh** [comment]
Internal tracking id: 122551397

**Comment by samtstern** [comment]
@mbleigh was this for functions?  If so we achieved this with the new emulator.

**Comment by akauppi** [comment]
@suyashbansal Would you please comment to Sam about being able to close this. 
I would second closing. Firebase emulators nowadays pick up changes rather well.

**Comment by samtstern** [comment]
@akauppi thanks for pinging this old bug.  I think we've addressed reloading well (not active HMR, but reload on refresh) so you're right we can close this out.

**Comment by suyashbansal** [comment]
Hey.. Yes it's working now. Thanks!
