### ISSUE TITLE
Partly deploying functions only deploys the first in sequence

### ISSUE THREAD

**Issue by JaapWeijland** [firebase/firebase-tools#2451]
### [REQUIRED] Environment info

**firebase-tools:** 8.5.0

**Platform:** macOS

### [REQUIRED] Test case

I try deploying my functions:

`firebase deploy --only functions:func1,func2,func3`

It will only deploy `func1`

### [REQUIRED] Steps to reproduce

Do the above.

### [REQUIRED] Expected behavior

All three functions to deploy, instead of only the first one, `func1`

### [REQUIRED] Actual behavior

Only deploys the first one, `func1`

### Notes

I am updating my engines from Node 8 to Node 10. This caused the functions to take a lot longer than usual to deploy. I had like 70 functions to update, which made me exceed the deploy quotum of 120 build minutes in 1 go (70 functions took all more than 3 minutes to deploy). After that, some functions of the 70 failed to deploy due to this exceeded quotum. Then, when trying to deploy the remaining functions, it only deployed the first one as described above.

I can imagine that the CLI only updates 1 function at a time due to this exceeded quotum, but if it does, it should say so.

**Comment by mbleigh** [comment]
You need to prefix each function you want to deploy with `functions:`, not
just the first one

**Comment by JaapWeijland** [comment]
You're right, hastily overlooked this in the docs.
