### ISSUE TITLE
firebase login command asks for login and password and leaves user hanging

### ISSUE THREAD

**Issue by madrigal1** [firebase/firebase-tools#2465]
### [REQUIRED] Environment info

```
Firebase Command Line Tools
Version 1.2.0
https://www.firebase.com

(node:38774) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:38774) Warning: Accessing non-existent property 'JType' of module exports inside circular dependency


```

**firebase-tools:**

**Platform:**
Manajro Linux
5.6.16

### [REQUIRED] Test case

![image](https://user-images.githubusercontent.com/30615210/87685246-cb6f8680-c7a0-11ea-83bb-188e0591f959.png)

### [REQUIRED] Steps to reproduce
firebase login in command line

### [REQUIRED] Expected behavior
takes me to a external browser to complete signin 

Does nt do the above
### [REQUIRED] Actual behavior
hangs with no out put or redirects

**Comment by samtstern** [comment]
@madrigal1 looks like you got your hands on a **VERY** old version of the Firebase CLI:
```
Firebase Command Line Tools
Version 1.2.0
```

We're now on version `8.6.0` so you're 7 major versions behind!  Please install the latest version, which will *never* ask you for a password:
https://firebase.google.com/docs/cli
