### ISSUE TITLE
Running 'Firebase Use --ADD" Results In ENOTFOUND admin.firebase.com admin.firebase.com:443

### ISSUE THREAD

**Issue by JimTheMan** [firebase/firebase-tools#247]
I was playing around with 'firebase use' and used the unalias command on my project (after adding a staging project I wanted to rename my default alias to "prod").

That worked, but now whenever I run firebase use --add:
firebase use --add

I get this error:
Error: Server Error. getaddrinfo ENOTFOUND admin.firebase.com admin.firebase.com:443

![cypherapp_ _-bash_ _87x24](https://cloud.githubusercontent.com/assets/5354163/21572590/d9272494-cea8-11e6-8606-20882c3cade5.png)

**Comment by JimTheMan** [comment]
I fixed it by uninstalling and reinstalling the global `firebase-tools` npm package so you guys can close this. I'll leave since it might help you fix this bug. :)
btw I'm using MacOS 10.11.5
npm 3.10.8
node 6.9.1

**Comment by sravindravmd** [comment]
Nothing do with this issue, just wait for few minutes and execute command
