### ISSUE TITLE
App Distribution upload timed out (Server Error. connect ETIMEDOUT)

### ISSUE THREAD

**Issue by acruis** [firebase/firebase-tools#2471]
### [REQUIRED] Environment info

**firebase-tools:** 7.12.1

**Platform:** macOS

### [REQUIRED] Test case

N/A. Please see below information instead.

### [REQUIRED] Steps to reproduce

1. Build an IPA at `IPA_PATH`
2. Run a Fastlane lane with the following content:
```rb
firebase_app_distribution(
            app: [app_id],
            ipa_path: IPA_PATH,
            groups: [tester groups],
            release_notes: "some_release_notes",
)
```

### [REQUIRED] Expected behavior

App Distribution upload is successful.

### [REQUIRED] Actual behavior

App Distribution upload failed with a `Server Error. connect ETIMEDOUT` error. The following is the partial Fastlane log.

```
[02:48:32]: ---------------------------------------
[02:48:32]: --- Step: firebase_app_distribution ---
[02:48:32]: ---------------------------------------
[02:48:33]: ▸ i  getting app details...
[02:48:36]: ▸ i  uploading distribution...
[02:49:55]: ▸ Error: failed to upload distribution. Server Error. connect ETIMEDOUT 23.21.198.175:443
```

**Comment by acruis** [comment]
Hi @samtstern, here are some more details:
* I didn't use a CLI command. As mentioned in the issue, I used the `firebase_app_distribution` Fastlane plugin to upload the IPA. Not sure what the CLI command looks like when run by the Fastlane plugin (hopefully `--debug` shows this)
* I didn't try to use `--debug`, but it looks like it's possible to enable debug mode with the plugin as well. I'll try that next and get back to you.
* I'm uploading a few IPA files one after the other (not in parallel, I'm just triggering the Fastlane action a few times). Each of them is about 340MB large.

**Comment by samtstern** [comment]
@acruis this repository is for issues with the `firebase` command-line tool.  Sounds like you're not having an issue with that, and maybe you want to report your issue here:
https://github.com/fastlane/fastlane-plugin-firebase_app_distribution

I'd transfer it for you, but GitHub doesn't allow cross-organization transfers.
