### ISSUE TITLE
Cant deploy several Cloud Function selectively

### ISSUE THREAD

**Issue by olivierkrener** [firebase/firebase-tools#2479]
### [REQUIRED] Environment info

**firebase-tools:** 8.6.0

**Platform:** Windows 10

### [REQUIRED] Test case

Deploy several cloud functions selectively  via the CLI
firebase deploy --only functions:func1,functions:func2

Deploying all functions or just 1 works fine, the issues appears when deploying selectively more than 1
firebase deploy --only functions                     // Works fine
firebase deploy --only functions:func1           // Works fine

### [REQUIRED] Steps to reproduce

Se above

### [REQUIRED] Expected behavior

The functions are deployed

### [REQUIRED] Actual behavior

An error message is displayed

+  functions: Finished running predeploy script.
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
+  functions: required API cloudbuild.googleapis.com is enabled
+  functions: required API cloudfunctions.googleapis.com is enabled
i  functions: preparing functions directory for uploading...
i  functions: packaged functions (60.36 KB) for uploading
+  functions: functions folder uploaded successfully
i  functions: current functions in project: // LIST OF FUNCTIONS
!  functions: the following filters were specified but do not match any functions in the project: func1 functions

**Comment by samtstern** [comment]
@olivierkrener if you're using powershell on windows you need to put quotes around arguments with commas:
```
firebase deploy --only "functions:func1,functions:func2"
```

**Comment by olivierkrener** [comment]
@samtstern That solved it.

What was misleading is that after a deploy failed for some functions the tool printed an error message saying I can try deploying only the functions that failed with the corresponding command line - and the command line was without quotes. Maybe the error message and suggested command line can be changed based on the current environment? (that may be too much work, then an additional message saying that sometimes it should be with quotes may be worth it?)

**Comment by samtstern** [comment]
@olivierkrener thanks!  As far as I know there's no way to detect Powershell from a Node script reliably.  But the quotes never hurt, so I will add them.

**Comment by samtstern** [comment]
Closing since your issue is fixed and made https://github.com/firebase/firebase-tools/pull/2510 to help in the future.
