### ISSUE TITLE
RTDB emulator does not load security rules on initialization

### ISSUE THREAD

**Issue by filipesilva** [firebase/firebase-tools#2483]
### [REQUIRED] Environment info

**firebase-tools:** 8.6.0

**Platform:** Windows

### [REQUIRED] Test case

```
git clone https://github.com/filipesilva/firebase-rtdb-loglevel
cd firebase-rtdb-loglevel
yarn
yarn emulators
```

This test case contains the following RTDB push:
```
import firebase from "firebase/app";
import "firebase/database";

var config = {
  databaseURL: "http://localhost:9000?ns=emulator-test-1",
  projectId: "emulator-test-1",
};
firebase.initializeApp(config);
firebase.setLogLevel("silent")
console.log("pushing")
firebase.database().ref('/path').push('value')
  .then(() => console.log("pushed"))
  .catch(() => console.log("caught"));  
```

With the following security rules:
```
{
  "rules": {
    ".read": true,
    ".write": false,
    "path":{
      ".validate": false
    }
  }
}
```

### [REQUIRED] Steps to reproduce

- open http://localhost:5000/, see the following messages in the console
```
pushing
pushed
```
- these messages indicate the push succeeded
- you can also check the security rules in effect using `curl localhost:9000/.settings/rules.json?ns=emulator-test-1 -H 'Authorization: Bearer owner'`, which shows the following rules:
```
{
    "rules": {
        ".read": true,
        ".write": true
    }
}
```
- save `database.rules.json` once with no changes
- reload http://localhost:5000/, see the following messages in the console
```
pushing
caught
```
- these message indicate the security rules are now in effect
- I can also see the following messages in the emulator log
```
i  database: Change detected, updating rules for emulator-test-1...
+  database: Rules updated.
```
-  `curl localhost:9000/.settings/rules.json?ns=emulator-test-1 -H 'Authorization: Bearer owner'` shows the following rules:
```
{
  "rules": {
    ".read": true,
    ".write": false,
    "path":{
      ".validate": false
    }
  }
}
```

### [REQUIRED] Expected behavior

The emulator should have loaded the security rules on initialization.

### [REQUIRED] Actual behavior

The emulator only loaded the security rules on change.

cc @samtstern I think this is a followup from https://github.com/firebase/firebase-tools/issues/1980.

**Comment by samtstern** [comment]
@filipesilva thank you for the extremely clear reproductioN!

**Comment by samtstern** [comment]
In the debug logs I see:
```
Starting Database Emulator with command {"binary":"java","args":["-Duser.language=en","-jar","/Users/samstern/.cache/firebase/emulators/firebase-database-emulator-v4.5.0.jar","--host","localhost","--port",9000]
```

So unlike the FIrestore emulator the RTDB emulator doesn't take rules as a command-line argument.  Looks like we need to proactively set them then.

**Comment by filipesilva** [comment]
Whoa that was fast @samtstern, cheers!
