### ISSUE TITLE
ws depedency adds node-gyp module

### ISSUE THREAD

**Issue by abeisgoat** [firebase/firebase-tools#2486]
Looks like we introduced a native dependency when we added `ws` as a dep. `ws` pulls in `bufferutil` and `utf-8-validate`. This will cause havoc with the firepit builds since they have issues with native extensions. 

I need to investigate how broken this mades the emulator UI in Firepit.

**Comment by wayjake** [comment]
node-gyp has been the bane of my existence on numerous occasions.
