### ISSUE TITLE
Emulator is not responding/working when trying to access via public IP

### ISSUE THREAD

**Issue by ElixirMike** [firebase/firebase-tools#2489]
I have the firebase emulator running on my localmachine. It' setup to listen for functions at http://localhost:5001 which works great.
I recently needed to use Google Tasks..and since there is no local emulator for this, I was hoping I could direct the task to call a GCF URL on my local machine so I could properly test.

I have created a public IP and setup the STATIC NAT FORWARDING for port 5001, so the public IP is pointing to my machine. I was able to successfully bring up my webserver on the public IP address.

However, I cannot get the emulator to respond when trying to access it via the public IP. In my case, I'm just trying to get to http://108.49.78.181:5001 , but I get "site cannot be reached".

I added the "host" attribute to the firebase.json file and sp;ecified "host" : "0.0.0.0", which let me access it via my local network such as http://192.168.1.216:5001  , but It still does not work with the public IP. 

I then tried to use "host" : "108.49.78.181", but the emulator doesn't even start and throws an error.

Is it possible to access the local GCF emulator from a public IP? How would I configure this?

**Comment by samtstern** [comment]
@ElixirMike have you considered using a forwarding service like https://ngrok.com/ ?  We don't directly test or support using public IPs with the emulators but that should work.

**Comment by ElixirMike** [comment]
How should it be configured? In the "Host" setting, should I be specifying the public ip address?

**Comment by samtstern** [comment]
If you're using `ngrok` just specify `localhost` in `firebase.json` and then let `ngrok` handle the rest, it will give you a public URL you can use.

**Comment by ElixirMike** [comment]
Cool, I'll try it out. Thx!

**Comment by samtstern** [comment]
@ElixirMike going to close this for now, let us know how it goes.  Also please be very careful when running the Functions emulator on a public IP.  Each function invocation spawns a new node process and if someone figured out how to inject code into it over the internet they do some damage on your machine!
