### ISSUE TITLE
Error in deploy firebase web

### ISSUE THREAD

**Issue by nikul** [firebase/firebase-tools#249]
Hello,

I am working on firebase web portal since 3-4 months and everything was working fine.
Suddenly I am not able to deploy files on firebase hosting since yesterday.
I am getting error like "Error: Authentication error", though I am already logged in firebase in cmd and also in web console. 
I tried many ways like update firebase tools, change my project directory, changed login password etc. but nothing worked.

Please guide me why it is not working suddenly.
Please check attached screen for ref.

Thanks
![capture](https://cloud.githubusercontent.com/assets/266397/21671434/6a8df20e-d341-11e6-8714-045456f7062a.PNG)

**Comment by xgqfrms-GitHub** [comment]
https://github.com/firebase/firebase-tools/issues/250

**Comment by Quethzel** [comment]
you need to run the command` firebase login` and login with your google account.

**Comment by mbleigh** [comment]
If anyone is seeing this, please run with `--debug` and provide the results in a new bug.

**Comment by KishanIos007** [comment]
I am getting error while login I am behind proxy

```
abc@abc-h110m-gaming-3:~/myplaces$ firebase login --debug --no-localhost
[2019-07-12T13:04:37.174Z] ----------------------------------------------------------------------
[2019-07-12T13:04:37.177Z] Command:       /usr/bin/node /usr/bin/firebase login --debug --no-localhost
[2019-07-12T13:04:37.177Z] CLI Version:   7.1.0
[2019-07-12T13:04:37.177Z] Platform:      linux
[2019-07-12T13:04:37.177Z] Node Version:  v12.6.0
[2019-07-12T13:04:37.178Z] Time:          Fri Jul 12 2019 18:34:37 GMT+0530 (India Standard Time)
[2019-07-12T13:04:37.178Z] ----------------------------------------------------------------------

? Allow Firebase to collect anonymous CLI usage and error reporting information? No

Visit this URL on any device to log in:
https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=87987303&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob

? Paste authorization code here: 4/hAHHYaU9w-qMimLRhATv3fgBKu3RUrzQh3r1JYSlOFc57fHRywUAkPc
[2019-07-12T13:04:48.336Z] >>> HTTP REQUEST POST https://accounts.google.com/o/oauth2/token  
 code=4/hAHHYaU9w-qMimLRhATv3fgBKu3RUrzQh3r1JYSlOFc57fHRywUAkPc, client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com, client_secret=j9iVZfS8kkCEFUPaAeJV0sAi, redirect_uri=urn:ietf:wg:oauth:2.0:oob, grant_type=authorization_code
[2019-07-12T13:04:48.371Z] Token Fetch Error: Error
    at new FirebaseError (/usr/lib/node_modules/firebase-tools/lib/error.js:9:18)
    at Request._callback (/usr/lib/node_modules/firebase-tools/lib/api.js:30:31)
    at self.callback (/usr/lib/node_modules/firebase-tools/node_modules/request/request.js:185:22)
    at Request.emit (events.js:203:13)
    at Request.EventEmitter.emit (domain.js:471:20)
    at Request.onRequestError (/usr/lib/node_modules/firebase-tools/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:203:13)
    at ClientRequest.EventEmitter.emit (domain.js:471:20)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
    at TLSSocket.emit (events.js:203:13)

Error: Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
```

**Comment by dhruvishp158** [comment]
> I am getting error while login I am behind proxy
> 
> ```
> abc@abc-h110m-gaming-3:~/myplaces$ firebase login --debug --no-localhost
> [2019-07-12T13:04:37.174Z] ----------------------------------------------------------------------
> [2019-07-12T13:04:37.177Z] Command:       /usr/bin/node /usr/bin/firebase login --debug --no-localhost
> [2019-07-12T13:04:37.177Z] CLI Version:   7.1.0
> [2019-07-12T13:04:37.177Z] Platform:      linux
> [2019-07-12T13:04:37.177Z] Node Version:  v12.6.0
> [2019-07-12T13:04:37.178Z] Time:          Fri Jul 12 2019 18:34:37 GMT+0530 (India Standard Time)
> [2019-07-12T13:04:37.178Z] ----------------------------------------------------------------------
> 
> ? Allow Firebase to collect anonymous CLI usage and error reporting information? No
> 
> Visit this URL on any device to log in:
> https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=87987303&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob
> 
> ? Paste authorization code here: 4/hAHHYaU9w-qMimLRhATv3fgBKu3RUrzQh3r1JYSlOFc57fHRywUAkPc
> [2019-07-12T13:04:48.336Z] >>> HTTP REQUEST POST https://accounts.google.com/o/oauth2/token  
>  code=4/hAHHYaU9w-qMimLRhATv3fgBKu3RUrzQh3r1JYSlOFc57fHRywUAkPc, client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com, client_secret=j9iVZfS8kkCEFUPaAeJV0sAi, redirect_uri=urn:ietf:wg:oauth:2.0:oob, grant_type=authorization_code
> [2019-07-12T13:04:48.371Z] Token Fetch Error: Error
>     at new FirebaseError (/usr/lib/node_modules/firebase-tools/lib/error.js:9:18)
>     at Request._callback (/usr/lib/node_modules/firebase-tools/lib/api.js:30:31)
>     at self.callback (/usr/lib/node_modules/firebase-tools/node_modules/request/request.js:185:22)
>     at Request.emit (events.js:203:13)
>     at Request.EventEmitter.emit (domain.js:471:20)
>     at Request.onRequestError (/usr/lib/node_modules/firebase-tools/node_modules/request/request.js:881:8)
>     at ClientRequest.emit (events.js:203:13)
>     at ClientRequest.EventEmitter.emit (domain.js:471:20)
>     at TLSSocket.socketErrorListener (_http_client.js:402:9)
>     at TLSSocket.emit (events.js:203:13)
> 
> Error: Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth
> 
> For CI servers and headless environments, generate a new token with firebase login:ci
> ```

hey bro
did you solve this problem??
