### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by rbashish** [firebase/firebase-tools#2493]
Hi, 
I have installed `Firebase CLI` through `npm install -g firebase-tools` but when I try to login by executing `firebase login`, I get `Segmentation Fault` error.

I don't understand what this is. Is it because of npm version ?

**Comment by samtstern** [comment]
@rbashish please fill out the issue template when filing an issue, we need all of the information requested in order to begin debugging.

For instance we need to know:

- What platform are you on?
- What version of the Firebase CLI are you using?
- What version of Node are you using?

**Comment by rbashish** [comment]
Hi @samtstern, here is the information requested:

**Platform**: `Linux [Ubuntu 18.04]`
**Firebase CLI**: `Segmentation fault`
**Node**: `12.18.3`

Additionally please refer to the screenshot:

![rbashish-firebase](https://user-images.githubusercontent.com/6831399/88771345-bcbfa100-d19c-11ea-8417-3286da6e2bba.png)

**Comment by samtstern** [comment]
Hmmm that's very strange.  Can you try one of the other install methods here?
https://firebase.google.com/docs/cli#install-cli-mac-linux

First uninstall `firebase-tools`
```
npm uninstall -g firebase-tools
```

Then use the other installer:
```
curl -sL https://firebase.tools | bash
```

**Comment by rbashish** [comment]
Hey @samtstern, I got this: The Segmentation fault was coming because my machine had a **corrupted firebase-tools binary installed**. So did an upgrade.

`curl -sL firebase.tools | upgrade=true bash`

Thnaks to your help!
