### ISSUE TITLE
Cloud functions from Firestore trigger have undefined context parameters in emulator tests

### ISSUE THREAD

**Issue by noelmansour** [firebase/firebase-tools#2495]
### [REQUIRED] Environment info

**firebase-tools:** 8.6.0

**Platform:** macOS

### [REQUIRED] Test case

Create a test that calls a cloud firestore triggered function that references the context parameter, e.g. 
```typescript
functions.firestore.document('users/{userId}').onUpdate((change, context) => {
    console.log(context.params.userId);
});
```

### [REQUIRED] Steps to reproduce

Run the test using emulator suite:
```bash
firebase emulators:exec "npm run test"
```

### [REQUIRED] Expected behavior

The context param should match that from the path of the document.

### [REQUIRED] Actual behavior

The context param is undefined.

I haven't tested this outside the emulator.

**Comment by noelmansour** [comment]
This can also be seen with the RTDB as well. In fact, when running the test from the [functions-samples](https://github.com/firebase/functions-samples/blob/master/quickstarts/uppercase/functions/test/test.online.js), I get the following output:

```bash
  Cloud Functions
    makeUpperCase
Uppercasing undefined input
      ✓ should upper case input and write it to /uppercase (919ms)
    addMessage
      ✓ should return a 303 redirect (45ms)


  2 passing (975ms)
```

Note the log containing "undefined" which is referencing a context param:

https://github.com/firebase/functions-samples/blob/fd298059a457bb1c12b46b0c01ee8492ce2bb7a1/quickstarts/uppercase/functions/index.js#L52

**Comment by noelmansour** [comment]
Looks like this is an issue with firebase-functions-test and not the emulator suite. See https://github.com/firebase/firebase-functions-test/issues/10

**Comment by samtstern** [comment]
Thanks for following up!
