### ISSUE TITLE
I am not install Firebase CLI tools using npm. Please help

### ISSUE THREAD

**Issue by rusherr02** [firebase/firebase-tools#2497]
Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. All rights reserved.

```
C:\Users\manav>npm -v
'CALL "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\\node_modules\npm\bin\npm-cli.js" prefix -g' is not recognized as an internal or external command,
operable program or batch file.
6.14.6

C:\Users\manav>firebase -v
internal/modules/cjs/loader.js:1068
  throw err;
  ^

Error: Cannot find module 'C:\Users\manav\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1065:15)
    at Function.Module._load (internal/modules/cjs/loader.js:911:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

C:\Users\manav>

Please help me!
I tried many times

**Comment by samtstern** [comment]
It's not clear from your post what happened but there are many ways to install the CLI:
https://firebase.google.com/docs/cli#install-cli-windows

Please try those methods and if they don't work, please file a new issue and provide all the information in the issue template.

**Comment by rusherr02** [comment]
I installed nodejs fro nodejs.org
And then from that..
i entered the command
npm install -g firebase-tools
Then some processing occurs...

But then when i entered firebase -v
It throws as i already mentioned in my issue.

I already did this things many times but i am unable to use/install
firebase in my pc.

I don't know why!
That's why i asked for help.
:)

**Comment by samtstern** [comment]
Since it seems like your Node install may be a problem please try the 'standalone binary' option on the link I gave you.  You'll be able to get a `firebase.exe` file that does not require Node on your machine.
