### ISSUE TITLE
Cannot create project

### ISSUE THREAD

**Issue by jarl-dk** [firebase/firebase-tools#2498]
### [REQUIRED] Environment info

**firebase-tools:** 8.6.0

**Platform:** Ubuntu

### [REQUIRED] Test case

Just creating a project

### [REQUIRED] Steps to reproduce

```bash
$ firebase projects:create
? Please specify a unique project id (warning: cannot be modified afterward) [6-30 characters]:
 identity-blablah
? What would you like to call your project? (defaults to your project ID) TestProject
✔ Creating Google Cloud Platform project
✖ Adding Firebase resources to Google Cloud Platform project

Error: Failed to add Firebase to Google Cloud Platform project. See firebase-debug.log for more info.

```

### [REQUIRED] Expected behavior

A project is created

### [REQUIRED] Actual behavior

Failed to add firebaseto google cloud project

**Comment by jarl-dk** [comment]
I notice this line in the logfile:
```
[debug] [2020-07-28T15:12:49.486Z] >>> HTTP REQUEST POST https://firebase.googleapis.com/v1beta1/projects/identity-blablah:addFirebase
```
Especially the `v1beta1` part of the API URL.

**Comment by jarl-dk** [comment]
Additional information.
I am a first timer wrt firebase.
Now that it didn't work out for me. I googleed and added firebase to the project manually via the browser. Through that process I had to accept several terms and ended up sucesfully adding firebase to that project.
After that first time to add firebase.
I tried again with
```sehll
firebase projects:create
```
and now it work flawlessly. So it seems there is an issue. Probably terms that needs to be accepted first time.

**Comment by samtstern** [comment]
@jarl-dk that's very interesting thanks for following up!  Could you show the whole log file from the failure?  I want to see the response code from that `POST` request.

**Comment by GFuzatto** [comment]
I believe this is somewhat related:

while developing gcp deployment manager scripts for iac I couldn't find firebase related resources so i'm implementing as cloudbuild scripts chaining. I couldn't make firebase projects:add --token ... work so I tried to run it locally also without success.
Going even further I also tried firebase login and firebase init to run such command also without success.

Here's firebase-debug.log:

```
[debug] [2020-08-03T14:12:26.525Z] ----------------------------------------------------------------------
[debug] [2020-08-03T14:12:26.526Z] Command:       /usr/local/bin/node /usr/local/bin/firebase projects:addfirebase fuzatto-dm-test
[debug] [2020-08-03T14:12:26.526Z] CLI Version:   8.6.0
[debug] [2020-08-03T14:12:26.526Z] Platform:      linux
[debug] [2020-08-03T14:12:26.527Z] Node Version:  v12.18.3
[debug] [2020-08-03T14:12:26.527Z] Time:          Mon Aug 03 2020 11:12:26 GMT-0300 (Brasilia Standard Time)
[debug] [2020-08-03T14:12:26.527Z] ----------------------------------------------------------------------
[debug] [2020-08-03T14:12:26.527Z] 
[debug] [2020-08-03T14:12:26.531Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2020-08-03T14:12:26.532Z] > authorizing via signed-in user
[debug] [2020-08-03T14:12:26.536Z] > refreshing access token with scopes: ["email","https://www.googleapis.com/auth/cloud-platform","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","openid"]
[debug] [2020-08-03T14:12:26.536Z] >>> HTTP REQUEST POST https://www.googleapis.com/oauth2/v3/token  
 <request body omitted>
[debug] [2020-08-03T14:12:26.786Z] <<< HTTP RESPONSE 200 {"content-type":"application/json; charset=utf-8","vary":"X-Origin, Referer, Origin,Accept-Encoding","date":"Mon, 03 Aug 2020 14:12:28 GMT","server":"scaffolding on HTTPServer2","cache-control":"private","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","alt-svc":"h3-29=\":443\"; ma=2592000,h3-27=\":443\"; ma=2592000,h3-T050=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","accept-ranges":"none","transfer-encoding":"chunked"}
[debug] [2020-08-03T14:12:26.792Z] >>> HTTP REQUEST POST https://firebase.googleapis.com/v1beta1/projects/fuzatto-dm-test:addFirebase  
 
[debug] [2020-08-03T14:12:27.135Z] <<< HTTP RESPONSE 403 {"vary":"X-Origin, Referer, Origin,Accept-Encoding","content-type":"application/json; charset=UTF-8","date":"Mon, 03 Aug 2020 14:12:28 GMT","server":"ESF","cache-control":"private","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","alt-svc":"h3-29=\":443\"; ma=2592000,h3-27=\":443\"; ma=2592000,h3-T050=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","accept-ranges":"none","transfer-encoding":"chunked"}
[debug] [2020-08-03T14:12:27.136Z] <<< HTTP RESPONSE BODY {"error":{"code":403,"message":"The caller does not have permission","status":"PERMISSION_DENIED"}}
[debug] [2020-08-03T14:12:27.137Z] HTTP Error: 403, The caller does not have permission
[debug] [2020-08-03T14:12:27.264Z] FirebaseError: HTTP Error: 403, The caller does not have permission
```
even though cloudbuild's service account might have limited permissions I'm project owner in the gcp project

**Comment by samtstern** [comment]
Tracking this issue internally as bug 162818859, waiting to hear if this is intended behavior or not.

**Comment by GFuzatto** [comment]
update:

I manually added firebase to the project and kept developing, when testing in a new project the deployment script went well. Maybe only the very first organization's firebase project link must be done manually?

**Comment by samtstern** [comment]
@GFuzatto yes that is what @jarl-dk suspects and it sounds like a good theory.  Just waiting for a teammate to confirm and to let me know if there's some way we could detect that state and improve the CLI error.

**Comment by samtstern** [comment]
Via internal discussion (Googlers: b/162818859)

Me:
> So this will be a 403 and the CLI needs to parse the error message to determine if it's a ToS error?

Eng:
> I don't see any better options.

So looks like we need an error handler here.

**Comment by Gorthog** [comment]
I have the exact same error:

```
=== Project Setup
[info] 
[info] First, let's associate this project directory with a Firebase project.
[info] You can create multiple project aliases by running firebase use --add, 
[info] but for now we'll just set up a default project.
[info] 
[debug] [2023-12-12T15:49:08.360Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/availableProjects pageSize=100
[debug] [2023-12-12T15:49:08.811Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/availableProjects 200
[debug] [2023-12-12T15:49:08.811Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/availableProjects [omitted]
[debug] [2023-12-12T15:49:11.743Z] >>> [apiv2][query] POST https://firebase.googleapis.com/v1beta1/projects/testgpt:addFirebase [none]
[debug] [2023-12-12T15:49:12.152Z] <<< [apiv2][status] POST https://firebase.googleapis.com/v1beta1/projects/testgpt:addFirebase 403
[debug] [2023-12-12T15:49:12.152Z] <<< [apiv2][body] POST https://firebase.googleapis.com/v1beta1/projects/testgpt:addFirebase {"error":{"code":403,"message":"The caller does not have permission","status":"PERMISSION_DENIED"}}
[debug] [2023-12-12T15:49:12.152Z] HTTP Error: 403, The caller does not have permission
```

**Comment by joehan** [comment]
Hey @Gorthog - based on the old details here, I think you either need to go to console.cloud.google.com and accept the GCP Terms of Service on the account you are logged in as, or ensure that you have at least the editor role on the project you are using.

Having said that, this issue is pretty old and its very difficult to separate the 2 cases from this error message. I'm going to close this issue as 'won't fix' - if you are still having trouble after trying both these fixes, please reopen a new issue.

**Comment by kovan** [comment]
You can't close it like this, man. There needs to be a better error message for the case, something like "You need to accept the ToS of Firebase to perform this operation, go to https://console.firebase.google.com, manually add Firebase to your GCP, and retry the operation.".

**Comment by bigjimhere** [comment]
Would it be possible to prompt the user to accept the Firebase terms and conditions in the terminal when running the `projects:create` command?

This issue prevents programmatic setup of Firebase projects for new GCP users. We are able to set up many Firebase features using the CLI, but we can't create the project itself.

This issue impedes the onboarding of users onto our platform, as [we have to ask them to manually set up a project](https://stoker-website.web.app/docs/Getting%20Started/#development-environment).

**Comment by kwankyu** [comment]
Today I was bitten by this issue when my student, absolutely a new GCP user, tried to create her first Firebase project. I failed to solve the issue until the class finished. Does "manually setting up a project" mean creating a project in the Firebase web console? Is that enough or should my student run some firebase command  in the terminal after that?

**Comment by bigjimhere** [comment]
@kwankyu yes you need to create a new Firebase project in the web console. You'll be prompted to accept the Firebase terms and conditions there.
