### ISSUE TITLE
Firebase emulator not able to list empty documents even if sub-collection is not null 

### ISSUE THREAD

**Issue by MasterAssailant** [firebase/firebase-tools#2499]
### [REQUIRED] Environment info

**firebase-tools:** 8.4.3
**Platform:** MacOS 10.15.6

### [REQUIRED] Test case

Please refer to steps to reproduce.

### [REQUIRED] Steps to reproduce

Step 1: Start firestore emulator

Step 2: Add a new doc under the path: 
db.collection(`users/{uid}/{sub-col1}/{sub_col1-doc1}/{sub_col1-doc1-sub_col2}`).doc();

### [REQUIRED] Expected behavior

The "users" collection should be displayed together with all the children's components.

### [REQUIRED] Actual behavior

Nothing is displayed. The data is actually there and can be queried just that the UI cannot display the data correctly. For the production server, this can be shown correctly with the intermediate docs and sub-collections shown with an italic font.

Thank you!

**Comment by samtstern** [comment]
@MasterAssailant thanks!  This is a known issue, you can follow along at this link:
https://github.com/firebase/firebase-tools-ui/issues/273
