### ISSUE TITLE
firebase-hosting-firebase-init-error-authentication-error

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [firebase/firebase-tools#250]
http://stackoverflow.com/questions/41590712/firebase-hosting-firebase-init-error-authentication-error
http://stackoverflow.com/questions/34590736/firebase-error-authentication-required-with-firebase-tools
## Error
![](https://i.stack.imgur.com/sNAOb.png)
## OK!
![](https://i.stack.imgur.com/CZvMU.png)

**Comment by xgqfrms-GitHub** [comment]
https://firebase.google.com/docs/auth/web/manage-users
https://www.npmjs.com/package/firebase-tools

**Comment by xgqfrms-GitHub** [comment]
![error authentication error 2](https://cloud.githubusercontent.com/assets/18028768/21849428/b0149da6-d840-11e6-88cb-38bb36278f91.png)
![firebase login failed](https://cloud.githubusercontent.com/assets/18028768/21849429/b031abd0-d840-11e6-9aac-0fe3277334aa.png)

**Comment by katowulf** [comment]
Could you include version info and environment (retry on latest if you aren't already)? Also try starting with logout, followed by another login to rule out an invalid cached token. Also, you referenced an issue related to deploy from behind proxies. Are you also behind a proxy?

**Comment by xgqfrms-GitHub** [comment]
All you said i had been tried out!

**Comment by xgqfrms-GitHub** [comment]
# I always using the latest stable version apps!

but it doen't work at all!

it should be the firebase bugs!

**Comment by xgqfrms-GitHub** [comment]
node v6.9.4

npm v4.0.5

firebase v3.2.0/firebase v3.2.1
