### ISSUE TITLE
Cannot trigger RTDB functions on secondary DB instance when using local emulator

### ISSUE THREAD

**Issue by greenlover1991** [firebase/firebase-tools#2501]
### Description

I posted in https://stackoverflow.com/questions/63145710/how-to-use-a-secondary-db-instance-on-firebase-local-emulator-with-realtime-data but was told to file this as a bug.

I am trying to run Realtime Database triggers on a secondary database instance on the local Firebase Emulator. I have followed the examples in:
* https://stackoverflow.com/questions/59171891/how-do-i-setup-firebase-realtime-db-triggers-for-multiple-databases-using-cloud
* https://firebase.google.com/docs/database/extend-with-functions#specify_the_instance_and_path

by specifying the `instance(dbInstanceId)` after the `functions.database`

But the function will only get triggered on events on the primary database, not on the secondary database.

### [REQUIRED] Environment info

Output of `firebase --version`: 8.6.0

**firebase-tools:**

**package.json**:

```javascript
  "engines": {
    "node": "10"
  },
  "main": "lib/index.js",
  "dependencies": {
    "firebase-admin": "^9.0.0",
    "firebase-functions": "^3.8.0"
  },
```

**Platform:** Windows 10

### [REQUIRED] Test case

Given **lib/index.ts**

```typescript
import * as functions from 'firebase-functions';
import * as admin from 'firebase-admin';

admin.initializeApp();

const defaultDb = admin.database();

// default instance name is 'sgo-personal'
export const onStaffCreatedDefault = functions.database
  .ref('/staff/{name}')
  .onCreate(async (snapshot, context) => {
    defaultDb.ref('/meta/defaultDbCount').set(admin.database.ServerValue.increment(1));
    console.log("Hello from default instance DB");
    return null;
  });

export const onStaffCreatedDb1 = functions.database.instance('db1')
  .ref('/staff/{name}')
  .onCreate(async (snapshot, context) => {
    defaultDb.ref('/meta/db1Count').set(admin.database.ServerValue.increment(1));
    console.log("Hello from DB1");
    return null;
  });

export const onStaffCreatedDb2 = functions.database.instance('db2')
  .ref('/staff/{name}')
  .onCreate(async (snapshot, context) => {
    defaultDb.ref('/meta/db2Count').set(admin.database.ServerValue.increment(1));
    console.log("Hello from DB2");
    return null;
  });
```

### [REQUIRED] Steps to reproduce

1. Add a staff on either `db1` or `db2` instances, no logs are printed.
2. But add a staff in the default instance, all the cloud functions are triggered based on the logs:

```
i  functions: Beginning execution of "onStaffCreatedDefault"
i  functions: Beginning execution of "onStaffCreatedDb2"
>  Hello from default instance DB
i  functions: Finished "onStaffCreatedDefault" in ~1s
i  functions: Beginning execution of "onStaffCreatedDb1"
i  functions: Finished "onStaffCreatedDb1" in ~1s
>  Hello from DB2
>  Hello from DB1
i  functions: Finished "onStaffCreatedDb2" in ~1s
```

### [REQUIRED] Expected behavior

* I expected that `/sgo-personal/meta/db2Count` would be 2 after adding 2 records in `db2`.
* I expected that `/sgo-personal/meta/db1Count` and `/defaultDbCount` would be 1 after adding 1 records each in `db1` and default instance.
* I expected that the "Hello from XXX" logs should only print based on which database instance fired the event.

### [REQUIRED] Actual behavior

* Actual behavior is only events on the default instance triggers **ALL** the functions, when it should have only triggered the `onStaffCreatedDefault` function
* Actual behavior is the `onStaffCreatedDb1` and `onStaffCreatedDb2` are not triggered at all when adding records on those DB instances

See screenshot: ![Local emulator with 3 DB instances](https://i.stack.imgur.com/6q45H.png)

There's no problem when I deployed them to production. I only encountered this issue when using local emulator. 

I'm looking at https://github.com/firebase/firebase-tools/blob/master/src/emulator/functionsEmulator.ts#L409, which always uses the `projectId` as the namespace instead of the `instanceId`, but I'm not sure if this is the correct starting point to trace the cause of the issue. 

Thanks!

**Comment by samtstern** [comment]
Thanks for filing this!  I was able to reproduce with the following functions:
```
const functions = require('firebase-functions');
const admin = require('firebase-admin');
const { app } = require('firebase-admin');

exports.writeOne = functions.https.onRequest(async (req, res) => {
  if (admin.apps.length === 0) {
    admin.initializeApp();
  }
  
  const db1 = admin.database();
  await db1.ref('/foo/bar').set({
    date: new Date().toISOString(),
  });

  res.send('ok');
});

exports.writeTwo = functions.https.onRequest(async (req, res) => {
  if (admin.apps.length === 0) {
    admin.initializeApp({
      databaseURL: 'https://secondary.firebaseio.com',
      credential: admin.credential.applicationDefault()
    });
  }

  const db2 = admin.database();
  await db2.ref('/foo/bar').set({
    date: new Date().toISOString(),
  });

  res.send('ok');
});

exports.triggerOne = functions.database.ref('/foo/bar').onWrite(() => {
  console.log('triggerOne');
  return true;
});

exports.triggerTwo = functions.database.instance('secondary').ref('/foo/bar').onWrite(() => {
  console.log('triggerTwo');
  return true;
});
```

it turns out that **both** triggers get added on the primary database, so basically `.instance()` is ignored.
