### ISSUE TITLE
High vulnerability package need to be updated [dot-prop]

### ISSUE THREAD

**Issue by WuHarry** [firebase/firebase-tools#2503]
![Screen Shot 2020-07-30 at 2 11 00 pm](https://user-images.githubusercontent.com/12295975/88879789-805c7580-d26e-11ea-9464-d1616640729b.png)

Package update request. 

the dot-prop package has been found vulnerable and needed to be updated.

### [REQUIRED] Environment info

8.6.0

**firebase-tools:**

macOS

**Platform:**

### [REQUIRED] Test case

`npm audit`

### [REQUIRED] Steps to reproduce

`npm audit`

### [REQUIRED] Expected behavior

no vulnerability 

### [REQUIRED] Actual behavior

found 2 high severity vulnerabilities in 1370 scanned packages

**Comment by samtstern** [comment]
@WuHarry thanks for filing this!  I tried to get GitHub's dependabot to fix it automatically but it said:
```
Dependabot cannot create a pull request as one or more other dependencies require a version that is incompatible with this update.
```

I'll see why.  Might have to file a bug against some of our dependencies.

**Comment by samtstern** [comment]
Here's the tree:
```
$ npm ls dot-prop
firebase-tools@8.6.0 /Users/samstern/Projects/firebase-tools
├─┬ configstore@5.0.1
│ └── dot-prop@5.2.0 
├─┬ firebase-admin@8.10.0
│ └─┬ @google-cloud/storage@4.6.0
│   └─┬ gcs-resumable-upload@2.3.3
│     └─┬ configstore@5.0.1
│       └── dot-prop@5.2.0 
└─┬ update-notifier@2.5.0
  └─┬ configstore@3.1.2
    └── dot-prop@4.2.0 
```

Let's see if we can update `update-notifier`

**Comment by samtstern** [comment]
@WuHarry we've done all we can do here, @bkendall is working on an update to `superstatic` which will fix the transitive dep.

**Comment by YahangWu** [comment]
Opps, seems that I missed all the messages. Thanks and well done team!
