### ISSUE TITLE
firebase login command showing unexpected error.

### ISSUE THREAD

**Issue by feelthecoder** [firebase/firebase-tools#2512]
![issue-firebase-tools](https://user-images.githubusercontent.com/44005233/89117128-fe13c180-d4b8-11ea-83cc-4c3566b0db17.png)

Trying to solve this issue from last few days but not able to get what's the problem is.

**Comment by feelthecoder** [comment]
Anyone Please help me to solve this issue.

**Comment by aditmodhvadia** [comment]
Run the command again with firebase login --debug and post it again with the details.

**Comment by samtstern** [comment]
@aditmodhvadia is right.  Please follow the issue template when filing issues otherwise it's not possible to debug.

**Comment by feelthecoder** [comment]
![log](https://user-images.githubusercontent.com/44005233/89258629-1fee7f00-d646-11ea-93f6-1755285e953e.png)

**Comment by aditmodhvadia** [comment]
@feelthecoder Can you confirm that does this error occur after you see a successful sign in message in your browser?
And if you are using the terminal via a remote computer or any set up like that, then you might want to use the flag --no-localhost with firebase login so you do not face issues related to it.

**Comment by feelthecoder** [comment]
@aditmodhvadia Browser is not opening by itself .  When i'm following link shown in image then login shows successfully but this error remains as it is.

**Comment by samtstern** [comment]
There have been many similar issues from Windows users, what's happening is the Firebase CLI is failing to launch your browser:
https://github.com/firebase/firebase-tools/issues?q=is%3Aissue+login+ENOENT

The workaround is to do:
```
firebase login --no-localhost
```

And follow the instructions it provides.

**Comment by feelthecoder** [comment]
I have followed the instructions but still not working.

**Error Reported when running firebase login --no-localhost**


VIKAS@VIKAS MINGW64 ~/Desktop/sysweb (working)
$ firebase login --no-localhost
i  Firebase optionally collects CLI usage and error reporting information to help improve our products. Data is collected in accordance with Google's privacy
policy (https://policies.google.com/privacy) and is not used to identify you.

? Allow Firebase to collect CLI usage and error reporting information? Yes
i  To change your data collection preference at any time, run `firebase logout` and log in again.

Visit this URL on any device to log in:
https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=512570070&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob

? Paste authorization code here:
Error: An unexpected error has occurred.

**Comment by samtstern** [comment]
@feelthecoder can you show the debug logs so we can see what the "unexpected error" is?

**Comment by feelthecoder** [comment]
I have already told about the dubug logs in this issue in my previous comments.

LINK

https://github.com/firebase/firebase-tools/issues/2512#issuecomment-668397877

**Comment by samtstern** [comment]
@feelthecoder I am wondering about the debug logs with `--no-localhost`.  So `firebase --debug login --no-localhost`.  I would not expect the error to be the same `ENOENT` error since the`no-localhost` option shouldn't be trying to spawn any processes. 

Is it the same?

**Comment by feelthecoder** [comment]
yes, error is same.

Please have a look:

VIKAS@VIKAS MINGW64 ~/Desktop/sysweb (working)
$ firebase --debug login --no-localhost
i  Firebase optionally collects CLI usage and error reporting information to help improve our products. Data is collected in accordance with Google's privacy
policy (https://policies.google.com/privacy) and is not used to identify you.

? Allow Firebase to collect CLI usage and error reporting information? Yes
i  To change your data collection preference at any time, run `firebase logout` and log in again.

Visit this URL on any device to log in:
https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=752770718&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob

? Paste authorization code here: [2020-08-06T10:54:07.022Z] Error: spawn cmd ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

Error: An unexpected error has occurred.

**Comment by samtstern** [comment]
@feelthecoder thank you for all the information.  Based on your reports it seems to be the same as these closed issues:
https://github.com/firebase/firebase-tools/issues/1765
https://github.com/firebase/firebase-tools/issues/1764
https://github.com/firebase/firebase-tools/issues/1599
https://github.com/firebase/firebase-tools/issues/1546
https://github.com/firebase/firebase-tools/issues/1430

The solution is to modify your `PATH`:
https://github.com/firebase/firebase-tools/issues/1546#issuecomment-516247230
https://github.com/firebase/firebase-tools/issues/1599#issuecomment-523657816

**Comment by feelthecoder** [comment]
Thank you so much. It Worked.

**Comment by adhinugraha** [comment]
> @feelthecoder thank you for all the information. Based on your reports it seems to be the same as these closed issues:
> #1765
> #1764
> #1599
> #1546
> #1430
> 
> The solution is to modify your `PATH`:
> [#1546 (comment)](https://github.com/firebase/firebase-tools/issues/1546#issuecomment-516247230)
> [#1599 (comment)](https://github.com/firebase/firebase-tools/issues/1599#issuecomment-523657816)

I am also facing the same issue like above. i have tried this. There is no chance to paste the code. anyone can help?
