### ISSUE TITLE
CLI errors out when project name is less than 5 chars

### ISSUE THREAD

**Issue by plug-n-play** [firebase/firebase-tools#2514]
### [REQUIRED] Environment info

Firebase version 8.6.0

**firebase-tools:**

**Platform:**
macOS 10.14.6

### [REQUIRED] Test case
Firebase CLI Issue

### [REQUIRED] Steps to reproduce
1. Open Terminal
2. Type `firebase init`
3. Enter project name as less than 6 characters

### [REQUIRED] Expected behavior
The terminal should display validation error and re-prompt to enter valid name greater than 6 or more characters.

### [REQUIRED] Actual behavior
`firebase init` errors out
Please see attached debug logs

[firebase-debug.log](https://github.com/firebase/firebase-tools/files/5012711/firebase-debug.log)

**Comment by aditmodhvadia** [comment]
@plug-n-play Seems like a feature request and not a bug in my opinion. Is it causing any other problems for you?

**Comment by plug-n-play** [comment]
@aditmodhvadia - IMHO, this is an existing feature which is not working as expected in the given use case. There is no description of what went wrong when the request to execute the existing feature fails and relies on user to open the created debug file where error description is found in the logs. Atleast the error description should be displayed in the terminal not everyone tends to open the debug file.

**Comment by aditmodhvadia** [comment]
I get your point. Then the bug over here is to show what went wrong in the terminal and, the feature request can be to re-prompt the user to enter the name of the project again. Just sharing my thoughts on this.
