### ISSUE TITLE
Dependency vulnerability for dot-prop

### ISSUE THREAD

**Issue by shalbert94** [firebase/firebase-tools#2515]
dot-prop has a security vulnerability

https://snyk.io/test/npm/firebase-tools
https://www.npmjs.com/advisories/1213

**Comment by samtstern** [comment]
See https://github.com/firebase/firebase-tools/issues/2503.  This is a transitive dependency through `superstatic` and we're working on it!

**Comment by joeboyscout04** [comment]
Any progress yet on the `superstatic` dependency?

**Comment by bkendall** [comment]
It's coming... soon is the best I can say (as we generally don't discuss
timelines). The superstatic repository itself has been updated to fix the
issue, so at least that part is done! Thanks for your patience.
