### ISSUE TITLE
firebase login redirect_uri_mismatch

### ISSUE THREAD

**Issue by hyperbrave** [firebase/firebase-tools#252]
After a long period of using firebase-tools without issue today I was unable to deploy via the cli, receiving an "Authentication Error".  So I ran firebase logout, and now am unable to login.  firebase login opens a browser window with a Google 400 "redirect_uri_mismatch" error

```
The redirect URI in the request, http://localhost:9005, does not match the 
ones authorized for the OAuth client. Visit 
https://console.developers.google.com/apis/credentials/oauthclient/SOME_
CLIENT_ID?project=MY_PROJECT_ID to update the authorized redirect URIs. 
```

I've added http://localhost:9005 to the console.developers.google "Authorized redirect URIs" list, which already had a firebase uri, but still have no luck logging in with firebase-tools.

Any ideas, or suggestions is appreciated.

I am running node 6.9.4, and firebase-tools 3.2.1

**Comment by hyperbrave** [comment]
this command worked
```
firebase login --interactive
```

**Comment by hyperbrave** [comment]
So this is occurring again, and this time the --interactive option does not work.

**Comment by hammy-109** [comment]
firebase login:ci --interactive

 this is the solution

**Comment by wallofmoments** [comment]
Is there any update on this? I've added the right URL to the API panel, yet none of the commands above produces a positive result

**Comment by krunal704** [comment]
You can try this 
firebase login --no-localhost
and after this you will need to add authorization code which will you will get after login in you browser on provided link

**Comment by medmin** [comment]
oh, man, why is this still not documented ??
