### ISSUE TITLE
firebase-tools cannot be installed using "install -g firebase-tools" command

### ISSUE THREAD

**Issue by alexeysmorkalov** [firebase/firebase-tools#2528]
### [REQUIRED] Environment info

This issue started to occur both on Windows 10 and linux/docker image in github actions

firebase --version
8.2.0
Update available 8.2.0 → 8.6.0 
Run npm i -g firebase-tools to update

// but it fails

**Platform:**
Windows, Linux

### [REQUIRED] Test case

`install -g firebase-tools`

### [REQUIRED] Steps to reproduce
`install -g firebase-tools`

### [REQUIRED] Expected behavior
firebase-tools is installed

### [REQUIRED] Actual behavior
Error, see log at

[2020-08-06T10_16_06_869Z-debug.log](https://github.com/firebase/firebase-tools/files/5034279/2020-08-06T10_16_06_869Z-debug.log)

or 
[Github action log](https://github.com/alexeysmorkalov/WebDevSandbox/runs/953084862?check_suite_focus=true)

**Comment by alexeysmorkalov** [comment]
Closing this since the issue does not happen anymore

**Comment by samtstern** [comment]
Note: this was related to this incident:
https://status.npmjs.org/incidents/cksjqc1w11v5

**Comment by alexeysmorkalov** [comment]
> Note: this was related to this incident:
> https://status.npmjs.org/incidents/cksjqc1w11v5

thank you for info!
