### ISSUE TITLE
Can't authenticate with service account on Jenkins CI server

### ISSUE THREAD

**Issue by wouterdevos** [firebase/firebase-tools#2529]
### [REQUIRED] Environment info

**firebase-tools:**

My machine - 8.6.0

Jenkins CI - 8.4.2

**Platform:**

My machine - macOS

Jenkins CI - Ubuntu

### [REQUIRED] Test case

I am trying to use the firebase CLI on our Jenkins CI to upload Android builds to Firebase App Distribution using a service account with the following command:

`firebase appdistribution:distribute`

### [REQUIRED] Steps to reproduce

I have successfully uploaded an Android build with my machine using a service account. I did this by defining the `GOOGLE_APPLICATION_CREDENTIALS` environment variable as per the documentation found [here](https://firebase.google.com/docs/app-distribution/authenticate-service-account?platform=android). I used the following command to upload the build:

`firebase appdistribution:distribute app/build/outputs/apk/debug/app-debug.apk --app <app-id> --release-notes <release-notes> --groups <group-name> --debug`

The same environment variable has been defined on the Jenkins CI and I have verified that the correct absolute path is being provided to the service account .json file.

### [REQUIRED] Expected behavior

The expected behaviour is that the build should be uploaded successfully.

### [REQUIRED] Actual behavior

```
Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
    at GoogleAuth.getApplicationDefaultAsync (/root/.cache/firebase/tools/lib/node_modules/google-auth-library/build/src/auth/googleauth.js:160:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async GoogleAuth.getClient (/root/.cache/firebase/tools/lib/node_modules/google-auth-library/build/src/auth/googleauth.js:502:17)
    at async GoogleAuth.getAccessToken (/root/.cache/firebase/tools/lib/node_modules/google-auth-library/build/src/auth/googleauth.js:524:24)

Error: Failed to authenticate, have you run firebase login?
```

**Comment by samtstern** [comment]
@wouterdevos if it's working on your machine but not in Jenkins that suggests it's an issue with your Jenkins setup, not the Firebase CLI.

Have you tried setting the env var and running the command all at once, for example:
```bash
GOOGLE_APPLICATION_CREDENTIALS=<path> firebase appdistribution:distribute app/build/outputs/apk/debug/app-debug.apk --app <app-id> --release-notes <release-notes> --groups <group-name> --debug
```

Sometimes CI systems are strange with how environment variables are exposed to commands.

**Comment by jhuleatt** [comment]
In case it helps others: I ran into this exact error, and it turned out that the JSON file that my `GOOGLE_APPLICATION_CREDENTIALS` env var pointed to contained invalid JSON. Due to a copy paste error, I had only copied half of the service account JSON into the file.

**Comment by wouterdevos** [comment]
Hi Sam,

Thank you for reaching out. I have recently received more assistance from
my devops team and we were able to fix the problem. The Firebase CLI is
working fine now. Thank you for your prompt response and suggestions.

Regards,
Wouter

**Comment by samtstern** [comment]
@wouterdevos glad to hear it!
