### ISSUE TITLE
Firebase auth import from firebase to firebase

### ISSUE THREAD

**Issue by zetos** [firebase/firebase-tools#253]
Hello, i am having some issues while trying to migrate auth users from one firebase project to another.

I followed [this steps](https://drive.google.com/file/d/0B94LePkXiqa6VUNoY0RCOGlqUzg/view) to get a `json` of the auth users in a project. Now i need to import them to another firebase project.

looking at the [auth:import commands](https://firebase.google.com/docs/cli/auth-import#json) i would need the `hash-algo` for the import command, wish i found [here](https://github.com/firebase/firebase-tools/issues/248) that the new firebase is now using SCRYPT. But i still need the `rounds` and i guess the `mem-cost` for the import command.

**Comment by Jeroeny** [comment]
Does it work if you leave those parameters out?

**Comment by zetos** [comment]
No, if i enter the command:
 `$ firebase auth:import users.json --hash-algo=SCRYPT`

i get the error: 
`Error: Must provide valid rounds(1..8) for hash algorithm SCRYPT`

**Comment by wyhao31** [comment]
If you contact custom support, they can give you detailed parameters for SCRYPT. But currently, the auth:import code still has a bug. It needs to pick up hash-key from command line options which I ignored before. We'll publish a new version to fix it and make sure the migration can work for you.

BTW, our auth:export will be available soon. [This one](https://drive.google.com/file/d/0B94LePkXiqa6VUNoY0RCOGlqUzg/view) will be deprecated.

Thanks.

**Comment by zetos** [comment]
Good to know, 

Thanks for the help.

**Comment by wyhao31** [comment]
Hey zetos,

New auth:import and auth:export are available now! You can check the [doc](https://firebase.google.com/docs/cli/auth) for more details.

**Comment by bogacg** [comment]
I still get error `!  No hash algorithm specified. Password users cannot be imported.` when I leave parameters out in `auth:import`. In this case users are created, but passwords don't work (`INVALID_PASSWORD` errors on login) 
If I type `firebase auth:import users.json --hash-algo=scrypt --rounds=8 --mem-cost=14` as in [given example here](https://firebase.google.com/docs/auth/web/manage-users#import_user_accounts), I get `Error: Must provide hash key(base64 encoded) for hash algorithm scrypt`

**Comment by wyhao31** [comment]
Hi Bogac,

You still need hash key and salt separator for scrypt. Doc is [here](https://firebase.google.com/docs/cli/auth). You can contact customer support to get these two parameters.

We need to update the doc you attached. Thanks.

**Comment by zetos** [comment]
Right now the only way to get those parameters is by contacting the custom support.

**Comment by pratiknikam** [comment]
These details are available through firebase admin now. Navigate to 

> Console > Project > Authentication > Three little dots on right side of all users > Password Hash Credentials

![image](https://user-images.githubusercontent.com/2853953/35457716-db81e07e-02a7-11e8-872a-709d4ef9f3b1.png)

**Comment by ptkpyitheim** [comment]
I feel like we should add @pratiknikam 's response to the [documentation for auth:export and auth:import.](https://firebase.google.com/docs/cli/auth)

We should also specify --project under an example command line.

I.E.
![Screen Shot 2020-09-04 at 3 22 22 PM](https://user-images.githubusercontent.com/36285777/92282050-7e678100-eec2-11ea-9069-14aa20456131.png)

**Comment by samtstern** [comment]
@ptkpyitheim that's a good idea, I'll add a note about password hash parameters.
