### ISSUE TITLE
database: Port 9000 is not open on localhost, could not start Database Emulator.

### ISSUE THREAD

**Issue by lborgman** [firebase/firebase-tools#2530]
After upgrading right now to firebase-tools 8.7.0 I get the error above when running `firebase emulators:start --inspect-functions`.

This is on Windows 10.

**Comment by samtstern** [comment]
@lborgman what if you change the port the emulator is running on (via `firebase init emulators`)?  Port 9000 could be busy for a number of reasons, it's not clear that this is a bug in the Firebase CLI.

Also please use the issue template when filing bugs, it's there to help us get to an answer sooner.

**Comment by lborgman** [comment]
Thanks, I've rebooted the PC. Everything seems to work again.

I don't have time to file very many issues, but this one was blocking.

 I see a lot of things that looks a bit strange when working with a rather complicated PWA. With a slow, cheap laptop ($400) and recently a lot of network trouble. Instead of debugging those things I just shut down Chrome and restarts it (with the same open tabs). This normally helps, but not this time. 

I'm not surprised that this happens. It is clearly related to error handling in Chrome.

**Comment by samtstern** [comment]
@lborgman understood!  My personal development machine is a 5-year-old Windows laptop that cost $700 back then so I also see plenty of strange and frustrating behavior when trying to run all my different development tools.

Going to close this since it was fixed by a reboot, appreciate your update.

**Comment by misha-reyzlin-hier** [comment]
In my case, the Java process hasn’t shut down after `ctrl+c`ing the terminal process (this happened I think because the functions emulator was showing error output – there was no "graceful shutdown" for sure).

I opened "Activity Monitor" and closed "Java" process and could launch the emulator again.

**Comment by reizkian** [comment]
For me, the command `$firebase emaulators:start` would show 

`Port 9000 is not open on 127.0.0.1, could not start Database Emulator.` 

because I have forced the Emulaor Suite to exit without waiting for subprocess to finish.

**Comment by johnberang12** [comment]
just type `npx kill-port 9000` in the terminal then start the emulator again and it works
