### ISSUE TITLE
Reference another project with "tsconfig.reference and tsconfig.composite"

### ISSUE THREAD

**Issue by paulbijancoch** [firebase/firebase-tools#2532]
### [REQUIRED] Environment info

**firebase-tools:**
7.1.1

**Platform:**
macOS 10.15.4 

### [REQUIRED] Test case
I want to emulate my index.ts (with http-functions and firestore-trigger) with `"serve": "npm run watch | firebase serve --only functions"`, but the emulator ends up with `⚠  Error: Cannot find module '../../src/app/auth/services/auth.trigger'`.
The `"build": "npm run lint && tsc"` runs perfectly fine, with no errors. The setup is a little special since it includes two typescript-projects, with references and composite:

├─ package.json
├─ tsconfig.json
├─ **src**
 │   ├── fileA.ts <-- I want to use these files
 │   ├── fileB.ts
├─ **functions**
 │   ├── package.json
 │   ├── tsconfig.json
 │   ├── src
 │   │   └── index.ts <-- this is the file I want to emulate

### [REQUIRED] Steps to reproduce
Create a project with the descripted structure and the following tsconfigs:

/tsconfig.json
```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "module": "esnext",
    "sourceMap": true,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "resolveJsonModule": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "types": [ "long", "jest" ],
    "lib": [
      "es2017",
      "es2016",
      "es2015",
      "dom"
    ],
    "declaration": true,
    "declarationMap": true,
    "rootDir": ".",
    "composite": true
  },
  "references": [],
  "include": [
    "main.ts",
    "*.ts",
    "src/**/*",
    "*.json"
  ],
  "exclude": [
    "node_modules",
    "functions"
  ]
}
`
functions/tsconfig.json:
`
{
  "compileOnSave": true,
  "compilerOptions": {
    "module": "commonjs",
    "noImplicitReturns": false,
    "noUnusedLocals": false,
    "noImplicitAny": false,
    "outDir": "lib",
    "sourceMap": true,
    "strict": true,
    "target": "es2017",
    "allowJs": true,
    "typeRoots": ["./node_modules/@types"],
    "resolveJsonModule": true
  },
  "references": [
      { "path": "../" }
  ],
  "include": [
    "./"
  ]
}
```

### [REQUIRED] Expected behavior
I hoped that the sources from the main project could be used in the index.ts through typescripts reference attribute.

### [REQUIRED] Actual behavior

```
⚠  Error: Cannot find module '../../src/app/auth/services/auth.trigger'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/generato/Documents/Sources/hi_code/angular/functions/lib/src/index.js:10:24)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
⚠  We were unable to load your functions code. (see above)
   - It appears your code is written in Typescript, which must be compiled before emulation.
   - You may be able to run "npm run build" in your functions directory to resolve this.
```

**Comment by samtstern** [comment]
@paulbijancoch where is `'../../src/app/auth/services/auth.trigger'` defined and where is it imported?  The functions emulator is pretty simple, we just run `node ${yourmainfile.js}` so if it can't find a module that's not likely to be an emulator issue.

**Comment by paulbijancoch** [comment]
Hey @samtstern

My `project/*functions*/src/index.ts` should import my `project/*src*/app/auth/services/auth.trigger.ts`.

To accomplish that, I followed the official [typescript guidelines for cross project references](https://www.typescriptlang.org/docs/handbook/project-references.html):
My **functions**-tsconfig has set a "references" the src-folder (`{ "path": "../" }`).
My **src**-tsconfig has set a "composite" to true.

`tsc -b` is running fine for both projects, but when running `node *functions*/lib/main.js` it does not include the build of the **src**-project.

What can I do?

**Comment by samtstern** [comment]
@paulbijancoch it's hard to say exactly what's going wrong, but there's something not right with how you're setting up your build.

Here's a project of mine where I have a similar pattern:
https://github.com/firebase/firebaseopensource.com

There's source in both `functions` and `shared`.  You can see I am able to do parent-dir imports from my functions:
https://github.com/firebase/firebaseopensource.com/blob/master/functions/src/index.ts#L19

I didn't use the technique you did, I just used `include`:
https://github.com/firebase/firebaseopensource.com/blob/master/functions/tsconfig.json#L24

It's important that after your build step, **all** of the built JS ends up in the `functions` folder.  Nothing outside of that will be included in your deployment.

I'm gonna close this issue because it's not a Firebase issue and I don't know enough TS-magic to offer much more advice.  Maybe try StackOverflow!

**Comment by paulbijancoch** [comment]
I see, i tried with `include`, but it still does not work.

Thank you for your help, I'll go with StackOverflow.

**Comment by paulbijancoch** [comment]
@samtstern I solved it by referencing the compiled output in lib (and included the whole project by the `include`).

Thank you for your help 🎉

**Comment by samtstern** [comment]
@paulbijancoch glad it worked out!
