### ISSUE TITLE
i dont see any more callstack

### ISSUE THREAD

**Issue by jungmoona** [firebase/firebase-tools#2535]
in my case.. 
when occured error  i can see only message
{"severity":"ERROR","message":"Unhandled error [Function: error]"}
coomand line only show that message

this is sample code link 
https://gist.github.com/6c65132c2e18f86d8f85acb805311b17.git

i had updated all npm, firebase-tools
platform : win10

**Comment by samtstern** [comment]
@jungmoona please follow the issue template when filing issues, it's really hard to tell what's going on here or what we should do about it.

If you're still having this issue please file a new issue and fill out the template completely.  We need the steps to reproduce the issue or we can't fix it.
