### ISSUE TITLE
Firebase Hosting: 404. That’s an error.  The requested URL was not found on this server. That’s all we know.

### ISSUE THREAD

**Issue by heliosnarcissus** [firebase/firebase-tools#2540]
### [REQUIRED] Environment info

**firebase-tools:**

**Platform:**

### [REQUIRED] Actual behavior

Last night I was able to successfully deploy my site to Firebase Hosting. 
When I woke up and tried to access my URL, I saw this:

404. That’s an error.

The requested URL was not found on this server. That’s all we know.

What happened ?

**Comment by samtstern** [comment]
@heliosnarcissus this does not sound like an issue with the Firebase CLI (if you think it is, please provide all the information requested).  Since it sounds like you're having an urgent production issue, please write in to Firebase Support:
https://firebase.google.com/support
