### ISSUE TITLE
How can I delete a firestore documents depending on a period of time ? Can I use the server timestamp value?

### ISSUE THREAD

**Issue by jehadmashhour** [firebase/firebase-tools#2541]
I need to delete a documents from Firebase firestore but when i use the following code, it deletes all the documents under the collection path  : 

_await firebase_tools.firestore
        .delete(path, {
        project: process.env.GCLOUD_PROJECT,
        recursive: true,
        yes: true,
        token: functions.config().fb.token
      });_

My question is :  How can I delete a documents depending on a date time ? **For instance , can i delete a documents older than a specific date time or server timestamp value?**

**Comment by samtstern** [comment]
@jehadmashhour no there is no way to delete documents based on conditions.  You have to query the documents first and then delete them individually.

Also this repo is only for issues with the Firebase CLI, please do not post general questions here.

**Comment by jehadmashhour** [comment]
@samtstern Thanks for your quick answer and I'm sorry for posting general questions here but I think my question is related to Firebase CLI and Firebase-tools also.

[https://firebase.google.com/docs/firestore/solutions/delete-collections#cloud_function](url)
(Firebase CLI and firebase-tools have the same meaning from the above link !!)

Please, how i can do a query by Firebase CLI or Firebase-tools , can you help me with a simple example or link  ?

**Comment by samtstern** [comment]
You cannot query with this library, use the Firebase Admin SDK to query.  The technique in the guide you have linked will not work for the query + delete pattern.
