### ISSUE TITLE
servicemanagement.googleapis.com: 404 Method Not Found

### ISSUE THREAD

**Issue by bkendall** [firebase/firebase-tools#2542]
If you are seeing errors (confirmed in the debug logs using `--debug`) for a request to `servicemanagement.googleapis.com` returning the `404` status `Method Not Found`, please upgrade your CLI to `>= v7.2.1`.

Versions of the CLI prior to `v7.2.1` (excluding `v7.1.0`) worked with `servicemanagement.googleapis.com` to get information about projects. That API has been turned down and has been replaced by `serviceusage.googleapis.com`.

Update the CLI to the latest version using `npm install -g firebase-tools@latest`.

Example output:

```
Error: HTTP Error: 404, Method not found.
```

Debug output:

```
[2020-08-11T18:01:47.109Z] Error Context: {
  "body": {
    "error": {
      "code": 404,
      "message": "Method not found.",
      "status": "NOT_FOUND"
    }
  },
  "response": {
    "statusCode": 404,
    "body": {
      "error": {
        "code": 404,
        "message": "Method not found.",
        "status": "NOT_FOUND"
      }
    },
    "request": {
      "uri": {
        ...
        "host": "servicemanagement.googleapis.com",
        ...
      },
      "method": "GET"
    }
  }
}
```

**Comment by r-ndom-developer** [comment]
@mbleigh that's it, it was still using v6.4.0. Thanks!
