### ISSUE TITLE
After successfully register Service Worker it says "FirebaseError: Messaging: We are unable to register the default service worker. The operation is insecure. (messaging/failed-service-worker-registration)."

### ISSUE THREAD

**Issue by uncannyMBM** [firebase/firebase-tools#2543]
I've registered the service worker before getToken() and it throw me a exception that "FirebaseError: Messaging: We are unable to register the default service worker. The operation is insecure. (messaging/failed-service-worker-registration)."

![fbase](https://user-images.githubusercontent.com/26273211/89934317-37270100-dc32-11ea-9e00-1701ac36e9cd.PNG)

**Comment by samtstern** [comment]
@uncannyMBM this repository is for issues with the Firebase CLI.  I don't think what you're experiencing has anything to do with the CLI, so I am going to close it.

Maybe try StackOverflow?  Or if you think it's an SDK bug, try the `firebase-js-sdk` repo.
