### ISSUE TITLE
Functions emulator surfaces JSON logs at some points

### ISSUE THREAD

**Issue by abeisgoat** [firebase/firebase-tools#2553]
Creating a background function which doesn't return a value results in the JSON version of a warning popping up

```
exports.dbtest = functions.database.ref("/hi").onWrite(() => {
  console.log("db write");
});
```

Invoking it logs...

```
>  {"severity":"WARNING","message":"Function returned undefined, expected Promise or value"}
```

This is... probably my fault and probably a result of the winston changes.

**Comment by GorvGoyl** [comment]
facing the same issue although it shouldn't exist in the first place. solved by putting `return true;` at the end of triggered function.

**Comment by bodike-pilot** [comment]
Thanks @GorvGoyl. The `return true` worked. But what is the rational for it? Why does `return ...trigger_function_output` not work as well?

**Comment by taeold** [comment]
This log entry seems to be intentional:

https://github.com/firebase/firebase-functions/pull/108

(I don't think I understand the rationale though).

Going to mark the issue as WAI and then start an internal discussion on why logging is necessary
