### ISSUE TITLE
Cannot launch firebase emulators (Cloud Functions) requires the module "firebase-admin" to be version >8.9.0 so your version is too old

### ISSUE THREAD

**Issue by begunfx** [firebase/firebase-tools#2556]
### [REQUIRED] Environment info

firebase-tools@8.7.0

macOS

### [REQUIRED] Test case

I don't have any test case.  Please see steps to reproduce below.

### [REQUIRED] Steps to reproduce

Install node version 12 locally, but have firebase functions set to node v10
Install emulators (all of them) into existing firebase project
Launch emulators (will probably get error regarding too old admin version (look for message about node version locally doesn't match global or something like that).
Downgrade node to 10.22
Update tools, functions and admin to latest.
Try to re-run firebase emulators init

### [REQUIRED] Expected behavior

I should be able to get a URL to launch the emulator suite.

### [REQUIRED] Actual behavior

Please see the following log output:
```
i  emulators: Starting emulators: functions, firestore, database, hosting, pubsub
⚠  hosting: The hosting emulator is configured but there is no hosting configuration. Have you run firebase init hosting?
⚠  functions: The following emulators are not running, calls to these services from the Functions emulator will affect production: hosting
✔  functions: Using node@10 from host.
⚠  firestore: Did not find a Cloud Firestore rules file specified in a firebase.json config file.
⚠  firestore: The emulator will default to allowing all reads and writes. Learn more about this option: https://firebase.google.com/docs/emulator-suite/install_and_configure#security_rules_configuration.
i  firestore: Firestore Emulator logging to firestore-debug.log
⚠  database: Did not find a Realtime Database rules file specified in a firebase.json config file. The emulator will default to allowing all reads and writes. Learn more about this option: https://firebase.google.com/docs/emulator-suite/install_and_configure#security_rules_configuration.
i  database: Database Emulator logging to database-debug.log
⚠  hosting: The hosting emulator is configured but there is no hosting configuration. Have you run firebase init hosting?
i  pubsub: Pub/Sub Emulator logging to pubsub-debug.log
i  ui: Emulator UI logging to ui-debug.log
i  functions: Watching "/Users/begun/Dropbox/SCHOOL/CLASSES/CSUMB/Capstone/VueDeu-Device_Management_Tool/CODE/VueDeu_CloudFunctions/functions" for Cloud Functions...
⚠  The Cloud Functions emulator requires the module "firebase-admin" to be version >8.9.0 so your version is too old. You can probably fix this by running "npm install firebase-admin@latest" in your functions directory.
i  functions: Your functions could not be parsed due to an issue with your node_modules (see above)
```

**Comment by samtstern** [comment]
@begunfx have you run `npm install` inside `VueDeu_CloudFunctions/functions`?  You have to do that every time you change your `node` version.

**Comment by begunfx** [comment]
@samtstern thanks for the suggestion.  I tried running npm install as you suggested but I'm still getting the same error.

**Comment by samtstern** [comment]
@begunfx can you show:

  1. Your `functions/package.json` file
  2. The debug logs from this failure

**Comment by begunfx** [comment]
package.json file:
```
{
  "name": "functions",
  "scripts": {
    "lint": "tslint --project tsconfig.json",
    "build": "tsc",
    "serve": "npm run build && firebase serve --only functions",
    "shell": "npm run build && firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "engines": {
    "node": "10"
  },
  "main": "lib/index.js",
  "dependencies": {
    "firebase-admin": "^8.6.1",
    "firebase-functions": "^3.3.0",
    "nodemailer": "^6.4.6"
  },
  "devDependencies": {
    "tslint": "^5.12.0",
    "typescript": "^3.2.2"
  },
  "private": true
}
```

As for the debug logs, I don't see a log file for the functions.  I have one for:
database-debug.log
firestore-debug.log
pubsub-debug.log
ui-debug.log

**Comment by samtstern** [comment]
@begunfx the fix is right in the error mesage:
```
⚠  The Cloud Functions emulator requires the module "firebase-admin" to be version >8.9.0 so your version is too old. You can probably fix this by running "npm install firebase-admin@latest" in your functions directory.
```

You are using version `8.6.1`:
```json
  "dependencies": {
    "firebase-admin": "^8.6.1",
    "firebase-functions": "^3.3.0",
    "nodemailer": "^6.4.6"
  },
```

Please update `firebase-admin` to `8.9.0` or later.  You can run `npm install --save firebase-admin@8.9.0` in your functions folder to get the minimum required.

**Comment by begunfx** [comment]
Just a little update.  I can launch the firestore emulator if I specify the --only flag.  It seems it's just the functions emulator that refuses to start.

**Comment by begunfx** [comment]
@samtstern that's really weird.  I ran an update on firebase-admin several times and had 9.1 installed.  Not sure why it was showing 8.6.  I just ran it again and this time it launched.  Thanks for the help.  Not sure what happened.
