### ISSUE TITLE
The error message is not friendly

### ISSUE THREAD

**Issue by enif-lee** [firebase/firebase-tools#256]
hi

i've got error message when i login to firebase-cli.

![default](https://cloud.githubusercontent.com/assets/9916002/22728084/5fb3719e-ee1f-11e6-90df-ed2bba4d55b3.JPG)

but, the cli told me just `Error: Authentication Error.`, about what?

so, i try to debug firebase-cli

here is really error about ocurred to me.

in `firebase/lib/api.js`
![123223](https://cloud.githubusercontent.com/assets/9916002/22728173/d48720f6-ee1f-11e6-95fc-6883fb5140c3.JPG)

inner exception was `unable to verify the first certificate`, but auth.js overwrite messages of all kinds of exceptions with `authentication error`. there is no way for the user to check inner exceptions.
![image](https://cloud.githubusercontent.com/assets/9916002/22728370/d64f55ec-ee20-11e6-908a-6d2c814a32e0.png)

exception message is very import point to user about trouble shooting when using tools.

(in my case, i resolved with forwarding message like this capture)
![image](https://cloud.githubusercontent.com/assets/9916002/22728509/a9ecc79a-ee21-11e6-8061-d147ceecafb3.png)

i think, [firebase login issue](https://groups.google.com/forum/#!topic/firebase-talk/JA-DpZ2hmvw), #155 is related issues. 

i'm sorry i did not speak English well.

**Comment by hyperbrave** [comment]
Why does this error occur?

**Comment by lakin32** [comment]
@hyperbrave  I guess behind proxy environment with self-signed-certificate.
