### ISSUE TITLE
Could not load the default credentials in functions:shell, but not an issue with emulators:start or deployed function

### ISSUE THREAD

**Issue by shalbert94** [firebase/firebase-tools#2561]
### [REQUIRED] Environment info

**firebase-tools:** 8.7.0

**Platform:** macOS

**Dependencies:**
"@google-cloud/secret-manager": "3.1.0",
"dotenv": "8.2.0",
"firebase-admin": "8.13.0",
"firebase-functions": "3.9.0",
"plaid": "7.0.0"

### [REQUIRED] Test case

Created an HTTP `onRequest` cloud function that uses Secret Manager. There's plenty of documentation around adjusting 
```
const admin = require('firebase-admin');
admin.initializeApp();
```
to 
```
var admin = require("firebase-admin");
var serviceAccount = require("path/to/serviceAccountKey.json");
admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
  databaseURL: "https://pennyworth-dev-8fbf2.firebaseio.com"
});
```
with making `GOOGLE_APPLICATION_CREDENTIALS` an environment variable pointing to `serviceAccountKey.json`. Unfortunately, that adjustment has changed nothing. 

### [REQUIRED] Steps to reproduce

Unsure of an answer that is better than "run `firebase functions:shell`"

### [REQUIRED] Expected behavior

When running `firebase functions:shell`, there should be no Google credential error when invoking an HTTP (`onRequest`) function, since `firebase emulators:start` and deployed functions don't have any issues.

### [REQUIRED] Actual behavior

Only when invoking the function from within `firebase functions:shell` I receive an error, which is:

> functions: Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
    at GoogleAuth.getApplicationDefaultAsync (/Users/shalomhalbert/Desktop/pennyworth-server/functions/node_modules/@google-cloud/secret-manager/node_modules/google-auth-library/build/src/auth/googleauth.js:155:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
⚠  Your function was killed because it raised an unhandled error.
RESPONSE RECEIVED FROM FUNCTION: 500, Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
    at GoogleAuth.getApplicationDefaultAsync (/Users/shalomhalbert/Desktop/pennyworth-server/functions/node_modules/@google-cloud/secret-manager/node_modules/google-auth-library/build/src/auth/googleauth.js:155:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by samtstern** [comment]
@shalbert94 thank you I was able to reproduce this bug with a simple function:

```js
exports.helloWorld = functions.https.onRequest((request, response) => {
  functions.logger.info("Hello logs!", {structuredData: true});
  response.send(process.env.GOOGLE_APPLICATION_CREDENTIALS || "None");
});
```

When called via HTTP:
```
HTTP/1.1 200 OK
connection: keep-alive
content-length: 89
content-type: text/html; charset=utf-8
date: Thu, 20 Aug 2020 11:19:28 GMT
etag: W/"59-KqBI0JvKZ2v6fruLgXX7gIRK0fA"
x-powered-by: Express

/Users/samstern/.config/firebase/samstern_google_com_application_default_credentials.json
```

When called via shell:
```
$ firebase functions:shell
i  functions: Loaded functions: helloWorld
⚠  functions: The following emulators are not running, calls to these services will affect production: firestore, database, pubsub
firebase > helloWorld()
Sent request to function.
firebase > >  {"structuredData":true,"severity":"INFO","message":"Hello logs!"}

RESPONSE RECEIVED FROM FUNCTION: 200, None
```
