### ISSUE TITLE
Setting a config object with incorrect syntax is being processed successfully by firebase first, but then errors everywhere.

### ISSUE THREAD

**Issue by baermathias** [firebase/firebase-tools#2568]
### [REQUIRED] Version info

**node:**

v12.16.1

**firebase-functions:**

**firebase-tools:**

8.6.0

**firebase-admin:**

### [REQUIRED] Steps to reproduce

Set a config object with incorrect syntax, instead of `slack.user="NewSlackUser"` go with `slack.user=NewSlackUser"`:

`firebase functions:config:set slack.user=NewSlackUser"`

This will be a accepted as valid code: 

`+  Functions config updated.`

After this you can't set or get anything, firebase everytime throws the error `NodeError: write after end`

### [REQUIRED] Expected behavior
Do not accept faulty syntax like this ``firebase functions:config:set slack.user=NewSlackUser"``

**Comment by baermathias** [comment]
@mbleigh both of these packages are deprecated:
https://www.npmjs.com/package/gcloud
https://www.npmjs.com/package/google-cloud
Which one did you use?

**Comment by samtstern** [comment]
@baermathias `gcloud` is a Python-based CLI tool:
https://cloud.google.com/sdk/gcloud

**Comment by joehan** [comment]
@taeold can you check for this case in the new `env` commands that you're working on?

**Comment by taeold** [comment]
What shell do I have to use in order to run the problematic command?

```bash
firebase functions:config:set slack.user=NewSlackUser"
```

isn't accepted in `bash` or `zsh` since the `"` is dangling at the end.

I tried 

```bash
firebase functions:config:set slack.user=NewSlackUser\"
```

And things seem to be fine.

**Comment by baermathias** [comment]
I think I used Tilix:
https://github.com/gnunn1/tilix

**Comment by taeold** [comment]
@baermathias I don't have a good way of checking that terminal. Can you help us verify that the issue persists on that terminal emulator? I find it a bit odd that term is at fault here - if you have time to check that and maybe another terminal, it would help us a ton to track this issue.
