### ISSUE TITLE
Is deploy.js not propagating all necessary cli options to the Uploader?

### ISSUE THREAD

**Issue by bijoutrouvaille** [firebase/firebase-tools#2569]
When using a custom json config (-c flag), the deploy command has been failing for me since at least 8.7.0. Debug output mentioned something about 'from' field missing. As a hacky workaround, I've modified the line referenced below to inherit the `options` object like this:

```
        const uploader = new Uploader({
            ...options, // <------- added this line
            version: deploy.version,
            files: files,
            public: options.config.path(deploy.config.public),
            cwd: options.cwd,
        });
```

https://github.com/firebase/firebase-tools/blob/6f5c7a2006f94a9884ecfec61380d6dd238959f6/src/deploy/hosting/deploy.js#L45

**Comment by samtstern** [comment]
@bijoutrouvaille can you give a more detailed example with:

1. Your config file
2. The exact invocation you're using for the command
3. The logs you get from adding `--debug` when it fails

**Comment by bijoutrouvaille** [comment]
@samtstern  I'll try to get to it, but I'm not sure when I'll have the time. There's definitely an issue there, so I figured posting the little I did is better than nothing. I think this error happens when there's not a file named firebase.json. And if there is, for some parts of the deployment the settings are read from there instead of the file indicated by `-c` flag.
