### ISSUE TITLE
Error: listen EADDRINUSE: address already in use :::5000

### ISSUE THREAD

**Issue by jackmatrix** [firebase/firebase-tools#2585]
### [REQUIRED] Environment info

**firebase-tools:** 8.9.2

**Platform:** macOS Catalina 10.15.6

### [REQUIRED] Test case

I get the following wrning when I start my functions locally 

`⚠  emulators: It seems that you are running multiple instances of the emulator suite for project t-api-e3558. This may result in unexpected behavior.`

### [REQUIRED] Steps to reproduce

Run `firebase emulators:start --only functions`

### [REQUIRED] Expected behavior

When I test my `/HelloWorld` endpoint I am expecting to get a `200 OK Status` with the following json response : 

`{"message" : "Hello world"}`

### [REQUIRED] Actual behavior

Instead I get the following error 

>  events.js:288
>        throw er; // Unhandled 'error' event
>        ^
>  
>  Error: listen EADDRINUSE: address already in use :::5000
>      at Server.setupListenHandle [as _listen2] (net.js:1309:16)
>      at listenInCluster (net.js:1357:12)
>      at Server.listen (net.js:1445:7)
>      at Function.listen (/Users/Desktop/fb_tour/functions/node_modules/express/lib/application.js:618:24)
>      at Object.<anonymous> (/Users/Desktop/fb_tour/functions/index.js:61:5)
>      at Module._compile (internal/modules/cjs/loader.js:1158:30)
>      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
>      at Module.load (internal/modules/cjs/loader.js:1002:32)
>      at Function.Module._load (internal/modules/cjs/loader.js:901:14)
>      at Module.require (internal/modules/cjs/loader.js:1044:19)
>      at require (internal/modules/cjs/helpers.js:77:18)
>      at /usr/local/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:681:33
>      at Generator.next (<anonymous>)
>      at fulfilled (/usr/local/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:5:58)
>      at processTicksAndRejections (internal/process/task_queues.js:97:5)
>  Emitted 'error' event on Server instance at:
>      at emitErrorNT (net.js:1336:8)
>      at processTicksAndRejections (internal/process/task_queues.js:84:21) {
>    code: 'EADDRINUSE',
>    errno: 'EADDRINUSE',
>    syscall: 'listen',
>    address: '::',
>    port: 5000
>  }

**Comment by abeisgoat** [comment]
Try restarting your machine, there's a chance the server didn't shut down properly and it's blocking port 5000

**Comment by Methkal1990** [comment]
This bug is easily reproducible:

function index.js:
```
const functions = require('firebase-functions');
const express = require("express");

const app = express();

app.get("/", (req, res) => {
    res.send("Hello There")
});

app.listen(PORT, console.log(`Listening on port ${PORT}`))
exports.helloWorld = functions.https.onRequest(app);
```
PORT is any not restricted port

then run the emulator:
`firebase serve --only functions`

and curl the function:
`curl http://localhost:5000/PROJECT_ID/us-central1/helloWorld/`

firebase tools version 8.9.1

**Comment by akauppi** [comment]
On macOS, you can see which process is sitting on top of a port by:

```
$ lsof -n -i4TCP:5000
```

Then `kill` the process and you don't need to do a restart.

---

Please also consider closing this issue - unless Firebase plans to do something to prevent ports hanging loose, at times. I think it's not worth the effort. This happens rarely enough.

**Comment by quantuminformation** [comment]
I just don't press control + c twice in row to speed up the process

but yeah, please close if you test 8.10

**Comment by rlueder** [comment]
I'm new to Firebase and stumbled on the `Error: listen EADDRINUSE: address already in use` error, this was the first mention to this specific error so commenting here for someone else with the same issue in the future.

The fix for me [was the one mentioned here ](https://github.com/firebase/firebase-tools/issues/6651#issuecomment-1881647322) to not use `process.env.PORT` and instead hard-code it to some other value (in my case I picked `9000`)

Other related reports of the same issue: #6651 #5418 #4684
