### ISSUE TITLE
Passing any `Authorization: Bearer *` to database REST endpoint bipasses security rules 

### ISSUE THREAD

**Issue by abeisgoat** [firebase/firebase-tools#2586]
Not sure if this is intentional, but it seems to just skip all security if you put ANY bearer token in.

**Comment by samtstern** [comment]
@abeisgoat do you have a test case here?  I thought `Bearer` was used for both ID tokens and access tokens?

**Comment by yuchenshi** [comment]
Hi @abeisgoat, thanks for the issue! I'd also like to take a chance to thank you for your continued contribution to Firebase.

Anyway, tl;dr RTDB REST API only accepts access tokens (OAuth admin access) in the `Authorization` header. If you'd like to pass an Firebase ID Token, you must use the `auth` query parameter. You can find out more at https://firebase.google.com/docs/database/rest/auth#authenticate_with_an_id_token

The RTDB Emulator intentionally does not validate Authorization header and will assume admin access for all strings.

**Comment by abeisgoat** [comment]
Why do we not validate the authorization header? It feels very strange to have the emulator bypass rules without warning then deploy and have totally different behavior.

**Comment by abeisgoat** [comment]
Nevermind, I understand now.
