### ISSUE TITLE
Cloud Run Vs Cloud Function Hosting Behaviour

### ISSUE THREAD

**Issue by Nishath4** [firebase/firebase-tools#2593]
As I see firebase help docs I can understand that I can only specify the cloud function rewrite for only us1-central since firebase hosting origin is available only there. If that the case then how can firebase is able to support region in rewrites for cloud run alone and why not cloud functions. Can anyone please let me know the difficulties in that and the behaviour of firebase hostig

**Comment by samtstern** [comment]
@Nishath4 this doesn't sound like a bug or a feature request for the Firebase CLI, so I am going to close this issue.  I don't know the answer to why rewrites work this way!  I would suggest asking on one of our more "conversational" community channels like Slack or our Google Group:
https://firebase.google.com/community
