### ISSUE TITLE
Limit access tokens to project scopye

### ISSUE THREAD

**Issue by treeder** [firebase/firebase-tools#2594]
I think #825 should be reopened. These feels like a really bad security issue if you add a personal token that can access all of your projects to a CI. It would be much better to be able to limit it to a single project. 

I'm referring to generating tokens via:

```sh
firebase login:ci
```

**Comment by samtstern** [comment]
This is basically what @mbleigh said here:
https://github.com/firebase/firebase-tools/issues/825#issuecomment-685106830
