### ISSUE TITLE
Connect to firestore emulator with admin SDK requires supplying the project-id

### ISSUE THREAD

**Issue by ZYinMD** [firebase/firebase-tools#2602]
I found that when I have a firestore running on local emulator, and I want to directly access it with a script using the admin SDK, I need to supply the project-id to the admin SDK, which I believe is not the intended behavior.

I use the nodejs `firebase-admin` package, not sure if the bug is theirs.

### [REQUIRED] Environment info

**firebase-tools:**
8.10.0
**npm firebase-admin package**
9.1.1 

**Platform:**
Windows
### [REQUIRED] Test case

see below
### [REQUIRED] Steps to reproduce

1. have the firestore emulator running
2. create a `test.js` locally:
```js
const admin = require('firebase-admin'); 
admin.initializeApp();
admin.firestore().collection('foo').add({ a: 1 });
```
3. run it: `$ FIRESTORE_EMULATOR_HOST="localhost:8080" node test.js`
### [REQUIRED] Expected behavior

should see a document created in the emulator firestore UI
### [REQUIRED] Actual behavior
`Error: Unable to detect a Project Id in the current environment.`

To fix this, I need to supply the project id to the admin SDK:
```js
admin.initializeApp({ projectId: 'my-project-id' }); // now works
```
But I believe it's not the intended behavior.

**Comment by markgoho** [comment]
try
``` js
const firebase = require('@firebase/testing');

function getAdminFirestore() {
  return firebase.initializeAdminApp({ projectId: MY_PROJECT_ID }).firestore();
}
```

**Comment by ZYinMD** [comment]
Hi @markgoho , thanks, your snippet was the same as mine (at the bottom of my post). 

The issue is not getting it to work, the issue is that project-id shouldn't be required. This code is very likely for the purpose of unit testing, and 1. I may change the project id with `firebase use`, and 2. I may not want to commit my project-id into source control for open source projects, which is why `.firebaserc` is a separate file from `firebase.json`.

**Comment by samtstern** [comment]
@ZYinMD this is the intended behavior, without some project ID (does not have to be a real one!) the Firestore Admin SDK can't construct the right calls to the Firestore API, or in this case the Firestore Emulator.

If you want to set this without modifying source code, use the `GCLOUD_PROJECT` environment variable which is respected by all Cloud SDKs.

**Comment by ZYinMD** [comment]
Hi @samtstern , thanks! Should it be mentioned in the doc [here](https://firebase.google.com/docs/emulator-suite/connect_firestore#admin_sdks)?

Also, about "project ID doesn't need to be a real one" that you mentioned: I tried to set it to 'foo', and indeed, it still works, which blew my mind. Should it also be mentioned in the doc?

**Comment by samtstern** [comment]
@ZYinMD I will update the docs, thanks!

**Comment by samtstern** [comment]
@ZYinMD just FYI if you're using the Firestore and Functions emulators together make sure they have the same project ID!  Otherwise triggers won't fire, etc.

**Comment by ZYinMD** [comment]
@samtstern to clarify: the emulator reads the real project-id from `.firebaserc`, and the admin-sdk running with the functions is also part of the emulator, which also reads the same project-id, which has no issues. However, the test suites mentioned in the OP is manually given a project-id, and you're saying this one should also be the same one, which is the real id, correct?

**Comment by samtstern** [comment]
@ZYinMD sorry for the slow response but yes that's exactly it.

**Comment by vajahath** [comment]
@samtstern If you could also add a single line code to [that documentation](https://firebase.google.com/docs/emulator-suite/connect_firestore#admin_sdks), that would be very nice. like:
```ts
admin.initializeApp({ projectId: 'my-project-id' });
```

**Comment by samtstern** [comment]
@vajahath will do!

**Comment by ZYinMD** [comment]
Hi @samtstern, I see that you have updated [the doc](https://firebase.google.com/docs/emulator-suite/connect_firestore#admin_sdks) since the discussion above. 

I just found that using a fake project-id has more problems than I thought - the documents inserted into the db with a fake project-id won't show up in the emulator UI, which means the setup of a fake-project id + admin-sdk + emulator for prototyping is pointless. 

You might want to make it more clear in the doc, the way it's written now is a little misleading because it advertises something that sounds great, but don't really work.

It's also worth noting that this setup is still usable in unit testing, because the tests don't involve the emulator UI. However, the test becomes flaky when it involves both directly accessing the db and accessing the db via functions, because the functions will always use the real project-id stored in `firebaserc`.

**Comment by samtstern** [comment]
@ZYinMD we're working on showing multiple databases in the Firestore Emulator UI, you can follow that here:
https://github.com/firebase/firebase-tools-ui/issues/281

**Comment by JamieDixon** [comment]
@ZYinMD Your comment here lead me to realise that the `project-id` relates to the project being used by `firebase use`. I was completely unaware that this was the case and was struggling to understand how the `project-id` had any relevance given that the docs say you can use anything you want. Thank you!

**Comment by MchlG** [comment]
So is there no way to view data in the Firestore emulator UI while using a fake project id? Right now the data only displays in the UI when I use the project ID that matches the project which I set via `firebase use` which means I have to use my real project id...

**Comment by samtstern** [comment]
You can always start the Firebase CLI using a fake project ID to match. Use
`firebase —project=<whatever> emulators:start`

But yes you do need to use the same project ID everywhere

**Comment by RicardoAratani** [comment]
I faced a similar problem. I was using two different projects, one for development another for production.
There are many places where the project ID is used, and a mismatch can yield weird bugs that can be hard to troubleshoot:
- .firebaserc on your project directory
- the admin.initializeApp() call
- the url used to call the functions (HTTP 404 when wrong)
- the RTDB name, if kept the default
- the service Account json file
- the google-services.json file
More?

**Comment by samtstern** [comment]
@RicardoAratani we are working on a plan to make it much more obvious when you have a project ID mismatch and also make it easier to set things up!
