### ISSUE TITLE
Dialogflow detectIntent stopped working after updating firebase-tools to 8.10.0

### ISSUE THREAD

**Issue by ValeraKvip** [firebase/firebase-tools#2605]
###  Environment info

8.7.0 //After downgrade

**firebase-tools:** 8.10.0

**package.json(only with related to question dependencies):**
    "dialogflow": "^1.2.0",
    "firebase-admin": "^8.13.0",
    "firebase-functions": "^3.6.1",
    "pb-util": "^0.1.3"

**Platform:** Windows 

### Test case
I'am using node js, firebase functions, firebase admin - to request dialogflow API. 
Today i have updated firebase tools to latest version (8.10.0) and got error:

> 'detectIntent Error: 7 PERMISSION_DENIED: Dialogflow API has not been used in project "[Looks like random number instead of my id] before or it is disabled" ...'

After downgrade  version to 8.7.0 everything works again! I have been developing the application for a long time, so there could be no problems on my part

###  Steps to reproduce 

I'am using code similar to this guide : 
 https://www.npmjs.com/package/@google-cloud/dialogflow

The error should be on this line
` const responses = await sessionClient.detectIntent(request);`

###  Expected behavior

have to return response with detected intent https://cloud.google.com/dialogflow/es/docs/reference/rest/v2/projects.agent.sessions/detectIntent

###  Actual behavior

Returns an error.

**Comment by samtstern** [comment]
@ValeraKvip this sounds like an error that happens while your functions are running, is that right?  If so this is not an issue with `firebase-tools` which is only involved in deployment.  I would suggest filing an issue with DialogFlow as that error comes from them.
