### ISSUE TITLE
Security Vulnerability in generated functions/package-lock.json

### ISSUE THREAD

**Issue by JuanJTorres11** [firebase/firebase-tools#2617]
### [REQUIRED] Environment info

 

**firebase-tools:** 8.10.0

**Platform:** Windows 10 2004

### [REQUIRED] Test case

I created a new project and used the firebase-tools CLI to configure some cloud functions that I intend to use; then, I push it to a github repository and activated the dependabot alerts wich created one alert saying that one of the dependencies (node-forge version 0.7.6) in the generatged package-lock.json has a known vulnerability that can be consulted in https://github.com/advisories/GHSA-92xj-mqp7-vmcj 

### [REQUIRED] Steps to reproduce

Link a local project with a firebase project using the firebase CLI and activate the use of functions in the setup process.

### [REQUIRED] Expected behavior

This generates a series of various files and directories that includes the package-lock.json in a new functions directory.

### [REQUIRED] Actual behavior

The dependency node-forge is forced to be 0.7.6 and cannot be automatically upgraded by dependabot after it found the vulnerability because it might conflict with other dependencies.

**Comment by bkendall** [comment]
I think what will really take care of this issue is https://github.com/firebase/firebase-functions/pull/781. `firebase-tools` will need a couple updates too, but `firebase-functions` needs an update too.
