### ISSUE TITLE
Could not start Database Emulator, port taken.

### ISSUE THREAD

**Issue by quantuminformation** [firebase/firebase-tools#2623]
### [REQUIRED] Environment info

firebase-tools: 8.6.0

Platform: MacOS
### [REQUIRED] Test case

Its from a larger project, not sure how much value this will give
### [REQUIRED] Steps to reproduce

If I start the db like so:

`firebase emulators:start --only database --import=./seed --export-on-exit`

then close with ctrl + c

then restart with
`firebase emulators:start --only database --import=./seed --export-on-exit`

I get
```
> functions@ database /Users/nikos/WebstormProjects/mentorcv/functions
> firebase emulators:start --only database --import=./seed --export-on-exit

i  emulators: Starting emulators: database
i  emulators: Shutting down emulators.
i  hub: Stopping emulator hub
⚠  database: Port 9056 is not open on localhost, could not start Database Emulator.
⚠  database: To select a different host/port, specify that host/port in a firebase.json config file:
      {
        // ...
        "emulators": {
          "database": {
            "host": "HOST",
            "port": "PORT"
          }
        }
      }
i  emulators: Shutting down emulators.
```

### [REQUIRED] Expected behavior
no errors

### [REQUIRED] Actual behavior

I have to keep changing the port

**Comment by samtstern** [comment]
@quantuminformation can you show the logs from shutting down the emulators with Ctrl+C?  It should print a message if they're not able to shut down cleanly.

**Comment by samtstern** [comment]
Also I think there have been a few bugfixes around clean shutdown since `8.6.0`, can you see if you can reproduce on the latest version?

**Comment by quantuminformation** [comment]
thx that fixed it, however with 8.10 I cant import json , new bug?

![image](https://user-images.githubusercontent.com/216566/93595864-c86b5f00-f9b8-11ea-92fe-1aa65be54c78.png)

**Comment by samtstern** [comment]
Yes that's a separate issue, please file a new bug on firebase-tools-ui

**Comment by quantuminformation** [comment]
ok

**Comment by quantuminformation** [comment]
ok https://github.com/firebase/firebase-tools-ui/issues/361

**Comment by quantuminformation** [comment]
Found the same issue with 8.10 installed 
![image](https://user-images.githubusercontent.com/216566/93742040-be7e7180-fbed-11ea-9524-cbf8db3ea1d3.png)

**Comment by samtstern** [comment]
This and #2626 both look like your emulators are not exiting correctly, do you have any logs from the last time they shut down after actually running?  The port being taken is not necessarily a bug.

**Comment by quantuminformation** [comment]
Ill watch it closely next time it happens, the problem seems to have fixed itself again. Are the logs just in the console?

**Comment by quantuminformation** [comment]
looks like im not giving enough time to shut down if I ctrl + c then ctrl + c again to force it

**Comment by samtstern** [comment]
@quantuminformation thanks for following up on this!  And yeah that's correct, one Ctrl+C attempts a clean shutdown (you have to wait) and a second one says "I don't care just give me my terminal back" which means there may be zombie emulators.
