### ISSUE TITLE
Command Not Found Error downloading latest release v8.11.0

### ISSUE THREAD

**Issue by jstheoriginal** [firebase/firebase-tools#2632]
Trying to install the latest release (https://github.com/firebase/firebase-tools/releases/tag/v8.11.0) via CircleCI using `curl -sL firebase.tools | bash` but it's failing with this error (both locally and on CI): 

```
curl -sL firebase.tools | upgrade=true bash                                                                                                                                                                    
tr: Illegal byte sequence
-- Checking for existing firebase-tools on PATH...
error: unknown option '--tool:setup-check'
-- Your machine has firebase-tools@7.14.0, attempting upgrade...
-- Checking your machine type...
-- Downloading binary from https://firebase.tools/bin/macos/latest
######################################################################## 100.0%##O=#  #
-- Setting permissions on binary...
/usr/local/bin/firebase: line 1: Not: command not found
bash: line 262: e: command not found
Something went wrong, firebase has not been installed.
Please file a bug with your system information on Github.
https://github.com/firebase/firebase-tools/
-- All done!
```

### [REQUIRED] Environment info

**firebase-tools:** 7.14.0 (irrelevant since I'm just trying to install the latest with `curl -sL firebase.tools | bash` on CI and `curl -sL firebase.tools | upgrade=true bash` locally

**Platform:** macOS

### [REQUIRED] Test case

run `curl -sL firebase.tools | upgrade=true bash`

### [REQUIRED] Steps to reproduce

run `curl -sL firebase.tools | upgrade=true bash`

### [REQUIRED] Expected behavior

it should install

### [REQUIRED] Actual behavior

it fails to install

**Comment by misterwell** [comment]
We started seeing this on our Travis build environment today as well. Here's the output:

```
$ curl -sL firebase.tools | bash
tr: Illegal byte sequence
-- Checking for existing firebase-tools on PATH...
-- Checking your machine type...
-- Downloading binary from https://firebase.tools/bin/macos/latest
######################################################################## 100.0%
-- Setting permissions on binary...
/usr/local/bin/firebase: line 1: Not: command not found
bash: line 262: e: command not found
Something went wrong, firebase has not been installed.
Please file a bug with your system information on Github.
https://github.com/firebase/firebase-tools/
-- All done!
The command "curl -sL firebase.tools | bash" failed and exited with 1 during .
```

**Comment by misterwell** [comment]
Is it just me, or did an errant `e` character make it into the script at firebase.tools:

Starting at line 255, note the `e` after `then`... I'm no shell expert but seems like that might be causing issues:
```
if [ -z "$VERSION" ]
then
e
    echo "Something went wrong, firebase has not been installed."
    echo "Please file a bug with your system information on Github."
    echo "https://github.com/firebase/firebase-tools/"
    echo "-- All done!"

    send_analytics_event failure
    exit 1
fi
```

**Comment by jstheoriginal** [comment]
I also noticed that the latest release only has the source code and doesn't have these 4 files like all previous releases have.

<img width="261" alt="Screen Shot 2020-09-22 at 5 10 51 PM" src="https://user-images.githubusercontent.com/5117473/93942746-a5151c80-fcf6-11ea-9cd9-b0a2b967b20f.png">

**Comment by bkendall** [comment]
Thanks for the report. I'm raising the issue with the appropriate folks.

**Comment by mdobroggg** [comment]
Same issue from CircleCI:

`-- Checking for existing firebase-tools on PATH...
-- Checking your machine type...
-- Downloading binary from https://firebase.tools/bin/macos/latest
######################################################################## 100.0%#=#=#                                                                         
-- Setting permissions on binary...
/usr/local/bin/firebase: line 1: Not: command not found
bash: line 262: e: command not found
Something went wrong, firebase has not been installed.
Please file a bug with your system information on Github.
https://github.com/firebase/firebase-tools/
-- All done!

Exited with code exit status 1

CircleCI received exit code 1`

**Comment by bkendall** [comment]
I re-published the assets, which I think is the root cause here. Give it a go again and let me know if that didn't resolve the issue.

**Comment by misterwell** [comment]
Can confirm my firebase.tools script run works now, at least on the travis linux build image we use. Thank you for the quick turnaround on this @bkendall & team! It's very much appreciated!

**Comment by jstheoriginal** [comment]
@bkendall all solved for me as well on my local mac & circleci. thanks for the quick turnaround!

**Comment by jbrennan** [comment]
I’m actually still seeing this today when running a build on CircleCI

**Comment by bkendall** [comment]
When we make a new release, the binaries used by the firebase.tools script lag by a few minutes. If you're still seeing issues with the script, please open a new issue (the binaries for 8.11.2 are up and available, so I expect them to be working for you now)
