### ISSUE TITLE
Empty namespaces are not exported on exit

### ISSUE THREAD

**Issue by quantuminformation** [firebase/firebase-tools#2634]
If I click delete on the root node the data is removed in the browser.

![image](https://user-images.githubusercontent.com/216566/93753946-3c984380-fc01-11ea-8872-7ee970d103e1.png)

Im using  `RUNNING_LOCAL=true firebase emulators:start --only database,functions  --inspect-functions   --import=./seed --export-on-exit`

however if I close the terminal and restart all data is still there. The only way I can remove the data on restart is to delete the seed file.

**Comment by samtstern** [comment]
@quantuminformation ok so I think I know what's happening!  When we do the export we ignore any "empty" namespaces, which are databases that have no data.  The reason for this is that sometimes during testing (especially with `@firebase/testing`) people create many databases that they don't want exported.

I think what we need to do is remember which namespaces were imported and then make sure to always export those, even if they're empty at the end.

**Comment by quantuminformation** [comment]
sorry for more work for you guys!

thx
