### ISSUE TITLE
Running functions.config() under emulator returns a proxy, not my actual config

### ISSUE THREAD

**Issue by quantuminformation** [firebase/firebase-tools#2636]
### [REQUIRED] Environment info

firebase-tools: 8.10.0

Platform: MacOS
### [REQUIRED] Test case

Part of a large project. 

### [REQUIRED] Steps to reproduce
try read your config in a node function: `functions.config()`

### [REQUIRED] Expected behavior
same result as running `firebase functions:config:get `  in the console

### [REQUIRED] Actual behavior
If I  try read my config in the function:

functions.config().functions.base_url

I will get error as `functions.config().functions` is undefined

If I log it, I get this:

![image](https://user-images.githubusercontent.com/216566/94068262-3a93d780-fdef-11ea-8270-73bec49b84c7.png)

**Comment by quantuminformation** [comment]
This is what I get when I try run in the emulator:
```
>  Debugger attached.
⚠  TypeError: Cannot read property 'base_url' of undefined
    at Object.<anonymous> (/Users/nikos/WebstormProjects/mentorcv/functions/lib/users.js:14:58)```

**Comment by quantuminformation** [comment]
this is the code 
![image](https://user-images.githubusercontent.com/216566/94144278-3b6d4d80-fe71-11ea-871a-5ad887497a26.png)

**Comment by quantuminformation** [comment]
Not sure if this helps, But I opened another issue on my frontend library

https://github.com/vitejs/vite/issues/854

**Comment by samtstern** [comment]
@quantuminformation we do intentionally proxy `functions.config()` and many other objects inside the emulator.  Do you have `.runtimeconfig.json` in your functions directory?

**Comment by quantuminformation** [comment]
.runtimeconfig.json , nope not there

**Comment by samtstern** [comment]
@quantuminformation ok then this is the expected behavior, see here:
https://firebase.google.com/docs/functions/local-emulator#set_up_functions_configuration_optional

**Comment by quantuminformation** [comment]
The reason I wanted to pull it dynamically is that I use different projects with the same codebase depending on what I'm using.

**Comment by quantuminformation** [comment]
So that fixes my error on the emulator, but would be pain to have to change that failed every time I want to switch live env

**Comment by samtstern** [comment]
@quantuminformation yeah unfortunately there's no support for "pulling" the config.  `functions.config()` is a synchronous interface. 

Your best bet is to just run `firebase functions:config:get > functions/.runtimeconfig.json` before running `firebase emulators:start`, that will make sure it's always fresh.

**Comment by quantuminformation** [comment]
yeah that works, thx again mate

**Comment by quantuminformation** [comment]
how do we get a config when running the emulator?

same code but running

        "emulate": "RUNNING_LOCAL=true firebase emulators:start --only database,functions  --inspect-functions   --import=./seed --export-on-exit  ",

gives;

⚠  It looks like you're trying to access functions.config().hosting but there is no value there. You can learn more about setting up config here: https://firebase.google.com/docs/functions/local-emulator
