### ISSUE TITLE
Unable to reset email or password due to Firebase site not found problem

### ISSUE THREAD

**Issue by MatthewCoetzee412** [firebase/firebase-tools#2639]
### Environment info

**firebase-tools: 8.5.0**

**firebase-auth: ^0.17.0-dev.2**

**Platform: Android**

### Test case

I used this Flutter code:

Reset password:
```Dart
  Future<void> resetPassword(String email) async {
    await _authInstance.sendPasswordResetEmail(email: email);
  }
```

Reset email:
```Dart
  Future<void> resetEmailAddress(
      String newEmail, String oldEmail, String password) async {
    var authResult = await _authInstance.signInWithEmailAndPassword(
        email: oldEmail, password: password);
    await authResult.user.updateEmail(newEmail);
    await _instance
        .collection('users')
        .doc(authResult.user.uid)
        .update({'email': newEmail});
  }
```

### Steps to reproduce

**By using the code above.**

---

### Expected behavior

It should take you to an elegant looking webpage from the URL link sent to your email(which works perfectly fine) where you are able to reset your email or password like below:
![Reset password Firebase image](https://user-images.githubusercontent.com/42652264/94233196-cdc03080-ff07-11ea-8a5f-0516be6d70a8.png)

---

### Actual behavior

But it is instead a Site not Found screen like below:
![image](https://user-images.githubusercontent.com/42652264/94233286-f2b4a380-ff07-11ea-88f9-ae0b469d349a.png)

---
### Flutter Doctor
[√] Flutter (Channel dev, 1.22.0-9.0.pre, on Microsoft Windows [Version 10.0.18363.1082], locale en-ZA)
    • Flutter version 1.22.0-9.0.pre at C:\flutter\flutter
    • Framework revision 7a43175198 (4 weeks ago), 2020-08-28 23:18:04 -0400
    • Engine revision 07e2520d5d
    • Dart version 2.10.0 (build 2.10.0-73.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Matthew Coetzee\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.49.1)
    • VS Code at C:\Users\Matthew Coetzee\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[√] Connected device (1 available)
    • SM A307FN (mobile) • RZ8MC05H2WF • android-arm64 • Android 10 (API 29)

• No issues found!
---

I have the Firebase Hosting activated, and none of the things on that list of what to do on the Firebase Site not found page apply to me as I am using Mobile and not web, and as far as I can tell no one else on YouTube was experiencing this problem whilst dealing with the Flutter framework. I also thought the problem initially was due to the fact I didn't have a custom domain but I am not sure I have seen no one attain this problem without a custom domain.

Thank you for you time, really appreciate it!
- Matt

**Comment by samtstern** [comment]
@MatthewCoetzee412 this does not look like an issue with the Firebase CLI, so this repository is not the place to debug it.  I would suggest a more general forum like StackOverflow or a mailing list: https://firebase.google.com/community
