### ISSUE TITLE
Upgrade firebase-admin to version  8.13.0 or later because the IAM API will no longer be supported

### ISSUE THREAD

**Issue by zawazawazawazawa** [firebase/firebase-tools#2653]
Starting July 1, 2021, API calls to SignBlob and SignJwt (also known as
JSON Web Tokens (JWT)) on the IAM API will no longer be supported and
may fail.

https://cloud.google.com/iam/docs/migrating-to-credentials-api

We must migrate our projects off the IAM API to the new
IAMCredentials API to avoid a service disruption.

The latest firebase-tools (v8.11.2) is depends on firebase-admin v8.10.0.
To use IAMCredentials API instead of IAM API, firebase-admin must be upgraded to v8.13.0 or later.

https://cloud.google.com/iam/docs/migrating-to-credentials-api#blob-client-libraries

**Comment by samtstern** [comment]
@zawazawazawazawa thanks for pointing this out.  We don't actually depend on `firebase-admin`, we only have a `devDependency` on it:
https://github.com/firebase/firebase-tools/blob/master/package.json#L180

And it's at version "^8.9.0" which will automatically choose the highest `8.x` version when you install, so that would include `8.13.0`.

Can you try re-installing `firebase-tools` in your project? That should do it.

**Comment by kmcnellis** [comment]
@samtstern is it worth changing the package.json to be ^8.13.0? (or even ^9)

**Comment by zawazawazawazawa** [comment]
@samtstern 
Thank you for reply.
I overlooked the description `devDependency`.
So in my project, it is not required any actions for this breaking change regarding `firebase-tools`

**Comment by samtstern** [comment]
@kmcnellis we could update to `^8.13.0` although that shouldn't really change anything?  We can't do `^9` yet because that drops Node 8 support.

@zawazawazawazawa thanks for following up!  Since this is fixed for you, going to close this issue.

**Comment by girwin90** [comment]
Hi @samtstern just to confirm with the 1st of July changes, the fact the old IAM URL exists here https://github.com/firebase/firebase-tools/blob/master/src/api.js#L163 doesn't mean an upgrade is needed within firebase-tools?

> Hello,
> 
> Starting July 1, 2021, your calls to SignBlob and SignJwt (also known as JSON Web Tokens (JWT)) on the IAM API will no longer be supported and may fail.
> 
> We are deprecating both authentication methods on: https://iam.googleapis.com
> 
> Instead, you can now use: https://iamcredentials.googleapis.com
> 
> You must migrate your projects off the IAM API to the new IAMCredentials API to avoid a service disruption. The IAMCredentials API supports higher traffic volumes across the network, giving you better access and reliability.

**Comment by samtstern** [comment]
@girwin90 it seems like only the `SignBlob` and `SignJwt` methods on the `iam.googleapis.com` host are being deprecated, not the whole host. We're not using either of those, so we should be fine. Thanks for checking!
