### ISSUE TITLE
`firebase use --clear` doesn't clear the active project

### ISSUE THREAD

**Issue by akauppi** [firebase/firebase-tools#2656]
### [REQUIRED] Environment info

**firebase-tools:** 

`8.11.2`

**Platform:** 

macOS 10.15.7

### [REQUIRED] Test case

Have one project (in `.firebaserc`) and try to switch it "off".

### [REQUIRED] Steps to reproduce

```
$ firebase use --clear
Cleared active project.

Project aliases for /Users/asko/Git/GroundLevel-es-firebase-app:

  dev (vue-rollup-example)

Run firebase use --add to define a new project alias.
```

### [REQUIRED] Expected behavior

- `firebase use` should show that no project is active

### [REQUIRED] Actual behavior

```
$ firebase use
Active Project: dev (vue-rollup-example)

Project aliases for /Users/asko/Git/GroundLevel-es-firebase-app:

* dev (vue-rollup-example)

Run firebase use --add to define a new project alias.
```

### With debug flag:

```
$ firebase use --clear --debug
[2020-09-30T13:54:28.133Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2020-09-30T13:54:28.134Z] > authorizing via signed-in user
Cleared active project.

Project aliases for /Users/asko/Git/GroundLevel-es-firebase-app:

  any (vue-rollup-example)

Run firebase use --add to define a new project alias.

$ firebase use --debug
[2020-09-30T13:54:36.618Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2020-09-30T13:54:36.619Z] > authorizing via signed-in user
Active Project: any (vue-rollup-example)

Project aliases for /Users/asko/Git/GroundLevel-es-firebase-app:

* any (vue-rollup-example)

Run firebase use --add to define a new project alias.
```

### Further observations

If I have two projects, the `firebase use --clear` command works correctly.

**Comment by kmcnellis** [comment]
This is WAI.  If you save a .firebaserc file in git, and share it with other members of your team, we want them to be able to use the default project automatically.  (See https://github.com/firebase/firebase-tools/blob/5fe7ae042efed825db455325d3b9332ca97e9b3d/src/command.ts#L252). 

However, if there are multiple projects in the .firebaserc, we don't know which one to use, so it doesn't set the project by default.

You can also work around this by deleting the .firebaserc file - then we'll just rely on the saved configstore variable, which is cleared by the --clear command.

If you'd like to have version of --clear command that deletes the .firebaserc, or forces the project to be unset, please file a feature request for it.

**Comment by kmcnellis** [comment]
Also related to #781
