### ISSUE TITLE
Hosting i18n rewrites not supported by emulator

### ISSUE THREAD

**Issue by laurentpayot** [firebase/firebase-tools#2664]
### [REQUIRED] Environment info

**firebase-tools:** 8.11.2

**Platform:** Ubuntu 20.04 LTS

### [REQUIRED] Test case

- public directory `dist` structure
```
dist
├── index.html
└── localized
    ├── en
    │   └── index.html
    └── fr
        └── index.html
```
- `dist/index.html`
```html
<html><body>Default hello!</body></html>
```
- `dist/localized/en/index.html`
```html
<html><body>Hello!</body></html>
```
- `dist/localized/fr/index.html`
```html
<html><body>Bonjour!</body></html>
```
- `firebase.json` 
```json
{
"hosting": {
    "public": "dist",
    "i18n": {
        "root": "/localized"
    },
    "ignore": [
        "firebase.json",
        "**/.*",
        "**/node_modules/**"
    ]
}
}
```

### [REQUIRED] Steps to reproduce

```bash
firebase serve -p 8000
```

### [REQUIRED] Expected behavior

Just like described in the doc at https://firebase.google.com/docs/hosting/i18n-rewrites, but on localhost server at port 8000:

`Hello!` displayed on a browser with English language locale `en-US`.
`Bonjour!` displayed on a browser with French language locale `fr-FR`.

### [REQUIRED] Actual behavior

On the actual Firebase deployed website i18n rewrites are working fine. But on localhost:8000, `Default hello!` is displayed whatever the browser locales are. So I cannot locally end-to-end test the i18n of my website.

**Comment by samtstern** [comment]
@laurentpayot thanks for pointing this out!  Hopefully @bkendall can comment on how we can bring this to the emulators.

**Comment by laurentpayot** [comment]
Any news? Emulators are getting closer to the real thing, except for hosting…

**Comment by ayyash** [comment]
index.html works under emulators but 404.html is ignored
