### ISSUE TITLE
Firebase-tools v8.11.2: Segmentation fault

### ISSUE THREAD

**Issue by anton-erofeev** [firebase/firebase-tools#2669]
### [REQUIRED] Environment info

**firebase-tools:**
8.11.2

**Platform:**
Ubuntu 18.04.4

### [REQUIRED] Test case
Any `firebase` command (`firebase deploy`)

### [REQUIRED] Steps to reproduce
1. npm i -g firebase-tools
2. Run `firebase deploy`

### [REQUIRED] Expected behavior
deployment execution

### [REQUIRED] Actual behavior
output: Segmentation fault

**Comment by mbleigh** [comment]
Please run with --debug and provide more context

**Comment by anton-erofeev** [comment]
Hi, @mbleigh 
I run it with --debug flag, but no logs are produced, only "Segmentation fault".
Seems to be related issue: https://github.com/firebase/firebase-tools/issues/2646 but i got this error on Ubuntu 18.04.4

**Comment by bkendall** [comment]
Without more information, we can't really debug this. I think the issue you mentioned in specific to the "built" distributable binaries that we provide, so it's probably not applicable here.

Could you:
1. confirm what version of node you are using?
1. verify that you're using the version installed by `npm`?
1. maybe remove and re-install `firebase-tools`
