### ISSUE TITLE
database-get output to file sometimes fails to write whole content

### ISSUE THREAD

**Issue by andrewliles** [firebase/firebase-tools#267]
I find that a command like this:

`firebase database:get --project PROJECT --token "TOKEN"  --pretty --output t.json / ; tail t.json`

stores invalid JSON 1 out of 3 times in the given file - easily viewable with the tail command; you'll see the last "chunk" of the file is missing.  In my case the full-sized pretty JSON is 99672 bytes.

Environment:

- Node v7.7.1
- NPM 4.1.2
- OS Amazon Linux v4.4.5-15.26.amzn1.x86_64

I guess it might be not flushing some buffer stream in https://github.com/firebase/firebase-tools/blob/master/commands/database-get.js#L75

**Workaround**
Use
`firebase database:get --project PROJECT --token "TOKEN"  --pretty / > t.json ; tail t.json`

**Comment by TomislavHorvat1** [comment]
I have the same problem, but only with one of my larger databases.

@andrewliles  good workaround
