### ISSUE TITLE
Using "apps.list" as a Module returns error "cannot read property 'project' of undefined"

### ISSUE THREAD

**Issue by appdeveloperhw** [firebase/firebase-tools#2672]
### [REQUIRED] Environment info

**firebase-tools:**

firebase-tools : 8.11.2
firebase version : 8.10.0

**Platform:**
macOS

### [REQUIRED] Test case

```
var client = require("firebase-tools");
client
        .use("projectId", { add: true })
        .then(function (data) {
            client.apps.list()
                .then(function (data) {
                    console.log(data);
                })
                .catch(function (err) {
                    console.log(err)
                    // handle error
                });
        })
        .catch(function (err) {
            console.log(err)
        });

```
### [REQUIRED] Steps to reproduce

Call above code from CLI.

### [REQUIRED] Expected behavior
I expect that when calling use() with projectId, and then call apps.list it would print apps list in current active project.

### [REQUIRED] Actual behavior

TypeError: Cannot read property 'project' of undefined
    at module.exports (/Volumes/Data/Folder test/node_modules/firebase-tools/lib/getProjectId.js:7:18)
    at /Volumes/Data/Folder test/node_modules/firebase-tools/lib/commands/apps-list.js:45:23
    at Generator.next (<anonymous>)
    at /Volumes/Data/Folder test/node_modules/firebase-tools/lib/commands/apps-list.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Volumes/Data/Folder test/node_modules/firebase-tools/lib/commands/apps-list.js:4:12)
    at Command.actionFn (/Volumes/Data/Folder test/node_modules/firebase-tools/lib/commands/apps-list.js:44:41)
    at Command.<anonymous> (/Volumes/Data/Folder test/node_modules/firebase-tools/lib/command.js:166:25)
    at Generator.next (<anonymous>)
    at fulfilled (/Volumes/Data/Folder test/node_modules/firebase-tools/lib/command.js:5:58)

**Comment by samtstern** [comment]
That comes from this line:
https://github.com/firebase/firebase-tools/blob/master/src/getProjectId.js#L19

Which means `options` is `undefined`.  It does seem like you're following the docs exactly so this is probably a bug on our side.

**Comment by samtstern** [comment]
@appdeveloperhw so I was able to confirm that this does not work:
```js
client.apps.list()
```

However these do:
```
// Provide "" for the optional "platform" argument and {} for options
const apps = await client.apps.list("", {});

// Provide "ANDROID" for the optional "platform" argument and {} for options
const apps = await client.apps.list("ANDROID", {});
```

So I'll try to update some docs and internal validation methods, but at least this should get things working!
