### ISSUE TITLE
Step 4 on Firebase Codelab FriendlyChat

### ISSUE THREAD

**Issue by affemann2** [firebase/firebase-tools#268]
Hi I  am stuck on step 4 of the walk through. I was able to successfully login. I successfully navigate to the web-start folder on my terminal and then it instructs me set up firebase cli by entering the code: 
firebase use --add

The terminal then reads $ Which project do you want to add? 

and then get's hung up. No options appear. 

the firebase-debug.log reads 
[debug] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase"]
[debug] >>> HTTP REQUEST GET https://admin.firebase.com/v1/projects  
 Sun Mar 05 2017 16:58:09 GMT-0800 (PST)
[debug] <<< HTTP RESPONSE 200

Thanks for the help

**Comment by Mugurel11** [comment]
Same problem here, no answer yet..

**Comment by mbleigh** [comment]
Can you please provide the full platform and version output of running it with `--debug`? Are you behind a proxy or corporate firewall? If you run `firebase list` do you see a list of projects?

**Comment by Mugurel11** [comment]
Problem fixed! It was a rookie mistake. I have 2 google accounts and apparently, even though i am connected to firebase with account #1 (where all my projects are) when i use "firebase list" in cmd it won't show me my projects, but when i am connected to firebase with account #2 "firebase list" will show my projects and "firebase use --add" will work

**Comment by laurenzlong** [comment]
Great to hear! thanks for the update.
