### ISSUE TITLE
`use` command doesn't find projects even when logged in

### ISSUE THREAD

**Issue by quantuminformation** [firebase/firebase-tools#2682]
### [REQUIRED] Environment info

firebase-tools: 8.12.0

Platform: MacOS 

### [REQUIRED] Test case

Part of a large project. 

### [REQUIRED] Steps to reproduce

This simple command used to work before  upgrading to 8.12 fireplace tools

➜  mentorcv git:(master) ✗ firebase use mentor-cv

Error: Invalid project selection, please verify project mentor-cv exists and you have access.

Having trouble? Try firebase [command] --help
➜  mentorcv git:(master) ✗ firebase login
Already logged in as xxxx

### [REQUIRED] Expected behavior
No errors

### [REQUIRED] Actual behavior
Error: Invalid project selection, please verify project mentor-cv exists and you have access.

**Comment by samtstern** [comment]
@quantuminformation please provide `firebase-debug.log` output

**Comment by quantuminformation** [comment]
Is it supposed to be in the same directory as the use command?

**Comment by samtstern** [comment]
@quantuminformation you could also run `firebase --debug use mentor-cv` to get it in your terminal.

**Comment by quantuminformation** [comment]
closing this, it just started working, must have been an old terminal window before the upgrade

**Comment by quantuminformation** [comment]
turned to be my terrible apartment complex  wifi
