### ISSUE TITLE
Prompt for a firebase project during `firebase deploy` if we don't find one

### ISSUE THREAD

**Issue by kmcnellis** [firebase/firebase-tools#2689]
Can we directly prompt for a project in interactive mode if there isn't already one defined, during firebase deploy?

Currently we return 
```
Error: No currently active project.
To run this command, you need to specify a project. You have two options:
- Run this command with --project <alias_or_project_id>.
- Set an active project by running firebase use --add, then rerun this command.
To list all the Firebase projects to which you have access, run firebase projects:list.
To learn about active projects for the CLI, visit https://firebase.google.com/docs/cli#project_aliases
```

**Comment by kmcnellis** [comment]
This prompt would only be show during a `firebase deploy` if a firebase.json file is found, but not a project.

It should ideally include both a project picker, and a workflow to create a new project

**Comment by samtstern** [comment]
@kmcnellis why not just run `firebase use add` before running `firebase deploy`?

**Comment by simondotm** [comment]
I wouldn't upvote this feature since it would potentially block scripted deploys (albeit faulty scripted deploys).
As @samtstern mentioned, `firebase use` works fine. Just do that.
