### ISSUE TITLE
The latest release v8.12.1 does not contain binaries

### ISSUE THREAD

**Issue by wpK** [firebase/firebase-tools#2690]
### [REQUIRED] Environment info

**firebase-tools:** v8.12.1
**Platform:** macOS, Windows, Ubuntu

### [REQUIRED] Test case

The latest release v8.12.1 does not contain the binaries.

- https://firebase.tools/bin/macos/latest **302 Found**
- https://firebase.tools/bin/linux/latest **302 Found**
- https://firebase.tools/bin/win/latest **302 Found**
- https://github.com/firebase/firebase-tools/releases/download/v8.12.1/firebase-tools-macos **404 Not Found**
- https://github.com/firebase/firebase-tools/releases/download/v8.12.1/firebase-tools-linux **404 Not Found**
- https://github.com/firebase/firebase-tools/releases/download/v8.12.1/firebase-tools-win.exe **404 Not Found**
- https://github.com/firebase/firebase-tools/releases/tag/v8.12.1

### [REQUIRED] Steps to reproduce

Run: `curl -sL https://firebase.tools | bash`

### [REQUIRED] Expected behavior

To install Firebase tools.

### [REQUIRED] Actual behavior

```
curl -sL https://firebase.tools | bash
-- Checking for existing firebase-tools on PATH...
-- Checking your machine type...
-- Downloading binary from https://firebase.tools/bin/macos/latest
######################################################################## 100.0%##=O#- #                                                                      
-- Setting permissions on binary...
/usr/local/bin/firebase: line 1: Not: command not found
Something went wrong, firebase has not been installed.
Please file a bug with your system information on Github.
https://github.com/firebase/firebase-tools/
-- All done!

Exited with code exit status 1
```

**Comment by GreenReaper** [comment]
As a workaround this will retrieve the preceding version, without #2688 or #2634 (can replace linux with macos):

`curl -Lo ./firebase https://firebase.tools/bin/linux/v8.12.0`

Or you can just grab it from [GitHub releases](https://github.com/firebase/firebase-tools/releases/). Of course anyone who got this far probably went there anyway.

**Comment by mbleigh** [comment]
Hey folks, looks like the build process had a problem uploading the standalone binaries with the latest release. I've manually attached the binaries to the release, give it another try!
