### ISSUE TITLE
Installation: mac-linux-auto-script fails

### ISSUE THREAD

**Issue by MiWeiss** [firebase/firebase-tools#2691]
### [REQUIRED] Environment info

**firebase-tools:** n.a.

**Platform:** Ubuntu 20.04.1 LTS 64 bit

### [REQUIRED] Test case

Run (as explained here https://firebase.google.com/docs/cli?authuser=0#mac-linux-auto-script)
> curl -sL https://firebase.tools | bash

Error:
```
[sudo] password for michael: 
-- Checking for existing firebase-tools on PATH...
-- Checking your machine type...
-- Downloading binary from https://firebase.tools/bin/linux/latest
######################################################################## 100.0%##=O#- #                                                                      
-- Setting permissions on binary...
/usr/local/bin/firebase: line 1: Not: command not found
Something went wrong, firebase has not been installed.
Please file a bug with your system information on Github.
https://github.com/firebase/firebase-tools/
-- All done!
```

Running as root leads to the same problem.

### [REQUIRED] Steps to reproduce

See above

### [REQUIRED] Expected behavior

No error. Firebase CLI correctly installed.

### [REQUIRED] Actual behavior

Script aborted, as shown above.

**Comment by alexrbrowne** [comment]
This is effecting all our builds at the moment. Looking for work arounds.

**Comment by daltonclaybrook** [comment]
It appears that the [v8.12.1 release](https://github.com/firebase/firebase-tools/releases/tag/v8.12.1) that was created 16 hours ago does not contain many of the normal release assets such as `firebase-tools-macos`. When the install script tries to download these assets, it receives a 404 from GitHub and fails installation.

**Comment by MiWeiss** [comment]
Thanks @daltonclaybrook.
Thus, this appears to be a duplicate of #2690.
