### ISSUE TITLE
Spark plan must use Node.js 8 but it's being deprecated Mar 15, 2021. What's the plan?  

### ISSUE THREAD

**Issue by cookmscott** [firebase/firebase-tools#2698]
Hello, Firebase Spark (free tier) currently only supports Node.js 8 for cloud Functions, per https://firebase.google.com/pricing.
```
The free (Spark) plan is limited to the Node.js 8 runtime
```

However, it is clear you will no longer provide support (or even allow) for use of Node.js 8 Functions early next year:
![image](https://user-images.githubusercontent.com/2273452/95755972-194a3c80-0c73-11eb-9190-900c7940b71b.png)

What is the plan here for Spark plan users that are getting started with cloud Functions?

**Comment by mbleigh** [comment]
Unfortunately in the future all use of Cloud Functions will require the
Blaze plan. Usage of Cloud Functions will still have a free tier, but
you'll need to enter a payment method to use it.

See this for more information:
https://firebase.google.com/support/faq#expandable-10

**Comment by cookmscott** [comment]
@mbleigh cool, didn't see that FAQ. Fair enough, thanks for the quick response! 

(and also thanks for answering here... if Google index's this it'll help people find the answer)
