### ISSUE TITLE
Errors when trying to deploy cloud functions

### ISSUE THREAD

**Issue by slinkstep** [firebase/firebase-tools#2699]
### [REQUIRED] Environment info.

**firebase-tools:** 8.12.1

**Platform:**  macOS 10.14.6

### [REQUIRED] Test case

1. Run: firebase deploy --only functions:[functionName]

### [REQUIRED] Steps to reproduce

1. Run: firebase deploy --only functions:[functionName]

### [REQUIRED] Expected behavior

Deploy the function to the firebase project

### [REQUIRED] Actual behavior

Since yesterday I have got different errors:

- Error: Server Error. connect ETIMEDOUT 172.217.28.106:443

![11334d72-1891-4a2c-87e4-20f8a943bf5d](https://user-images.githubusercontent.com/43453132/95767325-33d3e400-0c7a-11eb-854c-476fa8262093.jpeg)

- Error: Could not read public directory. Remove links and shortcuts and try again.

When put the debug flag I got this information too:

![ec11b907-c465-4e63-bafb-359663682e0b](https://user-images.githubusercontent.com/43453132/95767186-025b1880-0c7a-11eb-9684-77850411ef05.jpeg)

![f953ea34-3693-4a77-a7a2-570bc46724ad](https://user-images.githubusercontent.com/43453132/95767192-0424dc00-0c7a-11eb-9e1b-1435e51f2aad.jpeg)

I tried to run firebase logout and firebase login again and sometimes the login process gave me errors too:

<img width="511" alt="Screen Shot 2020-10-12 at 10 15 40 AM" src="https://user-images.githubusercontent.com/43453132/95767261-1bfc6000-0c7a-11eb-97f4-f0885360a706.png">

**Comment by samtstern** [comment]
@slinkstep see these similar issues:
https://github.com/firebase/firebase-tools/search?q=ETIMEDOUT&type=issues

Unfortunately there is nothing we can do about `ETIMEDOUT`, it happens when you have a slow or flaky internet connection.  I know it's super frustrating but it's not something we can fix within the CLI.

**Comment by slinkstep** [comment]
It's happening to all team members and we have stable connections

**Comment by samtstern** [comment]
@slinkstep hmmm now that I am looking at your screenshot I see two different errors:

1. `ETIMEDOUT`
2.  `input source must be valid Stream or Buffer instance`

Which one is the one that's happening to your whole team?

**Comment by slinkstep** [comment]
Both of them, as I said, they are random when we try to deploy. Right now we are getting ETIMEDOUT when we use firebase deploy --only functions:XXXX but if we run: gcloud functions deploy XXXXXX it works perfectly

**Comment by samtstern** [comment]
Hmmmm ok the fact that it works with `gcloud` is fishy.  Re-opening.

**Comment by slinkstep** [comment]
Any updates ? I haven't been able to deploy any function yet

**Comment by nikglavin** [comment]
To add to @aravindvnair99 comment I also have started experiencing this recently with no change to the code.

Functions deploys started to  fail intermittently from 03/10/2020.

When deploying I get the same error as above for random functions each deploy. Following the link to the logs the console returns: DENIED: Unable to write blob. This can be resolved by clearing the image for the failed function and redeploying. However it continues to fail on subsequent builds this is happening > 33% of the time.

I am using the Node 12 image it seem to be more reliable with Node 8 however this is now deprecated.

**Comment by aravindvnair99** [comment]
> To add to @aravindvnair99 comment I also have started experiencing this recently with no change to the code.
> 
> Functions deploys started to fail intermittently from 03/10/2020.
> 
> When deploying I get the same error as above for random functions each deploy. Following the link to the logs the console returns: DENIED: Unable to write blob. This can be resolved by clearing the image for the failed function and redeploying. However it continues to fail on subsequent builds this is happening > 33% of the time.
> 
> I am using the Node 12 image it seem to be more reliable with Node 8 however this is now deprecated.

@nikglavin Yes, each time what I am doing now is that I go to the GCP console and then clear the entire bucket. Then it works and fails again sometime down in the future in a few days. It's become a continuous cycle now. I even tried setting life cycle to 1 day and it didn't help.

**Comment by joerozek** [comment]
@aravindvnair99  which bucket are you clearning? the archive bucket?

**Comment by aravindvnair99** [comment]
> @aravindvnair99 which bucket are you clearing? the archive bucket? I'm having he same issue with a handful of my functions now.

@joerozek I was clearing the `artifacts` bucket.

**Comment by hosaka** [comment]
Also experiencing the same issue. Clearing the articacts bucket seems to help but only until the next deploy.

**Comment by aravindvnair99** [comment]
> Also experiencing the same issue. Clearing the articacts bucket seems to help but only until the next deploy.

@hosaka I don't seem to be facing issues anymore. But as mentioned in my previous comments, I was facing the issue while deploying from the local system and CI server. I am currently using Node.js 12. I don't know if that helped. Previously I was on Node.js 10. Which version are you using?

Also, here's a thread I started long ago when this issue first came up: https://github.com/firebase/firebase-functions/issues/795

**Comment by Suryanandx** [comment]
I am using Node.js 12 , I am having issues deploying. same error

**Comment by aravindvnair99** [comment]
@samtstern I guess this issue can be closed as there have been no further reports since. And as for me, things are working fine now.

**Comment by samtstern** [comment]
@aravindvnair99 thanks for following up!

**Comment by nikglavin** [comment]
I ended up resolving this issue by deleting the entire bucket (not just its contents) and then redeploying the functions since then I have not seen the issue again
