### ISSUE TITLE
Unable to Install firebase tools in ubuntu.

### ISSUE THREAD

**Issue by murali0009** [firebase/firebase-tools#2705]
### [REQUIRED] Environment info

Latest

Ubuntu 20.04.1 LTS , 64-bit

### [REQUIRED] Test case

Try to install firebase tools following https://firebase.google.com/docs/cli#install-cli-mac-linux

### [REQUIRED] Steps to reproduce

Try to run curl -sL https://firebase.tools | bash

### [REQUIRED] Expected behavior

Install firebase tools

### [REQUIRED] Actual behavior

-- Checking for existing firebase-tools on PATH...
-- Checking your machine type...
-- Downloading binary from https://firebase.tools/bin/linux/latest
######################################################################## 100.0%-######################################################################## 100.0% ######################################################################## 100.0% Warning: Failed to create the file /usr/local/bin/firebase: No such file or   
Warning: directory
                                                                           0.0%curl: (23) Failed writing body (0 != 16360)

-- Setting permissions on binary...
chmod: cannot operate on dangling symlink '/usr/local/bin/firebase'
bash: line 255: /usr/local/bin/firebase: No such file or directory
Something went wrong, firebase has not been installed.
Please file a bug with your system information on Github.
https://github.com/firebase/firebase-tools/
-- All done!

**Comment by abeisgoat** [comment]
So this looks like you had a broken `firebase` install before perhaps try `rm /usr/local/bin/firebase` and running the curl again?

**Comment by xam-ps** [comment]
Installing it trough npm (`npm install -g firebase-tools`) was working for me today without any problems (ubuntu 20.04), node 14.15.0

**Comment by abeisgoat** [comment]
Haven't heard from original author in 2 weeks, gonna close this.

**Comment by Arconapalus** [comment]
I came across the same issue, unable to install FireBase from both install script and NPM command. However, the remedies that I set were updating npm globally and node.js to the latest version. I uninstall firebase then installed it with the NPM command. Double checked that permissions for Firebase located in dir /usr/local/bin/firebase was set. I then closed out of all terminal or you could use source ~/.bashrc. and then opened the terminal up again and then ran the firebase script again. output 
```-- Checking for existing firebase-tools on PATH...
/usr/local/bin/firebase: line 1: Not: command not found
/usr/local/bin/firebase: line 1: Not: command not found
Your machine has a corrupted firebase-tools binary installed.
If you would like to upgrade your install run: curl -sL firebase.tools | upgrade=true bash
```
then I ran the ```curl -sL firebase.tools | upgrade=true bash```
successfully installed it. I don't know if have npm update or have firebase installed and then restart bash terminal in ubuntu resolved this or setting the permission of bin/firebase helped.

**Comment by tommyyama2020** [comment]
i came across the same and tried a solution above. But the issue still persists. 
Please let me know if anyone using ubuntu has fixed.

npm installation works but hopefully curl installation should work in ubuntu. I do not want to install npm unnecessarily.
Thanks .

**Comment by NullByte08** [comment]
You can install the firebase-tools via npm (Mac):

`sudo npm install -g firebase-tools`

Then in order to use the firebase commands just prefix with sudo everytime:

`sudo firebase --version`
