### ISSUE TITLE
I'm getting this error when try to install firebase-tools

### ISSUE THREAD

**Issue by malikasinger1** [firebase/firebase-tools#271]
# please help
I'm getting this error when try to install firebase-tools: 

```
PS D:\Projects\Uni\firebase-functions-hello-world> npm install -g firebase-tools
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\
\npm-cli.js" "install" "-g" "firebase-tools"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10

npm ERR! shasum check failed for C:\Users\AdMin\AppData\Local\Temp\npm-8448-fdc26aac\registry.npmjs.org
\jju\-\jju-1.3.0.tgz
npm ERR! Expected: dadd9ef01924bc728b03f2f7979bdbd62f7a2aaa
npm ERR! Actual:   2a552ad636b1e23979c677ab9f360cf1ac578f89
npm ERR! From:     https://registry.npmjs.org/jju/-/jju-1.3.0.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Projects\Uni\firebase-functions-hello-world\npm-debug.log
PS D:\Projects\Uni\firebase-functions-hello-world>
```

stackoverflow:  http://stackoverflow.com/questions/42725131/im-getting-this-error-when-try-to-install-firebase-tools

**Comment by mbleigh** [comment]
You've posted this across several issues now, which generates lots of email and generally doesn't get anything done faster. The error you're seeing here is related to NPM, not `firebase-tools` specifically. I'd try running `npm cache clean` and then trying to install again.

If that doesn't work, I'd do some Googling for "npm shasum check failed" and see if anyone else has suggestions. I'm not trying to be unhelpful, but it seems like a problem specific to your machine / NPM / Node.js configuration. I'm not going to be able to be much help on that front.

**Comment by Kikishan07** [comment]
I also get this error, give me any solution 


npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
C:\Users\arudhra\AppData\Roaming\npm
`-- (empty)

npm ERR! Windows_NT 6.1.7600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "firebase-tools"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! path C:\Users\arudhra\AppData\Roaming\npm\node_modules\firebase-tools
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\arudhra\AppData
\Roaming\npm\node_modules\firebase-tools' -> 'C:\Users\arudhra\AppData\Roaming\n
pm\node_modules\.firebase-tools.DELETE'
npm ERR!     at moveAway (C:\Program Files\nodejs\node_modules\npm\lib\install\a
ction\finalize.js:38:5)
npm ERR!     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\instal
l\action\finalize.js:27:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:117:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\arudhra\AppData
\Roaming\npm\node_modules\firebase-tools' -> 'C:\Users\arudhra\AppData\Roaming\n
pm\node_modules\.firebase-tools.DELETE'
npm ERR!     at Error (native)
npm ERR!  Error: EPERM: operation not permitted, rename 'C:\Users\arudhra\AppDat
a\Roaming\npm\node_modules\firebase-tools' -> 'C:\Users\arudhra\AppData\Roaming\
npm\node_modules\.firebase-tools.DELETE'
npm ERR!     at moveAway (C:\Program Files\nodejs\node_modules\npm\lib\install\a
ction\finalize.js:38:5)
npm ERR!     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\instal
l\action\finalize.js:27:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:117:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\arudhra\AppData
\Roaming\npm\node_modules\firebase-tools' -> 'C:\Users\arudhra\AppData\Roaming\n
pm\node_modules\.firebase-tools.DELETE'
npm ERR!     at Error (native)
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\arudhra\npm-debug.log
npm ERR! code 1

**Comment by mbleigh** [comment]
This looks like folder permission problems in your global node_modules
directory. Are you able to install other node modules globally without
issue?

**Comment by kenvantruong** [comment]
Kens-MacBook-Pro:~ username$ npm install -g firebase-tools
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
/Users/username/.npm-packages/bin/firebase -> /Users/username/.npm-packages/lib/node_modules/firebase-tools/bin/firebase
/Users/username/.npm-packages/lib
└── firebase-tools@3.6.1 



I'm also getting the error. Any help? @mbleigh

**Comment by imsarvesh** [comment]
Try using LTS version of NodeJs instead of Current version of NodeJs.
