### ISSUE TITLE
Prompt in `hosting:channel:create` is not working

### ISSUE THREAD

**Issue by sarajmunjal** [firebase/firebase-tools#2719]
### [REQUIRED] Environment info

**firebase-tools:**8.12.1

**Platform:**macOS

### [REQUIRED] Test case

Create a hosting channel using `hosting:channel:create` and don't specify the new channel's name in the command.

### [REQUIRED] Steps to reproduce

```
firebase hosting:channel:create 
? Please provide a URL-friendly name for the channel: *someName*
>> someName (with red arrows)
```
When the channel create command doesn't find a specified name, it prompts for one. This prompt seems to be blocking all inputs. 

If the same input is specified in the initial command, `firebase hosting:channel:create someName`, then it works.
### [REQUIRED] Expected behavior

The prompt should not block.

### [REQUIRED] Actual behavior

The prompt blocks.

**Comment by bkendall** [comment]
Fixed in `8.13.0`
