### ISSUE TITLE
Feature Request: add default .gitignore to ignore node_modules when running `firebase init functions`

### ISSUE THREAD

**Issue by quanvuong** [firebase/firebase-tools#272]

**Comment by yuchenshi** [comment]
The gitignore file should also contain a few common unwanted files such as `npm-debug.log`. When initializing functions with TypeScript, it should also ignore generated `.js` files from compiling.

https://github.com/firebase/functions-samples/blob/master/typescript-getting-started/.gitignore looks like a good start, but we probably need to take out the TypeScript parts (e.g. `functions/**/*.js`) if JavaScript is chosen.

We can either emit a `.gitignore` file when initializing the project, or `functions/.gitignore` when running `firebase init functions`.

**Comment by laurenzlong** [comment]
This is a great idea! You're welcome to make a PR. The logic for the functions portion of "firebase init" is in https://github.com/firebase/firebase-tools/tree/master/lib/init/features/functions

**Comment by yuchenshi** [comment]
@laurenzlong Thanks for the pointer. I'll look into it soon and try submitting a PR.

**Comment by nicolasgarnier** [comment]
Hey @laurenzlong it seems this is not working anymore. I don't see a `.gitignore` file generated by `firebase init` anymore. Do you know what happened? We're getting some reports of people complaining their IDE crashes because too many files are being added to git.

**Comment by nicolasgarnier** [comment]
Oups, never mind. I checked again and I do have the .gitignore (probably it was a hidden file last time I checked).
