### ISSUE TITLE
hosting:channel:deploy 502 error when channel id ends in certain characters

### ISSUE THREAD

**Issue by jhuleatt** [firebase/firebase-tools#2724]
If a channel id ends in certain characters (I've been able to repro with `-` and `_`), the CLI errors out with a 502. 

### [REQUIRED] Environment info

**firebase-tools:** 8.12.1

**Platform:** macOS

### [REQUIRED] Test case

```shell
firebase hosting:channel:deploy jeff-test-
```

### [REQUIRED] Steps to reproduce

Have a Firebase directory with hosting set up.

✅  This works fine:

```shell
firebase hosting:channel:deploy jeff-test
```

✅  This has the *expected* error:

```shell
firebase hosting:channel:deploy jeff-test@

Error: HTTP Error: 400, Channel IDs can only include letters, numbers, underscores, hyphens, and periods.
```

🛑  This errors with a **502**:

```shell
firebase hosting:channel:deploy jeff-test-

Error: HTTP Error: 502, Unknown Error
```
### [REQUIRED] Expected behavior

The CLI should either:

- deploy correctly because this doesn't violate the documented acceptable channel id characters ([docs](https://firebase.google.com/docs/hosting/test-preview-deploy#preview-channels:~:text=Replace%20CHANNEL_ID%20with%20a%20string%20with%20no%20spaces))
- error out with a detailed message explaining why my channel id is bad.

### [REQUIRED] Actual behavior

The CLI errors out with `Error: HTTP Error: 502, Unknown Error`

[firebase-debug.log](https://github.com/firebase/firebase-tools/files/5411094/firebase-debug.log)

**Comment by kmcnellis** [comment]
Theres a bug in the backend code that generates/validates hostnames (the `<site-channel-randomNumbers>.web.app`) that is causing channels ending with  `-` and `_` to fail.   Working on fixing it.

**Comment by jhuleatt** [comment]
I've tried running the commands again, and it looks like the backend fix has been rolled out.
