### ISSUE TITLE
Cannot deploy: Must supply either "site" or "target" in each "hosting" config.

### ISSUE THREAD

**Issue by claust** [firebase/firebase-tools#2726]
### [REQUIRED] Environment info

**firebase-tools:**
8.13.0

**Platform:**
Windows, Ubuntu 18.04.5
### [REQUIRED] Test case

After upgrading to firebase-tools 8.13.0, the `firebase deploy` command fails with the following error message:

`Error: Must supply either "site" or "target" in each "hosting" config.`

NB: Deploying with the `firebase deploy --only hosting` and `firebase deploy --only functions` works without errors.

There are no targets defined in neither `firebase.json` nor in `.firebaserc`.

```
{
  "functions": {
    "predeploy": [
      "npm --prefix \"$RESOURCE_DIR\" run lint",
      "npm --prefix \"$RESOURCE_DIR\" run build"
    ],
    "source": "functions"
  },
  "database": {
    "rules": "database.rules.json"
  },
  "firestore": {
    "rules": "firestore.rules",
    "indexes": "firestore.indexes.json"
  },
  "hosting": {
    "public": "site/dist",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "rewrites": [
      {
        "source": "**",
        "destination": "/index.html"
      }
    ]
  },
  "emulators": {
    "functions": {
      "port": 5001
    },
    "ui": {
      "enabled": true
    }
  }
}

```

### [REQUIRED] Steps to reproduce

I have tried to reproduce the issue in a new firebase project, but without luck.

### [REQUIRED] Expected behavior

The `firebase deploy` should complete without errors.

### [REQUIRED] Actual behavior

The `firebase deploy` fails to complete. The error is:

```
...
> tsc

+  functions: Finished running predeploy script.
i  database: checking rules syntax...
+  database: rules syntax for database testlagkagehuset-b6882 is valid
i  firestore: reading indexes from firestore.indexes.json...
i  cloud.firestore: checking firestore.rules for compilation errors...
+  cloud.firestore: rules file firestore.rules compiled successfully
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
+  functions: required API cloudbuild.googleapis.com is enabled
+  functions: required API cloudfunctions.googleapis.com is enabled

Error: Must supply either "site" or "target" in each "hosting" config.
```

### Workaround

Downgrade to version 8.12.1:
`npm install -g firebase-tools@8.12.1`

**Comment by bkendall** [comment]
I figured out that it's the `database` configuration that breaks this. The success of deploy depends on if `database` is in `firebase.json`. We're looking into this.

**Comment by bkendall** [comment]
This will be fixed in `8.13.1` soon

**Comment by LeonardoRick** [comment]
updated to `8.13.1` and already working. Thanks a lot

**Comment by gmanojisaac** [comment]
8.14.1 i am facing same issue
