### ISSUE TITLE
firebase init function gives Error: An unexpected error has occurred.

### ISSUE THREAD

**Issue by hmazter** [firebase/firebase-tools#273]
When running `firebase init function` I can choose a project and then the script crashes.

I have tried on Node 6.10, 7.5, 7.7 with firebase-tools global install and local install.
There is no difference if I choose a default project or not.

Attaching the error log:
[firebase-debug.txt](https://github.com/firebase/firebase-tools/files/835600/firebase-debug.txt)

**Comment by mbleigh** [comment]
Are you missing an s?

firebase init functions

**Comment by hmazter** [comment]
@mbleigh Thanks for answering.
Such a dumb mistake by me :smile: 

I was fooled by this part in the log: 
`=== Function Setup`
Made it seem like it was starting the function init

**Comment by azat99** [comment]
write firebase init functions instead of firebase init function

**Comment by hmazter** [comment]
@azat99 Thanks for the response.
This issue was already closed with that solution 6 month ago =)
