### ISSUE TITLE
Listing users is not implemented in the Auth Emulator

### ISSUE THREAD

**Issue by bartekpacia** [firebase/firebase-tools#2751]
I just found a feature which isn't implemented and I really need this. I thought I'll submit an issue for this.

**firebase-tools:**
v8.14.1

**Platform:**

MacOS 10.15.7

### [REQUIRED] Test case

```
import * as admin from "firebase-admin"
admin.initializeApp()s
admin.auth().listUsers(10)
```

### [REQUIRED] Steps to reproduce

Try to call `admin.auth().listUsers(10)` 

### [REQUIRED] Expected behavior

I'd like to be able to query all users at once (or rather, in batches of 1000) from Firebase Auth.

### [REQUIRED] Actual behavior

It crashes with

```
identitytoolkit.projects.accounts.batchGet is not implemented in the Auth Emulator:
```

```
An internal error has occurred. Raw server response: "{"error":{"code":501,"message":"identitytoolkit.projects.accounts.batchGet is not implemented in the Auth Emulator.","errors":[{"message":"identitytoolkit.projects.accounts.batchGet is not implemented in the Auth Emulator.","reason":"unimplemented"}],"status":"NOT_IMPLEMENTED"}}"
```

**Comment by samtstern** [comment]
@bartekpacia thanks for reporting this.  As you noticed the Auth Emulator does not yet implement 100% of the Auth endpoints, but we're working on it!

@yuchenshi how do you want to track these?  Individually or a central list?

**Comment by yuchenshi** [comment]
This is now internally tracked as b/171888483. @samtstern feel create to create internal bugs like these for feature requests individually.

**Comment by rromanchuk** [comment]
Does the authentication simulator support this rest API https://firebase.google.com/docs/reference/rest/auth   I'm not talking about the emulator management endpoints, but the actual API. 

My backend uses this exclusively, i mint JWTs for client, but the backend relies heavily on fetching/updating and managing the user profile, and firebase uid acts as an important fk on my own user records. This will implode quickly if these rest calls are crossing www to a real firebase staging/development via identitytoolkit.googleapis.com

**Comment by samtstern** [comment]
@rromanchuk yes the emulator works over REST APIs and tries to implement production endpoints exactly, just at a different host.

They're exposed like this:
```
http://localhost:9099/identitytoolkit.googleapis.com/{version}/projects/{projectId}/{api}
```

**Comment by rromanchuk** [comment]
@samtstern perfect! thank you
