### ISSUE TITLE
Killing Emulator doesn't kill child processes

### ISSUE THREAD

**Issue by edgework** [firebase/firebase-tools#2756]
8.14.1
macOS

killing the emulator with  ctrl-c  more often than not does not kill all child processes leaving the ports unavailable for restart. This happened occasionally in previous versions but since upgrading to 8.14.1 it happens 9/10 times.

**Comment by samtstern** [comment]
@edgework please use the issue template when filing issues.  Can you show the logs from one of those runs where the emulator processes are not killed?  Normally in that case we offer a `kill` command at the end of the execution that you can use to kill the zombie processes.

Note that this type of thing happen when you press ctrl-c more than once.  If you press it exactly once we do a clean shutdown and kill all processes.
