### ISSUE TITLE
Can't change the region where the functions will be deployed

### ISSUE THREAD

**Issue by johnnyasantoss** [firebase/firebase-tools#2757]
### [REQUIRED] Environment info

**firebase-tools:** *8.14.1*

**Platform:** *Linux/CI*

### [REQUIRED] Test case

1. Create a simple function (eg. Hello World fn)
2. Try to deploy overriding the env var `FIREBASE_FUNCTIONS_UPLOAD_REGION` with a valid region (got this from [this file](https://github.com/firebase/firebase-tools/blob/6943586ee0c865e95407b618a32361895adae9a8/src/api.js#L134))
3. Check the console to see that functions are being deployed to `us-central1`

### [REQUIRED] Steps to reproduce

Same as in test case

### [REQUIRED] Expected behavior

There should be a flag/env var to override the target region

### [REQUIRED] Actual behavior

All functions are deployed to `us-central1`

**Comment by samtstern** [comment]
@johnnyasantoss the environment variables in that file are mostly undocumented and for testing purposes.  They're not a reliable part of the API surface. 

Is there some reason why you need `FIREBASE_FUNCTIONS_UPLOAD_REGION` to work instead of using the normal method?  Normally you specify the `region` as part of the builder:

```
exports.webhookAsia = functions
    .region('asia-northeast1')
    .https.onRequest((req, res) => {
            res.send("Hello");
    });
```

If you really want to do this via environment variable, do something like `.region(process.env.FUNCTIONS_REGION)` and you can control that yourself.

**Comment by johnnyasantoss** [comment]
@samtstern My idea was to use **a env var** to change the default region for all those fns that didn't have a particular region set. Looking at the source code of the `funcitons/deploy.js` file that was the env var I thought that would be the one used everywhere. But there are some places that have it hardcoded to `us-central1`
e.g. https://github.com/firebase/firebase-tools/blob/e92ba5a0a672317c1db682cac1cffb684e4a5c04/src/functionsDeployHelper.js#L102
> If you really want to do this via environment variable, do something like .region(process.env.FUNCTIONS_REGION) and you can control that yourself.

I guess this would work, but still isn't like setting a `--region` parameter like in `gcloud`, this way its possible to change it at deploy-time and there's no need to fiddle with the FNs code to do so. It would be great to have such a feature. :smile:

**Comment by samtstern** [comment]
@johnnyasantoss I think my solution would still allow that:

```
FUNCTIONS_REGION="foo-bar1" firebase deploy --only function
```

Also it's worth noting you can use `gcloud` to deploy Firebase functions if you prefer that experience, it's all Google Cloud Functions in the end.

I'm going to close this issue as we're not planning on adding a `--region` flag and I think the workaround I provided is pretty decent. Hope it works for you!

**Comment by johnnyasantoss** [comment]
Yeah it worked perfectly, just had to do some refactoring.
Thank you 😁
