### ISSUE TITLE
Real time database fails when using Auth emulator

### ISSUE THREAD

**Issue by tomhicks** [firebase/firebase-tools#2758]
### [REQUIRED] Environment info

**firebase-tools:** 8.14.1

**Platform:** macOS

### [REQUIRED] Test case

In a web app:

```
  firebase.initializeApp({
    apiKey: "redacted",
    authDomain: "redacted",
    databaseURL: "redacted",
    projectId: "redacted",
    storageBucket: "redacted",
    messagingSenderId: "redacted",
    appId: "redacted",
    measurementId: "redacted",
  })

  authInstance = firebase.auth()
  firestoreInstance = firebase.firestore()
  rtbdInstance = firebase.database()


  authInstance.useEmulator("http://localhost:9099/")
  rtbdInstance.useEmulator("localhost", 9000)
  firestoreInstance.useEmulator("localhost", 8080)

  rtbdInstance.ref().once("value", r => console.log(r.val())) // fails and logs a warning
```

### [REQUIRED] Steps to reproduce

```
rtbdInstance.ref().once("value", r => console.log(r.val())) // fails and logs a warning
```

If I don't use the auth emulator it works fine, fetching my local database

### [REQUIRED] Expected behavior

I should get data

### [REQUIRED] Actual behavior

No data is returned, and a warning is logged into the dev tools console:

```
@firebase/database: FIREBASE WARNING: Provided authentication credentials for the app named "[DEFAULT]" are invalid. This usually indicates your app was not initialized correctly. Make sure the "apiKey" and "databaseURL" properties provided to initializeApp() match the values provided for your app at https://console.firebase.google.com/. 
```

---

My hunch is that the problem could be:

* the database emulator doesn't know that auth is being emulated and verifies the token against prod
* I've got an out of date database emulator? I have `i  database: downloading firebase-database-emulator-v4.6.0.jar`
* there is some specific order the various `useEmulator` calls have to be made in.

**Comment by samtstern** [comment]
@tomhicks thanks for reporting!  On the surface it looks like you're doing everything correctly so one of us will have to try and reproduce this and dig in.

**Comment by tomhicks** [comment]
Some more, possibly related context on this.

The following all relates to using the RTDB in `firebase-admin` although it seems to defer to `@firebase/database` which I *think* is used for the database web client?

Last night I spent a *long* time working through an issue where my integration tests weren't able to make a query to the RTDB. Ultimately I found a 403 was being returned from the "handshake" when trying to establish the websocket between the admin sdk and the RTDB. The behaviour on the outside was simply the request hanging (not promise rejecting) and my tests were failing due to a timeout (test runner gives up after waiting 5 seconds).

After a lot of digging and poking logs directly into the firebase dependency, it turned out that setting my `databaseURL` to `http://localhost:9000` was the issue. I needed to put `http://localhost:9000?ns=fake-project-id` (fake-project-id could be whatever) so that ultimately the websocket would be created with a URL ending `?v=5&ns=fake-project-id`.

Before, it was trying to connect to a URL ending `?v=5&ns=` and failing with the 403.

I don't think that is described in the documentation. Maybe it's obvious to other people (as that's the URL that shows in the database emulator tree view of the database) but it wasn't obvious to me at all.

This made me think these issues are related in some way, as they're both something to do with database and auth and how they interact.

It's entirely possible this is all user error, but at least making the docs clearer might help?

**Comment by tomhicks** [comment]
I just found this in the docs (regarding my most recent comment):

It mentions something about this URL:
> `http://localhost:9000/path/to/my/data.json?ns=<database_name>`

But then the environment variable docs say this:
> `export FIREBASE_DATABASE_EMULATOR_HOST="localhost:9000"`

and to add more confusion, if you use a URL that includes a path, it complains that you should just use the root!

**Comment by ShadowfeindX** [comment]
I've had the same issue for the past few days and my `databaseUrl` was already set to include the `projectId`. Are there any other changes you made perhaps that might have done something?

**Comment by samtstern** [comment]
@tomhicks thank you for documenting your confusion and your solution!  I agree this is something we need to document better.

Thanks to some recent changes in our SDKs (the releases last week) I would no longer recommend connecting to the emulator through the `databaseUrl` parameter of `initializeApp`.  Instead:

### 1 - Admin SDKs

For Admin SDKs the easiest thing to do is set the `FIREBASE_ADATABASE_EMULATOR_HOST` environment variable to `localhost:9000` or similar. The Admin SDK will internally add the scheme (`http://`) and the `?ns=` parameter as needed.

### 2 - Web SDK

For the Web SDK use the `useEmulator()` method to switch your connection to the emulator *after* you've called `initializeApp()`.  So `firebase.database().useEmulator('localhost', 9000)`. 

In both of these case you should provide _production_ arguments to `initializeApp()` and then use the techniques above to make your instance point at the emulator.

**Comment by samtstern** [comment]
@markarndt to take a look and possibly update the docs based on this feedback.

**Comment by tomhicks** [comment]
1 - Admin SDKs

I'm pretty sure I tried using the environment variable with the same result. I'll give it another go and confirm.

2 - Web SDK

I am calling `useEmulator` after `initializeApp`, as shown in the initial report.

---

I think there's something else going on here!

**Comment by samtstern** [comment]
@tomhicks yeah you're right there probably is something else going on!  Sorry I didn't mean to imply there was no validity to your report.

Are you using the Admin and Web SDKs in the same app?  The Admin SDK does delegate to the Web SDK implementation and sometimes if they're both present in the same context they can interfere with each other (although I did think we had fixed this).

**Comment by tomhicks** [comment]
I have a folder structure like:

```
app/
  node_modules/
  package.json
functions/
  node_modules/
  package.json
```

Not sure if that counts as “the same app” - I guess it shouldn’t?

**Comment by samtstern** [comment]
That looks like a normal structure, shouldn't be causing the problem.

**Comment by malcolmdeck** [comment]
Hey there, I've filed b/172261789 to track this internally :)

**Comment by samhorlbeck** [comment]
Jumping in here real quick---going back to the original issue (on web instead of in the admin SDK), would you mind posting the websocket URL being made in the browser? I'm unable to reproduce this on my end using your snippet and another project.

**Comment by tomhicks** [comment]
> Jumping in here real quick---going back to the original issue (on web instead of in the admin SDK), would you mind posting the websocket URL being made in the browser? I'm unable to reproduce this on my end using your snippet and another project.

Hi @samhorlbeck 

I have the entire contents of the @firebase/database `enableLogging(true)` output from my app. Only trouble is, I'm unsure if any of the keys and stuff it logs could be sensitive.

Is there a way I can give this to you securely?

**Comment by tomhicks** [comment]
Actually, here's what looks like one cycle of connection attempts:
```
[2020-11-02T23:21:23.943Z]  @firebase/database: p:0: Browser went online. 
[2020-11-02T23:21:23.948Z]  @firebase/database: p:0: Listen called for /galaxies/LPp8eCR63uCmmkNrueX6/users/gLZQS7iyD7kJOUb8BAqqzdmioN3K/position default 
[2020-11-02T23:21:23.972Z]  @firebase/database: p:0: Auth token refreshed 
[2020-11-02T23:21:23.976Z]  @firebase/database: p:0: Making a connection attempt 
[2020-11-02T23:21:23.977Z]  @firebase/database: getToken() completed. Creating connection. 
[2020-11-02T23:21:23.977Z]  @firebase/database: c:0:0: Connection created 
[2020-11-02T23:21:23.979Z]  @firebase/database: c:0:0:0 Websocket connecting to ws://localhost:9000/.ws?v=5&ns=orbital-chat 
[2020-11-02T23:21:23.986Z]  @firebase/database: c:0:0:0 Websocket connected. 
[2020-11-02T23:21:23.989Z]  @firebase/database: c:0:0: Realtime connection established. 
[2020-11-02T23:21:23.990Z]  @firebase/database: p:0: connection ready 
[2020-11-02T23:21:23.991Z]  @firebase/database: p:0: reportStats {"c":{"sdk.js.8-0-0":1}} 
[2020-11-02T23:21:23.991Z]  @firebase/database: p:0: {"r":1,"a":"s","b":{"c":{"sdk.js.8-0-0":1}}} 
[2020-11-02T23:21:23.992Z]  @firebase/database: p:0: {"r":2,"a":"auth","b":{"cred":"eyJ....REDACTED....0sifQ."}} 
[2020-11-02T23:21:23.993Z]  @firebase/database: p:0: Listen on /galaxies/LPp8eCR63uCmmkNrueX6/users/gLZQS7iyD7kJOUb8BAqqzdmioN3K/position for default 
[2020-11-02T23:21:23.993Z]  @firebase/database: p:0: {"r":3,"a":"q","b":{"p":"/galaxies/LPp8eCR63uCmmkNrueX6/users/gLZQS7iyD7kJOUb8BAqqzdmioN3K/position","h":""}} 
[2020-11-02T23:21:23.998Z]  @firebase/database: p:0: from server: {"r":1,"b":{"s":"ok","d":""}} 
[2020-11-02T23:21:23.998Z]  @firebase/database: c:0:0: Primary connection is healthy. 
[2020-11-02T23:21:23.999Z]  @firebase/database: p:0: from server: {"r":2,"b":{"s":"invalid_token","d":"missing 'kid' in header"}} 
[2020-11-02T23:21:23.999Z]  @firebase/database: Auth token revoked: invalid_token/missing 'kid' in header 
[2020-11-02T23:21:23.999Z]  @firebase/database: c:0:0: Closing realtime connection. 
[2020-11-02T23:21:24.000Z]  @firebase/database: c:0:0: Shutting down all connections 
[2020-11-02T23:21:24.000Z]  @firebase/database: c:0:0:0 WebSocket is being closed 
[2020-11-02T23:21:24.000Z]  @firebase/database: p:0: data client disconnected 
[2020-11-02T23:21:24.000Z]  @firebase/database: p:0: Trying to reconnect in 388.6984251879077ms 
[2020-11-02T23:21:24.001Z]  @firebase/database: 0: onDisconnectEvents 
[2020-11-02T23:21:24.002Z]  @firebase/database: c:0:0:0 Websocket connection was disconnected. 
```

This line seems useful! `Auth token revoked: invalid_token/missing 'kid' in header`

**Comment by tomhicks** [comment]
Apologies for dragging the admin sdk into this... maybe it's not pertinent after all.

**Comment by gmeans** [comment]
I came across this issue because I am running into the same thing. Reviewing the network tab in my app I see a pattern like this.

![image](https://user-images.githubusercontent.com/277741/97990925-a71ad280-1dae-11eb-8943-246e591de4a3.png)

That canceled request appears to be pointing at this LOC:

![image](https://user-images.githubusercontent.com/277741/97991001-c87bbe80-1dae-11eb-8f9c-20023806a32c.png)

It seems like, for whatever reason, it's unable to load that script it's appending to the page. Maybe it actually shouldn't be appending the script and that's causing the error.

Hope this helps. Happy to provide more info if needed.

**Comment by samhorlbeck** [comment]
@tomhicks that line is indeed very useful, thanks!
```
Auth token revoked: invalid_token/missing 'kid' in header
```

That was the missing piece, we're working on a fix. I will get back to you when it's done!
Thanks again!

**Comment by yuchenshi** [comment]
@samtstern would you mind opening up a new issue regarding docs (and also internally)? Tracking two things at once is hard

**Comment by mdo5004** [comment]
Hello!

So glad I found this thread -- I am having the exact same issue, except in my log I see

```
@firebase/database: Auth token revoked: invalid_token/Unsupported jwt algorithm: none 
```
