### ISSUE TITLE
firebase init hosting:github doesn't work for repos in orgs

### ISSUE THREAD

**Issue by jhuleatt** [firebase/firebase-tools#2763]
### [REQUIRED] Environment info

**firebase-tools: `8.14.1`**

**Platform: `macOS`**

### [REQUIRED] Test case

Try to use `firebase init hosting:github` with a repository in a GitHub organization.

### [REQUIRED] Steps to reproduce

1. Run `firebase init hosting:github`
1. When prompted for a GitHub repo, enter a repo that is part of a GitHub organization

### [REQUIRED] Expected behavior

Full configuration of [action-hosting-deploy](https://github.com/marketplace/actions/deploy-to-firebase-hosting)

### [REQUIRED] Actual behavior

Authenticates with GitHub successfully, but after entering the repo name, errors out with `FirebaseError: HTTP Error: 404, Not Found`

Originally reported by @JohnFitz in https://github.com/FirebaseExtended/action-hosting-deploy/issues/40. There's some more analysis in that issue. Looks like we may have to try to [get an organization's public key](https://docs.github.com/en/free-pro-team@latest/rest/reference/actions#get-an-organization-public-key) if the repo public key check fails?

**Comment by jhuleatt** [comment]
James, do you have time to look into this next week?

**Comment by jamesdaniels** [comment]
Yeah I can take a look.

**Comment by jhuleatt** [comment]
Seems like there is a workaround: https://github.com/FirebaseExtended/action-hosting-deploy/issues/40#issuecomment-723476614

> ALL you have to do is PRE grant Firebase CLI 3rd party github app in https://github.com/settings/applications and THEN do firebase init hosting:github. and enter it as organization/repo-name

**Comment by jhuleatt** [comment]
Maybe we just add a special error message if the github oauth step doesn't work? Something like:

```
Error: Unable to Oauth with GitHub. 

If your repository is part of an organization, visit https://github.com/settings/connections/applications/89cf50f02ac6aaed3484 to manually enable the Firebase CLI.

You can remove this access when this command has finished running successfully.
```

**Comment by phareim** [comment]
Seconding @jhuleatt's sugestion. 👍  (And thanks for thew help!)

**Comment by trullock** [comment]
Here with the same issue. Can confirm the workaround still works

**Comment by agtokty** [comment]
Hi all, 
Instead of granting organization access to [Firebase CLI](https://github.com/settings/connections/applications/89cf50f02ac6aaed3484) is it possible to create a service account to set the action secret manually?

**Comment by tommylenz** [comment]
Experiencing the same issue as well. Workaround doesn't seem to work for me, though. I have granted Firebase CLI 3rd party access but it still doesn't work.
+1 for a better error message, which is always helpful.
+1 for an explanation on how to set this up manually, as @agtokty requested - I think it's described pretty rough [in the docs](https://firebase.google.com/docs/hosting/github-integration?hl=en#set-up).

**Comment by tommylenz** [comment]
Maybe reference [this tutorial](https://github.com/FirebaseExtended/action-hosting-deploy/blob/main/docs/service-account.md)?

**Comment by deeprobin** [comment]
can confirm.

**Comment by joehan** [comment]
Closing this for now - please use the workaround in https://github.com/firebase/firebase-tools/issues/2763#issuecomment-735924088 if you are running into this issues.
