### ISSUE TITLE
8.14.1 Deploy existing function revert back memory allocated and timeout settings to default values

### ISSUE THREAD

**Issue by Trinhlvtq** [firebase/firebase-tools#2766]
I found the same issue  (https://github.com/firebase/firebase-tools/issues/545) from 3 years ago, but the ticket is close so I post a new issue

### [REQUIRED] Environment info

**firebase-tools:** 8.14.1
**firebase-functions:** 3.11.0
**firebase-admin:** 3.9.1
**Platform:** Linux

### [REQUIRED] Test case

```
const runtimeOpts = {
  timeoutSeconds: 60,
  memory: '1GB',
}
exports.onTestUpdate = functions.runWith(runtimeOpts).firestore.document(TEST_COLLECTION)
  .onUpdate(async (change, context) => {
    // do something
})
```

### [REQUIRED] Steps to reproduce

- Function `onTestUpdate` exist with memory 1GB
- Run command from local `firebase deploy --only functions:onTestUpdate`

### [REQUIRED] Expected behavior

After function ` onTestUpdate` successfully deployed, memory should be still 1GB

### [REQUIRED] Actual behavior

Although function ` onTestUpdate` successfully deployed, memory is reverted back 256MB
I had to go to https://console.cloud.google.com/functions/list?project=test to deploy the `onTestUpdate` again on the console (click Edit and select 1GB memory in the Memory allocated section) -> the new `onTestFunction` memory becomes 1GB.
If I do the deploy function locally again, the memory of the function reverts back 256MB again

Probably only occurs when deploy Cloud Firestore triggers
As for the Cloud HTTPs, memory is not reverts

**Comment by samtstern** [comment]
@Trinhlvtq does this happen if you do `firebase deploy --only functions` or just `firebase deploy`?  I am wondering if maybe this is a bug with our handling of `--only functions:onTestUpdate` for single-function deploys.

**Comment by Trinhlvtq** [comment]
@samtstern Thanks for reply!
I have this error when do `firebase deploy --only functions` and `firebase deploy`

**Comment by samtstern** [comment]
@Trinhlvtq I am not able to reproduce this.  I started fresh with `firebase init functions` and then added only these lines to `functions/index.js`:

```js
const functions = require('firebase-functions');

const runtimeOpts = {
  timeoutSeconds: 60,
  memory: '1GB',
}
exports.onTestUpdate = functions.runWith(runtimeOpts).firestore.document('test-collection/{doc}')
  .onUpdate(async (change, context) => {
    console.log("onUpdate");
  });
```

After running `firebase deploy --only functions` here's what I see in the Google Cloud console:
![Screen Shot 2020-11-12 at 11 31 03 AM](https://user-images.githubusercontent.com/8466666/98934848-ab32a880-24b0-11eb-88ef-1b2db5d759a3.png)

I am using `firebase-functions: "^3.11.0"` and `firebase-tools` version `8.15.1`.

At this point I am pretty confident that there's not an issue in the Firebase CLI and that there's something funky going on with your code.  Maybe you're somehow deploying an old source code directory?

If you are able to reproduce this via the same steps I used, please just let me know and I will re-open the issue.
