### ISSUE TITLE
Allow to import data in the emulator while it's running

### ISSUE THREAD

**Issue by IchordeDionysos** [firebase/firebase-tools#2768]
There is currently the option to export from the running emulator suite using the command:

```ts
firebase emulators:export ./dir
```

Importing is only possible when starting the emulator via a command option:

```ts
firebase emulators:start --import=./dir
```

## Use case:
Preparing Firestore documents for test cases is hard and needs a lot of boilerplate in the test case. Also often the same data is needed for multiple platforms (iOS, Android, Web).

So consider 
1. you start a clean emulator run without any imported data. 
2. Go in the emulator UI and create your documents for ONE test case.
3. Then click an export button in the UI, specify the export path, and the data for the test case gets saved.
4. You then will see a code 2-3 line code snippet (see below) with the path to the export automatically filled out.

The only thing you now have to do is to paste the code into your test case to set up the local Firestore emulator for your test case.

The code snippet would look like this:

```ts
const test = require('firebase-functions-test')();
await test.firestore.importFirestoreData('./dir/test_1');
```

maybe there is also a function like:

```ts
await test.firestore.replaceFirestoreData('./dir/test_1');
```

which would basically be:

```ts
await tester.firestore.clearFirestoreData();
await test.firestore.importFirestoreData('./dir/test_1');
```

A CLI command could look like this:

```ts
firebase emulators:import ./dir
```

## Sample test case

Function to test:
```ts
import {firestore} from 'firebase-admin';

async function getUppercasedName(ref) {
  const snap = await ref.get();
  return snap.data().name.toUppercase();
}
```

Test:
```ts
import {firestore} from 'firebase-admin';
const test = require('firebase-functions-test')();

it('firestore uppercased name test ', async () => {
  await test.firestore.replaceFirestoreData('./dir/test_uppercased_name');
  
  const result = await getUppercasedName(firestore().doc('posts/post1'));

  expect(result).toBe('UPPERCASED NAME');
});
```

**Comment by samtstern** [comment]
@IchordeDionysos thank you for the very detailed feature request!  I agree, this would be a great feature.  It's already been requested before here (https://github.com/firebase/firebase-tools/issues/2297) so I'm going to close this as a duplicate and we can continue discussing it over there.

Right now the main barrier to achieving this is the Firestore emulator, which currently only supports import at startup time.  I'll ask the team and see how hard it would be to allow import at runtime.
