### ISSUE TITLE
Auth Emulator and createSessionCookie /validDuration should be string

### ISSUE THREAD

**Issue by royletron** [firebase/firebase-tools#2770]
### [REQUIRED] Environment info

**firebase-tools:8.14.1**

**Platform:macOS**

### [REQUIRED] Test case

```js
const expiresIn = 60 * 60 * 24 * 5 * 1000;
const idToken = '<TOKEN FOUND USING auth().currentUser.getIdToken() ON CLIENT>'
await auth().createSessionCookie(idToken, {
  expiresIn
});
```

### [REQUIRED] Steps to reproduce

This is using `firebase-admin` on an `express` backed server, with a front end using `firebase` and `firebase/auth`. These are all connected to the firebase emulator running both firestore and the new auth. You'll need to get an ID token for a user (not sure if it has to be valid or not), and then pass this to the `createSessionCookie` example above. It should fail with the error `Invalid JSON payload received. /validDuration should be string`. This doesn't happen if I connect to a live Firebase project, only when using the emulator.

### [REQUIRED] Expected behavior

That we receive a cookie that we can send back to the client.

### [REQUIRED] Actual behavior

```
{ Error: An internal error has occurred. Raw server response: "{"error":{"code":400,"message":"Invalid JSON payload received. /validDuration should be string","errors":[{"message":"Invalid JSON payload received. /validDuration should be string","reason":"invalid","domain":"global"}],"status":"INVALID_ARGUMENT"}}"
     at FirebaseAuthError.FirebaseError [as constructor] (/Users/redacted-project-path/node_modules/firebase-admin/lib/utils/error.js:43:28)
     at FirebaseAuthError.PrefixedFirebaseError [as constructor] (/Users/redacted-project-path/node_modules/firebase-admin/lib/utils/error.js:89:28)
     at new FirebaseAuthError (/Users/redacted-project-path/node_modules/firebase-admin/lib/utils/error.js:148:16)
     at Function.FirebaseAuthError.fromServerError (/Users/redacted-project-path/node_modules/firebase-admin/lib/utils/error.js:187:16)
     at /Users/redacted-project-path/node_modules/firebase-admin/lib/auth/auth-api-request.js:1510:49
     at process._tickCallback (internal/process/next_tick.js:68:7)
   errorInfo:
    { code: 'auth/internal-error',
      message:
       'An internal error has occurred. Raw server response: "{"error":{"code":400,"message":"Invalid JSON payload received. /validDuration should be string","errors":[{"message":"Invalid JSON payload received. /validDuration should be string","reason":"invalid","domain":"global"}],"status":"INVALID_ARGUMENT"}}"' },
   codePrefix: 'auth' }
```

**Comment by samtstern** [comment]
@royletron where is your express server running?  Right now the Admin SDK only accepts emulated ID Tokens **when running inside of the Cloud Functions emulator**.  This is a decision we made for security reasons, although we are open to reconsidering this based on developer feedback.

**Comment by royletron** [comment]
@samtstern express is just running locally not inside the functions emulator. In prod we run a server on CloudRun so this is more related to our use case

**Comment by samtstern** [comment]
@royletron ok thanks for clarifying.  Right now there's not much you can do about this ... we'd like to expand the situations where we can support verifying emulated tokens but we're still debating the right way to do that.

**Comment by samtstern** [comment]
@royletron this feature request is being tracked over here: https://github.com/firebase/firebase-tools/issues/2764

I'm going to close this one so we can focus the discussion in one thread.

**Comment by andymatuschak** [comment]
@samtstern I think this is a real issue, actually! I'm encountering it even though I'm executing `createSessionCookie` inside the function emulator. So I dug in, and I believe the validation schema is wrong. The [auth emulator validation schema specifies validationDuration as a string](https://github.com/firebase/firebase-tools/blob/41885e0bd3e27da68bb02816fa257fce8ea86330/src/emulator/auth/schema.ts#L154), but the admin client (constructs it as a number)[https://github.com/firebase/firebase-admin-node/blob/master/src/auth/auth-api-request.ts#L1011].

I note that the OpenAPI schema for `createSessionCookie` [specifies the parameter as "string (int64 format)"](https://cloud.google.com/identity-platform/docs/reference/rest/v1/projects/createSessionCookie). If that means it's meant to be a string-encoded int64, then this is really a `firebase-admin-node` bug, although clearly the production auth server is accepting numbers for this parameter.

**Comment by samtstern** [comment]
@andymatuschak thanks for digging into that!  Filed: https://github.com/firebase/firebase-admin-node/issues/1084

**Comment by gvelesandro** [comment]
> @royletron where is your express server running? Right now the Admin SDK only accepts emulated ID Tokens **when running inside of the Cloud Functions emulator**. This is a decision we made for security reasons, although we are open to reconsidering this based on developer feedback.

I'm experiencing the same issue as described above, _even_ with my express server running inside of the Firebase Functions emulator.

**Comment by yuchenshi** [comment]
As of Firebase CLI v9.3.0, creating session cookie is now supported and we've also added coercion from number to string similar to production behavior (hat tip to @andymatuschak). Note that you need [Node.js Admin SDK v9.5.0](https://github.com/firebase/firebase-admin-node/releases/tag/v9.5.0) to *verify* these cookies properly.
