### ISSUE TITLE
Writing to firestore emulator silently fails when collection contains slashes

### ISSUE THREAD

**Issue by MarcusCemes** [firebase/firebase-tools#2772]
### [REQUIRED] Environment info

**firebase-tools:** 8.14.1

**Platform:** Windows

### [REQUIRED] Test case

```ts
await admin
        .firestore()
        .collection("collection1/doc1/collection2")
        .doc("doc2")
        .set({ data: true });
```

### [REQUIRED] Steps to reproduce

1. Create a function that runs the above code using the admin SDK.
2. Start the Firestore and Functions emulator suite.
3. Invoke the function using the local functions shell
4. Check the Firestore emulator using the Emulator UI

### [REQUIRED] Expected behavior

The emulator **implements the same query behaviour as the real Firestore**, where the collection name is split by slash and an error is thrown if the number of elements is even, meaning that the final element is a document (alternating document/collection).

This would avoid having to recursively iterate `.doc()` and `.collection()` and allow the use of Typescript enums for constant nested collection names.

### [REQUIRED] Actual behavior

The write succeeds but no document is written to the database, despite a valid `writeTime` being set on the query result. Replacing the collection with something without slashes or alternating `.doc()` and `.collection()` works.

The following is the emulator debug output when the function is invoked.

```
[2020-11-02T20:08:46.016Z] Nov 02, 2020 9:08:46 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected HTTP/2 connection.
 {"metadata":{"emulator":{"name":"firestore"},"message":"Nov 02, 2020 9:08:46 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead\r\nINFO: Detected HTTP/2 connection.\r\n"}}
```

**Comment by samhorlbeck** [comment]
This sounds like a bug, I've filed it internally at b/172370865

**Comment by yuchenshi** [comment]
The documents should be correctly created, but unfortunately a bug in Emulator UI prevents them from appearing in the Firestore Viewer. https://github.com/firebase/firebase-tools-ui/issues/273

Please subscribe to that issue for updates. For now, you can verify the documents are created using SDK code, or pull up Chrome DevTools on Emulator UI to use JS SDK on the spot. Sorry for the inconvenience.

**Comment by MarcusCemes** [comment]
Fantastic, as long as it's there I shouldn't have to rewrite any code. Thanks!
