### ISSUE TITLE
Suppress auth emulator warning message 

### ISSUE THREAD

**Issue by motiejunas** [firebase/firebase-tools#2773]
Is there any way to suppress _"WARNING: You are using the Auth Emulator, which is intended for local testing only. Do not use with production credentials."_ message?

This is really annoying when working with Chrome extensions that it is considered as an error.

**Comment by samtstern** [comment]
@motiejunas thank for the feedback, you're not the first one to tell us the warning banner is annoying although right now it's there because we are trying to be as cautious as possible about security.  

Can you explain a little more about how this affects Chrome Extensions?  I'm not familiar with that issue.

**Comment by motiejunas** [comment]
> @motiejunas thank for the feedback, you're not the first one to tell us the warning banner is annoying although right now it's there because we are trying to be as cautious as possible about security.
> 
> Can you explain a little more about how this affects Chrome Extensions? I'm not familiar with that issue.

Basically any console.error/console.warn renders this "Errors" button:

<img width="827" alt="Screenshot 2020-11-03 at 13 39 37" src="https://user-images.githubusercontent.com/23213802/97986532-2376db00-1dda-11eb-85ae-77046086bf64.png">


In a normal development routine, I do not see this button and if I see - I have to inspect and check what went wrong with the extension. Now, I have to repeat the same (inspect) every single time to check if this is any real problem or this is just a silly warning.

So it would be really cool to pass some extra flag to mute warnings.

**Comment by samtstern** [comment]
@motiejunas thanks for explaining!  Sounds like we should switch to `console.log` or `console.info` then/

**Comment by Joebayld** [comment]
What about the HTML overlay that happens on the webpage? Is there an API to not show this? 

<img width="547" alt="Screen Shot 2020-11-07 at 3 23 34 PM" src="https://user-images.githubusercontent.com/9399317/98453379-3d335d80-210d-11eb-9d94-94bbad344aae.png">

**Comment by samtstern** [comment]
@Joebayld there's no API to hide that right now, but we're working on providing some sort of option!  For now you can hopefully hide it with custom css.

**Comment by smhmd** [comment]
@samtstern In my use case, playing with the auth emulator, the warn and banner started messing up my testing.
![image](https://user-images.githubusercontent.com/46059092/100094592-8c8dc380-2e59-11eb-9093-a85bcb2a9d81.png)

**Comment by akauppi** [comment]
@Joebayld I did a global CSS that hides that message, in development.

**Comment by samtstern** [comment]
We're working on adding a flag to the `useEmulator` API to allow you to hide this warning, hopefully coming soon!

**Comment by nickmarca** [comment]
What does it want to mean by "Do not use with production credentials" tough ? Should I use any different `firebaseConfig` when using the emulator ?

**Comment by samtstern** [comment]
@nickmarca it means don't type in your real password or anything else sensitive since it's going to be exposed over `http` when traveling to the emulator.

**Comment by saevarb** [comment]
My main issue with the banner was that it was in the way at the bottom. While I am using another styling solution, dropping something like the following into index.css in my CRA project is a decent temporary fix.

`div.firebase-emulator-warning {
  top: 0;
  height: 30px;
  width: 200px !important;
  overflow: hidden;
}
`

**Comment by motiejunas** [comment]
With v8.2.0 it is now possible to hide the banner and console.log is used instead of console.warn.

**Comment by smhmd** [comment]
@motiejunas Could you explain how?

**Comment by samtstern** [comment]
@motiejunas @smhmd we've added a new option (documentation is a bit behind):

```js
firebase.auth().useEmulator("http://localhost:9099", { disableWarnings: true })
```

This is in the Firebase JS SDK 8.2.0 release:
https://firebase.google.com/support/release-notes/js#version_820_-_december_11_2020

**Comment by harrisonlo** [comment]
Are the types updated? I see the [commit](https://github.com/firebase/firebase-js-sdk/commit/f2562c2924f26e9230f7d47e084291bc56aef297#diff-db993f2c787645d3c8542fe9daebc40bca281dc07199def70f8aad1f9329175e) has updated it, but the downloaded index.d.ts file still has `useEmulator(url: string): void` (my node_modules/firebase/package.json says 8.2.0 so I think it's at the right version)

**Comment by samtstern** [comment]
@harrisonlo I'm not sure ... if you're seeing an issue with the types please raise that on the [firebase-js-sdk](https://github.com/firebase/firebase-js-sdk) repo and I'm sure they will take care of it!

**Comment by wmadden** [comment]
This message comes up repeatedly for me during automated test runs

**Comment by smhmd** [comment]
@wmadden Were you not able to suppress it using this?
 
> ```js
> firebase.auth().useEmulator("http://localhost:9099", { disableWarnings: true })
> ```
> 
> This is in the Firebase JS SDK 8.2.0 release:
> https://firebase.google.com/support/release-notes/js#version_820_-_december_11_2020

**Comment by wmadden** [comment]
Thanks @smhmd! That did the trick

**Comment by joaomelo** [comment]
> @motiejunas @smhmd we've added a new option (documentation is a bit behind):
> 
> ```js
> firebase.auth().useEmulator("http://localhost:9099", { disableWarnings: true })
> ```
> 
> This is in the Firebase JS SDK 8.2.0 release:
> https://firebase.google.com/support/release-notes/js#version_820_-_december_11_2020

Hi there,

I don't know if the intention was to suppress only web UI warnings but I'm still receiving them in the console during tests.

I'm using firebase SDK 8.3.0. Below snippets of the related code:

test case
```
  test('correctly connect to emulator', () => {
    const config = {
      app: initFirebaseAppFromEnv(),
      emulatorUrl: process.env.FIREBASE_AUTH_EMULATOR_URL
    };
    const identityProvider = createIdentityProvider(config);

    expect(identityProvider).toBeDefined();
  });
```

emulator init
```
export async function plugEmulator (fireauth, emulatorUrl) {
  fireauth.useEmulator(emulatorUrl, { disableWarnings: true });
  await clearUsers(fireauth, emulatorUrl);
  await createDefaultUser(fireauth);
}
```

Here is the console warning. 
![Captura de tela 2021-03-20 155755](https://user-images.githubusercontent.com/5727050/111882572-14618580-8995-11eb-854c-329c065b4eaf.png)

I'm doing something wrong?

**Comment by samtstern** [comment]
@motiejunas no you're not doing anything wrong, that `console.info` message is always logged even if the banner is not displayed.

**Comment by joaomelo** [comment]
I got it @samtstern. Thank you.

I understand the SDK concern about wrong connections. I wonder if I could suppress it somehow during tests. As test cases amount, things get increasingly noisy.

![Captura de tela 2021-03-22 131844](https://user-images.githubusercontent.com/5727050/112022741-54e60e00-8b11-11eb-8d7b-a7e55f0eac41.png)

**Comment by wceolin** [comment]
@joaomelo One workaround we're using is to actually mock the `console.info` implementation to suppress these warnings during tests (in our `setupTests.js` file):

```ts
jest.spyOn(global.console, 'info').mockImplementation((info: string) => {
  // Suppress Firebase auth emulator warning since they can be quite noisy during tests
  // https://github.com/firebase/firebase-tools/issues/2773
  if (info.includes('Auth Emulator')) {
    return undefined;
  }

  // eslint-disable-next-line no-console
  return console.log(info);
});
```

**Comment by joaomelo** [comment]
That's amazing, @wceolin! Thank you so much.

**Comment by mesqueeb** [comment]
> @nickmarca it means don't type in your real password or anything else sensitive since it's going to be exposed over `http` when traveling to the emulator.

I had to search a lot for this information... Why don't you just write this in the warning instead? I, like many others, was confused thought we had to use different firebase config/project. But it's just about using test users and not typing in your password.

Any chance we can see this error message improved by adding this valuable information? @nickmarca

**Comment by mattpupa** [comment]
> @motiejunas @smhmd we've added a new option (documentation is a bit behind):
> 
> ```js
> firebase.auth().useEmulator("http://localhost:9099", { disableWarnings: true })
> ```
> 
> This is in the Firebase JS SDK 8.2.0 release:
> https://firebase.google.com/support/release-notes/js#version_820_-_december_11_2020

This fix doesn't seem to work for me...not sure why. I still see the banner at the bottom of my html page. The weird thing is, I tried disconnecting the auth emulator completely, but commenting out this code in my script.js file, and removing `"auth": {
      "port": 9099
    }`

from my firebase.json file. Even with those changes, the banner is still showing up for me.

**Comment by fahadahmed** [comment]
When using Typescript I am getting a warning when adding the `{ disableWarnings: true}` . Also having the warning displayed when running the test suites becomes very noisy as highlighted before. Need a way to supress the warnings in Node environment.

**Comment by Joebayld** [comment]
@fahadahmed This is an issue with the JS SDK, not firebase tools. See open issue here: https://github.com/firebase/firebase-js-sdk/issues/4591

**Comment by SrBrahma** [comment]
> @nickmarca it means don't type in your real password or anything else sensitive since it's going to be exposed over `http` when traveling to the emulator.

I don't understand this. I am the only dev of my app, do I have to care about it?

**Comment by mesqueeb** [comment]
@SrBrahma if you are using public wifi there is a potential that an http request is intercepted. So if you use real life passwords, they could be compromised.

**Comment by falk-stefan** [comment]
I also hid the emulatore warning via CSS. Not that you can also make it click through using `pointer-events`:

```
.firebase-emulator-warning {
  opacity: 0.15;
  pointer-events: none;
}
```

**Comment by mangonaise** [comment]
### _For anyone who wants to prevent those noisy Auth Emulator warning messages from appearing in their test logs_

---

If you are connecting the auth emulator outside your test, then mocking `console.info` won't help (as the warning appears when you call `connectAuthEmulator()`. 

Here is a way to disable the logs, **but if you do this, it's a bad idea to simultaneously hide the DOM-injected warning with `disableWarnings`**, because then you won't see any warnings at all, anywhere. They are there for a reason.

```ts
// in the same file where you connect your emulators

const consoleInfo = console.info

function setShowAuthEmulatorWarning(show: boolean) {
  console.info = show ? consoleInfo : () => { }
}
```

Then, wrap `connectAuthEmulator()` inside 2 different calls to the above function; the 1st disables `console.info` and the 2nd re-enables it.

```ts
setShowAuthEmulatorWarning(false)
connectAuthEmulator(auth, 'http://localhost:9099')
setShowAuthEmulatorWarning(true)
```

**Comment by ben-tg** [comment]
This works great. https://github.com/firebase/firebase-tools/issues/2773#issuecomment-918861851

**Comment by peterfortuin** [comment]
Is this disableWarnings flag also possible from Flutter?

**Comment by zepol-yerffej** [comment]
> Is this disableWarnings flag also possible from Flutter?

Doesn't look like it.

**Comment by ANDREYDEN** [comment]
> Is this disableWarnings flag also possible from Flutter?

In my app I just add some CSS in the `web/index.html` to hide the banner:
```html
<body>
  <style>
    .firebase-emulator-warning {
      display: none;
    }
  </style>

  ...
</body>
```

**Comment by arnonrdp** [comment]
This is what worked for me:
```js
connectAuthEmulator(auth, 'http://127.0.0.1:9099', { disableWarnings: true })
```
