### ISSUE TITLE
hosting:channel:deploy partial deployment and 404 error when channel ID contains "#"

### ISSUE THREAD

**Issue by sttic** [firebase/firebase-tools#2783]
If a channel ID contains a `#`, the CLI begins deploying but errors out with a 404 after the "releasing new version..." step. It still creates the preview channel, using the characters before the `#` as the ID, however the resulting link is a "Site Not Found" page.

### [REQUIRED] Environment info

**firebase-tools:** 8.15.0

**Platform:** Manjaro Linux

### [REQUIRED] Test case

```
firebase hosting:channel:deploy test#removed
```

### [REQUIRED] Steps to reproduce

:white_check_mark: This works fine:

```
firebase hosting:channel:deploy test-removed
```

:white_check_mark: This has the expected error:

```
firebase hosting:channel:deploy test@removed

Error: HTTP Error: 400, Channel IDs can only include letters, numbers, underscores, hyphens, and periods.
```

:stop_sign: This errors with a 404:

```
firebase hosting:channel:deploy test#removed

=== Deploying to 'redacted'...

i  deploying hosting
i  hosting[redacted]: beginning deploy...
i  hosting[redacted]: found 51 files in out
✔  hosting[redacted]: file upload complete
i  hosting[redacted]: finalizing version...
✔  hosting[redacted]: version finalized
i  hosting[redacted]: releasing new version...

Error: HTTP Error: 404, Not Found
```

### [REQUIRED] Expected behavior

The CLI should error out explaining why my channel ID is bad.

### [REQUIRED] Actual behavior

The CLI starts deploying and then errors out with `Error: HTTP Error: 404, Not Found`. The partial deploy is seen with `firebase hosting:channel:list` and on the online Firebase console. It uses the characters before the `#` as the ID (i.e. `test#removed` -> `test`). Visiting the link results in the Firebase "Site Not Found" page.

> Run the command with --debug flag, and include the logs below.

```firebase hosting:channel:deploy test#removed --debug``` contains some information I rather not post publicly. I can send privately on request if needed.

**Comment by bkendall** [comment]
Interesting find - thanks for reporting. I think `#` shouldn't be allowed in the name (though I'll double check), so something's not doing the correct validation...
