### ISSUE TITLE
Firebase onUpdate triggering at the root node instead of deep path

### ISSUE THREAD

**Issue by srinivasanj** [firebase/firebase-tools#2796]
### [REQUIRED] Environment info

**firebase-tools:** 8.15.1

**Platform:** macOS

### [REQUIRED] Test case

See below please. Its rather straight forward.

### [REQUIRED] 
1. Create a simple data structure with couple of roots and deep paths in Firebase Database
2. Write an onUpdate function on any path
3. Update a value on the path to check if onUpdate triggers **only** at that path

Example:
/foo/bar/baz/really/deep/path
/foo/abc/really/deep/path
/foo/xyz/really/deep/path

Write onUpdate function at /foo/bar/baz/.

### [REQUIRED] 
Function triggers only at /foo/bar/baz/

### [REQUIRED] 
Function triggers at /foo/ if there are updates anywhere in the path.

**Comment by srinivasanj** [comment]
> This issue does not seem to follow the issue template. Make sure you provide all the required information.

Updated.

**Comment by srinivasanj** [comment]
Not an issue anymore. Very strange but it seems to be working as expected now.

**Comment by samtstern** [comment]
@srinivasanj thanks for following up!
