### ISSUE TITLE
Firebase--version shows "command not found" 

### ISSUE THREAD

**Issue by AedenThomas** [firebase/firebase-tools#2797]
### [REQUIRED] Environment info

**firebase-tools:** 8.15.1

**Platform:** macOS Catalina 10.15.6

### [REQUIRED] Test case

I just installed Firebase CLI by using
`brew` install firebase-cli 
and I'm getting the following error 

### [REQUIRED] Steps to reproduce

 sh firebase `--version`

### [REQUIRED] Expected behavior

Firebase version should be displayed 

### [REQUIRED] Actual behavior

```
/usr/local/bin/firebase: line 2: use strict: command not found
/usr/local/bin/firebase: firebase: line 3: syntax error near unexpected token `('
/usr/local/bin/firebase: firebase: line 3: `const semver = require("semver");'
```

**Comment by samtstern** [comment]
@AedenThomas seems like you may have an issue with your local `node` installation.  I'd suggest uninstalling the Firebase CLI and installing one of the standalone binary releases:
https://firebase.google.com/docs/cli#install_the_firebase_cli
