### ISSUE TITLE
Missing documentation for configuration "functions.source"

### ISSUE THREAD

**Issue by SamyPesse** [firebase/firebase-tools#280]
I'm using firebase for a large project which is using [lerna](https://github.com/lerna/lerna), and I'm storing the cloud functions in a package (`packages/cloud-functions`).

I had to explore the code to find the option [`functions.source`](https://github.com/firebase/firebase-tools/blob/ea12e608797b5e735d32dad8ba467dc6c7bd7864/lib/deploy/functions/prepare.js#L24).

It's not documented, neither the website or the README.

Thank you all 🍻

**Comment by kevinajian** [comment]
The option has been documented here:
https://firebase.google.com/docs/functions/manage-functions#deploy_functions
