### ISSUE TITLE
[Auth Emulator] Firebase ID token has no "kid" claim & missing signature

### ISSUE THREAD

**Issue by lupas** [firebase/firebase-tools#2813]
### Environment info

**firebase-tools:** 8.15.1
**firebase-js-sdk:** 8.0.1
**firebase-admin:** 9.3.0
**Platform:** macOS 10.15.7

### Issue

When using the **Auth Emulator** and running `getIdToken` on the authUser, the returned idToken is **missing the kid claim and the signature**.

This throws the following error when trying to verify the idToken in firebase-admin with `await admin.auth().verifyIdToken(idToken)`:

```
 ERROR  Firebase ID token has no "kid" claim. See https://firebase.google.com/docs/auth/admin/verify-id-tokens for details on how to retrieve an ID token.

  at FirebaseAuthError.FirebaseError [as constructor] (node_modules/firebase-admin/lib/utils/error.js:43:28)
  at FirebaseAuthError.PrefixedFirebaseError [as constructor] (node_modules/firebase-admin/lib/utils/error.js:89:28)
  at new FirebaseAuthError (node_modules/firebase-admin/lib/utils/error.js:148:16)
  at FirebaseTokenVerifier.verifyJWTWithProjectId (node_modules/firebase-admin/lib/auth/token-verifier.js:174:35)
  at node_modules/firebase-admin/lib/auth/token-verifier.js:103:26
```

### Test case

```js
// Firebase-js-sdk on the client
const idToken = await currentUser.getIdToken(true)
console.log(idToken)
```

### Steps to reproduce

1. Enable emulator
2. Call `getIdToken(true)` on the auth user
3. Log out the result
4. Compare it with emulator deactivated
5. Results will be different 

### Expected behavior

Return the idToken with kid claim in header and signature

> **Expected Example Result**: eyJhbGciOiJSUzI1NiIsImtpZCI6IjJmOGI1NTdjMWNkMWUxZWM2ODBjZTkyYWFmY2U0NTIxMWUxZTRiNDEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vbnV4dC1maXJlLWRlbW8iLCJhdWQiOiJudXh0LWZpcmUtZGVtbyIsImF1dGhfdGltZSI6MTYwNTE0MjA3NCwidXNlcl9pZCI6InY0NVhwQm5jTUJQY2RWa05UeGdlZ1ZKeDhTMDMiLCJzdWIiOiJ2NDVYcEJuY01CUGNkVmtOVHhnZWdWSng4UzAzIiwiaWF0IjoxNjA1MTQyMDc0LCJleHAiOjE2MDUxNDU2NzQsImVtYWlsIjoic2Rmc2FkZkBzZGZzYWRmLmFzZGYiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsic2Rmc2FkZkBzZGZzYWRmLmFzZGYiXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.rkGDML-cFHwvS1Ct3oeoFOA9YTamXaQRree5ukz8BZgDaZzCXJxFQDebQxtFdADGADj8BfmYU3NjCjIyhEM_iZ4blptLH1Vs3vub2IwJ2Eqifzwbgn2mpyImuhbjpDUtBbStO9pRBFAxttgkxuajw0WU0A6K_DE7WaFn5LuFR_MG8hITT1M_LQwokX5LfW52VjL4NZvJIXI1qPYU0_hfqfdXa59cMsEJ1J91J9HNXOI19N3qMnFTiOfkNE2FEjLpWJi_j25wrzuwOOXgkpQ8zSdN1Z13F_IlWzDxBq5nxh9i7ocIBA4xHWc8tlaV597S5QMb350srIg3hrE1Lfv30A

### Actual behavior

Kid claim and signature is missing:

> **Example Result**: eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJlbWFpbCI6InNkZnNkZkBzYWRmc2RmLnNkYWYiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImF1dGhfdGltZSI6MTYwNTE0MTY3NCwidXNlcl9pZCI6IlhiaXhla3Z6VVYzOGJ2RTA4ODE2cW83cDdxeXMiLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbInNkZnNkZkBzYWRmc2RmLnNkYWYiXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9LCJpYXQiOjE2MDUxNDE2NzQsImV4cCI6MTYwNTE0NTI3NCwiYXVkIjoibnV4dC1maXJlLWRlbW8iLCJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vbnV4dC1maXJlLWRlbW8iLCJzdWIiOiJYYml4ZWt2elVWMzhidkUwODgxNnFvN3A3cXlzIn0.

**Comment by samtstern** [comment]
@lupas where are you running `verifyIdToken` if you are running it *anywhere other than the Cloud Functions emulator* this is the currently intended behavior and you can track the request to change it here: https://github.com/firebase/firebase-tools/issues/2764

**Comment by lupas** [comment]
@samtstern 
Alright - thanks for the quick answer!

In the [nuxtjs/firebase module](https://github.com/nuxt-community/firebase-module) we are using `verifyIdToken(true)` within `onAuthStateChanged()` in a **service-worker** as described in the Firebase Auth docs [here](https://firebase.google.com/docs/auth/web/service-worker-sessions) to check if a user is signed in before SSR.

I'll close this one then and will be looking forward to https://github.com/firebase/firebase-tools/issues/2764 to be implemented :)
