### ISSUE TITLE
Deploy fails with v8.16+: Failed to get instance details for instance: <project-id>

### ISSUE THREAD

**Issue by jbaldassari** [firebase/firebase-tools#2819]
### [REQUIRED] Environment info

**firebase-tools:**
8.16.0, 8.16.1

**Platform:**
Ubuntu 18.04.5 LTS running in a Github Workflow

### [REQUIRED] Test case

Since upgrading to `firebase-tools` 8.16+ our deployments are failing when running the following commands:

```
firebase projects:list
firebase use ${GCP_PROJECT}
firebase deploy --non-interactive
```

The first two commands (`projects:list` and `use <project-id>`) complete successfully, but the `deploy --non-interactive` command fails with the following error:

```
Error: Failed to get instance details for instance: <project-id>. See firebase-debug.log for more details.
```

The `firebase-debug.log` file referenced by the error message does not exist, so we have been unable to get additional information about the cause of the failure.

The only workaround we've found so far is to pin the version of `firebase-tools` to `@8.15.1` rather than installing `@8`.

### [REQUIRED] Steps to reproduce

Run `firebase deploy --non-interactive`

### [REQUIRED] Expected behavior

`firebase deploy --non-interactive` deploys our project successfully

### [REQUIRED] Actual behavior

```
=== Deploying to '<project-id>'...


i  deploying database, hosting
i  database: checking rules syntax...


Error: Failed to get instance details for instance: <project-id>. See firebase-debug.log for more details.
Error: Process completed with exit code 1.
```

**Comment by sarajmunjal** [comment]
Hi James, thanks for reporting the issue.

To help us debug, could you check the value of the `GCP_PROJECT` variable and also provide the output you get after running `firebase target` ? My suspicion here is that the value of `GCP_PROJECT` is `<project_id` which seems like a placeholder and is not the actual project ID.

**Comment by jbaldassari** [comment]
Hi @sarajmunjal .  The error didn't actually say `<project-id>`.  I replaced our actual project ID with that generic placeholder  in this ticket because I didn't want to publish that information publicly.

**Comment by sarajmunjal** [comment]
That makes sense. Are you able to access your database from the Firebase Console for the same project @jbaldassari ?

**Comment by jbaldassari** [comment]
Yes @sarajmunjal we can access everything from the firebase console, and when we rolled back `firebase-tools` to `8.15.1` we were able to perform the deployments as normal.  It just seems to be an issue when using `firebase-tools` >= `8.16.0`.

By the way, if you suspect that there is a GCP/Firebase project configuration issue that is specific to us rather than a bug in `firebase-tools`, I'm happy to take this to email or another channel.

**Comment by bkendall** [comment]
@jbaldassari - can you try one thing for me? I ran into a similar issue when debugging a different problem. Could you try the `database:get` command and let me know if you get a similar error?

**Comment by bkendall** [comment]
I need to be a bit more specific: could you try with the same authentication method as your CI system? I think there's an API-enablement type issue that needs to be addressed, but I'm looking to verify that with you

**Comment by jbaldassari** [comment]
@bkendall yes, similar error for `databse:get` :
```
+ firebase database:get /

Error: Failed to get instance details for instance: <project-id>. See firebase-debug.log for more details.
Error: Process completed with exit code 1.
```

**Comment by bkendall** [comment]
Alright, magic "do this thing" test. Can you try enabling the [Realtime Database API](https://console.cloud.google.com/apis/library/firebasedatabase.googleapis.com) for your project (be sure to select the right one in the top dropdown) and retrying? If that works, that'll give us exactly the information we need.

**Comment by jbaldassari** [comment]
@bkendall enabling the realtime database api on the project did fix the problem, and I'm now able to execute deployments in that project with the latest version of `firebase-tools`.  In the api metrics I see that `google.firebase.database.v1beta.RealtimeDatabaseService.GetDatabaseInstance` was invoked.

**Comment by bkendall** [comment]
We've taken care of this in a couple ways, including enabling the API when `init database` is run. If anyone runs into an issue with this, let us know here or reach out to [Firebase Support](https://firebase.google.com/support)

**Comment by plvbroker** [comment]
Hi ! Just to let you know I ranb into the same issue today.
But enabling the Realtime Database also did not the trick 😥

**Comment by bkendall** [comment]
@plvbroker could you open a new issue with all the appropriate information? That'll be the best way to figure it out.
