### ISSUE TITLE
firebase emulators:start --only hosting:TARGET_NAME command does not work

### ISSUE THREAD

**Issue by motiejunas** [firebase/firebase-tools#2820]
First, I did add a custom target by running `firebase target:apply demo my-project`. However, when running `firebase emulators:start --only hosting:demo` I receive the following error message:

> Error: hosting:demo is not a valid emulator name, valid options are: ["auth","functions","firestore","database","hosting","pubsub"]

As per documentation (https://firebase.google.com/docs/hosting/multisites?authuser=0#cli-commands-with-deploy-targets) `firebase emulators:start --only hosting:TARGET_NAME` should emulate the Hosting content and configuration of the specified Hosting site at a locally hosted URL.

**Comment by samtstern** [comment]
@motiejunas thanks for reporting this, seems like a bug in the argument parser!
