### ISSUE TITLE
How to setup the Firebase Auth Emulator?

### ISSUE THREAD

**Issue by HemanthDavuluri** [firebase/firebase-tools#2821]
i got the all other emulators working but i couldnt get the auth working. can anybody help?

**Comment by samtstern** [comment]
@HemanthDavuluri when filing an issue please use the issue template.  This contains no information about what you tried, what exactly happened (logs, etc), or your development environment.  It's not possible to help you based on your question alone.

If you can provide that information please do so in a new issue.  If you're not sure how to provide that information, try your question on a more general forum like StackOverflow.
