### ISSUE TITLE
Firebase cloud function local code changes are not reflected in emulators

### ISSUE THREAD

**Issue by Abhimanyu14** [firebase/firebase-tools#2823]
I have posted a question in StackOverflow. Creating a bug here as recommended by Doug Stevenson.
StackOverflow Post link: https://stackoverflow.com/q/64845931/9636037

Issue details:
I am trying to develop API for my apps using Firebase cloud functions.
Following this (https://firebase.google.com/docs/emulator-suite) site to use the firebase emulator suite for development and testing locally.

Issue: The changes are not reflected in the locally emulated functions.

### [REQUIRED] Environment info

**firebase-tools:** 8.16.2
**Platform:** Windows 10
Node: 10.15.3 (node --version)

### [REQUIRED] Steps to reproduce

1. index.js code:

```js
exports.test = functions.https.onRequest(async (request, response) => {
   response.status(200).send("First");
});
```

2. Successfully deployed the test method.

the command used to deploy: 
```
firebase deploy --only functions:test
```

3. In Postman made the following GET request.

```
https://us-central1-<project-name>.cloudfunctions.net/test
Result: First
Status: 200 OK
```

4. Started the emulators:

```
firebase emulators:start --only functions
```

5. In Postman made the following GET request.

```
http://localhost:5001/<project-name>/us-central1/indexTest
Result: First
Status: 200 OK
```
Same as the actual deployed function.

6. Changed the function code to:

```js
exports.test = functions.https.onRequest(async (request, response) => {
    response.status(200).send("Second");
});
```

7. Getting the same result as before when hitting the emulated function in the localhost. The changes are not reflected.

Also, tried stopping the emulator and starting it again. No luck.

### [REQUIRED] Expected behavior

Locally emulated functions in the emulator should reflect the local code changes.

### [REQUIRED] Actual behavior

The emulator is not recognizing the local code changes.

**Comment by samtstern** [comment]
@Abhimanyu14 a few questions:

- Does your code have any compilation step? For example are you using TypeScript or a bundler like Webpack?  If so are you sure that has run?
- Can you show the debug logs from the emulators as well as the contents of your `package.json` file?

**Comment by Vloz** [comment]
Maybe not related, but using Typescript i had the same probleme today, without any change from me, tsc now output index.js to lib/src instead of lib. 
Had to change  "main" setting to "lib/src/index.js" in package.json.

**Comment by Abhimanyu14** [comment]
> @Abhimanyu14 a few questions:
> 
> * Does your code have any compilation step? For example are you using TypeScript or a bundler like Webpack?  If so are you sure that has run?
> * Can you show the debug logs from the emulators as well as the contents of your `package.json` file?

I am using Typescript. 
Not much data in logs.

**Comment by Abhimanyu14** [comment]
> @Abhimanyu14 a few questions:
> 
> * Does your code have any compilation step? For example are you using TypeScript or a bundler like Webpack?  If so are you sure that has run?
> * Can you show the debug logs from the emulators as well as the contents of your `package.json` file?

Logs:
i  functions: Beginning execution of "indexTest"
i  functions: Finished "indexTest" in ~1s

The name of the method is "indexTest"

**Comment by samtstern** [comment]
@Abhimanyu14 please provide the *debug* logs by doing this:
```
firebase --debug emulators:start
```

Also could I see your `package.json`?

**Comment by Abhimanyu14** [comment]
> firebase --debug emulators:start

package.json

{
  "name": "functions",
  "scripts": {
    "lint": "eslint \"src/**/*\"",
    "build": "tsc",
    "serve": "npm run build && firebase emulators:start --only functions",
    "shell": "npm run build && firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "engines": {
    "node": "12"
  },
  "main": "lib/index.js",
  "dependencies": {
    "firebase-admin": "^9.2.0",
    "firebase-functions": "^3.11.0"
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^3.9.1",
    "@typescript-eslint/parser": "^3.8.0",
    "eslint": "^7.6.0",
    "eslint-plugin-import": "^2.22.0",
    "typescript": "^3.8.0",
    "firebase-functions-test": "^0.2.0"
  },
  "private": true
}

**Comment by Abhimanyu14** [comment]
[firebase-debug.log](https://github.com/firebase/firebase-tools/files/5547263/firebase-debug.log)
Have uploaded a file. Is that what you are asking for. 
I am new to node JS and cloud functions.

**Comment by samtstern** [comment]
@Abhimanyu14 after changing your TypeScript code you have to run `npm run build` to compile it again. The Functions emulator looks at the *compiled* code which is in `lib/index.js` (that's what is defined in `main` in `package.json`).

So I suspect you're just forgetting to compile after changing the TS source.

**Comment by Abhimanyu14** [comment]
> @Abhimanyu14 after changing your TypeScript code you have to run `npm run build` to compile it again. The Functions emulator looks at the _compiled_ code which is in `lib/index.js` (that's what is defined in `main` in `package.json`).
> 
> So I suspect you're just forgetting to compile after changing the TS source.

Getting the following error message:

internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'semver'
Require stack:
- C:\Users\abhim\AppData\Roaming\npm\node_modules\npm\lib\utils\unsupported.js
- C:\Users\abhim\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:725:27)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:952:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:88:18)←[39m
    at Object.<anonymous> (C:\Users\abhim\AppData\Roaming\npm\node_modules\←[4mnpm←[24m\lib\utils\unsupported.js:2:14)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1063:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:928:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:769:14)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:952:19)←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: [
    ←[32m'C:\\Users\\abhim\\AppData\\Roaming\\npm\\node_modules\\npm\\lib\\utils\\unsupported.js'←[39m,
    ←[32m'C:\\Users\\abhim\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js'←[39m
  ]
}

**Comment by Abhimanyu14** [comment]
@samtstern ,

It works now. 
Was not aware that the Typescript files have to be built.
Thanks a lot.

**Comment by samtstern** [comment]
@Abhimanyu14 glad it's working!

Also you can use `tsc -w` to have TypeScript automatically rebuild every time you save.

**Comment by arishilyaeva** [comment]
It's such an obvious solution, I had the same issue and spent hours on debugging and trying to understand what I'm doing wrong, wish I could've found this answer sooner, would've saved so much time

**Comment by nivla360** [comment]
> It's such an obvious solution, I had the same issue and spent hours on debugging and trying to understand what I'm doing wrong, wish I could've found this answer sooner, would've saved so much time

same here
