### ISSUE TITLE
No Auth Emulation option when installing the emulators

### ISSUE THREAD

**Issue by RobSwish** [firebase/firebase-tools#2826]
### [REQUIRED] Environment info

**firebase-tools:8.13.0**

**Platform: macOS**

### [REQUIRED] Test case

Given I am installing the emulation suite
When presented with the different suites to install such as firestore, realtime, functions, etc
Then I am not shown the "Auth" option

The function to set my iOS Swift App to use the emulation also does not register:
<img width="925" alt="Screenshot 2020-11-16 at 13 15 55" src="https://user-images.githubusercontent.com/6002183/99256807-dd743b00-280d-11eb-9ee4-2c8fc7e3e662.png">

### [REQUIRED] Steps to reproduce

Install emulators via terminal
View available emulators
You should not be able to see auth

To be able to see auth

N/A

**Comment by RobSwish** [comment]
Follows the template exactly you silly bot.

**Comment by samtstern** [comment]
@RobSwish the Auth emulator was released on `8.14.0` so you need to update:
https://github.com/firebase/firebase-tools/releases/tag/v8.14.0

Support for using the Auth emulator with the iOS SDK was released in `7.0.0` of that SDK:
https://firebase.google.com/support/release-notes/ios

If you're having iOS SDK issues besides needing to update please file them on the `firebase-ios-sdk` repo.

**Comment by samtstern** [comment]
As for the silly bot, it was complaining that you missed the 'Expected Behavior' and 'Actual Behavior' sections of the issue template.

**Comment by RobSwish** [comment]
Oh, I put those behaviour things in but I guess not in the places it expected. Thanks for the speedy help. 

The docs for the emulators suite say:

"You will need CLI version 7.8.0 or higher to use the Emulator Sute" - (With that small typo) So I didn't update, but I will now.

**Comment by samtstern** [comment]
@RobSwish thanks for pointing that out! I will get those docs updated.
