### ISSUE TITLE
Hosting emulator redirects don't work on images

### ISSUE THREAD

**Issue by samtstern** [firebase/firebase-tools#2834]
### [REQUIRED] Environment info

**firebase-tools:** 8.16.1

**Platform:** macOS

### [REQUIRED] Test case

firebase.json
```js
{
  "hosting": {
    "public": "public",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "redirects": [{
      "source": "/docs/:path*",
      "destination": "/firebase/en/docs/:path",
      "type": 301
    }]
  }
}
```

Proof that the image exists:
```
$ ls public/firebase/en/docs/auth/case-studies/
fabulous.pdf     fabulous.png     index.html       kwaver-icon.jpg  rave.pdf         rave.png
```

Try to curl the image at redirected path, get 404:
```
$ http "http://localhost:5000/docs/auth/case-studies/kwaver-icon.jpg"
HTTP/1.1 404 Not Found
Connection: keep-alive
Content-Length: 177
Content-Security-Policy: default-src 'none'
Content-Type: text/html; charset=utf-8
Date: Tue, 17 Nov 2020 16:53:15 GMT
X-Content-Type-Options: nosniff

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /docs/auth/case-studies/kwaver-icon.jpg</pre>
</body>
</html>
```

Curl the image at original path, it works:
```
$ http "http://localhost:5000/firebase/en/docs/auth/case-studies/kwaver-icon.jpg"
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 6809
Content-Type: image/jpeg
Date: Tue, 17 Nov 2020 16:54:07 GMT
ETag: b8304bdc7364fd163e1694f65644db67
Last-Modified: Tue, 17 Nov 2020 16:47:53 GMT

+-----------------------------------------+
| NOTE: binary data not shown in terminal |
+-----------------------------------------+
```

In production the redirect works:
```
$ http "http://<redacted-project-id>.web.app/docs/auth/case-studies/kwaver-icon.jpg"
HTTP/1.1 301 Moved Permanently
Accept-Ranges: bytes
Connection: keep-alive
Content-Length: 0
Date: Tue, 17 Nov 2020 16:54:47 GMT
Location: https://<redacted-project-id>.web.app/docs/auth/case-studies/kwaver-icon.jpg
Retry-After: 0
Server: Varnish
X-Cache: HIT
X-Cache-Hits: 0
X-Served-By: cache-lcy19249-LCY
X-Timer: S1605632088.752684,VS0,VE0
```

### [REQUIRED] Steps to reproduce

See above

### [REQUIRED] Expected behavior

Local redirects work just like production redirects

### [REQUIRED] Actual behavior

See above

**Comment by samtstern** [comment]
@bkendall do you think this is a superstatic bug?  Not sure where redirects get handled locally.  Strange that this works for `html` pages but not for `jpg` files (in my experience)

**Comment by bkendall** [comment]
Yes, this would be a bug for superstatic. I'm not sure exactly _why_ this is not working, but definitely something we can check into.

**Comment by bkendall** [comment]
FWIW, I'm unable to replicate this. Can you double check that you're editing the correct config locally?

It doesn't actually _matter_ that the file at the location exists or not for a redirect. What matters is that the redirect matches. If you're seeing a `404`, I suspect it's because (1) the file you're requesting doesn't exist and (2) there are no redirects configured for that path.

**Comment by samtstern** [comment]
Hmm yeah I can't reproduce this either with a clean project ... must have been something with my specific project setup.
