### ISSUE TITLE
Functions emulator does not honor timeoutSeconds

### ISSUE THREAD

**Issue by xaphod** [firebase/firebase-tools#2837]
### [REQUIRED] Environment info

**firebase-tools:** 8.16.2

**Platform:** macOS 10.15.7

### [REQUIRED] Test case

```
exports.zip = functions
  .runWith({ memory: '1GB', timeoutSeconds: 540 })
  .https
  .onRequest(zip);
```

### [REQUIRED] Steps to reproduce

Run function on emulator such that it takes a long time to execute.

### [REQUIRED] Expected behavior

I expect that the function times out in 540 seconds.

### [REQUIRED] Actual behavior

The function times out in about 60 seconds (I did not time it, that is a guess).

Is it a known issue that the emulator doesn't respect `timeoutSeconds`, or did I do it wrong?

**Comment by samtstern** [comment]
@xaphod as far as I can tell timeout is working.  I wrote these two functions:

```js
const functions = require('firebase-functions');

exports.withTimeout = functions.runWith({
  timeoutSeconds: 30
}).https.onRequest((request, response) => {
  setTimeout(() => {
    response.send("Hello from Firebase!");
  }, 45 * 1000);
});

exports.withoutTimeout = functions.runWith({
  memory: '1GB'
}).https.onRequest((request, response) => {
  setTimeout(() => {
    response.send("Hello from Firebase!");
  }, 45 * 1000);
});
```

When I run the one with the 30s timeout:
```
i  functions: Beginning execution of "withTimeout"
⚠  functions: Your function timed out after ~30s. To configure this timeout, see
      https://firebase.google.com/docs/functions/manage-functions#set_timeout_and_memory_allocation.
>  /Users/samstern/Projects/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:668
>                  throw new Error("Function timed out.");
```

When I run the one without:
```
i  functions: Beginning execution of "withoutTimeout"
i  functions: Finished "withoutTimeout" in ~44s
```

**Comment by samtstern** [comment]
I also made sure it's not about going over 60s:
```js
exports.veryLongTimeout = functions.runWith({
  timeoutSeconds: 120
}).https.onRequest((request, response) => {
  setTimeout(() => {
    response.send("Hello from Firebase!");
  }, 100 * 1000);
});
```

Logs:
```
i  functions: Beginning execution of "veryLongTimeout"
i  functions: Finished "veryLongTimeout" in ~99s
```

**Comment by xaphod** [comment]
OK - given that we are seeing different behavior, what do you want me to show you?
Did you try 540 seconds (the published maximum)? Perhaps the bug is specific to that?
Also, here's how i'm starting the emulator in case it makes a difference: `firebase emulators:start --inspect-functions 9230 --only functions,hosting`

**Comment by samtstern** [comment]
@xaphod ah ok!  `--inspect-functions` should disable timeout behavior completely because we didn't want people hitting timeouts while they have execution paused on a breakpoint.  So maybe that's not working?

**Comment by samtstern** [comment]
Can you create a simple example like but but run it with `--inspect-functions` and a 540ms timeout and show me all the logs from when it fails?

**Comment by TheRealMikeD** [comment]
I am experiencing this same issue.  I launch the emulator with the command:
`firebase serve --only functions,hosting --port 5005`

My timeout is set to 540, as follows:
`const app = express();`
`...`
`exports.app = functions.runWith({timeoutSeconds: 540}).https.onRequest(app);`

I feel like it used to work as expected, but I haven't attempted to run anything that takes longer than 60 seconds for a few weeks, until today.

**Comment by volkyeth** [comment]
Also experiencing this from `v1.2.0` onwards
Reverting to `v10.1.5` solves it

**Comment by volkyeth** [comment]
Yeah, it's an undocumented breaking change on v10.2.0:
https://github.com/firebase/firebase-tools/compare/v10.1.5...v10.2.0#diff-0366293848c53849685ead9c0871e6ab4c0b2232ebdb379ba79a6def21f99fc3R972-R985

**Comment by edenhermelin** [comment]
any updates on this one? anyone knows if there is a plan to fix this soon?

**Comment by danieljy** [comment]
Yes this just tripped me up as well.

**Comment by Corchoneitor** [comment]
Not sure if related, but I'm having another problem with timeoutSeconds.
If I set it to more than 125s, and my function process over 120s it doesn't return response and therefore timeouts.
![image](https://user-images.githubusercontent.com/2912593/160879137-938cc383-62bd-4899-be21-80f582bfb6e6.png)

I was expecting to get the response after process ended and the function to finishes.

**Comment by billylo1** [comment]
> @samtstern could this be reopened? I, along with others, are still experiencing this issue.
> 
> I can confirm that @volkyeth's [workaround](https://github.com/firebase/firebase-tools/issues/2837#issuecomment-1048878134) works.

To confirm:  are you using firebase-tools 10.2+?

**Comment by jonadeline** [comment]
same issue here, running firebase-tools 10.2+

**Comment by joaoggnogueira** [comment]
Same issue here, running firebase-tools 10.2.2

**Comment by dennismuench** [comment]
Same issue here, running firebase-tools 10.8.0.

**Comment by jromero** [comment]
@yuchenshi this @google-oss-bot is aggressive. :D

**Comment by yuchenshi** [comment]
@jromero Sorry for that. The issue should stay open from now on.

**Comment by tiagohillebrandt** [comment]
Same issue is happening over here, I'm using firebase-tools 11.0.0.

```js
functions
  .region('us-central1')
  .runWith({ memory: '256MB', timeoutSeconds: 120 })
  .https
  .onRequest(app)
```

```
⚠  functions: Your function timed out after ~60s. To configure this timeout, see
      https://firebase.google.com/docs/functions/manage-functions#set_timeout_and_memory_allocation.
>  /home/vagrant/.nvm/versions/node/v16.14.2/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:634
>              throw new Error("Function timed out.");
>              ^
>  
>  Error: Function timed out.
>      at Timeout._onTimeout (/home/vagrant/.nvm/versions/node/v16.14.2/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:634:19)
>      at listOnTimeout (node:internal/timers:559:17)
>      at processTimers (node:internal/timers:502:7)

```

**Comment by tiagohillebrandt** [comment]
Here's a workaround I've just found while reading through the `functionsEmulatorRuntime.js` file:

```
FUNCTIONS_EMULATOR_TIMEOUT_SECONDS=120 firebase emulators:start
```

**Comment by phongyewtong** [comment]
i having this issue as well.

**Comment by futureofworktraining** [comment]
HI, I have the same issue. Nothing works except hardcoding "60" to "360". Even setting up FUNCTIONS_EMULATOR_TIMEOUT_SECONDS=540s doesn't work. Strange.

**Comment by taeold** [comment]
Firebase CLI v11.4.0 should now support timeout on your function configuration - no need to setup `FUNCTIONS_EMULATOR_TIMEOUT_SECONDS` environment variable.

**Comment by absemetov** [comment]
I use CLI 11.4.0 my functions work only with --inspect-functions parametr

`$firebase emulators:start --inspect-functions --only functions,hosting `

Function 1
```
exports.helloWorld = functions.https.onRequest((request, response) => {
  functions.logger.info("Hello logs!", {structuredData: true});
  response.send("Hello from Firebase!");
});
```
Function 2
```
const runtimeOpts = {
  timeoutSeconds: 540,
  memory: "1GB",
};

exports.express = functions.runWith(runtimeOpts).https.onRequest(app);
```

**Comment by mhesham32** [comment]
any idea how to silent/hide logs from Google API requested! it is very hard to debug the function with all of these logs

**Comment by actuallymentor** [comment]
I'm noticing this issue in gen2 functions when run with `{ timeoutSeconds: 540 }` on a `onDocumentCreated`. Is this a known issue?

**Comment by ARGON90** [comment]
Also getting the timeout error on newer versions, for what it's worth.
```
const functions = require("firebase-functions");
const {initializeApp} = require("firebase-admin/app");
const {getFirestore} = require("firebase-admin/firestore");

exports.testFunc = functions
    .runWith({timeoutSeconds: 120})
    .https
    .onRequest(async (request, response) =>{
   ...
   ...
   })
```

```
i  Your function timed out after ~60s. To configure this timeout, see
      https://firebase.google.com/docs/functions/manage-functions#set_timeout_and_memory_allocation.
i  Request to function failed: Error: socket hang up
```

firebase-admin: 11.11.1,
firebase-functions :4.7.0,
firebase-tools@12.9.1

**Comment by FlyNumber** [comment]
> Yeah, it's an [undocumented breaking change on v10.2.0](https://github.com/firebase/firebase-tools/compare/v10.1.5...v10.2.0#diff-0366293848c53849685ead9c0871e6ab4c0b2232ebdb379ba79a6def21f99fc3R972-R976)
> 
> Looks like setting env `FUNCTIONS_EMULATOR_TIMEOUT_SECONDS=540s` is a workaround for the dropped feature
> 
> It can be [added on a .env.local file](https://firebase.google.com/docs/functions/config-env#emulator_support) on the functions folder to be used only on emulator

My function uses node 20, could that be the reason the above hasn't worked for me? The only way I can get the function to work locally is with the --inspect-functions flag.

**Comment by nadermjaber** [comment]
> Yeah, it's an [undocumented breaking change on v10.2.0](https://github.com/firebase/firebase-tools/compare/v10.1.5...v10.2.0#diff-0366293848c53849685ead9c0871e6ab4c0b2232ebdb379ba79a6def21f99fc3R972-R976)
> 
> Looks like setting env `FUNCTIONS_EMULATOR_TIMEOUT_SECONDS=540s` is a workaround for the dropped feature
> 
> It can be [added on a .env.local file](https://firebase.google.com/docs/functions/config-env#emulator_support) on the functions folder to be used only on emulator

The only way I can get the function to work locally is with the --inspect-functions flag. I wonder if its because this function uses node 20.

**Comment by ARGON90** [comment]
@nadermjaber had the solution that finally worked for me. package.json:
    "firebase-admin": "^12.0.0",
    "firebase-functions": "^4.7.0",
    "node": "18"
  
  globally:
    "firebase-tools": 13.2.1 
    "node": 20 (This is being used, I wonder if it's the issue?)
    
   adding the --inspect-functions flag when I started the emulator finally got it working
