### ISSUE TITLE
Auth data import/export does not seem to work

### ISSUE THREAD

**Issue by loucou** [firebase/firebase-tools#2846]
### [REQUIRED] Environment info

**firebase-tools:** 8.16.2

**Platform:** Windows

### [REQUIRED] Test case

A simple firebase web app

### [REQUIRED] Steps to reproduce

I use Firebase emulators with the auth emulator (very happy with this new feature!)
I signup a user using email and password -> I can see it created in the emulator UI.
I insert some data in Firestore -> it works equally well. I export the data:

firebase emulators:export local_data

Later on, I restart the emulators with the exported data:

firebase emulators:start --import=local_data 

### [REQUIRED] Expected behavior

The Firestore data as well as authentication credentials for the created user should populated upon emulators restart.

### [REQUIRED] Actual behavior
The Firestore data is populated. But the authentication credentials are not.
No trace of the previously created user, no way to sign him in.

**Comment by samtstern** [comment]
@loucou thanks for the feedback!  This is already tracked here: https://github.com/firebase/firebase-tools/issues/2749

Let's close this one and keep the discussion on the older thread.

**Comment by loucou** [comment]
Fine by me, sorry I missed the original issue.
