### ISSUE TITLE
Firebase authentication emulator issue with popup signup

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [firebase/firebase-tools#2850]
### [REQUIRED] Environment info
Firebase tools:
if I do firebase --version I get 8.16.1
But I'm sure I installed 8.16.2 globally.

**Platform:**
Windows

### [REQUIRED] Steps to reproduce
When using firebase emulator authentication, using this code (so popup):
firebase.auth().signInWithPopup(provider);
will not create the test user in the authentication

however using a redirect:
firebase.auth().signInWithRedirect(provider);
Does create the test user correctly.

**Comment by jonadeline** [comment]
I'm have the opposite issue 🤔
When trying to use the redirect option I got the message than the domain is not authorised.

I'm using gitpod, so my dev environnement is not run on localhost but on a gitpod.io dedicated domain. 
This might be a specific use case which has not been managed ?

**Comment by holmberd** [comment]
I have a similar issue with unauthorised-domain error when using `signInWithPopup` and `signInWithredirect` from the background page of a chrome extension.

Added ticket to Firebase-js-sdk: https://github.com/firebase/firebase-js-sdk/issues/4335

**Comment by Menar5276** [comment]
> Just Go to Your console.firebase.google.com and select the **Authentication** tab and Go to **Sign In Method** Go to **Authorized domains** click the button **Add Domain** and type the URL on which your app is running and hit **Add**
> 
> AND YOU ARE GOOD TO GOO ☺☺☺

In my case i have the domain  added and got the same error

**Comment by lisajian** [comment]
This is a known issue in the v8 SDK, but should be solved in v9 - would you mind trying to update and see if you are still getting the error? Thanks!

**Comment by LanderBeeuwsaert** [comment]
Hi @lisajian , for me this issue can be closed, but I can't speak for the others who have asked the same question.

**Comment by lisajian** [comment]
Got it, thanks! Since this is resolved in v9, I'll close this issue.
