### ISSUE TITLE
IdToken of emulated auth user is badly formatted

### ISSUE THREAD

**Issue by Kevinand11** [firebase/firebase-tools#2851]
### [REQUIRED] Environment info

**firebase-tools:8.16.2**

**Platform:windows**

### [REQUIRED] Test case

```js
firebase.initializeApp(firebaseConfig)
firebase.auth().useEmulator('http://localhost:5004')

const googleProvider = new firebase.auth.GoogleAuthProvider()
const record = await auth.signInWithPopup(googleProvider)
const idToken = await record.user.getIdToken(true)
```
```js
// On Server
const sessionCookie = admin.auth().createSessionCookie(idToken, {
	expiresIn: 14 * 86400 * 1000
})
```
### [REQUIRED] Steps to reproduce

Setup emulator.
Create a user and login with the user. 
Generate a new idtoken with the logged in user. 
Send idtoken over to a server with initialized admin sdk. 
Create a session cookie with the idtoken provided 

### [REQUIRED] Expected behavior

The createSessionCookie should return a promise that revolves to a encoded string 

### [REQUIRED] Actual behavior
The createSessionCookie throws an error that idToken is not a valid firebase ID token, meaning that the idToken generated from the logged in user is badly formatted.

I have confirmed that an idToken is actually generated in the previous step, a very long string, however the createSessionCookie method of the admin sdk keeps saying it is badly formatted. Note that this only works with the auth emulator. If I use the regular auth servers, a good idtoken is generated and it works fine

**Comment by Kevinand11** [comment]
From what I can see by comparing a normal idToken and an idToken gotten from an auth emulator, that from the auth emulator ends with a fullstop

**Comment by samtstern** [comment]
@Kevinand11 are you running `createSessionCookie` inside the Functions emulator or on your own server?  The Auth Emulator produces intentionally insecure Id Tokens and those are currently only accepted by the Admin SDK when it's running inside the Cloud Functions emulator: https://github.com/firebase/firebase-tools/issues/2764

**Comment by Kevinand11** [comment]
I am running it inside a personal server. I have seen the past issue, #2764 . Sorry, I forgot to close this one. I will be closing it now.
