### ISSUE TITLE
Issue with admin to rtdb emulator: Error: Can't determine Firebase Database URL.

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [firebase/firebase-tools#2852]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10
  * Browser version: /
  * Firebase SDK version: admin version is: 9.4.1
  * Firebase Product: rtdb & emulator
  * Firebase tools version: 8.16.1

### [REQUIRED] Test case

```js
#!/usr/bin/env node
//
// let path = require('path');
// const fs = require('fs');

import * as admin from 'firebase-admin';
import { firestore } from 'firebase-admin/lib/firestore';
import { UserModel } from '../../src/app/core/models/user.model';
import Timestamp = firestore.Timestamp;

class PopulateLauncher {

  constructor() {
    process.env.GCLOUD_PROJECT = 'some-project';
    process.env.FIRESTORE_EMULATOR_HOST = 'localhost:8080';
    process.env.FIREBASE_AUTH_EMULATOR_HOST = 'localhost:9099';
    process.env.FIREBASE_DATABASE_EMULATOR_HOST = 'localhost:9000';

    admin.initializeApp({
      credential: admin.credential.cert(require('./serviceAccount.json'))
    });
  }

  async doPopulate() {
    let fs = admin.firestore();
    let au = admin.auth();

    let userRecord = await au.createUser({
      email: 'testuser@test.com',
      emailVerified: true,
      phoneNumber: '+11234567890',
      password: '123456',
      displayName: 'Test User',
      photoURL: 'http://www.example.com/12345678/photo.png',
      disabled: false
    });

    let newUser: Partial<UserModel> = {
      app_version: 0.93,
      created_by: 'testuser@test.com',
      created_on: Timestamp.now(),
      currentSheetKey: '',
      email: 'testuser@test.com',
      email_verified: true,
      firebase_id: userRecord.uid,
      has_user_logged_in_before: true,
      is_manager_coach_user_existence_checked: true,
      is_sending_mails_allowed: true,
      privacy_policy_approval_date: Timestamp.now(),
      provider_string: 'email',
      updated_by: 'testuser@test.com',
      updated_on: Timestamp.now()
    };

    await fs.doc('users/testuser@test.com').set(newUser);

    await admin.database().ref('/').set({
      app_version: 0.93,
      data: {
        version: 1
      }
    });
  }
}

async function asyncMain() {
  let populateLauncher = new PopulateLauncher();
  await populateLauncher.doPopulate();
}

asyncMain().then(() => {
  console.log('population done');
  process.exit(0);
});
```

### [REQUIRED] Steps to reproduce

if I run this code with ts-node, then it throws the error:
Error: Can't determine Firebase Database URL.
So the firestore & auth call go correctly to the emulator and create the document & user object; but the call to the real-time database emulator fails.

### [REQUIRED] Expected behavior

that the call would succeed.

**Comment by mothershipper** [comment]
I struggled with this for so long, finally figured it out. Just provide any db url and it will get overridden to the emulator:

```typescript
 admin.initializeApp({
      credential: admin.credential.cert(require('./serviceAccount.json')),
      databaseURL: 'https://some-project.firebase.io',
 });
```

**Comment by mothershipper** [comment]
This issue was the "aha" moment for me.

https://github.com/firebase/firebase-admin-node/issues/1096

**Comment by LanderBeeuwsaert** [comment]
@mothershipper 
works like a charm. Thanks!

**Comment by syonip** [comment]
Indeed as @mothershipper said, databaseURL field has to be sent.
This means that the documentation here is erroneous, it states that only projectId has to be sent:
https://firebase.google.com/docs/emulator-suite/connect_rtdb#admin_sdks

**Comment by stansotn** [comment]
The @mothershipper solution worked like a charm, spent a day searching for this.. The funny part is if I set `databaseURL: "localhost:9000"` in `admin.initializeApp` it stops working. The only plausible configuration is to set the environmental variable `export FIREBASE_DATABASE_EMULATOR_HOST="localhost:9000"` and `databaseURL` to a random valid-looking url. This should be mentioned in the emulators documentation!
