### ISSUE TITLE
Cannot update Firebase CLI tools

### ISSUE THREAD

**Issue by chrisjacobs91** [firebase/firebase-tools#2853]
### [REQUIRED] Environment info

Firebase CLI version 8.7.0 (cannot update beyond this)

**firebase-tools:**

**Platform:** macOS

### [REQUIRED] Test case

After updating firebase tools, firebase --version returns the old version (it does not update)

### [REQUIRED] Steps to reproduce

- firebase --version
- npm install -g firebase-tools
- firebase --version

### [REQUIRED] Expected behavior

Firebase CLI updates to latest version

### [REQUIRED] Actual behavior

I am using npm install -g firebase-tools to update my Firebase CLI on MacOS.

It runs with the following log:

```
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
/Users/cj/.npm-global/bin/firebase -> /Users/cj/.npm-global/lib/node_modules/firebase-tools/lib/bin/firebase.js
+ firebase-tools@8.16.2
updated 1 package in 26.937s
```
However when I use firebase --version I get the same old version (8.7.0). I have tried restarting the terminal and machine.

Based on the reply to a post from 4 years ago (firebase version is not updating through [npm install -g firebase-tools](https://stackoverflow.com/questions/38781189/firebase-version-is-not-updating-through-npm-install-g-firebase-tools) I added this script to my package.json

`"which": "firebase -V && which firebase"`
Running this gave me v8.7.0 and the following path: `/usr/local/bin/firebase`

This path is a shortcut to a file 'firebase.js'. When I open this file, it's located at `usr/local/lib/node_modules/firebase-tools/lib/bin/firebase.js`

When I move up to: `/usr/local/lib/node_modules/firebase-tools` At this path there is a firebase module and the package.json says the version is 8.7.0.

However, at the path referenced in the npm install log `/Users/cj/.npm-global/lib/node_modules/firebase-tools/lib/bin/firebase.js` there is a similar module and the package.json says the version is 8.16.2.

I have tried deleting both folders and then rerunning the npm install. However despite the install seeming to be successful and creating a folder in `/Users/cj/.npm-global/lib/node_modules/` when I run firebase --version I get the error `command firebase not found.`

I've tried changing that firebase.js alias `(usr/local/lib/node_modules/firebase-tools/lib/bin/firebase.js)` to point to the up to date firebase in `/Users/cj/.npm-global`

But now when I run firebase --version I get

```
cj@Chriss-MBP firebase % firebase --version
zsh: permission denied: firebase
```

I'm not sure why I have two versions of firebase / NPM and why one gets updated and the other seems to get used :/

**Comment by samtstern** [comment]
@chrisjacobs91 sounds like you've got a somewhat wacky node setup on your machine, and this is not a bug in the Firebase CLI in particular but rather you have competing Node modules on your `$PATH`.  Two suggestions:

1. Use `nvm` to install `node` and manage your path: https://github.com/nvm-sh/nvm
2. If you can't get it sorted, use one of the standalone Firebase CLI installation methods which don't require Node: https://firebase.google.com/docs/cli

**Comment by chrisjacobs91** [comment]
Thanks @samtstern I have now uninstalled as much as I can and reinstalled npm via nvm. 

I have managed to install firebase tools and it's up to date!

however...

when I use macOS terminal and navigate to my dev directory, firebase -Version returns correctly.

but in vs code terminal, the same command in the same directory doesn't work. 

Please could you help me with this?

### VS Code
<img width="400" alt="Screenshot 2020-11-23 at 19 02 45" src="https://user-images.githubusercontent.com/25010842/100004469-74696600-2dbf-11eb-8e82-62461b996042.png">

### macOS Terminal
<img width="430" alt="Screenshot 2020-11-23 at 19 02 53" src="https://user-images.githubusercontent.com/25010842/100004473-759a9300-2dbf-11eb-9627-56b462ab2981.png">

**Comment by samtstern** [comment]
@chrisjacobs91 that is very strange!  I hope you can understand though that there's really nothing I can do to help, VSCode is outside of our control :-/

**Comment by chrisjacobs91** [comment]
Thanks for your patience @samtstern turns out I need to initialise nvm in each console separately. Seems to be all working now and I am FINALLY running on firebase 8.16 🙌

**Comment by alex-drocks** [comment]
I also could not update firebase-tools with npm i -g firebase-tools.

Seems like nvm is the cause. I was stuck on an old version of firebase-tools no matter if I was using the npm i -g command.
I uninstalled my nvm node.js version out of curiosity and it also cleaned my global node_modules where the outdated firebase cli was stored. Now it's working.
