### ISSUE TITLE
Functions emulator uses prod auth on updateUser call

### ISSUE THREAD

**Issue by gfpacheco** [firebase/firebase-tools#2854]
### [REQUIRED] Environment info

**firebase-tools: 8.16.2**

**Platform: macOS**

### [REQUIRED] Test case

Using the emulators I was able to connect the app to auth, firestore and functions emulator.
But when one of the functions call `functions.app.admin.auth().updateUser(...)` it tries to update a user in the production firebase.

### [REQUIRED] Steps to reproduce

- Start the emulators
- Create an user
- Call a function that updates that user

### [REQUIRED] Expected behavior

User from auth emulator is updated

### [REQUIRED] Actual behavior

Call fails because user is not found in production auth

**Comment by samtstern** [comment]
@gfpacheco thanks for reporting. I have two questions:

- What version of `firebase-admin` are you using?  Please use `9.4.0` or higher as `9.3.0` had a bug with connecting to the auth emulator.
- Does the behavior differ if you use `firebase-admin` directly instead of `functions.app`?  Ex:

```js
const admin = require('firebase-admin');
admin.initializeApp();

const auth = admin.auth();
```

**Comment by gfpacheco** [comment]
I was already using 9.4.1, but when I tried a second time it worked, so my guess is this was related to #2749 and I had restarted the emulators somehow.

I guess the auth emulator is not really useful to us until that feature is available.

BTW, thanks for the quick reply!
