### ISSUE TITLE
Firebase commands do not work

### ISSUE THREAD

**Issue by Frostyanimations126** [firebase/firebase-tools#2855]
![image](https://user-images.githubusercontent.com/39423395/99993405-9f36c880-2d85-11eb-8645-2af62c26540c.png)I installed it yesterday

**Comment by samtstern** [comment]
@Frostyanimations126 looks similar to https://github.com/firebase/firebase-tools/issues/1684 which has been reported as solved.  A screenshot is not enough information to debug this, please provide all of the system information and logs required by the issue template if you think there is a regression.
