### ISSUE TITLE
Error: Could not start Database Emulator, port taken.

### ISSUE THREAD

**Issue by khansiddique** [firebase/firebase-tools#2856]
**First question:** I can not setup new Emulators port and project. I can not open other staff like real time database. That means the "firebase emulators:start" command not work for me.

```
i  emulators: Starting emulators: auth, functions, firestore, database, hosting, pubsub
!  functions: The functions emulator is configured but there is no functions source directory. Have you run firebase init functions?
!  firestore: Did not find a Cloud Firestore rules file specified in a firebase.json config file.
!  firestore: The emulator will default to allowing all reads and writes. Learn more about this option: https://firebase.google.com/docs/emulator-suite/install_and_configure#security_rules_configuration.
i  firestore: Firestore Emulator logging to firestore-debug.log
i  emulators: Shutting down emulators.
i  firestore: Stopping Firestore Emulator
!  Firestore Emulator has exited upon receiving signal: SIGINT
i  hub: Stopping emulator hub
!  database: Port 9000 is not open on localhost, could not start Database Emulator.
!  database: To select a different host/port, specify that host/port in a firebase.json config file:
      {
        // ...
        "emulators": {
          "database": {
            "host": "HOST",
            "port": "PORT"
          }
        }
      }
i  emulators: Shutting down emulators.

Error: Could not start Database Emulator, port taken.
```

**Second question:** I can not  setup new emulator. What should I do? I always get following results for command "firebase init"

```
=== Emulators Setup
? Which Firebase emulators do you want to set up? Press Space to select emulators, then Enter to confirm your choices. (Press <space> to select, <a> to toggle all, <i> to i
nvert selection)Authentication Emulator, Functions Emulator, Firestore Emulator, Database Emulator, Hosting Emulator, Pub/Sub Emulator
i  Port for auth already configured: 9099
i  Port for functions already configured: 5001
i  Port for firestore already configured: 8080
i  Port for database already configured: 9000
i  Port for hosting already configured: 5000
i  Port for pubsub already configured: 8085
i  Emulator UI already enabled with port: (automatic)
? Would you like to download the emulators now? No
```

**Comment by yuchenshi** [comment]
Hi! If you have something else running on Port 9000, try setting up a different port in `firebase.json`.

For your second question -- I believe you already have all emulators enabled. Is there something else you're looking for?

**Comment by LanderBeeuwsaert** [comment]
I use https://www.npmjs.com/package/kill-port before starting the emulator ; works like a charm

**Comment by nico75005** [comment]
Assuming you use a shell like bash for example, just do 
```
lsof -ti tcp:9000 | xargs kill -9
```

You port might be used due to a previous stop of the emulator in a wrong way.

**Comment by MalikOwais123** [comment]
> I use https://www.npmjs.com/package/kill-port before starting the emulator ; works like a charm

Thanks..

**Comment by arvindpdmn** [comment]
Why is this issue closed? It's a bug in Firebase database emulator. When closing, the emulator doesn't release the port. See log (it may not help):

```
i  emulators: Received SIGINT (Ctrl-C) for the first time. Starting a clean shutdown.
i  emulators: Please wait for a clean shutdown or send the SIGINT (Ctrl-C) signal again to stop right now.
i  emulators: Shutting down emulators.
i  ui: Stopping Emulator UI
!  Emulator UI has exited upon receiving signal: SIGINT
i  hosting: Stopping Hosting Emulator
i  database: Stopping Database Emulator
!  Database Emulator has exited upon receiving signal: SIGINT
i  hub: Stopping emulator hub
i  logging: Stopping Logging Emulator
```

**Comment by arvindpdmn** [comment]
> You port might be used due to a previous stop of the emulator in a wrong way.
What's the correct way to stop the emulator? I've been doing Ctrl-C.

**Comment by faizananwerali** [comment]
> > I use https://www.npmjs.com/package/kill-port before starting the emulator ; works like a charm
> 
> Thanks..

This is the command I use after installing kill-port

`kill-port --port 8000,9099,5001,8080,9000,5000,8085,9199,4000,4400,4500 && firebase emulators:start --project default`

**Comment by alessioforti** [comment]
Emulators should shut down ports not only when you shut down, but even when they crashes, they won't come up again otherwise.

While we wait this to be addressed, as said above, using kill-port worked like a charm.

A useful shortcut could be adding a script to package.json to kill the ports and restart:

`"restart-emulators": "npx kill-port --port 8000,9099,5001,8080 && firebase emulators:start"`

**Comment by joshdance** [comment]
A tip for rookies like me who find this in the future.

If you are using Live Server in VS Code, it takes port 5000. 

So you can open `firebase.json` and add specify a new port. I chose 6000.

```
  "emulators": {
    "hosting": {
      "host": "localhost",
      "port": "6000"
    }
  },
```

**Comment by arvindpdmn** [comment]
This is no longer a problem with latest Firebase. A new Java window opens. If this is closed, the port is released.

**Comment by srtager555** [comment]
> Assuming you use a shell like bash for example, just do
> 
> ```
> lsof -ti tcp:9000 | xargs kill -9
> ```
> 
> You port might be used due to a previous stop of the emulator in a wrong way.

Yeah, this command works without problems but I think that is better use the -15 before than the -9, because kill immediately the emulator can have problems. right?

https://www.cyberciti.biz/faq/unix-kill-command-examples/
