### ISSUE TITLE
Allow `--quiet` flag for `emulators:start`

### ISSUE THREAD

**Issue by kentcdodds** [firebase/firebase-tools#2859]
### [REQUIRED] Environment info

**firebase-tools:** 8.16.2 (latest)

**Platform:** macOS

### [REQUIRED] Test case

Literally anywhere, but sure you can use this: https://github.com/kentcdodds/elaborate

### [REQUIRED] Steps to reproduce

1. Run `firebase emulators:start`
2. Notice there's a ton of output, much of it is not useful
3. Dig through the firebase-tools code and find [this handy option](https://github.com/firebase/firebase-tools/blob/efd20bf8ea15037804b9e6ce2c2b876b94895ed8/src/emulator/functionsEmulator.ts#L134)
4. Try to enable it with `firebase emulators:start --quiet`
5. Notice the `error: unknown option '--quiet'` output
6. Try adding the option [here](https://github.com/firebase/firebase-tools/blob/efd20bf8ea15037804b9e6ce2c2b876b94895ed8/src/index.js#L21)
7. Run `firebase emulators:start --quiet` again
8. Notice that you no longer get the error, but `this.args.quiet` is still `undefined` in `functionsEmulator.js` so that doesn't work either.
9. Discover [emulators-startts](https://github.com/firebase/firebase-tools/blob/efd20bf8ea15037804b9e6ce2c2b876b94895ed8/src/commands/emulators-start.ts#L24) and try a few things but ultimately give up.

### [REQUIRED] Expected behavior

I want to be able to silence most of the output when I start my firebase function.

### [REQUIRED] Actual behavior

Instead, I get a bunch of output that hides output from my functions:

<img width="800" alt="Screen Shot 2020-11-23 at 4 41 06 PM" src="https://user-images.githubusercontent.com/1500684/100027786-b89e3b80-2daa-11eb-97ab-111c3d65cb2d.png">

Can you find my own logs? After a bit of time looking for them, so can I:

```
>  getting post with ID xbxfZqu5gXN5QyhcfmGk
```

I'd much rather not have to search through all that output, which is why I'd like to have this `--quiet` option. Or perhaps a `--loglevel` option or something. I just need a way to silence the firebase logs.

**Comment by samtstern** [comment]
@kentcdodds thanks for the feedback.  There has already been quite a lot of discussion about the emulators logging here:
https://github.com/firebase/firebase-tools/issues/1839

While we do agree that they're a bit noisy, it doesn't seem like we're going to be able to reach consensus about *which* logs need to be quieted.  Every log line has a few fans.

One way we're trying to address this is through the Emulators UI "Logging" tab which allows you to add custom filters for different types of logs and their content.  Have you tried that?

**Comment by kentcdodds** [comment]
Thanks for the info @samtstern,

I don't want to use the UI, I like seeing the logs in the terminal (I have other processes I'm running concurrently and like to see their logs as well).

Could we not start with a way to quiet *all* logs? Then things could become more granular from there.

**Comment by samtstern** [comment]
@kentcdodds that's a reasonable request, just want to clarify:

- Do you want your user logs from within Functions to be excluded?
- Do you want the initial startup logs (the table with the ports and such)?
- What about error-level logs?

**Comment by kentcdodds** [comment]
> - Do you want your user logs from within Functions to be excluded?

No, the pain point I'm feeling right now is that it's difficult for me to find my own logs in the sea of emulator logs. So I want only my logs to be shown when I enable `--quiet`

> - Do you want the initial startup logs (the table with the ports and such)?

I'm fine either way. Doesn't conflict with my desire to see my own function logs. I'd personally prefer something less huge during `--quiet` mode, but it's not a big deal. I just want to see my own logs.

> - What about error-level logs?

I think if error-level logs were hidden, then folks would be worried about missing important errors and wouldn't use `--quiet`, so those are probably good to keep included.

**Comment by exKAZUu** [comment]
@samtstern As another use case, we'd like to make `firebase emulators:exec` silent (by default).

When we use the `package.json` including the following content, the exit code of `yarn test` always return 0. So this mean we cannot detect a test failure.

```
  "scripts": {
    "test": "firebase emulators:exec --project edu-robot-apps-staging \"exit -1\" | grep -v \"hosting:\""
  },
```

on Mac OS with the following environment: 

```
$ node --version
v14.16.1
$ yarn --version
1.22.10
$ yarn firebase --version
9.9.0
```

**Comment by exKAZUu** [comment]
hm, I solved the issue by appending `set -o pipefail` to the head of the command.

**Comment by spicemix** [comment]
...and becomes quite a problem when load testing with `artillery`.

(Why load test on an emulator? To see how things work with the scenario before having to pay for it!)

I would like it for `:exec` as well as `:start` for CI use thanks!

**Comment by JasperSurmont** [comment]
Is there any progress in allowing us to use a `--quiet` flag to disable all emulator logs?

**Comment by nitaigao** [comment]
Yup, any progress, ideally would prefer to see zero log output from the emulators when running unit tests

**Comment by yuchenshi** [comment]
Hi, thanks for filing this feature request! We are unable to promise any timeline for this, but if others also have this request, adding a +1 on this issue can help us prioritize adding this to the roadmap.

(Googler-only internal tracking bug: b/194801987)

**Comment by spicemix** [comment]
If you're paying $200 for focus group participation on this feature please let me know

**Comment by mteece** [comment]
+1

**Comment by rorito** [comment]
+1

**Comment by hernantz** [comment]
We are facing this problem when running integration tests with the emulator, the output is kinda verbose, something like `--quiet` or `-vvvv` for output tuning would be helpful, right now the alternative is to filter using a grep pipe (`| grep`).

**Comment by eowo** [comment]
+1 
Hi! Can we have some update for this issue? Thx!

**Comment by yuchenshi** [comment]
Instead of combing through the lines on the CLI or using `grep`, an alternative is to use the Emulator UI Log Viewer, which allows advanced filtering and search. You can also filter on log levels. See: https://firebase.google.com/docs/reference/emulator-suite

**Comment by spicemix** [comment]
You ought to assign b/194801987 to a summer student. I'd think they'd be able to handle it.

**Comment by nicholasstephan** [comment]
There seem to be a number of issues around this issue, all are "closed" but I don't see any solutions. Is there any way yet to silence logs? 

Just my 2c: it seems sensible to silence the stdout emulator logs when using `firebase emulators:exec`, and only show logs from the executed command. The use case given in the documentation for `emulators:exec` is to run tests, but all the emulator logs make the test results almost impossible to read.

**Comment by and3rson** [comment]
Any updates? The functions are so noisy it's hard to filter any meaningful output from actual code.

**Comment by and3rson** [comment]
Bump? We're currently piping all output to `/dev/null`, which is ugly and hides possible important errors. What about a simple `--loglevel` CLI arg?

**Comment by ZacharyBohn** [comment]
@yuchenshi Can we re-open this please?  Or at least explain why it was closed?

**Comment by developomp** [comment]
@yuchenshi This issue has been closed prematurely and without a proper solution. Please reopen it.

**Comment by ecam900** [comment]
![image](https://github.com/firebase/firebase-tools/assets/15877592/1d28b51c-b6e4-49fe-91ea-35ae207f2a62)

I wish we could suppress these logs in the firebase configuration file - or at least via a command flag during starting the emulators. It clutters our CI logs in a non-meaningful way.

**Comment by christhompsongoogle** [comment]
Setting verbosity via flag: https://github.com/firebase/firebase-tools/pull/6429

**Comment by lox** [comment]
Has anyone actually been able to get this to work? I'm running `12.8.1` with the following:

```
firebase emulators:exec --project patientnot --log-verbosity SILENT 'npm run test:system'
```

I still get all the log spam:

```
  services/organization
    create
i  functions: Loaded environment variables from .env.dev.
i  functions: Beginning execution of "australia-southeast1-auth-onUserCreate"
>  info: Created userMeta for testOwner {}
i  functions: Finished "australia-southeast1-auth-onUserCreate" in 58.244959ms
      ✔ should create a new organization with valid inputs (1275ms)
i  functions: Beginning execution of "australia-southeast1-auth-onUserCreate"
>  info: Created userMeta for testOwner {}
i  functions: Finished "australia-southeast1-auth-onUserCreate" in 5.904875ms
      ✔ should throw a ValidationError when the user is already part of an organization (39ms)
i  functions: Beginning execution of "australia-southeast1-auth-onUserCreate"
>  info: Created userMeta for testOwner {}
i  functions: Finished "australia-southeast1-auth-onUserCreate" in 4.433375ms
      ✔ should throw a ValidationError when the user has not verified their email address
i  functions: Beginning execution of "australia-southeast1-auth-onUserCreate"
>  info: Created userMeta for testOwner {}
i  functions: Finished "australia-southeast1-auth-onUserCreate" in 5.289625ms
```

**Comment by ecam900** [comment]
Similar to @lox  - I also still get log spam, on version `12.8.1`:

![image](https://github.com/firebase/firebase-tools/assets/15877592/27ba19ba-348b-4c96-b32d-920946f86b00)

My command:

![image](https://github.com/firebase/firebase-tools/assets/15877592/31abcdd5-2ffd-4390-8b10-2521484ec773)

**Comment by joehan** [comment]
Looks like we may have missed a spot for piping through the new `--log-vebosity` flag to the functions emualtor. Going to take a look today and try to get a fix out in the next patch release.

**Comment by steveobd** [comment]
+1

**Comment by risalfajar** [comment]
Please update the docs about this:
https://firebase.google.com/docs/emulator-suite/install_and_configure#startup
