### ISSUE TITLE
Unsetting config (feature request/question)

### ISSUE THREAD

**Issue by ahaverty** [firebase/firebase-tools#286]
Hi Firebase,
I tried `firebase functions:config:unset` thinking it would unset everything in one shot, but it seems it needs an argument. I tried unsetting all root keys in one command `firebase functions:config:unset root1 root2 root3` but it seemed to only unset `root1` with no warning that it didn't unset `root2` or `root3`
Minor issue, but thought it was worth mentioning as a feature request/ documentation 👍
Thanks

**Comment by mbleigh** [comment]
Hmm, at the very least you should be able to unset multiple keys at once. @laurenzlong can you take a look? We may be doing a variadic/comma-separated mixup again.

**Comment by ahaverty** [comment]
Just to chip in as a clumsy user, my initial instinct `firebase functions:config:unset` might be a little dangerous unless it comes with some kind of confirm message. A message documenting that multiple unsetting root's is possible is prob best like you said @mbleigh

**Comment by hariprasadiit** [comment]
Firebase docs mention that we can unset multiple keys at once. but it's not working for me.

**Comment by laurenzlong** [comment]
Thanks for filing, it does work, but the keys have to be comma separated (no spaces in between)

```
firebase functions:config:unset root1,root2,root3
```

I filed a fix for the documentation, should be updated in the next day or two.
