### ISSUE TITLE
Cannot use Firestore emulator with localhost web hosting

### ISSUE THREAD

**Issue by chrisjacobs91** [firebase/firebase-tools#2861]
### [REQUIRED] Environment info

**firebase-tools:** 8.16.2

**Platform:** macOS

### [REQUIRED] Test case

I have the following code in the .js file for my webpage:
```
const db = firebase.firestore();
if (location.hostname === "localhost") {
  db.useEmulator("localhost", 8080);
}
```

I get the following console error: `TypeError: db.useEmulator is not a function. (In 'db.useEmulator("localhost", 8080)', 'db.useEmulator' is undefined)`

### [REQUIRED] Steps to reproduce

firebase emulators:start
open http://localhost:8080
console error: `TypeError: db.useEmulator is not a function. (In 'db.useEmulator("localhost", 8080)', 'db.useEmulator' is undefined)`

### [REQUIRED] Expected behavior

Expect firebase to load correctly, pointing to the emulated firestore instance

### [REQUIRED] Actual behavior

console error: `TypeError: db.useEmulator is not a function. (In 'db.useEmulator("localhost", 8080)', 'db.useEmulator' is undefined)`

**Comment by samtstern** [comment]
@chrisjacobs91 are you using Firebase JS SDK `8.0.0` or higher?  `useEmulator` is fairly new:
https://firebase.google.com/support/release-notes/js#realtime-database_2

**Comment by chrisjacobs91** [comment]
sorry @samtstern I thought I was just updating the CLI. All good thank you!
