### ISSUE TITLE
Cannot parse function triggers when using firebase-tools as a module and inspecting the script

### ISSUE THREAD

**Issue by rhodgkins** [firebase/firebase-tools#2865]
I've not used `require('firebase-tools').deploy()` directly to simplify things, but it is reproducible with that and the various `firebase.json` files...

```js
require('firebase-tools/lib/parseTriggers')('blah', '.', {}, {}).then(triggers => {
   console.info(triggers)
}, err => {
   console.error(err)
})
```

If you run the above script as `node script.js` the following is outputted, which makes sense because there's nothing to parse:

```
{ FirebaseError: Error occurred while parsing your function triggers. Please ensure that index.js only exports cloud functions.


    at ChildProcess.<anonymous> (/<snip>/node_modules/firebase-tools/lib/parseTriggers.js:27:24)
    at ChildProcess.emit (events.js:198:13)
    at ChildProcess.EventEmitter.emit (domain.js:448:20)
    at emit (internal/child_process.js:832:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  name: 'FirebaseError',
  children: [],
  context: undefined,
  exit: 1,
  message:
   'Error occurred while parsing your function triggers. Please ensure that index.js only exports cloud functions.\n\n',
  original: undefined,
  status: 500 }
```

However if you try to debug the script - running as `node --inspect-brk=23423 script.js`, the error changes to:

```
{ FirebaseError: There was an unknown problem while trying to parse function triggers. Please ensure you are using Node.js v6 or greater.
    at ChildProcess.<anonymous> (/<snip>/node_modules/firebase-tools/lib/parseTriggers.js:32:24)
    at ChildProcess.emit (events.js:198:13)
    at ChildProcess.EventEmitter.emit (domain.js:448:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
  name: 'FirebaseError',
  children: [],
  context: undefined,
  exit: 2,
  message:
   'There was an unknown problem while trying to parse function triggers. Please ensure you are using Node.js v6 or greater.',
  original: undefined,
  status: 500 }
```

The exit code of the `./triggerParser.js` fork is 12.

I've tracked this down to this line:

https://github.com/firebase/firebase-tools/blob/0cf70a09849aa5246c5165bf81cd14d2fcb025aa/src/parseTriggers.js#L31

Its because [fork uses the same `execArg` as the calling process](https://nodejs.org/api/child_process.html#child_process_child_process_fork_modulepath_args_options), so the `--inspect=23423` flag is being parsed to that and after getting the output the error is: `Starting inspector on 127.0.0.1:23423 failed: address already in use` because the parent process is already using that port.

I've managed to get around this by just setting empty `execArg` on the above line, but that drops other possible node args? Does that matter? Happy to do a PR if it doesn't!

**Comment by samtstern** [comment]
@rhodgkins as you can probably guess we don't consider `/lib/parseTriggers` or anything else in `/lib/` to be part of the public API of this package, so I'm not really surprised that it broke when you tried to use it programatically.  I would not rely on this stuff!  For instance I was fixing a bug today and was considering deleting/replacing `parseTriggers` entirely.

That said I am fine if you want to send a PR to explicitly drop `--inspect` and `--inspect-brk` from the forked `execArgs`, there's no harm in that.  But make sure you add a comment explaining why and also preserve any other args that may be in there.

**Comment by rhodgkins** [comment]
@samtstern sorry I should have added more info...!

>I've not used require('firebase-tools').deploy() directly to simplify things

By this I meant in the repro steps - I'm actually using firebase-tools [as a module](https://github.com/firebase/firebase-tools#using-as-a-module) calling `firebaseTools.deploy` (which eventually calls `/lib/parseTriggers`) in a script and was running into problems when debugging that script due to the above.

Shall look into a PR though - thanks.

**Comment by samtstern** [comment]
@rhodgkins ah ok `deploy` is part of the API so that makes more sense, thanks for explaining!
