### ISSUE TITLE
Pubsub cron emulation doesn't run

### ISSUE THREAD

**Issue by quantuminformation** [firebase/firebase-tools#2866]
### [REQUIRED] Environment info

tools: 8.16.2

**firebase-tools:**

macOS
### [REQUIRED] Test case

part of large project
### [REQUIRED] Steps to reproduce
`firebase emulators:start --only database,functions,pubsub  --inspect-functions   --import=./seed --export-on-exit`

```js
export const scheduledFunctionCrontab = functions.pubsub
    .schedule("* * * * *")
    .timeZone("Europe/London") // Users can choose timezone - default is America/Los_Angeles
    .onRun(async (context) => {
        debugger
        let ref = await admin.database().ref(`mentorCategoryHistory`).once("value")
```

### [REQUIRED] Expected behavior
Function to run every minute and hit the break point
### [REQUIRED] Actual behavior

I tried the following but I don't see the function run every minute or hit the breakpoint, I get this on console:

![image](https://user-images.githubusercontent.com/216566/100260977-6b58d000-2f4a-11eb-8ea7-4078773be8c8.png)
not sure if this helps:

![image](https://user-images.githubusercontent.com/216566/100261222-b7a41000-2f4a-11eb-8521-28029d333573.png)

**Comment by samtstern** [comment]
@quantuminformation scheduled functions don't run on schedule in the emulator, see https://github.com/firebase/firebase-tools/issues/2034

**Comment by dobromyslov** [comment]
@samtstern is there any feature request for this to be implemented in the emulators suite? 

Don't you agree that simple setInterval() scheduler would be awesome to get out of the box with the emulators suite?
