### ISSUE TITLE
[auth:import] Sync users all

### ISSUE THREAD

**Issue by koooge** [firebase/firebase-tools#2869]
Hi there,
I would like to make a copy of Firebase Auth's data in production to a test environment from time to time. `firebase auth:export & auth:import` is mostly useful to make such a test env, but `firebase auth:import` just imports it from json/csv. It does not delete existing data.
So, `auth:import` would be perfect to have kind of ` --delete` or `--sync` option.

I wonder if I should post this to https://firebase.google.com/support/contact/bugs-features/. 🤔

**Comment by samtstern** [comment]
@koooge yes this is best filed through the support feature request page (which you linked) because it would require a backend change not only a change in the Firebase CLI.

Thank you for the feedback!

**Comment by koooge** [comment]
Firebase Support response:

```
I see that you want to have a feature that would let you delete the existing data when using the auth:import command as well as to its own sync option. As an action, I've raised your request to our engineering team, and this will be evaluated for consideration. However, I cannot guarantee when this feature will be officially rolled out. For now, you may keep an eye out on our Firebase blog or release notes for any latest news or new features that we may have.

Should you have other Firebase-specific questions or want to request a new feature, please let us know through our support channel.
```

**Comment by samtstern** [comment]
@koooge sounds like it's filed with the right people, thank you for the feedback!

**Comment by fringley** [comment]
This would be a very helpful feature.  Does anyone know if firebase has made any updates to this feature request?
