### ISSUE TITLE
Unexpected error when invalid `functions` property used in `firebase.json`

### ISSUE THREAD

**Issue by jwngr** [firebase/firebase-tools#287]
**Version:** `3.5.0`

**Repro steps:**
1. Create a `firebase.json` that looks like this:
```
{
  "functions": {
    "foo": "foo"
  }
}
```
2. Run `firebase deploy`

**Expected:**
An error saying the `functions` property is invalid.

**Actual:**
```
=== Deploying to 'jwngr-functions-test'...

i  deploying functions

Error: An unexpected error has occurred.
```

**Comment by kevinajian** [comment]
This has been resolved.
