### ISSUE TITLE
Storage Rules Deployments Timeline in the Firebase Console

### ISSUE THREAD

**Issue by b3of** [firebase/firebase-tools#2871]
### [REQUIRED] Environment info

**firebase-tools:** 8.16.2

**Platform:** Windows 10

### [REQUIRED] Test case

Why there is no timeline of the deployments for the Storage Rules.

What I mean by a timeline is the one we see for the Firestore Rules in the left panel and above the Playground whenever a Firestore Rules get deployed/published

### [REQUIRED] Steps to reproduce

Deploy/Publish Storage Rules
### [REQUIRED] Expected behavior

Expected to see the same Firestore Rules deployments timeline 
### [REQUIRED] Actual behavior

I don't see a timeline for Storage Rules deployments

**Comment by samtstern** [comment]
@b3of this repo is for the Firebase CLI only. To file general Firebase feature requests, use this form:
https://firebase.google.com/support/troubleshooter/report
