### ISSUE TITLE
Is there a way to enable authentication with firebase tools?

### ISSUE THREAD

**Issue by Shaita-KrZ** [firebase/firebase-tools#2872]
Hi there,

Is there a way to enable Email/Passowrd and/or Facebook authentication with firebase tools? 
I found I can import users using auth:import but if i do not enable authentication, there's no way users could log in. 

When I create a new firebase project, I'd like to enable authentication without going to the Firebase console.

Regards.

**Comment by samtstern** [comment]
@Shaita-KrZ there's no way to do this through the CLI right now because the backend APIs are incomplete.  You can enable some of the IDP (Identity Provider) configurations through this REST API:
https://cloud.google.com/identity-platform/docs/reference/rest/v2/projects.defaultSupportedIdpConfigs

**Comment by Shaita-KrZ** [comment]
Hi there,

Thank you for your reply. I'm having trouble authenticating to this API. I don't know which kind of API key they expect.

They might expect the firebase project service account private key which by the way I was wondering if it were possible to get with firebase tools? Again the goal is to have my full process automated.

Thank you so much for the help.

**Comment by samtstern** [comment]
@Shaita-KrZ yeah that is quite confusing.  I think you will want to authenticate as either yourself or a service account and pass a token:
https://cloud.google.com/sdk/gcloud/reference/auth/application-default/print-access-token

**Comment by Shaita-KrZ** [comment]
@samtstern 

After checking how firebase tools handle authentication, I thought I could take advantage of the firebase login:ci command to get my famous access token (the process looked similar to the documentation). However, this did not work... This would have been amazing for my automation. I am not sure why it does not work.

Anyway, surprisingly your solutions worked perfectly !! The problem now is that I still need to find a way to get the service account file in an automated way. May you know if there's a way to retrieve the service account file (private key) outside of the firebase console?

Thanks for the help!

**Comment by samtstern** [comment]
@Shaita-KrZ sorry I don't know how to automate that and I don't think you should.  The idea is you download it once manually and keep it somewhere safe.

**Comment by samtstern** [comment]
I'm going to close this issue for now, I hope you were able to find a workaround using the REST APIs!  We're looking at adding some auth stuff to the Firebase CLI but this isn't the best place to track it since it's very early stages.
