### ISSUE TITLE
`firebase deploy --only hosting` does not fail if `package.json` does not contain `hosting` key

### ISSUE THREAD

**Issue by jwngr** [firebase/firebase-tools#288]
**Version:** `3.5.0`

**Repro steps:**
1. Create a `firebase.json` that is empty (that is, it is just an empty object `{}`).
2. Run `firebase deploy --only hosting`.

**Expected:**
An error saying the `hosting` property is missing.

**Actual:**
```
=== Deploying to 'jwngr-functions-test'...

i  deploying 
i  starting release process (may take several minutes)...

✔  Deploy complete!

Project Console: https://console.firebase.google.com/project/jwngr-functions-test/overview
```

**Comment by mbleigh** [comment]
Fixed by https://github.com/firebase/firebase-tools/pull/295
