### ISSUE TITLE
Error emulating the method generateEmailVerificationLink (auth emulator) - The provided ID token is not a valid Firebase ID token.

### ISSUE THREAD

**Issue by siarheidudko** [firebase/firebase-tools#2880]
### [REQUIRED] Environment info

**firebase-tools: 8.16.2**

**Platform: macOS Big Sur 11.0.1, Node.js 12.19.0**

### [REQUIRED] Test case

Error emulating the method `generateEmailVerificationLink`:
```FirebaseAuthError: There is no user record corresponding to the provided identifier.```

### [REQUIRED] Steps to reproduce

- Create User: ```admin.auth().createUser({email: 'test@test.com'});```
- Generate email verificaation link: ```admin.auth().generateEmailVerificationLink("test@test.com");```

### [REQUIRED] Expected behavior

Resolve string (url)

### [REQUIRED] Actual behavior

Reject with error: ```FirebaseAuthError: The provided ID token is not a valid Firebase ID token.```

**Comment by samtstern** [comment]
@siarheidudko I'm a bit confused, are you seeing `"There is no user record corresponding to the provided identifier."` or `"The provided ID token is not a valid Firebase ID token."`? Your issue mentions two different error messages.

Also can you give a little more context about how and where you run this code (including which version of the Admin SDK you're using) so that we can attempt to reproduce it?

**Comment by siarheidudko** [comment]
> @siarheidudko I'm a bit confused, are you seeing `"There is no user record corresponding to the provided identifier."` or `"The provided ID token is not a valid Firebase ID token."`? Your issue mentions two different error messages.
> 
> Also can you give a little more context about how and where you run this code (including which version of the Admin SDK you're using) so that we can attempt to reproduce it?

I made a mistake the first time. Correct error: `"The provided ID token is not a valid Firebase ID token."`
`"firebase-admin": "9.4.1"`

**Comment by samtstern** [comment]
@siarheidudko thank you I was able to reproduce this issue with this simple function:

```js
const functions = require("firebase-functions");
const admin = require("firebase-admin");
admin.initializeApp();

exports.testEmailLink = functions.https.onRequest(async (req, res) => {
  const email = `test${new Date().getTime()}@example.com`;

  console.log(`Creating user ${email}`);
  await admin.auth().createUser({ email: email });

  console.log(`Generating email link`);
  const link = await admin.auth().generateEmailVerificationLink(email);

  res.json({
    link: link
  });
});
```

Error:
```
⚠  functions: Error: The provided ID token is not a valid Firebase ID token.
    at FirebaseAuthError.FirebaseError [as constructor] (/private/var/folders/xl/6lkrzp7j07581mw8_4dlt3b000643s/T/tmp.dLn7PoLm/functions/node_modules/firebase-admin/lib/utils/error.js:43:28)
```

**Comment by TaylorFacen** [comment]
Following this because I'm getting the same error

**Comment by martijnplaat** [comment]
yes, I have the same problem as well.

**Comment by rosalyntan** [comment]
Filed b/175034284 for internal tracking.

**Comment by PawFV** [comment]
Same problem with auth emulators.

**Comment by yuchenshi** [comment]
Fixed in v8.20.0.

**Comment by SrBrahma** [comment]
I am getting it when calling `auth().getUser(uid)` sometimes.

**Comment by Ic3m4n34** [comment]
I'm having this issue with `9.3.0`
