### ISSUE TITLE
`firebase deploy` succeeds even if no `functions/` directory exists

### ISSUE THREAD

**Issue by jwngr** [firebase/firebase-tools#289]
**Version:** `3.5.0`

**Repro steps:**
1. Create a `firebase.json` that is empty (that is, it is just an empty object `{}`).
2. Make sure you don't have `functions/` directory.
2. Run `firebase deploy`.

**Expected:**
An error saying no `functions/` directory exists and that if you are using a custom directory, you can specify it via the `functions.hosting` property of your `firebase.json`.

**Actual:**
```
=== Deploying to 'jwngr-functions-test'...

i  deploying 

i  starting release process (may take several minutes)...

✔  Deploy complete!
```

This appears to be a no-op, and all existing Firebase Functions still exist after this "empty" deploy. So, no deploy is actually happening or else this would probably have deleted all my Functions, which would have been bad.

**Comment by mbleigh** [comment]
Fixed by https://github.com/firebase/firebase-tools/pull/295
