### ISSUE TITLE
False positive error while deploying functions

### ISSUE THREAD

**Issue by hiranya911** [firebase/firebase-tools#2892]
**firebase-tools:** 8.16.2

**Platform:** macOS

I encountered the following error multiple times while trying to deploy some functions:

```
$ firebase deploy --only functions
...
Functions deploy had errors with the following functions:
	


To try redeploying those functions, run:
    firebase deploy --only "functions:"


To continue deploying other features (such as database), run:
    firebase deploy --except functions

Error: Functions did not deploy properly.
```

In each case the functions were deployed successfully.

**Comment by samtstern** [comment]
@hiranya911 if you can still get this to happen can you run `firebase --debug deploy --only functions` so we can see the detailed logs?
