### ISSUE TITLE
deploy command with --only flag/option, unexpected behavior

### ISSUE THREAD

**Issue by muhammad-usman-anwar** [firebase/firebase-tools#2896]
### [REQUIRED] Environment info

**firebase-tools: 8.17.0**

**NodeJS: 14.15.1**
**Platform: Windows**

### [REQUIRED] Test case
I was trying to `deploy` the `hosting` using `--only` option, was resulting in __path__ related issue. When the path for hosting `public` was already set in __json__ file. Upon investigation found out that it was trying to check sdk version for  __functions__, since there was no `source` path was set so it was giving an __error__.

### [REQUIRED] Steps to reproduce

1. __firebase.json__ should have proper `hosting` config, `functions` config should be there but `source` is not set
2. run, `firebase deploy --only hosting`

### [REQUIRED] Expected behavior

Deploy command should only validate/execute functionality related to the given `--only` options

### [REQUIRED] Actual behavior

Deploy command is trying to validate `functions` option, when its not even provided to be deployed

**Comment by capripio** [comment]
Yup, it seems like firebase-tools overwrite config file, instead of appending it.

**Comment by samtstern** [comment]
@muhammad-usman-anwar thanks for reporting this, I don't quite understand the situation though. Could you give me a specific `firebase.json` example and then tell me what command to run to reproduce the error you're seeing?
