### ISSUE TITLE
publish-please@5.5.2 preinstall fails when updating to, or installing the latest version of firebase-tools (8.17.0) on OSX

### ISSUE THREAD

**Issue by Pushplaybang** [firebase/firebase-tools#2907]
### [REQUIRED] Environment info

attempting to update to the lastest version via npm as per the instructions:

```sh
                                                                                                   
   │                                          Update available 8.16.2 → 8.17.0                                           
   │                    To update to the latest version using npm, run npm install -g firebase-tools                     
   │   For other CLI management options, visit the CLI documentation (https://firebase.google.com/docs/cli#update-cli)   

```
v8.16.2 was working correctly.

**firebase-tools:**

macOS Catalina - 10.15.7
Node v12.20.0
NPM 6.14.8

### [REQUIRED] Test case

a test case cannot be provided, as this is an installation/update bug report.

### [REQUIRED] Steps to reproduce

attempt to install firebase tools with npm by running `npm install -g firebase-tools`

### [REQUIRED] Expected behavior

Successful installation, and availability of the firebase-tools, or should a failure in upgrading occur, the previous functioning version.

### [REQUIRED] Actual behavior

The installation fails with the following:

```sh
➜  firebase git:(feat/tags) ✗ npm remove -g firebase-cli && npm install -g firebase-tools
up to date in 0.032s
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
npm WARN deprecated har-validator@5.1.5: this library is no longer supported

> publish-please@5.5.2 preinstall /Users/paulvanzyl/.nvm/versions/node/v12.20.0/lib/node_modules/firebase-tools/node_modules/publish-please
> node lib/pre-install.js


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!! Starting from v2.0.0 publish-please can't be installed globally.          !!
!! Use local installation instead : 'npm install --save-dev publish-please', !!
!! Or use npx if you do not want to install publish-please as a dependency.  !!
!! (learn more: https://github.com/inikulin/publish-please#readme).          !!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by Pushplaybang** [comment]
as a side note, I had originally tried under node v10.* and then switched to v12.

**Comment by magiskboy** [comment]
I'm using node v13 but it still fails

**Comment by AmanAgarwalX** [comment]
My CI CD pipeline is also failing because I can't install firebase-tools in my Docker image.

**Comment by Nickman87** [comment]
Same here, CI completely broken...

**Comment by kot10n5tn** [comment]
firebase-tools@8.16.2 also does not work.

**Comment by jrstnly** [comment]
I've tried it under v12 and v14 and same issue. I'm wondering if this is a dependency issue because I'm not seeing publish-please listed as a direct dependency of firebase-tools.

**Comment by jsockchain** [comment]
My node version is v12.19.0 and failed installing firebase-tools@8.17.0.
It failed due to publish-please@5.5.2 and it removed the old version. 
Now I can't install firebase-tools again.

**Comment by jsockchain** [comment]
![image](https://user-images.githubusercontent.com/54032883/101284605-e7ef7800-37ae-11eb-8dc3-ee3f87b17017.png)

**Comment by Karman40** [comment]
same error here

**Comment by DharmarajX24** [comment]
Looks like you've got fast internet @jsockchain 
Here's link to the [official documentation](https://firebase.google.com/docs/cli#mac-linux-auto-script)

**Comment by Karman40** [comment]
> Looks like you've got fast internet @jsockchain
> Here's link to the [official documentation](https://firebase.google.com/docs/cli#mac-linux-auto-script)
> ![image](https://user-images.githubusercontent.com/63334359/101284690-56602480-3807-11eb-9a07-412b07fbe25b.png)
> _Ubuntu 20.04_

yes, if you have ubuntu or mac, but windows?

**Comment by jsockchain** [comment]
I am on Mac.
```
macOS Catalina - 10.15.6
Node - v12.19.0
Npm - v6.14.8
```

**Comment by DharmarajX24** [comment]
> > Looks like you've got fast internet @jsockchain
> > Here's link to the [official documentation](https://firebase.google.com/docs/cli#mac-linux-auto-script)
> > ![image](https://user-images.githubusercontent.com/63334359/101284690-56602480-3807-11eb-9a07-412b07fbe25b.png)
> > _Ubuntu 20.04_
> 
> yes, if you have ubuntu or mac, but windows?

You can download the [Firebase CLI binary for Windows](https://firebase.google.com/docs/cli#install-cli-windows)

**Comment by jrstnly** [comment]
Looks like one of firebase-tools dependencies has publish-please in it's dependencies instead of devDependencies causing this issue.

[adding publish-please to dependencies seems to be causing downstream problems](https://github.com/Automattic/cli-table/issues/129)

**Comment by lukencrocker** [comment]
Same issue for me. Stops my GitLab pipline and also does not work locally.

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!! Starting from v2.0.0 publish-please can't be installed globally.          !!
!! Use local installation instead : 'npm install --save-dev publish-please', !!
!! Or use npx if you do not want to install publish-please as a dependency.  !!
!! (learn more: https://github.com/inikulin/publish-please#readme).          !!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by rafekun** [comment]
same here

**Comment by DharmarajX24** [comment]
> Same issue for me. Stops my GitLab pipline and also does not work locally.
> 
> !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> !! Starting from v2.0.0 publish-please can't be installed globally. !!
> !! Use local installation instead : 'npm install --save-dev publish-please', !!
> !! Or use npx if you do not want to install publish-please as a dependency. !!
> !! (learn more: https://github.com/inikulin/publish-please#readme). !!
> !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Try installing using cURL or Standalone binary?

**Comment by Karman40** [comment]
@DharmarajX24 

In windows not possible to install binary
![image](https://user-images.githubusercontent.com/32225709/101285147-f1470780-37e3-11eb-9db7-22417e2f6c5d.png)

**Comment by DharmarajX24** [comment]
> @DharmarajX24
> 
> In windows not possible to install binary
> ![image](https://user-images.githubusercontent.com/32225709/101285147-f1470780-37e3-11eb-9db7-22417e2f6c5d.png)

@Karman40 
![image](https://user-images.githubusercontent.com/63334359/101285195-eb641d00-3809-11eb-9676-5904a3380b34.png)
They do have that in their documentation. If that doesn't work, it'll be best to email Firebase support.

**Comment by Karman40** [comment]
@DharmarajX24 According to the documentation, I tried but failed.

**Comment by DharmarajX24** [comment]
> @DharmarajX24 According to the documentation, I tried but failed.

@Karman40 would be best to contact Firebase Support

**Comment by Karman40** [comment]
Ohh yes "We'll usually get back to you within 2 business days (Monday-Friday, 9am-5pm Pacific Time), ". Maybe in a few weeks an answer will come.

**Comment by lukencrocker** [comment]
> > @DharmarajX24 According to the documentation, I tried but failed.
> 
> @Karman40 would be best to contact Firebase Support

I've already sent a message to Firebase support.

**Comment by rafekun** [comment]
It seemed the problem was gone.

**Comment by jrstnly** [comment]
Looks like the offending package has pushed the fix. Update/installation via npm works now.

**Comment by Pushplaybang** [comment]
> Looks like the offending package has pushed the fix. Update/installation via npm works now.

Will test immediately.

**Comment by Nickman87** [comment]
Everything is working again over here 👍

**Comment by DharmarajX24** [comment]
Received a reply from Firebase Support that they were working on it.
I tried it again and here's the output.
```
dharmaraj@dharmaraj-3647:~$ sudo npm i -g firebase-tools
[sudo] password for dharmaraj: 

npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
/usr/bin/firebase -> /usr/lib/node_modules/firebase-tools/lib/bin/firebase.js

> re2@1.15.9 install /usr/lib/node_modules/firebase-tools/node_modules/re2
> install-from-cache --artifact build/Release/re2.node --host-var RE2_DOWNLOAD_MIRROR || npm run rebuild

Trying https://github.com/uhop/node-re2/releases/download/1.15.9/linux-x64-72.br ...
Writing to build/Release/re2.node ...
Trying https://github.com/uhop/node-re2/releases/download/1.15.9/linux-x64-72.gz ...
Writing to build/Release/re2.node ...
Building locally ...
npm ERR! code EACCES
npm ERR! syscall scandir
npm ERR! path /root/.npm/_logs
npm ERR! errno -13
npm ERR! 
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR! 
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 65534:1000 "/root/.npm"
glob error [Error: EACCES: permission denied, scandir '/root/.npm/_logs'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/root/.npm/_logs'
}

> re2@1.15.9 rebuild /usr/lib/node_modules/firebase-tools/node_modules/re2
> node-gyp rebuild

gyp WARN EACCES current user ("nobody") does not have permission to access the dev dir "/root/.cache/node-gyp/12.20.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/firebase-tools/node_modules/re2/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/firebase-tools/node_modules/re2/.node-gyp'
gyp ERR! System Linux 5.4.0-56-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/firebase-tools/node_modules/re2
gyp ERR! node -v v12.20.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! re2@1.15.9 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the re2@1.15.9 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
(node:15722) UnhandledPromiseRejectionWarning: 243
(node:15722) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:15722) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

> protobufjs@6.10.2 postinstall /usr/lib/node_modules/firebase-tools/node_modules/protobufjs
> node scripts/postinstall

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/firebase-tools/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ firebase-tools@8.17.0
added 600 packages from 375 contributors in 70.399s
```

It does work but looks like there's still some error.
I used the command with sudo, but still EACCES error.

**Comment by Pushplaybang** [comment]
I can confirm the update has worked on my end, and I'm able to both install, and operate as normal.

**Comment by Pushplaybang** [comment]
@DharmarajX24 there seem to be unrelated errors explained in your output above, related to your local setup, specifically:

```sh
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR! 
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 65534:1000 "/root/.npm"
```

I'm closing this issue, as I believe it be resolved, and would suggest investigating, and then opening a separate related issue if you believe it is specific to firebase-tools.

**Comment by DharmarajX24** [comment]
> @DharmarajX24 there seem to be unrelated errors explained in your output above, related to your local setup, specifically:
> 
> ```shell
> npm ERR! Your cache folder contains root-owned files, due to a bug in
> npm ERR! previous versions of npm which has since been addressed.
> npm ERR! 
> npm ERR! To permanently fix this problem, please run:
> npm ERR!   sudo chown -R 65534:1000 "/root/.npm"
> ```
> 
> I'm closing this issue, as I believe it be resolved, and would suggest investigating, and then opening a separate related issue if you believe it is specific to firebase-tools.

Yes I figured that out. :)
