### ISSUE TITLE
onUpdate not trigger with customer databaseURL

### ISSUE THREAD

**Issue by paulyip** [firebase/firebase-tools#2908]
### [REQUIRED] Environment info

**firebase-tools:**
8.17.0

**Platform:**
macOS

### [REQUIRED] Test case

Add the following two cloud functions

```js
export const helloWorld = functions.https.onRequest(async(request, response) => {
    
    try 
    {
        await admin.database().ref().child('users').push({ name : 'peter' })
    }
    catch (error)
    {
        console.log(error)
    }
    response.send("Hello from Firebase from emulator!")
})

export const onDatabaseUpdate = functions.database
    .ref('/users/{userId}')
    .onUpdate(async(change, context) => {
        console.log('onDatabaseUpdate')
        return change.after.ref.update({age:23})
})
```

### [REQUIRED] Steps to reproduce

1 - call http://localhost:5001/xxx/us-central1/helloWorld to create user 'Peter' in database
2 - in the emulator change the user name from 'Peter' to 'Mary'
3 - a new field age '23' is created
4 - add the following line to provide a custom namespace
let config = {
    databaseURL :'http://127.0.0.1:9000/?ns=127'
}
admin.initializeApp(config)

5 - delete the user database
6 - call http://localhost:5001/xxx/us-central1/helloWorld to create user 'Peter' in database
7 - in the emulator change the user name from 'Peter' to 'Mary'
8 - no field 'age' is created

### [REQUIRED] Expected behavior

In step 8, a field age '24' should be created

### [REQUIRED] Actual behavior

no 'field' age is created

**Comment by samtstern** [comment]
@paulyip Cloud Functions are registered against the default database unless otherwise specified.  When you use `ns=127` you're implying that your default database is `127.firebaseio.com` and that (normally) your project ID is `127`.  Is that the case?

**Comment by paulyip** [comment]
No.  My project ID is another one said 'abc-123'.  For some  reason, Unity SDK cannot access the 'abc-123' database in emulator.  Instead, Unity SDK can only access the database with namespace '127'.  You may refer to the following link.

https://forum.unity.com/threads/firebase-realtime-database-emulator-and-unity.883486/#post-6596128

On the cloud function side, the cloud function write data to my 'abc-123' database by default.  Then, I change the database by using the following function.  I found that it can write data to the '127' database but the onUpdate function is not triggered as my test case.

let config = {
databaseURL :'http://127.0.0.1:9000/?ns=127'
}
admin.initializeApp(config)

The problem is why the onUpdate function not triggered after I change the dabaseURL?

**Comment by samtstern** [comment]
@paulyip this is the expected behavior.  The `onUpdate` function is registered to detect changes to your default database but you are accessing a different namespace, so the function does not fire.

Sounds like you're having a Unity-specific issue. I would suggest asking about that here:
https://github.com/firebase/quickstart-unity
