### ISSUE TITLE
Functions deploy command ignores any hidden files (files starting with .)

### ISSUE THREAD

**Issue by abstractpoint** [firebase/firebase-tools#291]
Functions deploy command ignores any hidden files (files starting with .) and there isn't a way to configure this via `firebase.json`

Why don't we have a config like this as for hosting part
```
{
  "hosting": {
    "public": "app",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ]
  }
}
```
The use case for this is when building a bundle to be deployed, certain frameworks output hidden files that need to be uploaded.

**Comment by jthegedus** [comment]
I believe the culprit is here: https://github.com/firebase/firebase-tools/blob/b428355023b5df4d06fa28123da825bb870ba9cf/lib/prepareFunctionsUpload.js#L104

This is only the Functions implementation but the Hosting should be in the similarly named file.

**Comment by laurenzlong** [comment]
Thanks for hunting down the line to fix @jthegedus ! Just made PR for the fix. I don't believe hosting has the same issue. It's a different process (tarball instead of zip).

**Comment by laurenzlong** [comment]
@abstractpoint we do also now support functions.ignore inside of firebase.json, give it a try!

**Comment by kroupacz** [comment]
Hello @laurenzlong. I tried to use "functions.ignore" inside of firebase.json, but it doesn't work for me. Are you sure, that it is already implemented in "firebase-tools"?
It would be really useful if the parameter "ignore" also worked for the Cloud Functions.

**Comment by laurenzlong** [comment]
Hey @kroupacz , that's what functions.ignore means, it's to indicate which files inside of the functions/ folder to ignore when deploying Cloud Functions for Firebase. Is that what you mean?

**Comment by kroupacz** [comment]
Hi @laurenzlong,
thank you for your reply.
I know what is the purpose of this config, but when I use firebase.json with configuration like this:

```
{
  "functions": {
    "source": "./",
    "ignore": [
      "README.md",
      "package-lock.json",
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ]
  }
}
```

it seems that it has no effect and all defined files in "ignore" rule are deployed (except node_modules).
I am using the latest version (3.9.2) of firebase-tools.
A similar configuration for "hosting.ignore" works well.

**Comment by koistya** [comment]
The ignore rules from `firebase.json/hosting/ignore` still have no effect on what files are being packaged.

**Comment by Cretezy** [comment]
@kroupacz very late, but change `ignore` to `.ignore`.
