### ISSUE TITLE
Firebase emulator stripping `Authentication` header when rewriting a function

### ISSUE THREAD

**Issue by jakebiesinger-storyhealth** [firebase/firebase-tools#2910]
### [REQUIRED] Environment info

Affects:
8.17.0
8.18.0

NOT present in:
8.16.2

**firebase-tools:** 8.18.0

**Platform:** macOS

### [REQUIRED] Test case

```
#Somefile.js
const app = express();
app.get('/foo', (req, res) => console.log(req.get('Authorization'));
export testAuth = functions.https.onRequest(app);

#firestore.json
"hosting": [
    {
      "target": "testTarget",
      "public": "public",
      "rewrites": [
        {
          "source": "/testAuth/**",
          "function": "testAuth"
        },
...
```

### [REQUIRED] Steps to reproduce

1. Start the firebase emulator:

firebase -P testTarget emulators:start --inspect-functions

2. send a curl command to the rewritten function, placing a bearer token on the command-line:

curl -H "Authorization: Bearer eyJhbGc..." localhost:5000/testAuth

### [REQUIRED] Expected behavior

The function should list the passed-in auth header in the output.

### [REQUIRED] Actual behavior

Instead, the auth header has been stripped (it's undefined):
> `undefined`

If I rerun directly calling the function (without having `hosting` do a rewrite, it successfully prints the auth token)

curl -H "Authorization: Bearer eyJhbGc..." localhost:5001/us-central1/someProjectId/testAuth

> `Authorization: Bearer eyJhbGc`

**Comment by samtstern** [comment]
@jakebiesinger-storyhealth thank you for the clear description.

@bkendall sounds like maybe a superstatic issue?

**Comment by bkendall** [comment]
It's not a superstatic issue because I can replicate this with just the functions emulator. Taking a further look now to see if I find anything useful...

**Comment by bkendall** [comment]
I take that back - I've not replicated this yet.

**Comment by bkendall** [comment]
Ah, I've figured it out. It has to do with the underlying request library changing from `request` to `node-fetch`. I believe the difference is that `request` allowed you to pipe entire requests including headers to and from it. I'm not actually forwarding on headers in https://github.com/firebase/firebase-tools/blob/master/src/hosting/proxy.ts#L71 like I should be in order for this to work. I'm working on a fix, but making it safe and tested will take a moment 🙂  Thanks for the report!
