### ISSUE TITLE
Is there a way to create default firebase realtime database?

### ISSUE THREAD

**Issue by Shaita-KrZ** [firebase/firebase-tools#2918]
Hello there,

I am trying to create a Firebase project with a default real-time database using the firebase tools cli.

I did not need to create the default real-time database before but now when I tried to push data to my database after creating the project I am getting the following error message: 

> It looks like you haven't created a Realtime Database instance in this project before. Go to https://console.firebase.google.com/project/abatest-jdsyrt/database to create your default Realtime Database instance.

So I tried to create the real-time database instance using:
`firebase database:instances:create`

But it does not work, I was able to make it work only if I changed my billing formula from Spark to Blaze but still it will create a second instance and not the default one. 

I am not sure what to do now.

Best regards.

**Comment by samtstern** [comment]
@Shaita-KrZ thank you for the question! When you called `firebase database:instances:create` do you remember what the error message was?

@sarajmunjal do you know the answer?

**Comment by alexleonov-tactiq** [comment]
Any updates on this? Here's the error message:

```
❯ firebase database:instances:create default

Error: It looks like you haven't created a Realtime Database instance in this project before.
Please run firebase init database to create your default Realtime Database instance.
```

Can't find any options for non-interactive initialisation so far.

**Comment by aimanharith67** [comment]
Who know the answer to this question????

**Comment by myflashlab** [comment]
I'm also interested to know the answer for this question

**Comment by guptamukul-google** [comment]
Does anyone have any solution to this ?

When I try to create default RTDB using [projects.locations.instances.create](https://firebase.google.com/docs/reference/rest/database/database-management/rest/v1beta/projects.locations.instances/create) and my cURL url looks like:

"https://firebasedatabase.googleapis.com/v1beta/projects/PROJECT_ID/locations/us-central1/instances?databaseId=PROJECTID-default-rtdb"

I am getting following error:

```
{
  "error": {
    "code": 400,
    "message": "Non-default namespaces cannot end with '-default-rtdb'.",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "INVALID",
        "metadata": {
          "suggested_database_ids": "PROJECT_ID-c3d49,PROJECT_ID-f7455,PROJECT_ID-f34d8"
        }
      }
    ]
  }
}
```

**Comment by fredzqm** [comment]
Most of the time, the default database is created in console's onboard page or `firebase init` flow.

If the default database isn't created yet, you can create it via the management API. Try out the API explorer, there is a `type` in the request body. It defaults to `USER_DATABASE`, so most requests don't need to specify it.

if `type` is set to `DEFAULT_DATABASE`, the reserved default name would be picked for you, no need to specify `databaseId`.

https://firebase.google.com/docs/reference/rest/database/database-management/rest/v1beta/projects.locations.instances/create
```
curl --request POST \
  'https://firebasedatabase.googleapis.com/v1beta/projects/firebase-staging/locations/us-central1/instances?key=[YOUR_API_KEY]' \
  --header 'Authorization: Bearer [YOUR_ACCESS_TOKEN]' \
  --header 'Accept: application/json' \
  --header 'Content-Type: application/json' \
  --data '{"type":"DEFAULT_DATABASE"}' \
  --compressed
```

**Comment by fredzqm** [comment]
Thank you @christhompsongoogle for routing the issue. Saraj no longer works here, so this bug got straggled.

Please route any RTDB-related issues to me~

**Comment by nahuelMarenco** [comment]
Hi there, I had the same issue... I solved it by starting the Realtime Database from the Firebase web console.

Kind regards.
