### ISSUE TITLE
Backend Error using auth:export

### ISSUE THREAD

**Issue by JimJty** [firebase/firebase-tools#292]
I am exporting user accounts using this command:

`firebase --token mytoken --project my-project-id auth:export users.json`

and I get this error:

`Error: HTTP Error: 500, Backend Error`

The firebase-debug.log reports the same error.

I have had the command work before and fail before. I emailed firebase support and they suggested that their server might be down and try again. I had and it did work but now I am seeing the issue again when trying to do this with another project-id.

Any suggestions to get this working? or another way to export users. I have the feeling this functionality is not fully supported by firebase since I had to email support to get my hash key to use the auth:import command. I'm running out of support tickets.

**Comment by vanburg** [comment]
Still true...

**Comment by AndrewSadler** [comment]
Exactly the same behaviour for me too today.

**Comment by miguelcarrascoq** [comment]
from your CLI type:
$ firebase list
then, select your project:
$ firebase use <Project ID / Instance>
then, move (cd) into a project directory or make "firebase init"
Finally,
$ firebase auth:export user.json

That, work for me. https://firebase.google.com/docs/cli/auth

**Comment by wyhao31** [comment]
Sorry, I missed this thread. The backend error of auth:export was actually due to a backend issue at that time. It's already be resolved a few weeks ago.
