### ISSUE TITLE
Update CLI Emulator status URL to include http://

### ISSUE THREAD

**Issue by Joebayld** [firebase/firebase-tools#2921]
Hi, 

I've noticed a small detail that affects users in VS Code. If you run the Firebase emulator via terminal in VS Code it makes it quite useful to open links directly from the terminal to Chrome. However, to view the emulator status UI for example, it shows the URL as 'localhost:4000'. Note that it doesn't include the 'http://' prefix thus confusing VS Code to think this is a file path and not a web URL. 

<img width="492" alt="image" src="https://user-images.githubusercontent.com/9399317/101853259-2751f780-3b14-11eb-8128-9d73b03a95a7.png">

When (Cmd) clicking the URL on Mac, the following happens: 
<img width="610" alt="image" src="https://user-images.githubusercontent.com/9399317/101853372-57999600-3b14-11eb-81c3-6a0669102a00.png">

As you can tell, it's thinking it's a file path and trying to navigate to the file. If the CLI would include 'http://' before the URL, it would open the link in Chrome (or whatever the users default browser is). I feel that would make for a better user experience. 

This might be an edge case but seems like something that can be useful. 

Thanks,
Joe

**Comment by samtstern** [comment]
@Joebayld thanks for this suggestion, it's a good idea and something I can clean up today while I'm in there making a related change.
