### ISSUE TITLE
FirebaseError: Missing or insufficient permissions with Firestore Emulator

### ISSUE THREAD

**Issue by BuffMcBigHuge** [firebase/firebase-tools#2926]
### Environment info

**Server**:
firebase-tools: 8.19.0

**Client**:
firebase: 8.2.0

**Platform:** 
macOS Big Sur, node v12.20

### Test case

I'm able to access the emulator firestore when I'm not authenticated, but the second I'm authenticated, I am unable to access anything in the firestore, receiving `FirebaseError: Missing or insufficient permissions.`

### Steps to reproduce

1) Run `firebase emulators:start --import database_backup`
2) Run local client application

```
import firebase from 'firebase'
import 'firebase/firestore'
import 'firebase/auth'
import 'firebase/functions'

firebase.initializeApp(config.google);

const db = firebase.firestore();
const auth = firebase.auth();
const functions = firebase.functions();

if (process.env.NODE_ENV !== 'production') {
	db.useEmulator('localhost', 8080);
	auth.useEmulator('http://localhost:9090');
	functions.useEmulator('localhost', 5001);
}
```

3) Request public firestore data (data is pulled correctly)
4) Login/Signup to a new user account (auth working correctly()
5) All firestore snapshots error, nothing can be read/written to db.

I ran debug mode, and noticed that the credential object is `null` once authenticated, could this be a cause?

**Note 1**: I am using the exact `firestore.rules` as my production and I do not have this problem. Happens only with emulation. My only solution at the moment is to not use the auth and firestore emulators. I've tried removing the rules altogether, and I get the same issue.

**Note 2**: I am able to write to the firestore in the emulator suite.

**Comment by BuffMcBigHuge** [comment]
I discovered what the issue was. 

I was calling `db.settings(settings)` after the emulator was set. It seemed to have been breaking the emulator configuration. Removing it solved my issue.

**Comment by samtstern** [comment]
@BuffMcBigHuge thanks for following up. Since you were able to fix your issue I am going to close it here. It sounds like it may have been related to this discussion, so we're working on improving it:
https://github.com/firebase/firebase-js-sdk/issues/4110
