### ISSUE TITLE
cloud function extension emulator throws error when adding data

### ISSUE THREAD

**Issue by russellwheatley** [firebase/firebase-tools#2930]
### [REQUIRED] Environment info

**firebase-tools:**
8.17.0

**Platform:**
macOS Catalina 10.15.4

### [REQUIRED] Test case

See steps to reproduce.

### [REQUIRED] Steps to reproduce

1. git clone `git@github.com:firebase/extensions.git`
2. run `npm i` from root of extension's directory.
3. cd `rtdb-limit-child-nodes` directory
4. create `test-params.env` file. Add environment variables & insert project id as appropriate:
```env
LOCATION=europe-west2
MAX_COUNT=2
NODE_PATH=test
SELECTED_DATABASE_INSTANCE=[INSERT YOUR OWN PROJECT ID]
```
5. delete line 129: `default: ${DATABASE_INSTANCE}` & line 131:`validationRegex: ^([0-9a-z_.-]*)$` from the `extension.yaml` file otherwise you will encounter the issue I raised [here](https://github.com/firebase/firebase-tools/issues/2928).
6.  run CLI command with your project id : `firebase ext:dev:emulators:start --test-params=test-params.env --project=[INSERT YOUR OWN PROJECT ID]` 

### [REQUIRED] Expected behavior

I expect the Cloud Function emulator to run when I add data to the RTDB emulator.

### [REQUIRED] Actual behavior

Error is thrown:

```
@firebase/database: FIREBASE FATAL ERROR: Cannot parse Firebase url. Please use https://<YOUR FIREBASE>.firebaseio.com

```

**Comment by joehan** [comment]
Closing - this is fixed by the extensions emulator ((https://firebase.google.com/docs/emulator-suite/use_extensions)
