### ISSUE TITLE
UID not present in the auth emulator idToken

### ISSUE THREAD

**Issue by vajahath** [firebase/firebase-tools#2948]
### [REQUIRED] Environment info
**firebase-tools:**: 8.20.0
**Platform:**: Windows

The `idToken` returned by the `auth.getRedirectResult()` function does not have the `uid` property **when used with firebase auth emulator**.
The `idToken` can be decoded to [`DecodedIdToken`](https://firebase.google.com/docs/reference/admin/node/admin.auth.DecodedIdToken), where it has the `uid` prop.

Eg. idToken form auth emulator:

![image](https://user-images.githubusercontent.com/12165822/102451565-bbfdad80-405e-11eb-8362-1e425e955b09.png)
```jsonc
{
  "sub": "7476255298788018254391595567660699225049",
  "iss": "",
  "aud": "",
  "exp": 0,
  "iat": 0,
  "name": "Peach Peach",
  "screen_name": "peach_peach",
  "email": "vajuoff.1@gmail.com",
  "email_verified": true,
  // missing uid
}
```
### [REQUIRED] Test case
```ts
const result = await auth.getRedirectResult(); // https://firebase.google.com/docs/reference/js/firebase.auth.Auth#getredirectresult

// for auth emulator, id token is not signed, but a JSON string
const decodedToken: DecodedIdToken = JSON.parse(result.credential.idToken);

expect(decodedToken.uid).not.toBeUndefined(); // fail
```
### [REQUIRED] Expected behavior
The token should have `uid` in it.
### [REQUIRED] Actual behavior
Missing `uid` in the token.

**Comment by yuchenshi** [comment]
Which third-party identity provider are you signing in with? Would you mind trying the same thing in production and paste the idToken you get? Does the production token have `uid` in it?

For reference, `result.credential.idToken` is not the Firebase Auth idToken, but the idToken returned by the third-party identity provider (IDP), so the fields are defined by IDP and will NOT follow [`DecodedIdToken`](https://firebase.google.com/docs/reference/admin/node/admin.auth.DecodedIdToken) schema. If you'd like to get the Firebase Auth idToken, use `result.user.getIdToken()` instead. This applies to both production and Auth Emulator. (And BTW, [`uid`](https://firebase.google.com/docs/reference/admin/node/admin.auth.DecodedIdToken#uid) is only present in the admin SDK return value -- see the linked doc which explains `uid` is not actually in the JWT token. You'd probably want `sub` instead.)

**Comment by vajahath** [comment]
Sorry for the delay. My identity provider was Google.
I was using `result.credential.idToken` instead of `result.user.getIdToken()`. That caused the issue. This issue can be closed now. Thanks @yuchenshi.

> Does the production token have uid in it?

Actually no. I was looking at `result.credential.idToken` instead of `result.user.getIdToken()`.
