### ISSUE TITLE
Error in deploying hosting

### ISSUE THREAD

**Issue by yasutak-k** [firebase/firebase-tools#2949]
### [REQUIRED] Environment info

**firebase-tools:**
9.0.1

**Platform:**
macOS

### [REQUIRED] Test case

Deploy firebase hosting

### [REQUIRED] Steps to reproduce

firebase deploy --only hosting

Adding settings for CloudRun to the rewrite configuration will result in an error.

firebase.json:
```
        {
          "source": "/**",
          "run": {
            "region": "asia-northeast1",
            "serviceId": "xxx-api"
          }
        }
```

### [REQUIRED] Expected behavior

Deploy completed without errors.

### [REQUIRED] Actual behavior
```
i  deploying hosting

Error: HTTP Error: 400, Precondition check failed.
```

end of firebase-debug.log:
```
[debug] [2020-12-17T06:32:50.423Z] <<< HTTP RESPONSE 400 {"vary":"X-Origin, Referer, Origin,Accept-Encoding","content-type":"application/json; charset=UTF-8","date":"Thu, 17 Dec 2020 06:32:50 GMT","server":"ESF","cache-control":"private","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","alt-svc":"h3-29=\":443\"; ma=2592000,h3-T051=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","accept-ranges":"none","transfer-encoding":"chunked"}
[debug] [2020-12-17T06:32:50.423Z] <<< HTTP RESPONSE BODY {"error":{"code":400,"message":"Precondition check failed.","status":"FAILED_PRECONDITION"}}
[error] 
[error] Error: HTTP Error: 400, Precondition check failed.
[debug] [2020-12-17T06:32:50.663Z] Error Context: {
  "body": {
    "error": {
      "code": 400,
      "message": "Precondition check failed.",
      "status": "FAILED_PRECONDITION"
    }
  },
  "response": {
    "statusCode": 400,
    "body": {
      "error": {
        "code": 400,
        "message": "Precondition check failed.",
        "status": "FAILED_PRECONDITION"
      }
    },
    "headers": {
      "vary": "X-Origin, Referer, Origin,Accept-Encoding",
      "content-type": "application/json; charset=UTF-8",
      "date": "Thu, 17 Dec 2020 06:32:50 GMT",
      "server": "ESF",
      "cache-control": "private",
      "x-xss-protection": "0",
      "x-frame-options": "SAMEORIGIN",
      "x-content-type-options": "nosniff",
      "alt-svc": "h3-29=\":443\"; ma=2592000,h3-T051=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"",
      "accept-ranges": "none",
      "transfer-encoding": "chunked"
    },
    "request": {
      "uri": {
        "protocol": "https:",
        "slashes": true,
        "auth": null,
        "host": "firebasehosting.googleapis.com",
        "port": 443,
        "hostname": "firebasehosting.googleapis.com",
        "hash": null,
        "search": null,
        "query": null,
        "pathname": "/v1beta1/sites/xxxxx/versions",
        "path": "/v1beta1/sites/xxxxx/versions",
        "href": "https://firebasehosting.googleapis.com/v1beta1/sites/xxxxx/versions"
      },
      "method": "POST"
    }
  }
}

```

**Comment by DavuluriHemanthChowdary** [comment]
I had this connections time out issue around 4:30 AM IST to 6:00 AM IST and after that it worked fine! And the timeout issue i had was when deploying only functions.

**Comment by yasutak-k** [comment]
I just tried it now (18:20 JST) and the result is the same.
If I remove the rewrite setting, it succeeds, so that may be the problem. 
But I don't know how to solve it.

As of 09 December 2020, 04:52:00 UTC it was successful. The version of firebase-tools at that time was 8.18.0.

If I downgrade to version 8.18.0 now, I get the same result.

**Comment by nostrapollo** [comment]
I'm having the same issue as described, no changes to firebase.json or hosting configurations. 

This could be related to changes in Cloud Run API again, as described in [#1444](https://github.com/firebase/firebase-tools/issues/1444#issuecomment-506396524) by @Memeriaj

**Comment by nikhilag** [comment]
I am facing the same issue as well. If I remove the rewrites for cloud run, then it works fine.

**Comment by nikhilag** [comment]
@mbleigh Would really appreciate your help in this matter. I am unable to deploy some important changes to production because of this issue.

**Comment by mogaming217** [comment]
I'm having the same issue. firebase-tools is 9.0.1.

```
  "hosting": {
    "public": "frontend/.next/static",
    "rewrites": [
      {
        "source": "**/**",
        "run": {
          "serviceId": "renderer",
          "region": "asia-northeast1"
        }
      }
    ],
    "postdeploy": [
      "npm --prefix frontend run gcloud:deploy"
    ]
  },
```

**Comment by gawen** [comment]
I'm having the same issue. I filled an issue before seeing this one. https://github.com/firebase/firebase-tools/issues/2951

**Comment by nelson-vendoo** [comment]
Having the same issue `firebase-tools@9.0.1` from yesterday afternoon 
```json
{
  "target": "app",
  "public": "packages/web-app/public",
  "ignore": ["firebase.json", "**/.*", "**/node_modules/**", "**/**.map"],
  "rewrites": [
    {
      "source": "/api{,/**}",
      "run": {
        "serviceId": "vendoo-server",
        "region": "us-central1"
      }
    }
  ]
}
```

**Comment by jwoyo** [comment]
This is not the first time hosting rewrites suddenly break. Last time (in august) we had this issue with Cloud Run services in some specific regions. Firebase Support resolved this by doing a rollback back then (case number: 00080862)

This happens on 9.0.1 and in older versions why I don't think this is an issue with firebase-tools. I will open a ticket at Firebase Support again.

**Comment by jmaguirrei** [comment]
Also having same issue here.
If I remove rewrites rule:

```
    {
        "source": "/api-methods",
        "run": {
          "serviceId": "wiki-usa-pro-api-methods",
          "region": "us-east1"
        }
      }
```
Deployment works, but clearly not an option.
Also opened a support case 00105255

**Comment by jwoyo** [comment]
@jmaguirrei – yep – deployments work with no rewrites.

For us this means that the next deployment to our prod. environment will break functionality. 🙄

For me that means: end of working day 🏝

**Comment by kurtinge** [comment]
We are experiencing the same issue when deploying and having rewrite towards region "europe-west1".

**Comment by lucasbstn** [comment]
Same issue here with rewrites to "europe-west1".

**Comment by abernier** [comment]
confirming, same issue also here, with `"rewrites"` and `"region": "europe-west1"`

**Comment by mbleigh** [comment]
Hey folks, we're seeing an issue specifically with deploying Cloud Run rewrites to Firebase Hosting at the moment. I'm working on getting something posted to the Firebase status dashboard (I'll link when it's there) but just acknowledging a problem that we're looking into.

**Comment by mbleigh** [comment]
This should be fully mitigated within the next 10 minutes or so. Sorry for the inconvenience, folks. If you're having issues after that, please comment!

**Comment by jmaguirrei** [comment]
@mbleigh Thanks very very very much for addressing this, it works for me know!

**Comment by jwanglof** [comment]
Works for me as well 👍

**Comment by abernier** [comment]
woooorking 👏

**Comment by yasutak-k** [comment]
@mbleigh It worked for me too. I appreciate your help!

**Comment by bcthakre** [comment]
Was the fix done to mitigate future issues as well since I am getting the same error? And seems like nothing much I can do from my end. Happens while setting GitHub for Actions. 

`Error: HTTP Error: 400, Precondition check failed.`
