### ISSUE TITLE
localhost:4000 is unable

### ISSUE THREAD

**Issue by KevsRepos** [firebase/firebase-tools#2950]
I initialized a firebase project. After that I started the emulators. The emulators started successfully:
` ✔  All emulators ready! View status and logs at localhost:4000`

Then I tried to go to the emulator ui, but literally nothing happens. The url just disappears when I hit enter and the tab remains the same. There are no error logs, nothing.

This is firebase.json:

```json
{
  "firestore": {
    "rules": "firestore.rules",
    "indexes": "firestore.indexes.json"
  },
  "functions": {
    "predeploy": [
      "npm --prefix \"$RESOURCE_DIR\" run lint"
    ],
    "source": "functions"
  },
  "emulators": {
    "auth": {
      "port": 9099
    },
    "functions": {
      "port": 5001
    },
    "firestore": {
      "port": 5002
    },
    "ui": {
      "enabled": true
    }
  },
  "remoteconfig": {
    "template": "remoteconfig.template.json"
  }
}
```

**Comment by KevsRepos** [comment]
What Information do you need?

**Comment by samtstern** [comment]
@KevsRepos the issue template asks for a bunch of information which we need for debugging:
https://github.com/firebase/firebase-tools/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

For example:

- What platform are you running on?
- What version of the CLI are you using?
- Is there anything in the debug logs?
