### ISSUE TITLE
web app not using emulators

### ISSUE THREAD

**Issue by Nomkid** [firebase/firebase-tools#2957]
### [REQUIRED] Environment info

**firebase-tools:** 9.0.1

**Platform:** Windows

### [REQUIRED] Steps to reproduce

1. Try to use firebase emulators with `?useEmulator=true` or `.useEmulator()`

### [REQUIRED] Expected behavior

1. It connects to auth and firestore emulators
2. It interfaces with those emulators

### [REQUIRED] Actual behavior

1. It connects to auth and firestore emulators
2. It still submits to the production console
3. It does not accept any responses

**Comment by samtstern** [comment]
@Nomkid can you show some code and logs to help us reproduce this? Specifically I'd like to see:

- What version of the Firebase JS SDK are you using?
- Are there any interesting debug or error logs?
- How are you calling `initializeApp()`?
- Which call in your app still connects to production?

**Comment by deepalwin** [comment]
I am facing the same issue, I am trying to use auth service in emulators with SDK - firebase.auth().useEmulator('http://localhost:9099/');

It does recognize the command and It does not work the way it should. Is there any more configuration that is required? Can you tell me the config variables (like API key etc) that should be used while using local emulators?  This is a serious issue with firebase, I am unable to mimic the services on emulators.

**Comment by samtstern** [comment]
@deepalwin when using the emulators (via `useEmulator`) the only important part of your `firebase.initializeApp(config)` is the Project ID.  Make sure this Project ID matches the one you're using with the Firebase CLI.

If you want to be sure, you can pass the `--project=` flag:
```
firebase --project="<your project id here>" emulators:start
```

**Comment by deepalwin** [comment]
@samtstern the project ID is the same that is available on firestore cloud? Coz there is no option to create a new project using CLI in emualtors.

**Comment by samtstern** [comment]
@deepalwin yes that's correct just use your real project ID

**Comment by dbajaj-qasource** [comment]
@samtstern Thanks for the useful information, However, I am still facing the issue. The error is Uncaught (in promise) TypeError: Cannot read property 'createUserWithEmailAndPassword' of undefined at data.

A post request is generated to a URL that contains my API Key and below is the response :

{
  "error": {
    "code": 404,
    "message": "Not Found",
    "errors": [
      {
        "message": "Not Found",
        "reason": "notFound"
      }
    ],
    "status": "NOT_FOUND"
  }
}

**Comment by deepalwin** [comment]
@samtstern Thanks for the useful information, However, I am still facing the issue. The error is Uncaught (in promise) TypeError: Cannot read property 'createUserWithEmailAndPassword' of undefined at data.

A post request is generated to a URL that contains my API Key and below is the response :

{
"error": {
"code": 404,
"message": "Not Found",
"errors": [
{
"message": "Not Found",
"reason": "notFound"
}
],
"status": "NOT_FOUND"
}
}

**Comment by samtstern** [comment]
@deepalwin please open a new issue showing us how to reproduce your problem and providing any logs you have, sounds like there's a lot going on there and it's not related to @Nomkid 's issue

**Comment by deepalwin** [comment]
@samtstern Sure, But initially I had the same issue. I implemented the steps provided by you for example use of - "firebase --project="<your project id here>" emulators:start" command. 

Once this was done my emulators got started (Both auth and hosting). I can see my application at 5000 and auth at 9099 localhosts but the auth emulator is not receiving my data as firebase auth.

**Comment by samtstern** [comment]
@deepalwin yeah I agree the high-level symptoms are the same but your mention of `createUserWithEmailAndPassword` not existing and a 404 issue lead me to believe the underlying cause is not related to what @Nomkid reported.

**Comment by Nomkid** [comment]
@samtstern
- I always update whenever there is an update available.
- Nothing to be seen.
- It's in a web app, so I'm using the reserved URL `/__/init.js?useEmulators=true` (whatever it is) copied right from the docs.
- The warning at the bottom still shows, but nothing is actually connecting to the emulators. I'm using Firestore and With, neither are using the emulators.

**Comment by samtstern** [comment]
@Nomkid thanks for getting back to me ... we need your help to reproduce this bug on our machines as right now you're the only one reporting this behavior. Can you help outline the steps to a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?  Ideally starting with `firebase init`.
