### ISSUE TITLE
Consider updating version of `universal-analytics` to remove deprecation warning.

### ISSUE THREAD

**Issue by psigen** [firebase/firebase-tools#296]
When installing via `npm install -g firebase-tools`, all platforms receive the warning:
```
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
```
This warning is transitive from the `univeral-analytics` package dependency, which requires `node-uuid` in its `0.3.x` line.  If you can update this to the `0.4.x` line, it uses the non-deprecated `uuid` package, and removes this warning.

**Comment by kevinajian** [comment]
This has been updated.
