### ISSUE TITLE
Firebase Emulator initialization URL given for module grouped firebase functions hangs and requires modification to work.

### ISSUE THREAD

**Issue by letsgamedotdev** [firebase/firebase-tools#2966]
### [REQUIRED] Environment info

**firebase-tools:** Firebase 9.1.0

**Platform:** Windows

### [REQUIRED] Test case

```
// ... from index.ts
exports.auth = require("./authFunctions");
```

```
// ... from authFunctons.ts
exports.isAdmin = functions.https.onCall((_, context) => {...}
```

In firebase CLI
```
+  functions[auth-isAdmin]: http function initialized (http://localhost:5001/letsplaydotdev/us-central1/auth.isAdmin). 
```

Going to `http://localhost:5001/letsplaydotdev/us-central1/auth.isAdmin` hangs and never responds. Going to `http://localhost:5001/letsplaydotdev/us-central1/auth-isAdmin` does establish connection.

### [REQUIRED] Steps to reproduce

Create function group and export it in index.ts. Start up emulator using `firebase emulators:start`. The initialized URL outputted hangs.

### [REQUIRED] Expected behavior

The firebase function's outputted URL does not hang.

### [REQUIRED] Actual behavior

The firebase function's outputted URL does hang.

**Comment by samtstern** [comment]
@letsgamedotdev thanks for reporting this!  That seems like a clear bug, I'll get a fix together.
