### ISSUE TITLE
firebase 9.1.0 local emulator not picking up js files changes

### ISSUE THREAD

**Issue by Anant101** [firebase/firebase-tools#2969]
i am not using typescript ,
 so i don't have to compile any anything but when i make changes in the functions and save the 
firebase emulators:start not picking up the changes
but firebase --debug emulators-start picks up the changes when i save it

**Comment by samtstern** [comment]
@Anant101 please use the issue template when filing an issue, this is not enough information to help you debug:
https://github.com/firebase/firebase-tools/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
