### ISSUE TITLE
firebase init database does not work without a project ID

### ISSUE THREAD

**Issue by samtstern** [firebase/firebase-tools#2981]
### [REQUIRED] Environment info

**firebase-tools:** 9.1.0
**Platform:** macOS

### [REQUIRED] Test case

Run `firebase init` and defer project selection:
```
? Which Firebase CLI features do you want to set up for this folder? Press Sp
ace to select features, then Enter to confirm your choices. Database: Configu
re Firebase Realtime Database and deploy rules

=== Project Setup

First, let's associate this project directory with a Firebase project.
You can create multiple project aliases by running firebase use --add,
but for now we'll just set up a default project.

? Please select an option: Don't set up a default project

=== Database Setup
i  database: ensuring required API firebasedatabase.googleapis.com is enabled...

Error: HTTP Error: 403, The caller does not have permission
```

### [REQUIRED] Steps to reproduce

See above

### [REQUIRED] Expected behavior

The `firebase int` flow should skip API enablement when there is no project ID and just set up local default rules/config.

### [REQUIRED] Actual behavior

Fails with a 403 error.

**Comment by bkendall** [comment]
@yuchenshi would you be able to look at this, or triage it to an appropriate someone?

**Comment by samtstern** [comment]
Just ran into this one again.
