### ISSUE TITLE
Firestore Emulator Security Rules 'get', 'exists' not finding existing documents

### ISSUE THREAD

**Issue by bradleymackey** [firebase/firebase-tools#2983]
### [REQUIRED] Environment info

**firebase-tools:** 9.1.0

**Platform:** macOS 11.1 x86_64

### [REQUIRED] Test case

```
service cloud.firestore {

    match /databases/{database}/documents {

        match /test/my-profile {
            function isThisAllowed() {
                let pth = /databases/$(database)/documents/test/toms-profile;
                return exists(pth);
            }
            allow read, write: if isThisAllowed();
        }
    }
}
```

Connect to Firestore emulator and add a document to `test/toms-profile`.
The read to `test/my-profile` will fail by a **non-admin** user, because the emulator does not detect the newly added document.

### [REQUIRED] Steps to reproduce

See example above.

### [REQUIRED] Expected behavior

The write to the example document succeeds, because the rule allows it if the other document exists.

### [REQUIRED] Actual behavior

Permission-denied error for `exists`.

This error is produced instead when using `get` instead of `exists`:
```
     FirebaseError: 7 PERMISSION_DENIED:
Service call error. Function: [get], Argument: [path_value {
  segments {
    simple: "databases"
  }
  segments {
    simple: "(default)"
  }
  segments {
    simple: "documents"
  }
  segments {
    simple: "test"
  }
  segments {
    simple: "toms-profile"
  }
}
]. for 'create' @ L12
```

This also seems to affect `getAfter` and `existsAfter`.

(Please let me know if this is actually working and is just a result of misconfiguration, I've been pulling my hair out over this).

**Comment by bradleymackey** [comment]
I figured it out - I was using the a `initializeAdminApp` to add data to the database, which cannot be discovered by test instances created with `initializeTestApp`. This is a bit of a hairy corner and I will adjust this issue accordingly.

**Comment by samtstern** [comment]
@bradleymackey that's not quite true, `initializeAdminApp` and `initializeTestApp` can certainly talk to the same database and populate data that the others can see ... just make sure the `projectId` fields match otherwise you're talking to two separate databases!

**Comment by bradleymackey** [comment]
You're 100% correct - it was some stupid misconfiguration on my end. Thanks a lot for the help.
