### ISSUE TITLE
Invalid value for config firebase.databaseURL: ....

### ISSUE THREAD

**Issue by StuStirling** [firebase/firebase-tools#2993]
### [REQUIRED] Environment info

**firebase-tools:** 9.1.0

**Platform:** macOS

### [REQUIRED] Test case

1. Create a firebase project 
2. Create a realtime database in region `Belgium (europe-west1) [beta]`

### [REQUIRED] Steps to reproduce

1. Using Firebase CLI, set the created firebase project as active project.
2. Attempt to deploy a firebase function to the default database or even specify the `database({instance})`

### [REQUIRED] Expected behavior

The cloud functions to be uploaded successfully.

### [REQUIRED] Actual behavior

The cloud function upload fails with the following output

```
✔  functions: Finished running predeploy script.
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
✔  functions: required API cloudbuild.googleapis.com is enabled
✔  functions: required API cloudfunctions.googleapis.com is enabled
i  functions: preparing functions directory for uploading...

Error: Invalid value for config firebase.databaseURL: https://███████-default-rtdb.europe-west1.firebasedatabase.app
```

I can successfully deploy the exact same functions to a different project. The difference being, I believe, the default realtime database is set to one in `United States (us-central1)` even though its disabled. Then when I specify my `europe-west1` instance for my functions the upload is successful.

**Comment by samtstern** [comment]
@StuStirling I'm not able to reproduce this on `9.1.1` which includes some database URL related fixes, can you try that? (Although due to issue #3000 you may want to wait for `9.1.2`)

Here's what I did:

1. Create a brand new project in the console
2. In the console create a RTDB instance in the EU region
3. Deploy these cloud functions:

```js
const functions = require("firebase-functions");
const admin = require("firebase-admin");
admin.initializeApp();

exports.onDatabase = functions.database.ref('/test/{child}').onWrite(async (change, ctx) => {
  console.log("onDatabase", change.after.ref.toString());
  return true;
});
```

Here are the logs:
```
=== Deploying to 'fir-dumpster-eu'...

i  deploying functions
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
✔  functions: required API cloudfunctions.googleapis.com is enabled
⚠  functions: missing required API cloudbuild.googleapis.com. Enabling now...
✔  functions: required API cloudbuild.googleapis.com is enabled
i  functions: preparing functions directory for uploading...
i  functions: packaged functions (20.95 KB) for uploading
✔  functions: functions folder uploaded successfully
i  functions: creating Node.js 12 function onDatabase(us-central1)...
✔  functions[onDatabase(us-central1)]: Successful create operation. 
```

I also modified some data in the console and I can see that the function ran correctly:
![Screen Shot 2021-01-07 at 11 34 08 AM](https://user-images.githubusercontent.com/8466666/103888227-6727e280-50b2-11eb-8a8f-b98f22634af0.png)

**Comment by mortenbekditlevsen** [comment]
I hope it's ok to open this issue again.
I have a project with two instances in us-central1 and for those I can create rtdb triggers just fine.

I added a third instance in eu-west1 and tried to add a trigger to it - both using:

```
functions.region("eu-west1").database.instance("ka-ching-base-dev-3").ref(...).onWrite(...)
```
and without setting the region:
```
functions.database.instance("ka-ching-base-dev-3").ref(...).onWrite(...)
```

Where 'ka-ching-base-dev-3' is the database instance residing in 'eu-west1'.

In both cases, when deploying I get something like:
```
021-09-10 15:11:40.483 CESTShard-b-Cron-mobilePayConfigurationrxb9m0zpruqw [2021-09-10T13:11:40.482Z] @firebase/database: FIREBASE WARNING: Database lives in a different region. Please change your database URL to https://ka-ching-base-dev-3.europe-west1.firebasedatabase.app (https://ka-ching-base-dev-3.firebaseio.com)
[2021-09-10T13:11:40.482Z] @firebase/database: FIREBASE WARNING: Database lives in a different region. Please change your database URL to https://ka-ching-base-dev-3.europe-west1.firebasedatabase.app (https://ka-ching-base-dev-3.firebaseio.com)
```

and the function times out.

I would assume that triggering on a database instance in a different region also automatically connects to that database?
