### ISSUE TITLE
error when installing firebase over slow connection: `OpenSSL SSL_read: Connection reset by peer, errno 104`, `Pkg: Error reading from file`

### ISSUE THREAD

**Issue by tiziano88** [firebase/firebase-tools#2995]
### [REQUIRED] Environment info

**firebase-tools:**

**Platform:** Linux

### [REQUIRED] Test case

n/a

### [REQUIRED] Steps to reproduce

Running the following command

```
curl -sL https://firebase.tools | bash
```

on linux machine with a slow connection, causes the download to be interrupted before the binary is completely downloaded. Nevertheless, the installer just continues installing the corrupted binary and showing the `All done!` message, but obviously the installed binary does not work at all.

### [REQUIRED] Expected behavior

- the server should allow for a longer timeout, since the firebase binary is quite large, and currently it is impossible to download it over a slow connection
- in case of a download error, the installer should not pretend the binary is correct, and instead should show a clearer error and not actually install a corrupted binary (which also makes the installer not work the next time, since it detects that a binary is already there)

### [REQUIRED] Actual behavior

```
-- Checking for existing firebase-tools on PATH...
-- Checking your machine type...
-- Downloading binary from https://firebase.tools/bin/linux/latest
######################################################################## 100.0%#=#=-#  #              ######################################################################## 100.0% -=O=#  #    #   #     ######################################################################## 100.0%  -=O=#   #   #    #   #########################################                                 57.7%
#########################################                                 57.7%
#######################################################################   99.2%curl: (56) OpenSSL SSL_read: Connection reset by peer, errno 104

-- Setting permissions on binary...
Pkg: Error reading from file.
Something went wrong, firebase has not been installed.
Please file a bug with your system information on Github.
https://github.com/firebase/firebase-tools/
-- All done!
```

**Comment by samtstern** [comment]
@abeisgoat this might be hard to reproduce but maybe see if you can get this to happen?

**Comment by lobertrand** [comment]
I get the same error when using any flavor of the `firebase` command (`firebase`, `firebase -version`, `sudo firebase`, `sudo firebase -h`...). It only prints `Pkg: Error reading from file.`.

I tried installing firebase using Pamac (AUR package), using `npm install -g firebase` and using `curl -sL https://firebase.tools | bash`. I got the same error each time.

I'm using Linux Manjaro, which is based on Arch Linux :
```terminal
$ cat /proc/version
Linux version 5.10.84-1-MANJARO (builduser@fv-az72-805) (gcc (GCC) 11.1.0, GNU ld (GNU Binutils) 2.36.1) #1 SMP PREEMPT Wed Dec 8 09:50:30 UTC 2021
```

My network connexion is pretty fast.

**Comment by yuchenshi** [comment]
@lobertrand would you mind uninstalling and trying the installation script again? If you still see such issues even after reinstalling, please post `md5sum $(which firebase)` so we can see if the file is corrupted somehow.

**Comment by lobertrand** [comment]
I finally tried downloading and using the standalone binary for linux and it worked fine ^^ (under the name `firebase-tools-linux`)
Now, il tried the installation script again and it worked too, I don't know why :
```
curl -sL https://firebase.tools | bash
-- Checking for existing firebase-tools on PATH...
which: no firebase in (/home/loic/.opam/default/bin:/home/loic/.rvm/gems/ruby-2.7.0/bin:/home/loic/.rvm/gems/ruby-2.7.0@global/bin:/home/loic/.rvm/rubies/ruby-2.7.0/bin:/home/loic/.nvm/versions/node/v12.19.0/bin:/home/loic/Documents/apps/hbase-2.2.5/bin:/home/loic/.local/bin:/home/loic/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin:/home/loic/.rvm/bin:/home/loic/.rvm/bin:/usr/lib/jvm/default/bin:/usr/lib/jvm/jdk1.8.0_231:/usr/lib/jvm/jdk1.8.0_231/bin:/home/loic/.rvm/bin:/home/loic/Documents/apps/Maude-3.1-linux/maude-3.1/)
-- Checking your machine type...
-- Downloading binary from https://firebase.tools/bin/linux/latest
######################################################################## 100,0%######################################################################### 100,0%######################################################################### 100,0% ######################################################################## 100,0%
-- Setting permissions on binary...
-- Checking your PATH variable...
-- firebase-tools@10.1.4 is now installed
-- All Done!
$ firebase --version
10.1.4
$ md5sum $(which firebase)
917b462dcf1944ec1a62c4e7d1213075  /usr/local/bin/firebase
```

I also found the exact error message in a node package : https://unpkg.com/browse/pkg-fetch@2.3.7/patches/node.v4.8.3.patch
At line 308 : `console.error('Pkg: Error reading from file.');`. Maybe it has something to do with the previous error.

**Comment by yuchenshi** [comment]
Closing as transient
