### ISSUE TITLE
Version 9.1.1 broke firebase init and deploy

### ISSUE THREAD

**Issue by AggelosM** [firebase/firebase-tools#3000]
### [REQUIRED] Environment info

**firebase-tools:** 9.1.1

**Platform:** WSL2

### [REQUIRED] Test case

`firebase init` doesn't work without an argument, and `firebase serve` says "Error: An unexpected error has occurred."

When downgrading to 9.1.0 none of these problems occur.

### [REQUIRED] Steps to reproduce

Install the latest version and execute the above commands.

### [REQUIRED] Expected behavior

`firebase init` works without an argument, and `firebase serve` serves

### [REQUIRED] Actual behavior

`firebase init` doesn't work without an argument, and `firebase serve` says "Error: An unexpected error has occurred."

---------

**Comment by MartinSeeler** [comment]
I can confirm, happened to me, too. After downgrade to 9.1.0 everything works. 

```
❯ npm -v
7.3.0
❯ node -v
v15.5.1
```

**Comment by ralcar** [comment]
Same for me, how can such a huge bug slip through?

**Comment by samtstern** [comment]
Yikes ... I'll look into this now.  In the meantime please downgrade!

**Comment by samtstern** [comment]
I was able to confirm the `firebase init` error and find a quick fix.  I caused the error in #2946.

As for `firebase deploy` it seems to be working for me.  I just deployed Database, Firestore, Hosting, and Functions with the latest CLI.  Can someone here who is seeing a `firebase deploy` failure run `firebase --debug deploy` and show me the logs?

**Comment by AggelosM** [comment]
@samtstern I'm sorry I meant `firebase serve` not deploy! I edited the issue.

**Comment by samtstern** [comment]
@AggelosM thanks! I was able to find the error in `firebase serve`.  By the way `firebase serve` is mostly deprecated, try using `firebase emulators:start` instead!
