### ISSUE TITLE
Server Error. connect ETIMEDOUT 142.250.76.74:443

### ISSUE THREAD

**Issue by gurulnd-git** [firebase/firebase-tools#3005]
Error while trying to deploy my node js app on Firebase functions, i've been trying for two days now... but its the same issue....

couldn't deploy my updated, is painful... i tried everything ... but no changes

**Comment by bkendall** [comment]
Please follow the template when reporting issues. There's not enough information here to begin to help you, unfortunately. If this is a connection issue, try deploying on another network.
