### ISSUE TITLE
Clear user accounts endpoint not working as intended

### ISSUE THREAD

**Issue by hamboomger** [firebase/firebase-tools#3013]
### [REQUIRED] Environment info

**firebase-tools:**
9.1.2

**Platform:**
MacOS 11.0.1

### [REQUIRED] Test case
Request to:
```
DELETE http://localhost:9099/emulator/v1/projects/{projectId}/accounts
```

### [REQUIRED] Steps to reproduce

1. Run firebase auth emulator using FIREBASE_AUTH_EMULATOR_HOST=localhost:9099
2. Make a DELETE request to `http://localhost:9099/emulator/v1/projects/{projectId}/accounts` as described in the API
3. Get an authentication error

### [REQUIRED] Expected behavior
Delete all user accounts

### [REQUIRED] Actual behavior
Following response:
```
{
    "error": {
        "code": 401,
        "message": "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",
        "errors": [
            {
                "message": "Login Required.",
                "domain": "global",
                "reason": "required",
                "location": "Authorization",
                "locationType": "header"
            }
        ],
        "status": "UNAUTHENTICATED"
    }
}
```

**Comment by hamboomger** [comment]
If it's not a bug and is an intended behaviour, could you please add more information about the authentication credential to the [authentication api reference page](https://firebase.google.com/docs/reference/rest/auth#section-auth-emulator-clearaccounts)?

**Comment by samtstern** [comment]
@hamboomger can you try adding the `Authorization` header to your request with the value `Bearer owner`?  I'll also make sure we get the docs up to date.

**Comment by samtstern** [comment]
@yuchenshi is this a bug or a docs issue?

**Comment by hamboomger** [comment]
@samtstern yep, works with the `Authorization` header, thanks 👍

**Comment by yuchenshi** [comment]
I'd say we should drop the requirement for the `Authentication` header since it is confusing. It's an emulator-specific API anyway, plus clearing data in Firestore emulator doesn't require `Authentication` header either.
