### ISSUE TITLE
Firebase emulator port taken when saving

### ISSUE THREAD

**Issue by kickbk** [firebase/firebase-tools#3016]
I'm trying to run Firebase locally. I have `functions` and `firestore` running as emulators.
When I save an update to any of my files, it reloads firebase, as it should. However, it tries to run the emulator again on the same port it did before and since the port is still active, it throws an error `Could not start Firestore Emulator, port taken` that the port is taken. I tried adding specific port for the firestore emulator in firebase.json with this:

    "emulators": {
      "firestore": {
        "port": "2525"
      }
    }

But that doesn't really change the fact that it tries to re-run the emulator on port 2525 when I save and cannot because it's already taken.

To add more details from the log:
```
i  emulators: Starting emulators: functions, firestore
⚠  emulators: It seems that you are running multiple instances of the emulator suite for project my-app. This may result in unexpected behavior.
⚠  functions: The following emulators are not running, calls to these services from the Functions emulator will affect production: auth, database, hosting, pubsub
✔  functions: Using node@12 from host.
i  emulators: Shutting down emulators.
i  functions: Stopping Functions Emulator
i  hub: Stopping emulator hub
⚠  firestore: Port 2525 is not open on localhost, could not start Firestore Emulator.
⚠  firestore: To select a different host/port, specify that host/port in a firebase.json config file:
      {
        // ...
        "emulators": {
          "firestore": {
            "host": "HOST",
            "port": "PORT"
          }
        }
      }
i  emulators: Shutting down emulators.

Error: Could not start Firestore Emulator, port taken.

Having trouble? Try firebase [command] --help
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! functions@ serve: `npm run build && firebase emulators:start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the functions@ serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mememe/.npm/_logs/2021-01-11T21_21_03_874Z-debug.log
[nodemon] app crashed - waiting for file changes before starting...
```

What do I do?

**Comment by kickbk** [comment]
For now, the only way I can keep working is by firing this script command `npm run build && npx kill-port 2525 && firebase emulators:start` so it kills the firestore emulator port whenever it reloads. Obviously that's stupid, so I'd really appreciate you guys letting me know how this should be done correctly.

**Comment by samtstern** [comment]
@kickbk can you avoid restarting the Firestore emulator on every file save? Unfortunately this is not something we can fix because many operating systems mark a port as "taken" for a few seconds (sometimes up to 30s) after it is released. So if you stop and start the emulators too often you may see errors like this.

**Comment by DavuluriHemanthChowdary** [comment]
When you run `firebase emulators:start` there will another two JDK terminals which pop up on the screen. One is for the Firestore emulator and another one is for the Database emulator. when you stop the emulators by `ctrl+c` in the main terminal where you ran the command initially it does not close the other two popped terminals by default. That means the firestore and database ports are still working. so make sure you close those two popped terminals too. it works fine on mine every time. Hope this is helpful.
![image](https://user-images.githubusercontent.com/73163402/104923344-ef1ac000-59c1-11eb-8bb9-022478720b52.png)

**Comment by micaiah-effiong** [comment]
On `mac` the process running on this port turns out to be an AirPlay server. You can deactivate it in System Preferences › Sharing and uncheck AirPlay Receiver to release port 5000.

Credit [Nono.MA](https://nono.ma/port-5000-used-by-control-center-in-macos-controlce#:~:text=The%20process%20running%20on%20this,Receiver%20to%20release%20port%205000%20.)
