### ISSUE TITLE
Emulator Hub not running without default project

### ISSUE THREAD

**Issue by grundid** [firebase/firebase-tools#3020]
### [REQUIRED] Environment info

**firebase-tools:** 9.1.2

**Platform:** macOS

### [REQUIRED] Test case

see steps to reproduce

### [REQUIRED] Steps to reproduce

firebase init
-> Select "Emulators: Set up local emulators for Firebase features"
-> Select "Don't set up a default project"
-> Select "Firestore Emulator"
 Would you like to enable the Emulator UI? (Y/n)
-> Select Y

now launch emulator with
firebase emulators:start

### [REQUIRED] Expected behavior

One would expect that the Emulator UI would start without a default project or at least give a warning or error why the emulator UI has not started.

### [REQUIRED] Actual behavior

You only see a message "Emulator Hub not running".

> All emulators ready! It is now safe to connect your app. 
> 
> ┌───────────┬────────────────┐
> │ Emulator  │ Host:Port      │
> ├───────────┼────────────────┤
> │ Firestore │ localhost:8080 │
> └───────────┴────────────────┘
>   Emulator Hub not running.
>   Other reserved ports: 
>

**Comment by samtstern** [comment]
Thanks for the feedback!  This logging was improved in #3021
