### ISSUE TITLE
Firebase functions emulator ignores region

### ISSUE THREAD

**Issue by JaapWeijland** [firebase/firebase-tools#3031]
### [REQUIRED] Environment info

**firebase-tools:**
9.2.0

**Platform:**
macOS
### [REQUIRED] Test case

`export const api = region('europe-west3').https.onRequest(server);`

When starting the emulator, the emulator correctly outputs the following URL:

`✔  functions[api]: http function initialized (http://localhost:5000/**[some-project]**/europe-west3/api).`

However, when visiting that URL, a 404 is given. Going to the following URL works however:

`http://localhost:5000/**[some-project]**/us-central1/api`

### [REQUIRED] Steps to reproduce
See above

### [REQUIRED] Expected behavior
Hitting the `europe-west3` URL working like the `us-central1` version does.

### [REQUIRED] Actual behavior
The `europe-west3` version hits a 404, while `us-central1` works.

**Comment by samtstern** [comment]
@JaapWeijland I am not able to reproduce this behavior.  Here are my two functions:

```js
const functions = require("firebase-functions");

exports.helloWorld = functions.https.onRequest((req,res) => {
    res.send("Hello, America\n");
});

exports.helloEurope = functions.region('europe-west3').https.onRequest((req, res) => {
    res.send("Hello, Europe\n");
});
```

When I run `firebase emulators:start` I see these logs (among others):
```
✔  functions[helloWorld]: http function initialized (http://localhost:5001/fir-dumpster/us-central1/helloWorld).
✔  functions[helloEurope]: http function initialized (http://localhost:5001/fir-dumpster/europe-west3/helloEurope).
```

I am able to `curl` both functions:

```
$ curl http://localhost:5001/fir-dumpster/us-central1/helloWorld
Hello, America
```

```
$ curl http://localhost:5001/fir-dumpster/europe-west3/helloEurope
Hello, Europe
```

Is there more to your situation? Do you possibly have two functions with the same name in different regions? If so that's a known limitation of the emulator right now.

**Comment by JaapWeijland** [comment]
Thanks for your answer! I oversimplified my example a bit.

What I actually have, is the following:

```
import {NestFactory} from '@nestjs/core';
import {AppModule} from './app.module';
import * as helmet from 'helmet';

import {ExpressAdapter} from '@nestjs/platform-express';
import * as express from 'express';
import {region} from 'firebase-functions';

const server = express();

server.get('/', (req, res) => {
    res.send('lol!');
});

// export const createNestServer = async (expressInstance: express.Express) => {
//     const _app = await NestFactory.create(AppModule, new ExpressAdapter(expressInstance), {
//         cors: true,
//     });
//     // app.use(helmet()); // protect from HTTP vulnerabilities
//     await _app.init();
// };

// createNestServer(server)
//     .then((v) => console.log('Nest Ready'))
//     .catch((err) => console.error('Nest broken', err));

export const api = region('europe-west3').https.onRequest(server);

export const europe = region('europe-west3').https.onRequest((req, res) => {
    res.send('Hello Europe');
});

```

I deliberately left the comments there. As you see, I'm experimenting with NestJS on Firebase. If filtered the issue down to be associated with Express though, so I'm not sure if NestJS has to do with anything here.

As you see, I gave the Express server to the endpoint to handle the traffic. For testing purposes, I added a regular signature to another endpoint. the `api` endpoint does not work with the `europe-west3` region, however, it works with `us-central1`. The `europe` endpoint does work as intended.

So, I think it has something to do with Express.

**Comment by samtstern** [comment]
@JaapWeijland ah that helps thanks!  I was able to roll a fix into this PR I was already working on:
https://github.com/firebase/firebase-tools/pull/3033

**Comment by JaapWeijland** [comment]
Thanks for including this in your PR, alas it does not seem to work here. I am using `firebase-tools v9.2.1` now and my express routes are still not accessible through `europe-west3` but still are with `us-central1`.

**Comment by samtstern** [comment]
@JaapWeijland can you show me the smallest test case that reproduces the issue on the latest version?

**Comment by JaapWeijland** [comment]
Ha Sam, I already deleted my comment. I was still using the old version when I thought I installed the newer one. I can confirm that latest version fixes the issue.

**Comment by samtstern** [comment]
@JaapWeijland oh thank you!  I use GitHub through my email mostly so I didn't notice it was deleted.  Appreciate the super fast reply.

**Comment by dzivoing** [comment]
This is still happening to me i have tried

```
setGlobalOptions({ region: 'europe-west1' });
```

and 

```
export const myFunction = onRequest({
  region: "europe-west1"
}, async (req: any, res: any) => {
});
```

For some reason emulator always runs with us-central1 

http://127.0.0.1:5001/myProject/us-central1/myFunction
