### ISSUE TITLE
Clound Functions Emulator Not handling query parameters for functions deployed locally. 

### ISSUE THREAD

**Issue by ansaardollie** [firebase/firebase-tools#3032]
When deploying functions locally using the emulator, any time a request is to a function and the URL used to make that request has query parameters, the response is HTTP 400 error. 

The following function was used:
```
export const helloWorld = functions.https.onRequest((req,res) => {
    console.log(req.query);
    res.send("Hello World");
});
```

When requesting this function using the url:
http://localhost:5001/{projectName}/{location}/helloWorld?id=test

I get a 400 error and in the emulator log the following happens:
function[helloWorld]
Beginning execution of "helloWorld"
14:52:13
W
function[helloWorld]
Your function timed out after ~60s. To configure this timeout, see
      https://firebase.google.com/docs/functions/manage-functions#set_timeout_and_memory_allocation.
14:52:13
I
function[helloWorld]
C:\Users\Ansaar Dollie\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:640
14:52:13
I
function[helloWorld]
            throw new Error("Function timed out.");
14:52:13
I
function[helloWorld]
            ^
14:52:13
I
function[helloWorld]

14:52:13
I
function[helloWorld]
Error: Function timed out.
14:52:13
I
function[helloWorld]
    at Timeout._onTimeout (C:\Users\Ansaar Dollie\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:640:19)
14:52:13
I
function[helloWorld]
    at listOnTimeout (internal/timers.js:554:17)
14:52:13
I
function[helloWorld]
    at processTimers (internal/timers.js:497:7)

Firebase Tools version: 9.2.0

**Comment by samtstern** [comment]
@ansaardollie thank you for reporting this, I can confirm this is a bug and I am investigating. I have no idea how this got past our tests ... I thought we have one for query params.

**Comment by samtstern** [comment]
Ok this is caused by my recent changes, I can see the mistake in the logs:
```
[2021-01-14T14:03:57.461Z] [functions] Got req.url=/fir-dumpster/us-central1/helloWorld?id=ok, mapping to path=?id=ok
```

**Comment by bynicodevelop** [comment]
Hello, 

I have an equivalent error with firebase emulators.

My code is 

```
exports.populate = functions
  .https.onRequest(async (request, response) => {
    console.log(request.query);

    response.json({
      status: "ok"
    });
  });
```

My http request is : 

http://localhost:5001/projectID/locationID/development-populate?n=10

And i have this error : 

<img width="552" alt="Capture d’écran 2021-01-15 à 11 49 12" src="https://user-images.githubusercontent.com/32275195/104716083-b19b0600-5727-11eb-9e65-2990430d6229.png">

My version of firebase is 9.2.0

**Comment by samtstern** [comment]
@bynicodevelop this will be fixed in the next release, either `9.2.1` or `9.3.0` depending on what else ships.

**Comment by bynicodevelop** [comment]
Thanks for the quick answer, but how can I update firebase tools to avoid this problem now?


Because I'm stuck: D

maybe: npm i -g firebase-tools @ master?

**Comment by bynicodevelop** [comment]
Sorry,

supid question :D 

npm i -g firebase-tools@9.1.2
