### ISSUE TITLE
Do the emulators support multiple/namespaced databases?

### ISSUE THREAD

**Issue by mothershipper** [firebase/firebase-tools#3050]
### [REQUIRED] Environment info

**firebase-tools:** 9.1.0

**Platform:** macOS

### [REQUIRED] Test case

```bash
firebase emulators:start
```

```typescript
     import * as admin from 'firebase-admin'
     // First app should get app-one as a namespace in the emulator(s)
     const testdbOne = admin.initializeApp({
      credential: admin.credential.applicationDefault(),
      // totally bogus, but the env var will override this.
      databaseURL: 'https://someapp.example.com',
      projectId: 'app-one'
    })
    // Second app should get app-two as a namespace in the emulator(s)
    const testdbTwo = admin.initializeApp({
      credential: admin.credential.applicationDefault(),
      // totally bogus, but the env var will override this.
      databaseURL: 'https://somothereapp.example.com',
      projectId: 'app-two'
    })
```

### [REQUIRED] Steps to reproduce

```bash
firebase emulators:start
```

### [REQUIRED] Expected behavior

I'd like to be able to host multiple databases in the firebase emulator, but struggling to make that work.  This is more of a question of whether or not this is supported.  The TL;DR; is that we have our test suite split into multiple parallel runs, but they share a network. We'd like to run a single emulator instance for all the tests, but each parallel run needs to have a namespaced database so the tests won't conflict with each other.

### [REQUIRED] Actual behavior

Running the above code with different project IDs re-use the same database namespace, and our tests conflict with each other.

**Comment by samtstern** [comment]
@mothershipper the emulators do support this case but the `projectId` field is unrelated to the Realtime Database namespace. 

If you want to use `app-two` as your namespace you should set `https://app-two.firebaseio.com` as your `databaseUrl`.  When the `FIREBASE_DATABASE_EMULATOR_HOST` env var is set this will be rewritten as something like `http://localhost:8000?ns=app-two`.
