### ISSUE TITLE
Firebase SDK proxy error: net::ERR_CONTENT_DECODING_FAILED 200 (OK)

### ISSUE THREAD

**Issue by davidbielik** [firebase/firebase-tools#3052]
### [REQUIRED] Environment info

**firebase-tools:**
9.2.1

**Platform:**
macOS
### [REQUIRED] Test case

1. Unzip, and run `firebase emulators:start --only hosting --project your-project-id` from within the directory
2. Load `http://localhost:5000/`
3. `GET http://localhost:5000/__/firebase/8.2.3/firebase-app.js net::ERR_CONTENT_DECODING_FAILED 200 (OK)`

[firebase-issue-3041.zip](https://github.com/firebase/firebase-tools/files/5817143/firebase-issue-3041.zip) - same repro files as #3041 

### [REQUIRED] Steps to reproduce

1. Make index.html which contains:
```
<script src="/__/firebase/8.2.3/firebase-app.js"></script>
<script src="/__/firebase/8.2.3/firebase-analytics.js"></script>
<script src="/__/firebase/init.js"></script>
```

2. Start the hosting emulator:
```
firebase emulators:start --only hosting
```

3. Load `http://localhost:5000/` and inspect javascript errors

### [REQUIRED] Expected behavior

`firebase-app.js` loads correctly

### [REQUIRED] Actual behavior

> GET http://localhost:5000/__/firebase/8.2.3/firebase-app.js net::ERR_CONTENT_DECODING_FAILED 200 (OK)

This does not seem to happen in production and only affects the emulator's response of the firebase libraries.

**Comment by samtstern** [comment]
@bkendall this seems like it could be related to your recent changes in #3042

**Comment by bkendall** [comment]
I'm able to replicate this, but it's `8.2.2/firebase-analytics` that's not loading for me. Interestingly, I updated it to `8.2.3` and the issue went away. I wonder if there's a problem with that particular version of the file? I can look a bit more, but could you try changing the version number and seeing if the issue persists? When I `curl` the `8.2.2` version of the file on the local emulator, the output is definitely incomplete, so that definitely flags an issue for me of some kind.

**Comment by davidbielik** [comment]
hey @bkendall upgrading the version number still showed the error for a few refreshes, but then resolved itself somehow. I'm unable to make a consistent reproduction case unfortunately.

**Comment by bkendall** [comment]
Yeah, I am in the same boat. I actually think this and #3055 are pushing me towards there being some kind of issue in the proxying logic where the response is being truncated. Unfortunately it's tricky to debug this kind of issue, so I'll need some time. Thanks for raising and your patience.

**Comment by abrice** [comment]
In javascript, I had the error with 8.2.3 earlier today so I changed the link to 8.2.10 and it resolved, all back to normal. I have never had the error before. 

Now it has just failed with:
GET http://localhost:5000/__/firebase/8.2.10/firebase-app.js net::ERR_CONTENT_DECODING_FAILED 200 (OK)
and changing versions makes no difference.

So, Firebase dev is now dead. This is a big problem.
