### ISSUE TITLE
Large number of redundant log messages when using `emulators:exec` to run Jest unit tests

### ISSUE THREAD

**Issue by amkoehler** [firebase/firebase-tools#3056]
### [REQUIRED] Environment info

**firebase-tools:** 9.2.1

**Platform:** Ubuntu (WSL 2)

### [REQUIRED] Test case

1. Create 1 or more unit tests in the `functions` directory of a firebase project that tests firestore db operations
2. Use firebase `emulators:exec` to run the tests: `$ firebase emulators:exec --only firestore "jest --env node --runInBand"`

We have a set of unit tests for our cloud functions that uses jest. Previously we were using [online mode](https://firebase.google.com/docs/functions/unit-testing#online-mode) for these tests, which hit a live firestore database, but with the firestore emulator we can now run these tests locally. The tests still work well, but when running the test in CI with `emulators:exec` I am setting a very large number of log messages that look like this:

```
    console.log
      i  You have set FIRESTORE_EMULATOR_HOST=0.0.0.0:8080, this command will execute against the Firestore Emulator running at that address.

      at Console.log (../node_modules/winston/lib/winston/transports/console.js:79:23)
```

Screenshot from dev ops pipeline:

![image](https://user-images.githubusercontent.com/3598113/105087396-00b2a500-5a60-11eb-9816-e558a657d1a8.png)

### [REQUIRED] Steps to reproduce

This appears to happen only when using `emulators:exec` to run the tests. It is not an issue when starting the emulator in a separate terminal tab and running `jest` independently. Unsure if this issue is unique to jest but I don't think that would be the case. At the end of each test suits we import `firebase-tools` in node to clean up any collections in the test. This still works fine with the emulator, but wondering if it's causing the strange behavior.

```
import * as firebaseTools from 'firebase-tools';
import * as admin from 'firebase-admin';
import * as functions from 'firebase-functions';
import to from 'await-to-js';

async function cleanupFirestore() {
  // cleanup db
  const deleteOperations: Promise<admin.firestore.WriteResult>[] = [];
  const collectionsToDelete = [
    'collection1',
    'collection2',
    'collection3',
    // ... other collections
  ];
  for (const collection of collectionsToDelete) {
    deleteOperations.push(
      firebaseTools.firestore.delete(collection, {
        project: process.env.GCLOUD_PROJECT,
        recursive: true,
        yes: true,
        token: functions.config().fb.token,
      }),
    );
  }

  const [err, result] = await to(Promise.all(deleteOperations));

  if (err) {
    console.error('An error occured during firestore cleanup:');
    console.error(err);

    throw err;
  }

  return result;
}

export default cleanupFirestore;

```

### [REQUIRED] Expected behavior

Minor issue in the long run, but would have not expected so many redundant log messages in my tests.

### [REQUIRED] Actual behavior

See Test Case above.

**Comment by samtstern** [comment]
Assigning this to @abeisgoat to take a look since this concerns logging.

**Comment by amkoehler** [comment]
This appears to have been caused by my use of `firebase-tools` to clean up the db after each test. I found in the docs that the emulator has a [built-in way to clear the database between tests](https://firebase.google.com/docs/emulator-suite/connect_firestore#clear_your_database_between_tests) and the log messages no longer appear.
