### ISSUE TITLE
Data added to Firestore Emulator is not visible in the emulator suite

### ISSUE THREAD

**Issue by jmcdl** [firebase/firebase-tools#3062]
### [REQUIRED] Environment info

**firebase-tools:** 9.2.1

**Platform:** macOS Big Sur 11.1

### [REQUIRED] Test case

I'm not sure how to offer a test case for this issue as it requires running the Firebase Emulator locally and connecting it to a React web app.

### [REQUIRED] Steps to reproduce

define emulator configuration in firebase.json

```
"emulators": {
    "functions": {
      "port": 5001
    },
    "auth": {
      "port": 9099
    },
    "hosting": {
      "port": 5000
    },
    "firestore": {
      "port": 5002
    },
    "ui": {
      "enabled": true
    }
  },
  "firestore": {
    "rules": "firestore.rules",
    "indexes": "firestore.indexes.json"
  },
```

Configure app to use emulator:

```
import "firebase/auth";
export const FirebaseAuthApi = firebase.auth();
// eslint-disable-next-line react-hooks/rules-of-hooks
FirebaseAuthApi.useEmulator("http://localhost:9099/");

import "firebase/firestore";
export const FirestoreApi = firebase.firestore();
// eslint-disable-next-line react-hooks/rules-of-hooks
FirestoreApi.useEmulator("localhost", 5002);
```

1. Run `firebase emulators:start`
2. Run React app connected to Firebase Emulator with `npm start`
3. Create a user at the sign-up screen, which triggers a document to be created in a "users" collection

### [REQUIRED] Expected behavior
The user is created in Firebase Emulator Auth and the user's data is added to a User collection in the Firestore Emulator and the newly created user object can be seen from the emulator suite.

### [REQUIRED] Actual behavior

The user is created in Firebase Emulator Auth and the user's data is added to a User collection in the Firestore Emulator but the newly created user object is not shown in the emulator suite. 

The same behaviour is observed for any data that is created in the Firestore emulator. It appears to be created correctly, since logging in the browser console shows that the data queried from Firestore collections is retrieved and used correctly by the app, however the emulator suite firestore remains completely empty.

**Comment by jmcdl** [comment]
I realised that I was using the wrong firebase project in the terminal where I was running the emulator. By switching to the correct project with `firebase use` the emulator begun to show the data as expected. 

I'll close this and leave this here in case it helps anyone scratching their head about the same problem.

**Comment by samtstern** [comment]
@jmcdl thank you for following up!
