### ISSUE TITLE
Firestore emulator ui bug

### ISSUE THREAD

**Issue by mfb-remotesocial** [firebase/firebase-tools#3068]
### [REQUIRED] Environment info

**firebase-tools:** 9.2.1

**Platform:** MacOS Catalina 10.15.7

### [REQUIRED] Test case

There seems to be a disconnect between Emulator UI and the Firestore Emulator data. I have had no issues with using a node script to bulk write data to localhost:8080 emulator in the past. As of yesterday, changes to the bulk update data are no longer reflected in the emulator UI or in the data available to the locally hosted client.

Data is however reflected within log output from within the script. 

### [REQUIRED] Steps to reproduce

1. Start the firebase emulators `firebase emulators:start`
2. Navigate to the emulator UI and see the state of the data
3. Run the following node.js code:
```
// require admin SDK
const admin = require('firebase-admin');

// init and run admin SDK
const options = { 
    projectId: 'rs-dev'
};
admin.initializeApp(options);

// sample data object to write to firestore emulator
const data = {
    games: {
        teamtaboo: {
            category: 'multi',
            name: 'Team Game'
        }    
    }
}

// connect to firestore via admin SDK
const firestore = admin.firestore();

// iterate through data and write to firestore
Object.entries(data).map( async ([key, value]) => {
    const collectionRef = firestore.collection(key);
    const preUpdateSnapshot = await collectionRef.get();
    preUpdateSnapshot.forEach((doc => {
        console.log(doc.id, '=>', doc.data());
    }));

    // iterate through each doc in the collection
    Object.entries(value).map( async ([key, value]) => {
        const docRef = collectionRef.doc(key);
        console.log(docRef);
        
        await docRef.set(value, { merge: true });
        const snapshot = await docRef.get();
        console.log(snapshot.data());
    });

    // list all docs in the collection
    const postUpdateSnapshot = await collectionRef.get();
    postUpdateSnapshot.forEach((doc => {
        console.log(doc.id, '=>', doc.data());
    }));
});
```
4. Note: the data appears to have been updated in Firestore `postUpdateSnapshot` by the script correctly
5. Return to the Emulator UI, note: the data is not reflecting any changes
6. Firebase client application accessing the emulated data is also not showing the new data.

### [REQUIRED] Expected behavior

Changes to the local Firestore data should be reflected within the Emulator UI and available to the locally running firebase client application

### [REQUIRED] Actual behavior

Firestore data appears to be running but is not updatable by scripts. Changes to the data within the emulator UI are reflected within the client app and also shown in the collection data the next time the script is run. Changes made via the script no longer update the data on the local emulator or within the Emulator UI or the client app.

A script such as this one was working yesterday before the most recent emulator update.

**Comment by mfb-remotesocial** [comment]
Apologies if the format of this bug request is not correct... the issue only appeared today after updating to the most recent version of the emulator.

**Comment by samtstern** [comment]
@mfb-remotesocial a few questions:

1. Can you double check that you're using the Project ID `'rs-dev'` everywhere? This should be the project the Firebase CLI is using and also the project your client code is using in initializeApp()
1. You mention this stopped recently, are you able to make this work by downgrading your Firebase CLI to an older version? If so, which version?
1. Can you reproduce this with a simpler script? How about a script that just does a single write to Firestore. Your script has some async race conditions which could be complicating matters (outlined below)

Using `.map` with an `async` function is a bad pattern:
```js
Object.entries(value).map( async ([key, value]) => {
   // ...
});
```
The code will *not* wait for all of your Object.entries callbacks to complete, it will simply iterate over them and continue, with each `async` operation happening concurrently.  Instead do this:

```js
// Each loop iteration will wait before the next one happens
for (const [key, value] of Object.entries(map) {
  await something();
}
```

Or you could do this:

```js
const promises = Object.entries(value).map( async ([key, value]) => {
   // ...
});

// All loop iterations will happen concurrently but this line will wait for them all to finsh
await Promise.all(promises);
```

**Comment by mfb-remotesocial** [comment]
Hey Sam, thanks for the reply... I'll implement these changes and get back to you with a more detailed response shortly. This may well fix the problem.

**Comment by mfb-remotesocial** [comment]
> Can you double-check that you're using the Project ID 'rs-dev' everywhere? This should be the project the Firebase CLI is using and also the project your client code is using in initializeApp()

This was the issue and apologies for raising a bug unnecessarily... the CLI had been changed to use a different project. I'll close this and again, thanks for taking the time to look at it. Thanks also for the call-out on the async code, totally makes sense and I'll be sure to switch to the for...of loop instead.

**Comment by samtstern** [comment]
@mfb-remotesocial no problem! Project ID confusion is one of our top issues and I'm adding this conversation to my "list of evidence" so I'm glad you filed it.
