### ISSUE TITLE
oobCode not appearing after updateEmail is called while using emulators

### ISSUE THREAD

**Issue by Mattinton** [firebase/firebase-tools#3070]
### [REQUIRED] Environment info

**firebase-tools: 9.2.1**

**Platform: macOS**

### [REQUIRED] Test case

```js
await testFirebaseApp.auth().createUserWithEmailAndPassword('test@email.com', 'testing');
await testFirebaseApp.auth().currentUser?.updateEmail('test1@email.com');

const oobCodes = await axios.get(`http://localhost:9099/emulator/v1/projects/project-test/oobCodes`);
```

### [REQUIRED] Steps to reproduce

Running the code above

### [REQUIRED] Expected behavior

oobCodes contains an oobCode for test@email.com to revert the email

### [REQUIRED] Actual behavior

The response does not contain an oobCode to revert the email. But does contain oobCodes for other actions such as resetPassword and verifyEmail

**Comment by samtstern** [comment]
@yuchenshi I'm not familiar with what the correct behavior here should be ... does updating the user's email generate an OOB code?
