### ISSUE TITLE
Pub/Sub Emulator has exited with code: 1

### ISSUE THREAD

**Issue by janswist** [firebase/firebase-tools#3073]
### [REQUIRED] Environment info

**firebase-tools:** 9.2.1

**Platform:** macOS

### [REQUIRED] Test case

None

### [REQUIRED] Steps to reproduce

`firebase emulators:start --only pubsub`

### [REQUIRED] Expected behavior

Normal work.

### [REQUIRED] Actual behavior

```
> firebase emulators:start --only pubsub

i  emulators: Starting emulators: pubsub
i  pubsub: Pub/Sub Emulator logging to pubsub-debug.log
⚠  pubsub: Fatal error occurred: 
   Pub/Sub Emulator has exited with code: 1, 
   stopping all running emulators
i  pubsub: Stopping Pub/Sub Emulator
⚠  pubsub: Error stopping Pub/Sub Emulator
i  hub: Stopping emulator hub
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! functions@ serve-pubsub: `firebase emulators:start --only pubsub`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the functions@ serve-pubsub script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

It requires me to download Java runtime, but to download it Oracle requires me to register with putting a lot of data on their register form. That's not making any sense to me. Shouldn't it all be handled by `firebase init emulators`?

pubsub-debug.log
```
No Java runtime present, requesting install.
```

**Comment by samtstern** [comment]
@janswist unfortunately we can't bundle Java with our emulators, try installing via https://openjdk.java.net/ which shouldn't require any of the information that Oracle requires.

**Comment by janswist** [comment]
Got it! Thank you :)

One note for others: I found installation guide [right here](https://techoral.com/blog/java/install-openjdk-10-on-mac.html) because on openjdk site it wasn't properly showed.
