### ISSUE TITLE
Error: Failed to list Firebase projects. See firebase-debug.log for more info.

### ISSUE THREAD

**Issue by rajkumarboddu** [firebase/firebase-tools#3078]
I'm facing the below issue while running `firebase init`. Please find the debug log below.

>
=== Project Setup
[info] 
[info] First, let's associate this project directory with a Firebase project.
[info] You can create multiple project aliases by running firebase use --add, 
[info] but for now we'll just set up a default project.
[info] 
[debug] [2021-01-25T08:48:03.977Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects pageSize=100
[debug] [2021-01-25T08:48:04.155Z] Failed to make request to https://firebase.googleapis.com/v1beta1/projects?pageSize=100
[debug] [2021-01-25T08:48:04.464Z] FirebaseError: Failed to make request to https://firebase.googleapis.com/v1beta1/projects?pageSize=100
    at Client.doRequest (/usr/local/lib/node_modules/firebase-tools/lib/apiv2.js:194:19)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
[error] 
[error] Error: Failed to list Firebase projects. See firebase-debug.log for more info.

_Originally posted by @rajkumarboddu in https://github.com/firebase/firebase-tools/issues/2469#issuecomment-766658849_

**Comment by samtstern** [comment]
@rajkumarboddu please use the issue template when filing issues, this does not have all the information we need to debug.  This also does not look like a complete debug log, please post the full log contents.
