### ISSUE TITLE
Emulators Stop

### ISSUE THREAD

**Issue by deepalwin** [firebase/firebase-tools#3079]
What is the specific command to stop the emulators? like we have a command to start the emulators - emulators:start 

just like that what is the command to stop the emulators? Apart from manually killing the ports and using ctrl + C

**Comment by samtstern** [comment]
@deepalwin there is no command to stop the emulators, they are a long running process and you kill them by killing the process (Ctrl+C) as you said.

**Comment by deepalwin** [comment]
@samtstern Thanks for the quick answer however I am using it in a CI server. I cannot manually use the ctrl+c command. Any other options available?

**Comment by samtstern** [comment]
@deepalwin on a CI server it's better to use `emulators:exec` which will shut itself down when done.  So for example:

```
firebase emulators:exec "./my-test-script.sh"
```

This will:

1. Start the emulators
2. Run your custom test script and wait for it to finish
3. Shut down the emulators
