### ISSUE TITLE
Support multi-line strings in Database rules JSON

### ISSUE THREAD

**Issue by VincentJ711** [firebase/firebase-tools#308]
I'm trying to do a simple database rules deploy using version 3.6.0 and I recieve the following error on the CL. 

```
Error: There was an error loading firebase.json:

Unexpected token ' ' at 6:35
      ".write": "data.exists() &&
                                 ^
Having trouble? Try firebase deploy --help
```

My rules are saved in a file 'database_rules.json', my firebase.json file looks like this:

```
{
  "rules": "database_rules.json",
  "hosting": {
    "public": "./",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**",
      "functions",
      "gulpfile.js"
    ]
  }
}
```

My rules are the following:

```
{
  "rules": {
    ".validate": "auth !== null",
    "_const": {
      ".read":"true",
      ".write": "data.exists() &&
          newData.exists()"
    }
  }
}
```
I was under the impression multi-line strings were OK, as they publish fine in the rules editor on the console.  If this is intended, what's the work-around to get this to deploy whilst preserving the newlines so they stay readable in the console?

**Comment by mbleigh** [comment]
Multi-line strings are not currently supported by the CLI when deploying rules. I'll change the title of this to reflect that as a bug/feature request.

**Comment by VincentJ711** [comment]
Got it. Thanks!

**Comment by eliezedeck** [comment]
To add to this, I think the fact that it mentions `firebase.json` instead of the actual file that it doesn't like is misleading.

Naturally, people will look at the mentioned file, yet, the problem isn't really there. It is actually in the `database.rules.json`. While `firebase.json` read the file in the `{"database": {"rules": "..."}`, it should mention that the problem lyes in the referenced file.

This could be one of these cases where the tool confuses the developer instead of helping.

**Comment by nathanvogel** [comment]
This would also make my life easier 👍

**Comment by danielo515** [comment]
So it is now possible to use multiline strings on the database.rules.json? Any recommendation to make it work on VSCode? It is not valid JSON  so we can not use JSON as file type

**Comment by samtstern** [comment]
@danielo515 a good trick is to set your syntax highlighter in VSCode (or any IDE) to treat the rules JSON file as a JavaScript file.

**Comment by danielo515** [comment]
Thanks for the tip @samtstern but how that helps? Broken strings are also a syntax error on JS unless you use inverted ticks 
 ` `` `
And if that is supported inside a JSON file, at that point the file may be better defined as a JS file insted
