### ISSUE TITLE
Auth import using CSV format is broken

### ISSUE THREAD

**Issue by lpellegr** [firebase/firebase-tools#3085]
Using version 9.2.2 (I haven't tested with older versions), when you export users from Firebase auth in CSV format and then reimport them using the CSV file generated by the Firebase CLI tool, many accounts are skipped and not recreated.

Here are the commands for reproduction:

```
$ firebase auth:export users.csv --project my-project
Exporting accounts to users.csv
✔  Exported 1000 account(s) successfully.
✔  Exported 196 account(s) successfully.
```

```
$ firebase auth:import users.csv  --project my-project-staging
⚠  No hash algorithm specified. Password users cannot be imported.
Processing users.csv (274675 bytes)
Starting importing 921 account(s).
✔  Imported successfully.
```

As you can see, _1196_ accounts were expected but only _921_ are imported. The destination project did not include any Firebase users before starting the import. 

Passing options (hash algorithm, etc.) change nothing: the same number of accounts is still missing.

Hopefully, using the same commands but JSON format instead of CSV fixes this problem and all accounts are recreated.

**Comment by uhhhclem** [comment]
Could you please check the users.csv file to see if it contains 1196 lines?  That will help us narrow down where the problem's occurring.

**Comment by lpellegr** [comment]
```
$ wc -l users.csv 
1196 users.csv
```

**Comment by samhorlbeck** [comment]
Hi @lpellegr thanks for the report. Would you please follow up with Firebase support? Looking into this issue will likely require a bit more info and coordination: https://firebase.google.com/support

**Comment by lpellegr** [comment]
@samhorlbeck That's done.

**Comment by kmcnellis** [comment]
Going to close this for now.  Feel free to reopen if fixing this requires action from the CLI
