### ISSUE TITLE
Warning, estimating Firebase Config based on GCLOUD_PROJECT. Initializing firebase-admin may fail

### ISSUE THREAD

**Issue by skhaz** [firebase/firebase-tools#3086]
When using the firebase emulator with jest, a warning is displayed on the terminal:

> Warning, estimating Firebase Config based on GCLOUD_PROJECT. Initializing firebase-admin may fail

### [REQUIRED] Environment info

**firebase-tools:** 9.2.2

**Platform:** WSL2

### [REQUIRED] Steps to reproduce

Run any test with firebase emulators

### [REQUIRED] Expected behavior

No warnings shown

### [REQUIRED] Actual behavior

Warning, estimating Firebase Config based on GCLOUD_PROJECT. Initializing firebase-admin may fail

**Comment by skhaz** [comment]
That's way everbody prefers AWS.

**Comment by samtstern** [comment]
@skhaz can you provide a more complete reproduction case?  This warning does not happen on every single test, I have run many tests without triggering this warning.

**Comment by skhaz** [comment]
@samtstern there's no test case, just `admin.initializeApp()`

**Comment by samtstern** [comment]
@skhaz this is not the repo for the Firebase Admin SDK, this is the repo for the Firebase CLI.  Please provide a series of steps that demonstrates a bug in the Firebase CLI or there's not much we can do.

Also there's nothing wrong with that warning, it means what it says.  In your local environment without an explicit config provided the SDK will attempt to initialize by guessing the location of your project's default resources from `GCLOUD_PROJECT`. When running inside the Cloud Functions emulator we provide an explicit config based on your local firebase project which should avoid that problem.
