### ISSUE TITLE
cannot connect with firebase database using php ^5.14.1

### ISSUE THREAD

**Issue by sosi-bit** [firebase/firebase-tools#3090]
i try to connect firebase database using php and i get this error This site can’t be reachedlocalhost refused to connect. Try: Checking the connection Checking the proxy and the firewall ERR_CONNECTION_REFUSED

<?php
require_once'./vendor/autoload.php';
use Kreait\Firebase\Factory;
use Kreait\Firebase\ServiceAccount;

 $serviceAccount = ServiceAccount::fromJsonFile(__DIR__ . '/mykey.json');
 $firebase = (new Factory)

   ->withServiceAccount($serviceAccount)

    ->withDatabaseUri('https://mcnsweb-ea923-default-rtdb.firebaseio.com/')

   ->create();

 $database = $firebase->getDatabase();
?>

**Comment by samtstern** [comment]
@sosi-bit this is the repository for the Firebase CLI and is not the right place to debug PHP or Realtime Database issues.  Firebase does not have an official PHP SDK at all so I assume you're using a third-party library?  You should file a GitHub issue with the owner of that library.

**Comment by sosi-bit** [comment]
ok i will do that.
