### ISSUE TITLE
Getting metadata from plugin failed with error: invalid_grant

### ISSUE THREAD

**Issue by markgoho** [firebase/firebase-tools#3098]
### [REQUIRED] Environment info

**firebase-tools:** 9.2.2

**Platform:** Windows

### [REQUIRED] Test case

Trying to test an HTTP onRequest function that writes to the emulated Firestore.

### [REQUIRED] Steps to reproduce

**index.ts**
``` typescript
import * as functions from 'firebase-functions';

export const testFirestoreWrite = functions.https.onRequest(
  async (request, response) => {
    await (await import('./testWrite')).testWrite(request, response);
  },
);
```
**testWrite.ts**
``` typescript
import * as functions from 'firebase-functions';
import * as admin from 'firebase-admin';

admin.initializeApp();

export async function testWrite(
  request: functions.https.Request,
  response: functions.Response<unknown>,
) {
  const body = request.body;
  const { collection, docId, doc } = body;
  console.log({ collection, docId, doc });
  try {
    await admin.firestore().collection(collection).doc(docId).create(doc);
  } catch (e) {
    console.error(e);
  }
  response.send(body);
}
```
**functions.spec.js**
``` javascript
const { expect } = require('chai');
const test = require('firebase-functions-test')({
  projectId: process.env.GCLOUD_PROJECT,
});
const admin = require('firebase-admin');
const myFunctions = require('../lib/index');

describe('Unit tests', () => {
  after(() => {
    test.cleanup();
  });

  it('tests a firestore write', async () => {
    const req = {
      body: {
        collection: 'test-collection',
        docId: 'abc1234',
        doc: { name: 'Mark Goho' },
      },
    };

    const sendPromise = new Promise(resolve => {
      const res = {
        send: text => { resolve(text); },
      };
      myFunctions.testFirestoreWrite(req, res);
    });

    const body = await sendPromise;
    expect(body).to.eq(req.body);
  });
});
```

### [REQUIRED] Expected behavior

Currently this test passes because the assertion evaluates to true, but I'd also expect the firestore write to succeed as well.

### [REQUIRED] Actual behavior

- I've started the emulator with `cross-env GCLOUD_PROJECT=fakeproject firebase emulators:start --project=fakeproject --only=firestore,functions,auth` 
- Functions directory is being watched with `tsc watch`
- Tests are running with `mocha functions.spec.js --exit`

This is the error output (from the try/catch block above):
``` bash
Error: 400 undefined: Getting metadata from plugin failed with error: invalid_grant
    at Object.callErrorFromStatus (C:\Users\Mark\Documents\IdeaCrew\active-branch-tracker\functions\node_modules\@grpc\grpc-js\build\src\call.js:31:26)
    at Object.onReceiveStatus (C:\Users\Mark\Documents\IdeaCrew\active-branch-tracker\functions\node_modules\@grpc\grpc-js\build\src\client.js:176:52)
    at Object.onReceiveStatus (C:\Users\Mark\Documents\IdeaCrew\active-branch-tracker\functions\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:334:141)
    at Object.onReceiveStatus (C:\Users\Mark\Documents\IdeaCrew\active-branch-tracker\functions\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:297:181)
    at C:\Users\Mark\Documents\IdeaCrew\active-branch-tracker\functions\node_modules\@grpc\grpc-js\build\src\call-stream.js:130:78
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
Caused by: Error
    at WriteBatch.commit (C:\Users\Mark\Documents\IdeaCrew\active-branch-tracker\functions\node_modules\@google-cloud\firestore\build\src\write-batch.js:426:23)
    at DocumentReference.create (C:\Users\Mark\Documents\IdeaCrew\active-branch-tracker\functions\node_modules\@google-cloud\firestore\build\src\reference.js:285:14)
    at Object.testWrite (C:\Users\Mark\Documents\IdeaCrew\active-branch-tracker\functions\lib\testWrite.js:11:67)
    at C:\Users\Mark\Documents\IdeaCrew\active-branch-tracker\functions\lib\index.js:28:72 {
  code: '400',
  details: 'Getting metadata from plugin failed with error: invalid_grant',
  metadata: Metadata { internalRepr: Map {}, options: {} },
  note: 'Exception occurred in retry method that was not classified as transient'
}
```

### Side Note
This would be a great quickstart testing example to include in https://github.com/firebase/quickstart-testing

### UPDATE:
When running `firebase emulators:exec 'npm run test'` I am _not_ getting these errors. I can't discern what the difference is when running emulators using this command vs. `firebase emulators:start`

**Comment by markgoho** [comment]
Found an [interesting thread on Reddit](https://www.reddit.com/r/Firebase/comments/h778n2/error_using_prod_firestore_w_emulator_suite/) where a person _wants to connect to prod_ but is getting this error. Is that what's happening here? Somehow my code is trying to reach out to the production Firestore?

**Comment by kmcnellis** [comment]
When running your test with `firebase emulators:exec`, the cli is automatically setting some environment variables for you, corresponding to the hostname/port of each emulator. [[source]](https://github.com/firebase/firebase-tools/blob/3f27bd884b32657ade95502e6987785d228fb370/src/emulator/commandUtils.ts#L316)  The admin sdk in your function under test will look for those variables to correctly connect to the firestore emulator instead of production

However, since you are directly calling the functions code via mocha, those environment variables aren't set, and your code is connecting to production.  The error is generally related to the gcloud cli (see https://github.com/firebase/firebase-functions/issues/121), and should go away by talking to the emulators instead.

You can either run the test by using `firebase emulators:exec`, or by changing your test to make the request over the network (running `firebase emulators:start` outputs the address you'd need to call - mine is `localhost:5001`,  for example)

**Comment by markgoho** [comment]
> changing your test to make the request over the network (running `firebase emulators:start` outputs the address you'd need to call - mine is `localhost:5001`, for example)

@kmcnellis can you point me to an example of this? I have no idea what `changing your test to make the request over the network` means

**Comment by kmcnellis** [comment]
I mean by using the [node http](https://nodejs.org/api/http.html) package, or something like [axios](https://www.npmjs.com/package/axios).  It's an HTTP onRequest function, so you can just do a GET or POST request to localhost:5001/testFirestoreWrite

**Comment by markgoho** [comment]
Ah hah!

So this _kind of_ makes sense. You're saying because the functions are exposed locally (localhost:number), I can tweak my tests to just use a node-based http library to just hit the endpoints, and _then_ test the outcome of those functions.

Is this documented anywhere officially? I feel like the documentation around local testing (now that we have emulators) hasn't quite kept up with the speed of development (not a terrible problem!). Repos like the [quickstart-testing](https://github.com/firebase/quickstart-testing/tree/master/unit-test-cloud-functions) are great, but we need more examples of how to perform these common actions _with emulators_.

@samtstern do you think that quickstart repo (the simple HTTP function) could be altered/added-to to show this strategy that @kmcnellis is suggesting?

**Comment by samtstern** [comment]
For other people who get the `invalid_grant` issue and **are** trying to access production it may mean that your token is invalid for some reason and you need to log in again.  Try running:

```
firebase login --reauth
```

and

```
gcloud auth application-default login
```

**Comment by samtstern** [comment]
I opened https://github.com/firebase/quickstart-testing/issues/97 to track improving the documentation! Closing this here as I don't think there's a CLI bug.
