### ISSUE TITLE
Upgrade to SDK 3.x

### ISSUE THREAD

**Issue by ishitatsuyuki** [firebase/firebase-tools#310]
It seems you're using connecting to the legacy server using the 2.x SDK, while encouraging others to upgrade. What a shame.

Please consider upgrade the database related code in this SDK to 3.x.

**Comment by mbleigh** [comment]
We're aware of this, but there are some legacy compatibility issues for our special usage of Firebase in the CLI that will take a while to untangle. We will move off of 2.x at some point, but there's no timeline on when that will be able to happen.
