### ISSUE TITLE
firebase emulators:exec should pass down the arguments from command line

### ISSUE THREAD

**Issue by skhaz** [firebase/firebase-tools#3100]
`firebase emulators:exec` should pass down the arguments from command line. For example

``` json
"scripts": {
  "test":  "firebase emulators:exec --only firestore --project sample 'jest --runInBand'",
}
```

If I run 

``` bash
npm run test -- foobar
```

`firebase emulators:exec` should take the extra argument (`-- foobar`) and pass down to jest, like this

``` bash
firebase emulators:exec --only firestore --project sample 'jest --runInBand -- foobar'
```

**Comment by fox1t** [comment]
You can still achieve this even if the support is not native. Add a custom `./test.sh` bash script with this content
```bash
./node_modules/.bin/firebase emulators:exec --project trustlayer "cross-env NOLOG=true vitest run $*"
```
and add this script to the package.json
```json
"test": "./test.sh"
```
Now you can invoke it like this:
`pnpm run test --runInBand ./src/my1.test.ts ./src/my2.test.ts`

(we are using vitest and pnpm, but it will work the same with other test runners and package managers).

**Comment by skhaz** [comment]
Closing this issue since I am not using Firebase anymore
