### ISSUE TITLE
Firebase authentication sends request to live firebase project instead of firebase emulators on next.js project

### ISSUE THREAD

**Issue by gbibeaul** [firebase/firebase-tools#3102]
### [REQUIRED] Environment info

**firebase-tools:** 9.3.0

**Platform:** macOs

### [REQUIRED] Test case

This might be better asked inside the firebase-app repo but not sure where is best:

The issue appears to be around sending signup requests to the firebase auth emulators. When creating a user the live firebase projects receives the request instead of the authentication emulator. The firestore emulator however sends and receives requests.

File responsible with initializing firebase

```js
import firebase from 'firebase/app';
import 'firebase/auth';
import 'firebase/functions';
import 'firebase/firestore';
import config from 'firebaseConfig';

if (!firebase.apps.length) {
  firebase.initializeApp(config);
  if (process.env.USE_FIREBASE_EMULATOR) {
    firebase.auth().useEmulator('http://localhost:9099');
    firebase.firestore().settings({
      host: 'localhost:8080',
      ssl: false,
    });
  }
}

export const fb = firebase;
```
This is the consuming code:

```
import { fb } from 'utils/firebase';

  const handleOnSubmit = (e: React.FormEvent) => {
    e.preventDefault();

    fb.auth()
      .createUserWithEmailAndPassword(userEmail, userPassword)
      .catch((err) => {
        console.log(err.code, err.message);
      });
  };
```
The user is succesfully created but not in the firebase emulator instead the users are created inside the firebase live project. The following warning is displayed indicating the auth emulators are properly connecting:
```
WARNING: You are using the Auth Emulator, which is intended for local testing only.  Do not use with production credentials.
```

### [REQUIRED] Steps to reproduce

1. start application with USE_FIREBASE_EMULATOR env var set
2. register user

### [REQUIRED] Expected behavior

user gets created in firebase emulator

### [REQUIRED] Actual behavior

user gets created in firebase live project

**Comment by yuchenshi** [comment]
Thanks for the report! This seems like an issue with the JS Auth SDK, and in order for us to dig into this, would you please:

1. Make sure you're using the latest stable JS SDK version (and please post the version number).
2. Add `console.log(fb.auth().emulatorConfig)` right before you create user -- this should log emulator config if enabled.
3. Open Chrome DevTools (Network tab) and then perform the button click, and pay special attention to see where new requests are actually going to. Feel free to copy / paste URLs or use screenshots.

----

Aside: I know this isn't really a solution, but note that the Auth Emulator does not validate the `apiKey` like production. This means you can conditionally swap out the key to `"fake-api-key"` or something like that (in your case, switching on `USE_FIREBASE_EMULATOR`). Hopefully, this can give you some confidence that even if it does hit production, it won't succeed and will fail in an obvious way.

**Comment by gbibeaul** [comment]
Sounds good I'll do this over the weekend!

**Comment by Ciph3rzer0** [comment]
Hope I can comment without reopening.  If anyone else finds themselves here, NextJS env variables are not passed to the browser unless they are prepended with "NEXT_PUBLIC", so if you want an emulated flag, use:
```bash
NEXT_PUBLIC_EMULATED=true
```
Then check if that new env variable exists instead, and the code above should work (mine was basically identical).
