### ISSUE TITLE
Error with deploying multiple functions

### ISSUE THREAD

**Issue by nirinsanity** [firebase/firebase-tools#3106]
### Related issues

https://github.com/firebase/firebase-functions/issues/672

### [REQUIRED] Version info

**node:** 12.18.1

**firebase-functions:** 3.13.1

**firebase-tools:** 9.2.2

**firebase-admin:** 8.10.0

### [REQUIRED] Test case

firebase deploy --only functions:saveGarment,functions:initiatePayment

### [REQUIRED] Steps to reproduce

I defined two functions saveGarment and initiatePayment and deployed them using the above command. 

### [REQUIRED] Expected behavior

I think it is supposed to deploy both the functions in a single command, speeding up the deployment process.

### [REQUIRED] Actual behavior

+  functions: Finished running predeploy script.
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
+  functions: required API cloudbuild.googleapis.com is enabled
+  functions: required API cloudfunctions.googleapis.com is enabled
i  functions: preparing functions directory for uploading...
i  functions: packaged functions (65.67 KB) for uploading
+  functions: functions folder uploaded successfully
i  functions: current functions in project: ext-firestore-send-email-processQueue(asia-east2), cancelPayment(us-central1), checkForExistingUser(us-central1), creditPurchaseNotification(us-central1), deleteGarment(us-central1), deleteTemplate(us-central1), feedbackNotification(us-central1), indexGarments(us-central1), indexTemplates(us-central1), initiatePayment(us-central1), newUserNotification(us-central1), newUserSignup(us-central1), paymentConfirmation(us-central1), saveAvatar(us-central1), saveGarment(us-central1), sendPurchaseMail(us-central1), signS3(us-central1), signUpFailed(us-central1), unindexGarments(us-central1), unindexTemplates(us-central1), updateGarments(us-central1), updateTemplates(us-central1), uploadTemplate(us-central1)
!  functions: the following filters were specified but do not match any functions in the project: saveGarment functions

### Were you able to successfully deploy your functions?

Deploying the functions one-by-one works fine. But combining two or more functions in a single deployment seems to throw the error:
functions: the following filters were specified but do not match any functions in the project: saveGarment functions

**Comment by Hivemind9000** [comment]
I am having the same problem. Seems to have happened fairly recently (last month or so), possibly after I upgraded from Node 10 to Node 14 (but that could be coincidental). Deploys all functions, or one at a time, fine. But if I try two functions using the syntax as documented and used by the OP, it fails silently. Says "Deploy Complete!" at the end, but the two functions are not deployed.

Exact command used (w/ latest firebase tools version):

`firebase deploy --only functions:setAppMemberSettings,functions:setAppSettings`

I suspected that "--only" is somehow not handling the comma delimiter... ?

**Comment by taeold** [comment]
I just gave a try in my project, and commands like below worked as expected:

```
firebase deploy --only functions:onpubsubv2,functions:onstoragev2
```

Maybe we silently made a bugfix in between the report of this bug and today. Can folks give the latest CLI version a try? @Hivemind9000 @nirinsanity

**Comment by Hivemind9000** [comment]
Thanks @taeold. Tried it this morning and it's working fine now. I have been avoiding using the deploy command like this since I posted here, so am unsure when exactly it was fixed. Cheers.

**Comment by taeold** [comment]
@Hivemind9000 Good to know. @nirinsanity Closing the issue for now. Let us know if you continue to have issues.

**Comment by nirinsanity** [comment]
I will try using the command in the coming few days and I'll try to update here once it's successful.

**Comment by Wellitonzs** [comment]
I was having this same problem when trying to deploy multiple functions and, after searching the internet, I discovered that to solve the problem it is necessary to execute the deployment as follows:

`firebase deploy --only "functions:func1,functions:func2"`

Remembering that so far, it is not possible to implement more than 3 functions at the same time.
Hope this helps 😃
