### ISSUE TITLE
Firebase Functions deploy requires keyboard input in GCP

### ISSUE THREAD

**Issue by krottv** [firebase/firebase-tools#3108]
### Environment

**firebase-tools:** Firebase CLI 9.3.0 (latest)

**Platform:** macOS bigSur 11.2

**NodeJs** Tried 10, 12, 14

### Steps to reproduce

I created a simple function from firebase documentation

```
const functions = require("firebase-functions");
// The Firebase Admin SDK to access Firestore.
const admin = require('firebase-admin');
admin.initializeApp();

// Take the text parameter passed to this HTTP endpoint and insert it into
// Firestore under the path /messages/:documentId/original
exports.addMessage = functions.https.onRequest(async (req, res) => {
  // Grab the text parameter.
  const original = req.query.text;
  // Push the new message into Firestore using the Firebase Admin SDK.
  const writeResult = await admin.firestore().collection('messages').add({original: original});
  // Send back a message that we've successfully written the message
  res.json({result: `Message with ID: ${writeResult.id} added.`});
});
```

deployed it - firebase deploy --only functions:

### Expected behavior

Upload it without exception 

### Actual behavior

Deployment error.
Build failed: Build error details not available. Please check the logs at xxx

Where I have a message 

```
replace /workspace/.runtimeconfig.json? [y]es, [n]o, [A]ll, [N]one, [r]ename: NULL
(EOF or read error, treating as "[N]one" ...)
```

Also it is related to issue from stackoverflow with no solution - https://stackoverflow.com/questions/65950774/firebase-functions-deploy-requires-keyboard-input-in-gcp

**Comment by taeold** [comment]
Thanks for reporting @krottv. We'll track this bug in https://github.com/firebase/firebase-tools/issues/3120 instead.
