### ISSUE TITLE
context.rawRequest.ip returns undefined in functions emulator

### ISSUE THREAD

**Issue by takaaa220** [firebase/firebase-tools#3115]
### [REQUIRED] Environment info

**firebase-tools:** 9.3.0

**Platform:** macOS

### [REQUIRED] Test case

I was trying to implement ip restriction in my function, but `context.rawRequest.ip` returned undefined in functions emulator. (actual my function in cloud functions returns valid ip address)

### [REQUIRED] Steps to reproduce

1. create a callable function (or onRequest)
2. start functions emulator (`firebase emulators:start`)
3. request to function

my function is below:
```typescript
export const ip = function.https.onCall((data, context) => {
  console.log(context.rawRequest.ip); // undefined

  return {
    ip: context.rawRequest.ip,
  }
});

---
$ curl -X POST -d '{"data":{}}' -H "Content-Type:application/json" http://localhost:5001/[PROJECT_NAME]/[REGION]/ip
> {"result":null}
```

### [REQUIRED] Expected behavior

 
context.rawRequest.ip returns valid ip address.

### [REQUIRED] Actual behavior

context.rawRequest.ip is undefined... ;(

**Comment by JFGHT** [comment]
Why was this closed? It's still a problem.
