### ISSUE TITLE
Improve error message for deploy Cloud Function missing config

### ISSUE THREAD

**Issue by MattMS** [firebase/firebase-tools#312]
In a project using Cloud Functions with a [Environment Configuration][1], when running `firebase deploy` before running `firebase functions:config:set`, the command throws a confusing error:

    Error: Error occurred while parsing your function triggers.
    TypeError: Cannot read property 'my_config_value' of undefined

My issue was that `my_config_value` was not as obviously named.
It was simply displaying `'value' of undefined` for a configuration of `my_config.value`.

The only file referenced in the stack trace was [triggerParser.js][2].

Maybe one simple fix would be a message if no configuration has been set?

[1]: https://firebase.google.com/docs/functions/config-env
[2]: https://github.com/firebase/firebase-tools/blob/master/lib/triggerParser.js

**Comment by mbleigh** [comment]
Unfortunately we have no real way of knowing what config values your code does or doesn't need. When you call `functions.config()` that returns a plain JS object so if you call `functions.config().foo.bar` and `foo` is not set, you'll see that kind of error.

You might consider using something like lodash's `get()` which lets you do something like:

    _.get(functions.config(), 'foo.bar', 'DEFAULT_VALUE_IF_UNSET');

Alternatively, you could throw your own error by checking for known needed config namespaces:

```js
['foo','bar'].forEach(ns => {
  if (!functions.config().ns) throw new Error(`Required config namespace ${ns} was not present.`)
});
```

**Comment by MattMS** [comment]
Thanks for the suggestions, I'll keep them in mind in future.

My issue was that I was deploying an existing code base to a new Firebase project, so there were no configuration values set.
A prompt triggered from finding a `config()` call when there are no configuration values set would have saved a lot of confusion.

I'm guessing this is a fairly edge case, but I thought I would raise it anyway for reference.

Thanks again. 😄
