### ISSUE TITLE
`database.rules.json` is not applied to the default RTDB instance in the emulator.

### ISSUE THREAD

**Issue by aameen951** [firebase/firebase-tools#3124]
Hi there,

This #2979 pull request fixed one part of the problem mentioned in #2965 where the default instance in hosting is different from the default instance in firebase-admin and both of them now reference the same instance which is `project-id-default-rtdb`.

However, the rules in `database.rule.json` are still being applied to `project-id` instead of `project-id-default-rtdb`, and I don't know how to change that manually.

### [REQUIRED] Environment info

firebase-tools: 9.3.0
Platform: Windows

### [REQUIRED] Test case

functions/index.js
```js
const admin = require("firebase-admin");

// After #2979, The following line will uses `http://localhost:9000?ns=project-id-default-rtdb`
admin.initializeApp();

admin.database().ref('test').set(1);
```

database.rules.json
```json
{
  "rules": {
    "test":{
      ".read": true
    },
    ".read": false,
    ".write": false
  }
}
```

### [REQUIRED] Steps to reproduce

1. Run the command: `curl localhost:9000/.settings/rules.json?ns=project-id-default-rtdb -H "Authorization: Bearer owner"`
2. The output is:
```json
{
    "rules": {
        ".read": true,
        ".write": true
    }
}
```
3. Run the command: `curl localhost:9000/.settings/rules.json?ns=project-id -H "Authorization: Bearer owner"`
4. The output is:
```json
{
  "rules": {
    "test":{
      ".read": true
    },
    ".read": false,
    ".write": false
  }
}
```

### [REQUIRED] Expected behavior

Since `project-id-default-rtdb` is now the default instance, the `database.rules.json` should also be applied to  `project-id-default-rtdb` instance instead of `project-id` instance.

### [REQUIRED] Actual behavior

Now, `database.rules.json` is applied to `project-id`.

**Comment by StevenHallLtd** [comment]
This has been driving me crazy.  Do you know of a workaround @aameen951?  I tried using the instance flag on the CLI, and also setting a target in firebase.json, but to no avail.  I'm not sure I'm setting it right as the docs aren't that explicit.

**Comment by samtstern** [comment]
Thanks @StevenHallLtd  and @aameen951 for reporting, let me take a look at this.

**Comment by aameen951** [comment]
@StevenHallLtd At first, I didn't know it was happening. But when I start to use queries with filters it became an annoying problem.
I worked around it by programmatically setting the rules on the database from firebase functions.
In your `functions/src/index.js`  do the following:

```ts
import * as functions from 'firebase-functions';
import * as admin from 'firebase-admin';

import { promises as fs } from 'fs';
import * as path from 'path';

// This is the database instance
const db = admin.database();

// check if the firebase function is running inside the emulator.
const IS_INSIDE_EMULATOR = process.env.FUNCTIONS_EMULATOR === 'true';

if(IS_INSIDE_EMULATOR)
{
  // read the rules file.
  fs.readFile(path.join(__dirname, "../../../database.rules.json"), 'utf8').then((source) => {
    // manually set the rules on the database.
    db.setRules(source);
  });
}

```

The one downside to this workaround so far is that if you change the rules file it won't update automatically, you have to go to any file that belongs to functions and save it to make functions reload and upload the rules file.

**Comment by samtstern** [comment]
Fixed in #3146 and will be included in the next release.

**Comment by phcoliveira** [comment]
I do not think this issue was fixed. I am using:
```
"firebase-tools": "13.14.0",
"firebase-admin": "12.1.0",
"firebase-functions": "5.0.1"
```
And I always end up having at least two databases.
Here is my file `.firebaserc`
```js
{
  "projects": {
    "default": "noice-app-eu-staging",
    "dev": "demo-dev"
  }
}
```
And this is the command I used:
```
pnpm exec firebase emulators:start --only=database --project=dev --debug
```

**Comment by phcoliveira** [comment]
Hello @amks1. Yeah, I got a reasonable solution. I have two firebase configuration files. The default `firebase.json` for deploying to production, and `firebase.local.json` for local development. I could have only if I had understood the targets well enough. But I hadn't.
So here is my `firebase.local.json` file:
```json5
{
	"functions": [
	  {
		// ...
	  }
	],
	"emulators": {
	  "auth": {
		"port": 9099
	  },
	  "database": {
		"port": 9000
	  },
	  "hosting": {
		"port": 5174
	  },
	  "functions": {
		"port": 5001
	  },
	  "ui": {
		"enabled": true,
		"port": 4200
	  },
	  "singleProjectMode": true
	},
	"database": [
		{
			"instance": "demo-local",
			"rules": "apps/database/main/rules.json"
		}
	],
	"hosting": {
	  // ...
	}
  }
```

The key feature here is having the `"database"` entry as an array. You can have as many instances as you want. For example: `demo-dev` and `demo-test`.

Then, when you start the emulators, you can specify this other configuration file:
```
pnpm exec firebase:emulators start --config='firebase.local.json'
```
In my case, I end up having only one database, which is what I wanted.
Then, both my client app and Firebase functions use the same database URL:
```
// client
PUBLIC_FIREBASE_DATABASE_URL="http://localhost:9000/?ns=demo-local"
```

```
// function
FIREBASE_DATABASE_URL="http://localhost:9000/?ns=demo-local"
```

**Comment by amks1** [comment]
Thank you so much @phcoliveira, I finally got it working.
I only have a local firebase (I'm using the web interface to administrate my production) so I just changed the `firebase.json` to this:
```
{
  "emulators": {
    "firestore": {
      "port": 8080
    },
    "database": {
      "port": 9000
    },
    "storage": {
      "port": 9199
    },
    "ui": {
      "enabled": true
    },
    "singleProjectMode": true
  },
  "storage": {
    "rules": "storage.rules"
  },
  "firestore": {
    "rules": "firestore.rules",
    "indexes": "firestore.indexes.json"
  },
  "database": [{
    "instance": "my-development",
    "rules": "database.rules.json"
  }]
}
```

Then I just ran `firebase emulators:start` normally, and the rules were applied. What I was missing earlier was the `instance` field in the `database` entry. If this is omitted, it creates a second database for some reason.
