### ISSUE TITLE
Extensions cannot be installed non-interactively

### ISSUE THREAD

**Issue by oxc** [firebase/firebase-tools#3127]
### [REQUIRED] Environment info

**firebase-tools:** 9.3.0

**Platform:** Ubuntu (on WSL)

### [REQUIRED] Test case

Install firestore-translate-text with parameters defined in config file (all params have default values, so can be omitted)

### [REQUIRED] Steps to reproduce

```
echo '' > empty-file
firebase --non-interactive ext:install firestore-translate-text --params=empty-file
```

### [REQUIRED] Expected behavior

The command runs without any user interaction.

### [REQUIRED] Actual behavior

The command requires multiple questions to be answered with Yes (which is in all cases the default answer).

**Comment by mothman11** [comment]
With the latest release, it looks like extensions can now be installed non interactively using the flags --force --non-interactive
