### ISSUE TITLE
firebase init functions - not working

### ISSUE THREAD

**Issue by stsmedia** [firebase/firebase-tools#314]
```
$ npm install -g firebase-tools
/usr/local/Cellar/node/0.10.26/bin/firebase -> /usr/local/Cellar/node/0.10.26/lib/node_modules/firebase-tools/bin/firebase
/usr/local/Cellar/node/0.10.26/lib
└── firebase-tools@3.6.1
$ firebase --version
3.0.2

$ firebase init functions
...
You're about to initialize a Firebase project in this directory:

  /Users/foo/dev/fb-test


i  Writing configuration info to firebase.json...
i  Writing project information to .firebaserc...

✔  Firebase initialization complete!
```

According to the getting started guide this should have created a functions directly with index.js etc. Instead I get 2 empty configs...

What is going wrong here?

**Comment by mbleigh** [comment]
You need to upgrade your CLI:

npm install -g firebase-tools

**Comment by stsmedia** [comment]
@mbleigh thanks for the suggestion. As you can see above, I only installed them yesterday for the first time and it reports as version 3.6.1 already. 

Any other suggestions?

**Comment by mbleigh** [comment]
But `firebase --version` is reporting `3.0.2` which implies that you likely have two `firebase` installs in your `$PATH` and it's a very old one that's picking up first. You'll need to do some digging to figure out which firebase is actually running and make sure that it's the correct one. `firebase --version` will **always** print an accurate version.

I also notice you have Node 0.10 -- for functions we strongly recommend (can't remember if we require, but we might) being on Node 6.

**Comment by stsmedia** [comment]
Thanks @mbleigh that did it. Wasn't aware that my firebase was out of date. Updated node as well.

**Comment by albi1995** [comment]
[debug] [2019-08-21T05:31:33.347Z] ----------------------------------------------------------------------
[debug] [2019-08-21T05:31:33.388Z] Command:       /usr/local/bin/node /usr/local/bin/firebase init
[debug] [2019-08-21T05:31:33.388Z] CLI Version:   7.2.4
[debug] [2019-08-21T05:31:33.388Z] Platform:      darwin
[debug] [2019-08-21T05:31:33.388Z] Node Version:  v10.16.2
[debug] [2019-08-21T05:31:33.559Z] Time:          Wed Aug 21 2019 11:01:33 GMT+0530 (India Standard Time)
[debug] [2019-08-21T05:31:33.559Z] ----------------------------------------------------------------------
[debug] 
[debug] [2019-08-21T05:31:33.649Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2019-08-21T05:31:33.649Z] > authorizing via signed-in user
[info] 
     ######## #### ########  ######## ########     ###     ######  ########
     ##        ##  ##     ## ##       ##     ##  ##   ##  ##       ##
     ######    ##  ########  ######   ########  #########  ######  ######
     ##        ##  ##    ##  ##       ##     ## ##     ##       ## ##
     ##       #### ##     ## ######## ########  ##     ##  ######  ########

You're about to initialize a Firebase project in this directory:

  /Users/albinjoseph

Before we get started, keep in mind:

  * You are initializing in an existing Firebase project directory

[info] 
=== Project Setup
[info] 
[info] First, let's associate this project directory with a Firebase project.
[info] You can create multiple project aliases by running firebase use --add, 
[info] but for now we'll just set up a default project.
[info] 
[info] i  .firebaserc already has a default project, using wiznet-india-practice.
[debug] [2019-08-21T05:31:40.414Z] >>> HTTP REQUEST GET https://firebase.googleapis.com/v1beta1/projects/wiznet-india-practice  
 
[debug] [2019-08-21T05:31:41.632Z] <<< HTTP RESPONSE 200
[info] 
=== Functions Setup
[info] 
[info] A functions directory will be created in your project with a Node.js
[info] package pre-configured. Functions can be deployed with firebase deploy.
[info] 
[debug] [2019-08-21T05:31:41.635Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2019-08-21T05:31:41.636Z] > authorizing via signed-in user
[debug] [2019-08-21T05:31:41.636Z] >>> HTTP REQUEST GET https://firebase.googleapis.com/v1beta1/projects/wiznet-india-practice  
 
[debug] [2019-08-21T05:31:42.314Z] <<< HTTP RESPONSE 200
[debug] [2019-08-21T05:31:42.322Z] >>> HTTP REQUEST POST https://serviceusage.googleapis.com/v1/projects/wiznet-india-practice/services/cloudfunctions.googleapis.com:enable  
 
[debug] [2019-08-21T05:31:42.323Z] >>> HTTP REQUEST POST https://serviceusage.googleapis.com/v1/projects/wiznet-india-practice/services/runtimeconfig.googleapis.com:enable  
 
[debug] [2019-08-21T05:31:43.337Z] <<< HTTP RESPONSE 200
[debug] [2019-08-21T05:31:44.628Z] <<< HTTP RESPONSE 200
[info] ✔  Wrote functions/package.json
[info] ✔  Wrote functions/tslint.json
[info] ✔  Wrote functions/tsconfig.json
[info] ✔  Wrote functions/src/index.ts
[info] ✔  Wrote functions/.gitignore
[info] 
[info] i  Writing configuration info to firebase.json...
[debug] [2019-08-21T05:32:23.255Z] Error: EACCES: permission denied, open '/Users/albinjoseph/firebase.json'
    at Object.openSync (fs.js:443:3)
    at Object.writeFileSync (fs.js:1194:35)
    at Config.writeProjectFile (/usr/local/lib/node_modules/firebase-tools/lib/config.js:179:8)
    at /usr/local/lib/node_modules/firebase-tools/lib/commands/init.js:130:16
    at process._tickCallback (internal/process/next_tick.js:68:7)
[error] 
[error] Error: An unexpected error has occurred.

**Comment by Geeklord-Tazheeb** [comment]
after firebase login.. 
firebase init is not working?

ERROR:

firebase : File C:\Users\thsha\AppData\Roaming\npm\firebase.ps1 cannot be loaded because running scripts is disabled on this system. 
For more information, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ firebase init
+ ~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

**Comment by codingraj3427** [comment]
> after firebase login.. firebase init is not working?
> 
> ERROR:
> 
> firebase : File C:\Users\thsha\AppData\Roaming\npm\firebase.ps1 cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170. At line:1 char:1
> 
> * firebase init
> * ```
>     + CategoryInfo          : SecurityError: (:) [], PSSecurityException
>     + FullyQualifiedErrorId : UnauthorizedAccess
>   ```

please login then run firebase init
