### ISSUE TITLE
firebase deploy --remove functions or hosting

### ISSUE THREAD

**Issue by gerhardcit** [firebase/firebase-tools#315]
Old function sticks in firebase when you rename a function  after the first deployment

Deploy this function:
```
exports.helloFn1 = functions.https.onRequest((request, response) => {
    response.send("Hello from Fn1!");
});
```
call, and then edit the index.js and change it to:
```
exports.helloFn2 = functions.https.onRequest((request, response) => {
    response.send("Hello from Fn2!");
});
```
`firebase deploy --only functions`

In the firebase console, both functions is there, with no option to delete it.

You can delete it in the cloud console `https://console.cloud.google.com` but admin will be done from the deployment point of view?
Or how is the plan to deploy functions by name from different places?

**Comment by laurenzlong** [comment]
What version of Firebase CLI are you using? Can you try upgrading by running 'npm install -g firebase-tools' and deploying again? That should hopefully delete the old function.

**Comment by gerhardcit** [comment]
@laurenzlong 
```
$ firebase --version
3.6.1
```

**Comment by laurenzlong** [comment]
Thanks for the info! Can you run `firebase deploy --only functions --debug` and attach the log file here?

**Comment by Jacobys527** [comment]
Hello, @laurenzlong, i deployed the generate thumbnail functions and now i don't need to do with this anymore, i just want delete the functions. But i couldn't find the delete functions, Need help.

**Comment by mbleigh** [comment]
Remove them from your exports and deploy, they will be deleted.

**Comment by Jacobys527** [comment]
Thanks for your reply @mbleigh, Could you explain more details please?

**Comment by Jacobys527** [comment]
I want to clean my functions.

**Comment by laurenzlong** [comment]
What @mbleigh had meant is that if the functions are no longer in functions/index.js when you deploy (because you deleted or commented out the code), then it will be deleted. If that is not working, then go to https://cloud.google.com/console/functions/list, click on the three dots to right of the function you'd like to delete to expand the menu, then click on "delete". Please reopen this issue if you're still experiencing problems.

**Comment by Jacobys527** [comment]
Thanks your reply, @laurenzlong. I'm on firebase, i know deploy again with new functions, old function changes into new one, but i will not use functions anymore, just cleaning functions. And three dots to right of the function only shows View logs,  i need your help.

**Comment by laurenzlong** [comment]
You can just deploy an empty functions/index.js in that case, that will delete all of your functions. Did you click on the link above that I gave you? (It's the cloud console, not Firebase console.) It should have a delete option, if it doesn't, please provide screenshot of what you see.

**Comment by Jacobys527** [comment]
Thank you @laurenzlong, it works with functions/index.js . Thank you for your kindness!

**Comment by babymagnum** [comment]
helo guys, need some help, i want to add and re-run the "firebase deploy --only functions" command but it give me bunch of error.
![image](https://user-images.githubusercontent.com/28477074/35390194-1efc24e0-020d-11e8-861d-420bffc278f8.png)

===============this is the log====================
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Zain\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   '--prefix',
1 verbose cli   '$RESOURCE_DIR',
1 verbose cli   'run',
1 verbose cli   'lint' ]
2 info using npm@5.6.0
3 info using node@v9.4.0
4 verbose stack Error: ENOENT: no such file or directory, open 'C:\CloudFunctionsPentosa\$RESOURCE_DIR\package.json'
5 verbose cwd C:\CloudFunctionsPentosa
6 verbose Windows_NT 10.0.16299
7 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Zain\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "--prefix" "$RESOURCE_DIR" "run" "lint"
8 verbose node v9.4.0
9 verbose npm  v5.6.0
10 error path C:\CloudFunctionsPentosa\$RESOURCE_DIR\package.json
11 error code ENOENT
12 error errno -4058
13 error syscall open
14 error enoent ENOENT: no such file or directory, open 'C:\CloudFunctionsPentosa\$RESOURCE_DIR\package.json'
15 error enoent This is related to npm not being able to find a file.
16 verbose exit [ -4058, true ]

thanks in advance

**Comment by laurenzlong** [comment]
@babymagnum Try removing "predeploy" from firebase.json

**Comment by babymagnum** [comment]
@laurenzlong its already solved, i was forgot to move 1 level up to folder functions, after that, its word perfectly just like before

**Comment by alastacat** [comment]
@laurenzlong I'm having the same issue, functions seem to remain despite deploying with empty index.js

**Comment by qruxtapose** [comment]
Having issues with this as well. I made sure to upgrade to the latest firebase-tools. When I deploy, old functions still persist even though I'm explicitly setting them to be deleted during deployment. I have to use this command to get rid of them:

`firebase functions:delete helloWorld`

It's a bit tedious.

**Comment by bkendall** [comment]
Right now there's a known issue where removing the function from your deployed file(s) (e.g. `index.js`) doesn't remove the function. See #982 for more details.

Short version:
- `firebase deploy --only functions` will _tell you_ that it will remove functions, but not actually do so. Run this to know what _will_ be removed.
- `firebase deploy --only functions --force` will remove the noted functions, but will _not_ ask for confirmation. This will actually delete the removed (from code) functions.

**Comment by Hinnn** [comment]
I have run firebase deploy in my terminal window, but the web page doesn't change. How to solve this problem? thank you!

**Comment by bkendall** [comment]
@Hinnn open a new issue with the appropriate details. Thanks.

**Comment by Mofedob** [comment]
> What version of Firebase CLI are you using? Can you try upgrading by running 'npm install -g firebase-tools' and deploying again? That should hopefully delete the old function.

Solved, thank you
