### ISSUE TITLE
firebase init Web Hosting causes Database Rules on Console to be removed...

### ISSUE THREAD

**Issue by Sun3** [firebase/firebase-tools#316]
Using the firebase init to deploy website to Firebase Hosting causes the Console Database Rules to be removed...  

Is there a way to stop this? The rules are overwritten  by default rules.

Thank you.

**Comment by mbleigh** [comment]
When you run `firebase init` you are given a choice of which Firebase features to initialize. If you choose Database, the security rules for the project you pick will be downloaded into a file you specify (by default `database.rules.json`) which will be deployed each time you run `firebase deploy`.

If you don't want this to happen, you should uncheck Database when running `firebase init` using the arrow keys and spacebar. For an already initialized project, remove the `"database"` key from `firebase.json` and delete the `database.rules.json` file.

**Comment by Sun3** [comment]
Thanks for clearing that up. I see what I did wrong. At the point of choosing the Hosting, I just moved my arrow down to hosting and hit Enter. Instead I was suppose to use the space bar in order to unselect unwanted features.

Thank you I appreciate it. When I was publishing the website I just did not expect other parts like Database rules were going to be effected.
