### ISSUE TITLE
Unable to publish functions using crashlytics event hooks

### ISSUE THREAD

**Issue by ToxicBakery** [firebase/firebase-tools#3169]
### [REQUIRED] Environment info

**firebase-tools:** 9.5.0

**Platform:** Ubuntu

### [REQUIRED] Test case

Use the crashyltics samples or create a new function such as this:  
```javascript
const functions = require('firebase-functions');

// Captures new issues opening them as a new medium severity issue
exports.newIssue = functions.crashlytics.issue().onNew(async (issue) => {
  console.log("hello")
});
```

### [REQUIRED] Steps to reproduce

`firebase deploy --debug --only functions`
This results in a deployment error.

### [REQUIRED] Expected behavior

The function is created for the new issue hook

### [REQUIRED] Actual behavior

Error
```
[2021-02-23T23:28:34.128Z] <<< HTTP RESPONSE BODY {"error":{"code":400,"message":"The request has errors","status":"INVALID_ARGUMENT","details":[{"@type":"type.googleapis.com/google.rpc.BadRequest","fieldViolations":[{"field":"event_trigger","description":"Unknown event_type providers/firebase.crashlytics/eventTypes/issue.new"}]}]}}
⚠  functions: failed to create function newIssue 
HTTP Error: 400, The request has errors
```

### More Info
I wrote two functions last year for automatically reporting issues and regressions from crashlytics to an external tool. I noticed that back in October those functions stopped being triggered. I thought it may be related to node8 deprecation so I updated my function to Node 12 but now I can't publish my function anymore due to the trigger apparently no longer existing. Was it removed?

**Comment by mbleigh** [comment]
Yes, Crashlytics functions were deprecated and removed in October of last year, unfortunately. It looks like we're not doing a good enough job of documenting that and cleaning up remaining pieces of it. I'll file a report internally to see if we can clean that up better.
