### ISSUE TITLE
ESLint Firebase Setup doesn't work out the box

### ISSUE THREAD

**Issue by augustkimo** [firebase/firebase-tools#3172]
### [REQUIRED] Environment info

Firebase 9.5.0

**Platform:**

NodeJS
Node v12.16.3

### [REQUIRED] Steps to reproduce

`firebase init` a fresh setup of Firebase Functions using NodeJS and ESlint. Try some code from the official Firebase examples, or something like this:
```
exports.helloWorld = functions.https.onCall(async(data, context) => {
  console.log('hello world");
});
```

### [REQUIRED] Expected behavior

ESlint/Firebase default setup allows a error free deploy.

### [REQUIRED] Actual behavior

Numerous ESLint errors and warnings, with lots of tweaking required. 

I make a good amount of projects using Firebase Functions. I used to `init`, write some code and deploy. 
Now every new project has many ESLint errors which take lots of tweaking to get past and the setup just doesn't feel "right" out of the box like in past versions. 

I see many other people complaining about this too, especially frustrated new users on StackOverflow. Please make ESLint Firebase defaults work better with functions. The current default settings are painful making ESlint a nuisance rather than a useful tool.

**Comment by joehan** [comment]
Thanks for raising this @augustkimo. I'll take a look and see if I can get this to a cleaner spot.

**Comment by joehan** [comment]
Hey @augustkimo, I'm having trouble finding these eslint issues. Here's what I've tried:
```
firebase init functions // Tried this with both JS & TS
// Uncomment the default function in index.js, or copy over the example function you posted & fix typos)
cd functions
npm run lint
```
and I didnt see  any unexpected eslint warnings or errors.

 Could you share some of the specific errors and warnings you're seeing? Also, you mentioned you saw other users on StackExchange with similar issues - I'll do some searching, but if you can share links to those questions it would be super helpful.
