### ISSUE TITLE
Auth Emulator does not work "Add user" with port forwarding

### ISSUE THREAD

**Issue by koooge** [firebase/firebase-tools#3177]
Hi there, I encountered an issue with the Firebase emulator.

### [REQUIRED] Environment info

**firebase-tools: 9.5.0

**Platform: macOS

### [REQUIRED] Test case

Run `firebase emulators:start` with port forwarding.

docker-compose example:
```
...
  firebase:
     ports:
         - "10000:4000" # UI
         - "10001:9099" # Auth 
```

### [REQUIRED] Steps to reproduce

1. docker-compose up
2. Access Firebase Suite UI (http://localost:10000) with Chrome
3. Open Authentication tab
4. Add user 

### [REQUIRED] Expected behavior

"Add user" works properly.

### [REQUIRED] Actual behavior

Nothing will happen.
Wih UI, [Save] in the "Add user" dialog button does not work. Noting happened.
Besides, I tried `admin.auth().createUser` via firebase-admin. It looks to get the response correctly, but Suite UI showed an empty list of users.

I found the workaround. It worked by bind the same port (9099) on the host:
```
     ports:
         - "10000:4000" # UI
         - "10001:9099" # Auth
         - "9099:9099" # Auth workaround
```

**Comment by samtstern** [comment]
@koooge this feels like the correct behavior to me if you're using Chrome outside of Docker but the emulator is running inside of Docker. The UI tries to communicate with the Auth Emulator on port 9099 but doesn't find anything. Then when you map `9099:9099` it works.

Let me know if I misunderstood!

**Comment by koooge** [comment]
Thanks @samtstern ,  You are right. It means Firebase Auth Emulator has to be served on the same port host and guest.
In my case, the port of host is assigned dynamically. For that reason, the port in docker needs to bind the port dynamically on docker run time. But, we would not be able to do it because it has to be statically defined in firebase.json.

```
  "auth": {
    "host": "0.0.0.0",
    "port": "9099"
  },
```

As a result, the Firebase Auth emulator must be hosted on 9099.
