### ISSUE TITLE
FirebaseError: Task index 0 failed: timed out after 30000ms

### ISSUE THREAD

**Issue by liunianhuaguoyanxi** [firebase/firebase-tools#3184]
Steps:
1.  Firebase init
2. Create a new project
3. Finish inputing the unique project id
4. Error: Failed to create project. See firebase-debug.log for more info.

My network has no problem ,but it was always interrupted here ,  I need your help.  

Firebase-debug.log:
You're about to initialize a Firebase project in this directory:
  /Users/liunianhuaguoyanxi/firebaseMyHosting

[info] 
=== Project Setup
[info] 
[info] First, let's associate this project directory with a Firebase project.
[info] You can create multiple project aliases by running firebase use --add, 
[info] but for now we'll just set up a default project.
[info] 
[info] i  If you want to create a project in a Google Cloud organization or folder, please use "firebase projects:create" instead, and return to this command when you've created the project. 
[debug] [2021-03-03T13:20:39.978Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects  
 {"projectId":"supermaninhost","name":"supermaninhost"}
[debug] [2021-03-03T13:20:49.057Z] <<< HTTP RESPONSE 200 {"content-type":"application/json; charset=UTF-8","vary":"X-Origin, Referer, Origin,Accept-Encoding","date":"Wed, 03 Mar 2021 13:20:48 GMT","server":"ESF","cache-control":"private","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","server-timing":"gfet4t7; dur=220","alt-svc":"h3-29=\":443\"; ma=2592000,h3-T051=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","accept-ranges":"none","transfer-encoding":"chunked"}
[debug] [2021-03-03T13:20:49.060Z] > refreshing access token with scopes: []
[debug] [2021-03-03T13:20:49.060Z] >>> HTTP REQUEST POST https://www.googleapis.com/oauth2/v3/token  
 <request body omitted>
[debug] [2021-03-03T13:20:52.281Z] <<< HTTP RESPONSE 200 {"pragma":"no-cache","expires":"Mon, 01 Jan 1990 00:00:00 GMT","cache-control":"no-cache, no-store, max-age=0, must-revalidate","date":"Wed, 03 Mar 2021 13:20:52 GMT","content-type":"application/json; charset=utf-8","vary":"X-Origin, Referer, Origin,Accept-Encoding","server":"scaffolding on HTTPServer2","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","alt-svc":"h3-29=\":443\"; ma=2592000,h3-T051=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","accept-ranges":"none","transfer-encoding":"chunked"}
[debug] [2021-03-03T13:20:52.309Z] >>> [apiv2][query] GET https://cloudresourcemanager.googleapis.com/v1/operations/cp.6663288257803655930 [none]
[debug] [2021-03-03T13:21:19.066Z] FirebaseError: Task index 0 failed: timed out after 30000ms.
[debug] [2021-03-03T13:21:25.878Z] FirebaseError: Task index 0 failed: timed out after 30000ms.
    at Timeout.<anonymous> (/usr/local/lib/node_modules/firebase-tools/lib/throttler/throttler.js:165:24)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
[error] 
[error] Error: Failed to create project. See firebase-debug.log for more info.

**Comment by joehan** [comment]
Hi @liunianhuaguoyanxi, I think this may be an issue with your account - I'm not able to repro this behavior. One thing to try would be creating a project using `firebase project:create supermaninhost`. If that doesn't work, I think your best bet will be to reach out to GCP support: https://cloud.google.com/support-hub

**Comment by liunianhuaguoyanxi** [comment]
I used firebase project:create supermaninhost
it also failed to create project   but  firebase-debug.log is that

Error: Failed to create project because there is already a project with ID supermaninhost. Please try again with a unique project ID.

I  have changed the project id and created again.it still run failed.

**Comment by liunianhuaguoyanxi** [comment]
I have solved this problem by resintalling the firebase-tools and modifying the proxy.

**Comment by joehan** [comment]
Glad to hear you were able to get this working! I'll close this.
