### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by williamvasconcelos** [firebase/firebase-tools#3185]
### [REQUIRED] Environment info

**firebase-tools: 9.5.0**

**Platform: macOS 10.15.7**

### [REQUIRED] Test case

Run firebase login:
`firebase login --no-localhost --debug`
### [REQUIRED] Steps to reproduce

Run firebase login:
`firebase login --no-localhost --debug`

### [REQUIRED] Expected behavior

Successful login.

### [REQUIRED] Actual behavior

```
➜  ~ firebase login --no-localhost --debug
i  Firebase optionally collects CLI usage and error reporting information to help improve our products. Data is collected in accordance with Google's privacy policy (https://policies.google.com/privacy) and is not used to identify you.
 
? Allow Firebase to collect CLI usage and error reporting information? (Y/n) [2021-03-03T17:44:28.401Z] FetchError: request to https://firebase-public.firebaseio.com/cli.json failed, reason: unable to get local issuer certificate
    at ClientRequest.<anonymous> (/usr/local/Cellar/firebase-cli/9.5.0/libexec/lib/node_modules/firebase-tools/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (node:events:378:20)
    at ClientRequest.EventEmitter.emit (node:domain:470:12)
    at TLSSocket.socketErrorListener (node:_http_client:462:9)
    at TLSSocket.emit (node:events:378:20)
    at TLSSocket.EventEmitter.emit (node:domain:470:12)
    at emitErrorNT (node:internal/streams/destroy:188:8)
    at emitErrorCloseNT (node:internal/streams/destroy:153:3)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)

Error: Failed to make request to https://firebase-public.firebaseio.com/cli.json

➜  ~ 

```

**Comment by joehan** [comment]
@williamvasconcelos This may have been a temporary issue, or may be an issue with your connection - I haven't been able to reproduce this.Are you able to access https://firebase-public.firebaseio.com/cli.json in your browser?

**Comment by MollyXuemn** [comment]
I got also the Login error:
./firebase login

Firebase optionally collects CLI usage and error reporting information to help improve our products. Data is collected in accordance with Google's privacy policy (https://policies.google.com/privacy) and is not used to identify you.

? Allow Firebase to collect CLI usage and error reporting information? Yes
i  To change your data collection preference at any time, run `firebase logout` and log in again.

Visit this URL on this device to log in:
https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=652927430&redirect_uri=http%3A%2F%2Flocalhost%3A9005

Waiting for authentication...
(node:19628) UnhandledPromiseRejectionWarning: FirebaseError: Failed to make request to https://firebase-public.firebaseio.com/cli.json
    at Client.doRequest (/usr/local/lib/node_modules/firebase-tools/lib/apiv2.js:211:19)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
(node:19628) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:19628) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Visit this URL on any device to log in:
https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=652927430&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob

? Paste authorization code here: 4/1AY0e-g5ZkaN01ovy6MAUh_qyWfbU-6cq8SQYTyjUs4IQbkQ9W74JabgZrsI

Error: Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci

**Comment by williamvasconcelos** [comment]
The problem is my proxy, i removed the SSL Inspection from URL.
