### ISSUE TITLE
Ignore .git folder in firebase.json

### ISSUE THREAD

**Issue by mishushakov** [firebase/firebase-tools#3189]
### [REQUIRED] Environment info

**firebase-tools:** v9.50

**Platform:** macOS

### [REQUIRED] Test case

```
firebase init
```

### [REQUIRED] Steps to reproduce

see above

### [REQUIRED] Expected behavior

`firebase.json` should ignore .git folder for hosting

### [REQUIRED] Actual behavior

`firebase.json` does not ignore .git folder therefor `firebase deploy` uploads application source code - opening up a potential vulnerability

**Comment by samtstern** [comment]
@mishushakov Firebase Hosting doesn't have a concept of "ignore" which is why the default structure is like this:

```
/your-project
|_ /public --> hosting files
|_ .git --> git files
|_ firebase.json --> firebase config
```

If you want to prevent this error you should move your public hosting folder to a subfolder which is at or below the level of your `.git` folder.
