### ISSUE TITLE
functions("region").httpsCallable("name") requests to wrong URL in emulator

### ISSUE THREAD

**Issue by Hagihara-A** [firebase/firebase-tools#3190]
### Environment info

**firebase-tools: 9.5.0**

**Platform: Windows + WSL2**

### Test case

https://github.com/Hagihara-A/fb-func-bug-reproduction

### Expected behavior
When I specify `firebase.functions().useEmulator(....)`, 
`firebase.functions("asia-northeast1").httpsCallable("name")` should request to the emulator such as `http://localhost:5001/xxxxxxxxxxxxx/asia-northeast1/name`

###  Actual behavior
Actually, `firebase.functions("asia-northeast1").httpsCallable("name")`  requests to `https://asia-northeast1-xxxxxxxxxxxxx.cloudfunctions.net/greeting`

### Steps to reproduce
Please clone repository written in Test case.
at root of project:
```bash
yarn firebase emulators:start 
```

at another terminal:
```bash
cd hosting && yarn start
```

Visit http://localhost:3000/.
I made two buttons says `no region function` & `asia function`. Click these buttons.
Though both buttons cause error, you can see button saying `no region function` requests to emulator. But button saying `asia function` requests to wrong (probably production) URL.

**Comment by samtstern** [comment]
@Hagihara-A thanks for reporting this! This is actually the intended behavior.  The `useEmulator()` method is not global, it modifies only one instance of the functions object. Each time you call `firebase.functions()` with new arguments you get a new instance.

So:
```
const functions = firebase.functions(); // Instance 1
functions.useEmulator(...);

const functionsAsia = firebase.functions('asia-northeast1'); // Instance 2
functionsAsia.useEmulator(...);
```
