### ISSUE TITLE
functions:config:clone results in escaped quotes within nested values

### ISSUE THREAD

**Issue by katowulf** [firebase/firebase-tools#320]
See firebase/firebase-functions#44

### Version info

**firebase-functions:** 0.5.3

**firebase-tools:** 3.6.1

**firebase-admin:** 4.1.3

### Test case

When cloning config environment, nested values have escaped quotes.

### Steps to reproduce
```
firebase use env1
firebase functions:config:set someservice.key="key"
firebase deploy
```

```
firebase use env2
firebase functions:config:clone --from env1
firebase functions:config:get
```
Outputs:
```
{
  "someservice": {
    "key": "\"key\""
   }
]
```

### Were you able to successfully deploy your functions?

Yes

### Expected behavior

Same config settings.

### Actual behavior

Invalid config values

**Comment by joehan** [comment]
@taeold Passing a bunch of old functions:config issues over to you so we can make sure that they get fixed in the env:* commands

**Comment by joehan** [comment]
Actually, since this duplicate #371, closing.
