### ISSUE TITLE
Auth emulator fails to create user with X-Client-Version forbidden from jsdom

### ISSUE THREAD

**Issue by maierson** [firebase/firebase-tools#3200]
Hello,

I am trying to create an integration test with jest for a component that registers a user. I have isolated below a minimal test case that fails with the X-Client-Version forbidden error.

### [REQUIRED] Environment info

**firebase-tools:** 9.6.0

**Platform:** MacOS Big Sur 11.2.2

**Node:** v14.15.5

### [REQUIRED] Test case

```js
import firebase from "firebase/app";
import "firebase/auth";

const PROJECT_ID = process.env.PROJECT_ID;
const VALID_EMAIL = "email@test.com";

let app;
beforeEach(() => {
  // This is the same config that the component uses. Works in Cypress
  const config = {
      apiKey: "...",
      authDomain: "...",
      databaseURL: "...",
      projectId: "...",
      storageBucket: "...",
      messagingSenderId: "...",
      appId: "...",
      measurementId: "...",
  }
  app = await firebase.initializeApp(config);
  app.auth().useEmulator("http://localhost:9099/", {
    disableWarnings: true,
    ssl: false,
  });
});

it("should create user", async () => {
  await app.auth().createUserWithEmailAndPassword(VALID_EMAIL, "placeholder_pass");
});

```
### [REQUIRED] Steps to reproduce

Launch the emulator: `yarn firebase emulators:start --only auth`;
Run the test with jest.

### [REQUIRED] Expected behavior

The user should be created and appear in the Authentication emulator UI.

### [REQUIRED] Actual behavior

The test fails with the following stack trace:

```
Error: Headers X-Client-Version forbidden
        at dispatchError (/Users/.../Documents/1-projects/.../node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:62:19)
        at validCORSPreflightHeaders (/Users/.../Documents/1-projects/.../node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:99:5)
        at Request.<anonymous> (/Users/.../Documents/1-projects/.../node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:372:12)
        at Request.emit (events.js:315:20)
        at Request.onRequestResponse (/Users/.../Documents/1-projects/.../node_modules/request/request.js:1059:10)
        at ClientRequest.emit (events.js:315:20)
        at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:641:27)
        at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
        at Socket.socketOnData (_http_client.js:509:22)
        at Socket.emit (events.js:315:20) undefined

```

**Comment by samtstern** [comment]
Hmmm it looks like JSDom is thinking there is a CORS issue. The only reference to this I can find online is an old comment saying that JSDom may not handle wildcard values with CORS headers correctly:
https://github.com/jsdom/jsdom/issues/2408#issuecomment-480969435

You can see that the Auth emulator sets the most permissive possible CORS headers:
https://github.com/firebase/firebase-tools/blob/d33369bb22d1c430c65a564e9535126d09bdf7f6/src/emulator/auth/server.ts#L126

Given that you said this works in Cypress I am pretty sure that this is actually a bug with JSDom. Looking in the JSDom source code this seems to be true:
https://github.com/jsdom/jsdom/blob/2d82763248296c5f118d6fd890317f5db5de1635/lib/jsdom/living/xhr/xhr-utils.js#L87

```js
function validCORSPreflightHeaders(xhr, response, flag, properties) {
  if (!validCORSHeaders(xhr, response, flag, properties, properties.origin)) {
    return false;
  }
  const acahStr = response.headers["access-control-allow-headers"];
  const acah = new Set(acahStr ? acahStr.trim().toLowerCase().split(headerListSeparatorRegexp) : []);
  const forbiddenHeaders = Object.keys(flag.requestHeaders).filter(header => {
    const lcHeader = header.toLowerCase();
    return !simpleHeaders.has(lcHeader) && !acah.has(lcHeader);
  });
  if (forbiddenHeaders.length > 0) {
    properties.error = "Headers " + forbiddenHeaders + " forbidden";
    dispatchError(xhr);
    return false;
  }
  return true;
}
```

That function would not handle `*` properly. I'll file an issue over there.

**Comment by maierson** [comment]
@samtstern This is great help. Thank you. I applied the provisional patch suggested and it now works.

**Comment by yuchenshi** [comment]
We also ran into this ourselves in tests, and I'm going to add a workaround here.
