### ISSUE TITLE
Unable to clone config from another Firebase project

### ISSUE THREAD

**Issue by ljle** [firebase/firebase-tools#3207]
### [REQUIRED] Environment info

**firebase-tools:** 9.6.0

**Platform:** Windows using WSL2 with Arch Linux

### [REQUIRED] Test case

I don't have a minimal example.

### [REQUIRED] Steps to reproduce

- Run `firebase functions:config:clone --from <another-firebase-project>`

### [REQUIRED] Expected behavior

- The Firebase environment configuration is cloned to the current project.

### [REQUIRED] Actual behavior

- After running the command I get the following error:

![image](https://user-images.githubusercontent.com/696474/110843688-5731a800-8287-11eb-8254-91c9e2f5f842.png)

**Comment by aravindvnair99** [comment]
@ljle I just tried `firebase functions:config:clone --from project-name` and was able to successfully. Not sure if this helps, but do you have access to the project you are trying to clone?

**Comment by taeold** [comment]
@ljle Based on the error message you shared, I wonder if there is something strange going on with the runtime config stored in the "other" project. 

For debugging, can you share the output of:

1. `firebase functions:config:clone --from <another-firebase-project> --debug`
2. `firebase functions:config:get --project <another-firebase-project>  --debug`
