### ISSUE TITLE
Emulator not always closing gracefully, and always closing it terminates react native bundler in another terminal

### ISSUE THREAD

**Issue by Agusfn** [firebase/firebase-tools#3208]
### [REQUIRED] Environment info

**firebase-tools:** 9.4.0

**Platform:** Windows 10 64bit

### [REQUIRED] Test case

Closing and starting the emulator multiple times.

### [REQUIRED] Steps to reproduce

In visual studio code, open the emulator in a new terminal with `--import` and `--export-on-exit` params, while having the React Native server runnning in another terminal, with the metro bundler. Then, attempting to terminate the emulators with CTRL+C. 

### [REQUIRED] Expected behavior

The expected behaviour is for only emulators to shut down, saving the data prior to shut down.

### [REQUIRED] Actual behavior

The actual behaviour is that sometimes, the emulator data won't save into the file specified in params. Also, sometimes, a java process with the service will be kept opened listening to the emulator ports, making it not possible to start the emulators normally again, having to terminate with task manager.

The other problem is that closing the emulators while having the react native process in another terminal in VS Code, will **_always_** terminate the react native process and the bundler. Making it necessary to build the application again and spending a lot of time.

**Comment by samtstern** [comment]
@Agusfn thanks for the feedback. Most of us here are unfamiliar with React Native. Could you provide a simple git repo we could clone in order to reproduce this problem? I have a Windows machine with VSCode I could use to test.
