### ISSUE TITLE
allow for logging when using as a node dependency

### ISSUE THREAD

**Issue by SJAnderson** [firebase/firebase-tools#321]
I noticed that when I called `deploy` like in the example below (warning, its coffee-script), none of the verbose CLI logs printed. Looks like logging is setup in the bin file, could we set that up in the module as well? Possibly add a `verbose` option to turn on or off.

```coffee
fb_tools.deploy {
  project: project
  projectDir: project_path
  cwd: project_path
  only: 'functions'
}
  .then ->
    log "#{project} deployed"
    next()
```

**Comment by prescottprue** [comment]
Totally agree this would be great.

**Comment by prescottprue** [comment]
The `nonInteractive: true` option mentioned in [#184](https://github.com/firebase/firebase-tools/issues/184) worked for me.

**Comment by kevinajian** [comment]
@SJAnderson does the `nonInteractive: true` work for you? Please reopen if this is still an issue.
