### ISSUE TITLE
Can't connect to functions shell when hosting emulator is running

### ISSUE THREAD

**Issue by Hacksore** [firebase/firebase-tools#3210]
### [REQUIRED] Environment info

**firebase-tools:** 9.6.1

**Platform:** macOS

### [REQUIRED] Test case
A project with all the emulators enabled (hosting, pubsub, functions, database, ui) - a good example is https://github.com/Hacksore/firebase-shell-bug 

### [REQUIRED] Steps to reproduce

See: https://github.com/Hacksore/firebase-shell-bug/blob/master/README.md

### [REQUIRED] Expected behavior

I should be able to get the functions shell REPL while the hosting emulator is running.

### [REQUIRED] Actual behavior
When all emulators are running via `firebase emulators:start` you will get a connection error when attempting to `firebase functions:shell`

```log
Error: Port 5000 is not open on localhost, could not start functions emulator.
```

**Comment by samtstern** [comment]
@Hacksore have you tried passing the `--port` argument to choose a different port? `firebase functions:shell --port 5001` should do it.

**Comment by Hacksore** [comment]
@samtstern I did indeed try when the emulators are running and it yielded no success. 

```log
firebase functions:shell --port 5001

Error: Port 5001 is not open on localhost, could not start functions emulator.

Having trouble? Try firebase [command] --help
```

**Comment by samtstern** [comment]
What if you do 5002?

**Comment by samtstern** [comment]
@Hacksore I'd say a bit of both. We should probably scan for a free port when running the shell instead of failing fast.
