### ISSUE TITLE
Failed to deploy functions with firebase-tools

### ISSUE THREAD

**Issue by darkcl** [firebase/firebase-tools#3212]
### [REQUIRED] Environment info

**firebase-tools:** 9.6.1

**Platform:** Fedora 33 and [bitbucket-pipeline](https://bitbucket.org/atlassian/firebase-deploy/src/master/)

### [REQUIRED] Test case

Running `GOOGLE_APPLICATION_CREDENTIALS=service.json firebase deploy --only functions`

### [REQUIRED] Steps to reproduce

Running `GOOGLE_APPLICATION_CREDENTIALS=service.json firebase deploy --only functions`

### [REQUIRED] Expected behavior

Expected functions to be deployed

### [REQUIRED] Actual behavior

In console it throws `Error: An unexpected error has occurred.`

In `firebase-debug.log` the last log is 

```
[debug] [2021-03-16T04:46:16.869Z] [functions] failed to list functions for {{project-id}}
[debug] [2021-03-16T04:46:16.869Z] [functions] Some Cloud Functions regions were unreachable, please try again later.
````
I have checked [firebase status](https://status.firebase.google.com/) and it seems all system are operational.

I also tried using VPN to connect to US as some [stackoverflow answer](https://stackoverflow.com/questions/61689102/some-cloud-functions-regions-were-unreachable-please-try-again-later) suggested, but I still have the same error

**Comment by morendav** [comment]
how was this resolved?
