### ISSUE TITLE
Auth Emulator not working

### ISSUE THREAD

**Issue by apeiniger** [firebase/firebase-tools#3213]
I'm using the newest version of firebase-tools 9.6.1. and have the problem that the Auth emulator is not working properly. There are no errors shown when starting the emulators:

![image](https://user-images.githubusercontent.com/2005574/111436628-7bb3d700-8702-11eb-9160-29112d855030.png)

But when I then go to the Auth Emulator UI and try to create a user nothing is happening (after clicking the Save in the new user form nothing happens). I checked the browser console and see the following when the page loads:

![image](https://user-images.githubusercontent.com/2005574/111436780-a9008500-8702-11eb-9862-3a04ea03be53.png)

This is how the form looks and nothing happens after clicking Save:

![image](https://user-images.githubusercontent.com/2005574/111436904-c7668080-8702-11eb-8e19-afe54b91fdbe.png)

Any ideas how to solve this are welcome. Thanks for checking.

**Comment by samtstern** [comment]
@apeiniger please use the issue template when filing issues, this is missing some important information. Can you tell me what operating system you're running? If it's Windows are you using WSL?

**Comment by apeiniger** [comment]
Sorry for not using the template. Came here directly from the link in the terminal. I'm running Ubuntu 20.04.1 LTS on AWS EC2. Accessing the interface via port forwarding in Visual Studio Code. Was never an issue that way in the past. I did an update of the firebase-tools to the newest version, but I'm not 100% sure if it has to do with that version update. I could try to downgrade and see if that resolves the issue.

**Comment by apeiniger** [comment]
I found the problem. It had to do with a wrong port forwarding. Issue can be closed. Thanks for looking into it.

**Comment by samtstern** [comment]
@apeiniger thank you for following up!
