### ISSUE TITLE
Callable functions are not being executed using the emulator

### ISSUE THREAD

**Issue by viniciusccarvalho** [firebase/firebase-tools#3218]
### [REQUIRED] Environment info

**firebase-tools:** 8.1.5

**Platform:** macOS

I don't have a full test case, but I have been experiencing this issue for a while. I have a service that abstracts the call to all firebase cloud functions.

### [REQUIRED] Steps to reproduce

Trying to deploy local functions and sometimes it fails

### [REQUIRED] Expected behavior

All functions should be invoked through the emulator

### [REQUIRED] Actual behavior
```
class PatientService {

    constructor() {

        this.storage = firebase.storage().ref()
        firebase.functions().useEmulator("localhost", 5001);

    }
```
I just toggle the use Emulator for now before sending to prod, but will use an environment detection.

Sometimes this works, I can't pinpoint whats wrong, some functions will be called locally, and randomly some will fail with cors errors as the browser tries to invoke the remote function and fail.

```

    get (id) {
        return new Promise((resolve, reject) => {
            var functions = firebase.app().functions("southamerica-east1")
            let getFunction = functions.httpsCallable("getPatient")
            getFunction({ id: id }).then(result => {
                console.log("get function return " + result)
                resolve(result.data)
            }).catch(error => {
                reject(error)
            })
        })
    }

    listPatients (filter) {
        return new Promise((resolve, reject) => {
            console.log("Will call function")
            var functions = firebase.app().functions("southamerica-east1")
            let listFunction = functions.httpsCallable("listPatients")
            listFunction().then((result) => {
                console.log(result)
                console.log("got response")
                resolve(result.data)
            }).catch(error => {
                console.log(error)
                reject(error)
            })
        })
    }
```

The functions are all registered on the emulator, but as I mentioned, sometimes they work sometimes they don't.

The very first time I tried the emulator all functions were ok, then after adding a new function the new function would not be called locally. Restarted the emulator, and after that, functions are randomly working.

Am I invoking `firebase.functions().useEmulator("localhost", 5001);` at the wrong place? I thought this was a config type of method that needed to be called just once.

```
functions
http function initialized (http://localhost:5001/caminho-virtual/southamerica-east1/savePatient).
08:56:07
I
functions
http function initialized (http://localhost:5001/caminho-virtual/southamerica-east1/addNote).
08:56:07
I
functions
http function initialized (http://localhost:5001/caminho-virtual/southamerica-east1/getPatient).
08:56:07
I
functions
http function initialized (http://localhost:5001/caminho-virtual/southamerica-east1/listPatients).```

But the `addNote` function which was the lastest to be added is not working. The app throws a CORS error as the function was being invoked remotely and not locally

**Comment by samtstern** [comment]
@viniciusccarvalho I think this is the issue:

```
// Returns the default functions instance in the default region
const f1 = firebase.functions()

// Returns a different functions instance in the southamerica-east1 region
const f2 = firebase.app().functions("southamerica-east1")

// This has NO EFFECT on f2
f1.useEmulator("localhost", 5001)
```

**Comment by viniciusccarvalho** [comment]
@samtstern that was it, thank you so much: I've updated my constructor to:
```
 this.functions = firebase.app().functions("southamerica-east1")
        this.functions.useEmulator("localhost", 5001)
```

And all is working as expected, thank you so much :) life saver

**Comment by samtstern** [comment]
@viniciusccarvalho I love when I guess right on the first try 😄  happy to help
