### ISSUE TITLE
Auth emulator is fetching users from production

### ISSUE THREAD

**Issue by tr4g** [firebase/firebase-tools#3222]
### [REQUIRED] Environment info

**firebase-tools:** 9.6.1

**Platform:** WSL2

### [REQUIRED] Test case

I have a user created in production with email "test@test.com" and my emulator data is empty, but I'm still able to use this on my function:
```
fb.auth.getUserByEmail("test@test.com")
```

and it works

and it creates a user in the emulator with the same ID as in production

### [REQUIRED] Steps to reproduce

create a user in production ,then run the aforementioned line on a local nodejs function

### [REQUIRED] Expected behavior

throw an error because the user doesn't exist in the emulator

### [REQUIRED] Actual behavior

creating a user in the emulator using production data, then actually getting that user

**Comment by samtstern** [comment]
@tr4g this is not enough information for us to reproduce the issue. Can you show the complete code of your function (or a simpler function that has this issue) and then also tell us how you're running it and invoking it?

**Comment by tr4g** [comment]
@samtstern thanks for replying, here's a reduced version of the function, basically connects to an endpoint in laravel to fetch a user and then creates it in firebase auth

```js

const fetch = require('node-fetch');

module.exports = fb => (data, context) => {

  return new Promise(async (resolve) => {

    let LARAVEL_HOST='http://platform:8080/sso/'
    let newUser = {}
    const laravelRequest = await fetch(LARAVEL_HOST+data.token);
    const laravelUser = await laravelRequest.json();


    try {
      const existingUser = await fb.auth.getUserByEmail(laravelUser.email)

      console.log('existing user', existingUser.uid);
      const newToken = await fb.auth.createCustomToken(existingUser.uid)
      return resolve({uid: existingUser.uid, internalToken: newToken})
    } catch (e) {
      console.log('new user');
      //create in local Auth
      try {
        newUser = await fb.auth.createUser({
          email: laravelUser.email,
          emailVerified: true,
          displayName: `${laravelUser.first_name} ${laravelUser.last_name}`
        });
      } catch (e) {
        console.log('error',e);
      }
      try {
        //create in local Firestore
        let accountRef = await fb.db.doc('accounts/'+newUser.uid)
        await accountRef.set({
          name:`${laravelUser.first_name} ${laravelUser.last_name}`,
          type: 'laravel',
          roles: ['user', 'admin'],
          email: laravelUser.email,
          created: (new Date()).getTime()
        });
      } catch (e) {
        console.log('error',e);
      }

      const newToken = await fb.auth.createCustomToken(newUser.uid)
      return resolve({uid: newUser.uid, internalToken: newToken})
    }

  });
}
```

**Comment by tr4g** [comment]
@samtstern yes, sorry, the function is called somewhere else:
```js
//firebase
const functions = require('firebase-functions')
const auth = admin.auth()
const db = admin.firestore()
const storage = admin.storage()

//functions
exports.authLaravel  =   functions.https.onCall(require('./_authLaravel')({auth,db,storage}))
```

**Comment by samtstern** [comment]
@tr4g ok but where do you do `admin.initializeApp()` and do you provide any arguments?  Sorry but this would be much easier if there was a full self-contained reproduction that I could copy and run.

**Comment by tr4g** [comment]
@samtstern i should have copied everything, sorry

```js
//init
const admin = require('firebase-admin')
admin.initializeApp({
  credential: admin.credential.cert(require('./creds.json')),
  storageBucket: 'XXXXX'
})
```

**Comment by samtstern** [comment]
When using the emulators you should just invoke it like this:
`admin.initializeApp()` ... using your production credentials could be why it's writing to production.

**Comment by tr4g** [comment]
@samtstern I tried that, but I get the following error:
```
Error: Credential implementation provided to initializeApp() via the "cred
ential" property failed to fetch a valid Google OAuth2 access token with the following error: "Error fetching access tok
en: Error while making request: getaddrinfo ENOTFOUND metadata.google.internal metadata.google.internal:80. Error code:
ENOTFOUND"
```

**Comment by samtstern** [comment]
@tr4g ok I'm sorry for all the back-and-forth but I think the only reasonable next step is an MCVE:
https://stackoverflow.com/help/minimal-reproducible-example

Please provide a full example I can git clone or copy and paste and see the same error you're seeing

**Comment by tr4g** [comment]
hi, sorry, it turned out to be an outdated version of firebase admin in the firebase folder, it would be nice to have a way to update all places where the library resides when a new version comes

**Comment by samtstern** [comment]
@tr4g thanks for following up!  Sounds like an `npm` feature request :-)

**Comment by carchrae** [comment]
i got hit with this as well.  just a few hours wasted trying to figure out why auth admin was not using the emulator.  

i can't see any easy way to add a warning about this though.  i guess emulation of auth was a rather late feature.    i'll add feedback on the doc page, but a big honking warning a version required would have saved me a lot of pain.

https://firebase.google.com/docs/emulator-suite/connect_auth

**Comment by samtstern** [comment]
I can see how this was easily missed, but for anyone looking for the SDK versions required for the emulators there is a table here:
https://firebase.google.com/docs/emulator-suite/install_and_configure#emulator_sdk_integrations

Looks like we need to get that upgraded for Storage.
