### ISSUE TITLE
Runtime environment variables are deleted during function deployment using tools 9.4.0 or greater 

### ISSUE THREAD

**Issue by pawlowskim** [firebase/firebase-tools#3226]
### [REQUIRED] Environment info

**firebase-tools:** 9.4.0 or greater

**Platform:** macOS Catalina (v 10.15.7), node v10.21.0

### [REQUIRED] Steps to reproduce

1. Create and deploy any cloud function
2. Edit created cloud function and add runtime environment variable `CUSTOM_VARIABLE:some_value` (from GCP console)
3. Re-deploy cloud function from 1.   

### [REQUIRED] Expected behavior

`CUSTOM_VARIABLE:some_value` - should persists across deployments.

### [REQUIRED] Actual behavior

Only `FIREBASE_CONFIG` runtime variable is available in the function.

Few things I have spotted:
- it doesn't matter if I update function from node 8 to node 10 during update
- deployment works using firebase-tools@9.3.0
- deployment tested and not working on version 9.4.0, 9.5.0, 9.6.1 (9.6.0 not tested)
- no breaking changes in release notes (yea, production broken because of that 😢 )
- v 9.3.0 `src/deploy/functions/prepare.js` had code line like this `var runtimeFromConfig = options.config.get("functions.runtime");` which is missing in 9.4.0+, and only default parameters are re-written to `environmentVariables` of a function. This might help you track down the problem. https://github.com/firebase/firebase-tools/compare/v9.3.0...firebase:v9.4.0#diff-ef26a08c6cb27fae2c011ca0638635007349132a1f8e3957a0ee1306d2cc3ce5R58

**Comment by i14h** [comment]
@pawlowskim thanks for reporting this. @joehan can you take a look please?

**Comment by taeold** [comment]
The fix should be available on the next release of the CLI (ETA: ~week?). I'll close the issue once the release including #3266 is cut.

**Comment by pawlowskim** [comment]
Great, thanks for the fix and update :) will test it out for sure.

**Comment by taeold** [comment]
Fixed released in 9.10.0. Please upgrade your CLI to receive the patch and deploy away!

**Comment by pawlowskim** [comment]
Would be good to update release notes https://github.com/firebase/firebase-tools/releases
Will test in next 2 weeks - thanks for the fix.

**Comment by taeold** [comment]
Ah missed my opportunity to update the changelog :( sorry.
