### ISSUE TITLE
When applying database settings the values aren’t stringified resulting in error.

### ISSUE THREAD

**Issue by misha-reyzlin-hier** [firebase/firebase-tools#3228]
### [REQUIRED] Environment info

**firebase-tools:** 9.6.1

**Platform:** macOS

### [REQUIRED] Test case

The problem is exactly as described in this StackOverflow question 
https://stackoverflow.com/questions/65214056/how-to-perform-large-deletes-in-the-firebase-realtime-database#comment118044022_65214056

firebase database:settings:set defaultWriteSizeLimit unlimited

### [REQUIRED] Steps to reproduce

Change into a directory with firebase project and run
firebase database:settings:set defaultWriteSizeLimit unlimited

This will return an error.

Expected behaviour is that it results in an updated database setting.

### [REQUIRED] Expected behavior

Command returns: 

✔  Successfully set setting.
✔  For database instance hierfoods-staging
	 defaultWriteSizeLimit = "\"unlimited\""

### [REQUIRED] Actual behavior

The command returns:  "Error: Unexpected error fetching configs at defaultWriteSizeLimit"

Patching the library in `./database/settings.js`  on line 23 from
```
return input;
```
to 
```
return JSON.stringify(input);
```

Makes the problem go away.

**Comment by samtstern** [comment]
Thanks for reporting! We're already working on a fix here:
https://github.com/firebase/firebase-tools/pull/3217
