### ISSUE TITLE
/usr/local/bin/firebase: line 1: Not: command not found -- when try to install CLI

### ISSUE THREAD

**Issue by kirmalyshev** [firebase/firebase-tools#3234]
Installing Firebase CLI tools fails, when try to install via curl 
Looks like its from the latest [release 9.8.0](https://github.com/firebase/firebase-tools/releases/tag/v9.8.0)

### [REQUIRED] Environment info

not installed
**firebase-tools:**

**Platform:** Ubuntu 

### [REQUIRED] Test case
`curl -sL firebase.tools`

### [REQUIRED] Steps to reproduce
`curl -sL firebase.tools`

### [REQUIRED] Expected behavior
Everything is installed, as expected

### [REQUIRED] Actual behavior
```
curl -sL firebase.tools | bash

-- Checking for existing firebase-tools on PATH...
-- Checking your machine type...
-- Downloading binary from https://firebase.tools/bin/linux/latest
######################################################################## 100.0%
-- Setting permissions on binary...
/usr/local/bin/firebase: line 1: Not: command not found
Something went wrong, firebase has not been installed.
Please file a bug with your system information on Github.
https://github.com/firebase/firebase-tools/
-- All done!

Exited with code exit status 1
```

**Comment by claryt** [comment]
Same issue Here

**Comment by henrymly** [comment]
Same

**Comment by outrunthewolf** [comment]
Same...

**Comment by MRandl** [comment]
I have a graded presentation tomorrow lol. Will rollback on 9.7.0 for now

**Comment by MRandl** [comment]
Update : looks like rolling back doesn't work

**Comment by bkirby42** [comment]
This worked for me. (replace platform with whatever you're using)

`curl -Lo ./firebase_bin https://firebase.tools/bin/macos/v9.7.0`

**Comment by MRandl** [comment]
> 9.8.0 is missing macos and linux executables.
> 
> Reverting to 9.7.0 worked for me. (replace platform with whatever you're using)
> 
> `curl -Lo ./firebase_bin https://firebase.tools/bin/macos/v9.7.0`

inspired from you, that worked for our CI : `curl -sL https://firebase.tools/bin/linux/v9.7.0 -o firebase_tools`
hope that helps somebody.

**Comment by abhijeetchz** [comment]
Seems like the issue is fixed, I retried the build now it passed that step. Can someone confirm?

**Comment by MRandl** [comment]
> Seems like the issue is fixed, I retried the build now it passed that step. Can someone confirm?

I get another mistake on the latest tag

`<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>15402300/bb2f9280-8d96-11eb-9a4b-758403abb6d9</Key><RequestId>R0NXY3QR0YAZZP65</RequestId><HostId>uaL2LBn5thrqCsXxPj9gA/GidUE3k9hHbVW3Aa1yNQ6Vi7nUJB+b/cyeUM7V/QxRjgJyYO2rBvI=</HostId></Error>`

**Comment by bkirby42** [comment]
It's fixed now.  As of 15 min ago, the linux binary was still missing, but now they are all there.

**Comment by MRandl** [comment]
yes, it runs correctly here

**Comment by claryt** [comment]
yeah, fixed!

**Comment by kirmalyshev** [comment]
Fixed! Great, thank you!
I close the issue

**Comment by Fernando7181** [comment]
downgrading worked for some reason
