### ISSUE TITLE
Error building and deploying project - ng build

### ISSUE THREAD

**Issue by akshaybabloo** [firebase/firebase-tools#3235]
### [REQUIRED] Environment info

**firebase-tools:** 9.8.0

**Platform:** macOS 10.15

### [REQUIRED] Steps to reproduce

1. Create an Angular project
2. Then - `firebase init` to initialise a project
3. Then - `ng deploy` to firebase

### [REQUIRED] Expected behavior

The project should buld and upload to firebase hosting

### [REQUIRED] Actual behavior

The project builds but then in the end I get - `firebaseTools.logger.add is not a function` error and then exists the program

**Comment by akshaybabloo** [comment]
Wrong repository. Sorry.

**Comment by BCusack** [comment]
AngularFire issue pre-release stuff https://github.com/angular/angularfire/issues/2785
