### ISSUE TITLE
Duplicate gitignore

### ISSUE THREAD

**Issue by aravindvnair99** [firebase/firebase-tools#3236]
### [REQUIRED] Environment info

**firebase-tools:** 9.8.0

**Platform:** Windows

### [REQUIRED] Test case

https://github.com/aravindvnair99/Firebase-MCVE

### [REQUIRED] Steps to reproduce

``` shell
$ firebase init

     ######## #### ########  ######## ########     ###     ######  ########
     ##        ##  ##     ## ##       ##     ##  ##   ##  ##       ##
     ######    ##  ########  ######   ########  #########  ######  ######
     ##        ##  ##    ##  ##       ##     ## ##     ##       ## ##
     ##       #### ##     ## ######## ########  ##     ##  ######  ########

You're about to initialize a Firebase project in this directory:

  D:\temp

? Are you ready to proceed? Yes
? Which Firebase CLI features do you want to set up for this folder? Press Space to select features, then Enter to confi
rm your choices. Functions: Configure and deploy Cloud Functions, Hosting: Configure and deploy Firebase Hosting sites

=== Project Setup

First, let's associate this project directory with a Firebase project.
You can create multiple project aliases by running firebase use --add,
but for now we'll just set up a default project.

? Please select an option: Don't set up a default project

=== Functions Setup

A functions directory will be created in your project with a Node.js
package pre-configured. Functions can be deployed with firebase deploy.

? What language would you like to use to write Cloud Functions? JavaScript
? Do you want to use ESLint to catch probable bugs and enforce style? Yes
+  Wrote functions/package.json
+  Wrote functions/.eslintrc.js
+  Wrote functions/index.js
+  Wrote functions/.gitignore
? Do you want to install dependencies with npm now? Yes

added 302 packages, and audited 303 packages in 19s

22 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

=== Hosting Setup

Your public directory is the folder (relative to your project directory) that
will contain Hosting assets to be uploaded with firebase deploy. If you
have a build process for your assets, use your build's output directory.

? What do you want to use as your public directory? public
? Configure as a single-page app (rewrite all urls to /index.html)? No
? Set up automatic builds and deploys with GitHub? No
+  Wrote public/404.html
+  Wrote public/index.html

i  Writing configuration info to firebase.json...
i  Writing project information to .firebaserc...
i  Writing gitignore file to .gitignore...

+  Firebase initialization complete!
```

### [REQUIRED] Expected behavior

Only one `gitignore` should be present at the root of the project.

### [REQUIRED] Actual behavior

Two `gitignore` files are made. One at root and one within `functions` folder which is redundant.

**Comment by samtstern** [comment]
@aravindvnair99 thanks for the very clear report. This is currently the intended behavior and nested `.gitignore` files are pretty normal in projects with multiple distinct purposes (such as a Firebase project with Hosting and Functions).  Is this a problem for you or just something you think could be optimized?

**Comment by aravindvnair99** [comment]
> @aravindvnair99 thanks for the very clear report. This is currently the intended behavior and nested `.gitignore` files are pretty normal in projects with multiple distinct purposes (such as a Firebase project with Hosting and Functions). Is this a problem for you or just something you think could be optimized?

@samtstern Not an issue for me particularly, but I just felt it could be optimised for everyone by having the `.gitignore` in a common place for better management. Rather than having to check multiple `.gitignore` files. I'll do one thing, I'll make a PR for you to take a look at. Give me a moment.

**Comment by samtstern** [comment]
@aravindvnair99 one issue here is if you run `firebase init functions` in a project directory that already has a `.gitignore` file in the root. In which case we will *not* overwrite that file but we will still create a new `functions/.gitignore` file.

**Comment by aravindvnair99** [comment]
> @aravindvnair99 one issue here is if you run `firebase init functions` in a project directory that already has a `.gitignore` file in the root. In which case we will _not_ overwrite that file but we will still create a new `functions/.gitignore` file.

@samtstern Ah right... I didn't think of that. I agree with you. For existing users, rewriting might end up revealing hidden files. What do you say about appending on towards existing `.gitignore` in that case?

**Comment by samtstern** [comment]
@aravindvnair99 that would probably work ... my concern with changing anything here is that there is nothing wrong with the current behavior and it is very simple. Changing it means that there are probably some edge cases we didn't think of where the user would end up without `node_modules` in `.gitignore` which is a bad outcome.

**Comment by aravindvnair99** [comment]
> @aravindvnair99 that would probably work ... my concern with changing anything here is that there is nothing wrong with the current behavior and it is very simple. Changing it means that there are probably some edge cases we didn't think of where the user would end up without `node_modules` in `.gitignore` which is a bad outcome.

@samtstern Right, I guess this issue and the PR I made can be closed as the cons outweigh the pros.

**Comment by samtstern** [comment]
👍 thank you for understanding! I really appreciate all of your contributions lately, I am sure we'll find more uses for your talent/energy.
