### ISSUE TITLE
firebase: command not found

### ISSUE THREAD

**Issue by Rishabh786Singh** [firebase/firebase-tools#3238]
### [REQUIRED] Environment info

**firebase-tools:**

**Platform:**

### [REQUIRED] Expected behavior

I did this "npm install -g firebase-tools" but when I am trying to login it is showing an error. "Firebase: command not found"

**Comment by aravindvnair99** [comment]
@Rishabh786Singh Make sure the binary is set in path.

**Comment by samtstern** [comment]
Thanks @aravindvnair99 for stepping in with some pointers!

@Rishabh786Singh please use the issue template when filing an issue. As it stands there's no evidence here that there's anything wrong with `firebase-tools`, sounds like you have an NPM path issue. If that issue persists you can always use the standalone binary build of the Firebase CLI.
