### ISSUE TITLE
Firebase Deploy Errors On Functions Using Optional Chaining

### ISSUE THREAD

**Issue by RFDPrint** [firebase/firebase-tools#3244]
### [REQUIRED] Environment info

**firebase-tools:9.8.0**

**Platform:Windows**

### [REQUIRED] Test case

Using the New ES2020 Feature Optional Chaining will cause an error when trying to deploy a function that takes advantage of this feature.

const customer = {
				metadata: {
					userId: userId
				},
				description: `UserId: ${userId}`,
				name: `${billing?.firstName} ${ billing?.lastName}`,
				address: {
					city: `${billing?.city}`,
					line1: `${billing?.street}`,
					state: `${billing?.state}`
				}
			}

### [REQUIRED] Steps to reproduce

Deploying functions with optional chaining will fail.

const customer = {
				metadata: {
					userId: userId
				},
				description: `UserId: ${userId}`,
				name: `${billing?.firstName} ${ billing?.lastName}`,
				address: {
					city: `${billing?.city}`,
					line1: `${billing?.street}`,
					state: `${billing?.state}`
				}
			}

### [REQUIRED] Expected behavior

  Deploy complete!

### [REQUIRED] Actual behavior
[2021-03-30T20:32:51.345Z]     
 Error during update for functions/api: 
Function failed on loading user code. This is likely due to a bug in the 
user code. Error message: Error: please examine your function logs to see the error cause: https://cloud.google.com/functions/docs/monitoring/logging#viewing_logs. Additional troubleshooting documentation can be found at https://cloud.google.com/functions/docs/troubleshooting#logging. Please visit https://cloud.google.com/functions/docs/troubleshooting for in-depth troubleshooting documentation.

Error: Functions did not deploy properly.

**Comment by bkendall** [comment]
Optional chaining isn't available except in very recent version of node (>= 14.5 according to [node.green](https://node.green/)).

What version of Node are you using in your deployment?

**Comment by RFDPrint** [comment]
I am using node 12

**Comment by RFDPrint** [comment]
This feature works fine using the emulator.

**Comment by mbleigh** [comment]
The emulator runs using whatever your local version of Node.js is -- when deploying it uses the specified runtime. If you change your engine to `"14"` it may work since Node.js 14 support is available in beta.

**Comment by bkendall** [comment]
Docs for changing your node version: https://firebase.google.com/docs/functions/manage-functions#set_nodejs_version

**Comment by emilioschepis** [comment]
Hi, I am experiencing sort of a similar problem.

I use TypeScript in my cloud functions, and I am targeting ES2020 in my `tsconfig.json`.
I set `"engine": "14"` in my `package.json` and I am able to deploy the functions without problems with the CLI from my local machine.

However, if I use the CLI (same version, 9.16.0) on a GitHub runner, it fails on the `?.` for "unexpected syntax".
[Here's a failing run with --debug](https://github.com/emilioschepis/geonotes-backend/runs/3261106553)

Do you have any idea of what could be causing it?
@mbleigh , @bkendall , is this enough information or should I open a separate issue? Thank you!

**Comment by floriangbh** [comment]
Same issue with Node 16.. 
https://github.com/firebase/firebase-tools/issues/3676#issuecomment-1103762659

**Comment by AlexanderChiclana** [comment]
same issue with node 18

**Comment by pelim** [comment]
changeing the ecma version to 2020 solved the problem for me


```
  parserOptions: {
    "ecmaVersion": 2020,
  }
```
