### ISSUE TITLE
Hosting emulator won't deliver init.js?useEmulator=true when started with other emulators

### ISSUE THREAD

**Issue by johnnyasantoss** [firebase/firebase-tools#3257]
### [REQUIRED] Environment info

**firebase-tools:** 9.8.0

**Platform:** Manjaro Linux 5.10

### [REQUIRED] Test case

See the section below.

### [REQUIRED] Steps to reproduce

I'm starting the emulators with `firebase emulators:start --import .data --export-on-exit .data --inspect-functions 9229` and attaching VSCode to debug it.
When initialized like this, the hosting emulator simply replies with `404`s to requests for `__/firebase/init.js?useEmulator=true` (the other scripts still there). Also, I'm not sure why, but it seems to me that the hosting simulator gets a lot slower when started like this :point_up: 
<details>
<summary>1st request of the init.js file, then all the others after getting redirected to index.html :point_down: </summary>
<pre>
...
i  hosting: 127.0.0.1 - - [02/Apr/2021:18:45:08 +0000] "GET /__/firebase/init.js?useEmulator=true HTTP/1.1" 200 12236 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0" {"metadata":{"emulator":{"name":"hosting"},"message":"127.0.0.1 - - [02/Apr/2021:18:45:08 +0000] \"GET /__/firebase/init.js?useEmulator=true HTTP/1.1\" 200 12236 \"-\" \"Mozilla/5.0 (X11; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0\""}}
i  hosting: 127.0.0.1 - - [02/Apr/2021:18:45:08 +0000] "GET /__/firebase/main.css HTTP/1.1" 200 12236 "http://localhost:5000/__/firebase/init.js?useEmulator=true" "Mozilla/5.0 (X11; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0" {"metadata":{"emulator":{"name":"hosting"},"message":"127.0.0.1 - - [02/Apr/2021:18:45:08 +0000] \"GET /__/firebase/main.css HTTP/1.1\" 200 12236 \"http://localhost:5000/__/firebase/init.js?useEmulator=true\" \"Mozilla/5.0 (X11; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0\""}}
i  hosting: 127.0.0.1 - - [02/Apr/2021:18:45:08 +0000] "GET /__/firebase/init.js?useEmulator=true HTTP/1.1" 200 12236 "http://localhost:5000/__/firebase/init.js?useEmulator=true" "Mozilla/5.0 (X11; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0" {"metadata":{"emulator":{"name":"hosting"},"message":"127.0.0.1 - - [02/Apr/2021:18:45:08 +0000] \"GET /__/firebase/init.js?useEmulator=true HTTP/1.1\" 200 12236 \"http://localhost:5000/__/firebase/init.js?useEmulator=true\" \"Mozilla/5.0 (X11; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0\""}}
i  hosting: 127.0.0.1 - - [02/Apr/2021:18:45:11 +0000] "GET /__/firebase/8.3.2/firebase-app.js HTTP/1.1" 200 20448 "http://localhost:5000/__/firebase/init.js?useEmulator=true" "Mozilla/5.0 (X11; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0" {"metadata":{"emulator":{"name":"hosting"},"message":"127.0.0.1 - - [02/Apr/2021:18:45:11 +0000] \"GET /__/firebase/8.3.2/firebase-app.js HTTP/1.1\" 200 20448 \"http://localhost:5000/__/firebase/init.js?useEmulator=true\" \"Mozilla/5.0 (X11; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0\""}}
i  hosting: 127.0.0.1 - - [02/Apr/2021:18:45:11 +0000] "GET /__/firebase/8.3.2/firebase-auth.js HTTP/1.1" 200 177065 "http://localhost:5000/__/firebase/init.js?useEmulator=true" "Mozilla/5.0 (X11; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0" {"metadata":{"emulator":{"name":"hosting"},"message":"127.0.0.1 - - [02/Apr/2021:18:45:11 +0000] \"GET /__/firebase/8.3.2/firebase-auth.js HTTP/1.1\" 200 177065 \"http://localhost:5000/__/firebase/init.js?useEmulator=true\" \"Mozilla/5.0 (X11; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0\""}}
i  hosting: 127.0.0.1 - - [02/Apr/2021:18:45:14 +0000] "GET /__/firebase/8.3.2/firebase-functions.js HTTP/1.1" 200 10153 "http://localhost:5000/__/firebase/init.js?useEmulator=true" "Mozilla/5.0 (X11; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0" {"metadata":{"emulator":{"name":"hosting"},"message":"127.0.0.1 - - [02/Apr/2021:18:45:14 +0000] \"GET /__/firebase/8.3.2/firebase-functions.js HTTP/1.1\" 200 10153 \"http://localhost:5000/__/firebase/init.js?useEmulator=true\" \"Mozilla/5.0 (X11; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0\""}}
i  hosting: 127.0.0.1 - - [02/Apr/2021:18:45:14 +0000] "GET /favicon.ico HTTP/1.1" 200 12236 "http://localhost:5000/__/firebase/init.js?useEmulator=true" "Mozilla/5.0 (X11; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0" {"metadata":{"emulator":{"name":"hosting"},"message":"127.0.0.1 - - [02/Apr/2021:18:45:14 +0000] \"GET /favicon.ico HTTP/1.1\" 200 12236 \"http://localhost:5000/__/firebase/init.js?useEmulator=true\" \"Mozilla/5.0 (X11; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0\""}}\
</pre>
</details>

When using `firebase emulators:start --only hosting` it responds with the correct file.

<details>
<summary>firebase emulators:start --only hosting --debug output</summary>
<pre>
...
i  hosting: 127.0.0.1 - - [02/Apr/2021:18:54:54 +0000] "GET /__/firebase/init.js?useEmulator=true HTTP/1.1" 200 - "-" "Mozilla/5.0 (X11; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0" {"metadata":{"emulator":{"name":"hosting"},"message":"127.0.0.1 - - [02/Apr/2021:18:54:54 +0000] \"GET /__/firebase/init.js?useEmulator=true HTTP/1.1\" 200 - \"-\" \"Mozilla/5.0 (X11; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0\""}}
i  hosting: 127.0.0.1 - - [02/Apr/2021:18:54:54 +0000] "GET /favicon.ico HTTP/1.1" 200 12236 "http://localhost:5000/__/firebase/init.js?useEmulator=true" "Mozilla/5.0 (X11; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0" {"metadata":{"emulator":{"name":"hosting"},"message":"127.0.0.1 - - [02/Apr/2021:18:54:54 +0000] \"GET /favicon.ico HTTP/1.1\" 200 12236 \"http://localhost:5000/__/firebase/init.js?useEmulator=true\" \"Mozilla/5.0 (X11; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0\""}}
</pre>
</details>

![image](https://user-images.githubusercontent.com/14189387/113443416-52fd3400-93c8-11eb-98d1-ac6af1e6d505.png)

### [REQUIRED] Expected behavior

It should work the same regardless of side effects from other parameters.

### [REQUIRED] Actual behavior

See Steps to reproduce

**Comment by samtstern** [comment]
@johnnyasantoss I am not able to reproduce this. I tried starting Hosting alone, Hosting + Functions, and Hosting + Functions with `--inspect-functions` set and in all cases I was able to get the `__init.js?useEmulator=true` file.

Can you try and help me figure out what's causing it on your side? I'll need to be able to reproduce this to debug it. Also please check if there is anything in the debug logs (run the command with `--debug`) which looks relevant!

**Comment by johnnyasantoss** [comment]
@samtstern I did a thorough look into it and found out that the problem appears to be when the emulators are launched by another parent process. I'm using `yarn run emulators` (using `package.json` scripts) to launch the emulators. When launched like this it results in this weird behavior.

**Comment by samtstern** [comment]
@johnnyasantoss I still cannot reproduce this, I created a brand new Firebase directory and used `yarn` to launch the emulators through a script with exactly the invocation in your report.

At this point I believe it's likely something on your machine. Maybe your emulators are trying to access a Firebase project that does not exist? You could always use the `--project` flag to be sure.

In any case I hope you can understand why I can't really go back and forth trying to guess this now that I've failed to reproduce it twice. If you want me to keep looking into this please try and make a minimal reproduction which I can clone and use: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by johnnyasantoss** [comment]
I've found the problem. I was using an outdated version of the firebase-tools package (`^8.14.1` as a dev dependence on the `package.json` file) :man_facepalming:. So, when running with `yarn` it would use the node_modules version, instead of the global one that was up-to-date.

**Comment by samtstern** [comment]
@johnnyasantoss thanks for following up!
