### ISSUE TITLE
auth:import - facebook provider (didn't create email) - cannot login via facebook after

### ISSUE THREAD

**Issue by horejsi** [firebase/firebase-tools#326]
Hello,
i call auth:import with facebook provider like:

`firebase auth:import usersFirebase.json`

```
{
  "users": [
    {
      "localId": "id",
      "displayName": "test",
      "email": "email",
      "providerUserInfo": [
        {
          "providerId": "facebook.com",
          "rawId": "fbid",
          "email": "email",
          "displayName": "test",
          "photoUrl": ""
        }
      ]
    }
  ]
}
```
after I call `auth:export export` and email isn't in providerUserInfo object.

looks:
```
{
  "localId": "id",
  "email": "email",
  "emailVerified": false,
  "displayName": "test",
  "createdAt": "1493933519000",
  "providerUserInfo": [
    {
      "providerId": "facebook.com",
      "rawId": "fbId",
      "displayName": "test",
      "photoUrl": ""
    }
  ]
}
```

Facebook login after that didn,t work.  Email/Password import works fine.

Can you please help me??
Thanks
Jan

**Comment by wyhao31** [comment]
What's the error message for Facebook login?

**Comment by horejsi** [comment]
I cannot login via Facebook.

**Comment by nicolasgarnier** [comment]
What's the actual issue while login with Facebook? You should be able to login anyways even without initially creating the user via `auth:import`. `auth:import` will simply make sure that that particular user gets the the chosen User ID.

**Comment by horejsi** [comment]
We need to use auth:import, because we migrate users from App Engine to Firebase and we need connect Firebase UID with our user in our Database. Use case:
1. We migrate data and users to our new database
2. we have to create users in Firebase - we use auth:import (email/password and facebook) with specific localId -> Firebase UID
3. we update our database (table users) with pair (email - Firebase UID)
4. in new application user will use same account (email/password or facebook) as before
Problem is that users with email/password work well, but if I create user by auth:import with Facebook provider it is not clear. I tested more and if I create user (generated Test User from Facebook app) using  auth:import - it works. But if I created real facebook user using auth:import it doesn't.
Thanks

**Comment by nicolasgarnier** [comment]
When you say "i cannot login via facebook." why do you say that? Do you get an error message during the auth flow? or is it just that the user a different UID (but the sign-in works). Can you give some actual examples of the input / output and/or error message or screenshots?

In general, the best for us is that you provide a minimal step-by-step way to replicate the issue for us (with examples and code, for example what simplified code you use to create a user with facebook+email password). And the expected result where you see the issue.

**Comment by horejsi** [comment]
I think I solved it.
Thanks
