### ISSUE TITLE
Security vulnerability with netmask

### ISSUE THREAD

**Issue by markgoho** [firebase/firebase-tools#3260]
### [REQUIRED] Environment info

**firebase-tools:** 9.8.0

**Platform:** Windows
``` bash
=== npm audit security report ===                        

# Run  npm update pac-resolver --depth 4  to resolve 1 vulnerability

  High            netmask npm package vulnerable to octal input data

  Package         netmask

  Dependency of   firebase-tools [dev]

  Path            firebase-tools > proxy-agent > pac-proxy-agent >
                  pac-resolver > netmask

  More info       https://npmjs.com/advisories/1658
```

**Comment by bkendall** [comment]
Fixed by #3252. Thanks!

**Comment by kevcenteno** [comment]
Can this be reopened?  `netmask` is still a dependency of firebase-tools as of version 9.10.0.

**Comment by bkendall** [comment]
Yes, `netmask` is still a dependency, but it's been upgraded in our `package.json`. If you re-install `firebase-tools`, it should upgrade the dependencies to match the new requirements (and not show any advisory). If you're seeing an advisory still on a fresh install of `firebase-tools`, please open a new issue with the details.

**Comment by buu700** [comment]
Is https://arstechnica.com/information-technology/2021/09/npm-package-with-3-million-weekly-downloads-had-a-severe-vulnerability related to this / is that currently a non-issue, or will `proxy-agent` now need to be updated?
