### ISSUE TITLE
Firebase database:remove not work with error message " Error: Task index 0 failed: retries exhausted after 4 attempts"

### ISSUE THREAD

**Issue by dhluong90** [firebase/firebase-tools#3272]
### [REQUIRED] Environment info

**firebase-tools:**
9.2.1

**Platform:**
macOS

### [REQUIRED] Test case
Try to clear realtime db via database:remove command.

### [REQUIRED] Steps to reproduce
1. Create collections under realtime db with sizing about 13.7 MB after exporting as Json.
2. Try to clear all with command "firebase database:remove /Conversations --project {project_name}" 

### [REQUIRED] Expected behavior
All the data will clear. 

### [REQUIRED] Actual behavior
Error Message: Error: Task index 0 failed: retries exhausted after 4 attempts

**Comment by samtstern** [comment]
@jpreynat thanks! Since this was fixed I am going to close this issue, let me know if I have misinterpreted your comment.

**Comment by jpreynat** [comment]
You're most welcome @samtstern 
No that's ok, it seems fixed since 9.6.0 and was able to run it successfully with the current latest release 👌
