### ISSUE TITLE
Firestore Emulator: Incorrect merge logic for nested data

### ISSUE THREAD

**Issue by sk-** [firebase/firebase-tools#3278]
**Keywords**: firestore emulator merge nested

The emulator incorrectly merges nested field when calling `set` with `{merge: true}`.

### [REQUIRED] Environment info

**firebase-tools:** 9.9.0

**Platform:** macOS

### [REQUIRED] Test case

```js
test('firestore emulator nested data merge bug', async () => {
  const ref = db.collection('test').doc('docId'); 
  await ref.create({nested: {foo: 'foo'}});
  await ref.set({nested: {bar: 'bar'}}, {merge: true});
  expect((await ref.get()).data()).toEqual({nested: {bar: 'bar'}});
});
```

### [REQUIRED] Steps to reproduce

Run the test and see how it fails.

### [REQUIRED] Expected behavior

`set` calls with merge enabled should only merge top level fields, not nested fields. In order to merge nested fields the `update` call is required.

### [REQUIRED] Actual behavior
`set` merged nested fields, which is different to what happens against the production servers.

**Comment by samtstern** [comment]
@sk- I ran this code in the emulators and in production and in all cases the doc data at the end was this:

```json
{
    "nested": {
        "bar": "bar",
        "foo": "foo"
    }
}
```

So I don't think there is a bug here. Production and the emulators are working the same. If you want to replace the `nested` map entirely do `ref.update("nested", { "bar": "bar" })`
