### ISSUE TITLE
why I always stuck in firebase-tools version 7.9.0?

### ISSUE THREAD

**Issue by AgungLaksana** [firebase/firebase-tools#3283]
so I run `sudo npm install -g firebase-tools` to get firebase-tools to latest version
but I check the version using `npm run firebase tools --version  ` I get 7.9.0 version. 
I expect I will get the latest firebase-tools version (9.10.0)

here is the screenshot: https://i.stack.imgur.com/ahJbf.png

am I missing something?

I am using Node 14 on my Firebase project and npm 7.9.0

it seems the firebase-tools has same version as npm

**Comment by samtstern** [comment]
There doesn't appear to be anything "special" about 7.9.0 that would be keeping you on that version:
https://github.com/firebase/firebase-tools/releases?after=v7.16.0

This is almost certainly an issue with your local `npm` install or your `PATH`. That's not a bug in the`firebase-tools` package so we can't debug it for you here, I would suggest StackOverflow.
