### ISSUE TITLE
Firesbase Storage security rules allow update rule not followed

### ISSUE THREAD

**Issue by hkchakladar** [firebase/firebase-tools#3292]
### [REQUIRED] Environment info: NA. Firesbase Storage security rules related.

**firebase-tools:**

**Platform:**

### [REQUIRED] Steps to reproduce

Firesbase Storage security rules allow update not working, can't prevent file over-write.

Example rule:

````
match /test/{userId}/{imageId} {
    	allow create: if request.auth.uid == userId;
        allow update: if false;
    }
````

Here I'm allowing authenticated users to only 'create' file, but not update/over-write.

### [REQUIRED] Expected behavior

It shouldn't be allowed to update/over-write the existing file.

### [REQUIRED] Actual behavior

But when I'm again uploading a different file, but with same file name {over-writing the existing file}, then it's allowed to update/over-write.

**Comment by samtstern** [comment]
@hkchakladar is this about the Storage emulator or Firebase Storage in production?

**Comment by hkchakladar** [comment]
I'm seeing this in Firebase Storage production.

**Comment by samtstern** [comment]
@hkchakladar this repository is only for issues in the Firebase CLI (including emulators) and we can't help with production backend issues. Please reach out to Firebase support: https://firebase.google.com/support
