### ISSUE TITLE
Method projects.databases.documents.list does not return `nextPageToken` on Firestore Emulator

### ISSUE THREAD

**Issue by IzumiSy** [firebase/firebase-tools#3294]
### [REQUIRED] Environment info

**firebase-tools:** 9.10.0

**Platform:** MacOS Catalina 10.15.7, Node.js v14.15.4

### [REQUIRED] Test case

N/A

### [REQUIRED] Steps to reproduce

1. Launch emulator

```
$ npx firebase emulators:start --only firestore --project aaa
```

2. Add 4 documents

<img width="1169" alt="スクリーンショット 2021-04-20 22 11 33" src="https://user-images.githubusercontent.com/982850/115401478-68c28400-a225-11eb-9120-ea1f7a84b5f8.png">

3. Request documents with `pageSize`.

```
$ curl "http://localhost:8080/v1beta1/projects/aaa/databases/(default)/documents/users?pageSize=2"
{
  "documents": [{
    "name": "projects/aaa/databases/(default)/documents/users/user0",
    "fields": {
      "name": {
        "stringValue": "user0"
      }
    },
    "createTime": "2021-04-20T13:10:58.492Z",
    "updateTime": "2021-04-20T13:10:58.492Z"
  }, {
    "name": "projects/aaa/databases/(default)/documents/users/user1",
    "fields": {
      "name": {
        "stringValue": "user1"
      }
    },
    "createTime": "2021-04-20T13:11:08.096004Z",
    "updateTime": "2021-04-20T13:11:08.096004Z"
  }]
}
```

### [REQUIRED] Expected behavior

The response should have the field: `nextPageToken`.

### [REQUIRED] Actual behavior

No `nextPageToken` field. It must be there.

**Comment by weixifan** [comment]
I filed an internal b/211321185 to track.

**Comment by DomGeoT** [comment]
Hi, is there any update on this being fixed?

**Comment by christhompsongoogle** [comment]
We have a fix out and should be included in the next firestore emulator release.
