### ISSUE TITLE
Running 'firebase init database' overwrites the firebase.json file completely.

### ISSUE THREAD

**Issue by NickChittle** [firebase/firebase-tools#3299]
### [REQUIRED] Environment info

**firebase-tools:**

firebase --version
9.10.0

**Platform:** Ubuntu

### [REQUIRED] Steps to reproduce

- `firebase init firestore`
- Go through firestore workflow
- `cat firebase.json` // Observe that this file has some firestore related configuration in it.
- `firebase init database`
- Go through the database workflow
- `cat firebase.json`
- The firestore section has been overwritten, which does not happen when combined with other products.

### [REQUIRED] Expected behavior

Firebase init should be additive for all products

### [REQUIRED] Actual behavior

Firebase init database overwrites all other configuration.

**Comment by samtstern** [comment]
@NickChittle yikes! I was able to reproduce this.

**Comment by samtstern** [comment]
Looks like this bug was introduced here:
https://github.com/firebase/firebase-tools/pull/2884/files#diff-2373d53b5da0f05c0be1ca69b7959c395f646e20128351f36d66a4a8ce7b76bfR119
