### ISSUE TITLE
operation disrupted on pushing a functions update

### ISSUE THREAD

**Issue by mergenil** [firebase/firebase-tools#330]
I updated the base of functions to 3.7.0 today and can not update or create new functions. I can delete them, that is it. 

I ran --debug on the deploy and just got an infinite poll running waiting for the function to respond it deployed correctly. After 7ish minutes it times out and says it did not deploy correctly.

**Comment by laurenzlong** [comment]
Hey @BafFlynN we are experiencing an outage right now and are working to fix it asap.

**Comment by mergenil** [comment]
@laurenzlong oh, thank you for letting me know :) I will close this.
