### ISSUE TITLE
deployFile.js stops working on 9.9.0+ 'FirebaseError: Failed to authenticate, have you run firebase login?'

### ISSUE THREAD

**Issue by mikehardy** [firebase/firebase-tools#3308]
### [REQUIRED] Environment info

**firebase-tools:** 9.8.0 works, 9.9.0 fails

**Platform:** Ubuntu, probably any

### [REQUIRED] Test case

Deploy a single file to a hosting environment using the nifty single-file deploy script from @puf here https://gist.github.com/puf/e00c34dd82b35c56e91adbc3a9b1c412#file-deployfile-js-L21

### [REQUIRED] Steps to reproduce

install deployFile.js, use it like this as an example (assuming you have a firebase hosting site called "kscoreappdev-dist" and there is a file in the current working directory called "KscoreApp-latest-dev.apk" and you put deployFile.js in a src directory sibling to current working directory:

```
node ../src/deployFile.js "kscoreappdev-dist" "/KScoreApp-latest-dev.apk" commit
```

### [REQUIRED] Expected behavior

If you have already logged in with firebase-tools 9.8.0 things work great. And they do.

### [REQUIRED] Actual behavior

Then you update to firebase-tools 9.9.0 (or 9.10.0 - I checked both) and it does not work

```
FirebaseError: Failed to authenticate, have you run firebase login?
    at requireAuth (/home/mike/work/Kullki/ksocialscore/packages/firebase/node_modules/firebase-tools/lib/requireAuth.js:48:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  children: [],
  context: undefined,
  exit: 1,
  original: Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
      at GoogleAuth.getApplicationDefaultAsync (/home/mike/work/Kullki/ksocialscore/packages/firebase/node_modules/firebase-tools/node_modules/google-auth-library/build/src/auth/googleauth.js:157:19)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async GoogleAuth.getClient (/home/mike/work/Kullki/ksocialscore/packages/firebase/node_modules/firebase-tools/node_modules/google-auth-library/build/src/auth/googleauth.js:504:17)
      at async GoogleAuth.getAccessToken (/home/mike/work/Kullki/ksocialscore/packages/firebase/node_modules/firebase-tools/node_modules/google-auth-library/build/src/auth/googleauth.js:526:24)
      at async autoAuth (/home/mike/work/Kullki/ksocialscore/packages/firebase/node_modules/firebase-tools/lib/requireAuth.js:24:19)
      at async requireAuth (/home/mike/work/Kullki/ksocialscore/packages/firebase/node_modules/firebase-tools/lib/requireAuth.js:45:20),
  status: 500
}
```

But if I use the new `firebase login:list` I see this (except my real domain):

```
Logged in as mike@example.com
```

It appears that the PR #3192 from @samtstern has somehow caused the `requireAuth` method used by the venerable `deployFile` script from @puf to no longer find the credentials. 

Even if I do `firebase login:use mike@example.com` (except with my real domain) - the command works but I get the same failure to find credentials.

I'm guessing it is related to these exact lines:

https://github.com/firebase/firebase-tools/pull/3192/files#diff-5be4488407c9ce7b616366f6eeab35e0f7b80b68c7bbf840ed57a12a49d5ac57L51-L53

It looks like an API change we need to send in an Auth object now instead of requireAuth just finding the default?

Most likely you all weren't aware this was being used externally, but it's not marked internal or anything :-). Not sure on your API guarantees.

Anyway, If I change deployFile like so it works:

```
// add this new import
const { getGlobalDefaultAccount } = require('firebase-tools/lib/auth');

// use the import to get the current default account (assuming that is the account you want...)
const defaultAccount = getGlobalDefaultAccount();

// now send that account in, instead of the empty object before
//requireAuth({}, ['https://www.googleapis.com/auth/cloud-platform'])  // old version, no account
requireAuth(defaultAccount, ['https://www.googleapis.com/auth/cloud-platform'])  // new version, works

```

I'll post the same on the deployFile gist for everyone using it there, but thought I'd open this (and then it will likely be closed?) in case future people search for it

**Comment by samtstern** [comment]
@mikehardy thanks for such a detailed explanation. We recently introduced support for multiple simultaneously logged-in accounts in the Firebase CLI which involved a big internal refactor. The gist you're referencing is importing `firebase-tools` internals which are not part of our public API and may change from release to release. For that reason I am going to close this, although I'll send it along to @puf to see if he has time to update the gist with your solution!

**Comment by mikehardy** [comment]
Puf has already ingested the change, closing works for me and if anyone trips on it now they'll be able to sort things out quickly if they find this. Cheers!
