### ISSUE TITLE
Emulator UI stops responding trying to display large collection

### ISSUE THREAD

**Issue by pcdwr** [firebase/firebase-tools#3313]
I have exported a Firestore database and successfully imported it into the emulator. There are a number of collections. One of the collections contains roughly 25,000 documents. When I attempt to view this collection in the Emulator UI it stops responding and I have to refresh to view other collections. There are several 500 errors in the console. The documents are there in the emulator. I can query and examine them in a Node script.

This problem exists in my web site as well. If I point to the emulator and attempt to display all documents in the collection I get the same errors.

The debug file is too large to upload so I have included some example lines in the attached file.
[partial-firestore-debug.log](https://github.com/firebase/firebase-tools-ui/files/6365814/partial-firestore-debug.log)

**Comment by jakeleventhal** [comment]
I have this as well. the issue seems to be that the emulator doesn't do any pagination logic

**Comment by christhompsongoogle** [comment]
This should be resolved by the latest version released this week. Please let me know if you're still encountering this issue.
