### ISSUE TITLE
Firebase CLI deletes function when "No" is replied to the "Are you sure?" question

### ISSUE THREAD

**Issue by wcalderipe** [firebase/firebase-tools#3314]
Hey, Firebase CLI deletes a function when users reply "No" to the "Are you sure?" question.

![image](https://user-images.githubusercontent.com/3832154/116219408-def64780-a74b-11eb-99ba-3ccc4a3c60c8.png)

### Environment info

**firebase-tools:** 9.8.0

**Platform:** macOS 11.2.3

### Steps to reproduce

1. Deploy a function to Cloud Functions
2. Delete the function using the Firebase CLI `firebase functions:delete <FN_NAME> --region <REGION>`
3. When asked if you're sure or not, reply with "No"

### Expected behavior

```
When deleting a function using Firebase CLI
And I reply "No" to "Are you sure?" question
Then Firebase *does not* delete my function
```

### Actual behavior

```
When deleting a function using Firebase CLI
And I reply "No" to "Are you sure?" question
Then Firebase *deletes* my function
```

**Comment by joehan** [comment]
Thanks for reporting this! I was just able to repro, so I'll get this fixed ASAP.

**Comment by wcalderipe** [comment]
@joehan you're welcome and thanks for taking an action fast 🙌

**Comment by joehan** [comment]
Forgot to close this before!
