### ISSUE TITLE
Hosting no longer deploying

### ISSUE THREAD

**Issue by ArcherEmiya05** [firebase/firebase-tools#3335]
### [REQUIRED] Environment info

9.10.0
Windows 10

### [REQUIRED] Test case

Deploying simple single web page

### [REQUIRED] Steps to reproduce

Deploying simple single web page

### [REQUIRED] Expected behavior

No error, success, not getting stuck forever.

### [REQUIRED] Actual behavior

Either the deployment just got stuck at 0% forever or failed retries exhausted 6 times...

PS: My long time beloved Firebase is constantly having deployment issue this started last year as well with deploying functions :c

**Comment by ArcherEmiya05** [comment]
![image](https://user-images.githubusercontent.com/38008900/117145086-4fa10200-ade5-11eb-8e0b-440f27e23e2d.png)

**Comment by shinycake** [comment]
try temporarily removing the `.git` folder from your public folder, running the deploy command, and then putting it back so you don't lose your git functionality. 

I think there's a new bug where the `.git` folder is not being ignored, I have had this exact issue ever since upgrading firebase-tools to 9.10

**Comment by ArcherEmiya05** [comment]
> 
> 
> try temporarily removing the `.git` folder from your public folder, running the deploy command, and then putting it back so you don't lose your git functionality.
> 
> I think there's a new bug where the `.git` folder is not being ignored, I have had this exact issue ever since upgrading firebase-tools to 9.10

I do not have .git folder in this web project though.

**Comment by kmcnellis** [comment]
Please provide the output of `firebase deploy --only hosting --debug`

**Comment by codecoll** [comment]
I have this issue as well. According to the debug output the server answers with error 409:

Wen uploading this happens six times:

`[time] [hosting][upload] file  (hash) HTTP ERROR 409: [object Headers] Couldn't process request (status=409)
`

And then comes the exhausted error:

`Task <hash> failed: retries exhausted after 6 attempts
`

**Comment by kmcnellis** [comment]
We've rolled out a backend change to fix this.   Can you try to deploy again, and let me know if there's any further issues?

**Comment by codecoll** [comment]
Deploy now finishes without errors. Thanks.

**Comment by ArcherEmiya05** [comment]
It has been fixed as I tried it sorry for late reply!
