### ISSUE TITLE
Node 14 GA

### ISSUE THREAD

**Issue by larssn** [firebase/firebase-tools#3339]
I'll keep it short. It seems Node 14 is out of preview and has entered GA: [Link](https://cloud.google.com/functions/docs/release-notes#:~:text=April%2019%2C%202021,-Cloud%20Functions%20has&text=Cloud%20Functions%20now%20supports%20the,js%2014)

However, firebase-tools still claim it's in beta.

**Comment by samtstern** [comment]
@larssn thanks for keeping us honest!
