### ISSUE TITLE
 FirebaseError: HTTP Error: 403, Unknown Error 

### ISSUE THREAD

**Issue by ghost** [firebase/firebase-tools#3353]
######## #### ########  ######## ########     ###     ######  ########
     ##        ##  ##     ## ##       ##     ##  ##   ##  ##       ##
     ######    ##  ########  ######   ########  #########  ######  ######
     ##        ##  ##    ##  ##       ##     ## ##     ##       ## ##
     ##       #### ##     ## ######## ########  ##     ##  ######  ########

You're about to initialize a Firebase project in this directory:

  C:\Users\kovva\Desktop\testing

[info] 
=== Project Setup
[info] 
[info] First, let's associate this project directory with a Firebase project.
[info] You can create multiple project aliases by running firebase use --add, 
[info] but for now we'll just set up a default project.
[info] 
[debug] [2021-05-11T16:33:39.925Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects pageSize=100
[debug] [2021-05-11T16:33:40.520Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects 200
[debug] [2021-05-11T16:33:40.520Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects [omitted]
[info] i  Using project testing-f9123 (testing) 
[info] 
=== Hosting Setup
[info] 
[info] Your public directory is the folder (relative to your project directory) that
[info] will contain Hosting assets to be uploaded with firebase deploy. If you
[info] have a build process for your assets, use your build's output directory.
[info] 
[debug] [2021-05-11T16:34:00.355Z] >>> [apiv2][query] GET https://www.gstatic.com/firebasejs/releases.json [none]
[debug] [2021-05-11T16:34:00.572Z] <<< [apiv2][status] GET https://www.gstatic.com/firebasejs/releases.json 200
[debug] [2021-05-11T16:34:00.573Z] <<< [apiv2][body] GET https://www.gstatic.com/firebasejs/releases.json {"current":{"version":"8.5.0","browserURL":"https://www.gstatic.com/firebasejs/8.5.0/firebase.js","packageURL":"https://www.gstatic.com/firebasejs/8.5.0/firebase.tgz"},"live":{"version":"8.5","browserURL":"https://www.gstatic.com/firebasejs/live/8.5/firebase.js","packageURL":"https://www.gstatic.com/firebasejs/live/8.5/firebase.tgz"},"components":{"analytics":"https://www.gstatic.com/firebasejs/8.5.0/firebase-analytics.js","app":"https://www.gstatic.com/firebasejs/8.5.0/firebase-app.js","auth":"https://www.gstatic.com/firebasejs/8.5.0/firebase-auth.js","database":"https://www.gstatic.com/firebasejs/8.5.0/firebase-database.js","firestore":"https://www.gstatic.com/firebasejs/8.5.0/firebase-firestore.js","functions":"https://www.gstatic.com/firebasejs/8.5.0/firebase-functions.js","installations":"https://www.gstatic.com/firebasejs/8.5.0/firebase-installations.js","messaging":"https://www.gstatic.com/firebasejs/8.5.0/firebase-messaging.js","storage":"https://www.gstatic.com/firebasejs/8.5.0/firebase-storage.js","performance":"https://www.gstatic.com/firebasejs/8.5.0/firebase-performance.js","remote-config":"https://www.gstatic.com/firebasejs/8.5.0/firebase-remote-config.js","firestore.memory":"https://www.gstatic.com/firebasejs/8.5.0/firebase-firestore.memory.js"}}
[info] +  Wrote out/index.html 
[info] 
[info] i  Detected a .git folder at C:\Users\kovva\Desktop\testing 
[info] i  Authorizing with GitHub to upload your service account to a GitHub repository's secrets store. 
[info] 
[info] Visit this URL on this device to log in:
[info] https://github.com/login/oauth/authorize?client_id=89cf50f02ac6aaed3484&state=1071201010&redirect_uri=http%3A%2F%2Flocalhost%3A9005&scope=read%3Auser%20repo%20public_repo
[info] 
[info] Waiting for authentication...
[debug] [2021-05-11T16:34:06.110Z] >>> HTTP REQUEST POST https://github.com/login/oauth/access_token  
 {"client_id":"89cf50f02ac6aaed3484","client_secret":"3330d14abc895d9a74d5f17cd7a00711fa2c5bf0","code":"0d89ea7c15e621c3842a","redirect_uri":"http://localhost:9005","state":"1071201010"}
[debug] [2021-05-11T16:34:06.600Z] <<< HTTP RESPONSE 200 {"server":"GitHub.com","date":"Tue, 11 May 2021 16:34:07 GMT","content-type":"application/json; charset=utf-8","transfer-encoding":"chunked","vary":"X-PJAX, Accept-Encoding, Accept, X-Requested-With","permissions-policy":"interest-cohort=()","etag":"W/\"5b1ff93d554ad54cf0c48e396df0245d\"","cache-control":"max-age=0, private, must-revalidate","strict-transport-security":"max-age=31536000; includeSubdomains; preload","x-frame-options":"deny","x-content-type-options":"nosniff","x-xss-protection":"0","referrer-policy":"origin-when-cross-origin, strict-origin-when-cross-origin","expect-ct":"max-age=2592000, report-uri=\"https://api.github.com/_private/browser/errors\"","content-security-policy":"default-src 'none'; base-uri 'self'; block-all-mixed-content; connect-src 'self' uploads.github.com www.githubstatus.com collector.githubapp.com api.github.com github-cloud.s3.amazonaws.com github-production-repository-file-5c1aeb.s3.amazonaws.com github-production-upload-manifest-file-7fdce7.s3.amazonaws.com github-production-user-asset-6210df.s3.amazonaws.com cdn.optimizely.com logx.optimizely.com/v1/events wss://alive.github.com; font-src github.githubassets.com; form-action 'self' github.com gist.github.com; frame-ancestors 'none'; frame-src render.githubusercontent.com; img-src 'self' data: github.githubassets.com identicons.github.com collector.githubapp.com github-cloud.s3.amazonaws.com secured-user-images.githubusercontent.com/ *.githubusercontent.com; manifest-src 'self'; media-src 'none'; script-src github.githubassets.com; style-src 'unsafe-inline' github.githubassets.com; worker-src github.com/socket-worker-3f088aa2.js gist.github.com/socket-worker-3f088aa2.js","x-github-request-id":"3D91:1F1C:9C4D19:A8469F:609AB1FE"}
[debug] [2021-05-11T16:34:06.605Z] >>> [apiv2][query] GET https://api.github.com/user [none]
[debug] [2021-05-11T16:34:07.085Z] <<< [apiv2][status] GET https://api.github.com/user 200
[debug] [2021-05-11T16:34:07.086Z] <<< [apiv2][body] GET https://api.github.com/user {"login":"sampath017","id":81136069,"node_id":"MDQ6VXNlcjgxMTM2MDY5","avatar_url":"https://avatars.githubusercontent.com/u/81136069?v=4","gravatar_id":"","url":"https://api.github.com/users/sampath017","html_url":"https://github.com/sampath017","followers_url":"https://api.github.com/users/sampath017/followers","following_url":"https://api.github.com/users/sampath017/following{/other_user}","gists_url":"https://api.github.com/users/sampath017/gists{/gist_id}","starred_url":"https://api.github.com/users/sampath017/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/sampath017/subscriptions","organizations_url":"https://api.github.com/users/sampath017/orgs","repos_url":"https://api.github.com/users/sampath017/repos","events_url":"https://api.github.com/users/sampath017/events{/privacy}","received_events_url":"https://api.github.com/users/sampath017/received_events","type":"User","site_admin":false,"name":null,"company":null,"blog":"","location":null,"email":null,"hireable":null,"bio":null,"twitter_username":null,"public_repos":0,"public_gists":0,"followers":1,"following":0,"created_at":"2021-03-22T04:10:30Z","updated_at":"2021-05-11T15:37:01Z","private_gists":0,"total_private_repos":0,"owned_private_repos":0,"disk_usage":0,"collaborators":0,"two_factor_authentication":false,"plan":{"name":"pro","space":976562499,"collaborators":0,"private_repos":9999}}
[info] 
[info] +  Success! Logged into GitHub as sampath017 
[info] 
[debug] [2021-05-11T16:34:19.952Z] >>> [apiv2][query] GET https://api.github.com/repos/ultron-AGI/testing/actions/secrets/public-key type=owner
[debug] [2021-05-11T16:34:20.399Z] <<< [apiv2][status] GET https://api.github.com/repos/ultron-AGI/testing/actions/secrets/public-key 403
[debug] [2021-05-11T16:34:20.401Z] <<< [apiv2][body] GET https://api.github.com/repos/ultron-AGI/testing/actions/secrets/public-key {"message":"Must have admin rights to Repository.","documentation_url":"https://docs.github.com/rest/reference/actions#get-a-repository-public-key"}
[debug] [2021-05-11T16:35:25.191Z] >>> [apiv2][query] GET https://api.github.com/repos/sampath017/testing/actions/secrets/public-key type=owner
[debug] [2021-05-11T16:35:25.582Z] <<< [apiv2][status] GET https://api.github.com/repos/sampath017/testing/actions/secrets/public-key 404
[debug] [2021-05-11T16:35:25.584Z] <<< [apiv2][body] GET https://api.github.com/repos/sampath017/testing/actions/secrets/public-key {"message":"Not Found","documentation_url":"https://docs.github.com/rest/reference/actions#get-a-repository-public-key"}
[debug] [2021-05-11T16:35:38.390Z] >>> [apiv2][query] GET https://api.github.com/repos/sampath017/testing/actions/secrets/public-key type=owner
[debug] [2021-05-11T16:35:38.813Z] <<< [apiv2][status] GET https://api.github.com/repos/sampath017/testing/actions/secrets/public-key 404
[debug] [2021-05-11T16:35:38.814Z] <<< [apiv2][body] GET https://api.github.com/repos/sampath017/testing/actions/secrets/public-key {"message":"Not Found","documentation_url":"https://docs.github.com/rest/reference/actions#get-a-repository-public-key"}

it says must have admin access but I am the owner of that organization.

**Comment by samtstern** [comment]
When filing an issue please follow the issue template. Looks like there's an issue with this repo:
https://github.com/ultron-AGI/testing

Either:

- You don't have permission to access the repo
- You don't have permission to add the Firebase Github App to the `ultron-AGI` organization or the repo

See:

- https://github.com/firebase/firebase-tools/issues/3143
- https://github.com/firebase/firebase-tools/issues/2763

**Comment by sampath017** [comment]
I filled it but no luck 😔

**Comment by sampath017** [comment]
ya solved, magically after pushing to the repo and after a while, it asked for permission. but firebase CLI should log better output for errors.

**Comment by sampath017** [comment]
`https://github.com/FirebaseExtended/action-hosting-deploy/issues/40#issuecomment-748017911 `this helped me
