### ISSUE TITLE
DELETE http://10.0.2.2:8080/emulator/v1/projects/<project_id>/databases/(default)/documents from Android Emulator.

### ISSUE THREAD

**Issue by jgavazzisp** [firebase/firebase-tools#3367]
### [REQUIRED] Environment info

9.10.2

**firebase-tools:**

macOS

**Platform:**

### [REQUIRED] Test case

Call `DELETE http://10.0.2.2:8080/emulator/v1/projects/<project_id>/databases/(default)/documents` from an Android emulator.

Trying to calling `CURL http://localhost:8080/emulator/v1/projects/<project_id>/databases/(default)/documents` from computer works as expected.

### [REQUIRED] Steps to reproduce

Call `DELETE http://10.0.2.2:8080/emulator/v1/projects/<project_id>/databases/(default)/documents` from Android an emulator.

### [REQUIRED] Expected behavior

Firestore database deleted.

### [REQUIRED] Actual behavior

Actual result: 404 HTTP Code and no database deleted.

Thanks

**Comment by samtstern** [comment]
@jgavazzisp this is not enough information to debug ... can you show actual code and logs here? Are there any logs from the emulator indicating it got the request? What about logs from your Android HTTP client?

If it works from CURL there is a high likelihood this is an error in your Android code and not an issue with the emulators, HTTP servers don't really care what platform their clients are!

**Comment by samtstern** [comment]
Ah I see your comment here:
https://github.com/firebase/firebase-tools/issues/3049#issuecomment-840970345

The problem is you're literally using `{projectId}` in the URL. Please replace that with your actual project ID!

**Comment by jgavazzisp** [comment]
@samtstern that was an example, I'm using the proper project id as follow:

![image](https://user-images.githubusercontent.com/309389/118325905-45ef6b00-b558-11eb-9986-8c2f15d0442f.png)

**Comment by samtstern** [comment]
Thanks for clarifying, in which case I'd need more info to look into this: https://github.com/firebase/firebase-tools/issues/3367#issuecomment-841101804
