### ISSUE TITLE
How to use auth:import ?

### ISSUE THREAD

**Issue by hgssk** [firebase/firebase-tools#337]
Hi
Now,I try to use auth:import.

【users.json】
{
  "users": [
    {
      "localId": "1",
      "emailVerified": null,
      "email": "123456789@test.com",
      "passwordHash": "15E2B0D3C33891EBB0F1EF609EC419420C20E320CE94C65FBC8C3312448EB225",
      "salt":null,
    },
  ]
}

【terminal】
npm run firebase auth:import ./users.json --hash-algo=HMAC_SHA256 --hash-key=hogehoge
↓
⚠  No hash algorithm specified. Password users cannot be imported.
Processing ./users.json (231 bytes)
Starting importing 1 account(s).
✔  Imported successfully.

How to apecify hash algorithm ??

**Comment by wyhao31** [comment]
It seems the --hash-algo parameter doesn't get passed to bin/firebase correctly? Could you use `firebase` directly rather than `npm run ..` ?

**Comment by hgssk** [comment]
Thanks ,wyhao31.

【terminal】
firebase auth:import ./users.json --hash-algo=HMAC_SHA256 --hash-key=hogehoge
↓
command not found: firebase

How can I get through the path the --hash-algo parameter ?

**Comment by wyhao31** [comment]
I think you should add `bin/firebase` to your system path if you want to run "firebase" directly.

**Comment by hgssk** [comment]
It work ! Thanks @wyhao31 
But I don't know how to create passwordhash.

"passwordHash": "15E2B0D3C33891EBB0F1EF609EC419420C20E320CE94C65FBC8C3312448EB225",
means "123456789" made by online-tool.

**Comment by wyhao31** [comment]
@hgssk 

What's online-tool? What's the hash algorithm used in online-tool?

**Comment by hgssk** [comment]
@wyhao31 Thanks a lot.

I used these hash generator.
ex)
[http://www.convertstring.com/ja/Hash/SHA256](url)

I choose SHA256 hash.

**Comment by wyhao31** [comment]
Sorry for the delay. You can use the online tool to generate SHA256 hash. If you want to use `auth:import`, you can specify `hash-algo` to SHA256. I think `rounds` should be 1.

You can take a look at our doc [here](https://firebase.google.com/docs/cli/auth). Thanks.

**Comment by hgssk** [comment]
@wyhao31 
Thanks !

This is users.json
`{
  "users": [
    {
      "localId": "1",
      "emailVerified": null,
      "email": "123@test.com",
      "passwordHash": "15E2B0D3C33891EBB0F1EF609EC419420C20E320CE94C65FBC8C3312448EB225",
      "salt":null,
    },
    {
      "localId": "2",
      "emailVerified": null,
      "email": "321@test.com",
      "passwordHash": "15E2B0D3C33891EBB0F1EF609EC419420C20E320CE94C65FBC8C3312448EB225",
      "salt":null,
    },
  ]
}`

15E2B0D3C33891EBB0F1EF609EC419420C20E320CE94C65FBC8C3312448EB225 = 123456789

and I tried to use command.
 `firebase-migration firebase auth:import ./users.json --hash-algo=SHA256 --hash-key=hogehoge --rounds=1
Processing ./users.json (429 bytes)
Starting importing 2 account(s).
✔  Imported successfully.
`
I think this is OK.

but I cannot use password 123456789...

**Comment by efranco2012** [comment]
Does anyone have the proper steps for this to work?

**Comment by efranco2012** [comment]
Found the solution here using node crypto for anyone else that may run into the same issue.   https://stackoverflow.com/questions/40798916/cant-import-user-account-with-cli-firebase-authimport-command

**Comment by wyhao31** [comment]
@hgssk @efranco2012 

I believe the passwordHash in the example (`15E2B0D3C33891EBB0F1EF609EC419420C20E320CE94C65FBC8C3312448EB225`) is base16 encoding, while CLI requires base64 encoding. You should do the translation from base16 to base64.

**Comment by bkendall** [comment]
Due to lack of activity, I'm closing this issue. If you have further issues, please open a new bug with the appropriate information! Thanks!
