### ISSUE TITLE
httpsCallable REST API interface uses field `result` instead of `data` - conflicts with the docs

### ISSUE THREAD

**Issue by akauppi** [firebase/firebase-tools#3377]
### [REQUIRED] Environment info

`firebase-tools` 9.10.2

**Platform:** macOS

### [REQUIRED] Test case

Can prepare one of my repos as a test case. This thing is pretty straightforward to see, though, so let me know if a minimum-viable is even needed.

### [REQUIRED] Steps to reproduce

1. Start an emulator, with a `httpsCallable` in it

   eg. `firebase emulators:start --project=fns-test --config firebase.json --only functions,firestore`

2. Exercise the said callable using REST API, not a client.

   ```
   $ URI_CALL='http://localhost:5002/fns-test/us-central1/greet'
   $ curl -v -X POST -H "Content-Type: application/json" -d "{ \"data\": \"ABC\" }" $URI_CALL
   ```

### [REQUIRED] Expected behavior

According to the [Protocol specification for https.onCall](https://firebase.google.com/docs/functions/callable-reference):

>The response from a client endpoint is always a JSON object. **At a minimum it contains either data or error, along with any optional fields.** If the response is not a JSON object, or does not contain data or error, the client SDK should treat the request as failed with Google error code INTERNAL (13).
>
>`error` - [...]
>`data` - The value returned by the function. [...]
>**If other fields are present, they should be ignored.**

Based on this, I am expecting:

```
{"data":"Greetings, ABC."}
```

### [REQUIRED] Actual behavior

```
{"result":"Greetings, ABC."}
```

The JS SDK client turns this into `data` - but based on the documentation it should be under that name already in the wire.

Also, you might want to check the notion about optional fields, in the doc (highlighted above).  I don't think there are any. Currently, the text both mentions "optional fields" but also states that any such should be ignored by the client. I think you can document that only `data` and `error` are expected fields.

**Comment by inlined** [comment]
Good catch! The input is {data} and the output is {result}. We'll update the docs.

**Comment by inlined** [comment]
Closing the bug. The fix is now checked in on our backend and will roll out with the next release.
