### ISSUE TITLE
Cloud functions with rewrite throws 500, without rewrite works

### ISSUE THREAD

**Issue by rendomnet** [firebase/firebase-tools#3391]
Steps to reproduce
Setup rewrite in firebase.json:
    "rewrites": [
      {
        "source": "/helloworld",
        "function": "helloWorld"
      }
    ]

firebase deploy --only functions,hosting

Expected behavior
Function should send "Hello from Firebase!" to the browser

Actual behavior
When I call function directly it works all the time
https://us-central1-****.cloudfunctions.net/helloWorld

if I call it https://example.com/helloWorld 
Sometimes it is working sometime 500 Internal Server Error
"firebase-functions": "3.8.0",

**Comment by mbleigh** [comment]
This was likely due to [a Firebase Hosting incident](https://status.firebase.google.com/incidents/brqdR99qQURSNLqN2v75) which is now resolved.
