### ISSUE TITLE
Unexpected Firebase Cloud Storage Emulator behaviour when objects uploaded using the Admin SDK and the Web SDK

### ISSUE THREAD

**Issue by ammanz** [firebase/firebase-tools#3393]
### [REQUIRED] Environment info

**firebase-tools:** 9.11.0

**node:** v14.16.0

**Platform:** Manjaro

### Setup

```
git clone https://github.com/ammanz/firebase-cloud-storage-emulator-issue.git
cd firebase-cloud-storage-emulator-issue && npm ci
firebase emulators:start`
```

### [REQUIRED] Steps to reproduce

1. `FIREBASE_STORAGE_EMULATOR_HOST=localhost:9199 node firebase-admin.js` 
2. Open emulator UI on Google Chrome and go to the storage emulator.
3. Click on any of the uploaded files in the default bucket.

### [REQUIRED] Expected behavior

- The detail pane of the image should show like the following: 
![image](https://user-images.githubusercontent.com/39636472/119075401-8c542800-b9a5-11eb-8f2b-95847f538483.png)

### [REQUIRED] Actual behavior

- Whole window goes blank, and does not revert unless you manually reload the page.

- The following is logged to the browser console:
```
It looks like you're using the development build of the Firebase JS SDK.
When deploying Firebase apps to production, it is advisable to only import
the individual SDK components you intend to use.

For the module builds, these are available in the following manner
(replace <PACKAGE> with the name of a component - i.e. auth, database, etc):

CommonJS Modules:
const firebase = require('firebase/app');
require('firebase/<PACKAGE>');

ES Modules:
import firebase from 'firebase/app';
import 'firebase/<PACKAGE>';

Typescript:
import firebase from 'firebase/app';
import 'firebase/<PACKAGE>';

(anonymous) @ index.ts:18
react-dom.production.min.js:225 FirebaseError: Firebase Storage: The given file does not have any download URLs. (storage/no-download-url)
ms @ react-dom.production.min.js:225
scheduler.production.min.js:12 Uncaught FirebaseError: Firebase Storage: The given file does not have any download URLs. (storage/no-download-url)
```
- Output of command with --debug flag:
[test-case-1-firebase-debug.log](https://github.com/firebase/firebase-tools/files/6519807/test-case-1-firebase-debug.log)
[test-case-1-firestore-debug.log](https://github.com/firebase/firebase-tools/files/6519808/test-case-1-firestore-debug.log)

### [REQUIRED] Steps to reproduce

1. `FIREBASE_STORAGE_EMULATOR_HOST=localhost:9199 node firebase-web-sdk.js` 
2. You need to manually end the node script in the terminal with CTRL+C.
3. Open emulator UI on Google Chrome and go to the storage emulator.
4. Click on any of the uploaded files in the default bucket.

### [REQUIRED] Expected behavior

- Same as first test case.

### [REQUIRED] Actual behavior

- The image thumbnail is missing in the detail pane:
![image](https://user-images.githubusercontent.com/39636472/119076163-f4573e00-b9a6-11eb-984d-e20f07aaa2b0.png)

- No errors are logged to the browser console.
- Output of command with --debug flag:
[test-case-2-firebase-debug.log](https://github.com/firebase/firebase-tools/files/6519819/test-case-2-firebase-debug.log)
[test-case-2-firestore-debug.log](https://github.com/firebase/firebase-tools/files/6519820/test-case-2-firestore-debug.log)

**Comment by ammanz** [comment]
One more thing that's not directly related, I think the environment variable in the [official documentation](https://firebase.google.com/docs/emulator-suite/connect_storage) has a typo: 
![image](https://user-images.githubusercontent.com/39636472/119078794-bc062e80-b9ab-11eb-9af8-f084c41877e8.png)

It should be `FIREBASE_STORAGE_EMULATOR_HOST`. I'm not entirely sure if this is the proper place to bring this up.

**Comment by abeisgoat** [comment]
Can you report the UI issue on the [firebase/firebase-tools-ui](https://github.com/firebase/firebase-tools-ui)?

I've reported the typo internally so it'll get sorted!

**Comment by nCr78** [comment]
@abeisgoat This issue isn't just on the firebase-tools-ui. You can't access (getDownloadURL) anything uploaded to the storage emulator through functions emulator.

Are there any workarounds for this until it gets fixed?

**Comment by ARMATAV** [comment]
This is broken even in the case where you're calling `getDownloadURL` on the frontend with the react library - `no-download-url` with emulator.
