### ISSUE TITLE
PubSub emulator leaves duplicates in the cache (CI)

### ISSUE THREAD

**Issue by akauppi** [firebase/firebase-tools#3395]
### [REQUIRED] Environment info

**firebase-tools:** 9.11.0

**Platform:** macOS

### [REQUIRED] Test case

Setting up PubSub emulator leaves both `pubsub-emulator-0.1.0` and `pubsub-emulator-0.1.0.zip` in the `.cache/firebase/emulators` folder.

I would like to prepare a CI image that has the Firebase emulator images prefetched.

BUG: I think `firebase setup:emulators:pubsub` would be better if it left just one of the two: directory or the `zip` file.

WORK-AROUND: If I know, which one is best to left, I can remove the other one in the Dockerfile. This would reduce the image size by 35MB.

### [REQUIRED] Steps to reproduce

```
$ firebase setup:emulators:pubsub
```

```
# ls -al ~/.cache/firebase/emulators/
...
-rwxr-xr-x    1 root     root      60204988 May 20 19:31 cloud-firestore-emulator-v1.11.15.jar
-rwxr-xr-x    1 root     root      28910604 May 20 19:31 firebase-database-emulator-v4.7.2.jar
drwxr-xr-x    3 root     root          4096 May 20 19:31 pubsub-emulator-0.1.0
-rw-------    1 root     root      36623622 May 20 19:31 pubsub-emulator-0.1.0.zip
```

### [REQUIRED] Expected behavior

Only one entry for PubSub.

### [REQUIRED] Actual behavior

Two entries for PubSub. Only one for the other emulators.

**Comment by samtstern** [comment]
@akauppi you should be able to remove the `.zip` file safely, however this is only an implementation detail and there's no guarantee that we won't change the caching behavior in the future.
