### ISSUE TITLE
--except is ignored during hosting deployment

### ISSUE THREAD

**Issue by prilutskiy** [firebase/firebase-tools#3397]
### Environment info

**firebase-tools:** 9.11.0

**Platform:** macOS

### Test case

Hi all,
`firebase deploy --only hosting:@my-project/my-app` works as expected, however `firebase deploy --except hosting:@my-project/my-app` does not. Instead, it ignores the `--except` and deploys all the websites.

As a temporary workaround I'm doing the following:

```
yarn firebase deploy --except hosting
yarn firebase deploy --only hosting:@my-project/my-app1,hosting:@my-project/my-app2
```

but it's too verbose and unnecessary complex.

**Comment by bkendall** [comment]
Sorry to only get around to this now, but you're right - I can still reproduce this. I have a PR out now to fix it! :)
