### ISSUE TITLE
Can't deploy my project. 

### ISSUE THREAD

**Issue by svkomin** [firebase/firebase-tools#340]
Can't deploy my project after firebase-cli update to version 3.9.0

$ firebase deploy

=== Deploying to 'mass-insta'...

Error: An unexpected error has occurred.

Having trouble? Try again or contact support with contents of firebase-debug.log

[firebase-debug.txt](https://github.com/firebase/firebase-tools/files/1017541/firebase-debug.txt)

**Comment by laurenzlong** [comment]
Hi @svkomin did you already initialize a Firebase project in this directory by running "firebase init"?

**Comment by laurenzlong** [comment]
And which features did you set up for this Firebase project? ( We recently changed the firebase init flow, so that you have to explicitly select which features you want to initialize). Can you tell me what are the keys in firebase.json?
