### ISSUE TITLE
Emulator suite support for firebase extensions

### ISSUE THREAD

**Issue by Spitzbua** [firebase/firebase-tools#3405]
### [REQUIRED] Environment info

**firebase-tools:**
9.11.0

**Platform:**
Windows 10

### [REQUIRED] Test case

For the development of new features we use the emulator suite to ensure that there is no impact on the production environment. As far as I know the function emulator does not support Firebase extension. It only emulates functions that are included in the local functions\index.js.

Now there is a new update of a Firebase extension (firestore-stripe-subscriptions) that we use. The update includes a new feature that we would like to implement. 

In general we need a way to develop and test the purchase flow (in this case) locally in combination with the stripe test environment (test env config: api keys, endpoints, webhooks).

Can you show me a way to achieve this? Is there a best practice here?

How can the firebase extension function be used on the emulator in addition to the project-specific functions?

### [REQUIRED] Steps to reproduce

- Install any firebase extension via firebase console or firebase cli
- Start emulation using firebase emulators:start (function emulator)

### [REQUIRED] Expected behavior

- Using firebase emulators:start emulates the project specific functions contained in functions\index.js and the installed firebase extension specific functions

### [REQUIRED] Actual behavior

- Using firebase emulators:start emulates only project specific functions contained in functions\index.js

**Comment by joehan** [comment]
Hey @Spitzbua, this is not something that is currently supported, but it is a phenomenal feature request. We've added this to our roadmap and I recently prototyped something similar for an internal hackathon; however, it will be some time before this is available. Stay tuned!

**Comment by KenCorbettJr** [comment]
This would be really useful for the Distributed Counter extension.  We are using that more and more and it would be so nice to have the distributed counter working locally in the emulator.

**Comment by zhigang1992** [comment]
Deploying to cloud function is extremely slow, and the Firebase Extensions are the only part that's holding us back on trying to all in with Emulators.

Right now it's too much work to manually integration these just for the emulators.

**Comment by Youdaman** [comment]
Would love to see this for the Stripe extensions. Not ideal testing in a live environment.

**Comment by pascalbe-humanize** [comment]
I would also be super interested in this feature. Making the testing env as similar to the prod env as possible is really important. 

Looking forward to that feature :)

**Comment by risalfajar** [comment]
It has been several months, is there any update?

**Comment by kuechlerm** [comment]
Shouldn't this be covered by : https://firebase.google.com/docs/emulator-suite/use_extensions  ?
I tried it with the firebase/storage-resize-images extension but cannot start the emulators anymore.

**Comment by risalfajar** [comment]
> Shouldn't this be covered by: https://firebase.google.com/docs/emulator-suite/use_extensions ? I tried it with the firebase/storage-resize-images extension but cannot start the emulators anymore.

Yes, it's just added this year. I think this issue can be closed now. @Spitzbua

**Comment by yuchenshi** [comment]
As some of you may have found out, this is now a supported use case with the new extensions emulator. Closing.
