### ISSUE TITLE
firestore-debug.log is empty despite debug statements in the security rules

### ISSUE THREAD

**Issue by wpghijsen** [firebase/firebase-tools#3411]
### [REQUIRED] Environment info

**firebase-tools:**
9.11.0

**Platform:**
Windows 10

### [REQUIRED] Test case

https://stackoverflow.com/questions/67696894/testing-firestore-security-rules-why-is-firestore-debug-log-empty-even-after-de

### [REQUIRED] Steps to reproduce

The steps to 
Using the files in the above stackoverflow link I ran

firebase --debug emulators:start
npm test.js

### [REQUIRED] Expected behavior

Something should show up in firestore-debug.log, but it remains empty.

### [REQUIRED] Actual behavior

Nothing shows up in firestore-debug.log

firebase-debug.log:
```
[debug] [2021-05-27T03:03:37.852Z] ----------------------------------------------------------------------
[debug] [2021-05-27T03:03:37.854Z] Command:       C:\Program Files (x86)\nodejs\node.exe C:\Users\wpghi\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js --debug emulators:start
[debug] [2021-05-27T03:03:37.854Z] CLI Version:   9.11.0
[debug] [2021-05-27T03:03:37.854Z] Platform:      win32
[debug] [2021-05-27T03:03:37.854Z] Node Version:  v14.17.0
[debug] [2021-05-27T03:03:37.855Z] Time:          Wed May 26 2021 20:03:37 GMT-0700 (Pacific Daylight Time)
[debug] [2021-05-27T03:03:37.855Z] ----------------------------------------------------------------------
[debug] 
[debug] [2021-05-27T03:03:37.863Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2021-05-27T03:03:37.864Z] > authorizing via signed-in user (wpghijsen@gmail.com)
[info] i  emulators: Starting emulators: firestore {"metadata":{"emulator":{"name":"hub"},"message":"Starting emulators: firestore"}}
[warn] !  emulators: It seems that you are running multiple instances of the emulator suite for project treetop-9c1b7. This may result in unexpected behavior. 
[debug] [2021-05-27T03:03:37.884Z] [hub] writing locator at C:\Users\wpghi\AppData\Local\Temp\hub-treetop-9c1b7.json
[debug] [2021-05-27T03:03:37.924Z] Ignoring unsupported arg: projectId {"metadata":{"emulator":{"name":"firestore"},"message":"Ignoring unsupported arg: projectId"}}
[debug] [2021-05-27T03:03:37.925Z] Ignoring unsupported arg: auto_download {"metadata":{"emulator":{"name":"firestore"},"message":"Ignoring unsupported arg: auto_download"}}
[debug] [2021-05-27T03:03:37.926Z] Starting Firestore Emulator with command {"binary":"java","args":["-Dgoogle.cloud_firestore.debug_log_level=FINE","-Duser.language=en","-jar","C:\\Users\\wpghi\\.cache\\firebase\\emulators\\cloud-firestore-emulator-v1.11.15.jar","--host","localhost","--port",8080,"--rules","C:\\Users\\wpghi\\treetop\\firestore.rules"],"optionalArgs":["port","webchannel_port","host","rules","functions_emulator","seed_from_export"],"joinArgs":false} {"metadata":{"emulator":{"name":"firestore"},"message":"Starting Firestore Emulator with command {\"binary\":\"java\",\"args\":[\"-Dgoogle.cloud_firestore.debug_log_level=FINE\",\"-Duser.language=en\",\"-jar\",\"C:\\\\Users\\\\wpghi\\\\.cache\\\\firebase\\\\emulators\\\\cloud-firestore-emulator-v1.11.15.jar\",\"--host\",\"localhost\",\"--port\",8080,\"--rules\",\"C:\\\\Users\\\\wpghi\\\\treetop\\\\firestore.rules\"],\"optionalArgs\":[\"port\",\"webchannel_port\",\"host\",\"rules\",\"functions_emulator\",\"seed_from_export\"],\"joinArgs\":false}"}}
[info] i  firestore: Firestore Emulator logging to firestore-debug.log {"metadata":{"emulator":{"name":"firestore"},"message":"Firestore Emulator logging to \u001b[1mfirestore-debug.log\u001b[22m"}}
[debug] [2021-05-27T03:03:39.734Z] Ignoring unsupported arg: auto_download {"metadata":{"emulator":{"name":"ui"},"message":"Ignoring unsupported arg: auto_download"}}
[debug] [2021-05-27T03:03:39.734Z] Ignoring unsupported arg: port {"metadata":{"emulator":{"name":"ui"},"message":"Ignoring unsupported arg: port"}}
[debug] [2021-05-27T03:03:39.735Z] Starting Emulator UI with command {"binary":"node","args":["C:\\Users\\wpghi\\.cache\\firebase\\emulators\\ui-v1.5.0\\server.bundle.js"],"optionalArgs":[],"joinArgs":false} {"metadata":{"emulator":{"name":"ui"},"message":"Starting Emulator UI with command {\"binary\":\"node\",\"args\":[\"C:\\\\Users\\\\wpghi\\\\.cache\\\\firebase\\\\emulators\\\\ui-v1.5.0\\\\server.bundle.js\"],\"optionalArgs\":[],\"joinArgs\":false}"}}
[info] i  ui: Emulator UI logging to ui-debug.log {"metadata":{"emulator":{"name":"ui"},"message":"Emulator UI logging to \u001b[1mui-debug.log\u001b[22m"}}
[debug] [2021-05-27T03:03:39.850Z] Web / API server started at http://localhost:4000
 {"metadata":{"emulator":{"name":"ui"},"message":"Web / API server started at http://localhost:4000\n"}}
[info] 
┌─────────────────────────────────────────────────────────────┐
│ ✔  All emulators ready! It is now safe to connect your app. │
│ i  View Emulator UI at http://localhost:4000                │
└─────────────────────────────────────────────────────────────┘

┌───────────┬────────────────┬─────────────────────────────────┐
│ Emulator  │ Host:Port      │ View in Emulator UI             │
├───────────┼────────────────┼─────────────────────────────────┤
│ Firestore │ localhost:8080 │ http://localhost:4000/firestore │
└───────────┴────────────────┴─────────────────────────────────┘
  Emulator Hub running at localhost:4400
  Other reserved ports: 4500
```

Issues? Report them at https://github.com/firebase/firebase-tools/issues and attach the *-debug.log files.
 
ui-debug.log
Web / API server started at http://localhost:4000

firestore-debug.log (empty)

**Comment by samtstern** [comment]
@wpghijsen in your test case on SO it looks like this is the line that would trigger `debug()`

```
allow update: if ((resource.data.authorId == request.auth.uid) ||
        userIsModerator()) && editOnlyChangesFields(["visibility", "content"]);
```

There's a lot going on in your test case, and it's hard to even determine if that `&&` condition will run at all! Instead could you try something much simpler? Consider this:

```
allow write: if debug(true)
```

Then write a test against that rule. If you still don't see anything in `firestore-debug.log` then we'll know we have a bug. Right now it's hard to say if the bug is in your code, your rules, or in the CLI/Emulators.

**Comment by wpghijsen** [comment]
Hi Sam,

Thanks for your response. As per your request, I changed the security rule in question to:

match /posts/{postId} {
      allow read: if (resource.data.visibility == "public") ||
        (resource.data.authorId == request.auth.uid);
      allow update: if ((resource.data.authorId == request.auth.uid) ||
        userIsModerator()) && editOnlyChangesFields(["visibility", "content"]);
      allow create: if debug(true);
    }

I then tested that the command would succeed by doing the following test (which passed):

it("Testing Post Create with Debug", async() => {
    const postPath = "/posts/post_123";
    const db = getFirestore(myAuth);
    const testDoc = db.doc(postPath);
    await firebase.assertSucceeds(testDoc.set({authorId: myId, visibility: "private", content: "lorem ipsum", headline: "Firebase Rules"}));
  });

As you can see the debug statement should have logged something, but sadly the firestore-debug.log is empty. 
Attached is the firebase-debug.log for your examination.

Thanks,

Willem
[firebase-debug.log](https://github.com/firebase/firebase-tools/files/6556951/firebase-debug.log)

**Comment by samtstern** [comment]
Ok a few more things here:

- You have provided `firebase-debug.log` but the debug statements would show up in `firestore-debug.log`
- Your `firebase-debug.log` has some "Invalid variable: request" warnings. Can you show your full rules?
- Are you sure your request is hitting the emulator and not production? How are you ensuring that in your tests?
- Are you sure there is no data at the location when you do `testDoc.set`? If there is already data there that would hit the `update` rule not `create`

**Comment by wpghijsen** [comment]
Hi Sam,

I provided the firebase-debug.log as I was not sure if you needed that info. 

The full rules (after updating for the debug statement you wanted) are as follows:
`
rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {

    function userIsModerator() {
      return request.auth.token.isModerator == true;
    }

    function documentFieldsCheckOut(requiredFields, optionalFields) {
      let allFields = requiredFields.concat(optionalFields);
      return request.resource.data.keys().hasOnly(allFields) &&
        request.resource.data.keys().hasAll(requiredFields);
    }

    function editOnlyChangesFields(allowedFields) {
      return debug(debug(request.resource.data.keys()).hasOnly(allowedFields));
    }

    match /{document=**} {
      allow read, write: if false;
    }
    match /readonly/{docId} {
      allow read: if true;
      allow write: if false;
    }
    match /users/{userId} {
      allow write: if (request.auth.uid == userId);
    }
    match /posts/{postId} {
      allow read: if (resource.data.visibility == "public") ||
        (resource.data.authorId == request.auth.uid);
      allow update: if ((resource.data.authorId == request.auth.uid) ||
        userIsModerator()) && editOnlyChangesFields(["visibility", "content"]);
      allow create: if debug(true);
    }
    }
    match /rooms/{roomId} {
      function userIsRoomMod() {
        return request.auth.uid in (get(/databases/$(database)/documents/rooms/$(roomId)).data.roomMods);
      }
      //Security rules for rooms go here
      match /posts/{postId} {
        allow update: if (resource.data.authorId == request.auth.uid) ||
          userIsRoomMod();
      }

    }
  }
}
`

I am pretty certain that the rules are being tested against the local instance, as the database on the emulator, http://localhost:4000,  gets updated and not the production instance.

The full tests I am running in test.js are:
`
const assert = require('assert');
const firebase = require('@firebase/testing');

const MY_PROJECT_ID = "my-project-3we3e";
const myId = "user_abc";
const theirId = "user_xyz";
const myAuth = {uid: myId, email: "abc@gmail.com"};
const modId = "user_mod";
const modAuth = {uid: modId, email: "mod@gmail.com", isModerator: true};

function getFirestore(auth) {
  return firebase.initializeTestApp({projectId: MY_PROJECT_ID, auth: auth}).firestore();
}

function getAdminFirestore() {
  return firebase.initializeAdminApp({projectId: MY_PROJECT_ID}).firestore();
}

beforeEach(async() => {
  await firebase.clearFirestoreData({projectId:MY_PROJECT_ID});
});

describe("Treetop App Functions", () => {

  it("Enforces Security Rule 1", () => {
    assert.equal(2+2,4);
  });

  it("Can read items in read-only section", async() => {
    const db = getFirestore(null);
    const testDoc = db.collection("readonly").doc("testDoc");
    await firebase.assertSucceeds(testDoc.get());
  });

  it("Cannot write items in read-only section", async() => {
    const db = getFirestore(null);
    const testDoc = db.collection("readonly").doc("testDoc2");
    await firebase.assertFails(testDoc.set({foo: "bar"}));
  });
  
  it("Can write user document with the same ID", async() => {
    const db = getFirestore(myAuth);
    const testDoc = db.collection("users").doc(myId);
    await firebase.assertSucceeds(testDoc.set({foo: "bar"}));
  });

  it("Cannot write user document with a different ID", async() => {
    const db = getFirestore(myAuth);
    const testDoc = db.collection("users").doc(theirId);
    await firebase.assertFails(testDoc.set({foo: "bar"}));
  });

  it("Can read posts marked public", async() => {
    const db = getFirestore(null);
    const testQuery = db.collection("posts").where("visibility", "==", "public");
    await firebase.assertSucceeds(testQuery.get());
  });

  it("Can query all personal posts", async() => {
    const db = getFirestore(myAuth);
    const testQuery = db.collection("posts").where("authorId", "==", myId);
    await firebase.assertSucceeds(testQuery.get());
  });

  it("Can't query all posts", async() => {
    const db = getFirestore(myAuth);
    const testQuery = db.collection("posts");
    await firebase.assertFails(testQuery.get());
  });

  it("Can read a single public post", async() => {
    const admin = getAdminFirestore();
    const postId = "public_post";
    const setupDoc = admin.collection("posts").doc(postId);
    await setupDoc.set({authorId: theirId, visibility: "public"});

    const db = getFirestore(null);
    const testRead = db.collection("posts").doc(postId);
    await firebase.assertSucceeds(testRead.get());
  });

  it("Cannot read a private post belonging to another user", async() => {
    const admin = getAdminFirestore();
    const postId = "private_post";
    const setupDoc = admin.collection("posts").doc(postId);
    await setupDoc.set({authorId: theirId, visibility: "private"});

    const db = getFirestore(myAuth);
    const testRead = db.collection("posts").doc(postId);
    await firebase.assertFails(testRead.get());
  });

  it("Can read a private post belonging to that same user", async() => {
    const admin = getAdminFirestore();
    const postId = "private_post";
    const setupDoc = admin.collection("posts").doc(postId);
    await setupDoc.set({authorId: myId, visibility: "private"});

    const db = getFirestore(myAuth);
    const testRead = db.collection("posts").doc(postId);
    await firebase.assertSucceeds(testRead.get());
  });

  it("Allows a user to edit their own post", async() => {
    const admin = getAdminFirestore();
    const postId = "post_123";
    const setupDoc = admin.collection("posts").doc(postId);
    await setupDoc.set({content: "before", authorId: myId});

    const db = getFirestore(myAuth);
    const testDoc = db.collection("posts").doc(postId);
    await firebase.assertSucceeds(testDoc.update({content: "after"}));
  });

  it("Does not allow a user to edit someone else's post", async() => {
    const admin = getAdminFirestore();
    const postId = "post_123";
    const setupDoc = admin.collection("posts").doc(postId);
    await setupDoc.set({content: "before", authorId: theirId});

    const db = getFirestore(myAuth);
    const testDoc = db.collection("posts").doc(postId);
    await firebase.assertFails(testDoc.update({content: "after"}));
  });

  it("Allows a moderator to edit someone else's post", async() => {
    const admin = getAdminFirestore();
    const postId = "post_123";
    const setupDoc = admin.collection("posts").doc(postId);
    await setupDoc.set({content: "before", authorId: theirId});

    const db = getFirestore(modAuth);
    const testDoc = db.collection("posts").doc(postId);
    await firebase.assertSucceeds(testDoc.update({content: "after mod edit"}));
  });

  it("Allows a user to edit their own room post", async() => {
    const postPath = "/rooms/room_abc/posts/post_123";
    const admin = getAdminFirestore();
    const setupDoc = admin.doc(postPath);
    await setupDoc.set({content: "before", authorId: myId});

    const db = getFirestore(myAuth);
    const testDoc = db.doc(postPath);
    await firebase.assertSucceeds(testDoc.update({content: "after"}));
  });

  it("Does not allow a user to edit someone else's room post", async() => {
    const postPath = "/rooms/room_abc/posts/post_123";
    const admin = getAdminFirestore();
    const setupDoc = admin.doc(postPath);
    await setupDoc.set({content: "before", authorId: theirId});

    const db = getFirestore(myAuth);
    const testDoc = db.doc(postPath);
    await firebase.assertFails(testDoc.update({content: "after"}));
  });

  it("Allows a room mod to edit someone else's room post", async() => {
    const roomPath = "rooms/room_abc";
    const postPath = `${roomPath}/posts/post_123`;
    const admin = getAdminFirestore();
    await admin.doc(roomPath).set({topic: "Unit Testers", roomMods: [myId, "dummyUser"]});
    await admin.doc(postPath).set({content: "before", authorId: theirId});

    const db = getFirestore(myAuth);
    const testDoc = db.doc(postPath);
    await firebase.assertSucceeds(testDoc.update({content: "after"}));
  });

  it("Allows a user to create a post when they list themselves as the author", async() => {
    const postPath = "/posts/post_123";
    const db = getFirestore(myAuth);
    const testDoc = db.doc(postPath);
    await firebase.assertSucceeds(testDoc.set({authorId: myId, visibility: "private", content: "lorem ipsum", headline: "Firebase Rules"}));
  });

  it("Does not allow a user to create a post when they list someone else as the author", async() => {
    const postPath = "/posts/post_123";
    const db = getFirestore(myAuth);
    const testDoc = db.doc(postPath);
    await firebase.assertFails(testDoc.set({authorId: theirId, visibility: "private", content: "lorem ipsum", headline: "Firebase Rules"}));
  });

  it("Allows a user to create a post with all required fields", async() => {
    const postPath = "/posts/post_123";
    const db = getFirestore(myAuth);
    const testDoc = db.doc(postPath);
    await firebase.assertSucceeds(testDoc.set({authorId: myId, visibility: "private", content: "lorem ipsum", headline: "Firebase Rules"}));
  });

  it("Does not allow a user to create a post without all required fields", async() => {
    const postPath = "/posts/post_123";
    const db = getFirestore(myAuth);
    const testDoc = db.doc(postPath);
    await firebase.assertFails(testDoc.set({authorId: myId, content: "lorem ipsum", headline: "Firebase Rules"}));
  });

  it("Allows a user to edit a post with allowed fields", async() => {
    const postPath = "/posts/post_123";
    const admin = getAdminFirestore();
    await admin.doc(postPath).set({content: "before", authorId: theirId, headline: "before_headline", visibility: "public"});

    const db = getFirestore(myAuth);
    const testDoc = db.doc(postPath);
    await firebase.assertSucceeds(testDoc.update({visibility: "public", content: "new lorem ipsum"}));
  });

it("Testing Post Create with Debug", async() => {
    const postPath = "/posts/post_123";
    const db = getFirestore(myAuth);
    const testDoc = db.doc(postPath);
    await firebase.assertSucceeds(testDoc.set({authorId: myId, visibility: "private", content: "lorem ipsum", headline: "Firebase Rules"}));
  });

});

after(async() => {
  await firebase.clearFirestoreData({projectId:MY_PROJECT_ID});
});
`

Any feedback is much appreciated.

**Comment by wpghijsen** [comment]
The above code got rendered strangely.. Hope it is still readable for you.

**Comment by wpghijsen** [comment]
Also as to:
'You have provided firebase-debug.log but the debug statements would show up in firestore-debug.log'
The firestore-debug.log is completely empty, which is why it was not included.

**Comment by samtstern** [comment]
@wpghijsen sorry but it's going to be too hard to try and find a bug in all of that. To narrow it down please try reducing your example to **one** rule and **one** test case so that we can prove it's not working.

Try this:

**firestore.rules**

```
rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /posts/{postId} {
      allow create: if debug(true);
    }
}
```

**test.js**

```js
const assert = require('assert');
const firebase = require('@firebase/testing');

const MY_PROJECT_ID = "my-project-3we3e";

function getFirestore(auth) {
  return firebase.initializeTestApp({projectId: MY_PROJECT_ID, auth: auth}).firestore();
}

function getAdminFirestore() {
  return firebase.initializeAdminApp({projectId: MY_PROJECT_ID}).firestore();
}

beforeEach(async() => {
  await firebase.clearFirestoreData({projectId:MY_PROJECT_ID});
});

describe("Treetop App Functions", () => {

  it("Enforces Security Rule 1", () => {
    assert.equal(2+2,4);
  });

 it("Testing Post Create with Debug", async() => {
    const postPath = "/posts/post_123";
    const db = getFirestore(null);
    const testDoc = db.doc(postPath);
    await firebase.assertSucceeds(testDoc.set({ hello: "world"}));
  });

});

after(async() => {
  await firebase.clearFirestoreData({projectId:MY_PROJECT_ID});
});
```

Also I think you want your `beforeEach()` and `after()` blocks inside your `describe()` block but for a single test that won't actually matter.

Please run the tests above with `firebase emulators:exec` to make sure it's connecting to the emulator (or use the `discoverEmulators()` utility). If that doesn't work, we'll know we have some kind of issue.

**Comment by wpghijsen** [comment]
Hi Sam,
I implemented your above code and the tests pass. Unfortunately the firestore-debug.log is empty after these tests as well.

Also this may be unrelated but worth mentioning: I am seeing the firestore-debug.log in both the treetop directory and the treetop/test directory. This is not new behavior, and the log is and has been empty in both places.

I have attached the firebase-debug.log for your consideration.
[firebase-debug.log](https://github.com/firebase/firebase-tools/files/6594845/firebase-debug.log)

**Comment by samtstern** [comment]
@wpghijsen I have tried this from a clean slate and I was not able to reproduce this.  Here's my full setup:

**index.js**
<details>
```js
const assert = require('assert');
const firebase = require('@firebase/testing');

const MY_PROJECT_ID = "demo-project-1234";

function getFirestore(auth) {
  return firebase.initializeTestApp({projectId: MY_PROJECT_ID, auth: auth}).firestore();
}

function getAdminFirestore() {
  return firebase.initializeAdminApp({projectId: MY_PROJECT_ID}).firestore();
}

beforeEach(async() => {
  await firebase.clearFirestoreData({projectId:MY_PROJECT_ID});
});

describe("Treetop App Functions", () => {

  it("Enforces Security Rule 1", () => {
    assert.equal(2+2,4);
  });

 it("Testing Post Create with Debug", async() => {
    const postPath = "/posts/post_123";
    const db = getFirestore(null);
    const testDoc = db.doc(postPath);
    await firebase.assertSucceeds(testDoc.set({ hello: "world"}));
  });

});

after(async() => {
  await firebase.clearFirestoreData({projectId:MY_PROJECT_ID});
});

```
</details>

**package.json**
<details>
```json
{
  "name": "tests",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "mocha index.js"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@firebase/rules-unit-testing": "^1.3.7",
    "@firebase/testing": "^0.20.11",
    "mocha": "^9.0.0"
  }
}
```
</details>

Then I run this command:
```
$ firebase --project=demo-project-1234 emulators:exec "npm run test"
```

I get the following output at the command line:

```
$ firebase --project=demo-project-1234 emulators:exec "npm run test"
i  emulators: Starting emulators: firestore
i  emulators: Detected demo project ID "demo-project-1234", emulated services will use a demo configuration and attempts to access non-emulated services for this project will fail.
i  firestore: Firestore Emulator logging to firestore-debug.log
i  Running script: npm run test

> tests@1.0.0 test /private/var/folders/xl/6lkrzp7j07581mw8_4dlt3b000643s/T/tmp.yydBaYhf/tests
> mocha index.js



  Treetop App Functions
    ✔ Enforces Security Rule 1
    ✔ Testing Post Create with Debug (508ms)


  2 passing (1s)

✔  Script exited successfully (code 0)
i  emulators: Shutting down emulators.
i  firestore: Stopping Firestore Emulator
i  hub: Stopping emulator hub
```

In **firestore-debug.log** I see this:

```
Jun 11, 2021 12:44:45 PM com.google.cloud.datastore.emulator.firestore.websocket.WebSocketServer start
INFO: Started WebSocket server on ws://localhost:58445
API endpoint: http://localhost:8080
If you are using a library that supports the FIRESTORE_EMULATOR_HOST environment variable, run:

   export FIRESTORE_EMULATOR_HOST=localhost:8080

Dev App Server is now running.

Jun 11, 2021 12:44:46 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected non-HTTP/2 connection.
Jun 11, 2021 12:44:46 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected HTTP/2 connection.
Jun 11, 2021 12:44:47 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected non-HTTP/2 connection.
Jun 11, 2021 12:44:47 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected HTTP/2 connection.
bool_value: true

Jun 11, 2021 12:44:47 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected non-HTTP/2 connection.
*** shutting down gRPC server since JVM is shutting down
*** server shut down
```

The evidence of the `debug()` command working is here:
```
bool_value: true
```

That's what `debug(true)` produces.

So at this point I am convinced that everything is working properly, there must be some sort of configuration error on your side. Please let me know if you can produce something as simple as my test case which will allow me to reproduce the bug.

**Comment by wpghijsen** [comment]
Hi Sam,

I started a completely new firestore project to test this out, treetop-rules
When I run: 
firebase --project=treetop-rules emulators:exec "npm run test"

I get the following:
C:\Users\wpghi\treetop-rules>firebase --project=treetop-rules emulators:exec "npm run test"
i  emulators: Starting emulators: firestore
i  firestore: Firestore Emulator logging to firestore-debug.log
i  Running script: npm run test
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\Users\wpghi\treetop-rules\package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\wpghi\treetop-rules\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\wpghi\AppData\Roaming\npm-cache\_logs\2021-06-15T19_30_52_439Z-debug.log
!  Script exited unsuccessfully (code 4294963238)
i  emulators: Shutting down emulators.
i  firestore: Stopping Firestore Emulator
!  Firestore Emulator has exited upon receiving signal: SIGINT
i  hub: Stopping emulator hub

Error: Script "npm run test" exited with code 4294963238


This seems to be error that is I am running into before the debug log is written to.

If the error is resulting from some configuration please tell me what to configure to avoid this, as the firestore-debug log is not being written to still. If you want me to, for example, completely uninstall my npm or firebase-cli for a different versions, I would be amenable to that. Let me know the exact steps you want me taking for the setup so I can replicate your best practices on my machine.

I have attached the firebase-debug log for your consideration
[firebase-debug.log](https://github.com/firebase/firebase-tools/files/6658232/firebase-debug.log)

**Comment by samtstern** [comment]
The error is here:
```
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\wpghi\treetop-rules\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
```

It seems like you're in the wrong directory. You can't run `"npm run test"` unless you're in a directory with a `package.json` that defines the `test` script.

**Comment by wpghijsen** [comment]
I see. I just ran it successfully in the test directory with no errors:

C:\Users\wpghi\treetop-rules\test>firebase --project=treetop-rules emulators:exec "npm run test"
i  emulators: Starting emulators: firestore
i  firestore: Firestore Emulator logging to firestore-debug.log
i  Running script: npm run test

> test@1.0.0 test C:\Users\wpghi\treetop-rules\test
> mocha --exit



  Treetop App Functions
    √ Enforces Security Rule 1
    √ Testing Post Create with Debug (483ms)


  2 passing (1s)

+  Script exited successfully (code 0)
i  emulators: Shutting down emulators.
i  firestore: Stopping Firestore Emulator
!  Firestore Emulator has exited upon receiving signal: SIGINT
i  hub: Stopping emulator hub

The firestore-debug.log is still empty. Can you please advise on installing and running the emulator and which versions I should do for Windows 10? Attached is the firebase.debug.log
[firebase-debug.log](https://github.com/firebase/firebase-tools/files/6665059/firebase-debug.log)
