### ISSUE TITLE
Callable functions broken by #3364

### ISSUE THREAD

**Issue by samtstern** [firebase/firebase-tools#3418]
Hi,
although nice addition, this broke every `firebase.functions().httpsCallable('lala')` for me 🙃

Emulator now expects `firebase.functions().httpsCallable('region-lala')`, which differs from the cloud environment. I have most functions in `europe-west1` and rest in `us-central`. No function is in multiple regions.

_Originally posted by @jirizavadil in https://github.com/firebase/firebase-tools/issues/3364#issuecomment-849530664_

**Comment by samtstern** [comment]
@jirizavadil actually I am not able to reproduce this. Here are my functions:

```js
const functions = require("firebase-functions");

exports.helloWorld = functions.https.onRequest((request, response) => {
  response.send("helloWorld");
});

exports.helloCallable = functions.https.onCall((ctx) => {
  console.log("helloCallable");
  return {};
});
```

I was able to make a simple request correctly (using [httpie](https://httpie.io/)):
```
$ http POST http://localhost:5001/fir-dumpster/us-central1/helloCallable Content-Type:application/json data=""
HTTP/1.1 200 OK
connection: keep-alive
content-length: 13
content-type: application/json; charset=utf-8
date: Thu, 27 May 2021 10:57:17 GMT
etag: W/"d-MoNXnKuD0ORPMCkqEFx5iouAPNo"
keep-alive: timeout=5
vary: Origin
x-powered-by: Express

{
    "result": {}
}
```

Can you explain what is not working?

**Comment by jirizavadil** [comment]
Hi @samtstern, as always incredibly fast response!

Using your index.html, all you need to break it is specifying function region other than `us-central1`.

index.js:
```
const functions = require("firebase-functions");

exports.helloWorld = functions.region("europe-west1").https.onRequest((request, response) => {
  response.send("helloWorld");
});

exports.helloCallable = functions.region("europe-west1").https.onCall((ctx) => {
  console.log("helloCallable");
  return {};
});
```

terminal:
```
jirizavadil@Kianna functions % firebase --version
9.12.0
jirizavadil@Kianna functions % firebase emulators:start
...
✔  functions[europe-west1-helloWorld]: http function initialized (http://localhost:5001/project_id/europe-west1/helloWorld).
✔  functions[europe-west1-helloCallable]: http function initialized (http://localhost:5001/project_id/europe-west1/helloCallable).
...
```

console:
```
13:38:32.022 Automatically connecting Firebase SDKs to running emulators:
13:38:32.038 functions: http://localhost:5001
13:38:32.127 Access to fetch at 'http://localhost:5001/project_id/us-central1/helloCallable' from origin 'http://localhost:5000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
13:38:32.128 POST http://localhost:5001/project_id/us-central1/helloCallable net::ERR_FAILED
```

I didn't actually try before, but not even `functions.httpsCallable('europe-west1-helloCallable')` makes a difference.

**Comment by samtstern** [comment]
@jirizavadil ah ok, sorry this is a result of some bad documentation.

If you want to use `httpsCallable` with another region you have to do this:

```js
const app = firebase.app();
const functions = app.functions('europe-west1');
functions.useEmulator('localhost', 5001);

const callable = functions.httpsCallable('helloCallable');
```

Note that you will have to call `useEmulator` manually here since you're using a new `app.functions()` instance. It's one instance per region.

Let me know if this works for you!

**Comment by jirizavadil** [comment]
@samtstern Damn, i only had this in my cloud environment, not in the emulated one. Strangely, it worked up until now. Sorry and thank you! You may close this.
