### ISSUE TITLE
Keep auth uid between emulator sessions

### ISSUE THREAD

**Issue by neuberoliveira** [firebase/firebase-tools#3421]
Dont think this is a bug but....
Iam using auth emulator, but every time i start emulator when i login (sms authentication) i got an different uid, even if i use the same phone number.

To be more clear: 

1. start emulator
2. do the sms login flow, at the end i got an uid like this My0Cttat8RcDiWqdz0Ii
3. stop emulator
4. start emulator (again)
5. do the sms login flow, with the same data as before, and then i got a different uid, 5wtMZJmoSzuyhLOHzxgh

Its a bit annoying have to fix ids on database to "continue" development of my application.

Is there a way the emulator can generate same uid even between emulator sesssions??

**Comment by samtstern** [comment]
@neuberoliveira by default the emulators clear themselves on each start. If you want to persist some data between sessions, you can use import/export:
https://firebase.google.com/docs/emulator-suite/install_and_configure#export_and_import_emulator_data

**Comment by neuberoliveira** [comment]
@samtstern sorry, forget to mention that, iam already using this feature.

let say i have a products collection, when i register a product i put a field like `owner_id` with the curret id of logged user.

when i stop and then start emulator again, the data was there, but when i login (sms) i got a new id, even if use the same phone number, and because of that i need to edit the `owner_id` field of an product manually, or register e new one.

to be more clear i would like to got the same user id for same phone number every time i start emulator.

**Comment by samtstern** [comment]
@neuberoliveira hmmm I'm not sure if we can/should support that but I am curious to hear what @yuchenshi thinks.

**Comment by yuchenshi** [comment]
Hmm the import should associate the phone number with an existing user (and uid) unless there's a bug in the Auth Emulator. Would you mind uploading a dump of your export directory (zipped) for further investigation? (No real phone numbers or passwords please)

**Comment by neuberoliveira** [comment]
Thanks for the help but i realize it was my bad somehow, i take a look in `auth_export/accounts.json` and realize it was not saving my "new user" there, this explain why i got a new id every time.

i put a `chmod 777` in emulator export dir and now `auth_export/accounts.json` is updated with my phone number and i can got the same id every time, at least for now.....

thanks again
