### ISSUE TITLE
function is not defined error after upgrading v9.6.1 to v9.12.0

### ISSUE THREAD

**Issue by syJSdev** [firebase/firebase-tools#3426]
### [REQUIRED] Environment info

**firebase-tools:** 9.12.0

**Platform:** linux

### [REQUIRED] Test case

`firebase functions:shell`

### [REQUIRED] Steps to reproduce
1. initialize the project with v9.6.1.
2. upgrade the firebase related packages to latest.
3. reinstall the packges (remove and install)
4. `firebase emulators:start`
5. `firebase functions:shell`

### [REQUIRED] Expected behavior
All http functions will should be callable in the shell.

### [REQUIRED] Actual behavior
But got this error
> Uncaught ReferenceError: functionName is not defined

**Comment by dimavedenyapin** [comment]
This also happens with me in OS X

**Comment by jaxnz** [comment]
Same issue here, rolling back to `firebase-tools 9.11.0` - works OK.

**Comment by rconjoe** [comment]
Ubuntu and Mac users on our team are experiencing this as well. Same 9.11.0 rollback works for now.

**Comment by joehan** [comment]
Hey all, sorry for this regression. I tested out @syJSdev 's fix, and it looks good to me - thanks a ton! We'll be releasing a patch version shortly to get this fixed
