### ISSUE TITLE
`curl -sL firebase.tools | bash` reports "tr: Illegal byte sequence" when executed on macOS

### ISSUE THREAD

**Issue by FanchenBao** [firebase/firebase-tools#3430]
### [REQUIRED] Environment info

**firebase-tools:** N/A. The problem is not with `firebase-tools` but with the installation script of `firebase-tools`.

**Platform:** macOS Catalina 10.15.7

### [REQUIRED] Test case

N/A. The problem is not with `firebase-tools` but with the installation script of `firebase-tools`.

### [REQUIRED] Steps to reproduce

On macOS Catalina terminal, execute the command:

```bash
curl -sL firebase.tools | bash
```
Observe that the first output is an error message "tr: Illegal byte sequence".

### [REQUIRED] Expected behavior

The installation script executes without problem.

### [REQUIRED] Actual behavior

An error message "tr: Illegal byte sequence" is shown at the very beginning.

### Root Cause

The cause of the error message is Line 99:

```bash
CID=$(cat /dev/urandom | LC_CTYPE=c tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
```
The error message can be avoided by specifying `LC_ALL=c` instead of `LC_CTYPE=c` ([Reference](https://gist.github.com/earthgecko/3089509#gistcomment-3371707))

Using `LC_ALL=c` is also compatible with Linux.

### Proposed Solution

Change Line 99 to this:

```bash
CID=$(cat /dev/urandom | LC_ALL=c tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
```

**Comment by samtstern** [comment]
@FanchenBao thank you for the very precise report!

**Comment by abeisgoat** [comment]
Thank you again, this change also looks good and has been applied!
