### ISSUE TITLE
`curl -sL firebase.tools | bash` does not output correct messages when `firebase` has already been installed

### ISSUE THREAD

**Issue by FanchenBao** [firebase/firebase-tools#3431]
### [REQUIRED] Environment info

**firebase-tools:** 9.11.0

**Platform:** macOS Catalina 10.15.7

### [REQUIRED] Test case

N/A. The problem is not with `firebase-tools` but with the installation script of `firebase-tools`.

### [REQUIRED] Steps to reproduce

1. Install `firebase` using `npm install -g firebase-tools`.
2. Run command `curl -sL firebase.tools | bash`.
3. Observe the bizarre output message.

### [REQUIRED] Expected behavior

The output message shall read like this:

```
-- Checking for existing firebase-tools on PATH...
Your machine already has firebase-tools@9.11.0 installed. Nothing to do.
-- All done!
```

### [REQUIRED] Actual behavior

This is the actual output message:

```
-- Checking for existing firebase-tools on PATH...
error: unknown option '--tool:setup-check'
Your machine has firebase-tools@9.11.0 installed.
If you would like to upgrade your install run: curl -sL firebase.tools | upgrade=true bash
```

### Root Cause

The problem is in Line 183:

```bash
if [[ "$(firebase --tool:setup-check)" == error* ]]; then
```

Apparently, stderr `error: unknown option '--tool:setup-check'` has not been captured in the if statement, which results in the error message printing to the console, `"$(firebase --tool:setup-check)"` evaluates to an empty string, and the if statement evaluates to false.

Furthermore, Line 129 has the same structure as Line 183. Hence, Line 129 is problematic as well.

### Proposed Solution

The problem can be resolved by piping stderr to stdout.

Line 183 shall be changed to:

```bash
if [[ "$(firebase --tool:setup-check 2>&1)" == error* ]]; then
```

Line 129 shall be changed to:

```bash
if [[ ! "$(firebase --tool:setup-check 2>&1)" == *bins* ]];
```

**Comment by abeisgoat** [comment]
A final great fix, thank you so much for all these detailed and thorough reports. They've all been merged.
