### ISSUE TITLE
This site can’t be reached

### ISSUE THREAD

**Issue by kk2491** [firebase/firebase-tools#3433]
Hi,

I am trying to configure the firebase emulator using docker in my local system. Getting the below error. 

![image](https://user-images.githubusercontent.com/38481564/120253057-0046d800-c2a4-11eb-87df-6f35451b4148.png)

Please find the attached debug logs. 

[database-debug.log](https://github.com/firebase/firebase-tools/files/6572728/database-debug.log)
[firebase-debug.log](https://github.com/firebase/firebase-tools/files/6572736/firebase-debug.log)
[firestore-debug.log](https://github.com/firebase/firebase-tools/files/6572738/firestore-debug.log)
[pubsub-debug.log](https://github.com/firebase/firebase-tools/files/6572739/pubsub-debug.log)

Using the same dockerfile I am able to configure successfully in a different system. However when I try in my main system it does not seem working fine.

And also in the system where it was successfully configured the emulator was configured in http://172.19.0.10, however in my main system it is taking localhost.

It would be great if someone could help me with the issue.

Thank you

**Comment by samtstern** [comment]
@kk2491 please follow the issue template when filing an issue. Right now it's not clear that there is any bug in the Firebase CLI or Emulators here, it just seems like you are having trouble configuring Docker.

If you need general help with your Docker setup, the best place to ask is StackOverflow. If you have evidence of a bug in the CLI, please file a new issue according to the template.
