### ISSUE TITLE
Typo in doc breaking the storage emulator functionality.

### ISSUE THREAD

**Issue by vajahath** [firebase/firebase-tools#3447]
This is a documentation issue regarding Storage emulator.
The doc is asking us to set the environment variable like:
```sh
export FIRESTORE_STORAGE_EMULATOR_HOST="localhost:9199"
#      ^^^^^^^^^ => But this should be FIREBASE instead of FIRESTORE
```
ref: https://firebase.google.com/docs/emulator-suite/connect_storage?#admin_sdks

I can see the correct keyword (`FIREBASE_STORAGE_EMULATOR_HOST`) is being used in the code instead of the incorrect one:
https://github.com/firebase/firebase-tools/blob/0fcaf5d2b10cacf9fa20339dcdc0c7e8c87fbc7f/src/emulator/constants.ts#L63

**Comment by joehan** [comment]
Thanks  @vajahath for pointing this out! @yuchenshi, can you fix this typo in the docs?

**Comment by yuchenshi** [comment]
Working on it :)

**Comment by abeisgoat** [comment]
@yuchenshi we make any progress here?

**Comment by abeisgoat** [comment]
JK, I see it's fixed.
