### ISSUE TITLE
Environment Config setting doesn't work for Strings or Integers

### ISSUE THREAD

**Issue by datureezy** [firebase/firebase-tools#345]
Running Firebase-Tools 3.9.0 on a Mac, unable to set any values, be they strings ("" & '') or integers.

firebase functions:config:set github.key=12345678
firebase functions:config:set github.key='12345678'
firebase functions:config:set github.key="12345678"

Able to unset values, but trying to set values returns this error in every case:
Error: HTTP Error: 400, Invalid value at 'variable.text' (TYPE_STRING), 45873492

Unfortunately, due to the inability to set env config values, deployments aren't possible... [edit: I had to install fb-tools@3.6.1 to get env variables set]

Please advise.

**Comment by laurenzlong** [comment]
Hey @datureezy this is a bug, thanks for reporting. 
Doing this right now will work: firebase functions:config:set github='{"key":"12345678"}'

**Comment by laurenzlong** [comment]
Fixed in https://github.com/firebase/firebase-tools/pull/348
