### ISSUE TITLE
Can not disable storage emulator

### ISSUE THREAD

**Issue by iSuslov** [firebase/firebase-tools#3453]
### [REQUIRED] Environment info

**firebase-tools:** 9.12.1

**Platform:** macOS 10.14.6 (18G87)

### [REQUIRED] Test case

After you install storage emulator, there is no way to disable it. Every time you start emulators now, it will start again and again.

### [REQUIRED] Steps to reproduce

- Install storage emulator with `firebase setup:emulators:storage` 
- Storage emulator `cloud-storage-rules-runtime-v1.0.0.jar` is installed.
- In `firebase.json` there is a new record `"emulators": {..."storage": {"port": 9199} }`
- If not exists, you forced to create `storage.rules` in the project folder and create top level entry 
 ` "storage": {
    "rules": "storage.rules"
  }` in `firebase.json`
- Start emulators 
- Storage emulator started. Output from the terminal `Storage │ localhost:9199 │ http://localhost:4000/storage`
- Stop emulators
- Remove `"storage": {"port": 9199} ` from `firebase.json`
- Start emulators again
- Storage emulator starts on the port `9199`
More debugging steps:
- Remove `cloud-storage-rules-runtime-v1.0.0.jar` from `/Users/User/.cache/firebase/emulators`
- Emulator still starts
- Adding `"enabled": false` to the emulator storage config object in  `firebase.json` also does nothing

### [REQUIRED] Expected behavior

Emulator should start only if `firebase.json` has an existing emulator config for it.

### [REQUIRED] Actual behavior

Emulator starts everytime. Even without emulator config in the `firebase.json` it starts the emulator because of top level entry here. In this example:
` "storage": {
    "rules": "storage.rules"
  }` 
https://github.com/firebase/firebase-tools/blob/3e4f7e9b3c6c7ff9c92a74f550df73d94cc97fc8/src/emulator/controller.ts#L325

Here instead of **or** it should be logical **and**

**Comment by samtstern** [comment]
@iSuslov this sounds like the intended behavior. When you run `emulators:start` with no arguments we start the storage emulator if either of the following is true:

  * You have a `storage` section in your `firebase.json`
  * You have a `emulators.storage` section in your `firebase.json`

If you want to start only certain emulators you can use the `--only` flag:
```
firebase emulators:start --only database
```

**Comment by bradleymackey** [comment]
I'd argue that having `emulators.storage.enabled: false` should *always* disable the emulator, regardless of the state of the rest of the `firebase.json`. I'm running into the same issue where I have a `storage` config in my `firebase.json` but don't want the emulator to be run. I was hoping that setting `"enabled": false` would be sufficient for this.

**Comment by samtstern** [comment]
@bradleymackey we don't read `enabled` on any of the emulators with the exception of `ui`, although I agree that would be nice as a feature!

**Comment by zgsrc** [comment]
Agreed.  Reading enabled is what you want.  Removing the storage section will affect the deployment of rules.  

Emulator doesn't work so much.  Need to disable or roll back to 9.10.
