### ISSUE TITLE
Can not work failurePolicy in function emulator.

### ISSUE THREAD

**Issue by ytetsuro** [firebase/firebase-tools#3468]
The following programs will not work in the current emulator environment.
To be precise, retry by `failurePolicy` does not work in the emulator.

```javascript
const dummy = functions
  .runWith({
    failurePolicy: true,
  }).firestore.document(`hello/{world}`)
  .onCreate(async (snap, context) => {
   throw new Error('infinity loop.');
})
```

It would be great to be able to check with the emulator to avoid infinite loops.

Please submit feature requests through our [support page](https://firebase.google.com/support/contact/bugs-features/).

**Comment by samtstern** [comment]
@ytetsuro thanks for the feature request!

**Comment by yuchenshi** [comment]
Duplicate of #3738

**Comment by ChrisGibb** [comment]
+1
