### ISSUE TITLE
Firebase Firestore Emulator Not Persisting/Saving Data

### ISSUE THREAD

**Issue by williamhaley** [firebase/firebase-tools#3475]
### Environment info

**firebase-tools:**

```
% firebase --version
9.12.1
```
```
"firebase-tools": "^9.12.1"
```

**Platform:**

macOS 11.4

### Test case

https://github.com/williamhaley/firestore-emulator-slow

### Steps to reproduce

1. Clone the test case repo and `npm i` to get dependencies
2. Start the emulators `./node_modules/.bin/firebase emulators:start --import=emulator-data --export-on-exit --debug`
3. Try running either simple demo application in my test case repo to insert a document
  * `FIRESTORE_EMULATOR_HOST=localhost:8080 go run demo.go`
  * `FIRESTORE_EMULATOR_HOST=localhost:8080 node demo.js`
4. Note that no data is persisted in the `emulator-dir` and no data shows as committed in the firestore admin UI

```
i  emulators: Starting emulators: firestore
i  firestore: Firestore Emulator logging to firestore-debug.log
i  ui: Emulator UI logging to ui-debug.log

┌─────────────────────────────────────────────────────────────┐
│ ✔  All emulators ready! It is now safe to connect your app. │
│ i  View Emulator UI at http://localhost:4000                │
└─────────────────────────────────────────────────────────────┘

┌───────────┬────────────────┬─────────────────────────────────┐
│ Emulator  │ Host:Port      │ View in Emulator UI             │
├───────────┼────────────────┼─────────────────────────────────┤
│ Firestore │ localhost:8080 │ http://localhost:4000/firestore │
└───────────┴────────────────┴─────────────────────────────────┘
  Emulator Hub running at localhost:4400
  Other reserved ports: 4500

Issues? Report them at https://github.com/firebase/firebase-tools/issues and attach the *-debug.log files.
```

[firebase-debug.log](https://github.com/firebase/firebase-tools/files/6620842/firebase-debug.log)
[firestore-debug.log](https://github.com/firebase/firebase-tools/files/6620843/firestore-debug.log)

### Expected behavior

Data directed to the emulator should have been persisted or an error should have been returned in a meaningful way.

### Actual behavior

Data is not persisted.

<img width="1399" alt="Screen Shot 2021-06-08 at 10 09 35 PM" src="https://user-images.githubusercontent.com/1851748/121286948-3a1c6d80-c8a6-11eb-848c-f6b3de8a0175.png">

<img width="943" alt="Screen Shot 2021-06-08 at 10 15 07 PM" src="https://user-images.githubusercontent.com/1851748/121287432-26253b80-c8a7-11eb-87f5-b6157c49090f.png">

```
% find emulator-data -type f -exec echo "{}" \; -exec cat {} \;
emulator-data/firebase-export-metadata.json
{
  "version": "9.12.1",
  "firestore": {
    "version": "1.12.0",
    "path": "firestore_export",
    "metadata_file": "firestore_export/firestore_export.overall_export_metadata"
  }
}emulator-data/firestore_export/firestore_export.overall_export_metadata
mDN3+(C%
```

**Comment by samtstern** [comment]
Note: when I first tried your reproduction I see these logs:

```
⚠  emulators: The Emulator UI requires a project ID to start. Configure your default project with 'firebase use' or pass the --project flag. {"metadata":{"emulator":{"name":"hub"},"message":"The Emulator UI requires a project ID to start. Configure your default project with 'firebase use' or pass the --project flag."}}

┌─────────────────────────────────────────────────────────────┐
│ ✔  All emulators ready! It is now safe to connect your app. │
└─────────────────────────────────────────────────────────────┘

┌───────────┬────────────────┐
│ Emulator  │ Host:Port      │
├───────────┼────────────────┤
│ Firestore │ localhost:8080 │
└───────────┴────────────────┘
  Emulator Hub not running.
  Other reserved ports: None
```

So I added a `--project=demo-project-1233` flag which made it run fine. Will work on reproducing the issue now.

**Comment by samtstern** [comment]
Hmmm ok I see the same empty Emulator UI and exports. However I expanded your script to look like this:

```js
const admin = require('firebase-admin');

admin.initializeApp();

const db = admin.firestore();

(async () => {
  const docRef = db.collection('users').doc('alovelace');

  const result = await docRef.set({
    first: 'Ada',
    last: 'Lovelace',
    born: 1815
  });

  console.log('write done', result);

  const snap = await docRef.get();
  console.log('read done', snap.data());
})();
```

And when I run it the data *is* there:
```
$ FIRESTORE_EMULATOR_HOST=localhost:8080 node demo.js
write done WriteResult {
  _writeTime: Timestamp { _seconds: 1623236547, _nanoseconds: 205828000 }
}
read done { last: 'Lovelace', born: 1815, first: 'Ada' }
```

However in the browser the `listCollectionIds` call is returning `{}` which is probably the root cause of the issue affecting both the Emulator UI *and* the export. I'll have to see what changed recently.

**Comment by samtstern** [comment]
Another note: I was also able to reproduce this with `firebase-tools` version `9.11.0` which means it's probably not related to https://github.com/firebase/firebase-tools/pull/3402

**Comment by samtstern** [comment]
Another note: if I manually add data to the Emulator via the UI it is persisted across shutdown and re-import:
<img width="1326" alt="Screen Shot 2021-06-09 at 12 10 17 PM" src="https://user-images.githubusercontent.com/8466666/121344448-c56f2080-c8f1-11eb-8983-3df7863d7299.png">

Also the Admin SDK script *should* be overwriting that data but it does not, even though it shows success:
$ FIRESTORE_EMULATOR_HOST=localhost:8080 node demo.js
write done WriteResult {
  _writeTime: Timestamp { _seconds: 1623236987, _nanoseconds: 914550000 }
}
read done { last: 'Lovelace', born: 1815, first: 'Ada' }

**Comment by williamhaley** [comment]
Thank you for all your feedback and confirming the issue(s) @samtstern.

I see the same behavior regarding adding `--project fake-project-id` to my emulators run command and running my golang app. I see data **is persisted as expected**.

I also can confirm that, with or without `--project fake-project-id`, the admin UI does seem to work properly in persisting and loading data.

My only variation from your notes is that expanding the `demo.js` script with your changes does not seem to change anything on my end. For whatever reason, **I don't see the node flavor of the demo code persisting any data.**

```diff
diff --git a/demo.js b/demo.js
index d5d509c..2bb52df 100644
--- a/demo.js
+++ b/demo.js
@@ -13,5 +13,8 @@ const db = admin.firestore();
     born: 1815
   });

-  console.log('done', result);
+  console.log('write done', result);
+
+  const snap = await docRef.get();
+  console.log('read done', snap.data());
 })();
```

The script looks like it ran fine, but the UI reflects nothing was inserted and nothing in `./emulator-data/` seems to reflect anything was persisted when I shut down the emulators.

```bash
% FIRESTORE_EMULATOR_HOST=localhost:8080 node demo.js
write done WriteResult {
  _writeTime: Timestamp { _seconds: 1623247512, _nanoseconds: 747000000 }
}
read done { last: 'Lovelace', born: 1815, first: 'Ada' }
```

Probably not quite related, but a little confusing while debugging; I also see that the UI is optimistic when a URL like `http://localhost:4000/firestore/test/OHNHb1GjJ24Wxf626Kj7` is used, which will happen (on my end at least) when a single document is inserted and the UI auto-redirects to that URL to show the details. 

If the datastore (`./emulator-data/` in my case) is deleted, the emulator restarted, and the browser is on that document detail URL, then it shows a UI like this even though there's no data. Again, probably unrelated and just a UX issue more than anything, but seemed maybe worth nothing.

<img width="1153" alt="Screen Shot 2021-06-09 at 9 08 24 AM" src="https://user-images.githubusercontent.com/1851748/121370322-42a29180-c902-11eb-8597-2c067b1f7126.png">

**Comment by williamhaley** [comment]
Ah, I see, I misread your earlier comment. I suppose I _am_ seeing the same behavior as you regarding the node script. The data is returned by `.get()`, but the admin UI isn't reflecting that ✔️

**Comment by samtstern** [comment]
🤦 this is a classic "project ID mismatch", which @yuchenshi pointed out to me.

If you specify the same project ID in both places you'll see it works:

Starting emulators:
```shell
./node_modules/.bin/firebase emulators:start --import=emulator-data --export-on-exit --debug --project=demo-project-1234
```

Running script:
```shell
GCLOUD_PROJECT=demo-project-1234 FIRESTORE_EMULATOR_HOST=localhost:8080 node demo.js
```

Or you could specify the project ID in `admin.initializeApp()` if you don't want to use `GCLOUD_PROJECT`. I actually have no idea what project ID the Admin SDK is using in the case where it's not specified, must be some fallback based on the local environment.

If this code had been running in any of the following environments, this would have been handled automatically:

  * Cloud Functions in production
  * Cloud Functions in the emulator
  * `firebase emulators:exec` script

There are some docs on this here (https://firebase.google.com/docs/emulator-suite/connect_firestore) and we have a separate project underway to throw an error in this case!

**Comment by williamhaley** [comment]
🎉 Yep, that's it. For my sake, specifying `GCLOUD_PROJECT=fake-project-id ...` on all my commands got things working.

I didn't think the project id actually had any impact/meaning for a local-only demo project like this so that wasn't clear to me. 

Thanks for clearing that up. I see now that even for a demo/local/dev/localhost project the fake (or whatever) project id _must_ consistently match on both the client and server for the simulators to work.
