### ISSUE TITLE
firebase deploy has changed the maximum length of a function name from 63 chars to 62 chars

### ISSUE THREAD

**Issue by dteirney** [firebase/firebase-tools#3493]
### [REQUIRED] Environment info

**firebase-tools:** 9.13.0

**Platform:** macOS

### [REQUIRED] Test case

https://github.com/dteirney/functions-samples/blob/master/quickstarts/pubsub-helloworld/functions/index.js

### [REQUIRED] Steps to reproduce

Try to deploy a function with a name with 63 characters that previously would deploy, but no longer does.

### [REQUIRED] Expected behavior

Deploy succeeds as with previous versions.

### [REQUIRED] Actual behavior

`Error: [object Object] function name(s) can only contain letters, numbers, hyphens, and not exceed 62 characters in length`

**Comment by dteirney** [comment]
Updated comment with function-samples forked and with a 63 char name added.

**Comment by dteirney** [comment]
Updated as we had a function name of 64 characters as well, which would previously deploy.

**Comment by samtstern** [comment]
Hmmm the `git blame` on that line looks like this limitation has been in place for at least 2 years. @joehan or @inlined did yiou change something recently>

**Comment by samtstern** [comment]
Based on the Cloud Functions console it looks like 63 is the correct limit, maybe this is a very old typo in our code:
<img width="585" alt="Screen Shot 2021-06-17 at 12 14 19 PM" src="https://user-images.githubusercontent.com/8466666/122386246-b284cd80-cf3b-11eb-980b-255cd2e51772.png">

**Comment by inlined** [comment]
The validate line has been in place for years, but the validation call was commented out until recently. We can up the limit if the backend will accept it.
