### ISSUE TITLE
Can't login to cli using a particular google account

### ISSUE THREAD

**Issue by amiani** [firebase/firebase-tools#3495]
### [REQUIRED] Environment info

**firebase-tools:** 9.13.0

**Platform:** MacOS

### [REQUIRED] Test case

N/A

### [REQUIRED] Steps to reproduce

npm install -g firebase-tools
firebase login OR firebase login --no-localhost

### [REQUIRED] Expected behavior

Choose google account through browser, authenticate cli tools.

### [REQUIRED] Actual behavior

When I try to authenticate with my google account:
<img src="https://user-images.githubusercontent.com/6980475/122212987-73d90f80-ce76-11eb-94c3-a9bec2982aca.png" width=286 height=304 />
This also occurs when using --no-localhost flag and authenticating using a different machine. I have used the firebase cli with this google account in the past.
I am able to authenticate with a different google account as normal.

**Comment by junaga** [comment]
Is this an Consumer Account? Because if it's a [Managed Google Account](https://cloud.google.com/architecture/identity/overview-google-authentication#managed_user_account) like provisioned by [Google Workspace](https://workspace.google.com/). It may be configured in such a way.

**Comment by joehan** [comment]
Hey @amiani -  this seems to be an issue with one specific Google account and not an issue with the firebase CLI. The maintainers of this repo aren't well equipped to debug this, so I am going to close it for now. If you are still facing this issue, please reach out to Firebase Support (https://firebase.google.com/support) and they may be better able to help you
