### ISSUE TITLE
storage deployment to specific target deploy to all targets

### ISSUE THREAD

**Issue by ederng29** [firebase/firebase-tools#3496]
When trying to deploy storage rules to a specific target the deployment goes to all targets

### [REQUIRED] Environment info

**firebase-tools:**. 9.13.0

**Platform:** macOS

### [REQUIRED] Test case

"firebase.json":
```
{
...
"storage": [
    {
      "target": "main",
      "rules": "storage.rules"
    },
    {
      "target": "backup",
      "rules": "storage-backup.rules"
    }
  ]
}
```

".firebaserc"
```
{
  "targets": {
    "my-firebase-project": {
      "storage": {
        "backup": [
          "my-firebase-project-backup"
        ],
        "main": [
          "my-firebase-project.appspot.com"
        ]
      }
    }
  }
}
```

### [REQUIRED] Steps to reproduce

deploy only backup target
firebase deploy --only storage:backup

### [REQUIRED] Expected behavior

deploy rules only for the backup target

### [REQUIRED] Actual behavior

i  storage: uploading rules storage.rules...
i  storage: latest version of storage-backup.rules already up to date, skipping upload...
✔  storage: released rules storage-backup.rules to firebase.storage
✔  storage: released rules storage.rules to firebase.storage

**Comment by bkendall** [comment]
Thanks for the report. It's been escalated internally (b/190826122) and someone from the Storage team will hopefully be looking at this soon.

**Comment by RCSandberg** [comment]
Many thanks for the help Eder!
