### ISSUE TITLE
`firebase init hosting:github` not working on 9.13

### ISSUE THREAD

**Issue by junaga** [firebase/firebase-tools#3498]
### Environment info

```sh
$ uname -a
Linux hs-win-box 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 GNU/Linux
$ npx firebase --version
9.13.0
```

### Test case

Install Firebase CLI v9.13
`npm init -y && npm install firebase-tools@latest`

Try to run this
`npx firebase init hosting:github`

### Expected behavior

It should have taken me through the [Firebase Hosting GitHub Action](https://firebase.google.com/docs/hosting/github-integration#set-up) wizard.

### Actual behavior

```sh
$ npx firebase --debug init hosting:github
[2021-06-16T19:09:09.015Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2021-06-16T19:09:09.015Z] > authorizing via signed-in user (hermann-stanew@invita.gmbh)

Error: hosting:github is not a supported feature; must be one of database, firestore, functions, hosting, storage, emulators, remoteconfig.
```

### Where it's broken

It works on 1.12, i downgraded to use this feature. I don't wanna deal with Service Accounts as a newbie. TY guys for the product, I Love Firebase.

**Comment by samtstern** [comment]
Ah yes this was probably caused by this PR:
https://github.com/firebase/firebase-tools/pull/3449

I'll get a fix ready!

**Comment by junaga** [comment]
Thank you!
