### ISSUE TITLE
broken link from npmjs.com package page

### ISSUE THREAD

**Issue by ultrasaurus** [firebase/firebase-tools#351]
I was looking for this repo via Google search (forgot for a minute it was called `firebase-tools`). 

1. I did a google search for "firebase CLI" 
2. this repo is the 3rd result, but I was scanning for the npm page, so I clicked fourth result which was: https://www.npmjs.com/package/firebase-cli  
3. on the right side:
![image](https://cloud.githubusercontent.com/assets/41906/26530164/829af276-4384-11e7-911c-8509134721d5.png) 

Result: github link: https://github.com/firebase/firebase-cli results in a 404

Expected: should link here

**Comment by laurenzlong** [comment]
It now seems to link here, can you check again @ultrasaurus, and reopen if you still see a 404?
