### ISSUE TITLE
Cannot read property 'backend' of undefined

### ISSUE THREAD

**Issue by mrassili** [firebase/firebase-tools#3512]
### [REQUIRED] Environment info

**firebase-tools:**
9.13.1

**Node:**
14.17.0

**Platform:**
maCOS 11.4

### [REQUIRED] Test case

Setup a hosting site and run deploy

### [REQUIRED] Steps to reproduce

Run `firebase deploy`

### [REQUIRED] Expected behavior

Successful deployment

### [REQUIRED] Actual behavior

Error: An unexpected error has occurred.
with this error: `TypeError: Cannot read property 'backend' of undefined`

Logs
![Screen Shot 2021-06-18 at 6 05 01 PM](https://user-images.githubusercontent.com/25288435/122595024-b742a200-d05f-11eb-9c74-7473b63631b3.png)

![Screen Shot 2021-06-18 at 6 01 15 PM](https://user-images.githubusercontent.com/25288435/122594641-2e2b6b00-d05f-11eb-9235-aa8dc97223b8.png)

**Comment by thibaut-adx** [comment]
Exactly the same error for the same environment!

**Comment by inlined** [comment]
From a cursory scan of the codebase it looks like this would crash if you don’t actually have any functions exported in your codebase. Can you confirm that this is the case?
