### ISSUE TITLE
Unable to auth:import from SHA1 password hash algorithm with salt

### ISSUE THREAD

**Issue by davidhartsough** [firebase/firebase-tools#3514]
### [REQUIRED] Environment info

**firebase-tools:** 9.13.1

**Platform:** macOS

### [REQUIRED] Test case

Run `auth:import`:

```bash
firebase auth:import users.json --hash-algo=SHA1 --rounds=1 --hash-input-order=PASSWORD_FIRST
```

Using this `users.json` file:

```json
{
  "users": [
    {
      "localId": "examplenewuserid",
      "email": "example@email.com",
      "emailVerified": false,
      "passwordHash": "Qzg4RTlDNjcwNDFBNzRFMDM1N0JFRkRGRjkzRjg3RERFMDkwNDIxNA==",
      "salt": "c2FsdA==",
      "createdAt": "1621041537556",
      "disabled": false,
      "providerUserInfo": []
    }
  ]
}
```

### [REQUIRED] Steps to reproduce

1. Assume we are going to import this user: `email: example@email.com, password: password`
2. Use 1 round of the SHA1 hashing algorithm with salt to get the hash, assuming the salt is `salt` and it is appended at the end after the password, resulting in the password hash: `C88E9C67041A74E0357BEFDFF93F87DDE0904214`
3. Then base64 encode both the hash and the salt: `"passwordHash": "Qzg4RTlDNjcwNDFBNzRFMDM1N0JFRkRGRjkzRjg3RERFMDkwNDIxNA==", "salt": "c2FsdA=="`
4. Create the `users.json` file as shown above
5. Run the `auth:import` command as shown above: `firebase auth:import users.json --hash-algo=SHA1 --rounds=1 --hash-input-order=PASSWORD_FIRST`

### [REQUIRED] Expected behavior

The new user should be fully imported/migrated to the project's firebase auth. 
To verify this, I should be able to run the `auth:export` command and see the new user, and I should be able to log in as that user (using the original email and password). 

```bash
firebase auth:export users-export.json
```

And I should see the following output in the exported JSON file: 

```json
{"users": [
{
  "localId": "examplenewuserid",
  "email": "example@email.com",
  "emailVerified": false,
  "passwordHash": "SOMETHING",
  "salt": "SOMETHING",
  "createdAt": "1621041537556",
  "disabled": false,
  "providerUserInfo": []
}]}
```

### [REQUIRED] Actual behavior

When I run the `auth:import` command with the `--debug` flag, I'm shown: 

(I'm hiding all personal information from the logs by replacing my email with `<EMAIL>` and my project id with `<PROJECT_ID>`.)

```
[2021-06-19T00:02:31.531Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2021-06-19T00:02:31.532Z] > authorizing via signed-in user (<EMAIL>)
[2021-06-19T00:02:31.534Z] [iam] checking project <PROJECT_ID> for permissions ["firebase.projects.get","firebaseauth.users.create","firebaseauth.users.update"]
[2021-06-19T00:02:31.540Z] > refreshing access token with scopes: ["email","https://www.googleapis.com/auth/cloud-platform","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","openid"]
[2021-06-19T00:02:31.540Z] >>> HTTP REQUEST POST https://www.googleapis.com/oauth2/v3/token  
 <request body omitted>
[2021-06-19T00:02:31.800Z] <<< HTTP RESPONSE 200 {"date":"Sat, 19 Jun 2021 00:02:31 GMT","pragma":"no-cache","cache-control":"no-cache, no-store, max-age=0, must-revalidate","expires":"Mon, 01 Jan 1990 00:00:00 GMT","content-type":"application/json; charset=utf-8","vary":"X-Origin, Referer, Origin,Accept-Encoding","server":"scaffolding on HTTPServer2","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","alt-svc":"h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000,h3-T051=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","accept-ranges":"none","transfer-encoding":"chunked"}
[2021-06-19T00:02:31.830Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects/<PROJECT_ID>:testIamPermissions  
 {"permissions":["firebase.projects.get","firebaseauth.users.create","firebaseauth.users.update"]}
[2021-06-19T00:02:32.034Z] <<< HTTP RESPONSE 200 {"content-type":"application/json; charset=UTF-8","vary":"X-Origin, Referer, Origin,Accept-Encoding","date":"Sat, 19 Jun 2021 00:02:32 GMT","server":"ESF","cache-control":"private","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","server-timing":"gfet4t7; dur=45","alt-svc":"h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000,h3-T051=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","accept-ranges":"none","transfer-encoding":"chunked"}
Processing users.json (334 bytes)
[2021-06-19T00:02:32.045Z] Preparing to import 1 user records in 1 batches.
Starting importing 1 account(s).
[2021-06-19T00:02:32.047Z] >>> HTTP REQUEST POST https://www.googleapis.com/identitytoolkit/v3/relyingparty/uploadAccount  
 {"users":[{"localId":"examplenewuserid","email":"example@email.com","emailVerified":false,"passwordHash":"Qzg4RTlDNjcwNDFBNzRFMDM1N0JFRkRGRjkzRjg3RERFMDkwNDIxNA==","salt":"c2FsdA==","createdAt":"1621041537556","disabled":false,"providerUserInfo":[]}],"hashAlgorithm":"SHA1","rounds":"1","passwordHashOrder":"PASSWORD_AND_SALT","targetProjectId":"<PROJECT_ID>"}
[2021-06-19T00:02:32.830Z] <<< HTTP RESPONSE 200 {"expires":"Mon, 01 Jan 1990 00:00:00 GMT","date":"Sat, 19 Jun 2021 00:02:32 GMT","cache-control":"no-cache, no-store, max-age=0, must-revalidate","pragma":"no-cache","content-type":"application/json; charset=UTF-8","vary":"X-Origin, Referer, Origin,Accept-Encoding","server":"ESF","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","alt-svc":"h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000,h3-T051=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","accept-ranges":"none","transfer-encoding":"chunked"}
✔  Imported successfully. 
```

So the command does in fact successfully POST to the https://www.googleapis.com/identitytoolkit/v3/relyingparty/uploadAccount endpoint, as it should, with the appropriate body. 

However, when I run the `firebase auth:export users-export.json` command, I get the following JSON: 

```json
{"users": [
{
  "localId": "examplenewuserid",
  "email": "example@email.com",
  "emailVerified": false,
  "createdAt": "1621041537556",
  "disabled": false,
  "providerUserInfo": []
}]}
```

The "passwordHash" and "salt" properties are missing. So when I try to login with this user (using the original email and password), I get the following error: 

```
Failed to load resource: the server responded with a status of 400
https://www.googleapis.com/identitytoolkit/v3/relyingparty/verifyPassword?key=MYAPIKEY
auth/user-not-found: There is no user record corresponding to this identifier. The user may have been deleted.
```

----

### Discussion

I understand that this is technically not an issue with the `firebase-tools` library/repo, because it is successfully POSTing to the Google Identity Toolkit API as expected. So the issue is actually occurring at the googleapis.com/identitytoolkit/v3/relyingparty/uploadAccount API endpoint. However, there is no public GitHub repo of that API's source code for me to go open an issue at. (This is the closest thing I've got! And I've also opened a support case with Firebase that is still ongoing.) 

<details>
  <summary>Additional Note: testing with Admin SDK</summary>

#### More Testing

I've also tried this auth import/migration with the Firebase Admin SDK. (I know this is not the repo for it, but I thought I should mention it as well.) Without getting too deep into it, I'll just say that I tried this Node.js script, and it did not work either. Same problems occurred (which further supports the idea that this is a problem originating at the Identity Toolkit API and not with either the firebase tools or with the admin SDK). Here is the script: 

```js
import admin from "firebase-admin";
import serviceAccount from "./serviceAccountKey.json";

admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
});
const usersToImport = [
  {
    uid: "examplenewuserid",
    email: "example@email.com",
    passwordHash: Buffer.from("C88E9C67041A74E0357BEFDFF93F87DDE0904214"),
    passwordSalt: Buffer.from("salt"),
    passwordHashOrder: "PASSWORD_AND_SALT", // <-- optional, but doesn't work with or without this
  },
];
const importOptions = {
  hash: {
    algorithm: "SHA1",
    rounds: 1,
  },
};
admin.auth().importUsers(usersToImport, importOptions).then((results) => {
  const { errors, failureCount, successCount } = results;
  console.log("errors:", errors);
  console.log("failureCount:", failureCount);
  console.log("successCount:", successCount);
}).catch(console.log);
```

</details>

----

Any and all help would be incredibly appreciated :) Thanks!

**Comment by davidhartsough** [comment]
I should also mention that I have tried this with the lowercase version of the hash. 

- The lowercase password hash is: `c88e9c67041a74e0357befdff93f87dde0904214`
- And base64 encoded that is: `Yzg4ZTljNjcwNDFhNzRlMDM1N2JlZmRmZjkzZjg3ZGRlMDkwNDIxNA==`

So the JSON file to import would look like this: 

```json
{
  "users": [
    {
      "localId": "exampleuid",
      "email": "email@email.com",
      "emailVerified": false,
      "passwordHash": "Yzg4ZTljNjcwNDFhNzRlMDM1N2JlZmRmZjkzZjg3ZGRlMDkwNDIxNA==",
      "salt": "c2FsdA==",
      "createdAt": "1621041537556",
      "disabled": false,
      "providerUserInfo": []
    }
  ]
}
```

Unfortunately this still does not work for me.

**Comment by davidhartsough** [comment]
I've tried to do all of this without the hex encoded values. So here's the code I used to get the base64 encoded password hash and the salt. (I put an example in Node.js and one in Python. Both get the same results.) 

<details>

<summary>Node.js</summary>

```js
const password = "password";
const salt = "salt";
const { createHash } = await import("crypto");
const hash = createHash("sha1");
hash.update(password + salt);
const encodedHash = hash.digest().toString("base64");
const encodedSalt = Buffer.from(salt).toString("base64");
console.log("encodedHash:", encodedHash);
console.log("encodedSalt:", encodedSalt);
```

</details>

<details>

<summary>Python</summary>

```py
import hashlib
import base64

password = "password"
salt = "salt"
password_and_salt = password + salt
hash_digest = hashlib.sha1(password_and_salt.encode("utf-8")).digest()
encoded_hash = base64.b64encode(hash_digest)
encoded_salt = base64.b64encode(bytes("salt", "utf-8"))
print(encoded_hash)
print(encoded_salt)
```

</details>

In the end, I get the following values: 

```
hash: "yI6cZwQadOA1e+/f+T+H3eCQQhQ="
salt: "c2FsdA=="
```

Thus I created this JSON file: 

```json
{
  "users": [
    {
      "localId": "legituser",
      "email": "legit@email.com",
      "emailVerified": false,
      "passwordHash": "yI6cZwQadOA1e+/f+T+H3eCQQhQ=",
      "salt": "c2FsdA==",
      "createdAt": "1621041537556",
      "disabled": false,
      "providerUserInfo": []
    }
  ]
}
```

Then I ran the `auth:import` command: 

```bash
firebase auth:import user.json --hash-algo=SHA1 --rounds=1 --hash-input-order=PASSWORD_FIRST
```

That outputs the following: 

```
Processing user.json (297 bytes)
Starting importing 1 account(s).
✔  Imported successfully.
```

Then I run the `auth:export` command:

```bash
firebase auth:export userexport.json  
```

That outputs: 

```
Exporting accounts to userexport.json
✔  Exported 13 account(s) successfully.
```

(I have 13 test users, so this is expected.) 

And that JSON export shows the following for my new user: 

```json
{
  "localId": "legituser",
  "email": "legit@email.com",
  "emailVerified": false,
  "createdAt": "1621041537556",
  "disabled": false,
  "providerUserInfo": []
},
```

So this user is missing the "passwordHash" and the "salt" properties as well. (And login does not work.)

**Comment by samtstern** [comment]
@davidhartsough thank you for all the information! Let me see if I can find the right person from the Auth team to take a look.

**Comment by samtstern** [comment]
@rosalyntan assigning to you since you're on call this week.

**Comment by rosalyntan** [comment]
Routing to the secondary oncall.

**Comment by yuchenshi** [comment]
Thanks for the detailed report! As you've observed, the issue is likely on the API backend. I understand that you've filed a support case -- which is the recommended avenue for such issues. Please make sure to link the findings in this GitHub issues there, and we'll get it to the right team.

I'm going to close this issue for now to avoid duplication, but again, we'll catch you on the flip side on the support ticket. For password related issues, we recommend sharing details like hashes and secrets on the support ticket instead for security reasons. Our support team can also look into your project config in case this is project-specific. Thanks again!
