### ISSUE TITLE
using Storage Emulator, I cannot use listAll function.

### ISSUE THREAD

**Issue by torkralle** [firebase/firebase-tools#3533]
### [REQUIRED] Environment info

**firebase-tools:**     "firebase-tools": "^8.15.0",

**Platform:** macOS Catalina

### [REQUIRED] Test case

I can get info by using listAll function in production environment,  but if I use storage emulator, I cannot get info.

### [REQUIRED] Steps to reproduce
// in initFile
const storage = firebase.storage();
storage.useEmulator("localhost", 9199);
// in apiFile
const storageRef = storage.ref(`${uid}`);
const res = await storageRef.listAll();

### [REQUIRED] Expected behavior
I can get all info by using listAll function.

### [REQUIRED] Actual behavior

FirebaseError: Firebase Storage: User does not have permission to access 'hogehogefugafuga'. (storage/unauthorized)
{"error":{"code":403,"message":"Permission denied. No LIST permission."}}

**Comment by samtstern** [comment]
@torkralle can you please show me your Storage rules?

**Comment by abeisgoat** [comment]
There is a known edge case with rules and listing on `/` but as long as your `uid` is not empty, it should work. +1 to @samtstern let's take a look at the rules, it could be an issue there or on our side.

**Comment by torkralle** [comment]
@samtstern 
Thank you, and I'm sorry for missing your reply...
My rule is here.
```
    match /{uid}/{fileName} {
      allow read: if request.auth != null;
    }
```

**Comment by torkralle** [comment]
and fetch image code is here.
```
try {
    const storageRef = storage.ref(`${uid}`);
    const res = await storageRef.listAll();
    let uploadedPhotos = [];
    const fetchImage = async (ref) => {
      const path = ref.location.path_;
      const url = await ref.getDownloadURL();
      uploadedPhotos.push({
        url,
        path,
      });
    };
    for (let i = 0; i < res.items.length; i++) {
      await fetchImage(res.items[i]);
    }
    return uploadedPhotos;
  } catch (e) {
    console.error(e);
  }
```

**Comment by tonyjhuang** [comment]
Filed internal bug to track, b/240637118

**Comment by tonyjhuang** [comment]
The fix will be present in the next version of the emulator
