### ISSUE TITLE
firebase init error

### ISSUE THREAD

**Issue by marcioseno** [firebase/firebase-tools#3535]
I created a simple expo bare app and I am trying to connect with firebase. I use firebase init and I have this:
TypeError: params.rootTag is null
runApplication
node_modules/react-native-web/dist/exports/AppRegistry/index.js:90

The problem appears when I create firebase init firestore.

Simplified test case:

Steps to reproduce:

create-react-native-app my-app
npm install --save firebase
npm install firebase-tools
firebase init

I am trying to show a simple Hello World

I am using:

React Native for Web (version): 0.17.1
React (version): 17.0.2
Browser: firefox 89.0

**Comment by samtstern** [comment]
@marcioseno the error you're getting is not from the Firebase CLI:
```
node_modules/react-native-web/dist/exports/AppRegistry/index.js:90
```

So I think this question would be better asked on StackOverflow or on a React Native repo.
