### ISSUE TITLE
Incomplete event context when creating a new user

### ISSUE THREAD

**Issue by jgavazzisp** [firebase/firebase-tools#3536]
### [REQUIRED] Environment info

**firebase-tools:** 9.14.0

**Platform:** Mac

### [REQUIRED] Test case

Creating a new user (either using google, magic link, or anonymous) which in its turn trigger firebase functions are such:

![image](https://user-images.githubusercontent.com/309389/123595740-5e37f280-d845-11eb-9e01-31326e9bc449.png)

Receives an incomplete auth event context as such:

![image](https://user-images.githubusercontent.com/309389/123595830-7a3b9400-d845-11eb-9784-c14f778ea7af.png)

The event is missing among other things the timestamp which I use to determine if the event is older than 10 minutes if so, stop to retry (fail-safe circuit for retriable functions).

### [REQUIRED] Steps to reproduce

Described above.

### [REQUIRED] Expected behavior

The event context should return eventId and timestamp.

### [REQUIRED] Actual behavior

EventId and timestamp are missing.

Debug log is attached.

Thanks
[log.txt](https://github.com/firebase/firebase-tools/files/6724251/log.txt)

**Comment by samtstern** [comment]
@jgavazzisp thanks for reporting! I've got a fix ready in #3540

**Comment by jgavazzisp** [comment]
thanks @samtstern
