### ISSUE TITLE
'demo-' projects don't seem to work (yet?)

### ISSUE THREAD

**Issue by spicemix** [firebase/firebase-tools#3549]
### [REQUIRED] Environment info

**firebase-tools: 9.14.0**

**Platform: macOs**

### [REQUIRED] Test case

Create a new project called `demo-myproject`

### [REQUIRED] Steps to reproduce

`firebase init`
...
Create new project
Name project `demo-myproject`

### [REQUIRED] Expected behavior

I get a firebase "demo" project made locally that only hits the emulators and never hits the server, as the [published emulators documentation tells me it does](https://firebase.google.com/docs/emulator-suite/connect_auth?authuser=0#choose_a_firebase_project).

### [REQUIRED] Actual behavior

-> firebase cli throws error and suggests reading log
-> log says `FirebaseError: HTTP Error: 400, field [project_id] has issue [project_id contains prohibited words]`

I was unable to find any documentation how to make these demo projects. They sound like a great idea though. Did documentation jump the gun letting us know about them too early? Or am I missing something obvious again? Thanks!

**Comment by samtstern** [comment]
@spicemix sorry I think this is just a misunderstanding! You can't actually "create" a `demo-` project. Instead you can just use `demo-` project IDs locally within the emulator suite. This is a safety feature, by using a project ID that starts with `demo-*` you can be _sure_ that there is no real project with that name in the Cloud and so you won't possibly make any damaging requests.

I'll forward this on to our documentation team so that they can maybe clarify.

**Comment by laurentpayot** [comment]
Oh, good to know. I would have done like @spicemix.

**Comment by spicemix** [comment]
So the workflow then is...create a project *not* with a `demo-` prefix, but use the `demo-` prefix...uh...somehow...the CLI won't do it for you...you have to know where to change the project ID...and make sure you do it in all the important places, by hand...?

If so, I would need documentation on exactly where and how. You might re-open this as a feature request on the CLI if it doesn't do this for users but this is advertised as a best practice in current documentation on the emulators. A CLI command for "set up demo- mode" might work a treat, and with additional commands we could toggle demo- mode on and off easily. And since it's claimed to be a best practice when starting a new firebase project, I'd think demo mode should be an option in the firebase init setup questionnaire, instead of an unexplained error buried in the logs.

FWIW, the only problem I'm having with the emulators without demo- mode (via the latest Angularfire) is that my auth stuff somehow still goes onto the main firebase cloud site instead of the auth emulator. I've tried many things to force it onto the emulator, but it still goes onto the cloud, and demo- mode was sorta my last hope on that. All the other emulators work fine, even the storage emulator that Angularfire doesn't officially support yet. I can keep trying to fix that but an easily applied demo mode that forces it at a lower level would be nice. Thanks!

**Comment by samtstern** [comment]
@spicemix we hear you! We're working on some larger changes to make the Emulators behavior much clearer when it comes to project IDs however they will be breaking changes for some workflows so they'll have to wait until the next major version of the Firebase CLI.

For now with `demo-*` projects you should put the project ID in the following places:

  * The `--project` flag when you start the emulators
  * In your `initializeApp` calls

<hr />

Some specific responses to your points:

> [...Thinking more about this, maybe this is part of "the emulators will accept any well-formed project ID" thing that I also find odd. Like, there is this weird disconnect between the local and cloud structures of a project, where sometimes the cloud is consulted even when using the emulators...but how would it be consulted if the project ID didn't match... Maybe the point is the cloud never actually needs to be consulted at all, local can run completely on its own, and simply by making demo- an illegal prefix, we are certain that is the case when using that project ID, as we could any project ID for the same project... I mean, am I rare in being confused by this? ]

You've got it right. By reserving an illegal project ID namespace (`demo-*`) we can make stronger assurances that real cloud resources are never used.

> [ Oh and to sum all that up...why not scrap the if (runningOnLocalhost()) firestore.useEmulators("http://localhost:9000") mess altogether then, and just let us use the CLI to set, at its low level, whether we use emulators, or staging, or prod? Why have us encrust our app code with conditionals that will only be used in testing, when you've got this CLI and control of the SDK API and can do the intercepting for us? ]

Actually we do this if you're running in the Hosting emulator! The `init.js?useEmulators=true` setting automatically calls `useEmulator` on all SDKs for which we detect a running emulator.

**Comment by spicemix** [comment]
Thanks @samtstern for your explanations. Of course this isn't an edge case thing, switching from emulators/staging/prod is central to your developer experience, and tricks like "let's have them just...swap out project IDs!" are obviously temporary while you develop a cleaner solution. So I look forward to that and I will claw through the temporaries in the meantime. Thanks!

**Comment by laurentpayot** [comment]
> We're working on some larger changes to make the Emulators behavior much clearer when it comes to project IDs however they will be breaking changes for some workflows so they'll have to wait until the next major version of the Firebase CLI.

I finally switched to `demo-` prefix for local development. Unfortunately we still have to inject the demo project ID  with `--project` flags in the emulators and with `initializeApp` calls. Any news @samtstern?
