### ISSUE TITLE
npm 7 / ability to specify npm version

### ISSUE THREAD

**Issue by aravindvnair99** [firebase/firebase-tools#3552]
I use Node.js 14.16.0 with npm 7 locally, but when I check the version on the cloud, I get Node.js 14.16.0 with npm 6.14.11. Right now we do have a field in `package.json` to specify the Node.js version but no such field for npm. I was wondering if there could be a field for that as well or if npm could be updated.

References:
- https://github.blog/2020-10-13-presenting-v7-0-0-of-the-npm-cli/
- https://github.blog/2021-02-02-npm-7-is-now-generally-available/
- https://github.com/firebase/firebase-tools/blob/b81da443dc3ca94221f7f1238c1d9a2dfe6273bd/templates/init/functions/javascript/package.lint.json#L12-L14

**Comment by samtstern** [comment]
@aravindvnair99 thanks for the request! We'd love to support `npm` v7 but this isn't something we can do unilaterally in the Firebase CLI. We would need a change in how Google Cloud Functions builds functions container images for deployment.

The best thing to do would be to file an issue on the GCF issue tracker requesting this:
https://cloud.google.com/support/docs/issue-trackers#trackers-list

Then if it's added on the backend, we can create a way to configure that through the Firebase CLI. For now though, there's not much we can do here.

cc @taeold

**Comment by aravindvnair99** [comment]
> @aravindvnair99 thanks for the request! We'd love to support `npm` v7 but this isn't something we can do unilaterally in the Firebase CLI. We would need a change in how Google Cloud Functions builds functions container images for deployment.
> 
> The best thing to do would be to file an issue on the GCF issue tracker requesting this:
> https://cloud.google.com/support/docs/issue-trackers#trackers-list
> 
> Then if it's added on the backend, we can create a way to configure that through the Firebase CLI. For now though, there's not much we can do here.
> 
> cc @taeold

Thank you for the clarification and response @samtstern! I understand and I have gone ahead and created an issue tracker here: https://issuetracker.google.com/issues/192771775

**Comment by taeold** [comment]
My guess is that nodejs16 (when it becomes available) will by default use npm v7. +1 to everything @samtstern said.

**Comment by aravindvnair99** [comment]
> My guess is that nodejs16 (when it becomes available) will by default use npm v7. +1 to everything @samtstern said.

@taeold Node.js 15 and above come with npm 7 by default, but it would be great to have it earlier too! Especially since new versions take time to be supported.

**Comment by aravindvnair99** [comment]
> My guess is that nodejs16 (when it becomes available) will by default use npm v7. +1 to everything @samtstern said.

@taeold Node.js 15 and above come with npm 7 by default, but it would be great to have it earlier too! Especially since new versions take time to be supported.

Additionally, having the ability to pin npm versions would also be a nice thing to have.

**Comment by taeold** [comment]
@aravindvnair99 Yep. I think the decision is for Google Cloud Functions team to make. It would be helpful if you can include the use cases for using npm v7 in your issue tracker. That way, the team can prioritize the work if they find the usecase compelling.
