### ISSUE TITLE
Firebase Storage emulator doesn't recognize multiple buckets rules

### ISSUE THREAD

**Issue by ggirotto** [firebase/firebase-tools#3554]
I'm trying to use Firebase Storage with my environment where I have multiple security rules associated with different buckets. The problem is that Firebase Storage seems to not recognize this multiple storage rules environment, and outputs the error:

`Error: Cannot start the Storage emulator without rules file specified in firebase.json: run 'firebase init' and set up your Storage configuration`

### [REQUIRED] Environment info

**firebase-tools:** 9.14.0

**Platform:** macOS

### [REQUIRED] Test case

Example firebase.json
<details>

```json
{
  "firestore": {
    "rules": "firestore.rules",
    "indexes": "firestore.indexes.json"
  },
  "functions": {
    "predeploy": [
      "npm --prefix \"$RESOURCE_DIR\" run lint",
      "npm --prefix \"$RESOURCE_DIR\" run build"
    ],
    "source": "functions"
  },
  "storage": [
    {
      "rules": "profile_pictures_storage.rules",
      "bucket": "<PROFILE_PICTURES_BUCKET>"
    },
    {
      "rules": "default_storage.rules",
      "bucket": "<DEFAULT_BUCKET_ID>"
    }
  ],
  "emulators": {
    "functions": {
      "port": 5001
    },
    "firestore": {
      "port": 8080
    },
    "pubsub": {
      "port": 8085
    },
    "ui": {
      "enabled": true
    },
    "auth": {
      "port": 9099
    },
    "storage": {
      "port": 9199
    }
  }
}
```

</details>

default_storage.rules
<details>

```
rules_version = '2';

service firebase.storage {
  match /b/{bucket}/o {
    match /{userId}/{imageId} {
      allow read: if false;
      allow write: if false;
    }
  }
}
```

</details>

profile_pictures_storage.rules
<details>

```
rules_version = '2';

service firebase.storage {
  match /b/{bucket}/o {
    match /{userId}/{imageId} {
      function isResourceSmallerThan(megabytes) {
        return request.resource.size < megabytes * 1024 * 1024;
      }
      function isAuthenticated() {
        return request.auth != null && request.auth.uid != null;
      }

      // Allows any authenticated user to read any user image
      allow read: if isAuthenticated();

      // Allows write if the user is the owner of the image folder and if the resource is smaller than 1MB
      allow write: if isAuthenticated() && request.auth.uid == userId && isResourceSmallerThan(1);
    }
  }
}
```

</details>

### [REQUIRED] Steps to reproduce

Setup local firebase emulator suite and use the files provided above

### [REQUIRED] Expected behavior

Expected that the Firebase Storage emulators starts correctly when running

`firebase emulators:start --only storage`

### [REQUIRED] Actual behavior

`Error: Cannot start the Storage emulator without rules file specified in firebase.json: run 'firebase init' and set up your Storage configuration`

**Comment by samtstern** [comment]
@ggirotto thanks for the feedback! This is the same as https://github.com/firebase/firebase-tools/issues/3390 so let's use that one.

**Comment by ggirotto** [comment]
Sorry about the duplicate issue. Will subscribe there
