### ISSUE TITLE
Firestore emulator runs in isolation from firebase functions emulator

### ISSUE THREAD

**Issue by segevsh** [firebase/firebase-tools#3558]
### [REQUIRED] Environment info

9.14.0

**firebase-tools:**

macOS

**Platform:**

### [REQUIRED] Test case

I am running the emulators (firestore, firebase functions), when I use the functions to write into firestore (using admin SDK), it writes, and return the written value correctly. When I look for that value in firestore UI the value is not there. 
Vice a versa - when I change the value in the interface and pull it back using the admin SDK in functions, the new value is not there

### [REQUIRED] Steps to reproduce

firebase.json:
```json
{
/// config
"emulators": {
    "auth": {
      "port": 9099
    },
    "functions": {
      "port": 5001
    },
    "firestore": {
      "port": 8088
    },
    "hosting": {
      "port": 5000
    },
    "pubsub": {
      "port": 8090
    },
    "ui": {
      "enabled": true
    }
  },
/// rest of config
}
```

```bash
firebase emulators:start --export-on-exit=./emulators-data --import=./emulators-data
```

I am using Jest, and configuring the following at the top of the file : 
```js
process.env.FIRESTORE_EMULATOR_HOST = 'localhost:8088'
```

### [REQUIRED] Expected behavior

When updating the value using functions, it should update firestore. When changing the value in the UI it should reflect in functions. functions and firestore should be synced and have the same values always.

### [REQUIRED] Actual behavior

Feels like firestore runs in isolation from functions. While both emulators are running and there are no errors, the values are not in sync at all. 
Almost feels like firebase functions is writing into a different data repo, that is not the firestore that is running.

**Comment by samtstern** [comment]
@segevsh this sounds like you are maybe accidentally using your **production** Cloud Firestore. Can you double-check that the values you're reading and writing are not showing up in the Firebase console?

Note that this only works with the Admin SDK:
```
process.env.FIRESTORE_EMULATOR_HOST = 'localhost:8088'
```

For the Firestore mobile SDKs you need to call `useEmulator('locahost', 8088)` to connect.

**Comment by segevsh** [comment]
that was the first thing I checked for, and I'm afraid that that wasn't it: 
1. I checkt the production DB 

2. that's the weird part: I changed the values in the DB and restarted the emulator. functions was showing the NEW value, but again was running in isolation. This means that upon firing it was loading firestore from the exported data (with the latest value from firestore), but somehow running it's own version from that point forward

**Comment by samtstern** [comment]
Ok in that case it sounds like a Project ID mismatch. Can you make sure that you're using the same Project ID everywhere?  Check `initializeApp` statements and maybe also use the `--project` flag when starting the emulators.

**Comment by segevsh** [comment]
Yes that worked! I had `process.env.GCLOUD_PROJECT` setup prior, but it didn't take, so I had to hard code it into the test runner. 

Looks like `GCLOUD_PROJECT` ignores my setting, and changes its value into 'not-a-project' 

So, I went ahead and changed the init app like so: 

```js
admin.initializeApp({
    projectId: <projectId>

});
```
