### ISSUE TITLE
[v9.15.0] Latest release breaks FirebaseExtended/action-hosting-deploy GitHub action

### ISSUE THREAD

**Issue by Vluf** [firebase/firebase-tools#3561]
### [REQUIRED] Environment info

**firebase-tools:** 9.15.0

**Platform:** GH Actions (Ubuntu)

### [REQUIRED] Test case

Deploy any website with the FirebaseExtended/action-hosting-deploy GH action

### [REQUIRED] Steps to reproduce

Deploy any website with the FirebaseExtended/action-hosting-deploy GH action

### [REQUIRED] Expected behavior

The site to deploy

### [REQUIRED] Actual behavior

```
 ***
    "status": "error",
    "error": "There was an error loading firebase.json:\n\nENOENT: no such file or directory, open '/home/runner/.npm/_npx/1967/lib/node_modules/firebase-tools/schema/firebase-config.json'"
  ***
```

[Most likely culprit](https://github.com/firebase/firebase-tools/compare/v9.14.0...v9.15.0#diff-6a283fba2ff79ed5ad1a1f26809d745a3e642e23307c37a9754814fd3bfdcc6cR17-R29)

**Comment by jhaynie** [comment]
we are seeing the same thing after upgrade.

```firebase deploy --only firebase```

Output:

```Error: There was an error loading firebase.json:

ENOENT: no such file or directory, open '/Users/redacted/.nvm/versions/node/v14.13.1/lib/node_modules/firebase-tools/schema/firebase-config.json'```

Version: 9.15.0

**Comment by portokallidis** [comment]
Same for us. 
`  "error": "There was an error loading firebase.json:\n\nENOENT: no such file or directory, open '/home/nporto/.npm-global/lib/node_modules/firebase-tools/schema/firebase-config.json'"`

**Comment by hdh3000** [comment]
same here

**Comment by bkendall** [comment]
Hmmm. Thanks for raising. Investigating real quick to see if it's a quick fix...

**Comment by hosuaby** [comment]
I have the same issue. Not only on GitHhub Actions but also locally when running `firebase emulators:exec`.

**Comment by bkendall** [comment]
I can replicate it (on deploy), I can fix it (PR coming), and I can publish it! Hang tight...

**Comment by bkendall** [comment]
I'm pushing out `v9.15.1` right now. Should be available soon!

**Comment by Vluf** [comment]
Awesome response time @bkendall thanks!

**Comment by bkendall** [comment]
> Awesome response time @bkendall thanks!

You're welcome. When I see the email "[release you did] [just broke everything]" I get that little feeling most people do as their stomach drops and go look as fast as I can 😝

**Comment by bkendall** [comment]
It's published!

**Comment by Vluf** [comment]
> It's published!

& I can confirm that it's solved :) Thanks again
