### ISSUE TITLE
There was an error loading firebase.json

### ISSUE THREAD

**Issue by shipley-dcc** [firebase/firebase-tools#3563]
### [REQUIRED] Environment info

**firebase-tools: 9.15.0**

**Platform: Ubuntu**

### [REQUIRED] Test case

1. Install version 9.15.0 of firebase-tools
2. Run command `firebase deploy --only functions`

### [REQUIRED] Steps to reproduce

From the command line run `firebase deploy --only functions`.
Returns immediately with this error:
**Error: There was an error loading firebase.json:**
**ENOENT: no such file or directory, open '/home/.../node_modules/firebase-tools/schema/firebase-config.json'**
Downgraded to version 9.14.0 and I could deploy without the error.

### [REQUIRED] Expected behavior

Deploy Firebase functions without receiving an error.

### [REQUIRED] Actual behavior

Receive error outlined above.

**Comment by shipley-dcc** [comment]
Fixed in version 9.15.1

**Comment by dgpc** [comment]
Same issue occurs with `firebase emulators:exec` after upgrading to 9.15.0.

Breaking upstream tools like `action-hosting-deploy`:
https://github.com/FirebaseExtended/action-hosting-deploy/issues/137

**Comment by bkendall** [comment]
Duplicate of #3561

Thanks for the report though!
