### ISSUE TITLE
Emulators don't update (loads older versions of the files)

### ISSUE THREAD

**Issue by SincerityJayce** [firebase/firebase-tools#3565]
As above, when I save the files and reload the localhost:5000 (hosting) it loads old versions of the files.

I have tried killing all ports and restarting the emulators, updating the git, deleting old folders.

'$ firebase deploy' will put the code live on the website faster than then emulators will load it on localhost.

the code on port 5000 will update eventually, but I don't know what causes it to update.

**Comment by yuchenshi** [comment]
I think you ran into browser caching. Please try the usual debug steps like clearing cache in your browser settings, force-reloading, opening in a different browser, and browser DevTools (which usually has a setting to bypass all caches).

If you're still seeing old files even after the steps above, please share with us a minimal repro (e.g. a project directory with `firebase.json` and a few hosting files) and we'll look into it. If it is indeed browser caching, you can also dig a bit deeper into the HTTP response headers and let us know if you have any suggestions for improvement.

**Comment by SincerityJayce** [comment]
as above

**Comment by abeisgoat** [comment]
+1 to what @yuchenshi said and without further details we can't help. Feel free to reopen if you have more info.
