### ISSUE TITLE
firebase login throws Error: redirect_uri_mismatch in browser 

### ISSUE THREAD

**Issue by wallofmoments** [firebase/firebase-tools#357]
Command: ` firebase --project my-project-id login --reauth`

This throws the following error in my browser: 

```
Error: redirect_uri_mismatch

The redirect URI in the request, http://localhost:9005, does not match the ones authorized for the OAuth client. Visit https://console.developers.google.com/apis/credentials/... to update the authorized redirect URIs.
```

On the developer console I have added `http://localhost:9005` under OAuth 2.0 client IDs (Web client) as an authorized redirect URI. Same error is thrown

**Comment by wallofmoments** [comment]
Is there any update on this? None of the login command flags (--interactive --reauth etc) work and api panel is correctly configured. 

Note: The URL suggested in the error notice points to a wrong project ID

**Comment by mbleigh** [comment]
Please re-open if this is sttill a problem.
