### ISSUE TITLE
"request entity too large" when trying to import into auth emulator

### ISSUE THREAD

**Issue by mayankj** [firebase/firebase-tools#3570]
### [REQUIRED] Environment info

**firebase-tools:** 9.13.0

**Platform:** Windows (using WSL)

### [REQUIRED] Test case

- Auth having more than 200 users triggers this error. 

### [REQUIRED] Steps to reproduce
- Create at least 200 users with the auth emulator running
- Export this using firebase emulators:export <dir-name> 
- Try importing this using firebase emulators:start --import <dir-name> and you will encounter this bug. 

### [REQUIRED] Expected behavior
Expected behaviour is for the import to succeed. 

### [REQUIRED] Actual behavior
![image](https://user-images.githubusercontent.com/2641144/125108206-bb3a7080-e0af-11eb-86b7-aec1bff8bf62.png)

Log file when ran with --debug: [log.log](https://github.com/firebase/firebase-tools/files/6792707/log.log)

**Comment by yuchenshi** [comment]
The fix is now merged and will be included in the next release.
