### ISSUE TITLE
Firebase deploy Cloud Functions failure on M1 Mac: "functions is declared but its value is never read."

### ISSUE THREAD

**Issue by grapeworksdev** [firebase/firebase-tools#3572]
M1 Mac Mini : OS Big Sur 11.4

### [REQUIRED] Test case

My index.ts just uses the default starting point:

`// // Start writing Firebase Functions
// // https://firebase.google.com/docs/functions/typescript
//
export const helloWorld = functions.https.onRequest((request, response) => {
  functions.logger.info("Hello logs!", {structuredData: true});
  response.send("Hello from Firebase!");
});
`

### [REQUIRED] Steps to reproduce
Run 'firebase deploy' or 'firebase deploy --only functions'

### [REQUIRED] Expected behavior
Deploy Cloud functions successfully

I am able to successfully deploy on a non-M1 Mac

### [REQUIRED] Actual behavior

Have "functions is declared but its value is never read." when running 'firebase deploy --only functions' or 'firebase deploy'

`➜  functions git:(master) ✗ firebase deploy --only functions

=== Deploying to 'explore-tallahassee'...

i  deploying functions
Running command: npm --prefix "$RESOURCE_DIR" run lint

> lint
> eslint --ext .js,.ts .

/Users/Ashton/functions/src/index.ts
  1:13  warning  'functions' is defined but never used  @typescript-eslint/no-unused-vars

✖ 1 problem (0 errors, 1 warning)

Running command: npm --prefix "$RESOURCE_DIR" run build

> build
> tsc

src/index.ts:1:1 - error TS6133: 'functions' is declared but its value is never read.

1 import * as functions from "firebase-functions";
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error.


Error: functions predeploy error: Command terminated with non-zero exit code2`

**Comment by taeold** [comment]
You are seeing an eslint error. You'll have fix your code as suggested from the error message.

It looks like you accidentally commented out the `export` keyword:

```js
export const helloWorld = functions.https.onRequest((request, response) => { functions.logger.info("Hello logs!", {structuredData: true}); response.send("Hello from Firebase!"); });
```

**Comment by grapeworksdev** [comment]
@taeold Sorry, I pasted it incorrectly. Here are the functions I'm currently using in my index.ts file:
`
import * as functions from "firebase-functions";

import * as admin from "firebase-admin";
admin.initializeApp();

// // Start writing Firebase Functions
// // https://firebase.google.com/docs/functions/typescript


// Create user in Cloud Firestore when a new user is authorized

export const newUserSignup = functions.auth.user().onCreate((user) => {
  // for background triggers, must return a value/promise
  return admin.firestore().collection("users").doc(user.uid).set({
    email: user.email,
    displayName: user.displayName,
  });
});

// Delete user in Firestore when deleted in auth
export const userDeleted = functions.auth.user().onDelete((user) => {
  // for background triggers, must return a value/promise
  const doc = admin.firestore().collection("users").doc(user.uid);
  return doc.delete();
});`

I added this to my .eslintrc.js file and am still receiving the same error:
`  rules: {
    "no-unused-vars": "off",
    "@typescript-eslint/no-unused-vars": ["error"]
  },`

Error:
`➜  functions git:(master) ✗ firebase deploy --only functions

=== Deploying to 'explore-tallahassee'...

i  deploying functions
Running command: npm --prefix "$RESOURCE_DIR" run lint

> lint
> eslint --ext .js,.ts .


/Users/Ashton/functions/src/index.ts
  1:13  warning  'functions' is defined but never used  @typescript-eslint/no-unused-vars

✖ 1 problem (0 errors, 1 warning)

Running command: npm --prefix "$RESOURCE_DIR" run build

> build
> tsc

src/index.ts:1:1 - error TS6133: 'functions' is declared but its value is never read.

1 import * as functions from "firebase-functions";
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error.


Error: functions predeploy error: Command terminated with non-zero exit code2
`

I am using an M1 Mac Mini. I am only experiencing this issue on the M1.. I am able to successfully deploy form an Intel Mac.

**Comment by taeold** [comment]
I don't see anything wrong with your code and setup, and I'm as puzzled as you are.

On a second look, the error seems to be coming from `tsc`. Is there a way for you to double check the contents of the `index.ts` on your M1 Mac Mini? My suspicion is that the code on your Mac Mini is not what you are sharing with us.

If that's not the case, then I'm stumped too. Have you seen any M1 related bugs for `tsc`?

**Comment by grapeworksdev** [comment]
By index.ts on my M1 Mac Mini, you mean the index.ts file that is part of my project, right? That is what I shared with you:

`
import * as functions from "firebase-functions";

import * as admin from "firebase-admin";
admin.initializeApp();

// // Start writing Firebase Functions
// // https://firebase.google.com/docs/functions/typescript


// Create user in Cloud Firestore when a new user is authorized

export const newUserSignup = functions.auth.user().onCreate((user) => {
  // for background triggers, must return a value/promise
  return admin.firestore().collection("users").doc(user.uid).set({
    email: user.email,
    displayName: user.displayName,
  });
});

// Delete user in Firestore when deleted in auth
export const userDeleted = functions.auth.user().onDelete((user) => {
  // for background triggers, must return a value/promise
  const doc = admin.firestore().collection("users").doc(user.uid);
  return doc.delete();
});`

I haven't seen any M1 related bugs for tsc.

**Comment by samtstern** [comment]
@grapeworksdev would you mind uploading your project to a GitHub repo so we can take a look? I agree with @taeold I think there's a mismatch between the code you _think_ you're using and the code you're actually using.

**Comment by grapeworksdev** [comment]
@samtstern I have it as a private repository; I invited you as a collaborator to take a look

**Comment by samtstern** [comment]
@grapeworksdev thanks! That repo does not include a `firebase.json`, are you sure you have uploaded the right stuff? I would expect a `firebase.json` file in the root.

**Comment by grapeworksdev** [comment]
@samtstern I ran firebase init again and setup cloud functions. For some reason, the files go to my desktop instead of the /functions directory of my project. Initially it only created the 'functions' folder but now I see a few other files, including the firebase.json file, which I added to the repository.
![Screen Shot 2021-07-13 at 10 54 28](https://user-images.githubusercontent.com/80786010/125474475-bdd3e832-bbd0-44c7-998d-847e8bb703d6.png)

I tried running firebase deploy --only functions again and received the following error:
```➜  functions git:(master) ✗ firebase deploy --only functions --project explore-tallahassee

=== Deploying to 'explore-tallahassee'...

i  deploying functions
Running command: npm --prefix "$RESOURCE_DIR" run lint

> lint
> eslint --ext .js,.ts .

node:internal/modules/cjs/loader:930
  throw err;
  ^

Error: Cannot find module '../package.json'
Require stack:
- /Users/Ashton/IntelliJ-Idea-Projects/Flutter-Projects/grape_works_dev/explore_tallahassee/functions/node_modules/.bin/eslint
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:927:15)
    at Function.Module._load (node:internal/modules/cjs/loader:772:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at process.onFatalError (/Users/Ashton/IntelliJ-Idea-Projects/Flutter-Projects/grape_works_dev/explore_tallahassee/functions/node_modules/.bin/eslint:106:25)
    at process.emit (node:events:394:28)
    at process._fatalException (node:internal/process/execution:170:25) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/Ashton/IntelliJ-Idea-Projects/Flutter-Projects/grape_works_dev/explore_tallahassee/functions/node_modules/.bin/eslint'
  ]
}

Error: functions predeploy error: Command terminated with non-zero exit code7
```
![Screen Shot 2021-07-13 at 10 55 47](https://user-images.githubusercontent.com/80786010/125474819-34a81eef-bec0-4495-b75f-5e50871b253c.png)
![Screen Shot 2021-07-13 at 10 55 54](https://user-images.githubusercontent.com/80786010/125474828-bd4d3f1d-4405-4901-900b-e40c4b41df55.png)

**Comment by samtstern** [comment]
@grapeworksdev try deleting that `firebase.json` file in your `Ashton` folder, I think that's messing everything up.

**Comment by grapeworksdev** [comment]
@samtstern I tried that, still getting the same error.

**Comment by samtstern** [comment]
Ok as a final nuclear option you can try also deleting:
```
$HOME/.config/configstore/firebase-tools.json
```
