### ISSUE TITLE
Cannot start firebase emulator functions with node 14. ES Module import failure on windows.

### ISSUE THREAD

**Issue by paulvanj** [firebase/firebase-tools#3573]
I am getting the following error:
```
i  emulators: Starting emulators: auth, functions, firestore, hosting, storage
!  functions: The following emulators are not running, calls to these services from the Functions emulator will affect production: database, pubsub
+  functions: Using node@14 from host.
i  firestore: Firestore Emulator logging to firestore-debug.log
i  hosting: Serving hosting files from: dist/apps/public-client
+  hosting: Local server: http://localhost:5005
i  ui: Emulator UI logging to ui-debug.log
i  functions: Watching "D:\Github\ros-firebase\dist\libs\cloud-functions" for Cloud Functions...
!  functions: Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'd:'
!  Your function was killed because it raised an unhandled error.
```

Is there anything I can do from my side to solve this problem, or am I forced to use commonjs as long as I am developing on windows? (I do not like the idea of adding `simport` throughout the entire dependency chain of my cloud-functions code.)

_Originally posted by @DibyodyutiMondal in https://github.com/firebase/firebase-tools/issues/2994#issuecomment-878954659_

**Comment by taeold** [comment]
I have a proposed fix on branch [`dl-cf3-esm-windows`](https://github.com/firebase/firebase-tools/tree/dl-cf3-esm-windows). Can someone help me confirm the fix on windows?

```bash
> git clone https://github.com/firebase/firebase-tools.git
> cd firebase-tools
> git checkout origin/dl-cf3-esm-windows 
> npm i
> npm run build
> npm link # firebase cli should now point to locally built one
# cd to your functions project
> firebase functions:shell
```

**Comment by paulvanj** [comment]
> I have a proposed fix on branch [`dl-cf3-esm-windows`](https://github.com/firebase/firebase-tools/tree/dl-cf3-esm-windows). Can someone help me confirm the fix on windows?
> 
> ```shell
> > git clone https://github.com/firebase/firebase-tools.git
> > cd firebase-tools
> > git checkout origin/dl-cf3-esm-windows 
> > npm i
> > npm run build
> > npm link # firebase cli should now point to locally built one
> # cd to your functions project
> > firebase functions:shell
> ```

![image_2021_07_13T13_36_33_732Z](https://user-images.githubusercontent.com/13675068/125461908-07cc68f1-269f-4892-ad99-1e716ee72ba2.png)
![image_2021_07_13T13_35_22_632Z](https://user-images.githubusercontent.com/13675068/125461938-a443da85-a6d6-4919-acd0-a0f945f631ac.png)

Thanks, gave it a try and it produced the following error(see attached)... although the file does exist.
I am using Nodejs 14.17.3, tsconfig is set for es2020 with package.json's type as "module"

**Comment by DibyodyutiMondal** [comment]
This looks like the same result I got when I tried to use pathToUrl by editing the firebase-tools files  inside of node_modules..

Is this the same?

**Comment by DibyodyutiMondal** [comment]
I think it is not working because the import statements do not have the `.js` extension, as they are coming from typescript. 
Added problems when we use json files with typscript via the `resolveJsonModule` typescript option

**Comment by taeold** [comment]
@paulvanj You may already know now, but you need to include `.js` extension when importing from local modules:

```js
// BAD
import Setup from './utils/setup' 
// GOOD
import Setup from './utils/setup.js' 
```

@DibyodyutiMondal Curious, are you required to use ES module in your setup? In most cases, you would use `module: commonjs` and move along, but it sounds like you want to package your function definitions as a ES module. Can you share what you are trying to achieve?

(I'm closing the issue, as I think the reported issue is now answered. Feel free to re-open if you are still having a problem @paulvanj ).

**Comment by taeold** [comment]
Oops. I forgot that the original issue is still unfixed. I'll get a PR setup and actually release a fix before fixing the issue.

**Comment by DibyodyutiMondal** [comment]
Well, you are right - since I am using Typescript anyway, from a development perspective, I don't need to worry if the cloud-functions code is commonjs or esm. However, the cloud-functions code references libraries containing data models and the like, that are also used by my front-end angular app.

Since functions-framework can only load commonjs, these libraries must also be in commonjs, which then results in angular not being able to tree-shake them, increasing the size of the website distribution.

Hence my high preference to be able to use esm.

**Comment by taeold** [comment]
@DibyodyutiMondal Thanks for sharing your setup. It sounds advanced, and I'm glad to have a chance to learn how functions is being used by our advanced users.

It sounds like using Typescript (along with Webpaxk) with ES module is a tricky business, and I'm not too familiar with these techs to offer useful advice 😢. I am personally curious and going to try different setups to see if we can come up with a good starting template. Would appreciate if you can share what you learn from your setup.

**Comment by DibyodyutiMondal** [comment]
Sure, I would love to do that. Is there a designated place for that already, or I can just do that here?

**Comment by taeold** [comment]
@DibyodyutiMondal This is probably a good place to start. Once we have some concrete patterns and recommendations we can suggest, I will work with our DevRel team to find a good place to share the content so other users can learn from it.

Again, thanks for being on the bleeding edge and being proactive about your issues.
