### ISSUE TITLE
Missing Index No Longer Gives Direct Link To Create

### ISSUE THREAD

**Issue by clive-h-townsend** [firebase/firebase-tools#3583]
### [REQUIRED] Environment info

**firebase-tools:9.16.0**

**Platform:Ubuntu**

### [REQUIRED] Test case

Create a query with no index

### [REQUIRED] Steps to reproduce

1. Create a query with no current index
2. Look at error
3. No link provided per https://firebase.google.com/docs/firestore/query-data/indexing#create_a_missing_index_through_an_error_message

### [REQUIRED] Expected behavior

Make the link
### [REQUIRED] Actual behavior

![image](https://user-images.githubusercontent.com/41023984/126051257-afdd8ea5-1214-44e5-a1f5-0b6d8139b2c2.png)

**Comment by clive-h-townsend** [comment]
https://stackoverflow.com/questions/68374000/uncaught-error-in-snapshot-listener-firebaseerror-no-matching-index-found

**Comment by spike123456** [comment]
I have the same issue. It always show FirebaseError: no matching index found. Although i just created the index

**Comment by jmeinlschmidt** [comment]
Same here

**Comment by MattHeslington** [comment]
I'm experiencing it too. To check whether it was related to a particular project I span up a new project but had exactly the same issue. I have manually created Indexes but this doesn't resolve.

**Comment by Franco-Alejandro** [comment]
Same issue here.

**Comment by dhirb** [comment]
Is this related to https://github.com/firebase/firebase-js-sdk/issues/5152?

**Comment by silicakes** [comment]
This should be fixed with a backend deployment from yesterday.

**Comment by jailsondamasceno** [comment]
here too

**Comment by abeisgoat** [comment]
This is related to backend issues, no the emulator or SDKs, see https://github.com/firebase/firebase-js-sdk/issues/5152
