### ISSUE TITLE
Firestore Emulator has a fatal error when trying to start it up (code:  3221226505)

### ISSUE THREAD

**Issue by Carkzis** [firebase/firebase-tools#3587]
[REQUIRED] Environment info
firebase-tools: 9.16.0
Platform:      Windows 10
Node Version:  v14.17.3

[REQUIRED] Test case
I can sign in fine from the terminal, but after entering:

    firebase emulators: start

I get an error and the emulator fails to load.

[REQUIRED] Steps to reproduce

Same as above, have also tried with multiple projects and get the same result.

[REQUIRED] Expected behavior

I expect that the Firestore Emulator opens, rather than get an error as per below.

[REQUIRED] Actual behavior

I get this in the terminal:

    C:\Users\marcj\AndroidStudioProjects\friendlyeats-android-master>firebase emulators:start
    i  emulators: Starting emulators: auth, firestore
    i  firestore: Firestore Emulator logging to firestore-debug.log
    !  firestore: Fatal error occurred:
       Firestore Emulator has exited with code: 3221226505,
       stopping all running emulators
    i  firestore: Stopping Firestore Emulator
    !  firestore: Error stopping Firestore Emulator
    i  hub: Stopping emulator hub

In the firebase-debug log, I get this:

    [debug] [2021-07-18T19:35:06.197Z] ----------------------------------------------------------------------
    [debug] [2021-07-18T19:35:06.199Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\marcj\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js --debug emulators:start
    [debug] [2021-07-18T19:35:06.199Z] CLI Version:   9.16.0
    [debug] [2021-07-18T19:35:06.199Z] Platform:      win32
    [debug] [2021-07-18T19:35:06.199Z] Node Version:  v14.17.3
    [debug] [2021-07-18T19:35:06.200Z] Time:          Sun Jul 18 2021 20:35:06 GMT+0100 (British Summer Time)
    [debug] [2021-07-18T19:35:06.200Z] ----------------------------------------------------------------------
    [debug] 
    [debug] [2021-07-18T19:35:06.249Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
    [debug] [2021-07-18T19:35:06.250Z] > authorizing via signed-in user (marc.jowett@gmail.com)
    [info] i  emulators: Starting emulators: auth, firestore {"metadata":{"emulator":{"name":"hub"},"message":"Starting emulators: auth, firestore"}}
    [debug] [2021-07-18T19:35:06.268Z] [hub] writing locator at C:\Users\marcj\AppData\Local\Temp\hub-friendly-eats-37b97.json
    [debug] [2021-07-18T19:35:06.289Z] Ignoring unsupported arg: projectId {"metadata":{"emulator":{"name":"firestore"},"message":"Ignoring unsupported arg: projectId"}}
    [debug] [2021-07-18T19:35:06.289Z] Ignoring unsupported arg: auto_download {"metadata":{"emulator":{"name":"firestore"},"message":"Ignoring unsupported arg: auto_download"}}
    [debug] [2021-07-18T19:35:06.290Z] Starting Firestore Emulator with command {"binary":"java","args":["-Dgoogle.cloud_firestore.debug_log_level=FINE","-Duser.language=en","-jar","C:\\Users\\marcj\\.cache\\firebase\\emulators\\cloud-firestore-emulator-v1.13.1.jar","--host","localhost","--port",8080,"--rules","C:\\Users\\marcj\\AndroidStudioProjects\\friendlyeats-android-master\\firestore.rules"],"optionalArgs":["port","webchannel_port","host","rules","functions_emulator","seed_from_export"],"joinArgs":false} {"metadata":{"emulator":{"name":"firestore"},"message":"Starting Firestore Emulator with command {\"binary\":\"java\",\"args\":[\"-Dgoogle.cloud_firestore.debug_log_level=FINE\",\"-Duser.language=en\",\"-jar\",\"C:\\\\Users\\\\marcj\\\\.cache\\\\firebase\\\\emulators\\\\cloud-firestore-emulator-v1.13.1.jar\",\"--host\",\"localhost\",\"--port\",8080,\"--rules\",\"C:\\\\Users\\\\marcj\\\\AndroidStudioProjects\\\\friendlyeats-android-master\\\\firestore.rules\"],\"optionalArgs\":[\"port\",\"webchannel_port\",\"host\",\"rules\",\"functions_emulator\",\"seed_from_export\"],\"joinArgs\":false}"}}
    [info] i  firestore: Firestore Emulator logging to firestore-debug.log {"metadata":{"emulator":{"name":"firestore"},"message":"Firestore Emulator logging to \u001b[1mfirestore-debug.log\u001b[22m"}}
    [warn] !  firestore: Fatal error occurred: 
       Firestore Emulator has exited with code: 3221226505, 
       stopping all running emulators {"metadata":{"emulator":{"name":"firestore"},"message":"Fatal error occurred: \n   Firestore Emulator has exited with code: 3221226505, \n   stopping all running emulators"}}
    [info] i  firestore: Stopping Firestore Emulator {"metadata":{"emulator":{"name":"firestore"},"message":"Stopping Firestore Emulator"}}
    [debug] [2021-07-18T19:35:10.412Z] Firestore Emulator: Unable to terminate process (PID=14092) {"metadata":{"emulator":{"name":"firestore"},"message":"Firestore Emulator: Unable to terminate process (PID=14092)"}}
    [warn] !  firestore: Error stopping Firestore Emulator {"metadata":{"emulator":{"name":"firestore"},"message":"Error stopping Firestore Emulator"}}
    [info] i  hub: Stopping emulator hub {"metadata":{"emulator":{"name":"hub"},"message":"Stopping emulator hub"}}

Please let me know if there is any further information I can give you to help.

**Comment by yuchenshi** [comment]
Would you mind uploading firestore-debug.log as well? That log file may contain reasons behind the fatal error.

**Comment by Carkzis** [comment]
Unfortunately the firestore-debug.log is always blank.

**Comment by yuchenshi** [comment]
I'm afraid this hints at problems with the `java` command itself. Please try reinstalling JVM or another JVM implementation.

Note that you can also run `java C:\\Users\\YOUR_USERNAME\\.cache\\firebase\\emulators\\cloud-firestore-emulator-v1.13.1.jar` manually in a command-line and see what happens. Feel free to reopen if it works on the command-line but not through the CLI, and we can take a closer look together.
