### ISSUE TITLE
Unable to deploy, even when skipping with --only or --except

### ISSUE THREAD

**Issue by eliezedeck** [firebase/firebase-tools#360]
This bug is related to #308, but also has some additional behavioral bug on the CLI.

While my `database.rules.json` file certainly contains multi-line rules, and only the Web Console database supports this feature, I am aware that the CLI doesn't support this yet.

The problem that I think is a bug, is the fact that using commands such as the ones below, will still consider the `"database"` section of the `firebase.json`:

```
firebase deploy --except database # causes error
firebase deploy --only hosting    # causes error
```

**Excepted behavior:** it should skip scanning the database rules altogether, and continue deploying whatever that has not been skipped, according to the `--except` or `--only` parameters. The use of these parameters should already give a hint to the CLI tool that the developer knows what she is doing already.

That alone should get us closer to supporting multi-line rules. We, developers, can manually copy the rules to the Web Console until the CLI supports this (but we still need to keep a copy of the database rules in our Git repo). And while at it, I think the checks on the `database.rules.json` really should not stop the deployment; after all, the REST API will validate it again, and the CLI should just forward the error message instead of stopping. May be a warning and asking the developer if she is sure about the weirdly delicious JSON rules with multiple lines.

**Comment by eliezedeck** [comment]
For anyone using multi-line rules, this is the one-line command I use to get around this missing feature:

```bash
mv database.rules.json _database.rules.json; echo '{"rules": {".read": false, ".write": false}}' > database.rules.json; firebase deploy --except database && mv _database.rules.json database.rules.json
```

The CLI scans the database rule, but is also checks that it is containing a minimal set of rules.

**Comment by JasonGoemaat** [comment]
Just a thought - I think if you deployed database rules that would cause an error, they might still be sitting out there on firebase.  So when you try to deploy your project again it might try to use those faulty rules that are already out there on firebase and give you the error.  To test this can you move your bad rules file back and try deploying with "--except database" again and see if you still get an error since the last deployed rules were valid?

**Comment by eliezedeck** [comment]
@JasonGoemaat nope. All these was tested on a valid rule already deployed.

And if you have noticed, **you cannot deploy an invalid rules, ever!** Getting to a point where you have a running invalid rule is just impossible.

**Comment by bkendall** [comment]
Due to lack of activity, I'm going to close this issue. I think most of this has been resolved, but if it has not, please open a new bug with the appropriate details and we can tackle them. Thanks!
