### ISSUE TITLE
Firebase functions are not being deployed while they used to be deployed without any problem

### ISSUE THREAD

**Issue by jko12130** [firebase/firebase-tools#3605]
### [REQUIRED] Environment info

**firebase-tools:8.9.0**

**Platform:macOS Big Sur v11.4**

### [REQUIRED] Test case

package.json:
```
{
  "name": "functions",
  "description": "Cloud Functions for Firebase",
  "scripts": {
    "serve": "firebase serve --only functions",
    "shell": "firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "engines": {
    "node": "10"
  },
  "dependencies": {
    "body-parser": "^1.19.0",
    "child-process-promise": "^2.2.1",
    "express": "^4.17.1",
    "firebase-admin": "^9.11.0",
    "firebase-functions": "^3.14.1",
    "gm": "^1.23.1",
    "lodash": "^4.17.21",
    "mkdirp-promise": "^5.0.1",
    "node-forge": "^0.10.0",
    "sharp": "^0.26.1"
  },
  "devDependencies": {
    "firebase-functions-test": "^0.1.6",
    "tslint": "~5.8.0",
    "typescript": "^3.3.4000"
  },
  "private": true
}
```

### [REQUIRED] Steps to reproduce

Deploy a test function using package.json above

### [REQUIRED] Expected behavior

The functions used to be deployed without any problem the last time I tried, which is 2-3 days ago, and should continue to do so. 

### [REQUIRED] Actual behavior

I cannot deploy any of the functions. All of the functions throw the following errors:

_Function failed on loading user code. This is likely due to a bug in the user code. Error message: Error: please examine your function logs to see the error cause: https://cloud.google.com/functions/docs/monitoring/logging#viewing_logs. Additional troubleshooting documentation can be found at https://cloud.google.com/functions/docs/troubleshooting#logging. Please visit https://cloud.google.com/functions/docs/troubleshooting for in-depth troubleshooting documentation._

From Firebase console I see the following error messages:

_Provided module can't be loaded.
Did you list all required modules in the package.json dependencies?
Detailed stack trace: Error: Cannot find module 'typescript'_

The problem is I have all the necessary packages including Typscript installed.

**Comment by EricBatlle** [comment]
So I'm not the only one? :'(

**Comment by taeold** [comment]
I'm unable to reproduce the issue on my project after copying over the dependencies you've set 😢 .

The error message `Detailed stack trace: Error: Cannot find module 'typescript'` is a bit cryptic to me - I'm not sure why user code would depend on it. Is there something in your function code that might explain what's going on?

Also, it looks like you are using an older version of the CLI. Can you try giving another go with the latest version of the tool (`npm install -g firebase-tools`)?

**Comment by pmabres** [comment]
I can confirm that this breaks while using firebase as a local package doing:
npm install --save-dev firebase-tools
the installed version is at 8.20.0 while the install w/ the global package is at 9.16.0

For me, using the global package with the firebase command worked well. not happy with being installed as a local package.

**Comment by jthegedus** [comment]
>I can confirm that this breaks while using firebase as a local package doing:
>npm install --save-dev firebase-tools
>the installed version is at 8.20.0 while the install w/ the global package is at 9.16.0

This suggests that the versions `8.20.0` and `9.16.0` perform differently, not that local vs global has different behaviour. Can you compare `9.16.0` when installed locally vs globally?

**Comment by pmabres** [comment]
9.16.0 installed global and locally both work

**Comment by jko12130** [comment]
Hi, this works now. It was a really silly mistake. While writing a new function, VS Code was smart enough to somehow automatically import the following module at the top:

const { isExpressionWithTypeArguments } = require('typescript');

Which led to all the errors. Silly mistake. Killed it dead, installed the new version globally, everything's fine. Thanks for helping out though!

**Comment by pmabres** [comment]
Even though the creator of the issue might have had a different issue, the versioning problem might still be there.
The only feedback I can provide while I was trying to deploy on GCP are the deployment logs from cloud build.


2021-07-26T05:06:43.259311458Z bad CRC f7974029 (should be 00000000)
2021-07-26T05:06:43.402991199Z ERROR: error fetching storage source: generic::unknown: retry budget exhausted (3 attempts): fetching gcs source: unpacking source from gcs: source fetch container exited with non-zero status: 2

It might be unrelated though.

**Comment by taeold** [comment]
@pmabres The `bad CRC` error message reminds me of github.com/firebase/firebase-tools/issues/3120.

It does sound like a new issue unrelated to this issue. Let us know by opening up a new issue (hopefully w/ steps to reproduce your error).
