### ISSUE TITLE
Firebase target fails to deploy

### ISSUE THREAD

**Issue by madeInLagny** [firebase/firebase-tools#3617]
**The issue:** 
I have a web project hosted on Firebase that deploys fine. I want to add a new site to the same project. Firebase fails to deploy went target is set.

**Steps to reproduce**

- Update Firebase CLI to 9.16.0
- Create new site on Firebase hosting console. Name: autoscrib-testv2
- Run firebase target:apply hosting test autoscrib-testv2
- .firebaserc gets updated to:

```
{
  "projects": {
    "default": "autoscrib"
  },
  "targets": {
    "autoscrib": {
      "hosting": {
        "test": [
          "autoscrib-testv2"
        ]
      }
    }
  }
}

```

- Update firebase.json to
```

 {
      "database": {
        "rules": "database.rules.json"
      },
      "hosting": {
        "target":"test",
        "public": "dist",
        "ignore": ["firebase.json", "**/.*", "**/node_modules/**"],
        "rewrites": [
          {
            "source": "**",
            "destination": "/index.html"
          }
        ],
        "headers": [
          {
            "source": "/sw.js",
            "headers": [
              {
                "key": "Cache-Control",
                "value": "no-cache"
              }
            ]
          }
        ]
      },
      "storage": {
        "rules": "storage.rules"
      }
    }

```
**Deploy Emulator works fine**

- Run firebase emulators:start --only hosting:test
- website deploys on localhost:5000
- 
**Error Message** 

- Run firebase deploy --only hosting:test
- Process stops while uploading files and show:
- 

`Task 38b07412931a6e5cf159943f5f46b65148978924d7f49bab13392fafd8b168d8 failed: retries exhausted after 6 attempts, with error: The "path" argument must be of type string. Received undefined
`

**Website deploys OK if no target is created**

**Comment by madeInLagny** [comment]
Problem was solved by running firebase init. Issue was generated by cli update.

**Comment by sabetAI** [comment]
I'm still having this issue after re-initializing with CLI version 9.20.0. Should I downgrade?
