### ISSUE TITLE
Unhandled error cleaning up build images after functions deployment

### ISSUE THREAD

**Issue by AgungLaksana** [firebase/firebase-tools#3627]
I often get error (or warning?) after deploying firebase cloud functions. the functions is deployed successfully but I very often (around 85%) I get this error 

> cleaning up build files...
> ⚠  functions: Unhandled error cleaning up build images. This could result in a small monthly bill if not corrected. You can attempt to delete these images by redeploying or you can delete them manually at https://console.cloud.google.com/gcr/images/xxxxxx/asia/gcf

is this error is caused by my code?

### [REQUIRED] Environment info

I use the latest version of firebase tools: 9.16.0
Node JS 14
and in MacOS
firebase-functions: "^3.14.1"

### [REQUIRED] Steps to reproduce

I deploy the functions using `firebase deploy` then that error/warning occured

### [REQUIRED] Expected behavior

I have no error after deployment.

**Comment by manwithsteelnerves** [comment]
@AgungLaksana Do you still see this issue? I'm facing every-time I deploy. No code errors but just deployment alone.

**Comment by AgungLaksana** [comment]
@manwithsteelnerves yes, every time I run `firebase deploy` then the error will appear, but whenever I deploy only one function, i.e `firebase deploy --only functions:func1` I seldom to see the error

**Comment by manwithsteelnerves** [comment]
I noticed that there are yellow ! marks in the cloud functions console and after deleting that it worked fine.

**Comment by AgungLaksana** [comment]
@manwithsteelnerves yellow ! marks? I can't find it in the console. could you please show me the location? :)

**Comment by manwithsteelnerves** [comment]
Open console.cloud.google.com and search for functions once you select your project.

**Comment by AgungLaksana** [comment]
I think I no longer see this error after updating to latest firebase tools. just update it using `npm install -g firebase-tools `
