### ISSUE TITLE
`serve --only functions` will not serve sub-module functions 

### ISSUE THREAD

**Issue by evaneus** [firebase/firebase-tools#363]
in my index.js i require a submodule.

extractTriggers.js creates `trigger.entryPoint` as `myModule.submodule` on the returned triggers.

in cloud-functions-emulator, controller.js `_createArchive (name, opts)` throws an error at line 144:

```javascript
        if (!exportedKeys.includes(opts.entryPoint) && !exportedKeys.includes(name)) {
          throw new Error(`Node.js module defined by file index.js is expected to export function named ${opts.entryPoint || name}`);
        }
```

`opts.entryPoint` is undefined because it was never passed in at `functions.js` line 107.

but even if I do pass it in there it still fails because `opts.entryPoint` is `myModule.submodule`

and `exportedKeys` only contains `['myModule']`

**Comment by evaneus** [comment]
This reproduces the issue.

firebase --version
3.9.1

tried with node 6.9.1 and 7.10

[issue-363.zip](https://github.com/firebase/firebase-tools/files/1052609/issue-363.zip)

**Comment by GabrielRivera21** [comment]
Instead of `exports.api` in your `sub.js` file, try `module.exports`

*index.js*
```javascript
const functions = require('firebase-functions');
const admin = require('firebase-admin');

admin.initializeApp(functions.config().firebase)

exports.helloWorld = functions.https.onRequest((req, res) => {
  res.send('hello world')
});

exports.sub = require('./sub')
```
*sub.js*
```javascript
const functions = require('firebase-functions');
const express = require('express');

const app = express();

app.get('/test', (req, res) => {
    res.send('hello sub world');
});

module.exports = functions.https.onRequest(app);
```

**Comment by evaneus** [comment]
Hi @GabrielRivera21 , thanks - it hadn't occurred to me to try that but it does work.

I guess issue remains that the docs as described here apparently would not work:
https://firebase.google.com/docs/cli/#partial_deploys

**Comment by GabrielRivera21** [comment]
@evaneus seems like there is some mistake somewhere. For now, make sure to add a "functions:" prefix on the function name if you're trying to deploy multiple functions, e.g:
```
firebase deploy --only functions:function1,functions:function2
```
instead of the way the docs are saying which is:
```
firebase deploy --only functions:function1,function2
```

**Comment by laurenzlong** [comment]
Hey @evaneus we do have a mistake in our docs which we are fixing. Gabriel's syntax is the correct one. I'm closing this issue now since a fix has been provided.
