### ISSUE TITLE
Firebase Auth emulator fails when trying to login from Facebook access token

### ISSUE THREAD

**Issue by Frank-D** [firebase/firebase-tools#3632]
### [REQUIRED] Environment info

**firebase-tools: 9.16.0**
**firebase sdk 8.3.0**
**Flutter (Channel stable, 2.2.3, on macOS 11.4**
**Dev Platform: macOS / VS Code**
**Target Platforms: iOS & Android**

### [REQUIRED] Steps to reproduce

1. From either iOS or Android local running flutter app (simulator/emulator), sign in against 'Facebook Login' Provider, and obtain in response the "facebook access token", which represents a valid/successful facebook user valid session.
2. Build facebook credentials obj using received facebook access token.
3. Try now to login user against firebase auth emulator: firebaseAuth.signInWithCredential(facebookAuthCredential)

### [REQUIRED] Expected behavior

Firebase auth emulator supports sign in new user from facebook credentials.

### [REQUIRED] Actual behavior

Steps 1 and 2 are successful. Step 3 is failing.
When trying to sign in user in firebase emulator auth, with facebook credentials/access token (firebaseAuth.signInWithCredential(facebookAuthCredential)), I obtain the below error message:
> "The Auth Emulator does not support facebook.com sign-in with credentials."

(ref.: https://stackoverflow.com/questions/68453137/facebook-auth-emulator-for-firebase-authentication/68630213#68630213)

**Comment by yuchenshi** [comment]
Hi there, as mentioned on the StackOverflow answer, this isn't supported due to technical limitations. More details at https://firebase.google.com/docs/emulator-suite/connect_auth#testing_idp_flows_with_manual_credential_retrieval
