### ISSUE TITLE
npx firebase init  "Detected a .git folder" behavior

### ISSUE THREAD

**Issue by leblancmeneses** [firebase/firebase-tools#3633]
### [REQUIRED] Environment info

**firebase-tools:** 9.16.0
**Platform:** Ubuntu

### [REQUIRED] Test case
git clone from-bitbucket
npm install --save firebase-tools
npx firebase init

### [REQUIRED] Expected behavior

Have the ability to disable the "Hosting:github Setup" prompt and continue with firebase init process without having to delete my .git folder.

### [REQUIRED] Actual behavior

because my folder has a .git folder I don't get a prompt to disable the following obtrusive prompt.  I'm not even using github for this project.

=== Hosting:github Setup

i  Detected a .git folder at /home/leblanc/repos/bitbucket/indiv_xxxxx
i  Authorizing with GitHub to upload your service account to a GitHub repository's secrets store.

Visit this URL on this device to log in:
https://github.com/login/oauth/authorize?client_id=89cf50xxxxx3484&state=140xxx68&redirect_uri=http%3A%2F%2Flocalhost%3A9005&scope=read%3Auser%20repo%20public_repo

Waiting for authentication...

after deleting the .git folder I still get this prompt.

**Comment by jhuleatt** [comment]
@leblancmeneses this is the CLI trying to [set up a Github Action](https://firebase.google.com/docs/hosting/github-integration#set-up). It should only happen when you answer "yes" to the prompt `Set up automatic builds and deploys with GitHub?` 

Is it happening even when you say no to that prompt?

**Comment by leblancmeneses** [comment]
After trying again with firebase-tools@9.16.0 I am noticing two options for hosting instead of one:

Hosting: Configure files for Firebase Hosting and (optionally) set up GitHub 
Action deploys

Hosting: Set up GitHub Action deploys

Must have been a user error when I did this on Aug 4.   Using "Hosting: Configure files for Firebase Hosting and (optionally) set up GitHub Action deploys" is working correctly.
