### ISSUE TITLE
[Firestore Emulator] Unable to add a "timestamp" field

### ISSUE THREAD

**Issue by ozgurg** [firebase/firebase-tools#3654]
### [REQUIRED] Environment info

**firebase-tools:** v9.16.0

**Platform:** macOS v11.5.1

### [REQUIRED] Test case

When I want to add a "timestamp" field, it seem to be added but when I refresh the emulator page, the added field is gone. Only occurs when add a field to existing document, not while creating a document.

### [REQUIRED] Steps to reproduce

https://user-images.githubusercontent.com/6717356/128784716-d0486b80-5030-409f-80ba-51a3d7c13a60.mov

### [REQUIRED] Expected behavior

"timestamp" field added.

### [REQUIRED] Actual behavior

Unable to add a "timestamp" field.
(Nothing logged to *.log files when this happen)

**Comment by sceee** [comment]
I think this duplicates #3649

**Comment by yuchenshi** [comment]
Fixed in v9.16.5
