### ISSUE TITLE
firebase deploy --only functions command not working

### ISSUE THREAD

**Issue by dinukasaminda** [firebase/firebase-tools#3667]
firebase deploy --only functions command not working on firebase-tools@9.16.2 but its working on firebase-tools@9.16.0,

on firebase-tools@9.16.2 getting error :

Error: Missing expected firebase config value databaseURL, config is actually{"firebase":{"projectId":"xxx","databaseURL":"xxx","storageBucket":"xxx","locationId":"xxx"}}
 If you are unit testing, please set process.env.FIREBASE_CONFIG

![Untitled](https://user-images.githubusercontent.com/16361266/129142651-ae1726d8-626c-40ae-b57f-7c3a04e5047f.jpg)

**Comment by b-smets** [comment]
We are experiencing the same issue using the latest version of `firebase-tools`.

**Comment by sagarsoni7** [comment]
+1 
This broke our Github action

**Comment by nilsreichardt** [comment]
Going back to `9.16.0` is a working workaround for me:
```sh
npm i -g firebase-tools@9.16.0
```

**Comment by iiAtlas** [comment]
+1 ! Reverted to `9.16.0` and deployed without issue.

**Comment by schlomo** [comment]
Same problem also with regular deployments. `9.16.0` creates a `FIREBASE_CONFIG` with content like this:

```json
{
    "firebase": {
        "projectId": "<PROJECT>",
        "databaseURL": "https://<PROJECT>.firebaseio.com",
        "storageBucket": "<PROJECT>.appspot.com",
        "locationId": "europe-west"
    }
}
```

which does not work because the firebase SDK expects a different format as explained in https://firebase.google.com/docs/functions/config-env#automatically_populated_environment_variables

version `9.16.0` creates a correct `FIREBASE_CONFIG`:

```json
{
    "projectId": "<PROJECT>",
    "databaseURL": "https://<PROJECT>.firebaseio.com",
    "storageBucket": "<PROJECT>.appspot.com",
    "locationId": "europe-west"
}
```

**Comment by mbleigh** [comment]
Hi folks, sorry to see the trouble the new releases of `firebase-functions` and `firebase-tools` are causing.

We are working to quickly bring out a new release that fixes the issues you're experiencing, but until then we recommend reverting to `firebase-functions@3.14.1` and `firebase-tools@9.16.0`. Stay tuned!

**Comment by inlined** [comment]
We've released a new version of `firebase-tools` which fixes this issue. There was also a version of the `firebase-functions` SDK that could cause troubles with the emulator, but 3.15.2 should fix this too.
