### ISSUE TITLE
Auth Emulator does not work in v9.16.1, v9.16.2 or v9.16.3 because auth_time is null when token is generated

### ISSUE THREAD

**Issue by lovelle-cardoso** [firebase/firebase-tools#3673]
The auth emulator seems to always generate a token where auth_time is null. This causes the auth emulator to throw "auth/internal-error" when calling getIdTokenResult.

This is most likely the bug causing https://github.com/firebase/firebase-tools/issues/3671 and https://github.com/firebase/firebase-tools/issues/3663

### [REQUIRED] Environment info

firebase-tools: 9.16.1, 9.16.2, 9.16.3

Platform: Windows

### [REQUIRED] Test case

Try calling getIdTokenResult in a client app that is connected to the latest version of firebase-tools's auth emulator. Notice the error that is thrown.

### [REQUIRED] Steps to reproduce

1. Run `npm run serve` using firebase-tools 9.16.3
2. Run a client application that connects to the firebase auth emulator
3. Signup a new user
4. Call getIdTokenResult on that new user

### [REQUIRED] Expected behavior

You are able to decode the user's token and retrieve their claims.

### [REQUIRED] Actual behavior

"auth/internal-error" is thrown

---

If you breakpoint the line of code where "auth/internal-error" is thrown, you'll see that the error is thrown because auth_time is null in the decoded token.

@yuchenshi This bug may possibly have something to do with the PR I submitted a few weeks ago. Perhaps lastLoginAt is undefined?

https://github.com/firebase/firebase-tools/pull/3611

If so, perhaps try changing these lines of code

https://github.com/firebase/firebase-tools/blob/8e8043b434d3489125805e866a73d6f4bfeaab65/src/emulator/auth/operations.ts#L1729-L1734

to

```
    auth_time:
      user.lastLoginAt != null && user.lastLoginAt != undefined
        ? toUnixTimestamp(new Date(user.lastLoginAt))
        : user.lastRefreshAt != null && user.lastRefreshAt != undefined
        ? toUnixTimestamp(new Date(user.lastRefreshAt))
        : toUnixTimestamp(new Date()),
```

**Comment by yuchenshi** [comment]
Thanks for pinning down #3611 as the cause. The fix though was a bit more involved. See #3674.

**Comment by lovelle-cardoso** [comment]
@yuchenshi Apologies for making more work for you! Great job on the fast fix!
