### ISSUE TITLE
firebase: database-push Syntax unclear

### ISSUE THREAD

**Issue by kmuthukrishnan** [firebase/firebase-tools#368]
Hi, Iam trying to push using 

`firebase database:push \country -d {"country1" : "Armenia"}`

It is giving me an error as follows: 
Error: HTTP Error: 400, Invalid data; couldn't parse JSON object, array, or value.

What am I doing wrong? Please help.

**Comment by laurenzlong** [comment]
You need to do: firebase database:push \country -d '{"country1" : "Armenia"}'

**Comment by stwilberth** [comment]
firebase database:push /country -d file.json   ??

**Comment by daverinnadesan** [comment]
I am also having the problem. The suggested solutions don't work. Has anyone found a solution yet?

**Comment by kmuthukrishnan** [comment]
Yes, place the Json objects in  individual quotes ' '

**Comment by daverinnadesan** [comment]
I tried that but am still unsuccessful.

Here is my command:
=> firebase database:push /country -d '{"country1" : "Armenia"}'
This results in 
=> Error: HTTP Error: 400, Invalid data; couldn't parse JSON object, array, or value.

I am running cli version 3.9.1

**Comment by kmuthukrishnan** [comment]
I used database.set. You could try that.

**Comment by laurenzlong** [comment]
hey @daverinnadesan , are you running windows? If so, you may need to do:
firebase database:push /country -d "{\"country1\" : \"Armenia\"}"

It's probably an issue with what windows views as an appropriate representation of JSON on the command line. See https://stackoverflow.com/questions/28648473/windows-curl-with-json-data-on-the-command-line

**Comment by daverinnadesan** [comment]
Hi @laurenzlong, Thank you for your help. That was indeed the problem.

**Comment by MuhammadUsman786786** [comment]
I was working on windows:
and @laurenzlong answer works for me.

`firebase database:push /country -d "{\"country1\" : \"Armenia\"}"`
