### ISSUE TITLE
Improve `withFunctionTriggersDisabled` error message when Cloud Functions emulator is not running

### ISSUE THREAD

**Issue by gustavopch** [firebase/firebase-tools#3686]
### Related issues

None.

### [REQUIRED] Version info

**node:** 12.22.3

**firebase-functions:** 3.14.1

**firebase-tools:** 9.16.0

**firebase-admin:** 9.10.0

### [REQUIRED] Test case

Not sure what to write here.

### [REQUIRED] Steps to reproduce

Use `withFunctionTriggersDisabled` to run something while the Cloud Functions emulator is not running (for example, because you mistakenly started the emulator suite with `--only firestore` instead of `--only firestore,functions`).

### [REQUIRED] Expected behavior

A specific error message saying that the emulator could not be reached or something like that, .e.g: `Ensure the Cloud Functions emulator is running`.

### [REQUIRED] Actual behavior

A generic and misleading error message saying `HTTP Error 400 when disabling functions triggers, are you using firebase-tools 8.13.0 or higher?`.

### Were you able to successfully deploy your functions?

I'm not deploying, just testing locally.

**Comment by i14h** [comment]
@abeisgoat can you take a look into this?

**Comment by tonyjhuang** [comment]
Reassigning to @joehan as I believe this was mistakenly tagged as a Storage emulator issue whereas it seems to apply to the Functions emulator.

**Comment by taeold** [comment]
Filing the issue in firebase-js-sdk where `withFunctionTriggersDisabled` is implemented instead.
