### ISSUE TITLE
Project selection during firebase init is not working on Node v8.1.0

### ISSUE THREAD

**Issue by laurenzlong** [firebase/firebase-tools#370]
Arrow keys do not move up and down in the project list as expected. Problem goes away when I downgrade Node to v7.

**Comment by laurenzlong** [comment]
It is caused by this issue: https://github.com/SBoudrias/Inquirer.js/issues/547, which is most likely cause by a regression in Node 8.1.0 which will get fixed in the next release. For now, please use a Node version below v8.

**Comment by mbleigh** [comment]
Can anyone who's seen this try with just-released Node v8.1.1?

**Comment by ChargerIIC** [comment]
Had this problem but resolved it by updating to v8.1.2

**Comment by laurenzlong** [comment]
Great thanks for the update!
