### ISSUE TITLE
Can't deploy to european region with organisation policy

### ISSUE THREAD

**Issue by LukasCornille** [firebase/firebase-tools#3709]
### [REQUIRED] Environment info

**firebase-tools:** 9.16.6

**Platform:** macOS

### [REQUIRED] Test case

Any test project works for this case I believe, as long as the organisation policies are set to only deploy to any EU location.

I have this function:
```ts
import * as functions from 'firebase-functions';
import sendToMailUp from './services/mailup';

// Empty interface because it's irrelevant for this example
interface User {}

const addUserToMailup = functions
  .region('europe-west1')
  .database.ref('/users')
  .onCreate(async ({ val }) => {
    const user = val() as User;

    return sendToMailUp(user);
  });

export default addUserToMailup;
```

which then gets import in the index.ts file as so:

```ts
import admin from 'firebase-admin';
import addUserToMailup from './addNewUserToMailup';

admin.initializeApp();

exports.addUserToMailup = addUserToMailup;
```

### [REQUIRED] Steps to reproduce

I've ran this with:

```console
firebase deploy --only functions

firebase deploy --only functions:addUserToMailup
```

### [REQUIRED] Expected behavior

I would expect this function to be deployed on the europe-west1 region

### [REQUIRED] Actual behavior

As you can see from the debug log, when trying to receive the location it will try to upload the function on the us-central1 region, which is not allowed by a policy from the company I am working for.

[firebase-debug.log](https://github.com/firebase/firebase-tools/files/7059799/firebase-debug.log)

**Comment by joehan** [comment]
Hi @LukasCornille - you can control which region your function code is uploaded to by setting the `FIREBASE_FUNCTIONS_UPLOAD_REGION` environment variable. From your terminal/.bash_profile, run:
```
export FIREBASE_FUNCTIONS_UPLOAD_REGION = eu-west4 
## or any other region that works for you
```

@inlined has also been talking about changing this to always use one of the regions you're deploying your functions to, so adding him for visibility.

**Comment by inlined** [comment]
This might be a good action item for CLI version 10. Will add it to our internal tracker for breaking changes.
