### ISSUE TITLE
Web V9

### ISSUE THREAD

**Issue by RaheutRahwana** [firebase/firebase-tools#3711]
### [REQUIRED] Environment info

**firebase-tools:**
v9.16.6

**Platform:**
Fedora 34
### [REQUIRED] Test case

Open http://localhost:5000/ on browser.

### [REQUIRED] Steps to reproduce

```
firebase init
firebase serve
```
and open http://localhost:5000/ on browser.

### [REQUIRED] Expected behavior

Everything works as it did on version 8

### [REQUIRED] Actual behavior

There are some errors like:
```
Uncaught SyntaxError: Unexpected token 'export' firebase-app.js:1590
Uncaught SyntaxError: Cannot use import statement outside a module firebase-auth.js:1
Uncaught Error: hosting/init-error: Firebase SDK not detected. You must include it before /__/firebase/init.js init.js:1
```

**Comment by davideast** [comment]
If you want to continue using Firebase off the window you'll need to either continue to use version 8 (not recommended) or upgrade to [version 9 compat](https://firebase.google.com/docs/web/modular-upgrade#window-compat).

## Using compat
```html
  <script src="/__/firebase/9.0.0/firebase-app-compat.js"></script>
  <script src="/__/firebase/9.0.0/firebase-auth-compat.js"></script>
  <script src="/__/firebase/9.0.0/firebase-firestore-compat.js"></script>
  <script src="/__/firebase/init.js"></script>
<script>
   const firebaseApp = firebase.initializeApp({ /* Firebase config */ });
   const db = firebaseApp.firestore();
   const auth = firebaseApp.auth();
</script>
```

## Our recommendation
We are recommending using the module based v9 API with a module bundler like webpack or rollup going forward. The v9 SDK is optimized for tree shaking which strips out unused library code and therefore reduces the amount of Firebase code included in your site.

### Resources for upgrading
- [New getting started workflow](https://firebase.google.com/docs/web/setup)
- [Upgrade guide](https://firebase.google.com/docs/web/modular-upgrade)
- [Module bundling guide](https://firebase.google.com/docs/web/module-bundling)
- [Getting started video](https://www.youtube.com/watch?v=rQvOAnNvcNQ)
