### ISSUE TITLE
Why do we need to install firebase tools a global npm install process???

### ISSUE THREAD

**Issue by blachawk** [firebase/firebase-tools#3723]
Why does all firebase documentation require that firebase tools and CLI installs at a global level???
```
npm install -g firebase-tools
```

what is wrong with taking a non-global approach, such as...
```
npm install firebase-tools -D
```

**Comment by akauppi** [comment]
Likely the authors' idea has been to reduce duplication of bytes, but if you only work on 1 or 2 projects, nothing prevents you from installing `firebase-tools` locally, as you suggest. 

If you do, `npx firebase` or `npx firebase-tools` are good ways to use the commands, from the terminal.

I have some understanding to documentation writers. You have to balance between clarity and options; listing all possible variations is simply confusing. And then copy-paste gravity leads to one way being shown more than the rest..

**Comment by abeisgoat** [comment]
Yeah basically what @akauppi said, personally I recommend installing locally into a project dir if you need to pin CLI versions, but other than that globally is generally fine.
