### ISSUE TITLE
Is it not possible to import production auth users with email+pw credentials into the emulator?

### ISSUE THREAD

**Issue by fabyeah** [firebase/firebase-tools#3750]
### [REQUIRED] Environment info

**firebase-tools: 9.10.2**
**Platform: macOS**

### [REQUIRED] Test case

See the reproduction procedure below.

### [REQUIRED] Steps to reproduce

1. export data from emulator
2. export production users: `firebase auth:export accounts.json`
3. replace emulator export `accounts.json` with production exported `accounts.json`
4. start emulator and import data
5. try to log in with email and password of a production user in the emulator

### [REQUIRED] Expected behavior

can log in with email + password production credentials locally in emulator

### [REQUIRED] Actual behavior

cannot log in with email + password production credentials locally in emulator

### Notes

I found this, saying it isn't possible: https://stackoverflow.com/questions/67739169/how-to-import-exported-auth-data-into-firebase-emulators

But the user accounts do show up in the auth emulator. Only problem are the passwords. I tried to modify the `config.json` which is created from the emulator export, by adding a `hashConfig` object with the "Password hash parameters" values from the Firebase Authentication web UI. 

As described here:

https://cloud.google.com/identity-platform/docs/reference/rest/v2/Config?hl=de
https://cloud.google.com/identity-platform/docs/reference/rest/v2/projects.tenants?hl=de#HashConfig

But to no avail. Shouldn't this work? Or is this functionality still missing from the emulator?

Also the hash options described here: https://firebase.google.com/docs/cli/auth?hl=el#authimport seem to be only for `firebase auth:import`, but don't work with `firebase emulators:start --import ...`.

**Comment by yuchenshi** [comment]
The Auth Emulator is not secure and doesn't support real hashing and won't be able to access your production hash parameters, even if you try to manually add them to `config.json`.

Would you mind sharing a bit more about your use case here? Why would you like to use real production passwords in Auth Emulator? Would it be useful if the Auth Emulator were to assign a fake password (e.g. `foobar`) to those imported accounts?

**Comment by fabyeah** [comment]
@yuchenshi Thanks for clearing that up. Initially I wanted to test my backup process to make sure I can properly recreate the production env from backed up firestore and auth data. As I have no additional dev env besides production, I wanted to do this locally in the emulator.

Besides that, I also have code that accesses and modifies user auth (for example disabling accounts), so I'd like the auth data locally, for testing with real data. But I don't need actual passwords for that.

I guess as it is currently and with the option to assign a new single password to all accounts (and thereby changing/adding login provider to email??), it is fine. Or even better, as it also allows me to log in as a user, when debugging user reported problems. Is the password setting feature on the roadmap? Guess until that is available one would have to do this in an additional script step.

**Comment by yuchenshi** [comment]
> Is the password setting feature on the roadmap?
This is internally tracked as b/178114542. While we cannot promise timelines, your input helps us prioritize. Thanks!

> as it also allows me to log in as a user, when debugging user reported problems.

This is already possible today with one single JS SDK call: `auth.signInWithCustomToken('{"uid": "THE_USER_ID_YOU_WANT_TO_SIGN_IN_AS"}')` (or its v9 equivalent). The trick is that the Auth Emulator [allows plain JSON strings as custom tokens](https://github.com/firebase/firebase-tools/blob/b9516920edd8cab90d4c2f47ee800e25e3643892/src/emulator/auth/operations.ts#L1212-L1215). We haven't found a good way to document this though, so give it a try and please let us know what you think!

This custom token technique is equally valid in production, except that you'd have to [create a real signed token](https://firebase.google.com/docs/auth/admin/create-custom-tokens) using the Admin SDK. However, many developers still find it valuable as it gives you full access to production resources, arguably closer to what users are experiencing.
