### ISSUE TITLE
`login:use` not working after 9.17.0 update

### ISSUE THREAD

**Issue by ibobo** [firebase/firebase-tools#3759]
### [REQUIRED] Environment info

**firebase-tools:** 9.18.0 (or 9.17.0)

**Platform:** macOS

### [REQUIRED] Test case

Not applicable.

### [REQUIRED] Steps to reproduce

1. `cd` to a firebase project folder
2. login to an account with `firebase login` (if you have no account logged in)
3. add another login with `firebase login:add`
4. select the newly added account with `firebase login:use <email of second account>`

### [REQUIRED] Expected behavior

`login:list` should say something like this:

```
Logged in as <email of second account>

Other available accounts (switch with "firebase login:use")
 - <email of first account>
```

and also, other commands should use the second account (the one in the `login:use` call)

### [REQUIRED] Actual behavior

```
Logged in as <email of first account>

Other available accounts (switch with "firebase login:use")
 - <email of second account>
```

This works correctly in `9.16.6`, but fails on `9.17.0` and `9.18.0`.

**Comment by bkendall** [comment]
Hmm. I'm able to replicate this. I'll take a look to see what's going on.

**Comment by Abdelrahmanhassan1** [comment]
The solution for this is to use the new command

```
firebase login --reauth
```

this forces the cli to login again from the web
