### ISSUE TITLE
Firebase deploy ignores functions subfolders prepended with `.`

### ISSUE THREAD

**Issue by jthegedus** [firebase/firebase-tools#376]
When I download and extract the source of my deployed Firebase Cloud Functions from Google Cloud Storage, any folders I prepend with `.` are not found.

Is this the expected behaviour? And if so, can it be documented somewhere or have I just missed something in the docs

**Comment by sergeybekrin** [comment]
@jthegedus I believe this is related to #291

**Comment by laurenzlong** [comment]
Yep, you're right, the two are related. Thanks for reporting!

**Comment by jthegedus** [comment]
Thanks for the response. Apologies, I tried my best to find an existing Issue :sweat_smile:

**Comment by laurenzlong** [comment]
No problem! Just made PR for fix.
