### ISSUE TITLE
resource is null in storage rules for "delete" rule

### ISSUE THREAD

**Issue by bosycom** [firebase/firebase-tools#3760]
**firebase-tools:** version 9.18.0

**Platform:** Windows

### Test case
Trying to delete a file in local storage emulator by reading metadata off of ```resource``` value in ```allow delete``` rule, but get null value error instead

#### Step 1: Add rule to storage.rules
```javascript
rules_version = '2';
service firebase.storage {
    match /b/{bucket}/o {
        match /users/{media} {
            allow read: if true;
            allow delete: if resource.metadata.public == "false";
            allow create, update: if true;
        }
    }
}
```

#### Step 3: Set custom metadata on file 1.webp
```javascript
await updateMetadata(ref(storage, 'users/1.webp'), {customMetadata: {public: "false"}});
```

#### Step 4: Try to delete file
```javascript
await deleteObject(ref(storage, 'users/1.webp'));
```

### Expected behavior

1. ```resource``` in storage rule is not null, instead contains metadata of resource that is to be deleted
2. Storage rule allows to successfully delete file

[Official Firebase doc](https://firebase.google.com/docs/storage/security/rules-conditions#resource_evaluation) about Resource Evaluation mentions that "These [metadata] properties can be inspected on read or write requests to ensure data integrity". ```delete``` rule is part of write request, hence it should work.

### Actual behavior

Console logs error
```
com.google.firebase.rules.runtime.common.EvaluationException: Error: C:\code\pr-next\storage.rules line [6], column [30]. Null value error.
```

Storage file is not deleted. ```resource``` is null.

I tested it only locally with emulator not in production.

**Comment by ApoorvaJ** [comment]
I can attest that this also happens for write rules. I'm trying to disable overwrites using `allow create: if resource == null;`, and I can overwrite anyway on the emulator. This doesn't happen in the Rules playground in the firebase console, so it looks like an emulator bug.

**Comment by abeisgoat** [comment]
Thanks for the info, this is probably an issue in our security rules payloads. We've been working internally to document what happens in prod and replicate it, so I'll put this as an area of note.
