### ISSUE TITLE
firebase deploy clears function subscription settings for pubsub.onPublish

### ISSUE THREAD

**Issue by dreadjr** [firebase/firebase-tools#3762]
### [REQUIRED] Environment info

**firebase-tools:** 9.17.0

**Platform:** cloud build (linux) or osx

### [REQUIRED] Test case
```javascript
exports.policyTrue = functions
  .runWith({
    failurePolicy: true,
  })
  .pubsub.topic("retry-topic")
  .onPublish((msg, ctx) => {
    return true;
  });
```
### [REQUIRED] Steps to reproduce

# deploy functions
`firebase deploy --only functions`

# configure dead letter or backoff, via gcloud or ui
```bash
gcloud pubsub subscriptions create SUBSCRIPTION_ID --topic=TOPIC_ID --min-retry-delay=MIN_RETRY_DELAY --max retry-delay=MAX_RETRY_DELAY
...
```

# deploy functions again 
`firebase deploy --only functions --force`

### [REQUIRED] Expected behavior

Settings on the subscription that cannot be set via the `firebase deploy --force` command should not be reset. It shouldn't require extra setup after a deploy to setup these settings. Since if the function starts running it can potentially ~10 seconds for up to 7 days. But if you were able to setup dead-lettering it prevents this with the failurePolicy on.

### [REQUIRED] Actual behavior

Settings on the subscription are reset / not retained

**Comment by inlined** [comment]
The Firebase CLI doesn't make any API calls to Pub/Sub while deploy your function. This is happening inside the Google Cloud Functions API call. Will research the right way to route this function.

**Comment by inlined** [comment]
Internal bug #211769948

**Comment by Lyokone** [comment]
@inlined I don't have access to the internal bug. Has it been fixed? Thanks

**Comment by joehan** [comment]
Internal bug has been closed, closing this as well

**Comment by gugahoi** [comment]
What is the outcome of this? How can we configure dead letter queues in pubsub cloud functions through Firebase? Is there any documentation?
