### ISSUE TITLE
Issue installing firebase-tools

### ISSUE THREAD

**Issue by Fisch201** [firebase/firebase-tools#377]
node v6.11.0
npm v5.0.3 
resolveWithNewModule @google-cloud/functions-emulator@1.00.0-alpha.21 installable status
get Error unexpected end of file

**Comment by laurenzlong** [comment]
Hey @Fisch201 does the installation fail altogether? When you run "firebase --version" does anything show up?

**Comment by Fisch201** [comment]
Firebase is not recognized as an internal or external command, operable program or batch file

**Comment by Fisch201** [comment]
I am only having issues installing it on my windows 10 machine / no issues installing npm or node

**Comment by Fisch201** [comment]
So i went and saw there was an updated npm version - upgraded to v5.0.4  and then tried the Firebase install and this time it complted successfully -   closing issue

**Comment by sudhanvadp** [comment]
npm v5.5.1 &
node v9.3.0 still not working...

**Comment by laurenzlong** [comment]
@sudhanvadp can you file another issue with all of your logs?

**Comment by sudhanvadp** [comment]
Thanks for ur reply
@laurenzlong No it worked after completely removing the node n reinstalling the latest stable version (node v8.9.4)

**Comment by sateslayer** [comment]
I'm using 
npm 6.5.0-next.0
node v11.6.0

It gives the following errors:
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm ERR! path /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!  { [Error: EACCES: permission denied, access '/usr/local/lib/node_modules']
npm ERR!   stack:
npm ERR!    "Error: EACCES: permission denied, access '/usr/local/lib/node_modules'",
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

Please assist me in this issue or give me a workaround

**Comment by bkendall** [comment]
@sateslayer it looks like it's a permissions issue. Is node installed as a system package? you may have to `sudo npm install -g firebase-tools`.

If you're still having trouble, please open a new issue rather than commenting on an old one. Thanks.
