### ISSUE TITLE
Firestore emulator does not properly set nested properties using dot notation

### ISSUE THREAD

**Issue by jsakas** [firebase/firebase-tools#3770]
### [REQUIRED] Environment info

**firebase-tools:** 9.18.0

**Platform:** macOS

### [REQUIRED] Test case

Please see `nested-properties` branch of my testing repo here: https://github.com/jsakas/firebase-repro/tree/nested-properties

Note: after creating the repro I realized you can also just start the firestore emulator and use the JavaScript console in the emulator UI. But below is my test case I used when verifying the issue. 

### [REQUIRED] Steps to reproduce

```
    await database.collection('tests').doc('12345').set({ 
      'top.a': 3,
      'top.b': 4,
    })
    
    const data2 = await (await database.collection('tests').doc('12345').get()).data();

    assert.equal(data2?.top.a, 3);
    assert.equal(data2?.top.b, 4);
```

### [REQUIRED] Expected behavior

It should set the nested property and create the following data structure:

```
{
  top: {
    a: 3,
    b: 4,
  }
}
```

Related documentation for non-emulated environments: https://firebase.google.com/docs/firestore/manage-data/add-data?authuser=0#update_fields_in_nested_objects

### [REQUIRED] Actual behavior

It creates this data structure:

```
{
  'top.a': 3,
  'top.b': 4,
}
```

**Comment by riordanpawley** [comment]
@jsakas I think that behaviour is for .update()

**Comment by yuchenshi** [comment]
Hi all, according to the JS SDK reference, only [the `.update` method](https://firebase.google.com/docs/reference/js/v8/firebase.firestore.DocumentReference?authuser=0#update) support the dot notation. The reference for `set` mentions the argument should be a Partial (i.e. verbatim keys and values).
