### ISSUE TITLE
`firebase emulators:start --only hosting` does not start emulator-ui

### ISSUE THREAD

**Issue by ChromeQ** [firebase/firebase-tools#3781]
### [REQUIRED] Environment info

**firebase-tools:** 9.18.0

**Platform:** Ubuntu

### [REQUIRED] Steps to reproduce

React project builds to the `build` folder, run `firebase emulators:start --only hosting` 

### [REQUIRED] Expected behavior

Should run the emulator and be visible in the Emultor-UI

### [REQUIRED] Actual behavior

Does not run the Emulator-UI and displays the following warning:
```bash
⚠  emulators: The Emulator UI requires a project ID to start. Configure your default project with 'firebase use' or pass the --project flag.
```
The suggestions do not fix the problem, I have .firebaserc and even when setting `--project my-project-id` it does not work, nor with `GCLOUD_PROJECT=my-project-id` system variable

**Comment by ChromeQ** [comment]
This bug does not manifest when adding any other emulator to the only field eg. `--only hosting,firestore` or `--only hosting,functions`

I have delved into the code and found the message is emitted here:
https://github.com/firebase/firebase-tools/blob/6878ae8d31bd9f8c46f499d3c3d3c1ac69dc09a1/src/emulator/controller.ts#L681

It fails the `shouldStart` check defined here:
https://github.com/firebase/firebase-tools/blob/6878ae8d31bd9f8c46f499d3c3d3c1ac69dc09a1/src/emulator/controller.ts#L201

And the reason is because `EMULATORS_SUPPORTED_BY_UI` does not contain `hosting`:
https://github.com/firebase/firebase-tools/blob/6878ae8d31bd9f8c46f499d3c3d3c1ac69dc09a1/src/emulator/types.ts#L57


I think we should allow the `--ui` option which is available to `firebase emulators:exec --help`, this would be a simple fix to add this to emulators-start:25 - https://github.com/firebase/firebase-tools/blob/6878ae8d31bd9f8c46f499d3c3d3c1ac69dc09a1/src/commands/emulators-start.ts#L25
```ts
.option(commandUtils.FLAG_UI, commandUtils.DESC_UI)
```

**Comment by ChromeQ** [comment]
I've realised this fix is hurting my setup, where I have two separate commands, one for server = `firebase emulators:start --only auth,functions,firestore` and one for client side = `firebase emulators:start --only hosting`

With the only hosting it still runs fine as separate terminal commands, with my PR suggestion applied I end up with:
```
i  emulators: Starting emulators: hosting
⚠  hub: emulator hub unable to start on port 4400, starting on 4401 instead.
...
i  emulators: Shutting down emulators.
i  hosting: Stopping Hosting Emulator
i  hub: Stopping emulator hub
i  logging: Stopping Logging Emulator
⚠  ui: Port 4000 is not open on localhost, could not start Emulator UI.
⚠  ui: To select a different host/port, specify that host/port in a firebase.json config file:
```

This may be part of a much bigger problem with managing multiple emulator commands together in one UI, possibly not possible?

**Comment by realPhillight** [comment]
> ### [REQUIRED] Environment info
> **firebase-tools:** 9.18.0
> 
> **Platform:** Ubuntu
> 
> ### [REQUIRED] Steps to reproduce
> React project builds to the `build` folder, run `firebase emulators:start --only hosting`
> 
> ### [REQUIRED] Expected behavior
> Should run the emulator and be visible in the Emultor-UI
> 
> ### [REQUIRED] Actual behavior
> Does not run the Emulator-UI and displays the following warning:
> 
> ```shell
> ⚠  emulators: The Emulator UI requires a project ID to start. Configure your default project with 'firebase use' or pass the --project flag.
> ```
> 
> The suggestions do not fix the problem, I have .firebaserc and even when setting `--project my-project-id` it does not work, nor with `GCLOUD_PROJECT=my-project-id` system variable

Hi @ChromeQ ,
I have exactly the same issue.
Where you able to solve it?
Any ideas on how I can solve it?
Thanks,

**Comment by bkendall** [comment]
I'm sorry I'm only now coming back to this.

I believe this is working as intended, unfortunately. Hosting doesn't start the UI because it doesn't require the UI. If another feature is enabled (like Functions) the UI will start, but since the UI wouldn't be useful, it makes sense to not start it.

I'm going to defer decision ultimately to the emulators team, but I've also made a PR to have a better error message in this case.
