### ISSUE TITLE
Emulators start with --import fails whether storage_export/blobs or storage_export/metadata empty folders do not exist

### ISSUE THREAD

**Issue by charliejuc** [firebase/firebase-tools#3823]
**firebase-tools: 9.20.0**

 

**Platform: Pop OS**

### [REQUIRED] Test case and Steps to reproduce

```
firebase emulators:export storeExport
```

Then after upload to git  and download the code, empty folders are not uploaded to version control: storeExport/storage_export/blobs or storeExport/storage_export/metadata

Then when you run:

```
firebase emulators:start --import storeExport
```

Previous command will fail.

### [REQUIRED] Expected behavior

Emulator should not require empty folders to work.

### [REQUIRED] Actual behavior

Fails when the above mentioned folders do not exist.

**Comment by tonyjhuang** [comment]
This should be fixed by 33647

**Comment by rhodgkins** [comment]
I'm not sure that #3647 will fix this - the `metadata` and `blobs` directories will always be empty if there's nothing to export. Usually for stuff like this I'd add in an empty `.gitadd` file but not sure if that's really appropriate!

**Comment by tonyjhuang** [comment]
I see, my mistake. We can update the emulator to handle importing a directory structure with missing `metadata` and `blobs ` folders at some point in the future, thanks for raising the issue @charliejuc

**Comment by tonyjhuang** [comment]
Filed internal bug to track, b/240637117

**Comment by abhis3** [comment]
Fix is merged in, should be in the next emulator release. Closing issue.
