### ISSUE TITLE
firebase emulator ignores engines.node property for functions and emulator:exec

### ISSUE THREAD

**Issue by modosc** [firebase/firebase-tools#3824]
the firebase emulator seems to ignore engines.node property and always uses node 12. i think this has also been mentioned tangentially in these issues:

https://github.com/firebase/firebase-tools/issues/2791
https://github.com/firebase/firebase-tools/issues/3296
https://github.com/firebase/firebase-tools/issues/1489

### [REQUIRED] Environment info

**firebase-tools:** 9.19.0

**Platform:** macOS

### [REQUIRED] Test case

https://github.com/modosc/firebase-repro

### [REQUIRED] Steps to reproduce

clone the above repo and follow the instructions in the README. 

### [REQUIRED] Expected behavior

the version of node specified in the `engines.node` property of `package.json` should be used for functions and when running `emulator:exec`

### [REQUIRED] Actual behavior

node 12 is always used

**Comment by abeisgoat** [comment]
It uses whatever is installed on your machine! If you'd like you can change your npm version with `nvm`.

**Comment by modosc** [comment]
@abeisgoat can you pease double-check this is the case when you run my repro case? i do not have node 12 installed via `nvm` or anything else, it seems like it's coming from firebase-tools

**Comment by modosc** [comment]
also note that i'm not asking for node 12 in my config - firebase-tools are ignoring the version i request.

**Comment by deckchairlabs** [comment]
Yeah I'm also having this issue. There is definitely no other node version installed, I'm using a VSCode devcontainer "16-bullseye" and the only additional "global" package I'm installing is firebase-tools.

**Comment by lduivenbode** [comment]
@modosc @deckchairlabs I've had the same issue and just solved it by moving away from the standalone version of `firebase-tools` to the npm installed version. Not sure if this helps your scenario, but it appears the standalone version is shipped with Node v12.x which was causing my code with optional chaining to fail.

**Comment by modosc** [comment]
i worked around this by using cloud functions directly instead of via firebase. just disappointed that this was closed with very little comment after i spent the time to publish an example repo which demonstrates the problem.
