### ISSUE TITLE
using StorageReference causes emulators to fall over

### ISSUE THREAD

**Issue by danday74** [firebase/firebase-tools#3839]
OS: Windows 10
Node: 14.17.3
"firebase": "9.1.3"
"firebase-admin": "10.0.0"
"firebase-functions": "3.15.7"
java version "1.8.0_301"

NOTE: I do not need assistance (as explained herein), this is solely for the benefit of the firebase team.

The following code causes the emulators to fall over (see stack trace below):

```
const startRef: StorageReference = ref(storage, appConfig.video.inPath)

listAll(startRef).then((res: IStoragePrefixesAndItems) => {
  const folderPromises = res.prefixes.map((origFolderRef: StorageReference) => {
    const folderRef: StorageReference = ref(storage, origFolderRef.fullPath)
    // using origFolderRef causes emulators to crash
    return listAll(origFolderRef)
  })
  return Promise.all(folderPromises)
}).then( ... etc
```

However, in the above code IF I replace:

`return listAll(origFolderRef)`

WITH:

`return listAll(folderRef)`

THEN everything works fine

Stack trace (when emulators fall over) follows:

!  Unexpected rules runtime error: Exception in thread "main"
!  Unexpected rules runtime error: java.lang.IllegalArgumentException: Path segment cannot be empty
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:147)
        at com.google.firebase.rules.runtime.utils.PathUtils.parse(PathUtils.java:122)
        at com.google.firebase.rules.runtime.utils.PathUtils.parseRaw(PathUtils.java:106)
        at com.google.firebase.rules.tools.local.server.ServerActionVerify.toNewPathValue(ServerActionVerify.java:42)
        at com.google.firebase.rules.tools.local.server.ServerActionVerify.perform(ServerActionVerify.java:103)
        at com.google.firebase.rules.tools.local.server.Server.performActionFromLine(Server.java:79)
        at com.google.firebase.rules.tools.local.server.Server.handleRequest(Server.java:46)
        at com.google.firebase.rules.tools.local.server.Server.start(Server.java:36)
        at com.google.firebase.rules.tools.local.FirebaseRulesTooling.main(FirebaseRulesTooling.java:83)

Error: Storage Emulator Rules runtime exited unexpectedly.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vehicle-damage-inspector-cloud-functions@ start: `sh start.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vehicle-damage-inspector-cloud-functions@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2021-10-17T01_37_49_599Z-debug.log

For your reference, my full code follows:

```
import { initializeApp } from 'firebase/app'
import { connectStorageEmulator, getMetadata, getStorage, listAll, ref, StorageReference } from 'firebase/storage'
import { appConfig } from '../app-config'
import { IAppOptions } from './interfaces/i-app-options'
import { find } from 'lodash'
import axios from 'axios'
import { axiosAsyncAwait } from './utils/axios-utils'
import { IResponse } from './interfaces/i-response'
import { IStoragePrefixesAndItems } from './interfaces/i-storage-prefixes-and-items'
import firebase from 'firebase/compat'
import FullMetadata = firebase.storage.FullMetadata

const listVideos = (storage: any, resolve: (value: (string | PromiseLike<string>)) => void, reject: (reason?: any) => void) => {

  const startRef: StorageReference = ref(storage, appConfig.video.inPath)

  listAll(startRef).then((res: IStoragePrefixesAndItems) => {
    const folderPromises = res.prefixes.map((origFolderRef: StorageReference) => {
      const folderRef: StorageReference = ref(storage, origFolderRef.fullPath)
      // using origFolderRef causes emulators to crash
      return listAll(origFolderRef)
    })
    return Promise.all(folderPromises)
  }).then((folderReses: IStoragePrefixesAndItems[]) => {
    const metadataPromises: Promise<FullMetadata>[] = folderReses.reduce((acc: Promise<FullMetadata>[], folderRes: IStoragePrefixesAndItems) => {
      const itemRef: StorageReference = find(folderRes.items, (itemReff: StorageReference) => itemReff.name.endsWith(appConfig.video.rgbFilename))
      if (itemRef) {
        const metadataPromise: Promise<FullMetadata> = getMetadata(itemRef)
        return [...acc, metadataPromise]
      } else {
        return acc
      }
    }, [])
    return Promise.all(metadataPromises)
  }).then((metadatas: FullMetadata[]) => {
    console.log(metadatas)
    resolve('done')
  }).catch(err => {
    reject(err)
  })
}

export const app = async (options: IAppOptions): Promise<string> => {

  const emulatorFunctionsPort: number = appConfig.firebase.emulatorPorts.functions
  // noinspection HttpUrlsUsage
  const pingUrl = `http://${appConfig.domain}:${emulatorFunctionsPort}/${appConfig.firebase.defaultProject}/us-central1/ping`
  const ping: IResponse = await axiosAsyncAwait(axios.get(pingUrl))
  const areEmulatorsRunning: boolean = ping.success

  const firebaseApp: any = initializeApp(appConfig.firebase)
  const storage: any = getStorage(firebaseApp)

  if (options.emulate && areEmulatorsRunning) {
    console.info('using emulators')
    connectStorageEmulator(storage, appConfig.domain, appConfig.firebase.emulatorPorts.storage)
  } else {
    console.info('using real')
  }

  return new Promise<string>((resolve, reject) => {
    listVideos(storage, resolve, reject)
  })
}

```

**Comment by abeisgoat** [comment]
Thanks for this report, I'll take a look.

**Comment by tonyjhuang** [comment]
Filed internal bug to track, b/240637641

**Comment by Yuangwang** [comment]
Hi, thanks for the report! I took a look but couldn't quite reproduce the same behavior so its possible that this has been fixed in a recent patch as we've been fixing many other issues recently. 

I'm closing this for now, but please give it another try and see if it works now. If it still doesn't work please link your `storage.rules` file as well as what folder structure you're creating and I'd be happy to reopen this and take another look

**Comment by MichaelOdumosu57** [comment]
Greetings I am having the same issue if I make a http get call and there is something wrong with the path for the img Url
