### ISSUE TITLE
issuse

### ISSUE THREAD

**Issue by johnikutty** [firebase/firebase-tools#3849]
i  Firebase optionally collects CLI usage and error reporting information to help improve our products. Data is collected in accordance with Google's privacy policy
(https://policies.google.com/privacy) and is not used to identify you.

? Allow Firebase to collect CLI usage and error reporting information? No

Visit this URL on this device to log in:
https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=519798024&redirect_uri=http%3A%2F%2Flocalhost%3A9005

Waiting for authentication...

http://localhost:9005/?state=519798024&code=4/0AX4XfWjCPftVr4H4TIYJhvtoTmZK_n4r7CJajKJ0P5zSFqI6lMKZGMadY9fGQGGf3f3A9g&scope=email%20https://www.googleapis.com/auth/userinfo.email%20openid%20https://www.googleapis.com/auth/cloudplatformprojects.readonly%20https://www.googleapis.com/auth/firebase%20https://www.googleapis.com/auth/cloud-platform&authuser=0&prompt=consent

**Comment by abeisgoat** [comment]
Please follow the template.
