### ISSUE TITLE
 Does the Firebase CLI command for exporting all Firebase accounts somehow excludes Apple ID logins? 

### ISSUE THREAD

**Issue by jamarthomas** [firebase/firebase-tools#3852]
### [REQUIRED] Environment info
 Does the Firebase CLI command for exporting all Firebase accounts somehow excludes Apple ID logins?

**Comment by abeisgoat** [comment]
This should probably go to [Firebase Support](https://firebase.google.com/support) if this is happening they'll have details on why!
