### ISSUE TITLE
Can't open firebase-tools-instant-win on Windows 10

### ISSUE THREAD

**Issue by shlighter** [firebase/firebase-tools#3855]
It used to work fine but now when I open it, I see the shell window for a second, and then it's getting closed.
I tried to install a new version but got the same Issue.
I installed the latest node.js and disabled windows defender.
It might be related to https://github.com/firebase/firebase-tools/issues/1796 which is closed
Also- https://github.com/firebase/firebase-tools/issues/1888 , https://github.com/firebase/firebase-tools/issues/1826
Please answer soon as I have to update my cloud function and now I'm stuck without the Firebase Client

**Comment by shlighter** [comment]
OK I have a workaround- I deploy my functions with the command prompt.  But I'm not sure what happened to your .exe file

**Comment by bkendall** [comment]
Since this seems to have been resolved (and a quick check showed me that the instant version was working on windows), I'm going to mark this to be closed? If it should be kept open, let us know. Thanks!
