### ISSUE TITLE
Firebase serve:  Error: Server Error. connect ETIMEDOUT 216.58.200.234:443

### ISSUE THREAD

**Issue by Symbolk** [firebase/firebase-tools#386]
I am using Firebase CLI to develop a web app, and I have to use Shadowsocks as a proxy.

After luckily resolving the "Authentication error", finally I can assign project with "firebase use --add".

However, if I want to start a local server with "firebase serve", I got this error in my laptop:

C:\Users\Symbolk\Desktop\CrowdJigsawPuzzle>firebase serve
=== Serving from 'C:\Users\Symbolk\Desktop\CrowdJigsawPuzzle'...
Error: Server Error. connect ETIMEDOUT 216.58.200.234:443

But it works well in my PC, so I wonder how to resolve it.

**Comment by afzalarsalan** [comment]
Can also confirm above error, but to a different IP address, presumbly a closer server.

**Comment by mbleigh** [comment]
Duplicate of #155

**Comment by roshsoftco** [comment]
For me, this goes away by updating firebase tools and logging in again. Run
`npm install -g firebase-tools` then,
`firebase logout` then,
`firebase login`.

Now try deploying,
`firebase deploy`

**Comment by RidhikGovind** [comment]
> For me, this goes away by updating firebase tools and logging in again. Run
> `npm install -g firebase-tools` then,
> `firebase logout` then,
> `firebase login`.
> 
> Now try deploying,
> `firebase deploy`

Thanks a lot. This really worked for me ! :+1:

**Comment by AbhisekJS** [comment]
> For me, this goes away by updating firebase tools and logging in again. Run
> `npm install -g firebase-tools` then,
> `firebase logout` then,
> `firebase login`.
> 
> Now try deploying,
> `firebase deploy`

Thanks This Works

**Comment by Tarun-i-mac** [comment]
> For me, this goes away by updating firebase tools and logging in again. Run
> `npm install -g firebase-tools` then,
> `firebase logout` then,
> `firebase login`.
> 
> Now try deploying,
> `firebase deploy`



> For me, this goes away by updating firebase tools and logging in again. Run
> `npm install -g firebase-tools` then,
> `firebase logout` then,
> `firebase login`.
> 
> Now try deploying,
> `firebase deploy`

thanks a lot
