### ISSUE TITLE
CORS settings does not take effect in hosting emulator

### ISSUE THREAD

**Issue by qiansen1386** [firebase/firebase-tools#3860]
### [REQUIRED] Environment info

**firebase-tools:**
9.21.0

**Platform:**
Windows
### [REQUIRED] Test case
I am testing Flutter web project
that require whitelist a domain for some images

Here is the `fireabase.json` I use
```json
//...
  "hosting": {
    "public": "build/web",
    "ignore": ["firebase.json", "**/.*", "**/node_modules/**"],
    "headers": [
      {
        "source": "**/*.@(jpg|jpeg|gif|png)",
        "headers": [
          {
            "key": "Cache-Control",
            "value": "max-age=7200"
          },
          {
            "key": "Access-Control-Allow-Origin",
            "value": "https://www.somedomain.com/"
          }
        ]
      }
    ],
```
However it does not work, I tried `firebase serve --only hosting` & `fireabse emulators:start --only hosting`. Neither of them works.

### [REQUIRED] Steps to reproduce

Include a NetworkImage in your flutter app pointing to an 3rd party source

### [REQUIRED] Expected behavior

Include the Access-Control-Allow-Origin header in response, so we could see those pics without firing many CORS error. 

### [REQUIRED] Actual behavior

The header is not passed.

**Comment by abeisgoat** [comment]
Can you provide the `har` file from the network pane in Chrome? That'll help us figure out what's happening!

**Comment by bkendall** [comment]
Your har file seems to be for your production service. Could you provide the HAR for the requests made to the emulator? Thanks

**Comment by qiansen1386** [comment]
[localhost.zip](https://github.com/firebase/firebase-tools/files/7562627/localhost.zip)
Here is the emulator response. But I need it for production also. Any suggestion?

**Comment by bkendall** [comment]
Okay, I'm fully understanding this request now: you're looking for `Access-Control-Allow-Origin` to be set on the response of the image you're embedding, correct? Unfortunately, that's not something the emulator or Hosting can solve for you. Those headers are set by the server serving the image, so it's up to _them_ to make that change. There's nothing actionable here that we can do to help, unfortunately.

**Comment by qiansen1386** [comment]
I see
