### ISSUE TITLE
Firebase-cli commands returning error

### ISSUE THREAD

**Issue by kr05** [firebase/firebase-tools#387]
I am trying to use the "firebase deploy" but it's returning the following error:

`Error: An unexpected error has occurred.`
It was working fine this morning and it suddenly stopped, and I haven't made any changes. I tried updating firebase-cli, firebase init, and firebase login, but none of these fixed the problem.

Here's the firebase-debug.txt file: 

[firebase-debug.zip](https://github.com/firebase/firebase-tools/files/1129493/firebase-debug.zip)

**Comment by laurenzlong** [comment]
Thanks for reporting, we have an outage due to a dependency (Google's Oauth2 service). The relevant teams have been paged, and are working actively to fix it.

**Comment by laurenzlong** [comment]
@kr05 Can you try again now?

**Comment by kr05** [comment]
Yes, it works perfect now. Thanks!

**Comment by mding5692** [comment]
Hi @laurenzlong  I actually have the same issue and its been going on for a while, just tried now and accidentally even updated to node 8.10 from issue #356 , it says 503 Error which i presume is the outage?

Heres the error in the debug.log:

`[debug] [2017-07-07T00:22:59.604Z] <<< HTTP RESPONSE 200
[info] i  functions: packaged functions (6.47 KB) for uploading
[debug] [2017-07-07T00:23:02.238Z] >>> HTTP REQUEST GET https://www.googleapis.com/storage/v1/b/staging.lucid-dev.appspot.com  
 Thu Jul 06 2017 20:23:02 GMT-0400 (EDT)
[debug] [2017-07-07T00:23:02.352Z] <<< HTTP RESPONSE 503
[debug] [2017-07-07T00:23:02.353Z] <<< HTTP RESPONSE BODY undefined
[debug] [2017-07-07T00:23:02.355Z] TypeError: Cannot read property 'error' of undefined
[error] 
[error] Error: An unexpected error has occurred.`

Much thanks.

**Comment by laurenzlong** [comment]
Hi @mding5692 , you're right, the outage is back. Sorry for the inconvenience. You can follow along in https://status.firebase.google.com/ for the latest status.

**Comment by mding5692** [comment]
Also just a note to others who might have an issue from the outage and get an error like this after the outage is reported to be fixed:

`Server Error. connect EHOSTUNREACH`

Try reinstalling firebase-tools again via:

`npm install -g firebase-tools`

because it might help and yep after fixing that one, I've been able to upload my cloud functions

**Comment by reyou** [comment]
@mding5692  

`npm install -g firebase-tools`

worked like a charm. Thanks!

**Comment by imMarkdeVries** [comment]
I'm having a problem with uploading functions  due to a 
_self signed certificate in certificate chain_

Does anybody know what to do. I tried the reinstall. Also stopped the virus protection.
 
Here is what happens

```
firebase deploy --only functions

=== Deploying to 'firestore-d1320'...

i  deploying functions
Running command: npm --prefix $RESOURCE_DIR run lint

> functions@ lint D:\projecten\InputGenerator\functions
> eslint .

+  functions: Finished running predeploy script.
i  functions: ensuring necessary APIs are enabled...
+  functions: all necessary APIs are enabled
i  functions: preparing functions directory for uploading...
i  functions: packaged functions (52.62 KB) for uploading
!  functions: Upload Error: Server Error. self signed certificate in certificate chain
i  functions: updating function firestoreEmail...
!  functions[firestoreEmail]: Deployment error.
Failed to retrieve function source code


Functions deploy had errors. To continue deploying other features (such as database), run:
    firebase deploy --except functions

Error: Functions did not deploy properly.
```

**Comment by cvharris** [comment]
@imMarkdeVries I believe it's due to gRPC not handling Mac self-signed certs well. This is especially a problem with companies that require all employee devices to have their own security certs for decrypting traffic. It's not clear how to have gRPC trust certs on a per-device basis.
