### ISSUE TITLE
Call projects.defaultLocation.finalize call on `init storage`

### ISSUE THREAD

**Issue by ramonbroox** [firebase/firebase-tools#3895]
### [REQUIRED] Environment info

**firebase-tools:** 9.22.0 

**Platform:** macOS

### [REQUIRED] Test case

```
firebase projects:create xxxxx
firebase init storage
```

### [REQUIRED] Steps to reproduce

```
firebase projects:create xxxxx
firebase init storage
```

### [REQUIRED] Expected behavior

Storage is initialized. If no defaultLocation is set, it is requested (like in `init database` and  `projects.defaultLocation.finalize` workflow is executed)

### [REQUIRED] Actual behavior

Have to go to the web console to select the defaultLocation, breaking the flow of automation.

**Comment by abeisgoat** [comment]
This is probably not going to be fixed due to repercussions on the entire Cloud project, we will however surface this internally so the team is aware of the request.
