### ISSUE TITLE
`signInWithEmailAndPassword` method throws an incorrect error when Authentication emulator is enabled

### ISSUE THREAD

**Issue by lysov** [firebase/firebase-tools#3898]
Given an invalid email argument and a valid password argument. `signInWithEmailAndPassword` method from JavaScript SDK throws an error with a `code` `auth/invalid-email` using an actual Firebase project. The method throws an error with a `code` `auth/missing-email` when an Authentication emulator is enabled.

### Environment info

**firebase-tools:** `9.22.0`
**firebase:** `9.2.0`
**Platform:** macOS `12.0.1`

### Test case

When a function `signInWithEmailAndPassword` is called using Authentication emulator, it's behavior should match real Firebase Authentication.

### Steps to reproduce

Given Firebase app is initialized and Authentication emulator is enabled. `signInWithEmailAndPassword` throws an error with a `code` `auth/missing-email`
```
const invalidEmail = '';
const validPassword = 'wowsuchsecureverysafepassword';
signInWithEmailAndPassword(getAuth(), invalidEmail, validPassword);
```

### Expected behavior

Given Firebase app is initialized and Authentication emulator is enabled. `signInWithEmailAndPassword` should throw an error with a `code` `auth/invalid-email`
```
const invalidEmail = '';
const validPassword = 'wowsuchsecureverysafepassword';
signInWithEmailAndPassword(getAuth(), invalidEmail, validPassword);
```

**Comment by lysov** [comment]
Would love to provide more information if somebody could point out what's missing.

**Comment by bkendall** [comment]
The bot is particularly picky, don't worry about that. Someone more familiar with the auth emulator will have to follow up on this.

**Comment by lisajian** [comment]
Thanks for raising this issue. The fix should be in the next version bump of firebase-tools (i.e. > 11.16.1)! If you're still facing the bug after the next version, please feel free to reopen or file a new issue

**Comment by hjaelee01** [comment]
Still facing the same issue here. I'm currently running on firebase-tools v.12.2.1.
