### ISSUE TITLE
Firebase deploy error

### ISSUE THREAD

**Issue by itsTeknas** [firebase/firebase-tools#390]
I'm getting the following error after hitting `firebase deploy --only functions`

```
i  deploying functions
i  functions: ensuring necessary APIs are enabled...
i  runtimeconfig: ensuring necessary APIs are enabled...
✔  runtimeconfig: all necessary APIs are enabled
✔  functions: all necessary APIs are enabled
i  functions: preparing functions directory for uploading...

Error: Error occurred while parsing your function triggers.

Error: The module '/private/var/folders/n3/h9nbc_ys2732s35_9jlgh98c0000gn/T/fbfn_6601274o3l5DKN66/node_modules/grpc/src/node/extension_binary/grpc_node.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 51. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/private/var/folders/n3/h9nbc_ys2732s35_9jlgh98c0000gn/T/fbfn_6601274o3l5DKN66/node_modules/grpc/src/node/src/grpc_extension.js:38:15)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
```

**Comment by itsTeknas** [comment]
```
npm -v
5.1.0
node -v
v8.1.3
```

**Comment by itsTeknas** [comment]
Tried to cd into /private/var/folders/n3/h9nbc_ys2732s35_9jlgh98c0000gn/T/fbfn_6601274o3l5DKN66/node_modules/grpc/

and run npm install --build-from-source

Still nothing

**Comment by itsTeknas** [comment]
I tried it with stable release also, but still the same issue.
I think something might be off with the grpc module's release which firebase-tools uses as a dependency.

**Comment by itsTeknas** [comment]
Solved it. The firebase-tools seem to need node V 7.10.0 as of now.
Installed it via nvm.

**Comment by dreadjr** [comment]
For reference, I received a similar error for a native module.

> The module '<xyz>'
> was compiled against a different Node.js version using
> NODE_MODULE_VERSION 64. This version of Node.js requires
> NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
> the module (for instance, using `npm rebuild` or `npm install`).

The reason was due to my installation method of firebase-tools
I used `curl -sL firebase.tools | bash`.
This was built with a different node version than my current.
Once I removed the firebase-tools and did `npm install -g firebase-tools`, the issue was resolved.
