### ISSUE TITLE
Firebase Emulator throws npm cli-table error only when importing firestore data

### ISSUE THREAD

**Issue by Mikephii** [firebase/firebase-tools#3909]
Im using  firebase-tools ^9.22.0

I am importing a relatively large firestore dataset. its using 7G of ram to run. 

the emulator starts all of the services correctly, deploys all the functions, and then throws this error in firebase-debug

`[debug] [2021-11-18T06:17:29.585Z] TypeError: Cannot read property 'rows' of undefined
    at new Table (C:\Users\Mike\Documents\Code\Antler\internal\functions\node_modules\cli-table\lib\index.js:51:15)
    at Command.actionFn (C:\Users\Mike\Documents\Code\Antler\internal\functions\node_modules\firebase-tools\lib\commands\emulators-start.js:47:33)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
[error] 
[error] Error: An unexpected error has occurred.`

the emulators stay open however and i need to close them via the task manager. I can even view the emulator UI but it just tells me that the emulators are disconnected.

**Comment by Mikephii** [comment]
i commented out some offending lines in emulator-start.js as suggested by others. this supresses the CLI-table error, but another issue im facing is that the UI says the suite is disconnected. 

All my emulators are running ok. the firestore emulator returns 'ok'. but the UI wont let me interact with them

**Comment by AdditionAddict** [comment]
@Mikephii Are you commenting out 47-87 of `emulators-start.js` i.e. don;y comment out `await killSignalPromise;`

**Comment by DaveMitten** [comment]
Anyone got any solutions for this, I am running into the same errors.

**Comment by DaveMitten** [comment]
TypeError: Cannot read property 'rows' of undefined
    at new Table (/Users/davidmitten/.nvm/versions/node/v14.17.6/lib/node_modules/firebase-tools/node_modules/cli-table/lib/index.js:51:15)


I'm getting this too

**Comment by phess101** [comment]
Resolved by PR https://github.com/firebase/firebase-tools/pull/3907

**Comment by nmduc68** [comment]
Same issue :((

**Comment by phess101** [comment]
@bkendall Could we get a version release including PR https://github.com/firebase/firebase-tools/pull/3907 to resolve these issues?

**Comment by DaveMitten** [comment]
Its the table that displays whats working, thats whats really annoying about this.

**Comment by abdok96** [comment]
> @bkendall Could we get a version release including PR #3907 to resolve these issues?

We really need this

**Comment by phess101** [comment]
I manually went in to the node_modules folder of the globally installed firebase-tools package and applied the code fix to cli-table as outlined https://github.com/Automattic/cli-table/pull/154/files.

**Comment by phess101** [comment]
Looks like cli-table just updated to 0.3.8. I haven't tested myself but it should resolve the issue

**Comment by abdok96** [comment]
> Looks like cli-table just updated to 0.3.8. I haven't tested myself but it should resolve the issue

It's working for me now. Thank you.

**Comment by bkendall** [comment]
Yeah, sorry about this :( unfortunate consequence of how npm works. A new version is going out the door now (`9.23.0`) but re-installing firebase-tools should also fix it. Thanks for y'alls patience
