### ISSUE TITLE
firebase serve --only functions on node 8

### ISSUE THREAD

**Issue by felipecocco** [firebase/firebase-tools#391]
I saw the issue which closed the warning about using node 8, but serving functions still displays a warning and requests you to downgrade to node 6.9.1

![image](https://user-images.githubusercontent.com/4644625/27995509-a9a3dd08-649d-11e7-999c-76552e5748f9.png)

**Comment by laurenzlong** [comment]
Thanks for the report @felipecocco , the emulator is an optional dependency, so that's why the warning is only there if you try to run the serve command and it fails.

**Comment by laurenzlong** [comment]
v6.9.1 is the version of Node that is used in the server, so that's why the local emulator works best with it as well.
