### ISSUE TITLE
Cloud function: /<segment>/** rewrite doesn't work

### ISSUE THREAD

**Issue by roosi** [firebase/firebase-tools#392]
I have the cloud function

```
const app = express()

app.get('/ping', (req, res) => {
  res.send('pong');
})

exports.api = functions.https.onRequest(app)
```
and it works fine

https://...cloudfunctions.net/api/ping
pong

Then I add following configuration

```
{
  "hosting": {
    "public": "public",
    "rewrites": [ {
      "source": "/api/**", "function": "api"
    } ]
  }
}
```

and try to call it from application url and it fails.

https://...firebaseapp.com/api/ping
404

If I use rewrite all calls to my functions like this

```
{
  "hosting": {
    "public": "public",
    "rewrites": [ {
      "source": "**", "function": "api"
    } ]
  }
}
```

then it works

https://...firebaseapp.com/ping
pong

Am I missing something here or isn't this scenario supported?

There is the blog writing about this, which uses and segment in rewrite:

[https://firebase.googleblog.com/2017/06/serving-dynamic-content-with-cloud.html](url)

**Comment by mbleigh** [comment]
You need to add /api to the start of your express route. Prefixes aren't
chopped off when URLs are sent to the cloud function.

**Comment by Pkmmte** [comment]
@roosi I also ran into this issue last week. It's annoying but the best solution I could come up with for a scenario like this is to create a `main` function and rewrite all hosting calls to it. This enables you to call `https://...firebaseapp.com/api/ping`, for example.

See my answer here for more details:
https://stackoverflow.com/a/45224176/1309346

**Comment by tommmyy** [comment]
I guess that the example at the https://github.com/firebase/functions-samples/blob/master/authorized-https-endpoint is broken too?
