### ISSUE TITLE
Emulator fails to start with M1 Mac

### ISSUE THREAD

**Issue by jakebiesinger-storyhealth** [firebase/firebase-tools#3920]
### [REQUIRED] Environment info

**firebase-tools:**
9.23.0

**Platform:**
Mac OS 12.0.1 (Monterey) running on an Apple M1 Max chip

### [REQUIRED] Test case

Install firebase tools and attempt to start the emulator:

```
$ npm install -g firebase-tools
$ firebase -P some-project emulators:start

...
i  emulators: Starting emulators: functions, firestore, hosting, pubsub, storage
✔  functions: Using node@14 from host.
i  firestore: Firestore Emulator logging to firestore-debug.log
i  pubsub: Pub/Sub Emulator logging to pubsub-debug.log
dyld[73075]: missing symbol called
[nodemon] app crashed - waiting for file changes before starting...
...

```

Aaand we can't get the emulator to start at all. Instead, we see it crash with that `dyld[73075]: missing symbol called` error.

**Comment by jakebiesinger-storyhealth** [comment]
This is possibly related to `sse4_crc32` not building correctly for M1 chips?

https://github.com/anandsuresh/sse4_crc32/issues/84

**Comment by Lovygoogle** [comment]
https://matjar-muntajat-tarathih.business.site/?m=truecurl -sL firebase.tools

**Comment by yuchenshi** [comment]
Does this only happen when you start the Pub/Sub emulator? For example, what happens if you run `firebase emulators:start --only firestore`.

**Comment by jfhr** [comment]
I had the same issue, but it seems to be related to the functions emulator. Didn't happen when using just the Pub/Sub emulator. It went away when I uninstalled `fast-crc32c` from my functions package.

**Comment by bkendall** [comment]
I just did a clean install of firebase-tools (`9.23.1`) on a M1 macOS device and I'm unable to replicate this. I'd recommend any one else having issues to clean their npm caches and re-install the CLI. Hopefully this is resolved for you, but since we've gotten no response recently, I'm going to close this.
