### ISSUE TITLE
Cannot Scope Cloud Function to an individual bucket on local Cloud Storage Emulator

### ISSUE THREAD

**Issue by marcfrankel** [firebase/firebase-tools#3932]
### [REQUIRED] Environment info

**firebase-tools:** 9.23.0

**Platform:** macOS 12.0.1 (Intel Mac)

### [REQUIRED] Test case

I am trying to scope a Cloud Storage triggered cloud function to a specific storage bucket as the documentation explains here: https://firebase.google.com/docs/storage/extend-with-functions. However, on the local emulator, the function is run no matter what bucket a file is uploaded to. This appears to be a bug in the local emulator because if I deploy the same function to Firebase it runs as one would expect there.

### [REQUIRED] Steps to reproduce

1. Create a Cloud Storage triggered function.
2. Scope function to a specific bucket
3. Upload a file to that specific bucket
4. Upload file to any other or default bucket
5. Function should have triggered both times despite being scoped to only run once.

Sample Code:
`export const transformProfileImage = functions.storage.bucket('scoped_bucket_name').object().onFinalize(async (file) => {
    console.log(file.name);
});`

### [REQUIRED] Expected behavior

The expected behavior is that the Cloud Function should only run when a file is uploaded to the scoped cloud bucket.

### [REQUIRED] Actual behavior

It actually runs no matter what bucket I uploaded it to on the local emulator. However, the expected behavior is correct if the function is deployed to firebase.

**Comment by abeisgoat** [comment]
This is a known issue which I believe has been addressed by @colerogers, but he can verify.

**Comment by colerogers** [comment]
I currently have a PR out for this fix - #3893 

@abeisgoat Can I get your sign off before merging it?

**Comment by colerogers** [comment]
Hi @marcfrankel the fix was merged and we will ship it with our next release.
