### ISSUE TITLE
Storage emulator incompatible with java client library

### ISSUE THREAD

**Issue by GrandmasterDan** [firebase/firebase-tools#3949]
### [REQUIRED] Environment info

9.23.1

macOS

### [REQUIRED] Test case

In my experience, every "storage" operation fails.  From some debugging output (note that as far as I can tell, the storage emulator does not output a log file) it looks like the java client (version 2.2.2) is using extra URL path parts as compared to what the emulator is looking for.  The java client library seems to be producing requests like this (just one example):
      GET http://localhost:9199/storage/v1/b
which fail, but from a curl command I can see that this succeeds;
      GET http://localhost:9199/b
and that goes for every operation.  It seems like the java client library is adding an extra "storage/v1" prefix to the URL of the operations.   I'm not 100% sure about that, though, that's just extra information that seemed relevant.  The symptoms are that all write operations return eithter a 500 Internal Server Error or 400 Bad Request and all read options return a 404 Not Found.  But the data is there, because I can see it with the emulator UI.   It seems like something with the java client library (the latest as of this posting, 2.2.2) is just incompatible with the emulator (the latest as of this posting, 9.23.1)

### [REQUIRED] Steps to reproduce

Connect the java storage client to the emulator and run any operation, they all fail.

### [REQUIRED] Expected behavior

Operations succeed

### [REQUIRED] Actual behavior

The storage seems to output no log file, and the --debug option prints nothing when any operation happens, so I don't know what I can submit here.

**Comment by abeisgoat** [comment]
This is expected as the scope of the Cloud Storage for Firebase emulator only replicates the endpoints used by 1) the Firebase client SDKs and 2) The `firebase-admin-node` SDK. Other Cloud Storage SDKs are out of scope (for the time being) so we don't expect them to work, however we're more than open to adding that compatibility if you'd like to contribute and open a PR.
