### ISSUE TITLE
9.23.3 released with latest tag, not 10.0.1

### ISSUE THREAD

**Issue by draperunner** [firebase/firebase-tools#3960]
It seems v9.23.3 was released to npm with the `latest` tag, yet I expect you wanted 10.0.1 to have this. tag.

```
npm info firebase-tools
```
returns
```
dist-tags:
latest: 9.23.3
```

Release history (`npm show firebase-tools@* version`:
```
firebase-tools@9.23.2 '9.23.2'
firebase-tools@10.0.0 '10.0.0'
firebase-tools@10.0.1 '10.0.1'
firebase-tools@9.23.3 '9.23.3'
```

### [REQUIRED] Environment info

**firebase-tools:** 9.23.2

**Platform:** macOS

### [REQUIRED] Test case

Run  `npm info firebase-tools` and check the dist-tags property.

### [REQUIRED] Steps to reproduce

Run  `npm info firebase-tools` and check the dist-tags property.

### [REQUIRED] Expected behavior

Version 10.0.1 should have the latest tag.

### [REQUIRED] Actual behavior

Version 9.23.3 has the latest tag.

**Comment by mcfarljw** [comment]
I'm wondering if this intentional too. I just did an update and it wants to downgrade from 10 to 9.

**Comment by mikehardy** [comment]
Just noticed this myself https://www.npmjs.com/package/firebase-tools
@bkendall you were just doing some rel-eng stuff, this cannot be intentional? Thought you'd want to know as it makes the release situation in the repo puzzling

**Comment by bkendall** [comment]
Oh boy, good call. I'll fix this up manually.

**Comment by bkendall** [comment]
Ah ha! I got it figured out. Thanks again for flagging (and glad I finally came back to look at my email for a moment!)
