### ISSUE TITLE
Command "firebase emulators:export ." deleted all my files without any warning

### ISSUE THREAD

**Issue by gitslav** [firebase/firebase-tools#3962]
### [REQUIRED] Environment info

**firebase-tools:** 9.19.0

**Platform:** macOS

### [REQUIRED] Steps to reproduce

1. In directory A create a symlink B to directory C (imagine all our projects are located here)
2. cd B
3. cd D (one of our projects)
4. run "firebase emulators:export ."

### [REQUIRED] Expected behavior

1. Important project files are still existing in current folder.
2. Set of entity export files is created in current folder.

### [REQUIRED] Actual behavior

1. All important project files are deleted
2. Set of entity export files are not created in current folder
3. Error "Export request failed, see emulator logs for more information." is shown

<img width="568" alt="Screenshot 2021-12-19 at 10 52 40" src="https://user-images.githubusercontent.com/3044045/146676713-80817ee4-6519-4bc3-a434-8dc0ec556e0d.png">

Edit:
After trying to reproduce the issue I found that I used a symlink while navigating to the final directory.

https://github.com/firebase/firebase-tools/blob/3d5b8cdbb36a8056803e42c720d9dca8f90ce26c/src/emulator/controller.ts#L749

This does not resolve/respect symlinks and is probably where the issue starts from.

**Comment by abeisgoat** [comment]
Hmm, thanks for raising this, the CLI should really prompt you if you're attempting to export to a directory which already has files in it. We'll put this as a feature request.

**Comment by gitslav** [comment]
@abeisgoat the CLI does prompt you if the path does not contain a symbolic link.
If it does contain a symbolic link the use of "path.resolve" function (shown above) breaks the flow and leads to a bug where the files are deleted.
A proper way to implement this should probably be by using "[fs.realpath](https://nodejs.org/docs/latest/api/fs.html#fs_fs_realpath_path_options_callback)" function as it is resolving properly ., .. and symbolic links.

**Comment by DiegoGonzalezCruz** [comment]
OMG I can't believe I'm not the only person...

**Comment by gitslav** [comment]
It's a really nasty bug. Not sure why @abeisgoat added a feature request label 😃

**Comment by yuchenshi** [comment]
Just to add a bit of context, we've fixed the most common and dangerous case of wiping your project directory in #4127 so please update to the latest CLI version. However, the detection is imperfect that it doesn't handle symlinks, which we can tackle next (as @gitslav suggested).

There's also a possibility for one to specify some other directory that is not within the project but contains other files, which we're still trying to figure out the best behavior. Prompting is a good idea, but it may break many test scripts and use cases that overwrites previous exports. Besides, it doesn't really work with `--export-on-exit` when the process is exiting and cannot wait on interactive input. Ideas welcome here.

**Comment by Elias070** [comment]
Lost half of all progress because of this bug... please fix, or atleast add warning in documentation

**Comment by colerogers** [comment]
Closing this out since we have #3092 as the proper place for discussion
