### ISSUE TITLE
allUsers > Cloud Functions Invoker role randomly added to newly deployed HTTP functions

### ISSUE THREAD

**Issue by feliksmatsko** [firebase/firebase-tools#3965]
### Environment info
**firebase-tools:** 10.0.1
**Platform:** macOS

### Test case
https://github.com/feliksmatsko/firebase-cli-issue

### Steps to reproduce
1. Create more than 40 normal http cloud functions ([example](https://github.com/feliksmatsko/firebase-cli-issue/blob/master/functions/src/index.ts))
2. run cli: _firebase deploy --only functions_

### Expected behavior
For ALL newly deployed cloud functions to have the same permissions

### Actual behavior
Some functions allow authenticated and some don't. The number of functions with and without invoker created is random.
Multiple errors in cli: "Error Failed to set invoker function f38 in region us-central1"

<img width="1266" alt="Screenshot 2021-12-20 at 15 20 16" src="https://user-images.githubusercontent.com/3799407/146773625-d94a02b9-c906-4252-8eb7-e9d75e3c586c.png">

**Comment by bkendall** [comment]
Do you have a log file for when this happens? That would help greatly in trying to debug this. I'm not sure off hand of an issue where this would only occasionally work but maybe there's something that can help shed light on it.

**Comment by inlined** [comment]
We can add more retries to this API call, but it tends to just be flaky. If you set `invoker: 'public'` in your functions we make sure this is set on every deploy.
