### ISSUE TITLE
Cannot deploy functions after deleting VPC connector

### ISSUE THREAD

**Issue by draperunner** [firebase/firebase-tools#3968]
It seems that when removing the `vpcConnector` setting in `runWith` and re-deploying, the Cloud Function configuration is not actually updated to remove the existing VPC connector network settings. Therefore, if deleting the VPC connector, you cannot deploy your functions.

A workaround is to manually remove the VPC Connector settings in each cloud function in the [Google Cloud Console](https://console.cloud.google.com) and redeploying. But I guess the intended behavior is that removing the setting from `runWith` should be enough, and therefore I report this as a bug.

### [REQUIRED] Version info

**node:**

v14.17.6
(Runs on CircleCI image `circleci/node:14`, which will use latest v14)

**firebase-functions: 3.16.0**

**firebase-tools: 9.22.0**

**firebase-admin: 9.12.0**

### [REQUIRED] Steps to reproduce

1. Go to [Google Cloud Console](https://console.cloud.google.com)
2. Go to "Serverless VPC Access" and create a connector for the region you run your functions in.
3. Configure one of your functions to use this connector:
```diff
+.runWith({ vpcConnector: 'my-connector' })
```
4. Deploy your function
5. Remove the `vpcConnector` setup:
```diff
-.runWith({ vpcConnector: 'my-connector' })
```
6. Deploy your function again.
7. Delete the VPC Connector in the Google Cloud Console.
8. Deploy your function again – it fails because the vpc connector does not exist 💥 

### [REQUIRED] Expected behavior

Functions should be successfully updated, without the use of the former VPC connector.

### [REQUIRED] Actual behavior

Function deployment fails, with the following error message:

> VPC connector projects/<my-project>/locations/europe-west1/connectors/<my-connector> is not ready yet or does not exist. Please visit https://cloud.google.com/functions/docs/troubleshooting for in-depth troubleshooting documentation.

### Were you able to successfully deploy your functions?

No.

**Comment by taeold** [comment]
This should've been closed in https://github.com/firebase/firebase-tools/pull/3973.
