### ISSUE TITLE
FR: Emulator browser programmatic login functionality for rapid e2e testing

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [firebase/firebase-tools#3970]
Hi all,

We're using the firebase emulator for our e2e testing with playwright.
During the e2e testing we populate the database with randomly generated users (example: testuser5242364@test.com) so that our tests can run in parallel (and rerun multiple times if necessary) without interfering with one another.
However each test default runs in a new browser instance, necessitating us to re-login each time which makes our test runs a lot longer.
A non-ideal solution would be to use the playwright functionality to re-use a storageState.json   https://github.com/microsoft/playwright/discussions/10715 ; however even if we would get this working, this will most probably not work when over tests with different randomly created users.
Is there a possibility (or could a functionality be added) that logs in a user somehow programmatically (only in the emulator of course)?
Or that somehow returns the browser storage state for that user so we can import it in the playwright chromium instance or something?
Maybe this is something more related to firebase-js-sdk? Or both?

Just as a note: Playwright + firebase emulator is crazy useful for e2e testing

**Comment by yuchenshi** [comment]
I don't know about Playwright, but yes, you can definitely just pass the email and password to the `signInWithEmailAndPassword` method: https://firebase.google.com/docs/auth/web/password-auth#sign_in_a_user_with_an_email_address_and_password

If you're using the FirebaseUI for Auth (e.g. the pre-build UI), note that the `AuthUI` is based on an underlying `firebase.auth()` instance. So all you need to do is:

```js
var auth = firebase.auth();

if (fooBarIsInMyTest()) {
  auth.signInWithEmailAndPassword(fooBarGetEmail(), fooBarGetPassword()); // returns a promise
   // note that you can skip the UI entirely during tests and just handle the promise above
} else {
  var ui = new firebaseui.auth.AuthUI(auth); // otherwise show UI as normal
  ui.start(...)
}

```

You'll have to implement your own way to pass the email and password to the page, e.g. by using query parameters in the URL. Please know that the basic building blocks are already there and feel free to get creative. For more questions on how to use Firebase Auth (UI / JS SDK) with Framework X, StackOverflow is a better forum.
