### ISSUE TITLE
Error: Failed to make request: Invalid response body while trying to fetch ... incorrect data check

### ISSUE THREAD

**Issue by ludvigaldrin** [firebase/firebase-tools#3975]
### [REQUIRED] Environment info

**firebase-tools: 10.0.1**
Also tried with version 9 something with the same result.

**Platform: macOS**

### [REQUIRED] Test case

I have a big project running but for test I created a new project and added one pubsub schedule function.

1. Firebase init function
2. Added one code pubusb schedule. 

`const functions = require("firebase-functions");
exports.scheduledFunctionCrontab = functions.pubsub.schedule('5 11 * * *')
    .timeZone('America/New_York') // Users can choose timezone - default is America/Los_Angeles
    .onRun((context) => {
        console.log('This will be run every day at 11:05 AM Eastern!');
        return null;
    });`
3. firebase deploy

### [REQUIRED] Steps to reproduce

Test case and reproduce is the same

### [REQUIRED] Expected behavior

I want it to deploy

### [REQUIRED] Actual behavior

`✔  functions: required API cloudscheduler.googleapis.com is enabled

Error: Failed to make request: Invalid response body while trying to fetch https://serviceusage.googleapis.com/v1/projects/XXXX/services/pubsub.googleapis.com: incorrect data check`

Additional information what I have tried:
Have disabled pubsub, removed all functions
In my larager normal project I have around 20 functions all works great. I have 6 pubsub topic functions that works. So its Schedule that is not working. I have tried different scheudle functions, different crontabs.

**Comment by bkendall** [comment]
"incorrect data check" is a new one for me.  Could you provide a bit more context from either running the command with `--debug` or from `firebase-debug.log`?

The other thing I'd ask is what permissions you have on the project: do you have permissions to enable APIs on the new project? If `cloudscheduler` is already enabled, you have permissions to check, but _enabling_ is another permission.

**Comment by ludvigaldrin** [comment]
Seems like there was some server error. For after the weekend I tried again and it worked.

**Comment by sleman-safiah** [comment]
try to change node version it works for me
