### ISSUE TITLE
emulators stopped working when I include the firestore emulator

### ISSUE THREAD

**Issue by voscausa** [firebase/firebase-tools#3976]
### [REQUIRED] Environment info

  10.0.1

This repo included: https://github.com/voscausa/vite-accounts

{
  "name": "vite-accounts",
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "devDependencies": {
    "@sveltejs/vite-plugin-svelte": "^1.0.0-next.30",
    "svelte": "^3.44.0",
    "vite": "^2.7.2"
  },
  "dependencies": {
    "firebase": "^9.6.1"
  }
}

**firebase-tools:**

Windows 10 latest pro

### [REQUIRED] Test case

Here is my code (with the logs) https://github.com/voscausa/vite-accounts

### [REQUIRED] Steps to reproduce

hostig emulator works fine without the firestore emulator (without firestore).

**Comment by voscausa** [comment]
Also the ui info in the logs does not show up. Ui doe not work
Here I have included the logs
[firestore_log.txt](https://github.com/firebase/firebase-tools/files/7788560/firestore_log.txt)
[firebase_log.txt](https://github.com/firebase/firebase-tools/files/7788561/firebase_log.txt)
.

**Comment by voscausa** [comment]
Cannot give anymore info. The emulators do not work when I include the firestore emulat

**Comment by voscausa** [comment]
This firebase.json works (withgout firestore) works fine:

```
{
  /* "firestore": {
    "rules": "firestore.rules",
    "indexes": "firestore.indexes.json"
  }, */
  "hosting": {
    "public": "dist",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "rewrites": [
      {
        "source": "**",
        "destination": "/index.html"
      }
    ]
  },
  "storage": {
    "rules": "storage.rules"
  },
  "emulators": {
    "auth": {
      "port": 9099
    },
    /* "firestore": {
      "port": 8080
    }, */
    "hosting": {
      "port": 5000
    },
    "storage": {
      "port": 9199
    },
    "ui": {
      "enabled": true,
      "port": 4000
    }
  }
}
```

But when I add firestore (by removing the above comments: I can access firestore, but all other emulators and the ui no longer work. And the information about the ui and the emulator ports is missing from the log.

**Comment by abeisgoat** [comment]
Can you share the console output that shows up in your terminal and a screenshot of the homepage of the emulator UI in the browser?

**Comment by voscausa** [comment]
When firestore is "active", The emulator UI does not work. And hosting does
not work.

[image: screenshot.png]

{
  "emulators": {
    "auth": {
      "port": 9099
    },
    "firestore": {
      "port": 8080
    },
    "hosting": {
      "port": 5000
    },
    "storage": {
      "port": 9199
    },
    "ui": {
      "enabled": true,
      "port": 4000
    }
  },
  /* "firestore": {
    "rules": "firestore.rules",
    "indexes": "firestore.indexes.json"
  }, */
  "hosting": {
    "public": "dist",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "rewrites": [
      {
        "source": "**",
        "destination": "/index.html"
      }
    ]
  },
  "storage": {
    "rules": "storage.rules"
  }
}


Met vriendelijke groet,

Robert Vos


Op ma 10 jan. 2022 om 22:18 schreef Abe Haskins ***@***.***>:

**Comment by iboxgithub** [comment]
Don't know if it's related but I also can't make the Emulators work anymore if Firestore is included. 
To reproduce, simply run `firebase init` in an empty folder and try to add at least Functions, Storage and Firestore.
The error I get is `Error: TIMEOUT: Port 8085 on localhost was not active within 60000ms`

**Comment by yuchenshi** [comment]
@iboxgithub Would you mind opening  a different issue for that?
