### ISSUE TITLE
Cleanup unused container images built for Firebase Function following firebase deploys

### ISSUE THREAD

**Issue by khmy2010** [firebase/firebase-tools#3978]
### [REQUIRED] Environment info

**firebase-tools:**  9.23.0

**Platform:** macOS 12.0.1

### [REQUIRED] Test case

1. Unused build artifact should either deleted or excluded from GCP billing

### [REQUIRED] Steps to reproduce

1. Create a new cloud function
2. Delete

### [REQUIRED] Expected behavior

1. Unused build artifact should either deleted or excluded from GCP billing

### [REQUIRED] Actual behavior
Unhandled error cleaning up build images. This could result in a small monthly bill if not corrected. You can attempt to delete these images by redeploying or you can delete them manually at (some website that show me 404)

Claimed to be solved in #3404, but not really the case.

**Comment by colerogers** [comment]
Hi @khmy2010, thanks for opening your first issue in Firebase!

I'm going to investigate this issue, but I need you to do a few things first so we can narrow the search.
- Can you update your `firebase-tools` to the latest version (Right now we're on 10.0.1).
- Can you re-run the delete command with the `--debug` flag at the end and paste the error output here.

Thanks

**Comment by lavdrimb** [comment]
I have the same issue a single funcion deploy with only console.log hello world cost me 408MB bandwith I m scared to continue.
Also before 2 days i had a bill 5.98$ only for deploying hello world function 4 or 5 times i had like 8.96 gb bandwith thats not normal why should use Container Registry Vulnerability Scanning ? All the billing was generated from this service imagine for the hello world console log 
  I have:
"firebase-admin": "^10.0.2",
"firebase-functions": "^3.18.0"
"node": "16"
