### ISSUE TITLE
Problem with CLOUD_RUNTIME_CONFIG (for loading .runtimeconfig.json) after upgrading from 9.16.0 to 10.0.1

### ISSUE THREAD

**Issue by johnnyoshika** [firebase/firebase-tools#3983]
### [REQUIRED] Environment info

**firebase-tools:** 10.0.1

**Platform:** Windows

### [REQUIRED] Test case

Create `.runtimeconfig.json` file in root of `functions` folder. Set it to:

```
{
  "env": {
    "foo": "bar"
  }
}

```

### [REQUIRED] Steps to reproduce

```
npm install -g firebase-tools@10.0.1
firebase emulators:start --only functions
```

Access config with:

```
import * as functions from 'firebase-functions';

const foo = functions.config().env.foo;
```

### [REQUIRED] Expected behavior

I expect the behavior to be the same as it was on `firebase-tools@9.16.0`, which is to load `.runtimeconfig.json` without any trouble.

### [REQUIRED] Actual behavior

Get this error:

```
!  It looks like you're trying to access functions.config().env but there is no value there. You can learn more about setting up config here: https://firebase.google.com/docs/functions/local-emulator
```

To fix this, I need to set this env variable before running `firebase emulators:start --only functions`.

```
$env:CLOUD_RUNTIME_CONFIG="$(pwd)/functions/.runtimeconfig.json"
```

StackOverflow reference: https://stackoverflow.com/a/70521419/188740

**Comment by johnnyoshika** [comment]
I did further testing but this time on macOS. The behavior in macOS has also changed between `firebase-tools@9.16.0` and `firebase-tools@10.0.1`.

In `firebase-tools@10.0.1`, if I run the following:

```
firebase emulators:start --only functions
```

...from the `functions` folder where all my functions code live, it loads `.runtimeconfig.json` without any trouble. If I run the command from one level higher (at the firebase project root), then I get this error:

```
⚠  It looks like you're trying to access functions.config().env but there is no value there. You can learn more about setting up config here: https://firebase.google.com/docs/functions/local-emulator
```

In `firebase-tools@9.16.0`, starting the emulator from the project root and functions folder both worked fine. It seems the default `CLOUD_RUNTIME_CONFIG` value has changed.

**Comment by taeold** [comment]
Hi @johnnyoshika - this issue seems similar to https://github.com/firebase/firebase-tools/issues/3793?

Can you please share the version of the Firebase Functions SDK you are using for your project? You may be able to get the issue fixed by updating the version of the Firebase Functions SDK to the latest version instead of explicitly seeting the CLOUD_RUNTIME_CONFIG environment variable.

**Comment by tolui** [comment]
Same problem here. 
Installed new windows, nodejs and latest Firebase cli
cloned my old firebase project
trying to run local emulator using firebase:emulators:start command
it gives me error "It looks like you're trying to access functions.config().jwt but there is no value there."
.runtimeconfig.json file is already in functions folder
deleted .runtimeconfig.json file and generated new one using command "firebase functions:config:get > .runtimeconfig.json" but problen not solved
Windows 10 pro, node 16.13.1, firebase cli 10.0.1

**Comment by johnnyoshika** [comment]
@tolui have you tried the firebase-functions update as @taeold suggested? I think this will fix it but I haven't had a chance to try it yet.

**Comment by tolui** [comment]
@johnnyoshika thanks
my current firebase-functions sdk was 3.14.0 and upgraded to latest 3.16.0 and it is working well

**Comment by taeold** [comment]
Glad to hear from you both @tolui and @johnnyoshika. Is it okay to mark this issue as closed now?

**Comment by johnnyoshika** [comment]
Thank you @taeold. I just tested it with `firebase-functions@3.16.0` and it works for me as well. Closing!
