### ISSUE TITLE
firebase projects:create fails to create project

### ISSUE THREAD

**Issue by yousafnawaz** [firebase/firebase-tools#3998]
### [REQUIRED] Environment info

**firebase-tools:** 10.0.1

**Platform:** Windows

### [REQUIRED] Steps to reproduce

![image](https://user-images.githubusercontent.com/91653057/148675875-cd49bc89-228f-45b8-8105-47c7790056a8.png)

### [REQUIRED] Expected behavior
it should create project or tell what needs to be done.. as error message is very confusing... I have only one project in firebase..

### [REQUIRED] Actual behavior
![image](https://user-images.githubusercontent.com/91653057/148675868-705b9dcf-d80b-4bf0-a117-7a8abe3fa159.png)

**Comment by abeisgoat** [comment]
Your project ID needs to be *globally* unique, that is to say that the ID must not be used by anyone, anywhere on Google Cloud. In the console, we'd randomly append a suffix to the project ID so that it is unique, but we don't do that, so you'll just need to get creative!
