### ISSUE TITLE
Not Found - GET https://registry.npmjs.org/colors/-/colors-1.4.1.tgz

### ISSUE THREAD

**Issue by xaphod** [firebase/firebase-tools#4010]
I realize this isn't Firebase's bug, but it's going to affect people using firebase-tools: package `colors` was messed around and removed from npm - see https://snyk.io/blog/open-source-npm-packages-colors-faker/

`firebase-tools` depends on `winston`, which depends on `winston-transport`, which depends on `logform` 2.3.0, which depends on `colors` 1.4.1.

So installing can now give the error `Not Found - GET https://registry.npmjs.org/colors/-/colors-1.4.1.tgz` 

Per `logform` contributor: `This fix is released in logform 2.3.2 and Winston 3.3.4`
https://github.com/winstonjs/logform/issues/126

**Comment by bkendall** [comment]
This is fixed by #4004
