### ISSUE TITLE
onFinalize trigger not working in Emulator

### ISSUE THREAD

**Issue by 3zzy** [firebase/firebase-tools#4014]
I'm using the latest Firebase SDK and trying to use the storage and function emulators but I can't get a simple test working although there are no errors.

```
// functions/index.js
const functions = require("firebase-functions");
const admin = require("firebase-admin");
require("firebase-functions/lib/logger/compat");

admin.initializeApp();

exports.helloWorld = functions.https.onRequest((request, response) => {
  console.log("Wello world!");
  response.send("Hello from Firebase!");
});

exports.firestoreTrigger = functions.firestore
  .document("my-collection/test")
  .onWrite((change, context) => {
    console.log({ change, context });
  });

exports.storageTrigger = functions.storage.object().onFinalize(async (object) => {
  console.log({ object });
});

```

The emulators all start up without issues. Now if I add a document its logged correctly by the `firestoreTrigger` function however if I upload a file manually using the emulator UI, nothing is logged.

Debug log attached.
[firebase-debug.log](https://github.com/firebase/firebase-tools-ui/files/7858046/firebase-debug.log)

**Comment by gmcdowell** [comment]
Guys seriously.. why are your tests not ensuring quality here.. we, your end users, spend enough time as it is navigating the constantly changing world that is Firebase/Flutter.. to have to be your QA team is a step too far.

Please please please sort this out

**Comment by colerogers** [comment]
@3zzy Thanks for opening your first issue in Firebase!!

I just tried the same steps that you ran and I'm able to successfully trigger the `onFinalize` trigger. My `firebase-functions` SDK is version `3.16.0` and my `firebase-tools` version is `10.1.2`.

What I think is happening here is the function that you've created is registered to your projects default bucket (which is usually something like `${project-Id}.appspot.com`), but when you start the Emulator UI, it defaults to a bucket called `default-bucket`.

So to change this you can either register your function to `default-bucket` by changing the signature to be
```
exports.storageTrigger = functions.storage.bucket("default-bucket").object().onFinalize(async (object) => {
  console.log({ object });
});
```
and re-run the Emulator to test your changes. [Here's where we document the default Cloud Storage bucket and how to listen to a specific bucket](https://firebase.google.com/docs/functions/gcp-storage-events#trigger-function-on-storage-changes).

Or, you can change the Emulator UI to show your default Cloud Storage bucket. If the Emulator address shows something like `http://localhost:4001/storage/default-bucket`, you would just change the last part of the address to be the bucket you want to listen on, like this `http://localhost:4001/storage/${project-Id}.appspot.com`, and refresh your browser.

If neither of these work for you, please post the versions of your functions sdk and firebase tools cli, thanks

**Comment by 3zzy** [comment]
@colerogers can confirm both work i.e changing the bucket to production bucket name or listening to a specific bucket. 

Thanks for that!

**Comment by gmcdowell** [comment]
@colerogers yes this does in fact resolve the issue.

Appreciate quick resolution, however I hope this will be resolved (default values being aligned) will be address moving forward.

**Comment by inlined** [comment]
Hey, thanks for sharing your debugging story. I think the fact that you needed help is probably a usability bug on our part, and I'm excited that we have a place where we can do better and protect people from the issues you faced here.

Fortunately we have some long-term investments we're making in Cloud Functions for Firebase that may fix this problem. The only downside is that these are long-term investments and I can't promise a timeline. Hopefully it's enough to know that the future is bright and more than just this simple bugfix is coming.

**Comment by chrisle** [comment]
This issue is also present in the current version as of this post (11.15.0). I reverted back to 11.9.0 using "npm i -G firebase-tools@11.9.0" and got it working again.
