### ISSUE TITLE
changes made by `firebase-admin` won't take effect in Firebase Emulator?

### ISSUE THREAD

**Issue by yaquawa** [firebase/firebase-tools#4020]
###  Environment info

**firebase-tools: v10.1.0**

**Platform:** macOS, node v16

###  Steps to reproduce
1. `firebase emulators:start --import /path/of/data/`
2. create a document `{id: '123', name: 'oldName'}` in collection `test`.
3. `firestore.collection('test').doc('123').update({name: 'newName'})`
4. check the value of `name` field of document `test/123`
5. the value of the `name` field is the original one(`oldName`).

###  Expected behavior
The client side SDK `firebase` works fine. However if I use the server-side SDK `firebase-admin` the changes are not going to be happened.

**Comment by jhubbardsf** [comment]
@yaquawa I think I know what you're issue might be. Make sure you set an environmental variable FIRESTORE_EMULATOR_HOST to localhost:8080. For example, in my js seed scripts that insert data for my user I have

```
const useEmulator = true;

if (useEmulator) {
	process.env['FIRESTORE_EMULATOR_HOST'] = 'localhost:8080';
}
```

Before initializing the admin sdk.

**Comment by yaquawa** [comment]
@jhubbardsf Thanks, I solved this by set `process.env.GCLOUD_PROJECT` to my project name, where the doc says it could be any value which is not correct…

**Comment by yuchenshi** [comment]
I'll close this since you've found the solution. Thanks for the feedback about project IDs and env vars though, and we're looking into that.
