### ISSUE TITLE
Confusing warning about node version

### ISSUE THREAD

**Issue by dsl101** [firebase/firebase-tools#4024]
### [REQUIRED] Environment info

**firebase-tools:**> firebase --version
10.1.1

**Platform:**> winver
Microsoft Windows Version 21H2 (OS Build 19044.1466)

### [REQUIRED] Test case

```
> firebase functions:shell
!  Your requested "node" version "14" doesn't match your global version "14"
```

Contents of `package.json`:
```
{
  "name": "functions",
  "description": "Cloud Functions for Firebase",
  "scripts": {
    "serve": "firebase serve --only functions",
    "shell": "firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "engines": {
    "node": "14"
  },
  "dependencies": {
    "camelcase": "^6.2.0",
    "firebase-admin": "^9.12.0",
    "firebase-functions": "^3.16.0",
    "firebase-tools": "^9.20.0",
    "glob": "^7.2.0",
    "jsonwebtoken": "^8.5.1",
    "lodash": "^4.17.15",
    "request": "^2.88.2",
    "request-promise-native": "^1.0.8"
  },
  "devDependencies": {
    "firebase-functions-test": "^0.1.6"
  },
  "private": true
}
```
### [REQUIRED] Expected behavior

That `"14" === "14"`

### [REQUIRED] Actual behavior

The CLI complains that the node version is wrong. Global version:
```
> node --version
v14.16.0
```

**Comment by dahmc** [comment]
Same on macOS 12.2

**Comment by laurentpayot** [comment]
Same on Ubuntu 21.10, with custom node version via npx:
```npx --package node@16.13.0 -- firebase emulators:start```
I get:
```⚠  Your requested "node" version "16" doesn't match your global version "16"```

**Comment by joehan** [comment]
Sorry all! This is just a logging bug - it seems like I forgot an else statement last time I changed this code. It should be fixed in our next release.
