### ISSUE TITLE
"Marked is not a function"

### ISSUE THREAD

**Issue by alisha-gupta** [firebase/firebase-tools#4028]
### [REQUIRED] Environment info

 Output of `firebase --version` -> 9.20.0

**firebase-tools: 10.1.1**

**Platform: macOS**

### [REQUIRED] Steps to reproduce

We did npm install firebase-tools@10.1.1 and the version of firebase-tools is showing as 10.1.1 whereas the "marked" dependency of firebase-tools is not upgraded to 4.0.10 as the commit claims, it is still showing as 0.7.0. Also the way "marked" is imported in firebase.js file is not upgraded in the latest firebase-tools version 10.1.1. 

### [REQUIRED] Expected behavior

[In firebase.js file] const { marked } = require("marked");
[In package-lock.json file] "marked": "4.0.10"

### [REQUIRED] Actual behavior

[In firebase.js file] const marked = require("marked");
[In package-lock.json file] "marked": "^0.7.0"

**Comment by MeSusmeeta** [comment]
Facing the same issue.

**Comment by AyashikaRamesh** [comment]
Stuck with the same issue.

**Comment by SonaliRathoreTw** [comment]
I am getting the same error

**Comment by bkendall** [comment]
Hi - so we're working on a release to actually update `marked`. The PR that has that update hasn't been released yet.

I'm not 100% sure how to reproduce this behavior though in your environments. One thing that might be causing it is your node version. What version(s) of node are being used here?

**Comment by SonaliRathoreTw** [comment]
Using node version 14.17.5


> Hi - so we're working on a release to actually update `marked`. The PR that has that update hasn't been released yet.
> 
> I'm not 100% sure how to reproduce this behavior though in your environments. One thing that might be causing it is your node version. What version(s) of node are being used here?

Using node version 14.17.5

**Comment by bkendall** [comment]
With `10.1.2` out of `firebase-tools`, are you still seeing the issue?

**Comment by alisha-gupta** [comment]
No, The issue is resolved , Thank you

**Comment by Coreusa** [comment]
Try `import { marked } from 'marked'`
