### ISSUE TITLE
Accept JSON file for functions:config:set

### ISSUE THREAD

**Issue by jpreynat** [firebase/firebase-tools#406]
Currently, it is possible to get the whole functions config as a JSON file using `firebase functions:config:get`, but we have to manually inline each variable when using the `firebase functions:config:set` command, which makes it practically unusable when working on different environments.

Ideally, we should be able to do:
```bash
firebase functions:config:get > config.json
firebase functions:config:set -f config.json
```

**Comment by ahaverty** [comment]
I agree with @jpreynat, we're dreading the day we forget to set a config var before deploying to our production. Tying config:set into our custom deploy scripts with a config.json would be a nice feature to see added.
Are there any workarounds right now, maybe piping in the config?

**Comment by laurenzlong** [comment]
Seems like you're trying to replicate config across projects. Would `firebase functions:config:clone` work for you?

**Comment by mbleigh** [comment]
To give some context, we've intentionally leaned away from file-based config because we think it encourages bad practices (namely, keeping a file full of secrets stored with your code, potentially even checked into your source repository).

What would you think about some way (mechanics TBD) to declare "required" config variables -- and if you tried to deploy without required config in the current project it would error out before anything was changed. Would that solve your main concerns? If not, why is having a file specifically useful to you?

**Comment by ahaverty** [comment]
@mbleigh That's exactly what I'm looking for.
Probably a given/what you meant by 'Mechanics TBD', but: Defining the keys/config structure in some file within our project rather than remotely, so that it goes through the git/PR review process like everything else. Nice idea! 
@jpreynat Sorry for hijacking issue

**Comment by jpreynat** [comment]
@laurenzlong Thanks for the advice, but we are not trying to duplicate a config.
Our main concern is to update different projects configuration depending on our deployment stage.
So basically, we have a config file per environment (dev, staging and prod), and set the Firebase config respectively (for PRs, push on master and tags).

@mbleigh Thanks for the information.
However, we aren't exactly sure how we can store all these envs another way than using config files.
They are currently formatted as JSON for reading simplicity, but we are thinking of formatting them as key/value pairs to pass them directly to the `functions:config:set` command.
I'll agree with you that this is no more secure than passing a JSON file.
Do you have any recommendations on how we could store our environment variables for different stages other than using files?

@ahaverty No worries, I'm glad that this can be debated here.

**Comment by mbleigh** [comment]
@jpreynat when you run `functions:config:set` it is stored with the current project. If you're using `firebase use` to switch between projects, your config will be persistent. So you can run `set` once per project and then it will *always* be there. This should solve the "different config for different environments" issue, so maybe I'm not understanding the real probleM?

**Comment by laurenzlong** [comment]
@jpreynat I'm going to close this issue for now, but please re-open if Michael and I have misunderstood your request.

**Comment by jpreynat** [comment]
@laurenzlong @mbleigh Sorry that I didn't answer quickly on this thread.
We found a workaround for this issue for now, but here is some context to clarify my request:

We are deploying our app using Travis (note that this would be great with any CI or even locally). Since we deploy our app to different stages depending on the branch and tag, it would be great to be able to use a different JSON file based on the environment.
For instance, this would allow to do either `firebase config:set -f staging.json` or `firebase config:set -f prod.json` depending on this condition.
Our workaround was to use `firebase` as a node module, but we still have to inline our JSON configuration, which is prone to errors.

**Comment by laurenzlong** [comment]
Hey @jpreynat I'm still a bit confused by your answer. Once you set the config once, it always stays there, even across deployments, unless you explicty unset the config values by running firebase functions:config:unset. So there's no need to have this as part of the CI process.

**Comment by bobrosoft** [comment]
Can somebody reopen this? %) @jpreynat @mbleigh  That's really one of the things which is missing. Atm I have near 15 config variables (and more coming) and that will be very handy if `functions:config:set` can accept JSON in some way.

**Comment by ahaverty** [comment]
Big vote from us for @mbleigh suggestion on "declare "required" config variables -- and if you tried to deploy without required config in the current project it would error out before anything was changed."
Becoming a pain point for us too, but that would solve all our issues and would fit nicely into the version control/review process 👍

**Comment by yaronyosef** [comment]
https://medium.com/@AllanHasegawa/setting-config-for-firebase-cloud-functions-with-json-136f455e7c69

**Comment by laurenzlong** [comment]
Hey @yaronyosef You can directly supply JSON to the firebase functions:config:set command, it's just that you have to format it in a way that's appropriate for your platform. For Linux, the following should work:

```
firebase functions:config:set foo='{"bar":"something","faz":"other"}'
```

**Comment by kanemotos** [comment]
Thank you for your sharing! @laurenzlong
I wanted to import from a file, so I used command like this.

`firebase functions:config:set service_accounts="$(cat service-account.json)"`

I imported a service account json file to Firebase Cloud Functions, because I wanted to use the user management API of Firebase Admin SDK.

**Comment by laurenzlong** [comment]
Cool use case! Thanks for sharing!

**Comment by dinvlad** [comment]
We would also prefer tracking non-secret configs through Git, where the committed JSON runtime config files (for multiple environments) will be authoritative and the CI environment would then apply `functions:config:set` from the file corresponding to a particular environment (and each environment corresponds to a separate Firebase project).

**Comment by mbleigh** [comment]
If you keep configs in git, it's trivial to read them into your functions runtime. Just put them at `configs/<project_id>.json` and then:

```js
let config = {};
try {
  config = require(`./configs/${process.env.GCLOUD_PROJECT}`);
} catch (e) {
  console.log('No config found for project', process.env.GCLOUD_PROJECT);
}
```

The runtime config used by Firebase is specifically designed to avoid having config checked into git, as (especially with secrets) we've found it to be a pattern that causes more problems than it solves.

**Comment by dinvlad** [comment]
That's true, although then we no longer use Config API for this purpose at all. It may be beneficial to still go through Config API for storing sensitive values (which seems to be an appropriate use case, based on Firebase docs) and load both tracked and untracked values in the same exact way (i.e. through `config()` provided by `firebase-functions`.

For the time being, I'm using the following one-liner to feed the entire `.runtimeconfig` to `functions:config:set`:
```
firebase functions:config:set $(jq -r 'to_entries[] | [.key, (.value | tojson)] | join("=")' < .runtimeconfig/${FIREBASE_ENV}.json)
```
where `FIREBASE_ENV` is the name of the environment used in deployment (e.g. `dev`). It would be nice to be able to shorten this further, e.g.
```
firebase functions:config:set -f .runtimeconfig/${FIREBASE_ENV}.json
```

**Comment by vongohren** [comment]
So how is this coming along? 😄

**Comment by ahaverty** [comment]
Would love to see @mbleigh [suggestion](https://github.com/firebase/firebase-tools/issues/406#issuecomment-316774781) be implemented still! We're constantly having issues forgetting to set configs on our non-dev targets

**Comment by mbleigh** [comment]
Thanks for the thread bump. Nothing to report yet, but I'll bring this up again in our planning meetings to see if we can start to make some progress on it.

**Comment by ahaverty** [comment]
@hgwood thanks for sharing! We will definitely be adding this to our CI too.

**Comment by CosmicMJ** [comment]
Just wanted to leave my solution to this "problem", and my thoughts on the discussion:

1. I understand that secret/sensitive values should NOT be stored in the repo. My solution is only for non-secret values. Secret values are set manually, but a way to mark config values as required would be wonderful for those secret values.
2. I think this is more important than some seem to think. It's a PITA to have to manually set individual configuration values for different deployment environment projects, and not be able to simultaneously view/compare them easily. Defining configurations in files makes the process a LOT easier.
3. I think adding a functions config editor to the web console would improve this a lot, but it would be really nice if there was a way to simultaneously view configurations for multiple projects, so you could easily compare configurations for different deployment environments.
4. I have been saying forever that firebase needs to allow environments to be defined within a single project, so you don't need multiple projects to use as deployment environments. If this existed, it'd be very easy to simultaneously view configurations for multiple environments within a single project.
5. My solution probably has issues, don't trust my explicit code, but I do like the general concept.

### My solution
I use cascading yaml configuration files, which is useful for default values and values that apply to all configurations regardless of deployment environment. 

./config/default.yml
```
app:
  name: My App
```

./config/dev.yml (similar config files for other deployment environments)
```
imports:
  - {resource: default.yml}
app:
  environmentName: Development
services:
  someOtherService:
    baseUrl: https://dev.someotherservice.com/api
```

Then, I've written a small node script that loads the resolved configuration, and returns a space-delimited list of key=val pairs

yaml_to_keyval.ts
```
import * as configYaml from "config-yaml"
import * as flat from "flat"


const yamlFile = process.argv[2]
const config = configYaml(yamlFile)
const flatConfig = flat(config)

const key_val_list = Object.keys(flatConfig).map(function(key){
    return `${key}="${flatConfig[key]}"`
})

console.log(key_val_list.join(' '))
```

During CI deployment, I use this script to obtain the key=val pairs and set them with functions:config:set
```
# env is set to the desired deployment environment (eg "dev"), which is passed as an argument to the CI script command
config_in="$(readlink -f ./config/$env.yml)"
key_vals="$(ts-node ./scripts/node/yaml_to_keyval.ts $config_in)"
firebase functions:config:set $key_vals
```

**Comment by mqln** [comment]
@kanemotos I like your `cat` solution, but did you not encounter a `Precondition check failed` error when trying to upload your cert file?

**Comment by dinvlad** [comment]
We ended up using Deployment Manager for these reasons.

We set all configuration through "config Yaml" for DM. Then DM creates appropriate Runtime Configs and Variables, and `firebase deploy` retrieves and sets their values at deploy time without having to use `firebase config:set` at all. This also allows us to create other resources (e.g. buckets and their access control) and set their values in RC without having to supply them externally to the template. Additionally, this allows us to use `camelCase` config and variable names.

The only time we set a value externally is when we need to pass an (encrypted) service account key through runtime config, because we create the SA as part of the deployment and also because DM cannot encrypt values securely. But we still use `gcloud beta runtime-config configs variables set` for that (after the DM deployment) and not `firebase config:set`, because the former accepts stdout from KMS.

**Comment by george43g** [comment]
I just wanted to add - reading through this it seems that some people missed a crucial point that leads to some confusion. **It would be really useful if this was cleared up in the documentation too.**

Basically, the functions.config() persists in between deployments, but ALSO can be set separately between different firebase projects!

This means that for dev, staging and prod environments, you'd have identically set up firebase projects (rather than using multi-site hosting, or deploying to the SAME project?) which persistently held different environment variables.
Once you've set aliases (or just switched projects with firebase use) you can deploy the same repo to multiple, separate firebase projects. This is how you have a dev environment, staging, and production - as separate projects.

Then, you can set separate environment configurations for each, like this:
firebase -P dev config:set - set variables for your development env
firebase -P prod config:set - set variables for your production env...

Then, you can deploy the same repo twice, like so:
firebase deploy -P dev
firebase deploy -P prod
and they will both deploy, to their respective firebase project, and will contain their own, separate environment configuration that will persist in-between deploys.

**Comment by ChaddPortwine** [comment]
Did something change, or did I forget a step? I downloaded a new Private Key .json file. I tried:

`firebase functions:config:set service_account="$cat /Users/dchaddportwine/Downloads/dev-is-xyz-123.json"
`

Add got the error:
`Invalid argument, each config value must have a 2-part key (e.g. foo.bar).`

**Comment by Kamshak** [comment]
Any way this could be prioritized? @mbleigh @laurenzlong 

It's very painful to import JSON into the config. All of the posted workarounds have their own issues or need setup 😞 Especially when escaping nightmares come into play because of newlines or quotes in strings.

**Comment by denkan** [comment]
Just sharing my vanilla JS solution which works regarding which platform you develop on (Windows, MacOS, Linux) :

Using separate projects for dev/test/prod.
#### /.firebaserc
```json
{
  "projects": {
    "dev": "my-project-name-dev",
    "test": "my-project-name-test",
    "prod": "my-project-name-prod"
  }
}
```

#### Config files
JSON-files in `/functions/config` folder:
```
/functions/config/config.dev.json 
/functions/config/config.test.json 
/functions/config/config.prod.json 
/functions/config/config.SAMPLE.json <-- only file tracked in git

Example content:
{
    "google": {
        "key": "my-api-key",
        "storage_bucket": "firebase-storage-bucket"
    },
    "another_vendor": {
        "my_prop": "my value"
    },
    ...
}
```
#### /functions/set-config.js
```js
const fs = require('fs');
const env = process.argv[2];

const configPath = `./config/config.${env}.json`;

if (!(configPath && fs.existsSync(configPath))) {
    return;
}

const collectConfigLines = (o, propPath, configLines) => {
    propPath = propPath || '';
    configLines = configLines || [];
    for (const key of Object.keys(o)) {
        const newPropPath = propPath + key;
        if (typeof o[key] === 'object') {
            collectConfigLines(o[key], newPropPath + '.', configLines);
        } else if (o[key] != null && o[key] !== '') {
            configLines.push(`${newPropPath}=${JSON.stringify(o[key])}`);
        }
    }
}

const config = require(configPath);
const configLines = [];
collectConfigLines(config, '', configLines);

const cp = require('child_process');
cp.execSync(`firebase use ${env}`);
cp.execSync(`firebase functions:config:set ${configLines.join(' ')}`);
```

#### /functions/package.json
```
...
"scripts": {
    "config:set:dev": "node set-config dev",
    "config:set:test": "node set-config test",
    "config:set:prod": "node set-config prod",
    ...
},
...
```

**Comment by baasbank** [comment]
If anyone is still looking, there's the method used in this medium article https://medium.com/indielayer/deploying-environment-variables-with-firebase-cloud-functions-680779413484. Saved my life.

**Comment by bezysoftware** [comment]
What I am personally missing is the ability to set a config variable *without* doing a deploy. We have CICD pipeline which does deployment to our different environments and we don't want a developer to build the code locally and deploy it, especially not to production. That's how things break.

Also if we want to change an existing variable later, with some feature in development, right now you have checkout the last released tag, build it, deploy, checkout back to your feature branch, continue. That really makes this unusable.

Essentially we would want remote config for cloud functions

**Comment by serweb-labs** [comment]
@bezysoftware I think you need to use environment variables (instead of enviroment configuration), you can skip the firebase layer and do it on google cloud platform, check it out https://cloud.google.com/functions/docs/env-var

**Comment by Md-Abdul-Halim-Rafi** [comment]
> Thank you for your sharing! @laurenzlong
> I wanted to import from a file, so I used command like this.
> 
> ```
> firebase functions:config:set service_account="$(cat service-account.json)"
> ```
> 
> I imported a service account json file to Firebase Cloud Functions, because I wanted to use the user management API of Firebase Admin SDK.

It didn't work

**Comment by dnhyde** [comment]
@Md-Abdul-Halim-Rafi 
> firebase functions:config:set service_account="$(cat service-account.json)"
Worked for me, I can see the config var with `firebase functions:config:get`. It did not work the first time because I was not in the project folder and did not select the firebase project on which to set the config variable, to select the firebase project use `firebase use --add`, the CLI will prompt you with the list of projects on your firebase console (assuming you are logged in in the CLI with `firebase login`)

**Comment by alekseykarpenko** [comment]
@dnhyde 
> firebase functions:config:set service_account="$(cat service-account.json)"

Seems this will not work while using in your json file any other value types except strings (e.g. boolean or number):
```json
{
   "test": {
        "hmm": true
    }
}
```
fails with:
```ssh
Error: HTTP Error: 400, Invalid value at 'variable.text' (TYPE_STRING), true
```

**Comment by rgant** [comment]
It seems reasonable to me that I should be able to do:

```
firebase functions:config:get > config.json
```

and then later:

```
firebase functions:config:set < config.json
```

It just makes sense to have these two commands be complementary. 

Having the config in a file allows for me to version control it and see how it has changed over time. 

It's unfortunate that the only way we have to accomplish this right now (using `env=$(cat config.json)`) also results in breaking my ability to have config.json be the actual values since I cannot wrap them in `{ env: ... }`.

**Comment by sloosh** [comment]
> "config:set:dev"

Sorry but when do you run the script "config:set:dev", I don't get it... thanks !

**Comment by sloosh** [comment]
> Just sharing my vanilla JS solution which works regarding which platform you develop on (Windows, MacOS, Linux) :
> 
> Using separate projects for dev/test/prod.
> 
> #### /.firebaserc
> ```json
> {
>   "projects": {
>     "dev": "my-project-name-dev",
>     "test": "my-project-name-test",
>     "prod": "my-project-name-prod"
>   }
> }
> ```
> 
> #### Config files
> JSON-files in `/functions/config` folder:
> 
> ```
> /functions/config/config.dev.json 
> /functions/config/config.test.json 
> /functions/config/config.prod.json 
> /functions/config/config.SAMPLE.json <-- only file tracked in git
> 
> Example content:
> {
>     "google": {
>         "key": "my-api-key",
>         "storage_bucket": "firebase-storage-bucket"
>     },
>     "another_vendor": {
>         "my_prop": "my value"
>     },
>     ...
> }
> ```
> 
> #### /functions/set-config.js
> ```js
> const fs = require('fs');
> const env = process.argv[2];
> 
> const configPath = `./config/config.${env}.json`;
> 
> if (!(configPath && fs.existsSync(configPath))) {
>     return;
> }
> 
> const collectConfigLines = (o, propPath, configLines) => {
>     propPath = propPath || '';
>     configLines = configLines || [];
>     for (const key of Object.keys(o)) {
>         const newPropPath = propPath + key;
>         if (typeof o[key] === 'object') {
>             collectConfigLines(o[key], newPropPath + '.', configLines);
>         } else if (o[key] != null && o[key] !== '') {
>             configLines.push(`${newPropPath}=${JSON.stringify(o[key])}`);
>         }
>     }
> }
> 
> const config = require(configPath);
> const configLines = [];
> collectConfigLines(config, '', configLines);
> 
> const cp = require('child_process');
> cp.execSync(`firebase -P ${env} functions:config:set ${configLines.join(' ')}`);
> ```
> 
> #### /functions/package.json
> ```
> ...
> "scripts": {
>     "config:set:dev": "node set-config dev",
>     "config:set:test": "node set-config test",
>     "config:set:prod": "node set-config prod",
>     ...
> },
> ...
> ```



> Just sharing my vanilla JS solution which works regarding which platform you develop on (Windows, MacOS, Linux) :
> 
> Using separate projects for dev/test/prod.
> 
> #### /.firebaserc
> ```json
> {
>   "projects": {
>     "dev": "my-project-name-dev",
>     "test": "my-project-name-test",
>     "prod": "my-project-name-prod"
>   }
> }
> ```
> 
> #### Config files
> JSON-files in `/functions/config` folder:
> 
> ```
> /functions/config/config.dev.json 
> /functions/config/config.test.json 
> /functions/config/config.prod.json 
> /functions/config/config.SAMPLE.json <-- only file tracked in git
> 
> Example content:
> {
>     "google": {
>         "key": "my-api-key",
>         "storage_bucket": "firebase-storage-bucket"
>     },
>     "another_vendor": {
>         "my_prop": "my value"
>     },
>     ...
> }
> ```
> 
> #### /functions/set-config.js
> ```js
> const fs = require('fs');
> const env = process.argv[2];
> 
> const configPath = `./config/config.${env}.json`;
> 
> if (!(configPath && fs.existsSync(configPath))) {
>     return;
> }
> 
> const collectConfigLines = (o, propPath, configLines) => {
>     propPath = propPath || '';
>     configLines = configLines || [];
>     for (const key of Object.keys(o)) {
>         const newPropPath = propPath + key;
>         if (typeof o[key] === 'object') {
>             collectConfigLines(o[key], newPropPath + '.', configLines);
>         } else if (o[key] != null && o[key] !== '') {
>             configLines.push(`${newPropPath}=${JSON.stringify(o[key])}`);
>         }
>     }
> }
> 
> const config = require(configPath);
> const configLines = [];
> collectConfigLines(config, '', configLines);
> 
> const cp = require('child_process');
> cp.execSync(`firebase -P ${env} functions:config:set ${configLines.join(' ')}`);
> ```
> 
> #### /functions/package.json
> ```
> ...
> "scripts": {
>     "config:set:dev": "node set-config dev",
>     "config:set:test": "node set-config test",
>     "config:set:prod": "node set-config prod",
>     ...
> },
> ...
> ```

Sorry but when do you run the script "config:set:dev", I don't get it... thanks !

**Comment by raseminiano00** [comment]
I'm getting an error on when running this firebase CI command
`firebase functions:config:set foo='{"bar":"something","faz":"other"}'`

The error was 
`Error: Invalid argument, each config value must have a 2-part key (e.g. foo.bar).`

**Comment by denkan** [comment]
@sloosh 
> Sorry but when do you run the script "config:set:dev" ? I don't get it... thanks !

For example, in one simpler project I deploy changes to Firebase manually (to a project for dev environment) and I have following in package.json:
```jsonp
"scripts": {
    "config:set:dev": "node set-config dev",
    "config:set:prod": "node set-config prod",
    "config:get": "firebase functions:config:get > .runtimeconfig.json",
    "serve": "npm run config:get && npm run build && firebase serve --only functions,hosting,storage",
    "watch": "nodemon --exec \"npm run build\"",
    "deploy:dev:functions": "npm run config:set:dev && firebase -P dev deploy --only functions",
    "deploy:dev:hosting": "firebase -P dev deploy --only hosting",
    "deploy:dev": "npm run config:set:dev && firebase -P dev deploy --only functions,hosting"
  },
```

So whenever I want to deploy changes in my functions to my dev project in Firebase, I use:
```shell
npm run deploy:dev:functions
```

The `deploy:dev:functions` command will first set the variables to the server, using `npm run config:set:dev` - and then run the deployment (`firebase -P dev deploy --only functions`).

**Comment by denkan** [comment]
> I'm getting an error on when running this firebase CI command
> `firebase functions:config:set foo='{"bar":"something","faz":"other"}'`
> 
> The error was
> `Error: Invalid argument, each config value must have a 2-part key (e.g. foo.bar).`

You need to rewrite the json into single props, as:
```
firebase functions:config:set foo.bar="something" foo.faz:"other"
```

**Comment by raseminiano00** [comment]
> @raseminiano00
> 
> > I'm getting an error on when running this firebase CI command
> > `firebase functions:config:set foo='{"bar":"something","faz":"other"}'`
> > The error was
> > `Error: Invalid argument, each config value must have a 2-part key (e.g. foo.bar).`
> 
> You need to rewrite the json into single props, as:
> 
> ```
> firebase functions:config:set foo.bar="something" foo.faz:"other"
> ```

The work around I found on this 
`firebase functions:config:set foo='{"bar":"something","faz":"other"}'`

is
`firebase functions:config:set foo.bar='{"faz":"something","qux":"other"}'`

is there any way I can set it directly to 'foo'?

**Comment by denkan** [comment]
@raseminiano00 
> `firebase functions:config:set foo.bar='{"faz":"something","qux":"other"}'`
>
> is there any way I can set it directly to 'foo'?

No. 
Not by using the CLI out of the box, afaik.
You need tricks - some specified in this thread.

**Comment by rgant** [comment]
Did that change? Because I have been doing this for months:

```
firebase functions:config:unset env && firebase functions:config:set env="$(cat functions/env.json)"

# env.json
{
  "mailchimp": {
    "api_key": "",
    "audience_id": ""
  },
  "site": {
    "base_url": "",
    "company": ""
  },
  "slack": {
    "webhook_host": "hooks.slack.com",
    "webhook_path": ""
  }
}

# use in functions
  const funcConfig: Config = config().env;
  const mcConfig: MailchimpConfig = funcConfig.mailchimp;
```

**Comment by tonioriol** [comment]
With the help of node, having a json config like this:


```js
//.runtimeconfig.prod.json
{
  "func1": {
    "send_notification": "true",
    "notification_email": "foo@bar"
  "fun2": {
    "client_secret": "asdf",
    "client_id": "sdg"
  }
}
```

```js
// config.js
const config = require('./.runtimeconfig.prod.json');


const stringifiedConfigsBySection = Object.entries(config).map(([key, value]) => {
  return Object.entries(value).map(([k, v]) => {
    return `${key}.${k}=${v}`;
  }).join(' ');
});

console.log(stringifiedConfigsBySection.join(' '));
```

Then you can do `firebase functions:config:set $(node config.js)`.

**Comment by MorenoMdz** [comment]
Offtopic but related question, can we list/print our ENV variables from the GCP cloud shell?

**Comment by morgs32** [comment]
@tonioriol happen to know how I could add some parentheses to that value? If I have some all caps in there then the firebase command breaks and if I call the firebase command directly it works.
```
firebase functions:config:set func1.send_notification="TRUE"
```

That works ^^^. But not `firebase functions:config:set $(node config.js)`

```
//.runtimeconfig.prod.json
{
  "func1": {
    "send_notification": "TRUE",
   }
}
```

**Comment by tonioriol** [comment]
> @tonioriol happen to know how I could add some parentheses to that value? If I have some all caps in there then the firebase command breaks and if I call the firebase command directly it works.
> 
> ```
> firebase functions:config:set func1.send_notification="TRUE"
> ```
> 
> That works ^^^. But not `firebase functions:config:set $(node config.js)`
> 
> ```
> //.runtimeconfig.prod.json
> {
>   "func1": {
>     "send_notification": "TRUE",
>    }
> }
> ```

No sorry, i haven't used that since then.

**Comment by dahu33** [comment]
Can we reopen this issue please?

**Comment by adinvadim** [comment]
I need this feature too. I'am using firebase set in my CD. Get secrets from Github Secrets and push their to the firebase config

**Comment by joantune** [comment]
This is ludicrous - we understand and we are grown up enough to just have that file on .gitignore - can you please support this? thanks!

**Comment by bswanwick** [comment]
take off the training wheels please

**Comment by johnico** [comment]
> Just sharing my vanilla JS solution which works regarding which platform you develop on (Windows, MacOS, Linux) :
> 
> Using separate projects for dev/test/prod.
> 
> #### /.firebaserc
> ```json
> {
>   "projects": {
>     "dev": "my-project-name-dev",
>     "test": "my-project-name-test",
>     "prod": "my-project-name-prod"
>   }
> }
> ```
> 
> #### Config files
> JSON-files in `/functions/config` folder:
> 
> ```
> /functions/config/config.dev.json 
> /functions/config/config.test.json 
> /functions/config/config.prod.json 
> /functions/config/config.SAMPLE.json <-- only file tracked in git
> 
> Example content:
> {
>     "google": {
>         "key": "my-api-key",
>         "storage_bucket": "firebase-storage-bucket"
>     },
>     "another_vendor": {
>         "my_prop": "my value"
>     },
>     ...
> }
> ```
> 
> #### /functions/set-config.js
> ```js
> const fs = require('fs');
> const env = process.argv[2];
> 
> const configPath = `./config/config.${env}.json`;
> 
> if (!(configPath && fs.existsSync(configPath))) {
>     return;
> }
> 
> const collectConfigLines = (o, propPath, configLines) => {
>     propPath = propPath || '';
>     configLines = configLines || [];
>     for (const key of Object.keys(o)) {
>         const newPropPath = propPath + key;
>         if (typeof o[key] === 'object') {
>             collectConfigLines(o[key], newPropPath + '.', configLines);
>         } else if (o[key] != null && o[key] !== '') {
>             configLines.push(`${newPropPath}=${JSON.stringify(o[key])}`);
>         }
>     }
> }
> 
> const config = require(configPath);
> const configLines = [];
> collectConfigLines(config, '', configLines);
> 
> const cp = require('child_process');
> cp.execSync(`firebase -P ${env} functions:config:set ${configLines.join(' ')}`);
> ```
> 
> #### /functions/package.json
> ```
> ...
> "scripts": {
>     "config:set:dev": "node set-config dev",
>     "config:set:test": "node set-config test",
>     "config:set:prod": "node set-config prod",
>     ...
> },
> ...
> ```

very nice  thank! 
can you add support for arrays and removing item from array?

``` x:["1","2"]```

when i will try to remove the "2" and running the script again nothing will happen

**Comment by ranouf** [comment]
> Did that change? Because I have been doing this for months:
> 
> ```
> firebase functions:config:unset env && firebase functions:config:set env="$(cat functions/env.json)"
> 
> # env.json
> {
>   "mailchimp": {
>     "api_key": "",
>     "audience_id": ""
>   },
>   "site": {
>     "base_url": "",
>     "company": ""
>   },
>   "slack": {
>     "webhook_host": "hooks.slack.com",
>     "webhook_path": ""
>   }
> }
> 
> # use in functions
>   const funcConfig: Config = config().env;
>   const mcConfig: MailchimpConfig = funcConfig.mailchimp;
> ```

Today in June 2025, when I do that, i have an error:
**Error: Invalid argument, each config value must have a 2-part key (e.g. foo.bar).**

I guess it's not working anymore :(
