### ISSUE TITLE
Firebase CLI doesn't properly detect JDK not being installed on macOS

### ISSUE THREAD

**Issue by peterfriese** [firebase/firebase-tools#4116]
## Problem

Newer versions of macOS don't have Java installed. Instead, Apple has a `java` stub binary at `/usr/bin/java`, which will issue the following message:

```
$ java
The operation couldn’t be completed. Unable to locate a Java Runtime.
Please visit http://www.java.com for information on installing Java.
```

(Launching with `java --help` or `java --version` yields the same message).

When trying to run the Emulator, this doesn't seem to be properly detected, so you end up with something like:

```
i  emulators: Starting emulators: firestore
⚠  firestore: Did not find a Cloud Firestore rules file specified in a firebase.json config file.
⚠  firestore: The emulator will default to allowing all reads and writes. Learn more about this option: https://firebase.google.com/docs/emulator-suite/install_and_configure#security_rules_configuration.
i  firestore: Firestore Emulator logging to firestore-debug.log
⚠  firestore: Fatal error occurred:
   Firestore Emulator has exited with code: 1,
   stopping all running emulators
i  firestore: Stopping Firestore Emulator
⚠  firestore: Error stopping Firestore Emulator
i  hub: Stopping emulator hub
```

Which is a bit misleading, since the problem isn't the missing rules file, but the missing Java Runtime.

### Solution
It seems that Apple's stub returns a non-zero error code:

```
$ java
The operation couldn’t be completed. Unable to locate a Java Runtime.
Please visit http://www.java.com for information on installing Java.

$ echo $?
1
```

This might help to detect this situation and show an error message along the lines of "It seems like you don't have a Java runtime installed - please follow this link to install one"

**Comment by dallarosa** [comment]
Went through the same problem and found out that the problem was java missing after looking at firestore-debug.log

**Comment by jgeary** [comment]
whats the solution to this? i want to run the firestore emulator on my (intel) mac. whats the cleanest way to do that?

**Comment by dallarosa** [comment]
Just go to java.com, download the JRE for the Intel Mac and install it.
I've done that it now everything is fine.

This is more a problem with the way firebase shows the error than a problem
with the tool itself, it should just say "you're missing Java and i need
you to install it" instead of giving this obscure error message and make
you go dive into log files (at least the log files are there)

2022年3月15日(火) 8:39 jgeary ***@***.***>:

**Comment by dallarosa** [comment]
Amazing! Thanks so much
