### ISSUE TITLE
ng add @angular/fire - init process / cursor input freezes on MacOS

### ISSUE THREAD

**Issue by astalea** [firebase/firebase-tools#4118]
### [REQUIRED] Environment info

**firebase-tools: 10.1.3**

**Platform: macOS 12.1**

### [REQUIRED] Test case

ng add @angular/fire gets stuck on project selection

### [REQUIRED] Steps to reproduce

enter "ng add @angular/fire"
follow steps
Cursor keys freeze on 
? Please select a project: (Use arrow keys or type to search)
❯ [CREATE NEW PROJECT] 
test-project

### [REQUIRED] Expected behavior

cursor up & down select options, return selects and progress

### [REQUIRED] Actual behavior

no keyboard input accepted

**Comment by tama3bb** [comment]
firebase-tools@10.1.0 freezes.
firebase-tools@10.0.1 works.

**Comment by bkendall** [comment]
I can replicate this (though it's a bit tricky since I have to do it through `ng`) but I don't see anything obvious as to why that's the case. @jamesdaniels may be able to help look as well

**Comment by RammAlvarez** [comment]
Same problem 

firebase-tools: 10.1.4
Platform: macOS 12.1

**Comment by HackPoint** [comment]
Same issue
"@angular/fire": "^7.2.0",
 "firebase": "^9.4.0",
Catalina 10.15.7 Mac i9
