### ISSUE TITLE
Firebas hosting gzip or Brotli is not working

### ISSUE THREAD

**Issue by akarabach** [firebase/firebase-tools#4119]
### [REQUIRED] Environment info

**firebase-tools:** 10.0.1

**Platform:** Windows

I have default configuration of firebase-tools and using github actions to deploy my bundle to firebase hosting, But in browser, I ses that gzip is not working for js files (bundle is about ~540kb)

![image](https://user-images.githubusercontent.com/12261380/152000077-e1b87eb7-a832-4499-ab17-7f0fb6fe4134.png)

just firebase deploy

### [REQUIRED] Expected behavior
gzip or brotli should out of the box 

### [REQUIRED] Actual behavior
gzip or brotli is not working as expected

**Comment by bkendall** [comment]
For production issues, could you reach out to us via https://firebase.google.com/support? We can look into your project there and debug - issues in this repo are really for the CLI itself.

Without digging into your specifics: Firebase Hosting will return the smallest-sized file of "identity", "gzip", and "brotli" - of whatever your browser supports. If the raw file (identity) is the smallest, we'd send that over the wire. I'd find that unlikely in most cases, but it's technically possible.
