### ISSUE TITLE
Not able select Firebase project

### ISSUE THREAD

**Issue by santoshgistto** [firebase/firebase-tools#413]
![tools](https://user-images.githubusercontent.com/12577046/28731108-3109fac8-73f0-11e7-8f54-f093fb6bb93f.png)

Arrow key buttons not working
OS : Ubuntu
Node version : 8.1.0
Npm version : 5.3.0
Firebase-tools version : 3.9.1

**Comment by mbleigh** [comment]
* What OS?
* What version of the Firebase CLI?
* What version of Node.js?
* Have you ever been able to make it work or is this a recent change?

**Comment by santoshgistto** [comment]
@mbleigh i have update the versions in ticket description and i am tried it first time on my machine

**Comment by mbleigh** [comment]
You need to update your Node version to 8.1.1 or later. There was a bug in 8.1.
