### ISSUE TITLE
Couldnt find FirebaseUtil.java in android studio......where to be created?

### ISSUE THREAD

**Issue by Abinayapssr** [firebase/firebase-tools#4133]
Please submit feature requests through our [support page](https://firebase.google.com/support/troubleshooter/report/features/).

**Comment by yuchenshi** [comment]
Sounds like you have a question for Android Studio but you've found the CLI repo. Please try posting on StackOverflow instead of 
contact [support](https://firebase.google.com/support/troubleshooter/report/features/).
