### ISSUE TITLE
firebase CLI not working

### ISSUE THREAD

**Issue by josejmoran** [firebase/firebase-tools#4140]
### [REQUIRED] Environment info

I downloaded the firebase CLI from: https://firebase.flutter.dev/docs/overview/#initialization and followed all the steps listed there to add firebase to my project, but I get the following error:

flutterfire configure
'git' is not recognized as an internal or external command,
operable program or batch file.
Building flutter tool...
Running pub upgrade...
i Found 0 Firebase projects. Selecting project trackmyhours-99c69.
FirebaseCommandException: An error occured on the Firebase CLI when attempting to run a command.
COMMAND: firebase --version
ERROR: The FlutterFire CLI currently requires the official Firebase CLI to also be installed, see https://firebase.google.com/docs/cli#install_the_firebase_cli for how to install it.

> firebase --version
10.1.4

I think this should be easier to configure. I followed all the steps as described in the web page.

**Platform:**

**Comment by bkendall** [comment]
I think you need to open up an issue on flutterfire's repository. If something's going wrong in one of their scripts, they should look into it. Take a look here: https://github.com/FirebaseExtended/flutterfire
