### ISSUE TITLE
Starting emulators forces downloading outdated cloud-firestore-emulator-v1.11.11.jar

### ISSUE THREAD

**Issue by eugvb** [firebase/firebase-tools#4142]
### [REQUIRED] Environment info

**firebase-tools:** 10.1.5

**Platform:** Windows 10, nodejs 16.4.0

### [REQUIRED] Test case
After run firebase emulators:start, begins downloading outdated emulators firestore, database and ui

### [REQUIRED] Steps to reproduce
1. Run firebase emulators:start
2. Download outdated emulators
3. Stop emulators
// to repeat
4. Run firebase init emulators
5. Download actual emulators
6. Go to step 1

### [REQUIRED] Expected behavior
Don't downgrade emulators

### [REQUIRED] Actual behavior
![image](https://user-images.githubusercontent.com/43745501/153090432-998de0ab-d9c3-4d5e-8464-849e16e68595.png)

**Comment by yuchenshi** [comment]
Each version of CLI comes with a version of the Firestore emulator and is designed to work with that version. I think you may have two different versions of Firebase CLI (`firebase-tools`) installed -- would you mind double checking `firebase --version` in each step?

Note that if you have `firebase-tools` installed as a **local** dependency (i.e. in `package.json`), a `npm run` script will use that instead, which may explain the version differences.

**Comment by eugvb** [comment]
I've solved this issue only after downgrading nodejs to v14.
This solutions helped me (Windows 10) and also it helped my colleague (macOS).

> Note that if you have firebase-tools installed as a local dependency (i.e. in package.json), a npm run script will use that instead, which may explain the version differences.

I have found local dependency firebase-tools:^8.0.0, right now, but in parent directory package.json, may be with nodejs v16 it couse problem
