### ISSUE TITLE
Firepit binaries are gigantic

### ISSUE THREAD

**Issue by rockwotj** [firebase/firebase-tools#4144]
From version 10.1.0 to version 10.1.1 there is a ~700MB increase in the firepit version of the binary. Can we restore it back to the ~100MB range?

<img width="1241" alt="image" src="https://user-images.githubusercontent.com/8669100/153117055-94aa2c53-4c4f-437b-b20c-f0ff6e3a0b2a.png">

**Comment by bkendall** [comment]
WHOA. That's a little scary. Wonder why that happened. I'll take a look.

**Comment by bkendall** [comment]
Muuuch better: https://github.com/firebase/firebase-tools/releases/tag/v10.2.0

**Comment by rockwotj** [comment]
Thanks for the speedy fix @bkendall! 🙏
