### ISSUE TITLE
'firebase init functions' uses outdated version of TypeScript

### ISSUE THREAD

**Issue by samatcolumn** [firebase/firebase-tools#4155]
If you use `firebase init functions` to start a fresh project with TypeScript you get version`^3.8.0`. There are a _lot_ of new features that have been released in `4.0+` which was announced 18 months ago. 

According to the Microsoft announcement post 4.0 is not considered a breaking change:
https://devblogs.microsoft.com/typescript/announcing-typescript-4-0/

**Comment by inlined** [comment]
The latest version of TypeScript _does_ make breaking changes if some linter settings are set (e.g. in the CLI we had to annotate all of our catch blocks to explicitly list `any` as the caught type even though that was disallowed in previous versions of TypeScript). That being said, I agree that we should update to the latest and greatest. Let's set the version to `^4.5.4`.
