### ISSUE TITLE
Unable to generate CI token with --no-localhost

### ISSUE THREAD

**Issue by gpfister** [firebase/firebase-tools#4159]
### [REQUIRED] Environment info

**firebase-tools:** 10.2.0

**Platform:** Ubuntu

### [REQUIRED] Test case

Run `firebase login:ci --no-localhost`, then try to deploy (`firebase deploy --token ...`)

### [REQUIRED] Steps to reproduce

1) firebase login:ci --no-localhost
2) firebase deploy --token ...

### [REQUIRED] Expected behavior

The token generated shoud work to deploy the project, just like when running `firebase login:ci` without `--no-localhost`

### [REQUIRED] Actual behavior

I get error : 

`Error: HTTP Error: 401, Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.`

To get it to work, I have to use the regular `firebase login:ci`, and copy paste from my browser the urls.

**Comment by prakashkgsuk** [comment]
I am trying to generate a firebase token on firebase CLI and authenticating via service account to run the **firebase login:ci** command. I have exported the GOOGLE_APPLICATION_CREDENTIALS env variable to the physical location of my service account json file (service account is having **Firebase App Distribution Admin** and 
**Firebase Develop Admin** roles ) but it still asks me to login through browser using my user account
Visit this URL on this device to log in:
https://accounts.google.com/o/oauth2/auth?client_id=xxxxxxx.....

My firebase version is - 10.2.2
I am running it on Google Cloud Shell (Debian OS)
What could be the issue, can you please help me with this?

**Comment by tosh** [comment]
I think I ran into this issue when trying to use firebase cli from within Github Codespaces

**Comment by prakashkgsuk** [comment]
I was able to resolve this by adding google cloud as authentication medium in Firebase app from firebase console.

**Comment by mbleigh** [comment]
I'm not able to reproduce this myself - I was able to successfully generate a CI token and use it to issue commands. Anyone experiencing this issue, please provide logs from running the command with `--debug`, especially the lines referencing auth:

```
[2022-04-18T20:23:12.581Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2022-04-18T20:23:12.582Z] > authorizing via --token option
```

For `GOOGLE_APPLICATION_CREDENTIALS` there should be no change in recent releases. It sounds like you found a workaorund.

**Comment by gpfister** [comment]
Hi, related to my original bug report, I don't know if I were too tired that day or if it was fix lately, but I was able to generate a CI token using the command `firebase login:ci --no-localhost`. I have the latest `firebase-tools`, versison 10.6.0, running on macOS 10.5 (arm64).

**Comment by soth4** [comment]
Cool
