### ISSUE TITLE
While running with Firestore Emulator cannot access remote Firestore db on other projects

### ISSUE THREAD

**Issue by TacB0sS** [firebase/firebase-tools#4164]
### [REQUIRED] Environment info

firebase tools: 10.2.0
node: 16
i  firestore: cloud-firestore-emulator-v1.13.1.jar...
i  database: firebase-database-emulator-v4.7.3.jar...
i  pubsub: pubsub-emulator-0.1.0.zip...
i  storage: cloud-storage-rules-runtime-v1.0.1.jar...
i  ui: ui-v1.6.4.zip...

macOS

### [REQUIRED] Test case
```
// running with emulator.. 
const local = getFirestore(initializeApp()).collection("collection-name")

// Service account of another project not the same one of the emulator.. 
const remote = getFirestore(initializeApp(serviceAccountProjectX)).collection("collection-name")

making a query on either one will return the same output, as if remote and local are connected to the same resource, although if printed to the console shows that are using completely different configurations
```

### [REQUIRED] Steps to reproduce
* initialize local emulator firestore and create a collection
* initialize remote firestore and create a same collection
* make a query on both
* same output

### [REQUIRED] Expected behavior

output of remote firestore expected to reflect its own content

### [REQUIRED] Actual behavior

see the data of the firestore emulator

**Comment by TacB0sS** [comment]
if I remove the Firestore emulator config from the firebase.json, everything works as expected..

**Comment by yuchenshi** [comment]
Mixing production and emulator usage is discouraged and as you may have seen, we're trying to make it hard to accidentally hit production. Would you mind sharing your use case (e.g. why would you want to talk to both at the same time)? We may be able to find a higher-level solution.

If mixing is still what you want to do, unfortunately, you may have to jump through hoops to find a workaround. If you intend to go down that route, we can help if you provide a standalone repro e.g. using a GitHub repository. I believe this may be related to your SDK setup or environment variables, and it is hard to tell just by looking at the snippet.

**Comment by TacB0sS** [comment]
We have a setup where we have a dev project for dev env, same for staging, and same for prod.. each with its own firebase,  firestore, bucket... etc.

I agree that in practice while running locally I would not want to mix local and prod (or even dev) environment's data, however, there are cases that I would like to import / export data from dev, staging or even prod to my local env (and in rare cases vice verse) for the sake of having an initial state and not reconstruct the entire collection of bugs troubleshooting and analyses.. and I want do it in runtime (from an Admin console page)

Given our setup I can argue that according to the logic you mentioned dev env should not be able access prod env database (I agree), but it could if I were to explicitly use a service account of prod project.. and I think it applies the same in this case..   default admin sdk should initialize pointing to the local emulator but if I choose to explicitly access a real database, then it is on me to use it wisely..

**Comment by yuchenshi** [comment]
Thanks for sharing your use case. As mentioned before, would you mind providing a standalone repro for us to look into this?

**Comment by TacB0sS** [comment]
Will need to find the time and create the simple repo to reproduce it.. will work on it
