### ISSUE TITLE
An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by Stas1967** [firebase/firebase-tools#4165]
Recently when starting firebase emulators in my angular project, this message appears in the console,
`It looks like you're using the development build of the Firebase JS SDK.
When deploying Firebase apps to production, it is advisable to only import
the individual SDK components you intend to use.

For the module builds, these are available in the following manner
(replace <PACKAGE> with the name of a component - i.e. auth, database, etc):

CommonJS Modules:
const firebase = require('firebase/app');
require('firebase/<PACKAGE>');

ES Modules:
import firebase from 'firebase/app';
import 'firebase/<PACKAGE>';

Typescript:
import firebase from 'firebase/app';
import 'firebase/<PACKAGE>';`
I have tried it with a new project without adding any connection to the database only (firebase init follow the steps and that's it) and the result is the same. I recently installed Solidworks for Makers and some java libraries have been installed. Maybe this can cause this problem. I can add documents to firestore, files to storage and users to authentication, what fails is Realtime database. I can't create lists or field
[database-debug.log](https://github.com/firebase/firebase-tools-ui/files/8055471/database-debug.log)

**Comment by fredzqm** [comment]
What's your local jdk version?
I am trying to reproduce this.

**Comment by Stas1967** [comment]
Checking with cmd (java -version) i find this.
openjdk version "1.8.0_302"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_302-b08)
OpenJDK 64-Bit Server VM (Temurin)(build 25.302-b08, mixed mode)

**Comment by TheoOliveira** [comment]
I am facing the same issue. I was heavily testing using local emulators and out of the blue this starts to happen.

`WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.netty.util.internal.ReflectionUtil (file:/home/dorvo/.cache/firebase/emulators/firebase-database-emulator-v4.11.0.jar) to field sun.nio.ch.SelectorImpl.selectedKeys
WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
16:54:30.741 [NamespaceSystem-akka.actor.default-dispatcher-4] INFO akka.event.slf4j.Slf4jLogger - Slf4jLogger started
16:54:30.944 [main] INFO com.firebase.server.forge.App$ - Listening at 127.0.0.1:9000
16:54:45.347 [NamespaceSystem-akka.actor.default-dispatcher-4] INFO com.firebase.core.namespace.NamespaceActor - serlares-pass-dev successfully activated FBKV (SurveyIdle(0)) wait: 160ms, init: 0ms
16:54:45.410 [NamespaceSystem-blocking-namespace-operation-dispatcher-6] INFO com.firebase.core.namespace.StateManager - Namespace serlares-pass-dev status Active to Active
16:54:45.449 [NamespaceSystem-blocking-namespace-operation-dispatcher-6] INFO com.firebase.core.namespace.StateManager - Namespace serlares-pass-dev status Active to Active
16:54:45.464 [NamespaceSystem-blocking-namespace-operation-dispatcher-6] INFO com.firebase.core.namespace.StateManager - Namespace serlares-pass-dev status Active to Active
16:54:45.478 [NamespaceSystem-blocking-namespace-operation-dispatcher-6] INFO com.firebase.core.namespace.StateManager - Namespace serlares-pass-dev status Active to Active
16:54:45.491 [NamespaceSystem-blocking-namespace-operation-dispatcher-6] INFO com.firebase.core.namespace.StateManager - Namespace serlares-pass-dev status Active to Active
16:54:45.503 [NamespaceSystem-blocking-namespace-operation-dispatcher-6] INFO com.firebase.core.namespace.StateManager - Namespace serlares-pass-dev status Active to Active
16:54:45.516 [NamespaceSystem-blocking-namespace-operation-dispatcher-6] INFO com.firebase.core.namespace.StateManager - Namespace serlares-pass-dev status Active to Active
16:54:45.530 [NamespaceSystem-blocking-namespace-operation-dispatcher-6] INFO com.firebase.core.namespace.StateManager - Namespace serlares-pass-dev status Active to Active
16:54:45.548 [NamespaceSystem-blocking-namespace-operation-dispatcher-6] INFO com.firebase.core.namespace.StateManager - Namespace serlares-pass-dev status Active to Active
16:55:34.645 [NamespaceSystem-akka.actor.default-dispatcher-5] INFO com.firebase.core.namespace.NamespaceActor - fake-server successfully activated FBKV (SurveyIdle(0)) wait: 3ms, init: 0ms
17:27:26.903 [Thread-0] INFO com.firebase.server.forge.App$ - Attempting graceful shutdown.
17:27:26.927 [NamespaceSystem-akka.actor.default-dispatcher-36] INFO com.firebase.core.namespace.Terminator$Terminator - 2 actors left to terminate: serlares-pass-dev, fake-server
17:27:26.930 [NamespaceSystem-akka.actor.default-dispatcher-73] INFO com.firebase.core.namespace.NamespaceActor - stopped namespace actor for fake-server
17:27:26.930 [NamespaceSystem-akka.actor.default-dispatcher-36] INFO com.firebase.core.namespace.DeadLetterResponder - Message CloseDataClient(Websockets) meant for other actor (akka://NamespaceSystem/user/serlares-pass-dev/$d) went to deadletter actor
17:27:26.934 [NamespaceSystem-akka.actor.default-dispatcher-84] INFO com.firebase.core.namespace.NamespaceActor - stopped namespace actor for serlares-pass-dev
17:27:26.937 [Thread-0] INFO com.firebase.server.forge.App$ - Graceful shutdown complete.
`

**Comment by fredzqm** [comment]
A bit busy today. @jmwski could you help look into this?

**Comment by FlyAtNight-cup** [comment]
when I closed local http proxy, It works.
