### ISSUE TITLE
Request to add/link new provider to the account results in 501

### ISSUE THREAD

**Issue by Junaid-Ahm** [firebase/firebase-tools#4170]
### [REQUIRED] Environment info

**firebase-tools:** 10.20.0

**Platform:** Ubuntu 20.04 x86_64

### [REQUIRED] Test case

This issue is only happening in emulator. Works fine with actual firebase project.

```
{
  "error": {
    "code": 501,
    "message": "linkProviderUserInfo is not implemented yet.",
    "errors": [
      {
        "message": "linkProviderUserInfo is not implemented yet.",
        "reason": "unimplemented"
      }
    ],
    "status": "NOT_IMPLEMENTED"
  }
}
```

### [REQUIRED] Steps to reproduce

1. Create an account in emulator (eg via firebase admin SDK's create user)
2. Attempt to add/link new provider to the existing account via update user (eg via firebase admin SDK's update user), which makes the POST request to endpoint `/accounts:update` results in the above error.

### [REQUIRED] Expected behaviour

Should add/link the provider info to the account. 

### [REQUIRED] Actual behaviour

Returns error with above error message.

**Comment by yuchenshi** [comment]
Hi, thanks for filing this issue! We are unable to promise any timeline for this, but if others also have this issue, adding a +1 on this issue can help us prioritize adding this to the roadmap.

(Googler-only internal tracking bug: b/222136653)

**Comment by yuchenshi** [comment]
FYI, we're also accepting Pull Requests for this feature. A good place to start is https://github.com/firebase/firebase-tools/blob/daa604a78cc648abae814350020aa4becb5ce207/src/emulator/auth/operations.ts#L977

**Comment by Junaid-Ahm** [comment]
@yuchenshi any plans for this?

**Comment by Junaid-Ahm** [comment]
@prameshj Can you also please review this and raise an internal ping for a followup?

**Comment by prameshj** [comment]
@malcolmdeck

**Comment by Junaid-Ahm** [comment]
@malcolmdeck Looking forward to your thoughts on this?

**Comment by christhompsongoogle** [comment]
We're aware of the issue but don't have a timeline on a resolution.

**Comment by NateMay** [comment]
Are there any other mechanisms to seed users in the emulator with providers linked? I can't seem to set provided data with `createUser()` or `updateUser()` so my team is currently forced to manually link providers within the UI.

**Comment by Junaid-Ahm** [comment]
@yuchenshi @christhompsongoogle @prameshj @joehan still waiting a timeline on this - opened in Feb'22

**Comment by christhompsongoogle** [comment]
Thanks for following up, but I have no updates to share. The fastest way to get this resolved would be to try your hand at a fix via Yuchen's link above.

**Comment by paulrostorp** [comment]
I've implement this as suggested by @yuchenshi in #6291.
I've published it to npm [here](https://www.npmjs.com/package/@paulrostorp/firebase-tools) as `@paulrostorp/firebase-tools`
