### ISSUE TITLE
HTTPS trigger securityLevel is overwritten on function re-deploy

### ISSUE THREAD

**Issue by Alex-Bubblemaster** [firebase/firebase-tools#4171]
### [REQUIRED] Environment info

**firebase-tools:** 10.2.0

**Platform:** macOS

### [REQUIRED] Test case

Using the [getting started with Firebase functions](https://firebase.google.com/docs/functions/get-started) article deploy and redeploy a function. The Require HTTPs flag is removed when the function is updated.

### [REQUIRED] Steps to reproduce

1. Create a GCP project in the Cloud Console
2. Follow steps 1-3 from the article
3. Edit `index.js` to include the `helloWorld` function
```
const functions = require("firebase-functions");
exports.helloWorld = functions.https.onRequest((request, response) => {
  functions.logger.info("Hello logs!", {structuredData: true});
  response.send("Hello from Firebase!");
});
```
4. Deploy the function `firebase deploy --project PROJECT_ID --only functions:helloWorld`
5. Go back to the console, click edit. The Function has the `Require HTTPS` flag enabled
6. Execute the `deploy` command again
7. Go back to Cloud Console, edit the function 
8. The function no longer has the `Require HTTPS` flag

### [REQUIRED] Expected behavior

The function retains the `Require HTTPS` flag

### [REQUIRED] Actual behavior

The `Require HTTPS` flag is removed

### Additional information

@inlined enforced HTTPS in newly created functions in the [createV1Function](https://github.com/firebase/firebase-tools/blob/master/src/deploy/functions/release/fabricator.ts#L212-L214) which enables the flag (awesome)

However, when we re-deploy, the [updateV1Function](https://github.com/firebase/firebase-tools/blob/master/src/deploy/functions/release/fabricator.ts#L325) sends the `updateMask` which contains the `httpsTrigger` field but the trigger is an empty object. 

Either `httpsTrigger` should not be sent as part of the `updateMask` properties or enforce HTTPs in the `updateV1Function` as well.

<img width="1105" alt="image" src="https://user-images.githubusercontent.com/10980842/154325313-e9a288a8-5301-46ad-9486-2f8e35102394.png">

**Comment by inlined** [comment]
@colerogers Solving this directly in the `functionFromEndpoint` code is technically a breaking change because it would set the value on existing functions which might rely on HTTP traffic. I'd take a look at `proto.fieldMasks` to not include a property as a field mask if it's an empty object.
