### ISSUE TITLE
Unable to upload app to distribution when app has not been released on play store

### ISSUE THREAD

**Issue by StephenHodgson** [firebase/firebase-tools#4183]
[Fastlane](https://docs.fastlane.tools/getting-started/android/beta-deployment/#uploading-your-app), [Firebase REST API](https://firebase.google.com/docs/reference/app-distribution/rest/v1/upload.v1.projects.apps.releases/upload), [gradle](https://firebase.google.com/docs/app-distribution/android/distribute-gradle), and [firebase console in web browser](https://firebase.google.com/docs/app-distribution/android/distribute-console), all allow users to upload apks and app bundles to firebase app distribution without the application needing to be published on the play store, but the firebase-tools cli fails with the response:

```This app is not published in the Google Play console.```

This specific feature and functionality ***does not require*** that the application first be published on play console to be able to downloaded and installed with App Tester using the other distribution tools outlined above. It seems strange that this tool would be the only one to fail this check and the others work as intended.

### [REQUIRED] Environment info

**firebase-tools:** latest

**Platform:** windows

### [REQUIRED] Test case

User can upload unpublished apps to firebase app distribution using firebase-tools.
User can download and install unpublished apps using App Tester.

### [REQUIRED] Steps to reproduce

- Create a new firebase project
- Create a new android application
- Setup firebase with the new android application
- (✅ passes) Attempt to upload the application to distribution using one of the methods listed above (other than firebase-tools)
- (❌ fails) Attempt to upload the application to distribution using the firebase-tools

### [REQUIRED] Expected behavior

Firebase tools will upload the application to distribution without requiring the application to first be published to play store

### [REQUIRED] Actual behavior

Uploading app to distribution fails because the application isn't published on the app store, even though other valid alternative methods will successfully be able to upload the application to distribution and make it available to install and test using App Tester

**Comment by melih-veloxia** [comment]
We're facing the same issue with Firebase CLI uploads right now.

**Comment by StephenHodgson** [comment]
Did a deep dive into the code today. 

Here's the line in question:
https://github.com/firebase/firebase-tools/blob/4349494edcdba5fb6ae66df13591bf2e6ea2c360/src/commands/appdistribution-distribute.ts#L81

It seems to me that this likely shouldn't be an error but maybe a warning.

**Comment by yuchenshi** [comment]
@tonybaroneee Would you mind looking into this or pass this on to the right person?

**Comment by lfkellogg** [comment]
Hi @StephenHodgson - to clarify, are you uploading AABs or APKs?

(For AABs, the app does in fact have to be published in Google Play. The specific requirements are listed in the AAB setup documentation for each client, under [Before you begin](https://firebase.google.com/docs/app-distribution/android/distribute-fastlane?apptype=aab#before_you_begin).)

**Comment by StephenHodgson** [comment]
@lfkellogg I was building an apk to upload

**Comment by StephenHodgson** [comment]
I tested with both abb and apk versions and the other distribution tools listed above still allows you to upload to firebase without it being published on google play.

**Comment by lfkellogg** [comment]
@StephenHodgson OK, thanks.

Can you please provide the full debug logs (using the `--debug` flag) from when you run the `appdistribution:distribute` command (removing any sensitive information first, such as email addresses or app IDs)?

**Comment by aprilmintacpineda** [comment]
This is happening to me as well

![image](https://user-images.githubusercontent.com/21032419/161057926-10307dfd-1b9e-4920-8890-71486aa9223d.png)

**Comment by lfkellogg** [comment]
@aprilmintacpineda When uploading AABs, the app does in fact have to be published in Google Play. The specific requirements are listed in the AAB setup documentation for each client, under [Before you begin](https://firebase.google.com/docs/app-distribution/android/distribute-fastlane?apptype=aab#before_you_begin).

**Comment by lfkellogg** [comment]
@StephenHodgson I'm going to close this issue since we haven't heard from you in a while. If you are still seeing the issue when uploading APKs, please post your debug logs and we can continue the investigation.

Just to reiterate, this behavior is expected when uploading AABs. See [each client's AAB setup docs](https://firebase.google.com/docs/app-distribution/android/distribute-fastlane?apptype=aab#before_you_begin) for more info.

**Comment by StephenHodgson** [comment]
@lfkellogg no problem, we ended up using a different method to upload.

**Comment by aprilmintacpineda** [comment]
Uploading APK worked.

**Comment by nzkn** [comment]
Hey, I am receiving similar issue when uploading aab.
```
firebase appdistribution:distribute ...
Error: "This app is not published in the Google Play console.
```

App is published for internal testing:
<img width="835" alt="Screenshot 2023-04-24 at 11 27 45" src="https://user-images.githubusercontent.com/69199372/233941529-c1891d4e-73f5-4229-816c-ba08ee5a7264.png">

The firebase still says that app is not on a published track.
<img width="824" alt="Screenshot 2023-04-24 at 11 28 21" src="https://user-images.githubusercontent.com/69199372/233941598-c73c40ee-4093-4616-b152-9c7f4f498103.png">

So the app is published in one of the tracks but the issue remains. Should I wait a bit more and the warning will disappear or I did do something wrong?

**Comment by lfkellogg** [comment]
@nzkn @FDuhen When you check the [App Dashboard](https://support.google.com/googleplay/android-developer/answer/9859454), you app is considered published if the app is showing one of the following statuses: Internal testing (not Draft internal testing), Closed testing, Open testing, or Production. What status do you see?

**Comment by Kaddtechnologies** [comment]
this is still an issue in 2024.

apk works but aab doesn't. There should be no constraint on an app being in the play store as internal non public apps can't be found.

this constraint needs to be removed

**Comment by ChristopheTrain** [comment]
What about companies that use a private Play Store? To be honest, blocking the upload of an AAB if the app is not in the Play Store has not been thought through very well.

With App Center shutting down, we planned to use Firebase to store our builds and distribute them to our testers. However, since we use a private Play Store, we now have to unpack the AAB, convert it to an APK, save the AAB in Azure Artifacts for deployment to the Play Store, and send the APK to Firebase for our testers.

This is incredibly frustrating. I really hope you reconsider lifting this restriction.

**Comment by noloman** [comment]
APK still doesn't work for me

**Comment by martipello** [comment]
i was also getting "integrationState": "APP_NOT_PUBLISHED" 
my states are 
Production Inactive
Open testing Inactive
Closed testing Inactive
Internal testing Active Not reviewed

switching from aab to apk fixed the issue

**Comment by ppamorim** [comment]
The issue remains, we can't publish builds to our testers even when the Internal testing is configured and published. Google please fix this issue.

**Comment by allco** [comment]
We have same problem. Why the issue is closed when it is not resolved and there is no workaround?
