### ISSUE TITLE
environment variable using .env doesn't seem to update

### ISSUE THREAD

**Issue by xxdd13** [firebase/firebase-tools#4192]
### [REQUIRED] Environment info

**firebase-tools:** 10.2.1

**Platform:** macOS 12

### [REQUIRED] Test case

Using .env, set NAME="AAA" and deploy a v2 function. Then change NAME in the .env file to something else, such as "BBB" and redeploy the function. The environment variable should be updated but doesn't.

### [REQUIRED] Steps to reproduce

Initialize a new project with firebase-tools, I chose just functions and used typescript

create a .env file
```env
NAME="AAA"
```

add a v2 onRequest function the src/index.ts 
```ts
import {onRequest} from "firebase-functions/v2/https";

export const hello = onRequest((request, response) => {
  response.send(`NAME = ${process.env.NAME} `);
});

```

deploy the function
```bash
firebase deploy --only functions:hello
```

visite the function in browser and it does say NAME = AAA
<img width="227" alt="image" src="https://user-images.githubusercontent.com/26791482/154605578-ab558d83-e131-4aa3-ab35-f925ffa9371b.png">

Then I updated the .env file
```env
NAME="BBB"
```
redeploy the function
```bash
firebase deploy --only functions:hello
```
Visited the url again but it still says NAME = AAA
<img width="234" alt="image" src="https://user-images.githubusercontent.com/26791482/154605714-65c5c630-3dd9-4130-b9b5-28a4ee257dc3.png">

I went to the GCP console to check the variables
https://console.cloud.google.com/functions/details/us-central1/hello?env=gen2&project=PROJECT_ID
<img width="269" alt="image" src="https://user-images.githubusercontent.com/26791482/154605946-31db40c2-0d4b-4274-9dfc-96e724a80dfc.png">

The cloud run console
<img width="991" alt="image" src="https://user-images.githubusercontent.com/26791482/154606095-59a97dd0-2518-4588-a2fe-229485be2d58.png">

checking the source in cloud functions, the .env does contain the NAME="BBB"
<img width="902" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/26791482/154606418-5a63f378-fa4e-4674-be02-ed9b5aadd060.png">

### [REQUIRED] Expected behavior

Updating .env file and redeploy should update the runtime environment variables

### [REQUIRED] Actual behavior
After an environment variable is set, it can not be updated via redeploy. Deleting the existing function then redeploy is required

**Comment by JuanJTorres11** [comment]
@taeold I'm having this exact behavior with functions v1. I'm updating the .env file and I can check in the source code in the GCP console that the new values are updated, but when calling the function. It keeps using the original .env value

**Comment by munroAllie** [comment]
@JuanJTorres11 You solve this, I too have this issue.

**Comment by JuanJTorres11** [comment]
> @JuanJTorres11 You solve this? I too have this issue.

You have to delete the function and deploy it again.

**Comment by r-dev-limited** [comment]
Have similar issue, my functions are deployed successfully but some miss ENV variables, I am not sure why
