### ISSUE TITLE
[emulator] onMetadataUpdate triggers on img uploaded

### ISSUE THREAD

**Issue by GrandSchtroumpf** [firebase/firebase-tools#4202]
### [REQUIRED] Environment info

**firebase-tools:** 10.2.0
**Platform:** Windows

### [REQUIRED] Test case
In the emulator `onMetadataUpdate` triggers on upload in the storage while this is not the case with the online version.

### [REQUIRED] Steps to reproduce
Using the emulators suite, in a cloud function create two triggers : 
```typescript
export const onMetadataChange = storage.bucket().object().onMetadataUpdate(() => {
  console.log('Metadata Changed');
});
export const onFinalize = storage.bucket().object().onFinalize(async object => {
  console.log('Finalized');
});
```

Upload an image on the bucket: both methods are triggered. But online only the `onFinalize` is triggered.

### [REQUIRED] Expected behavior
Emulator should behave the same as the online version

### [REQUIRED] Actual behavior
In the emulator `onMetadataUpdate` triggers on upload

**Comment by taeold** [comment]
@colerogers
