### ISSUE TITLE
Installation: Error: Cannot find module 'buffer-shims'

### ISSUE THREAD

**Issue by bogacg** [firebase/firebase-tools#421]
### Version info

**node** : 8.2.1

**npm** :  5.3.0

**OS**: Windows 10

### Steps to reproduce

`npm i -g firebase-tools`

### Expected behavior

Installs

### Actual behavior

Throws this error: 
```
> node-pre-gyp install --fallback-to-build --library=static_library

module.js:487
    throw err;
    ^

Error: Cannot find module 'buffer-shims'
    at Function.Module._resolveFilename (module.js:485:15)
```

**Comment by bogacg** [comment]
Uninstall & re-Install seemes to work after getting this error.

**Comment by ajostergaard** [comment]
Uninstall and re-install shouldn't be required though and bug was clearly not fixed... :-/
