### ISSUE TITLE
functions (emulator): Error: The downloaded data did not match the data from the server. To be sure the content is the same, you should download the file again.

### ISSUE THREAD

**Issue by bytewiz** [firebase/firebase-tools#4228]
### [REQUIRED] Environment info

**firebase-tools:** firebase-tools@9.12.1

**Platform:** Firebase Functions

### [REQUIRED] Test case

I followed and used the sample in functions-samples to generate a thumbnail of the image uploaded, which is a trigger on storage. It works fine in the regular environment. This error pops up when the file is uploaded and the function trigged by new file is fired. (this is the source code that is throwing the error with the emulator: https://github.com/firebase/functions-samples/tree/main/generate-thumbnail) 

This is the error:

`functions: Error: The downloaded data did not match the data from the server. To be sure the content is the same, you should download the file again.`

The upload of file work fine but the admin SDK function errors out with the above.

### [REQUIRED] Steps to reproduce

1. Run functions, storage emulator.
2. Upload file
3. Trigger function which listens for new storage objects
4. 💥  (error)

### [REQUIRED] Expected behavior

That there is no content mismatch when the function tries to download and compress the file.

### [REQUIRED] Actual behavior

Errors out and function is killed.

**Comment by yuchenshi** [comment]
@bytewiz Would you mind posting the full stack trace? That can help us triage if this is an issue in functions emulator, storage emulator, or the sample code.

**Comment by jeroenkroese** [comment]
This could be related to https://github.com/firebase/firebase-tools/issues/3469 and a few other issues, which are supposedly solved by PR https://github.com/firebase/firebase-tools/pull/3647. However, this PR has been waiting for a review for a few months now.. Must be a frustrating experience for the contributing author @rhodgkins
