### ISSUE TITLE
Deploying a function with an invalid reference gives poor warning/error

### ISSUE THREAD

**Issue by ahaverty** [firebase/firebase-tools#423]
### Version info
firebase --version: 3.9.2
firebase-tools: 4.2.0
firebase-functions: 0.6.1

### Steps to reproduce

Attempt to deploy a firebase function with a dollar ($) character in the reference path.
```javascript
const sampleFunction = functions.database.ref('/mySampleFunction/${postId}').onCreate(event =>{
    console.log(`New post with id: ${postId} created.`);
});
```

### Expected behavior

_I'm aware it's invalid syntax for a reference, but I was in the mindset of writing [javascript template literal](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) strings_ 🙃 _, and feel like I'm not going to be the last to mistake it._

Function fails to deploy with some indication that the syntax is incorrect.

### Actual behavior

The function attempts to deploy and actually doesn't fail until the timeout is reached (i.e. it attempts to deploy for about 20 seconds before eventually failing, hence why I'm raising)
I assumed it was some network/remote issue with firebase functions and contacted support before realising what I did.

**Comment by laurenzlong** [comment]
Thanks for filing @ahaverty . We're aware of this issue and will be addressing it on 2 fronts:
- server side validation of reference paths
- SDK validation of reference paths so the CLI will give you a warning right away before even trying to deploy.

**Comment by adamduren** [comment]
I found that this also happens if you accidentally leave a trailing slash in the document path as well if anyone comes across this issue and is looking for another possible solution.
