### ISSUE TITLE
Firebase serve --only functions appends ProjectID and Region

### ISSUE THREAD

**Issue by cidylle** [firebase/firebase-tools#425]
Currently when using <code>firebase serve --only functions</code> the resulting url is appended with my project name and the region such as: <code>http://localhost:5000/<project-name>/<region>/my-function-name</code>. 

This is currently breaking some of my code when trying to use `serve` to test my firebase functions.  Any suggestions on how to handle this ?

**Comment by laurenzlong** [comment]
Hey @cidylle this is expected behaviour. What do you mean by it's breaking your code?

**Comment by laurenzlong** [comment]
As well, please the issues template next time so we capture all the necessary info.
