### ISSUE TITLE
Unstable ordering of *.env generated by firebase ext:export

### ISSUE THREAD

**Issue by therefromhere** [firebase/firebase-tools#4256]
### [REQUIRED] Environment info

**firebase-tools:** 10.2.2

**Platform:** Ubuntu

### [REQUIRED] Test case

In a project with a firebase extension installed (eg firebase/firestore-bigquery-export), firebase ext:export would ideally
product stable env files.

It doesn't, I've not debugged but my hunch this is due to JS dict ordering?

Could the tool be updated to sort the env vars by name before output, so that the files are stable?

### [REQUIRED] Steps to reproduce

```
firebase ext:export -f
git commit -a
firebase ext:export -f
git diff
```

### [REQUIRED] Expected behavior

Consecutive runs of `firebase ext:export` would produce `extensions/*.env` files that are stable.

### [REQUIRED] Actual behavior

The *.env file line order changes with each run.

**Comment by joehan** [comment]
This is a very reasonable feature request - I'll take some time to work on it this week.
