### ISSUE TITLE
Functions emulator verification missing

### ISSUE THREAD

**Issue by MonteDan** [firebase/firebase-tools#4259]
Hello, I've been trying to call a function that reads and edits a document from my app on localhost and I'm getting an 'error':
```
{"verifications":{"app":"MISSING","auth":"MISSING"},"logging.googleapis.com/labels":{"firebase-log-type":"callable-request-verification"},"severity":"INFO","message":"Callable request verification passed"}
```
I'm connected to Firebase emulators.
```
import { httpsCallable } from 'firebase/functions';
import { connectFunctionsEmulator, getFunctions } from 'firebase/functions';

const functions = getFunctions(getApp());
connectFunctionsEmulator(functions, 'localhost', 5001);

const writeInDocument = httpsCallable(functions, "writeInDocument");
writeInDocument({content:"hello world"})
```

### [REQUIRED] Environment info
firebase-tools 10.2.2

firebase --version: 10.1.0
**firebase-tools:**

Windows

**Comment by taeold** [comment]
@MonteDan By design, emulator will bypass all token verification (since we know you are testing).

The log lines isn't relevant to the failure you described. I suspect your error is somewhere else?
