### ISSUE TITLE
Access-Control-Allow-Credentials headers not being set on localhost on 10.2.2

### ISSUE THREAD

**Issue by vpanyushenko** [firebase/firebase-tools#4261]
### [REQUIRED] Environment info

`firebase-tools@10.2.2`

**firebase-tools:10.2.2**

MacOS

### [REQUIRED] Test case

Running a local express server that hosts an API on port 5001. Frontend runs on port 3000. The express is correctly configured with the `cors` middleware which accepts localhost:5001 and localhost:3000. The request failed due to: 

```js
"Access to fetch at 'http://localhost:5001/px-platform-dev-a1ec4/us-central1/api/v1/auth/login' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Credentials' header in the response is '' which must be 'true' when the request's credentials mode is 'include'."

```

This could have something to do with #4227 but I'm not sure. 

### [REQUIRED] Steps to reproduce

See above

### [REQUIRED] Expected behavior

The request should pass preflight. This is not an issue with firebase-tools@10.2.1

### [REQUIRED] Actual behavior

It fails preflight so nothing get's logged to the terminal.

**Comment by yuchenshi** [comment]
Would you mind posting a minimal repro of your server and maybe also HAR files? This can help us look into the headers
