### ISSUE TITLE
Storage emulator does not respect rules after firebase-tools@10.1.5

### ISSUE THREAD

**Issue by rcb4t2** [firebase/firebase-tools#4268]
### [REQUIRED] Environment info

**firebase-tools: 10.2.2**

**Platform: macOS 11.6.4 (M1 processor)**

### [REQUIRED] Test case

I don't have the time to do this right now, but will try to add one

### [REQUIRED] Steps to reproduce

Add JS SDK firebase auth V9
Add JS SDK storage compat V8

Run the local emulator

Upload a file to storage that would be allowed by rules

### [REQUIRED] Expected behavior

Upload succeeds when rules allow it

### [REQUIRED] Actual behavior

Storage upload operation fails with caught error "not authorized", the same as when the rules do not allow the operation

No issues in production, the problem is just with the emulator

Our codebase has been working for several months with no issues. `firebase-tools@10.1.5` has no issue with identical code

**Comment by tonyjhuang** [comment]
Hi @rcb4t2, sorry you're running into this issue. For now I'd recommend to revert back to the last working version of the emulator.

To help us debug further, can you see if the issue persists when running off of the latest version of master?

**Comment by rcb4t2** [comment]
Thanks @tonyjhuang ! What's the best way to install firebase-tools from the latest master?

I tried `yarn global add https://github.com/firebase/firebase-tools.git#master` but it failed at the tsc build step

**Comment by tonyjhuang** [comment]
We actually just released https://github.com/firebase/firebase-tools/releases/tag/v10.3.0 today. Can you see if that helps solve your issue?

**Comment by rcb4t2** [comment]
@tonyjhuang Thanks! I'm getting a different error now on 10.3.0
`Firebase Storage: An unknown error occurred, please check the error payload for server response. (storage/unknown)`

Emulator logs do not show anything from the error

Please note also that I am using the V9 auth library, and still using the V8 compat version of storage. Not sure if that's part of the problem. It's on our roadmap to update storage to V9 but we're not there yet

**Comment by rcb4t2** [comment]
@tonyjhuang FWIW I converted our storage usage to V9 (we only use it in a few places, was pretty easy) and everything seems to be working as expected

Can you clarify that the `ref` method from storage can accept the public download URL as the url argument? It seems V9 no longer has a getRefFromURL method. It appears to be working as expected when passing the value of getPublicDownloadURL but wanted to double-check. Thanks!

**Comment by tonyjhuang** [comment]
I would defer to our public documentation: https://firebase.google.com/docs/reference/js/storage.md#ref

**Comment by tonyjhuang** [comment]
Glad you were able to find a fix, I'm going to close this issue now.
