### ISSUE TITLE
Error when deploy project

### ISSUE THREAD

**Issue by Txucishvili** [firebase/firebase-tools#427]
Error: Cannot understand what targets to deploy. Check that you specified valid targets if you used the --only or --except flag. Otherwise, check your firebase.json to ensure that your project is initialized for the desired features.

**Comment by mbleigh** [comment]
The error message has some pretty clear instructions... You're going to
need to be more specific about your project setup if you think there's
something wrong :)

**Comment by Txucishvili** [comment]
firebase.json is empty

**Comment by mbleigh** [comment]
What are you trying to deploy? If you don't have a functions directory or
configuration defined in json, there is nothing to deploy.
