### ISSUE TITLE
Firebase Hosting - Website deploy - failed: retries exhausted after 6 attempts

### ISSUE THREAD

**Issue by patbranchaud** [firebase/firebase-tools#4279]
Hello, we are experiencing a problem when deploying files on Firebase. Found multiple people with a similar problem but none of the solution is working for us.

We are building static websites with Gatsbyjs / React using Github actions and deploying to Firebase with this https://github.com/w9jds/firebase-action using this line : 

`firebase deploy --only hosting:alias --debug`

We are building multiple websites with the script within the Github actions and some work and other don't. It's complicated to troubleshoot, I'm looking for way to understand what is causing the problem more than a solution.

It is failing on different files every time we run the script.

That being said, we are having the same result when building the website locally and deploying on Firebase.

@kmcnellis you might understand the problem since you've been involved in similar issues. 

### [REQUIRED] Environment info

**firebase-tools:** 10.2.2

**Platform:** Linux (Ubuntu latest)

### [REQUIRED] Test case

Not sure where to start. The structure is big and complex, repository is private, I can share the repo with anybody that can help. Let me know.

### [REQUIRED] Steps to reproduce

Build a Gatsby website and deploy to Firebase.

### [REQUIRED] Expected behavior

✔  hosting[...]: release complete 
✔  Deploy complete! 

### [REQUIRED] Actual behavior

```
i  hosting: hashing files [2583/15042] (17%) 
Task 562f28e58a324d89fa1fc9b6b48277c50d17419d0fcbc88dfdcb2e15e27124cf failed: retries exhausted after 6 attempts, with error: Timeout reached making request to https://upload-firebasehosting.googleapis.com/upload/sites/[.....my file path....]
[2022-03-09T14:15:57.628Z] [hosting][upload queue][FINAL] {"max":37572,"min":6146,"avg":25447.725806451614,"active":199,"complete":63,"success":62,"errored":1,"retried":845,"total":298,"elapsed":192484}
[2022-03-09T14:15:57.629Z] FirebaseError: Timeout reached making request to https://upload-firebasehosting.googleapis.com/upload/sites/[.....my path....]
    at RetryOperation._fn (/usr/local/lib/node_modules/firebase-tools/lib/apiv2.js:236:35)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Error: Task 562f28e58a324d89fa1fc9b6b48277c50d17419d0fcbc88dfdcb2e15e27124cf failed: retries exhausted after 6 attempts, with error: Timeout reached making request to https://upload-firebasehosting.googleapis.com/upload/sites/[.....my file path....]
Task b4fe54de7363ec4ae5090c602950a4ac5a3ef4a7c4a9e2a9d8ba308b29006548 failed: retries exhausted after 6 attempts, with error: Timeout reached making request to https://upload-firebasehosting.googleapis.com/upload/sites/[.....my file path....]
Task cfde5a964e6c344f15a192a70d9f3ed241a194c85a854727da1dd7d70c8595aa failed: retries exhausted after 6 attempts, with error: Timeout reached making request to https://upload-firebasehosting.googleapis.com/upload/sites/[.....my file path....]
```

Another one :
```
i  hosting: hashing files [2896/15042] (19%) 
Task 3177628a20d2036210f2186d8782df7e7011bd190b332d88ead8984dff8567f6 failed: retries exhausted after 6 attempts, with error: Timeout reached making request to https://upload-firebasehosting.googleapis.com/upload/[.....my file path....]
[2022-03-09T16:42:09.874Z] [hosting][upload queue][FINAL] {"max":29992,"min":8039,"avg":24232.79310344827,"active":199,"complete":88,"success":87,"errored":1,"retried":819,"total":311,"elapsed":192442}
[2022-03-09T16:42:09.876Z] FirebaseError: Timeout reached making request to https://upload-firebasehosting.googleapis.com/upload/sites/[.....my file path....]
    at RetryOperation._fn (/usr/local/lib/node_modules/firebase-tools/lib/apiv2.js:236:35)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Adding my friends to the discussion : @dsurprenant @feldev

**Comment by bkendall** [comment]
In the latest, I've made it possible to set `FIREBASE_HOSTING_UPLOAD_CONCURRENCY` to a lower number than 200 that works best for you!

**Comment by asee69** [comment]
i can not deploy file in firebase

**Comment by yuchenshi** [comment]
@asee69 Please open a new issue and fill the template and we can help you from there.

**Comment by AEN-Nyathi** [comment]
just came across this issue what is the solution?

**Comment by AEN-Nyathi** [comment]
`Task c45bf58eb0a38f4b17d06bbdc1ae56a9018b8f9ea945583b0a5075aeafccf4be failed: retries exhausted after 6 attempts, with error: Timeout reached making request to https://upload-firebasehosting.googleapis.com/upload/sites/world-club/versions/14e2bf7cce1a7559/files/c45bf58eb0a38f4b17d06bbdc1ae56a9018b8f9ea945583b0a5075aeafccf4be   `

**Comment by AEN-Nyathi** [comment]
After seeing this solution. at [https://www.appsloveworld.com/reactjs/100/25/firebase-hosting-deploy-error-task-5fc-failed-retries-exhausted-after-6-atte](url)

> There are two reasons to happen this. 

1. by deleting .firebase folder in your root folder will solve problem. if this doesn't work,
2. your internet connection may slow and size of files in your project may be bigger. so try with fast internet connection.

with slow internet, if you try deploying again and again, you will see that number of files uploading decreases on console. that means your files are getting uploaded, but it is taking too much time, and firebase is getting exhausted
> 

for me it was the background image size after reducing the size it worked but now I'm trying to find out what is the right size for images as the size I took is too small w=601px by h=525px. now I'm just about to test sizes and find the one which works well

**Comment by devdomino** [comment]
My issue was a corrupt image file. Opening the image file; only 1/5 of the image would display (Windows). 

Adding --debug to the deploy, you should see the files object in the console output. The files object has the following structure:

"name.jpg": "31e671a...2d997d8f",

The Error: Task message will have that hash, i.e., 

Error: Task 31e671a...2d997d8f  ...

Review and open the file. Mine was corrupted during an FTP download.

**Comment by aymen-ben-massoud** [comment]
i need help  i can,t deploy the project on firebase 

Error: Task 342e172bf2211283257676dca0f95e42fd7f57f5be4e77380600c04517b5783d failed: retries exhausted after 6 attempts, with error: Timeout reached making request to https://upload-firebasehosting.googleapis.com/upload/sites/addtocart-c49b8/versions/c7918171fdb490c5/files/342e172bf2211283257676dca0f95e42fd7f57f5be4e77380600c04517b5783d

**Comment by taeold** [comment]
Hi folks. We aren't actively looking at closed issue - if you are experiencing similar issue, I recommend that you open up a new issue and follow the issue template (including reproduction steps). Thanks!

**Comment by robust34** [comment]
I need help. I can't deploy my project on firebase
The error message is like this:

=== Deploying to 'hp-project-dcd52'...

i  deploying hosting
i  hosting[hp-project-dcd52]: beginning deploy...
i  hosting[hp-project-dcd52]: found 2436 files in public
-  hosting: hashing files [2434/2436] (99%)
Error: Task index 0 failed: retries exhausted after 4 attempts, with error: HTTP Error: 400, Precondition check failed.
|  hosting: hashing files [2434/2436] (99%)

**Comment by drewbobO1** [comment]
> * hosting: hashing files [2434/2436] (99%)
>   Error: Task index 0 failed: retries exhausted after 4 attempts, with error: HTTP Error: 400, Precondition check failed.
>   |  hosting: hashing files [2434/2436] (99%)

I'm having the same issue here. The emulation runs fine, but refuses to follow through will the deployment, despite saying 100% of the files were
added:
```
i  deploying hosting
i  hosting[project]: beginning deploy...
i  hosting[project]: found 3347 files in public
⠸  hosting: adding files to version [3000/3347] (89%)
Error: Task index 0 failed: retries exhausted after 4 attempts, with error: HTTP Error: 400, Precondition check failed.
Error: Task index 0 failed: retries exhausted after 4 attempts, with error: HTTP Error: 400, Precondition check failed.
⠧  hosting: adding files to version [3347/3347] (100%)%
```
Really not sure where to go with this. Emptying the .firebase cache, reinitializing, reduced file quantity -- none of the above have resolved what's going on.

**Comment by kmcnellis** [comment]
Just locked this, since new issues likely aren’t related to the initial poster’s problem. Please file a new issue or reach out to support if you have a similar problem!
