### ISSUE TITLE
Error: Did not find any running emulators for project

### ISSUE THREAD

**Issue by DerrickAfrifa** [firebase/firebase-tools#4283]
I am trying to export emulator data however when I run the export command I get an error saying that there are no running instances of emulator for my project.

This is strange because when I run the start command with the `--export-on-exit` flag, this exports my data successfully.
I am running all commands in the same directory using different terminal windows.

Any ideas why the export command says it cannot find running emulators for my project even though my emulators are running for my project (the only project which is the default)?

According to [this](https://github.com/firebase/firebase-tools/issues/3092#issuecomment-771087057) comment, the Emulator Suite writes a temporary file to keep track of the running instances. Where is this file, it looks like mine is not being created. 

### Environment info

**firebase-tools:** v10.2.2

**Platform:** macOS Monterey

### Test case
n/a

### Steps to reproduce
1. Navigate to a firebase project directory. Run `firebase init` in an npm directory to initialise one.
2. Run the emulators with the following command:
```
firebase emulators:start
```
3. Create some data, for example, create data in Cloud Firestore.
4. Open a new terminal window in the same repository and run the following command:
```
firebase emulators:export ./firebase-emulator-data
```

### Expected behavior
Data is exported to a directory at ./firebase-emulator-data

### Actual behavior
Error message with the following text
```
Did not find any running emulators for project { projectId }
```

**Comment by m-elgamal** [comment]
I'm facing the same issue on M1 Mac

**Comment by m-elgamal** [comment]
fixed by upgrading to 10.4.0
Also make sure to run the export script in the functions folder

**Comment by m-elgamal** [comment]
Actually not fixed, same error with 10.4.0. the workaround i did is to use the --export-on-exit when running the project to auto backup on exit

**Comment by yuchenshi** [comment]
Any logs would be really helpful here, please.

**Comment by atanasyordanov21** [comment]
I had the same issue, and it appeared to be because of having different installations of firebase-tools across my system. Then I found this, which helped me to properly resolve:
[https://stackoverflow.com/questions/66192713/why-is-my-firebase-cli-version-different-than-what-i-just-installed-with-npm](url)

**Comment by danielo515** [comment]
Should I open a new issue? Or should I upload my files here? Because I'm facing this very error

**Comment by CarltonK** [comment]
> I had the same issue, and it appeared to be because of having different installations of firebase-tools across my system. Then I found this, which helped me to properly resolve: [https://stackoverflow.com/questions/66192713/why-is-my-firebase-cli-version-different-than-what-i-just-installed-with-npm](url) In may case I have different versions of node on my system, and each node version had its own installation of firebase-tools. So the emulators were running with a version of firebase-tools different than the one used when I tried to export.

This worked for me
