### ISSUE TITLE
I didn't get warned that some config was missing

### ISSUE THREAD

**Issue by hamishjohnson** [firebase/firebase-tools#4285]
### [REQUIRED] Environment info

**firebase-tools:** 10.2.2

**Platform:** macOS

### [REQUIRED] Steps to reproduce

in config.ts
```
import { functions } from './config'

export const revenueCatWebhookSecret =
  functions.config().revenue_cat.webhook_secret
```
Then use the value in any function and deploy
but DON'T add the config with `firebase functions:config:set`... just leave unset

### [REQUIRED] Expected behavior

Error message that the config is missing

### [REQUIRED] Actual behavior

Silently ignores the function and does not deploy

**Comment by taeold** [comment]
@hamishjohnson I think the Functions config has always behaved this way. Like environment variables, you are going to have to make sure that the value is set for your project. I think we _might_ consider adding a runtime check to make sure the value exists, but that FR should be filed in https://github.com/firebase/firebase-functions not here.

However, I do see that you are reporting that the function doesn't deploy b/c of this issue? Can you clarify what's going on there?
