### ISSUE TITLE
Security rule emulator errors when evaluating `allow read: if ["a"].size > 0;`

### ISSUE THREAD

**Issue by jorroll** [firebase/firebase-tools#4291]
### [REQUIRED] Environment info

**firebase-tools:** 10.2.2

**Platform:** Debian Linux inside a devcontainer on a macOS arm64/aarch64 laptop

### [REQUIRED] Test case

See this minimal reproduction: https://github.com/jorroll/firestore-emulators-issue

### [REQUIRED] Steps to reproduce

1. [Clone repo](https://github.com/jorroll/firestore-emulators-issue)
2. Optionally use [devcontainer](https://code.visualstudio.com/docs/remote/devcontainerjson-reference) to set up environment
3. run `yarn install`
4. Run `yarn firebase:emulators`
5. In a separate terminal window run `yarn test`
6. You should now see an error.

### [REQUIRED] Expected behavior

The security rule

```
allow read: if ["a"].size > 0;
```

Should always evaluate to `true` in the emulator.

### [REQUIRED] Actual behavior

The emulator throws the following error when trying to unit test the rule.

```
FirebaseError:

      Type error. Received: [list] Expected: [map,path]. for 'get' @ L4
```

**Comment by yuchenshi** [comment]
Hi, List `size` is actually a function, not a property, and needs to be accessed with `["a"].size()` (note the parenthesis). Reference: https://firebase.google.com/docs/reference/rules/rules.List#size

**Comment by jorroll** [comment]
@yuchenshi oh duh! Thanks! Part of the problem was that the error message I received wasn’t helpful. Would it be appropriate for me to open a new feature request asking for these emulator error messages to be improved? For example, when I tried wrapping the code in `debug([“a”].size)` nothing was printed to the log. Now I imagine that was because the debug function doesn’t know how to print a function object. So I feel like there were several places along the way where improvements could have clued me into this user error.
