### ISSUE TITLE
https://firebase.tools/bin/macos/latest returns 404 Not Found

### ISSUE THREAD

**Issue by iamnotabout** [firebase/firebase-tools#4299]
### [REQUIRED] Environment info

**firebase-tools:** latest

**Platform:** macOS

### [REQUIRED] Test case

$ curl -sL -o test https://firebase.tools/bin/macos/latest
$ file test
test: ASCII text, with no line terminators
$ cat test
Not Found

### [REQUIRED] Steps to reproduce

$ curl -sL -o test https://firebase.tools/bin/macos/latest
$ file test
test: ASCII text, with no line terminators
$ cat test
Not Found

### [REQUIRED] Expected behavior

Expected https://firebase.tools/bin/macos/latest to not be 404 Not Found

### [REQUIRED] Actual behavior

Actually https://firebase.tools/bin/macos/latest is currently 404 Not Found

**Comment by iamnotabout** [comment]
oh v10.3.0 of firebase-tools is recently release, so it didn't publish the binary yet

**Comment by marcshilling** [comment]
Seems like the same issue as https://github.com/firebase/firebase-tools/issues/2632 where all the assets weren't included with the release. @bkendall are you able to resolve this again?

**Comment by piyush-singh-ss** [comment]
@bkendall, we are also facing the same issue, the latest release does not have the macOS binary.

**Comment by bkendall** [comment]
oh weird, only one artifact is there. that's new. I'll take a look.
