### ISSUE TITLE
Command to print current project ID

### ISSUE THREAD

**Issue by SamyPesse** [firebase/firebase-tools#430]
When writing a script to deploy multiple components, it is sometimes needed to know which project is currently being used (`firebase use xyz`).

It'd be awesome to have a command `firebase current` that simply print the current project ID (no message so that it can be integrated in a bash script).

Currently the only way to know what is the current firebase project is to run `firebase list` and find it in the list.

---

I've read the [Contributing](https://github.com/firebase/firebase-tools/blob/master/.github/CONTRIBUTING.md), it looks like feature requests such as this one should not be posted here, but the website form for feature request doesn't look suited for requests about the CLI and tooling.

**Comment by mbleigh** [comment]
I think you're looking for `firebase use` (no other arguments). It will print a bit of extra text, but not if being run by a non-interactive shell. For instance:

    echo $(firebase use)

will just print out the name of the current project.

**Comment by mbleigh** [comment]
FWIW found a couple little bugs when testing this, which are addressed in #432
