### ISSUE TITLE
TypeError: Cannot read property 'data' of undefined since v10.3.1

### ISSUE THREAD

**Issue by jnizet** [firebase/firebase-tools#4313]
### [REQUIRED] Environment info

**firebase-tools:** 10.3.1

**Platform:** macOS, Ubuntu

### [REQUIRED] Test case

Hard to do. Here's however the URL of a PR on a public project that makes the tests fail because a firebase function running in the emulator is killed due to an internal error: https://github.com/jnizet/decouvertes-nature/pull/110.  

The stack trace is:
```
[emulators] i  functions: Beginning execution of "listUsers"
[emulators] ⚠  functions: TypeError: Cannot read property 'data' of undefined
[emulators]     at processBackground (/home/runner/work/decouvertes-nature/decouvertes-nature/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:550:24)
[emulators]     at invokeTrigger (/home/runner/work/decouvertes-nature/decouvertes-nature/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:640:19)
[emulators]     at handleMessage (/home/runner/work/decouvertes-nature/decouvertes-nature/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:742:15)
[emulators]     at processTicksAndRejections (internal/process/task_queues.js:95:5)
[emulators] ⚠  Your function was killed because it raised an unhandled error.
```

The source code of the function is that one: https://github.com/jnizet/decouvertes-nature/blob/renovate/firebase-tools-10.x/functions/src/users/users.ts#L51-L56

This function has never had any issue until v10.3.1

**Comment by taeold** [comment]
Fix is released in 10.4.0! Thanks for reporting the issue.
