### ISSUE TITLE
Firestore Storage Emulator always evaluate overwriting files as "RulesetOperationMethod.CREATE"

### ISSUE THREAD

**Issue by SamyPesse** [firebase/firebase-tools#4329]
### [REQUIRED] Environment info

**firebase-tools:** 10.4.1

**Platform:** macOS

### [REQUIRED] Steps to reproduce

While implementing tests to ensure a fie cannot be modified in a bucket, we are confronted to an issue with the Storage emulator: all file updates are being evaluated as "create" operations: https://github.com/firebase/firebase-tools/blob/089bea2ba739c0e03d858e76119e47144eda342c/src/emulator/storage/files.ts#L322-L323

It means that the following rules cannot be tested:

```
service firebase.storage {
    match /b/{bucket}/o {
        match /something/{fileName} {
            allow read: if true;
            allow write: if  resource == null ;
        }
    }
}
```

⚠️ I expect the production storage backend does't behave like this otherwise it's a massive security flaw.

### [REQUIRED] Expected behavior

If the file exists in the storage, it should be evaluated as a `UPDATE`, similar to how it's done for metadata: https://github.com/firebase/firebase-tools/blob/089bea2ba739c0e03d858e76119e47144eda342c/src/emulator/storage/files.ts#L273-L277

### [REQUIRED] Actual behavior

The operation is evaluated as a `CREATE`, independently from the file already existing or not.

**Comment by tonyjhuang** [comment]
Hi @SamyPesse, thanks for filing this. This behavior mimics the behavior of the storage server in production today. Please see https://github.com/firebase/firebase-js-sdk/issues/5079#issuecomment-871712273 for an explanation of what's going on.

Note that since the storage emulator does not support GCS object versioning, the workaround in the linked issue will not work in the emulator environment. I understand this can be confusing and but as of now, this is WAI.

**Comment by SamyPesse** [comment]
@tonyjhuang While looking deeper into it. I still can't reproduce this behaviour (which is a good thing imo, but I feel like I'm missing something).

Here is a minimal reproducible example: https://github.com/SamyPesse/firebase-storage-repro
I've just tested with a new firebase project and I'm getting the following when running it:

```
node ./test.js
Uploading first version...
Uploading second version...
[StorageError [FirebaseError]: Firebase Storage: User does not have permission to access 'test-9309.txt'. (storage/unauthorized)] {
  code: 'storage/unauthorized',
  customData: { serverResponse: '' },
  _baseMessage: "Firebase Storage: User does not have permission to access 'test-9309.txt'. (storage/unauthorized)"
}
```

It seems to demonstrate that `resource == null` does work as a way to prevent overwriting files.
What am I missing? (since you've said `This behavior mimics the behavior of the storage server in production today.`).

**Comment by tonyjhuang** [comment]
Sorry, I realize now I conflated the issue you raised with the other issue in the js sdk repo which is mainly that there's a lot of confusion around when `UPDATE` vs `CREATE` security rules are triggered. 

Your initial bug report does seem like a bug just in our emulator that we need to fix. I apologize for the confusion.

**Comment by SamyPesse** [comment]
I can confirm it looks like a difference between `update` and `write`:

### 🔴  Using `allow update: if false` doesn't work to prevent overwriting files

The following rules cannot be used to prevent over-writing files, it has the same effect as `write: true`

```
rules_version = '2';
service firebase.storage {
  match /b/{bucket}/o {
    match /{allPaths=**} {
      allow create: if true;
      allow update: if false;
      allow read: if true;
    }
  }
}
```

### ✅  using `allow write: if resource == null`

In that case the second file operation fails; and files cannot be over-written.

```
rules_version = '2';
service firebase.storage {
  match /b/{bucket}/o {
    match /{allPaths=**} {
      allow write: if resource == null;
      allow read: if true;
    }
  }
}
```

---

In that case my suggestion of a fix (https://github.com/firebase/firebase-tools/pull/4330) will not work, and the storage emulators will require more work to evaluate `write` or `update` depending on if only metadata are updated.

**Comment by tonyjhuang** [comment]
That's right, the `write` permission applies to both object upload and metadata update. `update` only apples to metadata updates, `create` only applies to object uploads (except in cases where you have object versioning enabled). https://github.com/firebase/firebase-tools/pull/4330 is likely not the right fix. Instead, we will need to set the `before resource` in the upload handler in `StorageLayer`.

I'm happy to review a PR if you want to create one, otherwise this may have to wait until someone on the team has cycles to look at this.

**Comment by SamyPesse** [comment]
@tonyjhuang I've updated https://github.com/firebase/firebase-tools/pull/4330 to make it match the behaviour of the production storage: over-writing a file will always evaluate as `create` but with `resource` being defined.

I've tested this behaviour in the production storage using:

```
rules_version = '2';
service firebase.storage {
  match /b/{bucket}/o {
    match /{allPaths=**} {
      allow create: if resource == null;
      allow read: if true;
    }
  }
}
```

Let me know what you think :)

**Comment by tonyjhuang** [comment]
Filed internal bug to track, b/240606901

**Comment by abhis3** [comment]
Change is merged in and issue should be fixed, resolving
