### ISSUE TITLE
Can't deploy function

### ISSUE THREAD

**Issue by munkhorgil** [firebase/firebase-tools#433]
### Version info
3.9.2

### Steps to reproduce
`firebase deploy --only functions`

### Expected behavior

Successfully deploy

### Actual behavior
i  functions: waiting for APIs to activate...

**Comment by laurenzlong** [comment]
How long does it get stuck on this message for? And have you tried this multiple times? Can you run again with --debug flag?

**Comment by munkhorgil** [comment]
@laurenzlong I got the following error in the debugging which is cannot find module. Obviously, I forgot to install dependencies.

Thanks!
