### ISSUE TITLE
Firebase export runs out of memory

### ISSUE THREAD

**Issue by samborambo305** [firebase/firebase-tools#4332]
### [REQUIRED] Environment info

**firebase-tools:** 10.2.2

**Platform:** macOS

### [REQUIRED] Test case

It is too complicated to provide a test case because it requires uploading a lot of data. The issue is the following:
If you create a sufficiently large export data database (~1GB of data - this isn't even that big) then the emulator takes crashes upon export. However, if you break up the export into several chunks, i.e. you export .25GB at a time with 4 separate exports, it works just fine.

### [REQUIRED] Steps to reproduce

See above

### [REQUIRED] Expected behavior

Export does not crash from OOM

### [REQUIRED] Actual behavior

Export crashes with OOM error

**Comment by yuchenshi** [comment]
Thanks for filing this. Let's merge the discussion into #4336.
