### ISSUE TITLE
Parse Error at 1:1 in HTTP REQUEST PUT http://localhost:9000/.settings/rules.json with Emulator UI.

### ISSUE THREAD

**Issue by l-monninger** [firebase/firebase-tools#4340]
### [REQUIRED] Environment info

**firebase-tools:** firebase-tools@10.3.0

**Platform:** macOS Monterrey 12.2.1

### [REQUIRED] Test case

I'm not entirely sure that this is reproducible, but whenever I init my project and try to either `firebase --debug emulators:exec --ui "echo hi"` or `firebase emulators:start` I run into this problem. 

I don't want to share too much about my rules, but this is what my `firebase.json` looks like:
```firebase.json
{
  "functions": {
    "source": "functions",
    "predeploy": [
      "npm --prefix \"$RESOURCE_DIR\" run lint"
    ]
  },
  "rules" : "./rules/storage.rules",
  "firestore": {
    "rules": "./rules/firestore.rules"
  },
  "storage" : {
    "rules" : "./rules/storage.rules"
  },
  "emulators": {
    "auth": {
      "port": 9099
    },
    "functions": {
      "port": 5001
    },
    "firestore": {
      "port": 8080
    },
    "storage": {
      "port": 9199
    },
    "ui": {
      "enabled": true
    }
  }
}
```

And, this is what my rules look like:
```
service firebase.storage {
   // super secret rules here
}
```

If I use version 2, I still get the error at 1:1.
```
rules_version='2'; // error message still indicates pares issue here
service firebase.storage {
    // super secret rules here
}
```

I can run `firebase emulators:start firestore,storage,functions` just fine. But, as soon as I introduce the UI this fails.

Using the `firebase --debug emulators:exec --ui "echo hi"`, shows the error occurs after `HTTP REQUEST PUT http://localhost:9000/.settings/rules.json` which yields the following response:

```
HTTP RESPONSE BODY {
  "error" : "1:1: Parse error.\n"
}
```

### [REQUIRED] Steps to reproduce

Not sure how to reproduce this yet.

### [REQUIRED] Expected behavior

The UI Emulator starts without an issues.

### [REQUIRED] Actual behavior

The UI Emulator crashes itself and all other emulators, reporting: `⚠  Emulator UI has exited upon receiving signal: SIGINT`

**Comment by yuchenshi** [comment]
Hi, would you mind contacting Firebase Support where you can privately share your rules and log files? We may be able to look into this.

**Comment by DennisAshford** [comment]
Did you find a solution to this issue? I am running into the same error and cannot figure out why.

**Comment by l-monninger** [comment]
> Did you find a solution to this issue? I am running into the same error and cannot figure out why.

I ended up moving away from the rules API as a means of access control, so no.
