### ISSUE TITLE
Duplicate access token on file.setMetadata

### ISSUE THREAD

**Issue by Expipiplusone** [firebase/firebase-tools#4341]
### Environment info

Firebase CLI 10.1.2 
Using emulators for functions, storage, firestore
Ubuntu 21.10

### Test case

Context: setting new file metadata via (node.js) function.
Example code:
```
  const fileRef = bucket.file( storagePath );
  const fileMetadata = ( await fileRef.getMetadata() )[0];
  
  // do something with metadata
  
  await fileRef.setMetadata( { metadata: newMetadata } );
```

### Steps to reproduce

Invoke function multiple times

### Expected behavior

New metadata should be set, access tokens should not be duplicated (see below)

### Actual behavior

New metadata are set as expected. However, in addition to that, a new access token (identical to the one already present) is added to the file, as can be seen in the emulator suite console under File location.
![Screenshot from 2022-03-19 02-23-44](https://user-images.githubusercontent.com/33549645/159101246-59e494e0-718c-47b2-996a-c15505b63237.png)

**If the file has N access tokens, they are all duplicated.**

**After a few repetitions, the file has so many access tokens that the function goes in error for `PayloadTooLargeError: request entity too large`.**

Tried on actual firebase (not emulator), no duplication occurs.

**Comment by tonyjhuang** [comment]
@abhis3 can you take a look at this?

**Comment by abhis3** [comment]
Ack, I'll take a look into it
