### ISSUE TITLE
Upgrading from firebase tools 10.0.1 to 10.1.5 gives error: Cannot find module 'marked'

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [firebase/firebase-tools#4342]
If I look in firebase.js, both 10.0.1 and 10.1.5 have this code:
![image](https://user-images.githubusercontent.com/1098243/159116660-50fd1a31-5ab3-4b6e-990e-78a226449426.png)

if I install dependencies for 10.1.5 my node_modules folder looks like:
![image](https://user-images.githubusercontent.com/1098243/159116667-ff29cd07-4a80-465d-a024-b1525f2bd28e.png)

if I install dependencies for 10.0.1 my node_modules folder looks like:
![image](https://user-images.githubusercontent.com/1098243/159116679-f8a52cd6-62a5-48ec-a3d2-65886ce87afe.png)

So the marked package is indeed gone.

**Platform: windows 10

**Comment by bkendall** [comment]
How are you installing the CLI tool? What version of node are you on? Are there debug logs you can provide?

Ignoring the template only leads to more questions, sorry. Can you provide some additional information?

**Comment by LanderBeeuwsaert** [comment]
Apologies, the extra information didn't seem relevant but I should have included it anyway.
Node version is v16.13.0
firebase tools is installed both globally as well as in the project folder.
The global instance doesn't seem to interfere.
It's when I switch in the project folder from 10.0.1 to a newer version (10.1.5 or 10.4.1) I get the issue about the marked package.
Even when doing a "firebase --version":

PS C:\lander\devprojects\acro-companion> firebase --version
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'marked'
Require stack:
- C:\lander\devprojects\acro-companion\node_modules\firebase-tools\lib\bin\firebase.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\lander\devprojects\acro-companion\node_modules\firebase-tools\lib\bin\firebase.js:18:16)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\lander\\devprojects\\acro-companion\\node_modules\\firebase-tools\\lib\\bin\\firebase.js'
  ]
}

A. If after that I change in the package.json the version to 10.0.1 and do "npm i" the issue is solved, but I'm back on version 10.0.1

B. If I add to devDependencies the package "marked", then I get an error:
Error: Cannot find module 'universal-analytics'
If I then add "universal-analytics", then I get the error:
Error: Cannot find module 'request'
So for a reason I don't understand, the correct packages are not installed.
I've tried this a few times.

**Comment by LanderBeeuwsaert** [comment]
After upgrading to npm 8 this was fixed
