### ISSUE TITLE
Error uploading large files to emulator storage since 10.3.0

### ISSUE THREAD

**Issue by jeroenkroese** [firebase/firebase-tools#4346]
### [REQUIRED] Environment info

**firebase-tools:** 10.4.0

**Platform:** macOS

### [REQUIRED] Test case

I have a simple file input dialog and I'm using [uploadBytesResumable](https://firebase.google.com/docs/reference/js/storage.md#uploadbytesresumable) from the Javascript SDK to upload to the storage emulator. This works fine for smaller files, but when I try to upload a larger file (~4MB), I receive an error in the console.

```
const uploadTask = uploadBytesResumable(
  storageRef,
  file.data
);

uploadTask.catch((error) => {
  console.log(error);
  console.log(uploadTask.snapshot);
});
```

### [REQUIRED] Steps to reproduce

Upload a larger file to the storage emulator. I've also been able to reproduce by uploading a larger file through the Emulator UI.

### [REQUIRED] Expected behavior

The file uploads successfully to the storage emulator.

### [REQUIRED] Actual behavior

`FirebaseError: Firebase Storage: An unknown error occurred, please check the error payload for server response. (storage/unknown)`

<img width="675" alt="Screenshot 2022-03-21 at 22 27 53" src="https://user-images.githubusercontent.com/16576066/159367028-f0101da1-54d1-467b-997c-73aafad957d0.png">

One difference I noticed between large files and small files is that the _resumable property of the UploadTask is only true for the larger files.

**Comment by ggirotto** [comment]
Not sure if my problem origin is the same, but I'm also receiving this error
