### ISSUE TITLE
Syntax error in the documentation for firebase deploy --only functions:groupA... 

### ISSUE THREAD

**Issue by Thkasis** [firebase/firebase-tools#436]
It's small but can cause confusion for newbies to Node exports, like myself. The [documentation ](https://firebase.google.com/docs/cli/#partial_deploys) has ";" at the end of each function in an export group rather than "," which causes CLI to throw syntax error. 

So instead of 
exports.groupA = {
  function1: functions.https.onRequest(...);
  function2: functions.database.ref('\path').onWrite(...);
}

Should be 
exports.groupA = {
  function1: functions.https.onRequest(...),
  function2: functions.database.ref('\path').onWrite(...),
}

Thanks for the good work you do.

**Comment by mbleigh** [comment]
Thanks for the report, we'll address it in the docs.

**Comment by kevinfoley** [comment]
@mbleigh  This still has not been addressed two years later.

**Comment by samtstern** [comment]
@kevinfoley yikes, fixing this now.

**Comment by samtstern** [comment]
(docs submitted, should be live within the day)
