### ISSUE TITLE
I cannot use "firebase init" for cloud messaging only

### ISSUE THREAD

**Issue by LostInDarkMath** [firebase/firebase-tools#4363]
### [REQUIRED] Environment info
**firebase-tools:** Firebase CLI version 10.5.0

**Platform:** Windows

### [REQUIRED]  Steps to reproduce

```
firebase init
? Are you ready to proceed? Yes
? Which Firebase features do you want to set up for this directory? Press Space to select features, then Enter to confirm your choices.
ENTER
```

### [REQUIRED] Expected behavior
I want to add Firebase Cloud Messaging to Flutter project that hasn't used Firebase before. So I run `firebase init`. But FCM is not listed, so I just pressed enter in order to to just the basic configuration.

### [REQUIRED] Actual behavior
```
Error: Must select at least one feature. Use SPACEBAR to select features, or specify a feature by running firebase init [feature_name]
```

Why can't I use the Firebase CLI for adding FCM?

**Comment by bkendall** [comment]
FCM doesn't have any integration with the Firebase CLI, so there's really nothing to do here. If there's something specific you'd actually want to do with the CLI for FCM, please file a [feature request for Firebase](https://firebase.google.com/support/troubleshooter/contact)
