### ISSUE TITLE
Writing to emulator firestore doesn't work, but it does work on a production app

### ISSUE THREAD

**Issue by Alien10123** [firebase/firebase-tools#4365]
### [REQUIRED] Environment info

**firebase-tools: 10.5.0**

**Platform: Windows**

### [REQUIRED] Steps to reproduce

Create a new Next Js app and setup the emulator. Only the firestore one is need to reproduce this, but I also have firebase auth. Then in your Next JS app connect to firebase with this code:
```typescript
interface firebaseConfig {
    apiKey: string;
    authDomain: string;
    projectId: string;
    storageBucket: string;
    messagingSenderId: string;
    appId: string;
}

function createFirebaseApp(config: firebaseConfig) {
    try {
        return getApp();
    } catch {
        // if (typeof window !== "undefined") {
            return initializeApp(config);
        // }
    }
}

createFirebaseApp(firebaseConfig);
```
And then to connect to the emulator do this:
```typescript
if (useEmulator) {
    connectFirestoreEmulator(db, "127.0.0.1", 8080);
}
```
Change the ports if you need. Then try and write to the database, like this for example (I can't write to firestore it doesn't matter what the write is) from the docs:
```typescript
        await setDoc(doc(db, "cities", "LA"), {
            name: "Los Angeles",
            state: "CA",
            country: "USA",
        });
```
Then you have reproduced it

### [REQUIRED] Expected behavior
It should make a write to the firestore emulator, or at least show up as a request in the ui. It works on a production app.

### [REQUIRED] Actual behavior
I don't get any errors, and nothing appears in the ui, not even a request. Looking in the firestore debug log, this appears:
```
Mar 28, 2022 7:07:35 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected non-HTTP/2 connection.
```

When I use the debug flag this appears a bunch of times:
```
[1] [2022-03-28T08:14:21.875Z] Mar 28, 2022 7:14:21 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
[1] INFO: Detected non-HTTP/2 connection.
[1]  {"metadata":{"emulator":{"name":"firestore"},"message":"Mar 28, 2022 7:14:21 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead\r\nINFO: Detected non-HTTP/2 connection.\r\n"}}
```

**Comment by yuchenshi** [comment]
Thanks for the report. I think you've ran into a Project ID mismatch. While you can write data to any valid project ID using the SDKs, the Emulator UI only shows data in the default project ID. You can try starting the emulators with `firebase emulators:start --project foo-bar`, where `foo-bar` matches what your Next JS app is using, and you should be able to see the data now.

**Comment by Alien10123** [comment]
That works @yuchenshi . Thanks. Sorry for taking a bit to respond.

**Comment by dandv** [comment]
I've run into a projectId mismatch issue as well.

It would help to [document the `.projectId` getter](https://github.com/googleapis/nodejs-firestore/issues/2278) on the Firestore object, to help diagnose this type of problem.
