### ISSUE TITLE
[FR] Log requests in Storage Emulator

### ISSUE THREAD

**Issue by dermasmid** [firebase/firebase-tools#4367]
### [REQUIRED] Environment info

**firebase-tools:** 10.2.2

**Platform:** Ubuntu 20.4

### [REQUIRED] Test case

When using the storage emulator i was not able to see any logs, even when running with --debug

### [REQUIRED] Steps to reproduce

start the storage emulator, upload a file or something, there will be no logs of that

### [REQUIRED] Expected behavior

storage should provide some logs and also save it to storage-debug.log

### [REQUIRED] Actual behavior
there's nothing logged from the storage emulator

[firebase-debug.log](https://github.com/firebase/firebase-tools/files/8369963/firebase-debug.log)

**Comment by yuchenshi** [comment]
The Storage Emulator does not have per-request logging. Would you like us to convert this to a feature request?

**Comment by dermasmid** [comment]
Yes, thanks

**Comment by tonyjhuang** [comment]
Does this env var not help? https://github.com/firebase/firebase-tools/blob/master/src/emulator/storage/apis/firebase.ts#L22
