### ISSUE TITLE
Cannot import to emulators

### ISSUE THREAD

**Issue by coreform** [firebase/firebase-tools#4392]
### [REQUIRED] Environment info

**firebase-tools:10.5.0**

**Platform:macOS**

### [REQUIRED] Test case

Can one import a production backup into the local emulators?

### [REQUIRED] Steps to reproduce

Install firebase-tools via curl. 

Take an export from a cloud firebase project using gsutils. chmod 755 in case it isn't already.

then either:

firebase emulators:start --import= ../backupFolder/backupFile.overall_export_metadata
= nothing happens,if you repeat the above command you may get a prompt: 

-or-

firebase emulators:exec --import= ../backupFolder/backupFile.overall_export_metadata
(not passing a folder because that yields: `is a directory Script exited unsuccessfully (code 126)`)
= runs through function initalizations then fails with: `Permission denied Script exited unsuccessfully (code 126)`

### [REQUIRED] Expected behavior

Script to execute to completion and yield populated local emulators.

### [REQUIRED] Actual behavior

Running script: ../backupFolder/backupFile.overall_export_metadata
/bin/sh: ../backupFolder/backupFile.overall_export_metadata: Permission denied
⚠  Script exited unsuccessfully (code 126)
i  emulators: Shutting down emulators.
i  functions: Stopping Functions Emulator
i  firestore: Stopping Firestore Emulator
i  storage: Stopping Storage Emulator
i  hub: Stopping emulator hub

**Comment by yuchenshi** [comment]
Would you mind trying again with `firebase emulators:exec --import=../backupFolder`? Note that there should be no space after the equal sign, and the argument should be a directory, not the metadata file.

**Comment by coreform** [comment]
Sure,

firebase emulators:exec --import=../backupFolder
error: missing required argument 'script'

firebase emulators:start --import=../backupFolder
i  emulators: Starting emulators: functions, firestore, storage
i  emulators: Shutting down emulators.
i  hub: Stopping emulator hub

Error: An unexpected error has occurred.

**Comment by yuchenshi** [comment]
Ah, my bad for suggesting `exec` earlier -- that is for use with a script. 

I think the `firebase emulators:start --import=../backupFolder` command is getting closer, would you mind adding `--debug` and upload the full log? We may be able to look into this.

**Comment by coreform** [comment]
Nono, my bad: it all came down to the whitespace and a typo in the real path. Sorry for taking up your time on that.

I was able to use the :start command to import. Though the import only sees Firestore populated, Storage is empty and part of our content is offloaded to Storage to mitigate hotspotting. I recall seeing an open issue about that matter so will head over there.
