### ISSUE TITLE
File uploads in storage emulator on m1 mac failing

### ISSUE THREAD

**Issue by rishisv** [firebase/firebase-tools#4396]
### [REQUIRED] Environment info

**firebase-tools:** 10.5.0

**Platform:** macOS version 12.2.1, Apple M1 Pro chip

### [REQUIRED] Test case

* Launch the storage emulator, localhost:9595/storage and upload a large file. 
* Error is seen in the console: 
`Uncaught (in promise) FirebaseError: Firebase Storage: An unknown error occurred, please check the error payload for server response. (storage/unknown)`

<img width="1102" alt="image" src="https://user-images.githubusercontent.com/59505526/161490387-f1c200c2-b32c-473b-bc79-f441ab0f98f1.png">

### [REQUIRED] Steps to reproduce

* Install firebase-tools, launch emulator locally, go to the storage emulator webpage and upload a large image

### [REQUIRED] Expected behavior

* No errors

### [REQUIRED] Actual behavior
* Error seen with large files > ~500KB.

**Comment by rishisv** [comment]
There's a related issue #4346 that talks about 4mb file sizes and on older version of firebase tools but I can't even upload ~500kb files with the latest version. My teammates on x86/intel mac do not have this issue.

**Comment by tohhsinpei** [comment]
Fixed in #4407
