### ISSUE TITLE
angular template has issues. 

### ISSUE THREAD

**Issue by rsatyan** [firebase/firebase-tools#44]
Enter the name of the Firebase app you would like to use for hosting
Firebase app: awareco

Available Templates

angular     - The AngularFire seed template
backbone    - Example to-do app using BackFire
chat        - A realtime multi-person chat client with JavaScript, HTML, and CSS
drawing     - Share a canvas and collaboratively draw with other users
ember       - Example blog built with EmberFire
firechat    - A more fully-featured chat widget using Firechat
firepad     - Collaborative text editing with Firepad
ionic       - A small chatroom application written for Ionic
leaderboard - A leaderboard which keeps track of high scores in realtime
presence    - Show who is available, who is idle, and who is gone
react       - Example to-do app using ReactFire
tetris      - Play head-to-head Tetris in your browser

Choose a template to help you get started with your app
Template: angular
Bootstrapping into directory 'awareco'...
Downloading and unpacking template...
 Initialization Error - Couldn't update template with project settings 

Not sure why the angular template is having problems, please help.

**Comment by drtriumph** [comment]
There was a change to the underlying repo without an accompanying change to the recipe that initializes this project. I've made the changes and so this should work now. Thanks for reporting the issue
