### ISSUE TITLE
Cannot select a default Firebase project?

### ISSUE THREAD

**Issue by dvhuy** [firebase/firebase-tools#440]
Hi,

Im trying using FB but i got the issue.

Step to reproduce.
- npm i firebase-tools -g
- firebase login 
- firebase init
- select Hosting: Configure and deploy Firebase Hosting sites
- **Select a default Firebase project**
At this step, i see the list project that i created in Firebase, but i can not using arrow to,
cannot exit terminal also.

I'm using node v8.1.0, tried to use node v6 but still not succeed!

I searched but not found the solution,

Please help me to find out the solution!

**Comment by dvhuy** [comment]
I changed to node version 6 and it works well.

**Comment by mbleigh** [comment]
FYI there were bugs affecting `firebase-tools` in Node 8.0.0 and Node 8.1.0 -- newer versions should work okay.

**Comment by dvhuy** [comment]
- just got issues when run `firebase init`, quick fix by the way:
Changed to Node version 6 for run `firebase init` then change again to version 8.1.0

**Comment by mbleigh** [comment]
You should upgrade to Node 8.1.1 or later and it will work fine.

**Comment by dvhuy** [comment]
It works, thank ;)

**Comment by jgervin** [comment]
Using Node 8.9.4 and it does NOT work. It won't list active projects. It only shows "Do NOT create a project" and "Create a New project"

**Comment by mustafa-alfar** [comment]
The problem is still countering me, I've tried nodejs version 8, 10 and 8 also doesn't work.
is there any suggestion ?

**Comment by ablenesi** [comment]
I'm facing the same issue tried multiple nodejs versions 8 10 12 none of them works

**Comment by mbleigh** [comment]
@mustafa-alfar @ablenesi I think #1420 is probably the bug to track for updates here. This bug is old and closed.
