### ISSUE TITLE
Invalid Refresh token in emulator with Identity Platform

### ISSUE THREAD

**Issue by Stf-F** [firebase/firebase-tools#4414]
### [REQUIRED] Environment info

**firebase-tools:** 10.2.0

**Platform:** Mac OS 12.1
 **Firebase SDK version:** 9.6.2
 **Node:** 16.13.1
**npm:** 8.1.2 (via nvm use 16)

### [REQUIRED] Test case

```javascript
      const unsubscribe = onAuthStateChanged(
        auth,
        async (user) => {
          if (user) {
              try {
                await user?.getIdToken(true); // <------ This yields token refresh errors
              } catch (e) {
                throw e;
            }
            // rest of logic here
          }
        },
      );
  ```

### [REQUIRED] Steps to reproduce
On localhost, against the Auth emulators: 
- In a Firebase project with firebase Auth working, upgrade to Identity Platform  
- Generate a sign in link on the server side via the admin SDK with the tenant ID ( [as per the official docs](https://cloud.google.com/identity-platform/docs/multi-tenancy-managing-tenants#generating_email_action_links))
- Authenticate with the link
- (Update the claims on the server side)
- Invoke the `getIdToken(true)` to force refresh the token
- Expect a crash

### [REQUIRED] Expected behavior

-  Being able to use the `getIdToken(true)` against the emulator when signing in with Identify Platform tokens.  

### [REQUIRED] Actual behavior

![image](https://user-images.githubusercontent.com/52630104/162050548-add3161d-ee12-4afe-8dd2-3323d12efb7b.png)

**Comment by yuchenshi** [comment]
Looks like the token refresh endpoint isn't tenant ID aware (yet). @lisajian for further triaging.

**Comment by Stf-F** [comment]
> Looks like the token refresh endpoint isn't tenant ID aware (yet). @lisajian for further triaging.

@yuchenshi, please also note that tenanted users created in localhost do not appear in the 'Authentication' tab of the emulator. Yet, they do exist and are successfully created as a [getUserByEmail()](https://cloud.google.com/identity-platform/docs/multi-tenancy-managing-tenants#getting_a_user) would successfully fetch them. Let me know, I am happy to file another bug report for this related issue if necessary.

**Comment by yuchenshi** [comment]
@Stf-F The Emulator UI does not support multi-tenancy at this moment. We'll let you know if / when support is added.

**Comment by lisajian** [comment]
Nice find and thanks for raising this issue @Stf-F! Working on making the token refresh endpoint tenant ID aware and will update with the changes shortly

**Comment by mesqueeb** [comment]
I'm still seeing this issue 
![image](https://github.com/firebase/firebase-tools/assets/3253920/a4c665b2-606d-4467-92b5-9ce852c82652)
