### ISSUE TITLE
firebase-admin Emulator can't find users

### ISSUE THREAD

**Issue by FrancescoBia** [firebase/firebase-tools#4426]
### [REQUIRED] Environment info

**firebase-tools:** 10.6.0

**Platform:** macOS (arm64) - Monterey 12.3

### [REQUIRED] Test case

I'm trying to handle the users via firebase-admin connected to the emulator. However, it seems like firebase-admin cannot find the users available in the emulator and visible via the emulator UI (the one at localhost:4000). Conversely, when a user is created via firebase-admin, this doesn't show in the UI (but firebase-admin is able to retrieve it via `listUsers()`. It's like the two are storing their users' lists in different locations.

I initially thought it was a problem with firebase-admin not being correctly connected to the emulator, but the issue seems to be related specifically to Auth, as any other operation with Realtime Database seems to work as expected with the emulator. Furthermore, also firebase auth via client works perfectly fine. So I'm not sure where the issue lies.

### [REQUIRED] Steps to reproduce

1. start firebase emulator
2. add a new user manually to via the emulator UI
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/9106253/162564122-8ad37deb-ad3e-4693-839c-3980650d86ad.png">
3. start firebase-admin with the emulator and list all users

``` javascript
import admin from 'firebase-admin'

process.env['FIREBASE_AUTH_EMULATOR_HOST'] = 'localhost:9099'

admin.initializeApp({
    projectId: 'your-project-id',
})

const auth = admin.auth()

auth.listUsers().then((result) => {
    console.log(result)
})
```

### [REQUIRED] Expected behavior

` console.log(result)` to log the user manually created.

### [REQUIRED] Actual behavior

log is `{ users: [] }`

**Comment by FrancescoBia** [comment]
Found the solution from an old issue. 
`projectId` needs to be configured to the actual project id for the emulator too, despite what the documentation says ([link](https://firebase.google.com/docs/emulator-suite/connect_auth#admin_sdks)). It should be updated to inform about this issue.

**Comment by dereekb** [comment]
From what I understand and have seen, the projectIds can be anything, however they get their own context, rather than having a shared context.

What I imagine was happening was you were creating it in one context and trying to read from another.

**Comment by amfc** [comment]
How should projectId be configured? I haven't been able to make it work for auth.

I have it as:

* an environment variable: export GCLOUD_PROJECT=example on the shell that opens the emulators

* a configuration option in firebase.initializeApp when initializing the javascript client library:

      firebase.initializeApp({
        apiKey: "example",
        projectId: "example",
        storageBucket: "example.appspot.com",
      });

* a configuration option in admin.initializeApp when initializing the javascript admin library:

      firebase.initializeApp({
        projectId: "example",
        storageBucket: "example.appspot.com",
      });


* an option in the command that opens the emulators: firebase -P example emulators:start

Data that is added to firestore and storage from the web or backend is shown correctly on the emulator's UI, and the users created with the admin library are also shown. However users created from the client library (with createUserWithEmailAndPassword) aren't shown (but still exist, as they can interact with the web)

**Comment by yuchenshi** [comment]
Hi all, we've updated the documentation to clarify this. On the Admin SDK side, the section now suggests matching project IDs: https://firebase.google.com/docs/emulator-suite/connect_auth#admin_sdks

@amfc The Emulator UI follows [the Project ID given to the Firebase CLI](https://firebase.google.com/docs/emulator-suite/connect_auth#choose_a_firebase_project). In other words, `firebase emulators:start --project example` should get you there.

We understand that it is frustrating to make sure the three places all match exactly and we appreciate your feedback. In the meantime, we also don't want to break other developers who want more isolation with multiple projects. We're in search of a better way and feel free to jot down your suggestions.
