### ISSUE TITLE
incredibly huge package size (687MB)

### ISSUE THREAD

**Issue by xr0master** [firebase/firebase-tools#4445]
Hi. The package size is greater than the size of all other packages in the sum for each project.

### [REQUIRED] Environment info

**firebase-tools:**
10.6.0

**Platform:**
macOS

### [REQUIRED] Test case

`du -sh node_modules/* | sort -hr`

<img width="567" alt="Screen Shot 2022-04-14 at 9 22 03 PM" src="https://user-images.githubusercontent.com/8962340/163453944-b8493c46-f71e-48a4-97ef-d52901c00f5d.png">

**Comment by yuchenshi** [comment]
Have you tried `npm install firebase-tools --only=prod`? That will exclude the dev dependencies.

**Comment by xr0master** [comment]
@yuchenshi the `--only=prod` will exclude all dev dependencies of the project.

**Comment by bkendall** [comment]
That's what `npm install` _should_ be doing anyway. It's because of the shrinkwrap file (I think) that it's installing the dev dependencies as well. To _use_ the CLI (or the CLI as a module), the dev dependencies aren't required in the slightest.

npm actually has [an open issue discussing this](https://github.com/npm/npm/issues/17185), though it's not exactly active. Maybe worth someone from our side tilting at npm to see if it can be addressed.

**Comment by bkendall** [comment]
(but, unfortunately, outside some really, really hacky stuff on our end, this is really an npm issue)

**Comment by bkendall** [comment]
https://github.com/npm/cli/issues/4323 is the issue I should have linked. That's the one with actual activity.

**Comment by haines** [comment]
Perhaps it would be possible to have a `prepublishOnly` script that strips the `dev` dependencies from npm-shrinkwrap.json as a workaround?

**Comment by ai** [comment]
@haines for my projects (PostCSS, Browserslist) I use [`clean-publish`](https://github.com/shashkovdanil/clean-publish) to cut development configs during the release.

**Comment by xr0master** [comment]
@akauppi `npm i firebase-tools --save-dev`

**Comment by bkendall** [comment]
I gave up waiting for npm to fix their issues and am using `clean-publish` to do this now. So, thanks for the tip to that @ai (nice username)

Fixed by #5023

**Comment by xr0master** [comment]
before
<img width="390" alt="image" src="https://user-images.githubusercontent.com/8962340/192879486-84043acb-f4a4-40ff-8b2e-ac80aeff824f.png">
after 
<img width="419" alt="image" src="https://user-images.githubusercontent.com/8962340/192879539-089c9fc4-c1fa-448e-941c-feae9a016668.png">

Still a bit thick, but 4 times smaller! Great job, thanks a lot @bkendall.

**Comment by bkendall** [comment]
GASP! I had the thought of "I wonder what's bloating that so" and discovered that `googleapis` is listed as a dependency but _really_ is a dev dependency... and it's 111MB.
