### ISSUE TITLE
Firebase app connected to Firestore emulator gets strange/inconsistent results

### ISSUE THREAD

**Issue by ivoelbert** [firebase/firebase-tools#4446]
### [REQUIRED] Environment info

**Platform:** macOS

### backend
**firebase-tools:** 10.6.0
**firebase-admin:** 9.12.0

### frontend:
**firebase:** 8.10.1

### [REQUIRED] Test case

It's hard to make a test case cause I'm getting different results across different computers.

Currently we're running functions, auth, and Firestore emulators, and those seem to be working fine. If we call an emulated function that reads/writes to Firestore, it works. I can go to the emulators UI and see the data in there.

The problem comes when our web app talks to the Firestore emulator. The network shows that we are talking to it (`localhost:8080`), but the same query on one computer returns some results, and on another it doesn't, even though in the Firestore emulator UI it shows data on both computers.

### [REQUIRED] Steps to reproduce

Our repo is private, and I am not able to reproduce this behavior in a smaller scale.

### [REQUIRED] Expected behavior

I should be able to read the data in any of my collections.

### [REQUIRED] Actual behavior

I can only read data from some collections.

if I read the `global-settings` collection, I can see the data in both computers (an array of 10 elements)
if I read the `users-v1` collection, I can't. I get an array of a few elements in one computer, and an empty one in another (with the same data in both emulators)

**Comment by christhompsongoogle** [comment]
Please provide a reproducible example - it's hard to determine what the configuration is that causes the issue here.
