### ISSUE TITLE
[Off-topic] How do you print such a nice command-line interface?

### ISSUE THREAD

**Issue by FranRiadigos** [firebase/firebase-tools#4453]
Hi,

I'm just curious about what do you guys use to print such a nice command-line interface with spinners, selectors, colours, etc.

Is it all manual scripting, or do you use any package or some sort of a JS extension that outputs to the command line?

Thanks.

**Comment by yuchenshi** [comment]
The Firebase CLI is open source so please take a look yourself: https://github.com/firebase/firebase-tools/blob/master/package.json

We use many differnet npm packages like `ora` for spinners, etc. You can also find other packages and their usages in this repo.

**Comment by yuchenshi** [comment]
Thanks for the compliment though
