### ISSUE TITLE
Firebase non-interactive hosting deploy not fetching GOOGLE_APPLICATION_CREDENTIALS

### ISSUE THREAD

**Issue by albertogeniola** [firebase/firebase-tools#4456]
### [REQUIRED] Environment info

**firebase-tools: 10.6.0**

**Platform: Linux**

### [REQUIRED] Test case

1. Create a GCP project (let it be my-gcp-test-project)
2. Create a GCP service account with OWNER credentials on the project
3. Create a Service Account key for that project
4. Download the service account key on the local disk (let it be sa.json)
5. Run firebase deploy command using that service account 

### [REQUIRED] Steps to reproduce

```bash
GOOGLE_APPLICATION_CREDENTIALS=./sa.json firebase use my-gcp-test-project
GOOGLE_APPLICATION_CREDENTIALS=./sa.json firebase firebase --non-interactive deploy --only hosting
```

### [REQUIRED] Expected behavior

The website is deployed to the target firebase project

### [REQUIRED] Actual behavior

The deploy fails as the firebase command fetches the local credentials (configured via gcloud) rather than the ones passed as GOOGLE_APPLICATION_CREDENTIALS.

**Comment by mbleigh** [comment]
Can you please provide logs from the command with `--debug`? It should print out where it is discovering credentials.

**Comment by albertogeniola** [comment]
Hi @mbleigh ,

I can confirm that, using the latest version of firebase-tools on a virgin environment (started a VM from scratch), the issue is fixed. Thanks a lot guys.
