### ISSUE TITLE
TypeError: Cannot read property 'data' of undefined when data exists

### ISSUE THREAD

**Issue by dtroupe18** [firebase/firebase-tools#446]
I have the following cloud function 

```
exports.keepPostKeysUpdated = functions.database.ref('/posts/{postid}').onWrite(event => { 
  console.log("write on posts...");
  console.log(event.previous.params.postID);
  console.log(event.data.previous.val());
  console.log(event.data.previous.val().postID);
  var postKey = event.data.previous.val().postID;


  // When a table, category, or region is changed the old upload has to be deleted
  if (event.data.previous.exists()) {
    if (event.data.previous.val().table != event.data.val().table || event.data.previous.val().region != 
        event.data.val().region || event.previous.data.val().category != event.data.val().category) {
          // category, region, or table was changed
          console.log(postKey);
          if (event.data.previous.val().table != event.data.val().table) {
            console.log("Table was changed");
            // delete the post from the old table
            const oldTable = event.data.previous.val().table;
            const newTable = event.data.val().table;

            addToNewTable(newTable, postKey);
            removePostFromOldTable(oldTable, postKey);
          }
          if (event.data.previous.val().category != event.data.val().category) {
            console.log("Category was changed");
            // delete the post from the old category
            const oldCategory = event.data.previous.val().category;
            const newCategory = event.data.val().category;

            addToNewCategory(newCategory, postKey);
            removePostFromOldCategory(oldCategory, postKey);
          }
          if (event.data.previous.val().region != event.data.val().region) {
            console.log("Region was changed");
            // delete post from old region
            const oldRegion = event.data.previous.val().region;
            const newRegion = event.data.val().region;

            addToNewRegion(newRegion, postKey);
            removePostFromOldRegion(oldRegion, postKey);
          }  
        }
        else {
          return
        }
}
else {
  // previous value does not exist this case is handled by 
  // copyPostKey
  return
}
});
```

It work perfectly fine when a table or region is changed but fails every time a category is changed. The error is coming from the line `var postKey = event.data.previous.val().postID;` How can this value be read some times but not others? I can even console log the key, but it says it can't be read when I try to assign it to postKey. Any idea what this issue is from? 

node = v6.11.2
firebase-tools = 3.10.10

**Comment by laurenzlong** [comment]
Since this is a very specific issue and not a general bug, can you please post this on Stackoverflow, or file a support ticket? https://firebase.google.com/support/

**Comment by dtroupe18** [comment]
If I can console log the value with `console.log(event.data.previous.val().postID);` but can't save it with `var postKey = event.data.previous.val().postID;` it's a bug. There are other people talking about similar issues [https://github.com/firebase/firebase-tools/issues/356](url) [https://github.com/GoogleCloudPlatform/cloud-functions-emulator/issues/100](url) Everything worked find until I updated to the newest version of firebase-tools this weekend....

**Comment by laurenzlong** [comment]
I'm a bit confused since since seems to be an issue with firebase-functions, but you're filing in the firebase-tools repository. Did you mean that this error happened while you are emulating the function locally with firebase-tools? If the error happens on your deployed function, then you should file an issue on https://github.com/firebase/firebase-functions.

Could you file another issue in the appropriate repository, ensure that you follow the issue template, and create minimum repro? It's hard for me to figure out what's going on with a large code snippet like this, since I don't have a sense of how your database is structured and how you are triggering the writes.
