### ISSUE TITLE
Add support for disabling output formatting by upgrading the cli-color dependency.

### ISSUE THREAD

**Issue by blakgeek** [firebase/firebase-tools#4471]
We use firebase tools in our Jenkins pipelines and formatting makes it hard to read the output.  The next version of cli-color 1.41.0 adds support for disabling formatting using the env variable NO_COLOR.

Please upgrade the dependency.

**Comment by joehan** [comment]
Done! We also love PRs - in the future, feel free to cut out the middleman and just make a PR 😄
