### ISSUE TITLE
Fireabse-tools@9.23.3 unable to be installed within the last hour

### ISSUE THREAD

**Issue by smonroe4242** [firebase/firebase-tools#4482]
### [REQUIRED] Environment info

Attempting to install the 9.23.3

**firebase-tools:**

**Platform:**

### [REQUIRED] Test case

npm install firebase-tools@9.23.3

### [REQUIRED] Steps to reproduce

npm install firebase-tools@9.23.3
### [REQUIRED] Expected behavior

Should install
### [REQUIRED] Actual behavior
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@google-cloud/pubsub/-/pubsub-2.19.2.tgz - Not found
npm ERR! 404 
npm ERR! 404  '@google-cloud/pubsub@https://registry.npmjs.org/@google-cloud/pubsub/-/pubsub-2.19.2.tgz' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

Fails unable to get @google-cloud/pubsub@2.19.2, released an hour ago but unavailable through npm

**Comment by barmmie** [comment]
Issue reported here.
https://github.com/googleapis/nodejs-pubsub/issues/1539

**Comment by smonroe4242** [comment]
Issue reported to a more relevant repo, closing this one.
