### ISSUE TITLE
.env.local file not loaded when using emulators:exec command

### ISSUE THREAD

**Issue by dimadeveatii** [firebase/firebase-tools#4510]
### [REQUIRED] Environment info

**firebase-tools:** 10.7.1

**Platform:** MacOS

### [REQUIRED] Test case

As per the [documentation](https://firebase.google.com/docs/functions/config-env#emulator_support), the Cloud Functions emulator is using the `.env.local` file to load variables. However, when running `firebase emulators:exec` the environment variables are not loaded from the `.env.local` file. 

### [REQUIRED] Steps to reproduce

Add a `.env.local` file:
```sh
# emulator variable in .env.local
MY_VAR=test
```

Run command:
```sh
firebase emulators:exec "node -p process.env.MY_VAR"
```

### [REQUIRED] Expected behavior

The value `test` is printed in the output.

### [REQUIRED] Actual behavior

`MY_VAR` is missing and the output is `undefined`.

> Note that the same issue holds for the `.secret.local` file.

**Comment by bigbitbus** [comment]
Also, probably worth mentioning this comment in another GH issue: 
https://github.com/firebase/firebase-tools/issues/4239#issuecomment-1065412510

**Comment by joehan** [comment]
Hey @dimadeveatii, sorry to hear that you are having issues. `.env.local` sets environment variables in the process running the emulated functions, not in the process running your test script. The repro that you provided is the intended behavior here. 

I just verified that I can access an environment variable set in `.env.local` from within an emulated function - ie:
```
// functions/.env.local
TEST=hello
```
```
// functions/index.js
exports.helloWorld = functions.https.onRequest((request, response) => {
  functions.logger.info(`Processs.env.TEST=${process.env.TEST}`);
  response.send(process.env.TEST);
});
```
if I then run:
```
firebase emulators:exec 'curl http:/localhost:5001/demo-test/us-central1/helloWorld'
```
"hello" is printed to my emulator logs. 

If you need to access environment variables from within your testing script, you'll have to load them from the .env.local within that script.
