### ISSUE TITLE
Relaxed limit on the number of characters in the function name of Cloud Functions

### ISSUE THREAD

**Issue by 1amageek** [firebase/firebase-tools#4532]
Hi.

Thank you for providing us with a great product.

I have a suggestion regarding the length of Function name.
Currently Cloud Functions limits the length of Function name to 62 characters or less. I would like to see the length of Function name extended to about 120 characters.

While it is important to limit the number of characters, is there a reason for this 62 character limit?

https://github.com/firebase/firebase-tools/blob/5ea735ec96eec1eb4d016ea447e092dadbec7481/src/deploy/functions/validate.ts#L129-L157

## Issue.
I use FirestoreTrigger with Cloud Functions, but I am having trouble naming the Function Name. So I have created and am operating with the following rules

For example

```
// Firestore
/domain/v1/users/:uid/items/:itemID
```

```
// Cloud Functions
domain-user-item-onCreate
domain-user-item-onUpdate
domain-user-item-onDelete
```

This approach is very useful when developing, as it allows for consistency in naming. However, with this approach, the deeper the nesting of Firestore's Collection, the longer the string will be.

The limitation of the Function Name to 62 characters makes it difficult to operate.

If there is no significant reason for 62 characters, please relax the restriction.

**Comment by yuchenshi** [comment]
This limit is on the Google Cloud Functions backend and the CLI is just trying to provide helpful error messages. Please reach out to Google Cloud Support regarding the limit and file a feature request.
