### ISSUE TITLE
Encountered error when installing Firebase CLI on MacBook Pro - Monterey v12.2

### ISSUE THREAD

**Issue by edwardchinfl** [firebase/firebase-tools#4533]
Encountered the following error when I ran : curl -sL https://firebase.tools | upgrade=true bash on a MacBook Pro macOS Monterey version 12.2 
bash: line 255: /usr/local/bin/firebase: Bad CPU type in executable
Something went wrong, firebase has not been installed.

Software info : 
  macOS 12.2 (21D49)
  Kernel Version:	Darwin 21.3.0
  Boot Volume:	Macintosh HD
  Boot Mode:	Normal
  Computer Name:	Edward’s MacBook Pro
  Username:	Edward Chin (edwardchin)
  Secure Virtual Memory:	Enabled
  System Integrity Protection:	Enabled
  Time since boot:	1:17

Hardware info
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro18,1
  Chip:	Apple M1 Pro
  Total Number of Cores:	10 (8 performance and 2 efficiency)
  Memory:	16 GB
  System Firmware Version:	7429.81.3
  OS Loader Version:	7429.81.3
  Serial Number (system):	RRW60Q0JQJ
  Hardware UUID:	F7A05D74-5843-5B15-B497-291E9B78AC0C
  Provisioning UDID:	00006000-001405E126E2801E
  Activation Lock Status:	Enabled

**Comment by edwardchinfl** [comment]
Issue resolved by installing Rosetta 2 : /usr/sbin/softwareupdate --install-rosetta --agree-to-license

**Comment by sunderee** [comment]
That should be documented somewhere, or mentioned in the stdout in case installation fails. Would that be an option?
