### ISSUE TITLE
providerId and uid are different for currentUser and currentUser.providerData

### ISSUE THREAD

**Issue by dzhamshed** [firebase/firebase-tools#4545]
### [REQUIRED] Environment info

**firebase-tools:** 10.9.0

**Platform:** macOS

### [REQUIRED] Test case

Using Firebase Emulators Suite, when user is signed in by email and password the providerId and uid are different for auth.currentUser and auth.currentUser.providerData.

### [REQUIRED] Steps to reproduce

```ts
// During initialization, connect to Firebase Authentication Emulator.
connectAuthEmulator(getAuth(), 'http://localhost:9099', { disableWarnings: true });

// Sign in user by email and password.
await signInWithEmailAndPassword(getAuth(), email, password);

getAuth().currentUser.uid // = "2MED4u7DwMVch7S7G2QW2v3qwYcC". This is correct as it's same as in Emulators UI.
getAuth().currentUser.providerId // = "firebase". It should be "password".
getAuth().currentUser.providerData // = [{"providerId":"password","uid":"user@example.com","displayName":"Example User","email":"user@example.com","phoneNumber":null,"photoURL":null}]
```

As you can see `providerId` is incorrect for the `currentUser` and `uid` inside `providerData` is the user's email address.

### [REQUIRED] Expected behavior

The`providerId` should be `password` for the `currentUser` and `uid` inside `providerData` should be actual user UID.

![image](https://user-images.githubusercontent.com/29413456/168003077-7d5d6cd1-d12b-4481-a1a5-7d35087ac202.png)

### [REQUIRED] Actual behavior

The `providerId` is incorrect for the `currentUser` and `uid` inside `providerData` is the user's email address.

**Comment by christhompsongoogle** [comment]
Values observed in production:

firebase.auth().currentUser.uid
'v2VQPUoCnCZxlxgmEFQwy3Wd3kG2'
firebase.auth().currentUser.providerData[0].uid
'109047843236878834542'

firebase.auth().currentUser.providerId
'firebase'
firebase.auth().currentUser.providerData[0].providerId
'google.com'


Full providerData:
displayName: "Chris Thompson"
email: "[redacted]@gmail.com"
phoneNumber: null
photoURL: "https://lh3.googleusercontent.com/a/AATXAJw-LEZ5BYBzR_VtSRNSEapXIsz3GHp0pJBY7GvD=s96-c"
providerId: "google.com"
uid: "109047843236878834542"

**Comment by christhompsongoogle** [comment]
Since this emulator behavior matches the production behavior, this is WAI from the emulator perspective. I spoke with the Access team and they don't have a plan to update this right now.

Please contact Support with any feedback to help the team prioritize this issue.
