### ISSUE TITLE
Firebase CLI not compatible with Node v12.22.1

### ISSUE THREAD

**Issue by nappernick** [firebase/firebase-tools#4563]
### [REQUIRED] Environment info

Firebase: v9.18.0
**firebase-tools:** v11.0.0

**Platform:** Linux (Docker container in Github Action)

### [REQUIRED] Test case
Deploying a preview of React app with `firebase-tools hosting:channel:deploy`, specifically:
```
 /opt/hostedtoolcache/node/12.22.12/x64/bin/npx firebase-tools hosting:channel:deploy *branch-name-hash*_breakdown_si --only *folder* --expires 7d --project *project-name* --json
  
  Firebase CLI v11.0.0 is incompatible with Node.js v12.22.12 Please upgrade Node.js to version >= 14.18.0
  
  The process '/opt/hostedtoolcache/node/12.22.12/x64/bin/npx' failed with exit code 1
```

### [REQUIRED] Steps to reproduce
Run Github action `FirebaseExtended/action-hosting-deploy` with create-react-app to generate preview channel

### [REQUIRED] Expected behavior
A Firebase preview channel is deployed

### [REQUIRED] Actual behavior
Actual call to firebase-tools is abstracted away through use of `FirebaseExtended/action-hosting-deploy`. Will investigate.

**Comment by bkendall** [comment]
I think you may have stumbled onto something interesting though. The GH action pulls the latest major version, which may not be desired. I'm passing this along as feedback :)

**Comment by thespeed94** [comment]
I have the same issue, right now.
I'm trying to use the recommended node version (14.18.0) but it doesn't exist on the container registry.

**Comment by yuchenshi** [comment]
@thespeed94 Would you mind trying a later Node.js version? For example, the latest stable 14.x.y or 16.x.y you can find on the registry.
