### ISSUE TITLE
Cloud functions emulation with rewrite throws 500, without rewrite works

### ISSUE THREAD

**Issue by fafcrumb** [firebase/firebase-tools#457]
### Version info

3.11.0

### Steps to reproduce

1. `firebase init` project with functions and hosting
2. In functions `index.js` uncomment default `helloWorld` function
3. Setup rewrite in `firebase.json`:
```
    "rewrites": [
      {
        "source": "/helloworld",
        "function": "helloWorld"
      }
    ]
```
4. `firebase serve --only functions,hosting`
5. Go to `localhost:5000/helloworld`

### Expected behavior

Function should send "Hello from Firebase!" to the browser

### Actual behavior

`500 Internal Server Error` is logged to the console
<img width="624" alt="screen shot 2017-09-17 at 5 10 32 pm" src="https://user-images.githubusercontent.com/17421035/30524945-35667990-9bcb-11e7-9325-3f8991cf87a0.png">

### Side Notes
Error only happens trying to use the rewrite url on the hosting port. The function url behaves correctly. It also behaves correctly when deployed.
My app had been calling my function flawlessly for months now. My guess is an update to firebase-tools introduced the error.

**Comment by davie-robertson** [comment]
I am so pleased to see it's not just me having this problem - I'm certain it worked a few days ago too. The simple timestamp example given here now longer works: https://youtu.be/LOeioOKUKI8

I'm using NVM and have tried various versions of node.js to try and fix this without any luck - I'm back to the 6.11.1 that's recommended.  However the functions I've been building will deploy and get served from firebase without any problems.

I think the problem relates to a PR (that I can't find right now - sorry) related to proxying. I can see from my console that a request to my function is being proxied to port 5001 and not 5003 where the functions emulator is listening:

```
i  functions: Preparing to emulate functions.
i  hosting: Serving hosting files from: public
✔  hosting: Local server: http://localhost:5000

✔  functions: app: http://localhost:5003/my-app/us-central1/app
127.0.0.1 - - [18/Sep/2017:08:48:04 +0000] "GET /__/firebase/init.js HTTP/1.1" 200 - "http://localhost:5000/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:55.0) Gecko/20100101 Firefox/55.0"
127.0.0.1 - - [18/Sep/2017:08:50:13 +0000] "GET /timestamp HTTP/1.1" 500 0 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:55.0) Gecko/20100101 Firefox/55.0"
http://localhost:5001/my-app/us-central1/app
127.0.0.1 - - [18/Sep/2017:08:50:13 +0000] "GET /timestamp HTTP/1.1" 500 0 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:55.0) Gecko/20100101 Firefox/55.0"

```

**Comment by genyklemberg** [comment]
This problem still exists for me:( 

i  hosting: Serving hosting files from: dist
+  hosting: Local server: http://localhost:5000

[hosting] Rewriting / to live function ssr
127.0.0.1 - - [07/Nov/2017:11:45:26 +0000] "GET / HTTP/1.1" 500 - "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"

No errors in log, just 
1:45:30.435 ПП | outlined_flag | ssr | Function execution took 60002 ms, finished with status: 'timeout'

**Comment by laurenzlong** [comment]
@genyklemberg can you ensure you have the latest version of firebase-tooks? (3.14.0), run "firebase --version"

**Comment by rajasekharSynclovis** [comment]
![problem](https://user-images.githubusercontent.com/52414947/61018599-ffa5af80-a3b4-11e9-836c-a24ae25dac63.PNG)
I am facing this problem past few days onwards, Help me firebase latest version i install 7.0.2

**Comment by bkendall** [comment]
@rajasekharSynclovis please open a new issue with the relevant details - it's easier to track over adding something to a closed issue. Thanks.
