### ISSUE TITLE
`error: unknown option '--local'` when trying to install an extension using CLI

### ISSUE THREAD

**Issue by vajahath** [firebase/firebase-tools#4577]
### [REQUIRED] Environment info
**firebase-tools:** 11.0.0
**Platform:**: Ubuntu

### [REQUIRED] Test case
```sh
$ firebase ext:install typesense/firestore-typesense-search --local --project=xxx
error: unknown option '--local'
```

Also checked with `--help`. But not giving enough info:
```
$ firebase ext:install --help
Usage: firebase ext:install [options] [extensionName]

install an official extension if [extensionName] or [extensionName@version] is provided; or run with `-i` to see all available extensions.

Options:
  -f, --force  automatically accept all interactive prompts
  -h, --help   output usage information
```
### [REQUIRED] Steps to reproduce

I was trying to install an extension and try it in emulator. For that I followed as per [firebase extension page](https://firebase.google.com/products/extensions/typesense-firestore-typesense-search#:~:text=How%20to%20install%20this%20extension).

![Screenshot from 2022-05-20 11-31-44](https://user-images.githubusercontent.com/12165822/169463054-08e9e708-3a0e-40e4-bcd4-3fe5e9103bc6.png)

### [REQUIRED] Expected behavior
I don't know. I was trying. I hope this should install the extension locally so that I can test with emulator.

### [REQUIRED] Actual behavior
```
error: unknown option '--local'
```
![Screenshot from 2022-05-20 11-19-59](https://user-images.githubusercontent.com/12165822/169461035-a99102fa-99b5-4e3f-b3e7-e1029cbcf7f3.png)

Run the command with --debug flag, and include the logs below: same result

Additionally, all the blue links in steps 3, 4, 5 are broken.
![Screenshot from 2022-05-20 11-32-57](https://user-images.githubusercontent.com/12165822/169463214-e4e04dec-8aa1-44ff-81cc-9055e95b2767.png)

**Comment by shauryaaher** [comment]
I have the same problem. I think it's because of the latest `firebase-tools` version. The latest version `11.0.0.` is a `MAJOR` version and is causing all sorts of problems.

**Comment by shauryaaher** [comment]
This issue needs attention.

**Comment by shauryaaher** [comment]
Can someone add the 'needs attention' label, please?

**Comment by joehan** [comment]
Hi @shauryaaher - sorry for the confusion here. As of firebase-tools@11.0.0, the default behavior is the same as `--local`. In order to install an extension locally, just run `firebase ext:install` (no --local flag). To deploy that to your project, then run `firebase deploy --only extensions`.

I'll make a fix to this ASAP to not error out if the `--local` flag is passed in. Sorry for the inconvience!

**Comment by benomatis** [comment]
will `firebase ext:install` not actually attempt to install the extension onto the default selected project instead of the emulator? if that's not the case, how do you install the extension to the default project instead, ie. how does v11 decide whether it should install to the default project or the emulator?

**Comment by joehan** [comment]
@benomatis Yes - as of firebase-tools@11, this is now a 2 step process. First, you add an extension to your local extensions manifest by running:
```
firebase ext:install
```
Then, you can emulate it by running:
```
firebase emulators:start
```
or actually install it onto a project by running:
```
firebase deploy (--only extensions)
```
If you then want to reconfigure, update, or delete an extension, you follow the same process. First, use the corresponding command to make a change in your local manifest:
```
firebase ext:(configure|update|uninstall) instance-name
```
then, run the same commands as above to emulate or deploy the new changes.
The docs (https://firebase.google.com/docs/extensions/manifest) lay this out in more detail.

**Comment by benomatis** [comment]
@joehan This worked, thank you.

**Comment by joehan** [comment]
Thanks everyone for reporting this. Just released firebase-tools@11.0.1, which includes a fix for this.

**Comment by shauryaaher** [comment]
Thanks a lot!

**Comment by shauryaaher** [comment]
Thanks a lot!

**Comment by benomatis** [comment]
@joehan: adding to the suggestion of @vajahath, I understand from the code that the `--local` flag is effectively deprecated, so it should probably not be there in the main docs, right?
