### ISSUE TITLE
Firestore emulator REST API returns "Not Found" for all endpoints other than DELETE documents

### ISSUE THREAD

**Issue by penx** [firebase/firebase-tools#4581]
### Environment info

**firebase-tools:** 11.0.0 (also tried with 10.7.1)
**Platform:** macOS

### Test case

https://github.com/penx/firestore-tools-rest-issue

#### In the above example

```sh
npm i
npm run dev
# in another terminal once emulator has started
npm test
```

#### Or independently

- Start Firestore emulator with any fixture data
- This step works - clear your emulator data with `curl -v -X DELETE "http://localhost:8080/emulator/v1/projects/my-project/databases/(default)/documents" `
  - Note this succeeds as per the documentation
- Repopulate with data
- Run `curl -v GET "http://localhost:8080/emulator/v1/projects/my-project/databases/(default)/documents"` to get a list of documents

_or_, with auth:

- get an idToken from `http://localhost:9099/identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=[API_KEY]`
- repeat above steps with `Authorization: Bearer ${bearerToken}` header

_or_ getting a sub path:

- Run `curl -v GET "http://localhost:8080/emulator/v1/projects/my-project/databases/(default)/documents/my-collection"` to get list my-collection

### Expected behavior

REST API should be available, should list available documents.

### Actual behavior

Shell output:

```
✗ curl -v GET "http://localhost:8080/emulator/v1/projects/my-project/databases"
* Could not resolve host: GET
* Closing connection 0
curl: (6) Could not resolve host: GET
*   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 8080 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#1)
> GET /emulator/v1/projects/my-project/databases HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< content-length: 10
< 
Not Found
* Connection #1 to host localhost left intact
* Closing connection 1
```

Emulator output:

```
[2022-05-23T16:42:13.885Z] May 23, 2022 5:42:13 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected non-HTTP/2 connection.
 {"metadata":{"emulator":{"name":"firestore"},"message":"May 23, 2022 5:42:13 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead\nINFO: Detected non-HTTP/2 connection.\n"}}
[2022-05-23T16:42:13.887Z] May 23, 2022 5:42:13 PM io.gapi.emulators.netty.NotFoundHandler handleRequest
INFO: Unknown request URI: /emulator/v1/projects/my-project/databases/(default)/documents
 {"metadata":{"emulator":{"name":"firestore"},"message":"May 23, 2022 5:42:13 PM io.gapi.emulators.netty.NotFoundHandler handleRequest\nINFO: Unknown request URI: /emulator/v1/projects/my-project/databases/(default)/documents\n"}}

```

### More info

Note others encountering the same issue:

- https://stackoverflow.com/questions/65610116/firestore-emulator-rest-api
- https://github.com/firebase/firebase-tools/issues/3077

**Comment by penx** [comment]
Think I've figured it out, the REST API URL needs to start with "http://localhost:8080/v1" rather than "http://localhost:8080/emulator/v1".

It would be great if this was covered by the docs somewhere. I've had to follow examples in order to get the REST API working, such https://github.com/firebase/firebase-tools/issues/3077,

**Comment by TTXD19** [comment]
https://firebase.google.com/docs/emulator-suite/connect_firestore#clear_your_database_between_tests

they really need to update their documentation for this, because in the "Clear your database between tests" sections
it's giving the wroing information....
