### ISSUE TITLE
Storage emulator interprets the machine's current time as UTC without converting it

### ISSUE THREAD

**Issue by macksal** [firebase/firebase-tools#4599]
### [REQUIRED] Environment info

**firebase-tools:** 11.0.1

**Platform:** OSX Catalina 10.15.7

### [REQUIRED] Test case

`broken.test.ts`: 

```ts
import * as rulesTest from "@firebase/rules-unit-testing";
import {equal} from "assert";
describe("Storage", function () {
    it("should populate timeCreated with approximately the current time", async () => {
        const env = await rulesTest.initializeTestEnvironment({});
        await env.clearStorage();
        await env.withSecurityRulesDisabled(async ctx => {
            const now = new Date();
            const ref = ctx.storage().ref("object1");
            await ref.put(new ArrayBuffer(1024));
            const meta = await ref.getMetadata();
            const timeCreated = new Date(meta.timeCreated);
            console.info("timeCreated: ", timeCreated);
            console.info("current time: ", now);
            // allow 5s of error either side
            equal(timeCreated.getTime() < now.getTime() + 5000, true);
            equal(timeCreated.getTime() > now.getTime() - 5000, true);
        });
        await env.cleanup();
    });
});
export {};
```

### [REQUIRED] Steps to reproduce

1. Set up a new firebase project with the storage emulator enabled.
2. Create a package for testing with these dependencies only, and the Mocha test case from above:

```json
"devDependencies": {
    "@firebase/rules-unit-testing": "^2.0.2",
    "@types/mocha": "^9.1.1",
    "firebase": "^9.8.2",
    "firebase-tools": "^11.0.1",
    "mocha": "^10.0.0",
    "ts-mocha": "^10.0.0",
    "typescript": "^4.7.2"
}
```

3. Run the test case with `yarn firebase emulators:exec --only storage 'ts-mocha broken.test.ts'`

### [REQUIRED] Expected behavior

4. The test should pass.

### [REQUIRED] Actual behavior

The test fails with the below output. I am running this at 12:38 PM in my timezone (Australia/Brisbane). 

```
timeCreated:  2022-05-31T12:38:44.572Z
current time:  2022-05-31T02:38:44.561Z
```

The bottom time from Node is correct and equal to the machine's actual time (the Z indicates it is UTC, so adding 10 for the timezone gives the correct local time of 12:38 PM). However, the timeCreated metadata field has been populated with the machine's time (12:38 PM UTC+10) interpreted as UTC, giving 12:38 PM UTC+0 which is 10 hours in the future.

**Comment by tonyjhuang** [comment]
Filed internal bug to track, b/240585492

**Comment by Yuangwang** [comment]
Closing this since it was fixed in https://github.com/firebase/firebase-tools/pull/4813
