### ISSUE TITLE
Firebase Functions Ignore Pattern Format

### ISSUE THREAD

**Issue by LaCocoRoco** [firebase/firebase-tools#4615]
### Environment info
**firebase-tools:** 11.0.1
**Platform:** Windows 10

### Test case
This should not be necessary. 
It is a general problem and  can be verified with any project.

### Steps to reproduce
After reading many Issues on Stackoverflow and Github i couldn't find a solution for my problem.
It took me hours to pinpoint down my problem.
There are two issues i have at deploying firebase functions.
The origin of the problem emerges by trying to work with a monorepo.
But i did not find any workaround for it.
In general i do not want to publish the full project folder to firebase functions.
With the accepted fireabse functions ignore pattern it is not possible to whitelist files.

[Stackoverflow Issue](https://stackoverflow.com/questions/39936217/firebase-deploy-ignore-all-files-but-public-folder)
[Github Issue](https://github.com/firebase/firebase-tools/issues/2677)
[Gitignore Pattern Format](https://git-scm.com/docs/gitignore)

The solution i desire:
```json
"functions": {
  "source": ".",
  "codebase": "next",
  "runtime": "nodejs16",
  "ignore": [
    "/*",
    "!.functions/**",
    "!.next/**",
    "!next.config.js",
    "!package-lock.json",
    "!package.json",
  ]
}
```

The solution i work with:
```json
"functions": {
  "source": ".",
  "codebase": "next",
  "runtime": "nodejs16",
  "ignore": [
    "**/node_modules/**",
    ".artifacts",
    ".cache",
    ".firebase",
    ".vscode",
    "@types",
    "backup",
    "config",
    "functions",
    "lib",
    "locales",
    "modules",
    "pages",
    "public",
    "styles",
    "tests",
    ".env",
    ".env.development",
    ".env.production",
    ".eslintrc.functions.json",
    ".eslintrc.hardhat.json",
    ".eslintrc.json",
    ".firebaserc",
    ".git",
    ".gitignore",
    ".prettierrc",
    "firebase.json",
    "firestore.indexes.json",
    "firestore.rules",
    "hardhat.config.ts",
    "next-env.d.ts",
    "README.md",
    "tsconfig.functions.json",
    "tsconfig.hardhat.json",
    "tsconfig.json"
  ]
}
```
In general i want to ignore all files and exclude the ones i need.
But there is more! To ignore per file is acceptable.
I could not find a solution to ignore a **pages** folder in the root but not in a subfolder.

```
.
├─ .functions
├─ .next
│  └── server
│      └── pages
├─ pages
```
I tried the ignore pattern `**/pages/**`, `*/pages/**`, `/pages/**`, `pages`, `pages/**`.

<img src="https://user-images.githubusercontent.com/10038346/171995442-e62ccd4a-6d5d-4460-a1aa-6f120e9a12b9.png" width="300">
But the root and subfolder always gets ignored together.
Someone knows i am doing something wrong?

### Expected behavior
Accept the ignored files as defined.

### Actual behavior
They do not.

**Comment by joehan** [comment]
Hey @LaCocoRoco, thanks for reporting this. I spent some time a while back trying to address this (see duplicate issue https://github.com/firebase/firebase-tools/issues/2677). Unfortunately, the solution you are currently using is the best one available right now.  Your proposed solution doesn't work because we ignore anything that matches at least 1 entry on the list - therefore, if you ignore "!./file1" and "!./file2", all files will be ignored.

After a bunch of tinkering, I came to the conclusion that an `ignore` list is a very poor fit for what you want to do (allow only certain files). I think the cleaner solution would be to add support for an allowlist instead.

Closing this since it is a duplicate
