### ISSUE TITLE
JSON parsing error when running firebase init

### ISSUE THREAD

**Issue by thephfernandes** [firebase/firebase-tools#4616]
### [REQUIRED] Environment info

**firebase-tools:** 11.0.1

**Platform:** Windows

### [REQUIRED] Test case

- Install firebase CLI
- Run `firebase init`
### [REQUIRED] Steps to reproduce
- Run `firebase init` inside a project
- When asked which features to automatically set up, select ` Firestore: Configure security rules and indexes files for Firestore`
- Enter the default filename for Realtime Database Security Rules (database.rules.json)

### [REQUIRED] Expected behavior
A json document containing database rules will be written to the project.

### [REQUIRED] Actual behavior
n JSON parsing error occurs.

Logs:
` ? What file should be used for Realtime Database Security Rules? database.rules.json`

`[2022-06-05T04:05:03.019Z] >>> [apiv2][query] GET https://<MY-APP>-default-rtdb.firebaseio.com/.settings/rules.json [none]`

`[2022-06-05T04:05:03.773Z] <<< [apiv2][status] GET https://<MY-APP>-default-rtdb.firebaseio.com/.settings/rules.json 200`

`[2022-06-05T04:05:03.773Z] <<< [apiv2][body] GET https://<MY-APP>-default-rtdb.firebaseio.com/.settings/rules.json`
`"{\n  /* Visit https://firebase.google.com/docs/database/security to learn more about security rules. */\n  \"rules\": {\n    \".read\": false,\n    \".write\": false\n  }\n}"`

`Error: Unable to parse JSON: SyntaxError: Unexpected token / in JSON at position 4`

**Comment by kdavong** [comment]
Hi,

When you actually use firebase init command, do you use an existing project? In this case, you should check your Realtime Database rules directly in your firebase console, because Firebase Init will try to copy it in local. Try to delete all comments in.

**Comment by thephfernandes** [comment]
My realtime database rules looks like this:
![image](https://user-images.githubusercontent.com/45126718/172065076-7e0d653b-b080-4b51-bd98-68a821414993.png)

Which matches the content of the request body posted in my original message

> `"{\n /* Visit https://firebase.google.com/docs/database/security to learn more about security rules. */\n \"rules\": {\n \".read\": false,\n \".write\": false\n }\n}"`

But it seems escaping characters with"\" isn't working properly after the response.

**Comment by kdavong** [comment]
Try to add an EOF in your json rules. (7th empty line)

**Comment by david-potgieter** [comment]
Workaround I used to get around this. Grab the Realtime DB rules from your console, and create a `database.rules.json` file manually locally. Remove the comments (as mentioned above) and ensure you have a well formed json and EOF.

Then run `firebase init`, and say `N` when prompted if you should overwrite the existing `database.storage.rules`. Rest of the init completes.

**Comment by bkendall** [comment]
This should be resolved in `v11.1.0` (which is going out today). Sorry for not getting the fix out sooner.

Duplicate #4596
