### ISSUE TITLE
Functions shell, cursor position wrong when using backspace

### ISSUE THREAD

**Issue by oscar-b** [firebase/firebase-tools#466]
Something odd going on with cursor position and deleting characters when using the new functions shell. It's off by one, deleting one character further to the left than you would anticipate. Running fish shell, not sure if that has anything to do with it.

### Version info

```
$ firebase --version                                                                                                                                                  
3.12.0
```

### Steps to reproduce

1. Start functions shell
2. Enter one character
3. Delete it with backspace. It works fine.
4. Enter two characters.
5. Delete one with backspace, the last character is removed but the first one is moved one step to the left and the cursor is in the wrong place.

### Expected behavior

Being able to delete characters with regular cursor position.

**Comment by ahaverty** [comment]
I'm seeing the exact same (cursor misplaced + same delete issues as @oscar-b) on intellij terminal
firebase-tools v3.12.0
firebase-functions v0.6.3
nodeJs v6.11.1

**Comment by mbleigh** [comment]
Do you see the fire emoji prompt? Wondering if it's a unicode issue.

**Comment by ahaverty** [comment]
@mbleigh I'm not seeing any fire emojis, and seeing strange box icons:

<img width="152" alt="screen shot 2017-09-22 at 23 02 18" src="https://user-images.githubusercontent.com/2920947/30765976-36454c2e-9fea-11e7-8f60-779c3afa4de1.png">

**Comment by mbleigh** [comment]
Then I can confirm that it's almost certainly a unicode issue. We'll see about fixing it soon 😄

**Comment by ahaverty** [comment]
VSCode gives me the 🔥 alright!
(Would love to hear/medium.com about firebase'rs IDE setup/plugins, seems like ye'r all on VSCode in there?)

<img width="74" alt="screen shot 2017-09-22 at 23 13 29" src="https://user-images.githubusercontent.com/2920947/30766269-bc3af53a-9feb-11e7-8919-17e121dc64cd.png">

**Comment by mbleigh** [comment]
Yup, I'm a pretty big fan of VSCode. Switched over maybe a year ago and haven't looked back! Not everyone uses the same thing though, I've seen everything from Atom to Vim to IntelliJ on the Firebase team.

**Comment by oscar-b** [comment]
![kapture 2017-09-23 at 0 22 59](https://user-images.githubusercontent.com/85102/30766443-633c0ca8-9ff5-11e7-81d2-a9ea0efff859.gif)

Hey @mbleigh! I see the 🔥  prompt correctly, see gif.

**Comment by mbleigh** [comment]
Yeah, it's still likely unicode. I've seen things before where unicode characters like emoji, since they take up two literal characters, can throw off terminals that aren't built to handle them well. Since the emoji is more of a flourish than a necessity, we'll probably just remove it in favor of always using the fallback `firebase` prompt.

**Comment by ahaverty** [comment]
`-flourish` flag? 😅
