### ISSUE TITLE
grpc installation issues

### ISSUE THREAD

**Issue by mayankmetha** [firebase/firebase-tools#467]
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
/usr/bin/firebase -> /usr/lib/node_modules/firebase-tools/bin/firebase

> grpc@1.4.1 install /usr/lib/node_modules/firebase-tools/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp ERR! Tried to download(undefined): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.4.1/node-v57-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.4.1 and node@8.5.0 (node-v57 ABI) (falling back to source compile with node-gyp) 
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/firebase-tools/node_modules/grpc/build'
gyp ERR! System Linux 4.10.0-35-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=/usr/lib/node_modules/firebase-tools/node_modules/grpc/src/node/extension_binary/grpc_node.node" "--module_name=grpc_node" "--module_path=/usr/lib/node_modules/firebase-tools/node_modules/grpc/src/node/extension_binary"
gyp ERR! cwd /usr/lib/node_modules/firebase-tools/node_modules/grpc
gyp ERR! node -v v8.5.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/usr/lib/node_modules/firebase-tools/node_modules/grpc/src/node/extension_binary/grpc_node.node --module_name=grpc_node --module_path=/usr/lib/node_modules/firebase-tools/node_modules/grpc/src/node/extension_binary' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/firebase-tools/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:125:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:927:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Linux 4.10.0-35-generic
node-pre-gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/firebase-tools/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /usr/lib/node_modules/firebase-tools/node_modules/grpc
node-pre-gyp ERR! node -v v8.5.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/usr/lib/node_modules/firebase-tools/node_modules/grpc/src/node/extension_binary/grpc_node.node --module_name=grpc_node --module_path=/usr/lib/node_modules/firebase-tools/node_modules/grpc/src/node/extension_binary' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: grpc@1.4.1 (node_modules/firebase-tools/node_modules/grpc):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: grpc@1.4.1 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

**Comment by mbleigh** [comment]
What OS and Node.js version are you using?

**Comment by peteclodi** [comment]
I received the same error both with NodeJS 8.5.0 and again after downgrading to NodeJS 6.11.3. In both cases I was running on Ubuntu 16.04 LTS

**Comment by zzeleznick** [comment]
Looks like OP is running Linux 4.10, tries to install the latest grpc, and fails with a permissions issue on his machine. 
```
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/firebase-tools/node_modules/grpc/build'
gyp ERR! System Linux 4.10.0-35-generic
```
_Possible root cause:_ Node and npm were installed under root and into a directory controlled by root.

**Comment by mayankmetha** [comment]
node : 8.7.0
os : Linux/Ubuntu 17.04/17.10

**Comment by dtruffaut** [comment]
Same error for me on Windows 7 x64

```
yarn install v1.3.2
warning package.json: License should be a valid SPDX license expression
warning package.json: "dependencies" has dependency "google-closure-compiler" with range "^20170910.0.0" that collides with a dependency in "devDependencies" of the same name with version "latest"
info No lockfile found.
warning aaa@1.0.0: License should be a valid SPDX license expression
warning aaa@1.0.0: "dependencies" has dependency "google-closure-compiler" with range "^20170910.0.0" that collides with a dependency in "devDependencies" of the same name with version "latest"
[1/4] Resolving packages...
warning yarn@1.3.2: It is recommended to install Yarn using the native installation method for your environment. See https://yarnpkg.com/en/docs/install
Couldn't find any versions for "firebase-admin" that matches "lastest"
? Please choose a version of "firebase-admin" from this list: 5.5.1
Couldn't find any versions for "firebase-tools" that matches "lastest"
? Please choose a version of "firebase-tools" from this list: 3.15.3
warning firebase-tools > universal-analytics > node-uuid@1.4.8: Use uuid module instead
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[4/5] ⢀ grpc: https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.7.2/node-v57-win32-x64-unknown.tar.gz
[-/5] ⢀ waiting...
[3/5] ⢀ puppeteer
[-/5] ⢀ waiting...
error C:\Program Files\nodejs\aaa\node_modules\grpc: Command failed.
Exit code: 7
Command: .\node_modules\.bin\node-pre-gyp install --fallback-to-build --library=static_library
Arguments:
Directory: C:\Program Files\nodejs\aaa\node_modules\grpc
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.39
node-pre-gyp info using node@8.6.0 | win32 | x64
node-pre-gyp info check checked for "C:\Program Files\nodejs\aaa\node_modules\grpc\src\node\extension_binary\node-v57-win32-x64-unknown\grpc_node.node" (not found)
node-pre-gyp http GET https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.7.2/node-v57-win32-x64-unknown.tar.gz
node-pre-gyp ERR! UNCAUGHT EXCEPTION
node-pre-gyp ERR! stack TypeError: require(...).Extract is not a function
node-pre-gyp ERR! stack     at C:\Program Files\nodejs\aaa\node_modules\node-pre-gyp\lib\install.js:79:40
node-pre-gyp ERR! stack     at download (C:\Program Files\nodejs\aaa\node_modules\node-pre-gyp\lib\install.js:69:12)
node-pre-gyp ERR! stack     at place_binary (C:\Program Files\nodejs\aaa\node_modules\node-pre-gyp\lib\install.js:73:5)
node-pre-gyp ERR! stack     at C:\Program Files\nodejs\aaa\node_modules\node-pre-gyp\lib\install.js:183:17
node-pre-gyp ERR! stack     at FSReqWrap.cb [as oncomplete] (fs.js:313:19)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\skeetmeet\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd C:\Program Files\nodejs\aaa\node_modules\grpc
node-pre-gyp ERR! node -v v8.6.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
```

https://github.com/firebase/firebase-js-sdk/issues/221
https://github.com/firebase/firebase-js-sdk/issues/267
https://github.com/firebase/firebase-functions/issues/130
https://github.com/firebase/firebase-admin-node/issues/132
https://github.com/firebase/firebase-tools/issues/442

**Comment by dtruffaut** [comment]
Additional note :  When firebase is installed with npm, no error. But as npm empties the directory previously filled with yarn, it is impossible to have both yarn and npm installed modules, it is one or the other. It is a no-go.

To sum up, the issue occurs when trying to install firebase with yarn.

**Comment by mayankmetha** [comment]
problem fixed on my system

**Comment by dtruffaut** [comment]
Ok, after several tries, let's just say _yarn_ fails, but _npm install_ works.

**Comment by nsksaisaravana** [comment]
I am also getting the same error when try to install **npm install firebase.**

Please check this screen shot.

![image](https://user-images.githubusercontent.com/17681573/35372253-fcb7dd86-01ec-11e8-9b97-b4bf6cec3029.png)

**Comment by laurenzlong** [comment]
Do you also get issue if you just did: "npm install grpc"?

If you do, please file an issue at https://github.com/grpc/grpc-node/issues

**Comment by nsksaisaravana** [comment]
@laurenzlong Thanks a lot and i got the solutin in the above URL

I faced a similar problem. For me, the problem seemed to be my antivirus (Kaspersky). Once I disabled it, I was able to install firebase.

**Comment by laurenzlong** [comment]
Thanks for sharing! I'm going to leave this issue open so other people can read out the different workarounds.

**Comment by mbleigh** [comment]
I'd like to consolidate grpc installation issues at grpc/grpc-node#121

**Comment by JavaidAhmad-Venture** [comment]
Issue Resolved!
In my case, I faced the same issue...
I installed 
npm install -g firebase@4.6.2

and removed cap ^ in package.json before firebase version.
#hopeItWillWorkForYou

**Comment by Darwinium** [comment]
Fixed after this:
> Issue resolved by removing cap ^ in package.json before firebase dependency.

**Comment by shubhamgupta608** [comment]
> Nothing worked for me. What I did, at last, I took grpc folder from some other project node_module folder and placed it into the new one. After that, I did 'npm install' and everything worked smoothly.

I had the same issue and invested 3 hrs of mine.This works finally.Thanks Sir!
