### ISSUE TITLE
FirebaseError: Failed to make request to https://firebase.googleapis.com/v1beta1/projects?pageSize=100

### ISSUE THREAD

**Issue by keshabmanni** [firebase/firebase-tools#4675]
[debug] [2022-06-22T10:04:21.335Z] ----------------------------------------------------------------------
[debug] [2022-06-22T10:04:21.336Z] Command:       C:\npm\node-v16.15.1-win-x64\node.exe C:\npm\node-v16.15.1-win-x64\node_modules\firebase-tools\lib\bin\firebase.js init
[debug] [2022-06-22T10:04:21.336Z] CLI Version:   11.1.0
[debug] [2022-06-22T10:04:21.337Z] Platform:      win32
[debug] [2022-06-22T10:04:21.337Z] Node Version:  v16.15.1
[debug] [2022-06-22T10:04:21.338Z] Time:          Wed Jun 22 2022 15:34:21 GMT+0530 (India Standard Time)
[debug] [2022-06-22T10:04:21.338Z] ----------------------------------------------------------------------
[debug] 
[debug] [2022-06-22T10:04:21.345Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2022-06-22T10:04:21.345Z] > authorizing via signed-in user (keshab********@gmail.com)
[info] 
     ######## #### ########  ######## ########     ###     ######  ########
     ##        ##  ##     ## ##       ##     ##  ##   ##  ##       ##
     ######    ##  ########  ######   ########  #########  ######  ######
     ##        ##  ##    ##  ##       ##     ## ##     ##       ## ##
     ##       #### ##     ## ######## ########  ##     ##  ######  ########

You're about to initialize a Firebase project in this directory:

  D:\Firebase

[info] 
=== Project Setup
[info] 
[info] First, let's associate this project directory with a Firebase project.
[info] You can create multiple project aliases by running firebase use --add, 
[info] but for now we'll just set up a default project.
[info] 
[debug] [2022-06-22T10:04:33.798Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects pageSize=100
[debug] [2022-06-22T10:04:34.019Z] Failed to make request to https://firebase.googleapis.com/v1beta1/projects?pageSize=100
[debug] [2022-06-22T10:04:34.155Z] FirebaseError: Failed to make request to https://firebase.googleapis.com/v1beta1/projects?pageSize=100
    at RetryOperation._fn (C:\npm\node-v16.15.1-win-x64\node_modules\firebase-tools\lib\apiv2.js:241:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[error] 
[error] Error: Failed to list Firebase projects. See firebase-debug.log for more info.

I have already tried: firebase logout/login, firebase login --reauth

**Comment by bkendall** [comment]
Couple things to check, I suppose:

1. Can you run `firebase projects:list` with success?
2. Does running the command on the C drive, rather than the D drive, give you different results?

**Comment by keshabmanni** [comment]
1. No, its error from same command(firebase projects:list). firebase init command also gives similar error.
2. no its same result.

**Comment by bkendall** [comment]
1. Are you able to access `https://firebase.googleapis.com/v1beta1/projects` from a web browser? It should return some type of error without any auth tokens.
2. Are you running with a proxy of any kind set up? Is it possible to try from a different network?

These types of issues are usually pretty hard to debug since it can be something very specific to one's setup...

**Comment by keshabmanni** [comment]
1. It shows json message: "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project."

2. No im not using any proxy. I tried from different network but same error.

**Comment by wellnesssolutions** [comment]
I am having the same issue. I did try many solutions but no help until now.

**Comment by bkendall** [comment]
Hey, I'm sorry to not have gotten back to you. Were you able to get it working? My only other guess might be that windows firewall is blocking the requests somehow, but it's definitely likely to be something in your setup rather than the CLI, unfortunately.

**Comment by adulusman** [comment]
i just try re apply the target , if fxed for me
 firebase target:apply hosting projectname projectname
