### ISSUE TITLE
v2 Cloud Function deploy doesn't respect `cpu` config

### ISSUE THREAD

**Issue by mqp** [firebase/firebase-tools#4679]
### [REQUIRED] Environment info

**firebase-tools:** 11.1.0

**Platform:** Arch Linux

### [REQUIRED] Test case

Define a function like this:

```typescript
import { onRequest } from 'firebase-functions/v2/https'

const opts = { cpu: 2 }
export const test = onRequest(opts, async (_req, res) => {
  res.status(200).json({})
})
```

### [REQUIRED] Steps to reproduce

Deploy the function.

`firebase deploy --only functions:test`

Observe on the dashboard that it is created with a CPU of only 1.

To get the CPU value to be respected, I had to fix `firebase-functions` to pass through the `cpu` field from the options into the trigger annotation, and then I had to fix `firebase-tools` to copy the `cpu` field from the annotation into the endpoint spec. Then it worked.

### [REQUIRED] Expected behavior

The configured CPU is applied, as documented in https://firebase.google.com/docs/functions/beta/manage-functions.

### [REQUIRED] Actual behavior

The configured CPU is not applied.

**Comment by inlined** [comment]
Confirmed fixed in the attached pull request. This should be fixed in our next minor CLI version, which we're working on as our top priority.
