### ISSUE TITLE
M1 Macbook: Error: listen `EADDRINUSE`: address already in use `:::9005`

### ISSUE THREAD

**Issue by thathurtabit** [firebase/firebase-tools#4684]
### [REQUIRED] Environment info

 

**firebase-tools:** 11.1.0

 

**Platform:** macOS 12.2.1

### [REQUIRED] Test case

I've just bought a new Macbook Pro (M1 Pro Chip) and have cloned a repo that runs without issue on my previous (non-M1) Macbook Pro - I mention this as I've heard M1 Macs won't run some applications...

Anyway,

* `npm i -g firebase-tools` - node version 16.14.2 | npm 8.5.0
* `$ firebase` outputs expected `Usage: firebase [options] [command]...` options
* `$ firebase emulators:start --only functions`

`ui-debug.log` outputs this (before crash):

```
Web / API server started at localhost:4000
```

Fails with:

```
i  emulators: Starting emulators: functions
⚠  functions: The following emulators are not running, calls to these services from the Functions emulator will affect production: auth, firestore, database, hosting, pubsub, storage
✔  functions: Using node@16 from host.
i  ui: Emulator UI logging to ui-debug.log
i  functions: Watching "/Users/myname/Repos/my-firebase-app/functions/" for Cloud Functions...
node:events:504
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::9005
    at Server.setupListenHandle [as _listen2] (node:net:1330:16)
    at listenInCluster (node:net:1378:12)
    at Server.listen (node:net:1465:7)
    at /Users/myname/Repos/my-firebase-app/functions/lib/index.js:75:47
    at new Promise (<anonymous>)
    at /Users/myname/Repos/my-firebase-app/functions/functions/lib/index.js:75:11
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1357:8)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'EADDRINUSE',
  errno: -48,
  syscall: 'listen',
  address: '::',
  port: 9005
}
i  emulators: Shutting down emulators.
i  ui: Stopping Emulator UI
⚠  Emulator UI has exited upon receiving signal: SIGINT
i  functions: Stopping Functions Emulator
i  hub: Stopping emulator hub
i  logging: Stopping Logging Emulator

```
Attempt to track down in-use port (`9005`?)

```
lsof -i tcp:9005
kill $(lsof -ti:9005)
kill: not enough arguments
```

### [REQUIRED] Steps to reproduce

Try to follow the above

### [REQUIRED] Expected behavior

Firebase functions run...

### [REQUIRED] Actual behavior

Firebase functions crash with above error

**Comment by bkendall** [comment]
So it's trying to bind to the `[::]` IPv6 address. Can you confirm a couple things?

1. Does this work after a fresh reboot?
2. Do you have the host and/or port configured in `firebase.json`? Could you configure the host in `firebase.json` for the functions emulator to use `"host": "127.0.0.1"`? The DNS resolver is picking the IPv6 address (even though we configure it not to), so I'm a little confused why it's doing that. Forcing it to the IPv4 address would at least see if the issue persists when it's not doing IPv6

**Comment by thathurtabit** [comment]
Hi @bkendall - thanks looking into this.

Unfortunately the problem still remains after a couple of reboots.

My current `firebase.json` looks like:

```json
{
  "functions": {
    "runtime": "nodejs16",
    "predeploy": [
      "npm --prefix \"$RESOURCE_DIR\" run lint",
      "npm --prefix \"$RESOURCE_DIR\" run build"
    ]
  }
}

```

I've tried to update as such (though I'm not sure if that's configured correctly):
```json
{
  "functions": {
    "runtime": "nodejs16",
    "host": "127.0.0.1",
    "predeploy": [
      "npm --prefix \"$RESOURCE_DIR\" run lint",
      "npm --prefix \"$RESOURCE_DIR\" run build"
    ]
  }
}
```

But unfortunately it's the the exactly same error 😢

**Comment by bkendall** [comment]
https://firebase.google.com/docs/emulator-suite/install_and_configure#security_rules_configuration has an eexample of how to set up the emulator ports. you should be able to set up something like

```json
{
  "emulators": {
    "functions": {
      "host": "127.0.0.1"
    }
  }
}
```

**Comment by thathurtabit** [comment]
Thanks @bkendall -

**firebase.json** now looks like (which I'm hoping is correct)

```json
{
  "functions": {
    "runtime": "nodejs16",
    "predeploy": [
      "npm --prefix \"$RESOURCE_DIR\" run lint",
      "npm --prefix \"$RESOURCE_DIR\" run build"
    ]
  },
  "emulators": {
    "functions": {
      "host": "127.0.0.1"
    }
  }
}

```

but unfortunately looks like the same error:

```bash
 firebase emulators:start --only functions
i  emulators: Starting emulators: functions
⚠  functions: The following emulators are not running, calls to these services from the Functions emulator will affect production: auth, firestore, database, hosting, pubsub, storage
✔  functions: Using node@16 from host.
i  ui: Emulator UI logging to ui-debug.log
i  functions: Watching "/Users/myname/Repos/music-notes-service/functions" for Cloud Functions...
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::9005
    at Server.setupListenHandle [as _listen2] (node:net:1372:16)
    at listenInCluster (node:net:1420:12)
    at Server.listen (node:net:1508:7)
    at /Users/myname/Repos/music-notes-service/functions/lib/index.js:75:47
    at new Promise (<anonymous>)
    at /Users/stephenfairbanks/Repos/music-notes-service/functions/lib/index.js:75:11
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1399:8)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'EADDRINUSE',
  errno: -48,
  syscall: 'listen',
  address: '::',
  port: 9005
}
i  emulators: Shutting down emulators.
i  ui: Stopping Emulator UI
⚠  Emulator UI has exited upon receiving signal: SIGINT
i  functions: Stopping Functions Emulator
i  hub: Stopping emulator hub
i  logging: Stopping Logging Emulator

Error: An unexpected error has occurred.

```

**Comment by bkendall** [comment]
Ahh - I wonder if you were starting up an express server on the same `PORT` somehow, and that was causing the conflict. Glad you found it though!

**Comment by mradamhoward** [comment]
I have the exact same problem but I am not using apollo-server-express. any ideas?

**Comment by indieocean** [comment]
We are experiencing the same issue as well.

**Comment by Beast-O-Group** [comment]
@mradamhoward Thanks a lot it worked for me

**Comment by mradamhoward** [comment]
Happy to help

**Comment by Beast-O-Group** [comment]
Its always good to help.

**Comment by MicahRCM** [comment]
Hey ya'll literally have the stupidest fix, but I just incremented the port I was using up by 1 and it magically deployed with no issues after banging my head for an hour. Huge help to me for tracking down the (extremely obvious issue of overlapping ports) was 
```firebase deploy --only functions --debug```

Best of luck!
