### ISSUE TITLE
Can't open firebase-tools-instant-win.exe on Windows 7

### ISSUE THREAD

**Issue by barisozbey** [firebase/firebase-tools#4699]
Hi guys, 

I'm still using Windows 7. I'cant install Firebase CLI. I can't use npm cuz node.js doesn't support Windows 7 anymore. When I open it, I see the shell window for a second, and then it's getting closed.

**Comment by AnujSsStw** [comment]
maybe try installing it on the wsl terminator.
https://docs.microsoft.com/en-us/windows/dev-environment/javascript/nodejs-on-wsl

**Comment by yuchenshi** [comment]
In case it is not clear, the standalone binary also bundles Node.js. Sorry, we really don't have the magic ability to fix Node.js compatibility with Windows, and I believe the workaround is to either using another installation method (e.g. WSL) or use an earlier Firebase CLI version.
