### ISSUE TITLE
Firestore Emulator different behavior in the Emulator and Cloud with OrderBy

### ISSUE THREAD

**Issue by MorenoMdz** [firebase/firebase-tools#4701]
### [REQUIRED] Environment info

**firebase-tools:** 
11.1.0

**Platform:**
MacOs

### [REQUIRED] Test case

The code below does not error locally with the emulator, but errors when targeting the cloud db.

```js
  let baseQuery = db
    .collection('incentives')
    .where('startTime', '<=', new Date())
    .where('status', '==', IncentiveStatus.Active)
    .where('target', '==', target)
    .where('valueType', 'in', [
      ValueType.Cash,
      ValueType.HourlyRate,
      ValueType.Rate,
    ])
    .orderBy('startTime')

  if (shiftId) {
    baseQuery = baseQuery.where('shiftId', '==', shiftId)
  }
  if (shiftIncentivesOnly) {
    baseQuery = baseQuery.orderBy('shiftId') // this is being used to ONLY fetch documents that have this field
  }

  const ref = await baseQuery.withConverter(defaultConverter<Incentive>()).get()
  const startedIncentives = ref.docs.map((doc) => ({
    id: doc.id,
    ...doc.data(),
  }))
...
```

### [REQUIRED] Expected behavior

Same errors in the emulator and in the cloud.

### [REQUIRED] Actual behavior

The emulator accepts this query and responds correctly.

**Comment by MorenoMdz** [comment]
> @MorenoMdz What is the production error message exactly? If it is related to missing indexes, then you've run into #2027 where Firestore indexes must be explicitly created in production but not the emulator. If so, feel free to close this issue and subscribe / +1 there. If it is something else, please provide as much information about the error as possible.

We could close this one, but looks like #2027 has many comments without much attention, we do need to have the same behavior in the emulator and the cloud db ideally.

**Comment by KarlsMaranjs** [comment]
I am encountering a very similar issue. But in my case I do not have an orderBy clause nor I receive any error in the emulator. I am using this query to fetch some products that belong to a user
```javascript
const prodRef = collection(firestore, ownerPath + '/products')
	const prodQuery = query(
		prodRef,
		where('category', '==', queryResult.id),
		where('available', '>', 0)
	)
const queryProducts = await getDocs(prodQuery)
```
I have this index created in firestore to handle the query:
![image](https://github.com/firebase/firebase-tools/assets/17086444/6dabf6d2-a025-463f-a024-4d937021676e)

When running locally I can fetch the products, however in the cloud environment I get an empty result (`queryProducts.empty === true`) and no product is retrieved. I have double checked that the info I am trying to retrieve exists and that the ids are all correct. But still nothing.
