### ISSUE TITLE
11.2.0 Functions no longer deploy

### ISSUE THREAD

**Issue by nery** [firebase/firebase-tools#4703]
### [REQUIRED] Environment info

**firebase-tools:**  11.2.0

**Platform:** Ubuntu, macOS
**Node:**  14.19.0
**Package Manager** NPM

### [REQUIRED] Test case

Create a new project and include a new `helloWorld` function. 
Update firebase config with key value pairs of both `string` and `object` values.
Try to deploy said function.

### [REQUIRED] Steps to reproduce

Type `firebase deploy --only functions:helloWorld` or `firebase deploy --only functions` in a console on a newly created project.

### [REQUIRED] Expected behavior

The firebase function(s) are deployed.

### [REQUIRED] Actual behavior

Deployment fails in all cases. Temporary resolution is rolling back to using an older version of `firebase-tools@11.0.0`

```logs
[2022-07-02T05:21:46.801Z] >>> [apiv2][query] GET https://runtimeconfig.googleapis.com/v1beta1/projects/***/configs [none]

[2022-07-02T05:21:46.920Z] <<< [apiv2][status] GET https://runtimeconfig.googleapis.com/v1beta1/projects/***/configs 200

[2022-07-02T05:21:46.921Z] <<< [apiv2][body] GET https://runtimeconfig.googleapis.com/v1beta1/projects/***/configs {*******}

[2022-07-02T05:21:46.923Z] >>> [apiv2][query] GET https://runtimeconfig.googleapis.com/v1beta1/projects/***/configs/cloudtask****url/variables [none]

[2022-07-02T05:21:47.013Z] <<< [apiv2][status] GET https://runtimeconfig.googleapis.com/v1beta1/projects/***/configs/cloudtask****url/variables 200

[2022-07-02T05:21:47.013Z] <<< [apiv2][body] GET https://runtimeconfig.googleapis.com/v1beta1/projects/***/configs/cloudtask****url/variables {}

[2022-07-02T05:21:47.014Z] Got unexpected error from Runtime Config; it has no status code:Cannot read property 'map' of undefined {"level":"debug"}
```
*Some pats have been scrubbed for data sensitivity reasons*

**Comment by anandsathe67** [comment]
Running into this as well. Disappointed how a release can be put out when basic deployment fails. Confirming downgrade to 11.0.0 works

**Comment by AriDevC** [comment]
I'm facing the same issue, after updating firebase-tools.

**Comment by dawogfather** [comment]
pretty annoyed also as i've hit a similar issue and wasted two days on it... will firebase reimburse me for it? 
i understand these things are complex but yeah we can't have these sorts of breaking changes to the tools. it's the second time its happened to me in the past two product releases...

**Comment by pradella** [comment]
I didn't test downgrading to 11.1.0, but I have downgraded to 10.2.2 and worked again.

**Comment by taeold** [comment]
Apologies folks for the issue. I'm going to consolidate this issue report to https://github.com/firebase/firebase-tools/issues/4706 which (I believe) describes the same root cause.

**Comment by nery** [comment]
Confirming this was fixed in #4706 and verified in version 10.3.0

**Comment by pranavwizphys** [comment]
Does not work with 10.3.0 version

**Comment by OlegNovosad** [comment]
Stopped working today. Version: `13.11.2`. Tried all other versions up to 10.x.y

**Comment by canbal** [comment]
> Stopped working today. Version: `13.11.2`. Tried all other versions up to 10.x.y

It might actually be an issue. I didn't change versions, and I'm seeing the same error. The timing of your post tells me the error message might indeed be related to GCP, and temporary.

**Comment by OlegNovosad** [comment]
> > Stopped working today. Version: `13.11.2`. Tried all other versions up to 10.x.y
> 
> It might actually be an issue. I didn't change versions, and I'm seeing the same error. The timing of your post tells me the error message might indeed be related to GCP, and temporary.

I was not changing versions this morning but started to do it in hope to resolve as our team needs to upload a critical fix exactly today :)

**Comment by jibril-gudal** [comment]
also seeing this issue atm

**Comment by doczoidberg** [comment]
same problem!

**Comment by Azati1** [comment]
> I was not changing versions this morning but started to do it in hope to resolve as our team needs to upload a critical fix exactly today :)

You can try to use google cloud console. It is possible to update your functions from online web editor. I have the same problem today and this is the only solution that helped me at the moment. https://console.cloud.google.com/functions

**Comment by doczoidberg** [comment]
this is not acceptable! my customers kill me

**Comment by canbal** [comment]
I filed a support ticket with GCP.

**Comment by theConstantHustler** [comment]
issue with v13.11.2 from morning!

**Comment by chrisK824** [comment]
Same here v12.3.1

**Comment by karolysaysbye** [comment]
Same issue like 1 hour ago :(

**Comment by andy-fang-piccollage** [comment]
Same issue here 😢 @ version `13.11.2`

**Comment by tringuyen99** [comment]
Same issue here 🤬 version @13.11.2

**Comment by iwanwmys** [comment]
Same issue here. Tried using an earlier version of firebase-tools,`11.24.1` and still getting "Cloud Runtime Config is currently experiencing issues ..." message but it's been almost an hour now.

**Comment by nandahibatullah** [comment]
Same issue, version @13.11.2
No changes to functions since the 12th either. Luckily this is't breaking our prod instance
or else we'd be otw to AWS

**Comment by theConstantHustler** [comment]
AWS 🏃 ...........GCP

**Comment by majoess** [comment]
Same issue

**Comment by shoppeva** [comment]
Still happening

**Comment by artemkurtiak** [comment]
Same issue

**Comment by T-P-F** [comment]
same:

% firebase deploy --only functions    

=== Deploying to '<>'...

i  deploying functions
Running command: npm --prefix "$RESOURCE_DIR" run lint

> lint
> eslint

✔  functions: Finished running predeploy script.
i  functions: preparing codebase default for deployment
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
i  artifactregistry: ensuring required API artifactregistry.googleapis.com is enabled...
✔  functions: required API cloudfunctions.googleapis.com is enabled
✔  functions: required API cloudbuild.googleapis.com is enabled
✔  artifactregistry: required API artifactregistry.googleapis.com is enabled

Error: Cloud Runtime Config is currently experiencing issues, which is preventing your functions from being deployed. Please wait a few minutes and then try to deploy your functions again.
Run `firebase deploy --except functions` if you want to continue deploying the rest of your project.

**Comment by T-P-F** [comment]
also in this command which we've been using for months/years:

% firebase functions:config:set node.env="prod"

Error: Unable to parse JSON: SyntaxError: Unexpected token < in JSON at position 0

**Comment by apovall** [comment]
Also seeing this, but kinda glad that others are too. I was tearing my hair out as to what is going on. Using `firebase tools @11.29.1`

**Comment by desk-pro** [comment]
Same here

**Comment by andrea809** [comment]
same here, version 13.11.2

**Comment by edwin-vinsyt** [comment]
Same issue with version firebase-tools@13.11.2

**Comment by rzfang** [comment]
> I filed a support ticket with GCP.

@canbal , any url link related ?
stare and reload page is all I can do...

**Comment by minki607** [comment]
anything related to cloud runtime config doesn't seem to work. things like firebase functions:config:get, set, unset doesn't work

**Comment by canbal** [comment]
> > I filed a support ticket with GCP.
> 
> @canbal , any url link related ? stare and reload page is all I can do...

It's an internal to the company support ticket. They will respond back via email. I'll report back.

**Comment by Xaypanya** [comment]
Encountering the same issue

`Error: Cloud Runtime Config is currently experiencing issues, which is preventing your functions from being deployed. Please wait a few minutes and then try to deploy your functions again.

To proceed with deploying the remainder of your project while excluding functions:
Run `firebase deploy --except functions`

**Comment by Xaypanya** [comment]
Encountering the same issue

Error: Cloud Runtime Config is currently experiencing issues, which is preventing your functions from being deployed. Please wait a few minutes and then try to deploy your functions again.

To proceed with deploying the remainder of your project while excluding functions:
Run `firebase deploy --except functions`

**Comment by janpansa** [comment]
Same issue for firebase deploy --only functions

tried with 12.5.4 and also latest versions.

Both used to work, but this morning not working.

**Comment by T-P-F** [comment]
![Screenshot 2024-06-19 at 11 17 46](https://github.com/firebase/firebase-tools/assets/61667947/7cd6c651-37c8-417e-8882-a174dfc9831f)

https://status.cloud.google.com/index.html

Status page is on the case! Time for a status page for the status page.

**Comment by philajay** [comment]
Error: Cloud Runtime Config is currently experiencing issues, which is preventing your functions from being deployed. Please wait a few minutes and then try to deploy your functions again.
Run `firebase deploy --except functions` if you want to continue deploying the rest of your project.

Exactly same issue on both windows and mac. Just happy to know its not me only

**Comment by utkarsh-verificient** [comment]
Yes it's working now

**Comment by phminella** [comment]
thanks for the fixing!

**Comment by hunterliu1003** [comment]
Same issue and it's working now.

**Comment by pranavwizphys** [comment]
For me that issue is gone but facing new issue 
package.json in functions directory has an engines field which is unsupported. Valid choices are: {"node": 10|12|14|16}

Deploys to runtimes below Node.js 10 are now disabled in the Firebase CLI. Existing Node.js 8 functions will stop executing at a future date. Update existing functions to Node.js 10 or greater as soon as possible.

Having trouble? Try firebase [command] --help
