### ISSUE TITLE
I get downloading cloud-firestore-emulator-v1.11.12.jar... every single time I start the emulators

### ISSUE THREAD

**Issue by MiguelNiblock** [firebase/firebase-tools#4705]
Every single time I start the firebase emulator I get `downloading cloud-firestore-emulator-v1.11.12.jar...`. Which takes a long time.

 I think this is not normal. How can I make so it doesn't have to download every time?

**Comment by bkendall** [comment]
What platform are you on? What version of `firebase-tools`? How did you install the CLI? Do you have logs to share?

The template is there to answer most of these questions. Please create a new issue with the appropriate information.

**Comment by agustincards14** [comment]
I am getting the error when using a script to run `emulators:start` in order to import/export firestore data into a certain folder.

firebase version 12.4.3
