### ISSUE TITLE
firebase login: google url authentication fails.

### ISSUE THREAD

**Issue by techtrapigo** [firebase/firebase-tools#471]
After copy pasting google auth url and choosing correct google account, it redirects to a localhost url which obviously fails.

Here is the google auth url:
https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=1010117220&redirect_uri=http%3A%2F%2Flocalhost%3A9005

Here is the url it goes to :
http://localhost:9005/?state=1010117220&code=4/ju2FikUtSdWac5FfTd75TzzDeys1wbe_wWyU3WA4qSk&authuser=1&session_state=80c0659aa8b1c1c721031e23850104b69eb75df3..3247&prompt=consent#

Please suggest what is wrong. Thanks

**Comment by mbleigh** [comment]
Please try running `firebase login --no-localhost` and follow the steps there. Reopen if that doesn't help 😄
