### ISSUE TITLE
11.2.0 fails to deploy: `Cannot specify both --only and --except` 

### ISSUE THREAD

**Issue by sunadoi** [firebase/firebase-tools#4710]
### [REQUIRED] Environment info

**firebase-tools:** 11.2.0

**Platform:** macOS, Ubuntu
**yarn:** 1.22.10

### [REQUIRED] Test case

Run  `yarn firebase deploy --except functions --project foo`

### [REQUIRED] Steps to reproduce

Update to v11.2.0, then run the above command.
Successfully deployed with v11.1.0.

### [REQUIRED] Expected behavior

Successfully deployed.

### [REQUIRED] Actual behavior

```
yarn firebase deploy --except functions --project foo

Error: Cannot specify both --only and --except
```

I'm only specifying `--except` option but I got the error.
Rolling back to 11.1.0 resolves the issue.

**Comment by bkendall** [comment]
What _are_ you deploying when you specify `--except functions`? Does your codebase include Hosting? RTDB rules? Can you share the relevant parts of `firebase.json`?

**Comment by sunadoi** [comment]
Thanks for the reply.
Here are the relevant configuration files and deploy command.

firebase.json
```
{
  "firestore": {
    "rules": "firestore.rules",
    "indexes": "firestore.indexes.json"
  },
  "functions": {
    "predeploy": ["yarn --cwd \"$RESOURCE_DIR\" install", "yarn --cwd \"$RESOURCE_DIR\" build"]
  },
  "hosting": [
    {
      "target": "target",
      ...
    },
  ],
  "storage": {
    "rules": "storage.rules"
  },
  "emulators": {
    ...
  }
}

```

.firebaserc
```
{
  "projects": {
    "default": "test",
    "prod": "prod"
  },
  "targets": {
    "test": {
      "hosting": {
        "target": [
          "test"
        ]
      }
    },
    "prod": {
      "hosting": {
        "target": [
          "prod"
        ]
      }
    }
  }
}

```

deploy command
```
npx firebase deploy --except functions --project test
```

**Comment by bkendall** [comment]
I'm pretty sure this is the same underlying issue as #4698. That fix is underway - if it's not fixed in the next release (after 11.2.1 - whatever's next), please re-open and I'll take another look.

Duplicate of #4698

**Comment by bkendall** [comment]
Duplicate of #4698

**Comment by sunadoi** [comment]
Confirmed that I can deploy with 11.2.1.
Thank you!!
