### ISSUE TITLE
Randomly occurring `getaddrinfo ENOTFOUND` error when deploying functions

### ISSUE THREAD

**Issue by eob** [firebase/firebase-tools#474]
### Version info

3.12.0

### Steps to reproduce

Happens randomly when I run

```
firebase deploy --only functions
```

### Expected behavior

Functions deploy.

### Actual behavior

Deployment fails with the following output:

```
i  deploying functions
i  functions: ensuring necessary APIs are enabled...
i  runtimeconfig: ensuring necessary APIs are enabled...
✔  runtimeconfig: all necessary APIs are enabled
✔  functions: all necessary APIs are enabled
i  functions: preparing functions directory for uploading...

Error: Server Error. getaddrinfo ENOTFOUND runtimeconfig.googleapis.com runtimeconfig.googleapis.com:443
```

**Comment by laurenzlong** [comment]
Sorry, this is due to instability in the Runtime Config service, with a temporary partial outage. The issue should be resolved now, and we are also working on revising the deploy process so that calling the RuntimeConfig service is optional and only done if you actually make use of config variables in your functions.

**Comment by rilian** [comment]
i have several runtime config options, and i'm getting these 

```
Server Error. getaddrinfo ENOTFOUND runtimeconfig.googleapis.com runtimeconfig.googleapis.com:443
```
on every 2nd `firebase deploy`

**Comment by shaimo** [comment]
This happens to me almost on every deploy. Each time 2-3 of the functions get this error and I have to re-deploy. Any way to make it more reliable?

**Comment by ricardo-journey** [comment]
@laurenzlong Do could you let us know if this is an issue that the Firebase team is planning on fixing and what would be the timeline?

**Comment by KrisBraun** [comment]
I am also regularly hitting this regularly in the last couple days.

**Comment by KrisBraun** [comment]
I've discovered in my case this was likely caused by deploying too many functions together. Since re-architecting to deploy in groups with <10 functions each, I haven't hit this yet.

**Comment by shaimo** [comment]
@KrisBraun is there a recommended way to break a project in a way that would allow deploying in “groups”? Can you tag a function as belonging in some group, or do it by separate files or anything like that?

**Comment by KrisBraun** [comment]
@shaimo This: https://firebase.google.com/docs/functions/organize-functions

You deploy per group, and can also run commands against a group (e.g. `firebase functions:delete admin`).

As an update, I just hit this error again on one of my larger groups with 7 functions.

**Comment by laurenzlong** [comment]
@ricardo-journey Can you please file a new issue if you are still experiencing this? And include your exact error messages. 

@shaimo we recommend deploying functions in groups of 10 or less, and @KrisBraun's link is the right one to follow.

**Comment by ricardo-journey** [comment]
@laurenzlong Actually, its a different error message. Here is the link to the new issue: https://github.com/firebase/firebase-tools/issues/2168 Thanks.
