### ISSUE TITLE
Cannot create CI tokens using a service account key file

### ISSUE THREAD

**Issue by cgranttm** [firebase/firebase-tools#4749]
### [REQUIRED] Environment info

**firebase-tools:**

11.2.2

**Platform:**

Windows

### [REQUIRED] Test case

Running firebase login:ci as a service account.

### [REQUIRED] Steps to reproduce

1. Create a service account with project editor permissions in the firebase GCP project, then export a key file from the IAM service account page in the GCP cloud console and save it locally.
2. Create an environment variable called GOOGLE_APPLICATION_CREDENTIALS pointing to that key file
3. Run `firebase login:ci` should use the application credentials file then output a CI token and not open a web browser with a login prompt.

### [REQUIRED] Expected behavior

The login token should be displayed in the console instead of opening a browser window.

### [REQUIRED] Actual behavior

A browser window with a login prompt appears.

As per https://github.com/firebase/firebase-tools/issues/2158 we would like to be able to generate CI tokens that don't expire after an hour but our gsuite policy makes them expire too quickly to be useful for CI, at the moment we're updating the token manually each time we need to deploy which is not ideal. We have also reproduced this on Macs running firebase 11.2.2.

**Comment by cgranttm** [comment]
Also we have verified that the environment variable is set up correctly, running `gcloud auth activate-service-account --key-file=$env:GOOGLE_APPLICATION_CREDENTIALS` successfully logs in as the service account in powershell.

**Comment by bkendall** [comment]
I don't believe `login:ci` would work with service accounts. In short, that token would be "owned" by the service account, and frankly I'm not sure if that's possible. To that end, I think this is WAI.

However, I assume you're wanting to run some CI pipeline using `firebase` commands? I think you want to follow [the guidance in that issue](https://github.com/firebase/firebase-tools/issues/2158#issuecomment-618075493) to set `GOOGLE_APPLICATION_CREDENTIALS` to a SA key that has the required permissions. With that set, the CLI should authenticate with the SA and be able to run.

If I'm misunderstood the endgame let me know, but this is my read of the issue you've described.

(Further, we're actually looking to move away from `login:ci` and `--token` generally in the CLI, so even if this path would work, it would eventually be deprecated)

**Comment by thipokch** [comment]
@bkendall So would this mean the we would have to encode the json as base64 and decode it on a ci machine? 🥲

**Comment by cgranttm** [comment]
@bkendall from that I think what we need to do is make a new SA that only has the firebasehosting.admin role, then store the keyfile in CI as well?

Thanks!

**Comment by bkendall** [comment]
Yup, that should do it (depending on what you're doing, of course).
