### ISSUE TITLE
When deploying functions: TypeError: Cannot read property 'service' of undefined

### ISSUE THREAD

**Issue by abMarlim** [firebase/firebase-tools#4770]
### [REQUIRED] Environment info

**firebase-tools:** 11.3.0

**Platform:** macOS
**Node:** v16.16.0

### [REQUIRED] Test case

Attempt to deploy updated functions that were previously deployed

### [REQUIRED] Steps to reproduce

Deploy via CLI with firebase deploy --only functions command

### [REQUIRED] Expected behavior

Deploy from "functions" folder normally

### [REQUIRED] Actual behavior

At the end of the firebase-debug.log file:
```
[debug] [2022-07-21T20:07:38.932Z] Building nodejs source
[debug] [2022-07-21T20:07:38.938Z] Could not find functions.yaml. Must use http discovery
[debug] [2022-07-21T20:07:39.155Z] Serving at port 9005

[debug] [2022-07-21T20:07:39.355Z] Got response from /__/functions.yaml {"endpoints":{"externals":{"platform":"gcfv1","httpsTrigger":{},"entryPoint":"externals"},"api_v1":{"platform":"gcfv1","httpsTrigger":{},"entryPoint":"api_v1"},"apiv2":{"platform":"gcfv2","labels":{},"httpsTrigger":{},"entryPoint":"apiv2"}},"specVersion":"v1alpha1","requiredAPIs":[]}
[debug] [2022-07-21T20:07:39.363Z] shutdown requested via /__/quitquitquit

[info] i  functions: preparing functions directory for uploading... 
[info] i  functions: packaged /Users/alexbrasileiro/Marlim/cryptoApi/functions (137.46 KB) for uploading 
[info] i  functions: packaged /Users/alexbrasileiro/Marlim/cryptoApi/functions (138.29 KB) for uploading 
[debug] [2022-07-21T20:07:39.601Z] >>> [apiv2][query] GET https://cloudfunctions.googleapis.com/v1/projects/marlim-crypto/locations/-/functions [none]
[debug] [2022-07-21T20:07:40.596Z] <<< [apiv2][status] GET https://cloudfunctions.googleapis.com/v1/projects/marlim-crypto/locations/-/functions 200
[debug] [2022-07-21T20:07:40.596Z] <<< [apiv2][body] GET https://cloudfunctions.googleapis.com/v1/projects/marlim-crypto/locations/-/functions {"functions":[{"name":"projects/marlim-crypto/locations/us-central1/functions/api_v1","httpsTrigger":{"url":"https://us-central1-marlim-crypto.cloudfunctions.net/api_v1","securityLevel":"SECURE_OPTIONAL"},"status":"ACTIVE","entryPoint":"api_v1","timeout":"60s","availableMemoryMb":256,"serviceAccountEmail":"marlim-crypto@appspot.gserviceaccount.com","updateTime":"2022-07-21T19:21:46.151Z","versionId":"36","labels":{"deployment-tool":"cli-firebase"},"sourceUploadUrl":"https://storage.googleapis.com/uploads-836009295537.us-central1.cloudfunctions.appspot.com/61a862ef-69b9-4307-bc20-fea7758ff6b0.zip","environmentVariables":{"FIREBASE_CONFIG":"{\"projectId\":\"marlim-crypto\",\"storageBucket\":\"marlim-crypto.appspot.com\",\"locationId\":\"us-central\"}","GCLOUD_PROJECT":"marlim-crypto"},"runtime":"nodejs16","ingressSettings":"ALLOW_ALL","buildId":"39ea34ce-6268-4ca2-9fe8-67d2cfd13041","buildName":"projects/541573807004/locations/us-central1/builds/39ea34ce-6268-4ca2-9fe8-67d2cfd13041","dockerRegistry":"ARTIFACT_REGISTRY"},{"name":"projects/marlim-crypto/locations/us-central1/functions/externals","httpsTrigger":{"url":"https://us-central1-marlim-crypto.cloudfunctions.net/externals","securityLevel":"SECURE_OPTIONAL"},"status":"ACTIVE","entryPoint":"externals","timeout":"60s","availableMemoryMb":256,"serviceAccountEmail":"marlim-crypto@appspot.gserviceaccount.com","updateTime":"2022-07-21T19:21:45.606Z","versionId":"16","labels":{"deployment-tool":"cli-firebase"},"sourceUploadUrl":"https://storage.googleapis.com/uploads-836009295537.us-central1.cloudfunctions.appspot.com/61a862ef-69b9-4307-bc20-fea7758ff6b0.zip","environmentVariables":{"FIREBASE_CONFIG":"{\"projectId\":\"marlim-crypto\",\"storageBucket\":\"marlim-crypto.appspot.com\",\"locationId\":\"us-central\"}","GCLOUD_PROJECT":"marlim-crypto"},"runtime":"nodejs16","ingressSettings":"ALLOW_ALL","buildId":"39ea34ce-6268-4ca2-9fe8-67d2cfd13041","buildName":"projects/541573807004/locations/us-central1/builds/39ea34ce-6268-4ca2-9fe8-67d2cfd13041","dockerRegistry":"ARTIFACT_REGISTRY"}]}
[debug] [2022-07-21T20:07:40.597Z] >>> [apiv2][query] GET https://cloudfunctions.googleapis.com/v2alpha/projects/marlim-crypto/locations/-/functions [none]
[debug] [2022-07-21T20:07:42.027Z] <<< [apiv2][status] GET https://cloudfunctions.googleapis.com/v2alpha/projects/marlim-crypto/locations/-/functions 200
[debug] [2022-07-21T20:07:42.027Z] <<< [apiv2][body] GET https://cloudfunctions.googleapis.com/v2alpha/projects/marlim-crypto/locations/-/functions {"functions":[{"name":"projects/marlim-crypto/locations/us-central1/functions/apiv2","buildConfig":{"build":"projects/541573807004/locations/us-central1/builds/1f328220-66c7-4bba-aa00-2adaabeaeef0","runtime":"nodejs16","entryPoint":"apiv2","source":{"storageSource":{"bucket":"gcf-v2-sources-541573807004-us-central1","object":"apiv2/function-source.zip"}},"sourceProvenance":{"resolvedStorageSource":{"bucket":"gcf-v2-sources-541573807004-us-central1","object":"apiv2/function-source.zip","generation":"1658431209596789"}}},"state":"FAILED","updateTime":"2022-07-21T19:22:19.383722406Z","labels":{"deployment-tool":"cli-firebase"},"stateMessages":[{"severity":"ERROR","type":"CloudRunServiceNotFound","message":"Cloud Run service projects/marlim-crypto/locations/us-central1/services/apiv2 for the function was not found. The function will not work correctly. Please redeploy."}],"environment":"GEN_2"}]}
[debug] [2022-07-21T20:07:42.187Z] TypeError: Cannot read properties of undefined (reading 'service')
    at /Users/alexbrasileiro/.nvm/versions/node/v16.16.0/lib/node_modules/firebase-tools/lib/deploy/functions/backend.js:197:113
    at Array.map (<anonymous>)
    at loadExistingBackend (/Users/alexbrasileiro/.nvm/versions/node/v16.16.0/lib/node_modules/firebase-tools/lib/deploy/functions/backend.js:197:69)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.existingBackend (/Users/alexbrasileiro/.nvm/versions/node/v16.16.0/lib/node_modules/firebase-tools/lib/deploy/functions/backend.js:173:9)
    at async prepare (/Users/alexbrasileiro/.nvm/versions/node/v16.16.0/lib/node_modules/firebase-tools/lib/deploy/functions/prepare.js:110:115)
    at async chain (/Users/alexbrasileiro/.nvm/versions/node/v16.16.0/lib/node_modules/firebase-tools/lib/deploy/index.js:33:9)
    at async deploy (/Users/alexbrasileiro/.nvm/versions/node/v16.16.0/lib/node_modules/firebase-tools/lib/deploy/index.js:68:5)
[error] 
[error] Error: An unexpected error has occurred.
```

**Comment by colerogers** [comment]
Hi @abMarlim sorry that you've run into this. In order for us to debug what is going on, can you create a minimal reproducible sample of the function(s) that you're trying to deploy. Thanks

**Comment by abMarlim** [comment]
> Hi @abMarlim sorry that you've run into this. In order for us to debug what is going on, can you create a minimal reproducible sample of the function(s) that you're trying to deploy. Thanks

Hi @colerogers of course, I'll try to create an example and get back here as soon as possible ;)

**Comment by aliseifi-business** [comment]
Have this issue as well:

```
CLI Version:   11.3.0
Platform:      win32
Node Version:  v16.13.1
```

**Comment by abMarlim** [comment]
The problem was in using Firebase Cloud Functions **v1** and **v2** in the same project. 

As I needed to use environment variables from v1 `functions.config()`, I was having a conflict and received this error: 

`Detailed stack trace: Error: functions.config() is no longer available in Cloud Functions for Firebase v2. Please see the latest documentation for information on how to transition to using environment variables`

The way to solve it was to use the [codebase](https://firebase.google.com/docs/functions/organize-functions) practice of firebase, with different versions of codes/functions in repositories and thus eliminating the problem.

**Comment by MrCalamitus** [comment]
Hi @abMarlim I have read the documentation but I don´t find the solve at this problem. I made a new project with **firebase init** but i have the same problem.

versions: 
````
npm 8.11.0
node v16.16.0
firebase 11.4.0
````

package.json 
````json
{
  "name": "functions",
  "description": "Cloud Functions for Firebase",
  "scripts": {
    "serve": "firebase emulators:start --only functions",
    "shell": "firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "engines": {
    "node": "16"
  },
  "main": "index.js",
  "dependencies": {
    "firebase-admin": "^10.0.2",
    "firebase-functions": "^3.18.0"
  },
  "devDependencies": {
    "firebase-functions-test": "^0.2.0"
  },
  "private": true
}
````

index.js
````javascript
const functions = require("firebase-functions");

// // Create and Deploy Your First Cloud Functions
// // https://firebase.google.com/docs/functions/write-firebase-functions
//
// exports.helloWorld = functions.https.onRequest((request, response) => {
//   functions.logger.info("Hello logs!", {structuredData: true});
//   response.send("Hello from Firebase!");
// });

````

ERROR : 
<img width="635" alt="image" src="https://user-images.githubusercontent.com/7023270/181602149-44e6520b-2837-42d6-8fc5-bdc943e28464.png">
````bash 
tail firebase-debug.log 
[debug] [2022-07-28T17:38:34.147Z] TypeError: Cannot read properties of undefined (reading 'service')
    at /Users/mrcalamitus/.nvm/versions/node/v16.16.0/lib/node_modules/firebase-tools/lib/deploy/functions/backend.js:197:113
    at Array.map (<anonymous>)
    at loadExistingBackend (/Users/mrcalamitus/.nvm/versions/node/v16.16.0/lib/node_modules/firebase-tools/lib/deploy/functions/backend.js:197:69)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.existingBackend (/Users/mrcalamitus/.nvm/versions/node/v16.16.0/lib/node_modules/firebase-tools/lib/deploy/functions/backend.js:173:9)
    at async prepare (/Users/mrcalamitus/.nvm/versions/node/v16.16.0/lib/node_modules/firebase-tools/lib/deploy/functions/prepare.js:110:115)
    at async chain (/Users/mrcalamitus/.nvm/versions/node/v16.16.0/lib/node_modules/firebase-tools/lib/deploy/index.js:33:9)
    at async deploy (/Users/mrcalamitus/.nvm/versions/node/v16.16.0/lib/node_modules/firebase-tools/lib/deploy/index.js:68:5)
[error] 
[error] Error: An unexpected error has occurred.

````

**Comment by abMarlim** [comment]
> Hi @abMarlim I have read the documentation but I don´t find the solve at this problem. I made a new project with **firebase init** but i have the same problem.
> 
> versions:
> 
> ```
> npm 8.11.0
> node v16.16.0
> firebase 11.4.0
> ```
> 
> package.json
> 
> ```json
> {
>   "name": "functions",
>   "description": "Cloud Functions for Firebase",
>   "scripts": {
>     "serve": "firebase emulators:start --only functions",
>     "shell": "firebase functions:shell",
>     "start": "npm run shell",
>     "deploy": "firebase deploy --only functions",
>     "logs": "firebase functions:log"
>   },
>   "engines": {
>     "node": "16"
>   },
>   "main": "index.js",
>   "dependencies": {
>     "firebase-admin": "^10.0.2",
>     "firebase-functions": "^3.18.0"
>   },
>   "devDependencies": {
>     "firebase-functions-test": "^0.2.0"
>   },
>   "private": true
> }
> ```
> 
> index.js
> 
> ```js
> const functions = require("firebase-functions");
> 
> // // Create and Deploy Your First Cloud Functions
> // // https://firebase.google.com/docs/functions/write-firebase-functions
> //
> // exports.helloWorld = functions.https.onRequest((request, response) => {
> //   functions.logger.info("Hello logs!", {structuredData: true});
> //   response.send("Hello from Firebase!");
> // });
> ```
> 
> ERROR : <img alt="image" width="635" src="https://user-images.githubusercontent.com/7023270/181602149-44e6520b-2837-42d6-8fc5-bdc943e28464.png">
> 
> ```shell
> tail firebase-debug.log 
> [debug] [2022-07-28T17:38:34.147Z] TypeError: Cannot read properties of undefined (reading 'service')
>     at /Users/mrcalamitus/.nvm/versions/node/v16.16.0/lib/node_modules/firebase-tools/lib/deploy/functions/backend.js:197:113
>     at Array.map (<anonymous>)
>     at loadExistingBackend (/Users/mrcalamitus/.nvm/versions/node/v16.16.0/lib/node_modules/firebase-tools/lib/deploy/functions/backend.js:197:69)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async Object.existingBackend (/Users/mrcalamitus/.nvm/versions/node/v16.16.0/lib/node_modules/firebase-tools/lib/deploy/functions/backend.js:173:9)
>     at async prepare (/Users/mrcalamitus/.nvm/versions/node/v16.16.0/lib/node_modules/firebase-tools/lib/deploy/functions/prepare.js:110:115)
>     at async chain (/Users/mrcalamitus/.nvm/versions/node/v16.16.0/lib/node_modules/firebase-tools/lib/deploy/index.js:33:9)
>     at async deploy (/Users/mrcalamitus/.nvm/versions/node/v16.16.0/lib/node_modules/firebase-tools/lib/deploy/index.js:68:5)
> [error] 
> [error] Error: An unexpected error has occurred.
> ```

Hi @MrCalamitus,

In my case after implementing the logic with _codebase_ I needed to **delete all Cloud Functions (v1 and v2)** that were in Firebase, and only then deploy all the functions again using the new codebase practice.

As the project was still in the test phase (not production), it was not a problem for me to delete all the functions, I don't know if it is possible in your case.

I hope it helps ;)
