### ISSUE TITLE
All Firebase Projects are Missing [Multi-Region]

### ISSUE THREAD

**Issue by gOzaru** [firebase/firebase-tools#4773]
### [REQUIRED] Environment info
**firebase-tools: 11.3.0**
**Platform: Windows**

### [REQUIRED] Test case
Use a simple hello world project using Node.js and try deploying to the Firebase using command:
`firebase deploy --only functions`

### [REQUIRED] Steps to reproduce
1. Create a hello world project
2. Add it in index.js
3. Deploy it

### [REQUIRED] Expected behavior
The firebase project should be able to deploy function as it used to be after updating three days ago. But suddenly it started to fail yesterday. I use multi-region based on us-central. I checked the status is okay on: 
- [https://status.cloud.google.com/](https://status.cloud.google.com/)
- [https://status.firebase.google.com/](https://status.firebase.google.com/) 

But the error code is:
```dart
Error: Failed to get Firebase project sultanan. 
Please make sure the project exists and your account has permission to access it.
```

I checked the Firebase console and found out that all of my projects are missing.
I cannot access any of it. 
I used multi-region in us-central.

### [REQUIRED] Actual behavior
It should be able to deploy successfully without any error.

**Comment by gOzaru** [comment]
![SS - Firebase Console Error on 21 July 2022](https://user-images.githubusercontent.com/3258483/180337436-8d58527c-4bcf-4c42-94a0-46e2f732c3ed.png)

**Comment by gOzaru** [comment]
Okay, now I can access my projects. 
But found a new error in debug.log:
```dart
[error] Error: Failed to list Firebase projects. See firebase-debug.log for more info.
[debug] [2022-07-22T01:23:41.940Z] ----------------------------------------------------------------------
[debug] [2022-07-22T01:23:41.943Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\Wege\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js projects:list
[debug] [2022-07-22T01:23:41.944Z] CLI Version:   11.3.0
[debug] [2022-07-22T01:23:41.944Z] Platform:      win32
[debug] [2022-07-22T01:23:41.944Z] Node Version:  v16.14.0
[debug] [2022-07-22T01:23:41.945Z] Time:          Fri Jul 22 2022 09:23:41 GMT+0800 (Singapore Standard Time)
[debug] [2022-07-22T01:23:41.946Z] ----------------------------------------------------------------------
[debug] 
[debug] [2022-07-22T01:23:42.025Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2022-07-22T01:23:42.026Z] > authorizing via signed-in user (wg.igd30@gmail.com)
[debug] [2022-07-22T01:23:42.032Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects pageSize=1000
[debug] [2022-07-22T01:23:52.193Z] Failed to make request to https://firebase.googleapis.com/v1beta1/projects?pageSize=1000
[debug] [2022-07-22T01:24:13.245Z] FirebaseError: Failed to make request to https://firebase.googleapis.com/v1beta1/projects?pageSize=1000
    at RetryOperation._fn (C:\Users\Wege\AppData\Roaming\npm\node_modules\firebase-tools\lib\apiv2.js:241:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[error] 
[error] Error: Failed to list Firebase projects. See firebase-debug.log for more info.
```

Does anyone know what happen?

**Comment by gOzaru** [comment]
After trying to use: `firebase init`
I managed to resetting the firebase, but got a new error again: 
```dart
Error: 
Failed to make request to https://serviceusage.googleapis.com/v1/projects/had-felix/services/firestore.googleapis.com
```

What happened to Firebase anyway?

**Comment by gOzaru** [comment]
> ![SS - Firebase Console Error on 21 July 2022](https://user-images.githubusercontent.com/3258483/180337436-8d58527c-4bcf-4c42-94a0-46e2f732c3ed.png)

Oh no, this is happening again.

**Comment by bkendall** [comment]
1. Can you check the developer tools on chrome? Is that giving you any specific error messages?
2. Are you going through any kind of proxy?

**Comment by gOzaru** [comment]
No, I don't use any proxy.
Is this picture below the main culprit?

![SS - Recommendation Error 02](https://user-images.githubusercontent.com/3258483/180346770-3bd0eafb-f5cd-46c4-ab20-3b2eed54edd7.png)

A week ago, I got recommendation from Google Cloud Platform and asked me to remove all these kinds of roles. But, after that day I can still deploy any of Cloud Functions until yesterday. If this is the culprit, then why did the GCP recommend it to be removed? What happened between Firebase and GCP? Why they considered it to be removes as best practices.

**Comment by gOzaru** [comment]
I had added all removed roles because of GCP Recommendations. 
But, I still get the same error:
```dart
Error: Failed to get Firebase project sultanan. 
Please make sure the project exists and your account has permission to access it.
```

![SS - Recommendation Error 03](https://user-images.githubusercontent.com/3258483/180348524-c1fbec0a-c9ab-4f9f-9069-7bdfbd8c1393.png)

**Comment by gOzaru** [comment]
I did this: 
- firebase login --reauth
- firebase init 
- write No to prevent overwriting the existing files
- firebase deploy --only functions 

and get this error: 

```dart
Error: 
Failed to make request to https://serviceusage.googleapis.com/v1/projects/sultanan/services/runtimeconfig.googleapis.com
This is the data:
{
  "error": {
    "code": 403,
    "message": "The request is missing a valid API key.",
    "status": "PERMISSION_DENIED"
  }
}
```

**Comment by gOzaru** [comment]
Now it returns this error code just like the beginning.
```dart
Error: Failed to get Firebase project sultanan. 
Please make sure the project exists and your account has permission to access it.
```

After I checked the firebase.debug.log, I found out:
```dart
{
  "error": {
    "code": 401,
    "message": "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",
    "status": "UNAUTHENTICATED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "CREDENTIALS_MISSING",
        "domain": "googleapis.com",
        "metadata": {
          "method": "google.firebase.service.v1beta1.FirebaseProjectService.GetFirebaseProject",
          "service": "firebase.googleapis.com"
        }
      }
    ]
  }
}
```

This is my code in index.js:
```js
const admin = require("firebase-admin");
const config = JSON.parse(process.env.FIREBASE_CONFIG);
admin.initializeApp(config);
```

Okay, if this error doesn't give up any hint to solution; I am gonna remove this Firebase project and start over from the beginning. Just because Firebase erased my previous Service Account of Firebase Admin SDK, and that because of the FALSE FLAG made by Google Cloud Platform's Recommendations, I will not ever believe in any of those damn things. This thing really made me upset. It is like there is no collaboration between Firebase and GCP teams.
