### ISSUE TITLE
unkpg.com as CDN is very slow

### ISSUE THREAD

**Issue by xar** [firebase/firebase-tools#4775]
### [REQUIRED] Environment info

**firebase-tools:** 11.3.0

**Platform:** macOs, Linux

### [REQUIRED] Test case

Start Auth emulator and wait for `domcontentloaded`

### [REQUIRED] Steps to reproduce

We have issue with speed of unkpg.com a lot of times It takes too much time to load `material-components-web.min.js` in Auth emulator. We have tried on multiple enviroments (CI in Hetzner, local machine connected to fiber network) often times it takes more than 1 minute to load and as side effect it is failing our tests.
![Screenshot 2022-07-22 at 10 28 06](https://user-images.githubusercontent.com/184865/180397884-2077833f-d262-4774-89f1-5596f73fe222.png)

### [REQUIRED] Expected behavior

Fast CDN / scripts bundled for instant load

### [REQUIRED] Actual behavior

Slow loading of material-components-web.min.js blocking `domcontentloaded`

**Comment by bkendall** [comment]
I'm not sure what this has to do with Firebase or its CLI.

**Comment by xar** [comment]
Hey @bkendall , sorry for late reply - but Firebase is using `unpkg.com` for loading material-components in Auth emulator - when user logs in via Google login...

**Comment by bkendall** [comment]
If you're still seeing issues, I think your best bet would be to reach out to [Firebase support](https://firebase.google.com/support) so they can route this to the right team. Thanks!
