### ISSUE TITLE
TypeError [ERR_INVALID_ARG_VALUE]: The argument 'id' must be a non-empty string. Received ''

### ISSUE THREAD

**Issue by ThatRandomGuy09** [firebase/firebase-tools#4784]
TypeError [ERR_INVALID_ARG_VALUE]: The argument 'id' must be a non-empty string. Received '', i am having this error while working in express.js, can you help me

**Comment by Mr-Robot-err-404** [comment]
Had the same issue, realized it was a very basic mistake. 

In my case, I wrote:
const express = require() instead of:
const express = require("express")

Check that the argument in the bracket is fill. Hope that helps

**Comment by ThatRandomGuy09** [comment]
@Mr-Robot-err-404 I have tried this too but I am getting the same error, trying installing the new version of node and then executing it but it didn't work

**Comment by taeold** [comment]
@ThatRandomGuy09 Hi! As reported, it's difficult for us to track down the issue you are experiencing. Would you mind following the issue template and providing us a small, reproducible code so we can help w/ debugging?

**Comment by ThatRandomGuy09** [comment]
@taeold hey, appreciate your efforts for the help, but I figured the error and solved it, Thanks again

**Comment by fateme-zka** [comment]
> @taeold hey, appreciate your efforts for the help, but I figured out the error and solved it, Thanks again

Can you plz tell us what was your solution?
because I have same issue.

**Comment by fateme-zka** [comment]
> > @taeold hey, appreciate your efforts for the help, but I figured out the error and solved it, Thanks again
> 
> Can you plz tell us what your solution was? because I have the same issue.

As I said I had the same issue, I can bet you, you should check where you require some library. Your problem would be found there🤦‍♂️🤦‍♂️

**Comment by InnocentDaksh63** [comment]
yes in my case it is also happening beacuase i imported a sequelize package by 

const sequelize = require('');
but when i used like -
const sequelize = require('sequelize');  
it gets removed and project is running successfully
