### ISSUE TITLE
Ability to whitelist domains for Firebase Auth to work

### ISSUE THREAD

**Issue by andrewhamili** [firebase/firebase-tools#4789]
I want to deploy my website using firebase Auth Emulator. It actually works not, however, the other auth methods will not work because the domain we are using is not whitelisted. Is there any way to whitelist domain to Firebase Auth Emulator?

**Comment by lisajian** [comment]
Hey @andrewhamili! Could you provide more context to the issue you're running into by filing a support issue here: https://firebase.google.com/support/troubleshooter/contact? As it stands, we don't have enough information to help troubleshoot the issue. Thanks!

**Comment by andrewhamili** [comment]
![image](https://user-images.githubusercontent.com/20767537/182494070-e5814952-0c20-41a3-abe8-f471b75d74f1.png)
Here is the screenshot of what we are experiencing while using Firebase Auth emulator.

Based on the error log. the domain/URL should be whitelisted. But on Firebase Auth emulator, there was no way we could whitelist any URL's for 3rd-party auth providers to work while using the Auth Emulator.

The auth emulator (originally localhost:9099) was placed under proxy so that it will be accessible outside the server via domain. (http://auth-uat.homeful.ph)

**Comment by lisajian** [comment]
The error you're seeing happens when you're trying to hit a domain (in this case for signing in with redirect) but it hasn't been registered as an authorized domain. Please follow the instructions in the error message to do so for your domain, http://auth-uat.homeful.ph.

**Comment by andrewhamili** [comment]
Does this also apply if we are using Auth emulator?

**Comment by lisajian** [comment]
Ah, I see. I'm assuming you're using the JSSDK and followed the instructions https://firebase.google.com/docs/emulator-suite/connect_auth#android_ios_and_web_sdks? You shouldn't be running into that error if you're calling `connectAuthEmulator()`. We'd need more information about what you're doing to help diagnose the issue (e.g. a minimal reproduction); please either follow the bug template for this repo or if you need to share more info on a non-public platform, please file a customer support issue.

**Comment by andrewhamili** [comment]
Hi, the goal of this issue is to have an ability to whitelist a domain for some auth providers (google, facebook, etc) so that firebase emulator could be used for staging (demo) environments
