### ISSUE TITLE
Function timeout is reset to default after deploying

### ISSUE THREAD

**Issue by belenbuccolo** [firebase/firebase-tools#4801]
Related to  [#548](https://github.com/firebase/firebase-tools/issues/548)

### [REQUIRED] Environment info

**firebase-tools:** Latest (11.4.0)
**Platform:** macOS

### [REQUIRED] Test case

Have a function which you want to increase the tiemout to. Increase the timeout on GCP and deploy. On the following deploy the timeout resets back to the default value.

Function with increased timeout:
<img width="928" alt="image" src="https://user-images.githubusercontent.com/35378809/182177109-4a760d6e-0c81-4a88-8e37-36e060e6dc79.png">
Same function after running `firebase deploy --only functions`
<img width="928" alt="image" src="https://user-images.githubusercontent.com/35378809/182176851-8d6dd11d-d8f1-4aae-9cc5-da660e1d01ea.png">

### [REQUIRED] Steps to reproduce

1. Increase the timeout of a function (540s for example) on GCP and deploy it.
2. Deploy all functions using firebase deploy --only functions.
3. See how the function timeout reverted back to 60s

### [REQUIRED] Expected behavior

The timeout should remain 540s

### [REQUIRED] Actual behavior

The timeout resets back to 60s

**Comment by taeold** [comment]
Hi @belenbuccolo. I think our latest CLI release fixes this bug.

FWIW, you can also try setting the timeout manually in your function definition:

https://firebase.google.com/docs/functions/manage-functions#set_timeout_and_memory_allocation

**Comment by justinekatebe69** [comment]
> Hi @belenbuccolo. I think our latest CLI release fixes this bug.
> 
> FWIW, you can also try setting the timeout manually in your function definition:
> 
> https://firebase.google.com/docs/functions/manage-functions#set_timeout_and_memory_allocation

How to do increase timeout inside code for post requests that use app.post ?
