### ISSUE TITLE
Functions Emulator fails to emulated nested exports

### ISSUE THREAD

**Issue by christophe-g** [firebase/firebase-tools#481]
`> firebase experimental:functions:shell` fails at emulating functions organized in sub-folder

### Version info
3.12.0

### Steps to reproduce
Organize function src in a modular way as above

**in `/functions/index.js`** : 
```js
const functions = require('firebase-functions');
exports.builder = require('./src/builder/index');

```
**in `functions/scr/builder/index.js`** : 
``` js
const functions = require('firebase-functions');
const doBuild = require('./listener');

const buildListenerPath = '/build/buildRequest/{uid}/survey/{id}/{lan}/timestamp';
exports.doBuild = functions.database.ref(buildListenerPath).onWrite(doBuild);
```

**and run `firebase experimental:functions:shel`**

### Expected behavior
`builder-doBuild` is emulated

### Actual behavior
console produces 
```
⚠  functions: Failed to emulate Error
```

However this works as expected: 
```js
const builder = require('./src/builder/index');
exports.doBuild = builder.doBuild;
```

**Comment by hariprasadiit** [comment]
facing same issue. any update on this?

**Comment by hariprasadiit** [comment]
@laurenzlong  any update on this issue?

**Comment by laurenzlong** [comment]
Hey @hariprasadiit this is still on our radar, and @tinaliang will be working on it.

**Comment by ChrisTalman** [comment]
This still seems to be a problem.

**Comment by tinaliang** [comment]
This feature has been integrated in #677 , so I will be closing this issue.
