### ISSUE TITLE
Multi-region function deploy fails on v11.4.0

### ISSUE THREAD

**Issue by vojdan** [firebase/firebase-tools#4810]
### [REQUIRED] Environment info

**firebase-tools:** 11.4.0 and 11.4.1 (works fine in 11.3.0)

**Platform:** MacOS, TypeScript

### [REQUIRED] Test case

```
export const theFuncName = functions
	.region('us-central1', 'australia-southeast1')
	.runWith({
	    maxInstances: 50,
        })
	.https.onRequest(async (request: functions.https.Request, response: functions.Response) => {
            // function body
        })
```

### [REQUIRED] Steps to reproduce

`firebase deploy`

### [REQUIRED] Expected behavior
Deploy succeeds.

### [REQUIRED] Actual behavior

Deploy error:
```Error: More than one backend found for function name: theFuncName. If the function is deployed in multiple regions, you must specify a region.```

**Comment by bkendall** [comment]
As of `v11.4.0`, you are able to configure Hosting to rewrite to a function in any region. I'm thinking that throwing an error here was a tad aggressive on our part - maintaining the status quo of "if we see `us-central1` we should continue to use that" should be what we do. We've got a couple things stacked up to make a release of the CLI today, so I'll see if I can make that adjustment.

In the meantime, if in `firebase.json` you specify a `region` for the `rewrite` to your function (either `us-central1` or `australia-southeast1`), you'll be unblocked!

**Comment by vojdan** [comment]
The new default works! The message shows up explaining what the issue is.

Thanks!

**Comment by bkendall** [comment]
👍 you're welcome!
