### ISSUE TITLE
11.4.1 .runtimeconfig.json not loaded in functions emulator

### ISSUE THREAD

**Issue by milo-** [firebase/firebase-tools#4811]
### [REQUIRED] Environment info

**firebase-tools:** 11.4.1

**Platform:** Ubuntu (Github Actions)

### [REQUIRED] Test case

Running the functions emulator no longer works in our github-actions after moving from 11.4.0. to 11.4.1

### [REQUIRED] Steps to reproduce

Run functions emulator in 11.4.1 on ubuntu with .runtimeconfig.json

### [REQUIRED] Expected behavior

The functions emulator should load .runtimeconfig.json and the functions.config() should be available in the emulator

### [REQUIRED] Actual behavior

functions.config() is undefined

**Comment by Den-Ree** [comment]
@milo- I had the same isssue, solved by switching on `GOOGLE_APPLICATION_CREDENTIALS`, problem was that warning  message was inserted in `.runtimeconfig.json`.

**Comment by milo-** [comment]
@Den-Ree you legend thank you! I was logging it out trying to figure out the issue and completely missed that.
