### ISSUE TITLE
"An unexpected error has occurred" with "firebase deploy"

### ISSUE THREAD

**Issue by bpaduch** [firebase/firebase-tools#483]
Just started getting this issue today, recently on our production build in Travis CI ([build link](https://travis-ci.org/ampproject/docs/builds/281400133)):

```text
$ firebase deploy --token "$FIREBASE_TOKEN" --non-interactive
⚠  Your CLI authentication needs to be updated to take advantage of new features.
⚠  Please run firebase login --reauth
=== Deploying to 'ampproject-b5f4c'...
i  deploying hosting
i  hosting: preparing build directory for upload...
i  Progress: [
Error: An unexpected error has occurred.
```
The build works correctly on the Master branch but not production. Worked fine 5 hours ago.

### Version info

firebase version: 3.12

### Steps to reproduce

Restart Travis CI production build and deployment fails with "An unexpected error has occurred".

**Comment by mbleigh** [comment]
We had an [incident affecting deploys](https://status.firebase.google.com/incident/Hosting/17014) earlier today. Should be resolved now.
