### ISSUE TITLE
Unable to deploy functions using vpc connector

### ISSUE THREAD

**Issue by Schmale97** [firebase/firebase-tools#4833]
### [REQUIRED] Environment info

**firebase-tools:** 11.4.2
**firebase-functions:** 3.22.0
**Platform:** macOS
**Node:** 16.6.0

### [REQUIRED] Test case

Functions unable to deploy when deploying to 'europe-west2' when using a vpc connector

### [REQUIRED] Steps to reproduce

1. Set up vpc connector in europe-west2
2. Deploy cloud function that uses the vpc connector 

### [REQUIRED] Expected behavior

Functions deploy successfully

### [REQUIRED] Actual behavior

Functions fail to be created or updated

This doesn't output to thee debug.log file but is in the console logs

[2022-08-04T18:54:48.790Z] <<< [apiv2][body] PATCH https://cloudfunctions.googleapis.com/v1/projects/my-project/locations/europe-west2/functions/login {"error":{"code":400,"message":"The request has errors","status":"INVALID_ARGUMENT","details":[{"@type":"type.googleapis.com/google.rpc.BadRequest","fieldViolations":[{"field":"vpc_connector","description":"A Cloud Function and a Serverless VPC Access connector must be located in the same region."}]}]}}
⚠  functions: failed to update function projects/my-project/locations/europe-west2/functions/login

**Comment by Schmale97** [comment]
I am also seeing an error in the logs where it is unable to detect the firebaseSDK

```
[debug] [2022-08-04T18:54:22.462Z] checkFunctionsSDKVersion encountered error:Invalid Version:  {}
```
```
[debug] [2022-08-04T18:54:23.074Z] Could not parse firebase-functions version '' into semver. Falling back to parseTriggers.
```

**Comment by ZEAL-MATCH-LTD** [comment]
I'm not sure if this is linked but :

### env
```
firebase-tools: 11.4.2
firebase-functions: 3.22.0
Node: v16.16.0
```

### Output
```bash
deploying default flavor
Now using alias default ([appid])

Error: Failed to make request to https://runtimeconfig.googleapis.com/v1beta1/projects/[appid]/configs/slack/variables/webhookurlv2newsignuppractitioner

Error: Failed to make request to https://runtimeconfig.googleapis.com/v1beta1/projects/[appid]/configs/verification/variables

...

✔  functions: Finished running predeploy script.
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
i  artifactregistry: ensuring required API artifactregistry.googleapis.com is enabled...
✔  functions: required API cloudfunctions.googleapis.com is enabled
✔  artifactregistry: required API artifactregistry.googleapis.com is enabled
✔  functions: required API cloudbuild.googleapis.com is enabled
i  functions: preparing codebase default for deployment
i  functions: Loaded environment variables from .env.
i  functions: preparing functions directory for uploading...
i  functions: packaged /Users/[name/Documents/C/[project]/functions (398.39 KB) for uploading
i  functions: ensuring required API cloudscheduler.googleapis.com is enabled...
✔  functions: required API cloudscheduler.googleapis.com is enabled

Error: Failed to get Firebase project zeal-dev-25931. Please make sure the project exists and your account has permission to access it.
```

I've never seen this issue before and i'm

**Comment by Schmale97** [comment]
I think this may be a duplicate actually https://github.com/firebase/firebase-tools/issues/4780
