### ISSUE TITLE
Error [ERR_REQUIRE_ESM]/ ERR_PACKAGE_PATH_NOT_EXPORTED when importing some packages

### ISSUE THREAD

**Issue by rawatnaresh** [firebase/firebase-tools#4859]
### [REQUIRED] Environment info

**firebase-tools:** 11.2.2

**Platform:** macOS

### [REQUIRED] Test case

```js
import * as functions from "firebase-functions";
import fetch from "node-fetch";

export const helloWorld = functions.https.onRequest(async (request, response) => {
  const resp = await fetch('https://github.com/');
  response.send("Hello from Firebase!");
});

```

### [REQUIRED] Steps to reproduce

- init firebase functions `firebase init functions`
- Install node-fetch `yarn add node-fetch`
- Run functions `yarn serve`

### [REQUIRED] Expected behavior

When i use `node-fetch` with other nodejs projects it works perfectly but I'm not able to import it in firebase-functions. Same thing happened while using [ipfs-http-client](https://www.npmjs.com/package/ipfs-http-client#install) with functions.

### [REQUIRED] Actual behavior
`node-fetch`

![Screen Shot 2022-08-11 at 12 09 35](https://user-images.githubusercontent.com/29520305/184075634-261e88e8-439f-4cea-8168-4248a9dd4abf.png)

`ipfs-http-client`

![Screen Shot 2022-08-11 at 12 18 05](https://user-images.githubusercontent.com/29520305/184076624-891e5323-b84c-45cb-87b0-e8c3ca1c29d7.png)

**Comment by bkendall** [comment]
I do believe that `init functions` inits a commonjs module, not an ES module. `node-fetch` at v3+ is an ES module, which cannot be required from a commonjs module. You'll have to make the appropriate updates to `package.json` and `tsconfig.json` to be able to use `node-fetch` v3+. Alternatively, install `node-fetch@2` and this should work.

I'll flag this with the CF3 team and see if we want to change or make the experience different, but hopefully the above unblocks you! 🙂
