### ISSUE TITLE
brave/safari report CORS issue when calling emulated function from nextjs app

### ISSUE THREAD

**Issue by paymog** [firebase/firebase-tools#4864]
### [REQUIRED] Environment info

**firebase-tools:** 11.6.0

**Platform:** macOS

### [REQUIRED] Test case

1. npx create-next-app --ts
2. firebase init (only functions)
3. uncomment the default helloworld example and make it `onCall` instead of `onRequest`
4. create a button in the next app which calls the helloworld callable
5. configure the next app to use the emulator in dev

### [REQUIRED] Steps to reproduce

1. start the next app
2. start the firebase functions emulator - `npm run build && firebase emulators:start --only functions`
3. open the browser to localhost:3000
4. open the browser console
5. click the button from step 4 in the previous section which calls the callable
6. see that there's a CORS issue
7. check the firebase emulator logs and see there aren't CORS issues

### [REQUIRED] Expected behavior

I expect there to be no cors issues when using the emulator

[firebase-debug.log](https://github.com/firebase/firebase-tools/files/9316741/firebase-debug.log)

### [REQUIRED] Actual behavior

There are CORS issues reported by the browser but nothing noted in the logs. Inspecting the browser requests I don't see any `Access-Control-Allow-Origin` heads. I've attached my firebase debug logs. Here are screenshots of the two requests the browser makes when calling the callable.

Overview of two requests

<img width="1090" alt="image" src="https://user-images.githubusercontent.com/1986950/184367145-b5949e80-3096-4cc4-9624-0e9a99c6c3f9.png">

The main request

<img width="1187" alt="image" src="https://user-images.githubusercontent.com/1986950/184367236-6223e6f4-f438-42d7-805b-008dd847acb6.png">

the options request

<img width="864" alt="image" src="https://user-images.githubusercontent.com/1986950/184367262-accfe597-4997-4403-81fc-0e9fc04fe4d2.png">

**Comment by paymog** [comment]
Note that these CORS issues don't exist in production, only when calling the emulated function. In production I have my webapp hosted by Vercel.

**Comment by taeold** [comment]
Do you mind trying out our new Next.js integration to see if you can get around the cors issue?

https://firebase.google.com/docs/hosting/nextjs
