### ISSUE TITLE
firebase deploy functions fails on dependencies on scoped packages

### ISSUE THREAD

**Issue by bittlingmayer** [firebase/firebase-tools#487]
### Version info

3.12.0

### Steps to reproduce

0. Create a project with functions.

1. packages.json - Add a scoped package to `dependencies`

Example: `"@google-cloud/translate": "^1.0.0"`.

You can run `npm install` from inside `functions/` and verify that `functions/node_modules/@google-cloud/common` and `functions/node_modules/@google-cloud/translate` now exist.

2. index.js - Add a `require`to use that package

Example: `const Translate = require('@google-cloud/translate');`

3. Run `firebase deploy`

### Expected behavior

The project should deploy **functions** with no problems, just like when including other packages.

### Actual behavior

> 2
>
> === Deploying to 'xlearn-47d8e'...
>
> i  deploying functions, hosting
i  functions: ensuring necessary APIs are enabled...
i  runtimeconfig: ensuring necessary APIs are enabled...
✔  runtimeconfig: all necessary APIs are enabled
✔  functions: all necessary APIs are enabled
i  functions: preparing functions directory for uploading...
>
> Error: Error parsing triggers: Cannot find module '@google-cloud/translate'
>
> Try running "npm install" in your functions directory before deploying.

**Comment by bittlingmayer** [comment]
### Workaround

1. Comment out the `require` line in index.js, and any lines that reference the module it loads.

2. Run `firebase deploy`

3. In the Cloud Console, go to *Cloud Functions >* function name *> Edit > index.json*, comment everything back in, *Save* and *Test*

**Comment by laurenzlong** [comment]
I followed your steps but am unable to reproduce (using the latest firebase-tools, v3.13.1). As well the error message above says `Cannot find module ''`, which leads me to believe it's something other than @google-cloud/translate that's causing the issue.
