### ISSUE TITLE
.env.local file gets overwritten by Google Secrets manager in Firebase Emulator

### ISSUE THREAD

**Issue by Oktogazh** [firebase/firebase-tools#4872]
### Environment info

**firebase-tools: 11.1.0**

**Platform: Ubuntu**

### Test case
```
// .env.local
STRIPE_SECRET_KEY=sk_test_51KMD...

// index.js
exports.createAccountLink = functions
  .region('europe-west1')
  .runWith({ secrets: ['STRIPE_SECRET_KEY'] })
  .https
  .onCall(async (data, context) => {
    console.log(process.env.STRIPE_SECRET_KEY);
```

### Steps to reproduce
**Case 1**:
Start a function from the emulator which require the `STRIPE_SECRET_KEY` secret, whose value gets overwritten with that of the live secret in the Google Cloud Secret Manager of my project in use.
Yet the log of the emulator states that:
```
functions: Loaded environment variables from .env.local.
i  functions: Finished "createAccountLink" in ~1s
i  functions: Beginning execution of "createAccountLink"
>  {"verifications":{"app":"MISSING","auth":"MISSING"},"logging.googleapis.com/labels":{"firebase-log-type":"callable-request-verification"},"severity":"INFO","message":"Callable request verification passed"}
>  sk_live_...
```

**Case 2**:
When trying to debug that, I modified the name of the secret with  `STRIPE_SECRET_KE` wherever it appears ups there.
As a result I got those error messages:
```
i  functions: Loaded environment variables from .env.local.
⬢  functions: Unable to access secret environment variables from Google Cloud Secret Manager. Make sure the credential used for the Functions Emulator have access or provide override values in /home/alan/amnis/amnis-backend/functions/.secret.local:
        FirebaseError: HTTP Error: 404, Secret [projects/1002743208074/secrets/STRIPE_SECRET_KE] not found or has no versions.
```

### Expected behavior

The variables of the `.env.local` file should be used in the emulator, as I understand it should be done in the documentation.
"[Contents of .env.local take precedence over .env and the project-specific .env file.](https://firebase.google.com/docs/functions/config-env#emulator_support)"

### Actual behavior
I don't know whether that's a bug or a feature but the emulator log is quite misleading as it states that the local `.env.local` file is being used as a source when the function is being called, yet it's the Google Cloud Secret Manager. And until one uses a variable name that's not in the GCSM, it will not be mentioned that the emulator is using this other sevice.

Maybe you could clarify this in the documentation, or make sure the `.env.local` variables take precedence over the Google Cloud Secret Manager variables, or (even better), create an option after `firebase emulator:start` command so that we could decide which variables source we want to take the precedence.

Thank you for your amazing job

**Comment by joehan** [comment]
In order to provide local versions of secrets, you'll need to use a .secret.local file instead of .env.local, as described here: https://firebase.google.com/docs/functions/config-env#secrets_and_credentials_in_the_emulator

So, for your example above, you'll just need to provide the secret value in .secret.local:
```
// .secret.local
STRIPE_SECRET_KEY=sk_test_51KMD...

// .env.local
ANY_OTHER_ENV=still-goes-here-if-it-isnt-secret

// index.js
exports.createAccountLink = functions
  .region('europe-west1')
  .runWith({ secrets: ['STRIPE_SECRET_KEY'] })
  .https
  .onCall(async (data, context) => {
    console.log(process.env.STRIPE_SECRET_KEY);
```
