### ISSUE TITLE
Firebase emulators can't start with emulator Data on one of my computers (exit status 2)

### ISSUE THREAD

**Issue by ThePianistop66** [firebase/firebase-tools#4875]
Node 14.17
java 1.8.0_301
Firebase 9.20.0

Here are the logs:

`0 info it worked if it ends with ok`
`1 verbose cli [`
`1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',`
`1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',`
`1 verbose cli   'run',`
`1 verbose cli   'server'`
`1 verbose cli ]`
`2 info using npm@6.14.14`
`3 info using node@v14.17.5`
`4 verbose run-script [ 'preserver', 'server', 'postserver' ]`
`5 info lifecycle PROJECTNAME@0.1.0~preserver: PROJECTNAME@0.1.0`
`6 info lifecycle PROJECTNAME@0.1.0~server: PROJECTNAME@0.1.0`
`7 verbose lifecycle PROJECTNAME@0.1.0~server: unsafe-perm in lifecycle true`
`8 verbose lifecycle PROJECTNAME@0.1.0~server: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\CLIENT\Documents\PROJECTNAME\node_modules\.bin;C:\Users\CLIENT\AppData\Local\Programs\Python\Python39\Scripts\;C:\Users\CLIENT\AppData\Local\Programs\Python\Python39\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Users\CLIENT\AppData\Local\Microsoft\WindowsApps;C:\Users\CLIENT\AppData\Roaming\npm;C:\Users\CLIENT\AppData\Local\atom\bin;C:\Users\CLIENT\AppData\Local\Programs\Microsoft VS Code\bin`
`9 verbose lifecycle PROJECTNAME@0.1.0~server: CWD: C:\Users\CLIENT\Documents\PROJECTNAME`
`10 silly lifecycle PROJECTNAME@0.1.0~server: Args: [ '/d /s /c', 'firebase emulators:start --import emulatorData' ]`
`11 silly lifecycle PROJECTNAME@0.1.0~server: Returned: code: 2  signal: null`
`12 info lifecycle PROJECTNAME@0.1.0~server: Failed to exec server script`
`13 verbose stack Error: PROJECTNAME@0.1.0 server: `firebase emulators:start --import emulatorData``
`13 verbose stack Exit status 2`
`13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)`
`13 verbose stack     at EventEmitter.emit (events.js:400:28)`
`13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)`
`13 verbose stack     at ChildProcess.emit (events.js:400:28)`
`13 verbose stack     at maybeClose (internal/child_process.js:1055:16)`
`13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)`
`14 verbose pkgid PROJECTNAME@0.1.0`
`15 verbose cwd C:\Users\CLIENT\Documents\PROJECTNAME`
`16 verbose Windows_NT 10.0.19043`
`17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "server"`
`18 verbose node v14.17.5`
`19 verbose npm  v6.14.14`
`20 error code ELIFECYCLE`
`21 error errno 2`
`22 error PROJECTNAME@0.1.0 server: `firebase emulators:start --import emulatorData``
`22 error Exit status 2`
`23 error Failed at the PROJECTNAME@0.1.0 server script.`
`23 error This is probably not a problem with npm. There is likely additional logging output above.`
`24 verbose exit [ 2, true ]`

**Comment by colerogers** [comment]
Please re-open if you're still having this issue
