### ISSUE TITLE
Two different repositories deploying different functions to the same firebase project

### ISSUE THREAD

**Issue by martosoler** [firebase/firebase-tools#488]
### Version info

3.12.0

### Steps to reproduce

I have two different repositories where I was thinking to store my google functions: 
`common-repo` and `application-repo`.

Repository `common-repo` will contain functions that will be heavily used by applications in the client side, while `application-repo` will support the API of each application.
Each one has its corresponding `functions` folder and works fine but when I do deploy from one, deletes the functions that were created with the other one despite of having different names both.

### Expected behavior

I was expecting each repo to contribute with its functions to the Firebase project. I don't want to store all my functions in one repo as that is not contributing to reuse.
Somebody could argue that I can deploy my `common-repo` to a `common-project` in Firebase but I would like to keep the repo detached from what Firebase project is related to and decide that at the moment of deploy.

### Actual behavior

The firebase project only contains the last deployed functions

**Comment by mbleigh** [comment]
We're looking at ways to make this better, but in the meantime, you can use `firebase deploy --only functions:<fnName>,functions:<fnName2>` etc. to do targeted deploys in each of your directories without trashing the other.

**Comment by martosoler** [comment]
Let me see if I understand correctly.

What you are saying is that I should trigger the same deploy twice, each one from a different directory: `firebase deploy --only functions:commonFunction functions:appFunction`.

`appFunction` does not exists in `common-repo`, will this work?

**Comment by mbleigh** [comment]
If you have `fn1` in one directory, you'd do `firebase deploy --only functions:fn1` from that directory, and if you have `fn2` in another, you'd do `firebase deploy --only functions:fn2` there. By specifying `only` you will prevent unrecognized functions from being deleted.

**Comment by mattschwarz** [comment]
@mbleigh forgive the bump, but wonder if any other solution has come along for this? The moment we have another repo contributing to cloud functions we must now specify all function names in both repos during deploys? Has this gotten any “smarter”?

**Comment by mbleigh** [comment]
If you have multiple repos I would encourage using two "function groups", e.g.

```js
// repo 1 index.js
exports.repo1 = {
  func1: functions.https.onRequest(/* ... */)
};

// repo 2 index.js
exports.repo2 = {
  func1: functions.https.onRequest(/* ... */)
};
```

Then in repo1 you could deploy all the functions with `firebase deploy --only functions:repo1` and the same but with `repo2` in repo2. That keeps things pretty straightforward.

I am thinking some more on this though.

**Comment by mattschwarz** [comment]
@mbleigh that's a good short-term, thanks! Yes would be great to find a way not to worry about this. I basically have to setup a deploy script to make sure developers don't accidentally overwrite other functions during deploy :(

**Comment by remotevision** [comment]
one thing that hung me up was that if the functions are exposed as an api, then your `rewrites` in your `firebase.json` for hosting need to include all functions across all functions exposed as an api. This is obviously going to be error prone if duplicated. Is there a clean way to handle this - `git submodule` or a separate repo for hosting config?

**Comment by laurenzlong** [comment]
Hey @remotevision if you are separating your functions into two separate repositories. I would recommend keeping hosting config in a third repository, and then deploying that separately by running `firebase deploy --only hosting`

**Comment by remotevision** [comment]
thank you @laurenzlong. That is what I suspected and makes a lot of sense. This is part deployment and part microservices question, but assuming each function has it's own repo, does this become unmanageable if I have 50 or 60 functions using shared middleware?

**Comment by laurenzlong** [comment]
Hey @remotevision it depends on what you mean by shared middleware and what you mean by unmanageable. Why are they in individual repos? And does shared middleware mean shared code?

You won't have issues with 50 to 60 functions in terms of deployment if you deploy them individually. There are performance degradations if you deploy too many functions at the same time. But [quota for Cloud Functions](https://cloud.google.com/functions/quotas) is 1000 deployed functions per project so you'll definitely be fine from that perspective.

**Comment by joehan** [comment]
Many years later, this is finally well supported by functions codebases https://firebase.google.com/docs/functions/organize-functions#organize_functions_in_codebases
