### ISSUE TITLE
Starting emulators with `--inspect-functions` flag does not product desired result

### ISSUE THREAD

**Issue by brad426** [firebase/firebase-tools#4885]
### Environment info

**firebase-tools:** 11.4.0

**node:** v16.16.0

**Platform:** macOS 12.5 (Apple Silicon) 

### Test case

Create a fresh firebase project
```
firebase init
emulators:start --inspect-functions
```

### Steps to reproduce
```
firebase init
emulators:start --inspect-functions
```
Shows warning:
> To enable function inspection, please run "/usr/local/bin/firebase is:npm i node@/usr/local/bin/firebase --save-dev" in your functions directory

```
cd functions
/usr/local/bin/firebase is:npm i node@/usr/local/bin/firebase --save-dev
```

Output:
```
npm ERR! code ENOLOCAL
npm ERR! Could not install "../../../../../../usr/local/bin/firebase" as it is not a directory and is not a file with a name ending in .tgz, .tar.gz or .tar
```

[firebase-debug.log](https://github.com/firebase/firebase-tools/files/9352899/firebase-debug.log)

**Comment by eldadj** [comment]
Run `/usr/local/bin/firebase is:npm i node --save-dev`

**Comment by colerogers** [comment]
Hi @brad426 what version of node are you using?

**Comment by brad426** [comment]
> Hi @brad426 what version of node are you using?

16.6.0

**Comment by brad426** [comment]
after upgrading to firebase cli version `11.7.0`  I can now run `firebase emulators:start --inspect-functions` without seeing the warning:
```
To enable function inspection, please run "/usr/local/bin/firebase is:npm i node@/usr/local/bin/firebase --save-dev" in your functions directory
```

Everything seems to be working perfectly now

**Comment by Tianle-Leviathan** [comment]
I am running into the same issue and the debug mode is not working properly. No process is listening on 9229 when running emulator. 
I am running firebase emulator on ubuntu 20.04. Node version is v16.17.0

**Comment by YahavGB** [comment]
Same here,

```
❯ firebase --version
11.9.0
❯ node -v
v18.9.0
```

**Comment by ReniDelonzek** [comment]
O mesmo aqui
`firebase --version
11.16.0`

**Comment by ReniDelonzek** [comment]
In my case running `/usr/local/bin/firebase is:npm i node@16 --save-dev` solved the problem
