### ISSUE TITLE
Cannot create a 2nd gen function

### ISSUE THREAD

**Issue by steveoh** [firebase/firebase-tools#4920]
### [REQUIRED] Environment info

**firebase-tools:**

firebase --version
11.8.0

**Platform:**

macOS

### [REQUIRED] Test case

no test case required

### [REQUIRED] Steps to reproduce

firebase init
firebase deploy --only functions

### [REQUIRED] Expected behavior

I expect to be able to create a v2 function

### [REQUIRED] Actual behavior

v1 functions are always created

**Comment by bkendall** [comment]
There's not enough information here to debug anything. Please take a look at the [docs](https://firebase.google.com/docs/functions/beta) for the limitations on what can be done with v2 and the [getting started page](https://firebase.google.com/docs/functions/beta/get-started) to see how to use the v2 handlers from firebase-functions.
