### ISSUE TITLE
env variables are only available during application runtime

### ISSUE THREAD

**Issue by Wian-TMC** [firebase/firebase-tools#4921]
Why is this closed ?

You cannot deploy to `v2` of functions when using `functions.config()`, and that seems to be the only solution for accessing any deployment variables. This is a big issue

_Originally posted by @Wian-TMC in https://github.com/firebase/firebase-tools/issues/4239#issuecomment-1225858494_

**Comment by taeold** [comment]
You can read about our rationale here: https://github.com/firebase/firebase-functions/issues/1084

In short, we are close to shipping out a replacement for the Runtime Config. Thanks for your patience.
