### ISSUE TITLE
functions failed while using firebase emulators:start

### ISSUE THREAD

**Issue by networkpankaj** [firebase/firebase-tools#4923]
### [REQUIRED] Environment info

**firebase-tools:**

**Platform:**

### [REQUIRED] Actual behavior

functions: Failed to load function definition from source: FirebaseError: Failed to load function definition from source: Failed to generate manifest from function source: ReferenceError: reqire is not 
defined

**Comment by brad426** [comment]
Looks like you've spelled require incorrectly.
You have  "reqire", should be `require`

**Comment by bkendall** [comment]
@brad426 's comment seems very likely. There's also not enough information here to debug - the template is there for a reason, please follow it!
