### ISSUE TITLE
Getting "Somthing went wrong" when trying to login my CLI into Firebase

### ISSUE THREAD

**Issue by psygo** [firebase/firebase-tools#4936]
`npm i -g firebase-tools`

**firebase-tools:** 11.8.0

**Platform:** at least Windows and ArchLinux

### [REQUIRED] Test case

> I had actually originally asked [this question on StackOverflow](https://stackoverflow.com/q/73560524/4756173), but I think it is even more appropriate to ask it here, I guess. And I just found out someone else has had the [same problem](https://stackoverflow.com/q/73546284/4756173) yesterday.

I'm coming back into using Firebase after about 2 years, and now I'm having trouble trying to login my CLI into Firebase (yes, I have installed `npm i -g firebase-tools`). I've tried 3 different commands for it, all of them result in one of the images below:

- `firebase login`
- `firebase login:ci`
- `firebase login:ci --no-localhost`

Here is the result, after I allow Firebase CLI to integrate with my account:

![image](https://user-images.githubusercontent.com/11823725/187757290-01bb2483-8ab3-4f1c-a12e-54276e6fc78c.png)
![image](https://user-images.githubusercontent.com/11823725/187757337-0aecf71f-1f64-4add-a4b3-e18950e08f11.png)

### [REQUIRED] Steps to reproduce

> Difficult to reproduce, since it might be only related to my account, I don't know. Anyway, see the previous subsection.

### [REQUIRED] Expected behavior

To login.

### [REQUIRED] Actual behavior

Error screen with the most generic error message ever.

**Comment by psygo** [comment]
And here is what appears on my Inspector's Console, 2 improvement issues:

![image](https://user-images.githubusercontent.com/11823725/187780585-d6299326-64e9-4159-81dd-cd0dbd3d13c5.png)

**Comment by psygo** [comment]
I don't know why or how, but **opening the link through Chrome** actually worked. I was opening it through Brave, thinking that, since both are based on the Chrome engine, nothing would change.

**Comment by bkendall** [comment]
Sounds like something odd in the google login flow, which we don't really have much control over. If you're still having issues though, I'd recommend auth-ing with a service account in GOOGLE_APPLICATION_CREDENTIALS - it would at least skip this process.

**Comment by psygo** [comment]
At least maybe forward the problem to someone who does have control over this feature?

**Comment by tomholford** [comment]
> I don't know why or how, but **opening the link through Chrome** actually worked. I was opening it through Brave, thinking that, since both are based on the Chrome engine, nothing would change.

+1, experienced the same issue. Installing Chrome and using the auth link there worked smoothly.
