### ISSUE TITLE
Auth Emulator blocking functions are giving error 'auth/claims-too-large'

### ISSUE THREAD

**Issue by DibyodyutiMondal** [firebase/firebase-tools#4946]
1. When the blocking function returns a response, the response is sent to 
`processBlockingFunctionResponse` ([here](https://github.com/firebase/firebase-tools/blob/36c0ba153e44c6ab708a833fa04ddaeb70bdc4b1/src/emulator/auth/operations.ts#L3061))
2. From inside the above function, `customClaims` are extracted as-is and sent to another function ([here](https://github.com/firebase/firebase-tools/blob/36c0ba153e44c6ab708a833fa04ddaeb70bdc4b1/src/emulator/auth/operations.ts#L3091))
3. This other function `validateSerializedCustomClaims` specifies in the signature ([here](https://github.com/firebase/firebase-tools/blob/36c0ba153e44c6ab708a833fa04ddaeb70bdc4b1/src/emulator/auth/operations.ts#L2438)) that claims must be of type string.

4. However, the claims object in point 2 was never stringified. It was a POJO.
As a result, this line :` assert(claims.length <= CUSTOM_ATTRIBUTES_MAX_LENGTH, "CLAIMS_TOO_LARGE");` throws an error.
`claims.length` is `undefined`, therefore the condition is false. (as illustrated below)
Fun thought: What would happen if we set a custom claim called `length`?

![image](https://user-images.githubusercontent.com/50345677/188168646-f30ea8f2-f982-484e-a8fb-5828b37800ad.png)

5. Since this assertion fails, the user is never created, customClaims are never set, and the flow errors out.

Suggested Remedy: 
1. Serialize the claims before sending it for validation, or
2. As part of validation, convert it to string if it is not a string

### [REQUIRED] Environment info

**firebase-tools:** 11.8.0
**firebase-functions:** 3.23.0

**Platform:**

**Comment by DibyodyutiMondal** [comment]
#### Problem

Ok, so the stuff I said above was a bit off the mark. Here is the result of some further investigation

1. Here, the value of `response.userRecord.customClaims` is a plain object, not a string. (Please keep it in mind - it'll be important later)
https://github.com/firebase/firebase-tools/blob/36c0ba153e44c6ab708a833fa04ddaeb70bdc4b1/src/emulator/auth/operations.ts#L3072


2. Then, we send `userRecord.customClaims` to `validateSerializedCustomClaims` for validation.
This fails, because the validation logic expects a string, which it asserts must have length less than the max limit (1000):
https://github.com/firebase/firebase-tools/blob/36c0ba153e44c6ab708a833fa04ddaeb70bdc4b1/src/emulator/auth/operations.ts#L2438-L2439

3. Even if validation succeeded, we set `updates.customAttributes` to `userRecord.customClaims` (which is an object)
https://github.com/firebase/firebase-tools/blob/36c0ba153e44c6ab708a833fa04ddaeb70bdc4b1/src/emulator/auth/operations.ts#L3092
This fails further down the line, because `updates.customAttributes` must be string, because it is `JSON.parse`d in `generateJwt()`:
https://github.com/firebase/firebase-tools/blob/36c0ba153e44c6ab708a833fa04ddaeb70bdc4b1/src/emulator/auth/operations.ts#L2363


#### Proposed Solution
https://github.com/firebase/firebase-tools/blob/36c0ba153e44c6ab708a833fa04ddaeb70bdc4b1/src/emulator/auth/operations.ts#L3090-L3093
Replace with:
```
case "customClaims":
          const stringifiedClaims = JSON.stringify(userRecord.customClaims!);
          validateSerializedCustomClaims(stringifiedClaims);
          updates.customAttributes = stringifiedClaims;
          break;
```


PS: Also, please consider looking into sessionClaims as well - I think it may have similar issues. I did not test it as I don't use it for my current project. I'd have loved to look into it, but this one took me longer than expected, and I must catch up on my work.

PPS: My fingers are crossed that this problem only happens in the emulator, not in production. I'll tr it out and update the thread.

**Comment by lisajian** [comment]
Thanks @DibyodyutiMondal for filing the issue. Would you mind including missing the information from the issue template (e.g. test case, steps to reproduce, etc) so we can reproduce any errors you're encountering?

**Comment by DibyodyutiMondal** [comment]
Unfortunately, I am unable to provide a full repro, but I can gladly tell the steps. These steps will reproduce the error in the latest firebase sdk version.

Steps to reproduce:
1. Create a blocking function that adds a persisted custom claim on user creation. (for example, `{ roles: [] }` )
2. Start the auth and function emulator
3. Create a web page with sign in (I suppose google signin is easiest to implement, since all you need is a button and a page)
4. Attempt to sign in with a new user
5. You should get  an http 400 error with the following body
  ```
{
  "error": {
    "code": 400,
    "message": "CLAIMS_TOO_LARGE",
    "errors": [
      {
        "message": "CLAIMS_TOO_LARGE",
        "reason": "invalid",
        "domain": "global"
      }
    ]
  }
}
  ```

**Comment by Oleksandr-Guidde** [comment]
@lisajian I also see the same error. What information needed to fix this? It's easy to reproduce: add any customClaims in `beforeCreate` function and you'll see an error on a client when trying to create a new user (for example via google popup sign in).

**Comment by lisajian** [comment]
Hey @Oleksandr-Guidde, a PR went out that updated the claim type to address the issue. The change went out in version 11.12.0. Can you try updating your firebase-tools version and let me know if you're still seeing the error? Thanks

**Comment by DibyodyutiMondal** [comment]
I am not seeing an error in customClaims. I have not checked for sessionClaims.
