### ISSUE TITLE
Requested files stored in the firebase storage emulator as gzip are always fetched uncompressed

### ISSUE THREAD

**Issue by braadworst** [firebase/firebase-tools#4957]
### [REQUIRED] Environment info

**firebase-tools:** 11.8.0

**Platform:** MacOS (11.5.2), Chrome (104.0.5112.101)

### [REQUIRED] Test case

Doesn't apply

### [REQUIRED] Steps to reproduce

- Save a compressed file to the storage emulator from a cloud function
- Request the file via fetch from the client
- Observe the returned `content-encoding`, this is set to `identity`

### [REQUIRED] Expected behavior

Files should be fetched as gzipped files instead of uncompressed files, the `content-encoding` header on the response should be `gzip`

### [REQUIRED] Actual behavior

When I save a file via my cloud function as a gzipped compressed version it saves it correctly as a compressed file in the storage emulator. But when I then request my file in the frontend via the native fetch API it always respond with the uncompressed version. The response header `content-encoding` is always set to `identity`. According to the docs [here](https://cloud.google.com/storage/docs/transcoding) when the file is stored compressed (that is the case) and the request has the `accept-encoding` set to `gzip` (this is the case, this is controlled by the browser and actually set to `gzip, deflate, br`) it should return compressed.

I've uploaded a compressed file to the actual production bucket and fetched it, and in that case it was working as expected.

Final note, as my file is created in a cloud function and I need the getDownloadUrl that you normally receive when uploading a file from the client I had to use a workaround as described [here](https://stackoverflow.com/questions/42956250/get-download-url-from-file-uploaded-with-cloud-functions-for-firebase) and addressed [here](https://github.com/firebase/firebase-admin-node/issues/1352). I am building a custom url by setting the `firebaseStorageDownloadTokens `. I don't expect this to influence the situation by I've added it for full disclosure

Thank you

**Comment by tonyjhuang** [comment]
Hi @braadworst can you provide a repro?

**Comment by tonyjhuang** [comment]
I've been able to reproduce this and am working on a fix now.

**Comment by bryantwilliam** [comment]
I know this is 3 years old, but I left a relevant comment about this here: https://github.com/firebase/firebase-tools/pull/5185#issuecomment-2906855983
