### ISSUE TITLE
Node 16 breaks workspaces 

### ISSUE THREAD

**Issue by kristfal** [firebase/firebase-tools#4962]
### Related issues

This is similar to https://github.com/firebase/firebase-functions/issues/1050, but it probably belongs here - not there.

### [REQUIRED] Version info

**node:** v16.13.2
**firebase-functions:** 3.11.0
**firebase-tools:** 11.8.0
**firebase-admin:** 9.2.0

### [REQUIRED] Test case

Add the following object to package.json

```json
  "workspaces": {
    "nohoist": [
      "example-package-name"
    ]
  },
  "engines": {
    "node": "16"
  },
```

### [REQUIRED] Steps to reproduce

Run `firebase deploy`

### [REQUIRED] Expected behavior

Successful deployment

### [REQUIRED] Actual behavior

Failed deployment

```json
{
  "@type": "type.googleapis.com/google.cloud.audit.AuditLog",
  "status": {
    "code": 3,
    "message": "Build failed: npm ERR! code EWORKSPACESCONFIG\nnpm ERR! workspaces config expects an Array\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /www-data-home/.npm/_logs/2022-03-01T15_39_30_803Z-debug.log; Error ID: b0ba1f57"
  },
  "authenticationInfo": {
    "principalEmail": "REDACTED"
  },
  "serviceName": "cloudfunctions.googleapis.com",
  "methodName": "google.cloud.functions.v1.CloudFunctionsService.UpdateFunction",
  "resourceName": "REDACTED"
}
```

### Were you able to successfully deploy your functions?

Downgrading to node 14 or removing workspaces entry in package.json solves the issue.

### Misc

The schema validation of package.json used to not allow objects. This has been resolved in a later version of schemastore.

See comment: https://github.com/microsoft/vscode/issues/77912#issuecomment-515391585

**Comment by bkendall** [comment]
Can you file a [feature request for this](https://firebase.google.com/support/troubleshooter/report/features)? This looks like it's going to have to be something that's dealt with in the underlying infrastructure which is a different team. Unfortunately, not something that the CLI itself is going to solve.
