### ISSUE TITLE
Version 11.8.1 does not release functions anymore

### ISSUE THREAD

**Issue by danmindru** [firebase/firebase-tools#4966]
### [REQUIRED] Environment info

**firebase-tools:** [11.8.1](https://www.npmjs.com/package/firebase-tools/v/11.8.1)

**Platform:** Ubuntu 20.04.5 (Azure Devops CI)

### [REQUIRED] Test case

Deploy any v2 function using cli tools, i.e.:

```js
const { onRequest } = require('firebase-functions/v2/https');

exports.fnname = onRequest( {
    region: [
      'europe-central2',
      'europe-west3',
      'europe-west4',
      'us-west2',
      'us-central1'
    ],
    memory: '4GiB',
    minInstances: 0,
    maxInstances: 3,
    concurrency: 100,
    cpu: 4
  }, (req, res) => {
    res.send("Hello");
});
```

The function runtime config might affect the result, but not sure which part is relevant so including it all.

### [REQUIRED] Steps to reproduce

Run:
```bash
firebase deploy --only functions --project <project-name>
```

### [REQUIRED] Expected behavior

Expected functions to be deployed, getting output such as:

```
i  functions: packaged /home/vsts/work/1/s/functions (22.86 MB) for uploading 
✔  functions: functions folder uploaded successfully 
i  functions: updating Node.js 14 function convertpdf(europe-central2)... 
i  functions: updating Node.js 14 function ssrapp(europe-central2)... 
i  functions: updating Node.js 14 function ssrapp(europe-west3)... 
i  functions: updating Node.js 14 function ssrapp(europe-west4)... 
i  functions: updating Node.js 14 function ssrapp(us-west2)... 
i  functions: updating Node.js 14 function ssrapp(us-central1)...

✔  Deploy complete! 
```

### [REQUIRED] Actual behavior

After running the command, the following output is generated and no functions are deployed

```
[2022-09-09T13:33:37.836Z] Building nodejs source
i  functions: Loaded environment variables from .env. 
[2022-09-09T13:33:37.839Z] Could not find functions.yaml. Must use http discovery
[2022-09-09T13:33:37.980Z] Serving at port 9005

[2022-09-09T13:33:38.426Z] Got response from /__/functions.yaml {"endpoints":"fnname":{"platform":"gcfv2","concurrency":100,"minInstances":0,"maxInstances":3,"cpu":4,"availableMemoryMb":4096,"region":["europe-central2","europe-west3","europe-west4","us-west2","us-central1"],"labels":{},"httpsTrigger":{},"entryPoint":"fnname"}},"specVersion":"v1alpha1","requiredAPIs":[]}

i  functions: preparing functions directory for uploading... 
```
(task exits with no further output but also without an error)

This worked fine yesterday in our CI, but stopped working today (we used `npm i -g firebase-tools` as part of the CI config, so we got automatically upgraded to v11.8.1). 

Changing to `npm i -g firebase-tools@v11.8.0` got it back working.

**Comment by danmindru** [comment]
Just a note - this is similar to #4952, however the bug there suggests that v11.8.0 has issues. 
Version v11.8.0 worked fine, the issue we've having is with v11.8.1

**Comment by ohois** [comment]
Same issue here. I have v1 functions and some can be published and some cannot. Maybe it fails when the payload is too large?

The failing function has some assets and is > 40MB (would be silly if that is the case but who knows)

**Comment by evelant** [comment]
Yeah 11.8.1 is completely broken when deploying functions it seems. I've got the same behavior, it just silently exits after `preparing functions directory for uploading... `. There's no output after that even in debug mode.

**Comment by TheIronDev** [comment]
@evelant @ohois @danmindru 

Thank you for calling attention to this!

We have identified the root cause and will be patching in a release Monday morning. 

In the mean time, installing `firebase-tools@11.8.0` will unblock you.

Sorry for the breakage.  🐢
