### ISSUE TITLE
Having a leading "/" in the path will throw an error  

### ISSUE THREAD

**Issue by GregIngelmo** [firebase/firebase-tools#497]
### Version info
3.13.1

### Steps to reproduce
1. Create a document inside the collection `/users/` with an id `ViDe80R7HFsCjYq7Dk8k`
2. Run cli command:
```sh
firebase firestore:delete -r "/users/ViDe80R7HFsCjYq7Dk8k"
```

### Expected behavior

Should delete the document @ the path.

### Actual behavior

Throws error
```sh 
Error: Path must not have any empty segments.
```

### Comment
The code that detects empty 'segments' doesn't account for leading or trailing slashes.

https://github.com/firebase/firebase-tools/blob/4535410654cefaf53aec9dbfebec2cdb58045404/lib/firestore/delete.js#L49-L61

**Comment by samtstern** [comment]
@GregIngelmo thanks, this has been fixed and will be included in the next release.
