### ISSUE TITLE
Firebase tools throw an error, and it can't upgraded

### ISSUE THREAD

**Issue by ahmedhnewa** [firebase/firebase-tools#4973]
### [REQUIRED] Environment info

I use the latest version

This tool has encountered an error. Please file a bug on Github (https://github.com/firebase/firebase-tools/) and include firepit-log.txt

**firebase-tools:**

**Platform:**
macOS

### [REQUIRED] Steps to reproduce

I don't know, All I get is an error
 message while using the Firebase command and It tells me to report the bug to GitHub
with this file
[firepit-log.txt](https://github.com/firebase/firebase-tools/files/9549502/firepit-log.txt)

### [REQUIRED] Expected behavior

The firebase command should work as it is

This tool has encountered an error. Please file a bug on Github (https://github.com/firebase/firebase-tools/) and include firepit-log.txt

### [REQUIRED] Actual behavior

This tool has encountered an error. Please file a bug on Github (https://github.com/firebase/firebase-tools/) and include firepit-log.txt

**Comment by bkendall** [comment]
Interesting. The relevant error is likely `EACCES: permission denied, unlink '/Users/ahmedhnewa/.cache/firebase/runtime/shell'`

Could you try deleting `/Users/ahmedhnewa/.cache/firebase` and reinstalling firebase-tools? If you're still having issues then, let us know how you're installing it as well.

**Comment by ahmedhnewa** [comment]
> Interesting. The relevant error is likely `EACCES: permission denied, unlink '/Users/ahmedhnewa/.cache/firebase/runtime/shell'`
> 
> Could you try deleting `/Users/ahmedhnewa/.cache/firebase` and reinstalling firebase-tools? If you're still having issues then, let us know how you're installing it as well.

Thank you, the problem has been resolved
