### ISSUE TITLE
Updating global firebase-tools throws an error during install via NPM

### ISSUE THREAD

**Issue by DisruptLive** [firebase/firebase-tools#4978]
### [REQUIRED] Environment info

`firebase --version`
**firebase-tools: 11.9.0**
_attempted upgrade from 11.8.1 to 11.9.0 completed with error thrown during the process (noted below)_

**Platform: MacOS 12.4**

### [REQUIRED] Test case

In my _test_ case, i have/need an older version of NPM installed globally, thus _could the cause of the issue i am experiencing be the version of NPM i currently have installed?_
**NPM Version: 6.14.17**

### [REQUIRED] Steps to reproduce

`sudo npm install -g firebase-tools`

### [REQUIRED] Expected behavior

Successful install of latest version of `firebase-tools` 

### [REQUIRED] Actual behavior

`firebase-tools` appears to have updated to latest version despite the following error being thrown during the installation process:

```
ERROR: Failed to set up Chromium r869685! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
[Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/firebase-tools/node_modules/puppeteer/.local-chromium'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/usr/local/lib/node_modules/firebase-tools/node_modules/puppeteer/.local-chromium'
}
```

**Comment by bkendall** [comment]
This should be addressed in that we don't include devdeps anywhere in our published package, as of `v11.11.0`. Give it a shot and see if it still happens!

Fixed by #5023
