### ISSUE TITLE
"1" printed in the console log in non-verbose mode during firebase deploy

### ISSUE THREAD

**Issue by hramakrishnappa** [firebase/firebase-tools#499]
Hi folks,

Version:
3.13.1

Problem: A "1" printed in the console log in non-verbose mode during `firebase deploy` command execution.

Repro steps: I created a new firebase project, ran `firebase init functions`, wrote a sample function from a repo and ran `firebase deploy`. The first printed line in the console is a "1". Maybe it is leftover from a local debug print during development!

> 
> ~/w/L/T/functions> firebase deploy
> 1
> 
> === Deploying to 'qa-1'...
> 
> i  deploying functions
> i  functions: ensuring necessary APIs are enabled...
> i  runtimeconfig: ensuring necessary APIs are enabled...
> ✔  runtimeconfig: all necessary APIs are enabled
> ✔  functions: all necessary APIs are enabled
> i  functions: preparing functions directory for uploading...
> i  functions: packaged functions (15.31 KB) for uploading
> ✔  functions: functions folder uploaded successfully
> i  starting release process (may take several minutes)...
> i  functions: creating function sendOnNewIssue...
> ✔  functions[sendOnNewIssue]: Successful create operation.
> ✔  functions: all functions deployed successfully!
> 
> ✔  Deploy complete!
>

**Comment by jeffreya421** [comment]
Wyf

**Comment by mbleigh** [comment]
Is this still happening for anyone?
