### ISSUE TITLE
Cannot serve functions ->  TypeError: Cannot read properties of undefined (reading 'INTERNAL')

### ISSUE THREAD

**Issue by qty0** [firebase/firebase-tools#4991]
### [REQUIRED] Environment info

**firebase-tools:** 11.9.0

**Platform:** MacOS Monterey 12.5.1 (21G83)

### [REQUIRED] Test case
Please see below

### [REQUIRED] Steps to reproduce
1. `firebase init functions` -> `typescript`
2. Add to `src/index.ts` -> 
```import * as functions from "firebase-functions";
import { initializeApp } from "firebase-admin";
// Start writing Firebase Functions
// https://firebase.google.com/docs/functions/typescript

const db = initializeApp().firestore()


export const healthCheckDB = functions.https.onRequest(async (req, res) => {
    const config = (await db.collection('config').doc('config').get()).data()
    res.send(config)
});
```
3. `npm run build && firebase emulators:start --only functions`

### [REQUIRED] Expected behavior
firestore is accessible through the firebase-admin package.

### [REQUIRED] Actual behavior
```⬢  functions: Failed to load function definition from source: FirebaseError: Failed to load function definition from source: Failed to generate manifest from function source: TypeError: Cannot read properties of undefined (reading 'INTERNAL')```

[firebase-debug.log](https://github.com/firebase/firebase-tools/files/9592039/firebase-debug.log)
[ui-debug.log](https://github.com/firebase/firebase-tools/files/9592040/ui-debug.log)

**Comment by colerogers** [comment]
Hi @qty0 that error usually occurs when your ts/js file has errors when we discover your functions. If you're using the latest version of the admin sdk, then you'll need to change your init code to something like this
```
import { initializeApp } from "firebase-admin/app";
import { getFirestore } from "firebase-admin/firestore";

initializeApp();
const db = getFirestore();
```

Here's the reference docs for the admin sdk's firestore submodule - https://firebase.google.com/docs/reference/admin/node/firebase-admin.firestore

**Comment by qty0** [comment]
i could not get `firebase-admin/firestore | getFirestore` working, and after some trial and error, came up with this. I think it works as intended, I'm just a dumbass :)

```

import * as functions from "firebase-functions";
import * as admin from "firebase-admin";

admin.initializeApp()

export const fn = functions.region('europe-west2')
export const db = admin.firestore()

```
