### ISSUE TITLE
Wrong Header response when testing an invalid URL

### ISSUE THREAD

**Issue by mrondon** [firebase/firebase-tools#4999]
### [REQUIRED] Environment info

**firebase-tools:** 11.9.0

**Platform:** Ubuntu 22.04

### [REQUIRED] Test case

I'm getting Insecure Content Security Policy (CSP)/X-Frame-Options found in URI https://fir-test-8d3c5.web.app/%2e%2e,
I know this is an invalid URL, but maybe it should be handled by the default redirect page, what I'm noticing is that it's skipping my firebase.json configurations

### [REQUIRED] Steps to reproduce

1. create and host a project with this setting in the firebase.json file:
```
      "headers": [
        {
          "source": "**",
          "headers": [
            {
              "key": "X-Frame-Options",
              "value": "DENY"
            }
          ]
        },
        ...
        ]
```
or simply use my project that it's already live

2. from the terminal: `HEAD https://fir-test-8d3c5.web.app/%2e%2e`  (or yours `http://your-url/%2e%2e`)

### [REQUIRED] Expected behavior
The response should look like this: (notice the X-Frame-Options: DENY Header)
```
200 OK
Cache-Control: max-age=3600
Connection: close
Date: Wed, 21 Sep 2022 16:30:47 GMT
Accept-Ranges: bytes
ETag: "d16fdbc630912933c7906c848c00b3827f9854e8996916438a9f8d803fd8ca7f"
Vary: x-fh-requested-host, accept-encoding
Content-Length: 6202
Content-Type: text/html; charset=utf-8
Last-Modified: Tue, 20 Sep 2022 15:42:40 GMT
Alt-Svc: h3=":443";ma=86400,h3-29=":443";ma=86400,h3-27=":443";ma=86400
Client-Date: Wed, 21 Sep 2022 16:30:47 GMT
Client-Peer: 199.36.158.100:443
Client-Response-Num: 1
Client-SSL-Cert-Issuer: /C=US/O=Google Trust Services LLC/CN=GTS CA 1D4
Client-SSL-Cert-Subject: /CN=web.app
Client-SSL-Cipher: TLS_AES_256_GCM_SHA384
Client-SSL-Socket-Class: IO::Socket::SSL
Client-SSL-Version: TLSv1_3
Strict-Transport-Security: max-age=31556926; includeSubDomains; preload
X-Cache: MISS
X-Cache-Hits: 0
X-Frame-Options: DENY
X-Served-By: cache-scl2220035-SCL
X-Timer: S1663777847.498437,VS0,VE413
```

### [REQUIRED] Actual behavior

This is the actual response, notice it's skipping the default redirect rule
```
404 Not Found
Cache-Control: max-age=0
Connection: close
Date: Wed, 21 Sep 2022 16:23:32 GMT
Vary: x-fh-requested-host, accept-encoding
Content-Type: text/html; charset=utf-8
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Client-Date: Wed, 21 Sep 2022 16:23:33 GMT
Client-Peer: 172.217.192.95:443
Client-Response-Num: 1
Client-SSL-Cert-Issuer: /C=US/O=Google Trust Services LLC/CN=GTS CA 1C3
Client-SSL-Cert-Subject: /CN=upload.video.google.com
Client-SSL-Cipher: TLS_AES_256_GCM_SHA384
Client-SSL-Socket-Class: IO::Socket::SSL
Client-SSL-Version: TLSv1_3
Client-Transfer-Encoding: chunked
Strict-Transport-Security: max-age=31556926
Surrogate-Control: max-age=31556926
Surrogate-Key: __fb:error __fb:discard:disabled __fb:fh:origin_v3 __fb:fh:origin-server:prod
X-Borg-Cell: na
X-Borg-Continent: N_AMERICA
X-Content-Type-Options: nil
X-Frame-Options: nil
X-Xss-Protection: nil
```

**Comment by bkendall** [comment]
I've thought about this a bit. I think unspecified behavior (dealing with an invalid URL in this case) isn't something we want to work to define. If there's a specific case (e.g. "the 404 page isn't getting my rules applied") that's something we can address, but different servers handle the invalid URL differently, which makes it quite difficult to solve.

Thanks for flagging, but this is something we're just going to have to close for now.

**Comment by mrondon** [comment]
@bkendall is there something I can do to catch this invalid URL and prevent this from happening on the application side? I tried several patterns in the `source` but none of them seemed to work.
