### ISSUE TITLE
Debug mode in 11.10.0 broke for me (re #4886)

### ISSUE THREAD

**Issue by spicemix** [firebase/firebase-tools#5008]
### [REQUIRED] Environment info

**firebase-tools:**
11.10.0

**Platform:**

MacOS latest intel

### [REQUIRED] Test case

That may be more work for me than fixing this is for you, this release is only a few hours old, giving you early heads up.

### [REQUIRED] Steps to reproduce

I use `firebase emulators:start --inspect-functions 9229` rather than just `firebase emulators:start` to enter debug mode. This works perfectly for my typescript functions on 11.9.0 but the functions just hang on 11.10.0.

### [REQUIRED] Expected behavior

However, if I do just use `firebase emulators:start` in 11.10.0, everything works fine. I just can't debug this way.

### [REQUIRED] Actual behavior

Well, I think it's a bit of hassle to run logs and clean them up for public consumption, but I think you'll appreciate the feedback that the fix in #4886 broke for me in practice in debug mode only (which you mention is different now). Being able to debug is handy so I will roll back to 11.9.0 until you have this fixed thanks!

**Comment by spicemix** [comment]
✅ Fixed for me in 11.11.0 thank you so very much

**Comment by spicemix** [comment]
Ooooops my global update workflow `npm-check -ug` that had worked for years just broke somehow on me in the most sly way...it reported installation, with no error, but in fact didn't update my global deps. So I had tested under 11.9.0 instead of 11.11.0, without knowing. The problem still exists for me in 11.12.0. I never actually tested 11.11.0. So I have to reopen this thank you.

**Comment by tomas-carv-com** [comment]
I have similar issue, every time I run emulators with `--inspect-functions` I cant connect to them or they dont function correctly. Triggers does not work etc.

**Comment by tomas-carv-com** [comment]
And I see these 2 PRs which are affecting --inspect-functions

https://github.com/firebase/firebase-tools/commit/454be140a47502a2aad128d8e8053e278c295213
https://github.com/firebase/firebase-tools/commit/b1099a2c3b0a104124eda5d8bf4b48e3aac38c37

I mean now debugging is completely broken. I cant use app if debugging is on

**Comment by taeold** [comment]
We think we have a fix and are working on a patch.

If anyone has time to help - would love to have folks test out the dl-fn-emu-inspect-bug branch which contains our proposed fix on their workflow.

Steps for running a local version of the Firebase CLI is available at https://github.com/firebase/firebase-tools/blob/master/CONTRIBUTING.md#getting-started.
