### ISSUE TITLE
Error running deploy command in 11.10.0 - "Error: Cannot find module 'is-npm'"

### ISSUE THREAD

**Issue by stewart42** [firebase/firebase-tools#5010]
### Environment info

**firebase-tools:**

```
➜ npx firebase-tools --version
Downloading Chromium r869685 - 112.4 Mb [====================] 100% 0.0s 
11.10.0
Cannot find module 'is-npm'
Require stack:
- /Users/stewart/.npm/_npx/45995/lib/node_modules/firebase-tools/node_modules/update-notifier/index.js
- /Users/stewart/.npm/_npx/45995/lib/node_modules/firebase-tools/lib/bin/firebase.js
```

**Platform:**

macOS (m1)

### Test case

Using version 11.10 to do a `hosting:channel:deploy` does succeed in deploying, however it fails to exit successfully as a error is thrown `Cannot find module 'is-npm'`

### Steps to reproduce

run `npx firebase-tools hosting:channel:deploy pr414-blah --only special-deploy --expires 14d --project test-project  --debug`

### Expected behavior

The deploy succeeds and exits successfully with no errors.

### Actual behavior

```
❯ npx firebase-tools hosting:channel:deploy pr414-blah --only special-deploy --expires 14d --project test-project  --debug
Downloading Chromium r869685 - 112.4 Mb [====================] 100% 0.0s 
[2022-09-23T08:52:38.718Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2022-09-23T08:52:38.719Z] > authorizing via signed-in user (***@***.com)
[2022-09-23T08:52:38.719Z] [iam] checking project test-project for permissions ["firebase.projects.get","firebasehosting.sites.update"]
[2022-09-23T08:52:38.721Z] > refreshing access token with scopes: []
...
✔  hosting:channel: Channel URL (***): https://***.web.app [expires 2022-10-07 10:52:45] 
[2022-09-23T08:53:10.615Z] Error: Cannot find module 'is-npm'
Require stack:
- /Users/stewart/.npm/_npx/46162/lib/node_modules/firebase-tools/node_modules/update-notifier/index.js
- /Users/stewart/.npm/_npx/46162/lib/node_modules/firebase-tools/lib/bin/firebase.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at lazy (/Users/stewart/.npm/_npx/46162/lib/node_modules/firebase-tools/node_modules/import-lazy/index.js:2:51)
    at /Users/stewart/.npm/_npx/46162/lib/node_modules/firebase-tools/node_modules/import-lazy/index.js:10:11
    at UpdateNotifier.notify (/Users/stewart/.npm/_npx/46162/lib/node_modules/firebase-tools/node_modules/update-notifier/index.js:117:59)
    at process.<anonymous> (/Users/stewart/.npm/_npx/46162/lib/node_modules/firebase-tools/lib/bin/firebase.js:108:20)
    at process.emit (events.js:412:35)
    at process.exit (internal/process/per_thread.js:179:15)
    at /Users/stewart/.npm/_npx/46162/lib/node_modules/firebase-tools/lib/command.js:105:25
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

Error: An unexpected error has occurred.

```

Note that even  `--version` triggers the error (see at the top of this issue)

**Comment by emrahyumuk** [comment]
+1

**Comment by matvi3nko** [comment]
I can confirm. We also faced this issue even with no code changes in our projects. Currently we cannot deploy them.

**Comment by aliak00** [comment]
Also confirmed - We were on version 10.7.0 and it's happening.

**Comment by ratrock** [comment]
This is happening to us, too, using `FirebaseExtended/action-hosting-deploy@v0` Github action. We deployed successfully yesterday, but not today.

**Comment by jmarbutt** [comment]
This is happening to us also.

**Comment by bkendall** [comment]
That is... very odd. I see it in `npm ls`, so it _should_ be there but obviously...

Can one of y'all who can replicate it locally tell me what version of node and npm you are using?

**Comment by DerekLinHF** [comment]
this is also happening to us as well

**Comment by bkendall** [comment]
Ah, I'm getting more of the sense that it's GH action specific. Let me see if I can figure out what's going on there.

**Comment by yuleidyvdres** [comment]
Same here

**Comment by dayoherrera** [comment]
Same here

**Comment by JavierB7** [comment]
It's happening to us also.

**Comment by odinho** [comment]
I suggest stopping with all the "me too"'s. It's likely affecting a huge number of projects. Put a thumbs-up emoji on the top post.

If you're using Firebase hosting and **not** getting this, a comment might make sense. It sounds like this currently affects everyone using this.

**Comment by amithvns** [comment]
We are using Firebase hosting for different repo's github actions and some are working and some are failing. 
At a quick glance looks like it is failing for actions where its set use nodejs version 14.x and the actions are successful where we are not setting to use nodejs 14.x

**Comment by theonetheycallneo** [comment]
Yes we also get an error going 1 version back as well, `yarn add -D firebase-tools@11.9.0`


```
error /Users/neo/Projects/vatom-inc/wallet/node_modules/jsdoc/node_modules/underscore: Command failed.
Exit code: 127
Command: patch-package
Arguments:
```

**Comment by aliak00** [comment]
Confirmed @amithvns's at-a-glance! Changed my github actions to use node 16 and it's working.

<img width="1243" alt="image" src="https://user-images.githubusercontent.com/2638284/192094754-9548341d-736f-4293-8274-1d4783145e77.png">

**Comment by jmarbutt** [comment]
Our (@amithvns also ) app has some older dependencies that currently don't work with node `v16.x` so we solved this by swapping the version before our build and then swapping back to 16x. 

Here are our build steps 

```yaml
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: node -v && npm ci && npm run build
      - name: Setup node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
```

**Comment by jmarbutt** [comment]
I guess my real question is why did this really break? Because if you are specifying a version like `FirebaseExtended/action-hosting-deploy@v0`, shouldn't it not have breaking changes unless we bump the version?

**Comment by matvi3nko** [comment]
We also use ```FirebaseExtended/action-hosting-deploy@v0``` and have this error Error: Cannot find module 'is-npm’ even npm I -D is-npm doesn’t help. Thanks

**Comment by theonetheycallneo** [comment]
What we did for now is switch to rolling back the version:
```
yarn global add patch-package firebase-tools@11.9.0
```
then remove this action and do it manually:
```
echo $(firebase hosting:channel:deploy {FIREBASE_PROJECT_ID} --expires 7d --debug --json)
            read appUrl storybookUrl < <(echo $(firebase hosting:channel:deploy {FIREBASE_PROJECT_ID} --expires 7d --debug --json | jq -r '.result.app.url, .result.storybook.url'))

            echo $appUrl 
            echo $storybookUrl

            pr_response=$(curl --location --request GET "https://api.github.com/repos/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/pulls?head=$CIRCLE_PROJECT_USERNAME:$CIRCLE_BRANCH&state=open" \
            -u $PR_BOT_USER:$PR_BOT_TOKEN)

            if [ $(echo $pr_response | jq length) -eq 0 ]; then
              echo "No PR found to update"
            else
              pr_comment_url=$(echo $pr_response | jq -r ".[]._links.comments.href")
            fi

            body=":rocket: Visit the preview URL for this PR (updated for commit $CIRCLE_SHA1): \n- $appUrl\n- $storybookUrl"

            curl --location --request POST "$pr_comment_url" \
            -u $PR_BOT_USER:$PR_BOT_TOKEN \
            --header 'Content-Type: application/json' \
            --data-raw "{ \"body\": \"$body\" }"
```

One Suggestion:
- We should have an optional "version" parameter to specify the firebase-tools@{version} for this action.

**Comment by bkendall** [comment]
For folks watching: we're going to release this tomorrow morning

**Comment by theonetheycallneo** [comment]
Schweet ness!AWOn Sep 26, 2022, at 8:13 PM, Bryan Kendall ***@***.***> wrote:﻿
For folks watching: we're going to release this tomorrow morning
