### ISSUE TITLE
Firebase React App getDownloadURL unknown error 400

### ISSUE THREAD

**Issue by ikamyx** [firebase/firebase-tools#5014]
Hello a

I get this error when I try to get URL of the image I stored on firebase

localhost/:1 Uncaught (in promise) FirebaseError: Firebase Storage: An unknown error occurred, please check the error payload for server response. (storage/unknown) 400

This is my rule

```
service firebase.storage {
    match /b/{bucket}/o {
        match /{allPaths=**} {
            allow read, write: if true;
    }
  }
}
```

and this is my code

```
    useEffect(() => {
            listAll(imageListRef).then((response) => {
                response.items.forEach((item) => {
                    getDownloadURL(item).then((url) => {
                        props.setFiles(el => ({
                            ...el,
                            url: url
                        }))
                    })
                })
            })
    }, [])
```

I checked imageListRef, it's not empty 
Only the request return with no result with this error

**Comment by yuchenshi** [comment]
Would you mind posting the full stack trace, along with any Firebase CLI log files?
