### ISSUE TITLE
Grouped functions deployment fails with errorType: OK

### ISSUE THREAD

**Issue by pehagg** [firebase/firebase-tools#5025]
### [REQUIRED] Environment info

**firebase-tools:** 11.10.0

**Platform:** macOS

### [REQUIRED] Test case

N/A, see next section.

### [REQUIRED] Steps to reproduce

1. Create a set of two or more grouped functions, as per Firebase documentation.
2. Issue `firebase deploy --only functions:myNewAndShinyGroupedFunctions`
3. Grab a cup of coffee while you wait for the deployment to fail

Running this from a yarn workspace (monorepo), which is most likely the source for the warning in the error message.

### [REQUIRED] Expected behavior

Deployment of grouped functions should work, as it did yesterday (problem noticed first time today, some 4 or so hours ago). The error message should explain what went wrong.

### [REQUIRED] Actual behavior

When deploying any grouped functions, or occasionally when deploying a single function within a group, I get the following error: 

```console
Build failed: {"metrics":{},"error":{"buildpackId":"","buildpackVersion":"","errorType":"OK","canonicalCode":"OK","errorId":"","errorMessage":""},"stats":[{"buildpackId":"google.nodejs.runtime","buildpackVersion":"1.0.0","totalDurationMs":1038,"userDurationMs":0},{"buildpackId":"google.utils.archive-source","buildpackVersion":"0.0.1","totalDurationMs":85,"userDurationMs":85},{"buildpackId":"google.nodejs.npm","buildpackVersion":"1.0.0","totalDurationMs":19965,"userDurationMs":19663},{"buildpackId":"google.nodejs.functions-framework","buildpackVersion":"0.9.4","totalDurationMs":5331,"userDurationMs":4999},{"buildpackId":"google.config.entrypoint","buildpackVersion":"0.9.0","totalDurationMs":0,"userDurationMs":0},{"buildpackId":"google.utils.label","buildpackVersion":"0.0.2","totalDurationMs":0,"userDurationMs":0}],"warnings":["*** Improve build performance by generating and committing package-lock.json."],"customImage":false}
```

This error is repeated for each failed function deployment in the group. Grouped function deployments seem to almost always fail as a whole (1-2 functions in the group may in some rare cases deploy successfully), single function deployments succeed about 50% of the time.

**Comment by Dulajdeshan** [comment]
I am also having this issue.

**Comment by pehagg** [comment]
As an added bonus, the functions that eventually get deployed don't have the the `allUsers` principal added to them anymore. Can't really say if this is related or its own issue.

**Comment by SimonKib** [comment]
Me too

**Comment by codethik** [comment]
Same, we tried to downgrade to previous version but it has no effect

**Comment by ferraricharles** [comment]
Same here, started today, Yesterday I could deploy normally. I saw this issue in GCP https://issuetracker.google.com/issues/233923087, though the functions which are failing are random so I don't think it has anything to do with the artifact registry.

**Comment by taeold** [comment]
We are investigating the issue. Thanks for raising the issue. Will post an update in a few hours.

**Comment by pehagg** [comment]
> 1. Visit https://pantheon.corp.google.com/cloud-build/builds

Would love to help, but this link leads me to a (Google) corporate SSO page which requires a @google.com email address. Any corresponding address in GCP console? I checked the Cloud Build dashboard but it doesn't list any Cloud Function builds.

**Comment by pehagg** [comment]
Nevermind, was looking underneath the wrong region, my builds are already using my function region. The build fails on step 1, with the following error message:

```
"build": ERROR: failed to export: failed to write image to the following tags: [europe-west1-docker.pkg.dev/<REDACTED>/gcf-artifacts/channel--get:version_5: PUT https://europe-west1-docker.pkg.dev/v2/<REDACTED>/gcf-artifacts/channel--get/manifests/version_5: MANIFEST_UNKNOWN: Requested entity was not found.]
```

**Comment by pehagg** [comment]
Missed another error that was preceding the one above. Here's snippet of build log, including a couple of preceding lines with both errors included:

```
...

"build": Saving europe-west1-docker.pkg.dev/<REDACTED>/gcf-artifacts/channel--get:version_5...
"build": *** Images (sha256:782aadeae28490586d244f47acc66dd60f4f0ddf88f3d83dd2b82782d8dc8325):
"build": europe-west1-docker.pkg.dev/<REDACTED>/gcf-artifacts/channel--get:version_5 - PUT https://europe-west1-docker.pkg.dev/v2/<REDACTED>/gcf-artifacts/channel--get/manifests/version_5: MANIFEST_UNKNOWN: Requested entity was not found.
"build": ERROR: failed to export: failed to write image to the following tags: [europe-west1-docker.pkg.dev/<REDACTED>/gcf-artifacts/channel--get:version_5: PUT https://europe-west1-docker.pkg.dev/v2/<REDACTED>/gcf-artifacts/channel--get/manifests/version_5: MANIFEST_UNKNOWN: Requested entity was not found.]

...
```

When comparing these logs with a successful deployment of the same function, it's not the dash in the function name. The successful ones have it too.

**Comment by pehagg** [comment]
Inspired by @ferraricharles 's comment, I checked the project's Artifact Registry, as the error points towards that direction. The project's Container Registry transition settings has all hosts routed to Container Registry and each route has a warning icon next to the status message. These are the default settings that have been in effect since the project was created. Nobody has touched the settings either.

**Comment by SimonKib** [comment]
@taeold The correct URL to look this up is https://console.cloud.google.com/cloud-build/builds (yours go through a Google SSO as @pehagg mentions)

I see very similar errors as @pehagg 
I notice that we are both using "europe-west1" region. 

At the top of my CI log I also notice a warning that in the future major version of firebase-tools, you will no longer support token-based login, but I hope this is not related.

Here are the relevant parts from my log:
```
2022-09-27 16:17:43.768 CEST Step #1 - "build": ERROR: failed to export: failed to write image to the following tags: [europe-west1-docker.pkg.dev/redacted/gcf-artifacts/api--subscription--start_subscription:version_331: PUT https://europe-west1-docker.pkg.dev/v2/redacted/gcf-artifacts/api--subscription--start_subscription/manifests/version_331: MANIFEST_UNKNOWN: Requested entity was not found.]
Info
2022-09-27 16:17:44.385 CESTFinished Step #1 - "build"
Info
2022-09-27 16:17:44.385 CESTERROR
Info
2022-09-27 16:17:44.385 CESTERROR: build step 1 "europe-west1-docker.pkg.dev/gae-runtimes/gcp/buildpacks/google-gae-18/nodejs/builder:nodejs16_20220912_16_17_0_RC00" failed: step exited with non-zero status: 246
```

**Comment by SimonKib** [comment]
...Without changing anything it started working again. Would be great to understand what happened and if we can do anything to avoid it?
Also, I checked [the status page for Firebase](https://status.firebase.google.com/) and could not see anything.

**Comment by taeold** [comment]
@SimonKib @pehagg Thanks for sharing more info (sorry about the bad link!)

My hunch tells me that there may have been an issue with Google Cloud Functions. I'll reach out to the team and see if I can uncover anything.

Thank you all for your patience and being proactive about issue. I appreciate it.

**Comment by pehagg** [comment]
I'll close the issue, as things are back to normal. Would be interested in knowing the root cause though.
