### ISSUE TITLE
Optional usage collection when logging in

### ISSUE THREAD

**Issue by idancali** [firebase/firebase-tools#503]
### Version info

**3.13.1**

### Steps to reproduce

```
firebase login
```

or

```
client.login()
```

### Expected behavior

The prompt should be made optional.

### Actual behavior

The user is always prompted:

```
? Allow Firebase to collect anonymous CLI usage and error reporting information? (Y/n) 
```

**Comment by thechenky** [comment]
This should be possible now with using service accounts: https://cloud.google.com/docs/authentication/getting-started. You would need to create a service account and have the token as an env variable on the same machine from which you'd be doing `firebase login`.
