### ISSUE TITLE
Auth Emulator blocking functions is not creating user with custom claims

### ISSUE THREAD

**Issue by juandpaez** [firebase/firebase-tools#5044]
### [REQUIRED] Environment info

**firebase-tools:** 11.12.0

**Platform:** Windows

### [REQUIRED] Test case

Unfortunately, I don't have an automated test for it

### [REQUIRED] Steps to reproduce

1. Create a blocking function like the following example:
```.js
export const beforeUserCreated = functions
  .region(firebaseRegion)
  .auth.user()
  .beforeCreate(async (authUser, context) => {
    const { email } = authUser;

    const claims = {
      role: "admin",
    };
    return { customClaims: claims };
  });
```
2. In the web front-end, implement sing-in functionallity with `GoogleAuthProvider` and `signInWithPopup`
3. Run the emulators and the web app
4. Try signing in
5. Open the emulator UI, go to the Authentication page, check  if the user has the assigned claims

### [REQUIRED] Expected behavior

According to the firebase documentation: [Here](https://firebase.google.com/docs/functions/beta/auth-blocking-events#modifying_a_user), the user should be modified and assigned the claims

### [REQUIRED] Actual behavior

The user is not getting the claims assigned, I went to the Authentication page of the Emulator UI, and checked the user claims and the field is empty

**Comment by lisajian** [comment]
Hey @juandpaez,

Trying to gain some more context about the issue:

1. What version of Firebase Functions are you using? The syntax appears to that of Cloud Functions v1 ([link](https://firebase.google.com/docs/auth/extend-with-blocking-functions)) whereas the documentation linked in the issue is for Cloud Functions v2 (i.e. [link](https://firebase.google.com/docs/functions/beta/auth-blocking-events#modifying_a_user))
2. Are you seeing any logs in the Functions Emulator UI? The path of which should be the path to the emulator UI with `/functions` appended to the end, e.g. http://localhost:4000/functions

Thanks!

**Comment by juandpaez** [comment]
Hi, here my responses:
1. The package I am using for firebase-functions is 3.22.0. 
   When I created the issue, I made a quick google search to find the docs and apparently I copied the link of the beta preview, my mistake. The correct link would be this [Link](https://firebase.google.com/docs/auth/extend-with-blocking-functions#modifying_a_user). (The same you pointed out for v1).
   When my code runs on production it works properly, is just the emulator which is failing.
2. The only messages I see in the logs are:
18:16:42
function[europe-west3-auth-beforeUserCreated] Beginning execution of "auth.beforeUserCreated" 18:16:43
function[europe-west3-auth-beforeUserCreated] Finished "auth.beforeUserCreated" in 485.079ms

Hope that helps!

**Comment by lisajian** [comment]
Hey @juandpaez, thanks for the info! Could you try updating your `firebase-functions` version to 3.23.0 or higher? There was bug in v3.22.0 that impacted setting custom claims and session claims, and the fix went out in [v3.23.0](https://github.com/firebase/firebase-functions/releases/tag/v3.23.0). Please feel free to close this issue if that fixes the bug you're seeing!

Credits and much thanks to @colerogers for pointing out the fix in v3.23.0

**Comment by juandpaez** [comment]
Hi @lisajian 
Thanks for the quick response, I update the package and it worked as expected.
Thanks!

**Comment by baughmann** [comment]
Is this not working again?

I'm using the emulator via `firebase emulators:start` with
```shell
firebase --version
11.27.0
```

```json
  "dependencies": {
    "firebase-admin": "^11.5.0",
    "firebase-functions": "^4.2.0"
  },
```

And the function
```typescript
import * as functions from 'firebase-functions';
import * as admin from 'firebase-admin';
admin.initializeApp();

export const beforeSignIn = functions.auth.user().beforeSignIn(async (user) => {
  // log the call
  functions.logger.info('beforeSignIn', user);
  const { uid } = user;
  await admin.auth().setCustomUserClaims(uid, { foo: 'bar' });
  return user;
});
```

That *should* be getting called by my client-side code:
```typescript
  const signInWithGoogle = async (): Promise<IUser | null> => {
    try {
      await signInWithRedirect(auth, googleProvider);
      return getUser((await getRedirectResult(auth))?.user);
    } catch (error) {
      console.error('error signing in with google: ', error);
      return null;
    }
  };
```
