### ISSUE TITLE
Emulate functions individually

### ISSUE THREAD

**Issue by ahaverty** [firebase/firebase-tools#508]
### Version info
3.13.1

### Steps to reproduce
This is more of a feature request
I'm emulating over 50 functions (mostly realtime database).
Emulating 1 function versus 50+ is a lot quicker to start up and seems to use less resources.
I tend to only work on one function at a time too.
I'm currently just commenting out the functions I don't want to emulate on the index.
Something like `firebase experimental:functions:shell --only functionName` would be ideal.

### Expected behavior
Firebase tools allows specific function emulations

### Actual behavior
Functions are slow to startup/emulate and seem to be resource heavy

**Comment by laurenzlong** [comment]
That is in fact on our roadmap! Thanks for the validation.

**Comment by thechenky** [comment]
Internal bug reference: 66904717

**Comment by abeisgoat** [comment]
This has been dramatically improved with the new emulator backend. Please re-open if you're still experiencing, however I suspect it will be a non-issue now.
