### ISSUE TITLE
[FR] Allow deploying gen2 http functions as unauthenticated

### ISSUE THREAD

**Issue by larssn** [firebase/firebase-tools#5084]
**Is your feature request related to a problem? Please describe.**
It's my understanding that gen2 http functions deploy as requiring authentication by default, which is the opposite of gen1.
This makes migration from gen1 to gen2 trickier than it should be.

**Describe the solution you'd like**
I'd like a global default where I can change this behavior.
I'd also like a CLI parameter that can override this.

**Comment by inlined** [comment]
HTTPS functions default to open in v2 just like v1. The only difference is that v2 functions cannot support HTTP (a feature we soft-disabled in v1 a while ago as well)
