### ISSUE TITLE
Firebase Deploy Functions Failed (Linux): libc.so.6, GLIBC_2.28, required by node (maybe a more helpful error message?)

### ISSUE THREAD

**Issue by psygo** [firebase/firebase-tools#5085]
> This was originally [posted on StackOverflow](https://stackoverflow.com/q/73899382/4756173).

I'm trying to deploy a function which *is working* locally with the emulators, but, when trying to deploy, give me this:

```error
i  functions: creating Node.js 16 function <function-name>(us-central1)...
Build failed: node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28'
not found (required by node); Error ID: 653c7ba4

Functions deploy had errors with the following functions:
        <function-name>(us-central1)
i  functions: cleaning up build files...

Error: There was an error deploying functions
```

What I've tried so far:

1. Downgrade my Node version from 18 to 16.

    Yes, I do have this in my `package.json`:

    ```json
    "engines": {
      "node": "16"
    },
    ```

1. Rebuild everything from scratch with Node 16.

I think `libc.so.6` is related to Java, but I don't know how that helps. Here is my `java --version`:

```
java 19 2022-09-20
Java(TM) SE Runtime Environment (build 19+36-2238)
Java HotSpot(TM) 64-Bit Server VM (build 19+36-2238, mixed mode, sharing)
```

> I'm using Archcraft, a distro based on Arch Linux.

> I've just realized that I can share my whole repo, since it's an open source project. [Here it is](https://github.com/psygo/go-brasil-ranking/tree/9c44182e545ed7cd24b3f0ca947f521c65f846ee).

> [A related issue](https://stackoverflow.com/q/73888393/4756173).

**Comment by benboughton1** [comment]
I have the same issue even after adjusting package.json node version to 16.

**Comment by kyduff** [comment]
> I have the same issue even after adjusting package.json node version to 16.

I also have this issue. @psygo Can you clarify what you mean when you said you changed your node version to `16.x.x`? Hadn't you already tried changing `engines.node` to 16?

**Comment by russellwheatley** [comment]
I would also add that your nodejs version in your `firebase.json` overrides the nodejs version set in your `package.json` as described here: https://firebase.google.com/docs/functions/manage-functions?gen=2nd#set_nodejs_version

Seems like your issue is now resolved, @psygo?
