### ISSUE TITLE
Angular not using firebase emulator providers?

### ISSUE THREAD

**Issue by brooksdra** [firebase/firebase-tools#5092]
### [REQUIRED] Environment info

firebase --version
11.8.1

**firebase-tools:**

macOS on Apple silicon

**Platform:**

### [REQUIRED] Test case

Launching emulator with "firebase emulators:start --only auth,firestore"
Launching my Angular development environment with  "ng serve"
Using signInWithGoogle continues to reference my firebase hosted testing environment instead of the emulator.
Using signInWithEmailAndPassword continues to reference my firebase hosted testing environment instead of the emulator.

### [REQUIRED] Steps to reproduce

I've configured firebase emulators to run as follows, and they are running as expected.

┌─────────────────────────────────────────────────────────────┐
│ ✔  All emulators ready! It is now safe to connect your app. │
│ i  View Emulator UI at http://localhost:4001                │
└─────────────────────────────────────────────────────────────┘

┌────────────────┬────────────────┬─────────────────────────────────┐
│ Emulator       │ Host:Port      │ View in Emulator UI             │
├────────────────┼────────────────┼─────────────────────────────────┤
│ Authentication │ localhost:5005 │ http://localhost:4001/auth      │
├────────────────┼────────────────┼─────────────────────────────────┤
│ Firestore      │ localhost:5006 │ http://localhost:4001/firestore │
└────────────────┴────────────────┴─────────────────────────────────┘
  Emulator Hub running at localhost:4400
  Other reserved ports: 4500

I've configured Angular with:

**environment.ts**
```
export const environment = {
  // See Firebase Project settings general, your application
  logLevel: 0,       //All = 0, Debug = 1, Info = 2, Warn = 3, Error = 4, Fatal = 5, Off = 6,
  production: false,
  useEmulators: true,
  firebase: {
    projectId: "journal-ease-test",
```
...

**app.module.ts**
 ```
providers: [
    ...
    { provide: USE_AUTH_EMULATOR, useValue: environment.useEmulators ? [ 'http://localhost:5005' ] : undefined },
    { provide: USE_FIRESTORE_EMULATOR, useValue: environment.useEmulators ? [ 'localhost', 5006 ] : undefined },
  ...
  ],
```
**Notes:** 
- Debugging confirms environment.useEmulators = true
- Per StackOverflow, I've tried different variations of  [ 'http://localhost:5005' ] and [ 'localhost', 5005 ] and [ 'http://localhost', 5005 ] for USE_AUTH_EMULATOR configuration.

### [REQUIRED] Expected behavior

Launching emulator with "firebase emulators:start --only auth,firestore"
Launching my Angular development environment with  "ng serve"
Using signInWithGoogle continues should show the emulated user creation dialog.
Using signInWithEmailAndPassword should reference an existing emulator user.

### [REQUIRED] Actual behavior

Launching emulator with "firebase emulators:start --only auth,firestore"
Launching my Angular development environment with  "ng serve"
Using signInWithGoogle continues to reference my firebase hosted testing environment instead of the emulator.
Using signInWithEmailAndPassword continues to reference my firebase hosted testing environment instead of the emulator.

**Comment by davideast** [comment]
Hey @brooksdra! Try using the provide APIs and if that doesn't work open up an issue in @angular/fire.

```ts
imports: [
    provideFirebaseApp(() => initializeApp(environment.firebase)),
    provideAuth(() => {
      const auth = getAuth();
      connectAuthEmulator(auth, 'http://localhost:9099', { disableWarnings: true });
      return auth;
    }),
    provideFirestore(() => {
      const firestore = getFirestore();
      connectFirestoreEmulator(firestore, 'localhost', 8080);
      return firestore;
    })
 ]
```

**Comment by brooksdra** [comment]
Thank you, That, with slight modifications, got me up and running.

```
    provideFirebaseApp(() => initializeApp(environment.firebase)),
    provideAuth(() => {
      const auth = getAuth();
      if (environment.useEmulators) {
        connectAuthEmulator(auth, 'http://localhost:5005', { disableWarnings: true });
      }
      return auth;
    }),
    provideFirestore(() => {
      const firestore = getFirestore();
      if (environment.useEmulators) {
        connectFirestoreEmulator(firestore, 'localhost', 5006);
      }
      return firestore;
    }),
```
Also, I transmitted these comments to a few AngularFire issues that could use it.
