### ISSUE TITLE
Firebase Hosting: `firebase deploy` ignores the -m argument in version 11.14.1

### ISSUE THREAD

**Issue by guneemwelloeux** [firebase/firebase-tools#5107]
In version 11.14.1 of `firebase-tools`, the `firebase deploy` command seems to completely ignore the -m argument (description), and the description in empty in the Firebase Hosting dashboard.
Version 11.13.0 was working fine in that regard.

I believe this change to be the offending one, where it seems that the release message was dropped in the new api.createRelease function

https://github.com/firebase/firebase-tools/commit/3a92daf7d663afb3d08790640f44bc77435c9d4e#diff-7d0f3d70809a7e16334fc0ebd9d0b60757f72a416dd11397b62c37ef41b5ed1fL51

**Comment by bkendall** [comment]
You're right. A consequence of a refactor that happened. Will squish the bug.
