### ISSUE TITLE
Error: Server Error. unable to get local issuer certificate

### ISSUE THREAD

**Issue by obbe79** [firebase/firebase-tools#512]
### Version info

3.13.1

### Steps to reproduce
I regularly use npm through my corporate proxy (I have properly configured it and it works with no problems) and I successfully installed firebase-tools.
However after successfully logging into my firebase account, I tried to `firebase use --add ` in my project folder and got:

```
[debug] [2017-10-17T08:57:24.732Z] ----------------------------------------------------------------------
[debug] [2017-10-17T08:57:24.734Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\####\AppData\Roaming\npm\node_modules\firebase-tools\bin\firebase use --add
[debug] [2017-10-17T08:57:24.734Z] CLI Version:   3.13.1
[debug] [2017-10-17T08:57:24.734Z] Platform:      win32
[debug] [2017-10-17T08:57:24.734Z] Node Version:  v6.11.2
[debug] [2017-10-17T08:57:24.735Z] Time:          Tue Oct 17 2017 10:57:24 GMT+0200 
[debug] [2017-10-17T08:57:24.735Z] ----------------------------------------------------------------------
[debug] 
[debug] [2017-10-17T08:57:24.745Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase"]
[debug] [2017-10-17T08:57:24.745Z] > authorizing via signed-in user
[debug] [2017-10-17T08:57:24.747Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/projects  
 Tue Oct 17 2017 10:57:24 GMT+0200
[debug] [2017-10-17T08:57:25.319Z] Error: unable to get local issuer certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:610:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)
[error] 
[error] Error: Server Error. unable to get local issuer certificate
```
My first guess is that the problem is related to the proxy. However npm works fine with my proxy config. I tried to add to npm the following:

`npm config set cafile "<path-to-cacert.pem>"`

with no luck.
Does anybody know what is going on? Am I missing some steps?
Thank you.

**Comment by obbe79** [comment]
Ok so basically after 2 days of research I finally came up with a (hack)solution by looking at Node.js documentation on TLS.  
Setting the following environment variable does the trick:

`set NODE_TLS_REJECT_UNAUTHORIZED=0`

I personally don't like this solution but at least it makes me work. 
Is this something that has to be fixed? 
Or am I missing something on the configuration of npm behind a proxy?

Thanks.

**Comment by alekseichuk** [comment]
@obbe79 is there any other proper fix for this? thanks.

**Comment by obbe79** [comment]
Unfortunately I was not able to find a different solution.
