### ISSUE TITLE
Firebase Deploy Succeeds but does not deploy to console.

### ISSUE THREAD

**Issue by saphyron** [firebase/firebase-tools#5124]
### [REQUIRED] CLI

**firebase-tools:**

**Windows:**

### [REQUIRED] Trying to deploy, Suceeds but nothing happens
> firebase deploy

=== Deploying to 'dual-universe-hauling'...

i  deploying database, firestore
i  database: checking rules syntax...
+  database: rules syntax for database dual-universe-hauling-default-rtdb is valid
i  firestore: reading indexes from firestore.indexes.json...
i  cloud.firestore: checking firestore.rules for compilation errors...
+  cloud.firestore: rules file firestore.rules compiled successfully
+  firestore: deployed indexes in firestore.indexes.json successfully
i  firestore: latest version of firestore.rules already up to date, skipping upload...
i  database: releasing rules...
+  database: rules for database dual-universe-hauling-default-rtdb released successfully
+  firestore: released rules firestore.rules to cloud.firestore

+  Deploy complete!

### [REQUIRED] Expected behavior

That it deploys

### [REQUIRED] Actual behavior

It does not deploy
![image](https://user-images.githubusercontent.com/30288325/195765228-b12bf93c-154d-4e7d-8897-c5b206d6cbac.png)

**Comment by saphyron** [comment]
Kept trying to deploy until it finally deployed, no clue why it did not until then.

**Comment by bkendall** [comment]
```
=== Deploying to 'dual-universe-hauling'...

i deploying database, firestore
```

Looks like you didn't have a Hosting config, so it wouldn't have deployed anything that would have been visible in the Console view for Hosting.

**Comment by nipunasudha** [comment]
Please tell me how to disable this feature
