### ISSUE TITLE
Deploy storage rules using CLI

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [firebase/firebase-tools#513]
I've found #383 and #461. Is it possible at this time to deploy storage rules using CLI? If yes, how? Is it documented somewhere?

**Comment by laurenzlong** [comment]
firebase init storage

After set up is complete:
firebase deploy 
OR
firebase deploy --only storage

**Comment by laurenzlong** [comment]
I've also filed a bug internally to update our documentation with these instructions.

**Comment by mbleigh** [comment]
Documented in the [getting started](https://firebase.google.com/docs/storage/security/start#edit_rules) for Storage Rules, as well as [an in-depth look at deploy targets](https://firebase.google.com/docs/cli/targets) if you're doing multi-bucket.
