### ISSUE TITLE
Something went wrong, firebase has not been installed

### ISSUE THREAD

**Issue by abdalazeez1** [firebase/firebase-tools#5130]
run on ubunte 22.04
when i run  
`curl -sL https://firebase.tools | bash
`

-- Checking for existing firebase-tools on PATH...
-- Checking your machine type...
-- Downloading binary from https://firebase.tools/bin/linux/latest
######################################################################## 100.0%#Warning: Failed to open the file /usr/local/bin/firebase: No such file or     
Warning: directory
                                                                           0.0%curl: (23) Failure writing output to destination

-- Setting permissions on binary...
chmod: cannot access '/usr/local/bin/firebase': No such file or directory
bash: line 255: /usr/local/bin/firebase: No such file or directory
Something went wrong, firebase has not been installed.
Please file a bug with your system information on Github.
https://github.com/firebase/firebase-tools/
-- All done!

**Comment by mohammadriyad903** [comment]
I am getting same problem here
`sudo bash -c 'curl -sL https://firebase.tools | bash'
-- Checking for existing firebase-tools on PATH...
-- Checking your machine type...
-- Downloading binary from https://firebase.tools/bin/linux/latest
######################################################################## 100.0%#Warning: Failed to open the file /usr/local/bin/firebase: No such file or     
Warning: directory
                                                                           0.0%curl: (23) Failure writing output to destination

-- Setting permissions on binary...
chmod: cannot access '/usr/local/bin/firebase': No such file or directory
bash: line 255: /usr/local/bin/firebase: No such file or directory
Something went wrong, firebase has not been installed.
Please file a bug with your system information on Github.
https://github.com/firebase/firebase-tools/
-- All done!
`

**Comment by gmarizy** [comment]
> @abdalazeez1 Does the path `/usr/local/bin` exists? What happens if you run: `sudo bash -c 'curl -sL https://firebase.tools | bash'`?

Same error for me.

**Comment by ThatLinuxGuyYouKnow** [comment]
> Look at "curl: (23) Failure writing output to destination". This works for me:
> 
> $ sudo snap remove curl $ sudo apt install curl
> 
> When you do sudo snap install curl, curl is useless.

Same problem even with an apt installl

**Comment by Mo7mud** [comment]
Same issue on Linux Mint:
```
curl -sL firebase.tools | bash
-- Checking for existing firebase-tools...
-- Your machine has a corrupted firebase-tools binary, attempting upgrade...
-- Checking your machine type...
-- Downloading binary from https://firebase.tools/bin/linux/latest
######################################################################## 100.0%##O=#  #   ###############                                                           21.7%curl: (92) HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)

[sudo] password for mohammad:       
-- Setting permissions on binary... /usr/local/bin/firebase
Something went wrong, firebase has not been installed.
Please file a bug with your system information on Github.
https://github.com/firebase/firebase-tools/
-- All done!
```
