### ISSUE TITLE
Deploy error using `firebase-functions@latest`

### ISSUE THREAD

**Issue by gOzaru** [firebase/firebase-tools#5132]
### [REQUIRED] Environment info

**firebase-tools: 11.14.4**
"firebase-functions": "^4.0.0-rc.0"

**Platform: Windows**

### [REQUIRED] Test case

https://stackoverflow.com/questions/74083042/npm-error-fix-the-upstream-dependency-conflict-installing-npm-packages-cloud-f

### [REQUIRED] Steps to reproduce

I updated `npm install -g firebase-tools`, then `npm i firebase-functions@latest`. Then try to deploy.

### [REQUIRED] Expected behavior

It should have deployed all the functions.

### [REQUIRED] Actual behavior

Build failed: npm ERR! code ERESOLVE npm ERR! ERESOLVE could not resolve npm ERR! npm ERR! While resolving: firebase-functions-test@0.2.3 npm ERR! Found: firebase-functions@4.0.0-rc.0 npm ERR! node_modules/firebase-functions npm ERR! firebase-functions@"^4.0.0-rc.0" from the root project npm ERR! npm ERR! Could not resolve dependency: npm ERR! peer firebase-functions@">=2.0.0" from firebase-functions-test@0.2.3 npm ERR! node_modules/firebase-functions-test npm ERR! dev firebase-functions-test@"^0.2.0" from the root project npm ERR! npm ERR! Conflicting peer dependency: firebase-functions@3.24.1 npm ERR! node_modules/firebase-functions npm ERR! peer firebase-functions@">=2.0.0" from firebase-functions-test@0.2.3 npm ERR! node_modules/firebase-functions-test npm ERR! dev firebase-functions-test@"^0.2.0" from the root project npm ERR! npm ERR! Fix the upstream dependency conflict, or retry npm ERR! this command with --force, or --legacy-peer-deps npm ERR! to accept an incorrect (and potentially broken) dependency resolution. npm ERR! npm ERR! See /www-data-home/.npm/eresolve-report.txt for a full report.

**Comment by gOzaru** [comment]
![SS - Firefunctions Screenshot 2022-10-16 065507](https://user-images.githubusercontent.com/3258483/196010520-17dd8101-f881-4011-90a8-363126e48695.jpg)

**Comment by gOzaru** [comment]
![SS - Firefunctions Screenshot 2022-10-16 075507](https://user-images.githubusercontent.com/3258483/196010729-8fccd2eb-00f8-490b-8506-675ed412a6e2.jpg)

**Comment by TheIronDev** [comment]
The error messaging is suggesting that there is a peerDep issue with the latest canary release of `firebase-functions`.

The tl;dr - `firebase-functions-test` peerDep is getting confused with the pre-release version of `firebase-functions`.

What happens when you pin `firebase-functions` to `3.24.1`?

**Comment by gOzaru** [comment]
I tried to go back to latest version and it works fine.

**Comment by gOzaru** [comment]
Weird. All of my functions return unauthenticated null..

**Comment by HilarionLV** [comment]
> I tried to go back to latest version and it works fine. I meant 3.24.1. Weird. All of my functions return unauthenticated null... It used to be okay.

Here you have how to fix it: 
https://cloud.google.com/functions/docs/securing/managing-access-iam

Note: By default, entities that need to invoke an HTTP function must explicitly present authentication credentials (proof of identity) as well as having the required permissions. The authentication requirement, however, can be [turned off](https://cloud.google.com/functions/docs/securing/managing-access-iam#allowing_unauthenticated_http_function_invocation). For more information on how to acquire and present the appropriate authentication credential, see [Authenticating for invocation](https://cloud.google.com/functions/docs/securing/authenticating).

**Comment by petrvecera** [comment]
We run into this error too, first it complains that firebase functions are not latest and then:
```
pm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: my-fb-app@0.1.0
npm ERR! Found: firebase-functions@4.0.1
npm ERR! node_modules/firebase-functions
npm ERR!   firebase-functions@"^4.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer firebase-functions@"^3.23.0" from firebase-frameworks@0.6.1
npm ERR! node_modules/firebase-frameworks
npm ERR!   firebase-frameworks@"^0.6.0" from the root project
```

**Comment by gOzaru** [comment]
Has this error solved yet?

**Comment by gOzaru** [comment]
> > I tried to go back to latest version and it works fine. I meant 3.24.1. Weird. All of my functions return unauthenticated null... It used to be okay.
> 
> Here you have how to fix it: https://cloud.google.com/functions/docs/securing/managing-access-iam
> 
> Note: By default, entities that need to invoke an HTTP function must explicitly present authentication credentials (proof of identity) as well as having the required permissions. The authentication requirement, however, can be [turned off](https://cloud.google.com/functions/docs/securing/managing-access-iam#allowing_unauthenticated_http_function_invocation). For more information on how to acquire and present the appropriate authentication credential, see [Authenticating for invocation](https://cloud.google.com/functions/docs/securing/authenticating).

Thank you for the help

**Comment by gOzaru** [comment]
I just disabled App Check on Cloud Functions and it worked again as it should be. 
Is something wrong with latest App Check on Cloud Function?
As I am using the latest 4.1.0 function.

**Comment by gOzaru** [comment]
Sorry, I forgot to activate App Check library on Flutter. My bad. I will close this.
