### ISSUE TITLE
Hosting Emulator: Geting 404 error page instead of index.html

### ISSUE THREAD

**Issue by ASHHAD-BASE** [firebase/firebase-tools#5133]
I have recently updated firebase tools by `npm update -g firebase-tools`
and the expected hosting emulator behavior has changed.
I am getting 404 page instead of index.html.

**Expected behavior**

when accessing `localhost:5000` I should get `localhost:5000/index.html`
but i am getting `404` not found page
also I am getting `localhost:5000/index.html` when using url `localhost:5000/index.html`.

**To Reproduce**

I have tried installing emulator suite from scratch on another machine
and still getting 404 not found page instead of index.html
so this bug may have been introduced in new versions of firebase-tools

OS: windows
Browser :n/a
firebase-tools Version :11.14.4

**Comment by Frankellyguzman** [comment]
I am having the same issue, were you able to figure it out?

**Comment by TheLowHigh** [comment]
I'm also having this issue, I'm still trying to figure out why.

**Comment by bkendall** [comment]
Can y'all give me a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) for this? I've done `init hosting` with rewrites, without rewrites, but I've been unable to reproduce this issue.

**Comment by TheLowHigh** [comment]
https://github.com/TheLowHigh/Firebase404

**Comment by bkendall** [comment]
With your Firebase404 repo, running on macOS:

```
~ » curl -I http://localhost:5004
HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8
Content-Length: 318
ETag: 0dbe35bef73e03f6689c1719f365f752
Last-Modified: Mon, 17 Oct 2022 19:25:49 GMT
Vary: Accept-Encoding
Date: Mon, 17 Oct 2022 19:26:43 GMT
Connection: keep-alive
Keep-Alive: timeout=5

~ » curl -I http://localhost:5004/index.html
HTTP/1.1 301 Moved Permanently
Location: /
Content-Type: text/html; charset=utf-8
Date: Mon, 17 Oct 2022 19:26:53 GMT
Connection: keep-alive
Keep-Alive: timeout=5
```

I've got a windows machine behind me - looks like I'm giving that a whirl.

**Comment by TheLowHigh** [comment]
Just installed wsl and debian and everything is working, I belive this might be a windows only issue

**Comment by bkendall** [comment]
yup! opened up the windows machine and I get a 404 page on `/` (but a 301 on `/index.html`, which is correct with cleanURLs).

When I remove `cleanURLs`, I get different behavior. It returns the 404 page on `/` and `/index.html` works (200).

I may copy this issue over to superstatic since that's where the issue will be, but this is definitely a weird one.

**Comment by HuskerSam** [comment]
this works now!  thanks!
