### ISSUE TITLE
Multiple errors from common/params when build with Typescript

### ISSUE THREAD

**Issue by readyiman** [firebase/firebase-tools#5138]
### [REQUIRED] Environment info

**firebase-tools: 11.14.4**

**Platform: Windows**

### [REQUIRED] Test case

Any ts file

### [REQUIRED] Steps to reproduce

`npm run build` on Functions folder

### [REQUIRED] Expected behavior

Build done

### [REQUIRED] Actual behavior

Multiple similar errors from same folder:
```
node_modules/firebase-functions/lib/common/params.d.ts:21:164 - error TS1005: ';' expected.    

21 export declare type Extract<Part extends string> = Part extends `{${infer Param}=**}` ? Param : Part extends `{${infer Param}=*}` ? Param : Part extends `{${infer Param}}` ? Param : never;
   
```
Found 25 errors.

**Comment by readyiman** [comment]
All errors is in this file `node_modules/firebase-functions/lib/common/params.d.ts`

**Comment by inlined** [comment]
What version of TypeScript are you using? Some of the metaprogramming in this file requires a relatively recent version of TS. Can you confirm that the error still presents if you run `npm install --save typescript@latest`?

**Comment by readyiman** [comment]
Was 3.8.0, run and updated to 4.8.4. Does work.
I'm always updated firebase-tools and firebase-functions as the CLI recommend to, but there is no Ts update recommendation.
This is my first time encounter this.
Problem solved. Thanks.

**Comment by readyiman** [comment]
Btw @inlined, I just realized my package.json devDependencies looking like this
```json
"devDependencies": {
    "@typescript-eslint/eslint-plugin": "^3.9.1",
    "@typescript-eslint/parser": "^3.8.0",
    "eslint": "^7.6.0",
    "eslint-config-google": "^0.14.0",
    "eslint-plugin-import": "^2.22.0",
    "firebase-functions-test": "^0.2.0",
    "typescript": "^4.8.4"
  },
```
Do I need to update all those eslint too? What the command to update it?

**Comment by inlined** [comment]
I don't honestly know if you need a major version bump of eslint. To install the latest version of a package, use `npm install --save <package>@latest`

**Comment by thedav22** [comment]
I'm having the same problem, but updating Typescript did not work for me. Is there another step I missed?
