### ISSUE TITLE
Firebase Deploy Svelte uses wrong path

### ISSUE THREAD

**Issue by Nushio** [firebase/firebase-tools#5144]
### [REQUIRED] Environment info

**firebase-tools:** 11.15.0, using experimental webframeworks support

**Platform:** macOS

### [REQUIRED] Test case

Not sure how to do this, but steps to reproduce below. 

### [REQUIRED] Steps to reproduce

1. Brand new sveltekit project
2. Try firebase serve (it works)
3. Try firebase deploy (it fails, more info below)

### [REQUIRED] Expected behavior

App should deploy.

### [REQUIRED] Actual behavior

Error: ENOENT: no such file or directory, lstat

App fails. The .firebase/project-name/hosting folder is empty. 

Running the deploy command with --debug, I see that the path it's trying to access is wrong. 
 Error: ENOENT: no such file or directory, lstat '/Users/myuser/vanillasvelte/Users/myuser/vanillasvelte/.svelte-kit/output/client'

Instead, it should just use /Users/myuser/vanillasvelte/.svelte-kit/output/client.

**Comment by Nushio** [comment]
The issue is on line 69 (nice!) of [vite/index.ts](https://github.com/firebase/firebase-tools/blob/master/src/frameworks/vite/index.ts)

export async function ɵcodegenPublicDirectory(root: string, dest: string) {
  const viteConfig = await getConfig(root);
  const viteDistPath = join(root, viteConfig.build.outDir);
  await copy(viteDistPath, dest);
} 

The root folder is being joined with the outDir.

**Comment by Nushio** [comment]
I spent some time and forked the firebase-tools, and experimented with the [svelte/index.ts](https://github.com/firebase/firebase-tools/blob/master/src/frameworks/svelte/index.ts) plugin

Copying/adding these lines is enough to get it to build properly, but deploying will require a new svelte adapter to work, which is probably out of the scope of this project.

`export async function ɵcodegenPublicDirectory(root: string, dest: string) {
  const svelteConfig = await getConfig(root);
  await copy(svelteConfig.build.outDir, dest);
}
async function getConfig(root: string) {
  const { resolveConfig } = relativeRequire(root, "vite");
  return await resolveConfig({ root }, "build", "production");
}`

Should I / can I send a PR with these changes? I'd love to be an official contributor. 👼

**Comment by inlined** [comment]
If you want to send a PR we'll definitely review it. We're open source for a reason. Otherwise we'll try to get to this as soon as possible.
