### ISSUE TITLE
next js app  "Site not found" error with  VPN

### ISSUE THREAD

**Issue by jasan-s** [firebase/firebase-tools#5148]
### [REQUIRED] Environment info

**firebase-tools:**
 11.15.0

**Platform:**
MacOS

### [REQUIRED] Steps to reproduce

Deploy next js app using `Firebase deploy` after web frameworks experiment enabled and then visit project hosted url with VPN enabled (I'm using Mozilla VPN)
### [REQUIRED] Expected behavior

Hosted app should serve next js app everytime I visit my `myfirebaseproject.web.app`

### [REQUIRED] Actual behavior

When using VPN,  project url `myfirebaseproject.web.app` leads to the following error 
> "site not found'

![Screenshot_20221020-094137~2](https://user-images.githubusercontent.com/13863953/197013189-be0110d1-12be-464d-8c42-d370b17380a2.png)

## Additional Note:
Previous next js app deployed using older version CLI with  `firebase --open-sesame frameworkawareness`  is accessible with VPN. The problem only exists with next js app using the latest CLI

**Comment by jamesdaniels** [comment]
This issue should be long fixed, likely it was the codebase getting turned entirely into SSR & something not working. Please open a new issue if you're able to reproduce with firebase-tools v12
