### ISSUE TITLE
cannot deploy custom event triggers (onCustomEventPublished)

### ISSUE THREAD

**Issue by taishi55** [firebase/firebase-tools#5153]
### [REQUIRED] Environment info

**firebase-tools:** 11.15.0

**Platform:** macOS

### [REQUIRED] Test case

?

### [REQUIRED] Steps to reproduce

1. create a project and install stripe extension with setup
2. initialize firebase function
3. add 
```
import { onCustomEventPublished } from "firebase-functions/v2/eventarc";

export const customevent = onCustomEventPublished(
    {
      eventType: "com.stripe.v1.customer.subscription,
      channel: "locations/us-west1/channels/firebase",
      region: "us-west1",
    },
    (event) => { ... });
```
5. deploy the function
6. you will see an error and fail the deployment

### [REQUIRED] Expected behavior

Successful deployment

### [REQUIRED] Actual behavior
```
Could not create or update Cloud Run service customevent, Container Healthcheck failed. Revision 'customevent-00001-rem' is not ready and cannot serve traffic. The user-provided container failed to start and listen on the port defined provided by the PORT=8080 environment variable. Logs for this revision might contain more information.

```

**Comment by inlined** [comment]
We have additional work to do to create the channel on demand when a function is created. If you deploy the Extension that writes to the channel first and then deploy the function that listens to it, does that work for now?

**Comment by taishi55** [comment]
The problem was using `config()`. Use secret manager instead of using config(). Then you can deploy without a problem
