### ISSUE TITLE
[feature request] expect firebase serve --open to open new tab at local hosting

### ISSUE THREAD

**Issue by hiepxanh** [firebase/firebase-tools#516]
### Expected behavior

I don't find this feature, i think it will be more convince to have this feature, I don't have to open new tab each time, when I combine this with batch file

**Comment by mbleigh** [comment]
Because `firebase serve` can also be used to serve functions (and, in the future, potentially other things as well) there isn't necessarily a canonical URL to open. We can keep this under consideration, but right now I'd say it's unlikely.
