### ISSUE TITLE
Functions emulator is not working with Firestore emulator document onCreate trigger

### ISSUE THREAD

**Issue by chinesehemp** [firebase/firebase-tools#5165]
### [REQUIRED] Environment info

**firebase-tools:** 11.15.0

**Platform:** macOS

### [REQUIRED] Test case

Firebase function index.ts

```typescript
import * as functions from "firebase-functions";

export const createStreamUser = functions
  .runWith({
    timeoutSeconds: 60,
    memory: "256MB",
  })
  .region("europe-west2")
  .firestore.document("users/{user}")
  .onCreate(async (snapshot, context) => {
    await (await import("./createUser")).default(snapshot, context);
  });
```

createUser.ts

```typescript
import * as functions from "firebase-functions";
import { QueryDocumentSnapshot } from "firebase-functions/v1/firestore";
import { EventContext } from "firebase-functions";

export default async (
  snapshot: QueryDocumentSnapshot,
  context: EventContext
) => {
  functions.logger.log("Firebase user doc created", { snapshot, context });
  try {
    functions.logger.log("User created");
    return;
  } catch (error) {
    throw new functions.https.HttpsError(
      "aborted",
      "Could not create user"
    );
  }
};
```

### [REQUIRED] Steps to reproduce

1. Run `npm run build` in `functions/`
2. Run `firebase emlators:start`
3. Create a new firestore emulator doc in `users/`

### [REQUIRED] Expected behavior

The emulator log should output `"User created"`

### [REQUIRED] Actual behavior

Function isn't triggered by the new firestore emulator doc

**Comment by christhompsongoogle** [comment]
Thanks Chinesehemp, can you include some debug logs (firestore, functions) and let us know if this is working in a previous version?

**Comment by chinesehemp** [comment]
My bad. It looks like my `"main": "lib/functions/src/index.js"
` in `package.json` was incorrectly set. Closing issue.
