### ISSUE TITLE
[Emulator] Functions don't load starting with firebase-functions@4.0.1

### ISSUE THREAD

**Issue by GrandSchtroumpf** [firebase/firebase-tools#5171]
### [REQUIRED] Environment info
**firebase-tools:** 11.15.0
**Platform:** Windows

### [REQUIRED] Test case
**structure**:
```
node_modules/
dist/
  functions
    package.json
firebase.json
package.json
```
**firebase.json**:
```
{
  ...,
  "functions": {
    "source": "dist/functions",
    "runtime": "node16"
  },
}
```

### [REQUIRED] Steps to reproduce
```
npm i firebase-functions@4.01
firebase emulators:start
```
The functions are not loaded from source

### [REQUIRED] Expected behavior
Functions should be loaded from source even if the node_modules are not in the `functions.source` in `firebase.json`

### [REQUIRED] Actual behavior
The function `checkFunctionsSDKVersion` cannot detect the version of firebase-functions and the functions are not loaded from source.

Notes: 
- This started with `firebase-function@4.0.1`. When using the version `3.24.1` the functions are loaded correctly.
- Running `npm i` in the source directory fixes it. But as this source is a build directory, I cannot run `npm i` each time I change a functions in dev mode.

This might be related to #4906, but as this issue happened with `firebase-functions@4.0.1` and the issue 4906 was created before this version I'm not sure...

**Comment by atsjo** [comment]
I have the same issue, starting with firebase-function@4, using a nx repo and yarn

**Comment by akauppi** [comment]
@GrandSchtroumpf I want to be polite, but also a bit curious about this:

>Functions should be loaded from source even if the node_modules are not in the functions.source in firebase.json

Do you have a source that states that should be the case?

I have always kept `node_modules` within `functions`, and think it's a good manner. In the beginning of my Firebase journey, saw projects that mixed the main project and the Cloud Functions in the same `package.json` and didn't like that.

**Comment by GrandSchtroumpf** [comment]
@akauppi I can understand you don't like it. I would rather not do that, but when working with a monorepo & bundler, I need it... If you've got a better solution for working with cloud functions in an `nx` monorepo let me know.
> Do you have a source that states that should be the case?

I don't know if it *should be*, but it's working with version 3.24.1 of firebase-functions and below, so it feels like a regression from my point of view.

> Also, I suppose you have some .js files in the dist/functions/?

Yes I watch the file changes in my src folder and output the js result in the `dist/functions`, so there are `.js` files.

**Comment by Nr9** [comment]
I have the same issue, starting with firebase-function@4, using a nx repo and yarn

Structure
```
node_modules/
backend/
    functions/
        dist/
            index.js
        package.json ("main": "dist/index.js")
    firebase.json
package.json
```

**Comment by inlined** [comment]
I've made a primary bug for this issue in the firebase-functions repo and am closing duplicates to help us continue triaging and prioritizing. See [firebase-functions/1227](https://github.com/firebase/firebase-functions/issues/1277) for an explanation of what's going on here.
