### ISSUE TITLE
Firebase authentication dashboard shows wrong number of users

### ISSUE THREAD

**Issue by norahabsentia** [firebase/firebase-tools#518]
### Version info

3.13.1

### Steps to reproduce

Export the list of users from any project & re-import them(either as is or with minor modifications) with 
```
firebase auth:import account_file.json --hash-algo=BCRYPT
```  

### Expected behavior

The dashboard should show the correct number of users from the imported json(in this case 18564, or the same) after overwriting them completely(the data is properly overwitten though, we checked that out).

### Actual behavior

The dashboard shows 37120 users but after running the export command again the file contains only 18564 entries.
The dashboard displays the wrong number of users & this is obviously problematic when showing the correct number of users for any firebase-project.

**Comment by pjr0001** [comment]
experiencing this as well. 15k users is showing as 30k users. I messed up the import created_at date so i did another import, data appears unique and correct, but counter is double the user count

**Comment by mbleigh** [comment]
Please file a request [with Firebase support](https://firebase.google.com/support/) to address this, as the CLI has no direct input on the Auth backend or console.

**Comment by yasinturkdogan** [comment]
I am having the same exact issue after one year this ticket has been created. I couldn't find any duplicate records but number of users are displayed wrong.

**Comment by laurenzlong** [comment]
Hey @yasinturkdogan please see @mbleigh's comment above. This is a backend issue, and the best way to get it resolved is by filing a ticket with [Firebase Support](https://firebase.google.com/support/troubleshooter/) so they can look into your issue specifically.
