### ISSUE TITLE
Add Firebase to your Flutter app - CANNOT Install the required command line tools

### ISSUE THREAD

**Issue by emagnu** [firebase/firebase-tools#5188]
``

### [REQUIRED] Environment info

Firebase Version n.a.
Please note i am not using any version of Firebase CLI yet. This issue is about installing it in the first place!

I unsuccessfully attempted the installation several times. My best guess is that there must be an error in  the provided bash script (https://firebase.tools/). 
Please find a link to Google's Firebase CLI  automatic install script on this page: https://firebase.google.com/docs/cli#setup_update_cli

firebase --version
firebase: command not found

**firebase-tools:**

Attempting installation for Ubuntu's Linux:
I am attempting to install firebase CLI on Linux (Ubuntu 22.10 stable Linux kernel 5.19)

**Platform:**

OS: Ubuntu 22.10
Laptop: Dell Vostro 3500

### [REQUIRED] Test case

I wanted to add Firebase to a test Flutter app i am developing for the purpose. I followed the steps as advised by google as recommended on this page: "Add Firebase to your Flutter app"." (https://firebase.google.com/docs/flutter/setup?platform=ios)
Please note that:
a) Flutter is installed on this computer and has been used to develop apps for at least 5 months with no issues.
b) The Firebase account used has been opened and in use for a year and i was singed in when i attempted to install the Firebase CLI. 
c) I am using VS code as IDE and it was up and running with the app i am developing to test Firebase loaded. 

I went through the above mentioned page steps several times but the output was always the same. Please see the "steps" as detailed underneath on this page: https://firebase.google.com/docs/flutter/setup?platform=ios)

Step 1: Install the required command line tools

Point 1 hyperlink to another page to install Firebase CLI:
1. If you haven't already, install the Firebase CLI. (https://firebase.google.com/docs/cli#setup_update_cli)

On this page there are 3 methods to install the Firebase CLI for Linux. I chose the easiest: "automatic install script"

Under "automatic install script" you are requested to run `curl` -sL https://firebase.tools | `bash` which i religiously did. The following shows the result: 

emagnu@V35:~$ curl -sL firebase.tools | bash

-- Checking for existing firebase-tools on PATH...
-- Checking your machine type...
-- Downloading binary from https://firebase.tools/bin/linux/latest
######################################################################## 100.0%#Warning: Failed to open the file /usr/local/bin/firebase: No such file or     
Warning: directory
curl: (23) Failure writing output to destination

-- Setting permissions o n binary...
chmod: cannot access '/usr/local/bin/firebase': No such file or directory
bash: line 255: /usr/local/bin/firebase: No such file or directory
Something went wrong, firebase has not been installed.
Please file a bug with your system information on Github.
https://github.com/firebase/firebase-tools/

AS REQUESTED I " filed a bug with your system information on Github." then i aborted the instalation as other suggested ways are above my skills.

### [REQUIRED] Steps to reproduce
As per above. No other steps were taken. 

This is my first report, i apologise if i am not too clear, please contact me on emagnubcp@gmail.com if you need further details. i will only be happy to provide further clarifying examples.

### [REQUIRED] Expected behavior

Installation should complete!

### [REQUIRED] Actual behavior

**Firebase has not been installed!**
This is the final part of the output.
Something went wrong, firebase has not been installed.
Please file a bug with your system information on Github.
https://github.com/firebase/firebase-tools/

curl -sL https://firebase.tools | bash

Obviously i went ahead to see if the error was just misleading and attempted the following step 

Log in and test the Firebase CLI
  `firebase` login` 

This is the output:
emagnu@V35:~$ firebase login
firebase: command not found

**Comment by gmarizy** [comment]
Same on Ubuntu 23.04. I ended using npm version instead.

**Comment by aalej** [comment]
Hey folks, apologies for the radio silence here, this issue fell through the cracks. Looking at the logs provided, this seems like an issue with the installation of curl. I looked up the error `curl: (23) Failure writing output to destination` and found this [Stack Exchange post](https://askubuntu.com/questions/1387141/curl-23-failure-writing-output-to-destination).

Running the following commands should fix the issue:
```
sudo snap remove curl
sudo apt install curl
rm -rf /usr/local/bin/firebase
sudo curl -sL https://firebase.tools | bash
```

If you're still encountering this issue, feel free to let us know and we'll reopen this thread.
