### ISSUE TITLE
allow storing firebase.json config in package.json file

### ISSUE THREAD

**Issue by sylveon** [firebase/firebase-tools#519]
Right now, we need a separate file to store the config (`firebase.json`). I'd like to make it possible to store them in `package.json`, like [jshint allows](http://jshint.com/blog/better-npm-integration/). For example:
```json
{
    "dependencies": {
        "firebase-tools": "*"
    },
    "firebaseConfig": {
        "hosting": {
            "public": "public"
        }
    }
}
```

**Comment by stefandeml** [comment]
+1
that would be awesome!

**Comment by sylveon** [comment]
Is there any reason for just marking this issue as won't fix and closing it?

**Comment by thechenky** [comment]
This is not something we will support. These two files are separate for a reason, and combining them together will cause unnecessary overhead.
