### ISSUE TITLE
firebase deploy --only functions run successfully without deploy any function if run within yarn workspace (Already nohoist every dependency). 

### ISSUE THREAD

**Issue by TrustyTechSG** [firebase/firebase-tools#5191]
### [REQUIRED] Environment info

**firebase-tools:**11.15.0

**Platform:** MacOS 13.0

### [REQUIRED] Test case
index.js

```
import functions from "firebase-functions";

export const hello = functions.https.onRequest((request, response) => {
  response.send("Hello from Firebase!");
});
```

package.json
```
{
  "name": "test",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "private": true,
  "sideEffects": false,
  "mode": "production",
  "type": "module",
  "scripts": {
    "start": "npm run shell"
  },
  "dependencies": {
    "firebase-functions": "^4.0.1"
  },
  "engines": {
    "node": "16"
  }
}

```
firebase.json
```
{
  "functions": [
    {
      "source": "/",
      "codebase": "test"
    }
  ]
}
```

### [REQUIRED] Steps to reproduce

1. Put the above package.json, index.js and firebase.json into test folder under a simple yarn workspace
/root
/packages/test
/package.json (worksapce package.json)
```
{
  "name": "testing",
  "private": true,
  "workspaces": {
    "packages": [
      "packages/*"
    ],
    "nohoist": [
      "**/firebase-admin",
      "**/firebase-admin/**",
      "**/firebase-functions",
      "**/firebase-functions/**"
    ]
  },
}
```

2. Run yarn, and cd to packages/test to verify all dependency are installed locally (within the same folder)
3. Run firebase deploy --only functions.

### [REQUIRED] Expected behavior

Function hello been successfully created.

### [REQUIRED] Actual behavior

deploy command run successfully without error, but no function deployed.

**Now, simply copy the packages/test folder to anywhere outside the workspace root and cd to the new folder immediately run: firebase deploy --only functions. Function hello successfully deployed.**

**Comment by TrustyTechSG** [comment]
Thank you for the reply @inlined, just asking is this update also going to support deploy function with unpublished local workspace dependency? currently I notice the deploy process assume all dependencies are publish available, which is not true for workspace use case, we have many unpublished dependencies.

**Comment by taeold** [comment]
Same bug, reported on https://github.com/firebase/firebase-functions/issues/1277. Noted here for cross-tracking.

**Comment by taeold** [comment]
Also similar bug in https://github.com/firebase/firebase-tools/issues/5145.

**Comment by taeold** [comment]
We reverted back the change that broke many users in v4.0.2 of the firebase functions sdk.

We are working on a long term solution to make the function deployment aware of workspaces and other dev toolings that changes where npm packages are installed (e.g. pnpm).

In the meantime, please give 4.0.2 a try. Would appreciate your feedbacks.

See https://github.com/firebase/firebase-functions/issues/1277#issuecomment-1297505449 for more info.

**Comment by joehan** [comment]
Closing since I beleive #5215 fixed this.
