### ISSUE TITLE
Failed to validate secret versions

### ISSUE THREAD

**Issue by Tyris** [firebase/firebase-tools#5193]
### [REQUIRED] Version info

**node:** 

v14.19.3

**firebase-functions:** 4.0.1

**firebase-tools:** 11.15.0

**firebase-admin:** 10.2.0

### [REQUIRED] Test case

```ts
import { defineSecret } from "firebase-functions/params";
const SOME_SECRET= defineSecret('SOME_SECRET');
exports.some_function = functions
  .runWith({
    secrets: [
      SOME_SECRET,
    ]
  })
.database.ref('/some_trigger/{some_id}').onCreate(async (snapshot, context) => {
  console.log(process.env[SOME_SECRET.name]);
});
```

### [REQUIRED] Steps to reproduce

`firebase deploy`

### [REQUIRED] Expected behavior

It should prompt for the new secret on deployment per the documentation at https://firebase.google.com/docs/functions/config-env#secret_parameters

### [REQUIRED] Actual behavior

It doesn't prompt for new secrets or deploy, and instead throws this error:

```
Error: Failed to validate secret versions:
- FirebaseError HTTP Error: 404, Secret [projects/12345/secrets/SOME_SECRET] not found or has no versions.
```

### Were you able to successfully deploy your functions?

No.

**Comment by Tyris** [comment]
@taeold this isn't a feature request, it's a bug.

**Comment by webel** [comment]
I'm also seeing this, although a complete noob when it comes to firebase. Although earlier I've successfully deployed new secrets by defining them locally in my `.env`, including them in `runWith` thing and then deploying.

**Comment by endyquang** [comment]
I'm running into similar error, using the `defineSecret` as described on [Parameterized configuration](https://firebase.google.com/docs/functions/config-env#params) 

## Version info

**node**: 16.16.0

**firebase-functions**: 4.0.2

**firebase-tools**: 11.16.1

**firebase-admin**: 11.2.0

## Error
```
Error: Failed to validate secret versions:
- FirebaseError HTTP Error: 400, The provided Secret Version ID [projects/815xxxxxxxx/secrets/[object Object]/versions/latest] does not match the expected format [projects/*/secrets/*/versions/*]
```
After digging into the code I found out the `[object Object]` thing is `{name: 'THE_SECRET_NAME'}`
Then after trying to fix that, it still failed to deploy, here's the error in `firebase-debug.log`
```
{
  "name": "FirebaseError",
  "children": [],
  "context": {
    "body": {
      "error": {
        "code": 400,
        "message": "Invalid value at 'function.secret_environment_variables[0]' (secret), Starting an object on a scalar field\nInvalid value at 'function.secret_environment_variables[0]' (key), Starting an object on a scalar field",
        "status": "INVALID_ARGUMENT",
        "details": [
          {
            "@type": "type.googleapis.com/google.rpc.BadRequest",
            "fieldViolations": [
              {
                "field": "function.secret_environment_variables[0]",
                "description": "Invalid value at 'function.secret_environment_variables[0]' (secret), Starting an object on a scalar field"
              },
              {
                "field": "function.secret_environment_variables[0]",
                "description": "Invalid value at 'function.secret_environment_variables[0]' (key), Starting an object on a scalar field"
              },
            ]
          }
        ]
      }
    },
    "response": {
      "statusCode": 400
    }
  },
  "exit": 1,
  "message": "HTTP Error: 400, Invalid value at 'function.secret_environment_variables[0]' (secret), Starting an object on a scalar field\nInvalid value at 'function.secret_environment_variables[0]' (key), Starting an object on a scalar field",
  "status": 400
}
```

Now I give up using secret.

**Comment by matzeso** [comment]
Running into the same issue as you are @endyquang .
Did you manage to solve it? It looks as though you would need to provide the secret name in the secrets array, instead of the object then - but for local development with emulators everything works fine.

**Comment by endyquang** [comment]
@matzeso Yes I managed to make it work, it turned out only string works with the secrets array
So until this is fixed, for who still want to use the `defineSecret` we can do this
```javascript
const secretAccessKey = defineSecret('SECRET_ACCESS_KEY');
runWith({
  secrets: [secretAccessKey.name],
})
```

**Comment by AmichayMiara** [comment]
Having the same issue, but with using .env file (https://firebase.google.com/docs/functions/config-env#secret_parameters).

Any workaround in this case? 
It already using a string key, but got the same error.

**Comment by leo-paz** [comment]
Using secretAccessKey.name helped fix the [Object object] issue. I was still getting a 404 that it couldn't find the secret instead of being prompted to input a secret.

Adding the secrets manually in Secrets Manager in Google Cloud Console fixed it

**Comment by carlrey9** [comment]
This is an additional service from Google and is similar to other services, first is free but has a limit. You should activate this service(Secret Manager API) and register your secrets. You can find this sign-in to google cloud, search secret manager Api 
add, and go to manage to register the secrets: [https://cloud.google.com/secret-manager](url) .
![image](https://user-images.githubusercontent.com/48773188/229774401-95a9c972-6995-4a03-80f4-b50a71610276.png)

**Comment by Lyokone** [comment]
Hi 👋 Trying to reproduce this issue. It seems that on the latest version (12.7.0 at the time of writing this), the issue has been fixed, and you are prompted to create a secret during the first deployment. 

Let us know if you are still having this issue; thanks

**Comment by AssafBok** [comment]
I had the same issue. Just adding the variable to Google's secret manager, didn't help.
I managed to solve this by using the firebase CLI tool and setting the variable (in this case was INTERNAL_ROUTING_KEY) with `firebase functions:secrets:set INTERNAL_ROUTING_KEY `
the tool asks for a value:
`? Enter a value for INTERNAL_ROUTING_KEY [hidden]` 
and verifiying by this 
`firebase functions:secrets:get INTERNAL_ROUTING_KEY`
![image](https://github.com/firebase/firebase-tools/assets/116381145/f6b2c1b8-b92d-4fae-8845-1d1661ba8de5)

The logs of `firebase deploy` seems to validate this during the deployment process.
The logs show that the command checks the account's IAM policies for access to that variable, which is a new line after the manual assignment using the CLI tool.

*using firebase-tools v13.5.2 and firebase-functions v4.8.1 (today's latest)
