### ISSUE TITLE
firebase emulators open an additional windows that does not close when the emulators are closed

### ISSUE THREAD

**Issue by joaomelo** [firebase/firebase-tools#5217]
### [REQUIRED] Environment info

**firebase-tools:** 11.14.3
**Platform:** Windows 11

### [REQUIRED] Test case

You can clone this repo and start the firebase emulators in it: https://github.com/joaomelo/hot-vue

### [REQUIRED] Steps to reproduce

Clone the repo (I think it will have the same behavior for any project thought), install firebase tools globally, open the windows terminal, and start firebase emulators with `firebase emulators:start` or `firebase emulators:exec "npm test"`

### [REQUIRED] Expected behavior

I would expect that the process would be contained in the same terminal tab it started, and when stopped (with CRTL + C  for "start" or the test completes for "exec") the emulator would be terminated as a whole.

### [REQUIRED] Actual behavior

When we start the emulators, it opens a new window using CMD (even if the emulators were started in the windows terminal). This new process does not terminate if you stop the one where you started the emulator. This causes an undesired behavior: if you need to start emulators again, it will fail and print an error. You have to search for that hanging CMD window to recover. This is very disruptive if someone is in a fast dev cycle. I made a gif to illustrate better.

![firebase emulators](https://user-images.githubusercontent.com/5727050/200125637-d3f8b4fe-6e4d-4e79-ab94-9833a628dc84.gif)

Couldn't this new window be suppressed and run in the background or closed automatically? 

This is even more disruptive with `emulators:exec`, which is supposed to run a script and end without intervention. That CMD process will hang there and disable the ability to call another execution without closing that extra window.

**Comment by ishowta** [comment]
maybe duplicate https://github.com/firebase/firebase-tools/issues/3871

**Comment by christhompsongoogle** [comment]
Looks like a duplicate, let's follow-up there.
