### ISSUE TITLE
Firebase functions:shell is ignoring emulator and using production instead

### ISSUE THREAD

**Issue by risalfajar** [firebase/firebase-tools#5225]
### [REQUIRED] Environment info

**firebase-tools:** 11.15.0

**Platform:** Pop OS (Ubuntu)

### [REQUIRED] Test case

The problem is not project-related.

### [REQUIRED] Steps to reproduce

1. Create a Firebase project
2. Init a Firebase emulator (at least have Firestore and Functions)
3. Create a callable function that access Firestore to be tested
4. Start Firestore emulator
5. Start Functions shell
6. Call the function in point 3

### [REQUIRED] Expected behavior

The function will affect Firestore in emulator

### [REQUIRED] Actual behavior

The function affects Firestore in production
![image](https://user-images.githubusercontent.com/28381124/200367393-64e2caaa-9ffa-41ad-b8a5-e62117d9da1a.png)

**Comment by taeold** [comment]
`functions:shell` command predates Firestore/Storage/other emulator and doesn't not attempt to spin them up as part of its command. You will need to use `emulator:start` with configurations for other emulators to get them up and running.

I think this request is a good feature request though - I'll track the issue as a feature request instead.

**Comment by risalfajar** [comment]
@taeold i have already started the emulators as in the steps number 4.

**Comment by taeold** [comment]
AFAIK The Emulator suite works best when launched via emulator:start command. That way we know exactly what emalators are running and coordinate necessary changes to make sure that the emulated function calls the emulated service, not production ones.

I didn't think the setup you described where we have 2 process launching emalators ever worked because the functions emulator launched via functions:shell command wouldn't be able to know if Firestore emulator is running - and where.

Are you saying that this setup used to work in the past and no longer works now?

As for bug or feature request - I see why you'd call it a bug. It's just an attempt to prioritize things.

If we broke your existing, working setup with a recent release, yes we will definitely patch it asap.

As for others issues, we have to find time to work on them, and marking it as feature request is our best attempt to put some order to incoming, unplanned work! Sorry if this is disappointing.

**Comment by risalfajar** [comment]
@taeold I have 2 terminals opened with different command:
1. `firebase emulators:start --import=./emulators-cache --export-on-exit --only "auth","firestore","database","pubsub","storage"`
2. `firebase functions:shell`

What I am expecting is for the Shell to detect the emulator, and calling any function  from it would affect the emulator only.

**Comment by risalfajar** [comment]
Identical issue: #2116

Could you help @samtstern ?

**Comment by taeold** [comment]
@risalfajar Unfortunately for all of us, Sam no longer works at Firebase :(

Thanks for sharing more context - I didn't look at your initial screenshot carefully and yes it looks like things should've worked as you described as suggested by the log output. Sorry for confusion my part.

**Comment by risalfajar** [comment]
@taeold that's unfortunate 🙁

But I hope this is a quick fix since it have been fixed before.

**Comment by jlalvarez18** [comment]
I have the same issue:

`functions: Connected to running firestore emulator at 127.0.0.1:8080, calls to this service will affect the emulator`
`⚠  functions: The following emulators are not running, calls to these services will affect production: database, pubsub, storage, eventarc`

--- Invoke function here

`⚠  functions: The Cloud Firestore emulator is not running, so calls to Firestore will affect production.`

The above output states that it sees the emulator. When you invoke a function it then proceeds to hit production. This is a serious bug that needs to be resolved.

**Comment by Yvens16** [comment]
Hello, any updates on this? Since there is not link for the pubsub.schedule functions and the shell doesn't recognize other emulators running there is no way to test my pubsub function locally... 😭😭
Hope it will be fixed soon 🤞

Thank you for your hard work guys!

**Comment by taeold** [comment]
Sorry for the delay folks. Top item in my plate, but due to Thanksgiving, the earliest we can ship a fix would be next week. Will keep the status updated as we get closer to releasing a fix. Thank you all for your patience.

**Comment by taeold** [comment]
@Yvens16 If you haven't already, can you file another issue?

**Comment by apetta** [comment]
> Any updates? IMO, this should be a priority fix.

Rolling back to 11.14.0 works for now

**Comment by risalfajar** [comment]
> Rolling back to 11.14.0 works for now

I'll try that. Thanks!

**Comment by Yvens16** [comment]
Hello @taeold I filled another issue ? But just out of curiosity why did I need to ? 

Thank you

**Comment by bartkoedijk** [comment]
@apetta  Thank you! I have been facing this issue for hours now.
When i downgraded to 11.14.0 it finally worked again.

Downgrade command: 
`npm install -g firebase-tools@11.14.0`

**Comment by orbiteleven** [comment]
I'm still seeing this behavior using `v11.18.0`:

In one terminal I run:
```sh
firebase emulators:start --import ./data/firebase --export-on-exit --only auth,firestore
```
and validate that they're running in the UI. 

In the 2nd I run: 
```sh
firebase functions:shell

i  functions: Loaded functions: createUserDocument, newSlackUserNotify, sendNewFlightNotifications
i  functions: Connected to running firestore emulator at 127.0.0.1:8080, calls to this service will affect the emulator
⚠  functions: The following emulators are not running, calls to these services will affect production: database, pubsub, storage, eventarc
firebase > testEmulatorConnection()
'Successfully invoked function.'
firebase > ⚠  functions: The Cloud Firestore emulator is not running, so calls to Firestore will affect production.
⚠  Google API requested!
   - URL: "https://oauth2.googleapis.com/token"
   - Be careful, this may be a production service.
>  {
>    User: 1
>  }
```

The test function:
```typescript
import * as FirebaseAdmin from 'firebase-admin';
import * as functions from 'firebase-functions';

const admin = FirebaseAdmin.initializeApp();

export const testEmulatorConnection = functions
  .region('europe-west1')
  .pubsub.schedule('every 1 minutes')
  .onRun(async () => {
    const users = await admin.firestore().collection('users').get();
    const userDoc = users.docs[0].data();
    console.log(userDoc);
  });
```

**Comment by orbiteleven** [comment]
Thanks, @risalfajar. Unfortunately, #4952 is preventing us from updating; [v.11.20.0](https://github.com/firebase/firebase-tools/releases/tag/v11.20.0) does not include #5391, so we wait...

**Comment by MorenoMdz** [comment]
> @taeold I have 2 terminals opened with different command:
> 
> 1. `firebase emulators:start --import=./emulators-cache --export-on-exit --only "auth","firestore","database","pubsub","storage"`
> 2. `firebase functions:shell`
> 
> What I am expecting is for the Shell to detect the emulator, and calling any function from it would affect the emulator only.
> 
> The Shell definitely knows that emulators are running (see screenshot above). But as soon as I call a function, it stopped detecting those emulators, hence calling the production.

I used this for years and now I went to develop something and lucky I realized in time it was not connecting to the local emulator any more, I almost called some not-very-safe cloud functions in Prod.

Sorry for the vent but why does the FB team keep cutting features from Firebase like this without no warnings? And if it is a regression the team needs to step up and fix it faster. It is not even close to the first time this happens.

**Comment by MorenoMdz** [comment]
> @orbiteleven they fixed it in [v11.19.0](https://github.com/firebase/firebase-tools/releases/tag/v11.19.0)
> 
> I still use v11.14.0 though, so I haven't tested it

It does not, running from 11.25.2 still gives me this warning:

`⚠  functions: Functions Emulator unable to start on port 5001, starting on 5002 instead.`

**Comment by tjlondon-npauctions** [comment]
Did we ever find a solution to this? 

Trying to execute some shell commands against my emulator with imported data, but the shell always wants to start a new emulator.

**Comment by sirusbaladi** [comment]
Same issue for me too, this such a fundamental feature.
Using 12.8.1

**Comment by ChromeQ** [comment]
I just ran into this issue, my problem was that I had updated `firebase-tools` on one part of my project and not the other, so ensure the version of firebase-tools that runs the emulator and the one that runs the shell are the same version.

This won't apply to you if you use a global installation of `firebase-tools` but I prefer to have local installations in my packages of the monorepo (I intend to write a test to ensure the versions are in sync but didn't get round to it yet!)

**Comment by rrust** [comment]
If you see this:

> ⚠  functions: Functions Emulator unable to start on port 5001, starting on 5002 instead.

You can start the shell with the emulator running on port 5001 like this:

`firebase functions:shell --port 5001`

This will get you this:

> ⚠  functions: You are already running the Cloud Functions emulator on port 5001. Running the emulator and the Functions shell simultaenously can result in unexpected behavior.
...

> i  functions: Connected to running firestore emulator at 127.0.0.1:8080, calls to this service will affect the emulator
> i  functions: Connected to running pubsub emulator at 127.0.0.1:8085, calls to this service will affect the emulator
> i  functions: Connected to running eventarc emulator at 127.0.0.1:9299, calls to this service will affect the emulator

I suppose this is isn't the intended behavior, but it does the trick for me.

**Comment by ir-fuel** [comment]
The above does not seem to work for me.

I start the emulators:

```
┌─────────────────────────────────────────────────────────────┐
│ ✔  All emulators ready! It is now safe to connect your app. │
│ i  View Emulator UI at http://127.0.0.1:4000/               │
└─────────────────────────────────────────────────────────────┘

┌────────────────┬──────────────┬──────────────────────────────────┐
│ Emulator       │ Host:Port    │ View in Emulator UI              │
├────────────────┼──────────────┼──────────────────────────────────┤
│ Authentication │ 0.0.0.0:9099 │ http://127.0.0.1:4000/auth       │
├────────────────┼──────────────┼──────────────────────────────────┤
│ Functions      │ 0.0.0.0:5001 │ http://127.0.0.1:4000/functions  │
├────────────────┼──────────────┼──────────────────────────────────┤
│ Firestore      │ 0.0.0.0:8080 │ http://127.0.0.1:4000/firestore  │
├────────────────┼──────────────┼──────────────────────────────────┤
│ Storage        │ 0.0.0.0:9199 │ http://127.0.0.1:4000/storage    │
├────────────────┼──────────────┼──────────────────────────────────┤
│ Extensions     │ 0.0.0.0:5001 │ http://127.0.0.1:4000/extensions │
└────────────────┴──────────────┴──────────────────────────────────┘
  Emulator Hub running at 127.0.0.1:4400
  Other reserved ports: 4500, 9150
┌─────────────────────────┬───────────────┬─────────────────────┐
│ Extension Instance Name │ Extension Ref │ View in Emulator UI │
└─────────────────────────┴───────────────┴─────────────────────┘
Issues? Report them at https://github.com/firebase/firebase-tools/issues and attach the *-debug.log files.
```

in another tab I call:
```
firebase functions:shell --port 5001
```

And this is the output:

```
⚠  functions: The following emulators are not running, calls to these services will affect production: firestore, database, pubsub, storage, eventarc, tasks
```

using firebase version 13.29.1

**Comment by gugahoi** [comment]
Still an issue, the described commands do not work and the emulator shell is unable to auto connect the running emulators. Is there something that needs to be done in code to direct the functions in the shell to leverage the emulator manually? Maybe some env variables?

**Comment by gugahoi** [comment]
If you are using the recommended `demo-` projects to develop locally, make sure to put the appropriate flag and things look to work again:

```
npx firebase functions:shell --project demo-abcd
```

Maybe this can be added to documentation to save future users some time trying random suggestions out.

**Comment by risalfajar** [comment]
Just want to add, this happened to me because I have two projects (staging and production).

I'm running the emulator using the production project, but running the shell using the staging project, so the two wouldn't connect.

TL:DR Make sure the emulator and shell are **in the same project**.
