### ISSUE TITLE
Firebase CLI v11.16.0 is incompatible with Node.js v12.22.12 Please upgrade Node.js to version ^14.18.0 || >=16.4.0

### ISSUE THREAD

**Issue by rizwan92** [firebase/firebase-tools#5239]
### [REQUIRED] Environment info

**firebase-tools:** 11.16.0

**Platform:** nodejs , firebase-functions, mac-os : Ventura 13.0.1

### [REQUIRED] Test case

firebase emulators:start --only functions

facing issue 
```
Firebase CLI v11.16.0 is incompatible with Node.js v12.22.12 Please upgrade Node.js to version ^14.18.0 || >=16.4.0
```
my index.js 

```
/* eslint-disable object-curly-spacing */
const functions = require("firebase-functions");

// // Create and Deploy Your First Cloud Functions
// // https://firebase.google.com/docs/functions/write-firebase-functions
//
exports.app = functions.https.onRequest((request, response) => {
  functions.logger.info("Hello logs!", { structuredData: true });
  response.send("Hello from Firebase!");
});

```
dependencies 

```
   "engines": {
    "node": "12"
  },
  "main": "index.js",
  "dependencies": {
    "firebase-admin": "^10.0.2",
    "firebase-functions": "^4.0.2"
  },

```

**nodejs:** v18.12.1

### [REQUIRED] Steps to reproduce

just run firebase emulators:start --only functions you will get this error in

### [REQUIRED] Expected behavior

it should start my emulator ui and local function server 

when i roll back firbase-tool to 10.9.2 and rm -rf node_mdoules && rm -rf package-lock.json

then i ran firebase emulators:start --only functions 

then it throws this error 

```
msahu2595@MANISHs-iMac functions % firebase emulators:start --only functions
i  emulators: Starting emulators: functions
⚠  functions: The following emulators are not running, calls to these services from the Functions emulator will affect production: auth, firestore, database, hosting, pubsub, storage
⚠  Your requested "node" version "12" doesn't match your global version "18". Using node@18 from host.
i  ui: Emulator UI logging to ui-debug.log
i  functions: Watching "/Users/msahu2595/Desktop/rizwan/bowoot-master/functions" for Cloud Functions...
i  emulators: Shutting down emulators.
i  ui: Stopping Emulator UI
⚠  Emulator UI has exited upon receiving signal: SIGINT
i  functions: Stopping Functions Emulator
i  hub: Stopping emulator hub
i  logging: Stopping Logging Emulator
Error: Failed to parse backend specification:
- FirebaseError object endpoints[app].availableMemoryMb failed validation

Having trouble? Try firebase [command] --help

```

### [REQUIRED] Actual behavior

this should run mu local emulator and local server

my firbase.json file 

```
{
  "functions": {
    "source": "functions",
    "predeploy": [
      "npm --prefix \"$RESOURCE_DIR\" run lint"
    ]
  },
  "hosting": {
    "public": "build",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "rewrites": [
      {
        "source": "**",
        "destination": "/index.html",
        "function": "app"
      }
    ]
  },
  "database": {
    "rules": "database.rules.json"
  },
  "storage": {
    "rules": "storage.rules"
  },
  "emulators": {
    "auth": {
      "port": 9099
    },
    "functions": {
      "port": 5001
    },
    "database": {
      "port": 9000
    },
    "hosting": {
      "port": 5000
    },
    "storage": {
      "port": 9199
    },
    "ui": {
      "enabled": true
    },
    "singleProjectMode": true
  }
}


```

**Comment by joehan** [comment]
Support for node12 was dropped in [v11.0.0,](https://github.com/firebase/firebase-tools/releases/tag/v11.0.0) because node12 is long past EOL (https://endoflife.date/nodejs) & we needed to drop support in order to update critical dependencies. 

If you need to use node12, you'll need to stick with firebase-toold@10 - however, we strongly recommend updating your functions to use a more recent node version.

**Comment by rizwan92** [comment]
Issue is still the same 
I upgraded the dependencies you can see in below pictures and 

<img width="1670" alt="image" src="https://user-images.githubusercontent.com/19162978/202694534-8f41f0b9-722a-4feb-88d9-2376729c9a25.png">

and the firebase version is 
<img width="698" alt="image" src="https://user-images.githubusercontent.com/19162978/202694946-346ef1fa-b6f6-4055-aa82-c41e47c329e0.png">

and after running npm run serve its giving the same error

<img width="1429" alt="image" src="https://user-images.githubusercontent.com/19162978/202695099-bc7628d5-aded-4f7f-adbe-a03598f2894c.png">

**Comment by rizwan92** [comment]
@joehan  ?? any update on it

**Comment by nobulirakli** [comment]
just chiming to say if you have WSL installed, check the version installed on there. i found that 16.1.0 was coming from my debian terminal. no idea why powershell is reading from there, but it could be a clue
