### ISSUE TITLE
Error when deploying only functions if database rules.json doesn't exist

### ISSUE THREAD

**Issue by serhiipalash** [firebase/firebase-tools#524]
Error when deploying only functions if database rules.json doesn't exist

### Version info
<img width="454" alt="screen shot 2017-10-30 at 21 53 07" src="https://user-images.githubusercontent.com/14208343/32192410-c3292670-bdbc-11e7-986a-035ba478a39e.png">

### Actual behavior

I have project structure like this
```
/
  functions/
    ...
  database/
    rules/
      paths/
         root.bolt
         users.bolt
          ...
  firebase.json
```

My database rules builds into `/database/build/rules.json` and I have in my **firebase.json**. 

```
"database": {
    "rules": "database/build/rules.json"
 }
```

When I try to deploy only functions and `database/build/rules.json` doesn't exist I get error `Imported file database/build/rules.json does not exist`

<img width="748" alt="screen shot 2017-10-30 at 22 02 41" src="https://user-images.githubusercontent.com/14208343/32192870-21b1a4d2-bdbe-11e7-9e72-d2b9896918ad.png">

### Expected behavior

Deployment of functions doesn't require that the database rules file specified in `firebase.json` exists.

**Comment by mbleigh** [comment]
This is happening as a pre-flight check that verifies the `firebase.json` is accurate. I think it's probably reasonable to avoid that check when scoped deploys are happening, but it's fairly deep in the internals so may take some time to fix.

**Comment by serhiipalash** [comment]
> may take some time to fix

Ok. Thanks!

**Comment by serhiipalash** [comment]
@mbleigh thanks! It works.
