### ISSUE TITLE
NextJS Image Optimization causes 500 errors on refresh

### ISSUE THREAD

**Issue by bruceharrison1984** [firebase/firebase-tools#5241]
### [REQUIRED] Environment info

**firebase-tools: 11.16.0**

**Platform: Windows/Linux**

### [REQUIRED] Test case

SSG Page (no SSR)

Deploying a NextJS app via `firebase deploy` or github action fails if using the `next/image` and refreshing the page. This returns a 500 response.

Removing all Image components allows the page to render, as well as be refreshed without error. No usable error is surfaced through Google logs, nor the client.

### [REQUIRED] Steps to reproduce

Deploy a NextJS app to Firebase that contains an Image component. Refresh the page, and a 500 should appear.

### [REQUIRED] Expected behavior

I should be able to use the next/image component, or be steered towards another implementation.

### [REQUIRED] Actual behavior

The page refresh fails with a 500. These happens if deployed, or running locally.

**Comment by jamesdaniels** [comment]
We ended up fixing some issues by manually adding the sharp dep on deploy if image optimization is detected, if you have troubles with v11.19.0+ let us know.
