### ISSUE TITLE
Keep file IDs the same for repeated firebase emulators:export calls

### ISSUE THREAD

**Issue by IchordeDionysos** [firebase/firebase-tools#5266]
A few releases ago, there was a change in how the command `firebase emulators:export --only storage` command works.

Previously, the file names were URL encoded instead e.g. the file gs://not-a-bucket/foo/bar.svg would become the following:

- blobs
  - not-a-bucket%2Ffoo%2Fbar.svg
- metadata
  - not-a-bucket%2Ffoo%2Fbar.svg.json
  
Now a UUID is used instead, leading to the following structure instead:

- blobs
  - UUID-FOOO-BAAAAR.svg
- metadata
  - UUID-FOOO-BAAAAR.json

However, the UUID of the same file changes every time your run:

```
firebase emulators:start --import ./emulator_export
firebase emulators:export ./emulator_export
```

It would be cool if the UUIDs would stay the same so you can depend your tests on that

We have a test that looks like this:

```ts
await fs.readFile(
  './test/tools/fixtures/emulator_export/storage_export/blobs/' +
  'b7fbcaa2-5669-46c4-bc27-de0dcc064386' // not-a-bucket/foo/bar.svg
);
```

And this test breaks every time we need to update our test data. Then we need to go into the export data, look into the metadata files, figure out the new UUID of the file and copy the new ID into the test.

**Comment by danbaechtold** [comment]
I'd like this to get fixed, too, because we store the development data export in Git, and now every time the emulators are started/stopped we get hundreds of changes.
