### ISSUE TITLE
Firebase Functions and Node Support

### ISSUE THREAD

**Issue by gauntface** [firebase/firebase-tools#527]
Node version 8 is now in LTS: https://nodejs.org/en/

When attempting to use Firebase Functions locally, this is the error I get:

>   functions: Cannot start emulator. Please use Node version v6.9.1, you have v8.2.1

Please keep up with the current Node ecosystem.

**Comment by mbleigh** [comment]
Node v8 is coming to GCF, but we don't have a specific timeline for it. Since that's dependent entirely on the Cloud Functions product and not the CLI, I'm going to go ahead and close this since there's no action to take on this end.
