### ISSUE TITLE
Firestore document is read multiple times after a single update in Firebase emulator

### ISSUE THREAD

**Issue by ablbol** [firebase/firebase-tools#5272]
I am using Firestore emulator to save users data in my Flutter mobile app. Each user in my app has a stream that listens to the user's document.I noticed that after the user document is UPDATED, document is read twice or more in the emulator. I have attached an image from the Firestore emulator that shows that. Is there a reason why I am getting multiple reads after a single update. I am not doing any read to the user document outside the stream.  Also in my Firestore security rules I have simple rules like this:

```
allow update: if true;
allow get: if true;
allow list: if true;
```
Which means I am not reading the user doc inside Firestore security rules.

![Screenshot 2022-11-27 at 8 15 21 AM](https://user-images.githubusercontent.com/22548671/204121223-f3e2e359-d5e9-4b52-bfa3-689e35aa27bd.jpg)

This is how I am listening to the user document. The print statement prints only one read. But if I am reading the user document only in the stream, then how do I end up with multiple reads in the emulator?

```
  Stream<MyProfile?> watchMyProfile() {
    return _firestore
        .doc(PathService.user(uid))
        .withConverter<MyProfile>(
          fromFirestore: (snapshot, _) {
            return MyProfile.fromJson(snapshot.data()!);
          },
          toFirestore: (myProfile, _) => myProfile.toJson(),
        )
        .snapshots()
        .map((doc) => doc.data())
        .map(
      (myProfile) {
        // THIS ONLY PRINTS ONCE. BUT THE EMULATOR HAS MULTIPLE READS
        debugPrint('watchMyProfile - read my profile');
        return myProfile;
      },
    );
  }
```

### [REQUIRED] Environment info

11.16.1.

**firebase-tools:**

macOS

**Platform:**

### [REQUIRED] Expected behavior

I expect to see one document read after an update of the document.

### [REQUIRED] Actual behavior
Currently I am seeing multiple reads of the user document after a single update of the user document.

**Comment by christhompsongoogle** [comment]
Dupe: https://github.com/firebase/firebase-tools/issues/4325
