### ISSUE TITLE
Trigger function secrets are not in line with runWith definition

### ISSUE THREAD

**Issue by pehagg** [firebase/firebase-tools#5279]
### [REQUIRED] Environment info

**firebase-tools:** 11.16.1
**firebase-functions:** 3.24.1

**Platform:** macOS

### [REQUIRED] Test case

Don't have time for this right now.

### [REQUIRED] Steps to reproduce

When deploying a Firestore trigger function (onCreate) that references a secret added with `firebase functions:secrets:set`, the function doesn't have access to the defined secret in the `runWith` section, instead it picks another secret that is defined for another function in the source file (I'm using grouped functions). 

This is what is exposed, what _should be exposed_ is `ALGOLIA_API_KEY`: 

<img width="456" alt="secrets" src="https://user-images.githubusercontent.com/672472/204746163-02997a97-aa18-45c9-9d08-23c2053704d3.png">

The only way to workaround the issue is to manually expose the secret to the function using the web console. 

This issue has also been brought up in the [community Slack](https://firebase-community.slack.com/archives/C29NN871C/p1667981877428169) on November 9th.

This used to work earlier just fine. The last change I can recall is updating firebase-tools, the function hasn't changed for many months, I just redeployed it. 

### [REQUIRED] Expected behavior

The function should have access to the exposed secret(s) defined in `runWith` section.

### [REQUIRED] Actual behavior

Described above.

**Comment by Lyokone** [comment]
Hey 👋 Are you still experiencing this issue with the latest version? We are not able to reproduce this.

**Comment by pehagg** [comment]
Haven't run into this issue for a long time anymore. I have refactored things and redefined secrets, which might've resolved it somehow.

Closing issue as resolved.
