### ISSUE TITLE
Can't find project with "use --add" but can deploy with "--project my_project"

### ISSUE THREAD

**Issue by Alqueraf** [firebase/firebase-tools#529]
Hello, I created a new project some days ago from the firebase dashboard and it is not seen with the firebase-tools CLI.

### Version info
`firebase --version`
3.14.0

### Steps to reproduce
It is not shown when I use `firebase list`, and neither with `firebase use --add` or `firebase use --add --project my_project`. However I can deploy locally and to firebase using `firebase deploy --project my_project`, but it is extremely annoying to add this extra parameter every time.

I also did `firebase logout` and `firebase login` to no result.
I have full ownership of the project with my G account.

### Expected behavior
My firebase project should appear as an option with `firebase list` or `firebase use --add`

### Actual behavior
Current project is missing, only older projects are displayed

**Comment by Alqueraf** [comment]
It appeared today, after a week, without updating or changing anything on my side.

Can be closed, but for future references, seems like sometimes it can take a lot of time to appear on the CLI.

**Comment by cenbarter** [comment]
I just wanted to say that I am experiencing this exact problem right now. It has been a couple of days and the project still won't appear when I use `firebase list` or `firebase use --add`

`firebase --version`
3.17.4

**Comment by gspat24** [comment]
same here! `firebase --version (3.18.4)`

**Comment by bkendall** [comment]
I'm closing this. Please reopen it if you're seeing this issue.

**Comment by micksatana** [comment]
Same issue, I tried many suggestions on the Internet, no luck. Strange thing is in the console I can see all projects. Only in CLI not listing the projects (confirmed using the same account).

[See detail in my case here](https://github.com/firebase/firebase-tools/issues/1098)

**Comment by PRASHANTPR7** [comment]
same here, please help
