### ISSUE TITLE
Trouble running functions in emulator error Cannot read properties of undefined (reading 'runWith')

### ISSUE THREAD

**Issue by nolafs** [firebase/firebase-tools#5296]
I am not able to run my function in emulator after updating to the latest firebase-functions. I am getting the following error:

[debug] [2022-12-02T11:18:55.511Z] Got response from /__/functions.yaml Failed to generate manifest from function source: TypeError: Cannot read properties of undefined (reading 'runWith')

### [REQUIRED] Environment info

Project is in Typescript

"firebase": "^9.14.0",
"firebase-admin": "^11.3.0",
"firebase-functions": "^4.1.0",
"firebase-tools": "^11.16.1",

Platform: macOS

### [REQUIRED] Test case

No test as I cannot even compile anything

### [REQUIRED] Steps to reproduce

Starting the emulator with database import

### [REQUIRED] Expected behavior

Compile and run the functions

### [REQUIRED] Actual behavior

[Error ](functions: Failed to load function definition from source: FirebaseError: Failed to load function definition from source: Failed to generate manifest from function source: TypeError: Cannot read properties of undefined (reading 'runWith'))

**Comment by aalej** [comment]
Hi @nolafs, I tried replicating the issue you mentioned by emulating Functions and Database,  however, I wasn’t able to get any error messages or issues when compiling and running Functions. With this, could you provide me with an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) or more details about the steps you took so that we can try to replicate this?

**Comment by lazee** [comment]
I do not know the exact reason behind the problem, but I had the same problem. After tweaking tsconfig.json and eslintrc.js a bit, I managed to get things working again.

<details>
<summary>dependencies</summary>

```json
  {"dependencies": {
    "@google-cloud/pubsub": "3.2.1",
    "body-parser": "1.20.1",
    "cookies": "0.8.0",
    "cors": "2.8.5",
    "date-fns": "2.29.3",
    "express": "4.18.2",
    "express-bearer-token": "2.4.0",
    "firebase-admin": "^11.3.0",
    "firebase-functions": "^4.1.0",
    "jsonwebtoken": "8.5.1",
    "uuid": "9.0.0"
    },
  "devDependencies": {
    "@types/body-parser": "1.19.2",
    "@types/cookies": "0.7.7",
    "@types/cors": "2.8.13",
    "@types/express": "^4.17.14",
    "@types/jsonwebtoken": "8.5.9",
    "@types/node": "16.18.7",
    "@types/uuid": "9.0.0",
    "@typescript-eslint/eslint-plugin": "^5.46.0",
    "@typescript-eslint/parser": "^5.46.0",
    "eslint": "^8.29.0",
    "eslint-config-google": "^0.14.0",
    "eslint-plugin-import": "^2.26.0",
    "firebase-functions-test": "3.0.0",
    "jest": "29.3.1",
    "typescript": "4.9.4"
  }}
   ```
</details>

<details>
<summary>eslintrc.js</summary>

```js
module.exports = {
  root: true,
  env: {
    es6: true,
    node: true,
  },
  extends: [
    "eslint:recommended",
    "plugin:import/errors",
    "plugin:import/warnings",
    "plugin:import/typescript",
    "google",
    "plugin:@typescript-eslint/recommended",
  ],
  parser: "@typescript-eslint/parser",
  parserOptions: {
    project: ["./functions/tsconfig.json", "./functions/tsconfig.dev.json"],
    sourceType: "module",
  },
  ignorePatterns: [
    "/lib/**/*", // Ignore built files.
  ],
  plugins: ["@typescript-eslint", "import"],
  rules: {
    "object-curly-spacing": "never",
    "require-jsdoc": [
      "error",
      {
        require: {
          FunctionDeclaration: false,
          MethodDefinition: false,
          ClassDeclaration: false,
          ArrowFunctionExpression: false,
          FunctionExpression: false,
        },
      },
    ],
    quotes: ["error", "double"],
    "import/no-unresolved": 0,
  },
};
```
</details>

<details>
<summary>tsconfig.json</summary>

```json
{
  "$schema": "https://json.schemastore.org/tsconfig",
  "compilerOptions": {
    "module": "commonjs",
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "outDir": "lib",
    "sourceMap": true,
    "strict": true,
    "target": "es2017"
  },
  "compileOnSave": true,
  "include": ["src"]
}
```
</details>

<details>
<summary>tsconfig.dev.json</summary>

```json
{
  "$schema": "https://json.schemastore.org/tsconfig",
  "compilerOptions": {
    "module": "commonjs",
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "outDir": "lib",
    "sourceMap": true,
    "strict": true,
    "target": "es2017"
  },
  "compileOnSave": true,
  "include": ["src"]
}
```
</details>

Firebase admin and functions are then imported like this:

```ts
import * as admin from 'firebase-admin';
import { initializeApp } from 'firebase-admin/app';
import * as firebase_functions from 'firebase-functions';
import { rest } from './rest';

initializeApp();
const firestoreDb = admin.firestore();
firestoreDb.settings({ timestampsInSnapshots: true });

export const api = firebase_functions
  .runWith({
    timeoutSeconds: 60,
    memory: "512MB",
  })
  .https.onRequest(rest(firestoreDb));

```
