### ISSUE TITLE
firebase serve --only functions Cannot start emulator grpc_node.node

### ISSUE THREAD

**Issue by pablo-gonzalez** [firebase/firebase-tools#531]
### Version info

CLI Version:   3.14.0
Platform:      linux
Node Version:  v7.10.0

### Steps to reproduce

Running `firebase serve --only functions`

I get this error:

> ⚠  functions: Cannot start emulator. Error: The module '/usr/lib/node_modules/firebase-tools/node_modules/grpc/src/node/extension_binary/grpc_node.node'
> was compiled against a different Node.js version using
> NODE_MODULE_VERSION 48. This version of Node.js requires
> NODE_MODULE_VERSION 51. Please try re-compiling or re-installing
> the module (for instance, using `npm rebuild` or`npm install`).

### Expected behavior

Start emulator normally

### Actual behavior

Not able to start emulator.
I have tried:
1. `npm uninstall grpc` and then re-install
2. `npm rebuild grpc`.

**Output of npm rebuild grpc**
```
> grpc@1.7.1 install /home/pablo/projects/fpt-pwa/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

[grpc] Success: "/home/pablo/projects/fpt-pwa/node_modules/grpc/src/node/extension_binary/node-v51-linux-x64/grpc_node.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
grpc@1.7.1 /home/pablo/projects/fpt-pwa/node_modules/grpc

```

3. Remove node_modules inside functions directory and then `npm install`.
4. Uninstall and re-install firebase-tools.

No success.

**Comment by pablo-gonzalez** [comment]
This was fixed uninstalling heroku client which has his own node version and reinstalling nodejs.
There was a conflict on my Ubuntu 64 bits system.

Sorry for the incovenience.

**Comment by agatheblues** [comment]
For those who do not have an Heroku client but stumbled upon this error, here's how I solved it:
Go to `C:\Users\username\AppData\Roaming\npm\node_modules\firebase-tools\` and run `npm rebuild --update-binary` from there. Also be mindful that you need node version `6.11.1` installed!
