### ISSUE TITLE
`user.customClaims` property in the `beforeSignIn` blocking function is a string in the emulator instead of an object

### ISSUE THREAD

**Issue by DibyodyutiMondal** [firebase/firebase-tools#5327]
Assume that we have 2 functions
1. `beforeCreate`: sets a persistent claim
2. `beforeSignIn`: Checks for the claim set in `beforeCreate` in order to do some work

```typescript

 export const bugRepro = {
  beforeCreate: cloud.functions.auth.user().beforeCreate(async () => {
    return {
      customClaims: {
        someClaim: true
      }
    }
  }),
  beforeSignIn: cloud.functions.auth.user().beforeSignIn(async (user) => {
    console.debug(typeof user.customClaims);
    // typescript tells me that `user.customClaims` is supposed to be `Record<string, any> | undefined`
    // But the output for the above statement is
    // 'string' in emulator  <= emulator is working, but type is incorrect
    // 'object' in production (cloud run)

    // Expectation: simple access
    // const myClaim = user.customClaims?.['someClaim'];

    // Reality:
    // must pre-process custom claims
    const customClaims =
      environment.development ?
        user.customClaims ? JSON.parse(user.customClaims as any) : null :
        user.customClaims;

    const myClaim = customClaims?.['someClaim'];

    // While not related to this issue, but I'd like to ask:
    // When I was debugging and iterating over the live functions, I noticed
    // the following line of code will throw an error for brand new users
    // with the error 'code: 'auth/user-not-found'.
    // I assume that the user is not saved in firebase auth at this point yet,
    // rather it waits for the `beforeSignIn` blocking function as well.
    // Is this intended behaviour or a bug?
    await getAuth().getUser(user.uid)

    // ...
  })
}
```

### [REQUIRED] Environment info

**firebase-tools:**
11.17.0
**Platform:** 
Local: Ubuntu on WSL2 on Windows 11
Production: Cloud Run

**Comment by lisajian** [comment]
Hey @DibyodyutiMondal, thanks for filing this issue - I'll open a PR to address `typeof user.customClaims` shortly. As for the comment above `await getAuth().getUser(user.uid)`, did you get the error in production or when running against the auth emulator?

**Comment by DibyodyutiMondal** [comment]
@lisajian 

> did you get the error in production or when running against the auth emulator?

 it definitely was in production. To be honest, it's become a bit hazy to memory after such a long time. But in that comment, I've mentioned specifically that it was live cloud functions, and I trust that. 

I don't remember it being a problem in the emulator. Or maybe I didn't check? My thought process at the time was: "if it's not proper in production, what's the point of checking the emulator?".

(Me thinks, I was being lazy since testing in production means deploying after every small change, so I didn't check the emulator. Sorry for that)

**Comment by lisajian** [comment]
@DibyodyutiMondal All good, no worries! This is in line with what I'd expect as well. In production, it should throw an error at that point and your assumption in the comments is correct. However, the emulator suite would not throw an error - it makes two separate writes for user creation and sign in, so the user ID would be present at the time of sign in. This was done intentionally as a means to simplify the emulator logic, and we accepted that this would cause a divergence between production and emulator environment. If that is causing any issues for you, feel free to request a feature change / bug for that. Thanks!
