### ISSUE TITLE
functions predeploy/postdeploy do not work when contains `=`

### ISSUE THREAD

**Issue by aaharu** [firebase/firebase-tools#5339]
### [REQUIRED] Environment info

**firebase-tools:** 11.18.0

**Platform:** macOS

### [REQUIRED] Test case

```jsonc
// firebase.json
{
  "functions": {
    "predeploy": "npm run build --workspace=packages/foobar",  // NG
    // "predeploy": "npm run build --workspace packages/foobar", // OK
    // "predeploy": "npm run build --workspace\\=packages/foobar", // OK
    // "predeploy": "npm run build -w packages/foobar", // OK
    // "predeploy": "npm --prefix \"$RESOURCE_DIR\" run build", // OK
    "source": "packages/foobar"
  }
}
```

```
$ firebase deploy --only functions

=== Deploying to '---'...

i  deploying functions
Running command: npm run build --workspace=packages/foobar
✔  functions: Finished running predeploy script.
```

It outputs `Finished running predeploy script.`, but the predeploy was not running.
This behavior seems to be caused by `cross-env-shell`.

### [REQUIRED] Steps to reproduce

Add predeploy script that contains `=` to firebase.json.

### [REQUIRED] Expected behavior

The predeploy and postdeploy scripts have finished running.

**Comment by taeold** [comment]
@aaharu Thanks for bringing this to our attention. I wasn't aware of that limitation in `cross-env` package.

https://github.com/kentcdodds/cross-env/issues/24
6
Looks like `cross-env` package is depreacted, and the work needed to fix this bug might amount to - "rewrite cross-env" :(. Frankly, that isn't something I can prioritize on, but if we see that many users are having similar problem we'll definitely put this work in higher priority queue.

**Comment by AvaPL** [comment]
It's still an issue in 2026 :( @taeold Is there any chance till will be addressed?
