### ISSUE TITLE
Firebase hosting is not honoring rewrite rules specified in firebase.json

### ISSUE THREAD

**Issue by nareshbhatia** [firebase/firebase-tools#534]
I'd like a request for `logo.svg` to be served by `/logo.svg` but everything else by `/index.html` (single page app). I have specified the rewrite rules for this as follows:

```
"rewrites": [
  {
    "source": "logo.svg",
    "destination": "/logo.svg"
  },
  {
    "source": "**",
    "destination": "/index.html"
  }
]
```

However pointing to `/logo.svg` gives a 404 from my app. So the first rewrite rule is not being honored.

**Comment by mbleigh** [comment]
Exact matches for static content always have priority over rewrites -- if
you remove the first rule and have a logo.svg in your public directory when
you deploy that should be all you need to do. Please point us to a deployed
URL if you are seeing otherwise so we can take a look.

Cheers,
Michael

**Comment by nareshbhatia** [comment]
Hi @mbleigh, thanks for the quick response. I tried your suggestion. It works if I use the firebase domain name, but doesn't with our real domain name. You can try here:

1. https://slidesup-website.firebaseapp.com/logo.svg - this works
2. https://slidesup.com/logo.svg - this doesn't

Please help.

**Comment by mbleigh** [comment]
Might be a caching issue with your browser? Both URLs work for me

**Comment by nareshbhatia** [comment]
You are right! It was a caching issue. Thanks so much for your help.
