### ISSUE TITLE
Updating vulnerable dependencies

### ISSUE THREAD

**Issue by ZvozdaB** [firebase/firebase-tools#5343]
firebase-tools 11.18.0 contains 2 vulnerable dependencies.

High - qs vulnerable to Prototype Pollution 
More info  - https://github.com/advisories/GHSA-hrpp-h998-j3pp

Moderate - Got allows a redirect to a UNIX socket  
 More info - https://github.com/advisories/GHSA-pfrx-2q88-qq97

**Comment by jamesxabregas** [comment]
The UNIX socket redirect issue has been reported months ago. Could this be fixed soon?

**Comment by bkendall** [comment]
`qs` can be addressed, looks like that dependency is able to be updated.

`got` is a dependency of (ultimately) `update-notifier` which is unable to be updated to `v6` because the package switches to be an ES module, which this tool cannot import.

We should be able to triage this; or, PRs are always welcome.

**Comment by jamesxabregas** [comment]
> `got` is a dependency of (ultimately) `update-notifier` which is unable to be updated to `v6` because the package switches to be an ES module, which this tool cannot import.

Why can't this package import an ES module?

**Comment by bkendall** [comment]
short version: firebase-tools is a CommonJS module, which is unable to import (via `require`) ES modules.

Source: https://nodejs.org/api/esm.html#interoperability-with-commonjs

**Comment by jamesxabregas** [comment]
Would switching to [`update-notifier-cjs`](https://www.npmjs.com/package/update-notifier-cjs) solve the issue?

**Comment by bkendall** [comment]
Yes, quite possibly that could work! I think we'd have to make the switch
in `firebase-tools` and `superstatic`, but that seems like a viable
alternative.

**Comment by buu700** [comment]
How about just using a dynamic import?

```diff
11c11
< const updateNotifierPkg = require("update-notifier");
---
> const updateNotifierPkgPromise = import("update-notifier");
14c14,16
< const updateNotifier = updateNotifierPkg({ pkg });
---
> const updateNotifierPromise = updateNotifierPkgPromise.then((updateNotifierPkg) =>
>     updateNotifierPkg({ pkg })
> );
81c83
< process.on("exit", (code) => {
---
> process.on("exit", async (code) => {
107a110
>         const updateNotifier = await updateNotifierPromise;
```

**Comment by bkendall** [comment]
Unfortunately that doesn't work because Typescript replaces the dynamic importing when it transpiles (I did look into this, and it didn't quite work).

I do have a PR out to address the update-notifier bit.
