### ISSUE TITLE
Unable to use result of defineString in runWith config

### ISSUE THREAD

**Issue by RYFN** [firebase/firebase-tools#5347]
### [REQUIRED] Environment info

**firebase-tools:** 11.18.0

**Platform:** macOS

### [REQUIRED] Test case

Params docs https://firebase.google.com/docs/functions/config-env#params state 

> // To use configured parameters inside the config for a function, provide them 
> // directly. To use them at runtime, call .value() on them.

However, attempting to use this in a typescript deployment of a function;

```
import { defineString } from 'firebase-functions/params';
...
const vpcConnector = defineString('MY_VPC');

export const someFunction = functions
    .region('europe-west2')
    .runWith({
        vpcConnector: vpcConnector,
        vpcConnectorEgressSettings: 'ALL_TRAFFIC'
    })
    .https.onCall(async (data, context) => {
          ...
``` 

Leads to TS error `Type 'StringParam' is not assignable to type 'string | ResetValue | undefined'. Type 'Param<string>' is not assignable to type 'ResetValue'.`

I can `vpcConnector: vpcConnector.value()` but from the docs, this seems like an incorrect approach?

![Screenshot 2022-12-19 at 12 17 59](https://user-images.githubusercontent.com/2254840/208424485-8672ab36-de5e-489c-b2f8-93fcf8f5dba7.png)

### [REQUIRED] Steps to reproduce

See example above.

### [REQUIRED] Expected behavior

Use variables created from `defineString` in runtime config in TS function

### [REQUIRED] Actual behavior

Types won't allow return value of defineString to be used in runtime config.

**Comment by Berlioz** [comment]
Seems like we forgot to update the type definition of VpcConnector in the options structs. https://github.com/firebase/firebase-functions/pull/1329 should fix it.

**Comment by RYFN** [comment]
The above fix is working great for VpcConnector! Thank you.

An extension to this, when using defineString in region, workaround of casting `as any` works, but is undesirable. 

![Screenshot 2023-02-13 at 15 43 56](https://user-images.githubusercontent.com/2254840/218504158-68048fb5-d485-453b-ab89-63691d8b2636.png)

Would you like me to raise this as a separate issue?

**Comment by joehan** [comment]
@RYFN Yep, please raise a separate issue for that. I'm gonna close this one since it appears to be fixed.
