### ISSUE TITLE
Document codebase usage in firebase deploy --only functions:codebase

### ISSUE THREAD

**Issue by devth** [firebase/firebase-tools#5350]
The cli help output should include how to use the [codebase feature](https://firebase.google.com/docs/functions/organize-functions#organize_functions_in_codebases) for filtering:
https://github.com/firebase/firebase-tools/blob/86a5ba1472e4cb3bfda00450326efdce705d102f/src/commands/deploy.ts#L54-L58

It's also unclear if both codebase and groups can be used to provide more granular filtering.

**Comment by christhompsongoogle** [comment]
Thanks devth, if you're willing to improve the documentation I'd be happy to approve a PR. Assigned to Berlioz in the meantime to take a look.

**Comment by devth** [comment]
Sure, I'm willing to improve it! First, I need to understand how it actually works 😂 I'll try to dig in.

**Comment by aalej** [comment]
It looks the documentation for codebase usage in `firebase deploy --only functions` was added in #7542. The combination for deploying a function in a codebase would look something like:
```
--only functions:<codebase_name>:<function_name>
```
or
```
--only functions:<codebase_name>:<group_name>.<function_name>
```

That said, I'm going to go ahead and close this. If you think this is a mistake, feel free to ask this to be reopened. Thanks!
