### ISSUE TITLE
Getting EPROTO error when trying to upload a file with Cloud Storage emulator

### ISSUE THREAD

**Issue by erwannb-pro** [firebase/firebase-tools#5356]
### [REQUIRED] Environment info

**firebase-tools:** 10.9.2

**Platform:** Ubuntu

### [REQUIRED] Test case

When starting the firebase emulator and setting up the Cloud Storage part everything is fine, but when I'm trying to upload a file to the local storage I get an error saying : 

`FetchError: request to https://firebase-emulator:50090/upload/storage/v1/b/my-bucket/o?name=file.txt&uploadType=resumable failed, reason: write EPROTO 140587632953280:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:`

Note that i'm using the firebase emulator in a docker container and with a nodeJS stack with @google-cloud/storage:6.8.0 version.
Feel free to ask if you need some other informations on any other version number you need.

### [REQUIRED] Steps to reproduce

Install Firebase 10.9.2

use storage.rules file : 

```
rules_version = '2';
service firebase.storage {
  match /b/{bucket}/o {
    match /{allPaths=**} {
      allow read, write;
    }
  }
}
```

with firebase.json config (ports & ips are for our environment) : 

```
{
    "firestore": {
        "rules": "firestore.rules",
        "indexes": "firestore.indexes.json"
    },
    "storage": {
        "rules": "storage.rules"
    },
    "emulators": {
        "firestore": {
            "host": "0.0.0.0",
            "port": 50080
        },
        "pubsub": {
            "host": "0.0.0.0",
            "port": 50085
        },
        "ui": {
            "enabled": true,
            "host": "0.0.0.0",
            "port": 50000
        },
        "storage": {
            "host": "0.0.0.0",
            "port": 50090
        }
    }
}
```

Add the following environment variable (here we use the docker container name, but can be any uri) : 

`STORAGE_EMULATOR_HOST=firebase-emulator:50090`

And try a code like this in your js file : 

```
import {Storage} from '@google-cloud/storage';

const storage = new Storage({projectId: example-id});
await storage.bucket(bucketName).upload(filePath);
```

### [REQUIRED] Expected behavior

It should upload the file on the bucket at the root path of it.

### [REQUIRED] Actual behavior

Upload nothing and throw this error : 

```
FetchError: request to https://firebase-emulator:50090/upload/storage/v1/b/my-bucket/o?name=file.txt&uploadType=resumable failed, reason: write EPROTO 140587632953280:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
```

Edit : Could be useful, we use a debian@11.0.0 image with java@16.0.2 installed for our docker. It could be a problem with that.

**Comment by tonyjhuang** [comment]
Does this help? https://stackoverflow.com/questions/61916754/error-in-postman-error-write-eproto-8768error1408f10bssl-routinesssl3-get

**Comment by erwannb-pro** [comment]
Hi Tony,

I wanted to try this solution but I have a problem when doing it in our code.

From the Emulator UI, the upload works perfectly fine and indeed, it calls the local storage with HTTP (example of a call that have been made from the UI : http://127.0.0.1:50090/v0/b/my-bucket/o?name=file.txt


But when using the Google Storage NodeJS library I don't see a way to tell it to call in HTTP and not in HTTPS. Do you know how to force calls to be made in HTTP only or am I out of luck on this one ?

**Comment by Zujaj** [comment]
Changing the environment variable from `process.env.STORAGE_EMULATOR_HOST = 'localhost:9199'` to `process.env.STORAGE_EMULATOR_HOST = 'http://localhost:9199'` worked for me as well. Thanks, @tonyjhuang & @erwannb-pro, I was facing the same problem with Firebase 12.4.7.
