### ISSUE TITLE
Firebase functions emulator re-loads functions again and again every 10-15 seconds, even though there are no changes

### ISSUE THREAD

**Issue by sivaneshl** [firebase/firebase-tools#5361]
### [REQUIRED] Environment info

**firebase-tools:** 11.1.0

**Platform:** Windows10

### [REQUIRED] Test case

Firebase functions emulator keeps on reloading functions again and again even though there are no changes. I get the 
```+  functions: Loaded functions definitions from source: function1, function2, function3, function4...``` 
message on the console every 10-15 seconds.  With 50+ functions, I am not able to look for actual logs from the functions, as these messages are bombing all over the console. 
I am starting the emulator for functions only.
```firebase emulators:start --only functions```

I don't know what is causing the changes to load the functions again and again. I have added the log files to the firebase.json `ignore` configuration. 
```
  "functions": {
    "predeploy": [
      "npm --prefix \"$RESOURCE_DIR\" run lint"
    ],
    "ignore": [
      "node_modules",
      ".git",
      "firebase-debug.log",
      "firebase-debug.*.log",
      "*.log"
    ]
  },
  ```

### [REQUIRED] Steps to reproduce

Start the emulator for cloud functions using ```firebase emulators:start --only functions```

### [REQUIRED] Expected behavior

Functions should reload only if there are changes to the source

### [REQUIRED] Actual behavior

Functions reload again and again every 10-15secs even though there are no changes. 

![image](https://user-images.githubusercontent.com/3358933/209203660-090340b7-ff09-4bd4-9208-cb9ab4bd72ca.png)

**Comment by taeold** [comment]
Hi @sivaneshl. Can you run the emulator with `--debug` flag (e.g. `firebase emulators:start --debug`)?

You should see log entries like `File ${filePath} changed, reloading triggers` that indicates which file is changing.

**Comment by sivaneshl** [comment]
@taeold It actually says that the yml file we have for api gateway config is being changed, but there are no changes as such. 
In fact, I have provided the file to be ignored for the functions emulator, still it reloads again and again. 

```
"functions": {
    "predeploy": [
      "npm --prefix \"$RESOURCE_DIR\" run lint"
    ],
    "ignore": [
      "node_modules",
      ".git",
      "firebase-debug.log",
      "firebase-debug.*.log",
      "*.log",
      "swagger-*.yml",
      "src\\docs\\swagger-*.yml"
    ]
  }
  ```

**Comment by taeold** [comment]
@sivaneshl Internally, we use [chokidar](https://github.com/paulmillr/chokidar) to watch for file changes:

https://github.com/firebase/firebase-tools/blob/86a5ba1472e4cb3bfda00450326efdce705d102f/src/emulator/functionsEmulator.ts#L400-L407

I'm not sure what's happening in your setup, but `chokidar` seems to be noticing changes in your file system. Possibly a bug in chokidar - would be interesting to see if you can find the root issue in the library we are using.

I also notice that Functions Emulator doesn't consider the ignore files today. That's a very good feature request, though I can't promise we will get working on it right away.

Let me know if I can provide more info on how filesystem updates work. I'm curious to learn why chokidar is thinking that your yaml file is constantly changing 🤔

**Comment by sivaneshl** [comment]
Agreed. We have a process that constructs the `swagger-{env}.yml` file based on the environment you select during `firebase use {env}`. But it will update the file, only if there are any changes in the  main `swagger.yml` file. In this case, there are no changes. I did even compared white spaces and it seems fine. Thank you for looking into it. I will see if I can find anything from the `chokidar` library.
