### ISSUE TITLE
Upgrade to node 18 fails for authentication emulator

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [firebase/firebase-tools#5367]
### [REQUIRED] Environment info

**firebase-tools:**
11.16.1

Windows 10

**Platform:**

### [REQUIRED] Test case
Upgrading node from v16.14.2 to the latest 18.12.1 seems to give an issue with programmatically getting to the authentication emulator. We get:
![image](https://user-images.githubusercontent.com/1098243/209460952-de127ab6-4a87-45a8-a6d7-30e6c0c8ea0c.png)
FirebaseAppError: Error while making request: connect ECONNREFUSED ::1:9095. Error code: ECONNREFUSED
    at C:\lander\devprojects\acro-companion\e2e-testing\node_modules\firebase-admin\lib\utils\api-request.js:178:19
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Populator.addUser (file:///C:/lander/devprojects/acro-companion/e2e-testing/utils/populator.ts:1:2302)
    at BootPopulator.doPopulate (file:///C:/lander/devprojects/acro-companion/e2e-testing/utils/boot-populator.ts:1:539)
    at asyncMain (file:///C:/lander/devprojects/acro-companion/e2e-testing/utils/boot-populator.ts:1:880) {
  errorInfo: {
    code: 'app/network-error',
    message: 'Error while making request: connect ECONNREFUSED ::1:9095. Error code: ECONNREFUSED'
  },
  codePrefix: 'app'
}

This is when we use a firebase-admin node instance to create test users through the authentication emulator running on port 9095
re-installing v16.14.2 solves the issue

**Comment by taeold** [comment]
Can you describe your setup? How are you connecting to the Auth Emulator (are you manually setting up the environment variable?)

FYI Node 18 changed the way "localhost" gets resolved and will prefer ipv6. Your auth emulator instance may be connecting to ipv4 instead.

**Comment by LanderBeeuwsaert** [comment]
Hi @taeold , ah that's already interesting about the ipv6, however we just use localhost to connect so I suppose that should work the same?

So when running the emulator, we start a node.js process that does this:
![image](https://user-images.githubusercontent.com/1098243/209949003-3ae6d145-bff0-4e7b-9e0c-477dbf6b73ac.png)
with the databaseURL pointing to our remote firebase test environment.

Is there something we need/can configure somewhere to make the auth emulator instance connect to ipv6? (or as a first step can we check somewhere if it's connecting to ipv4 or ipv6?)

**Comment by taeold** [comment]
@LanderBeeuwsaert IIUC Firebase Emulators will spin up and connect to ipv4 instead.

Can you try replacing `localhost` with `127.0.0.1` in your `process.env` variables and let us know if that helps?

**Comment by LanderBeeuwsaert** [comment]
Hi all, yes this solved it thanks!
