### ISSUE TITLE
Storage Emulator Security Rules: Use of ternary operator not allowed

### ISSUE THREAD

**Issue by dbc-dev** [firebase/firebase-tools#5370]
### [REQUIRED] Environment info

**firebase-tools:**
11.19.0

**Platform:**
macOS

### [REQUIRED] Test case

Using ternary operators inside the storage.rules file outputs a warning. A [similar](https://github.com/firebase/firebase-tools/issues/2066) issue was reported and fixed 2 years ago for Firestore rules.

### [REQUIRED] Steps to reproduce

1. In the storage.rules file write any ternary expression (e.g `allow read: if true ? true : false;`)
2. Run Storage Emulator `firebase emulators:start`

### [REQUIRED] Expected behavior

According to the [documentation](https://firebase.google.com/docs/rules/rules-language#building_conditions) the ternary operator is allowed for both Cloud Firestore & Cloud Storage.

### [REQUIRED] Actual behavior
⚠  Use of ternary operator not allowed in (...)/storage.rules:(line)

**Comment by dalgarins** [comment]
right now the linter in the firebase console is disabled is related with this issue?
