### ISSUE TITLE
Extensions with scheduled triggers not supported. PR created ✔

### ISSUE THREAD

**Issue by stfsy** [firebase/firebase-tools#5374]
### [REQUIRED] Environment info

**firebase-tools:** 11.19.0

**Platform:** Windows

### [REQUIRED] Test case
There is a new unit test case in #5373 

### [REQUIRED] Steps to reproduce

- Use a Windows machine
- Install firebase-tools
- Install firestore-counter extension
- Start the emulator
- Logs say that function controllerCore was ignored because of an unknown trigger

### [REQUIRED] Expected behavior
Extensions with scheduled trigger are also supported by the emulator.

### [REQUIRED] Actual behavior
Extensions with scheduled trigger are also supported by Emulator. 

The `triggerHelper` module defines which triggers are supported. The scheduleTrigger is currently not handled and therefore not supported. 

https://github.com/firebase/firebase-tools/blob/86a5ba1472e4cb3bfda00450326efdce705d102f/src/extensions/emulator/triggerHelper.ts#L33-L47

To be able to use extensions like `firebase-counter` in the emulator and without modifications we need support for scheduleTriggers. I created PR #5373 which converst the scheduleTrigger to a pubSub trigger which in turn can be triggered by writing to the pubsub topic.

**Comment by stfsy** [comment]
@polarby i saw you are also using the counter extension in the emulator. Thought you might be interested as well

**Comment by polarby** [comment]
If you need to run functions with a low frequency (once every hour/day..) you can usually run those functions manually. Tasks that require high-frequency emulation, will be much more challenging to handle and probably requires support for scheduled functions from the firebase team.

### Low-frequency functions (manual emulation)
Run the terminal in your project directory 
```
$  firebase functions:shell
```
It will show all your callable functions, including your scheduled ones. Simply run those by calling them:
```
yourScheduledFunc();
```

**Comment by stfsy** [comment]
@polarby thank you. Appreciate it. 

In this case the controllerCore function is not even recognized as a callable function by the emulator. It is completey ignored because of the unknown trigger and therefore does not get loaded/instantiated at all 😞

**Comment by polarby** [comment]
Yeah, that sure is a Problem. A workaround for now (and not too time-consuming) is for sure to copy-paste the source code of those emulated functions and then run them. But let's keep this issue open for the implementation of this essential feature!

**Comment by stfsy** [comment]
Would it make sense to merge my PR in the mean time? Its not very invasive and at least enables the emulator to parse and instantiate the function, so that It can be triggered from the parent application without copying the source code.

**Comment by joehan** [comment]
Thanks for the contribution! Closing this since you fixed it.
