### ISSUE TITLE
debug.log error

### ISSUE THREAD

**Issue by muhammadzahir14** [firebase/firebase-tools#5382]
### [REQUIRED] Environment info

**firebase-tools:**

**Platform:**

### [REQUIRED] Actual behavior

[firebase-debug.log](https://github.com/firebase/firebase-tools/files/10327003/firebase-debug.log)
[database-debug.log](https://github.com/firebase/firebase-tools/files/10327005/database-debug.log)

**Comment by aalej** [comment]
Hi, this issue seems to be a duplicate of [#5381](https://github.com/firebase/firebase-tools/issues/5381). I'll be closing this for now.
