### ISSUE TITLE
crashlytics:symbols:upload does not work on MacOS

### ISSUE THREAD

**Issue by hopkins-joseph** [firebase/firebase-tools#5383]
Run this command:
`firebase crashlytics:symbols:upload --app 1:559634585778:android:598689cc660f9499 BB_2_03_14_15-2.3.14-v2031402.symbols    `

Get ERROR:
```
i  Generating symbols for BB_2_03_14_15-2.3.14-v2031402.symbols
⚠  An unknown error occurred

Error: java command failed with args: -jar,/Users/josephhopkins/.cache/firebase/crashlytics/buildtools/crashlytics-buildtools-2.9.2.jar,-symbolGenerator,breakpad,-symbolFileCacheDir,/var/folders/pt/84r66vz96fl_w6znskr83w900000gn/T/crashlytics-4eee6e96-aea1-4042-a47e-23082d22d9d5/nativeSymbols/1-559634585778-android-598689cc660f9499/breakpad,-verbose,-generateNativeSymbols,-unstrippedLibrary,BB_2_03_14_15-2.3.14-v2031402.symbols,-clientName,firebase-cli;crashlytics-buildtools
```

**Comment by aalej** [comment]
Hi @hopkins-joseph, I understand that you are having an issue with the Firebase Crashlytics upload symbols command. Could you file another ticket and provide us with more details such as the version of Firebase Tools you’re using, and filling out the required template as this will help in our investigation. With that, I’ll be closing this for now.
