### ISSUE TITLE
npm workspaces support broken since 11.19.0

### ISSUE THREAD

**Issue by mpsq** [firebase/firebase-tools#5385]
Firebase CLI is broken since https://github.com/firebase/firebase-tools/pull/5215 when using `npm` workspaces. (11.18.0 works fine)

### Environment info

- firebase-tools `11.19.0`
- npm `8.18`
- node 16
- npm workspaces
- Archlinux

### Steps to reproduce

Any `firebase` cli command with npm workspaces set up

### Expected behavior

Command should succeed

### Actual behavior

Errors (not sure the 1st is relevant):

```
Could not find functions.yaml. Must use http discovery
Error: spawn ./node_modules/.bin/firebase-functions ENOENT
```

**Comment by mpsq** [comment]
The issue seems to be that https://github.com/firebase/firebase-tools/blob/master/src/deploy/functions/runtimes/node/index.ts#L111, `this.sourceDir` references the module and not the root (where `node_modules` is)

**Comment by joehan** [comment]
@taeold Seems like this may be related to https://github.com/firebase/firebase-tools/issues/4952?

**Comment by taeold** [comment]
Thanks @joehan. Closing in favor of https://github.com/firebase/firebase-tools/issues/4952
