### ISSUE TITLE
V2 function deployments failing

### ISSUE THREAD

**Issue by milo-** [firebase/firebase-tools#5395]
### [REQUIRED] Environment info

**firebase-tools:** 11.19.0

**Platform:**
macOS

### [REQUIRED] Test case

Try and deploy a v2 function

### [REQUIRED] Steps to reproduce

Deploy a v2 function

### [REQUIRED] Expected behavior

Deployment succeeds

### [REQUIRED] Actual behavior

Error: The following Cloud Functions V2 regions are currently unreachable:
	europe-west1

This looks like it might be a GCP wide issue, not just firebase as our v2 functions are failing to load in the console too with the error: Missing Functions from 3 regions: europe-west2, us-central1, europe-west1

**Comment by Berlioz** [comment]
I believe you're correct in that this was a GCP issue affecting gen 2 functions--the timing matches up with an incident report (https://status.cloud.google.com/incidents/SQXFKiCS8wTZ7Qbm516f). We don't anticipate a repeat.
