### ISSUE TITLE
silent the progress log

### ISSUE THREAD

**Issue by rolandjitsu** [firebase/firebase-tools#54]
Is there a way to silent the progress log when the deploy is happening? It just looks very weird when I use it on Travis.

**Comment by robertdimarco** [comment]
@rolandjitsu There is not currently an option for this, but we'd happily accept a PR!

**Comment by robertdimarco** [comment]
Also, how does it appear in Travis? What problem are you running in to?

**Comment by rolandjitsu** [comment]
@robertdimarco it looks something like [this](https://travis-ci.org/rolandjitsu/ng2-play).

**Comment by drtriumph** [comment]
I think this should be fixed in [v2.0.0](https://github.com/firebase/firebase-tools/releases/tag/v2.0.0). Please reopen if it is still an issue
