### ISSUE TITLE
Failed / load function definition source / generate manifest / [ERR_PACKAGE_PATH_NOT_EXPORTED]

### ISSUE THREAD

**Issue by kwhjvdkamp** [firebase/firebase-tools#5401]
Complete error message: 
!!  functions: Failed to load function definition from source: FirebaseError: Failed to load function definition from source: Failed to generate manifest from function source: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in C:\GitHubRepositories\Consult-Koen\functions\node_modules\firebase\package.json   See screenshot 1 !!

Searched on key '[ERR_PACKAGE_PATH_NOT_EXPORTED]'. One issuey (already closed) popped up! A possible cause was mentioned why this error has been risen. Solution should be something to imporove package (which one ?) and/or tsconfig.ts. Possibly, instead of using  commonjs, an 'es'-module should be used, but I do not see (understand) why my error does have something to do with node-fetch v3+ e.d.

Try to be as consice as possible. 

First noticed this message after upgrading to angular 15 (from 14). I do have to solve an issue about @keyframes but that does not have anything to do with this trouble (if it is trouble, I'm not sure, at least it seems so it distract me from my main path). At the functions part I do have several commands which I use to upload data to my cloud firestore. These commands all working fine, able to upload (update) data. However after deploying everthing I receive on the terminal there is an error in 'index.js' which I do NOT have in index.ts. In case this functionality in 'index.ts' 'does not work', I should not be able to upload data to the cloud firestore, simply because in that case I should receive a 'permission denied (err 7)', however, I AM ABLE to upload data to my firestore!!
                                         									 
Something is wrong transpiling (compiling) 'index.js' from 'index.ts'. but I don't how to fix?

I do notice the error message at the functions-part when trying to fetch remote data back into my local bucket for proper development. I also have notice this error message when I performed a complete deploy. This last error evelates now in something wrong in index.js (which I do NOT have) in index.ts (because I able to upload data). The error about index.js appeared when doing 'firebase deploy'. 

Back to the functions-part, as said, trying to renew my local bucket with data which has been uploaded to my firestore db, I am using a two steps procedure. On step 2 calling 'firebase emulators:start --import ./seed' the error is written (output), see screenshot 1. 

Opening the emulator page simply to check if fetched data is visible, it seems that data is fetched from the cloud into my local bucket, despite some other  noticeable UX problems on that emulators webpage, which I didn't noticed before. See screenshot 3: trouble (UX) on emulator web page compared to page on the firebase console.

Environment and other required info: Windows 11, Visual Studio Code, Github for desktop. Versions: See screenshot 2

Output firebase-tools: See screenshot 1
Versions: See screenshot 2
Output command 'firebase deploy': screenshot 3
Screenshot 4

As said, it is possible, it has something to do with using 'commonjs', as other-one said transform to using es-module. 
Q: How to transfor to es-modules, any appropriate instruction is welcome, thanks ahead!
                                									 
Trial-Error testing: Something is wrong transpiling (compiling) 'index.js' from 'index.ts'. but I don't how to fix?

![Emulator_problem](https://user-images.githubusercontent.com/9660415/210981680-37e13ef4-88ca-467e-b355-ca70a4badfb1.png)
![Version](https://user-images.githubusercontent.com/9660415/210981668-f2e7e1f4-da31-477b-bbe9-a6b995ccd03e.png)
![Emulator_problem_3](https://user-images.githubusercontent.com/9660415/210981673-e347530d-1806-4800-83eb-bbb2a6b9c5bf.png)
![Firebase_Trouble](https://user-images.githubusercontent.com/9660415/210981678-491cb340-777e-4395-a381-2c9e62cc0ec7.png)
![output-deploy_problem](https://user-images.githubusercontent.com/9660415/211003212-588e1cf4-64ec-48b5-8b8d-e491529c8167.png)
![screenshot 3](https://user-images.githubusercontent.com/9660415/211003217-6f3d7ec1-28cf-4f58-8cb6-9e6ed1026ba0.png)

**Comment by russellwheatley** [comment]
Hey @kwhjvdkamp - do you mind providing steps to reproduce this with a code sample, please? Thanks.
