### ISSUE TITLE
unable to install firebase CL on MacBook Pro M2

### ISSUE THREAD

**Issue by grapesfrog** [firebase/firebase-tools#5403]
### [REQUIRED] Environment info

Trying to install latest version

**firebase-tools:**

macOS 
M2  Chio 

### [REQUIRED] Test case

Tried installing firebase CL using : curl -sL https://firebase.tools | bash
Error occured:
-- Checking for existing firebase-tools on PATH...
-- Checking your machine type...
-- Downloading binary from https://firebase.tools/bin/macos/latest
######################################################################## 100.0%#=#=#                                           ######################################################################## 100.0%
-- Setting permissions on binary...
bash: line 255: /usr/local/bin/firebase: Bad CPU type in executable
Something went wrong, firebase has not been installed.
Please file a bug with your system information on Github.
https://github.com/firebase/firebase-tools/
-- All done!

Then tried installing using: curl -sL https://firebase.tools | upgrade=true bash
Still failed to install got error:
-- Checking for existing firebase-tools on PATH...
bash: line 169: /usr/local/bin/firebase: Bad CPU type in executable
-- Your machine has a corrupted firebase-tools binary, attempting upgrade...
-- Checking your machine type...
-- Downloading binary from https://firebase.tools/bin/macos/latest
######################################################################## 100.0%#=#=#                                           ######################################################################## 100.0%
-- Setting permissions on binary...
bash: line 255: /usr/local/bin/firebase: Bad CPU type in executable
Something went wrong, firebase has not been installed.
Please file a bug with your system information on Github.

curl -sL https://firebase.tools | bash

### [REQUIRED] Expected behavior
Firebase tools to be installed 

### [REQUIRED] Actual behavior
Firebase tools install

**Comment by grapesfrog** [comment]
issue resolved by installing rosetta

**Comment by vdshko** [comment]
For those who are facing this issue again (like me now with Apple Silicon M3), here are the steps to fix it (in Terminal):

1. Install Firebase CLI: `brew install firebase-cli`
2. Log in to Firebase: `firebase login`
2.1 Log in via the web (you will be automatically switched to your browser).

If you need to log in and have a token, then the command in step 2) must be: `firebase login:ci`

That's it!
