### ISSUE TITLE
Next JS deployment with internationalisation support is serving only the locale routes but not the root route. How can I fix this?

### ISSUE THREAD

**Issue by sanesanyo** [firebase/firebase-tools#5406]
### [REQUIRED] Environment info

firebase-tools: 11.14.3

Platform: Windows 10

### [REQUIRED] Test case

When I run the app on local host, the root route is served but when I deploy the app on Firebase using the experimental NextJS hosting, only the locale routes are served but not the root. Thus when I enter the root domain, I get an error.

### [REQUIRED] Steps to reproduce

Just deploy an internationalised app using next-translate and you will see the issue.

### [REQUIRED] Expected behavior

Expected behaviour is the same as the local host i.e. root routes are served as well as locale routes.

### [REQUIRED] Actual behavior

Only locale routes are served & no root routes available.

**Comment by sanesanyo** [comment]
I am seriously getting fed up with these issues. First it took me so much time to even get the Next JS deployed as I had to debug so many errors. I even have a separate thread for it where pretty much no one from Firebase responded. How is this possible? Are you not supposed to be developer friendly??

**Comment by TheIronDev** [comment]
@sanesanyo Thanks for opening up this issue!

Do you have a build step required (like running `next build`) ?
Do you have a repo we could look at?

**Comment by sanesanyo** [comment]
@TheIronDev  For running locally, I run: npm run dev or firebase serve. For deploying on Firebase: firebase deploy after initialising the experimental feature (just like mentioned in the documentation). I am assuming when I run: firebase deploy, the build process is running automatically. I am not sending any explicit command for the build. Unfortunately, my repo is private thus cannot share but may be I can share with you the config files or anything that is necessary. Like I said, everything just works as expected locally but on deployment the root routes do not work. My feeling is that only locale routes are created as I cannot find any index.html file in the root of hosting folder and like I already mentioned, I have no control over the build.

**Comment by jamesdaniels** [comment]
NextJS i18n is now supported.

**Comment by jamesdaniels** [comment]
@mrjackyliang it should be `en_us` per Firebase i18n support https://firebase.google.com/docs/hosting/i18n-rewrites

**Comment by mrjackyliang** [comment]
> @mrjackyliang it should be `en_us` per Firebase i18n support https://firebase.google.com/docs/hosting/i18n-rewrites

That didn't work either. Had to use `en` instead. Odd, because in Next.js, their standard was en-US.
