### ISSUE TITLE
An unknown error while generating symbols.zip 

### ISSUE THREAD

**Issue by SonaT-H** [firebase/firebase-tools#5411]
Hello! Could you help me with this problem?
I was trying to make my Crashlytics more readable, so I did everything like in this documentation
https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports?platform=unity

Then after this command
firebase crashlytics:symbols:upload --app=FIREBASE_APP_ID PATH/TO/SYMBOLS
I'm getting this message:

i  Generating symbols for Users/candywings/Desktop/symbols.zip
⚠️  An unknown error occurred

Error: java command failed with args: -jar,/Users/candywings/.cache/firebase/crashlytics/buildtools/crashlytics-buildtools-2.9.2.jar,-symbolGenerator,breakpad,-symbolFileCacheDir,/var/folders/cz/pvb_p_bd38b7jbm0g09gyplc0000gp/T/crashlytics-740996b9-861e-4290-aceb-d686ccdbd42c/nativeSymbols/1-259280956191-android-75e36a5847975b2516de2a/breakpad,-verbose,-generateNativeSymbols,-unstrippedLibrary,Users/candywings/Desktop/symbols.zip,-clientName,firebase-cli;crashlytics-buildtools

Want to notice that the app id and the path are correct.

**Comment by bkendall** [comment]
@SonaT-H - can you verify that you have `java` installed on your machine? running `java --version` would be sufficient (and share the output, please).

**Comment by SonaT-H** [comment]
@bkendall Thank you so much for your answer! I don't know how, but Java was not installed on my machine. Now it works!
