### ISSUE TITLE
Error: Failed to get Firebase project undefined

### ISSUE THREAD

**Issue by haode333** [firebase/firebase-tools#5415]
### [REQUIRED] Environment info

```
[debug] [2023-01-12T04:55:23.454Z] CLI Version:   11.20.0
[debug] [2023-01-12T04:55:23.454Z] Platform:      win32
[debug] [2023-01-12T04:55:23.454Z] Node Version:  v19.3.0
```

**firebase-tools:** 11.20.0

**Platform:** win32

### [REQUIRED] Test case

N/A

### [REQUIRED] Steps to reproduce

1. install with npm
2. run ```firebase login```
3. run ```firebase init```
4. run ```firebase deploy```

### [REQUIRED] Expected behavior

Successfully deploy

### [REQUIRED] Actual behavior

[debug] [2023-01-12T04:55:23.451Z] ----------------------------------------------------------------------
[debug] [2023-01-12T04:55:23.453Z] Command:       C:\Users\---\scoop\apps\nodejs\current\node.exe C:\Users\---\scoop\apps\nodejs\current\bin\node_modules\firebase-tools\lib\bin\firebase.js deploy
[debug] [2023-01-12T04:55:23.454Z] CLI Version:   11.20.0
[debug] [2023-01-12T04:55:23.454Z] Platform:      win32
[debug] [2023-01-12T04:55:23.454Z] Node Version:  v19.3.0
[debug] [2023-01-12T04:55:23.454Z] Time:          Wed Jan 11 2023 22:55:23 GMT-0600 (北美中部标准时间)
[debug] [2023-01-12T04:55:23.454Z] ----------------------------------------------------------------------
[debug] 
[debug] [2023-01-12T04:55:23.507Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/undefined [none]
[debug] [2023-01-12T04:55:23.746Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects/undefined 403
[debug] [2023-01-12T04:55:23.746Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects/undefined {"error":{"code":403,"message":"The caller does not have permission","status":"PERMISSION_DENIED"}}
[debug] [2023-01-12T04:55:23.747Z] HTTP Error: 403, The caller does not have permission
[debug] [2023-01-12T04:55:23.748Z] FirebaseError: HTTP Error: 403, The caller does not have permission
    at responseToError (C:\Users\---\scoop\persist\nodejs\bin\node_modules\firebase-tools\lib\responseToError.js:49:12)
    at RetryOperation._fn (C:\Users\---\scoop\persist\nodejs\bin\node_modules\firebase-tools\lib\apiv2.js:288:77)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[error] 
[error] Error: Failed to get Firebase project undefined. Please make sure the project exists and your account has permission to access it.

**Comment by aalej** [comment]
Hi @haode333, looking at the debug logs you provided, the issue might be with permissions. Could you try logging out using `firebase logout` then logging in using `firebase login`. You could also try `firebase login --no-localhost` or `firebase login --reauth`.

After doing so, could you try running `firebase deploy --debug` again and provide us with the output debug logs? Also, could you check if there is any typo inside your `.firebaserc` file?

**Comment by haode333** [comment]
Hi @aalej ,

I believe it's not recognizing the correct project name. 
If you look at the last line of log it recognizes the project as "undefined" and trying to access https://firebase.googleapis.com/v1beta1/projects/undefined which obviously I don't have permission of.

**Comment by aalej** [comment]
Hi @haode333, I did notice that the project you’re trying to access was `undefined`. I was unable to replicate the issue when I tried following the steps you provided. However, I tried modifying some files and noticed that a similar error message was displayed if there were any typos or if there was no project specified inside the `.firebaserc` file.

I don’t think that you manually modified the `.firebaserc` file, but just to make sure, could you let me know if there is any typo? The `.firebaserc` file should look like this:

```
{
 "projects": {
   "default": "<project_id>"
 }
}
```

It would also be helpful if you could let us know the output of running `firebase use` in the directory where you initialized Firebase. This should list all currently defined aliases in your project directory.

**Comment by haode333** [comment]
Hi @aalej ,

Sorry for the late reply. The problem is with that I have multiple aliases and none is currently used.
Below is my ```firebase use``` result
```
No project is currently active, and no aliases have been created..

Project aliases for D:\Github\haode333\xxxx:

  default (project_id_1)
  secondary (project_id_2)
  v2 (project_id_3)

Run firebase use --add to define a new project alias.
```
If I do ```firebase use default``` I'm able to run ```firebase deploy``` without problem.

However I would expect firebase to be smart enough to list the aliases instead of trying to deploy to ```undefined```.

**Comment by aalej** [comment]
Hi @haode333, thanks for letting us know the cause of the issue and that you are able to run `firebase deploy` after selecting a project.

I tried to replicate the issue again without manually modifying the `.firebaserc` file. When I tried this again, a prompt was shown stating that I did not have a currently active project.

The steps I took to were:

1. run `firebase init` (I selected Firestore. Please let me know if you selected any other services)
2. run `firebase use --add` to add other project aliases
3. run `firebase use --clear`. This was the only way I can remove the currently active project
4. run `firebase deploy`

The output of running `firebase deploy` was:

```
Error: No project active, but project aliases are available.

Run firebase use <alias> with one of these options:

  default (<project_id_1>)
  staging (<project_id_2>)
```

I’m guessing that I may have missed something here; could you let me know which Firebase features you selected and if I am missing anything from the steps to reproduce the issue?

**Comment by haode333** [comment]
I feel it's because I reinstalled Windows. Is there any telemetry data used by firebase that's, for example, in AppData?

**Comment by mellowcello77** [comment]
I am experiencing the same issue when trying to deploy with `firebase deploy --token "$FIREBASE_TOKEN"` on CodeMagic
I get the token when using Firebase login:ci, but keep getting the same error:

Error: Failed to get Firebase project undefined. Please make sure the project exists and your account has permission to access it.

**Comment by aalej** [comment]
Hi @haode333, sorry for the delay, I tried different scenarios to replicate the issue. I was able to reproduce the same error message by trying to deploy hosting when there is no active project. Just to verify, could you let me know if you are deploying to hosting?

Seems like the cause of the error was the call to this method [getFirebaseProject](https://github.com/firebase/firebase-tools/blob/master/src/management/projects.ts#L430) in this [line](https://github.com/firebase/firebase-tools/blob/e8a59e64d85dee0273e58e1bc5eb86860e5f660d/src/getDefaultHostingSite.ts#L10). 

The steps I took were similar to before, but I selected `hosting`:

1. run `firebase init` ( select Hosting )
2. run `firebase use --add` to add other project aliases
3. run `firebase use --clear`
4. run `firebase deploy`

@mellowcello77, I understand that you’re also experiencing the same issue. Just to verify, could you let us know if there is currently an active project to deploy to by running `firebase use`?

**Comment by mellowcello77** [comment]
Hi @aalej - thank you for your message. 

I do have active projects when I run firebase use yes:

```
wesley@MacBook-Pro smartmatter_app % firebase use
Active Project: sm (smartmatterapp)

Project aliases for /Users/wesley/Code/smartmatter_app:

  default (smartmatter-dev)
  sm-dev (smartmatter-dev)
  sm-stage (smartmatter-stage)
* sm (smartmatterapp)
```

**Comment by aalej** [comment]
Hi @mellowcello77, thanks for verifying. Seems like something odd is happening in your case. I tried to replicate your issue, but I am unable to reproduce the same error message if there is an active project.

Given that the cause of the original issue of this ticket was that there was no active project, and that you encountered the error even when there is an active project, it’s possible that the cause of your issue is different. I would recommend filing a new ticket; this way, we can avoid confusion and it would be more efficient in identifying the cause of the issue.

**Comment by haode333** [comment]
> Hi @haode333, sorry for the delay, I tried different scenarios to replicate the issue. I was able to reproduce the same error message by trying to deploy hosting when there is no active project. Just to verify, could you let me know if you are deploying to hosting?
> 
> Seems like the cause of the error was the call to this method [getFirebaseProject](https://github.com/firebase/firebase-tools/blob/master/src/management/projects.ts#L430) in this [line](https://github.com/firebase/firebase-tools/blob/e8a59e64d85dee0273e58e1bc5eb86860e5f660d/src/getDefaultHostingSite.ts#L10).
> 
> The steps I took were similar to before, but I selected `hosting`:
> 
> 1. run `firebase init` ( select Hosting )
> 2. run `firebase use --add` to add other project aliases
> 3. run `firebase use --clear`
> 4. run `firebase deploy`


sorry for the delay. Yes I'm deploying to hosting.

**Comment by aalej** [comment]
Thanks for the verification @[haode333](https://github.com/haode333). #5483 should catch errors and output a message listing the available aliases when attempting to deploy without a project.
