### ISSUE TITLE
"An unexpected error occured" NextJS 13

### ISSUE THREAD

**Issue by leo-paz** [firebase/firebase-tools#5421]
### Environment info

**firebase-tools:** have tried v11.14.2 -> v11.20.0
**Node:** have tried with v16.2 and v18

**Platform:** macOS M1 Monterey 12.6 

### Test case

run `npx firebase deploy`

### Steps to reproduce

Running `npx firebase deploy` in a NextJS 13 project with new app directory structure.

### Expected behavior

For it to build and deploy my next app using the new app directory structure

### Actual behavior

I receive a `Error: An unexpected error has occurred.` message after my next app is built with no link to a firebase.debug.log.

Just wondering if anyone can point me in a right direction? I got a firebase.debug.log output once but cannot consistently get a file output again so i'm a little lost.

**Comment by TheIronDev** [comment]
Hi @aalej , thanks for opening up a bug!

Have you been able to deploy at all, or has it always been stuck?
Does running this locally work?
Does it work with `firebase emulators:start`?

Thank you!
Tyler

**Comment by leo-paz** [comment]
@TheIronDev I'm assuming you meant to tag me and yes on firebase emulators:start, hosting did work.

![image](https://user-images.githubusercontent.com/26093865/212780344-910b07b7-8e90-4ab5-9e2f-4fa26af0dd10.png)

**Comment by hodeyp** [comment]
I'm having the same issue trying to release a nextjs 13 app. I have checked the debug logs and it is failing here...


```
1:61082232775:web:d7229cd6d1b3e25c0a9be2/config 200
[debug] [2023-01-23T11:38:02.745Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects/-/webApps/

XXXXXXXXX/config {"projectId":"xxxxxxxxxxxxx","appId":"1:61082232775:web:d7229cd6d1b3e25c0a9be2","databaseURL":"https://xxxxxxxxxxxxx-default-rtdb.europe-west1.firebasedatabase.app","storageBucket":"xxxxxxxxxxxxx.appspot.com","locationId":"europe-west","apiKey":"XXXXXXXXX","authDomain":"xxxxxxxxxxxxx.firebaseapp.com","messagingSenderId":"61082232775","measurementId":"XXXXXXXXXX"}
[debug] [2023-01-23T11:38:20.192Z] SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at ɵcodegenFunctionsDirectory (/usr/local/lib/node_modules/firebase-tools/lib/frameworks/next/index.js:218:37)
    at async prepareFrameworks (/usr/local/lib/node_modules/firebase-tools/lib/frameworks/index.js:305:84)
    at async deploy (/usr/local/lib/node_modules/firebase-tools/lib/deploy/index.js:53:13)
[error] 
[error] Error: An unexpected error has occurred.
```

**Comment by leo-paz** [comment]
@hodeyp where do you get to see these logs?

**Comment by hodeyp** [comment]
@leo-paz if you look at the folder you ran the script from there are a bunch of `[XXX]-debug.log` files. All the info is in there.

**Comment by leo-paz** [comment]
I found that the firebase cli is looking for this file that simply doesn't exist
```
[debug] [2023-01-31T01:03:46.469Z] Error: ENOENT: no such file or directory, open '/Users/leopaz/dev/outlit/Core/outlit/apps/blog/.next/routes-manifest.json'
```

I configured it like mentioned in the nextjs 13 integration docs:
```
hosting: [
    {
      "target": "blog",
      "source": "outlit/apps/blog"
    }
]
```

**Comment by leo-paz** [comment]
I finally got it to deploy by changing my next.config.mjs to include:
```
const nextConfig = {
  distDir: '.next',
}
```

I think they forgot to have the firebase cli read the distDir and so it defaults to looking in .next

**Comment by alekseykarpenko** [comment]
+1 
I have the same issue on my migrated project, falling at deploy:
```
[2023-02-11T16:03:31.321Z] SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at ɵcodegenFunctionsDirectory (/Users/ak/.nvm/versions/node/v16.19.0/lib/node_modules/firebase-tools/lib/frameworks/next/index.js:220:37)
    at async prepareFrameworks (/Users/ak/.nvm/versions/node/v16.19.0/lib/node_modules/firebase-tools/lib/frameworks/index.js:306:84)
    at async deploy (/Users/ak/.nvm/versions/node/v16.19.0/lib/node_modules/firebase-tools/lib/deploy/index.js:53:13)
```
@leo-paz 's solution didn't help me with that
It seems it fails on this line: https://github.com/firebase/firebase-tools/blob/master/src/frameworks/next/index.ts#L354

While `npm ls --omit=dev --all --json` in the root directory shows up some *ESPROBLEMS* errors (but still returning a valid JSON I suppose)

Also, by using my fresh test project that has been deployed successfully before, I discovered that the problem may be related to npm peer dependency conflict, as I simply installed some outdated plugin that requires older version of react under the hood 🤷‍♂️

**Comment by borisyordanov** [comment]
I have the same problem. The `npm ls` command succeeds locally. The same app can be deployed on Vercel or Netlify without an issue.

![cWHQ3o0TxC](https://user-images.githubusercontent.com/12392666/221128810-55ab496b-a1fa-46e2-909b-d1e1ef5efee9.png)

**Comment by jilherme** [comment]
Downgrading next `13.3.1` to `13.2.4` fixed for me.

**Comment by lukasnevosad** [comment]
Having (probably) the same issue. In my case the log ends with
```
[2023-05-05T09:56:31.549Z] Error: ENOENT: no such file or directory, open '/Users/lukasnevosad/Projects/Yomio/scholis/web/.next/server/client-reference-manifest.js'

Error: An unexpected error has occurred.
```

Strange thing is that the file it claims it cannot open actually exists:
```
web git:(master) ls -al /Users/lukasnevosad/Projects/Yomio/scholis/web/.next/server/
total 376
drwxr-xr-x  17 lukasnevosad  staff    544 May  5 11:58 .
drwxr-xr-x  11 lukasnevosad  staff    352 May  5 11:58 ..
-rw-r--r--   1 lukasnevosad  staff      2 May  5 11:58 app-paths-manifest.json
-rw-r--r--   1 lukasnevosad  staff  66395 May  5 11:58 client-reference-manifest.js
-rw-r--r--   1 lukasnevosad  staff  66375 May  5 11:58 client-reference-manifest.json
-rw-r--r--   1 lukasnevosad  staff     66 May  5 11:58 flight-server-css-manifest.js
-rw-r--r--   1 lukasnevosad  staff     42 May  5 11:58 flight-server-css-manifest.json
-rw-r--r--   1 lukasnevosad  staff    567 May  5 11:58 middleware-build-manifest.js
-rw-r--r--   1 lukasnevosad  staff     83 May  5 11:58 middleware-manifest.json
-rw-r--r--   1 lukasnevosad  staff     33 May  5 11:58 middleware-react-loadable-manifest.js
-rw-r--r--   1 lukasnevosad  staff    120 May  5 11:58 next-font-manifest.js
-rw-r--r--   1 lukasnevosad  staff     94 May  5 11:58 next-font-manifest.json
drwxr-xr-x   5 lukasnevosad  staff    160 May  5 11:58 pages
-rw-r--r--   1 lukasnevosad  staff    100 May  5 11:58 pages-manifest.json
-rw-r--r--   1 lukasnevosad  staff     57 May  5 11:58 server-reference-manifest.js
-rw-r--r--   1 lukasnevosad  staff     30 May  5 11:58 server-reference-manifest.json
-rw-r--r--   1 lukasnevosad  staff   5217 May  5 11:58 webpack-runtime.js
```

**Comment by randytsao24** [comment]
@lukasnevosad I was running into the same issue, upgrading (in my case) to `13.2.4` seemed to have done the trick. Hope that works for you.

**Comment by lukasnevosad** [comment]
> @lukasnevosad I was running into the same issue, upgrading (in my case) to `13.2.4` seemed to have done the trick. Hope that works for you.

Yes, I confirm 13.2.4 works

**Comment by christhompsongoogle** [comment]
Thanks all for confirming 13.2.4 is working.
