### ISSUE TITLE
Firebase Funcitons Cloud Firestore Trigger Deploy ERROR!

### ISSUE THREAD

**Issue by jakkph** [firebase/firebase-tools#5428]
**This is my code** 

`const functions = require("firebase-functions");`
`const region = "asia-southeast1";`
`const admin = require("firebase-admin");`

`admin.initializeApp();`

`exports.makeOrder = functions.region(region).firestore.document("receipts/{receiptId}")`
  `.onCreate((snapshot, context) => {`
  `  const newValue = snapshot.data();`

   ` console.log(newValue);`

  `});`

**After try many times to deploy , i always got this ERROR**
`Failed to configure trigger event-type:providers/cloud.firestore/eventTypes/document.create resource:projects/XXXXX/databases/(default)/documents/receipts/{receiptId} service:firestore.googleapis.com`

`Functions deploy had errors with the following functions:
        makeOrder(asia-southeast1)
i  functions: cleaning up build files...`

`Error: There was an error deploying functions`

**Comment by FortySL** [comment]
same problem here, and it comes with all 4 methods

**Comment by morizyun** [comment]
same problem. Please tell me how to solve it.

**Comment by cuihanggit** [comment]
same problem, can not add new Trigger.

**Comment by Thaanu2001** [comment]
Try adding `/` before the document reference worked for me.


Try this -
```
exports.makeOrder = functions.region(region).firestore.document("/receipts/{receiptId}")
.onCreate((snapshot, context) => {
  const newValue = snapshot.data();

 console.log(newValue);

});
```

**Comment by jakkph** [comment]
> It works now, looks like the bug has been fixed.

YESSSSS, it's deploy complete now...smooth as silk  😊😊
