### ISSUE TITLE
Errors not propagated from child processes

### ISSUE THREAD

**Issue by doowb** [firebase/firebase-tools#543]
### Version info

3.15.0

### Steps to reproduce

Try to use a function name with dashes:

```js
module.exports['foo-bar'] = functions.https.onRequest((req, res) => res.send('hi'));
```

Run the following deployment command:

```sh
firebase deploy --only functions
```

### Expected behavior

I expected to get the error thrown from the [extractTriggers](https://github.com/firebase/firebase-tools/blob/master/lib/extractTriggers.js#L13) code.

### Actual behavior

I got the generic "Error deploying functions" error.

Even though I fixed my function name and no longer get the error, I wanted to bring it up to see if there's a better way to expose the actual error.

**Comment by tinaliang** [comment]
Thanks for letting us know! We've fixed the error in https://github.com/firebase/firebase-tools/pull/603.
