### ISSUE TITLE
11.20.0 firestore filter UI unusable due to improper zindexing

### ISSUE THREAD

**Issue by evelant** [firebase/firebase-tools#5431]
![image](https://user-images.githubusercontent.com/858965/212733285-cd6ba029-b24e-469e-aa2b-5988ed2b749f.png)
^ the filter UI is "behind" the rest of the UI and therefore unusable. This is likely a one line fix. Happens in chrome. In safari the element shows up on top but is not clickable, clicks pass through to underlying view.

### [REQUIRED] Environment info

**firebase-tools: 11.20.0** 

**Platform: macOS**

### [REQUIRED] Test case

Start emulators, navigate to firestore UI, click on filter button, observe that z-indexing is broken and the UI is unusable becuase it goes behind the UI

### [REQUIRED] Steps to reproduce

1. Start emulators
2. Navigate to firestore tab
3. Click the filter button

### [REQUIRED] Expected behavior

The UI should be usable

### [REQUIRED] Actual behavior
The UI is unusable because of a zindex bug

N/A

**Comment by aalej** [comment]
Hi @evelant, thanks for the information you provided, and for reporting this. It looks like the the issue with the Firestore Emulator filter/query UI has been addressed in [#5399](https://github.com/firebase/firebase-tools/issues/5399), and a fix has been created. With this, I’ll be closing this ticket as a duplicate.

For now, I can only recommend downgrading to `firebase-tools v11.19.0` while waiting for the fix to be released. Thank you for your patience and apologies for the inconvenience this may have caused.
