### ISSUE TITLE
Firestore emulator does not reload rules, even though it indicates it does.

### ISSUE THREAD

**Issue by Turburlar** [firebase/firebase-tools#5432]
### [REQUIRED] Environment info

**firebase-tools:**11.20.0

**Platform:**Ubuntu: 22.04

### [REQUIRED] Test case

```
match /myCol/{id} {
          allow read: if true;
          allow write: if false;
        }
```

### [REQUIRED] Steps to reproduce

1. Create a rule on a document with a value of false for read.
```
match /myCol/{id} {
          allow read: if false;
          allow write: if false;
        }
```
2. Start the firestore emulator:
`firebase emulators:start --import .firebase-export --export-on-exit`

3. Read the document with a client, then in the Firestore emulator UI, observe request, and it highlights the line where the permission failure occured.

4. Update the rules to true.
```
match /myCol/{id} {
          allow read: if true;
          allow write: if false;
        }
```

5. Read the document with a client, then in the Firestore emulator UI, and observe the request. It will show a failed request and still highlight the changes lines as failing with false.

### [REQUIRED] Expected behavior

The rules will be updated like the emulator out states they are.

### [REQUIRED] Actual behavior

The rules are not updated.

**Comment by christhompsongoogle** [comment]
Hi Turburlar, for clarification - does the second request succeed but the UI is incorrect? or does the second request fail also? We were able to reproduce the UI issue but not a Firestore issue.

**Comment by Turburlar** [comment]
The second request fails as if the value is still false.

**Comment by dionisiatara** [comment]
Hello! I was wondering if there's any update on this? I am currently on the latest version (v11.24.0) and it's still happening on my end. Thanks!

**Comment by loolooii** [comment]
I'm experiencing this problem as well. My rules in the request tab are still the old rules, so I can't verify whether my rules are correct and that's the main purpose of using an emulator.

**Comment by christhompsongoogle** [comment]
The latest version of the emulator suite should resolve this issue. Please retest and let me know if you're still experiencing this issue.

**Comment by swabbiedotdev** [comment]
Still occurring with firebase-tools 14.18.0 and nextjs 15.5.0

To isolate:
1. Completely cleared all caches: ~/.cache/firebase, ~/.config/firebase, ~/Library/Preferences/firebase
2. Deleted local caches: .firebase, .next, node_modules
3. Fresh emulator start with verified latest firestore.rules
4. Fresh browser session (incognito mode, cleared site data)
5. Redownloaded emulator jar files

Emulator works for first operation after fresh start. Nextjs fast refresh triggers firestore reconnection, and emulator immediately serves stale cached rules. Error references old rules with get() calls that were removed from firestore.rules many versions ago

Emulator is unusable with nextjs dev mode due to constant hot refresh reconnections. Only workaround is switching to a production firebase for development

**Comment by brettpoulin** [comment]
With Next.js 15.5.7 and firebase-tools 15.0.0 I run some queries on my "development" database (not default) and see the "firestore.development.rules" rules in the Request tab as I would expect, then change the rules...
and it says 

i  firestore: Change detected, updating rules...
✔  firestore: Rules updated.

but when I run some queries again it shows the old rules in the request tab, just as before. 

If I restart the emulator after changing the rules, the rules change as I would expect. 

When I just use the default database, the rules are applied as expected (almost). 
In fact, I find that the rules that should have only applied to the "development" database are applied to the "default" database as well. 

It may be that my setup of the emulator is not correct in the firebase.json ...

```
{
  "functions": [
    {
      "source": "functions",
      "codebase": "default",
      "firestore":"development",
      "ignore": [
        "node_modules",
        ".git",
        "firebase-debug.log",
        "firebase-debug.*.log",
        "*.local"
      ],
      "predeploy": ["npm --prefix \"$RESOURCE_DIR\" run lint"]
    }
  ],
  "firestore": [
    {
      "database": "development",
      "rules": "firestore.development.rules",
      "indexes": "firestore.development.indexes.json"
    }
  ],
  "emulators": {
    "apphosting": {
      "port": 5002,
      "rootDirectory": "../starter-2/",
      "startCommand": "npm run dev"
    },
    "functions": {
      "database": "development",
      "port": 5001
    },
    "firestore": {
      "port": 8080,
      "databases": [
        {
          "database": "development",
          "rules": "firestore.development.rules",
          "indexes": "firestore.development.indexes.json"
        }
      ]
    },
    "ui": {
      "enabled": true
    },
    "singleProjectMode": false,
    "auth": {
      "port": 9099
    }
  }
}

```
