### ISSUE TITLE
Firestore rules debug() function fails to log list result of query, and its derived functions.

### ISSUE THREAD

**Issue by Turburlar** [firebase/firebase-tools#5436]
**firebase-tools:** 11.20.0

**Platform:** Ubuntu 22.04

### Test case

```
function getGroups() {
      return debug(get(/databases/$(database)/documents/userdata1/$(request.auth.token.infoId)/infos/$(request.auth.token.group)).data.groups);
    }

```

### Steps to reproduce

1. create a firestore rules function that queries some array data.
2. Wrap the query in a debug() call.
3. Run the rules with the Firestore Emulator.
4. Observe that there is nothing printed in the firestore-debug.log.
5. Create a subsequent function based on the initial function. Observe that all functions composed of the initial function do not write to the log either.

### [REQUIRED] Expected behavior

Log the value.

### [REQUIRED] Actual behavior

Does not log the value.

**Comment by christhompsongoogle** [comment]
Hi Turburlar, please include the full rules file for debugging.
