### ISSUE TITLE
Feature request: ability to run Firebase functions from the command line

### ISSUE THREAD

**Issue by bcattle** [firebase/firebase-tools#544]
Hey, it would be really useful to be able to run your actual production Firebase functions from the command line. My thought would be to add a command `functions:run` to the CLI interface. This could take args or not. This functionality would be similar to [`aws lambda invoke`](http://docs.aws.amazon.com/cli/latest/reference/lambda/invoke.html).

**Comment by laurenzlong** [comment]
That's a great idea! We use Github issues to keep track of bugs, and use https://firebase.google.com/support/contact/bugs-features/ to keep track of feature requests typically. Could you file the request there so it can be tracked appropriately?

**Comment by bcattle** [comment]
Sure, I will thanks.
