### ISSUE TITLE
Version 11.21.0 breaks firebase deploy functions compatibility with pnpm 

### ISSUE THREAD

**Issue by YannicEl** [firebase/firebase-tools#5448]
### [REQUIRED] Environment info

**firebase-tools:** 11.21.0

**Platform:** Windows 11

**Node:** 18.13.0

### [REQUIRED] Test case

https://github.com/YannicEl/firebase_tools_pnpm_bug

### [REQUIRED] Steps to reproduce

1. Run `cd .\functions\`
2. Run `pnpm install`
3. Replace `<project_id>` in `./functions/package.json` with a valid project id that you have premission to deploy
4. Run `pnpm run deploy` this will deploy the function in `./functions/src` to the specified firebase project

### [REQUIRED] Expected behavior

One callable function named `handler` ist deployed to the firebase project.

### [REQUIRED] Actual behavior

The deploy fails with
In the console:
```
The system cannot find the path specified.
```
In the `firebase-debug.log`:
```
[debug] [2023-01-21T08:28:14.281Z] Error: spawn C:\Users\bamio\Desktop\firebase_tools_bug\node_modules\.pnpm\firebase-functions@4.2.0_firebase-admin@11.5.0\node_modules\.bin\firebase-functions ENOENT
    at notFoundError (C:\Users\bamio\Desktop\firebase_tools_bug\node_modules\.pnpm\cross-spawn@7.0.3\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (C:\Users\bamio\Desktop\firebase_tools_bug\node_modules\.pnpm\cross-spawn@7.0.3\node_modules\cross-spawn\lib\enoent.js:40:16)
    at cp.emit (C:\Users\bamio\Desktop\firebase_tools_bug\node_modules\.pnpm\cross-spawn@7.0.3\node_modules\cross-spawn\lib\enoent.js:27:25)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

When downgrading firebase-tools to the previous version `11.20.0` this works just fine. You can test this in the same repsoirtoy by running `pnpm install firebase-tools@11.20.0` in `./functions`

This might have somthing to do with #5391 but I am not entirly sure.

**Comment by evelant** [comment]
This also affects the emulators. If you use pnpm and try to start the emulators on `11.21.0` you get

```
....path_to_project..../node_modules/.pnpm/firebase-functions@4.2.0_firebase-admin@11.5.0/node_modules/.bin/firebase-functions ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

Error: An unexpected error has occurred.
```

Perhaps a test case needs to be added to check if all 3 major package managers (npm, pnpm, yarn) work correctly before releases go out?

**Comment by laurentpayot** [comment]
Confirmed. Cannot run emulators anymore with firebase-tools v11.21.0 and pnpm v7.25.1. I’m getting the same unexpected error as @evelant.

**Comment by tofsjonas** [comment]
Similar problem here, on MacBook M1 macOs Ventura, node 18.13.0, pnpm 7.26, using emulator
Error in console:

```
Error: An unexpected error has occurred.
```

In firebase.log:
```
[debug] [2023-01-25T21:34:24.652Z] Building nodejs source
[debug] [2023-01-25T21:34:24.653Z] Could not find functions.yaml. Must use http discovery
[debug] [2023-01-25T21:34:24.656Z] Error: spawn /Users/jonas/Programmering/wow/bakhjarl/functions/node_modules/.pnpm/firebase-functions@4.2.0_firebase-admin@11.5.0/node_modules/.bin/firebase-functions ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

No problems with 11.20 (Except that it ignores my `.env` file, but that is another matter)

**Comment by DibyodyutiMondal** [comment]
not just deploys, it also breaks emulator support. Current workaround for me is to run `npm install` inside the `dist` folder after output and before emulation or deploys.

**Comment by evelant** [comment]
@taeold Is there going to be a release for this? I'm blocked by it at the moment and can't roll back to an earlier version due to https://github.com/firebase/firebase-tools/issues/4952

**Comment by taeold** [comment]
@evelant Released today at v11.22.0!

**Comment by DibyodyutiMondal** [comment]
@taeold The emulator works fine now, but now can't resolve the Firebase Functions SDK

**Comment by ChromeQ** [comment]
@taeold Success! 🎉 I can successfully run the emulator and deploy WITHOUT having to install deps _inside_ the `functions` dir on v11.22.0.

Thank you so much for persevering and getting it fixed! 🙏
