### ISSUE TITLE
3.15.2 Deploy existing function revert back memory allocated and timeout settings to default values

### ISSUE THREAD

**Issue by yizhoucao** [firebase/firebase-tools#545]
### Version info

3.15.2

### Steps to reproduce

1. Deploy any function
2. In google cloud console, change the memory allocated and/or timeout
3. Deploy that same function again

### Expected behavior

By just updating existing function, the memory allocated and timeout settings that were changed in google cloud console should not be override back to the default value (256mb and 60 seconds). This is the behavior up until version 3.15.0

### Actual behavior

The memory allocated and timeout settings are now always overridden back to default value after every deploy, even though the deployment just update existing functions.

**Comment by laurenzlong** [comment]
Fix is released now is 3.15.3. Thanks for catching this!

**Comment by yizhoucao** [comment]
Thanks, all good now

**Comment by chrisleyva** [comment]
Using version 11.16.1, I am still having this issue.
