### ISSUE TITLE
Broken dependency: @apidevtools/json-schema-ref-parser

### ISSUE THREAD

**Issue by rcb4t2** [firebase/firebase-tools#5450]
The `@apidevtools/json-schema-ref-parser` dependency is broken, and prevents firebase-tools from being installed on Node version <17. Please note, this dependency is also being abandoned and a replacement should be found

https://github.com/APIDevTools/json-schema-ref-parser/issues/298

"Suggest pinning to the exact version 9.1.0 if you haven't already, until a 9.1.2 can be released."

### [REQUIRED] Environment info

**firebase-tools:** 11.20.0

**Platform:** Ubuntu

### [REQUIRED] Test case

on a system using Node <17:
```sh
yarn global add firebase-tools
```

### [REQUIRED] Steps to reproduce

On a system running Node version <17, install firebase-tools

### [REQUIRED] Expected behavior

firebase-tools will be installed successfully

### [REQUIRED] Actual behavior

installation fails due to broken dependency @apidevtools/json-schema-ref-parser
`error @apidevtools/json-schema-ref-parser@9.1.1: The engine "node" is incompatible with this module. Expected version ">= 17". Got "14.21.2"`

**Comment by breakingthebuild** [comment]
Seeing the same issue `error @apidevtools/json-schema-ref-parser@9.1.1: The engine "node" is incompatible with this module. Expected version ">= 17". Got "14.20.0"`

**Comment by costag1982** [comment]
I am seeing the exact same error

`error @apidevtools/json-schema-ref-parser@9.1.1: The engine "node" is incompatible with this module. Expected version ">= 17". Got "16.19.0"`

this was working before not sure if an update has caused this

**Comment by filiperochs** [comment]
I used the `npm install -g firebase-tools` as such from [https://firebase.google.com/docs/cli#windows-npm](https://firebase.google.com/docs/cli) and it worked for me.

**Comment by Bayaraa77** [comment]
is it resolved the error @filiperochs ?

**Comment by Bayaraa77** [comment]
i get it in my dockerfile but still not working

**Comment by filiperochs** [comment]
What is your node version?

**Comment by keehahaha** [comment]
> What is your node version?

"14.21.2"

**Comment by keehahaha** [comment]
I also can not upgrade the runtime to 17 too. How can I work around it ?

**Comment by keehahaha** [comment]
I find a solution --> You can use --> yarn install --ignore-engines --> to allows package authors to state which node engines are required for the package to work.

**Comment by code-valkyrie** [comment]
> yarn install --ignore-engines

Worked for me! Thankyou 🙂

**Comment by Bayaraa77** [comment]
@filiperochs my node version is 16.18.1

**Comment by kennethg-singlifeph** [comment]
> keehahaha

i try this but no luck on my end node version 14.18.3

**Comment by Bayaraa77** [comment]
yarn install --ignore-engines 

it is worked, thank you :)

**Comment by Psycarlo** [comment]
I get the same error

`The engine "node" is incompatible with this module. Expected version ">= 17". Got "16.19.0"`

Using in Github Actions

**Comment by geowalrus4gh** [comment]
seeing same issue 
error @apidevtools/json-schema-ref-parser@9.1.1: The engine "node" is incompatible with this module. Expected version ">= 17". Got "16.10.0"

**Comment by christhompsongoogle** [comment]
It's recommended to use npm to install firebase-tools that way we can say with certainty that using npm to install firebase-tools should be safe.

The folks who added the breaking change in the patch will need to fix it. We can technically put in a explicit dependency on an earlier version to fix it, but it's only a stop-gap

**Comment by ueda19850603** [comment]
It seems that cloud function deployment fails.


✔  functions: Finished running predeploy script.
i  functions: preparing codebase default for deployment
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
i  artifactregistry: ensuring required API artifactregistry.googleapis.com is enabled...
✔  functions: required API cloudbuild.googleapis.com is enabled
✔  artifactregistry: required API artifactregistry.googleapis.com is enabled
✔  functions: required API cloudfunctions.googleapis.com is enabled
⚠  functions: package.json indicates an outdated version of firebase-functions. Please upgrade using npm install --save firebase-functions@latest in your functions directory.
i  functions: preparing functions directory for uploading...
i  functions: packaged /Users/shinyaueda/git/nipo_plus/functions (4.68 MB) for uploading
i  functions: ensuring required API cloudscheduler.googleapis.com is enabled...
✔  functions: required API cloudscheduler.googleapis.com is enabled
✔  functions: functions folder uploaded successfully
i  functions: updating Node.js 16 function test(us-central1)...
Build failed: yarn install v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
error @apidevtools/json-schema-ref-parser@9.1.1: The engine "node" is incompatible with this module. Expected version ">= 17". Got "16.19.0"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error Found incompatible module.; Error ID: 12c8ef4a

Functions deploy had errors with the following functions:
        test(us-central1)
i  functions: cleaning up build files...

Error: There was an error deploying functions

**Comment by jamesmoschou** [comment]
v9.1.2 of @apidevtools/json-schema-ref-parser has been released, which reverts the breaking change. You should be able to upgrade to this using normal npm version to get it working again.

**Comment by sesam** [comment]
Rebuilding containers that depend on firebase-tools now works again also on the oldest LTS node version 14.

**Comment by bkendall** [comment]
Glad they were able to publish a new package (finally) without the breaking change. Seems like this has cleared up!

**Comment by rcb4t2** [comment]
Thanks all! Yes they fixed the broken package

https://github.com/APIDevTools/json-schema-ref-parser/issues/298#issuecomment-1403537259
