### ISSUE TITLE
Firebase CLI Can't Find Cloud Firestore Instance because Firebase Doesn't Set GCP Default Resource Location

### ISSUE THREAD

**Issue by sambshapiro** [firebase/firebase-tools#5452]
### Environment info

**firebase-tools: 11.21.0** 

**Platform: macOS**

### Test case

Initialize firestore in firebase CLI for a new project by runnning `firebase init firestore`.

### Steps to reproduce

1. Create a new Firebase project in the web console.
2. Create a fresh Firestore database.
3. Install/update firebase tools CLI on your Mac.
4. Log in to Firebase via the firebase tools CLI.
5. Run `firebase init firestore --debug` and when prompted, select the Firebase project you created in step 1.

### Expected behavior

Successful API request of:
`[2023-01-22T19:52:19.975Z] <<< [apiv2][body] GET https://appengine.googleapis.com/v1/apps/[app-name]`

Below, you can see the cause of the issue is that the default GCP resource location is not set. It would seem that the expected behavior would be for the console to force/prompt the user to choose a default GCP resource location with initial setup.

### Actual behavior

```
[2023-01-22T19:48:57.505Z] <<< [apiv2][body] GET https://appengine.googleapis.com/v1/apps/[app-name] {"error":{"code":404,"message":"App does not exist.","status":"NOT_FOUND"}}
[2023-01-22T19:48:57.505Z] error getting database typeHTTP Error: 404, App does not exist. {"name":"FirebaseError","children":[],"context":{"body":{"error":{"code":404,"message":"App does not exist.","status":"NOT_FOUND"}},"response":{"statusCode":404}},"exit":1,"message":"HTTP Error: 404, App does not exist.","status":404}
[2023-01-22T19:48:57.506Z] database_type: undefined

Error: It looks like you haven't used Cloud Firestore in this project before. Go to https://console.firebase.google.com/project/[app-name]/firestore to create your Cloud Firestore database.
```

### Temporary Solution
A solution has already been found in an off-topic (closed) issue here: https://github.com/firebase/firebase-tools/issues/4254

The solution (https://github.com/firebase/firebase-tools/issues/4254#issuecomment-1310619259):

1. Go to firebase web console.
2. Click project settings (gear icon on the left).
3. Select your project.
4. Set the default GCP resource location.

However, I'm filing the bug report because users will continue to have this issue and experience confusion as the CLI gives a non-descriptive error, and it would seem that the expected behavior would be for the console to force/prompt the user to choose a default GCP resource location with initial setup.

### Permanent Solution
Options include:
- Console prompting user to set the default GCP location when setting up the Firestore instance initially
- CLI giving more descriptive error, that GCP default resource location needs to be set in the console
- CLI automatically setting the default GCP resource location

**Comment by joehan** [comment]
Thanks for reporting this. `init firestore` was checking for a default resource location, because firestore used to require one. Now that it doesn't (and now that setting up a Firestore DB doesn't set DRL), this check was frequently failing for new projects.

Fixed by #5261
