### ISSUE TITLE
Unable to evaluate the expression as the maximum memory usage of 1000 has been reached. for 'create' 

### ISSUE THREAD

**Issue by evelant** [firebase/firebase-tools#5453]
### [REQUIRED] Environment info

**firebase-tools:** 11.19.0 (latest usable version, 11.20.0 has a bug with UI, 11.21.0 doesn't work with pnpm)

**Platform:** MacOS

### [REQUIRED] Test case

When working with a larger document rules fail with 

```
INFO: operation failed:
Unable to evaluate the expression as the maximum memory usage of 1000 has been reached. for 'create' @ L359
com.google.cloud.datastore.core.exception.DatastoreException:
```

It seems like security rules treat accessing `resource.data` as accessing _every single property of the document_. Otherwise there would be no way I can see that my simple rules would fail with the above error. 

Example rule:

```
function logChunkCreateRules() {
          let requestAuthUid = getRequestAuthUid();
          let requestResourceData = request.resource.data;

          return requestResourceData.get(["members", requestAuthUid, "userId"], null) == requestAuthUid;
}
```

How is it possible that this rule exceeds the 1000 property access limit? This seems like a bug. It's breaking my app in production.

### [REQUIRED] Steps to reproduce

Write a basic security rule such as the example above, run it again a large document, observe failure.

### [REQUIRED] Expected behavior

Security rules should not fail in an undefined, undocumented, manner.

### [REQUIRED] Actual behavior

Security rules fail when they should not.

**Comment by evelant** [comment]
I think I've managed to get a bit more clarity on what's happening here. The highlights are:

1. There is a 1mb document limit in firestore, well documented
2. You can access the document being updated in your security rules to validate conditions against the data
3. There is an _undocumented_ limit in security rules. As a document approaches or hits the 1mb Firestore data limit a security rule will crash _if it accesses any part of the document_ (`resource.data`). 

That undocumented limit has some really nasty side effects. Once you've run into it you're stuck -- the app can no longer update the data because the rules will always fail. That means the app cannot correct the problem even if you know what it is. 

Seemingly the only solution is to write a separate script that finds and modifies the offending data using the admin sdk to bypass security rules.

This has been a major source of frustration for my team _and for our customers_ who had to deal with a broken app while we worked to sniff out this undocumented limit/bug and work around it.

**Comment by christhompsongoogle** [comment]
Thanks evelant, we've filed a bug with the docs team to document the 1MB limit. In the meantime the 1MB limit is a limitation on Firestore itself in that we need to fetch the entire document. I'd recommend following up with Firebase Support to raise the issue there also: https://firebase.google.com/support.

**Comment by christhompsongoogle** [comment]
I've consulted with the team and this is what I found:

Firestore has a published limit of ~1MB for a document (see below)
https://firebase.google.com/docs/firestore/quotas#limits

What's happening here is that the rules language fetches the entire document, it exceeds this limit and fails before it can establish whether the access is allowed or not. You're correct that the client may not be able to resolve the problem, you may wish to use the admin SDK to bypass the security rules and adjust the document sizes.

In the future it may be possible for rules language to fetch individual fields of a document instead of the entire document using Firestore's query partitions but I don't have a timeline to share for this change.

**Comment by evelant** [comment]
@christhompsongoogle thanks for looking into it further. 

The thing I don't understand is that Firestore _can_ read or update a document when it's at the 1mb limit. Why can't security rules read that document when firestore clients can?

That's the issue that caused so much trouble for my team and my customers. The behavior of rules is effectively different than that of firestore clients. Since the rules fail _before_ any firestore client will fail it causes major disruptions. 

If this behavior is indeed intended (that is, firestore rules will fail to read docs even when firestore clients will not fail) then I think at the very least it needs to be thoroughly documented. I had what was effecively a multi-day outage in my app because of this behavior. 

IMO this behavior is incorrect and is effectively a bug. If anything firestore should reject writes _before_ documents get to a point where they're not longer readable by security rules. That would effective solve this problem and everything would work as documented.

**Comment by christhompsongoogle** [comment]
Update: 

We have a fix in the works that will raise this limit when reading docs for rules evaluations. It will go out with the next firestore emulator release
