### ISSUE TITLE
Storage Emulator: Folder names get appended to downloaded file's file name

### ISSUE THREAD

**Issue by simenness** [firebase/firebase-tools#5457]
### [REQUIRED] Environment info

**firebase-tools:** 11.21.0

**Platform:** Windows 11

### [REQUIRED] Test case

Download a file ``image.jpg`` from the Storage Emulator that is in a folder or two ``folder/folder2``.

### [REQUIRED] Steps to reproduce

Download a file from the Storage Emulator that is in a folder (or few).

### [REQUIRED] Expected behavior

File name should be ``image.jpg``

### [REQUIRED] Actual behavior

Downloaded file's name: ``folder_folder2_image.jpg``. (folder names get appended to the file's file name)

Might be the same-ish fix as with https://github.com/firebase/firebase-tools/issues/5430.

**Comment by aalej** [comment]
Hi @simenness, thanks for reporting this issue. To clarify, could you let us know how you are downloading the file from the Storage emulator? Are you using any specific Firebase SDK?

Also, it would be helpful if you could provide an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) so that we can try to replicate the issue locally.

**Comment by simenness** [comment]
Well, I am using JS SDK 9, but the same thing happens via the emulator UI...

1) Setup demo emulator with storage & Emulator UI.

2) Run emulator
> ``firebase emulators:start --project demo-project``

3) Open up Emulator UI, and create a folder
![image](https://user-images.githubusercontent.com/27001067/214844296-65341ed2-4dce-4922-b675-3ac1ca7c6c15.png)


4) Navigate into the folder and upload a file
![image](https://user-images.githubusercontent.com/27001067/214845669-5b3f810f-f3f4-4bac-b8ad-97c054e8b61d.png)
![image](https://user-images.githubusercontent.com/27001067/214846325-ac467e3b-a2be-4e93-b534-356d9a075975.png)
![image](https://user-images.githubusercontent.com/27001067/214849308-986e1745-1ba7-4100-b83b-85da05f71643.png)

5) Click the file
![image](https://user-images.githubusercontent.com/27001067/214849858-dd40b3e3-63c4-4072-bb12-fa1a1681bf78.png)

6) Then it's name
![image](https://user-images.githubusercontent.com/27001067/214850022-3832f68a-77cb-4918-969b-3fe41b9cb39f.png)

Outcome:
![image](https://user-images.githubusercontent.com/27001067/214850482-25699595-616c-4475-ba5e-0be94c44a9cf.png)
The file got the path appended to it, and im guessing the underscores would has been backslashes from Windows...

**Comment by simenness** [comment]
Id expect this to NOT happen on any other OS that use forward slashes in their paths.

**Comment by aalej** [comment]
I am able to reproduce the same behavior on the Emulator UI on a macOS machine; when downloading a file, the file’s path also gets appended to the file name.

You mentioned that you were experiencing the same issue using the Firebase JS SDK, could you provide a code snippet showing how you are downloading the file so that I can try to reproduce this?

**Comment by simenness** [comment]
> I am able to reproduce the same behavior on the Emulator UI on a macOS machine; when downloading a file, the file’s path also gets appended to the file name.

Oh ok...
> You mentioned that you were experiencing the same issue using the Firebase JS SDK, could you provide a code snippet showing how you are downloading the file so that I can try to reproduce this?

This should do...
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Firebase Storage Emulator Demo</title>
    <style>
      html {
        font-family: "Roboto", sans-serif;
        color: #999;
        background-color: #222;
      }
    </style>
  </head>
  <body>
    <h1>Firebase Storage Emulator Demo</h1>

    <p>First upload a preset string, then download it :)</p>

    <div>
      <button id="upload">Upload</button>
      <button id="download" disabled>Download</button>
    </div>
  </body>
  <script type="module">
    import { initializeApp } from "https://www.gstatic.com/firebasejs/9.15.0/firebase-app.js";
    import {
      getStorage,
      ref,
      uploadString,
      getDownloadURL,
      connectStorageEmulator,
    } from "https://www.gstatic.com/firebasejs/9.15.0/firebase-storage.js";

    // Firebase configuration
    const firebaseConfig = {
      projectId: "demo-ember",
      appId: "demo",
      apiKey: "demo",
      authDomain: "demo",
      storageBucket: "demo",
    };

    // Initialize Firebase
    initializeApp(firebaseConfig);
    // Use the Firebase Storage emulator
    connectStorageEmulator(getStorage(), "localhost", 9199);

    // Buttons
    const upload = document.getElementById("upload");
    const download = document.getElementById("download");

    // References
    const storageRef = ref(getStorage(), "folder");
    const fileRef = ref(getStorage(), "folder/test");

    // Upload button click handler
    upload.addEventListener("click", (e) => {
      const fileString = "Hello World";

      uploadString(fileRef, fileString).then((snap) => {
        console.log("Uploaded a raw string!");

        download.disabled = false;
      });
    });

    // Download button click handler
    download.addEventListener("click", (e) => {
      // Get the download URL
      getDownloadURL(fileRef).then((url) => {
        console.log("Download URL: ", url);

        const a = document.createElement("a");
        a.href = url;
        a.download;

        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
      });
    });
  </script>
</html>
```

**Comment by aalej** [comment]
Thanks for providing the code snippet. I was able to reproduce the issue you mentioned, and it looks like it only occurs when using the emulator. When I tried to connect to a Firebase project, the file path does not get appended to the downloaded file name.

I’ll let the team know about this issue so that they can take a look into it.

**Comment by SherpaMiguel** [comment]
This is happening to me in production env 

<img width="537" alt="Image" src="https://github.com/user-attachments/assets/3f8d7199-61f5-4dca-803b-c85cc8bfcb31" />

<img width="944" alt="Image" src="https://github.com/user-attachments/assets/62e4c113-32d9-419e-bf01-8c54a7e02395" />
