### ISSUE TITLE
function timeout reset to default after deploy

### ISSUE THREAD

**Issue by amirhrl** [firebase/firebase-tools#548]
### Version info
3.15.3

### Steps to reproduce
1. deploy a function using 
    firebase deploy --only functions
2. using the google cloud console increase the timeout of that function
3. deploy same fucntion again

### Expected behavior
The timeout should remain the increased value

### Actual behavior
The timeout resets to 60 seconds (default value)

In version 3.15.2 there was similar bug that reset both memory limit and timeout. 
In current version only timeout is reset

**Comment by laurenzlong** [comment]
Hey @amirhrl I'm unable to reproduce the issue, can you please run the command again with the --debug flag and attach the logs here?

**Comment by amirhrl** [comment]
Please see attached
![after_change_timeout](https://user-images.githubusercontent.com/10544628/33429996-8f5f28d4-d5d7-11e7-890e-183f8d46a54e.png)
![after_second_deploy](https://user-images.githubusercontent.com/10544628/33429997-8f829d78-d5d7-11e7-8bc6-87a5768b6196.png)
[init_deploy.log](https://github.com/firebase/firebase-tools/files/1517671/init_deploy.log)
[second_deploy.log](https://github.com/firebase/firebase-tools/files/1517672/second_deploy.log)

**Comment by alixaxel** [comment]
I'm experiencing the same problem.

**Comment by laurenzlong** [comment]
This PR will fix it: https://github.com/firebase/firebase-tools/pull/554. Thanks for reporting!
