### ISSUE TITLE
Unable to login on MacBook M1

### ISSUE THREAD

**Issue by josecaseiro** [firebase/firebase-tools#5481]
I'm getting erros trying to login into firebase cli on Macbook M1.

Below is the error log:

Welcome to firepit v1.1.0!
Doing JSON parses for version checks at /snapshot/firepit/vendor/node_modules/firebase-tools/package.json
firebase-tools
No existing firebase-tools install found.
Installed ft@none and packaged ft@11.22.0
Legacy firepit / firebase-tools detected, clearing it out...

Checking for npm/bin/npm-cli install at /Users/josecaseiro/.cache/firebase/tools/lib/node_modules/npm/bin/npm-cli
Checking for npm/bin/npm-cli install at /Users/josecaseiro/.cache/firebase/tools/node_modules/npm/bin/npm-cli
Checking for npm/bin/npm-cli install at /snapshot/firepit/node_modules/npm/bin/npm-cli
Found npm/bin/npm-cli install.
Checking for npm/bin/npm-cli install at /Users/josecaseiro/.cache/firebase/tools/lib/node_modules/npm/bin/npm-cli
Checking for npm/bin/npm-cli install at /Users/josecaseiro/.cache/firebase/tools/node_modules/npm/bin/npm-cli
Checking for npm/bin/npm-cli install at /snapshot/firepit/node_modules/npm/bin/npm-cli
Found npm/bin/npm-cli install.
Runtime binaries created.
/usr/local/bin/firebase
/usr/local/bin/firebase,/snapshot/firepit/firepit.js,login
Checking for npm/bin/npm-cli install at /Users/josecaseiro/.cache/firebase/tools/lib/node_modules/npm/bin/npm-cli
Checking for npm/bin/npm-cli install at /Users/josecaseiro/.cache/firebase/tools/node_modules/npm/bin/npm-cli
Checking for npm/bin/npm-cli install at /snapshot/firepit/node_modules/npm/bin/npm-cli
Found npm/bin/npm-cli install.
Checking for npm/bin/npm-cli install at /Users/josecaseiro/.cache/firebase/tools/lib/node_modules/npm/bin/npm-cli
Checking for npm/bin/npm-cli install at /Users/josecaseiro/.cache/firebase/tools/node_modules/npm/bin/npm-cli
Checking for npm/bin/npm-cli install at /snapshot/firepit/node_modules/npm/bin/npm-cli
Found npm/bin/npm-cli install.
Runtime binaries created.
Checking for firebase-tools/lib/bin/firebase install at /Users/josecaseiro/.cache/firebase/tools/lib/node_modules/firebase-tools/lib/bin/firebase
Checking for firebase-tools/lib/bin/firebase install at /Users/josecaseiro/.cache/firebase/tools/node_modules/firebase-tools/lib/bin/firebase
Checking for firebase-tools/lib/bin/firebase install at /snapshot/firepit/node_modules/firebase-tools/lib/bin/firebase
CLI not found! Invoking setup...
Attempting to install to "/Users/josecaseiro/.cache/firebase/tools"

Using embedded cache for quick install...

ShellJSInternalError: EPERM: operation not permitted, uv_cwd

**Comment by bkendall** [comment]
Do you have Rosetta installed on the machine? We don't publish an ARM-compiled version of the CLI as you're installing it, so Rosetta would still be required.

(You also may want to confirm how you're installing the CLI. Manually deleting `/Users/josecaseiro/.cache/firebase/tools` might help as well)

**Comment by josecaseiro** [comment]
@bkendall thank you for your comment.

I deleted the firebase/tools folder and the error persisted.

I solved it after running  `dart pub global activate flutterfire_cli` command
