### ISSUE TITLE
Emulators Node inspector issue after recompiling TypeScript

### ISSUE THREAD

**Issue by dan-wu-open** [firebase/firebase-tools#5508]
### [REQUIRED] Environment info

**firebase-tools:** 11.22.0

**Platform:** macOS

### [REQUIRED] Test case

```
❯ firebase emulators:start --only functions --inspect-functions
i  emulators: Starting emulators: functions
⚠  functions: You are running the Functions emulator in debug mode (port=9229). This means that functions will execute in sequence rather than in parallel.
⚠  functions: The following emulators are not running, calls to these services from the Functions emulator will affect production: auth, firestore, database, hosting, pubsub, storage
i  ui: Emulator UI logging to ui-debug.log
✔  functions: Using node@16 from host.
i  functions: Loaded environment variables from .env.
✔  functions: Loaded functions definitions from source: payments.
✔  functions[us-central1-payments]: http function initialized (http://127.0.0.1:5001/my-project/us-central1/payments).
⚠  --inspect-functions only supported for Node.js runtimes.

┌─────────────────────────────────────────────────────────────┐
│ ✔  All emulators ready! It is now safe to connect your app. │
│ i  View Emulator UI at http://127.0.0.1:3001/               │
└─────────────────────────────────────────────────────────────┘

┌───────────┬────────────────┬─────────────────────────────────┐
│ Emulator  │ Host:Port      │ View in Emulator UI             │
├───────────┼────────────────┼─────────────────────────────────┤
│ Functions │ 127.0.0.1:5001 │ http://127.0.0.1:3001/functions │
└───────────┴────────────────┴─────────────────────────────────┘
  Emulator Hub running at 127.0.0.1:4400
  Other reserved ports: 4500

Issues? Report them at https://github.com/firebase/firebase-tools/issues and attach the *-debug.log files.
 
i  functions: Loaded environment variables from .env.
>  Starting inspector on 127.0.0.1:9229 failed: address already in use
```

### [REQUIRED] Steps to reproduce

1. Start my TypeScript compiler
2. Start emulators with `firebase emulators:start --only functions --inspect-functions`
3. Start debugger in VSCode
```
    {
      "name": "Debug",
      "type": "node",
      "request": "attach",
      "port": 9229, // default for Firebase Emulator
      "restart": true,
      "skipFiles": ["<node_internals>/**"]
    },
```
4. Trigger the breakpoint -> it works!
5. Make a code change
6. Trigger the breakpoint again -> it doesn't work :(
7. See the error `>  Starting inspector on 127.0.0.1:9229 failed: address already in use`

### [REQUIRED] Expected behavior

Should be able to hit the breakpoint again...

### [REQUIRED] Actual behavior

It logs that error once and then subsequent attempts don't work either. I need to restart everything to get it to work.

Changing the Javascript build files directly also causes this behavior, so I don't think it's TypeScript itself.

It seems like the Emulator is restarting the Node process when the JS files change, but doesn't clean up the inspector process correctly.

**Comment by dan-wu-open** [comment]
Hi, just an update, I noticed this issue only happens when I'm running gen-2 functions in the emulator

**Comment by colerogers** [comment]
@dan-wu-open Thanks for opening your first issue at Firebase! I'm able to reproduce this but with both 1st & 2nd gen functions. Interesting that your only seeing it with 2nd gen 🤔. I'll need to dig a little deeper to see how we can stop the debugger from re-attaching

**Comment by vanderlin** [comment]
also having this issue

**Comment by taeold** [comment]
@dan-wu-open or anyone watching this issue:

My hunch is that there is some race condition somewhere in the Debug Client and the underlying process that is hosting the function.

I'm actually having difficult time reproducing the error given @dan-wu-open's debug configuration for some reason. Here's what I'm trying:

1. Start running `tsc` with `--watch` flag
2. Start emulator using `firebase emulators:start --inspect-functions`
3. Configure VScode debugger to auto-attach to port 9229
4. Make changes to the source code
5. Watch the debugger re-attach to the new process

I think the only edge case I've discovered is that when you are in an active debug session AND you change the source code, the debug client will be bound to the process. I'm going to create a PR to address that particular case.

If you have discovered any other observation or edge cases in the meantime, I'd love to know.

**Comment by dan-wu-open** [comment]
Thanks @taeold, that's a good hypothesis. Lemme know if there's any other information that could help. Could it be a different version of another npm packge?

**Comment by taeold** [comment]
@dan-wu-open The patch that we hoped would make this setup more reliable is available in the latest version of the CLI.

Would you mind giving it a spin and letting us know whether it was helpful?

**Comment by dan-wu-open** [comment]
Woohoo it worked. Thanks @taeold! 🥂

```
✔  functions: Using node@16 from host.
i  functions: Loaded environment variables from .env, .env.prod, .env.local.
✔  functions: Loaded functions definitions from source: injectCreatedAt.
i  functions: Loaded environment variables from .env, .env.prod, .env.local.
>  Debugger listening on ws://127.0.0.1:9229/15a7721f-2a7a-4a4c-a82e-9765f5e0ce81
>  For help, see: https://nodejs.org/en/docs/inspector
>  Debugger attached.
>  {"severity":"INFO","message":"hello"}
```
