### ISSUE TITLE
Installing 11.22.0 results in --inspect-functions only supported for Node.js runtimes and debugger will not attach

### ISSUE THREAD

**Issue by Zelfapp** [firebase/firebase-tools#5509]
### [REQUIRED] Environment info

**firebase-tools:** 11.22.0

**Platform:** Manjaro Linux

**Nodejs version is:** 16.16.0

### [REQUIRED] Test case

Using `npm i -g firebase-tools` to install 11.22.0 and then trying to start emulator with `--inspect-functions` I can no longer attach a debugger in 11.22.0. Instead I get the warning during startup that `--inspect-functions only supported for Node.js runtimes`. So I tried this fix on an [issue](https://github.com/firebase/firebase-tools/issues/4885#issuecomment-1320730178) that is now closed, by running `/usr/local/bin/firebase is:npm i node@16 --save-dev` in my functions directory. However, this did not solve the problem. I completely removed the `node_modules` directory and reinstalled everything. Tried completely uninstalling firebase-tools, which is installed globally, and then reinstalling, but the only thing that worked was to downgrade to 11.21.0.

Please advise, what is the upgrade path to 11.22.0? Thanks.

### [REQUIRED] Steps to reproduce

1. From functions directory `firebase emulators:start --import=../saved-data --export-on-exit --inspect-functions` add the `--inspect functions` flag to start in debug mode.
2. Using vscode or webstorm attempt to attach a debugger to listen on port 9229.

### [REQUIRED] Expected behavior

In firestore emulator console should see:

- `>  Debugger listening on ws://127.0.0.1:9229/...` during emulator startup when using `--inspect-functions` flag.
- `>  Debugger attached.` when attaching a debugger from an IDE.

### [REQUIRED] Actual behavior

During firebase emulator startup I see this warning: `--inspect-functions only supported for Node.js runtimes` and I cannot attach a debugger to listen on port 9229.

**Comment by joerozek** [comment]
Experiencing the same problem on Max OSX 12.5, node 16.15

**Comment by Zelfapp** [comment]
> Experiencing the same problem on Max OSX 12.5, node 16.15

Give my post a thumbs up and it will get more attention. I still have not found a resolution.

**Comment by tanaka-baseed** [comment]
[functionsEmulator.ts](https://github.com/firebase/firebase-tools/blob/master/src/emulator/functionsEmulator.ts)
`      if (!emulatableBackend.bin?.startsWith("node")) {
        this.logger.log("WARN", "--inspect-functions only supported for Node.js runtimes.");`

In my environment, the emulatableBackend.bin has the full path included. Therefore, the path string is at the beginning and the "node" string is at the end. Isn't endsWith correct?
I directly edited it in my environment and it worked.
