### ISSUE TITLE
Can't configure with Next.JS to use GCP secrets

### ISSUE THREAD

**Issue by steebchen** [firebase/firebase-tools#5514]
### [REQUIRED] Environment info

**firebase-tools:** 11.23.0

**Platform:** macOS

### [REQUIRED] Test case

As per the comments in #5247, it's not currently not possible to use/configure NextJS projects to use GCP secrets, they have to be configured manually via the GCP console. I think it would be important to provide a way so that these secrets would be set automatically from the .env or that you could configure them programatically.

**Comment by jamesdaniels** [comment]
This should be addressed once [d6826ee](https://github.com/firebase/firebase-tools/commit/d6826ee9e9c2dc5b8e320953aa794be7ba2fdcdb) is out the door, we now allow configuration of the function via firebase.json (hosting.frameworksBackend) and [that includes secrets](https://firebase.google.com/docs/functions/beta/reference/firebase-functions.https.httpsoptions.md#httpshttpsoptionssecrets).

**Comment by steebchen** [comment]
Cool! Although it's not clear to me what I would specify there, just the GCP secret name? How would I configure which env var it would use for the secret?

**Comment by tamerxkilinc** [comment]
I think it would be the same as when you write cloud functions yourself.
With the cloud function sdk you would write the following: `.runWith({secrets: ["MY_SECRET"]})`
So I would guess you would also add the secret names you need to firebase.json.
In your code you can then access them via process.env, e.g. `const mySecret = process.env.MY_SECRET;`

**Comment by steebchen** [comment]
It should be possible to get the secrets without the need of any code, or at least that's how I would imagine the ideal workflow at least. I would have to try it myself but I still don't see how the config in firebase.json looks (I'm hoping that's the only thing you need), as you would likely need to define the secret name **and** the env var name to provide the secret value (that's what you currently need to configure in the UI).

**Comment by null-reference** [comment]
@steebchen I was able to get it working by setting a secret using the firebase CLI and then updating my config like so:

```
"hosting": {
    "source": ".",
    "ignore": ["firebase.json", "**/.*", "**/node_modules/**"],
    "frameworksBackend": {
      "secrets": ["MY_API_KEY"]
    }
  }
```

Once I did that, I was able to access the secret using `process.env.MY_API_KEY`.

**Comment by steebchen** [comment]
I see, thanks for the info!

**Comment by steebchen** [comment]
Doesn't seem to work for me. I'm on `firebase-tools@11.24.0`. 

firebase.json

```
{
  "firestore": {
    "rules": "firestore.rules",
    "indexes": "firestore.indexes.json"
  },
  "hosting": {
    "source": ".",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "frameworksBackend": {
      "secrets": [
        "FBASE_PRIVATE_KEY",
        "COOKIE_SECRET"
      ]
    }
  }
}
```

The cloud function simply does not reference the secrets after doing `firebase deploy`.


I do have an existing function, but I'm assuming it should be updated correctly?

Any idea?
