### ISSUE TITLE
Error with `firebase deploy` : `type:: command not found`

### ISSUE THREAD

**Issue by aaga** [firebase/firebase-tools#5515]
### Environment info

- GitHub Actions

**firebase-tools:** 11.22.0

**Platform:** Ubuntu

### Test case

Attempting to run `firebase deploy --only functions,firestore` as a step in CI (GitHub Actions). Here is the action as defined in the repo: https://github.com/mozilla-rally/rally/blob/main/.github/workflows/deploy-functions-to-staging.yaml

### Steps to reproduce

- Run the "Deploy functions to staging" action on the `fix-function-deployment` branch: https://github.com/mozilla-rally/rally/tree/fix-function-deployment/web-platform/functions

### Expected behavior

- Successful deployment

### Actual behavior

- Deployment unsuccessful, with error `type:: command not found`
```
  GOOGLE_APPLICATION_CREDENTIALS="$HOME"/gcloud.json web-platform/functions/node_modules/.bin/firebase deploy --only functions,firestore --project *** -c web-platform/firebase.json
  shell: /usr/bin/bash -e ***0***
  env:
    NPM_CONFIG_USERCONFIG: /home/runner/work/_temp/.npmrc
    NODE_AUTH_TOKEN: XXXXX-XXXXX-XXXXX-XXXXX
##[debug]/usr/bin/bash -e /home/runner/work/_temp/1711829f-541b-4aa6-a693-5ab3e095f70c.sh
***
/home/runner/work/_temp/1711829f-541b-4aa6-a693-5ab3e095f70c.sh: line 6: type:: command not found
Error: Process completed with exit code 127.
##[debug]Finishing: Deploy firebase functions to staging
```

**Comment by blidd-google** [comment]
Hi @aaga, it looks as though the GitHub Action step is looking for the `firebase` command inside of a nested `node_modules` folder. Instead, you could try installing the `firebase` CLI in a previous step of your GitHub Actions by following the instructions provided [here](https://firebase.google.com/docs/cli#cli-ci-systems). Then, you should be able to invoke the deploy command with `firebase deploy --only functions, firestore ...`. Hope this helps!
