### ISSUE TITLE
dynamic routes in app dir in nextjs13 not working

### ISSUE THREAD

**Issue by RajendraAVerma** [firebase/firebase-tools#5522]
### [REQUIRED] Environment info

**firebase-tools:** 11.23.0

**Platform:** Window

### [REQUIRED] Test case

I am using NextJs 13 with experimental feature of "appDir"
while deploying to firebase hosting, dynamic routes become static path.
for example :
path `app/[slug]/page.jsx` become `http://example.web.app/[slug]`  

![ss](https://user-images.githubusercontent.com/29675930/219047530-72422ddd-e60b-4f45-97bd-c872d405f02c.png)

**You can see [slug] is consider as static page**

### [REQUIRED] Steps to reproduce

1. create nextjs13 app `npx create-next-app@latest --experimental-app`
2. create `app/[slug]/page.jsx`.
3. enable `firebase experiments:enable webframeworks`
4. make sure to enable billing.
5. `firebase init hosting` then` firebase deploy`
6. after successfully deployment, check `http://your-domain.web.app/hello`, you will see page not found but `http://example.web.app/[slug]` is working.

in `firebase.json`
```
{
  "hosting": {
    "source": ".",
    "cleanUrls": false,
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ]
  }
}
```
in `next.config.js`

```
/** @type {import('next').NextConfig} */
const nextConfig = {
  experimental: {
    appDir: true,
  },
}

module.exports = nextConfig
```

in `jsconfig.json`

```
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/*": ["./*"]
    }
  }
}
```

### [REQUIRED] Expected behavior

It should generate dynamic routes.

### [REQUIRED] Actual behavior

Dynamic routes not generated.

**Comment by nerder** [comment]
Any update on this issue? Is Next13 actually supported as of now?

**Comment by dominicdev** [comment]
any update?

**Comment by AmritpalChera** [comment]
Hey, instead of creating a file called [slug].tsx or smt. Make a folder called [slug] in the app directory (experimental setup):

post
  - page.tsx
  - [slug]/page.tsx
