### ISSUE TITLE
Typing missing to allow functionParams defineString to be used for region

### ISSUE THREAD

**Issue by RYFN** [firebase/firebase-tools#5524]
### [REQUIRED] Environment info

**firebase-tools:** 11.22.0

**Platform:** macOS

### [REQUIRED] Test case

```
const region = defineString('REGION');

export const onCreate = functions
    //results in TS error, see attached image
    .region(region)
    .firestore.document('document/{docId}')
    .onCreate(async (snapshot, context)
```
![218504158-68048fb5-d485-453b-ab89-63691d8b2636](https://user-images.githubusercontent.com/2254840/219126658-0f5b38f2-e625-41d7-9af9-34cbad43a7a5.png)

### [REQUIRED] Steps to reproduce

Per test case

### [REQUIRED] Expected behavior

Should be able to use  output of defineString to configure function region

### [REQUIRED] Actual behavior

Need to cast result of defineString with `as any` to allow typescript build. Function works as expected when deployed with 

```
const region = defineString('REGION');

export const onCreate = functions
    .region(region as any)
    .firestore.document('document/{docId}')
    .onCreate(async (snapshot, context)
```

Follow up to https://github.com/firebase/firebase-tools/issues/5347, resolved by https://github.com/firebase/firebase-functions/pull/1329/files suspect adding `Expression<string> |` to region config would fix this?

(further to this, what's best practice when using defineString in globally defined things in functions? e.g. using the following results in a deployment warning, but not using `.value()` causes an error)

```
const redisUsername  = defineString('REDIS_USERNAME') 

//username expects a string
const redisOptions: RedisClientOptions = {
    username: redisUsername.value()
};
... 
export const onCreate = functions
    .region(region as any)
    .firestore.document('document/{docId}')
    .onCreate(async (snapshot, context)
    ...
```

**Comment by colerogers** [comment]
Thanks for pointing this out! I drafted a fix in the SDK which will close this issue out once it's merged.

**Comment by simonmitchell** [comment]
@colerogers any advice on the question regarding globally defined things?
