### ISSUE TITLE
Web Frameworks: Deploying a NextJs app that uses `getServerSideProps` doesn't create a CloudFunction to handle the SSR

### ISSUE THREAD

**Issue by ErickJoestar** [firebase/firebase-tools#5526]
### [REQUIRED] Environment info

**firebase-tools:** 11.23.1

**Platform:** macOS

### [REQUIRED] Test case
`firebase deploy` only deploys the hosting and doesn't build the Cloud Function 
```
firebase deploy 

> firebase-next-ssr-auth@0.1.0 deploy
> firebase deploy

Detected a Next.js codebase. This is an experimental integration, proceed with caution.

info  - Linting and checking validity of types  
info  - Creating an optimized production build  
info  - Compiled successfully
info  - Collecting page data  
info  - Generating static pages (2/2)
info  - Finalizing page optimization  

Route (pages)                              Size     First Load JS
┌ λ /                                      331 B          73.4 kB
├   /_app                                  0 B            73.1 kB
└ ○ /404                                   181 B          73.2 kB
+ First Load JS shared by all              73.1 kB
  ├ chunks/framework-cda2f1305c3d9424.js   45.2 kB
  ├ chunks/main-f11614d8aa7ee555.js        26.8 kB
  ├ chunks/pages/_app-17bcdbe1cad2241d.js  287 B
  └ chunks/webpack-4e7214a60fad8e88.js     712 B

λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)


=== Deploying to 

i  deploying hosting
i  hosting[testing-ca405]: beginning deploy...
i  hosting[testing-ca405]: found 15 files in .firebase/testing-ca405/hosting
✔  hosting[testing-ca405]: file upload complete
i  hosting[testing-ca405]: finalizing version...
✔  hosting[testing-ca405]: version finalized
i  hosting[testing-ca405]: releasing new version...
✔  hosting[testing-ca405]: release complete

✔  Deploy complete!

Project Console: 
Hosting URL: 
```
Accessing the page returns a 404
<img width="840" alt="image" src="https://user-images.githubusercontent.com/31946895/219254088-bbef1c8b-f6cd-47ef-9182-a57b7066b360.png">

Example repo: https://github.com/ErickJoestar/Firebase-Next-SSR-Auth/tree/showcase-getServerSideProps

If the app has more reasons to build a Cloud Function, for example having a page with a non-static route,  it fixes the problem since it's detected correctly and creates the Cloud Function.
Example: https://github.com/ErickJoestar/Firebase-Next-SSR-Auth/tree/showcase-getServerSideProps-non-static-route

### [REQUIRED] Steps to reproduce
1. Initialize a project with NextJs
2. Enable web frameworks `firebase experiments:enable webframeworks`
3. Init hosting `firebase init hosting`
4. Create a page that uses `getServerSideProps`
6. Deploy the app

### [REQUIRED] Expected behavior

Firebase tools detects that the app requires a Cloud Function to handle the Server Side Rendering and deploys both the function and hosting

### [REQUIRED] Actual behavior

It doesn't detect that it requires a Cloud Function and only deploys the Hosting, this causes the app to throw a 404 error when accessing the URL

**Comment by jamesdaniels** [comment]
This should all be working as of recent CLI releases, please open a new issue if you have any trouble with firebase-tools v12
