### ISSUE TITLE
firebase login --no-localhost failed

### ISSUE THREAD

**Issue by giantss** [firebase/firebase-tools#5549]
```
  google_sign_in: ^6.0.1
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.9
```

`firebase login --no-localhost`
I can't log in successfully, it has delayed me for a day, and I am very tired now, please help me.

Below is the process I performed，After entering the authorization code, it has not been successful。
```
$ firebase --debug login --no-localhost
i  Firebase optionally collects CLI and Emulator Suite usage and error reporting information to help improve our products. Data is collected in accordance with Google's privacy policy (https://policies.google.com/privacy) and is not used to identify you.
 
? Allow Firebase to collect CLI and Emulator Suite usage and error reporting information? Yes
i  To change your data collection preference at any time, run `firebase logout` and log in again. 
[2023-02-24T08:27:41.062Z] >>> [apiv2][query] POST https://auth.firebase.tools/attest [none]
[2023-02-24T08:27:41.062Z] >>> [apiv2][body] POST https://auth.firebase.tools/attest {"session_id":"dc7ba1ca-75f7-4150-a61a-49a594dfa550"}
[2023-02-24T08:27:41.722Z] <<< [apiv2][status] POST https://auth.firebase.tools/attest 200
[2023-02-24T08:27:41.722Z] <<< [apiv2][body] POST https://auth.firebase.tools/attest {"token":"oBb8XGq1rYoO1tqQCk-bg4V252DdcuZ-wKAmI71dlvM"}

To sign in to the Firebase CLI:

1. Take note of your session ID:

   DC7BA

2. Visit the URL below on any device and follow the instructions to get your code:

   https://auth.firebase.tools/login?code_challenge=lkU1XR4I8EnQKW5L7UTEPo0_z5c2kVUNHXplVDecqVg&session=dc7ba1ca-75f7-4150-a61a-49a594dfa550&attest=oBb8XGq1rYoO1tqQCk-bg4V252DdcuZ-wKAmI71dlvM

3. Paste or enter the authorization code below once you have it:

? Enter authorization code: 4/0AWtgzh4123K2cT9fvU4ykXZdAbCGZeBfZQutFSUNWGEMXYp_QtAGEJUgvbj0TTl6lpX2NQ
[2023-02-24T08:29:21.913Z] >>> [apiv2][query] POST https://accounts.google.com/o/oauth2/token [none]
[2023-02-24T08:29:21.914Z] >>> [apiv2][body] POST https://accounts.google.com/o/oauth2/token [omitted]
[2023-02-24T08:30:36.917Z] Token Fetch Error: FirebaseError: Failed to make request to https://accounts.google.com/o/oauth2/token
    at RetryOperation._fn (/usr/local/lib/node_modules/firebase-tools/lib/apiv2.js:242:31)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

Error: Unable to authenticate using the provided code. Please try again.

```

**Comment by aalej** [comment]
Hi @giantss, thanks for reaching out to us. I tried to replicate the error, but I encountered no issues when running the `firebase login --no-localhost` command. Could you let us know what version of firebase-tools you’re using? If you’re not using the latest version of firebase-tools, which is v11.24.0, I would recommend upgrading to see if you would still encounter the issue in the latest version.

Also, could you try running `firebase login --no-localhost --reauth` to see if this would work?

**Comment by giantss** [comment]
Hi @aalej 
`v11.24.0`

<img width="710" alt="image" src="https://user-images.githubusercontent.com/13778798/221456885-3c34e67a-92bc-401e-855f-bc49cb6846ef.png">

`firebase login --no-localhost --reauth`  Failed!!!

**Comment by aalej** [comment]
@giantss sorry for the extra hoop here, but could you provide the debug logs by adding the --debug flag? Run `firebase login --no-localhost --reauth --debug`.

Since it looks like there is a failing request, could you try connecting to a different network or temporarily turn off any proxy, firewall or VPN that you may have?

**Comment by timtang3115** [comment]
I have met the same issue, I run

**Comment by timtang3115** [comment]
I have the same issue, I run firebase login --no-localhost --reauth --debug:
<img width="1041" alt="image" src="https://user-images.githubusercontent.com/127286943/223640770-f7118a19-4fb3-4594-9a03-e6b6d084cde0.png">

**Comment by timtang3115** [comment]
This time stoped at:
<img width="1345" alt="image" src="https://user-images.githubusercontent.com/127286943/223644127-733a3344-8bde-42ef-9190-e77e048b8e0a.png">

**Comment by AreYReady** [comment]
我也是遇到这个情况，核心其实是网络问题。我挂着vpn，开着全局也碰到这个问题。我自己是mac，我在终端输入代理指令，让终端也翻墙之后，就可以了。
