### ISSUE TITLE
Firebase Hosting does not deploy a cloud function/ not working for Image Optimisation

### ISSUE THREAD

**Issue by okaforcj** [firebase/firebase-tools#5556]
### [REQUIRED] Environment info

11.24.0

**firebase-tools:**

**Platform:**

### [REQUIRED] Test case

Enable Image component in nextjs config (implement an Image Tag)

### [REQUIRED] Steps to reproduce

Use an Image tag from "next/image" and deploy firebase

### [REQUIRED] Expected behavior

Optimise images 

### [REQUIRED] Actual behavior

Returns 400 error with "url parameter  is not allowed"

**Comment by joehan** [comment]
Hey @okaforcj, could you share the debug logs from this error? ('firebase deploy --debug)
