### ISSUE TITLE
firebase deploy not running vite build in prod mode

### ISSUE THREAD

**Issue by tanjunior** [firebase/firebase-tools#5564]
### [REQUIRED] Environment info

**firebase-tools:** 11.24.0

**Platform:** Windows

### [REQUIRED] Test case
Create a new vite react project
console.log(import.meta.env.DEV) in app.js
`npm run dev`
console log return true
`npm run build`
`npm run serve`
console log return false
`firebase experiments:enable webframeworks`
`firebase init hosting`
`firebase deploy`
`firebase serve`
console log return true

### [REQUIRED] Steps to reproduce
Create a new vite react project
console.log(import.meta.env.DEV) in app.js
`npm run dev`
console log return true
`npm run build`
`npm run serve`
console log return false
`firebase experiments:enable webframeworks`
`firebase init hosting`
`firebase deploy`
`firebase serve`
console log return true

### [REQUIRED] Expected behavior
console log should return false in a `firebase build` as it runs `npm run build(vite build)` and `vite build` builds in production mode by default

### [REQUIRED] Actual behavior
console log return true in a `firebase build`

**Comment by tanjunior** [comment]
found a work around by following https://vitejs.dev/guide/static-deploy.html#google-firebase

change `firebase.json` hosting from 
```
"hosting": {
    "source": ".",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "frameworksBackend": {
      "region": "asia-east1"
    }
  }
```
to

```
  "hosting": {
    "public": "dist",
    "rewrites": [
      {
        "source": "**",
        "destination": "/index.html"
      }
    ],
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "predeploy": [
      "npm run build"
    ]
  },
```

**Comment by jamesdaniels** [comment]
We are forcing the Vite build to production, we will override NODE_ENV in a future release but this should be sufficient.

**Comment by joelharkes** [comment]
@tanjunior there is no way to run HMR vite in the emulator hosting?

**Comment by AlxVallecillo** [comment]
Thank you @tanjunior  that worked just fine

**Comment by mrchantey** [comment]
Is this supposed to be fixed? I'm getting `import.meta.env.DEV == true` with `firebase deploy` in `firebase-tools 13.11.2`.

The static deploy `firebase.json` solution won't work for SSR apps using frameworks.
