### ISSUE TITLE
On Every Blocking Function Deploy, Additional provider token credentials options are reset

### ISSUE THREAD

**Issue by seanaguinaga** [firebase/firebase-tools#5565]
Firebase product - Firebase Functions - Blocking, specifically

Not sure where else to put this

On every deploy, these checkboxes are unchecked - breaking them when deployed

Is this the correct behavior?

<img width="986" alt="Screenshot 2023-02-15 at 9 02 15 AM" src="https://user-images.githubusercontent.com/15254340/219101102-b5926a11-48bf-4167-9c6e-0325fdad8edd.png">

**Comment by blidd-google** [comment]
Hi @seanaguinaga, thanks for your patience. This behavior is indeed correct — our deployment logic considers your functions code as the source of truth for your functions configuration options. So if you have not set the option to pass ID tokens, refresh tokens, and/or access tokens in your functions code, the settings you configured in the console will be overridden upon re-deployment. My suggestion would be to configure your functions like so:

```
exports.beforeCreate = functions.auth.user({
  blockingOptions: {
    idToken: true,
    accessToken: true,
    refreshToken: true,
  },
}).beforeCreate((user, context) => {
  console.log("user yo", user);
});
```

FYI: if you set these options for one function, they will propagate to all your functions as well. So setting `idToken: true` will mean all your auth blocking functions will receive ID tokens.

**Comment by seanaguinaga** [comment]
Oh wow I never would've known that config existed!

Thank you very much!
