### ISSUE TITLE
Firebase tools deploy resets both cloud function's timeout and memory settings

### ISSUE THREAD

**Issue by idoideas** [firebase/firebase-tools#5576]
### [REQUIRED] Environment info

**firebase-tools:** 11.24.0 (Latest at the time of posting)

**Platform:** MacOS

### [REQUIRED] Test case

When I redeploy a cloud function with a change, it seems like the cloud function's settings of timeout and memory are being reset back to 60 seconds and 256MB.
Even if I manually change it again in the Google Cloud console, the next deployment is going to reset it.
Seems very similar to this issue #4801. This creates unexpected timeouts for our systems and we can't manually change it back with every deployment, let alone when we run `firebase deploy --only functions` which affects all of them at once.
### [REQUIRED] Steps to reproduce

1. Deploy a cloud function using `firebase deploy --only functions:[SPECIFIC-FUNCTION]`.
2. Go to the Google Cloud console and increase its memory and timeout settings.
3. Redeploy the function using either `firebase deploy --only functions` / `firebase deploy --only functions:[SPECIFIC-FUNCTION]`
4. Go to the Google Cloud console. You'll notice the function's settings have been reset to their defaults.

### [REQUIRED] Expected behavior

Timeout and memory should stay the same as they were manually set unless explicitly instructed to change through the CLI. 

### [REQUIRED] Actual behavior

Timeout and memory reset back to 60s and 256MB.

**Comment by blidd-google** [comment]
Hi @idoideas — have you set the `preserveExternalChanges` option to true? Doing so will preserve the changes you make to memory and timeout settings in the Google Cloud console. 

```
// 1st gen functions
exports.func = functions.runWith({ preserveExternalChanges: true }).https.onRequest(...);

// 2nd gen functions

exports.func = onRequest({ preserveExternalChanges: true }, ...);
// or you can set options globally
const { setGlobalOptions } = require("firebase-functions/v2");
setGlobalOptions({preserveExternalChanges: true });
```

However, we do recommend configuring runtime options inside the functions code, as the runtime options you set in the code is the source of truth and will override options set via other methods (like in Google Cloud console). 

For example:
```
// 1st gen functions
exports.funcv1 = functions
    .runWith({
        memory: "512MB",
        timeoutSeconds: 120,
    })
    .https.onRequest(...);

// 2nd gen functions
exports.funcv2 = functions.https.onRequest({
    memory: "512MB", 
    timeoutSeconds: 120,
}, ...);
```


Here is our [documentation](https://firebase.google.com/docs/functions/manage-functions#set_runtime_options) for setting functions runtime options.

**Comment by MeTaNoV** [comment]
@blidd-google what about next.js webframework integration? Where could I configure the `preserveExternalChanges` option?

**Comment by yepMad** [comment]
@MeTaNoV so that this never gets lost: just set a value for "memory" in the firebase.json file. Example:

```
{
  "firestore": {
    "rules": "firestore.rules",
    "indexes": "firestore.indexes.json"
  },
  "hosting": {
    "source": ".",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "frameworksBackend": {
      "region": "us-central1",
      "memory": "2GiB"
    }
  },
  "storage": {
    "rules": "storage.rules"
  }
}
```

Accepted values ​​are:
`"128MiB", "16GiB",  "1GiB", "256MiB", "2GiB", "32GiB", "4GiB", "512MiB", "8GiB"`

Source: https://github.com/firebase/firebase-tools/blob/master/schema/firebase-config.json
