### ISSUE TITLE
CDN in China

### ISSUE THREAD

**Issue by hugetiny** [firebase/firebase-tools#5580]
I hope firebase could provide a way to use  firebase in China.
At least ,firebase could provide a way for developers to set CDNs manually in firebase-tools or some configuration files. 
`firebase.tools` is not banned in China so far.

The project below shows some unofficial CDNs for google can be used in China 
https://github.com/justjavac/ReplaceGoogleCDN

by the way,I found out that some domains with static things from Google are not banned in China:
```
dl.google.com 
fonts.googleapis.com
fonts.gstatic.com
...
```

**Comment by bkendall** [comment]
Please file a feature request with [Firebase Support](https://firebase.google.com/support). This isn't something that can be solved from the CLI's side of things, so filing a feature request with the team is the way to go. Thanks!
