### ISSUE TITLE
FirebaseCommandException: An error occured on the Firebase CLI when attempting to run a command. COMMAND: firebase projects:create mynotes-flutter-ectjo --json

### ISSUE THREAD

**Issue by RC-KapilDev** [firebase/firebase-tools#5583]
### [REQUIRED] Environment info

**firebase-tools:**

**Platform:**

**Comment by aalej** [comment]
Hi @RC-KapilDev, I understand that there's an issue related to creating a Firebase project using the CLI. It would be more helpful if you specify the details using the provided template in a new ticket. This way, it would be more efficient in identifying the cause of the issue. That being said, I'll be closing this for now.
