### ISSUE TITLE
flutterfire cli

### ISSUE THREAD

**Issue by Ripudhman** [firebase/firebase-tools#5584]
i Found 0 Firebase projects.
✔ Enter a project id for your new Firebase project (e.g. my-cool-project) · ripudhman-first-project                                                                 
i New Firebase project ripudhman-first-project created successfully.
FirebaseCommandException: An error occured on the Firebase CLI when attempting to run a command.
COMMAND: firebase projects:create ripudhman-first-project --json
ERROR: Failed to create project. See firebase-debug.log for more info.

**Comment by aalej** [comment]
Hi @Ripudhman, could you file a new issue following the provided template? Information such as the contents of the firebase-debug.log, version of firebase-tools, and etc. is necessary so that we can have basic information to start our investigation. Thanks!
