### ISSUE TITLE
Support for multiple databases?

### ISSUE THREAD

**Issue by samodadela** [firebase/firebase-tools#560]
firebase --version: 3.16.0

I found that "firebase deploy" deploys the rules only to the default database. How can I specify another database? We are sharding firebase by sharding on multiple databases (Firebase introduced multiple databases support). 

I found this article (though it's 2 years old) which mentions using the -f flag but it doesn't seem to work... Article is [here](https://firebase.googleblog.com/2015/11/the-firebase-cli-now-with-database_82.html)

**Comment by samodadela** [comment]
Bump! Can someone respond - does it support multiple databases or not?

**Comment by justinrosenthal** [comment]
Yes, you can have different rules for each database instance.  See the **Edit and deploy Firebase Database Rules for each instance** section in the [documentation for multiple databases](https://firebase.google.com/docs/database/usage/sharding)
