### ISSUE TITLE
Pub/Sub Emulator has exited with code: 1

### ISSUE THREAD

**Issue by Ruisi-Lu** [firebase/firebase-tools#5614]
### [REQUIRED] Environment info

**firebase-tools:** 11.24.1
**Node.js:** v16.19.1
**Java:** OpenJDK 11.0.18

**Platform:** macOS13.2.1 M1

### [REQUIRED] Test case

 Run `firebase emulators:start --only pubsub`

### [REQUIRED] Actual behavior

````
i  emulators: Starting emulators: pubsub
i  pubsub: Pub/Sub Emulator logging to pubsub-debug.log
⚠  pubsub: Fatal error occurred: 
   Pub/Sub Emulator has exited with code: 1, 
   stopping all running emulators
i  pubsub: Stopping Pub/Sub Emulator
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
⚠  pubsub: Error stopping Pub/Sub Emulator
i  hub: Stopping emulator hub
````

````
// pubsub-debug.log
Error: Invalid or corrupt jarfile /Users/ruisi/.cache/firebase/emulators/pubsub-emulator-0.7.1/pubsub-emulator/lib/cloud-pubsub-emulator-0.7.1.jar
````

I have tried to manually delete `cloud-pubsub-emulator-0.7.1.jar`, and use `firebase setup:emulators:pubsub` to reinstall.

**Comment by christhompsongoogle** [comment]
Thanks for the report. We're not able to reproduce this bug on our end just yet.

Question: I see you're running JDK11 - if you upgrade to the latest version JDK 19 or 20, does that resolve the issue?

https://openjdk.org/projects/jdk/

**Comment by Ruisi-Lu** [comment]
> Thanks for the report. We're not able to reproduce this bug on our end just yet.
> 
> Question: I see you're running JDK11 - if you upgrade to the latest version JDK 19 or 20, does that resolve the issue?
> 
> https://openjdk.org/projects/jdk/
> 
> Other ideas to help us identify the issue: Ensure you have a project selected via `firebase use` If you're up for it, try the emulator via the gcloud CLI, instructions here: https://cloud.google.com/pubsub/docs/emulator

I was using Node19.8.1 and openjdk19.0.2 at the time of the problem, after I clean and reinstalled Node16 and jdk11 the problem still exists.

I can run pubsub emulator using gcloud CLI by `gcloud beta emulators pubsub start` .
- Google Cloud CLI version: 423.0.0
- Cloud Pub/Sub Emulator version: 0.8.1

**Comment by christhompsongoogle** [comment]
Thanks Ruisi-Lu,

If you run `firebase emulators:start --only pubsub` with the --debug flag, does it add any additional details of interest?

**Comment by Ruisi-Lu** [comment]
> Thanks Ruisi-Lu,
> 
> If you run `firebase emulators:start --only pubsub` with the --debug flag, does it add any additional details of interest?

Thanks for your help.
After I run pubsub emulator using cloud CLI, my firebase CLI can run pubsub emulator.
I try running `gcloud components remove pubsub`, and firebase CLI pubsub is also normal.
I can't able to reproduce the bug for now, and I don't understand where have problem.

**Comment by austinn** [comment]
Possible related issue: https://github.com/firebase/firebase-tools-ui/issues/933

As soon as I downgraded to Node 16, it started working again

**Comment by nugentmichael1** [comment]
I had this issue until I downgraded Node from latest (19.x.x) to LTS (18.15.0).

**Comment by christhompsongoogle** [comment]
Thanks for the input everyone, we've been seeing a few Node 19 errors so downgrading to 18 should be a first step. If that doesn't resolve the issue please file an issue or post in this thread.

**Comment by nicobuch-southpole** [comment]
Hi! I've been struggling with the same issue for the last few days. I tried with Node 18 and 16 but none worked, I also tried diferent Java versions but it is the same :/ 

Any hint on how could I troubleshoot what could be the root problem?

**Comment by tamerxkilinc** [comment]
Had the same issue today. The following instructions worked for me on macOS:
1. Delete the downloaded jar file. You can find the directory when you start the emulators with the `--debug `flag.
2. Make sure you use NodeJS 16 or 18
3. Make sure you use Java 17 or 19
4. Run the following command: `firebase setup:emulators:pubsub`. This will download the jar file.
5. Try running the pubsub emulator again: `firebase emulators:start --only pubsub`

**Comment by iSuslov** [comment]
😫 I've found the real issue. If you want to buy me a new tesla, you are more than welcome to find my paypal email in my profile. 

To be clear, I'm talking about this error:

> Error: Invalid or corrupt jarfile ...

- It's not your Java
- It's not your Docker settings (if you run one)
- Affects any version of `firebase-tools`

**What happens?**
This issue occurs if you **download & set up** emulators using node v18.16+ or v19.8+. It works fine if you have emulators installed by other versions of node **even** if you upgrade node version afterwards.
Since it only happens for `pubsub` & `UI` emulators, I suspect that `firebase-tools` struggle to correctly unzip downloaded archives. 

@christhompsongoogle & firebase team, please take a look at the changelogs for the node versions mentioned above to nail down the exact issue:  
v19.8.0 [changelog](https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V19.md#2023-03-14-version-1980-current-targos)
v18.16.0 [changelog](https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V18.md#18.16.0)

**Comment by nicobuch-southpole** [comment]
On my experience this issue was caused because of trying to run the Pub/Sub emulator with a non LTS version of Node. Once you downgrade Node, you also need to remove the entire `.cache` directory that it is pointed out so it can be regenerated with the new version. 
Hope it helps!

**Comment by eastlondoner** [comment]
This reproduces the issue for us

```
FROM openjdk:20-slim

# Firebase emulator support in node versions is tricky
RUN apt-get update -y \
  && apt-get install -y curl \
  && curl -fsSL https://deb.nodesource.com/setup_16.x | bash - \
  && apt-get update -y \
  && apt-get install -y nodejs \
  && apt purge curl -y \
  && apt clean -y \
  && apt autoremove -y \
  && rm -rf /var/lib/apt/lists/* 

RUN npm install -g firebase-tools@11.28.0

COPY entrypoint /firebase/entrypoint
WORKDIR /firebase

ENV GCLOUD_PROJECT="demo-firebase-emulator"

# Run a no-op command to download the firebase jar files (and store them in the docker image)
RUN firebase emulators:exec --only pubsub --project "${GCLOUD_PROJECT}" "exit 0"

ENTRYPOINT ["/firebase/entrypoint"]
```

**Comment by jb-thery** [comment]
I have this error with openjdk 20 and not 18 :
``` functions git:(develop) ✗ firebase emulators:start --only pubsub --debug
[2023-04-23T16:32:14.935Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2023-04-23T16:32:14.936Z] > authorizing via signed-in user (jb.thery@flameapp.studio)
i  emulators: Starting emulators: pubsub {"metadata":{"emulator":{"name":"hub"},"message":"Starting emulators: pubsub"}}
[2023-04-23T16:32:15.161Z] [logging] Logging Emulator only supports listening on one address (127.0.0.1). Not listening on ::1
[2023-04-23T16:32:15.162Z] [pubsub] Pub/Sub Emulator only supports listening on one address (127.0.0.1). Not listening on ::1
[2023-04-23T16:32:15.162Z] assigned listening specs for emulators {"user":{"hub":[{"address":"127.0.0.1","family":"IPv4","port":4400},{"address":"::1","family":"IPv6","port":4400}],"logging":[{"address":"127.0.0.1","family":"IPv4","port":4500}],"pubsub":[{"address":"127.0.0.1","family":"IPv4","port":8085}]},"metadata":{"message":"assigned listening specs for emulators"}}
[2023-04-23T16:32:15.165Z] [hub] writing locator at /var/folders/7n/f_k_gzy90xjdd5l584mkc9z00000gn/T/hub-workoutgen-staging.json
[2023-04-23T16:32:15.168Z] Ignoring unsupported arg: projectId {"metadata":{"emulator":{"name":"pubsub"},"message":"Ignoring unsupported arg: projectId"}}
[2023-04-23T16:32:15.168Z] Ignoring unsupported arg: auto_download {"metadata":{"emulator":{"name":"pubsub"},"message":"Ignoring unsupported arg: auto_download"}}
[2023-04-23T16:32:15.168Z] Starting Pub/Sub Emulator with command {"binary":"/Users/jbty/.cache/firebase/emulators/pubsub-emulator-0.7.1/pubsub-emulator/bin/cloud-pubsub-emulator","args":["--host=127.0.0.1","--port=8085"],"optionalArgs":["port","host"],"joinArgs":true} {"metadata":{"emulator":{"name":"pubsub"},"message":"Starting Pub/Sub Emulator with command {\"binary\":\"/Users/jbty/.cache/firebase/emulators/pubsub-emulator-0.7.1/pubsub-emulator/bin/cloud-pubsub-emulator\",\"args\":[\"--host=127.0.0.1\",\"--port=8085\"],\"optionalArgs\":[\"port\",\"host\"],\"joinArgs\":true}"}}
i  pubsub: Pub/Sub Emulator logging to pubsub-debug.log {"metadata":{"emulator":{"name":"pubsub"},"message":"Pub/Sub Emulator logging to \u001b[1mpubsub-debug.log\u001b[22m"}}
[2023-04-23T16:32:15.336Z] Error: Invalid or corrupt jarfile /Users/jbty/.cache/firebase/emulators/pubsub-emulator-0.7.1/pubsub-emulator/lib/cloud-pubsub-emulator-0.7.1.jar
 {"metadata":{"emulator":{"name":"pubsub"},"message":"Error: Invalid or corrupt jarfile /Users/jbty/.cache/firebase/emulators/pubsub-emulator-0.7.1/pubsub-emulator/lib/cloud-pubsub-emulator-0.7.1.jar\n"}}
⚠  pubsub: Fatal error occurred: 
   Pub/Sub Emulator has exited with code: 1, 
   stopping all running emulators {"metadata":{"emulator":{"name":"pubsub"},"message":"Fatal error occurred: \n   Pub/Sub Emulator has exited with code: 1, \n   stopping all running emulators"}}
i  pubsub: Stopping Pub/Sub Emulator {"metadata":{"emulator":{"name":"pubsub"},"message":"Stopping Pub/Sub Emulator"}}
[2023-04-23T16:32:19.339Z] Pub/Sub Emulator: Unable to terminate process (PID=14918) {"metadata":{"emulator":{"name":"pubsub"},"message":"Pub/Sub Emulator: Unable to terminate process (PID=14918)"}}
[2023-04-23T16:32:19.340Z] [pubsub] {"name":"FirebaseError","children":[],"exit":1,"message":"pubsub: Pub/Sub Emulator: Unable to terminate process (PID=14918)","status":500}
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
⚠  pubsub: Error stopping Pub/Sub Emulator {"metadata":{"emulator":{"name":"pubsub"},"message":"Error stopping Pub/Sub Emulator"}}
i  hub: Stopping emulator hub {"metadata":{"emulator":{"name":"hub"},"message":"Stopping emulator hub"}}
```
