### ISSUE TITLE
execSync('firebase functions:config:get') is truncated to 8192 bytes

### ISSUE THREAD

**Issue by oxc** [firebase/firebase-tools#5618]
### [REQUIRED] Environment info

**firebase-tools:** 11.18.0

**Platform:** macOS

### [REQUIRED] Test case

Create a functions config that is larger than 8192 bytes in size. Run `execSync('firebase functions:config:get')` on an affected system, and the output will be truncated to 8192 bytes.

So far, we encountered this only on macOS.

Piping this to `| cat` seems to serve as a workaround, even though that seems to contradict the nodejs docs below, which claim that pipes are asynchronous on POSIX systems.

### [REQUIRED] Steps to reproduce

```
firebase functions:config:set foo.bar="$(curl 'https://lipsum.com/feed/json?what=bytes&amount=10000')"
# will be truncated to 8192 bytes
echo "require('child_process').execSync('firebase functions:config:get', { encoding: 'utf8' })" | node -p -
```

```
# prints fully on our test systems
echo "require('child_process').execSync('firebase functions:config:get | cat', { encoding: 'utf8' })" | node -p -
```

### [REQUIRED] Expected behavior

I expect the full json object to be printed to stdout.

### [REQUIRED] Actual behavior

The output gets truncated at 8192 bytes.

### Additional information

As mentioned in the following nodejs docs, stdout might not be fully flushed when process.exit() is called.

https://nodejs.org/api/process.html#a-note-on-process-io
https://nodejs.org/api/process.html#processexitcode

> Calling process.exit() will force the process to exit as quickly as possible even if there are still asynchronous operations pending that have not yet completed fully, including I/O operations to process.stdout and process.stderr.

This seems to be what is happening here. The json object is printed with `logger.info` here:
https://github.com/firebase/firebase-tools/blob/b177da255568c14803fae9629f9492a8f22af936/src/commands/functions-config-get.ts#L33

The `process.exit()` is called here: 
https://github.com/firebase/firebase-tools/blob/b177da255568c14803fae9629f9492a8f22af936/src/command.ts#L220

**Comment by edenhermelin** [comment]
any updates on this one?

**Comment by joehan** [comment]
@edenhermelin I spent some time digging into this this morning. I tried to repro the issue using the MVP provided, and was not able to on macOS. I upped the config size to 100kb, and still could not repro it. Given this, I don't plan to prioritize a fix for this without a stronger reason. If you are running into this as well, could you provide some more detail about what you're seeing, what node version, firebase-tools version, and OS you are on,  and how it is affecting what you want to do?

 I did spend some time looking into whether we could safely remove the `process.exit()` in command.ts. Doing so caused unexpected behavior when exiting `emulators:start` commands. Given the current low impact of this issue and the potential refactors that fixing it might require, I'm not planning to prioritize this right now

**Comment by joehan** [comment]
Forgot to close this, but the root problem here turned out to be that for very large steams, console.log behaves async. Fixed in https://github.com/firebase/firebase-tools/pull/6359
