### ISSUE TITLE
firebase init overwrites existing configuration for projects were set up via the console

### ISSUE THREAD

**Issue by gsoltis** [firebase/firebase-tools#562]
### Steps to reproduce

Create project via console, add some configuration (security rules, firestore indexes, etc.), then run `firebase init` in the directory used for that project. Follow the steps and select the existing project.

### Expected behavior

When running firebase init and selecting an existing project, the configuration files (rules, indexes, etc.) reflect the current configuration of the project.

Having a link in the various configuration screens of the console to the CLI commands to get that configuration would also be helpful.

### Actual behavior

Some files, notably the firestore indexes, are in their default state. Configuration for other services likely are too, but I haven't tried all of them.

**Comment by samtstern** [comment]
@mbleigh do you think this should be default behavior of `firebase init` or something that is enabled by a flag?

**Comment by glennlawyer** [comment]
Firebase init does NOT overwrite the `.firebaserc` file. Additionally, it asks before overwriting other fires. So to me it seems a bug that it overwrites the rules and indicies without warning the user.

**Comment by laurenzlong** [comment]
For realtime database security rules, "firebase init" fetches existing rules that may have been set up through the Firebase Console. It seems like this is a disparity between how Firestore rules/indices behave and how database rules behave. @samtstern Do you know if it'll be possible to do a fetch of the existing Firestore rules and indices during firebase init?

**Comment by samtstern** [comment]
@laurenzlong should be possible:

  * We can already fetch indexes in JSON format by just running `firebase firestore:indexes` so we just need to run that during init and pipe it to the right file.
  * Whatever API the console uses to track rules revisions should make it easy to get the current rules.  But I don't personally have experience with that.

**Comment by laurenzlong** [comment]
Ok cool, I'll ask around.

**Comment by glennlawyer** [comment]
You are right, technically a different issue, but certainly related.

I agree with your description of the ideal behavior; with perhaps some nuance for the case that only local rules exist or only console rules exist. 

Would be great to see this implemented.

**Comment by samtstern** [comment]
I am gonna take a stab at this.

**Comment by laurenzlong** [comment]
Thanks Sam! I believe the database rules behavior is:
- if you have an existing file, ask if you'd like to use it or over-write it
- if you don't have an existing file, fetch the rules from the server and write those into a file
- otherwise, write default rules into a file. 

You'll have to double check the code to make sure. But I think this is easier than asking users to decide between the 2 sets of rules.

**Comment by samtstern** [comment]
Yep I am basically copying that behavior.

**Comment by samtstern** [comment]
@glennlawyer #831 implements the correct behavior for rules, next I can do indexes (which is less pressing since you can't accidentally remove existing indexes using the CLI)

**Comment by glennlawyer** [comment]
@laurenzlong the behavior you describe is clear and logical. Agree that asking users to decide between two sets of rules is awkward.

Now that the script gives more info, if a user wants to override the default behavior, they should be able to do so manually.

**Comment by samtstern** [comment]
Closing this due to #832, should be in the next release (cc: @laurenzlong to maybe comment on that)
