### ISSUE TITLE
Installing firebase-tools (latest, 19.25) and running "firebase use default" fails with module p-limit not found

### ISSUE THREAD

**Issue by gunnarmein-ts** [firebase/firebase-tools#5621]
### [REQUIRED] Environment info

npm install firebase-tools --location=global
run on a github ubuntu worker around 3:40 pm pst

**firebase-tools:**
cannot give you the version that quickly, need to modify job. we presume it was 19.25 since it was published a couple of hours ago.

Ubuntu

**Platform:**

### [REQUIRED] Test case

install firebase-tools and run firebase use default

### [REQUIRED] Steps to reproduce

npm install firebase-tools --location=global
firebase use default

### [REQUIRED] Expected behavior

not crashing

### [REQUIRED] Actual behavior

<img width="1287" alt="image" src="https://user-images.githubusercontent.com/86687645/226762459-5d8e70f5-fddf-4611-8afd-9402a30162a6.png">

We hope we are wrong but we don't see how. The script ran fine this morning. Thanks for looking!

**Comment by SpencerMartel** [comment]
Same issue as#5619

**Comment by joehan** [comment]
This should be resolved now in version 11.25.1 - apologies for the trouble!
