### ISSUE TITLE
nextJs deployment hangs/stuck at stage "Building a Cloud Function to run this application"

### ISSUE THREAD

**Issue by hkropp** [firebase/firebase-tools#5622]
### [REQUIRED] Environment info

nextJs / firebase hosting

nodejs ﻿v18.13.0

**firebase-tools:**
firebase-tool >= v11.23.0

**Platform:**
macOS
### [REQUIRED] Test case

* firebase deploy --only hosting

### [REQUIRED] Steps to reproduce

* try deploy nextJS project with firebase >= v11.23.0

### [REQUIRED] Expected behavior

* works with firebase-tools <= v11.19.0

### [REQUIRED] Actual behavior

* hangs is stuck
* https://stackoverflow.com/questions/75581545/stuck-or-hanging-issue-when-deploying-a-nextjs-app-to-firebase-hosting

No relevant debug output. Just hangs.

Is working with v11.19.0 (and probably below). Bug likely introduced after that. Probably related to the Cloud Run changes.

**Comment by jamesdaniels** [comment]
We now time out while bundling the next.config.js, it should proceed with a warning.
