### ISSUE TITLE
Predeploy functions not firing for Functions using Typescript 

### ISSUE THREAD

**Issue by MidnightLightning** [firebase/firebase-tools#5627]
### [REQUIRED] Environment info

**firebase-tools:** v11.25.1

**Platform:** macOS, running inside Docker with source code mounted on host

### [REQUIRED] Test case

```
docker run -it --rm -u node -v ${PWD}:/app -w /app node:16 bash
npm install -g firebase-tools
firebase login --no-localhost
firebase init
```

Choosing just Functions, yes to Typescript, no to esLint, yes to install dependencies now. Edit `/functions/src/index.ts` and uncomment the template `helloWorld` function.

```
firebase --debug emulators:start
```
That starts the emulators, but fails to deploy the Function:

```
[2023-03-23T13:17:20.638Z] Validating nodejs source
[2023-03-23T13:17:21.279Z] > [functions] package.json contents: {
  "name": "functions",
  "scripts": {
    "build": "tsc",
    "build:watch": "tsc --watch",
    "serve": "npm run build && firebase emulators:start --only functions",
    "shell": "npm run build && firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "engines": {
    "node": "16"
  },
  "main": "lib/index.js",
  "dependencies": {
    "firebase-admin": "^11.5.0",
    "firebase-functions": "^4.2.0"
  },
  "devDependencies": {
    "typescript": "^4.9.0",
    "firebase-functions-test": "^3.0.0"
  },
  "private": true
}
⬢  functions: Failed to load function definition from source: FirebaseError: There was an error reading functions/package.json:

 functions/lib/index.js does not exist, can't deploy Cloud Functions {"metadata":{"emulator":{"name":"functions"},"message":"Failed to load function definition from source: FirebaseError: There was an error reading functions/package.json:\n\n functions/lib/index.js does not exist, can't deploy Cloud Functions"}}
```

### [REQUIRED] Steps to reproduce

Included in test case

### [REQUIRED] Expected behavior

The default installation of Firebase (`firebase init`) sets up a `/firebase.json` with `"predeploy": ["npm --prefix \"$RESOURCE_DIR\" run build"]` and a `/functions/package.json` that has `"scripts": { "build": "tsc" }` in it.

Therefore, upon startup, the "predeploy" action from the overall project should fire, and do the Typescript compiling, before deciding if it can be deployed.

### [REQUIRED] Actual behavior

The startup flow for the emulator suite seems to be validating the `/functions/package.json` first (to tell if it has proper `script` actions defined?), but that call is failing (because `/functions/package.json` defines "main" as `/functions/lib/index.js`, which doesn't exist until `tsc` builds it), and therefore the "predeploy" action seems to be skipped.

Additionally, the emulator suite does start, and appears to be watching the `/functions/src` folder for changes. If I then make a change to `index.ts`, the emulator process notices, and tries to rebuild, but hits that same "functions/lib/index.js does not exist, can't deploy Cloud Functions" error.

If I stop the emulator process, do a `npm run build` action manually, that succeeds and makes a `/functions/lib/index.js` file.

Then a `firebase --debug emulators:start` command finds and deploys the `helloWorld` function that was just complied. However, if a change is then made to `/functions/src/index.ts` (the source Typescript file), the running process sees it and does:

```
2023-03-23T13:31:03.472Z] File /app/functions/src/index.ts changed, reloading triggers {"metadata":{"emulator":{"name":"functions"},"message":"File /app/functions/src/index.ts changed, reloading triggers"}}
[2023-03-23T13:31:04.475Z] Validating nodejs source
[2023-03-23T13:31:05.094Z] > [functions] package.json contents: {
  "name": "functions",
  "scripts": {
    "build": "tsc",
    "build:watch": "tsc --watch",
    "serve": "npm run build && firebase emulators:start --only functions",
    "shell": "npm run build && firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "engines": {
    "node": "16"
  },
  "main": "lib/index.js",
  "dependencies": {
    "firebase-admin": "^11.5.0",
    "firebase-functions": "^4.2.0"
  },
  "devDependencies": {
    "typescript": "^4.9.0",
    "firebase-functions-test": "^3.0.0"
  },
  "private": true
}
[2023-03-23T13:31:05.096Z] Building nodejs source
[2023-03-23T13:31:05.097Z] Failed to find version of module node: reached end of search path /app/functions/node_modules
✔  functions: Using node@16 from host. 
[2023-03-23T13:31:05.103Z] Could not find functions.yaml. Must use http discovery
[2023-03-23T13:31:05.106Z] Found firebase-functions binary at '/app/functions/node_modules/.bin/firebase-functions'
[2023-03-23T13:31:05.819Z] Serving at port 8360

[2023-03-23T13:31:06.761Z] Got response from /__/functions.yaml {"endpoints":{"helloWorld":{"platform":"gcfv1","availableMemoryMb":null,"timeoutSeconds":null,"minInstances":null,"maxInstances":null,"ingressSettings":null,"serviceAccountEmail":null,"vpc":null,"httpsTrigger":{},"entryPoint":"helloWorld"}},"specVersion":"v1alpha1","requiredAPIs":[]}
[2023-03-23T13:31:06.767Z] shutdown requested via /__/quitquitquit

✔  functions: Loaded functions definitions from source: helloWorld. {"metadata":{"emulator":{"name":"functions"},"message":"Loaded functions definitions from source: helloWorld."}}
```

It first declares an error finding "version of module node", however the `/functions/package.json` file has an `"engines": { "node": 16 }` declaration in it?

It then looks for a `/functions/functions.yaml` and cannot find it (which is accurate; the setup process doesn't create one), and it falls back to using "http discovery". It sees the `helloWorld` function, and reloads it "from source", but that appears to be the `/functions/lib/index.js` file as it was previously; it doesn't do a `npm run build` (no "predeploy") and does not pick up the changes that were just made to `/functions/src/index.ts` (which were what triggered the redeploy in the first place).

I would expect in both scenarios (initial startup, and noticing a source file changed), the "Building nodejs source..." step would include running the "predeploy" hooks (which would recompile the Typescript module).

**Comment by blidd-google** [comment]
Hi @MidnightLightning, the functions emulator does not run the pre-deploy hooks by design — they are specifically for the firebase CLI to run prior to deploying the functions to production, and my sense is that it would be surprising behavior to run the hooks prior to spinning up the functions emulator as well.

Thus, we recommend running `npm run build` to compile your Typescript code before starting the emulators, as you may have noticed in the `serve` script we provide in our default functions setup (`"serve": "npm run build && firebase emulators:start --only functions"`).

If you would like code changes to be immediately compiled and reflected in your emulated functions, I would try running `npm run build:watch` in another shell and then `npm run serve`. Any changes you make to your code upon save will then be propagated to your emulated functions automatically, without having to run any extra commands.

I hope this helps!

**Comment by blidd-google** [comment]
These are indeed hitches in the emulator developer experience — adding a "compilation" step to the emulator's live code watching to avoid running two processes is a valid feature request that would improve the emulator's intuitiveness.

> would highly recommend using a different term than "deploy" for "bringing up a local version of a function in the Emulator suite"

This is also a fair point, and I can see how overloading the term "deploy" could cause confusion for developers.

I've opened a feature request at https://github.com/firebase/firebase-tools/issues/5633 to track this request. Thanks for flagging this issue, and hopefully we can design and implement a better devx for emulator developers.
