### ISSUE TITLE
Functions deployment fails with firebase-tools import on Node 18

### ISSUE THREAD

**Issue by andrewkrippner** [firebase/firebase-tools#5631]
### [REQUIRED] Environment info

firebase-tools: 11.25.1

Platform: macOS (local), GitHub Actions

### [REQUIRED] Test case

Basic firebase functions repo. Deployment works with node 16 specified in the package.json engines field.

Dependencies used in functions are: 

```
"dependencies": {
        "@hubspot/api-client": "8.2.0",
        "@sendgrid/mail": "7.7.0",
        "@xmldom/xmldom": "0.8.0",
        "canvas": "2.11.0",
        "firebase-admin": "11.5.0",
        "firebase-functions": "4.2.1",
        "firebase-tools": "11.25.1",
        "jsdom": "21.1.0",
        "makerjs": "0.17.6",
        "paper": "0.12.17",
        "stripe": "11.16.0"
},
```

### [REQUIRED] Steps to reproduce

Change engine to Node 18.

Run `firebase deploy --only functions`

### [REQUIRED] Expected behavior

Successful deployment, as it does with Node 16.

### [REQUIRED] Actual behavior

Failure to deploy.

```
Could not load the function, shutting down.
. Please visit https://cloud.google.com/functions/docs/troubleshooting for in-depth troubleshooting documentation.
Function failed on loading user code. This is likely due to a bug in the user code. Error message: Provided module can't be loaded.
Is there a syntax error in your code?
Detailed stack trace: Error: ENOENT: no such file or directory, mkdir '/www-data-home/.config/configstore'
    at Object.mkdirSync (node:fs:1395:3)
    at module.exports.sync (/workspace/node_modules/firebase-tools/node_modules/make-dir/index.js:114:6)
    at set all [as all] (/workspace/node_modules/firebase-tools/node_modules/configstore/index.js:59:12)
    at Configstore.set (/workspace/node_modules/firebase-tools/node_modules/configstore/index.js:91:12)
    at Object.<anonymous> (/workspace/node_modules/firebase-tools/lib/track.js:20:31)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
```

**Comment by aalej** [comment]
Hi @andrewkrippner, thanks for reaching out to us. I am unable to replicate the issue you mentioned. I tried changing the engine to Node 18 and copied over the dependencies you've provided, but I did not encounter any issues deploying functions. 

I’m not sure if I’m missing anything to properly replicate this, so I’d like to ask if it would be possible if you can provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) so that I can reproduce the issue on my end?

**Comment by andrewkrippner** [comment]
> Hi @andrewkrippner, thanks for reaching out to us. I am unable to replicate the issue you mentioned. I tried changing the engine to Node 18 and copied over the dependencies you've provided, but I did not encounter any issues deploying functions. 
> 
> 
> 
> I’m not sure if I’m missing anything to properly replicate this, so I’d like to ask if it would be possible if you can provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) so that I can reproduce the issue on my end?

Ok thank you for taking a look. I'll work on getting the bug pinned down when I find some time. I suspect it has to do with the require import for the firebase tools dependency

**Comment by joehan** [comment]
Hey @andrewkrippner, thanks for reporting this. Looks like you're running into an issue we're aware of, where importing firebase-tools causes build failures for Node 18 functions. We're looking into better error handling to prevent this issue.

**Comment by andrewkrippner** [comment]
> Hey @andrewkrippner, thanks for reporting this. Looks like you're running into an issue we're aware of, where importing firebase-tools causes build failures for Node 18 functions. We're looking into better error handling to prevent this issue.

Excellent thank you. To be clear, local building works but deployment to functions fails.

**Comment by TrustyTechSG** [comment]
Im having the exact same issue, local dev is OK, can't make deployment. Just tried downgrade to node 16 works. thanks a lot @andrewkrippner
