### ISSUE TITLE
auth emulator creates a user with empty strings for email and password, using createUserWithEmailAndPassword

### ISSUE THREAD

**Issue by isbogdanov** [firebase/firebase-tools#5639]
### [REQUIRED] Environment info

**firebase-tools:** 11.25.1

**Platform:**mac os, nmp

### [REQUIRED] Test case

Auth emulator creates a user with empty email and password.

          const email = ""; 
          const password = ""; 
          await createUserWithEmailAndPassword(auth, email, password)
            .then((user) => {
              console.log("Registered and logged in:", user);
            })
            .catch((error) => {console.log(error)}

### [REQUIRED] Steps to reproduce

Passing empty strings to createUserWithEmailAndPassword results in account creation and signing in with the created user credentials, even though credentials lack. Basically it resembles anonymous login, but the created and signed in **current user** is not anonymous (isAnonymous: false) despite the fact that all object fields except for uid are empty. 

At the same time deployed version does not allow for empty strings to be passed to createUserWithEmailAndPassword. Doing so results in error "auth/invalid-email"

### [REQUIRED] Expected behavior

Expected throwing an error "auth/invalid-email"

### [REQUIRED] Actual behavior

Empty account gets created

**Comment by aalej** [comment]
Hi @isbogdanov, thanks for reporting this issue. I was able to replicate the behavior you mentioned. When using the Auth emulator, a user is created with a blank email address. But when connecting to a Firebase project, an error is raised. I’ll notify our team about this so that they can take a look, and I’ll be marking this as reproducible.

**Comment by aalej** [comment]
Hi, this should be fixed in [#5906](https://github.com/firebase/firebase-tools/pull/5906). That said, I’ll be closing this issue. Feel free to ask this to be reopened if the issue still occurs. Thanks!
