### ISSUE TITLE
Emulator cannot start up when multiple projects defined and not logged in

### ISSUE THREAD

**Issue by MidnightLightning** [firebase/firebase-tools#5647]
### [REQUIRED] Environment info

**firebase-tools:** 11.25.1

**Platform:** macOS

### [REQUIRED] Test case

Run `firebase init`, then modify `.firebaserc` to have multiple projects defined. For example:

```json
{
  "projects": {
    "default": "my-prod-project",
    "dev": "my-dev-project"
  }
}
```

### [REQUIRED] Steps to reproduce

Run `firebase emulators:start --project=default`.

### [REQUIRED] Expected behavior

The `--project` flag should be honored (as documented at https://firebase.google.com/docs/cli/#use_aliases) and pick the project to run as.

### [REQUIRED] Actual behavior

The emulator fails to start, with an error of: 

```
Error: No project active, but project aliases are available.

Run firebase use <alias> with one of these options:
```

If you try and use `firebase use default`, it errors out with `Error: Failed to authenticate, have you run firebase login?`. However a key feature of the emulator suite is it can run without being authenticated (removing one of the two project configs from `.firebaserc` allows it to start up just fine without doing a `firebase login` first).

**Comment by aalej** [comment]
Hi @MidnightLightning, thanks for reaching out to us. I am unable to reproduce the issue you mentioned. I’m using `firebase-tools` v11.25.2 on a macOS and here are the steps I took:

1. Run `firebase login`
2. Run `firebase init emulators --project=<project_id_1>`
3. Modify the `.firebaserc` file to:
```
{
 "projects": {
   "default": "<project_id_1>",
   "dev": "<project_id_2>"
 }
}
```
4. Run `firebase logout`
5. Run `firebase emulators:start --project=default`. A warning is shown, but I was able to start the emulator:
```
⚠  emulators: You are not currently authenticated so some features may not work correctly. Please run firebase login to authenticate the CLI.
```

Could you verify if these are also the steps you took, and share with us the debug logs after running `firebase emulators:start --project=default --debug`? If I’m missing a step, please let me know.

**Comment by christhompsongoogle** [comment]
IIUC without the `demo-` prefix the emulators will attempt to fetch metadata from the firebase backend. In order to run while logged out use a project ID that starts with `demo-` and that should allow local running of the emulator suite (with some exceptions for non-GA emulators).

**Comment by joehan** [comment]
@MidnightLightning Glad that you were able to get around this issue. I don't believe we actually cache this info - however, if you ever want to 'clear the cache' for firebase-tools and get rid of any saved aliases/logins/default projects, you can delete the following files:

 `~/.config/configstore/firebase-tools.json` (holds info about logins, default projects for directories, and analytics optin/optout)
`.firebaserc` (One per firebase project directory - holds info about aliases)
`~/.cache/firebase` (Holds JAR files for downloaded emulators, and downloaded extensions code)
