### ISSUE TITLE
Deploying to firebase hosting fails for NextJS site

### ISSUE THREAD

**Issue by nichitaAdns** [firebase/firebase-tools#5649]
### [REQUIRED] Environment info

**firebase-tools:**  11.25.2

**Platform:** macOS

### [REQUIRED] Test case

Seems to work on a brand new website, but does not work on my project. O should mention my project has billing enabled, it's on the Blaze plan (despite the error message suggesting I should add a billing method)

### [REQUIRED] Steps to reproduce

I run firebase deploy --only hosting, and I get:

✔  functions: functions folder uploaded successfully
✔  functions: .firebase/xx/functions folder uploaded successfully
i  hosting[xx]: beginning deploy...
i  hosting[xx]: found 84 files in .firebase/xx/hosting
✔  hosting[xx]: file upload complete
i  functions: updating Node.js 16 function firebase-frameworks-xx:ssrxx(us-central1)...
⚠  functions: HTTP Error: 400, Could not update Cloud Run service projects/xx/locations/us-central1/services/ssrxx. spec.template.spec.containers.resources.limits.memory: Invalid value specified for memory. For the specified value, maxScale may not exceed 80.
Consider running your workload in a region with greater capacity, decreasing your requested memory-per-instances, or requesting an increase in quota for this region if you are seeing sustained usage near this limit, see https://cloud.google.com/run/quotas. Your project may gain access to further scaling by adding billing information to your account.
⚠  functions: failed to update function projects/xx/locations/us-central1/functions/ssrxx
Failed to update function projects/xx/locations/us-central1/functions/ssrxx

### [REQUIRED] Expected behavior

I expect the new version to deploy successfully

### [REQUIRED] Actual behavior

It crashes, see above logs for information. Looks like I could fix it if I could specify a memory maxScale, but I don't think there's a way to do that from the CLI currently..?

**Comment by atco-jh** [comment]
Can you post your firebase config and nextjs config? I'm having a similar issue with deployments, but I'm not getting the same error.

**Comment by ZNickq** [comment]
Hi @atco-jh , nextjs config:

`const path = require('path')

/** @type {import('next').NextConfig} */

module.exports = {
  trailingSlash: true,
  reactStrictMode: false,
  experimental: {
    esmExternals: false,
    jsconfigPaths: true // enables it for both jsconfig.json and tsconfig.json
  },
  webpack: config => {
    config.resolve.alias = {
      ...config.resolve.alias,
      apexcharts: path.resolve(__dirname, './node_modules/apexcharts-clevision')
    }

    return config
  },
  async redirects() {
    return [
      {
        source: '/f/:path*',
        destination: '/subclient-form/:path*',
        permanent: false
      },
    ]
  }
}
`

Firebase config:
`{
  "firestore": {
    "rules": "firestore.rules"
  },
  "functions": {
    "predeploy": [
      "npm --prefix \"$RESOURCE_DIR\" run build"
    ]
  },
  "hosting": {
    "source": "frontend",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ]
  },
  "storage": {
    "rules": "storage.rules"
  }
}
`

Folder structure:
<img width="321" alt="Screenshot 2023-04-11 at 14 06 23" src="https://user-images.githubusercontent.com/980516/231142034-5c4621bb-74a1-42d4-8aa7-b6f17d7904d7.png">


I use SSR in a few functions. I deployed this project sucessfully with all of these settings for a few months, but it's crashing now (on both the dev and prod firebase projects)

**Comment by avilao** [comment]
I also have this problem but for some reason this specific project limit is 10. Is there a way to set a limit on firebase.json or something?

**Comment by jamesdaniels** [comment]
You can configure this in your firebase.json, [`hosting.frameworksBackend.maxInstances`](https://github.com/FirebaseExtended/firebase-framework-tools#configuring-your-backend)
