### ISSUE TITLE
Why does firebase deploy list a static page as non-static

### ISSUE THREAD

**Issue by vp-walter** [firebase/firebase-tools#5660]
### [REQUIRED] Environment info

When I try to deploy a next project, the pages marked as static by next build are given as reasons why cloud functions are needed (subsequently causing cold start delays rather than serving static pages from cdn).

**firebase-tools:** using 11.19.0 but tried others as well

**Platform:** Windows

### [REQUIRED] Steps to reproduce

First I'm hoping someone can just clarify if I am misunderstanding something (see the actual behavior below).

### [REQUIRED] Expected behavior

I expect cloud functions to only apply to the api routes and the server side rendered pages.

### [REQUIRED] Actual behavior

I have a Next.js 12 project, with a page that has minimal stuff in it:
```
const Dashboards = () => {
  return <div>This is the Dashboards page</div>;
};

export default Dashboards;
```

but then firebase deploy lists this as a reason why it needs cloud functions even though next.js lists this as a static page.

```
Route (pages)                              Size     First Load JS
┌   /_app                                  0 B             349 kB
├ λ /[provider]                            5.61 kB         355 kB
├ ○ /404                                   194 B           350 kB
├ λ /api/hello                             0 B             349 kB
├ ○ /charts (657 ms)                       73.3 kB         423 kB
├ ○ /dashboards                            274 B           350 kB
├ ○ /our-approach                          1.15 kB         351 kB
├ ○ /research                              344 B           350 kB
├ ○ /search (1804 ms)                      272 B           350 kB
├ ○ /security                              1.37 kB         351 kB
└ ○ /user/settings                         4.99 kB         354 kB
+ First Load JS shared by all              350 kB
  ├ chunks/framework-4556c45dd113b893.js   45.2 kB
  ├ chunks/main-d2fa5d94e1c1d6ef.js        31.3 kB
  ├ chunks/pages/_app-2bbab969a0265f20.js  271 kB
  ├ chunks/webpack-7366c3a031b580cf.js     1.88 kB
  └ css/d25682aacd1f4b07.css               1.09 kB

λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)

Building a Cloud Function to run this application. This is needed due to:
 • non-static route /api/hello
 • non-static route /charts
 • non-static route /dashboards
 • non-static route /our-approach
 • non-static route /research
 • and 5 other reasons, use --debug to see more
```
I deleted the next.config.js file, tried different versions of firebase, downgraded next from 13 to 12 and eliminated other elements of next that I though might be contributing (like font optimization). I think there is something basic about firebase webframework deploy that I am not understanding.

**Comment by jamesdaniels** [comment]
The current test checks the .next/server/pages-manifest.json and compares it the prerender manifest—any paths that we find that haven't been prerendered are marked a requiring a backend. The logic is here https://github.com/firebase/firebase-tools/blob/0a4a4c2a3ed8a0b63cd82ac6a1a6834bb558c933/src/frameworks/next/index.ts#L140

Do you mind peeking at those manifest files and letting me know if you see anything obviously off with the heuristic?

**Comment by vp-walter** [comment]
Thanks for getting back to me so quickly. After looking through the next build code  and inspecting the manifest files I have some thoughts. First,

Here is the pages-manifest:

```
{
  "/_app": "pages/_app.js",
  "/_document": "pages/_document.js",
  "/_error": "pages/_error.js",
  "/api/hello": "pages/api/hello.js",
  "/charts": "pages/charts.html",
  "/dashboards": "pages/dashboards.html",
  "/research": "pages/research.html",
  "/search": "pages/search.html",
  "/user/settings": "pages/user/settings.html",
  "/security": "pages/security.html",
  "/[provider]": "pages/[provider].js",
  "/404": "pages/404.html"
}
```

and here is the prerender-manifest.json

```
{
  "version": 4,
  "routes": {},
  "dynamicRoutes": {},
  "preview": {
    "previewModeId": "be19391efc29541249f5eda1d2081238",
    "previewModeSigningKey": "f6656c01593210d1b7a73cc2245b691e12aba59945e691b72ec44ad39748baf4",
    "previewModeEncryptionKey": "56915c1bd77f3fda13d98e2c7a0b30196dd75214a5ebf077fe269e672f0c0075"
  },
  "notFoundRoutes": []
}
```

and here is the routes-manifest.json

```
{
  "version": 3,
  "pages404": true,
  "basePath": "",
  "redirects": [
    {
      "source": "/:path+/",
      "destination": "/:path+",
      "internal": true,
      "statusCode": 308,
      "regex": "^(?:/((?:[^/]+?)(?:/(?:[^/]+?))*))/$"
    },
    {
      "source": "/",
      "destination": "/research",
      "statusCode": 308,
      "regex": "^(?!/_next)/(?:/)?$"
    }
  ],
  "headers": [],
  "dynamicRoutes": [
    {
      "page": "/[provider]",
      "regex": "^/([^/]+?)(?:/)?$",
      "routeKeys": {"provider": "provider"},
      "namedRegex": "^/(?<provider>[^/]+?)(?:/)?$"
    }
  ],
  "staticRoutes": [
    {
      "page": "/charts",
      "regex": "^/charts(?:/)?$",
      "routeKeys": {},
      "namedRegex": "^/charts(?:/)?$"
    },
    {
      "page": "/dashboards",
      "regex": "^/dashboards(?:/)?$",
      "routeKeys": {},
      "namedRegex": "^/dashboards(?:/)?$"
    },
    {
      "page": "/research",
      "regex": "^/research(?:/)?$",
      "routeKeys": {},
      "namedRegex": "^/research(?:/)?$"
    },
    {
      "page": "/search",
      "regex": "^/search(?:/)?$",
      "routeKeys": {},
      "namedRegex": "^/search(?:/)?$"
    },
    {
      "page": "/security",
      "regex": "^/security(?:/)?$",
      "routeKeys": {},
      "namedRegex": "^/security(?:/)?$"
    },
    {
      "page": "/user/settings",
      "regex": "^/user/settings(?:/)?$",
      "routeKeys": {},
      "namedRegex": "^/user/settings(?:/)?$"
    }
  ],
  "dataRoutes": [
    {
      "page": "/[provider]",
      "routeKeys": {"provider": "provider"},
      "dataRouteRegex": "^/_next/data/Ekne4IulbzrDLoTFumlp0/([^/]+?)\\.json$",
      "namedDataRouteRegex": "^/_next/data/Ekne4IulbzrDLoTFumlp0/(?<provider>[^/]+?)\\.json$"
    }
  ],
  "rsc": {
    "header": "RSC",
    "varyHeader": "RSC, Next-Router-State-Tree, Next-Router-Prefetch",
    "contentTypeHeader": "text/x-component"
  },
  "rewrites": []
}
```

I am not sure if the usage of these manifest files depends on the next version being used, but just from those manifest files it's not clear to me what the prerender-manifest does (is that used for sites that explicitly have static props in the page?).

It seems to me that a page with html output in the pages-manifest and in the 'staticRoutes' of routes-manifest does not need to be included in the firebase function?

[I am looking at these lines in the next build code](https://github.com/vercel/next.js/blob/3a49a29a7068ce7fb516f349d89416b99e4f8f87/packages/next/src/build/index.ts#L2589)

What do you think? would it make sense to change the heuristic a bit?

**Comment by jamesdaniels** [comment]
Agree, if the extension is .html we should be good.

**Comment by vp-walter** [comment]
awesome. thank you for adding the change so quickly!
