### ISSUE TITLE
Running firebase deploy for Next Js 

### ISSUE THREAD

**Issue by friday-sds** [firebase/firebase-tools#5661]
### [REQUIRED] Environment info

**firebase-tools: 11.25.2**
**Node Js: 16.14.2**

**Platform: macOS (m1 / arm64)**

### [REQUIRED] Steps to reproduce

Try following this [doc](https://firebase.google.com/docs/hosting/frameworks/nextjs) for a basic next js 13 (appDir) project

### [REQUIRED] Expected behavior
Your app should deploy in firebase hosting and you will have an url 

### [REQUIRED] Actual behavior
Getting this error 
`Building a Cloud Function to run this application. This is needed due to:
 • app directory (unstable)

info  - Creating an optimized production build ...[2023-04-05T12:05:37.437Z] TypeError: Cannot read properties of null (reading 'endsWith')
    at ɵcodegenPublicDirectory (/Users/xyz/.cache/firebase/tools/lib/node_modules/firebase-tools/lib/frameworks/next/index.js:206:56)
    at async prepareFrameworks (/Users/xyz/.cache/firebase/tools/lib/node_modules/firebase-tools/lib/frameworks/index.js:269:13)
    at async deploy (/Users/xyz/.cache/firebase/tools/lib/node_modules/firebase-tools/lib/deploy/index.js:53:13)

Error: An unexpected error has occurred.
info  - Creating an optimized production build ..%`

Next Js Config
`/** @type {import('next').NextConfig} */
const nextConfig = {
  experimental: {
    appDir: true,
  },
}

module.exports = nextConfig`

**Comment by jamesdaniels** [comment]
My guess is NextJS altered one of the manifest files (for the app directory) that we're peaking in to export static content for the CDN. 

That line of code we're testing whether we're dealing with a React Server Component, so we can copy from the correct directory. I'll take a peek, thanks for the report.

**Comment by friday-sds** [comment]
My guess is it has something to do with the `api` routes for app directory

**Comment by jamesdaniels** [comment]
@friday-sds that would make sense, as it's app directory & in that manifest but not an RSC with json that needs rehydration. I'll see if I can repro.

**Comment by PanosParalakis** [comment]
@jamesdaniels  any updates regarding this issue ?

**Comment by jamesdaniels** [comment]
@friday-sds @PanosParalakis mind giving the fixes a spin `npm i -g github:firebase/firebase-tools#frameworksCTA`? Let me know how it goes

**Comment by PanosParalakis** [comment]
@jamesdaniels  I think it tries to build and no matter how many dependencies I install globally l keep getting errors when trying to install. 

`❯ npm i -g github:firebase/firebase-tools#frameworksCTA
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 127
npm ERR! git dep preparation failed
npm ERR! command /.nvm/versions/node/v18.15.0/bin/node /.nvm/versions/node/v18.15.0/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm ERR! code 127
npm ERR! npm ERR! path /.npm/_cacache/tmp/git-clonekmnjgl
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command sh -c npm run clean && npm run build:publish
npm ERR! npm ERR! > firebase-tools@11.27.0 clean
npm ERR! npm ERR! > rimraf lib dev
npm ERR! npm ERR!
npm ERR! npm ERR!
npm ERR! npm ERR! > firebase-tools@11.27.0 build:publish
npm ERR! npm ERR! > tsc --build tsconfig.publish.json && npm run copyfiles
npm ERR! npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm ERR! sh: tsc: command not found`

**Comment by PanosParalakis** [comment]
Hi @jamesdaniels  did you manage to look at this issue further? TY!

**Comment by joenewbry** [comment]
Hi based on the logs for me. There's an error here:

`const isReactServerComponent = route.dataRoute.endsWith(".rsc");`

And that's from looking at the firebase-debug.log line:
`TypeError: Cannot read properties of null (reading 'endsWith')
    at ɵcodegenPublicDirectory (/usr/local/lib/node_modules/firebase-tools/lib/frameworks/next/index.js:206:56)`

**Comment by joenewbry** [comment]
@jamesdaniels trying out the branch you mentioned and I'll let you know how the deploy goes

**Comment by joenewbry** [comment]
Not sure if it's helpful. It looks like certain routes don't have a corresponding dataRoute.

`
{
  initialRevalidateSeconds: false,
  srcRoute: '/admin',
  dataRoute: '/admin.rsc'
}
{
  initialRevalidateSeconds: false,
  srcRoute: '/signup',
  dataRoute: '/signup.rsc'
}
{
  initialRevalidateSeconds: false,
  srcRoute: '/signin',
  dataRoute: '/signin.rsc'
}
{
  initialHeaders: { 'content-type': 'text/plain;charset=UTF-8' },
  initialRevalidateSeconds: false,
  srcRoute: '/api/hello',
  dataRoute: null
}
`

**Comment by joenewbry** [comment]
from the prerenderedManifest it looks like the dataRoutes for favicon.ico is also null

`
    '/favicon.ico': {
      initialHeaders: [Object],
      initialRevalidateSeconds: false,
      srcRoute: '/favicon.ico',
      dataRoute: null
`

**Comment by joenewbry** [comment]
@jamesdaniels the branch worked for me! 🙌 thanks!

**Comment by joenewbry** [comment]
Also kinda dumb question but I'm wondering what the difference between using `npm i -g github:firebase/firebase-tools#frameworksCTA` and cloning the repository locally and running `npm i` and `npm link`?


I wasn't able to use `npm i -g github:firebase/firebase-tools#frameworksCTA`. A bunch of things broke for me when I tried that but the cloning locally and then installing method worked great!

**From npm i**
`joe@joes-mbp my-app % npm i -g github:firebase/firebase-tools#frameworksCTA
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! git dep preparation failed
npm ERR! command /Users/joe/.nvm/versions/node/v16.20.0/bin/node /Users/joe/.nvm/versions/node/v16.20.0/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/Users/joe/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm ERR! code 1
npm ERR! npm ERR! path /Users/joe/.npm/_cacache/tmp/git-cloneHifUji
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command sh -c -- npm run clean && npm run build:publish
npm ERR! npm ERR! > firebase-tools@11.27.0 clean
npm ERR! npm ERR! > rimraf lib dev
npm ERR! npm ERR! 
npm ERR! npm ERR! 
npm ERR! npm ERR! > firebase-tools@11.27.0 build:publish
npm ERR! npm ERR! > tsc --build tsconfig.publish.json && npm run copyfiles
npm ERR! npm ERR! 
npm ERR! npm ERR! src/configstore.ts(1,30): error TS2307: Cannot find module 'configstore' or its corresponding type declarations.`

**Comment by PanosParalakis** [comment]
> I wasn't able to use `npm i -g github:firebase/firebase-tools#frameworksCTA`. A bunch of things broke for me when I tried that but the cloning locally and then installing method worked great!
> .`

Thanks for that @joenewbry,  I was having similar issue, I did not try cloning but I ll give it a go
