### ISSUE TITLE
Deploy does not add VPC settings to existing functions

### ISSUE THREAD

**Issue by cjsewell** [firebase/firebase-tools#5671]
### [REQUIRED] Environment info

**firebase-tools:** 11.25.3

**Platform:** Ubuntu

### [REQUIRED] Test case

Deploy a cloud function without `vpcConnector`/`vpcConnectorEgressSettings`

Create a VPC and Add `.runWith({ vpcConnector: 'your vpc id, vpcConnectorEgressSettings: 'PRIVATE_RANGES_ONLY' })` and deploy the function again

### [REQUIRED] Steps to reproduce

See  Test case

### [REQUIRED] Expected behavior

The VPC settings to be updated

### [REQUIRED] Actual behavior

VPC setting remain unchanged

**Comment by cjsewell** [comment]
It was a config issue.... Not a bug

**Comment by stfsy** [comment]
@cjsewell Could you elaborate what was wrong? Facing the same problem.

```
export const api = onRequest({
    region: 'europe-west3',
    memory: '1GiB',
    cpu: 1,
    maxInstances: 20,
    concurrency: 20,
    minInstances: 0,
    serviceAccount: process.env.SERVICE_ACCOUNT,
    vpcConnector: process.env.DSQ_GCP_VPC_CONNECTOR,
    vpcConnectorEgressSettings: 'ALL_TRAFFIC'
}, async (...args) => {
   ...
})
```

and `DSQ_GCP_VPC_CONNECTOR` has value `projects/discue-io/locations/europe-west3/connectors/vpc-access-connector` which is the id returned by TF apply

**Comment by stfsy** [comment]
@cjsewell Got it thank you. 

During deployment time of the function, environment variables from .env files are **not** available.

As mentioned in https://github.com/firebase/firebase-functions/issues/1084 we need to use Params, which seem to be resolved later in the process and can have env vars as default.

```js
import { defineString } from 'firebase-functions/params';

const vpcConnectorParam = defineString("DSP_GCP_VPC_CONNECTOR", {
    default: process.env.DSP_GCP_VPC_CONNECTOR
})

setGlobalOptions({
    "vpcConnector": vpcConnectorParam,
    "vpcConnectorEgressSettings": "ALL_TRAFFIC",
})

```
