### ISSUE TITLE
Email Link Auth Emulator not working.

### ISSUE THREAD

**Issue by drayilara** [firebase/firebase-tools#5682]
While using the firebase auth emulator, I cant sign in a user using Email link.
Although a link to sign in user is logged to the emulator console, when I click on it, I get this error: 

`Firebase: Error (auth/invalid-action-code).`

When I check the emulator auth console, no user is produced.

Please note that I have configured my live app to handle continueUrl redirect and everything works fine on the live app(cloud) version of the app.

**Expected behaviour**

I expect that a user should be created in the auth console and a success should be seen in my logs.

**Desktop (please complete the following information):**

- OS: Linux
- Browser: Chrome

**Comment by drayilara** [comment]
Thanks for responding.

Yes, I am sending the link using `sendSignInLinkToEmail`

This is what the sign-in code looks like:

`const handleLogin = (e) => {
    e.preventDefault();
    setLoginLoading(true);
    sendSignInLinkToEmail(auth, email, {
      //This is the URL that we will redirect back to after clicking on the link in the mailbox
      url: process.env.REACT_APP_EMAIL_LINK_AUTH_REDIRECT_URL,
      handleCodeInApp: true,
    })
      .then(() => {
        localStorage.setItem("emailForSignIn", email);
        setLoginLoading(false);
        setLoginError("");
        setInfoMsg("We have sent you an email with a link to sign in");
      })
      .catch((err) => {
        setLoginLoading(false);
        setLoginError(err.message);
      });
  };`

When I initiate handleLogin, a link is logged to my console. This link:

`http://127.0.0.1:9099/emulator/action?mode=signIn&lang=en&oobCode=BRTBrJbdKqDTCd9LduKxVTqtGi8gUtCt7stg4BeEUxCxa9FChbTd1P&apiKey=fake-api-key&continueUrl=https%3A%2F%2Ftribe-of-founders.web.app%2Flogin`

This is very similar to the example in the docs except it has an additional connectUrl param.

On clicking the link, I expect to be routed to `domain/login` where I have this code to log in on the web(according to the docs):

`if (isSignInWithEmailLink(auth, window.location.href)) {
        // now in case user clicks the email link on a different device, we will ask for email confirmation
        let email = localStorage.getItem("emailForSignIn");
        if (!email) {
          email = window.prompt("Please provide your email");
        }
        // after that we will complete the login process
        setInitialLoading(true);
        signInWithEmailLink(
          auth,
          email,
          window.location.href
        )
          .then((result) => {
            // we can get the user from result.user but no need in this case
            console.log(result.user);
            localStorage.removeItem("emailForSignIn");
            setInitialLoading(false);
            setInitialError("");
            navigate("/");
          })
          .catch((err) => {
            setInitialLoading(false);
            setInitialError(err.message);
            navigate("/login");
          });
      }`

`auth is an instance of getAuth(app)` 

My app config looks like this:

`import { initializeApp } from "firebase/app";
import { getAuth, connectAuthEmulator } from "firebase/auth";
//import "firebase/firestore";

const env = process.env;

let firebaseConfig;

firebaseConfig = {
  apiKey: env.REACT_APP_FIREBASE_API_KEY,
  authDomain: env.REACT_APP_FIREBASE_AUTH_DOMAIN,
  projectId: env.REACT_APP_FIREBASE_PROJECT_ID,
  storageBucket: env.REACT_APP_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: env.REACT_APP_FIREBASE_MESSAGING_SENDER_ID,
  appId: env.REACT_APP_FIREBASE_APP_ID,
  measurementId: env.REACT_APP_FIREBASE_MEASUREMENT_ID,
};


const firebaseApp = initializeApp(firebaseConfig);
// const db = firebase.firestore();

if (window.location.hostname === "127.0.0.1") {
  console.log("testing locally -- hitting local auth and firestore emulators");
  connectAuthEmulator(getAuth(), "http://localhost:9099");
}

console.log(firebaseApp.name ? "Firebase Mode Activated!" : "Firebase not working :(");


export default firebaseApp;
`

firebase.json looks like this:

`{
  "hosting": {
    "public": "build",
    "ignore": ["firebase.json", "**/.*", "**/node_modules/**"],
    "rewrites": [
      {
        "source": "**",
        "destination": "/index.html"
      }
    ]
  },
  "emulators": {
    "auth": {
      "host": "localhost",
      "port": 9099
    },
    "firestore": {
      "host": "localhost",
      "port": 8080
    },
    "hosting": {
      "host": "localhost",
      "port": 5000
    },
    "ui": {
      "enabled": true,
      "port": 4000
    }
  }
}
`

Cavaet: I just started building the auth flow for this app, and I have used up the 5 email auth daily allowance on the cloud app. Could this be why I can't run auth on the emulator?
 
Looking forward to your response, thank you.

**Comment by christhompsongoogle** [comment]
@aalej tried to repro this but wasn't successful.

A few notes/questions:

The 5 email auth daily allowance doesn't affect the emulators at all
Is your browser host `localhost` or `127.0.0.1` - there's a combination of the two, it may be causing issues if on an ipv6 machine.

env.REACT_APP_FIREBASE_PROJECT_ID -> does this match the project ID selected when you run `firebase use` ? I'm attempting to rule out the possibility of calling prod instead of the emulator.

**Comment by julia-stamborovski** [comment]
serio que ninguem vai resolver
