### ISSUE TITLE
Secrets created with defineSecret are not firebase-managed

### ISSUE THREAD

**Issue by Schmale97** [firebase/firebase-tools#5689]
### [REQUIRED] Environment info

**firebase-tools:** 11.26.0
**firebase-functions:** 4.2.0

**Platform:** macOD

### [REQUIRED] Test case
```
import * as functions from 'firebase-functions'
import { defineString } from 'firebase-functions/params'

const secret = defineString('SECRET')

export const helloWorld = functions
  .runWith({
    secrets: [secret],
  })
  .https.onCall(() => {
    console.log('HELLO_WORLD')
  })
```
### [REQUIRED] Steps to reproduce

Deploy the above function

Check the secret in GCP Console -> it shows the secret 'SECRET' as being firebase-hosting-managed.

Update the secret in the cli with the command `firebase functions:secrets:set SECRET`

It will show a warning

```
⚠  Your secret is not managed by Firebase. Firebase managed secrets are automatically pruned to reduce your monthly cost for using Secret Manager. 
```

### [REQUIRED] Expected behavior

Secrets setup through defineSecret should be firebase managed

### [REQUIRED] Actual behavior

Secrets setup through defineSecret are not firebase managed

**Comment by jhuleatt** [comment]
Looks like secrets are tagged with `firebase-hosting-managed` on secret creation:

https://github.com/firebase/firebase-tools/blob/e939a2b7e9cd6cfae302eb92ab9ac4e927f88050/src/deploy/functions/params.ts#L460

But then `secrets:set` looks for `firebase-managed`:

https://github.com/firebase/firebase-tools/blob/3efed5a39307953578dd74dc7693e0fbba4b1a9c/src/functions/secrets.ts#L26
