### ISSUE TITLE
Access Firestore from within Next.js app

### ISSUE THREAD

**Issue by MidnightLightning** [firebase/firebase-tools#5694]
### [REQUIRED] Environment info

**firebase-tools:** 11.26.0

**Platform:** macOS, running a Docker container

### [REQUIRED] Test case

- Create Next.js app
- `firebase init`
- `firebase experiments:enable webframeworks`
- `firebase --debug emulators:start`
- Access a page that attempts to use `firebase-admin/firestore.getFirestore` to connect to Firestore

### [REQUIRED] Steps to reproduce

After creating a basic Next.js app, install the `admin-tools` module, and start up the Firebase emulator.

Create a file at `pages/api/myendpoint.ts` with contents like:

```
import { initializeApp } from 'firebase-admin/app'
import { getFirestore, Timestamp } from 'firebase-admin/firestore'
import { NextApiRequest, NextApiResponse } from 'next'

// The Firebase Admin SDK to access Firestore.
initializeApp()
const db = getFirestore()

const handler = async (req: NextApiRequest, res: NextApiResponse) => {
  db.collection('foo').doc('bar').set({ baz: true });
  res.json({ ok: true });
}
export default handler
```

This is a basic page that just tries to connect to the Firebase app and make a connection to Firestore.

### [REQUIRED] Expected behavior

When called, the Next.js API endpoint should just respond with a JSON `{ ok: true }` response.

### [REQUIRED] Actual behavior

```
error - FirebaseAppError: The default Firebase app already exists. This means you called initializeApp() more than once without providing an app name as the second argument. In most cases you only need to call initializeApp() once. But if you do want to initialize multiple apps, pass a second argument to initializeApp() to give each app a unique name.
  at AppStore.initializeApp (/app/node_modules/firebase-admin/lib/app/lifecycle.js:41:23)
  at initializeApp (/app/node_modules/firebase-admin/lib/app/lifecycle.js:102:36)
  at eval (webpack-internal:///(api)/./pages/api/siwe-verify.ts:22:66)
  at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errorInfo: {
    code: 'app/duplicate-app',
    message: 'The default Firebase app already exists. This means you called initializeApp() more than once without providing an app name as the second argument. In most cases you only need to call initializeApp() once. But if you do want to initialize multiple apps, pass a second argument to initializeApp() to give each app a unique name.'
  },
  codePrefix: 'app'
}
```

The server gives an error that the Firebase app is already initialized. However, if I remove the `initializeApp()` call, a different error occurs:

```
Unable to detect a Project Id in the current environment. 
To learn more about authentication and Google APIs, visit: 
https://cloud.google.com/docs/authentication/getting-started
  at GoogleAuth.findAndCacheProjectId (/app/node_modules/google-auth-library/build/src/auth/googleauth.js:123:19)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async Firestore.initializeIfNeeded (/app/node_modules/@google-cloud/firestore/build/src/index.js:1156:35)
  at async WriteBatch._commit (/app/node_modules/@google-cloud/firestore/build/src/write-batch.js:460:9)

...

Caused by: Error
  at WriteBatch.commit (/app/node_modules/@google-cloud/firestore/build/src/write-batch.js:433:23)
  at DocumentReference.set (/app/node_modules/@google-cloud/firestore/build/src/reference.js:393:27)
```

So it progresses past the initialization but then fails to actually interact with the Firestore Emulator.

Does the "webframeworks" process create a Firebase app instance that client apps should hook into instead of trying to initialize their own? Because the Next.js "API" pages get compiled down to be a Function, I would expect it to be able to use the Admin SDK to communicate with the Firestore functionality on the same project it's a Function of.

**Comment by garrett-wombat** [comment]
You have to check if there are already instances of the sdk floating around 
```
const _firebase = getApps().length ? getApp() : initializeApp(config);
```

**Comment by MidnightLightning** [comment]
Aha, thank you for that tip, @garrett-wombat. That got me on the right path for a solution. For my use-case there were also some Firestore configurations that needed to be set up (`.settings()` call) which should only happen if the instance is not configured yet. So for me, this was the solution I needed:

```ts
import { getApps, initializeApp } from 'firebase-admin/app'
import { getFirestore } from 'firebase-admin/firestore'

function getAppFirestore() {
  const existingApps = getApps()
  console.debug('apps', existingApps)
  if (existingApps.length > 0) {
    // Already configured; grab the existing
    return getFirestore(existingApps[0])
  } else {
    // First run; configure the app first
    initializeApp()
    const db = getFirestore()
    db.settings({ ignoreUndefinedProperties: true })
    return db
  }
}
const db = getAppFirestore()
```
