### ISSUE TITLE
Functions v2 named using uppercase letters are not deployed

### ISSUE THREAD

**Issue by jirizavadil** [firebase/firebase-tools#5695]
### Environment info

**firebase-tools:** `11.27.0`

**Platform:** `macOS 13.3`

### Test case

create a function named `tralaLa` with default env, config, etc. and deploy it

### Steps to reproduce

1. create function
2. run `firebase deploy --only functions`

### Expected behavior

deployed function `tralaLa`

### Actual behavior

```
[2023-04-15T07:49:37.658Z] <<< [apiv2][body] GET https://cloudfunctions.googleapis.com/v2/projects/PROJECT_ID/locations/-/functions {}

Error: calls-exportData v2 function name(s) can only contain lower case letters, numbers, hyphens, and not exceed 62 characters in length
```

### Notes
This behavior is now out of sync with Google Cloud Functions v2, which already allows uppercase letters since April 04, 2023: 

`Name must start with a letter followed by up to 62 letters, numbers, hyphens, or underscores and must end with a letter or a number` (from tooltip at https://console.cloud.google.com/functions/add)

release notes: https://cloud.google.com/functions/docs/release-notes#April_04_2023

i was able to deploy `tralaLa` via GCP Console as a v2 function.

**Comment by bkendall** [comment]
I believe this is known and is being worked on, if not fixed already :)
