### ISSUE TITLE
CLI stuck on "Creating node.js function" after upgrade and Unable to update existing deployed functions

### ISSUE THREAD

**Issue by chinomnsoawazie** [firebase/firebase-tools#5696]
### [REQUIRED] Environment info
`node js 18`

**firebase-tools:**

**Platform:**

#### Case 1
- Create a new function
- Run "npm run deploy` via the cli
#### Case 2
- From an existing _deployed_ function folder run `npm run deploy`

#### Case 1
- Create a new function using `firebase init functions`
- Run `npm run deploy` via the cli
#### Case 2
- From an existing _deployed_ function folder run `npm run deploy`

### [REQUIRED] Expected behavior

Case 1: Function is created and deployed
Case 2: Deployed function is updated
### [REQUIRED] Actual behavior
Case 1: 
- After about more than 15 mins, the CLI returns the following error
``` 
Could not create or update Cloud Run service xyzfunction. Reconciling latest revision template. Resource readiness deadline exceeded.
Error: There was an error deploying functions
```
Error from console is something along these lines:
```
run.googleapis.com

v1
xyzproject/revisions/xyzfunction-00001-foq
Ready condition status changed to False for Revision xyzunction-00001-foq with message: Unable to create 0 instances for "xyzfunciton-00001-foq" because there are already 0 in this region.
```

Despite this function seemingly not being created, it shows up on the dashboard.

Case 2: 
Functions deploy had errors with the following functions after about more than 15mins:
```
Could not create or update Cloud Run service slumv1. Creating Service. Resource readiness deadline exceeded.

Functions deploy had errors with the following functions:
	xyzfunction(us-east1)
i  functions: cleaning up build files...

Error: There was an error deploying functions
```

In Case 1, there is an error icon beside the function on the functions console in Firebase
In Case 2, nothing to readily indicate the function is in an error state.

Apparently, Google wants me to pay them to report a bug!

**Comment by TheIronDev** [comment]
I've not been able to reproduce case1 or case2.

Would you be able to share a repo or code snippet (along with the `package.json`)?

Additionally, I'm curious what happens when you attempt both cases with `--debug` (amending `package.json` that is.)

**Comment by puf** [comment]
Hey @chinomnsoawazie . Sorry to hear that you ran into problems deploying your Cloud Functions updates. I can imagine that is stressful and frustrating, and definitely not the experience we want you to have with our products.

If you want us to look into your failing project to see what's going on, we'll either need a log here - or you can [reach out to Firebase support](https://firebase.google.com/support/contact/troubleshooting/) (which is free) and submit it there.
