### ISSUE TITLE
Hosting emulator fails because launch cannot find Vite in bin

### ISSUE THREAD

**Issue by baraya** [firebase/firebase-tools#5705]
### [REQUIRED] Environment info

firebase-tools: ```11.28.0```

Platform: ```Windows```

### [REQUIRED] Test case

npm >9
firebase experiments:enable webframeworks
firebase emulators:start

### [REQUIRED] Steps to reproduce
1. Include Vite or other web hosting option
2. Enable webframeworks option
3. Start emulators

### [REQUIRED] Expected behavior
Vite to start

### [REQUIRED] Actual behavior
Error: Could not find the vite executable.

Notes:
package.json does not have an engines.npm definition and npm bin looks to be dropped in v9. Downgrading with npm install -g npm@8.19.4 fixed the issue.

https://docs.npmjs.com/cli/v8/commands
https://docs.npmjs.com/cli/v9/commands

https://github.com/firebase/firebase-tools/blob/b80de641dae17d4866b6fa3dead8a18396cde1d5/src/frameworks/index.ts#L237

**Comment by baraya** [comment]
Canceling. Node compat matrix for the node version in the package.json shows I should be using npm 8.

**Comment by ideodora** [comment]
@baraya 
> Canceling. Node compat matrix for the node version in the package.json shows I should be using npm 8.

where is the version you described?

**Comment by baraya** [comment]
@ideodora 

https://nodejs.org/en/download/releases
