### ISSUE TITLE
CollectionGroup with a Query returned non existing documents with enableMultiTabIndexedDbPersistence

### ISSUE THREAD

**Issue by darinw** [firebase/firebase-tools#5706]
### [REQUIRED] Environment info

**Firebase CLI:** v11.27.0
**Platform:** Windows 10

### [REQUIRED] Test case
I am getting documents returned to me that do not exist in firestore(that i deleted via emulator ui). They will also not go away after a restart of the emulator(not exporting data). 
### [REQUIRED] Steps to reproduce
0) set security rules to open
1) create a document: bug/bug1 with {name: 'bug report'}
2) create a  document: bug/bug1/comments/comment1 with {author: 'user1'}
3) run the following and notice that the document exists and the collection group finds the document as well
```
enableMultiTabIndexedDbPersistence(firestore)
const myComments = query(collectionGroup(this.afs, '_organizationStaff'), [where('author', '==', 'user1')])
getDocsFromServer(myComments).then( (snap)=> {
  console.log('collection group items', snap.docs.length)
})
getDocFromServer(doc(this.afs, '/bug/bug1/comments/comment1')).then( (doc)=> {
  console.log('doc exists', doc.exists())
})
```
4) in the emulator ui delete the /bug/bug1 AND check "Also delete nested collections and documents"
5) re run the code above and notice that document does not exist when directly request.. it does exist from the collection group.

Note: Restarting the emulator will not resolve this issue, not will recreated the objects and deleting them directly. I was able to get it to clear up once but it mostly can't be removed.

### [REQUIRED] Expected behavior
It should not return in a collection group query after it has been deleted.

### [REQUIRED] Actual behavior
deleting an item will not remove it from collection group queries

**Comment by darinw** [comment]
I actually noticed that i am running with enableMultiTabIndexedDbPersistence() as well.. 

That seems to be required for this issue.. however when the document comes back it does not have fromCache: true

**Comment by TheIronDev** [comment]
Hi @darinw , do you have a repo or code sample where I can reproduce this?

Thank you!
