### ISSUE TITLE
Security vulnerability in pinned vm2 version

### ISSUE THREAD

**Issue by joshtemple** [firebase/firebase-tools#5720]
vm2 is currently pinned to `3.9.11`, which has [a Critical security vulnerability](https://github.com/advisories/GHSA-xj72-wvfv-8985). Because of the way it's defined in `npm-shrinkwrap.json`, we haven't been able to successfully override the vm2 version, either with npm package `overrides` or with external packages like `npm-force-resolution`.

Please update to at least 3.9.17 for the fix, thanks!

**Comment by joehan** [comment]
Thanks for pointing this out! This fix should go in the next release
