### ISSUE TITLE
Error: Could not find the ng executable.

### ISSUE THREAD

**Issue by hittten** [firebase/firebase-tools#5721]
### [REQUIRED] Environment info

**firebase-tools:** v11.28.0

**Platform:** MacOS 13.2.1 (22D68) - 13-inch, M1, 2020

### [REQUIRED] Test case

I'm following this guide https://firebase.google.com/docs/hosting/frameworks/angular to deploy an Angular project with SSR on cloud functions.

### [REQUIRED] Steps to reproduce

1. `nvm install 18.15.0`
2. `npm i -g npm@9.6.5`
3. `npm i firebase-tools@11.28.0`
4. `npm i -g @angular/cli@15.2.6`
5. `ng new myApp`
6. `firebase experiments:enable webframeworks`
7. `firebase init hosting`
? Detected an existing Angular codebase in the current directory, should we use this? **Yes**
? In which region would you like to host server-side content, if applicable? **europe-west1 (Belgium)**
? Set up automatic builds and deploys with GitHub? **No**
8. `firebase deploy` <-- Until here everything works.
9. `ng add @nguniversal/express-engine`
10. `firebase deploy`

Detected a Angular codebase. This is an experimental integration, proceed with caution.

Error: Could not find the ng executable.

Having trouble? Try firebase [command] --help

### [REQUIRED] Expected behavior

A deployed application with an SSR Firebase Cloud function for SSR requests and statics files in Firebase hosting

### [REQUIRED] Actual behavior
[debug] [2023-04-23T11:55:11.853Z] ----------------------------------------------------------------------
[debug] [2023-04-23T11:55:11.854Z] Command:       /Users/xxxxxx/.nvm/versions/node/v18.15.0/bin/node /Users/xxxxxx/.nvm/versions/node/v18.15.0/bin/firebase deploy --debug
[debug] [2023-04-23T11:55:11.854Z] CLI Version:   11.28.0
[debug] [2023-04-23T11:55:11.854Z] Platform:      darwin
[debug] [2023-04-23T11:55:11.855Z] Node Version:  v18.15.0
[debug] [2023-04-23T11:55:11.855Z] Time:          Sun Apr 23 2023 13:55:11 GMT+0200 (Central European Summer Time)
[debug] [2023-04-23T11:55:11.855Z] ----------------------------------------------------------------------
[debug] 
[debug] [2023-04-23T11:55:11.888Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2023-04-23T11:55:11.888Z] > authorizing via signed-in user (xxxxxx@xxxxxx.com)
[debug] [2023-04-23T11:55:11.888Z] [iam] checking project XXXXXXXX for permissions ["firebase.projects.get","firebasehosting.sites.update"]
[debug] [2023-04-23T11:55:11.889Z] > refreshing access token with scopes: []
[debug] [2023-04-23T11:55:11.890Z] >>> [apiv2][query] POST https://www.googleapis.com/oauth2/v3/token [none]
[debug] [2023-04-23T11:55:11.890Z] >>> [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[debug] [2023-04-23T11:55:12.071Z] <<< [apiv2][status] POST https://www.googleapis.com/oauth2/v3/token 200
[debug] [2023-04-23T11:55:12.072Z] <<< [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[debug] [2023-04-23T11:55:12.086Z] >>> [apiv2][query] POST https://cloudresourcemanager.googleapis.com/v1/projects/XXXXXXXX:testIamPermissions [none]
[debug] [2023-04-23T11:55:12.086Z] >>> [apiv2][(partial)header] POST https://cloudresourcemanager.googleapis.com/v1/projects/XXXXXXXX:testIamPermissions x-goog-quota-user=projects/XXXXXXXX
[debug] [2023-04-23T11:55:12.086Z] >>> [apiv2][body] POST https://cloudresourcemanager.googleapis.com/v1/projects/XXXXXXXX:testIamPermissions {"permissions":["firebase.projects.get","firebasehosting.sites.update"]}
[debug] [2023-04-23T11:55:12.716Z] <<< [apiv2][status] POST https://cloudresourcemanager.googleapis.com/v1/projects/XXXXXXXX:testIamPermissions 200
[debug] [2023-04-23T11:55:12.716Z] <<< [apiv2][body] POST https://cloudresourcemanager.googleapis.com/v1/projects/XXXXXXXX:testIamPermissions {"permissions":["firebase.projects.get","firebasehosting.sites.update"]}
[debug] [2023-04-23T11:55:12.718Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/XXXXXXXX [none]
[debug] [2023-04-23T11:55:12.987Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects/XXXXXXXX 200
[debug] [2023-04-23T11:55:12.987Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects/XXXXXXXX {"projectId":"XXXXXXXX","projectNumber":"729501192752","displayName":"XXXXXXXX","name":"projects/XXXXXXXX","resources":{"hostingSite":"XXXXXXXX","storageBucket":"XXXXXXXX.appspot.com","locationId":"europe-west"},"state":"ACTIVE","etag":"1_fce7f316-24e8-4fad-9c3c-8282aebb8bf2"}
[error] 
[error] Error: Could not find the ng executable.

**Comment by jamesdaniels** [comment]
Addressing with #5710, should be out in the next CLI release
