### ISSUE TITLE
Unable to upload appbundle through firebase cli

### ISSUE THREAD

**Issue by nzkn** [firebase/firebase-tools#5723]
### [REQUIRED] Environment info

11.15.0

**Platform:**
macOS

### [REQUIRED] Test case

None

### [REQUIRED] Steps to reproduce

I am trying to distribute aab to firebase app distribution with firebase cli:
`firebase appdistribution:distribute ***.aab --app **** --groups ***`

I am getting following error:
`Error: "This app is not published in the Google Play console.`

The app is published on the internal testing track in google play console:

<img width="835" alt="Screenshot 2023-04-24 at 11 27 45" src="https://user-images.githubusercontent.com/69199372/233947862-1c0de658-4364-47ec-adf3-735988f1d787.png">

Firebase and google console apps are registered with the same package name.

Firebase project is linked to the google play:

<img width="254" alt="Screenshot 2023-04-24 at 11 54 49" src="https://user-images.githubusercontent.com/69199372/233948216-2ffe5aef-416d-49dd-993f-f05c111b2735.png">

<img width="823" alt="Screenshot 2023-04-24 at 11 55 13" src="https://user-images.githubusercontent.com/69199372/233948323-e7721c1d-fec1-46ee-b637-122be24d18f7.png">

### [REQUIRED] Expected behavior

I expect the firebase cli distribution to work.

### [REQUIRED] Actual behavior

Error is returned when distributing the app:
`Error: "This app is not published in the Google Play console.`

**Comment by tejasd** [comment]
Hi @nzkn - can you confirm that the app is listed in one of the following statuses on the **all apps** page: Internal testing (not Draft internal testing), Closed testing, Open testing, or Production?

If it isn't, can you follow the steps (specifically step 2) mentioned at https://firebase.google.com/docs/app-distribution/android/distribute-console?apptype=aab#before-you-begin

**Comment by nzkn** [comment]
It is listed in internal testing track

**Comment by tejasd** [comment]
I'm not sure it's possible to debug the specific conditions which make it unpublished here. It might be worth unlinking, and relinking the app to see if that warning disappears.

If not, can you contact support, and share details so that it might be possible to debug why the app is considered unpublished?

https://firebase.google.com/support/troubleshooter/contact
