### ISSUE TITLE
Local Emulator won't run multiple functions at once

### ISSUE THREAD

**Issue by mashoba7** [firebase/firebase-tools#5729]
### Environment info

**firebase-tools:** 11.28.0

**Platform:** macOS Ventura (13.0)

### Test case
Create 2 functions where one has delay and the other returns an immediate result:

```
exports.immediateFunction = functions
    .region("europe-west2")
    .https
    .onRequest(async (req, res) => {
        res.send({ "result": "Immediate result." });
    });

exports.delayedFunction = functions
    .region("europe-west2")
    .https
    .onRequest(async (req, res) => {
        await new Promise(f => setTimeout(f, 5000));
        res.send({ "result": "Delayed for 5000 ms." });
    });
```

and then run the command: `firebase emulators:start --inspect-functions`

### Steps to reproduce

Trigger `delayedFunction` first and then `immediateFunction` straight after.

### Expected behavior

Should be getting response from `immediateFunction` immediately.

### Actual behavior

`immediateFunction` waits for `delayedFunction` to complete.

**Use case:**
I have a function that makes a request to an external API for which I have set up a webhook pointing to another function. However, because the first function is waiting for external API to result, my webhook function won't run and the whole process will fail due to webhook request timeout.

**Comment by joehan** [comment]
This is working as intended - when running the functions emulator with the `--inspect-functions` flag, we run all of your functions in series on a single worker, to make it easier for you to debug. You can remove this flag to avoid this issue.
