### ISSUE TITLE
Function Deployment fails with 500 or 503 when trying to access Secrets in europe-west3

### ISSUE THREAD

**Issue by luckyhandler** [firebase/firebase-tools#5739]
### [REQUIRED] Environment info

**firebase-tools: 11.29.0**

**Platform: macOS 13.3.1**

### [REQUIRED] Test case

```
exports.testFunction = functions
  .region("europe-west3")
  .runWith({ secrets: ["SECRET"] })
  .https.onRequest(async (req, res) => {
    // code
  });
```

### [REQUIRED] Steps to reproduce

- Define a secret in [Secret Manager](https://console.cloud.google.com/security/secret-manager) with location `europe-west3`
- Deploy the  testFunction to your project with `firebase deploy --only functions:testFunction`
- Receive error `Error: Failed to validate secret versions` with 
  - either `FirebaseError HTTP Error: 500, Failed to de-alias project.`
  - or `FirebaseError HTTP Error: 503, The service is currently unavailable.`

### [REQUIRED] Expected behavior

The deployment should complete.

### [REQUIRED] Actual behavior

An error occurs
-->  `Error: Failed to validate secret versions` with 
  - either `FirebaseError HTTP Error: 500, Failed to de-alias project.`
  - or `FirebaseError HTTP Error: 503, The service is currently unavailable.`

**Comment by qmathe** [comment]
I'm getting the same error (HTTP Error: 500, Failed to de-alias project) when trying to deploy cloud functions in europe-west1.

**Comment by luckyhandler** [comment]
I was just able to successfully deploy - so the issue seems to be resolved.

**Comment by colerogers** [comment]
Hey folks sorry for the headache. I'm pretty sure this is related to the issues that GCP is having in some `europe` regions. Here's a public dashboard that you can refer to for service availability - https://status.cloud.google.com/incidents/dS9ps52MUnxQfyDGPfkY#73mBtVKKfeJGJ1yaY7hV

Since it seems to be resolved for you, I'll go ahead and close out this issue

**Comment by qmathe** [comment]
Same for me, it's working again since yesterday.
