### ISSUE TITLE
Firebase serve doesn't play nice with Polymer's ImportHref()

### ISSUE THREAD

**Issue by xelra** [firebase/firebase-tools#574]
This is a cross-post, because I didn't know whether it's a Polymer or a Firebase CLI issue.

I'm using Polymer and Firebase and while developing, I noticed that I'm getting errors in the Chrome console when I try to navigate to a non-existing url/file and the whole app breaks.

Upon a whole day of investigating, I figured out that the issue is between the Firebase CLI and probably `importHref()`.

I managed to reproduce the issue with a fresh init of Firebase and a fresh init of the Polymer Starter Kit.

Steps to reproduce:
- Run `firebase init`
- Choose "Hosting", select project, default directory `public/`, "yes" single page app.
- `cd public/`
- `polymer init`
- Create a Polymer Starter Kit application, the one with the drawer, header and the 3 views
- `cd ..`
- `firebase serve`

Now navigate to a non-existing url and you'll see the following error:
![image](https://user-images.githubusercontent.com/908568/34185912-9b424112-e528-11e7-8271-b61b96e9cd31.png)
Click somewhere in the app and there will be more errors. From here on out the whole app is broken until reload:
![image](https://user-images.githubusercontent.com/908568/34185935-bf10a016-e528-11e7-828e-b18705b12f63.png)

This problem does not appear when serving with `polymer serve`. It will properly call `onerror` and redirect to 404.

I didn't test any more variations, but it can probably be reproduced in other ways too.

I want to emphasize that this problem does **not** appear when navigating to **existing** urls/files.

**Comment by xelra** [comment]
In the cross-referenced issue it was determined that it's trying to import Polymer multiple times, which leads to the app breaking.

I was pointed to a rewrite rule that looks like this:
```
"rewrites": [
      {
        "source": "**/!(*.*)",
        "destination": "/index.html"
      }
    ]
```
It fixes the **big** issue with the app breaking completely, but it's not perfect either. Any suffix in the url that contains a `.` will not redirect to 404 in a Polymer SPA, but instead fail the `GET`.

Still, it would be great if this rewrite rule, or maybe an even better rule that also catches the problem with suffixes containing a `.`, could be added to `firebase init`, so that a Polymer-compatible `firebase.json` can be created.

This issue was really hard fix or find at all. It took 4 people and almost a whole day.

**Comment by mbleigh** [comment]
This seems like something that needs to be documented properly in the Polymer Starter Kit somewhere -- I'm not really sure what needs to happen in this CLI to better accommodate PSK (as I'm also not sure what the actual problem is). In general `firebase serve` is usually best used with the fully-compiled (non-dev) versions of apps.
