### ISSUE TITLE
Error Install Standalone Binary | unexpected token `newline'

### ISSUE THREAD

**Issue by erikjhordan-rey** [firebase/firebase-tools#5746]
### [REQUIRED] Environment info

firebase-tools: 11.29.1

Platform: macOS 13.2.1

**firebase-tools:**

**Platform:**

### [REQUIRED] Test case

` curl -sL firebase.tools | bash`

### [REQUIRED] Steps to reproduce

- Execute the command `curl -sL firebase.tools | bash`

### [REQUIRED] Expected behavior

The **firebase.tools** should be installed. 

### [REQUIRED] Actual behavior

**Local Computer**
```bash
~ » curl -sL firebase.tools | bash                                    
-- Checking for existing firebase-tools on PATH...
/usr/local/bin/firebase: line 1: syntax error near unexpected token `newline'
/usr/local/bin/firebase: line 1: `<?xml version="1.0" encoding="UTF-8"?>'
Your machine has a corrupted firebase-tools binary installed.
```

**CI environment (Travis CI Mac)**

![imagen](https://user-images.githubusercontent.com/5893477/234732640-f63a4624-3692-4ffb-b281-385f5722bdf8.png)

**Comment by ederpadilla** [comment]
help my travis ci its failing :(

**Comment by alfapatwin** [comment]
Confirmed with the official link Standalone installation link for Mac OS https://firebase.tools/bin/macos/latest. Coming back with No such key message.

**Comment by davidecantini** [comment]
Same issue here

**Comment by sspogra** [comment]
Same issue.

**Comment by JoaoManaroulas** [comment]
Same issue here. On macOS 12 image being run on Azure Devops, if that matters.

**Comment by aalej** [comment]
Hi everyone, apologies for the issue this has caused. I was able to replicate the issue mentioned on a macOS machine. I’ve notified our team so that they can investigate what is causing this.

**Comment by bkendall** [comment]
Builds are all available at https://github.com/firebase/firebase-tools/releases/tag/v11.29.1 now, so the standalone installer should be good now.

I hit _multiple_ issues trying to upload - I wonder if GitHub is having some server-side problems. But, we got there!

Sorry for the issues!
