### ISSUE TITLE
firebase deploy --only hosting fails with webframeworks experiment enabled

### ISSUE THREAD

**Issue by lesnitsky** [firebase/firebase-tools#5773]
### Environment info

**firebase-tools:** 11.29.1

**Platform:** macOS arm

### Steps to reproduce

- `npx create-next-app`
- create an API route
- `firebase deploy --only hosting`

### Expected behavior

Deploy succeeds

###  Actual behavior

Deploy fails

<details>
<summary>logs</summary>
<pre><code>
[2023-05-01T23:05:07.409Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2023-05-01T23:05:07.411Z] > authorizing via signed-in user (a@lesnitsky.dev)
[2023-05-01T23:05:07.412Z] [iam] checking project publican-dce87 for permissions ["firebase.projects.get","firebasehosting.sites.update"]
[2023-05-01T23:05:07.415Z] >>> [apiv2][query] POST https://cloudresourcemanager.googleapis.com/v1/projects/publican-dce87:testIamPermissions [none]
[2023-05-01T23:05:07.416Z] >>> [apiv2][(partial)header] POST https://cloudresourcemanager.googleapis.com/v1/projects/publican-dce87:testIamPermissions x-goog-quota-user=projects/publican-dce87
[2023-05-01T23:05:07.417Z] >>> [apiv2][body] POST https://cloudresourcemanager.googleapis.com/v1/projects/publican-dce87:testIamPermissions {"permissions":["firebase.projects.get","firebasehosting.sites.update"]}
[2023-05-01T23:05:08.324Z] <<< [apiv2][status] POST https://cloudresourcemanager.googleapis.com/v1/projects/publican-dce87:testIamPermissions 200
[2023-05-01T23:05:08.327Z] <<< [apiv2][body] POST https://cloudresourcemanager.googleapis.com/v1/projects/publican-dce87:testIamPermissions {"permissions":["firebase.projects.get","firebasehosting.sites.update"]}
[2023-05-01T23:05:08.329Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/publican-dce87 [none]
[2023-05-01T23:05:08.721Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects/publican-dce87 200
[2023-05-01T23:05:08.724Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects/publican-dce87 {"projectId":"publican-dce87","projectNumber":"525778539019","displayName":"publican","name":"projects/publican-dce87","resources":{"hostingSite":"publican-dce87"},"state":"ACTIVE","etag":"1_6fc0943c-7c92-4870-846e-fffa8dfaf3e4"}
Detected a Next.js codebase. This is an experimental integration, proceed with caution.

info  - Checking validity of types  
info  - Using wasm build of next-swc
warn  - Attempted to load @next/swc-darwin-x64, but it was not installed
info  - Creating an optimized production build  
info  - Compiled successfully
info  - Collecting page data  
info  - Generating static pages (3/3)
info  - Finalizing page optimization  

Route (pages)                              Size     First Load JS
┌ ○ /                                      258 B          73.4 kB
├   /_app                                  0 B            73.1 kB
├ ○ /404                                   182 B          73.3 kB
└ λ /api/[all]                             0 B            73.1 kB
+ First Load JS shared by all              73.4 kB
  ├ chunks/framework-eaa0f3520361d921.js   45.2 kB
  ├ chunks/main-dda1ec63a16662d1.js        26.8 kB
  ├ chunks/pages/_app-ae907860a06fe57a.js  296 B
  ├ chunks/webpack-8fa1640cc84ba8fe.js     750 B
  └ css/ab44ce7add5c3d11.css               247 B

λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)

Building a Cloud Function to run this application. This is needed due to:
 • non-static route /api/[all]

npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@3. I'll try to do my best with it!
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for inotify@1.4.6: wanted {"os":"linux","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm ERR! notsup Valid OS:    linux
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   darwin
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lesnitsky/.npm/_logs/2023-05-01T23_05_36_653Z-debug.log
[2023-05-01T23:05:36.684Z] Error: Command failed: npm i --omit dev --no-audit
    at checkExecSyncError (node:child_process:828:11)
    at Object.execSync (node:child_process:899:15)
    at execSync (pkg/prelude/bootstrap.js:2111:30)
    at prepareFrameworks (/Users/lesnitsky/.cache/firebase/tools/lib/node_modules/firebase-tools/lib/frameworks/index.js:399:42)
    at async deploy (/Users/lesnitsky/.cache/firebase/tools/lib/node_modules/firebase-tools/lib/deploy/index.js:53:13)

Error: An unexpected error has occurred.

Having trouble? Try again or contact support with contents of firebase-debug.log
</code></pre>
</details>

<details><summary>npm-debug.log</summary>
<pre><code>0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/bin/firebase',
1 verbose cli   '/snapshot/firepit/node_modules/npm/bin/npm-cli',
1 verbose cli   '--script-shell=/Users/lesnitsky/.cache/firebase/runtime/shell',
1 verbose cli   '--globalconfig=/Users/lesnitsky/.cache/firebase/runtime/npmrc',
1 verbose cli   '--userconfig=/Users/lesnitsky/.cache/firebase/runtime/npmrc',
1 verbose cli   '--scripts-prepend-node-path=auto',
1 verbose cli   'i',
1 verbose cli   '--omit',
1 verbose cli   'dev',
1 verbose cli   '--no-audit'
1 verbose cli ]
2 info using npm@6.14.18
3 info using node@v16.16.0
4 verbose npm-session d5f1b5047337d83a
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/dev 955ms (from cache)
8 silly pacote tag manifest for dev@latest fetched in 977ms
9 timing stage:loadCurrentTree Completed in 1018ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
13 silly install loadShrinkwrap
14 warn read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@3. I'll try to do my best with it!
15 timing stage:loadIdealTree:loadShrinkwrap Completed in 6ms
16 silly install loadAllDepsIntoIdealTree
17 silly resolveWithNewModule dev@0.1.3 checking installable status
18 http fetch GET 304 https://registry.npmjs.org/inotify 832ms (from cache)
19 silly pacote range manifest for inotify@>= 0.1.6 fetched in 840ms
20 silly resolveWithNewModule inotify@1.4.6 checking installable status
21 timing stage:rollbackFailedOptional Completed in 1ms
22 timing stage:runTopLevelLifecycles Completed in 1875ms
23 silly saveTree podium@0.1.0
23 silly saveTree └─┬ dev@0.1.3
23 silly saveTree   └── inotify@1.4.6
24 verbose stack Error: Unsupported platform for inotify@1.4.6: wanted {"name":"inotify","version":"1.4.6","engines":{"node":">=0.8"},"os":["linux"],"dependencies":{"bindings":"^1.3.1","nan":"^2.12.1"},"optionalDependencies":{},"peerDependenciesMeta":{},"devDependencies":{},"bundleDependencies":false,"peerDependencies":{},"deprecated":false,"_resolved":"https://registry.npmjs.org/inotify/-/inotify-1.4.6.tgz","_integrity":"sha512-WW8/uqIA04O3AePQVe/Ms3ZLR0yGamaz8YOEpaXc4WBAGOPZfzu58wWErEPSUYaPyDrJRIeCn6PEIQgC1ZyQ5w==","_shasum":"c5a51852df1647d1a589d46c4baa2771ed36b8d2","_shrinkwrap":null,"_id":"inotify@1.4.6","_from":"inotify@>= 0.1.6","_requested":{"type":"range","registry":true,"raw":"inotify@>= 0.1.6","name":"inotify","escapedName":"inotify","rawSpec":">= 0.1.6","saveSpec":null,"fetchSpec":">= 0.1.6"},"_spec":"inotify@>= 0.1.6","_where":"/Users/lesnitsky/w/lesnitsky/podium/.firebase/publican-dce87/functions/node_modules/dev"} (current: {"os":"darwin","cpu":"x64"})
24 verbose stack     at checkPlatform (/snapshot/firepit/node_modules/npm/node_modules/npm-install-checks/index.js:46:14)
24 verbose stack     at thenWarnEngineIssues (/snapshot/firepit/node_modules/npm/lib/install/validate-args.js:63:5)
24 verbose stack     at /snapshot/firepit/node_modules/npm/node_modules/iferr/iferr.js:3:64
24 verbose stack     at checkEngine (/snapshot/firepit/node_modules/npm/node_modules/npm-install-checks/index.js:25:10)
24 verbose stack     at /snapshot/firepit/node_modules/npm/lib/install/validate-args.js:60:3
24 verbose stack     at resolveWithNewModule (/snapshot/firepit/node_modules/npm/lib/install/deps.js:677:10)
24 verbose stack     at /snapshot/firepit/node_modules/npm/lib/install/deps.js:600:7
24 verbose stack     at /snapshot/firepit/node_modules/npm/node_modules/iferr/iferr.js:3:64
24 verbose stack     at /snapshot/firepit/node_modules/npm/node_modules/call-limit/call-limit.js:28:43
24 verbose stack     at processTicksAndRejections (node:internal/process/task_queues:78:11)
25 verbose pkgid inotify@1.4.6
26 verbose cwd /Users/lesnitsky/w/lesnitsky/podium/.firebase/publican-dce87/functions
27 verbose Darwin 22.1.0
28 verbose argv "/usr/local/bin/firebase" "/snapshot/firepit/node_modules/npm/bin/npm-cli" "--script-shell=/Users/lesnitsky/.cache/firebase/runtime/shell" "--globalconfig=/Users/lesnitsky/.cache/firebase/runtime/npmrc" "--userconfig=/Users/lesnitsky/.cache/firebase/runtime/npmrc" "--scripts-prepend-node-path=auto" "i" "--omit" "dev" "--no-audit"
29 verbose node v16.16.0
30 verbose npm  v6.14.18
31 error code EBADPLATFORM
32 error notsup Unsupported platform for inotify@1.4.6: wanted {"os":"linux","arch":"any"} (current: {"os":"darwin","arch":"x64"})
33 error notsup Valid OS:    linux
33 error notsup Valid Arch:  any
33 error notsup Actual OS:   darwin
33 error notsup Actual Arch: x64
34 verbose exit [ 1, true ]
</code></pre></details>

<details><summary>package.json</summary>
<pre><code>{
  "name": "podium",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@types/node": "18.16.3",
    "@types/react": "18.2.0",
    "@types/react-dom": "18.2.1",
    "eslint": "8.39.0",
    "eslint-config-next": "13.3.4",
    "next": "13.3.4",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "typescript": "5.0.4"
  }
}</code></pre></details>

I tried uninstalling firebase tools with `curl -sL firebase.tools | uninstall=true bash`, dropped all my global caches (`node_modules`), nothing helps

When I navigate to `.firebase/<project-id>/functions` folder manually and run `npm i --omit dev` there – install succeeds. My guess is something wrong with the npm-cli used by firebase tools. As seen in `npm-debug.log`:

```
17 silly resolveWithNewModule dev@0.1.3 checking installable status
18 http fetch GET 304 https://registry.npmjs.org/inotify 832ms (from cache)
19 silly pacote range manifest for inotify@>= 0.1.6 fetched in 840ms
20 silly resolveWithNewModule inotify@1.4.6 checking installable status
21 timing stage:rollbackFailedOptional Completed in 1ms
22 timing stage:runTopLevelLifecycles Completed in 1875ms
23 silly saveTree podium@0.1.0
23 silly saveTree └─┬ dev@0.1.3 <----------- ????????? -----------
23 silly saveTree   └── inotify@1.4.6
```
for some unknown to me reason there's a `dev` dependency that is not present in my `package.json` and `package-lock.json`

**Comment by subfuzion** [comment]
In my case, the problem was not the version of the Firebase CLI. The problem was that `firebase deploy` set the node engine version in the generated `.firebase/PROJECT/functions/package.json` to the same version of Node that I was using at the time locally (`20`).

<img width="350" alt="image" src="https://user-images.githubusercontent.com/159738/236931897-2e77028c-5376-4db0-9263-49d7ccdcb22e.png">

I was able to solve this and tested with both Firebase CLI version `11.29.1` and `11.30.0` with both of the following scenarios:

- Downgrading version of Node.js to `v16.20.0` (using `nvm`)
- Upgrading version of Node.js back to `v20.1.0` but setting node engine explicitly in `package.json` (the CLI gave a warning that problems may be encountered because it detected that I was running version 20, but the deploy output shows that it's updating a Node.js `16` function and succeeds)

```json
  "engines": {
    "node": "16"
  }
```

**Comment by bogacg** [comment]
Today I wanted to update my SvelteKit app, process goes smooth for build of web app but then problem mentioned by @subfuzion happens again. `npm ERR! code EBADENGINE`

>  This integration expects Node version 16 or 18. You're running version 20
Setup:
- Windows
- Node 20.2.0
- Firebase CLI 12.0.1

On Linux machine I see a totally different problem. Build process initialized by Firebase deploy fails at the early stage.

```
require() of ES Module .../node_modules/@sveltejs/kit/src/core/postbuild/analyse.js not supported.
.
.
.
  code: 'ERR_REQUIRE_ESM'
}
[vite-plugin-sveltekit-compile] Failed with code 1
```

Tried it with Node v16, v18 and v20. Firebase CLI 12.0.1.

When directly executing SvelteKit build there are no errors.

Is there a way `firebase deploy --only hosting` uses existing build artifact instead of it tries to start one itself?

Can we skip that step?

**Comment by bogacg** [comment]
New version, still having problems:

Today I tried to publish with latest Firebase Tools CLI, v12.1.0 on Windows & Linux. Despite release notes claims Node v20 compatible I'm still seeing errors:

**Windows, Node 20.2.0 Firebase 12.1.0**
```
!  This integration expects Node version 16 or 18. You're running version 20, problems may be encountered.
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: <proj-name>@0.0.1
npm ERR! notsup Not compatible with your version of node/npm: <proj-name>@0.0.1
npm ERR! notsup Required: {"node":"18"}
npm ERR! notsup Actual:   {"npm":"9.6.6","node":"v20.2.0"}
```
**Linux, Node 20.2.0 & 18.16.0, Firebase 12.1.0** 

```
> inotify@1.4.6 install /home/<username>/<proj-location>/.firebase/<firebase-proj-name>/functions/node_modules/inotify
> node-gyp rebuild

/bin/sh: 1: node-gyp: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file /home/<username>/.cache/firebase/runtime/shell
npm ERR! errno ENOENT
npm ERR! inotify@1.4.6 install: `node-gyp rebuild`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the inotify@1.4.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/<username>/.npm/_logs/2023-05-22T09_46_11_487Z-debug.log

Error: An unexpected error has occurred.
```
I did execute Linux command in `su` as well, thinking maybe that script mentioned in above error message requires elevated privilege, yet got same error in the end.

Another strange thing with Linux error is, when I check Firebase error log I see this: 
```
[debug] [2023-05-22T09:51:43.803Z] Command:       /usr/local/bin/firebase /root/.cache/firebase/tools/lib/node_modules/firebase-tools/lib/bin/firebase deploy --only hosting
[debug] [2023-05-22T09:51:43.804Z] CLI Version:   12.1.0
[debug] [2023-05-22T09:51:43.804Z] Platform:      linux
[debug] [2023-05-22T09:51:43.804Z] Node Version:  v16.16.0
```
So does Firebase command execute in Node v16 regardless of my current working version?

**Comment by jamesdaniels** [comment]
I think the problem is that you're using the standalone version of firebase-tools which ships with it's own version of NodeJS, e.g, `curl -sL firebase.tools` rather than the NPM one `npm i -g firebase-tools`. Allowing frameworks to target Node 20 in #5879

**Comment by bogacg** [comment]
@jamesdaniels I believe you've only read last part of what I have posted above. 

The error is still there:

```
!  This integration expects Node version 16 or 18. You're running version 20, problems may be encountered.
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: <pkg-name>@0.2.0
npm ERR! notsup Not compatible with your version of node/npm: <pkg-name>@0.2.0
npm ERR! notsup Required: {"node":"18"}
npm ERR! notsup Actual:   {"npm":"9.6.6","node":"v20.2.0"}
```

Just executed it on Node 20.2.0, Firebase Tools 12.1.0.

**Comment by jamesdaniels** [comment]
Node20 support wasn't cut in Friday's 12.1.0, it should go out with the next release

**Comment by jamesdaniels** [comment]
Stand=alone firebase-tools does indeed ship with it's own version of NodeJS. This is by design. If you're an NPM developer you should probably use `npm i -g firebase-tools` rather than `curl -sL firebase.tools`. Which was the original issue.
