### ISSUE TITLE
Firebase functions on docker 

### ISSUE THREAD

**Issue by vinodhum** [firebase/firebase-tools#579]
Hi,
I when I try to emulate firebase function localy on docker i am betting below error.

I  functions: Preparing to emulate functions.
E1225 08:21:26.196295300     736 server_chttp2.c:38]         {"created":"@1514190086.196267700","description":"Only 1 addresses added out of total 2 resolved","file":"../deps/grpc/src/core/ext/transport/chttp2/server/chttp2_server.c","file_line":255,"referenced_errors":[{"created":"@1514190086.196261400","description":"Failed to add port to server","file":"../deps/grpc/src/core/lib/iomgr/tcp_server_uv.c","file_line":418,"referenced_errors":[{"created":"@1514190086.196256200","description":"Failed to bind to port","file":"../deps/grpc/src/core/lib/iomgr/tcp_server_uv.c","file_line":275,"os_error":"address not available"}]}]}
⚠  functions: Failed to load functions source code. Ensure that you have the latest SDK by running npm i --save firebase-functions inside the functions directory.
⚠  functions: Error from emulator. FirebaseError: Error parsing triggers: Cannot find module '/data/firebase/functions'

I already tired npm install in functions folder.

any idea to fix it or if its known bug.

 Thank you

### Version info

firebase --version
3.16.0
node --version
v6.11.5

### Steps to reproduce

install docker using node:6.11.5
install firebase-tools
run local firebase functions using "firebase serve --only functions"

### Expected behavior

emulate functions localy

### Actual behavior
I  functions: Preparing to emulate functions.
E1225 08:21:26.196295300     736 server_chttp2.c:38]         {"created":"@1514190086.196267700","description":"Only 1 addresses added out of total 2 resolved","file":"../deps/grpc/src/core/ext/transport/chttp2/server/chttp2_server.c","file_line":255,"referenced_errors":[{"created":"@1514190086.196261400","description":"Failed to add port to server","file":"../deps/grpc/src/core/lib/iomgr/tcp_server_uv.c","file_line":418,"referenced_errors":[{"created":"@1514190086.196256200","description":"Failed to bind to port","file":"../deps/grpc/src/core/lib/iomgr/tcp_server_uv.c","file_line":275,"os_error":"address not available"}]}]}
⚠  functions: Failed to load functions source code. Ensure that you have the latest SDK by running npm i --save firebase-functions inside the functions directory.
⚠  functions: Error from emulator. FirebaseError: Error parsing triggers: Cannot find module '/data/firebase/functions'

**Comment by merlinnot** [comment]
Hi, the error at the top does not prevent functions emulator from working just fine, starting GRPC server by default will be removed in future releases AFAIK. You should focus on resolving the two last warnings. Just double check you have a source code of the functions in the directory you’ve specified as a build directory.

Everything works fine in my dev env, also based on Docker: https://github.com/merlinnot/devver

**Comment by vinodhum** [comment]
Thanx merlinnot,
you mean to say first error is related to docker and other 2 warnings are firebase correct ?
firebase has 2 options one is JS version and other is type script, on JS i can get the emulator working but ports not getting exposed I guess its due to that error.

and typescript version is giving other error so emulator is not starting.

**Comment by merlinnot** [comment]
Did you try to compile your ts project first?

**Comment by vinodhum** [comment]
Mirlinnot,
Thank you,
I was able to resolve it by editing 
/root/.config/configstore/@google-cloud/functions-emulator/config.json
and setting localhost to 0.0.0.0

and about typescript compiling, for some reason firebase serve command was not running build before emulating. so as an alternate I am using "npm run serve"
