### ISSUE TITLE
2nd gen Storage trigger doesn't have access to bucket

### ISSUE THREAD

**Issue by jhuleatt** [firebase/firebase-tools#5794]
### [REQUIRED] Environment info

**firebase-tools:** 11.30.0

**Platform:** macOS

### [REQUIRED] Test case

Deploy a 2nd gen Storage trigger that uses the Admin SDK to download and upload to the default Storage bucket.

### [REQUIRED] Steps to reproduce

1. Create a fresh Firebase project
2. Enable Cloud Storage
3. Deploy the function code [from this sample](https://github.com/firebase/functions-samples/tree/jhuleatt-remove-imagemagick/2nd-gen/thumbnails)
4. Upload an image to the Cloud Storage bucket in the Firebase console
5. Check the function logs to see the permission denied error

### [REQUIRED] Expected behavior

Image is resized by the function

### [REQUIRED] Actual behavior

Error:

```
Error: {hash}-compute@developer.gserviceaccount.com does not have storage.objects.get access to the Google Cloud Storage object. Permission &#39;storage.objects.get&#39; denied on resource (or it may not exist).
```

**Comment by jhuleatt** [comment]
never mind, this was due to an IAM permissions issue that prevented the compute engine service account from getting the access it needed

**Comment by aalej** [comment]
Based on the latest comment, it seems like this issue is resolved. That said, I'll be closing this ticket. Thanks!
