### ISSUE TITLE
Firebase Cloud Function: "Unexpected end of form" error with multipart/form-data

### ISSUE THREAD

**Issue by donfreddy** [firebase/firebase-tools#5800]
I'm trying to create a file upload endpoint on my Cloud Function Nestjs app. I've tried interceptor with different modules such as  multer and busboy, but none could escape the "Unexpected end of form at Multipart._final" error while running the server with firebase emulator, the error appears on frontend, Swagger and Postman I tried to re-write the same exact code to a standalone nestjs app without firebase and it works perfectly. Below you can find the interceptor that I wrote with busboy:

```ts
@Injectable()
export class ApiFileInterceptor implements NestInterceptor {
  intercept(context: ExecutionContext, next: CallHandler): Observable<any> | Promise<Observable<any>> {
    const request = context.switchToHttp().getRequest();

    return new Promise((resolve, reject) => {
      const busboy = Busboy({ headers: request.headers, limits: { fileSize: 1024 * 1024 * 10 } });
      const fileBuffer: any = {};

      busboy.on('file', (name, file, filename, encoding, mimetype) => {

        file.on('data', (data) => {
          console.log('File [' + name + '] got ' + data.length + ' bytes');
          fileBuffer[name] = data;
        });

        file.on('end', () => {
          console.log('File [' + name + '] Finished');
          fileBuffer[name] = Buffer.concat(fileBuffer[name]);
        });
      });

      busboy.on('field', (name, value) => {
        console.log('Field [' + name + ']: value: ' + value);
        fileBuffer[name] = value;
      });

      busboy.on('finish', () => {
        console.log('Done parsing form!');
        request.body = fileBuffer;
        resolve(next.handle());
      });

      busboy.on('error', (err) => {
        console.error(err);
        reject(err);
      });

      request.pipe(busboy);
    });
  }
}
```

### [REQUIRED] Environment info

**firebase-tools: 11.26.0**

**Platform: macOS**

**Comment by blidd-google** [comment]
Hi @donfreddy, I'm not sure I understand where you are using firebase cloud functions here — could you provide a reproducible example for me to follow and share the error logs when running the emulator with the `--debug` flag?

**Comment by PeterPlevko** [comment]
I had the same problem and this [stackoverflow](https://stackoverflow.com/questions/76220138/handling-multipart-form-data-post-with-nest-in-cloud-functions-firebase/77701854#77701854) post helped me fix it it works
