### ISSUE TITLE
Missing documentation on using as module

### ISSUE THREAD

**Issue by michaellee8** [firebase/firebase-tools#581]
Currently, there are no instructions on how to use the `firebase-tools` as a node.js module can be observed other than that few lines in `README.md`, I believe a proper API document is required so that others can follow and use it properly.

**Comment by MartinFreire** [comment]
hi, also how to use with the new typescript project structure
I have a project that I need to do some pre-built things and settings for each different project before deploy and this could come very useful.

**Comment by mbleigh** [comment]
Dup of #322
