### ISSUE TITLE
Any version after 11.17.0 fails to deploy (Failed to find location of Firebase Functions SDK)

### ISSUE THREAD

**Issue by snorreks** [firebase/firebase-tools#5822]
If i try to use any versions after firebase-tools 11.17.0, i get "Failed to find location of Firebase Functions SDK" error. I have also tried the latest firebase-tools 12.0.0, and i get the same error. I have tried to uninstall and install firebase-tools again. Using pnpm and global.
`firebase deploy --only functions`
`pnpm firebase deploy --only functions`
But get the same error.

### [REQUIRED] Version info

**node:** 18.14.2

**firebase-functions:** 4.4.0

**firebase-tools:** 11.17.0

**firebase-admin:** 11.8.0

**os:** Windows 11 Pro, 22H2, 22621.1105

### [REQUIRED] Steps to reproduce

1. Deploy any function using `firebase deploy --only functions`
2. Notice that no function can deploy.

### [REQUIRED] Expected behavior

Expect to deploy the functions.

### [REQUIRED] Actual behavior

[firebase-debug.log](https://github.com/firebase/firebase-functions/files/11438086/firebase-debug.log)

### Were you able to successfully deploy your functions?

No. I get this error
```bash
i  deploying functions
i  functions: preparing codebase default for deployment
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
i  artifactregistry: ensuring required API artifactregistry.googleapis.com is enabled...
+  artifactregistry: required API artifactregistry.googleapis.com is enabled
+  functions: required API cloudbuild.googleapis.com is enabled
+  functions: required API cloudfunctions.googleapis.com is enabled

Error: Failed to find location of Firebase Functions SDK. Please file a bug on Github (https://github.com/firebase/firebase-tools/).
```

**Comment by aalej** [comment]
Hi @snorreks, I am unable to replicate the issue you mentioned. I tried creating a new project to deploy functions and I did not encounter any issues while deploying. I’m not sure if I may be missing something to properly replicate this. Could you provide more details on how you set up your project, and if you’re able to reproduce the issue in a fresh project? Thanks!

I’m using the following to replicate this issue:
platform: macOS
firebase-tools: v12.0.0
node: v18.15.0   
firebase-admin: 11.8.0
firebase-functions: 4.4.0

**Comment by colerogers** [comment]
Also, I tried out the sample and I'm also unable to reproduce the bug

**Comment by snorreks** [comment]
I see, it worked when you changed firebase-tools to 12.0.0, and ran `pnpm i`? Are you using windows?

It is not possible to move around the repo structure. I am using nx, pnpm and [nx-cloud-functions-deployer](https://www.npmjs.com/package/nx-cloud-functions-deployer), it is working with firebase-tools 11.17.0 and lower.

Do you think a quick fix is to create npm package wrapper:
```
- root (pnpm)
  - package layer (npm)
    - deploy function folder
```
where npm package layer only have firebase-functions installed?

Do you know if [/src/deploy/functions/runtimes/node/index.ts](https://github.com/firebase/firebase-tools/blob/2e84e941339b33f4ab512d46161a4383e29a6222/src/deploy/functions/runtimes/node/index.ts#L175) changed after 11.17.0?

**Comment by russellwheatley** [comment]
Hey @snorreks - did you manage to resolve your issue?
