### ISSUE TITLE
firebase init functions - not working

### ISSUE THREAD

**Issue by jinmin888** [firebase/firebase-tools#583]
npm WARN firebase-functions@0.7.5 requires a peer of firebase-admin@~5.5.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.6.6 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@1.6.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\min\AppData\Roaming\npm-cache\_logs\2018-01-01T03_39_12_432Z-debug.log

NPM install failed, continuing with Firebase initialization...

i  Writing configuration info to firebase.json...
i  Writing project information to .firebaserc...

+  Firebase initialization complete!

**Comment by mumumilk** [comment]
Update firebase-admin to 5.5.0 in your package.json:

"firebase-admin": "5.5.0"

**Comment by JonahElbaz** [comment]
Life saver mumumilk
