### ISSUE TITLE
Brand new Sveltekit does not work with firebase emulators:start/deploy

### ISSUE THREAD

**Issue by ms-hetty** [firebase/firebase-tools#5835]
Hi

I've created an entirely new project with the console tools:

> npm create svelte@latest chatty
┌  Welcome to SvelteKit!
│
◇  Which Svelte app template?
│  SvelteKit demo app
│
◇  Add type checking with TypeScript?
│  Yes, using TypeScript syntax
│
◇  Select additional options (use arrow keys/space bar)
│  none
│
└  Your project is ready!

> npm install

> firebase init
? Which Firebase features do you want to set up for this directory? Press Space to select 
features, then Enter to confirm your choices. Hosting: Configure files for Firebase Hosting and 
(optionally) set up GitHub Action deploys

=== Project Setup

First, let's associate this project directory with a Firebase project.
You can create multiple project aliases by running firebase use --add, 
but for now we'll just set up a default project.

? Please select an option: Create a new project
i  If you want to create a project in a Google Cloud organization or folder, please use "firebase projects:create" instead, and return to this command when you've created the project.
? Please specify a unique project id (warning: cannot be modified afterward) [6-30 characters]:
 xxxxxxx
? What would you like to call your project? (defaults to your project ID) chatty
✔ Creating Google Cloud Platform project
✔ Adding Firebase resources to Google Cloud Platform project

🎉🎉🎉 Your Firebase project is ready! 🎉🎉🎉

Project information:
   - Project ID: xxxxxxx
   - Project Name: chatty

Firebase console is available at
https://console.firebase.google.com/project/steffihe-chatty/overview
i  Using project xxxxxxx (chatty)

=== Hosting Setup

? Detected an existing SvelteKit codebase in the current directory, should we use this? Yes
 (x2)
? In which region would you like to host server-side content, if applicable? europe-west1 
(Belgium)
? Set up automatic builds and deploys with GitHub? No

i  Writing configuration info to firebase.json...
i  Writing project information to .firebaserc...

✔  Firebase initialization complete!

> firebase emulators:start
i  emulators: Starting emulators: hosting
⚠  hosting: Hosting Emulator unable to start on port 5000, starting on 5002 instead.

   Thank you for trying our experimental support for SvelteKit on Firebase Hosting.
   While this integration is maintained by Googlers it is not a supported Firebase product.
   Issues filed on GitHub will be addressed on a best-effort basis by maintainers and other community members.

   Documentation: https://firebase.google.com/docs/hosting/frameworks/frameworks-overview
   File a bug: https://github.com/firebase/firebase-tools/issues/new?template=bug_report.md
   Submit a feature request: https://github.com/firebase/firebase-tools/issues/new?template=feature_request.md

   We'd love to learn from you. Express your interest in helping us shape the future of Firebase Hosting: https://goo.gle/41enW5X

node:internal/modules/cjs/loader:1156
      throw err;
      ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/steffi/dev/chatty/node_modules/vite/bin/vite.js not supported.
vite.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename vite.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /Users/steffi/dev/chatty/node_modules/vite/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

    at Function.runMain (pkg/prelude/bootstrap.js:1979:12) {
  code: 'ERR_REQUIRE_ESM'
}

I try already to install node-fetch 2 globally, but this also didn't help.

I'm using a Mac with current v20 node.

I can run the project without any problem with:
> npm run dev

**Comment by coehne** [comment]
Hi,
did you try running it with node 18? I think 20 is not yet supported. It worked for me like a charm. I wrote down the steps I did [here](https://github.com/coehne/svelteKitOnFireabase). The only difference I can spot is that I used node 18 instead of 20.

**Comment by ms-hetty** [comment]
Thank you. Yes, you've put me on the right path - i guess.
I had a bit a mess with my node versions.

Now, I'm on Node 18 and i've successfully emulated and deployed

**Comment by adityaruplaha** [comment]
I'm unable to make this work on Node v18.16.0. I have everything up to date, the error is essentially identical.

**Comment by adityaruplaha** [comment]
Nevermind, as such would have it, I found the solution right after asking for help.

For the record, I was using [firebase-tools-bin](https://aur.archlinux.org/packages/firebase-tools-bin), which of course doesn't play well with nvm. Mixing up node versions was the real issue here.

Also, it turns out, Node 20 works now! Though the support for a Node 20 runtime for Cloud Functions is preview, so use with caution.
