### ISSUE TITLE
login with firebase-tools is throwing an error

### ISSUE THREAD

**Issue by developerPratik** [firebase/firebase-tools#584]
Logging in with the firebase-tools using command `firebase login` is throwing an error. 

![firebase login error screen](https://user-images.githubusercontent.com/19855458/34466813-827376a8-ef08-11e7-81dc-a7d2485a2c7d.png)

I have updated firebase-tools as well with current version, i.e. 3.16.0. Could this be a bug in the new version? Please help.. any help is appreciated :)

**Comment by Antaxpatel** [comment]
I am also facing the same issue again and again I tried all the things with the help of A.I. I also tried no local host logging through CI reauthentication and more by accessing the versions of Node and FireBase CLI but it doesn't work. I started the FireBase CLI from the standard binary and it works with the authentication.

**Comment by Antaxpatel** [comment]
I got solution firebase cli is not supporting the latest 24 version, switch to the 22 version of node.js and it will perfectly work, right?
