### ISSUE TITLE
Failing to build extension when uploading from GitHub

### ISSUE THREAD

**Issue by gavinsawyer** [firebase/firebase-tools#5842]
### Environment info

**firebase-tools:** 12.0.0

**Platform:** macOS 13.3.1 on Apple Silicon

### Test case

I have a working Firebase Extension which I cannot submit for publication due to an internal error with `firebase ext:dev:upload`.

### Steps to reproduce

This can be reproduced using an official Firebase Extension:

1. Download the official Firebase Extension "Delete User Data" from [the repo](https://github.com/firebase/extensions/tree/next/delete-user-data).
2. Run `firebase ext:dev:upload ${YOUR_PUBLISHER_ID}/delete-user-data`. It asks for the GitHub repo and the path for the extension.yaml before validating the code. It does so successfully on my extension as well as this one.

### Expected behavior

The CLI should complete the build process or output a clearer error message. Because the same thing is happening with a working extension ("Delete User Data") and with my extension, I don't know what is going wrong.

### Actual behavior

The CLI outputs the error `Error: generic::internal: failed to build ExtensionVersion "publishers/${YOUR_PUBLISHER_ID}/extensions/delete-user-data/versions/0.1.16" source due to internal error`. The debugged logs show the createFromSource operation completing with error code 13.

**Comment by gavinsawyer** [comment]
I'm now using firebase-tools@12.2.1 and still encountering this issue.

Running...
```bash
% firebase ext:dev:upload gavinsawyer/firebase-web-authn --repo https://github.com/gavinsawyer/firebase-web-authn --ref main --root /dist/libs/extension --stage stable -f --debug
```
results in the CLI repeating...
```bash
Uploading gavinsawyer/firebase-web-authn@9.4.18...[2023-05-30T20:34:54.630Z] <<< [apiv2][status] GET https://firebaseextensionspublisher.googleapis.com/v1beta/projects/gavinsawyer-bf631/operations/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX 200
Uploading gavinsawyer/firebase-web-authn@9.4.18...[2023-05-30T20:35:26.632Z] [LRO Poller] Retrying task index 0
```
until eventually the operation produces:
```json
{
  "name": "projects/gavinsawyer-bf631/operations/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
  "done": true,
  "error": {
    "code": 13,
    "message": "generic::internal: failed to build ExtensionVersion \"publishers/gavinsawyer/extensions/firebase-web-authn/versions/9.4.18\" source due to internal error"
  }
}
```

Is there a place I can find logs for these operations? Not seeing anything in Logs Explorer.

**Comment by gavinsawyer** [comment]
Still have this issue on v12.3.0. Can anybody replicate?

1. Clone `firebase/extensions`
2. From inside `extensions/storage-resize-images` run:
```
% npx firebase-tools@12.3.0 ext:dev:upload ${YOUR_PUBLISHER_ID}/storage-resize-images --repo https://github.com/firebase/extensions --ref next --root /storage-resize-images --stage stable --debug
```

**Comment by joehan** [comment]
After digging a bit, I think there are a few issues here:

1 - root should not start with a / - this needs to be fixed on the extensions backend, filed internal bug 286094970 to fix this. For now, just get rid of the leading /

2 -  Once i remove that /, I get a different error when trying to upload your extension. Your repo does not have a package-lock.json (https://github.com/gavinsawyer/firebase-web-authn/tree/main/libs/extension). The build script for extensions runs `npm ci`, which requires a package-lock.json in the extensions root folder. If you add one, you should be able to successfully upload your extensions

**Comment by gavinsawyer** [comment]
Thank you so much! I was able to upload a stable version :)

The docs only mention `npm ci` being run in the functions folder. Most extensions don't have a `package.json` file in the root at all, so I thought it would be ignored.

[Appendix: Troubleshooting build errors](https://firebase.google.com/docs/extensions/publishers/upload-and-publish#troubleshooting)
> When you upload your extension, the backend first builds your source code using the following process:
> 1. Clones your GitHub repository and checks out the source ref specified.
> 2. Installs NPM dependencies by running `npm clean-install` in every function source directory specified in `extension.yaml`.
> 3. [...]

**Comment by joehan** [comment]
Ooh, thanks for pointing those docs out - I'll make sure we clarify them so that other publishers don't feel the same frustration.
