### ISSUE TITLE
Dependencies Vulnerabilities 

### ISSUE THREAD

**Issue by mgm793** [firebase/firebase-tools#5843]
### [REQUIRED] Environment info

**firebase-tools:** 12.0.0

**Platform:** all

### [REQUIRED] Test case

There are some vulnerabilities on the dependencies:

<img width="465" alt="Screenshot 2023-05-16 at 08 55 18" src="https://github.com/firebase/firebase-tools/assets/11296854/72e19ad6-9fff-40f5-9e58-5991ea2e7901">
<img width="499" alt="Screenshot 2023-05-16 at 08 55 24" src="https://github.com/firebase/firebase-tools/assets/11296854/bdb928df-2a4b-44d7-baa3-a129653fb091">

### [REQUIRED] Steps to reproduce

N/A

### [REQUIRED] Expected behavior

N/A

### [REQUIRED] Actual behavior

N/A

**Comment by bkendall** [comment]
Looks like the `vm2`  thing is new, which is unfortunate. I'm updating it again and that'll be included in the next release.

The other one in `request` is also annoying. But, we actually don't use `request` outside of the `functions:shell` command (where it's used as an interactive prompt basically, so it's a bit harder to completely remove). I'm going to let the PR close this out for vm2 - there's nothing to be done about request at the moment (though I'll bother the folks about removing `request` again)
