### ISSUE TITLE
Failed to load function definition from source: FetchError: request to http://localhost:8167/__/quitquitquit failed, reason: connect ECONNREFUSED ::1:8167

### ISSUE THREAD

**Issue by fcvuongdc** [firebase/firebase-tools#5845]
### [REQUIRED] Environment info

**firebase-tools:**

**Platform:**

**Comment by bkendall** [comment]
Unfortunately we need more information. Please create a new issue and follow the template, including a [minimum reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example) and we'll be able to take a look.
