### ISSUE TITLE
firebase not installed on MacBook Pro

### ISSUE THREAD

**Issue by balleza316** [firebase/firebase-tools#5850]
[firepit-log.txt](https://github.com/firebase/firebase-tools/files/11490316/firepit-log.txt)

### [REQUIRED] Environment info
Local environment

**firebase-tools: curl -sL https://firebase.tools | bash**

**Platform: macOS Ventura 13.3.1 (a) (22E772610a)**

### [REQUIRED] Test case
Install CLI firebase on macOS Ventura

### [REQUIRED] Expected behavior
Firebase installed

### [REQUIRED] Actual behavior
his tool has encountered an error. Please file a bug on Github (https://github.com/firebase/firebase-tools/) and include firepit-log.txt

**Comment by balleza316** [comment]
[REQUIRED] Environment info
firebase-tools:
firebase CLI

Platform:
macOS Ventura 13.3.1 (a) (22E772610a)

[REQUIRED] Test case
Install CLI firebase on macOS Ventura

[REQUIRED] Steps to reproduce
curl -sL https://firebase.tools/ | bash

[REQUIRED] Expected behavior
firebase CLI Installed

[REQUIRED] Actual behavior
his tool has encountered an error. Please file a bug on Github (https://github.com/firebase/firebase-tools/) and include firepit-log.txt
[firepit-log.txt](https://github.com/firebase/firebase-tools/files/11490398/firepit-log.txt)

**Comment by christhompsongoogle** [comment]
Hi [balleza316](https://github.com/balleza316),

As a first step, try deleting the following directory before installing: /Users/HumbertoBanorte/.cache/firebase

It looks like there was a permissions problem in downloading some firebase cache items.

**Comment by balleza316** [comment]
Same problem

Attach the new firepit-log.txt
[firepit-log.txt](https://github.com/firebase/firebase-tools/files/11491820/firepit-log.txt)

**Comment by bkendall** [comment]
@balleza316 

Can you check the permissions on `/Users/HumbertoBanorte/.cache` and `/Users/HumbertoBanorte/.cache/firebase`? `ls -al /Users/HumbertoBanorte/.cache` should give all the information necessary. It would be odd if you didn't have the right permissions to modify that folder, but it could be possible.
