### ISSUE TITLE
[web frameworks]  .env is not loaded by simpleProxy

### ISSUE THREAD

**Issue by Geoffrey-Pliez** [firebase/firebase-tools#5852]
### [REQUIRED] Environment info

**firebase-tools:**
12.0.x

**Platform:**
Windows

### [REQUIRED] Steps to reproduce

Since https://github.com/firebase/firebase-tools/pull/5774 , emulator no longer retrieves variables from env.

For example, the simple proxy function no longer emulates the __session call because [firebaseDefaultsJSON](https://github.com/firebase/firebase-tools/blob/b0b6797198d3e6fde8631a03d234a31dcf3b3f3d/src/frameworks/utils.ts#L75) is always null

possible solutions are either not to reset the .env in the prepareFramework function or to load them in the emulator

### [REQUIRED] Expected behavior

emulator load .env 

### [REQUIRED] Actual behavior

it's not the case

**Comment by aalej** [comment]
Hi @Geoffrey-Pliez. Apologies for the delay, and thanks for providing details about your observations. I would like to ask if it would be okay if you could provide us with more details like how your app retrieves the env values or if possible an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) so that I can try to reproduce the issue?

**Comment by Geoffrey-Pliez** [comment]
Hi @aalej,

I'm using the following code to connect my app

`const auth = await signInWithEmailAndPassword(getAuth(), login, password);`
`const idToken = await auth.user.getIdToken();`
 `await fetch("/__session", {
        method: idToken ? "POST" : "DELETE",
        headers: idToken ? { Authorization: `Bearer ${idToken}` } : {},
      });`

and my app uses simpleProxy to emulate prod mode via [Astro project](https://github.com/firebase/firebase-tools/blob/b0b6797198d3e6fde8631a03d234a31dcf3b3f3d/src/frameworks/astro/index.ts#L79)  on hosting Emulator.

SimpleProxy tries to retrieve [env variables](https://github.com/firebase/firebase-tools/blob/b0b6797198d3e6fde8631a03d234a31dcf3b3f3d/src/frameworks/utils.ts#L75) but these are always null since PR[#5774](https://github.com/firebase/firebase-tools/pull/5774).

Indeed PR#5774 reset process.env in the [prepareFramework function](https://github.com/firebase/firebase-tools/blob/b0b6797198d3e6fde8631a03d234a31dcf3b3f3d/src/frameworks/index.ts#L542)

Neither simpleProxy nor emulator loads variables again.

Solution :
 either not reset process.env on prepareFramework  and  remove

    `delete process.env.__FIREBASE_DEFAULTS__;`
    `delete process.env.__FIREBASE_FRAMEWORKS_ENTRY__;`

or load env in simpleProxy and replace 
    `const firebaseDefaultsJSON = process.env.__FIREBASE_DEFAULTS__`
    by
    `const firebaseDefaultsJSON = "getFirebaseDefaultsFromFile(.env)"`
