### ISSUE TITLE
Python Functions emulator fails with space in project directory path

### ISSUE THREAD

**Issue by benbrunyee** [firebase/firebase-tools#5854]
### [REQUIRED] Environment info

**firebase-tools:** 12.0.1

**Platform:** Windows

### [REQUIRED] Test case

1. Create a directory with a space e.g., `C:\Users\name\Desktop\project directory\
2. Run `firebase init functions` and run through the setup for `Python` functions.
3. Fix any pip version errors you get and re-run `firebase init functions` to get dependencies installed
4. Run `firebase init emulators` and setup the `functions` emulator
5. Run `firebase emulators:start` and see error below:

```
bruny:vite-project$ firebase emulators:start
i  emulators: Starting emulators: functions
!  ui: Emulator UI unable to start on port 4000, starting on 4001 instead.
!  functions: The following emulators are not running, calls to these services from the Functions emulator will affect production: auth, firestore, database, hosting, pubsub, storage
i  ui: Emulator UI logging to ui-debug.log
i  functions: Watching "C:\Users\bruny\Desktop\project directory\vite-project\functions" for Cloud Functions...
!  functions: Failed to detect functions from source FirebaseError: User code failed to load. Cannot determine backend specification.
stderr:C:\Users\bruny\AppData\Local\Programs\Python\Python311\python.exe: can't open file 'C:\\Users\\bruny\\Desktop\\project': [Errno 2] No such file or directory

!!  functions: Failed to load function definition from source: FetchError: request to http://127.0.0.1:8081/__/quitquitquit failed, reason: connect ECONNREFUSED 127.0.0.1:8081
```

### [REQUIRED] Steps to reproduce

(More environment info)
`yarn --version` = `1.22.19`
`vite --version` = `vite/4.3.3 win32-x64 node-v16.13.2`

1. Create a directory with a space e.g., `C:\Users\name\Desktop\project directory\
2. Create a SveltKit vite project in the above directory with `yarn create vite`. Select `SvelteKit` and `TypeScript` as the options. The project name here does not matter
4. Run `firebase init functions` and run through the setup for `Python` functions.
5. Fix any pip version errors you get and re-run `firebase init functions` to get dependencies installed
6. Run `firebase init emulators` and setup the `functions` emulator
7. Run `firebase emulators:start` and see error below:

```
bruny:vite-project$ firebase emulators:start
i  emulators: Starting emulators: functions
!  ui: Emulator UI unable to start on port 4000, starting on 4001 instead.
!  functions: The following emulators are not running, calls to these services from the Functions emulator will affect production: auth, firestore, database, hosting, pubsub, storage
i  ui: Emulator UI logging to ui-debug.log
i  functions: Watching "C:\Users\bruny\Desktop\project directory\vite-project\functions" for Cloud Functions...
!  functions: Failed to detect functions from source FirebaseError: User code failed to load. Cannot determine backend specification.
stderr:C:\Users\bruny\AppData\Local\Programs\Python\Python311\python.exe: can't open file 'C:\\Users\\bruny\\Desktop\\project': [Errno 2] No such file or directory

!!  functions: Failed to load function definition from source: FetchError: request to http://127.0.0.1:8081/__/quitquitquit failed, reason: connect ECONNREFUSED 127.0.0.1:8081
```

### [REQUIRED] Expected behavior

The functions emulator should be able to handle spaces in directory paths.
This should work in Git Bash, CMD, PowerShell

### [REQUIRED] Actual behavior

The emulator fails to run unless I modify the path to remove the space.
This is the case when running using Git Bash, CMD and PowerShell

**Comment by aalej** [comment]
Hi @benbrunyee, thanks for reporting this issue. I was able to replicate the behavior you mentioned using firebase-tools v12.0.1 on a macOS machine by following steps similar to the one provided in your test case:

1. Create a directory with a space 
2. Run `firebase init functions` and run through the setup for Python functions.
3. Run `firebase init emulators` and setup the functions emulator
4. Run `firebase emulators:start`

That said, I’ll notify our team about this so that we can investigate this issue. I'll also be marking this issue as reproducible.

**Comment by taeold** [comment]
The issue should be resolved in the next release. Thank you for reporting the issue!
