### ISSUE TITLE
Firebase deploy does not automatically build Flutter apps

### ISSUE THREAD

**Issue by chimon2000** [firebase/firebase-tools#5862]
### [REQUIRED] Environment info

```bash
firebase --version
12.0.1
```

**firebase-tools:** 12.0.1

**Platform:** macOS

**firebase.json:**

```json
{
  "hosting": {
    "public": "build/web",
    "ignore": ["firebase.json", "**/.*", "**/node_modules/**"]
  }
}

```

### [REQUIRED] Test case

https://github.com/chimon2000/test_preview_deploys

### [REQUIRED] Steps to reproduce

1. Create a new Fluter project
2. Link the application to a Firebase project using `firebase init`
3. Deploy application using `firebase deploy`

### [REQUIRED] Expected behavior

Doing a Firebase deploy in a new Flutter repository automatically triggers a build.

### [REQUIRED] Actual behavior

The following error:

```bash
firebase deploy

=== Deploying to 'test-preview-deploys'...

i  deploying hosting
i  hosting[test-preview-deploys]: beginning deploy...

Error: Directory 'build/web' for Hosting does not exist.
```

**Additional Context:**

https://twitter.com/jamesuriah/status/1659377435165466624?s=20

**Comment by aalej** [comment]
Hi @chimon2000, thanks for providing a detailed description of the issue you encountered. I tried to reproduce this, but I did not encounter any errors while deploying the web app. Could you try following these steps to see if you would still encounter any issue while deploying:

1. Run `flutter create <app_name>` to create a Flutter app, then cd into the directory
2. Run `firebase experiments:enable webframeworks`
3. Run `firebase init hosting --project <project_id>`, which will show a prompt
```
? Detected an existing Flutter codebase in the current directory, should we use this? (Y/n) 
```
4. Run `firebase deploy`

If you still encounter any errors after doing so, could you try running `firebase deploy --debug` and provide us with the output debug logs? This is so that we can get a better understanding of what caused the issue.

**Comment by chimon2000** [comment]
My issue was that I was using the "public" config rather than the
"source" one. Does the CLI prompt for that after i enable webframeworks?

On May 19, 2023, GitHub Notifications ***@***.***> wrote:
> Hi @chimon2000 <https://github.com/chimon2000>, thanks for providing a
> detailed description of the issue you encountered. I tried to
> reproduce this, but I did not encounter any errors while deploying the
> web app. Could you try following these steps to see if you would still
> encounter any issue while deploying:
>
> 1. Run flutter create <app_name> to create a Flutter app, then cd into
>    the directory
> 2. Run firebase experiments:enable webframeworks
> 3. Run firebase init hosting --project <project_id>, which will show a
>    prompt
>
> ? Detected an existing Flutter codebase in the current directory,
> should we use this? (Y/n)
> 1. Run firebase deploy
>
> If you still encounter any errors after doing so, could you try
> running firebase deploy --debug and provide us with the output debug
> logs? This is so that we can get a better understanding of what caused
> the issue.
>

—
Reply to this email directly, view it on GitHub
<https://github.com/firebase/firebase-tools/issues/5862#issuecomment-
1554633688>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/ABUWPFMKM6OS5FIBDVIZD7TXG55DNANCNFSM6AAAAAAYHHRMPM>.
You are receiving this because you were mentioned.Message ID:
***@***.***>

**Comment by jamesdaniels** [comment]
@chimon2000 yeah, you need to enable the web frameworks experiment to see the prompts during `init hosting`

**Comment by jamesdaniels** [comment]
Flutter docs now live https://firebase.google.com/docs/hosting/frameworks/flutter

**Comment by chimon2000** [comment]
> Flutter docs now live https://firebase.google.com/docs/hosting/frameworks/flutter

Once I made those changes everything worked like a charm!
