### ISSUE TITLE
Failed to generate manifest from function source

### ISSUE THREAD

**Issue by PMLS3** [firebase/firebase-tools#5877]
### Related issues

No

### [REQUIRED] Version info
 "firebase-admin": "^11.5.0",
    "firebase-functions": "^4.4.0",

**node:**
v18.15.0

**firebase-functions:** 
4.4.0

**firebase-tools:**
12.0.0

**firebase-admin:**
11.7.0

### [REQUIRED] Test case

firebase init, uncomment given helloWorld funciton and run npm run firebase deploy --only functions

Deployment of functions

### [REQUIRED] Actual behavior

 Failed to load function definition from source: Failed to generate manifest from function source: SyntaxError: Invalid or unexpected token
### Were you able to successfully deploy your functions?

No...

**Comment by imardini** [comment]
I'm having the same error:
`[debug] [2023-06-01T11:26:51.877Z] Building nodejs source
[debug] [2023-06-01T11:26:51.878Z] Could not find functions.yaml. Must use http discovery
[debug] [2023-06-01T11:26:51.887Z] Found firebase-functions binary at '/Users/ivanmardini/profile-maker/app/server/functions/node_modules/.bin/firebase-functions'
[debug] [2023-06-01T11:26:52.028Z] Serving at port 8403

[debug] [2023-06-01T11:26:52.070Z] Got response from /__/functions.yaml Failed to generate manifest from function source: SyntaxError: Unexpected token '{'
[debug] [2023-06-01T11:26:52.074Z] Failed to parse functions.yaml incomplete explicit mapping pair; a key node is missed; or followed by a non-tabulated empty line at line 1, column 62:
     ... rom function source: SyntaxError: Unexpected token '{'
                                         ^ {"name":"YAMLException","reason":"incomplete explicit mapping pair; a key node is missed; or followed by a non-tabulated empty line","mark":{"name":null,"buffer":"Failed to generate manifest from function source: SyntaxError: Unexpected token '{'\n\u0000","position":61,"line":0,"column":61},"message":"incomplete explicit mapping pair; a key node is missed; or followed by a non-tabulated empty line at line 1, column 62:\n     ... rom function source: SyntaxError: Unexpected token '{'\n                                         ^"}
[debug] [2023-06-01T11:26:52.077Z] shutdown requested via /__/quitquitquit

[error] 
[error] Error: Failed to load function definition from source: Failed to generate manifest from function source: SyntaxError: Unexpected token '{'
`

**Comment by madmacc** [comment]
I have the same issue. Deploying one function.
I can deploy to dev environment but not to prod.

Error:
`Error: Failed to load function definition from source: Failed to generate manifest from function source: TypeError: Cannot read properties of undefined (reading 'key')`

    "firebase-admin": "^9.12.0",
    "firebase-functions": "^3.24.1",
    "firebase-tools": "^9.22.0",
