### ISSUE TITLE
Unable to specify function deployment region using defineString

### ISSUE THREAD

**Issue by nikita-mishchenko** [firebase/firebase-tools#5897]
### [REQUIRED] Environment info

**firebase-tools:** 11.30.0

**Platform:** macOS

### [REQUIRED] Test case

Having the followin code in typecript
```
export const functionsDefaultLocationParam = defineString(
    'FUNCTIONS_DEFAULT_LOCATION',
    {
        default: 'europe-west1',
    },
)

export const myFunction = onCall<
    MyFunctionRequest,
    Promise<MyFunctionResponse>
>(
    {
        region: functionsDefaultLocationParam,
    },
   async (request): Promise<MyFunctionResponse> => {
      // some logic inside
   }
)
```

`.env` file:
```
FUNCTIONS_DEFAULT_LOCATION=europe-west1
```

### [REQUIRED] Steps to reproduce

Having code from above run `firebase deploy`

### [REQUIRED] Expected behavior

Function deployed

### [REQUIRED] Actual behavior

`Error: Illegal type coercion of param FUNCTIONS_DEFAULT_LOCATION to type string[]`

### Some additional information

For some reason it is trying to resolve it as string[] instead of string.
I tried to debug a bit and found that for some reason method `resolveList` from `src/deply/functions/params.ts` is triggered and it has the following part which then throw an error:
```
if (typeof from === "string") {
    return resolveExpression("string[]", from, paramValues) as string[];
}
```

**Comment by blidd-google** [comment]
I'm going to close this issue for now, as the feature request is already being tracked here: https://github.com/firebase/firebase-functions/issues/1369.

**Comment by nikita-mishchenko** [comment]
Ok, great. Thanks

**Comment by StevenH86** [comment]
> firebase/firebase-functions#1369

You can't you dotenv method because region needs to be set during deployment and env vars are only accessible at runtime.
