### ISSUE TITLE
firebase init issue

### ISSUE THREAD

**Issue by nooralsbah** [firebase/firebase-tools#59]
Hi 
I have problem when i run firebase init   in Terminal showed me this message 

Initialization Warning - Creating new firebase app inside a non-empty directory.
Initialization Error - Can't create new firebase app inside an existing firebase project
 
any idea to help

**Comment by drtriumph** [comment]
It looks like you're trying to initialize a new app within an already initialized folder. You only need to run `firebase init` once, and after that you should just need to run `firebase deploy` to deploy a new version of your site.

If you want to start afresh and reinitialize the directory you're in, you need to find and delete the `firebase.json` file that's in one of the parent folders to where you're currently running the tools from

**Comment by nooralsbah** [comment]
thank you everything works perfectly
