### ISSUE TITLE
Firestore 426 Upgrade Required error

### ISSUE THREAD

**Issue by elbro** [firebase/firebase-tools#5901]
### [REQUIRED] Environment info

**firebase-tools:** 12.21

**Platform:** Ubuntu 22.04 (Via WSL2)

### [REQUIRED] Test case

Node 18
openjdk 11.0.19

Same exact codebase / install steps works fine in Ubuntu 20, but not on this machine with Ubuntu 22 and all the same versions.

### [REQUIRED] Steps to reproduce

firebase emulators:start

appears to connect correctly.
![image](https://github.com/firebase/firebase-tools/assets/4560065/6c2f61f6-6bff-46c4-80ab-363a58b1d2ad)

### [REQUIRED] Expected behavior

Should connect and work as usual

### [REQUIRED] Actual behavior

![image](https://github.com/firebase/firebase-tools/assets/4560065/edcd77d0-bbd1-46ab-8ab4-0ba4030996e9)

**Comment by christhompsongoogle** [comment]
Hi [elbro](https://github.com/elbro), can you share more information? The full HTTP URL that's failing, how to reproduce it, some code snippets if possible.

What version of firebase are you using?
HTTP 2.0 may yield better results also

**Comment by elbro** [comment]
Getting this again;

firebase --version: 12.4.2

in console i see this request returning 426
`POST | http://localhost:9100/google.firestore.v1.Firestore/Listen/channel?VER=8&database=projects/swg-baas/databases/(default)&RID=26737&CVER=22&X-HTTP-Session-Id=gsessionid&zx=b15b562ci40&t=1`

firebase.json:
```"emulators": {
    "auth": {
      "port": 9099
    },
    "functions": {
      "port": 9101
    },
    "firestore": {
      "port": 9100
    },
    "ui": {
      "enabled": true,
      "port": 8000
    },
    "singleProjectMode": true
  },```

**Comment by christhompsongoogle** [comment]
In the original report it looks like listCollectionIds is being called - is this from the Emulator UI? Or does the `connectFirestoreEmulator` fail immediately?

**Comment by elbro** [comment]
> listCollectionIds



> In the original report it looks like listCollectionIds is being called - is this from the Emulator UI? Or does the `connectFirestoreEmulator` fail immediately?
> 
> If we can reproduce the problem on our end it'll make fixing it much faster.

Hey, it's failing immediately; in console i see immediate 426 POST errors. Can't figure out why it's not connecting to the emulator - how can I troubleshoot that?

**Comment by elbro** [comment]
Completely ignoring my app, I see `Access to fetch at 'http://127.0.0.1:9100/v1/projects/swg-baas/databases/(default)/documents:listCollectionIds' from origin 'http://localhost:8000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.` error visiting the emulator UI

**Comment by elbro** [comment]
edit: pretty sure it's related to this https://github.com/firebase/firebase-tools-ui/issues/332
