### ISSUE TITLE
Firebase deploy send always dev version

### ISSUE THREAD

**Issue by Geoffrey-Pliez** [firebase/firebase-tools#5902]
### [REQUIRED] Environment info

**firebase-tools:**
 v12.0.x

**Platform:**
all

### [REQUIRED] Steps to reproduce

run firebase deploy with a web framework project

### [REQUIRED] Expected behavior

const buildTargetPurpose = 'deploy'

### [REQUIRED] Actual behavior

const buildTargetPurpose = 'serve'

the cause is that the context._name variable injected into the prepareFrameworks function by the deploy function no longer exists

**Comment by iSuslov** [comment]
@Geoffrey-Pliez JFYI there is a workaround to use `FIREBASE_FRAMEWORKS_BUILD_TARGET=production firebase deploy ` which I saw in a similar thread

**Comment by aalej** [comment]
Hi @Geoffrey-Pliez, it looks like issue you described is the same as #5896. As mentioned by @iSuslov, a workaround is to use `FIREBASE_FRAMEWORKS_BUILD_TARGET=production firebase deploy` or to use firebase-tools v12.1.0 while waiting for the fix to be released.

That said, I’ll be closing this issue as a duplicate. If you think this is a mistake, feel free to re-open. Thanks!
