### ISSUE TITLE
/internal/setRules endpoint on the emulator is no longer working for rules unit testing

### ISSUE THREAD

**Issue by etienne-ditchlabs** [firebase/firebase-tools#5904]
### [REQUIRED] Environment info

**firebase-tools:** 12.2.1

**Platform:** macOS

### [REQUIRED] Test case

The PR #4902 broke the end point in the `@firebase/rules-unit-testing` package used to setup the storage rules when unit testing ([See broken call](https://github.com/firebase/firebase-js-sdk/blob/df8604e4dada5874ce0513e3376ded130b6231b4/packages/rules-unit-testing/src/impl/rules.ts#L75)).

Therefore this code is no longer working:
```
import {
  initializeTestEnvironment,
} from "@firebase/rules-unit-testing"

beforeAll(async () => {
    testEnv = await initializeTestEnvironment({
      projectId: process.env.GCLOUD_PROJECT,
      storage: {
        rules: fs.readFileSync("../storage.rules", "utf8"),
      },
    })
  })
```

### [REQUIRED] Steps to reproduce

1. Setup the `storage.rules` file
2. Run the test

### [REQUIRED] Expected behavior

Should work like it used to be by loading the `storage.rules` into the emulator using the `/internal/setRules` endpoint.

### [REQUIRED] Actual behavior

```
Not Implemented

      at node_modules/@firebase/rules-unit-testing/src/impl/rules.ts:87:11
      at step (node_modules/@firebase/rules-unit-testing/dist/index.cjs.js:74:23)
      at Object.next (node_modules/@firebase/rules-unit-testing/dist/index.cjs.js:55:53)
      at fulfilled (node_modules/@firebase/rules-unit-testing/dist/index.cjs.js:45:58)
```

**Comment by si1k** [comment]
For anyone searching for help on the dreaded "Not Implemented" error coming from your unit testing. 

Downgrade to 12.2.0 or set that within your Action  installing firebase-tools, e.g., `yarn global add firebase-tools@12.2.0`. You may need to delete yarn.lock/node_modules to clear things up. This was a frustrating thing to troubleshoot with the "Not Implemented" error.

**Comment by tonyjhuang** [comment]
Hi, taking a look this week.

**Comment by armthethinker** [comment]
Ran into this too. Thought it was something I did wrong when setting up a new machine. @si1k's [suggestion of downgrading to 12.2.0](https://github.com/firebase/firebase-tools/issues/5904#issuecomment-1570109035) got my project working again.

**Comment by matt-hall-zory** [comment]
Any progress? I'm stuck on a 12.2.0 downgrade.

**Comment by Psycarlo** [comment]
Downgrading to 12.2.0 worked for me.

- Removed yarn.lock and node_modules

`npm -g install firebase-tools@12.2.0`
`yarn add --dev firebase-tools@12.2.0`
