### ISSUE TITLE
Installation issue (enoversions)

### ISSUE THREAD

**Issue by nimonian** [firebase/firebase-tools#591]
### Version info

Not installed

### Steps to reproduce

Install Node.js, npm and run `npm i -g firebase-tools`

### Expected behavior

firebase-tools is installed

### Actual behavior

Installation fails with the message `npm ERR! No valid versions available for timed-out`

### Other information

I haven't checked the logs because I don't know what to look for. Maybe someone who knows better can direct me. I updated Node.js and npm shortly before attempting. I'm on Windows. The whole message from the console is 

    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: timed-out@^4.0.1 (node_modules\firebase-tools\node_modules\got\node_modules\timed-out):
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: No valid versions available for timed-out
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: duplexer3@^0.1.4 (node_modules\firebase-tools\node_modules\got\node_modules\duplexer3):
    npm WARN 404 SKIPPING OPTIONAL DEPENDENCY: Not Found: duplexer3@^0.1.4

    npm ERR! code ENOVERSIONS
    npm ERR! No valid versions available for timed-out

**Comment by githubsaturn** [comment]
Someone reported this issue for my package as well. Did some digging and turned out to be a problem with `update-notifier` package. Simply running `npm i update-notifier` fails.

**Comment by twiedow** [comment]
I get the same error. When searching in the nom registry there is no such module. But I have no idea if there is actually a dependency on a module with such name. npm-remote-ls does not list a dependency with such name.

**Comment by jwiesmann** [comment]
I am having exactly the same issue.. 
Updated to node v8.9.4 and npm 5.6.0 did not help.
Here the relevant logs from npm 

> 1428 warn optional SKIPPING OPTIONAL DEPENDENCY: timed-out@^4.0.1 (node_modules/firebase-tools/node_modules/got/node_modules/timed-out):
> 1429 warn optional SKIPPING OPTIONAL DEPENDENCY: No valid versions available for timed-out
> 1430 verbose type range
> 1431 verbose stack timed-out: No valid versions available for timed-out

**Comment by terrybleger** [comment]
I think the author/maintainer for timed-out was already dead. Please fix this asap.

**Comment by githubsaturn** [comment]
Turned out npm is down!
https://status.npmjs.org/

**Comment by terrybleger** [comment]
Then we should kill whoever that made npm down.

**Comment by nimonian** [comment]
Looks like this was just a case of bad timing! The npm status says there are a few more packages left to restore. I'll confirm when I have it working so the issue can be closed.

**Comment by krupper** [comment]
floatdrop/pinkie-promise#4

**Comment by krupper** [comment]
floatdrop/pinkie-promise#4

**Comment by krupper** [comment]
The problem is solved! :D @nimonian

**Comment by nimonian** [comment]
Yes indeed! @krupper Another mystery solved. `firebase-tools` is now installed and working. Thanks everyone.
