### ISSUE TITLE
Functions - Failed to initialize a region

### ISSUE THREAD

**Issue by diblaze** [firebase/firebase-tools#592]
### Version info
3.16.0

### Steps to reproduce

Uploading a simple function using "firebase deploy"

### Expected behavior

Function gets uploaded without issue.

### Actual behavior

Error message is cast:
 `!  functions[sendNotification]: Deployment error.
Failed to initialize a region`

**Comment by laurenzlong** [comment]
This is a production issue, not an issue with firebase-tools, please file a [support ticket](https://firebase.google.com/support/) if you are still experiencing it.

**Comment by maheshwarLigade** [comment]
I am facing same error While deploying function from google action console.

The deployment of your Cloud Function failed:
Failed to initialize region (action ID: 97dda049805e7e13)

**Comment by SandeepJJoshi** [comment]
getting same error!!
Failed to initialize region (action ID: 9fe58f0678ecae0f)

**Comment by thechenky** [comment]
Hi @maheshwarLigade and @SandeepJJoshi thanks letting us know. There were some issues with deployments in the time period you were experiencing this, but they should now be resolved. Can you try again and let me know if you're still seeing these issues? Which regions were you trying to deploy your functions to?

**Comment by thechenky** [comment]
Thanks for the update!

**Comment by rohit-tambe** [comment]
I face same issue even after enable cloud function from gcc

**Comment by moaaz-bhnas** [comment]
I'm having the same issue
