### ISSUE TITLE
Unable to fetch from emulator realtime-database

### ISSUE THREAD

**Issue by mikcsabee** [firebase/firebase-tools#5926]
### [REQUIRED] Environment info

**firebase-tools: 12.2.1**

**Platform: Windows, Ubuntu**

### [REQUIRED] Test case

I try to fetch the config entry from the realtime database, using the deployed emulator. The following code works, if the `initializeApp` uses the production variables, but if I try to use the emulator, it's timeouts.

```javascript
const admin = require("firebase-admin");

console.log(
  "FIREBASE_DATABASE_EMULATOR_HOST",
  process.env.FIREBASE_DATABASE_EMULATOR_HOST
);
console.log("FIRESTORE_EMULATOR_HOST", process.env.FIRESTORE_EMULATOR_HOST);
console.log("GCLOUD_PROJECT", process.env.GCLOUD_PROJECT);

const databaseURL = `https://${process.env.GCLOUD_PROJECT}.firebaseio.com`;

console.log("databaseURL: ", databaseURL);

admin.initializeApp({
  projectId: process.env.GCLOUD_PROJECT,
  databaseURL,
});

const db = admin.database();

function getConfig() {
  return new Promise((resolve, reject) => {
    const ref = db.ref("config");
    ref
      .once(
        "value",
        (snapshot) => {
          resolve(snapshot.val());
        },
        (error) => {
          console.error("error -1-", error);
          reject(error);
        }
      )
      .catch((error) => {
        console.error("error -2-", error);
        reject(error);
      });

    setTimeout(() => reject("Timeout"), 30_000);
  });
}

console.log("try to fetch config...");

getConfig()
  .then((value) => {
    console.log("value", value);
    process.exit(0);
  })
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
```

### [REQUIRED] Steps to reproduce

```sh
npm install
export FIREBASE_DATABASE_EMULATOR_HOST="localhost:9000"
export FIRESTORE_EMULATOR_HOST="localhost:8080"
export GCLOUD_PROJECT="test"
node index.js
```

### [REQUIRED] Expected behavior

Print the config entry.

### [REQUIRED] Actual behavior
```
FIREBASE_DATABASE_EMULATOR_HOST localhost:9000
FIRESTORE_EMULATOR_HOST localhost:8080
GCLOUD_PROJECT test
databaseURL:  https://test.firebaseio.com/
try to fetch config...
Timeout
```

More info in the example repo: https://github.com/mikcsabee/firebase-emulator-admin
This is how I running it: https://github.com/mikcsabee/firebase-emulator-admin/blob/main/.github/workflows/run.yml
And here is the output:  https://github.com/mikcsabee/firebase-emulator-admin/actions/runs/5135757339/jobs/9241606639

**Comment by aalej** [comment]
Hi @mikcsabee, thanks for reaching out and providing an MCVE. From what I understand, the code you provided reads a value from the Realtime Database. When connecting to an actual Firebase project, you are able to get the values, but when using the emulator, you are unable to get the value which results in a “Timeout”.

I’m thinking this issue might be related to https://github.com/node-fetch/node-fetch/issues/1624 where Node 18 defaults to ipv6 address resolution. Could you try changing `localhost` to `127.0.0.1` to see if there would be any changes in the behavior?

```bash
export FIREBASE_DATABASE_EMULATOR_HOST="127.0.0.1:9000"
export FIRESTORE_EMULATOR_HOST="127.0.0.1:8080"
export GCLOUD_PROJECT="test"
```

Also, does changing the host for the Realtime Database emulator to `0.0.0.0` change anything? You can set this in firebase.json alongside the port:

```json
"database": {
  "host": "0.0.0.0",
  "port": 9000
},
```

**Comment by mikcsabee** [comment]
Hi @aalej .
Thanks for the hint, that solved the issue :)
