### ISSUE TITLE
Firebase Hosting / npm

### ISSUE THREAD

**Issue by RicoThorsoe** [firebase/firebase-tools#593]
<img width="624" alt="skaermbillede 2018-01-07 kl 16 53 46" src="https://user-images.githubusercontent.com/35184386/34651084-80cdcbce-f3cb-11e7-9e36-f6c8e93f5f28.png">
pleas somebody help!
I've tried everything! but nothing works I've searched the web for more than 10 hours. I can not find anything that works

**Comment by merlinnot** [comment]
What do you mean? What doesn't work?

**Comment by RicoThorsoe** [comment]
<img width="407" alt="skaermbillede 2018-01-07 kl 22 15 29" src="https://user-images.githubusercontent.com/35184386/34654180-4f00f102-f3f8-11e7-99f7-ba0fb6ac5db9.png">
<img width="865" alt="skaermbillede 2018-01-07 kl 22 15 01" src="https://user-images.githubusercontent.com/35184386/34654181-4f1ca3c0-f3f8-11e7-96a3-2d4d386ca2d2.png">
When I write (firebase init) my comando doesn't work, it would look like the image with the big firebase sign

**Comment by merlinnot** [comment]
It seems like your `$HOME/.npm-global/bin` is not in your `$PATH`

You can learn more about it here: https://coolestguidesontheplanet.com/add-shell-path-osx/

If you will still have a problem, please run `echo $PATH` and paste the output here.

**Comment by RicoThorsoe** [comment]
<img width="574" alt="skaermbillede 2018-01-07 kl 23 14 18" src="https://user-images.githubusercontent.com/35184386/34654768-8e6e1ce0-f400-11e7-9126-58cdeee370ef.png">
<img width="446" alt="skaermbillede 2018-01-07 kl 23 12 18" src="https://user-images.githubusercontent.com/35184386/34654769-8e8b5b52-f400-11e7-85c4-cc89eb7f9f6a.png">
It still doesn't  work :( Maybe I did something wrong with Picture Number 1?

**Comment by merlinnot** [comment]
As you can see it doesn’t show up in your `$PATH`. Did you save the file? Did you restart your terminal?

**Comment by merlinnot** [comment]
I can also highly recommend using https://brew.sh to make installing everything on the MacOS much easier, so you don’t run into problems like this.

**Comment by RicoThorsoe** [comment]
How can I see if I have saved the file?

**Comment by RicoThorsoe** [comment]
ohh I will try that

**Comment by merlinnot** [comment]
You can run
`echo 'export PATH="$HOME/.npm-global/bin:$PATH"' >> ~/.bash_profile`, restart your terminal and you should be good.

Pro tip for the future: when you fix something, try to understand why didn’t it work earlier and why does it work now. The most important thing in programming is to learn every single day.

**Comment by RicoThorsoe** [comment]
Many thanks for all the help

**Comment by RicoThorsoe** [comment]
it works now, thank you for your time

**Comment by merlinnot** [comment]
Remember to close the issue.
