### ISSUE TITLE
/blog goes to 404 using rewrites

### ISSUE THREAD

**Issue by checho221** [firebase/firebase-tools#5938]
* Operating System version: Windows 11
  * Browser version: _____
  * Firebase SDK version: _____
  * Firebase Product: hosting

I am using Next.js Rewrite feature and it is working well on localhost and other hosting but in firebase the index page for blog goes to 404 page

I have the following route:

/blog/[id].js - Working well on firebase

In next.conf.js and firebase.json

"rewrites": [
      {
        "source": "/blog",
        "destination": "/blog/default"
      }
]

When it is deployed the /blog index falls to 404, others dynamic routes are working well like /blog/post-1 or any

**Comment by checho221** [comment]
> This seems to be a hosting question and is out of scope of this repo. I'm going to move it to the CLI repo as the CLI handles the hosting deploy, and if it's further back from that, they can reroute it to the appropriate hosting contact.

Please provide link to CLI repo so i can open a new issue.

@hsubox76  I realized recently that the original rewrites in next.config.js are being respected, but at the internal level of the application using, for example, the <Link> of nextjs, but when updating the route manually in the browser it responds 404

**Comment by joehan** [comment]
Hey @checho221, this issue was moved over to the right repo. Could you share the version of next.js you are deploying, as well as the version of firebase-tools that you are using to deply with (`firebase --version`)?

**Comment by checho221** [comment]
Hello @joehan, could you provide link to the issue in that repo? 

Nextjs V12.3.1
Firebase V12.7.0

**Comment by checho221** [comment]
I resolved by using next.conf.js rewrites as ever and firebase rewrites going to functions

Routing:
/pages/blog/[id].js

Nextjs:

"rewrites": [
      {
        "source": "/blog",
        "destination": "/blog/default"
      }
    ]

firebase.json:

"rewrites": [
      {
        "source": "/blog",
        "function": "funcName"
      }
    ]
    
All firebase dynamic routes are handled by a fb function and static ones are handled by hosting
