### ISSUE TITLE
Hot reloading of local webserver

### ISSUE THREAD

**Issue by valorloff** [firebase/firebase-tools#594]
Hi!
can we expect in the future hot reloaded dev server? 
and nodemonable functions local emulator?
Thanks

**Comment by laurenzlong** [comment]
The functions emulator (through `firebase serve --only functions` and `firebase experimental:functions:shell`) already does hot reloading.

The hosting emulator also does hot reloading.

**Comment by mbleigh** [comment]
The Hosting emulator does not do hot reloading, and it's not in our near-term roadmap due to the additional dependencies it requires. We would like to make it easy to connect the Hosting emulator to live reload setups, though.

**Comment by laurenzlong** [comment]
Thanks for the correction!

**Comment by imjared** [comment]
Chiming in to express my support, subscribe to the issue, and clarify my "👍" . I definitely don't mind doing the dirty work and connecting to a hot reload setup but would love to have this option available as local dev of functions right now is a bit less than ideal.

As always, thanks for some rad work overall that makes my life sooo much easier.

**Comment by imjared** [comment]
Seems like this works now? https://firebase.google.com/docs/functions/local-emulator

> For both tools, code changes you make during an active session are automatically reloaded by the emulator. If your code needs to be transpiled (TypeScript, React) make sure to do so before running the emulator.

**Comment by laurenzlong** [comment]
Hot loading is supported in functions emulator, but not hosting emulator at the moment.

**Comment by MM3y3r** [comment]
Yes please. I would love to see this.

**Comment by Dinduks** [comment]
Hi. Any news of this?

**Comment by jiangell** [comment]
I've spent the last couple of hours looking into this. Why isn't there simply a proxy option for when serving locally?

Most developers would keep their frontend src's out side of their firebase deployment folder, why not just allow us to locally use the served spas in the emulator?

**Comment by samtstern** [comment]
@jiangell that is already possible today.  I normally have two terminals running:

1. Running my frontend build script with the `--watch` flag (or whatever your tool supports) which builds my site to `./dist` every time I save.
2. Running the Firebase Hosting local server (`firebase serve`) pointing at `./dist`

**Comment by jiangell** [comment]
@samtstern but that isn't HMR. I have already gotten my vue app to build --watch pointing into the emulator's public directory, but I still have to manually update the browser.

When vue serve is run, I believe it doesn't actually write files to disk, and it serves the app through an https server. What I would like to do is have the firebase hosting emulator be able to simply pull from the vue serve webserver, and thus have vue handle all the in browser HMR.

**Comment by dinvlad** [comment]
Have there been any updates on this?

**Comment by dinvlad** [comment]
As a workaround, this works great using Webpack DevServer: https://github.com/firebase/firebase-tools/issues/1676#issuecomment-698042925

**Comment by vdegenne** [comment]
browsersync to the rescue

**Comment by Dzivo** [comment]
How long will we have to do complicated stuff until we get development support we deserve might i remind you that we are paying for your services. Emulator and local development support as well as debuging and other things i nonexistant and then we wait for 6 years for simple features like this. It makes me puke when i have to work with GCP and Firebase

**Comment by MichelFloyd** [comment]
This package.json configuration works:
```
"scripts": {
    "build": "tsc",
    "build:watch": "tsc --watch",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log",
    "start": "concurrently \"npm run build:watch\" \"firebase emulators:start --only functions\"",
     },
```
With the above `npm start` hot reloads.

**Comment by ShaMan123** [comment]
#1676
Still very much relevant. HMR is an industry standard (thankfully).
Connecting the FE to BE requires work and needs HMR.
I would expect firebase to publish a vite plugin etc. to support this.
Sharing my vite config (a monkey patch for vite firebase like hosting) for anyone interested:

```typescript


import { readFileSync } from "fs";
import globToRegExp from "glob-to-regexp";
import { defineConfig, type ProxyOptions } from "vite";
import { emulators, hosting } from "./firebase.json";

let EMULATORS_ACTIVE

const firebaseConfig = JSON.parse(readFileSync("./.firebaserc").toString());
const projectId = firebaseConfig.projects.default;
const functionRewrites = Object.fromEntries(
  hosting.rewrites
    .filter((def) => !!def.function)
    .map(
      ({
        source,
        function: functionName,
        region = emulators.functions.region,
      }) => [
        `/${functionName}`,
        {
          target: EMULATORS_ACTIVE
            ? `http://localhost:${emulators.functions.port}/${projectId}/${region}/${functionName}`
            : `https://${region}-${projectId}.cloudfunctions.net/${functionName}`,
          changeOrigin: true,
          rewrite: (path) => path.replace(globToRegExp(source), ""),
        } satisfies ProxyOptions,
      ]
    )
);
const server = EMULATORS_ACTIVE
  ? {
      proxy: functionRewrites,
    }
  : undefined;

export default defineConfig({
  // ...
  server
})


```
