### ISSUE TITLE
Unable to set cloud function permissions

### ISSUE THREAD

**Issue by janek515** [firebase/firebase-tools#5958]
### [REQUIRED] Environment info

**firebase-tools:** 12.3.1

**Platform:** Windows

### [REQUIRED] Test case

I'm trying to create Cloud Functions with no public HTTP access. 
What I saw as the solution was to utilize the `invoker` property of `GlobalOptions`.
No matter what I set it to (i.e "private", "some-service-accoun[at]some-project.iam.gserviceaccount.com" ) the functions still deployed as a public one i.e. Cloud Run Invoker was set to `allUsers`

### [REQUIRED] Steps to reproduce

1. Create a Firebase project with functions enabled
2. execute `setGlobalOptions({ invoker: "private" })`
3. deploy the functions

### [REQUIRED] Expected behavior

In the Cloud Run panel, the functions should have the "Require Authentication" property set.

### [REQUIRED] Actual behavior

In the Cloud Run panel, the functions have the "Allow unauthenticated invocations" property set.

**Comment by janek515** [comment]
Hi, the code I was using was the following:
```ts
import { onRequest } from "firebase-functions/v2/https";
import { setGlobalOptions } from "firebase-functions/v2/options";

setGlobalOptions({
  region: "europe-west1",
  invoker: "private",
  memory: "128MiB",
});

export const hello = onRequest((_, res) => {
  res.send("Hello!");
});
```

The code you suggested actually worked, so the issue is only with the setGlobalOptions function.

**Comment by colerogers** [comment]
@janek515 Thanks for opening your first issue in Firebase! Looks like you found a little bug, I created a PR for it and we should have it patched in the next SDK release. Thanks!
