### ISSUE TITLE
Unable to use yarn in cloud functions

### ISSUE THREAD

**Issue by janek515** [firebase/firebase-tools#5960]
### [REQUIRED] Environment info

**firebase-tools:** 12.3.1

**Platform:** Windows

### [REQUIRED] Test case

When I'm using yarn (i.e. the yarn.lock file is present) and I try deploying Cloud Functions (Node.js 18 runtime) the following error appears. 
![image](https://github.com/firebase/firebase-tools/assets/37900649/b46c29c5-e577-4ea1-a65e-0a392582f6a6)
You can easily guess that what's happening is the docker image on Cloud Run tries to use yarn berry commands, but only yarn 1.x is installed there. The fix would be to add a `yarn set version berry` in the Dockerfile. I'm aware that this could be only partially connected with this repo, but I'm not sure where else to report it.

The workaround is to either exclude the `yarn.lock` file in `firebase.json` or to bundle yarn with the functions (using .yarnrc.yml's `yarnPath`), but this adds 2MB to the bundle.

Also someone referenced the same issue here https://stackoverflow.com/questions/76427975/firebase-functions-deployment-error-cant-resolve-command-plugin-not-found

### [REQUIRED] Steps to reproduce

1. Initialize js functions in a firebase project folder
2. use yarn to install the dependencies
3. deploy the functions

### [REQUIRED] Expected behavior
The functions should deploy.

### [REQUIRED] Actual behavior

The deployment fails with the above-mentioned error.

**Comment by Fuzzyma** [comment]
I had the same problem without docker. Firebase always uses yarn v1.
I solved it by miss-using the gcp-build script:

```json
{
  // ... other package.json stuff
  scripts: {
    "gcp-build": "yarn set version berry"
  }
}
```

**Comment by IchordeDionysos** [comment]
@Fuzzyma this does not work for me ...

How do you deploy the Cloud Function? are you using the `gcloud` CLI or do you use `firebase deploy`?

**Comment by joehan** [comment]
@IchordeDionysos IIUC, either way should work with the `gcp-build` script - that will be run on the Cloud Functions server when they build a container image for your code.

**Comment by joehan** [comment]
Hey all, Im going to close this issue since there is a clear workaround (set yarn version in package.json engines) and the root issue isn't in the repo. If you are still having trouble with functions using yarn and want to raise the issue further, please use the public issue tracker for Cloud Functions https://issuetracker.google.com/components/187195
