### ISSUE TITLE
Nuxt + firebase deployment for web frameworks failing.

### ISSUE THREAD

**Issue by Rohithgilla12** [firebase/firebase-tools#5964]
### [REQUIRED] Environment info

**firebase-tools:**
![image](https://github.com/firebase/firebase-tools/assets/19389850/1c493f28-38f0-47ce-9b55-82fb9c6433b5)

**Platform:** `macOS`

### [REQUIRED] Test case
When deploying a nuxt app to use firebase hosting, the deployment is successful but the app would resolve to 

![image](https://github.com/firebase/firebase-tools/assets/19389850/7c8e5b9f-6f70-47d3-8ded-2f9603c14a51)

Deployed domain
https://delete-me-fe49e.web.app/

### [REQUIRED] Steps to reproduce

- Initialise the nuxt project with ` npx nuxi init firebase-nuxt`
- `pnpm i` or `yarn` or `npm`
- `firebase init hosting`
- `firebase deploy` 

When in the interactive `firebase deploy` command, it asked for choosing regions for hosting, it asked if the project that is detected is `nuxt` or not. I did answer em right.

### [REQUIRED] Expected behavior

The app is deployed and I see my nuxt app.

### [REQUIRED] Actual behavior

Getting a 404 error.
![image](https://github.com/firebase/firebase-tools/assets/19389850/e60df7f9-09c5-467c-970c-b4197883bc5b)

**Comment by aalej** [comment]
Hi @Rohithgilla12. Apologies for the delay, and thanks for providing detailed steps on how to reproduce the issue. I was able to replicate the behavior you mentioned. That said, I’ll notify our team about this so that they can take a look. One thing I noticed is that when using firebase-tools v12.1.0, I did not encounter any issues deploying.

**Comment by Rohithgilla12** [comment]
@aalej 

Did the similar steps with firebase tools version `12.1.0`

![image](https://github.com/firebase/firebase-tools/assets/19389850/0ea74cfc-0754-4ce8-9606-ef87c12f35bc)


Output of the console
![image](https://github.com/firebase/firebase-tools/assets/19389850/766d1dda-fc5e-4444-939e-c35522917d21)

Output of the web app
![image](https://github.com/firebase/firebase-tools/assets/19389850/326b402f-92bc-41de-afad-aea1e6576841)

Sometimes this
![image](https://github.com/firebase/firebase-tools/assets/19389850/cc9e58e1-9496-4ed4-ae2f-ceb1407d9563)



Link for the deployed site 
https://delete-me-fe49e.web.app

**Comment by ekwus** [comment]
Hey

I've got the exact same issue, however downgrading to ```12.1.0``` didn't solve it for me. Everything working in the dev mode but also doesn't work in the emulator.

Additional bit of info is that the 404 Not Found page has the Nuxt favicon.ico so in part it is working

Cheers

Dave

**Comment by Abdulrhman02** [comment]
is there any update or workaround for this issue :)
