### ISSUE TITLE
Emulator fails to start for nextJS app

### ISSUE THREAD

**Issue by sgnagnarella** [firebase/firebase-tools#5970]
### [REQUIRED] Environment info

**firebase-tools: 11.28.0**

**Platform: macOS**

### [REQUIRED] Test case

1. Enable experimental web frameworks
2. Run `firebase init hosting`
3. Go through the options to create the boilerplate NextJS app.
4. Run `firebase emulators:start`
5. Emulator should run.

### [REQUIRED] Steps to reproduce

1. Enable experimental web frameworks
2. Run `firebase init hosting`
3. Go through the options to create the boilerplate NextJS app.
4. Run `firebase emulators:start`
5. Emulator crashes with the attached error.

### [REQUIRED] Expected behavior

Emulator running

### [REQUIRED] Actual behavior

emulator not running and throwing this error in the logs (Attaching)
[firebase-debug.log](https://github.com/firebase/firebase-tools/files/11730007/firebase-debug.log)

**Comment by aalej** [comment]
Hi @sgnagnarella, thanks for reaching out. You mentioned that you were using firebase-tools v11.28.0. As per our [docs](https://firebase.google.com/docs/hosting/frameworks/nextjs#before_you_begin), you’ll need to use the Firebase CLI v.12.1.0+ when using the Next.js web framework. 

Currently we’re looking into an issue where the emulator crashes [#5934](https://github.com/firebase/firebase-tools/issues/5934) which affects firebase-tools v12.30.0. While we’re investigating that issue, I would recommend using either v12.2.x or v12.1.0.

**Comment by sgnagnarella** [comment]
Deploy fails in 12.2 with this error:

Error: Directory 'hosting/public' for Hosting does not exist.

Both deploy and emulator work on 12.1 so I will stick with that.
