### ISSUE TITLE
Do Next.js rewrites with an external destination (proxying) work with web framework?

### ISSUE THREAD

**Issue by vp-walter** [firebase/firebase-tools#5976]
### [REQUIRED] Environment info

**firebase-tools:** 12.3.1 (latest as of now)

**Platform:** Windows (locally)

### [REQUIRED] Test case

- add an external destionation to the nextjs config rewrites.

### [REQUIRED] Steps to reproduce

Here is what my rewrites look like:
 async rewrites() {
    return [
      {
        source: "/mp/track/:slug*",
        destination: "https://api-js.mixpanel.com/track/:slug*",
      },
      {
        source: "/mp/engage/:slug*",
        destination: "https://api-js.mixpanel.com/engage/:slug*",
      },
      {
        source: "/mp/:slug*",
        destination: "https://api-js.mixpanel.com/:slug*",
      },
    ];
  },

### [REQUIRED] Expected behavior
Locally this works and the nextjs server just proxies the request.

### [REQUIRED] Actual behavior

Once it deploys with firebase via the SSR Cloud function, the logs for the ssrproject function show that it first issues a redirect (from https://<our-domain>.com/mp/track/?verbose=1 to https://<our-domain>/mp/track?_=1686698765113&ip=1&verbose=1) and when the app tries to hit that second url it sends a 408.

I've looked through a ton of the docs. It doesn't say anywhere that external rewrites like this aren't supported. That would be my first question, is this possible?

Secondly the cloud function just logs the response (308 at first, and then a 408), so if you have suggestions for extra debugging help, I'm all ears.

**Comment by alexastrum** [comment]
Fixed in https://www.npmjs.com/package/firebase-frameworks/v/0.10.4
