### ISSUE TITLE
NextJS Image Optimization failing on version next@^13.4.5

### ISSUE THREAD

**Issue by AlexBrasileiro** [firebase/firebase-tools#5977]
### [REQUIRED] Environment info

**firebase-tools:** firebase-tools@12.0.0

**Platform:** macOS

### [REQUIRED] Test case

Dependencies that work

"axios": "^1.4.0",
"firebase": "^9.22.2",
**"next": "^13.4.2",**
"react": "^18.2.0",
"react-dom": "^18.2.0",
"react-share": "^4.4.1",
"sharp": "^0.32.1",
"styled-components": "^5.3.11",
"yup": "^1.2.0",
"zustand": "^4.3.8"

Dependencies that don't Work

"axios": "^1.4.0",
"firebase": "^9.22.2",
**"next": "^13.4.5",**
"react": "^18.2.0",
"react-dom": "^18.2.0",
"react-share": "^4.4.1",
"sharp": "^0.32.1",
"styled-components": "^5.3.11",
"yup": "^1.2.0",
"zustand": "^4.3.8"

### [REQUIRED] Steps to reproduce

Only update version of Next

### [REQUIRED] Expected behavior

That the NextJS Image Optimization feature continues to work normally

### [REQUIRED] Actual behavior

Looking at the print below, all images now have the error 500 / 503 and the log on the server:

![Screenshot 2023-06-14 at 11 58 30](https://github.com/firebase/firebase-tools/assets/15070031/f99e345c-9a41-4bd9-a5f5-32ca1b5f87ea)

```log
"Error: Process exited with code 1\n    at process.<anonymous> (/layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/invoker.js:92:22)\n    at process.emit (node:events:513:28)\n    at process.emit (node:domain:489:12)\n    at process.exit (node:internal/process/per_thread:190:15)\n    at ChildProcess.<anonymous> (/workspace/node_modules/next/dist/server/lib/render-server-standalone.js:42:25)\n    at ChildProcess.emit (node:events:525:35)\n    at ChildProcess.emit (node:domain:552:15)\n    at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)\n    at Process.callbackTrampoline (node:internal/async_hooks:130:17)",
"}",
"  port: 22739",
"  address: '199.36.158.100',",
"  syscall: 'listen',",
"  errno: -99,",
"  code: 'EADDRNOTAVAIL',",
"    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:111:8) {",
"    at GetAddrInfoReqWrap.doListen [as callback] (node:net:1660:7)",
"    at listenInCluster (node:net:1511:12)",
"    at Server.setupListenHandle [as _listen2] (node:net:1446:21)",
"Invariant: failed to start render worker Error: listen EADDRNOTAVAIL: address not available 199.36.158.100:22739",
```

**Comment by alexastrum** [comment]
Fixed in https://www.npmjs.com/package/firebase-frameworks/v/0.10.4
