### ISSUE TITLE
Cannot find package 'firebase' imported from /workspace/node_modules/firebase-frameworks/dist/firebase-aware.js

### ISSUE THREAD

**Issue by limes** [firebase/firebase-tools#5996]
### Environment info

**firebase-tools:** 12.3.1

**Platform:** macOS

### Test case

1.  Set up new Angular (v16.1) project with latest AngularFire (v7.6.1)
2. Follow https://firebase.google.com/docs/hosting/frameworks/angular

### Steps to reproduce

1. run `firebase deploy`
2. see logs from created SSR function (Google Cloud Logs Explorer)

### Expected behavior

See properly generated SSR website in *.web.app domain

### Actual behavior

Google Cloud logs explorer:

`DEFAULT 2023-06-16T08:36:17.362069Z } Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'firebase' imported from /workspace/node_modules/firebase-frameworks/dist/firebase-aware.js
DEFAULT 2023-06-16T08:36:17.362073Z at new NodeError (node:internal/errors:399:5)
DEFAULT 2023-06-16T08:36:17.362078Z at packageResolve (node:internal/modules/esm/resolve:889:9)
DEFAULT 2023-06-16T08:36:17.362082Z at moduleResolve (node:internal/modules/esm/resolve:938:20)
DEFAULT 2023-06-16T08:36:17.362087Z at defaultResolve (node:internal/modules/esm/resolve:1153:11)
DEFAULT 2023-06-16T08:36:17.362092Z at nextResolve (node:internal/modules/esm/loader:163:28)
DEFAULT 2023-06-16T08:36:17.362097Z at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
DEFAULT 2023-06-16T08:36:17.362101Z at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
DEFAULT 2023-06-16T08:36:17.362106Z at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
DEFAULT 2023-06-16T08:36:17.362110Z at link (node:internal/modules/esm/module_job:76:36)
`

Browser:

```
Error 503 first byte timeout
first byte timeout

Error 54113
Details: cache-cph2320035-CPH 1686904748 1405985199

Varnish cache server

```

**Comment by plungarini** [comment]
Same issue here, i have an Angular Universal app with SSR, PWA and prerendering. I get:

`Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'firebase' imported from /workspace/node_modules/firebase-frameworks/dist/firebase-aware.js`

When i look at my Google Cloud Functions logs. In my frontend, instead, i get a 504 error:

```
Uncaught (in promise) Error: Response not Ok (fetchAndCacheOnce): request for https://lungabros.it/index.html returned response 504 Gateway Timeout
    at LazyAssetGroup.fetchAndCacheOnce (ngsw-worker.js:430:17)
    at async LazyAssetGroup.handleFetch (ngsw-worker.js:357:21)
    at async ngsw-worker.js:922:22
    at async AppVersion.handleFetch (ngsw-worker.js:921:21)
    at async Driver.handleFetch (ngsw-worker.js:1443:19)
```

I don't know if the error i'm seeing in the frontend when my angular app is deployed is related to the server, but i think so. Looking online it fails getting the cache from the service worker i guess.

**Comment by alexastrum** [comment]
Fix released in https://www.npmjs.com/package/firebase-frameworks/v/0.10.5
