### ISSUE TITLE
nextJS deploy fails with default confs

### ISSUE THREAD

**Issue by gabrielsalvador** [firebase/firebase-tools#5998]
### [REQUIRED] Environment info

**firebase-tools:**
firebase-tools: 12.3.1

**Platform:**
MacOS
### [REQUIRED] Test case
Deploy a nextJS app with experimental web-framework support

### [REQUIRED] Steps to reproduce
run firebase init hosting with pretty much all default settings
run firebase deploy

### [REQUIRED] Expected behavior
app is deployed to firebase and accessible through the web

### [REQUIRED] Actual behavior
#Actual behavior
process crashes, its trying to create a function with maxInstances=100 which does not work, and doesn't let me configure that

console logs:
  functions: Your current project quotas don't allow for the current max instances setting of 100. Either reduce this function's maximum instances, or request a quota increase on the underlying Cloud Run service at https://cloud.google.com/run/quotas.
⚠  functions: You can adjust the max instances value in your function's runtime options:
        setGlobalOptions({maxInstances: 10})
Failed to create function projects/clinidoc-ai/locations/europe-west1/functions/ssrclinidocai

**Comment by indu40** [comment]
- Please post the `hosting` section of your `firebase.json` file, example how it could look like:
```
"hosting": {
    "source": ".",
    "frameworksBackend": {
      "region": "europe-west1",
      "minInstances": 0,
      "maxInstances": 5,
      "memory": "1GiB"
      }
    },
```
- Have you enabled billing on your Firebase project (required if you plan to use SSR)?

**Comment by guivinson** [comment]
Hello, i encounter the same problem
```
i  functions: creating Node.js 18 (2nd Gen) function firebase-frameworks-projects-runners:ssrprojectsrunners(us-central1)...
⚠  functions: Your current project quotas don't allow for the current max instances setting of 100. Either reduce this function's maximum instances, or request a quota increase on the underlying Cloud Run service at https://cloud.google.com/run/quotas.
⚠  functions: You can adjust the max instances value in your function's runtime options:
        setGlobalOptions({maxInstances: 10})
Failed to create function projects/projects-runners/locations/us-central1/functions/ssrprojectsrunners
```

- my firebase.json

```json
{
  "hosting": {
    "source": ".",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ]
  }
}
```

- biling is enabled

**Comment by jpenna** [comment]
@gabrielsalvador How did you fix it?

**Comment by mooncitizen** [comment]
> "minInstances": 0,
>       "maxInstances": 5,
>       "memory": "1GiB"

FYI this fixed it for me :) thanks

**Comment by elai97** [comment]
> * Please post the `hosting` section of your `firebase.json` file, example how it could look like:
> 
> ```
> "hosting": {
>     "source": ".",
>     "frameworksBackend": {
>       "region": "europe-west1",
>       "minInstances": 0,
>       "maxInstances": 5,
>       "memory": "1GiB"
>       }
>     },
> ```
> 
> * Have you enabled billing on your Firebase project (required if you plan to use SSR)?

This worked for me... Thank you ✌️
