### ISSUE TITLE
Setting Strict-Transport-Security header for Firebase Hosting is not working

### ISSUE THREAD

**Issue by kireerik** [firebase/firebase-tools#5999]
### Environment info

**firebase-tools:** 12.4.0

**Platform:** Windows

### Test case

I am setting it to `max-age=31536000;includeSubDomains;preload`.

But the value for this header that is actually served is `max-age=0;includeSubDomains;preload` instead.

**Comment by kireerik** [comment]
@google-oss-bot This should be enough.

**Comment by bkendall** [comment]
A couple questions:

1. How are you setting this header? Are you setting it in `firebase.json`? Is this a header returned from a dynamic backend?
2. Are you seeing this in production? In the emulator?

**Comment by kireerik** [comment]
1. Yes, I am setting it properly in `firebase.json`. (Setting other headers works.) No. It is a static website.
I am setting it like this:
- [firebase.js#L37-L39](https://github.com/kireerik/refo/blob/48072d16f27d007e5c16d628cec1c00a91a67235/example/index/index/firebase.js#L37-L39) ([page.js#L33](https://github.com/kireerik/refo/blob/48072d16f27d007e5c16d628cec1c00a91a67235/example/index/index/page.js#L33))

&nbsp;
2. I am setting it in production. The emulator is not working properly. No set header is emulated as I saw if I remember correctly.

**Comment by bkendall** [comment]
I'm unable to replicate it not working in the emulator (using `v12.4.0` of `firebase-tools`). The `firebase.json` that I set up to reproduce:

```
{
  "hosting": {
    "public": "public",
    "headers": [{
      "source": "**",
      "headers": [{
        "key": "Strict-Transport-Security",
        "value": "max-age=1;includeSubDomains;preload"
      }]
    }]
  }
}
```

And my response headers:

```
» curl -i http://127.0.0.1:5002/
HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8
Content-Length: 13
ETag: b519c2cce7d2191ef8ae24808863256a
Last-Modified: Tue, 20 Jun 2023 21:34:00 GMT
Vary: Accept-Encoding
Strict-Transport-Security: max-age=1;includeSubDomains;preload # <<-- here it is
Date: Wed, 21 Jun 2023 16:39:40 GMT
Connection: keep-alive
Keep-Alive: timeout=5
```

I'm making the assumption that you're seeing *other* headers being set correctly, but I'm unable to confirm that this specific header isn't being set in the emulator.

Is it possible to get a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to show the behavior you're seeing?

**Comment by kireerik** [comment]
Using the emulator I only see `Referrer-Policy`, but not the others.

On the deployed site I see all, but `Strict-Transport-Security` is set to `max-age=31536000;includeSubDomains;preload` instead of `max-age=0;includeSubDomains;preload`.

**Comment by bkendall** [comment]
Without more information (maybe something useful logged with `--debug`?) or simple reproduction steps, there's not much I can do for you - I've provided the exact sample I'm using and the latest build seems to be working as expected.

I'm not exactly sure what your setup is doing, but I'd double check that (a) the `firebase.json` configuration that you're using is correct - it seems to be generated by tooling, right? - (b) that the Firebase emulator is actually serving the request, and (c) if there's some other proxy involved, that it's not mangling/overwriting any headers itself

Sorry I can't be of more help. Do let us know if you have any more information to share.

**Comment by kireerik** [comment]
Yes, it is generated and it is correct. Other headers work properly in production.
I think the emulator is just not working properly, but I am more interested in Firebase Hosting to work properly.

Does this work for you if you deploy a site to Firebase Hosting?

**Comment by bkendall** [comment]
You may have gotten me confused: so this is an error with the header not working in *production*?

The `Strict-Transport-Security` header isn't overridable on the `[site].web.app` (or `[site].firebaseapp.com`) domains because it needs to be consistent across all the subdomains. However, I am able to override it on a custom domain:

```
» curl -I https://**********
HTTP/2 200
cache-control: max-age=3600
content-type: text/html; charset=utf-8
etag: "91c127a13c5c75397785651f51c1ee84bce9eb186e6e66ed9460b62745dc4a1f"
last-modified: Tue, 27 Jun 2023 11:38:13 GMT
strict-transport-security: max-age=1;includeSubDomains;preload
accept-ranges: bytes
date: Tue, 27 Jun 2023 12:43:17 GMT
x-served-by: cache-msp11877-MSP
x-cache: MISS
x-cache-hits: 0
x-timer: S1687869798.635250,VS0,VE125
vary: x-fh-requested-host, accept-encoding
alt-svc: h3=":443";ma=86400,h3-29=":443";ma=86400,h3-27=":443";ma=86400
content-length: 4606
```

**Comment by bkendall** [comment]
Works just fine:

```
» curl -I https://******************
HTTP/2 200
...
strict-transport-security: max-age=0;includeSubDomains;preload
```

If you're seeing an issue in production, I'd recommend reaching out to [Firebase Support](https://firebase.google.com/support) and we can look more specifically into your situation.
