### ISSUE TITLE
LS, CP and RM commands

### ISSUE THREAD

**Issue by JosefJezek** [firebase/firebase-tools#60]
Could you make LS, CP and RM commands as gsutil?

https://cloud.google.com/storage/docs/gsutil/commands/cp
https://cloud.google.com/storage/docs/gsutil/commands/rm
https://cloud.google.com/storage/docs/gsutil/commands/ls

**Comment by drtriumph** [comment]
We don't currently expose the underlying files stored for hosting, nor is this in our short- to mid-term roadmap for the product. For now, the `deploy` command is your only option for sending files to Firebase Hosting
