### ISSUE TITLE
[Win10] Functions: package.json relative imports: '.' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by exp0nge** [firebase/firebase-tools#600]
### Version info

3.16.0

### Steps to reproduce

1. firebase init
(choose function)

### Expected behavior

`firebase deploy --only functions` deploys

### Actual behavior
`'.' is not recognized as an internal or external command, operable program or batch file.` as a result of:
`"build": "./node_modules/.bin/tslint -p tslint.json && ./node_modules/.bin/tsc",`
"fix"
`"build": ".\\node_modules\\.bin\\tslint -p tslint.json && .\\node_modules\\.bin\\tsc",`

**Comment by laurenzlong** [comment]
Fixed in https://github.com/firebase/firebase-tools/pull/603
