### ISSUE TITLE
Cannot deploy V2 cloud functions with Firestore trigger

### ISSUE THREAD

**Issue by putnokiabel** [firebase/firebase-tools#6018]
### [REQUIRED] Environment info

**firebase-tools:** 12.4.0

**Platform:** macOS

### [REQUIRED] Test case

A function with a minimal V2 firestore trigger, e.g.
```js
const { onDocumentUpdated } = require("firebase-functions/v2/firestore");


exports.on_update_reward_v2 = onDocumentUpdated("rewards/{rewardId}", (event) => {
    console.log(event.id);
});
```

### [REQUIRED] Steps to reproduce

1. Create a function with a minimal V2 Firestore trigger (see test case)
2. Run `firebase deploy --only functions:function_name`

### [REQUIRED] Expected behavior

The function is deployed successfully, and functions as a Firestore trigger.

### [REQUIRED] Actual behavior

The CLI creates a function but it's not deployed successfully.
Logs without `--debug`:
```log
firebase deploy --only functions:on_update_reward_v2

=== Deploying to 'v2-firestore-trigger-test-app'...

i  deploying functions
Running command: npm --prefix "$RESOURCE_DIR" run lint

> lint
> ./node_modules/.bin/eslint

✔  functions: Finished running predeploy script.
i  functions: preparing codebase default for deployment
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
i  artifactregistry: ensuring required API artifactregistry.googleapis.com is enabled...
✔  artifactregistry: required API artifactregistry.googleapis.com is enabled
✔  functions: required API cloudbuild.googleapis.com is enabled
✔  functions: required API cloudfunctions.googleapis.com is enabled
⚠  functions: package.json indicates an outdated version of firebase-functions. Please upgrade using npm install --save firebase-functions@latest in your functions directory.
i  functions: preparing functions directory for uploading...
i  functions: packaged /Users/Macbook/Test-Firebase/functions (132.19 KB) for uploading
i  functions: packaged /Users/Macbook/Test-Firebase/functions (132.45 KB) for uploading
i  functions: ensuring required API run.googleapis.com is enabled...
i  functions: ensuring required API eventarc.googleapis.com is enabled...
i  functions: ensuring required API pubsub.googleapis.com is enabled...
i  functions: ensuring required API storage.googleapis.com is enabled...
✔  functions: required API pubsub.googleapis.com is enabled
✔  functions: required API storage.googleapis.com is enabled
✔  functions: required API eventarc.googleapis.com is enabled
✔  functions: required API run.googleapis.com is enabled
i  functions: generating the service identity for pubsub.googleapis.com...
i  functions: generating the service identity for eventarc.googleapis.com...
✔  functions: functions folder uploaded successfully
i  functions: creating Node.js 16 (2nd Gen) function on_update_reward_v2(us-central1)...
Could not create or update Cloud Run service on-update-reward-v2, Container Healthcheck failed. Revision 'on-update-reward-v2-00001-fac' is not ready and cannot serve traffic. The user-provided container failed to start and listen on the port defined provided by the PORT=8080 environment variable. Logs for this revision might contain more information.

Logs URL: https://console.cloud.google.com/logs/viewer?project=v2-firestore-trigger-test-app&resource=cloud_run_revision/service_name/on-update-reward-v2/revision_name/on-update-reward-v2-00001-fac&advancedFilter=resource.type%3D%22cloud_run_revision%22%0Aresource.labels.service_name%3D%22on-update-reward-v2%22%0Aresource.labels.revision_name%3D%22on-update-reward-v2-00001-fac%22 
For more troubleshooting guidance, see https://cloud.google.com/run/docs/troubleshooting#container-failed-to-start

Functions deploy had errors with the following functions:
        on_update_reward_v2(us-central1)
i  functions: cleaning up build files...

Error: There was an error deploying functions
```

Logs with `--debug` are attached in a file due to character limit.
[deployment.log](https://github.com/firebase/firebase-tools/files/11826664/deployment.log)

I can see a function in the console that failed to deploy:
<img width="1493" alt="image" src="https://github.com/firebase/firebase-tools/assets/29568469/c7330b1f-0e99-47eb-9e11-af3815c00ebb">
Redeploying does not help. Deleting function and retrying does not help.

From the documentation at https://firebase.google.com/docs/functions/firestore-events?gen=2nd it seems like the Firebase tooling should support deploying a Firebase function with a Firestore trigger (even though there is no explicit example of the deployment).
I _can_ deploy V2 Firebase functions with an HTTP trigger using the exact same process, which leads me to think this is a bug within `firebase-tools`. Can someone help me solve the issue or offer an alternative way of deploying a V2 Firestore trigger?

P.S. From the logs it looks like `firebase-tools` expects the function to behave like an HTTP function, and fails when the function does not respond to HTTP requests.

**Comment by aalej** [comment]
Hi @putnokiabel, thanks for reaching out to us. I tried to replicate the issue you mentioned, but I encountered no errors when running `firestore deploy --only functions: on_update_reward_v2` using the code snippet you provided.

Not sure what I might be missing here, but would it be possible if you can provide an  [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) where the issue is reproducible? This will help us check if this might be a configuration issue, backend issue, or an issue with firebase-tools.

**Comment by putnokiabel** [comment]
Upon further investigation it looks like a problem with my project / account, since it works properly on a fresh project. I'll try to debug further or file a support ticket. Thank you for your help @aalej !

**Comment by nolafs** [comment]
I am having the same issue but I do not have luxury of changing the project. Any solution?

**Comment by rahulgoti-insight** [comment]
Hi @putnokiabel What was permission issue please? I'm facing the same issue. It would be great if you can explain/help about solution you got please. Thanks :)

**Comment by putnokiabel** [comment]
Unfortunately this has been too long ago and I don't remember what the issue was exactly.

I remember I once encountered an issue (not sure if it was this one) where the cloud function logs didn't have enough information on why deployment failed, but the cloud run logs / cloud run revision logs did. Perhaps you can have a look there!
