### ISSUE TITLE
Predeploy hooks not run when deploying individual functions

### ISSUE THREAD

**Issue by sam-throne** [firebase/firebase-tools#6021]
### [REQUIRED] Environment info

**firebase-tools:** From HEAD

**Platform:** macOS

### [REQUIRED] Test case

```
"functions": [
  {
    "predeploy": "echo PREDEPLOY",
    "source": "build",
  },
]
```

### [REQUIRED] Steps to reproduce

`firebase deploy --only functions:myFunction`

### [REQUIRED] Expected behavior

It should print PREDEPLOY

### [REQUIRED] Actual behavior

Nothing is printed

This is a regression introduced by #6011

**Comment by blidd-google** [comment]
Thanks for bringing this to our attention, follow-up PR here should resolve the issue: https://github.com/firebase/firebase-tools/pull/6023.
