### ISSUE TITLE
Unclear error message when running functions:shell when there is no default project set up

### ISSUE THREAD

**Issue by nhpf** [firebase/firebase-tools#6070]
### Environment info
**firebase-tools:** 12.4.2
**Platform:** Arch Linux
**Node:** 18.8.0

### Test case
This bug happens when we try to run the functions shell but there is no project defined in `.firebaserc`
The error message should be more explicit when the Firebase project ID is missing.

### Steps to reproduce
- Create a new directory
- With `firebase init` select only functions
- **Don't set up a default project**
- Use TypeScript and ESLint
- Install dependencies with npm
- `cd functions`
- Uncomment the example function in `src/index.ts`:
```ts
import {onRequest} from "firebase-functions/v2/https";
import * as logger from "firebase-functions/logger";

export const helloWorld = onRequest((request, response) => {
  logger.info("Hello logs!", {structuredData: true});
  response.send("Hello from Firebase!");
});
```
- Run `npm run shell`

### Expected behavior
The functions shell should initiate

### Actual behavior
I get the error message: `Error: An unexpected error has occurred.`
And the debug log with:
```
[debug] [2023-07-01T13:32:04.748Z] AssertionError [ERR_ASSERTION]: expected value to be defined but got "undefined"
    at new AssertionError (node:internal/assert/assertion_error:467:5)
    at Object.assertDefined (/home/nick/.nvm/versions/node/v18.8.0/lib/node_modules/firebase-tools/lib/utils.js:380:15)
    at Command.actionFunction [as actionFn] (/home/nick/.nvm/versions/node/v18.8.0/lib/node_modules/firebase-tools/lib/functionsShellCommandAction.js:29:11)
    at /home/nick/.nvm/versions/node/v18.8.0/lib/node_modules/firebase-tools/lib/command.js:224:25
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[error] 
[error] Error: An unexpected error has occurred.
```

That points to [this function](https://github.com/firebase/firebase-tools/blob/57dd7fef80d9b9294da41bb93cf25a1108674459/src/command.ts#L411) in the `firebase-tools` repository.

---

### Solution
Setting your Firebase project ID in `.firebaserc` solves this issue.
PR proposal: the error message should be more explicit when the Firebase project ID is missing.

**Comment by aalej** [comment]
Hi @nhpf, thanks for the detailed report and feedback! I agree that the error message could be improved to provide more context, which would make it easier to troubleshoot.

I’ll raise this to our team so that they can take a look.
