### ISSUE TITLE
[NextJS] POST route handlers (route.ts) consistently results in timeouts

### ISSUE THREAD

**Issue by piazzamp** [firebase/firebase-tools#6071]
### [REQUIRED] Environment info

**firebase-tools:** 12.2.1 (also reproduced on 12.5.2)
**nextjs:** 13.4.7 (also reproduced on 13.4.9)

**Platform:** macOS

### [REQUIRED] Test case

https://github.com/piazzamp/firebase-test
Running IRL: https://test-case-fbt.web.app/

### [REQUIRED] Steps to reproduce

1. Use app router
2. Setup a route.ts with a POST handler
3. Send a request to the POST handler

### [REQUIRED] Expected behavior
The request should be routed to the handler defined in the corresponding route.ts file (eg: `fetch('/api/text', {method: 'POST'})` in my example repo should route to the POST method in app/api/text/route.ts)

### [REQUIRED] Actual behavior
408 timeouts in production only. However, the emulator works as expected and runs the right server-side request handler. Logs from the gcp function don't indicate the function code is running at all.

Oddly, the GET request that does almost the exact same thing but reads from URL params instead of the request body works just fine.

**Comment by piazzamp** [comment]
Since this only affects POSTs (or reading request bodies) I think it might be the same as vercel/next.js#50166
But I'd love a second opinion 😄

**Comment by ilmimris** [comment]
any idea how to overcome this issue?

**Comment by Sangkwun** [comment]
I am also experiencing the same issue.
```
"next": "13.4.9",
 "firebase": "^9.9.0",
"firebase-admin": "^11.9.0",
"firebase-frameworks": "0.10.5",
```

**Comment by piazzamp** [comment]
as mentioned in that ^ comment on #6133, this actually affects any requests with a body, regardless of whether that body's being read in the route handler.

**Comment by MeTaNoV** [comment]
Also experiencing this... Did you switch to the old API to make it work?

**Comment by Sangkwun** [comment]
In my case I switched to vercel.

**Comment by piazzamp** [comment]
I also considered switching to vercel but I did something much more cumbersome: I added separate firebase functions for the routes that absolutely need a body (eg: image upload) (for other stuff I just jam everything into url params). Then I added some rewrites to my firebase.json to get everything to be on the same domain so I could get my session cookie 😖. Overall it's pretty nasty & brittle but it looks like this:
```
my-cool-project
├── firebase.json
├── functions
│   └── src
|        └── index.ts
└── hosting
    └── app
```
and then in firebase.json:
```json
"hosting": {
    "source": "hosting",
    "rewrites": [
      {"source": "/api/special/uploadimage", "function": "uploadImage"}
    ]
}
```

**Comment by jamesdaniels** [comment]
This has been addressed with the release of `firebase-frameworks@0.11.0` https://github.com/FirebaseExtended/firebase-framework-tools/pull/122
