### ISSUE TITLE
12.4.2  Flutter Web webframeworks experiment "Unable to detect the web framework in use"

### ISSUE THREAD

**Issue by g-adorni-neting** [firebase/firebase-tools#6085]
I have a Flutter Web project, up to version 12.4.0 by enabling web frameworks experiments I was able to deploy to Firebase hosting correctly. 

By upgrading to 12.4.2 instead, the deploy or the firebase init with the same configuration gives me: 

```
firebase deploy --only hosting           
Could not determine the web framework in use.

Error: Unable to detect the web framework in use, check firebase-debug.log for more info.
```

I also tried with version 12.4.1 and it gives the same problem. By downgrading to 12.4.0 everything goes back to working properly.

**Comment by aalej** [comment]
Hi @g-adorni-neting, thanks for reporting this issue. I was able to reproduce this. I encountered the same error when using v12.4.2 and v12.4.1 as you mentioned. After downgrading to v12.4.0, I was able to run `firebase deploy` without any issues.

Let me notify our team about this so that they can investigate.

**Comment by seniorpreacher** [comment]
I experience the same issue in v12.4.3, but downgrading to v12.4.0 did not fix it for me. 
Also downgrading to 12.3.1, than 12.2.1 and 12.1.0 did not fix it for me, I get the same error as [g-adorni-neting](https://github.com/g-adorni-neting).

The weird thing is that `firebase-debug.log` disappears when the deploy script exits, so I can't even see the detailed logs to provide more info.

note: the command worked for me until the latest update, maybe I miss a cache clearing step when downgrading? 🤔 

```
os: macOS 13.4
node: 20.2.0
npm: 9.6.6
```

**Comment by larssn** [comment]
Related:
When doing a `firebase init hosting`, and then pointing it to your Flutter app, the warning "Could not determine the web framework in use.", and a choice of web frameworks appears, but no choice of Flutter Web can be seen.

Easy to reproduce:
```
mkdir firebasetest
cd firebasetest
flutter create hosting --platforms web
firebase init hosting
<run through the steps>
```

**Comment by MarcoHuib** [comment]
I'm experiencing the same issue, but with Next.js framework. I can't resolve it with the latest version, and as mentioned in this discussion, version 12.4.0 works for me as well. For now, I can proceed, but I would like to see a solution to this problem.

mac: 13.4.1
node: v20.6.1
npm: 9.8.1

**Comment by lasharela** [comment]
@andreasgrossmann yes, you are right. documentation is out dates and CLI also generates source by default.
