### ISSUE TITLE
Unable to run v2 functions on firebase functions:shell 

### ISSUE THREAD

**Issue by ilonawong** [firebase/firebase-tools#6089]
### [REQUIRED] Environment info

**firebase-tools:** 12.4.2

**Platform:** MacOS

### [REQUIRED] Test case
Any v2 function (specifically, `onDocumentWritten`)

### [REQUIRED] Steps to reproduce
run firebase functions:shell, try and call the v2 function with any combination of params

```
v2_function_test({ 
      data: { before, after }
})

v2_function_test({ before, after })
``` 

and this error pops up:
```
Error: Cannot determine payload type, datacontenttype is undefined, failing out

functions: Error: Error: Cannot parse event payload.
    at createBeforeSnapshot (/Users/iwong/repos/partiful/node_modules/firebase-functions/lib/v2/providers/firestore.js:140:15)
    at makeChangedFirestoreEvent (/Users/iwong/repos/partiful/node_modules/firebase-functions/lib/v2/providers/firestore.js:171:37)
    at func (/Users/iwong/repos/partiful/node_modules/firebase-functions/lib/v2/providers/firestore.js:237:32)

```

If I try to add datacontenttype as a param, it just gets nested inside a "data" object.

### [REQUIRED] Expected behavior
Be able to run v2 functions locally

### [REQUIRED] Actual behavior
It doesn't, error above

**Comment by taeold** [comment]
Hey @ilonawong - thank you for filing this bug report. Confirmed that this is an issue for functions shell - we'll work on getting something out soon to support 2nd Gen functions in `functions:shell` command.

**Comment by ilonawong** [comment]
Thanks @taeold! Any approximate timeline? We converted a bunch of our functions over and we're limited to reverting to v1 to run yarn shell right now haha.

**Comment by taeold** [comment]
@ilonawong Going for mid next week 🙏🏼
