### ISSUE TITLE
Firebase hosting deploy issue with Nextjs : Unable to find the next dep, try NPM installing?

### ISSUE THREAD

**Issue by deathg0d** [firebase/firebase-tools#6100]
### Environment info

**firebase-tools:** 12.4.3 and 12.3.0

**Platform:** Windows

### Test case
--

### Steps to reproduce

Trying to deploy nextjs (13.4.9) app on firebase hosting. After the setup provided here:https://firebase.google.com/docs/hosting/frameworks/nextjs I run into an error when I do firebase deploy.

### Expected behavior

Deployed to firebase hosting

### Actual behavior

Here's the content of the firebase-debug.log file:
```
...
   Thank you for trying our early preview of Next.js support on Firebase Hosting.
   During the preview, support is best-effort and breaking changes can be expected. Proceed with caution.

   Documentation: https://firebase.google.com/docs/hosting/frameworks/nextjs
   File a bug: https://github.com/firebase/firebase-tools/issues/new?template=bug_report.md
   Submit a feature request: https://github.com/firebase/firebase-tools/issues/new?template=feature_request.md

   We'd love to learn from you. Express your interest in helping us shape the future of Firebase Hosting: https://goo.gle/41enW5X

[debug] [2023-07-09T10:39:34.742Z] Error: Unable to find the next dep, try NPM installing?
    at getConfig (<WORKING DIR>\node_modules\firebase-tools\lib\frameworks\next\index.js:382:19)
    at build (<WORKING DIR>\node_modules\firebase-tools\lib\frameworks\next\index.js:62:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async prepareFrameworks (<WORKING DIR>\node_modules\firebase-tools\lib\frameworks\index.js:211:33)
    at async deploy (<WORKING DIR>\node_modules\firebase-tools\lib\deploy\index.js:55:13)
[error] 
[error] Error: An unexpected error has occurred.
```

Same error with version 12.4.3 and 12.3.0.

**Comment by aalej** [comment]
Hi @deathg0d. I’m unable to reproduce the error you mentioned. Not sure if I may be missing something here, but here are the steps I took:

1. Run `npx create-next-app@latest`
2. Run `cd my-app`
3. Run `firebase init hosting --project <project_id>`
4. Run `firebase deploy`

I’ve tried to reproduce the issue using a macOS and Windows machine, but I encountered no issues running `firebase deploy` on both. In case I’m missing a step, just let me know.

Could you provide an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) or more details on the steps you took so that we can reproduce the issue on our end? Thanks!

**Comment by JetsonDavis** [comment]
deathg0d,

I'm having enormous difficulties deploying a Next.js 13.4.4 app to Firebase.  Let me know if you'd like to compare notes.

**Comment by alexastrum** [comment]
@JetsonDavis 
In the last 2 days we've encountered an issue (#6110) that was preventing Next.js deployments from finishing succesfully.
If you started having issues right before posting your comment, try to re-deploy now and it should work. 

@deathg0d 
Please follow the following troubleshooting steps:
1. Make sure that:
  - You have the latest CLI tools installed (12.4.4): `npm install -g firebase-tools`
  - Your `firebase.json` `hosting > source` config points to the correct Nextjs source folder
  - The `package.json` in your Nextjs source folder has the correct `next` dependency
2. Remove `node_modules` and reinstall with `npm install`
3. If the steps above do not fix your issue, please open an issue and provide the source code for a https://stackoverflow.com/help/minimal-reproducible-example.

**Comment by JetsonDavis** [comment]
@alexastrum Thank you for the update.  Is it possible to view the server logs?  Also, I'm having my api calls hang and eventually time out.  Any idea why that might be?  I'm using /project_id.web.app as the path.

**Comment by deathg0d** [comment]
> I'm not sure how to replicate this, but I were having this error a lot yesterday. @alexastrum I've had it before and after #6110. What I did to fix it was to just run `npm i` and try to deploy again. After a few retries it went past this message.

Mine's just a basic nextjs project, and then followed this: https://firebase.google.com/docs/hosting/frameworks/nextjs
I tried `npm i` multiple times already and have retried deploying many times. Still getting the same error `Error: Could not find the next executable.`

**Comment by al4nnw** [comment]
> Error: Could not find the next executable.

I think this error indicates that there is no `.next` folder inside your project. You should try building with `npm run build` before trying to deploy.

**Comment by deathg0d** [comment]
> > Error: Could not find the next executable.
> 
> I think this error indicates that there is no `.next` folder inside your project. You should try building with `npm run build` before trying to deploy.

I did actually. And I do have a .next folder. I also tried changing the folder to `out` or `dist` and specifying this in firebase.json.

**Comment by GabrielFn** [comment]
deathg0d did you manage to solve this last problem?

**Comment by GabrielFn** [comment]
@deathg0d did you manage to solve this last problem?

**Comment by deathg0d** [comment]
> @deathg0d did you manage to solve this last problem?

Sadly not yet :(
