### ISSUE TITLE
[frameworks] npm error during frameworks build when using `firebase@^10.0.0`

### ISSUE THREAD

**Issue by ezracelli** [firebase/firebase-tools#6109]
When deploying hosting with web framework integration, [`firebase-tools` forcefully adds `firebase-frameworks` as a dependency during the build step](https://github.com/firebase/firebase-tools/blob/v12.4.3/src/frameworks/index.ts#L414). `firebase-frameworks` has a peer dependency on `firebase@^9.9.0`.

https://github.com/FirebaseExtended/firebase-framework-tools/blob/0.10.4/package.json#L89

This conflicts with projects wanting to use [the newly-released `firebase@^10.0.0`](https://firebase.google.com/support/release-notes/js#version_1000_-_july_6_2023).

- `firebase-frameworks`' `peerDependencies` should be updated to accept either `firebase@^9.9.0` or `firebase@^10.0.0` (assuming there's no breaking changes relevant to that package)
- `firebase-tools`' [hard-coded version of `firebase-frameworks`](https://github.com/firebase/firebase-tools/blob/v12.4.3/src/frameworks/constants.ts#L28) should be bumped to match

(`firebase-frameworks`' README says to submit bug reports here.)

### [REQUIRED] Environment info

**firebase-tools:** 12.4.3

**Platform:** NixOS 23.11 (Tapir)

### [REQUIRED] Test case

`./firebase.json`

```json
{
  "hosting": {
    "source": "./hosting"
  }
}
```

`./hosting/package.json`

```json
{
  "name": "hosting",
  "main": "./index.js",
  "directories": {
    "serve": "./public"
  },
  "dependencies": {
    "firebase": "^10.0.0",
    "express": "latest"
  }
}
```

`./hosting/index.js`

```js
module.exports = (req, res) => {
    res.end();
};
```

### [REQUIRED] Steps to reproduce

```console
$ firebase deploy --only hosting
```

### [REQUIRED] Expected behavior

The deploy should complete successfully.

### [REQUIRED] Actual behavior

<details>
<summary><code>npm</code> output from `firebase deploy` hidden, click to expand</summary>

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: firebase-frameworks@0.10.5
npm ERR! Found: firebase@10.0.0
npm ERR! node_modules/firebase
npm ERR!   firebase@"^10.0.0" from the root project
npm ERR!   firebase@"^10.0.0" from hosting@undefined
npm ERR!   node_modules/hosting
npm ERR!     hosting@"file:package.tgz" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peerOptional firebase@"^9.9.0" from firebase-frameworks@0.10.5
npm ERR! node_modules/firebase-frameworks
npm ERR!   firebase-frameworks@"^0.10.4" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: firebase@9.23.0
npm ERR! node_modules/firebase
npm ERR!   peerOptional firebase@"^9.9.0" from firebase-frameworks@0.10.5
npm ERR!   node_modules/firebase-frameworks
npm ERR!     firebase-frameworks@"^0.10.4" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```
</details>

**Comment by oscarklm** [comment]
I'm having the same issue. I downgraded firebase to ^9.9.0 which seemed to solve the issue, and for me so far using ^9.9.0 doesn't seem like an issue. Unsure whether it will be down the road?

**Comment by lxitixl** [comment]
Had to downgrade to ^9.9.0 for this as well which forced a bunch of rollbacks in firebase api calls

**Comment by JeremyWebb45** [comment]
Yeah that worked for me

**Comment by 0xEljh** [comment]
> Had to downgrade to ^9.9.0 for this as well which forced a bunch of rollbacks in firebase api calls

Wanted to avoid this downgrade and got it to work by adding a `.npmrc` file to the root project with `legacy-peer-deps=true`

This creates a `.npmrc` file in the firebase functions build (`.firebase/app/functions/.npmrc`)

**Comment by DevNickJr** [comment]
> > Had to downgrade to ^9.9.0 for this as well which forced a bunch of rollbacks in firebase api calls
> 
> Wanted to avoid this downgrade and got it to work by adding a `.npmrc` file to the root project with `legacy-peer-deps=true`
> 
> This creates a `.npmrc` file in the firebase functions build (`.firebase/app/functions/.npmrc`)

This Worked for me

**Comment by MeTaNoV** [comment]
Not sure why this issue was closed since it hasn't been resolved... The .npmrc trick is very dangerous in my opinion...
