### ISSUE TITLE
Update firestore.rules from origin

### ISSUE THREAD

**Issue by lucasluizss** [firebase/firebase-tools#6114]
Would be nice to update the local firestore.rules by taking the rules added in the origin. So I would not need to interact every time I do the deployment.

Please submit feature requests through our [support page](https://firebase.google.com/support/troubleshooter/report/features/).

**Comment by ehsannas** [comment]
@lucasluizss thanks for your suggestion.

It's not very clear what the request is. Can you please elaborate? (also, what do you mean by origin?)

**Comment by lucasluizss** [comment]
> @lucasluizss thanks for your suggestion.
> 
> It's not very clear what the request is. Can you please elaborate? (also, what do you mean by origin?)

Origin would be from Firebase rules. The local rules are in the JSON located in the project. When I change some query that need to be indexed the query fails and there is a link with the fix in the console error (with the link to add the required rules) after the rules are added to Firebase in the Google Console but not updated locally. So every time I do the deployment manually it will ask for re-write the rules (Y/N) based on the Firebase console configured rules.

**Comment by ehsannas** [comment]
Thanks for the clarification, @lucasluizss . I have filed a feature request internally, but can't comment on if/when it will be implemented. Internally tracking via b/291337094.
