### ISSUE TITLE
The Firebase CLI `functions:list` command is not complete for large Functions deployments

### ISSUE THREAD

**Issue by al-the-x** [firebase/firebase-tools#6118]
### [REQUIRED] Environment info

**firebase-tools: `11.24.1`**

**Platform: Mac OS X 13.2.1**

### [REQUIRED] Test case

Create and deploy a large number of Firebase Functions. We have over 300 deployed, but the limit seems to be around 50.

### [REQUIRED] Steps to reproduce

Attempt to list all the deployed functions either in pretty-print or JSON mode: 
- Pretty print: `firebase functions:list`
- JSON mode: `firebase functions:list -j`

### [REQUIRED] Expected behavior

The list should contain an entry for EACH Cloud Function deployed.

### [REQUIRED] Actual behavior

The pretty printed list is truncated after 100-ish functions. The JSON mode is truncated after 40-ish entries. The lists are both truncated in a way that indicates that an error occurred and the CLI stopped processing the output.

**Comment by Berlioz** [comment]
I can't duplicate this on OSX, though I'm on firebase-tools 12.4.4 (can't see anything in the changelogs or the actual diff that would have fixed your issue, though). Just uploaded a couple hundred functions to my personal account and `functions:list` didn't truncate for me, with tables or json, in both iterm2 and the default Terminal app.

At this point I suspect the cause might be in your local configuration. I've never heard of a terminal just deciding to truncate output after a while but...I can't think of anything else, either. Can you `cat` a very large file without getting truncated output? Are you sending terminal input through ssh or a unix pipe? Do you experience the same problem on a different computer, or from a VM?

I'm sorry I can't be more help but I genuinely don't know where to start without a repro.
