### ISSUE TITLE
Error: Could not find rules for the following storage targets: rules

### ISSUE THREAD

**Issue by godrays** [firebase/firebase-tools#6125]
Hi everyone, 

I've been using Firebase for a while now and everything seems great, except for the fact that the storage.rules files can't be found when I attempt to deploy the rules. The firestore.rules files, however, deploy without any problems.

Is this a known problem? I couldn't find a solution for it.

Thank you for the help.

### [REQUIRED] Environment info

```
firebase-tools 12.4.4
firebase 12.4.4
corepack 0.17.0
npm  9.5.1

macOS Ventura 13.4
```

### [REQUIRED] Test case

Not sure what to put here.

### [REQUIRED] Steps to reproduce

**storage.rules file**
```
rules_version = '2';

service firebase.storage
{
    match /b/{bucket}/o
    {
        match /test/{allPaths=**}
        {
            allow read: if true;
            allow write: if true;
        }
    }
}
```

**firebase.json file**
```
{
  "firestore": {
    "rules": "rules/firestore.rules",
    "indexes": "firestore.indexes.json"
  },
  "storage": {
    "rules": "rules/storage.rules"
  },
  ...
```
Note: I tried to put storage.rules in root folder as well but still didn't work.

**rules file location**

```
<project_root>/rules/firestore.rules
<project_root>/rules/storage.rules              
```

**Command to deploy**

```
firebase deploy --only storage:rules
```

### [REQUIRED] Expected behavior

Deploying rules without an error.

### [REQUIRED] Actual behavior

```
$ firebase deploy --only storage:rules

=== Deploying to 'xxxxxxxxxxxxxx'...

i  deploying storage

Error: Could not find rules for the following storage targets: rules
```

**Comment by aalej** [comment]
Hi @godrays, thanks for reaching out. Could you try running `firebase deploy --only storage` to see if this would deploy your Cloud Storage for Firebase rules? Here is the [reference](https://firebase.google.com/docs/cli#partial_deploys) to the deploy commands.

**Comment by pakinsa** [comment]
I had to change my code from this: 

```bash
rules_version = '2';
service firebase.storage {
  match /b/{bucket}/o {
    // User-specific content
    match /user_uploads/{userId}/{allPaths=**} {
      allow read, write: if request.auth != null && request.auth.uid == userId;
    }
    
    // Public course materials
    match /course_content/{courseId}/{file} {
      allow read: if true;
      allow write: if request.auth != null && 
                   get(/databases/$(database)/documents/admins/$(request.auth.uid)).exists;
    }
  }
}
```

To this:

```bash
rules_version = '2';
service firebase.storage {
  match /b/{bucket}/o {
    match /user_uploads/{userId}/{file} {
      allow read, write: if request.auth != null && request.auth.uid == userId;
    }
  }
}
```

Then I use this based on users suggestion in this issue, ```$ firebase deploy --only storage```, rules were updated in the storage console successfully without warnings, or below errors:

i  firebase.storage: checking storage.rules for compilation errors...
!  [W] 13:20 - Invalid function name: get.
!  [W] 13:37 - Invalid variable name: database.

Thanks Devs.
