### ISSUE TITLE
Cannot deploy SvelteKit project to Firebase

### ISSUE THREAD

**Issue by blehn** [firebase/firebase-tools#6128]
### [REQUIRED] Environment info

**firebase-tools:** 12.4.4
node version 18.16.1 or 16.20.1

**Platform:** macOS

### [REQUIRED] Test case

Deploy new SvelteKit project to Firebase

### [REQUIRED] Steps to reproduce

1. Create a new SvelteKit app with the skeleton option, typescript syntax, eslint and prettier
2. Create a new Firebase app in the Firebase web admin with Blaze/billing enabled
3. Set up Hosting in the Firebase app
4. Set up Firebase in SvelteKit app using  `firebase experiments:enable webframeworks` and `firebase init` (select the newly created Firebase app during setup)
5. Run `npm run dev -- --open` to verify that app is building and running locally
6. Run `firebase deploy`

### [REQUIRED] Expected behavior

App deploys to firebase and runs on firebase domain

### [REQUIRED] Actual behavior

Deploy fails. Logs attached
[firebase-log.txt](https://github.com/firebase/firebase-tools/files/12043729/firebase-log.txt)

**Comment by leoortizz** [comment]
Hey @blehn does this issue still happening with the latest version of `firebase-tools`?
