### ISSUE TITLE
In frameworks mode, unable to deploy hosting in case configuration names are changed

### ISSUE THREAD

**Issue by itherocojp** [firebase/firebase-tools#6138]
In my Angular project, the configuration production has been renamed to live and the development has been done to dev, and the stage has been added currently.

In this situation, when I try to deploy my app to firebase hosting, an error below occurs.

```
Error: Configuration 'production' is not set in the workspace.
```

I know the frameworks mode is now experimental. It would be much better if we could switch it to a different configuration name.

Or are there any good ways to solve this?

Currently I do this.
1. Turn off frameworks mode.
2. Remove source and frameworks region from firebase.json and add public to it.
3. Run ng build and firebase deploy

Thank you.

---

```
"dependencies": {
    "@angular/animations": "^16.1.5",
    "@angular/common": "^16.1.5",
    "@angular/compiler": "^16.1.5",
    "@angular/core": "^16.1.5",
    "@angular/fire": "^7.6.1",
    "@angular/forms": "^16.1.5",
    "@angular/platform-browser": "^16.1.5",
    "@angular/platform-browser-dynamic": "^16.1.5",
    "@angular/router": "^16.1.5",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.13.0",
    "firebase": "^7.0 || ^8.0"
  },
```

**Comment by 9kubczas4** [comment]
The `custom` configuration name could be specified using the `FIREBASE_FRAMEWORKS_BUILD_TARGET` env variable.

On MacOS: `FIREBASE_FRAMEWORKS_BUILD_TARGET='live' firebase deploy`
On Windows: `set FIREBASE_FRAMEWORKS_BUILD_TARGET='live' firebase deploy`

Also in PR #6594 there is an improvement, the error message for this particular situation will be more meaningful: `Unable to determine the application to deploy, specify a target via the FIREBASE_FRAMEWORKS_BUILD_TARGET environment variable`.
