### ISSUE TITLE
User code failed to load. Cannot determine backend specification

### ISSUE THREAD

**Issue by rendomnet** [firebase/firebase-tools#6139]
### [REQUIRED] Environment info

**firebase-tools:** 12.4.4

**Platform:** Windows 11

### [REQUIRED] Test case
A month ago, I had a functional code that worked perfectly. However, as I attempt to deploy it now, I am encountering a frustratingly elusive error that provides minimal information on its origin.
"Error: User code failed to load. Cannot determine backend specification"  <--??!!

### [REQUIRED] Steps to reproduce

Why your errors are so useless? Why working code stoped working when you upgrade something on your side.

### [REQUIRED] Expected behavior

deploying

### [REQUIRED] Actual behavior
Error: User code failed to load. Cannot determine backend specification

**Comment by TomV** [comment]
I am seeing the exact same issue and I am deploying code that used to deploy fine.  I have even rolled back both firebase-tools (several versions, iteratively) and a few versions of firebase-frameworks.  Same issue - how was this closed?

**Comment by mustafaekim** [comment]
I am also experiencing this issue whenever I upgrade the firebase-tools package from 11.26.1 to a recent version. Why?

**Comment by Dagmawi-a-Negatu** [comment]
Was anyone able to find the source? Having the same issue :(

**Comment by mustafaekim** [comment]
See [here](https://github.com/firebase/firebase-tools/issues/5888)

**Comment by Dagmawi-a-Negatu** [comment]
Downgrading firebase tools and running on 16 nodejs seemed to fix my issue.
