### ISSUE TITLE
Error: Unable to detect the web framework in use, check firebase-debug.log for more info.when using vite

### ISSUE THREAD

**Issue by Emerald-9612** [firebase/firebase-tools#6195]
I used firebase init hosting to create a vite app but it responded with Error: Unable to detect the web framework in use, check firebase-debug.log for more info. This is the cli I used it  might help to reproduce this 

### [REQUIRED] Environment info

**firebase-tools:**

**Platform:**

### [REQUIRED] Steps to reproduce
PS C:\Users\win\CODE\Firebase> firebase init hosting

     ######## #### ########  ######## ########     ###     ######  ########
     ##        ##  ##     ## ##       ##     ##  ##   ##  ##       ##
     ######    ##  ########  ######   ########  #########  ######  ######
     ##        ##  ##    ##  ##       ##     ## ##     ##       ## ##
     ##       #### ##     ## ######## ########  ##     ##  ######  ########

You're about to initialize a Firebase project in this directory:

  C:\Users\win\CODE\Firebase

? Are you ready to proceed? Yes

=== Project Setup

First, let's associate this project directory with a Firebase project.
You can create multiple project aliases by running firebase use --add,
but for now we'll just set up a default project.

? Please select an option: Use an existing project
? Select a default Firebase project for this directory: rpg-multiplayer-e7254 (<my project id>)
i  Using project <my project id>

=== Hosting Setup
? Do you want to use a web framework? (experimental) Yes
? What folder would you like to use for your web application's root directory? game
Could not determine the web framework in use.
? Please choose the framework: Vite
? What language would you like to use? JavaScript

Scaffolding project in C:\Users\win\CODE\Firebase\game...

Done. Now run:

  cd game
  npm install
  npm run dev
                                                                                                                                                                                               [
added 8 packages, and audited 9 packages in 9s

3 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
? In which region would you like to host server-side content, if applicable? asia-east1 (Taiwan)
? Set up automatic builds and deploys with GitHub? No

i  Writing configuration info to firebase.json...
i  Writing project information to .firebaserc...
i  Writing gitignore file to .gitignore...

+  Firebase initialization complete!
PS C:\Users\win\CODE\Firebase\game> npm run build
PS C:\Users\win\CODE\Firebase\game> cd ../       
PS C:\Users\win\CODE\Firebase> firebase deploy

**Comment by aalej** [comment]
Hey @Emerald-9612, sorry for the late response here. I tried to reproduce this issue using the latest version of Firebase Tools, which is currently 13.8.0, and I was unable to encounter any errors during setup or deployment.

From what I can gather, the steps you took were:
1. Run `firebase experiments:enable webframeworks`
1. Run `firebase init hosting --project PROJECT_ID`
    - Are you ready to proceed? Yes
    - Do you want to use a web framework? (experimental) Yes
    - What folder would you like to use for your web application's root directory? game
    - Please choose the framework: Vite
    - What language would you like to use? JavaScript
    - In which region would you like to host server-side content, if applicable? asia-east1 (Taiwan)
    - Set up automatic builds and deploys with GitHub? No
1. Run `cd game`
1. Run `npm install`
1. Run `cd ../`
1. Run `firebase deploy`

No errors were raised during deployment or setup. This issue has likely been addressed in the most recent versions. I'll go ahead and close this since this seems to be resolved. If you're still encountering this issue, feel free to let us know and we'll reopen this thread.
