### ISSUE TITLE
Doesn't work with Node v4.1

### ISSUE THREAD

**Issue by kd7yva** [firebase/firebase-tools#62]
If I use nvm to use node 0.12.1, then firebase-tools work.  But if I set nvm to use v4.1 then when I firebase deploy I get a hung cli as if it is waiting for something.  I have to ctrl-c to get out.

**Comment by drtriumph** [comment]
I've not been able to reproduce this on Ubuntu or Mac Yosemite. What setup do you have? Are you trying to deploy a large number of files (thousands or more) or is the site you're trying to deploy particularly large (gigabytes?)

**Comment by kd7yva** [comment]
Good to know that you can't reproduce.  I will look into my setup further and get back to you.  Thanks!

**Comment by drtriumph** [comment]
Could I get you to try again now - we had a hiccup on one of our servers earlier and it might be an unfortunate coincidence

**Comment by kd7yva** [comment]
Thanks Chris; but it ended up the same.  I then continued to remove all
firebase related npm installs and reinstall firebase-tools; and it worked.
I must have had a bad sym link in there somewhere.  I'm running fine now :)
 Thanks

**Comment by drtriumph** [comment]
Glad you got everything working, thanks for sharing the resolution
