### ISSUE TITLE
Deploy message showing "shutdown requested via /__/quitquitquit" using version 12.4.1

### ISSUE THREAD

**Issue by taeold** [firebase/firebase-tools#6212]
### [REQUIRED] Environment info

**firebase-tools:** 12.4.1

**Platform:** macOS

### [REQUIRED] Test case

Init a new CF3 functions project

### [REQUIRED] Steps to reproduce

`firebase deploy`

### [REQUIRED] Expected behavior

Deploy succeeds without suspicious error log entries

### [REQUIRED] Actual behavior

```
" i functions: Loading and anaylzing source code for codebase default to determine what to deploy
Serving at port 8061

shutdown requested via /__/quitquitquit"
```

which is confusing. Shouldn't print this if this is all internal implementation detail

**Comment by salman-mastermind** [comment]
please fix it quickly, many people aren't able to deploy their cloud functions.

**Comment by taeold** [comment]
@salman-mastermind This message is unrelated to deployment error - it's a debug message that's being printed on every deploy regardless of a successful/unsucessful deploy. If you are having trouble deploying your function, please open up a issue or reach out to [Firebase Support](https://firebase.google.com/support) so we can help!

**Comment by salman-mastermind** [comment]
@taeold , please have a look when I run the deploy command, it tries to validate the code of the function by running an emulator, if it passes the validation then the tool proceeds to push & deploy the code. In most users' cases, it fails & errors out at the emulator-based validation step.

![image](https://github.com/firebase/firebase-tools/assets/85483006/8381d823-1a12-443d-b5df-f7545d202cfc)

**Comment by aalej** [comment]
Hi @salman-mastermind, I understand that you’re having an issue with deploying your functions. However, the issue filed here is more related to cleaning up/removing the log “shutdown requested via /__/quitquitquit”. The message is printed every time a deployment is made, whether it is successful or unsuccessful.

I would recommend opening a new issue and specifying the details using the provided template. This way, it would be more efficient in identifying the cause of the error you’re encountering. Thanks!
