### ISSUE TITLE
crashlytics: symbols: upload command works for Android but not iOS

### ISSUE THREAD

**Issue by roblframpton** [firebase/firebase-tools#6215]
### [REQUIRED] Environment info

**firebase-tools:** 12.4.6

**Platform:** Windows 10

### [REQUIRED] Test case

Build any Flutter application, such as the default demo app, using `split-debug-info`, both for Android and iOS:

```
flutter build appbundle --obfuscate --split-debug-info=./debug/android
flutter build apk --obfuscate --split-debug-info=./debug/ios
```

### [REQUIRED] Steps to reproduce

Now try to upload the debug symbols as per [this part of the documentation](https://firebase.google.com/docs/crashlytics/get-started?platform=flutter#add-sdk).  Note that this documentation erroneously states that `split-debug-symbols` is not supported for iOS; this has not been true for some time.

```
firebase crashlytics:symbols:upload --app [Android app ID] ./debug/android
firebase crashlytics:symbols:upload --app [iOS app ID] ./debug/ios
```

### [REQUIRED] Expected behavior

Both commands succeed, with output like this:

```
i  Downloading crashlytics-buildtools.jar to /home/circleci/.cache/firebase/crashlytics/buildtools/crashlytics-buildtools-2.9.2.jar
i  For open source licenses used by this command, look in the META-INF directory in the buildtools.jar file
i  Generating symbols for ./debug/android
i  Generated symbols for ./debug/android
i  Output Path: /tmp/crashlytics-1808a0d4-9e81-4694-be57-1dfd1ba55e13/nativeSymbols/1-1000310226573-android-de00c0518473f7a0476cc4/breakpad
i  Uploading all generated symbols...
i  Successfully uploaded all symbols
```

### [REQUIRED] Actual behavior

The Android command succeeds, but iOS fails with an obscure error message:

```
i  Downloading crashlytics-buildtools.jar to /Users/distiller/.cache/firebase/crashlytics/buildtools/crashlytics-buildtools-2.9.2.jar
i  For open source licenses used by this command, look in the META-INF directory in the buildtools.jar file
i  Generating symbols for ./debug/ios
⚠  [CRASHLYTICS LOG DEBUG] Crashlytics Buildtools initialized.
[CRASHLYTICS LOG DEBUG] Extracting dump_syms from dump_syms/macos/dump_syms.bin to /Users/distiller/project/.crashlytics/dump_syms.bin
[CRASHLYTICS LOG DEBUG] Breakpad symbol generator initialized: /Users/distiller/project/.crashlytics/dump_syms.bin
[CRASHLYTICS LOG DEBUG] Generating native symbol files for /Users/distiller/project/./debug/ios; writing output to: /var/folders/bl/wbxjgtzx7j5_mjsmfr3ynlc00000gp/T/crashlytics-e6e14cd5-030b-42f7-8865-b943caa9fed6/nativeSymbols/1-1000310226573-ios-a0322176ba30adc7476cc4/breakpad
[CRASHLYTICS LOG DEBUG] 1 native libraries found at ./debug/ios
[CRASHLYTICS LOG DEBUG] Crashlytics generating Breakpad Symbol file for: /Users/distiller/project/./debug/ios/app.ios-arm64.symbols
[CRASHLYTICS LOG DEBUG] Extracting Breakpad symbols to temp file: /var/folders/bl/wbxjgtzx7j5_mjsmfr3ynlc00000gp/T/crashlytics-e6e14cd5-030b-42f7-8865-b943caa9fed6/nativeSymbols/1-1000310226573-ios-a0322176ba30adc7476cc4/breakpad/app.ios-arm64.symbols9104355891287269409.tmp
java.io.IOException: Breakpad symbol generation failed (exit=1), see STDERR
	at com.google.firebase.crashlytics.buildtools.ndk.internal.breakpad.BreakpadSymbolGenerator.generateSymbols(BreakpadSymbolGenerator.java:133)
	at com.google.firebase.crashlytics.buildtools.Buildtools.generateNativeSymbolFiles(Buildtools.java:273)
	at com.google.firebase.crashlytics.buildtools.CommandLineHelper.executeGenerateSymbols(CommandLineHelper.java:185)
	at com.google.firebase.crashlytics.buildtools.CommandLineHelper.executeCommand(CommandLineHelper.java:118)
	at com.google.firebase.crashlytics.buildtools.CommandLineHelper.main(CommandLineHelper.java:65)
	at com.google.firebase.crashlytics.buildtools.Buildtools.main(Buildtools.java:111)


Error: java command failed with args: -jar,/Users/distiller/.cache/firebase/crashlytics/buildtools/crashlytics-buildtools-2.9.2.jar,-symbolGenerator,breakpad,-symbolFileCacheDir,/var/folders/bl/wbxjgtzx7j5_mjsmfr3ynlc00000gp/T/crashlytics-e6e14cd5-030b-42f7-8865-b943caa9fed6/nativeSymbols/1-1000310226573-ios-a0322176ba30adc7476cc4/breakpad,-verbose,-generateNativeSymbols,-unstrippedLibrary,./debug/ios,-clientName,firebase-cli;crashlytics-buildtools
```

### Further notes

This issue was previously raised [here](https://github.com/firebase/firebase-tools/issues/5291), but it was attributed to an [issue in FlutterFire](https://github.com/firebase/flutterfire/issues/8934).  However, that issue did not address this error, and in any case, has now been resolved.

There is also an enourmous lack of clarity around iOS debugging symbols.  There are two parts of the documentation explaining how symbol upload works ([here](https://firebase.google.com/docs/crashlytics/get-started?platform=flutter#add-sdk) and [here](https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports?platform=flutter#apple)), neither of which acknowledge the other method.  So I'm not clear whether this step is even necessary, but the confusing documentation and error message are not stating that this is not required.  And, I'm not getting deobfuscated stack traces, even though I'm (attempting) to use both methods, so I'd like to understand whether this command is the problem or not.

**Comment by samedson** [comment]
Hey @roblframpton we haven't yet added support for iOS in the Firebase CLI. To upload dSYMs, you can use the `upload-symbols` tool here: https://github.com/firebase/firebase-ios-sdk/tree/master/Crashlytics

**Comment by HamzaMihfad** [comment]
@samedson can you please give us more details on how to use `upload-symbols` tool here: https://github.com/firebase/firebase-ios-sdk/tree/master/Crashlytics

**Comment by joehan** [comment]
@HamzaMihfad take a look at https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports?platform=ios

**Comment by gmarizy** [comment]
There is the exact same bug "Breakpad symbol generation failed (exit=1), see STDERR" with Android: https://github.com/firebase/firebase-android-sdk/issues/4280

**Comment by roblframpton** [comment]
@samedson Thanks for clarifying.  It appears the documentation has now been clarified too.  Perhaps the error message could be a little clearer?
