### ISSUE TITLE
Firebase function deployment fails with 'missing' dependencies error

### ISSUE THREAD

**Issue by sebastien-f** [firebase/firebase-tools#6216]
### [REQUIRED] Environment info

**firebase-tools:** 12.4.7
node : v18.16.1
npm : 9.5.1
firebase-functions: 4.4.1

**Platform:** Windows 10

### [REQUIRED] Test case

`firebase deploy --only functions`

### [REQUIRED] Steps to reproduce

1. `npm install -g firebase-tools`
2. `mkdir not-working`
3. `cd not-working`
4. `firebase init functions`
    - Are you ready to proceed > `Yes`
    - Please select an option > `Use an existing project`
    - Choose a project
    - What language would you like to use > `Typescript`
    - Do you want to use ES Lint > `Yes`
    - Do you want to install dependencies with npm now > `Yes`
7. `cd functions`
8. `npm i` (useless, but to be sure)
9. Edit index.ts, uncomment the helloWorld onRequest function (should be ligne 16 to 19)
10. in the CLI, run `firebase deploy --only functions:helloWorld`

### [REQUIRED] Expected behavior

Function will be deployed

### [REQUIRED] Actual behavior

Function is built, but the deploiement fails with the following error : 
```

Build failed with status: FAILURE and message: ...2.5 from lock file
npm ERR! Missing: @babel/plugin-syntax-typescript@7.22.5 from lock file
npm ERR! Missing: camelcase@6.3.0 from lock file
npm ERR! Missing: leven@3.1.0 from lock file
npm ERR! Missing: supports-color@8.1.1 from lock file
npm ERR! Missing: mimic-fn@2.1.0 from lock file
npm ERR! Missing: error-ex@1.3.2 from lock file
npm ERR! Missing: json-parse-even-better-errors@2.3.1 from lock file
npm ERR! Missing: lines-and-columns@1.2.4 from lock file
npm ERR! Missing: is-arrayish@0.2.1 from lock file
npm ERR! Missing: find-up@4.1.0 from lock file
npm ERR! Missing: ansi-styles@5.2.0 from lock file
npm ERR! Missing: react-is@18.2.0 from lock file
npm ERR! Missing: kleur@3.0.3 from lock file
npm ERR! Missing: sisteransi@1.0.5 from lock file
npm ERR! Missing: resolve-from@5.0.0 from lock file
npm ERR! Missing: buffer-from@1.1.2 from lock file
npm ERR! Missing: escape-string-regexp@2.0.0 from lock file
npm ERR! Missing: char-regex@1.0.2 from lock file
npm ERR! Missing: glob@7.2.3 from lock file
npm ERR! Missing: picocolors@1.0.0 from lock file
npm ERR! Missing: convert-source-map@1.9.0 from lock file
npm ERR! Missing: makeerror@1.0.12 from lock file
npm ERR! Missing: tmpl@1.0.5 from lock file
npm ERR! Missing: yallist@3.1.1 from lock file
npm ERR! Missing: ansi-styles@3.2.1 from lock file
npm ERR! Missing: escape-string-regexp@1.0.5 from lock file
npm ERR! Missing: supports-color@5.5.0 from lock file
npm ERR! Missing: color-convert@1.9.3 from lock file
npm ERR! Missing: color-name@1.1.3 from lock file
npm ERR! Missing: has-flag@3.0.0 from lock file
npm ERR! Missing: locate-path@5.0.0 from lock file
npm ERR! Missing: argparse@1.0.10 from lock file
npm ERR! Missing: sprintf-js@1.0.3 from lock file
npm ERR! Missing: p-locate@4.1.0 from lock file
npm ERR! Missing: p-limit@2.3.0 from lock file
npm ERR! Missing: p-try@2.2.0 from lock file
npm ERR! Missing: locate-path@5.0.0 from lock file
npm ERR! Missing: p-locate@4.1.0 from lock file
npm ERR! Missing: p-limit@2.3.0 from lock file
npm ERR!
npm ERR! Clean install a project
npm ERR!
npm ERR! Usage:
npm ERR! npm ci
```

The build debug log adds a bit more details : 
```
Step #1 - "build": Running "npm ci --quiet (NODE_ENV=production)"
Step #1 - "build": npm ERR! code EUSAGE
Step #1 - "build": npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
```

I did a whole video from the steps to reproduce to illustrate what I'm encountering. It's located here : https://www.youtube.com/watch?v=7UDvvdPUeYI
I logged (with firebase login) before the video starts to avoid displaying the account. Blurred two parts that were showing to much informations not related to the issue (other projects and opened windows)

Note that I'm opening that new issue because the previous (unsolved) exact same one has been closed for some errors in me typing the issue.

See https://github.com/firebase/firebase-tools/issues/6199 for more info (and https://github.com/firebase/firebase-tools/issues/5888 that is also related).

**Comment by joehan** [comment]
Hey @sebastien-f, sorry to hear that you are experiencing this issue. I tried to repro by following the exact steps in your video, and did not experience any issues on Mac (so this may be Windows specific). Based on the logs you're seeing, I suspect something strange is happening with package-lock.json and package.json. Could you share the contents of those 2 files here?

**Comment by sebastien-f** [comment]
@joehan 

I've uploaded the requested files : 
- [package.json](https://firebasestorage.googleapis.com/v0/b/openwine-dev.appspot.com/o/tmp%2Fpackage.json?alt=media&token=635a4707-81c6-4455-81b7-6bab99743f4a)
- [package-lock.json](https://firebasestorage.googleapis.com/v0/b/openwine-dev.appspot.com/o/tmp%2Fpackage-lock.json?alt=media&token=14334271-2c32-4b25-9d52-30fe640fb109)
- [whole project](https://firebasestorage.googleapis.com/v0/b/openwine-dev.appspot.com/o/tmp%2Fnot-working.zip?alt=media&token=28e62f92-1330-4170-88ce-32eefec75d52) (except node_modules) : 

It seems to be a windows only problem. If I do those exact repro steps from a mac or from Ubuntu through WSL it will work if I precede the deploy with an npm install. If I just copy the project and try to deploy (without `npm i`, it will fail the same)

As I tried to look deeper into it (see #6199's comments) it seems that it's coming from the fact that the build server runs `npm ci` instead of `npm install`. CI seems to not be platform independent (which kinda defeat its purpose in my view). The only source I found on that is this [SO comment](https://stackoverflow.com/a/74853105/111625). 

**Important note** : `firebase deploy` has been working for 2+ years until recently. I'm using functions in a project and I've been deploying new and updated functions over that timespan, from windows, without issue until recently (if it helps, I can probably pinpoint the latest date of successful deploy from windows).

**Comment by PratyakshGupta48** [comment]
### **How I solved the issue.**

This issue started appearing while deploying my cloud functions a week ago. I could not find a solution and was getting mad.
I read and tried every information on the internet to resolve the error, but no success.

Finally, I decided to reset my machine, and then tried to redeploy the cloud function with the exact same configuration and versions and this time it worked!

Also, thoroughly comparing I found that when we install NodeJS on our machine , with all the required packages **_python311_** also gets installed which helps in downloading of the missing dependencies mentioned in the error and i had deleted python311 folder from C drive thinking it as junk which might is causing all the trouble.

I hope my comment helps in resolving the issue!🫡
![Screenshot 2023-08-07 220438](https://github.com/firebase/firebase-tools/assets/136789163/d5d12027-2178-414c-b1d8-37e18a61c65e)

**Comment by joehan** [comment]
@PratyakshGupta48 thanks a ton for weighing in - I suspect that something similar is causing this issue.

@sebastien-f I just tested the same steps on a Windows machine without issue, which leads me to believe that there is an issue with npm on you machine. I compared the package-lock.json from my windows machine, and it has many more entries that the one you shared.  If you're still having issues, try reinstalling `npm` and `node` on your machne.

**Comment by sebastien-f** [comment]
@joehan thank you for the feedback, I will try that sometime this week and report accordingly.

**Comment by sebastien-f** [comment]
@joehan here are the steps I took : 
- deleted node_modules and package.json from functions folder
- fully uninstalled both node and npm, deleted npm cache, .npmrc and everything I could find npm related
- checked that it was not installed anymore
- reinstalled node 18.16.1 (to match the build server) which installed npm 9.5.1
- reinstalled firebase-tools (12.4.7)
- ran npm install
- ran firebase deploy functions
- got the same error
- tried to run npm ci in the functions folder, no error on my machine
- ran firebase deploy functions, still the same error

But your comment that it was something related to npm was still on my mind, especially because I also noticed the difference between ubuntu's and windows' package-lock.json file size. 

And then I remembered, a few years ago, fiddling with npm config because of a React update.

I had a global legacy-peer-deps set to true. Removed it and try to deploy with success this time. 

Thank you again for your help.

**Comment by Maria4lexzy** [comment]
@sebastien-f 

the command `npm config set legacy-peer-deps false` worked for me as well. Thanks!

**Comment by blestab** [comment]
> @sebastien-f
> 
> the command `npm config set legacy-peer-deps false` worked for me as well. Thanks!

This is what worked for me too but I also needed to delete node_modules and package-lock.json, and then npm i in the functions folder. Then firebase deploy --only functions worked

**Comment by Bash4195** [comment]
@blestab I've wasted so much time on this issue... I can't thank you enough for sharing your solution, It should be illegal to love you this much.

**Comment by tunahantatli** [comment]
I have been struggling with this error for hours. npm config set legacy-peer-deps false saved me too. Thank you.

**Comment by MannanJaffery** [comment]
Thanks alot , I wasted 2 days sleep for this issue

**Comment by imshaaz21** [comment]
Modify firebase.json functions to ignore package-lock.json
