### ISSUE TITLE
NextAuth Google Sign-in Redirect Fails on Firebase Hosting with Next.js 13 Support

### ISSUE THREAD

**Issue by markdagraca** [firebase/firebase-tools#6225]
### [REQUIRED] Environment info

**firebase-tools:** 12.4.3

**Platform:** windows

### [REQUIRED] Test case

When using NextAuth with Next.js 13, the application works as expected in the local environment, redirecting to the Google provider. However, when deployed to Firebase with its new Next.js framework support, the site loads, but the sign-in does not redirect to the Google sign-in. The POST request fails with a 408 error.

### [REQUIRED] Steps to reproduce

1. Deploy the Next.js application with NextAuth to Firebase with new Next.js framework support.
2. Click to sign in.
3. Observe the failure to redirect and the 408 error in the network console.

### [REQUIRED] Expected behavior

The application should redirect to the Google sign-in page when clicking on the sign-in button, both in the local and Firebase-hosted environments.

### [REQUIRED] Actual behavior

The application does not redirect to the Google sign-in page when hosted on Firebase. The POST request fails with a 408 error. The logging expected is not appearing in the logging explorer in GCP. The Firebase hosting URL is in the OAuth credentials and is being used as the NextAuth URL env param.
Here is the code snippet located in /pages/api/auth/[...nextauth].ts:

```typescript
import { NextApiRequest, NextApiResponse } from "next";
import NextAuth from "next-auth";
import Google from "next-auth/providers/google";
import { NextRequest, NextResponse } from "next/server";

const { GOOGLE_ID, GOOGLE_SECRET } = process.env;
if (!GOOGLE_ID || !GOOGLE_SECRET) {
  throw new Error(
    "Missing GOOGLE_ID and GOOGLE_SECRET environment variables. Did you forget to run your script?",
  );
}
export default NextAuth({
  providers: [
    Google({
      name: "GOOGLE LOGIN",
      clientId: GOOGLE_ID,
      clientSecret: GOOGLE_SECRET,
    }),
    // ...add more providers here
  ],
  debug: true,
  logger: {
    error(code, ...message) {
      console.log(code, message);
    },
    warn(code, ...message) {
      console.log(code, message);
    },
    debug(code, ...message) {
      console.log(code, message);
    },
  },
});

**Comment by markdagraca** [comment]
Thanks for the quick reply @balazsorban44! I'll try V5; I tried V4 and got this issue [firebase-tools#6225](https://github.com/firebase/firebase-tools/issues/6225).

From what I read, it seems Firebase hosting strips the headers.

Please check your Twitter DM; I just sent you a message.

**Comment by markdagraca** [comment]
Bumped by increasing the memory on the backend services firebase.json to 1gb which allowed me to discover the real error it seem to be hanging up on making a local request

DEFAULT 2023-08-12T05:47:41.470713Z Failed to proxy http://127.0.0.1:39668/api/auth/signin/google Error: socket hang up
DEFAULT 2023-08-12T05:47:41.470743Z at connResetException (node:internal/errors:717:14)
DEFAULT 2023-08-12T05:47:41.470751Z at Socket.socketCloseListener (node:_http_client:475:25)
DEFAULT 2023-08-12T05:47:41.470757Z at Socket.emit (node:events:525:35)
DEFAULT 2023-08-12T05:47:41.470763Z at Socket.emit (node:domain:552:15)
DEFAULT 2023-08-12T05:47:41.470768Z at TCP.<anonymous> (node:net:322:12)
DEFAULT 2023-08-12T05:47:41.470774Z at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
DEFAULT 2023-08-12T05:47:41.470779Z code: 'ECONNRESET'
DEFAULT 2023-08-12T05:47:41.470784Z }

**Comment by markdagraca** [comment]
looks like this issue is related to post request with body not being processed correctly when using nextjs+firebase similar issue are being reported

https://github.com/firebase/firebase-tools/issues/6385
https://github.com/firebase/firebase-tools/issues/6308

**Comment by leoortizz** [comment]
@markdagraca Apologies for the delay here. The related issues are closed, are you still having this issue?
