### ISSUE TITLE
Firebase python functions fails to deploy if package.json is present in the functions directory 

### ISSUE THREAD

**Issue by dilippanicker** [firebase/firebase-tools#6228]
### [REQUIRED] Environment info

**firebase-tools: 12.4.7**

**Platform: Ubuntu 22, python 3.11**

### [REQUIRED] Test case

Firebase python functions fails to deploy if package.json is present in the functions directory 
### [REQUIRED] Steps to reproduce

1. Create a python functions directory and main.py which deploys fine (either in emulator or cloud)
2. Create a package.json file in the same functions directory (empty will do)

### [REQUIRED] Expected behavior
functions should deploy successfully.

### [REQUIRED] Actual behavior
Deploy fails with Error:
```
Failed to load function definition from source: FirebaseError: runtime field is required but was not found in firebase.json.
To fix this, add the following lines to the functions section of your firebase.json:
"runtime": "nodejs18"  
```

**Comment by aalej** [comment]
Hi @dilippanicker, thanks for reaching out. I was able to reproduce the error you mentioned and I would like to get a better overview of this. Could you help us understand why you’re adding a package.json file inside your Python functions directory?

**Comment by kaycebasques** [comment]
Hi, just ran into this. My layout looks like this:

* src
  * server
    * functions

I avoid deeply nested directories when possible. I wanted to move the stuff in `//src/server/functions` into `//src/server`. Sounds like Firebase has an implicit policy against this if it means `package.json` is in the same directory as the Firebase Functions Python code?

**Comment by BenSullivan-iOS** [comment]
> Since there haven't been any recent updates here, I am going to close this issue.
> 
> @dilippanicker if you're still experiencing this problem and want to continue the discussion just leave a comment here and we are happy to re-open this.

I'm experiencing this exact issue, I have Python 3.11 installed. Firebase version 12.9.1. Everything appears setup correctly, I'm using python in the `main.py` and have a `package.json`, yet I receive the following error. It constantly asks for Node, not sure what I'm missing, does anyone know what I may have missed?

<img width="636" alt="Screenshot 2023-11-18 at 21 19 41" src="https://github.com/firebase/firebase-tools/assets/15668536/bddbed45-824e-4e6e-adba-8d7036b9f87a">
