### ISSUE TITLE
Emulator: beforeUserCreated blocking function not triggered when creating user via Admin SDK

### ISSUE THREAD

**Issue by jdddog** [firebase/firebase-tools#6235]
### [REQUIRED] Environment info

**firebase-tools:** 12.4.7

**Platform:** Ubuntu 22.04 LTS

### [REQUIRED] Test case
When using the Firebase Emulator, the beforeUserCreated 2nd gen blocking function is not triggered if the user is created via the Admin SDK.

### [REQUIRED] Steps to reproduce

Create a 2nd gen blocking function with beforeUserCreated:
```typescript
import { beforeUserCreated } from "firebase-functions/v2/identity";

export const userBeforeCreate = beforeUserCreated(async (event) => {
  // Do something, e.g. add a custom claim to the user
  return {
    customClaims: { admin: true },
  };
});
```

See here for docs: https://firebase.google.com/docs/functions/auth-blocking-events?gen=2nd

Run firebase emulators:
```bash
firebase emulators:start --only functions,auth
```

Export environment variable before running create user code:
```
export FIREBASE_AUTH_EMULATOR_HOST="127.0.0.1:9099"
```

Run this code in a JavaScript environment:
```javascript
const admin = require("firebase-admin");

admin.initializeApp({
  projectId: "my-project-id",
});
const auth = admin.auth();

auth
  .createUser({
    email: "test-user@test.com",
    password: "123456",
  })
  .then((userRecord) => {
    console.log("Successfully created new user:", userRecord.uid);
  })
  .catch((error) => {
    console.log("Error creating new user:", error);
  });
```

The new user appears in Auth Emulator UI, however, `beforeUserCreated` is not triggered.

### [REQUIRED] Expected behavior

When creating a user via the Admin SDK, the `beforeUserCreated` blocking function should be triggered. 

There should be a way to write unit / integration tests for the `beforeUserCreated` blocking function, which means that there must be a way to create a user and have the `beforeUserCreated` blocking function triggered in an emulated environment?

### [REQUIRED] Actual behavior

The `beforeUserCreated` blocking function is not triggered.

**Comment by aalej** [comment]
Hi @jdddog, thanks for reaching out. Creating users using the Admin SDK will not trigger Auth Blocking functions. As mentioned in this [comment](https://github.com/firebase/firebase-functions/issues/1219#issuecomment-1240787500), the reason for this is that the Admin SDK should run in a privileged environment and whatever check you have for blocking user creation doesn't need to be blocked for privileged operation.

I would recommend filing a feature request to [Google Cloud Identity Platform](https://cloud.google.com/identity-platform/docs/support#file_feature_requests_and_bug_reports) if triggering Auth blocking functions when creating users using the Admin SDK is something you would like to see implemented.
