### ISSUE TITLE
IDX SvelteKit app does not deploy to Firebase Hosting

### ISSUE THREAD

**Issue by nalin** [firebase/firebase-tools#6241]
### [REQUIRED] Environment info

12.4.7

**firebase-tools:**

N/A

**Platform:**

IDX

### [REQUIRED] Test case

I'm trying to deploy my IDX SvelteKit app to Firebase...not sure how to give you a reproduceable version of this.

### [REQUIRED] Steps to reproduce

N/A

### [REQUIRED] Expected behavior

That it deploys to Firebase

### [REQUIRED] Actual behavior

I get this error: 
[error] [Firebase Plugin] Error deploying to hosting: Cannot find module 'file:///home/user/contract-monitor/svelte.config.js'

However this file does exist.

**Comment by aalej** [comment]
Hi @nalin, I understand that it would be difficult to provide a test case. I’m currently unsure how to reproduce this issue, and I’d like it if you could provide us with some details on steps you took to setup your IDX SvelteKit app and integrate it with Firebase. 

Having that information will help us have a baseline for troubleshooting the issue.
