### ISSUE TITLE
Deployment Failed with Next.js

### ISSUE THREAD

**Issue by xuc323** [firebase/firebase-tools#6244]
### [REQUIRED] Environment info

**firebase-tools:** v12.4.7

**Platform:** macOS

### [REQUIRED] Test case

A simple `create-next-app` that requires the creation of Cloud Functions (Image Optimization).

### [REQUIRED] Steps to reproduce

```
firebase deploy
```

### [REQUIRED] Expected behavior

The app deploys successfully.

### [REQUIRED] Actual behavior

```
Building a Cloud Function to run this application. This is needed due to:
 • Image Optimization
 • non-static component /_not-found

npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: firebase-frameworks@0.10.5
npm ERR! Found: firebase@10.1.0
npm ERR! node_modules/firebase
npm ERR!   firebase@"^10.1.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peerOptional firebase@"^9.9.0" from firebase-frameworks@0.10.5
npm ERR! node_modules/firebase-frameworks
npm ERR!   firebase-frameworks@"^0.10.4" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: firebase@9.23.0
npm ERR! node_modules/firebase
npm ERR!   peerOptional firebase@"^9.9.0" from firebase-frameworks@0.10.5
npm ERR!   node_modules/firebase-frameworks
npm ERR!     firebase-frameworks@"^0.10.4" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:

[2023-08-11T18:17:15.651Z] Error: Command failed: npm i --omit dev --no-audit
    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at prepareFrameworks (/usr/local/lib/node_modules/firebase-tools/lib/frameworks/index.js:367:42)
    at async deploy (/usr/local/lib/node_modules/firebase-tools/lib/deploy/index.js:55:13)

Error: An unexpected error has occurred.
```

**Comment by BiskremMuhammad** [comment]
Same!! any help plz

**Comment by BiskremMuhammad** [comment]
hey @xuc323 , 
try downgrading firebase in your `package.json` file to 

```
"dependencies": {
        "firebase": "^9.23.0",
        "firebase-admin": "^11.10.1",
        "firebase-frameworks": "0.10.4"
    }
```

**Comment by xuc323** [comment]
> hey @xuc323 , try downgrading firebase in your `package.json` file to
> 
> ```
> "dependencies": {
>         "firebase": "^9.23.0",
>         "firebase-admin": "^11.10.1",
>         "firebase-frameworks": "0.10.4"
>     }
> ```

Thanks for the suggestion!
I've considered that, but I kind of need the latest `firebase` package to work.

**Comment by guilhermekonell** [comment]
Hi @xuc323, I'm also having this problem, any solution for this?

**Comment by xuc323** [comment]
> Hi @xuc323, I'm also having this problem, any solution for this?

I'd say to remove everything that might trigger the creation of cloud functions. It should be resolved when the new package version is published, but I'm not sure when..

**Comment by xuc323** [comment]
`firebase-framework-tools` v0.10.6 is now released which fixed the peer dependency conflict. I'm closing this issue.
