### ISSUE TITLE
Deploying fails if you have a .runtimeconfig.json

### ISSUE THREAD

**Issue by Kamshak** [firebase/firebase-tools#625]
### Version info

3.17.3

### Steps to reproduce

- Create a new project: firebase init
- Fill out all the stuff
- Uncomment the hello world function
- Fetch config for the sim: firebase functions:config:get > .runtimeconfig.json
- Deploy: firebase deploy --only functions

### Expected behavior

It Deploys

### Actual behavior

```Deployment error.
Error in the build environment
```
If you download the source code from the cloud console you can see that the zip file contains two .runtimeconfig.json files.

-------

Not sure why or how this happens. Would love to know why the local file is included, i thought it would fetch it from the runtimeconfig api. Are there docs on this somewhere

**Comment by laurenzlong** [comment]
Hey @Kamshak is there a reason why you are running "firebase functions:config:get > .runtimeconfig.json" prior to deployment?

**Comment by merlinnot** [comment]
@laurenzlong It's often needed for shell/serve: https://firebase.google.com/docs/functions/local-emulator#install_and_configure_the_cloud_functions_shell

**Comment by Kamshak** [comment]
@laurenzlong exactly what @merlinnot said :)

**Comment by laurenzlong** [comment]
That makes sense, I'll look into a fix.
