### ISSUE TITLE
SvelteKit Hosting Deployment Error: `ENOENT: no such file or directory`

### ISSUE THREAD

**Issue by Aretle** [firebase/firebase-tools#6253]
### [REQUIRED] Environment info

**firebase-tools:** 12.4.7

**Platform:** Ubuntu 22.04.3 LTS 

### [REQUIRED] Test case

I set up a simple SvelteKit project using the steps in the [documentation](https://kit.svelte.dev/docs/creating-a-project). Then I Initialised a Firebase project with hosting and experimental web-frameworks enabled. After running `firebase deploy`, I receive "Error: An unexpected error has occurred."

Checking the `firebase-debug.log` file, there is the following information:
```
[debug] [2023-08-14T08:05:05.374Z] Error: ENOENT: no such file or directory, lstat '/home/aretle/Desktop/my-app/home/aretle/Desktop/my-app/.svelte-kit/output/server'
```
The path to the project (`home/aretle/Desktop/my-app/`) is written twice, which is the wrong path. The directory: `/home/aretle/Desktop/my-app/.svelte-kit/output/server` exists.

I found some similar closed issues:
https://github.com/firebase/firebase-tools/issues/5144
https://github.com/firebase/firebase-tools/issues/5158

### [REQUIRED] Steps to reproduce

```bash
npm install -g firebase-tools

npm create svelte@latest my-app
cd my-app
npm install

npm install firebase

firebase login
firebase experiments:enable webframeworks
firebase init
firebase deploy
```

### [REQUIRED] Expected behavior

The default SvelteKit app is deployed to Firebase and I can visit it on the Web.

### [REQUIRED] Actual behavior

```
[debug] [2023-08-14T08:41:10.107Z] Error: ENOENT: no such file or directory, lstat '/home/aretle/Desktop/my-app/home/aretle/Desktop/my-app/.svelte-kit/output/server'
[error] 
[error] Error: An unexpected error has occurred.
```

**Comment by neil3000** [comment]
I have the same issue on a project, but not on a different one. Still trying to figure out why

**Comment by llaupi** [comment]
Could you solve it?

**Comment by llaupi** [comment]
pudiste resolverlo
 ?

**Comment by pjarnfelt** [comment]
Mid december and issue still persists!

**Comment by 9kubczas4** [comment]
Hi,

I was investigating this issue, and I wasn't able to reproduce it using firebase-tools - v12.4.7, v12.4.6, v12.9.1 and v13.0.0 with various versions of sveltekit. 

Could someone who notices this error create an example repository?
Thank you in advance

**Comment by dominoFire** [comment]
I am seeing this issue showing my path twice
