### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by rmanikam** [firebase/firebase-tools#6258]
ERROR
Request failed with status code 404
AxiosError: Request failed with status code 404
    at settle (http://localhost:3000/main.63179569887fcf60ee0b.hot-update.js:2046:12)
    at XMLHttpRequest.onloadend (http://localhost:3000/main.63179569887fcf60ee0b.hot-update.js:758:66)

### [REQUIRED] Environment info

**firebase-tools:**

**Platform:**

**Comment by aalej** [comment]
Hi @rmanikam, I understand that you’re encountering an error. However, for us to be able to start our initial investigation, we would need other information. 

Could you file a new issue and specify the details using the provided template? This way, it would be more efficient in identifying the cause of the error. That being said, I'll be closing this for now.
