### ISSUE TITLE
Unable to complete "npm install -g firebase-tools" command in windows 10 environment

### ISSUE THREAD

**Issue by chetan4651** [firebase/firebase-tools#626]
### Version info

OS - windows 10
node.js version  -  8.9.4 
npm version - 5.6.0

### Steps to reproduce

1) open command prompt in selected folder
2) Run "npm install -g firebase-tools" command.

### Expected behavior
Should be installed packages related to firebase.

### Actual behavior
Getting errors while running above mentioned command..

### LOG

 C:\Users\Chetan\Desktop\aaa>npm install -g firebase-tools
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
C:\Users\Chetan\AppData\Roaming\npm\firebase -> C:\Users\Chetan\AppData\Roaming\npm\node_modules\firebase-tools\bin\firebase

> grpc@1.4.1 install C:\Users\Chetan\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp ERR! Tried to download(undefined): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.4.1/node-v57-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.4.1 and node@8.9.4 (node-v57 ABI) (falling back to source compile with node-gyp)
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=C:\\Users\\Chetan\\AppData\\Roaming\\npm\\node_modules\\firebase-tools\\node_modules\\grpc\\src\\node\\extension_binary\\grpc_node.node" "--module_name=grpc_node" "--module_path=C:\\Users\\Chetan\\AppData\\Roaming\\npm\\node_modules\\firebase-tools\\node_modules\\grpc\\src\\node\\extension_binary"
gyp ERR! cwd C:\Users\Chetan\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\grpc
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --library=static_library --module=C:\Users\Chetan\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\grpc\src\node\extension_binary\grpc_node.node --module_name=grpc_node --module_path=C:\Users\Chetan\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\grpc\src\node\extension_binary' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Chetan\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\grpc\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Windows_NT 10.0.16299
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Chetan\\AppData\\Roaming\\npm\\node_modules\\firebase-tools\\node_modules\\grpc\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd C:\Users\Chetan\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\grpc
node-pre-gyp ERR! node -v v8.9.4
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --library=static_library --module=C:\Users\Chetan\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\grpc\src\node\extension_binary\grpc_node.node --module_name=grpc_node --module_path=C:\Users\Chetan\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\grpc\src\node\extension_binary' (1)
npm WARN rollback Rolling back concat-map@0.0.1 failed (this is probably harmless): EPERM: operation not permitted, scandir 'C:\Users\Chetan\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\grpc\node_modules\node-pre-gyp\node_modules\rimraf\node_modules\glob\node_modules\minimatch\node_modules\brace-expansion\node_modules'
npm WARN rollback Rolling back concat-map@0.0.1 failed (this is probably harmless): EPERM: operation not permitted, scandir 'C:\Users\Chetan\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\grpc\node_modules\node-pre-gyp\node_modules\tar-pack\node_modules\fstream-ignore\node_modules\minimatch\node_modules\brace-expansion\node_modules'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: grpc@1.4.1 (node_modules\firebase-tools\node_modules\grpc):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: grpc@1.4.1 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ firebase-tools@3.17.3
added 7 packages and updated 2 packages in 111.968s

**Comment by danielsada** [comment]
Same error, different causes

![image](https://user-images.githubusercontent.com/2849006/35244098-a65dac3c-ff84-11e7-937f-425522eeeee5.png)

**Comment by techiepop** [comment]
hey i am also getting the same error

**Comment by bogacg** [comment]
Uninstall this one and install previous version (v3.17.2) See [my answer on Stackoverflow](https://stackoverflow.com/a/48357822/1539073)

**Comment by mbleigh** [comment]
Have you tried updating to the latest version of NPM and the latest patch version of the version of Node you're using? That's the most common solution for these types of problems in my experience.

**Comment by bogacg** [comment]
In my case:
* Node 9.3.0
* NPM: 5.5.1

**Comment by mbleigh** [comment]
Please report your issues in grpc/grpc-node#121 as I'm trying to consolidate all GRPC installation errors to that bug.

**Comment by bogacg** [comment]
**UPDATE 2**

`windows-build-tools` package got an update yesterday so I installed it with hope it solves the problems installing latest version of `firebase-tools`. It did not, same errors occur.

**Comment by exawatt** [comment]
I had a similar problem and error on my Windows 10 machine. My solution was to download Python 2.7.14 msi installer from python.org. During install customization, be sure to enable the "Add python.exe to Path" option. 

Then run `npm install -g firebase-tools` again. This worked for me.

Node v8.9.4
NPM v5.6.0
firebase-tools v3.17.4

**Comment by bogacg** [comment]
@exawatt I did, Python is working on my machine, it had nothing to do with build error for native packages it tries to build & fails.

**Comment by danilolopesabreu** [comment]
@bogacg Any solution plz ?

**Comment by xelra** [comment]
The problem here is that there are no pre-built binaries available for Node 9 and gRPC 1.4.1 and building gRPC fails on Windows. I've invested a lot of time trying to get gRPC to build, but still no luck.

There are gRPC binaries available for the latest version though, 1.9.1. 

@mbleigh Can the version of the gRPC dependency be bumped to 1.9.1? That would solve this issue for all of us Windows users, because we wouldn't have to build anymore.

**Comment by xelra** [comment]
Until the version is bumped, I could get gRPC to compile by temporarily removing `%USERPROFILE%\.node-gyp\<version>\include\node\openssl`. Otherwise `MSBuild.exe` fails.

**Comment by h0rdak** [comment]
Please update to a version of grpc that has precompiled binaries for windows, compiling _anything_ on windows is a pain, the only sane solution is to have it precompiled.

**Comment by danilolopesabreu** [comment]
Guys, i dont belive... work for me. take a look: 

Kaspersky Anti-virus has an active invasive check into HTTPS connections that causes this kind of problem with npm. Tested with antivirus on and off and I can confirm that it is causing the problem.

After completely disabling Encrypted connections scanning all worked as intended.

https://github.com/grpc/grpc-node/issues/140

**Comment by jagungodak** [comment]
Cleane installation Chace with:

npm  cache clean  --force

and install again firebase tools

npm  install  -g  firebase-tools

**Comment by james-lubin** [comment]
> 
> 
> Cleane installation Chace with:
> 
> npm cache clean --force
> 
> and install again firebase tools
> 
> npm install -g firebase-tools

Thank you so much! That fixed the error.

**Comment by dwatrous** [comment]
I had the same problem with Windows Defender. After disabling Windows Defender, it all worked as expected.

I should note that I'm working in a Linux VM in virtualbox on top of Windows 10, and Windows Defender still caused this issue.

**Comment by GuySarkinsky** [comment]
Hi! That solved me the problem: 
sudo npm i -g firebase-tools

**Comment by rub9542** [comment]
try running as administrator, it worked for me........

**Comment by mnansyah** [comment]
here is my case:
$ npm --version
6.14.6

$ node --version
v12.18.3

using this command :$ npm install -g firebase-tools =>FAILED.
using this command :$ npm i -g firebase-tools          => SUCCESS.

not sure what different between 'install' and 'i'.

**Comment by noman20** [comment]
use sudo install

**Comment by hadxits** [comment]
I solved this issue.  i think firebase-tools module depend on specific npm version
  1. npm uninstall -g firebase-tools
  2. npm install -g npm 
  3. npm install -g firebase-tools   


   │      New major version of npm available! 6.14.8 → 7.20.1       │
   │   Changelog: https://github.com/npm/cli/releases/tag/v7.20.1   │
   │               Run npm install -g npm to update!                │

**Comment by zehrasarac** [comment]
That solved me the problem:
exp 11.0.0 version for
- npm i firebase-tools@11.0.0

**Comment by vincentbtb** [comment]
I already solved  firebase-tools install with this command:
curl -sL firebase.tools | bash
This link is my reference: https://www.npmjs.com/package/firebase-tools/v/9.23.3
![fireBase-error_Screenshot_2024-03-17_05-30-07](https://github.com/firebase/firebase-tools/assets/145306676/5c57eeee-122f-46f4-8e79-757b8045193a)
