### ISSUE TITLE
? Allow Firebase to collect CLI and Emulator Suite usage and error reporting information? (Y/n) !  Unable to fetch the CLI MOTD and remote config.

### ISSUE THREAD

**Issue by tharanitharan305** [firebase/firebase-tools#6278]
C:\Users\thara>firebase login
i  Firebase optionally collects CLI and Emulator Suite usage and error reporting information to help improve our products. Data is collected in accordance with Google's privacy policy (https://policies.google.com/privacy) and is not used to identify you.

? Allow Firebase to collect CLI and Emulator Suite usage and error reporting information? (Y/n) !  Unable to fetch the CLI MOTD and remote config.
Error: An unexpected error has occurred.
┌────────────────────────────────────────────────────────────┐
│             firebase-tools update check failed                                                                                         │
│            Try running with sudo or get access                                                                                        │
│            to the local update config store via                                                                                        │
│ sudo chown -R $USER:$(id -gn $USER) C:\Users\thara\.config                                                         │
└────────────────────────────────────────────────────────────┘

Error: An unexpected error has occurred.

 |
\/   |
     \/
 |
\/
plz any one help me iam verymuch intrested in learning new things but this made a struck for 4 days searched in many places no correct gauidence plaz help me
![Screenshot 2023-08-18 220305](https://github.com/firebase/firebase-tools/assets/126382407/220d4722-bc63-4eba-bb5e-2350cb028fc6)
![Screenshot 2023-08-18 223038](https://github.com/firebase/firebase-tools/assets/126382407/eef6d44f-d81f-432b-890e-ebd7eb2b05a5)

**Comment by aalej** [comment]
Hi @tharanitharan305 , sorry to hear that you’re encountering this issue. I’m thinking that the cause of this might be a failing network request. For us to get a better understanding of what is causing this issue, could you provide your `firebase-debug.log` file after running `firebase login --debug`?
