### ISSUE TITLE
NextJS App Dir Metadata tags are not shown

### ISSUE THREAD

**Issue by williamaditama** [firebase/firebase-tools#6282]
### [REQUIRED] Environment info

Used NextJS with firebase

12.4.8

**firebase-tools:**

Windows

**Platform:**

### [REQUIRED] Test case

export metadata: Metadata = { title: .., description: .... }
using NextJS appdir

### [REQUIRED] Steps to reproduce

Initialize next project with appdir and metadata

### [REQUIRED] Expected behavior

Should show meta tags in chrome and the title should show in the tab title

### [REQUIRED] Actual behavior

tab title only shows website URL

**Comment by williamaditama** [comment]
I fixed it. It was an issue on my code. I removed the "use client"; from the root layout.tsx and it works perfectly

**Comment by paulinon** [comment]
Glad to hear that you've fixed this, @williamaditama. That said, I'll be closing this issue. Feel free to reopen if a new issue arises.
