### ISSUE TITLE
functions: Failed to load function definition from source: FirebaseError: Functions codebase could not be analyzed successfully. It may have a syntax or runtime error

### ISSUE THREAD

**Issue by ayfokir** [firebase/firebase-tools#6284]
### [REQUIRED] Environment info

**firebase-tools:**

**Platform:**

**Comment by blidd-google** [comment]
Hi there, the message you provided in the title indicates that there may be some kind of runtime/syntax error with your code that is preventing the CLI from analyzing your functions. Without more detail I'm unable to help you diagnose the issue; please take another look at your code, and if you believe you've discovered a bug, feel free to open up another issue with each of the sections filled out.
