### ISSUE TITLE
Cannot access `.runtimeconfig.json` when run from `firebase serve --only functions`

### ISSUE THREAD

**Issue by mono0926** [firebase/firebase-tools#629]
### Version info

```
> firebase --version
3.17.3
> node --version
v6.11.5
> npm --version
5.6.0
```

```
firebase-functions: 0.8.1
```

### Steps to reproduce

Locate `functions/.runtimeconfig.json`:

```json
{
  "environment": {
    "project_id": "development"
  }
}
```

Locate `functions/index.js`:

```index.js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const functions = require("firebase-functions");
const util = require("util");
// This is key line:
console.log(`environment: ${util.inspect(functions.config().environment.project_id)}`);

exports.foo = functions.https.onRequest((req, res) => {
    console.log(req);
});
//# sourceMappingURL=index.js.map
```

Run this:

```
firebase serve --only functions
```

### Expected behavior

`functions.config().environment` isn't `undefined` and `functions.config().environment.project_id` should be `development`.
Under firebase v3.16.0, the value was successfully accessed.

### Actual behavior

The error occurs:

```
TypeError: Cannot read property 'project_id' of undefined
```

console.log(`environment: ${util.inspect(functions.config().environment)}`);

`console.log(`environment: ${util.inspect(functions.config().environment)}`);` shows reasonable result even at version firebase v3.17.3.

```
info: environment: { project_id: 'development' }
```

**Comment by mono0926** [comment]
@laurenzlong 

It works fine at https://github.com/firebase/firebase-tools/releases/tag/v3.17.4 👍 
Thanks 🙏

**Comment by laurenzlong** [comment]
no probs!

**Comment by rolandjitsu** [comment]
I am still having this kind of issue. I'm using:
```json
"firebase-admin": "^5.9.0",
"firebase-functions": "^0.8.1",
"firebase-tools": "^3.17.4"
```

And I get:
```
$ EMULATE_FNS=true firebase experimental:functions:shell
i  functions: Preparing to emulate functions.
Warning: You're using Node.js v8.9.0 but Google Cloud Functions only supports v6.11.1.
⚠  functions: Failed to load functions source code. Ensure that you have the latest SDK by running npm i --save firebase-functions inside the functions directory.
⚠  functions: Error from emulator. FirebaseError: Error occurred while parsing your function triggers.

TypeError: Cannot read property 'key' of undefined
    at Object.<anonymous> (/Users/rolandjitsu/Projects/gvatravel/frontend/packages/functions/lib/index.js:12:25)
```

The `key of undefined` is because it doesn't seem to read the runtime env file.

**Comment by laurenzlong** [comment]
@rolandjitsu Can you give more info?

- Can you give me the line in your code that accesses config? 
- Did you run `firebase functions:config:get>.runtimeconfig.json` inside the functions folder prior to emulating?

**Comment by rolandjitsu** [comment]
@laurenzlong yes.

So the key error happens at:
```ts
import * as admin from 'firebase-admin';
import * as functions from 'firebase-functions';
import {DocumentReference} from '@google-cloud/firestore'; // TODO: Import from @firebase namespace
const mail = require('@sendgrid/mail');


// Init FB
const config = functions.config();
admin.initializeApp(config.firebase as admin.AppOptions);

// Set the SendGrid API key
const sgConfig = config.sendgrid;
mail.setApiKey(sgConfig.key); // here is where I try to read the key
```

Of course I ran that, and the contents are:
```json
{
    "sendgrid": {
        "key": "some string here"
    }
}
```

**Comment by laurenzlong** [comment]
Do you have a non-standard directory structure? Does functions/node_modules/firebase-functions exist?

Alternatively, you can also try setting process.env.CLOUD_RUNTIME_CONFIG to be the config you need, that'll also get picked up by the SDK.

**Comment by rolandjitsu** [comment]
@laurenzlong I am using Yarn [https://yarnpkg.com/lang/en/docs/workspaces/](workspaces), so in that sense, I'd say it's somewhat not a traditional setup.

All packages are hoisted and installed at the root of the project and every package (that includes the functions) only has a few binaries and some packages in its own `node_modules`.

I will give it a try with the env variable.

**Comment by dynamiclynk** [comment]
I am still getting this
```
PS C:\Users\me\Documents\projects\SafeTTrade\functions> firebase --version
3.17.7
```

config call
```
'use strict';
const functions = require('firebase-functions');
const admin = require('firebase-admin');
const environmentName=functions.config().environment.name
```

```
package.json
{
  "name": "functions",
  "description": "Cloud Functions for Firebase",
  "scripts": {
    "lint": "./node_modules/.bin/eslint .",
    "serve": "firebase serve --only functions",
    "host": "firebase serve --only functions,hosting",
    "shell": "firebase experimental:functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "dependencies": {
    "@babel/cli": "^7.0.0-beta.42",
    "@babel/core": "^7.0.0-beta.42",
    "@babel/preset-env": "^7.0.0-beta.42",
    "ajv": "^6.0.0",
    "camelcase": "^4.1.0",
    "firebase-admin": "^5.11.0",
    "firebase-functions": "^0.9.1",
    "g": "^2.0.1",
    "glob": "^7.1.2",
    "nodemailer": "^4.6.0",
    "nodemailer-ses-transport": "^1.5.1"
  },
  "devDependencies": {
    "eslint": "^4.12.0",
    "eslint-plugin-promise": "^3.6.0"
  },
  "private": true
}
```

.runtimeconfig.json in my functions folder root

```
{
  "environment": {
    "nameshort": "dev",
    "name": "development"
  }
}
```

error in ping() function

> firebase > ping()
> Sent request to function.
> firebase > info: User function triggered, starting execution
> info: Function crashed
> TypeError: Cannot read property 'name' of undefined
>     at FnHttpUtil.ping.functions.https.onRequest (C:\Users\me\Documents\projects\SafeTTrade\functions\src\fn-httpUtil.js:17:43)
>     at FnHttpUtil.cloudFunction [as ping] (C:\Users\me\Documents\projects\SafeTTrade\functions\node_modules\firebase-functions\lib\providers\https.js:37:41)
>     at exports.ping.functions.https.onRequest (C:\Users\me\Documents\projects\SafeTTrade\functions\index.js:24:21)
>     at cloudFunction (C:\Users\me\Documents\projects\SafeTTrade\functions\node_modules\firebase-functions\lib\providers\https.js:37:41)
>     at app.use (C:\Users\me\AppData\Local\Yarn\Data\global\node_modules\@google-cloud\functions-emulator\src\supervisor\worker.js:142:11)
>     at Layer.handle [as handle_request] (C:\Users\me\AppData\Local\Yarn\Data\global\node_modules\express\lib\router\layer.js:95:5)
>     at trim_prefix (C:\Users\me\AppData\Local\Yarn\Data\global\node_modules\express\lib\router\index.js:317:13)
>     at C:\Users\me\AppData\Local\Yarn\Data\global\node_modules\express\lib\router\index.js:284:7
>     at Function.process_params (C:\Users\me\AppData\Local\Yarn\Data\global\node_modules\express\lib\router\index.js:335:12)
>     at next (C:\Users\me\AppData\Local\Yarn\Data\global\node_modules\express\lib\router\index.js:275:10)
> info: Execution took 14 ms, user function completed successfully
> 
> RESPONSE RECEIVED FROM FUNCTION: 500, {"stack":"TypeError: Cannot read property 'name' of undefined\n    at FnHttpUtil.ping.functions.https.onRequest (C:\\Users\\me\\Documents\\projects\\SafeTTrade\\functions\\src\\fn-httpUtil.js:17:43)\n    at FnHttpUtil.cloudFunction [as ping] (C:\\Users\\me\\Documents\\projects\\SafeTTrade\\functions\\node_modules\\firebase-functions\\lib\\providers\\https.js:37:41)\n    at exports.ping.functions.https.onRequest (C:\\Users\\me\\Documents\\projects\\SafeTTrade\\functions\\index.js:24:21)\n    at cloudFunction (C:\\Users\\me\\Documents\\projects\\SafeTTrade\\functions\\node_modules\\firebase-functions\\lib\\providers\\https.js:37:41)\n    at app.use (C:\\Users\\me\\AppData\\Local\\Yarn\\Data\\global\\node_modules\\@google-cloud\\functions-emulator\\src\\supervisor\\worker.js:142:11)\n    at Layer.handle [as handle_request] (C:\\Users\\me\\AppData\\Local\\Yarn\\Data\\global\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (C:\\Users\\me\\AppData\\Local\\Yarn\\Data\\global\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at C:\\Users\\me\\AppData\\Local\\Yarn\\Data\\global\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (C:\\Users\\me\\AppData\\Local\\Yarn\\Data\\global\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (C:\\Users\\me\\AppData\\Local\\Yarn\\Data\\global\\node_modules\\express\\lib\\router\\index.js:275:10)","message":"Cannot read property 'name' of undefined","name":"TypeError"}

**Comment by amnrzv** [comment]
Did you run `firebase functions:config:get>.runtimeconfig.json` in Windows Powershell by any chance?

I recently ran into this issue and figured out that it's happening for me only in Powershell.
Works fine in Command Prompt.

**Comment by plachmann** [comment]
I also found this problem when run from Powershell. I switched to Command Prompt and it worked.

**Comment by soaxelbrooke** [comment]
`firebase functions:config:get>.runtimeconfig.json` at firebase project root did not provide config to the running functions in my case, but the CLOUD_RUNTIME_CONFIG env var did work.

**Comment by TarikHuber** [comment]
Same here with Powershell. Command Prompt is working fine.

**Comment by laurenzlong** [comment]
For powershell, please use the command:
`firebase functions:config:get | ac .runtimeconfig.json`

We will fix our docs to include this info.

**Comment by TarikHuber** [comment]
Still the same when using `firebase functions:config:get | ac .runtimeconfig.json` :( but the command prompt is enough for me 😄

**Comment by RezaRahmati** [comment]
switching to command prompt doesn't solve my problem

**Comment by kossnocorp** [comment]
For those who can't make `.runtimeconfig.json` work, if you start functions from unusual location or environment, there's [a problem in firebase-functions that assumes `.runtimeconfig.json` location to be: `../../../.runtimeconfig.json` relative to the package](https://github.com/firebase/firebase-functions/blob/2e642b7348982946eb7d7c25a8e604713888b86b/src/config.ts#L87).

The solution would be to use env var `CLOUD_RUNTIME_CONFIG` that accepts both JSON string and absolute (I guess?) path to the `.runtimeconfig.json`:

```bash
env CLOUD_RUNTIME_CONFIG="$(pwd)/build/development/.runtimeconfig.json" \
    firebase serve --project staging
```

...or:

```bash
env CLOUD_RUNTIME_CONFIG="{\"easycron\":{\"token\":\"xxx\",\"group\":\"yyy\"}}" \
    firebase serve --project staging
```

Unfortunately, if `CLOUD_RUNTIME_CONFIG` can't be processed the command silently ignores it, so play around with the path or make sure you escape JSON string if it doesn't work for you right away.

**Comment by polRk** [comment]
In typescript, put your .runtimeconfig.json in build folder

**Comment by dekunleroy** [comment]
> Do you have a non-standard directory structure? Does functions/node_modules/firebase-functions exist?
> 
> Alternatively, you can also try setting the CLOUD_RUNTIME_CONFIG environment variable to be the config you need, that'll also get picked up by the SDK.
> 
> On Linux/Mac, that would look like running the following in the terminal:
> 
> ```
> export CLOUD_RUNTIME_CONFIG='{"sendgrid": {"key":"some string here"}}'
> ```

Thanks @laurenzlong, this worked for me

**Comment by hamishjohnson** [comment]
For me, I had to put .runtimeconfig.json in the root of the workspace
