### ISSUE TITLE
firebase functions deploy always returns "Error in the build environment"

### ISSUE THREAD

**Issue by stanvanheumen** [firebase/firebase-tools#630]
### Version info

firebase-tools v3.17.3
node v8.9.1

firebase-admin v5.8.1
firebase-functions v0.8.1

### Steps to reproduce

1. Run firebase deploy --only functions or firebase deploy --only functions:[function-name]
2. Wait till the CLI gives more feedback.
3. The CLI returns Deployments errors for all functions with the explaination "Error in the build environment"

### Expected behavior

The functions should be deployed properly.

### Actual behavior

The CLI always returns "Error in the build environment"

The firebase debug log: [firebase-debug.log](https://github.com/firebase/firebase-tools/files/1659695/firebase-debug.log)

**Comment by laurenzlong** [comment]
This is a server error, can you file a support ticket? https://firebase.google.com/support/

**Comment by jirawatee** [comment]
I meet this problem too and I fixed it by command lines below.

```
npm install firebase-functions@latest firebase-admin@latest --save
npm install -g firebase-tools
```

Hope it will help :)
