### ISSUE TITLE
Use custom artefacts registry 

### ISSUE THREAD

**Issue by tttmaximttt** [firebase/firebase-tools#6301]
How  I can use different  artefacts registry  then `gcf-artifacts`
I want to deploy multiple cloud functions from one artifacts registry image to multiple projects, not create new registry in every project.

**Comment by joehan** [comment]
This is not supported. From https://cloud.google.com/functions/docs/reference/rest/v2beta/projects.locations.functions#DockerRegistry:~:text=for%20eligible%20deployments.-,dockerRepository,-string 

`Cross-project repositories are not supported. Cross-location repositories are not supported.`

**Comment by tttmaximttt** [comment]
@joehan thanks a lot
