### ISSUE TITLE
NextJS API Routes not working with Firebase Hosting

### ISSUE THREAD

**Issue by ritvij14** [firebase/firebase-tools#6308]
### [REQUIRED] Environment info

**firebase-tools:** 12.5.2

**Platform:** Mac OS

### [REQUIRED] Test case

I have a simple NextJS Project using `pages` router with one single API endpoint in the `src/pages/api` folder. The API endpoint works correctly locally, but after deploying to firebase hosting it gives error, with not much info but it is either status code 500 or 408 (timeout)

Code:

Component code:

```typescript
      <Button
        onClick={async () => {
          try {
            fetch("api/mixpanel/track", {
              method: "POST",
              headers: {
                "Content-Type": "application/json",
              },
              body: JSON.stringify({
                event: "<EVENT_NAME>",
              }),
            })
              .then((res) => {})
              .catch((err) => {
                captureException(err); // I have enabled Sentry but for some reason those longs also don't appear, but lets ignore that mostly a Sentry issue
              });
          } catch (error: any) {
            Logger.log(error.toString()); // custom logging util which is configured to only work with localhost
          }
        }}
      >
        Track event
      </Button>
```

API code:
`src/pages/api/mixpanel/track.ts`

```typescript
import { NextApiRequest, NextApiResponse } from "next";

import { Logger } from "@utils/logger";
import mixpanel from "@utils/mixpanel";

export default function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method === "POST") {
    const event = req.body.event;
    const properties = req.body.properties;

    try {
      if (properties) {
        mixpanel.track(event, properties);
      } else {
        mixpanel.track(event);
      }
      return res.status(200).json({
        message: "Success",
      });
    } catch (e) {
      Logger.log("NextJS Server error: unable to track mixpanel");
      return res.status(500).json({
        message: "NextJS Server error: unable to track mixpanel",
      });
    }
  }
}
```

### [REQUIRED] Steps to reproduce

Deploy NextJS project with API routes to firebase hosting

### [REQUIRED] Expected behavior

API route working correctly.

### [REQUIRED] Actual behavior

Errors with status codes 408 or 500 (no specificity in these either, which will occur is random, but it does not work is the main thing)

**Comment by UXDart** [comment]
is there any workaround?

**Comment by ritvij14** [comment]
@UXDart  none that I know of till now, except to drop the `api` folder all together and use plain simple cloud functions.

**Comment by aalej** [comment]
Hi @ritvij14, thanks for reporting this. I was able to reproduce the issue you mentioned. I tried to use the code snippet you provided, but removed the parts related to `mixpanel` and `logger`, and I noticed that on my end, POST request responds with 500 error.

From what I can tell, the issue started occurring after Next.js v13.4.12 as I’m able to get 200 responses when using v13.4.12. Let me notify our team about this issue so that we can provide more context and investigate this behavior.

**Comment by UXDart** [comment]
what version of NextJS should we use? docs mentions 13.4.7, support says 13.4.7...

**Comment by ritvij14** [comment]
Thanks for looking into this @aalej, in the meantime I will continue with 13.4.12.

**Comment by ritvij14** [comment]
@aalej I had created a question on Stackoverflow as well, in case you need more info of simpler examples I tried.

https://stackoverflow.com/questions/77020369/nextjs-api-route-post-request-does-not-work-with-firebase-hosting

Thanks for your solution was stuck with this for 3 days and with 13.4.12 it works fine. And I don't even need to use the `config` to turn off `bodyParser` (this also doesn't do anything in the latest version btw)

**Comment by andreistefan112** [comment]
Anyone has any idea of how to fix this in next 13.4.12 but with the new App Directory (Router)? I have tried almost everything but with no success. Also the "bodyParser: false" is not supported in the new version of Next. I have ended up by encoding(base64) the body data into a custom request header and then decoding it on the server(api route) side but this is not a good solution at all. Any help would be really appreciated. Thanks!

**Comment by andreistefan112** [comment]
@ritvij14, yes it is the same (408).
Also the (13.4.12) was the only version that supported app router and worked with next internal api route (Get requests only). The other app router versions of next were all throwing 500 errors on all requests.
Anyway, thanks for your answer

**Comment by dominicdev** [comment]
any update on this?

**Comment by dominicdev** [comment]
tried to trace it seems the body was missing and also get the log as possible from hosting here is the log 

`DEFAULT 2023-09-28T09:01:07.157729Z closeEmitted: [33mtrue[39m,
DEFAULT 2023-09-28T09:01:07.157732Z defaultEncoding: [32m'utf8'[39m,
DEFAULT 2023-09-28T09:01:07.157736Z awaitDrainWriters: [1mnull[22m,
DEFAULT 2023-09-28T09:01:07.157740Z multiAwaitDrain: [33mfalse[39m,
DEFAULT 2023-09-28T09:01:07.157744Z readingMore: [33mtrue[39m,
DEFAULT 2023-09-28T09:01:07.157747Z dataEmitted: [33mfalse[39m,
DEFAULT 2023-09-28T09:01:07.157751Z decoder: [1mnull[22m,
DEFAULT 2023-09-28T09:01:07.157755Z encoding: [1mnull[22m,
DEFAULT 2023-09-28T09:01:07.157760Z [[32mSymbol(kPaused)[39m]: [33mfalse[39m
DEFAULT 2023-09-28T09:01:07.157765Z },
DEFAULT 2023-09-28T09:01:07.157770Z _events: [Object: null prototype] {
DEFAULT 2023-09-28T09:01:07.157776Z end: [36m[Function (anonymous)][39m,
DEFAULT 2023-09-28T09:01:07.157782Z error: [36m[Function (anonymous)][39m
DEFAULT 2023-09-28T09:01:07.157789Z },
DEFAULT 2023-09-28T09:01:07.157793Z _eventsCount: [33m2[39m,
DEFAULT 2023-09-28T09:01:07.157797Z _maxListeners: [90mundefined[39m,
DEFAULT 2023-09-28T09:01:07.157803Z socket: [36m<ref *1>[39m Socket {
DEFAULT 2023-09-28T09:01:07.157808Z connecting: [33mfalse[39m,
DEFAULT 2023-09-28T09:01:07.157812Z _hadError: [33mfalse[39m,
DEFAULT 2023-09-28T09:01:07.157816Z _parent: [1mnull[22m,
DEFAULT 2023-09-28T09:01:07.157820Z _host: [1mnull[22m,
DEFAULT 2023-09-28T09:01:07.157824Z _closeAfterHandlingError: [33mfalse[39m,
DEFAULT 2023-09-28T09:01:07.157829Z _readableState: ReadableState {
DEFAULT 2023-09-28T09:01:07.157833Z objectMode: [33mfalse[39m,
DEFAULT 2023-09-28T09:01:07.157837Z highWaterMark: [33m16384[39m,
DEFAULT 2023-09-28T09:01:07.157842Z buffer: BufferList { head: [1mnull[22m, tail: [1mnull[22m, length: [33m0[39m },
DEFAULT 2023-09-28T09:01:07.157848Z length: [33m0[39m,
DEFAULT 2023-09-28T09:01:07.157853Z pipes: [],
DEFAULT 2023-09-28T09:01:07.157858Z flowing: [33mtrue[39m,
DEFAULT 2023-09-28T09:01:07.157863Z ended: [33mfalse[39m,
DEFAULT 2023-09-28T09:01:07.157869Z endEmitted: [33mfalse[39m,
DEFAULT 2023-09-28T09:01:07.157875Z reading: [33mtrue[39m,
DEFAULT 2023-09-28T09:01:07.157880Z constructed: [33mtrue[39m,
DEFAULT 2023-09-28T09:01:07.157886Z sync: [33mfalse[39m,
DEFAULT 2023-09-28T09:01:07.157891Z needReadable: [33mtrue[39m,
DEFAULT 2023-09-28T09:01:07.157897Z emittedReadable: [33mfalse[39m,
DEFAULT 2023-09-28T09:01:07.157902Z readableListening: [33mfalse[39m,
DEFAULT 2023-09-28T09:01:07.157907Z resumeScheduled: [33mfalse[39m,
DEFAULT 2023-09-28T09:01:07.157912Z errorEmitted: [33mfalse[39m,
DEFAULT 2023-09-28T09:01:07.157917Z emitClose: [33mfalse[39m,
DEFAULT 2023-09-28T09:01:07.157921Z autoDestroy: [33mtrue[39m,
DEFAULT 2023-09-28T09:01:07.157928Z destroyed: [33mfalse[39m,
DEFAULT 2023-09-28T09:01:07.157933Z errored: [1mnull[22m,
DEFAULT 2023-09-28T09:01:07.157937Z closed: [33mfalse[39m,
DEFAULT 2023-09-28T09:01:07.157940Z closeEmitted: [33mfalse[39m,
DEFAULT 2023-09-28T09:01:07.157944Z defaultEncoding: [32m'utf8'[39m,
DEFAULT 2023-09-28T09:01:07.157950Z awaitDrainWriters: [1mnull[22m,
DEFAULT 2023-09-28T09:01:07.157953Z multiAwaitDrain: [33mfalse[39m,
DEFAULT 2023-09-28T09:01:07.157956Z readingMore: [33mfalse[39m,
DEFAULT 2023-09-28T09:01:07.157960Z dataEmitted: [33mfalse[39m,
DEFAULT 2023-09-28T09:01:07.157964Z decoder: [1mnull[22m,
DEFAULT 2023-09-28T09:01:07.157968Z encoding: [1mnull[22m,
DEFAULT 2023-09-28T09:01:07.158066Z [[32mSymbol(kPaused)[39m]: [33mfalse[39m
DEFAULT 2023-09-28T09:01:07.158071Z },
DEFAULT 2023-09-28T09:01:07.158076Z _events: [Object: null prototype] {
DEFAULT 2023-09-28T09:01:07.158081Z end: [36m[Array][39m,
DEFAULT 2023-09-28T09:01:07.158086Z timeout: [36m[Function: socketOnTimeout][39m,
DEFAULT 2023-09-28T09:01:07.158091Z data: [36m[Function: bound socketOnData][39m,
DEFAULT 2023-09-28T09:01:07.158098Z error: [36m[Function: socketOnError][39m,
DEFAULT 2023-09-28T09:01:07.158103Z close: [36m[Array][39m,
DEFAULT 2023-09-28T09:01:07.158108Z drain: [36m[Function: bound socketOnDrain][39m,
DEFAULT 2023-09-28T09:01:07.158113Z resume: [36m[Function: onSocketResume][39m,
DEFAULT 2023-09-28T09:01:07.158117Z pause: [36m[Function: onSocketPause][39m
DEFAULT 2023-09-28T09:01:07.158122Z },
DEFAULT 2023-09-28T09:01:07.158127Z _eventsCount: [33m8[39m,
DEFAULT 2023-09-28T09:01:07.158132Z _maxListeners: [90mundefined[39m,
DEFAULT 2023-09-28T09:01:07.158138Z _writableState: WritableState {
DEFAULT 2023-09-28T09:01:07.158144Z objectMode: [33mfalse[39m,
DEFAULT 2023-09-28T09:01:07.158149Z highWaterMark: [33m16384[39m,
DEFAULT 2023-09-28T09:01:07.158153Z finalCalled: [33mfalse[39m,
DEFAULT 2023-09-28T09:01:07.158157Z needDrain: [33mfalse[39m,
DEFAULT 2023-09-28T09:01:07.158160Z ending: [33mfalse[39m,
DEFAULT 2023-09-28T09:01:07.158163Z ended: [33mfalse[39m,
DEFAULT 2023-09-28T09:01:07.158168Z finished: [33mfalse[39m,
DEFAULT 2023-09-28T09:01:07.158171Z destroyed: [33mfalse[39m,
DEFAULT 2023-09-28T09:01:07.158174Z decodeStrings: [33mfalse[39m,
DEFAULT 2023-09-28T09:01:07.158178Z defaultEncoding: [32m'utf8'[39m,
DEFAULT 2023-09-28T09:01:07.158182Z length: [33m0[39m,
DEFAULT 2023-09-28T09:01:07.158185Z writing: [33mfalse[39m,
DEFAULT 2023-09-28T09:01:07.158189Z corked: [33m0[39m,
DEFAULT 2023-09-28T09:01:07.158193Z sync: [33mtrue[39m,
DEFAULT 2023-09-28T09:01:07.158196Z bufferProcessing: [33mfalse[39m,
DEFAULT 2023-09-28T09:01:07.158200Z onwrite: [36m[Function: bound onwrite][39m,
DEFAULT 2023-09-28T09:01:07.158205Z writecb: [1mnull[22m,
DEFAULT 2023-09-28T09:01:07.158209Z writelen: [33m0[39m,
DEFAULT 2023-09-28T09:01:07.158214Z afterWriteTickInfo: [1mnull[22m,
DEFAULT 2023-09-28T09:01:07.158218Z buffered: [],
DEFAULT 2023-09-28T09:01:07.158231Z bufferedIndex: [33m0[39m,
DEFAULT 2023-09-28T09:01:07.158236Z allBuffers: [33mtrue[39m,
DEFAULT 2023-09-28T09:01:07.158241Z allNoop: [33mtrue[39m,
DEFAULT 2023-09-28T09:01:07.158246Z pendingcb: [33m0[39m,
DEFAULT 2023-09-28T09:01:07.158251Z constructed: [33mtrue[39m,
DEFAULT 2023-09-28T09:01:07.158256Z prefinished: [33mfalse[39m,
DEFAULT 2023-09-28T09:01:07.158262Z errorEmitted: [33mfalse[39m,
DEFAULT 2023-09-28T09:01:07.158266Z emitClose: [33mfalse[39m,
DEFAULT 2023-09-28T09:01:07.158272Z autoDestroy: [33mtrue[39m,
DEFAULT 2023-09-28T09:01:07.158277Z errored: [1mnull[22m,
DEFAULT 2023-09-28T09:01:07.158282Z closed: [33mfalse[39m,
DEFAULT 2023-09-28T09:01:07.158287Z closeEmitted: [33mfalse[39m,
DEFAULT 2023-09-28T09:01:07.158291Z [[32mSymbol(kOnFinished)[39m]: []
DEFAULT 2023-09-28T09:01:07.158296Z },
DEFAULT 2023-09-28T09:01:07.158301Z allowHalfOpen: [33mtrue[39m,
DEFAULT 2023-09-28T09:01:07.158305Z _sockname: [1mnull[22m,
DEFAULT 2023-09-28T09:01:07.158309Z _pendingData: [1mnull[22m,
DEFAULT 2023-09-28T09:01:07.158313Z _pendingEncoding: [32m''[39m,
DEFAULT 2023-09-28T09:01:07.158317Z server: Server {
DEFAULT 2023-09-28T09:01:07.158320Z maxHeaderSize: [90mundefined[39m,
DEFAULT 2023-09-28T09:01:07.158324Z insecureHTTPParser: [90mundefined[39m,
DEFAULT 2023-09-28T09:01:07.158328Z requestTimeout: [33m300000[39m,
DEFAULT 2023-09-28T09:01:07.158333Z headersTimeout: [33m60000[39m,
DEFAULT 2023-09-28T09:01:07.158338Z keepAliveInitialDelay: [33m0[39m,
DEFAULT 2023-09-28T09:01:07.158343Z _idleStart: [33m241[39m,
DEFAULT 2023-09-28T09:01:07.158381Z rejectNonStandardBodyWrites: [33mfalse[39m,
DEFAULT 2023-09-28T09:01:07.158384Z maxHeadersCount: [1mnull[22m,
DEFAULT 2023-09-28T09:01:07.158389Z _idleNext: [36m[TimersList][39m,
DEFAULT 2023-09-28T09:01:07.158396Z [32m'2'[39m: [36m[Function: parserOnHeadersComplete][39m,
DEFAULT 2023-09-28T09:01:07.158401Z _consumed: [33mtrue[39m,
DEFAULT 2023-09-28T09:01:07.158405Z _events: [36m[Object: null prototype][39m,
DEFAULT 2023-09-28T09:01:07.158409Z sendDate: [33mtrue[39m,
DEFAULT 2023-09-28T09:01:07.158412Z socket: [36m[Circular *1][39m,
DEFAULT 2023-09-28T09:01:07.158416Z end: [36m[Function (anonymous)][39m,
DEFAULT 2023-09-28T09:01:07.158422Z [[32mSymbol(kCapture)[39m]: [33mfalse[39m,
DEFAULT 2023-09-28T09:01:07.158425Z [[32mSymbol(kHandle)[39m]: TCP {
DEFAULT 2023-09-28T09:01:07.158429Z [[32mSymbol(kSetKeepAlive)[39m]: [33mfalse[39m,
DEFAULT 2023-09-28T09:01:07.158432Z [[32mSymbol(kSetKeepAliveInitialDelay)[39m]: [33m0[39m,
DEFAULT 2023-09-28T09:01:07.158436Z [32m'cache-control'[39m,
DEFAULT 2023-09-28T09:01:07.158440Z [32m'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36'[39m,
DEFAULT 2023-09-28T09:01:07.158445Z [32m'2001:4455:10d:7b00:c0f1:56d6:df9:c89f,66.249.82.135,::ffff:169.254.1.1'[39m,
DEFAULT 2023-09-28T09:01:07.158449Z [32m'sec-fetch-mode'[39m,
DEFAULT 2023-09-28T09:01:07.158453Z [32m'https://rdai-community-portal.web.app/my_course/'[39m,
DEFAULT 2023-09-28T09:01:07.158457Z [32m's48hDkrIORDrAz3sjuyh5gIWcInqIjSROZ47KAY+w/I=!MNL!cache-mnl9724-MNL'[39m,
DEFAULT 2023-09-28T09:01:07.158557Z [32m'x-middleware-invoke'[39m,
DEFAULT 2023-09-28T09:01:07.158561Z method: [32m'POST'[39m,
DEFAULT 2023-09-28T09:01:07.158566Z buffer: BufferList { head: [1mnull[22m, tail: [1mnull[22m, length: [33m0[39m },
DEFAULT 2023-09-28T09:01:07.158570Z autoDestroy: [33mtrue[39m,
DEFAULT 2023-09-28T09:01:07.158575Z },
`

**Comment by deathg0d** [comment]
Same issue, any fix on this? 13.4.12 is not working for me for `server get routes` (requests are redirected to 404). The only combination (somewhat) working for me is next@13.4.7 and firebase-tools@12.5.2. Even with this combination I am struggling with these issues:

1. SSR get requests: works on emulator and cloud run revision urls but NOT on firebase hosting default url. More info: https://github.com/firebase/firebase-tools/issues/6434
2. SSR post requests: Same issue as on this thread, timeout issues

**Comment by pinqiW** [comment]
same issue for me , i tried next@13.4.12 and next@13.4.7+firebase-tool@12.5.2 none of them worked for me
<img width="1010" alt="Screenshot 2023-10-08 at 18 12 59" src="https://github.com/firebase/firebase-tools/assets/47824719/f4fba74f-e85b-438c-895a-694c110f7dc5">
@aalej if u could please help?  And i can't even get access to the test/ page in firebase hosting which suppose to be a very simple one.

# API routing problem
<img width="294" alt="Screenshot 2023-10-08 at 18 18 16" src="https://github.com/firebase/firebase-tools/assets/47824719/d86b88cd-7247-4ea8-bb8f-71078ade40ab">

component code:
```
const queryBigQuery = async()=>{
        try {
            const res = await fetch('/api/bigquery/data/fetchBigQuery', {

                method: 'GET',
                headers: { 'Content-Type': 'application/json' },
            })

            if (res.ok) {
                const jsonData = await res.json()
                console.log('Fetched Data:', jsonData)  // Debugging line to view fetched data


                const typedData: IDataItem[] = jsonData.map((item: any) => ({
                    asset_id: String(item.asset_id),
                    hazard_score: Number(item.hazard_score),
                    longitude: String(item.longitude),
                    latitude: String(item.latitude),
                    name: String(item.name),
                    valuation: item.valuation // keep 'any' type for this
                }))


                setData(typedData)  // Update the state with fetched data
            } else {
                console.error(`Error: ${res.status}`)
            }
        } catch (error) {
            console.error('Failed to fetch user data:', error)
        }
    }
```

pages/api/bigquery/data/fetchBigquery.ts

```
export default async function fetchBigQuery(req: NextApiRequest, res: NextApiResponse) {

    if (req.method !== 'GET') {
        res.status(405).end()  // Method not allowed
        return
    }

    const query = `SELECT asset_id, name, valuation, climate.max_hazard_score AS hazard_score,
   ST_X(location.geopoint) AS longitude,
  ST_Y(location.geopoint) AS latitude,
FROM alter-prime-dev.client_dmo_mar.out_dmo_mar_climate_hazards__assets
WHERE climate.scenario = "RCP 4.5" AND climate.year = "2030" `

    try {

       const [rows] = await bigquery.query({query})

        if (rows.length === 0) {
            return res.status(200).json({ message: 'No data found' })
        }
        return res.status(200).json(rows)  // Return the rows as a JSON response
    } catch (error) {
        return res.status(500).json({ error: 'BigQuery error' })
    }
}


```
# test/ problem
```
'use client'
import React  from 'react'

const Test: React.FC = () => {

    return (
        <div>
              test deployemnt
        </div>
    )

}

export default Test
```
<img width="529" alt="Screenshot 2023-10-08 at 18 20 03" src="https://github.com/firebase/firebase-tools/assets/47824719/319157ba-e988-4836-93bb-3bdf79271640">

**Comment by kwarc-star** [comment]
Any update on this?

**Comment by AaronJY** [comment]
Just wanted to share that another GitHub issue is also tracking this problem: https://github.com/vercel/next.js/issues/50166#issuecomment-1804814449

**Comment by jamesdaniels** [comment]
This has been addressed with the release of `firebase-frameworks@0.11.0` https://github.com/FirebaseExtended/firebase-framework-tools/pull/122

**Comment by fulcanelly** [comment]
> This has been addressed with the release of `firebase-frameworks@0.11.0` [FirebaseExtended/firebase-framework-tools#122](https://github.com/FirebaseExtended/firebase-framework-tools/pull/122)

how to use it ? cannot find any docs on that
