### ISSUE TITLE
Error: functions/index.js does not exist, can't deploy Firebase Functions

### ISSUE THREAD

**Issue by dfischer** [firebase/firebase-tools#631]
### Version info

3.17.3

### Steps to reproduce

Setup a new typescript project

Run `npm run build`

### Expected behavior

It deploys and uses the file from `lib/index.js` (which it isn't) declared in package.json under `main`

### Actual behavior

`npm run deploy --debug`

```
> @ deploy XXX/functions
> firebase deploy --only functions


=== Deploying to 'XXX-XXXX'...

i  deploying functions
Running command: npm --prefix $RESOURCE_DIR run build

> @ build /XXX/functions
> tsc

✔  functions: Finished running predeploy script.

Error: functions/index.js does not exist, can't deploy Firebase Functions
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ deploy: `firebase deploy --only functions`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/DFischer/.npm/_logs/2018-01-24T15_28_36_051Z-debug.log```

**Comment by dfischer** [comment]
```{
  "name": "functions",
  "scripts": {
    "test": "jest",
    "build": "./node_modules/.bin/tsc",
    "serve": "npm run build && firebase serve --only functions",
    "shell": "npm run build && firebase experimental:functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "jest": {
    "transform": {
      "^.+\\.tsx?$": "ts-jest"
    },
    "testRegex": "(/__tests__/.*|(\\.|/)(test|spec))\\.(jsx?|tsx?)$",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json"
    ]
  },
  "dependencies": {
    "@types/axios": "^0.14.0",
    "@types/lodash": "^4.14.92",
    "@types/node": "^8.0.53",
    "axios": "^0.17.1",
    "body-parser": "^1.17.2",
    "firebase-admin": "^5.0.0",
    "firebase-functions": "^0.8.1",
    "lodash": "^4.17.4",
    "pipedrive": "^3.0.2",
    "sendgrid": "^5.2.0",
    "smooch-core": "^5.6.0",
    "string-tokenizer": "^0.0.8"
  },
  "devDependencies": {
    "@types/express": "^4.11.0",
    "@types/jest": "^22.1.0",
    "jest": "^22.1.4",
    "ts-jest": "^21.2.3",
    "tslint": "^5.9.1",
    "typescript": "^2.6.1"
  },
  "private": true,
  "main": "lib/index.js",
}
```

**Comment by laurenzlong** [comment]
@dfischer Can you run the command again with the --debug flag, and paste the output here? As well, where is your package.json located?

**Comment by dfischer** [comment]
package.json is located in ./functions/package.json

```
npm run deploy --debug

> @ deploy /Users/DFischer/Code/X/X/functions
> firebase deploy --only functions


=== Deploying to 'X-XXX'...

i  deploying functions
Running command: npm --prefix $RESOURCE_DIR run build

> @ build /Users/DFischer/Code/X/X/functions
> tsc

✔  functions: Finished running predeploy script.

Error: functions/index.js does not exist, can't deploy Firebase Functions
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ deploy: `firebase deploy --only functions`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/DFischer/.npm/_logs/2018-01-24T15_28_36_051Z-debug.log
```

**Comment by tinaliang** [comment]
The package.json content should have been printed in the console with the debug command. 

Unfortunately, I was unable to reproduce this exact error. As a last resort (if you want), can you try npm uninstall -g firebase-tools && npm i -g firebase-tools and reinitializing your project?

**Comment by dfischer** [comment]
@tinaliang Should I reinitialize in the root directory `/project/` or `/project/functions/` ?

**Comment by mbleigh** [comment]
Try changing the `deploy` command in your `package.json` to `firebase deploy --only functions --debug` and then show us the results. That should help us understand what the CLI is seeing before it fails.

**Comment by tinaliang** [comment]
@dfischer reinitialize in /project/

**Comment by annie** [comment]
thank you for all your hard work @tinaliang

**Comment by eunicekokor** [comment]
great work firebase team! great quick responses @tinaliang!

**Comment by daniil-konovalenko** [comment]
I have the same issue on 3.17.4  
Reinstalling firebase-tools and reinitializing the project doesn't help. 
Here is the output of `$ firebase deploy --only functions --debug`:
```
$ firebase deploy --only functions --debug
[2018-02-02T08:42:11.096Z] ----------------------------------------------------------------------
[2018-02-02T08:42:11.101Z] Command:       /home/dan/.nvm/versions/node/v6.11.5/bin/node /home/dan/.nvm/versions/node/v6.11.5/bin/firebase deploy --only functions --debug
[2018-02-02T08:42:11.102Z] CLI Version:   3.17.4
[2018-02-02T08:42:11.103Z] Platform:      linux
[2018-02-02T08:42:11.103Z] Node Version:  v6.11.5
[2018-02-02T08:42:11.104Z] Time:          Fri Feb 02 2018 11:42:11 GMT+0300 (STD)
[2018-02-02T08:42:11.107Z] ----------------------------------------------------------------------

[2018-02-02T08:42:11.128Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2018-02-02T08:42:11.129Z] > authorizing via signed-in user
[2018-02-02T08:42:11.133Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/projects/anyconf-a

 Fri Feb 02 2018 11:42:11 GMT+0300 (STD)
[2018-02-02T08:42:11.950Z] <<< HTTP RESPONSE 200 server=nginx, date=Fri, 02 Feb 2018 08:42:12 GMT, content-type=application/json; charset=utf-8, content-length=100, connection=close, x-content-type-options=nosniff, strict-transport-security=max-age=31536000; includeSubdomains, cache-control=no-cache, no-store
[2018-02-02T08:42:11.953Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/database/anyconf-a/tokens

 Fri Feb 02 2018 11:42:11 GMT+0300 (STD)
[2018-02-02T08:42:12.612Z] <<< HTTP RESPONSE 200 server=nginx, date=Fri, 02 Feb 2018 08:42:13 GMT, content-type=application/json; charset=utf-8, content-length=256, connection=close, x-content-type-options=nosniff, strict-transport-security=max-age=31536000; includeSubdomains, cache-control=no-cache, no-store

=== Deploying to 'anyconf-a'...

i  deploying functions
Running command: npm --prefix functions run build

> functions@ build /mnt/c/Users/User/Projects/junto/anyconf/anyconf-cloud-functions/functions
> tslint -p tslint.json && ./node_modules/.bin/tsc

✔  functions: Finished running predeploy script.
[2018-02-02T08:42:19.412Z] > [functions] package.json contents: {
  "name": "functions",
  "description": "Cloud Functions for Firebase",
  "scripts": {
    "serve": "firebase serve --only functions",
    "shell": "firebase experimental:functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log",
    "build": "./node_modules/.bin/tslint -p tslint.json && ./node_modules/.bin/tsc"
  },
  "dependencies": {
    "@types/cookie-parser": "^1.4.1",
    "@types/cors": "^2.8.3",
    "@types/express": "^4.11.1",
    "cookie-parser": "^1.4.3",
    "cors": "^2.8.4",
    "express": "^4.16.2",
    "firebase": "^4.9.0",
    "firebase-admin": "^5.8.1",
    "firebase-functions": "^0.8.1",
    "firestore": "^1.1.6",
    "typescript": "^2.7.1"
  },
  "private": true,
  "devDependencies": {
    "tslint": "^5.9.1"
  }
}

Error: functions/index.js does not exist, can't deploy Firebase Functions

```

**Comment by tinaliang** [comment]
@daniil-konovalenko You're missing the "main" field in your package.json. Please add `"main": "lib/index.js"` to your package.json.

**Comment by daniil-konovalenko** [comment]
@tinaliang works now, thank you!

**Comment by dfischer** [comment]
Not sure what happened but reinitializing from scratch fixed it. I'm good, thanks :)

**Comment by alemarcano** [comment]
I speak Spanish, which is referred to "reinitializing the project"

**Comment by Abeer-h** [comment]
i have the same error in deploy 
index.js does not exist ...

**Comment by Sami-Haroon-Khan** [comment]
i am getting this error 👎 

            mode.
[17:07:09]  console.error: [2018-06-13T12:07:09.305Z] @firebase/firestore: Firestore (5.0.4): The behavior for Date
            objects stored in Firestore is going to change AND YOUR APP MAY BREAK. To hide this warning and ensure your
            app does not break, you need to add the following code to your app before calling any other Cloud Firestore
            methods: const firestore = firebase.firestore(); const settings = {/* your settings... */
            timestampsInSnapshots: true}; firestore.settings(settings); With this change, timestamps stored in Cloud
            Firestore will be read back as Firebase Timestamp objects instead of as system Date objects. So you will
            also need to update code expecting a Date to instead expect a Timestamp. For example: // Old: const date =
            snapshot.get('created_at'); // New: const timestamp = snapshot.get('created_at'); const date =
            timestamp.toDate(); Please audit all existing usages of Date when you enable the new behavior. In a future
            release, the behavior will change to the new behavior, so if you do not follow these steps, YOUR APP MAY
            BREAK.

**Comment by laurenzlong** [comment]
@Sami-Haroon-Khan This is a warning from the `firebase` module, due to a change in behavior of Firestore timestamp values. You shouldn't need to use `firesbase` in your functions. I recommend using `firebase-admin` to access Firestore. Since it is already a peer dependency of `firebase-functions`, this will make your overall package smaller.

**Comment by laurenzlong** [comment]
If you do want to continue using `firestore`, then follow the instructions in the message  to suppress the warning.

**Comment by Sami-Haroon-Khan** [comment]
@laurenzlong  Yes, I fixed it by following the instructions. Thanks.

**Comment by asasababoon** [comment]
> Not sure what happened but reinitializing from scratch fixed it. I'm good, thanks :)

how do you "reinitialize" ? is there a certain command?.  I do not understand how to do this

**Comment by juanpa097** [comment]
Delete a `functions` folder if you have one.

**Comment by sam-rad** [comment]
Had this issue with Google Functions not being deployed. Make sure the directory containing the file is not ignored in `.gcloudignore` file:

```
node_modules
#!include:.gitignore

# HERE
!functions
```

**Comment by turnono** [comment]
solved by setting "main" in package.json to: 
`"main": "lib/functions/src/index.js"`

**Comment by stanleyillidge** [comment]
@turnono es la solución mas exacta en mi caso, I fixed it

**Comment by mendrik** [comment]
I'm going to leave a comment here, because I got the same error for another reason.
When one imports files outside of functions/src, the tsc compiler will move the root of the compilation up, so that lib/ doesn't contain the index.js as expected.
The way to fix this is to add a paths section in tsconfig under compilerOptions and add a mapping there so the import like "../../../src/x" become "@shared/x" for example

**Comment by halim-boussada** [comment]
firebase deploy --only functions --debug
[2020-12-03T17:41:40.273Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2020-12-03T17:41:40.276Z] > authorizing via signed-in user
[2020-12-03T17:41:40.277Z] [iam] checking project ssss-847a8 for permissions ["cloudfunctions.functions.create","cloudfunctions.functions.delete","cloudfunctions.functions.get","cloudfunctions.functions.list","cloudfunctions.functions.update","cloudfunctions.operations.get","firebase.projects.get"]
[2020-12-03T17:41:40.296Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects/ssss-847a8:testIamPermissions
 {"permissions":["cloudfunctions.functions.create","cloudfunctions.functions.delete","cloudfunctions.functions.get","cloudfunctions.functions.list","cloudfunctions.functions.update","cloudfunctions.operations.get","firebase.projects.get"]}   
[2020-12-03T17:41:41.449Z] <<< HTTP RESPONSE 200 {"content-type":"application/json; charset=UTF-8","vary":"X-Origin, Referer, Origin,Accept-Encoding","date":"Thu, 03 Dec 2020 17:41:44 GMT","server":"ESF","cache-control":"private","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","server-timing":"gfet4t7; dur=784","alt-svc":"h3-29=\":443\"; ma=2592000,h3-T051=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","accept-ranges":"none","transfer-encoding":"chunked"}    
[2020-12-03T17:41:41.478Z] >>> HTTP REQUEST POST https://iam.googleapis.com/v1/projects/ssss-847a8/serviceAccounts/ssss-847a8@appspot.gserviceaccount.com:testIamPermissions
 {"permissions":["iam.serviceAccounts.actAs"]}
[2020-12-03T17:41:42.483Z] <<< HTTP RESPONSE 200 {"content-type":"application/json; charset=UTF-8","vary":"X-Origin, Referer, Origin,Accept-Encoding","date":"Thu, 03 Dec 2020 17:41:45 GMT","server":"ESF","cache-control":"private","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","alt-svc":"h3-29=\":443\"; ma=2592000,h3-T051=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","accept-ranges":"none","transfer-encoding":"chunked"}
!  functions: package.json indicates an outdated version of firebase-functions.
Please upgrade using npm install --save firebase-functions@latest in your functions directory.

=== Deploying to 'ssss-847a8'...

i  deploying functions
[2020-12-03T17:41:48.880Z] > [functions] package.json contents: {
  "name": "functions",
  "scripts": {
    "lint": "eslint \"src/**/*\"",
    "build": "tsc",
    "serve": "npm run build && firebase emulators:start --only functions",
    "shell": "npm run build && firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "engines": {
    "node": "12"
  },
  "main": "lib/index.js",
  "dependencies": {
    "firebase-admin": "^9.2.0",
    "firebase-functions": "^3.11.0"
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^3.9.1",
    "@typescript-eslint/parser": "^3.8.0",
    "eslint": "^7.6.0",
    "eslint-plugin-import": "^2.22.0",
    "typescript": "^3.8.0",
    "firebase-functions-test": "^0.2.0"
  },
  "private": true
}

Error: There was an error reading functions\package.json:

 functions\lib\index.js does not exist, can't deploy Cloud Functions

**Comment by AviadKlein10** [comment]
Have the same problem:

"Error: There was an error reading functions\package.json:

functions\lib\index.js does not exist, can't deploy Cloud Functions"

Nothing is working please help!

**Comment by jayDesai89** [comment]
I am working on one my personal project just for learning, and I am trying to Host my app
Project frame-work : Angular 8
Below is my package.json file, 
<======================>
```
{
  "name": "demo-weather-app",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~8.2.14",
    "@angular/cdk": "~8.2.3",
    "@angular/common": "~8.2.14",
    "@angular/compiler": "~8.2.14",
    "@angular/core": "~8.2.14",
    "@angular/fire": "^6.1.4",
    "@angular/forms": "~8.2.14",
    "@angular/material": "^8.2.3",
    "@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/router": "~8.2.14",
    "angular-popper": "^2.0.1",
    "angularfire2": "^5.4.2",
    "bootstrap": "^4.4.1",
    "firebase": "^8.2.4",
    "hammerjs": "^2.0.8",
    "jquery": "^3.4.1",
    "ngx-google-places-autocomplete": "^2.0.4",
    "ngx-spinner": "^8.1.0",
    "rxjs": "~6.5.4",
    "tslib": "^1.10.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.803.22",
    "@angular/cli": "~8.3.22",
    "@angular/compiler-cli": "~8.2.14",
    "@angular/language-service": "~8.2.14",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.5.3"
  }
}
```

<======================>
Upon `firebase init`    I am selecting   =>  Hosting: Configure and deploy Firebase Hosting sites
Upon `firebase deploy` I am getting following error : 

Error: There was an error reading functions\package.json:

 functions\lib\index.js does not exist, can't deploy Cloud Functions

 What should I do ? Please Help

**Comment by wayoalamos** [comment]
JUST SOLVED THIS AND FOUND WHAT I THINK IS A BUG
The g cloud function does not support the "lib" name for the folder that contains your compiled js

MY SOLUTION:
My env:
[Nodejs16 - I dont think it matters the version]
[Typescript ^4.0.0  - I dont think it matters the version, but it has to be on typescript ]

Edit package.json file .. edit 
`"main": "lib/index.js",` 
for 
`"main": "blablabla/index.js",`  ,

Then, to be consistent, go to your tsconfig.json file and edit  
`"outDir": "blablabla", `  ,

Also if you are using a github action, make sure you add  `source_dir: 'functions'` in the with statement.

**Comment by JanieHuang** [comment]
I feel silly about this one, so for anyone stuck on this and for some reason none of the above works: 

See what package --debug flag is using. I found it was using the nextjs package.json, and not the cloud functions folder package.json. 

I checked the firebase.json and realized under "functions" after i initialized there's a section where it says: 

```
  "functions": [
    {
      "source": ".",
      "codebase": "default",
      "runtime": "nodejs16",
      "ignore": [
        ".firebase/**",
        ".firebaserc",
        "firebase.json",
        "**/node_modules/**",
        "**/public/**"
      ]
    },
        {
      "source": "functions",
      "predeploy": [
        "npm install",
        "npm run build"
      ],
      "codebase": "functions",
      "runtime": "nodejs16",
      "ignore": [
        ".firebase/**",
        ".firebaserc",
        "firebase.json",
        "**/node_modules/**",
        "**/public/**"
      ]
    }
  ]
 ```
Remove the first one, so it should now look like this: 

```
  "functions": [
        {
      "source": "functions",
      "predeploy": [
        "npm install",
        "npm run build"
      ],
      "codebase": "functions",
      "runtime": "nodejs16",
      "ignore": [
        ".firebase/**",
        ".firebaserc",
        "firebase.json",
        "**/node_modules/**",
        "**/public/**"
      ]
    }
  ]
 ```

absolute silly mistake on my part. Hopefully someone else isn't making the same

**Comment by OskarGroth** [comment]
Here's how I resolved this:

I was importing files from other parts of the parent dir (types located in a ../shared dir). This caused my build folder to append `functions/src` subdirectories, `lib/myBuiltFiles` became `lib/firebase/src/myBuiltFiles`.

So I updated my package.json to say `"main": "lib/functions/src/index.js",`, but the error remained.

Then I found the issue, I had the following ignore in my firebase.json:

```
      "ignore": [
        "**/node_modules",
        ".git",
        "**/src"
      ],
```

This was causing everything under lib/functions/src to be ignored. Basically my whole built app was never uploaded.
After changing the ignore to be `./src` instead, the issue disappeared.

**Comment by TheNemus** [comment]
> JUST SOLVED THIS AND FOUND WHAT I THINK IS A BUG The g cloud function does not support the "lib" name for the folder that contains your compiled js
> 
> MY SOLUTION: My env: [Nodejs16 - I dont think it matters the version] [Typescript ^4.0.0 - I dont think it matters the version, but it has to be on typescript ]
> 
> Edit package.json file .. edit `"main": "lib/index.js",` for `"main": "blablabla/index.js",` ,
> 
> Then, to be consistent, go to your tsconfig.json file and edit `"outDir": "blablabla", ` ,
> 
> Also if you are using a github action, make sure you add `source_dir: 'functions'` in the with statement.

**that's exactly my issue. Please solve thig bug**
