### ISSUE TITLE
Error: start firebase emulators 

### ISSUE THREAD

**Issue by danieljancar** [firebase/firebase-tools#6320]
### [REQUIRED] Environment info

**firebase-tools:**

11.28.0

**Platform:**

macOS Ventura, v13.2.1

### [REQUIRED] Test case

When trying to emulate firebase features locally, I get an error where the progress bar for downloading `cloud-firestore-emulator-v1.16.2.jar` is stuck on 99% and not finish downloading.

### [REQUIRED] Steps to reproduce

To try and reproduce the error paste following command into your local firebase project.

```bash
cd functions && npm run build && cd .. && firebase emulators:start --import .local.data
```

After that if everything works it should successfully setup and start your emulators, otherwise you get the same error like me where the download for the above mentioned file won't finish.

### [REQUIRED] Expected behavior

I expected the command to run succesfully and setup/start my local firebase emulators.

### [REQUIRED] Actual behavior

```bash
npm run emulate-dev --debug

> functions@1.0.0 emulate-dev
> cd functions && npm run build && cd .. && firebase emulators:start --import .local.data


> build
> tsc

i  emulators: Starting emulators: auth, functions, firestore, hosting
⚠  hosting: Hosting Emulator unable to start on port 5000, starting on 5002 instead.
⚠  functions: The following emulators are not running, calls to these services from the Functions emulator will affect production: database, pubsub, storage
i  firestore: Importing data from /Users/LU16001/Documents/twenty-one/applications/personalverein/.local.data/firestore_export/firestore_export.overall_export_metadata
i  firestore: downloading cloud-firestore-emulator-v1.18.1.jar...
Progress: ==================================================================================================================================================================================> (99% of 65MB)
```

**Comment by aalej** [comment]
Hi @danieljancar, from what I can tell, the key issue here is that you are unable to download the `cloud-firestore-emulator-v1.18.1.jar` when starting the Firebase Emulator. I tried to reproduce this issue based on the information you provided, but no issues were raised when downloading the emulator.

Could you try updating to the latest version of `firebase-tools` which is currently v12.5.2, then run `firebase setup:emulators:firestore --debug` to download the Firestore Emulator? Share with us your `firebase-debug.log` file as it contains a detailed log that we can use to check what caused the issue. Please remove any personal identifiable information(PII) before sharing the file. Thanks!
