### ISSUE TITLE
Unable to deploy with VPC from external shared project

### ISSUE THREAD

**Issue by steveoh** [firebase/firebase-tools#6327]
### [REQUIRED] Environment info

**firebase-tools:** 12.5.2

**Platform:** macos

### [REQUIRED] Test case

Trying to use a shared vpc from a different project with `.env` and

```
FUNCTION_VPC="projects/shared/locations/us-central1/connectors/shared"
```

```js
const vpc = params.defineString('FUNCTION_VPC');
setGlobalOptions({
  vpcConnector: vpc
});
```

### [REQUIRED] Steps to reproduce

Try to deploy with these values and firebase tools mutates the `vpcConnector` string to an invalid value.

```
functions: HTTP Error: 400, Could not update Cloud Run service projects/my-project/locations/us-central1/services/function. spec.template.metadata.annotations: Expected a VPC access connector name like projects/*/locations/*/connectors/*, but obtained projects/not-shared-project/locations/us-central1/connectors/{{the full value of the FUNCTION_VPC}}
```

I assume the issue is around https://github.com/firebase/firebase-tools/blob/09c8d88ff5f1b4c4e617064c7da729b2301d905b/src/deploy/functions/runtimes/node/parseTriggers.ts#L502-L514

But my connector has a `/` in it so it shouldn't get modified. I wonder if it has to do with the `Expression<string>` type that has a `.value()` not being invoked or something until later? Or maybe the `/` is encoded when read from the environment file?

### [REQUIRED] Expected behavior

The VPC value I specify is used

### [REQUIRED] Actual behavior

The string is mutated and the deployment fails.

**Comment by thomasmburke** [comment]
Another reference to the connector in the source: https://github.com/firebase/firebase-tools/blob/09c8d88ff5f1b4c4e617064c7da729b2301d905b/src/deploy/functions/build.ts#L496-L500

**Comment by steveoh** [comment]
all of the connector building strings are protected by the `/` include but somehow I am getting through and it's getting appended. How is that possible?

**Comment by thomasmburke** [comment]
does the `--debug` potentially log the values of `.env` ?

**Comment by steveoh** [comment]
i'm stepping through my node_modules and found this which implies it doesn't know the value yet and hasn't expanded the value so it doesn't have the `/` and why it gets appended incorrectly. It's resolving too late.

![image](https://github.com/firebase/firebase-tools/assets/325813/c12d97e6-ad8d-47eb-a834-2857686854cd)

**Comment by steveoh** [comment]
I'm happy to contribute that as a PR if you think it is a good solution?

**Comment by thomasmburke** [comment]
Not a maintainer of the repo - so don't have an in depth understanding of how param changes could impact other situations. You'd definitely get feedback you are looking for on a PR, just follow [the contributing guide](https://github.com/firebase/firebase-tools/blob/09c8d88ff5f1b4c4e617064c7da729b2301d905b/CONTRIBUTING.md)

**Comment by steveoh** [comment]
Ok opened a PR to see the testing results as I don't have this repo checked out and cloned. Curious to see if this causes any failures.
