### ISSUE TITLE
Firebase login doesn't work with Azure web based console

### ISSUE THREAD

**Issue by jerryjeremiah** [firebase/firebase-tools#636]
I have installed the quickstart messaging app on a azure web site.
I have used the web based console to install firebase-tools.
Then I run firebase login:ci --interactive --no-localhost
It gives me the URL which I used to create the authorization code.
But it doesn't wait for me to enter the authorization code.
It prints the following and then drops back to the prompt:
? Paste authorization code here: [33D[33C
I am sure it is because the console isn't really as interactive as it needs to be.
Can I pass the authorization code on the command line somehow?
Or is there a way to make the firebase thing work with the Azure web based console?

Thanks,

Jerry

**Comment by mbleigh** [comment]
I'm not familiar with the Azure web console. If you're providing `--no-localhost` and the shell doesn't allow you to do what needs to be done, I think that environment will be unsupported for the moment. I'd encourage you to raise the issue with Azure to see if they have suggestions or workarounds. If there's something it seems like we can do, feel free to re-open.
