### ISSUE TITLE
Emulator breaks Next.js+Tailwind

### ISSUE THREAD

**Issue by sqrrrl** [firebase/firebase-tools#6378]
### [REQUIRED] Environment info

**firebase-tools:**

12.5.4

**Platform:**
ChromeOS/Linux

### [REQUIRED] Test case

See steps to reproduce. Can be recreated with firebase init + create-next-app.

### [REQUIRED] Steps to reproduce

- Init a new firebase directory, defaults for everything except enabling web framework support. Init w/Next.js
- Delete the default next project (rm -rf hosting)
- Run npx create-next-app@latest, set project name to hosting, defaults for everything (should default to tailwind)
- Run firebase emulators:start --project demo-x
- Open http://localhost:5000

### [REQUIRED] Expected behavior

Site renders correctly

### [REQUIRED] Actual behavior

Site loads, but styling is incorrect

Kill the emulator
cd hosting
npm run dev

open http://localhost:3000 to view expected results

Appears that postcss/tailwind simply isn't processing the sources when launched through the emulator.

**Comment by sqrrrl** [comment]
Looks like it's because firebase-tools is starting it as a custom server to control the host/port, but that ends up bypassing webpack per https://nextjs.org/docs/pages/building-your-application/configuring/custom-server

Not sure how deploy handles things, but assuming deploys support the normal build chain, thoughts on changing the emulator to run as a separate process? E.g. `next dev -H <host> -p <port>` would still use the emulator config but (hopefully) would allow next to run it's normal tool chain.

**Comment by cholmboe** [comment]
I got the same issue

**Comment by leoortizz** [comment]
@sqrrrl I tried but could not reproduce this issue with the latest Next.js with Tailwind and the latest version of firebase-tools. If you can provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), please share it so that we can replicate the issue on our end.

**Comment by julianraj** [comment]
It seems like the problem exists only if the firebase emulator is started from outside the NextJS directory. It works perfectly once you start the emulator from within the NextJS directory as suggested [here](https://github.com/firebase/firebase-tools/issues/5903#issuecomment-1568239576).

**Comment by KeunwooPark** [comment]
@julianraj 's solution worked for me. In addition, if the solution doesn't work, try deleting the `.next` directory. It worked for me.
