### ISSUE TITLE
Firebase tools doesn't deploy NextJs web framework for NextJs >=13.5.0

### ISSUE THREAD

**Issue by Ferido07** [firebase/firebase-tools#6382]
### [REQUIRED] Environment info

**firebase-tools:** 12.5.4

**Platform:** Ubuntu

### [REQUIRED] Test case

Deploying Next.js >= v13.5.0 to firebase doesn't complete due to error. All permission and account setup is correct.

### [REQUIRED] Steps to reproduce

- Setup firebase for nextjs deployment. 
- Deploy project using `firebase hosting:channel:deploy new-awesome-feature --expires 7d`

### [REQUIRED] Expected behavior

Deployment complete successfully

### [REQUIRED] Actual behavior

```
TypeError: Cannot destructure property 'customConfig' of '(intermediate value)(intermediate value)(intermediate value)' as it is null.
.
.
.  
The process '/usr/local/bin/npx' failed with exit code 2
Error: The process '/usr/local/bin/npx' failed with exit code 2
```

**Comment by devideo-dev** [comment]
same issues here

**Comment by Ferido07** [comment]
We just have to wait until the fix is reveiwed and merged.

**Comment by dsgriffin** [comment]
yep - confirming that attempting a v13.5 nextjs is blocked right now.

**Comment by aalej** [comment]
Hey everyone, thanks for raising this issue. I was able to replicate the behavior mentioned. When trying to deploy using Next.js version 13.5.x, an error is being raised.

Let me notify our engineering team about this issue so that they can take a look into this.  I’ll also be marking this issue as reproducible.

**Comment by Ferido07** [comment]
@aalej I have created a PR for the fix please try to approve it and see if it passes all the tests.

**Comment by gblue1223** [comment]
I fixed the issue with firebase-tools@12.6.2 and next@13.4.19.
```
$ npm i -g firebase-tools@12.6.2 && npm i next@13.4.19  && firebase deploy
```

**Comment by Ferido07** [comment]
@gblue1223 The issue is already fixed on firebase-tools@12.6.0 You can check here https://github.com/firebase/firebase-tools/blob/v12.6.0/CHANGELOG.md You can upgrade you next to v13.5

**Comment by ANTONINEUTRON** [comment]
I fixed this issue by installing  firebase-tools@12.6.2 while using next 14.0.4

**Comment by HubertRyanOfficial** [comment]
> I fixed this issue by installing firebase-tools@12.6.2 while using next 14.0.4

It worked for me
