### ISSUE TITLE
NextJS request times out whenever I send a request with request body

### ISSUE THREAD

**Issue by peetya** [firebase/firebase-tools#6385]
### [REQUIRED] Environment info

**firebase-tools:** `12.5.4`

**Platform:** `macOS`

### [REQUIRED] Test case

```typescript
// src/app/api/test/route.ts
import { NextResponse } from 'next/server';

export async function POST(request: Request) {
    const res = await request.json()
    return NextResponse.json({ res })
}
```

### [REQUIRED] Steps to reproduce

1. Deploy the next.js application to Firebase using `firebase deploy`
2. Call the API with any request data (e.g. `curl --request POST --location 'http://<URL>/api/test' --header 'Content-Type: application/json' -- data '{}'`)

### [REQUIRED] Expected behavior

I expect to get back the response.

### [REQUIRED] Actual behavior

The call times out (`408 Request Timeout`). I experience this issue only when I send request data. If I do a simple POST request without any request data, it works fine.

### Additional info
- I tested locally by running `npm run dev` and it worked fine
- I tested locally with emulators by running `firebase emulators:start` and it worked fine
- I tested with Pages Router instead of App router, same outcome
- NextJS version: `13.4.12`

**Comment by dominicdev** [comment]
having same issue :(

**Comment by peetya** [comment]
FYI I tested now with the latest `firebase-tools` (`v12.6.1`) and I also updated NextJS to `13.5.3` and now I don't get timeout anymore.

I was facing a different issue, whenever I sent a request body, I got the following error: `TypeError: Response body object should not be disturbed or locked`

There is an ongoing discussion about this error, but I don't think it's related to `firebase-tools`: https://github.com/vercel/next.js/discussions/49524

After some experiments, I realized that this error happens only with the NextJS App Router, when I used the Pages Router, it worked fine.

So I would suggest that if someone is experiencing this issue, consider using Pages Router for your API endpoints instead of App Router.

**Comment by lansolo99** [comment]
I experienced the issue with Next 14 app router, and the only workaround I found so far is indeed using the page router (as suggested by @peetya ) to get my response on the client side (and to get this working with emulators for my part).
