### ISSUE TITLE
Auth, importing users with SHA512 hash is successful but fails with wrong password when logging in.

### ISSUE THREAD

**Issue by Dazza666** [firebase/firebase-tools#6386]
### [REQUIRED] Environment info

Firebase tools: 12.5.4
macOS

### [REQUIRED] Test case

For the last three days, I have been trying all possible avenues to attempt to import a user with a SHA512 hash into firebase.

I am convinced that there is a problem with it.

In our existing implementation of the hash calculation, a hash is calculated as follows in PHP for a given password:

```
function custom_hash($password, $salt) {
    $input = $password . $salt;
    $hash = $input;

    for ($i = 0; $i < 20; $i++) {
        $hash = hash('sha512', $hash);
    }

    return "$hash";
}

$password = "UnifiedDatabase";
$salt = "f756d4f36a6cefc92d05000335f582d7ee27f5fa";

$hash = custom_hash($password, $salt);
```

So, we add the salt to the password, then hash it 20 times.

For a given test user 'test@test.com' with a password of 'UnifiedDatabase' this generates a hash:

**295b878d69a34f821cb9fc5a754f38c92511f6f40ef93596556d4ae64b84fdd2df9290a1954ea6e133ca68545f5a26dd73bad8264b2faf5ad5f1851b44272d43**

The salt used is: 

**f756d4f36a6cefc92d05000335f582d7ee27f5fa**
 
I then create a users object containing the following information and save it as users.json:

```
{
  "users": [
    {
      "localId": "hashtest",
      "email": "test@test.com",
      "emailVerified": false,
      "passwordHash": "KVuHjWmjT4IcufxadU84ySUR9vQO+TWWVW1K5kuE/dLfkpChlU6m4TPKaFRfWibdc7rYJksvr1rV8YUbRCctQw==",
      "salt": "Zjc1NmQ0ZjM2YTZjZWZjOTJkMDUwMDAzMzVmNTgyZDdlZTI3ZjVmYQ=="
    }
  ]
}
```
 
Note, that the 'hexed' hash has been unhexed first before being converted to base64, but I have also attempted to input the hex value converted to base64 as is with no luck
The salt has been converted straight from 'f756d4f36a6cefc92d05000335f582d7ee27f5fa' to base 64

I ran the following command in mac os terminal to achieve this:

`echo 295b878d69a34f821cb9fc5a754f38c92511f6f40ef93596556d4ae64b84fdd2df9290a1954ea6e133ca68545f5a26dd73bad8264b2faf5ad5f1851b44272d43 | xxd -r -p | openssl base64`

but also verified the output with other methods

Finally, the command im using to import is:

`firebase auth:import users.json --hash-algo=SHA512 --rounds=20 --hash-input-order=PASSWORD_FIRST`

Other potentially useful information - 

Separately, I created a BCRYPT hash and then attempted to import this into firebase, and it did work - so I believe the process to import and log in im following is correct.

I read in a old issue from 2020 (https://github.com/firebase/firebase-admin-node/issues/792) that firebase only supported salt first, but I believe that this has been improved since then as the parameter --hash-input-order now exists in the CLI, however this issue is regarding the node implementation which didn't contain --hash-input-order and still doesn't appear to...Regardless performing the salt first did not make it work either.

### [REQUIRED] Steps to reproduce

import:

```
{
  "users": [
    {
      "localId": "hashtest",
      "email": "test@test.com",
      "emailVerified": false,
      "passwordHash": "KVuHjWmjT4IcufxadU84ySUR9vQO+TWWVW1K5kuE/dLfkpChlU6m4TPKaFRfWibdc7rYJksvr1rV8YUbRCctQw==",
      "salt": "Zjc1NmQ0ZjM2YTZjZWZjOTJkMDUwMDAzMzVmNTgyZDdlZTI3ZjVmYQ=="
    }
  ]
}
```

via:

`firebase auth:import users.json --hash-algo=SHA512 --rounds=20 --hash-input-order=PASSWORD_FIRST`

Then try to log in with:

test@test.com
UnifiedDatabase

### [REQUIRED] Expected behavior

When logging in for the user test@test.com / UnifiedDatabase it does not return wrong password and successfully logs in

### [REQUIRED] Actual behavior

When logging in for the user test@test.com / UnifiedDatabase it returns:

Error logging in: auth/wrong-password Firebase: The password is invalid or the user does not have a password. (auth/wrong-password)

**Comment by joehan** [comment]
Hey @Dazza666, sorry that you're running into issues here. Unfortunately, I think you need to reach out to Firebase support for assistance here (https://firebase.google.com/support/troubleshooter/contact). 

`auth import` is a pretty thin wrapper - it basically just reads the options you provide, reads the users.json file, does some light validation, and packages those together into API calls to Firebase Auth. I sanity checked the code path that does this (https://github.com/firebase/firebase-tools/blob/master/src/accountImporter.ts#L303), and it seems like its passing everything along correctly.

My best guess is that there is some minor difference between your PHP hash calculation and the one Firebase Auth does on the backend. Since that calculation is not implemented in this repo, I can't do much to help debug further - however, Firebase Support can get this to people who can.
