### ISSUE TITLE
Scrypt library is not compliant with standards - exported users cannot be verified on Golang scrypt implementation

### ISSUE THREAD

**Issue by aarti** [firebase/firebase-tools#639]
### Version info
3.17.3

### Steps to reproduce

firebase --project $PROJECT_ID  auth:export $ACCT_OUT_FILE

### Expected behavior

Pick my user's password_hash and salt, use Go Scrypt library to create key 
https://godoc.org/golang.org/x/crypto/scrypt
`dk, err := scrypt.Key([]byte("mypassword"), salt, 16384, 8, 1, 64)`
Compare hashes to verify 
`subtle.ConstantTimeCompare(password_hash, dk) == 1`

returns false

### Actual behavior

Scrypt encryption should follow RFC standards and work with Go's implementation of Scrypt.

**Comment by aarti** [comment]
Related issue https://github.com/firebase/firebase-tools/issues/409 for additional discussion

**Comment by mbleigh** [comment]
As discussed in #409 the Google implementation of scrypt used by Firebase will be open-sourced in the future. In the meantime, this is an issue best dealt with by filing an issue with [Firebase Support](https://firebase.google.com/support/) as there is nothing to act upon in the CLI at this time.

**Comment by kmcnellis** [comment]
We just open sourced Firebase's version of scrypt so that you can do your own password verification. You can check it out at github.com/firebase/scrypt.
