### ISSUE TITLE
firebase-debug  ui-debug

### ISSUE THREAD

**Issue by ruanperera** [firebase/firebase-tools#6396]
[database-debug.log](https://github.com/firebase/firebase-tools/files/12706137/database-debug.log)
[firebase-debug.log](https://github.com/firebase/firebase-tools/files/12706138/firebase-debug.log)
[ui-debug.log](https://github.com/firebase/firebase-tools/files/12706139/ui-debug.log)

### [REQUIRED] Environment info

**firebase-tools:**

**Platform:**

**Comment by aalej** [comment]
Hi @ruanperera. I’m not sure what the exact issue here is, also had a look into the logs you provided and there doesn't seem to be any errors being raised. Without a clear description of the issue, I don’t think there is much we could do here. 

Could you please file a new issue following the provided template for issue reports and provide a clear description of the issue you’re encountering? For now, I’m going to close this issue.
