### ISSUE TITLE
Error: double-loading config "/Users/gokhanyordem/.cache/firebase/runtime/npmrc" as "global", previously loaded as "user" at Config.#loadObject (/snapshot/firepit/node_modules/npm/node_modules/@npmcli/config/lib/index.js:571:13) at /snapshot/firepit/node_modules/npm/node_modules/@npmcli/config/lib/index.js:617:31 at async Config.#loadFile (/snapshot/firepit/node_modules/npm/node_modules/@npmcli/config/lib/index.js:616:5) at async Config.load (/snapshot/firepit/node_modules/npm/node_modules/@npmcli/config/lib/index.js:287:5) at async Npm.#load (/snapshot/firepit/node_modules/npm/lib/npm.js:195:5) at async /snapshot/firepit/node_modules/npm/lib/cli-entry.js:40:5  NPM install failed, continuing with Firebase initialization... please help me with this

### ISSUE THREAD

**Issue by gkhnyrdm** [firebase/firebase-tools#6399]
### [REQUIRED] Environment info

**firebase-tools:**

**Platform:**

**Comment by gkhnyrdm** [comment]
When i started 'firebase init functions' and i choose the project at firebase and then i get this isse

**Comment by aalej** [comment]
Hi @gkhnyrdm, I understand that you’re encountering an issue here with configuring Firebase into your directory. For us to be able to start our initial investigation, we would need sufficient information about your issue. Could you please file a new issue and specify the details using the provided template? I'm going to close this for now.
