### ISSUE TITLE
Dynamic routing not working in Nextjs when deploy to firebase hosting

### ISSUE THREAD

**Issue by qaws5503** [firebase/firebase-tools#6403]
### [REQUIRED] Environment info

**firebase-tools: 12.5.4**

**Platform: macOS**
**Framework: Next.js 13.4.7**

I'm using page route.

My firebase.json
```
{
  "hosting": {
    "source": ".",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "frameworksBackend": {
      "region": "asia-east1"
    }
  }
}
```

### [REQUIRED] Test case

Just create a nextjs project and use a dynamic route.

### [REQUIRED] Steps to reproduce

1. create a nextjs project
2. create a new file path test/[id]/index.tsx
3. deploy to firebase hosting
4. Open the url https://your.domain.com/test/randomId

### [REQUIRED] Expected behavior

Can handle dynamic route properly.

### [REQUIRED] Actual behavior

All works fine in simulator when using `firebase emulators:start`. And successfully deploy to firebase hosting.

Static pages works fine, but when open the dynamic route endpoint, will encounter problem.

#### Reproduce

Below is the log of the SSR function which was auto created when deploying.

This is the error in the reproduce project
```
The request was not authenticated. Either allow unauthenticated invocations or set the proper Authorization header. Read more at https://cloud.google.com/run/docs/securing/authenticating Additional troubleshooting documentation can be found at: https://cloud.google.com/run/docs/troubleshooting#unauthorized-client
```

And returns the follow message to front-end
```
Error: Forbidden
Your client does not have permission to get URL /test/dsa from this server.
```

#### Original Project

Below is the error in my original project, it has a lot of deps.
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'Firebase' imported from /workspace/.next/server/pages/_app.js
    at new NodeError (node:internal/errors:405:5)
    at packageResolve (node:internal/modules/esm/resolve:887:9)
    at moduleResolve (node:internal/modules/esm/resolve:936:20)
    at defaultResolve (node:internal/modules/esm/resolve:1129:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:835:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ESMLoader.import (node:internal/modules/esm/loader:524:22)
    at importModuleDynamically (node:internal/modules/cjs/loader:1188:29)
    at importModuleDynamicallyWrapper (node:internal/vm/module:429:21) {
      code: 'ERR_MODULE_NOT_FOUND'
    }
```

And return the message `Internal Server Error` to front-end.

It's weird that two of them return different error.
But still seems to have a bug with dynamic route.

I've tried using gerServerSideProps still can't serve a dynamic route. And beside of this problem with dynamic route.

All undefined pages will encounter the same error above, it should return nextjs 404 page instead. So I think this is related to firebase hosting.

**Comment by zaxonus** [comment]
I am facing a similar issue (https://stackoverflow.com/questions/77936270/nextjs-dynamic-links-firebase) though I have firebase-tools version 13.1.0. Do you have any suggestion ?

**Comment by qaws5503** [comment]
You don't need to set rewrite for dynamic route. Just let the `firebase.json` file as same as default and firebase will do the magic. Make sure you followed the [instruction](https://firebase.google.com/docs/hosting/frameworks/nextjs).

**Comment by guivinson** [comment]
I encounter the same issue (403 Forbidden): on dynamic routes (/[projectId]/page.tsx) which are not using getServerSideProps
Working in dev in the emulator, not anymore once deployed

ubuntu 22-04
nextjs 13.4.7
firebase -V : 13.0.2

firebase.json
```json
{
  "hosting": {
    "source": ".",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "frameworksBackend": {
      "region": "europe-west1",
      "minInstances": 0,
      "maxInstances": 1
    }
  },
  "emulators": {
    "auth": {
      "port": 9099
    },
    "hosting": {
      "port": 5000
    },
    "ui": {
      "enabled": true
    },
    "singleProjectMode": true
  }
}
```

next.config.js
```ts
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
}

module.exports = nextConfig
```
