### ISSUE TITLE
Error: HTTP Error: 403, Unknown Error

### ISSUE THREAD

**Issue by kimown** [firebase/firebase-tools#641]
### Version info

3.17.4

### Steps to reproduce

OS X 10.12.6
node -v
```
v8.9.3
```
tree .
``` tree .
.
|-- firebase.json
`-- public
    `-- index.html

1 directory, 2 files
```

ls -a
``` ls -a
.firebaserc	firebase.json	public
```
Then I run `firebase deploy`,

![image](https://user-images.githubusercontent.com/7932380/35483562-97d06a20-047e-11e8-9a66-ffb69ed3de04.png)

**Comment by mbleigh** [comment]
Please run with --debug and provide the results. Do you have access to the
fir-demo-project project?

**Comment by kimown** [comment]
@mbleigh 

```
=== Deploying to 'fir-demo-project'...

i  deploying hosting
i  hosting: preparing public directory for upload...
[2018-01-29T01:53:16.132Z] >>> HTTP REQUEST PUT https://deploy.firebase.com/v1/hosting/fir-demo-project/uploads/-L3zb_9i-Z15MlRlbtCs?fileCount=1&message=  
  
 Mon Jan 29 2018 09:53:16 GMT+0800 (CST)
[2018-01-29T01:53:17.738Z] <<< HTTP RESPONSE 403 server=nginx, date=Mon, 29 Jan 2018 01:53:17 GMT, content-type=application/json; charset=utf-8, content-length=89, connection=close, access-control-allow-origin=*, access-control-allow-methods=GET, PUT, POST, DELETE, OPTIONS, strict-transport-security=max-age=31556926; includeSubDomains; preload, x-content-type-options=nosniff
[2018-01-29T01:53:17.738Z] <<< HTTP RESPONSE BODY code=403, message=The caller does not have permission, status=PERMISSION_DENIED

Error: HTTP Error: 403, Unknown Error
[2018-01-29T01:53:17.741Z] Error Context: {
  "body": {
    "code": 403,
    "message": "The caller does not have permission",
    "status": "PERMISSION_DENIED",
    "error": {
      "message": "Unknown Error"
    }
  },
  "response": {
    "statusCode": 403,
    "body": {
      "code": 403,
      "message": "The caller does not have permission",
      "status": "PERMISSION_DENIED",
      "error": {
        "message": "Unknown Error"
      }
    },
    "headers": {
      "server": "nginx",
      "date": "Mon, 29 Jan 2018 01:53:17 GMT",
      "content-type": "application/json; charset=utf-8",
      "content-length": "89",
      "connection": "close",
      "access-control-allow-origin": "*",
      "access-control-allow-methods": "GET, PUT, POST, DELETE, OPTIONS",
      "strict-transport-security": "max-age=31556926; includeSubDomains; preload",
      "x-content-type-options": "nosniff"
    },
    "request": {
      "uri": {
        "protocol": "https:",
        "slashes": true,
        "auth": null,
        "host": "deploy.firebase.com",
        "port": 443,
        "hostname": "deploy.firebase.com",
        "hash": null,
        "search": "?fileCount=1&message=",
        "query": "fileCount=1&message=",
        "pathname": "/v1/hosting/fir-demo-project/uploads/-L3zb_9i-Z15MlRlbtCs",
        "path": "/v1/hosting/fir-demo-project/uploads/-L3zb_9i-Z15MlRlbtCs?fileCount=1&message=",
        "href": "https://deploy.firebase.com/v1/hosting/fir-demo-project/uploads/-L3zb_9i-Z15MlRlbtCs?fileCount=1&message="
      },
      "method": "PUT"
    }
  }
}
```

**Comment by mbleigh** [comment]
Yes, you won't be able to deploy to a project you only have "viewer" permission on. You should be able to deploy by doing:

    firebase use example-6730b
    firebase deploy

**Comment by kimown** [comment]
@mbleigh 

Thanks ^_^

**Comment by jameskip** [comment]
I had a similar issue. I was actually signed into a different Firebase account in my CLI. After running `firebase logout` and `firebase login` with the correct Firebase account it worked fine.

**Comment by dinhnhat0401** [comment]
@mbleigh 's comment helped me to figure out what happened.
I have already logged in with firebase but using another account.
So I need to log out using: `firebase logout`
Then `firebase login` again with the appropriate account.
And after that, I want to use `firebase projects:list` to list up all projects belong to this user.

**Comment by jefelewis** [comment]
> I had a similar issue. I was actually signed into a different Firebase account in my CLI. After running `firebase logout` and `firebase login` with the correct Firebase account it worked fine.

This worked for me. Thank you!

**Comment by GeorgeShao** [comment]
Had the same issue, but restarting my computer then doing `firebase login` worked for me. Thanks!

**Comment by SvenWritesCode** [comment]
Just retrying worked for me 🤷

**Comment by KillDozerX2** [comment]
I had the same issue. But I had actually not provisioned Functions in the Management Console. All I had to do was go to the console > Cloud Functions and click on `Get Started` and finish the prompt.

**Comment by whalemare** [comment]
For my case was be little harder to find solution, but I did it:

Last day ago, I was rename typo in my project name (ex. from `my-prodject` to `my-project`)
After that, I trying to deploy functions, but it crashed all the time with errors described above. So here the fix:

`firebase use --clear` - for clearing all project aliases
`firebase use --add` - for selection project in dropdown inside CLI

Select your project and type something for create alias, `prod` for example

After that, file `.firebaserc` was be regenerated and you can `firebase deploy` (I need rerun in several times)

**Comment by ranajahanzaib** [comment]
In my case, it was because the **Firebase CLI** didn't have the necessary permissions to access the repo in the GitHub org. This is required to enable CI/CD with GitHub Actions. In order for Firebase CLI to store secrets to repo/org, you must grant GitHub org access. You can do so by going to the **Authorized OAuth Apps** tab in [Settings/Applications](https://github.com/settings/connections/applications/) and granting permission there.
