### ISSUE TITLE
Webframeworks [NextJS] - Failed to deploy API Routes with App Folder

### ISSUE THREAD

**Issue by ablbol** [firebase/firebase-tools#6413]
### [REQUIRED] Environment info

**firebase-tools:** 12.6.1

**Platform:** Nextjs 13.5.3

### [REQUIRED] Test case

Create a Nextjs 13 project with API route and try to deploy to Firebase hosting.  The API will not deploy. No cloud function was created for the API route.

### [REQUIRED] Steps to reproduce
I have a Nextjs website with an API route (app/api/revalidate/route.ts).  When deploying the website using Firebase Hosting, the API is not deployed.

### [REQUIRED] Expected behavior

I expect the API route to be deployed as a cloud function. (api/revalidate)

### [REQUIRED] Actual behavior
API route was not deploy.

[debug.txt](https://github.com/firebase/firebase-tools/files/12746698/debug.txt)

**Comment by dominicdev** [comment]
having this problem too  any updates?

**Comment by ceefour** [comment]
I have this problem too, please support App Router.

**Comment by leoortizz** [comment]
@ablbol per the logs you provided the Cloud Function is deployed successfully. The `/api/revalidate` route is working here: https://oolfa-prod.web.app/api/revalidate. What's exactly not working in your endpoint?

Note that recently some fixes were released for Next.js server-side features:
- Mainly the fix to this issue could have fixed your issues: #6308
- #6188 
- #6133
- #6071

Can you try a new deploy with the latest `firebase-tools` version(`npm i -g firebase-tools@latest`) and report back here? CC @dominicdev @ceefour

**Comment by ceefour** [comment]
I'm mistaken, this is about API Routes, while my problem is about App Router. I will create a different issue.
