### ISSUE TITLE
Next js i18n redirection is not working

### ISSUE THREAD

**Issue by lucasoz** [firebase/firebase-tools#6415]
### [REQUIRED] Environment info

**firebase-tools:** 12.6.1

**Platform:** Ubuntu

### [REQUIRED] Test case

I'm deploying the my next js app (next 13.5.3) in firebase. My app is very simple, I added to app the page router i18n for internazionatization based on routes for example `/en` when user language is english. When I deploy the app and index the www.your-domain.com page with my browser language in english the app returns the / page instead of /en page. I try in local and it works perfectly.

BTW: I try to return a redirect directly from getServerSideProps to another page for example /to-do but I had another error. I mean that is something related to the next js 13 routing with pages directory

Index.tsx --->
```tsx
export async function getServerSideProps(context: GetServerSidePropsContext) {
  return {
    redirect: {
      destination: `/to-do`,
      permanent: false,
    },
  };
}
```

**Error: Forbidden
Your client does not have permission to get URL / from this server.**

### [REQUIRED] Steps to reproduce

1. npx create-next-app@latest
What is your project named? my-app
Would you like to use TypeScript? Yes
Would you like to use ESLint? Yes
Would you like to use Tailwind CSS? Yes
Would you like to use `src/` directory? No
Would you like to use App Router? (recommended) No
Would you like to customize the default import alias (@/*)? Yes
What import alias would you like configured? @/*
2. Add the following in the `next.config.js` file bellow `reactStrictMode`
```js
i18n: {
    locales: ["en", "es"],
    defaultLocale: "es",
},
```
3. Deploy on firebase
4. Set your browser language in english
5. Index your-domain.com

### [REQUIRED] Expected behavior

Browser should redirect to '/en'

### [REQUIRED] Actual behavior

Browser is not redirecting, I'm getting `your-domain.com`

**Comment by leoortizz** [comment]
Hey @lucasoz! Thanks for the detailed steps to reproduce. Firebase i18n works through rewrites: https://firebase.google.com/docs/hosting/i18n-rewrites

I tested it [in this project](https://github.com/leoortizz/nextjs-firebase-i18n-test) following the steps you provided and found that even if the page is not redirecting to `/en`, the served content locale is `en`. You can check this through `html`'s element `lang` attribute.
