### ISSUE TITLE
How are people working around the broken `.env.local` functionality?

### ISSUE THREAD

**Issue by ekalosak** [firebase/firebase-tools#6417]
As reports are all over this project's issue tracker, I won't restate the error in detail. Briefly, the claim in the docs that you can [set development workstation environment variables using .env.local](https://firebase.google.com/docs/functions/config-env?gen=2nd#emulator_support) is false.

So, this is a question to the community: how are you working around this issue?

I've accidentally deployed using development values in `.env`, which was obviously bound to happen, so that's not really a workable solution. Thoughts?

**Comment by ekalosak** [comment]
For anyone else hunting this down, the `export function loadUserEnvs` responsible for loading `.env` and `.env.local` etc. is in `src/functions/env.ts` at `L361`.

I can't find an obvious error in the TypeScript. Hmm, maybe the environment variables are being loaded from `.env` elsewhere and this function is a red herring?

**Comment by ekalosak** [comment]
Ah. The variables from `.env.local` are loaded _after_ the `main.py` modules are loaded. So anything that consumes environment variables at load-time will only get those in `.env`; anything that consumes environment variables at execution-time will get the patches from the `.env.*` files.

Would have been nice to have this in the docs, but hopefully others who hit this hidden feature will be able to find this thread in the meantime.

**Comment by blidd-google** [comment]
Hi @ekalosak, thanks for your in-depth investigation of environment configuration. You are correct that environment variables defined in .env.local will be available at runtime, not load time. I'm gonna go ahead and close this issue, but will raise your suggestion with our docs team and recommend making this clarification for our users.
