### ISSUE TITLE
 fresh install on CentOS9: Unable to fetch the CLI MOTD and remote config.

### ISSUE THREAD

**Issue by chocobloc** [firebase/firebase-tools#6422]
12.6.1

CentOS 9
**Platform:**

### [REQUIRED] Test case
create CentOS 'fresh' hetzner x86 instance;
Install nodejs:

$ sudo dnf install -y nodejs
$ node -v
   -> v16.20.10

install firebase-tools
$ npm install -g firebase-tools
$ firebase --version
   -> 12.6.1
$ firebase init
Error: Failed to authenticate, have you run firebase login?
⚠  Unable to fetch the CLI MOTD and remote config.

$ firebase login --no-localhost
i  Firebase optionally collects CLI and Emulator Suite usage and error reporting information to help improve our products. Data is collected in accordance with Google's privacy policy (https://policies.google.com/privacy) and is not used to identify you.

? Allow Firebase to collect CLI and Emulator Suite usage and error reporting information? (Y/n) ⚠  Unable to fetch the CLI MOTD and remote config.
 (...then I successfully logged in with my gmail account ... to continue:)

$ firebase init
     ######## #### ########  ######## ########     ###     ######  ########
     ##        ##  ##     ## ##       ##     ##  ##   ##  ##       ##
     ######    ##  ########  ######   ########  #########  ######  ######
     ##        ##  ##    ##  ##       ##     ## ##     ##       ## ##
     ##       #### ##     ## ######## ########  ##     ##  ######  ########

You're about to initialize a Firebase project in this directory:

  /app

Before we get started, keep in mind:

  * You are currently outside your home directory

? Which Firebase features do you want to set up for this directory? Press Space to select features, then Enter to confirm your choices.
(Press <space> to select, <a> to toggle all, <i> to invert selection, and <enter> to proceed)
❯◯ Realtime Database: Configure a security rules file for Realtime Database and (optionally) provision default instance
 ◯ Firestore: Configure security rules and indexes files for Firestore
 ◯ Functions: Configure a Cloud Functions directory and its files
 ◯ Hosting: Configure files for Firebase Hosting and (optionally) set up GitHub Action deploys
 ◯ Hosting: Set up GitHub Action deploys
 ◯ Storage: Configure a security rules file for Cloud Storage
 ◯ Emulators: Set up local emulators for Firebase products
(Move up and down to reveal more choices)⚠  Unable to fetch the CLI MOTD and remote config.

Choosing "Functions: Configure a Cloud Functions directory and its files"

=== Project Setup

First, let's associate this project directory with a Firebase project.
You can create multiple project aliases by running firebase use --add,
but for now we'll just set up a default project.

? Please select an option:
  Use an existing project
❯ Create a new project
  Add Firebase to an existing Google Cloud Platform project
  Don't set up a default project

=== Project Setup

First, let's associate this project directory with a Firebase project.
You can create multiple project aliases by running firebase use --add,
but for now we'll just set up a default project.

? Please select an option: Create a new project
i  If you want to create a project in a Google Cloud organization or folder, please use "firebase projects:create" instead, and return to this command when you've created the project.
? Please specify a unique project id (warning: cannot be modified afterward) [6-30 characters]:
 woundsolutionsprod
? What would you like to call your project? (defaults to your project ID) woundsolutionsprod
✖ Creating Google Cloud Platform project

Error: Failed to create project. See firebase-debug.log for more info.

[firebase-debug.log](https://github.com/firebase/firebase-tools/files/12777961/firebase-debug.log)

### [REQUIRED] Expected behavior

Being able to create a new firebase project

### [REQUIRED] Actual behavior

Unable to fetch the CLI MOTD and remote config.

**Comment by chocobloc** [comment]
FetchError: request to https://firebase-public.firebaseio.com/cli.json failed, reason: Client network socket disconnected before secure TLS connection was established;

Tried a curl on my cloud instance: {"cloudBuildErrorAfter":1594252800000,"cloudBuildWarnAfter":1590019200000,"defaultNode10After":1594252800000,"minVersion":"3.0.5","node8DeploysDisabledAfter":1613390400000,"node8RuntimeDisabledAfter":1615809600000,"node8WarnAfter":1600128000000}

**Comment by joehan** [comment]
Hey @chocobloc, sorry to see that you're running into issues.

This `Unable to fetch the CLI MOTD` message is just a warning - this is a best effort call & it failing won't affect the rest of the CLI. Looking at your debug logs, the real issue here is:
```
 POST https://cloudresourcemanager.googleapis.com/v1/projects 403
```
The logged in user doesn't have permissions to create a project. Are you able to create projects as that user on a different machine? Are you part of an organization?

**Comment by chocobloc** [comment]
Hello @joehan,thanks for coming back to me. I think that was a non-compatibility problem between firebase and node.js. I tried to update the ticket on .git but did no more find it. 
I tried the same with a fresh install, this time by using node.js 18.17.1 and firebase 8.4.1. That combo worked much better. 
Can you please close the corresponding ticket or educate me where to find it so I can comment and close it myself. Thanks in ***@***.***

    On Thursday, October 5, 2023 at 06:54:42 PM GMT+2, joehan ***@***.***> wrote:  
 
 


Hey @chocobloc, sorry to see that you're running into issues.

This Unable to fetch the CLI MOTD message is just a warning - this is a best effort call & it failing won't affect the rest of the CLI. Looking at your debug logs, the real issue here is:
 POST https://cloudresourcemanager.googleapis.com/v1/projects 403

The logged in user doesn't have permissions to create a project. Are you able to create projects as that user on a different machine? Are you part of an organization?
