### ISSUE TITLE
Error 403 on next js redirect SSR

### ISSUE THREAD

**Issue by lucasoz** [firebase/firebase-tools#6426]
### [REQUIRED] Environment info

**firebase-tools:** 12.6.1

**Platform:** Ubuntu

### [REQUIRED] Test case

Hi, I'm using next 13 with pages directory and I'm trying to use a simple redirection from a page to another with server side rendering and I'm getting a 403 error

![image](https://github.com/firebase/firebase-tools/assets/18173423/ac42a13c-6adf-46c5-9dfa-c290917c9645)

### [REQUIRED] Steps to reproduce

Create a next js 13 app with pages directory:

1. npx create-next-app@latest
What is your project named? my-app
Would you like to use TypeScript? Yes
Would you like to use ESLint? Yes
Would you like to use Tailwind CSS? Yes
Would you like to use src/ directory? No
Would you like to use App Router? (recommended) No
Would you like to customize the default import alias (@/)? Yes
What import alias would you like configured? @/

2. Create a folder `example` and a file index.tsx inside with the following:
```tsx
export function getServerSideProps() {
  return {
    redirect: {
      destination: "/",
      permanent: false,
    },
  };
}

export default function Index() {
  return <div>Example</div>;
}
```

3. Deploy with firebase hosting [https://firebase.google.com/docs/hosting/frameworks/nextjs?hl=es-419](url)
4. Enter your-domain.com/example` page in the browser

### [REQUIRED] Expected behavior

Redirection works

### [REQUIRED] Actual behavior

Redirection is getting a 403 error

**Comment by kevineleven** [comment]
The deployment creates any SSR code as a cloud function - I encountered this same issue and was able to work around it by updating my IAM settings for _both_ Cloud Functions _and_ Cloud Run.

https://cloud.google.com/functions/docs/securing/authenticating?&_ga=2.197954991.-1080258126.1678554131#authenticating_function_to_function_calls

https://cloud.google.com/run/docs/authenticating/public

Hope this helps.

**Comment by leoortizz** [comment]
Hey @lucasoz, as @kevineleven mentioned in the comment above, your Cloud Fuction(Next.js server) should be publicly accessible. It's public by default but your organization policy can change that. 

Please confirm if allowing public access fixes the issue for you.
