### ISSUE TITLE
Nextjs SSR functions broken - functions forward to 404 pages

### ISSUE THREAD

**Issue by deathg0d** [firebase/firebase-tools#6434]
### [REQUIRED] Environment info

**firebase-tools:** 12.6.2, 12.6.1, 12.6.0

**Platform:** Windows

### [REQUIRED] Test case

Any app with SSR capabilities

### [REQUIRED] Steps to reproduce

Create a simple app with SSR routes and deploy using firebase-tools version 12.6.0 or above. I personally tried with three versions, may be more are affected.

### [REQUIRED] Expected behavior

All SSR routes must be routed to Firebase cloud functions. Functions must be executed without error.

### [REQUIRED] Actual behavior

Routes ARE forwarded to functions. Functions execute without any error logs but all SSR routes are forwarded to 404 page.

-----
### Temporary emulator fix:
Downgrade firebase-tools to 12.5.2

After downgrading, functions work in emulators but not in Firebase deployed website.

Note: Some users might not even be able to deploy to Firebase due to this issue: https://github.com/firebase/firebase-tools/issues/6173 in 12.5.2. I had to manually go into this file `node_modules\firebase-tools\lib\frameworks\utils.js` and change `const NPM_ROOT_TIMEOUT_MILLIES = 2000;` to `const NPM_ROOT_TIMEOUT_MILLIES = 5000;` (based on https://github.com/firebase/firebase-tools/issues/6173#issuecomment-1723763941). This fix is of course only temporary. However, it doesn't matter because SSR functions are not working.

**Comment by deathg0d** [comment]
I did a little more digging into this. I opened google cloud console at https://console.cloud.google.com/, typed SSR in the search box. It shows me my SSR functions as a single cloud run service. Entered dashboard for this service and went to the revisions tab. It shows me a list of deployed versions of the SSR functions. Each revision has a `revision url` next to it. This url is different from the default hosting deploy url.

These urls are supposed to also host the deployed website, but these won't open just yet. So I went to Firebase console > authentication > settings > Authorized domains and added the latest revision url as the domain. After this step, the deployed website is viewable in this revision url. What's more - all SSR routes also work!

This leads me to believe that `firebase deploy` is unable to tie up SSR functions to the default Firebase domain?

**Comment by leoortizz** [comment]
Hey @deathg0d! Some fixes were done in the Next.js server since your last comment, are you still having this issue?

**Comment by deathg0d** [comment]
Hi @leoortizz I haven't been able to try it out yet. Will get to work on it next week.

**Comment by deathg0d** [comment]
@leoortizz Hi, I updated firebase-tools and deployed again. The complete project is unreachable. All requests timeout with the following message: "upstream request timeout". Even the index page isn't working anymore. I am on next@13.4.7 as this was the recommended version here: https://firebase.google.com/docs/hosting/frameworks/nextjs

Does the new firebase-tools update require a newer version of next?

**Comment by leoortizz** [comment]
@deathg0d thanks for testing. The latest version should work with Next.js 14. I tried a couple deployments and wasn't able to reproduce the timeout error.

Can you provide a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) so I can investigate further?

**Comment by deathg0d** [comment]
> @deathg0d thanks for testing. The latest version should work with Next.js 14. I tried a couple deployments and wasn't able to reproduce the timeout error.
> 
> Can you provide a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) so I can investigate further?

The timeout error was on next 13.4.7.

Currently I have updated to these versions:
"firebase": "10.7.1",
"firebase-admin": "11.11.1",
"next": "14.0.4",

dev dependencies:
"firebase-tools": "13.0.2",

But I am hitting this error: https://github.com/vercel/next.js/issues/50166#issuecomment-1870390227

I am trying to look into it right now. Do you know of this issue? Otherwise I will try to create a reproducible example.

**Comment by deathg0d** [comment]
> I see you're using `firebase-tools` as a dev dependency. Depending on how you run `firebase` your terminal won't use that version, but the global installed `firebase-tools` instead. Can you make sure you're running `npm install -g firebase-tools@latest` to get the latest version?
> 
> `firebase --version` will give you the version you're using.
> 
> The timeout error was fixed in this PR: [FirebaseExtended/firebase-framework-tools#122](https://github.com/FirebaseExtended/firebase-framework-tools/pull/122), which was released in [`firebase-frameworks v0.11.0`](https://github.com/FirebaseExtended/firebase-framework-tools/releases/tag/firebase-frameworks-v0.11.0). The new `firebase-frameworks` version is picked up automatically via the latest `firebase-tools`.

I do not have a globally installed firebase-tools, I generally use it like this:
```
.\node_modules\.bin\firebase --version
```
(returns `13.0.2`)
or to deploy:
```
.\node_modules\.bin\firebase deploy --only hosting --debug
```

I will try with the global install but not sure that would solve it. After updating to latest versions I am not hitting the timeout issue. My build is deployed, but I am hitting `500 Internal Server Error` on all routes.

Firebase error log:

```
}
]
'/workspace/node_modules/next/dist/server/next.js'
'/workspace/node_modules/next/dist/server/next-server.js',
'/workspace/node_modules/next/dist/server/require.js',
'/workspace/.next/server/app/page.js',
requireStack: [
code: 'MODULE_NOT_FOUND',
at t (/workspace/.next/server/webpack-runtime.js:1:143) {
at 68300 (/workspace/.next/server/chunks/203.js:78:11995)
at t (/workspace/.next/server/webpack-runtime.js:1:143)
at 25319 (/workspace/.next/server/app/page.js:1:852)
at require (node:internal/modules/cjs/helpers:119:18)
at mod.require (/workspace/node_modules/next/dist/server/require-hook.js:65:28)
at Module.require (node:internal/modules/cjs/loader:1143:19)
at Module._load (node:internal/modules/cjs/loader:922:27)
at /workspace/node_modules/next/dist/server/require-hook.js:55:36
at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
- /workspace/node_modules/next/dist/server/next.js
- /workspace/node_modules/next/dist/server/next-server.js
- /workspace/node_modules/next/dist/server/require.js
- /workspace/.next/server/app/page.js
Require stack:
⨯ Error: Cannot find module 'next/dist\client\components\static-generation-async-storage.external.js'
```

**Comment by deathg0d** [comment]
hi @leoortizz The error was apparently from this issue https://github.com/vercel/next.js/issues/58244 I am compiling from windows and therefore there was a path mismatch in linux environment. To solve this I installed [ubuntu on windows](https://ubuntu.com/tutorials/install-ubuntu-on-wsl2-on-windows-10#1-overview) and deployed to firebase from there. The errors went away and the project is now deployed.

However, I ran into another issue! Firebase admin doesn't seem to be working. All pages that require ssr authentication are now not working. I am trying to think of a way to debug this :/ 

versions:

"firebase": "10.7.1",
"firebase-admin": "11.11.0",
"next": "14.0.4",

"firebase-tools": "13.0.2",

**Comment by leoortizz** [comment]
I'm glad you figured out the issue and found the root cause.

If the topic that originated this issue is not an issue anymore, please open a new issue so we can investigate it.

> However, I ran into another issue! Firebase admin doesn't seem to be working. All pages that require ssr authentication are now not working. I am trying to think of a way to debug this :/

Can it be related to #6245, #6246 or #6247?

**Comment by leoortizz** [comment]
> I do not have a globally installed firebase-tools, I use it like this:
> 
> ```
> .\node_modules\.bin\firebase --version
> ```
> 
> (returns `13.0.2`) or to deploy:
> 
> ```
> .\node_modules\.bin\firebase deploy --only hosting --debug
> ```
> 
> I will try with the global install but not sure that would solve it. After updating to latest versions I am not hitting the timeout issue. My build is deployed, but I am hitting `500 Internal Server Error` on all routes.

it's fine then, the global install won't make a difference in this case

**Comment by deathg0d** [comment]
Hi @leoortizz I logged everything and I am actually getting this error in firebase console logs : `Auth error FirebaseAppError: The default Firebase app does not exist. Make sure you call initializeApp() before using any of the Firebase services.` This originates from my layout file that pulls user info on the server side. My layout file looks something like this:

```
import { firebaseAdmin } from "<path>/firebaseAdmin";
export default async function RootLayout({ children }) {
  // get user details serverside using firebaseAdmin:
  // const token = get token from cookies; <--- logs proper token in firebase console logs
  // const { uid, email } = await firebaseAdmin.auth().verifyIdToken(token); <--- this logs the auth error in firebase console logs
```

And my firebaseAdmin file looks like this:
```
import * as firebaseAdmin from "firebase-admin";
import serviceAccount from "<path>/firebase_secret.json";

if (firebaseAdmin.apps.length === 0) {
  console.log("Initiate app");
  firebaseAdmin.initializeApp({
    credential: firebaseAdmin.credential.cert(serviceAccount),
  });
}

export { firebaseAdmin };
```

I **have** called initializeApp(). This works perfectly in local development, only errors out when deployed to firebase.

Edit: I figured out what the issue is but may be I could use your help to handle it properly. So looks like the issue is `if (firebaseAdmin.apps.length === 0)` fails on firebase deployment. However, this is needed in local development otherwise the local compilation fails with: 
```
⨯ Error: The default Firebase app already exists. This means you called initializeApp() more than once without providing an app name as the second argument. In most cases you only need to call initializeApp() once. But if you do want to initialize multiple apps, pass a second argument to initializeApp() to give each app a unique name.
```

Could you please explain a bit why firebase deployment requires initializeApp to be triggered always and local development requires a check so that it doesn't get triggered again? New to firebase next deployment :(

**Comment by deathg0d** [comment]
As for this issue, to summarize, the following updates to the dependencies solved the issue for me:
"firebase": "10.7.1",
"firebase-admin": "11.11.0",
"next": "14.0.4",

devDependencies
"firebase-tools": "13.0.2",

(discussion above for 500 error)
