### ISSUE TITLE
Failed to generate token: secretOrPrivateKey must be an asymmetric key when using ES256

### ISSUE THREAD

**Issue by efraespada** [firebase/firebase-tools#6436]
### Environment info

**firebase-tools:** 11.21.0

**Platform:** macOS

### Test case

Create a basic firebase functions project. `firebase init` of functions. Include a function. 

```ts
// index.ts

exports.your_api_v2 = require('./api/v2/api/your_api_v2');
```

```ts
// your_api_v2.ts

import {onCall} from "firebase-functions/v2/https";

export const myCustomFunction = onCall({
    timeoutSeconds: 20,
}, async (): Promise<any> => {
    return {
        "response": "done"
    }
});
```

### Steps to reproduce

Deploy any function.

```bash
firebase deploy --only functions:your_api_v2
```

### Expected behavior

The deployment is fine.

### Actual behavior

Running command: npm --prefix "$RESOURCE_DIR" run build

> build
> tsc

✔  functions: Finished running predeploy script.
i  functions: preparing codebase default for deployment
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
i  artifactregistry: ensuring required API artifactregistry.googleapis.com is enabled...
✔  functions: required API cloudbuild.googleapis.com is enabled
✔  artifactregistry: required API artifactregistry.googleapis.com is enabled
✔  functions: required API cloudfunctions.googleapis.com is enabled

[2023-10-09T15:51:49.238Z] Building nodejs source
i  functions: Loading and analyzing source code for codebase default to determine what to deploy 
[2023-10-09T15:51:49.239Z] Could not find functions.yaml. Must use http discovery
[2023-10-09T15:51:49.274Z] Found firebase-functions binary at '/Users/efraespada/landa-workspace/landa-backend/functions/node_modules/.bin/firebase-functions'
Serving at port 8392

[2023-10-09T15:51:50.488Z] Got response code 400; body Failed to generate manifest from function source: VError: Failed to generate token: secretOrPrivateKey must be an asymmetric key when using ES256
shutdown requested via /__/quitquitquit

Error: Functions codebase could not be analyzed successfully. It may have a syntax or runtime error

**Comment by aalej** [comment]
Hi @efraespada, thanks for providing a detailed report. To ensure that `firebase-tools` has the latest updates and bug fixes, could you try updating to the latest version which is currently [v12.6.2](https://github.com/firebase/firebase-tools/releases/tag/v12.6.2), then redeploy your function using `firebase deploy --only functions:your_api_v2`? Is there any difference in the behavior when deploying?

**Comment by efraespada** [comment]
Sorry for the delay. The problem was caused by other dependency, but I had to downgrade the version for having valid logs for realizing where the problem was.

Logs output should be improved.
