### ISSUE TITLE
Splitting Functions into multiple files deploys all functions if only a single function has changed

### ISSUE THREAD

**Issue by imbradyboy** [firebase/firebase-tools#6444]
### [REQUIRED] Environment info

**firebase-tools:** 12.7.0

**Platform:** macOS

### [REQUIRED] Test case

If functions are split into multiple files and lazy loaded, a change in a single function causes all unchanged functions to deploy instead of "skipping the deploy of unchanged functions with experimental support for skipdeployingnoopfunctions"

### [REQUIRED] Steps to reproduce
1. Setup Cloud Function files like so

function1.ts
```ts
export const function1 = async (request) => {
    // function logic here
    return true;
};
```

function2.ts
```ts
export const function2 = async (request) => {
    // function logic here
    return true;
};
```

index.ts
```ts
import { onCall } from 'firebase-functions/v2/https';


export const function1 = onCall(async (request) => {
        await (await import('./function1')).function1(request);
    });

export const function2 = onCall(async (request) => {
        await (await import('./function2')).function2(request);
    });
```

2. Make any change in `function2.ts` function `function2`
3. Deploy cloud functions with `firebase deploy --only functions`

### [REQUIRED] Expected behavior

Only function2 deploys, with function1 showing "Skipping the deploy of unchanged functions with experimental support for skipdeployingnoopfunctions"

### [REQUIRED] Actual behavior

Both functions are updated and redeployed

**Comment by blidd-google** [comment]
Hi @imbradyboy, the skipnoopdeployfunctions feature will skip the deployment of [codebases](https://firebase.google.com/docs/functions/organize-functions?gen=2nd#organize_functions_in_codebases) that are unchanged, not individual functions. So unfortunately in your example, the both functions will still be re-deployed. However, if you split up the functions into separate codebases, the unchanged codebase will not be deployed.
