### ISSUE TITLE
Broken deployment due to missing storage bucket

### ISSUE THREAD

**Issue by joshjacks** [firebase/firebase-tools#6448]
### Environment info

**firebase-tools:** 12.6.2 (and still present in 12.7.0)

**Platform:** macOS 

### Test case

NA

### Steps to reproduce

I create a bucket via Terraform (exactly as shown in the docs [here](https://firebase.google.com/docs/projects/terraform/get-started#tf-sample-storage-default))

```terraform
resource "google_app_engine_application" "default" {
  provider    = google-beta
  project     = google_project.default.project_id
  location_id = "europe-west"

  depends_on = [
    google_firestore_database.firestore
  ]
}

resource "google_firebase_storage_bucket" "default" {
  provider  = google-beta
  project   = google_project.default.project_id
  bucket_id = google_app_engine_application.default.default_bucket
}
```

This is successful, it appears in the web console. On `firebase deploy` I receive

```
There was an issue deploying your functions. Verify that your project has a Google App Engine instance setup at https://console.cloud.google.com/appengine and try again. If this issue persists, please contact support.

Error: Your project is being set up. Please wait a minute before deploying again
```

And with `firebase deploy --debug`:

```
 Default storage bucket is undefined.
```

This is likely related to the changes in [v12.6.1...v12.6.2](https://github.com/firebase/firebase-tools/compare/v12.6.1...v12.6.2). The API call being made in `src/gcp/storage.ts` has changed.

Probably related to issue #6162  

### Expected behavior

I would expect if the bucket appears correctly in the web console, then it should be usable via the CLI. I haven't confirmed whether this is a Terraform specific issue. If I downgrade firebase-tools to 12.6.1 & use the exact same Terraform config everything works correctly.

### Actual behavior

Full debug logs (partially redacted):
```
[2023-10-15T11:41:01.706Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/<redacted> [none]
[2023-10-15T11:41:01.919Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects/<redacted> 200
[2023-10-15T11:41:01.920Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects/<redacted> {"projectId":"<redacted>","projectNumber":"<redacted>","displayName":"<redacted>","name":"projects/<redacted>","resources":{"hostingSite":"<redacted>"},"state":"ACTIVE","etag":"<redacted>"}
[2023-10-15T11:41:01.920Z] Default storage bucket is undefined.
```

I have created several new projects via Terraform and this is 100% reproducible

**Comment by joshjacks** [comment]
**Update**

- I made a basic project the web console then tried to deploy via the CLI. Everything worked well
- I described the bucket in the broken project and this working project as json
- There was no notable diff in the buckets (just project id and timestamps)

So must be some combination of the new endpoint being used *and* the way the bucket is created via Terraform

**Comment by joshjacks** [comment]
*Update - the cause of the issue*

Terraform does not do the equivalent of "finalising the project location" described in the REST docs ([here](https://firebase.google.com/docs/projects/api/workflow_set-up-and-manage-project#finalize-default-location))

Calling this REST endpoint caused the CLI to work again. It did not modify or create my AppEngine or Storage bucket. So it must do something "behind the scenes" with the Firebase config.

This didn't impact the firebase-tools CLI before but I don't know if you want to consider this a bug or not...

**Comment by joehan** [comment]
Hey @joshjacks, thanks for raising this issue and glad that you found a workaround to the problem. We're in the process of making some changes across Firebase to how default project resource locations work to make them more accurate across different surfaces and (for some products) more flexible. It looks like you've uncovered a rough edge in the transition. 

The change you identified in 12.6.2 was actually rolled back (and will go out in the next major version). It seems like we might also need some changes to the Terraform provider and the Firebase docs. Going to pass this along to the storage team to make sure we cover those as well/

**Comment by abhis3** [comment]
This issue has been resolved, please feel free to reopen if it is still an issue
