### ISSUE TITLE
Functions emulator tries to start if it just sees a functions folder present

### ISSUE THREAD

**Issue by CodingDoug** [firebase/firebase-tools#6450]
### Environment info

**firebase-tools:** 12.7.0

**Platform:** macOS

### Test case

Functions emulator starts with nothing more than a functions folder present.

### Steps to reproduce

```
$ firebase init emulators
... choose only Firestore
... take all the defaults

$ firebase emulators:start
... see that only Firestore starts
... ^C

$ mkdir functions
$ firebase emulators:start
... see that Functions emulator runs
```

The emulator generates the error:

> ⬢  functions: Failed to load function definition from source: FirebaseError: Could not detect language for functions at /path/to/functions

But the emulator continues to run on the default 5001 port.

### Expected behavior

I expect that the functions emulator not try to run at all.

IMO the only time it should try to run is if there is something in my firebase.json that suggests it should (perhaps a value for port under emulators/functions/port).

### Actual behavior

Explained above.

**Comment by aalej** [comment]
Hi @CodingDoug, thanks for raising this issue and for providing a detailed report. I was able to reproduce the behavior you mentioned. I’ll notify our engineering team about this issue and mark this as reproducible.
