### ISSUE TITLE
RuntimeOptions are not applied when used for firestore trigger functions.

### ISSUE THREAD

**Issue by mateuuszzzzz** [firebase/firebase-tools#6459]
### [REQUIRED] Environment info

**firebase-tools: 12.7.0, node 16**

**Platform: macOS Ventura 13.0 (M2 Pro chip)**

### [REQUIRED] Test case
Define trigger cloud function and export it in `functions/src/example.js`

```
const functions = require('firebase-functions')
const regionalFunctions = functions.region('europe-west1')

const runtimeOpts = {
  memory: '4GB'
}

const handleOnCreate = async (snapshot, context) => {
  // Do some actions..
}

module.exports = function (exports) {
    exports.triggeredCloudFunction = regionalFunctions.runWith(runtimeOpts).firestore.document('collection/{documentUID}/subcollection/{subdocumentUID}')
   .onCreate(handleOnCreate)
}

```

Export it in `functions/index.js`:

```
require('./src/example')(module.exports)
```

Deployment is successful. Only runtime options are not applied. We checked other functions in the project. If it's not Firestore trigger then runtime options are applied correctly.
_**Also, please notice that the project structure is crucial in this case.**_ If we define function directly in `index.js` like this:
```
const functions = require('firebase-functions')
const regionalFunctions = functions.region('europe-west1')

const runtimeOpts = {
  memory: '4GB'
}

const handleOnCreate = async (snapshot, context) => {
  // Do some actions..
}

const triggeredCloudFunction = regionalFunctions.runWith(runtimeOpts).firestore.document('collection/{documentUID}/subcollection/{subdocumentUID}')
   .onCreate(handleOnCreate)
}

module.exports = {
  triggeredCloudFunction
}
```
then everything works as expected.

### [REQUIRED] Steps to reproduce

1. Create a firebase function with `onCreate` trigger (in our case trigger for subcollection of other collection).
2. Define custom runtime options.
3. Pass them to `runWith`
4. Deploy function with this command: `firebase deploy --only functions:triggeredCloudFunction`
5. In GCP dashboard for newly created function one can see standard runtime options (256 MB).

### [REQUIRED] Expected behavior
Deployed function should have 4GB of memory.

### [REQUIRED] Actual behavior
Function has only 256MB of memory.

**Comment by aalej** [comment]
Hi @mateuuszzzzz, thanks for reaching out and for providing a detailed report. I’m currently unable to reproduce the behavior you mentioned. After deploying using `firebase deploy --only functions:triggeredCloudFunction`, the correct value for the memory(4GB) is set.

From what I can gather, your project structure looks like [this](https://github.com/aalej/issues-6459). If there's anything I'm missing or if I made a mistake, please let me know.

Also, could you let us know which version of `firebase-functions` you’re using and share your `firebase-debug.log` file after running `firebase deploy --only functions:triggeredCloudFunction`? The debug logs should contain additional information which could help narrow down the cause of the issue. Please remove any PII (personal identifiable information) before sharing the file.
