### ISSUE TITLE
[v13.0.0 Blocker] Ensure Web Frameworks works on Node 20

### ISSUE THREAD

**Issue by joehan** [firebase/firebase-tools#6466]
`test:frameworks` is failing now that we run it on Node 20 - ie https://github.com/firebase/firebase-tools/actions/runs/6514116615/job/17748657833?pr=6447

Let's get this passing again, and do some extra manual testing of deploying Web Frameworks on Node 20.

**Comment by jamesdaniels** [comment]
Manual testing is good so far, no concerns FYI. I'll get the tests running.
