### ISSUE TITLE
[v13.0.0 Blocker] GetStorageDefaultBucket through Storage API

### ISSUE THREAD

**Issue by joehan** [firebase/firebase-tools#6467]
We currently get the Default Storage Bucket by calling a FireData API that will be deprecated soon. We need to switch to using the Storage API for this. This will require some new permissions (included in Storage Bucket Viewer role) - we should also document these and ensure that when they are missing we error cleanly.

**Comment by tcf909** [comment]
The change was rolled out before the ACL was actually made public (breaking deployments):

![image](https://github.com/firebase/firebase-tools/assets/1562915/9b24c5b1-9a7f-4d98-8644-252ab0dadf7e)

**Comment by joehan** [comment]
@tcf909 Just double checked the source and it seems like the permission has been public in prod for quite a while. I'm reaching out to the responsible team to help figure out why its not showing up for custom roles - however, in the meantime, `firebasestorage.admin` and `firebasestorage.viewer` definitely both include  "firebasestorage.defaultBucket.get":

**Comment by tcf909** [comment]
@joehan thank you got the response. I will have the team add those temporarily. We had to roll back to 12.x.x latest to keep the pipeline operating today. 

Any thoughts on how that permission might be "available" but not visible in our cloud console?

**Comment by tcf909** [comment]
@joehan thank you for the update.
