### ISSUE TITLE
Support Next.JS server actions

### ISSUE THREAD

**Issue by jlucaso1** [firebase/firebase-tools#6468]
Please submit feature requests through our [support page](https://firebase.google.com/support/troubleshooter/report/features/).

**Comment by jlucaso1** [comment]
Server actions are stable now with recent Next.js 14 update

**Comment by walter-cavinaw** [comment]
It would be great if the firebase team could integrate server actions. Including the ability to synch user auth and still use security rules for storage and firestore.
