### ISSUE TITLE
Cannot serve functions using CI token

### ISSUE THREAD

**Issue by Kamshak** [firebase/firebase-tools#647]
**Motivation**: I have encountered a lot of errors trying to run functions in the emulator. I assume most are because of the dated node on Cloud Functions. I tried installing 6.11 locally via NPM but i ran into strange errors which i could not debug.

So what does a dev if they can't get their environment set up? Start from scratch, clear all side effects and run it in a container. The idea is to serve from within a container for debugging so everyone on the team can develop quickly without having to spend a lot of time on their dev environment.

**Goal**:  Run firebase serve --only functions in a container. Since it requires a login and the config store is not accessible we need to run with --token and a CI token.

### Version info

firebase-tools: 3.17.0

### Steps to reproduce

1) Initialize a new functions project: firebase init functions
2) Selected options: TypeScript, skip NPM install
3) Use the following Dockerfile: https://gist.github.com/Kamshak/3cbd5ebf2a48b13605ea28429ae774de
4) Build the container: ``docker build . -t firebase-app``
5) Run the container: ``docker run -it firebase-app firebase serve --only functions --token $FIREBASE_TOKEN``

### Expected behavior

It should start

### Actual behavior

```
=== Serving from '/app'...

i  functions: Preparing to emulate functions.
[2018-01-30T10:04:32.328Z] Fetching environment
[2018-01-30T10:04:32.331Z] TypeError: Cannot read property 'refresh_token' of undefined
    at module.exports (/usr/local/share/.config/yarn/global/node_modules/firebase-tools/lib/ensureDefaultCredentials.js:31:45)
    at FunctionsEmulator.start (/usr/local/share/.config/yarn/global/node_modules/firebase-tools/lib/functionsEmulator.js:114:3)
    at Object.start (/usr/local/share/.config/yarn/global/node_modules/firebase-tools/lib/serve/functions.js:9:29)
    at /usr/local/share/.config/yarn/global/node_modules/firebase-tools/lib/serve/index.js:16:19
    at arrayMap (/usr/local/share/.config/yarn/global/node_modules/lodash/lodash.js:660:23)
    at Function.map (/usr/local/share/.config/yarn/global/node_modules/lodash/lodash.js:9571:14)
    at _serve (/usr/local/share/.config/yarn/global/node_modules/firebase-tools/lib/serve/index.js:14:21)
    at Command._action (/usr/local/share/.config/yarn/global/node_modules/firebase-tools/commands/serve.js:42:12)
    at /usr/local/share/.config/yarn/global/node_modules/firebase-tools/lib/command.js:176:29
    at tryCatch (/usr/local/share/.config/yarn/global/node_modules/rsvp/dist/rsvp.js:525:12)

Error: An unexpected error has occurred.
```

**Comment by mbleigh** [comment]
The Firebase CLI detects [Google Application Default Credentials](https://cloud.google.com/docs/authentication/production).

The best way to handle this would be to download a service account for the project in question, then mount that into your Docker image and point the `GOOGLE_APPLICATION_CREDENTIALS` environment variable at the mounted path. The Firebase CLI should then automatically pick up the credentials and the emulator should be runnable.

**Comment by Kamshak** [comment]
I see thanks! Does that token work for deploy as well?

**Comment by mbleigh** [comment]
Yes

**Comment by Kamshak** [comment]
@mbleigh doesn't seem to work.
Downloaded a firebase admin service account as sa.json
```
> docker run -v /home/test/sa.json:/sa.json -e GOOGLE_APPLICATION_CREDENTIALS=/sa.json -it firebase-app /bin/bash -w /app  /bin/bash

> cat /sa.json
{   "type": "service_account",   "project_id": "firebase-project",   "private_key_id": "dddddd",   "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEuwIBADANBgkqh... }

> firebase serve --only functions
Error: No project active, but project aliases are available.
Run firebase use <alias> with one of these options:

  default (my-project-name)
  staging (my-project-name)
  production (my-project-name-prod)

> firebase use staging
Error: Command requires authentication, please run firebase login

> firebase serve --only functions -P my-project-name

Error: HTTP Error: 404, The specified project was not found.

Having trouble? Try firebase serve --help
```

**Comment by ZimbiX** [comment]
Why would the credential method be preferable to using a token? =S

**Comment by dinvlad** [comment]
@Kamshak have you been able to to deploy using `GOOGLE_APPLICATION_CREDENTIALS`? We're still getting `404`.

**Comment by Kamshak** [comment]
@dinvla yes it works for me but I'm not on the newest version of the package

**Comment by dinvlad** [comment]
@Kamshak - could you share the version number you use? That could help us troubleshoot why it doesn't work now. Thanks!
