### ISSUE TITLE
Type Mismatch Problems While Setting "cors" Property for Gen 2 Firebase Functions using TypeScript and a Parameterized Variable

### ISSUE THREAD

**Issue by BenJackGill** [firebase/firebase-tools#6470]
The documentation for [Firebase Parameterized Variables](https://firebase.google.com/docs/functions/config-env?gen=2nd) says we should call them directly inside function configs (i.e. do not append `.value()` on the end).

Therefore when using Parameterized Variables for the `cors` property of the `onCall` function config we should be directly using `defineString()` for a single domain or `defineList()` for an array of domain strings.

Currently this is not possible because the IDE (Visual Studio Code) will throw a TypeScript mismatch error.

In the examples below I am using `defineString()` but it's exactly the same for `defineList()`.

**1) Correct usage as per the docs, but throws IDE error:**
```TypeScript
import { onCall } from "firebase-functions/v2/https";
import { defineString } from "firebase-functions/params";

export const func = onCall(
  {
    cors: defineString("DOMAIN"), // Error shows here on "cors"
  },
  () => {
    // Do something here
  },
);
```

Visual Studio Code is showing this TypeScript mismatch error:

```
Type 'StringParam' is not assignable to type 'string | boolean | RegExp | (string | RegExp)[] | undefined'.
  Type 'Param<string>' is missing the following properties from type '(string | RegExp)[]': length, pop, push, concat, and 29 more.ts(2322)
https.d.ts(25, 5): The expected type comes from property 'cors' which is declared here on type 'CallableOptions'
```

**2) Workaround of appending `.value()` removes the IDE error, but shows lots of warnings in the deployment logs, also it goes against the docs:**
```TypeScript
import { onCall } from "firebase-functions/v2/https";
import { defineString } from "firebase-functions/params";

export const func = onCall(
  {
    cors: defineString("DOMAIN").value(),
  },
  () => {
    // Do something here
  },
);
```
This works, but the terminal deployment logs complain with this:

```
{"severity":"WARNING","message":"params.DOMAIN.value() invoked during function deployment, instead of during runtime."}
{"severity":"WARNING","message":"This is usually a mistake. In configs, use Params directly without calling .value()."}
{"severity":"WARNING","message":"example: { memory: memoryParam } not { memory: memoryParam.value() }"}
```

**3) Workaround of using ` as unknown as string` will avoid all errors and warnings, but it's considered bad TypeScript code to cast to `unknown`:**
```TypeScript
import { onCall } from "firebase-functions/v2/https";
import { defineString } from "firebase-functions/params";

export const func = onCall(
  {
    cors: defineString("DOMAIN") as unknown as string,
  },
  () => {
    // Do something here
  },
);
```

**Conclusion:**

Ultimately we need the `cors` function config property to accept `defineString()` or `defineList()` parameterized variables without throwing a TypeScript error in the IDE.

### [REQUIRED] Environment info

MacOS

firebase-tools: 12.7.0
firebase-admin: 11.11.0
firebase-functions: 4.4.1

**Comment by Berlioz** [comment]
So, I have good news and bad news.

The bad news is that I think the type definition here is intentional. Functions handles the `cors` property in a HTTP options trigger by [rewriting](https://github.com/firebase/firebase-functions/blob/3e7a4b77967e46a067712445c499c5df005b8e31/src/v2/providers/https.ts#L270) the function to use next.js' cors middleware under the hood. This rewrite happens before the function hits the param resolving code, so there wouldn't be any point for cors to accept Expression<string> or Expression<list> types.

The good news is that there's a pretty straightforward workaround. You should be able import the [cors middleware](https://www.npmjs.com/package/cors) yourself and use the string param inside the function body:
```
import { onRequest } from "firebase-functions/v2/https";
import { defineString } from "firebase-functions/params";
import * as cors from "cors";

var domain = defineString("DOMAIN");

export const func = onRequest({} (req, res) => {
    cors({origin: domain.value()})(req, res, () => {
        // your function body here - use the provided req and res from cors
    })
});
```

**Comment by BenJackGill** [comment]
Actually now that I think about it, I've been using `defineString("DOMAIN") as unknown as string`, and it's been working fine in practice.

So it seems like this might be more of a TypeScript type definition issue than a fundamental problem with using `defineString("DOMAIN")` for the `cors` property. The workaround is just quieting down the IDE warning, not changing the actual code behavior.

Perhaps something was missed in your assessment and the param is processed before hitting the next.js cors middleware. It's the only thing that makes sense - because it does work for me - but I would prefer to have the types updated so the IDE warning goes away.

**Comment by BenJackGill** [comment]
@Berlioz Was hoping this issue could be reopened and resolved because the workaround does not work for `onCall` functions as shown in the original post, it will only work with `onRequest` functions.

This is because `cors` middleware needs a `req` and `res` object but `onCall` functions only have `req`.
