### ISSUE TITLE
Error with firebase init

### ISSUE THREAD

**Issue by KhoaLeTranMinh** [firebase/firebase-tools#6472]
### [REQUIRED] Environment info

12.7.0
**firebase-tools:**

**Platform:**

### [REQUIRED] Steps to reproduce

During the git init, when it jumps to deploy setup, pressing enter will tell you the following error
### [REQUIRED] Actual behavior

=== Deploy Setup
[debug] [2023-10-24T10:16:52.860Z] >>> [apiv2][query] GET https://placeholder.googleapis.com/v1alpha/projects/next-firebase-app-bd099/locations/us-central1/stacks/acme-inc-web [none]
[debug] [2023-10-24T10:16:53.248Z] <<< [apiv2][status] GET https://placeholder.googleapis.com/v1alpha/projects/next-firebase-app-bd099/locations/us-central1/stacks/acme-inc-web 404
[debug] [2023-10-24T10:16:53.249Z] <<< [apiv2][body] GET https://placeholder.googleapis.com/v1alpha/projects/next-firebase-app-bd099/locations/us-central1/stacks/acme-inc-web "<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content=\"initial-scale=1, minimum-scale=1, width=device-width\">\n  <title>Error 404 (Not Found)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>404.</b> <ins>That’s an error.</ins>\n  <p>The requested URL <code>/v1alpha/projects/next-firebase-app-bd099/locations/us-central1/stacks/acme-inc-web</code> was not found on this server.  <ins>That’s all we know.</ins>\n"
[error] 
[error] Error: Failed to get or create a stack using the given initialization details: FirebaseError: Unable to parse JSON: SyntaxError: Unexpected token < in JSON at position 0

**Comment by aalej** [comment]
Hi @KhoaLeTranMinh, thanks for providing debug logs. Similar to [#6469](https://github.com/firebase/firebase-tools/issues/6469), I think you’re looking for the `webframeworks` experiment, not the `internalframeworks` experiment.

Try running the following commands:
```
firebase experiments:disable internalframeworks
firebase experiments:enable webframeworks
``` 
then run `firebase init` again.

For now, I’ll be closing this as a duplicate.
