### ISSUE TITLE
CORS Error When Deploying V1, V2 Functions in a Single Directory and Calling Callable V2 Function

### ISSUE THREAD

**Issue by leeyongeun9** [firebase/firebase-tools#6481]
### [REQUIRED] Environment info

**firebase-tools:** 12.7.0

**Platform:** macOS

### [REQUIRED] Test case
After deploying V1 functions and V2 functions, which include a callable V2 function (onCall), all within a single directory using the command `firebase deploy --only functions`, I encountered a problem when attempting to call the callable V2 function from a web app using the web-modular API (specifically, httpsCallable). The function failed to work and returned a CORS error.

However, I noticed that when I deployed only the onCall function with its name specified, using the command `firebase deploy --only functions:theFunction`, the function worked as expected and returned the intended result.

### [REQUIRED] Steps to reproduce
Provided above

### [REQUIRED] Expected behavior
Provided above

### [REQUIRED] Actual behavior
Provided above

**Comment by leeyongeun9** [comment]
I did not have this issue when I use firebase-tools version 12.4.8

**Comment by aalej** [comment]
Hi @leeyongeun9, sorry to hear that you’re encountering this issue and thanks for reporting this. Looking at the details provided, it seems like the issue you're encountering could be related to #6414. 

To help us verify if the issues could be related, could you share stack traces of the error raised during runtime of your functions?
