### ISSUE TITLE
`firebase deploy` not working in webframeworks experiment on windows

### ISSUE THREAD

**Issue by junaga** [firebase/firebase-tools#6511]
```sh
npx firebase experiments:enable webframeworks
npx firebase firebase deploy
```

from the debug `.log` file, `firebase-tools` tries to upload a a directory `C:C:\\` and it's not found.

I am using https://astro.build/ with SSR mode, but I think the bug is somewhere higher in the code.

**Comment by StevAlberts** [comment]
This worked for me `firebase deploy --only hosting` for Flutter Web .

**Comment by junaga** [comment]
okay then the bug is probably framework specific. I am using [https://github.com/firebase/firebase-tools/tree/master/src/frameworks/astro](https://github.com/firebase/firebase-tools/tree/master/src/frameworks/astro)

**Comment by TheElegantCoding** [comment]
nothing ?

**Comment by junaga** [comment]
@TheElegantCoding they now have Firebase App Hosting, not sure if this issue is relevant anymore.

**Comment by TheElegantCoding** [comment]
App hosting ? i managed to deploy but ssr dont work well

**Comment by junaga** [comment]
yeah, "App Hosting" https://firebase.google.com/docs/app-hosting, it's like "Firebase Hosting" but with direct support for Web Frameworks.

feel free to add me on discord `@junaga` for other questions

**Comment by leoortizz** [comment]
Hey @junaga, Astro support is not yet available in App Hosting. 

Here is the guide to deploy Astro projects to Firebase Hosting with SSR: https://github.com/firebase/firebase-tools/blob/master/src/frameworks/docs/astro.md#serve-fully-dynamic-content-ssr

Can you please check if you're following the instructions from the docs and let us know if that goes well?

If that doesn't work, could share a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) with us? This will help us accurately reproduce the issue.
