### ISSUE TITLE
firebase init fails for hosting on v12.9.0

### ISSUE THREAD

**Issue by yalcinozer** [firebase/firebase-tools#6527]
### [REQUIRED] Environment info

**firebase-tools:**
12.9.0

**Platform:**
macOS Ventura 13.1

### [REQUIRED] Test case

- Run `firebase init hosting`
- Try to init a hosting project either by a new project or existing project
- It will display "No active project" or will fail for some other reasons.

### [REQUIRED] Steps to reproduce
- Run `firebase init hosting`
- Try to init a hosting project either by a new project or existing project
- It will display "No active project" or will fail for some other reasons.

### [REQUIRED] Expected behavior
I downgraded to 12.5.0 and it runs flawlessly

It should initiate a new firebase project successfully
### [REQUIRED] Actual behavior
It fails to init a firebase project.

**Comment by aalej** [comment]
Hey @yalcinozer, thanks for reporting this issue. I was able to reproduce the error you mentioned. For now, I’d recommend downgrading to `firebase-tools` v12.8.1 since it seems like the issue is not reproducible there. Let me notify our team about this so that they can take a look.
