### ISSUE TITLE
[Crashlytics] [Flutter] Unable to upload `mapping.json` for symbols created for dart code

### ISSUE THREAD

**Issue by sarthakydv** [firebase/firebase-tools#6531]
### [REQUIRED] Environment info

**firebase-tools:** 12.7.0

**Platform:** macOS

### [REQUIRED] Test case

Passing class name to a logger is a standard practice and helps with debugging.
However, the crashlytics logs that we are getting do not map them back to the original names.

flutter provides the option to do it locally. [Instructions here](https://docs.flutter.dev/deployment/obfuscate#read-an-obfuscated-name)

It will be a huge help if it is done by crashlytics natively.

### [REQUIRED] Steps to reproduce

1. Make a release build of a flutter app with obfuscation enabled
```
flutter build appbundle --obfuscate --split-debug-info=build/app/outputs/android/crashytics/symbols --extra-gen-snapshot-options=--save-obfuscation-map=build/app/outputs/android/crashytics/obfuscation_map.json
```
2. Trigger a crash
3. The logs on the crashlytics dashboard would have obfuscated class names

### [REQUIRED] Expected behavior

Deobfuscated class names

### [REQUIRED] Actual behavior
Obfuscated class names

Error: set --resource-file <resourceFile> to a valid Android resource file path, e.g. app/main/res/values/strings.xml

**Comment by argzdev** [comment]
Hey @sarthakydv, thanks for reporting. It looks like this issue might be more of a Flutter concern. That said, could file an issue to the [Flutterfire team](https://github.com/firebase/flutterfire/issues)? They'll be able to assist you better. Thanks!
