### ISSUE TITLE
2nd gen functions lost there trigger and then gets stuck in deployment or deletion

### ISSUE THREAD

**Issue by gerhardcit** [firebase/firebase-tools#6534]
### [REQUIRED] Environment info

**firebase-tools: 12.9.1

**Platform:macOS

### [REQUIRED] Test case

When you change export GOOGLE_CLOUD_REGION="something other than us-central" sometime during a functions deployment,
your functions becomes impossible to update or delete.

### [REQUIRED] Steps to reproduce

Deploy a function normally (default is us-central1)
change GOOGLE_CLOUD_REGION=europe-west1 and redeploy.

change GOOGLE_CLOUD_REGION=
and try and redeploy.

### [REQUIRED] Expected behavior

New Functions should deploy.
errors should have more detail.

### [REQUIRED] Actual behavior

I ended up with this result
```
Functions deploy had errors with the following functions:
        helloAnything(us-central1)
        helloEurope(us-central1)
        helloWorld(us-central1)
i  functions: cleaning up build files...
⚠  functions: Unhandled error cleaning up build images. This could result in a small monthly bill if not corrected. You can attempt to delete these images by redeploying or you can delete them manually at https://console.cloud.google.com/artifacts/docker/<PROJECT_NAME>/us-central1/gcf-artifacts
Error: There was an error deploying functions:
- Error Failed to create function helloAnything in region us-central1
- Error Failed to update function helloEurope in region us-central1
- Error Failed to update function helloWorld in region us-central1
```

trying `firebase functions:delete helloWorld --force` does not work at all.

Then I'm stuck with this.. on a project that I cannot delete. Only functions is broken.. but there are lots off other stuff already happening in the project.

![Screenshot 2023-11-21 at 10 53 15](https://github.com/firebase/firebase-tools/assets/5508278/bc9bda90-0efe-4427-ab9e-c4f4fd7a97db)

**Comment by gerhardcit** [comment]
More info. Eventually this popped up on the 3rd deploy try
`firebase deploy --only functions`

Build failed with status: FAILURE and message: This project is using pnpm but you have not included the Functions Framework in your dependencies. Please add it by running: 'pnpm add @google-cloud/functions-framework'..

Ran this:
`pnpm add @google-cloud/functions-framework` 

package.json ended up with this:
```
"dependencies": {
    "@google-cloud/functions-framework": "^3.3.0",
    "firebase-admin": "^11.8.0",
    "firebase-functions": "^4.3.1"
  },
```

this fixed the functions.. but now they are in us-central1

![Screenshot 2023-11-21 at 12 39 40](https://github.com/firebase/firebase-tools/assets/5508278/37954db8-af01-4945-beb7-fc0874032d58)

Now I can delete things at least.

**Comment by gerhardcit** [comment]
Next, when I do this:
`export GOOGLE_CLOUD_REGION=europe-west1`

`firebase deploy --only functions`
I ended up with a function in us-central1 but the HTTP link is in Europe?

![Screenshot 2023-11-21 at 12 46 29](https://github.com/firebase/firebase-tools/assets/5508278/699ec321-7b6d-49de-8bab-59e4da4a2f04)

The documentation between http region and function region does not seem clear.

Then finally: 
```
export const helloEurope = onRequest({
    region: "europe-west1",
}, (request, response) => {
    logger.info("Hello Europe update!", { structuredData: true });
    response.send("Hello from Europe update!");
});
```

and deployed with 
```
export GOOGLE_CLOUD_REGION=europe-west1
firebase deploy --only functions
```

resulted in this:

![Screenshot 2023-11-21 at 12 49 18](https://github.com/firebase/firebase-tools/assets/5508278/11a07152-6ffd-4a9c-8df0-ff189f6442df)

Now is seems the the http is in Europe, the function is in Europe, and it can access the RTDB that is in europe.

But that seems not a simple way to do it.

**Comment by Berlioz** [comment]
I'm not sure where GOOGLE_CLOUD_REGION came from. As far as I know it's not something the Firebase CLI uses at all. The solution you landed on, by setting a `region` field in the individual Function configuration, is the intended method for configuring regionality (https://firebase.google.com/docs/functions/manage-functions?gen=2nd).

**Comment by sumit-1510-sharma** [comment]
Okay so if anyone facing this same problem, you might be installing some dependencies (for example in my case :- `npm install @google-cloud/tasks`) in your root directory but when using functions, you need to install them inside functions folder and your package.json inside that folder should look like below:

```
"dependencies": {
    "@google-cloud/tasks": "^5.5.2",
    "firebase-admin": "^12.6.0",
    "firebase-functions": "^6.0.1",
    "functions": "file:"
  },
```

Hope it helps 🙌
