### ISSUE TITLE
Redeploying all functions on any change

### ISSUE THREAD

**Issue by nikita-mishchenko** [firebase/firebase-tools#6538]
### [REQUIRED] Environment info

**firebase-tools: 12.7.0**

**Platform: macOS / CICD Debian**

### [REQUIRED] Test case

I have a Firebase app with workspace for functions that contains around 100 functions in `index.js`. 

If functions are not changed that everything works as expected, I'm getting `Skipping the deploy of unchanged functions with experimental support for skipdeployingnoopfunctions` and functions are not deployed. But if any of the functions is changed, all functions would be redeployed. 

As I understand, this happens because when `toSkip` object is calculated it compares the source code hash of the functions to deploy and the functions that are already deployed. And when you deploy functions it copies the source code of all functions that are in `index.js`(basically whole directorty without `exclude`). So in other words, it copies the same source code of all the functions multiplied by functions count times, and because of this, if you change one of the function the hash of all functions source code is changed and all functions are redeployed.

### [REQUIRED] Steps to reproduce

1) Have at least 2 function.
2) Change one function.
3) Deploy functions.

### [REQUIRED] Expected behavior

Only functions that where changed will be redeployed.

### [REQUIRED] Actual behavior

All functions are redeployed.

**Comment by blidd-google** [comment]
Hi @nikita-mishchenko, your understanding is correct that the CLI will only skip deployment of functions if none of the functions co-located in same source have been changed. The `skipdeployingnoopfunctions` feature is meant to be used in conjunction with "codebases" (see the docs [here](https://firebase.google.com/docs/functions/organize-functions?gen=2nd#organize_functions_in_codebases)) — if you organize your functions into codebases, then when you run `firebase deploy`, only the codebases containing functions that have been modified will be re-deployed and the other codebases will be skipped.

If you have further questions about how to use the codebases feature, you can direct them to the [Firebase Support](https://firebase.google.com/support) channel.
