### ISSUE TITLE
Gen2 onCall() doesn't contain auth object.

### ISSUE THREAD

**Issue by petrot** [firebase/firebase-tools#6540]
### [REQUIRED] Environment info

**firebase-tools:** 12.9.1
**firebase-functions:** 4.5.0
**firebase-admin:** 11.11.1

**Platform:** macOS

### [REQUIRED] Test case

I have a Gen1 function, it works as expected:

```
import * as functions from 'firebase-functions';

export const createAdminUserFn = functions.https.onCall(
  async (data: UserData, context: functions.https.CallableContext) => {
    console.log('data', data);
    console.log('auth', context.auth);
    ...
```
I would like to update it to Gen2.

With the Gen2 syntax, the request object doesn't contain the auth block
```
import { onCall } from 'firebase-functions/v2/https';

export const createAdminUserFn = onCall(
  async (request) => {
    console.log('data', request.data);
    console.log('auth', request.auth);
    ...
```

### [REQUIRED] Steps to reproduce

See my code

### [REQUIRED] Expected behavior

Gen2 request contains the auth object

**Comment by Berlioz** [comment]
Gen2 functions don't expose context.auth right now. This is working as...not intended, exactly, but there are changes in the underlying architecture which aren't fully under our control. You can get equivalent behavior by passing in the UID to the context manually, or by just using a gen1 function (it's fine to mix gen1 and gen2 functions in the same file/deployment).
