### ISSUE TITLE
Parameterized configuration is not working with python

### ISSUE THREAD

**Issue by RTae** [firebase/firebase-tools#6550]
### [REQUIRED] Environment info

**firebase-tools:** 12.5.2

**Platform:** macOS

### [REQUIRED] Test case
Change runtime optional in each environment by using **dotenv** file

### [REQUIRED] Steps to reproduce
1. Create two **dotenv** file, which are **.env** and **.env.temp**
2. Set variables into **.env** and **.env.temp**, let keep track on variable **PROJECT_ID**
    2.1 **.env** : **PROJECT_ID=local**
    2.2 **.env.temp** : **PROJECT_ID=temp**
4. Run `firebase use temp`
5. Run `firebase deploy`

### [REQUIRED] Expected behavior
It must use **PROJECT_ID** in each environment; in this case must be **PROJECT_ID=temp**

### [REQUIRED] Actual behavior
it use environment variable from **.env** file, **.env.temp** does not overwrite the default configuration

### Example code
```python
from firebase_functions import pubsub_fn, params
import os

REGION = os.environ.get("REGION")
PUBSUB_TOPIC_NAME = os.environ.get("PUBSUB_TOPIC_NAME")
PROJECT_ID = params.StringParam("PROJECT_ID")

@pubsub_fn.on_message_published(
    topic=PUBSUB_TOPIC_NAME,
    region=REGION,
    service_account=f"test@{PROJECT_ID}.iam.gserviceaccount.com",
    memory=16384,
    timeout_sec=540,
    cpu=8,
)
def Test(
    event: pubsub_fn.CloudEvent[pubsub_fn.MessagePublishedData],
) -> None:
   # Code
```

**Comment by aalej** [comment]
Hi @RTae, thanks for reaching out and sharing a code snippet along with steps to reproduce the issue. Currently, I’m unable to reproduce the behavior you mentioned. I think the values in your `.env.temp` file are not being loaded. When running `firebase deploy`, do you see a log message similar to:
```
i  functions: Loaded environment variables from .env, .env.temp.
```
I’m using firebase-tools v12.9.1 to try and replicate this issue. Could you try updating to the latest version to see if there are any changes in behavior when deploying?

**Comment by RomanTheLegend** [comment]
I can confirm the behavior. There seem to be a race condition when loading ENV variables because in the example below it uses `CPU` value from one file, but pairs it with `MEMORY` from another

Using current firebase-tools version and Python 3.11

**.env**
```
PROJECT_ID=

ENV_ID=
CPU=2
MEMORY=GB_8
```

**.env.default**
```
PROJECT_ID=xxxxxxxxxxxxx

ENV_ID=sandbox
CPU=1
MEMORY=GB_1

DEPLOYMENT_REGIONS=(US EU)

REGION_US=us-central1
REGION_EU=europe-west1
REGION_GB=europe-west2
REGION_CA=northamerica-northeast2
```


It supposed to use 1 CPU box with 1 GB mem, but instead it uses 1 CPU with 8 GB mem which is invalid:

```
functions: Loaded environment variables from .env, .env.default.
...

functions: my_python_func folder uploaded successfully
 functions: updating Python 3.11 (2nd Gen) function 
my_python_func:my_python_func_us(us-central1)...
⚠  functions: Request to https://cloudfunctions.googleapis.com/v2/projects/xxxxxxxxxxxxx/locations/us-central1/functions/my_python_func?......
had HTTP Error: 400, Could not update Cloud Run service projects/xxxxxxxxxxxxx/locations/us-central1/services/my-python-func-us. spec.template.spec.containers[0].resources.limits.memory: 
Invalid value specified for container memory. For 1.0 CPU, memory must be between 128Mi and 4Gi inclusive.
````
