### ISSUE TITLE
!!  functions: Failed to load function definition from source: FirebaseError: There was an error reading .output\server\package.json:

### ISSUE THREAD

**Issue by ferdinandetchu** [firebase/firebase-tools#6563]
Trying to host nuxt 3 app with firebase and I run in to the error

!!  functions: Failed to load function definition from source: FirebaseError: There was an error reading .output\server\package.json:
 .output\server\index.js does not exist, can't deploy Cloud Functions
 
 when I want to run the Firebase emulator please how can I fix these
 
 My firebase.json file
```
{
  "functions": { "source": ".output/server", "runtime": "nodejs18" },
  "hosting": {
    "site": "billy-kirts-group-website",
    "public": ".output/public",
    "cleanUrls": true,
    "rewrites": [{ "source": "**", "function": "server" }],
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ]
  }
}
```

my nuxt.config.ts file

```
// https://nuxt.com/docs/api/configuration/nuxt-config
import vuetify, { transformAssetUrls } from 'vite-plugin-vuetify'
export default defineNuxtConfig({
  nitro: {
    firebase: {
      gen: 2,
      nodeVersion: '18'
    }
  },
  devtools: { enabled: true },
  css: ['@/assets/main.css'],
  build: {
    transpile: ['vuetify'],
  },
  modules: [
    (_options, nuxt) => {
      nuxt.hooks.hook('vite:extendConfig', (config) => {
        // @ts-expect-error
        config.plugins.push(vuetify({ autoImport: true }))
      })
    },
    //...
  ],
  vite: {
    vue: {
      template: {
        transformAssetUrls,
      },
    },
  },
})
```

[firebase-debug.log](https://github.com/firebase/firebase-tools/files/13536897/firebase-debug.log)

**Comment by jamesdaniels** [comment]
FYI `hosting.public` rather than `hosting.source` means they are going it their own without Web Frameworks.

@ferdinandetchu without seeing your functions source I doubt we'd be of much help. FWIW we have expirimental support for detecting and integrating Web Frameworks (like Nuxt) for you, PTAL https://firebase.google.com/docs/hosting/frameworks/frameworks-overview
