### ISSUE TITLE
Deploy storage : an unexpected error has occurred

### ISSUE THREAD

**Issue by mRogledi** [firebase/firebase-tools#657]
Hi, when i try to deploy the final message is "Error: An unexpected error has occurred", what is the error?  

I've tried to run deploys individually, so the error occurs when i run `firebase deploy --only storage`.
can you help me please?  

log file: [firebase-debug.log](https://github.com/firebase/firebase-tools/files/1697040/firebase-debug.log)

**Comment by laurenzlong** [comment]
This is a server side error message, please file a support ticket at firebase.google.com/support
