### ISSUE TITLE
Unable to deploy due to error with Google App Engine (Default storage bucket is undefined.)

### ISSUE THREAD

**Issue by Blunderchips** [firebase/firebase-tools#6570]
### [REQUIRED] Environment info

**firebase-tools:** 12.9.1

**Platform:** docker image (CD deployment from node image)

![image](https://github.com/firebase/firebase-tools/assets/7081037/e641bdbd-c81f-4346-b129-bd9123ccff86)

### [REQUIRED] Steps to reproduce

> firebase deploy --force -m "Pipeline ${CI_PIPELINE_ID}, build ${CI_BUILD_ID}"

### [REQUIRED] Expected behavior

App deploys with out error.

### [REQUIRED] Actual behavior

![image](https://github.com/firebase/firebase-tools/assets/7081037/fd7d8c23-e4e5-4796-aa9e-ba892e05507e)

Failing across two of our environments. Both applications are still running but we are unable to make any new deployments. We have of course giving it a good couple of minutes and tried to redeploy.

With debug flag:

![image](https://github.com/firebase/firebase-tools/assets/7081037/e722af41-2e6f-4cd5-ab7d-23358410c06a)

Needless to say, we have been making use of the storage bucket for many months now. Checking our storage bucket through the firebase web portal, we can see all our data is still there. We have made no change to our storage bucket config.

**Comment by ahanusek** [comment]
We have the same issue. Not major changes in this pipeline and project for months.

**Comment by Burgov** [comment]
Duplicate of https://github.com/firebase/firebase-tools/issues/6567

**Comment by Blunderchips** [comment]
> Duplicate of #6567

Appears to be, going to close this issue.
