### ISSUE TITLE
Firebase Functions emulator error occurs when the computer is connected to the internet: "Failed to load function definition from source."

### ISSUE THREAD

**Issue by timotheeduran** [firebase/firebase-tools#6605]
### [REQUIRED] Environment info

**firebase-tools:13.0.1** (Also happens with earlier versions, like 12.9.1)
**Platform:macOS 14.1.1**
**node: v18.17.0**
**npm: 10.2.5**

### [REQUIRED] Test case

[Example Firebase project for this issue](https://github.com/timotheeduran/firebase-issue-mcve)

### [REQUIRED] Steps to reproduce

1. **Clone the repo provided above** OR follow these steps:
    1. Run `firebase init` in an empty directory.
    2. Select the `Functions` feature.
    3. Select `Create a new project`.
    4. Choose an ID.
    5. Choose the default name.
    6. Choose `JavaScript`. (Doesn't impact the bug)
    7. Don't turn on ESLint with `N`. (Doesn't impact the bug)
    8. Install dependencies with `Y`.
    9. Go to the `functions` directory and run `npm install`.
    10. Go back to the root.

2. Run `firebase emulators:start` from the root of the project.
3. ❌ An error occurs: `functions: Failed to load function definition from source: FirebaseError: User code failed to load. Cannot determine backend specification`.
4. Turn off the wifi or any internet connection.
5. Restart the Mac.
6. Run `firebase emulators:start` from the root of the project.
7. ✅ The script works correctly and prints `functions: Loaded functions definitions from source: .`.
8. Turn on the wifi again.
9. Run `firebase emulators:start` from the root of the project.
10.  ❌ An error occurs: `functions: Failed to load function definition from source: FirebaseError: User code failed to load. 
11. Turn off the wifi or any internet connection.
12. Run `firebase emulators:start` from the root of the project.
13.  ❌ An different error occurs: `Error: An unexpected error has occurred.`

### [REQUIRED] Expected behavior

Running `firebase emulators:start` should print `functions: Loaded functions definitions from source` with no error.

### [REQUIRED] Actual behavior

Terminal output of running the `firebase emulators:start` command without and then with internet.
[terminal_output.txt](https://github.com/firebase/firebase-tools/files/13640612/terminal_output.txt)
[firebase-debug.log](https://github.com/firebase/firebase-tools/files/13640628/firebase-debug.log)

* The emulator can't load functions when connected to the internet.
* The issue happens:
    * With a JS or TS codebase.
    * With a brand new project or an old codebase (1 year old).
    * With other emulators (firestore, auth, etc.) or only the functions emulator.
    * With different internet connections, including VPN or not.
    * With firebase-tools: 13.0.1 or earlier, like 12.9.1. (You can downgrade with `npm uninstall -g firebase-tools` and then `npm install -g firebase-tools@12.9.1`)
 
💡 The issue happened suddenly this afternoon around 15:00 (UTC+1, Switzerland) without changing anything in my code or updating anything. I suspect a change on Google servers since the issue seems to be linked to having an internet connection.

**Comment by timotheeduran** [comment]
Hi @aalej,

Thanks for your time. Sorry for the mix up, here is the correct `firebase-debug.log` file, when connected to internet.
[firebase-debug.log](https://github.com/firebase/firebase-tools/files/13648884/firebase-debug.log).

**Comment by timotheeduran** [comment]
Hello! No I don't have anything like that. I took care of checking that no VPN was activated also. 

The fact that the emulator worked in the morning and then not in the afternoon is strange. Especially having not updated or changed anything. At least that I'm aware of.

I'm thinking about something like an update on Google's servers side. Would this be possible? Especially because it breaks only when connected to internet.

**Comment by timotheeduran** [comment]
Hi, it seems to be working this morning, again without changing anything at all. 
I still have no idea why this happened but I suggest we close this issue and reopen it if it happens again.

Thank you for your time.

**Comment by StormKop** [comment]
Hi everyone, stuck on this for a few days. With the exact same error. Any idea how to resolve this?
firebase-tools: 13.0.2
platform: macOS 14.2
node: 18.8.0
npm: 10.2.4

Tried, with the internet on/off approach but it still failed to work. Anything else I can add here to help debug the issue?

**Comment by maelp** [comment]
I have the same issue

**Comment by AidenKT** [comment]
I concur, same issue and matching error
