### ISSUE TITLE
Firebase Hosting web frameworks w/ Angular, selecting environments

### ISSUE THREAD

**Issue by kanehjeong** [firebase/firebase-tools#6614]
I am using the firebase hosting web frameworks experimental feature with an Angular v17 SSR enabled project. When doing a build with Angular by itself, you can usually do something like `ng build --configuration staging`. However, the `firebase deploy --only hosting` command will automatically build your project using the production configuration when you're using the web frameworks feature, and there doesn't seem to be a way to specify any parameters for your build.

Feature Request: Allow you to specify the environment configuration for hosting i.e. `firebase deploy --only hosting --configuration staging` when using Angular with firebase, which will build your project based on the configuration defined in `angular.json`.

**Comment by 9kubczas4** [comment]
Hi @kanehjeong,

The solution could be to use the `FIREBASE_FRAMEWORKS_BUILD_TARGET` variable.

On MacOS: `FIREBASE_FRAMEWORKS_BUILD_TARGET='staging' firebase deploy --only hosting`
On Windows: `set FIREBASE_FRAMEWORKS_BUILD_TARGET='staging' firebase deploy --only hosting`

Support for `FIREBASE_FRAMEWORKS_BUILD_TARGET` variable is already implemented in recent versions of the firebase-tools.

**Comment by kanehjeong** [comment]
@9kubczas4 I was not aware of this. I tried it out and it seems to work as expected. Not as convenient as a flag but good enough :) I will close the ticket.

**Comment by boldi24** [comment]
Hi @9kubczas4 and @kanehjeong,

Did you face this message when you tried to used FIREBASE_FRAMEWORKS_BUILD_TARGET?
```
Error: Invalid value for FIREBASE_FRAMEWORKS_BUILD_TARGET environment variable: staging. Valid values are: production, development
```
I have the latest 13.6.1 firebase-tools installed.

Cheers

**Comment by blackpr** [comment]
This does not work for me. Is there any new way for this?

**Comment by 9kubczas4** [comment]
@blackpr what version of Angular and OS did you use?

**Comment by blackpr** [comment]
wsl with `Ubuntu 22.04.4 LTS`
angular v13

**Comment by ecancil** [comment]
This is no longer working, for me at least

firebase 13.15.0
angular 18.0.7
