### ISSUE TITLE
I can't install firebase-tools

### ISSUE THREAD

**Issue by Hedurtado** [firebase/firebase-tools#6618]
### [REQUIRED] Environment info

**firebase-tools:** None

**Platform:** cmd

### [REQUIRED] Test case

I run this commando

npm install -g firebase-tools

### [REQUIRED] Steps to reproduce

I opened my cmd and run the command 
npm install -g firebase-tools

### [REQUIRED] Expected behavior

firebase-tools been installed

### [REQUIRED] Actual behavior

npm ERR! code 1
npm ERR! path C:\Users\eehur\.cache\firebase\tools\node_modules\firebase-tools\node_modules\protobufjs
npm ERR! command failed
npm ERR! command C:\Users\eehur\.cache\firebase\runtime/shell.bat -c -- node scripts/postinstall
npm ERR! '--' is not recognized as an internal or external command,
npm ERR! operable program or batch file.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\eehur\AppData\Local\npm-cache\_logs\2023-12-14T21_40_28_420Z-debug-0.log

[2023-12-14T21_40_28_420Z-debug-0.log](https://github.com/firebase/firebase-tools/files/13678629/2023-12-14T21_40_28_420Z-debug-0.log)

**Comment by joehan** [comment]
Hey @Hedurtado, based on the error message you shared, it looks like the postinstall script for protobufjs is failing on your machine. We've seen this happen a few times before (ie https://stackoverflow.com/questions/67348819/what-is-the-meaning-of-this-error-protobufjs6-11-2-postinstall-node-scripts)

Could you try running `npm install -g --unsafe-perm firebase-tools` ?

On a separate note: it seems like protobufjs changed its postinstall script in v7.0.0 to prevent issues like this. We are mostly on >7.0.0, but it seems like there is one dep somewhere that is still bringing in ^6.0.0. I'll take an action item to update our deps to try to remove this transitive dependency.

**Comment by Hedurtado** [comment]
I ran the command it git bash as administrator and when I tried to check the firebase version it said firebase isn't a command.
Also I tried in PowerShell as administrator with the same result.

I checked the link you sent and I ran npm install --save firebase-tools in both PS and Git bash and end with the same result as above.

**Comment by joehan** [comment]
@Hedurtado Another option you could try is to install via https://firebase.tools . The builds on that site come bundled with Node, which should skip the postinstall step that is failing for you:

```
curl -sL firebase.tools | bash
```

**Comment by Hedurtado** [comment]
I ran it and I get this error
```
PS C:\Windows\system32> curl -sL firebase.tools | bash
Invoke-WebRequest : A parameter cannot be found that matches parameter name 'sL'.
At line:1 char:6
+ curl -sL firebase.tools | bash
+      ~~~
    + CategoryInfo          : InvalidArgument: (:) [Invoke-WebRequest], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```

**Comment by joehan** [comment]
Ahh, it looks like you are not using a bash shell, whoops. Try following the directions for 'Standalone binary' in our docs:
https://firebase.google.com/docs/cli#setup_update_cli

**Comment by Hedurtado** [comment]
I already tried it, but I get this error :/ 
At this point I don't know what I'm doing wrong
```
> firebase projects:list
× Preparing the list of your Firebase projects

Error: Failed to list Firebase projects. See firebase-debug.log for more info.
```

[firebase-debug.log](https://github.com/firebase/firebase-tools/files/13781662/firebase-debug.log)

**Comment by joehan** [comment]
The debug log looks like you have not run `firebase login` - you'll need to run that in order to use any commands that access your firebase project.

The main error message definitely could be more descriptive here tho - I'm going to clarify that message so hopefully others have an easier time.

**Comment by Hedurtado** [comment]
I solve it.
It looks like I was already login but the cli told me that i wasnt authenticated.
```
~ Let's make sure your Firebase CLI is ready...
+ Looks like your CLI is set up!

~ Looks like you're not authenticated. Let's log in!
Already logged in as edwin.hurtado@yachaytech.edu.ec
```

So I've to logout and login again and now it works 

```
Waiting for authentication...

+  Success! Logged in as edwin.hurtado@yachaytech.edu.ec

> firebase projects:list
√ Preparing the list of your Firebase projects
```

Thanks you for your support
