### ISSUE TITLE
Is it necessary to read the main field in a package.json on predeploy?

### ISSUE THREAD

**Issue by jthegedus** [firebase/firebase-tools#662]
### Version info
`"firebase-tools": "^3.17.4",`

### Platform Information
Ubuntu 17.10

### Steps to reproduce

My blog example repo is configured to reproduce this issue.

https://github.com/jthegedus/blog-examples/tree/master/firebase-functions-express

Just download, install, configure the `.firebaserc` file and run `yarn deploy`.

### Expected behavior

I expected the deploy to use the `index.js` file at the location specified by the `firebase.json`
```json
{
  "functions": {
    "source": "dist/functions",
```

### Actual behavior

The deploy step fails due to concatenating the dir specified in the `firebase.json` with the dir from the `package.json`s `main` field.

<details>
<summary><b>logs</b></summary>

```
james@james-xps:~/Projects/Personal/blog-examples/firebase-functions-express$ yarn deploy --debug
yarn run v1.3.2
$ yarn firebase deploy --only functions --debug
$ /home/james/Projects/Personal/blog-examples/firebase-functions-express/node_modules/.bin/firebase deploy --only functions --debug
[2018-02-08T12:03:58.239Z] ----------------------------------------------------------------------
[2018-02-08T12:03:58.242Z] Command:       /home/james/.asdf/installs/nodejs/8.9.4/bin/node /home/james/Projects/Personal/blog-examples/firebase-functions-express/node_modules/.bin/firebase deploy --only functions --debug
[2018-02-08T12:03:58.243Z] CLI Version:   3.17.4
[2018-02-08T12:03:58.243Z] Platform:      linux
[2018-02-08T12:03:58.243Z] Node Version:  v8.9.4
[2018-02-08T12:03:58.243Z] Time:          Thu Feb 08 2018 23:03:58 GMT+1100 (AEDT)
[2018-02-08T12:03:58.243Z] ----------------------------------------------------------------------

[2018-02-08T12:03:58.251Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2018-02-08T12:03:58.252Z] > authorizing via signed-in user
[2018-02-08T12:03:58.254Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/projects/blog-post-examples

 Thu Feb 08 2018 23:03:58 GMT+1100 (AEDT)
[2018-02-08T12:03:59.257Z] <<< HTTP RESPONSE 200 server=nginx, date=Thu, 08 Feb 2018 12:03:59 GMT, content-type=application/json; charset=utf-8, content-length=129, connection=close, x-content-type-options=nosniff, strict-transport-security=max-age=31536000; includeSubdomains, cache-control=no-cache, no-store
[2018-02-08T12:03:59.260Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/database/blog-post-examples/tokens

 Thu Feb 08 2018 23:03:59 GMT+1100 (AEDT)
[2018-02-08T12:04:00.145Z] <<< HTTP RESPONSE 200 server=nginx, date=Thu, 08 Feb 2018 12:04:00 GMT, content-type=application/json; charset=utf-8, content-length=268, connection=close, x-content-type-options=nosniff, strict-transport-security=max-age=31536000; includeSubdomains, cache-control=no-cache, no-store

=== Deploying to 'blog-post-examples'...

i  deploying functions
Running command: yarn clean && yarn build:funcs && yarn deps:copy && yarn deps:install
$ rimraf dist/functions
$ cpx src/functions/index.js dist/functions
$ cpx *{package.json,yarn.lock} dist/functions
$ cd dist/functions && yarn
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.3: The platform "linux" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "firebase-admin > @firebase/database@0.1.9" has unmet peer dependency "@firebase/app-types@^0.1.0".
warning "firebase-admin > @firebase/database > @firebase/database-types@0.1.1" has unmet peer dependency "@firebase/app-types@^0.1.0".
[4/4] Building fresh packages...
✔  functions: Finished running predeploy script.
[2018-02-08T12:04:10.524Z] > [functions] package.json contents: {
  "name": "firebase-functions-express",
  "description": "",
  "keywords": [
    "firebase",
    "cloud functions",
    "express",
    "expressjs"
  ],
  "author": "James Hegedus",
  "license": "MIT",
  "private": true,
  "version": "1.0.0",
  "main": "src/index.js",
  "homepage": "https://github.com/jthegedus/blog-examples/blob/master/firebase-functions-express/README.md",
  "bugs": {
    "url": "https://github.com/jthegedus/blog-examples/issues/new"
  },
  "scripts": {
    "fblogin": "yarn firebase login",
    "serve": "yarn firebase serve --only functions",
    "shell": "yarn firebase experimental:functions:shell",
    "deploy": "yarn firebase deploy --only functions",
    "build:funcs": "cpx src/functions/index.js dist/functions",
    "deps:copy": "cpx *{package.json,yarn.lock} dist/functions",
    "deps:install": "cd dist/functions && yarn",
    "clean": "rimraf dist/functions"
  },
  "dependencies": {
    "cors": "^2.8.4",
    "express": "^4.16.2",
    "firebase-admin": "^5.8.2",
    "firebase-functions": "^0.8.1"
  },
  "devDependencies": {
    "cpx": "^1.5.0",
    "firebase-tools": "^3.17.4",
    "rimraf": "^2.6.2"
  }
}

Error: dist/functions/src/index.js does not exist, can't deploy Firebase Functions

Having trouble? Try firebase deploy --help
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

</details>

The culprit seems to be https://github.com/firebase/firebase-tools/blob/c0f4949d3b1cc797028c824408c1a8e95e03d955/lib/deploy/functions/prepare.js#L48

Is this concatentation behaviour necessary? Since we're defining the dir to deploy, could it not be required that this dir has an `index.js` without considering the `package.json`s `main` field? Or probably better, check if that dir has a `index.js` first and if it does not, then try concatenating the `main` field and see where we end up.

---

For context, the `main` field is required by CodeSandbox.io to point to a file, but if I point it to the `src/functions/index.js` file I get the deploy script looking for 
```shell
dist/functions/src/functions/index.js
```
instead of finding
```shell
dist/functions/index.js
```
as per my `firebase.json`s `"source": "dist/functions"`.

**Comment by laurenzlong** [comment]
Since using `main` inside package.json is how the functions runtime find the source code inside the uploaded folder, changing the behavior at deploy time will not help since you'll just be deploying a folder that the functions runtime will misinterpret, and the function won't work.

**Comment by jthegedus** [comment]
Interesting. I generally structure my code as below without any `main` field.

```shell
# Before build
./package.json
./src/functions/index.js

# After build
./dist/functions/index.js
./dist/functions/package.json
```

So if the `main` field is empty, then the uploaded folder is assumed to be the root of the function? And if that's the case, would you support a `firebase.json` option to opt-out of looking at the `main` field and assume the uploaded folder is the root?

**Comment by laurenzlong** [comment]
I believe that in the absence of "main", the functions runtime assumes it's index.js. It's important to note that only things inside of the functions folder is uploaded to the functions backend, not firebase.json. So things inside firebase.json can only affect deployment behavior, not what happens once the folder is uploaded to the server. This is because Cloud Functions is not a Firebase-specific product, and can be used with any Cloud projects, not just Firebase projects.

**Comment by mbleigh** [comment]
You can think of the `source` config option as pointing at the *package directory* for your functions. It is then up to the standard Node.js semantics to decide what file is considered the entrypoint. This defaults to whatever is in `main` and falls back to `index.js`.

I don't think we will be changing this behavior, as we are doing our best to adhere to common best practices in Node.js development and you can always change or remove `main` from your `package.json` if you want `index.js` to be picked up.

**Comment by jthegedus** [comment]
@laurenzlong @mbleigh Thanks for the clarification.

I recognise that having a single `package.json` for the repo instead of a standalone `package.json` for the functions is not standard usage, and that the `main` field is being used with common best practices, I'm just coming across pain points of having a monorepo structure with a multitude of tools that all follow this same best practice and therefore conflict.

Thanks for the explanation and your time :smile:
