### ISSUE TITLE
`firebase emulators:start --log-verbosity` not working

### ISSUE THREAD

**Issue by junaga** [firebase/firebase-tools#6622]
firebase-tools: `13.0.2` \
Platform: Linux

Run `firebase emulators:start` with the `--log-verbosity` flag in either `DEBUG`, `INFO`, `QUIET`, `SILENT`. 

+ `database-debug.log` 
+ `firebase-debug.log`

always contain info and debug logs.

**Comment by aalej** [comment]
Hi @junaga, just to get a better overview of this report, I’d like to confirm a few things:

Do you expect that the `.log` files would not be generated when passing one of the options for `--log-verbosity`?

Could you elaborate what you mean by “always contain info and debug logs”? From what I can gather, setting `--log-verbosity` to either `QUIET` or `SILENT` should not show info and debug logs from the emulator. Are the logs still being shown on the terminal?

Having these information will help us verify if this is a bug, working as intended, or a feature that we can add.

**Comment by junaga** [comment]
the logs are not shown the terminal, but the `.log` files are created. I expected the log files verbosity to decrease with stricter levels of `--log-verbosity`.

**Comment by joehan** [comment]
@junaga This is working as intended - we log everything to these debug logs so that they can be used to help debug issues.

If you want a less verbose .log file, consider piping the console output to a file.

**Comment by junaga** [comment]
@joehan weird, but ok

**Comment by junaga** [comment]
sounds disrespectful to the userbase, in my opinion
