### ISSUE TITLE
NX Firebase hosting integration

### ISSUE THREAD

**Issue by barack98** [firebase/firebase-tools#6623]
When I try to deploy an angular standalone app
I get the following error

_Could not determine the web framework in use.

Error: Unable to detect the web framework in use, check firebase-debug.log for more info._

How can I easily integrate Firebase with my NX monorepos
Is there a workaround this

**Comment by aalej** [comment]
This seems to be a duplicate of #6049. That said, I’ll go ahead and close this for now. Please refer to the other issue for any updates.
