### ISSUE TITLE
Debian unable to install firebase-tools 

### ISSUE THREAD

**Issue by ms747** [firebase/firebase-tools#663]
### Version info

3.17.4

### Platform Information

Linux
### Steps to reproduce

sudo npm -g install firebase-tools
Also tried
sudo npm -g install firebase-tools@3.17.4
sudo npm -g install firebase-tools@3.0^
sudo npm -g install firebase-tools@latest
(Same behaviour)
### Expected behavior

Firebase tools getting successfully installed

### Actual behavior

npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'google-cloud/functions-emulator' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'firebase-tools'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 4.15.1-towo.1-siduction-amd64
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "firebase-tools" "-g"
npm ERR! cwd /home/ms
npm ERR! node -v v8.9.3
npm ERR! npm -v 1.4.21
npm ERR! code E404
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/ms/npm-debug.log
npm ERR! not ok code 0

**Comment by mbleigh** [comment]
Your NPM is very, very out of date. Run `npm install -g npm`
