### ISSUE TITLE
Loaded functions definitions from source: app. 07:31:57 I functions http function initialized (http://127.0.0.1:5001/fullstack-foodapp-dec-23/us-central1/app).

### ISSUE THREAD

**Issue by Kirishan31** [firebase/firebase-tools#6642]
### [REQUIRED] Environment info

**firebase-tools:**

**Platform:**

**Comment by paulinon** [comment]
Hi @Kirishan31,

Please file a new ticket and provide the needed infomation indicated in the issue template. This way, we can have a better understanding of what's causing the issue to happen. Thanks.
