### ISSUE TITLE
Typo in Cloud storage bucket metadata location type (mutli-region)

### ISSUE THREAD

**Issue by crashdump** [firebase/firebase-tools#6648]
### [REQUIRED] Environment info

**firebase-tools:**

v13.0.2

**Platform:**

macOS, Windows, Linux

### [REQUIRED] Test case

Interact with the cloud storage API and fetch any bucket's metadata

### [REQUIRED] Steps to reproduce

Interact with the cloud storage API and fetch any bucket's metadata

### [REQUIRED] Expected behavior

`LocationType` should return `multi-region`

### [REQUIRED] Actual behavior

`LocationType` should return `mutli-region` (note the location of the l)

**Comment by aalej** [comment]
I'm going to go ahead and close this as #6649 has been merged. Thanks for the contribution!
