### ISSUE TITLE
The CJS build of Vite's Node API is deprecated.

### ISSUE THREAD

**Issue by lcsd** [firebase/firebase-tools#6652]
### [REQUIRED] Environment info

**firebase-tools: 13.0.2**

**Platform: Ubuntu**

### [REQUIRED] Test case

  $> VITE (VUE3) start app , config VueFire with  auth and hosting
  $> firebase experiments:enabled webframeworks
  $> firebase init hosting auth

### [REQUIRED] Steps to reproduce

  $> firebase emulators: start => ERRORS BUT
  $> firebase deploy => deploys OK with folowinf MSG (from Vite 5.0)
      "The CJS build of Vite's Node API is deprecated. See 
              https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated
       for more details."

### [REQUIRED] Expected behavior

  No more CJS (node require) in firebase code

### [REQUIRED] Actual behavior

      "The CJS build of Vite's Node API is deprecated. See 
              https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated
       for more details."

** MY firebase.json file;** see *rewrites* following Vite instructions for FireBase Deploy.
```firebase.json
{
  "hosting": {
    "source": ".",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "frameworksBackend": {
      "region": "us-east1"
    },
    "site": "g2ato-v3p1-fb",
    "rewrites": [{
      "source": "**",
      "destination": "/index.html"
    }],
    "redirects": [],
    "headers": [{
        "source": "**/*.[jt]s",
        "headers": [{
            "key": "Set-Cookie",
            "value": "__FIREBASE_DEFAULTS__=xxx...;"
     }],
    "cleanUrls": true,
    "webFramework": "vite"
  },
  "emulators": {
    "hosting": {
      "port": 5000
    },
    "singleProjectMode": true
  }
}
```

**Comment by leoortizz** [comment]
Hey @lcsd I created a PR to fix the warning in #6660.

However, note that at the moment this is just a warning from Vite that should not break the build: https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated.  It will only be removed in Vite 6, so as the current version is 5, everything should still work with CJS. I suspect the error you're getting with `firebase emulators:start` is something else, can you please double check?

**Comment by AdielCohen** [comment]
I did everything in:
https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated
And it didn't fix the problem.

I created new project with vite + REACT+ Typescript SWC (npm create vite@latest) And after that, I did deploy with Firebase
And I got two responses from terminal:

"The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details."
"While this integration is maintained by Googlers it is not a supported Firebase product.
Issues filed on GitHub will be addressed on a best-effort basis by maintainers and other community members."

**Comment by leoortizz** [comment]
> I did everything in: https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated And it didn't fix the problem.
> 
> I created new project with vite + REACT+ Typescript SWC (npm create vite@latest) And after that, I did deploy with Firebase And I got two responses from terminal:
> 
> "The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details." "While this integration is maintained by Googlers it is not a supported Firebase product. Issues filed on GitHub will be addressed on a best-effort basis by maintainers and other community members."

Hey @AdielCohen, note that this is just a warning that should not break anything in your app. As soon as we merge and release #6660 the warning will be gone.

**Comment by AdielCohen** [comment]
> > I did everything in: https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated And it didn't fix the problem.
> > I created new project with vite + REACT+ Typescript SWC (npm create vite@latest) And after that, I did deploy with Firebase And I got two responses from terminal:
> > "The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details." "While this integration is maintained by Googlers it is not a supported Firebase product. Issues filed on GitHub will be addressed on a best-effort basis by maintainers and other community members."
> 
> Hey @AdielCohen, note that this is just a warning that should not break anything in your app. As soon as we merge and release #6660 the warning will be gone.

I see, thank you very much!
Is there an estimated month for release?
