### ISSUE TITLE
Nextjs Server Action is not working on hosting

### ISSUE THREAD

**Issue by OhDavit** [firebase/firebase-tools#6653]
### [REQUIRED] Environment info

**firebase-tools:** 13.0.2

**Platform:** macOS

### [REQUIRED] Test case

Deploying Next js app with form and server actions

### [REQUIRED] Steps to reproduce

- Create an application next js app with npx
- Add React form and Server Action as a form handler(onSubmit)
- Initiate firebase project within the existing next js app
- Deploy to hosting
- Go to the page web.app.mydomain.com/discovery, fill the form and click on submit button

### [REQUIRED] Expected behavior
Should work exactly as in the emulator, i.e. pressing Submit button calls backend function(server action) which does process request.

### [REQUIRED] Actual behavior
Pressing Submit button doesn't call backend function(server action)

**Comment by mycoberago** [comment]
I am seeing the same exact issue.

The only difference from @OhDavit is my firebase-tools is 13.0.3.

Thank you for your efforts.
