### ISSUE TITLE
Firebase Deploy Throws Failed To Configure Trigger Error

### ISSUE THREAD

**Issue by dylanrandle** [firebase/firebase-tools#6655]
### [REQUIRED] Environment info

**firebase-tools:** 13.0.2

**Platform:** macOS, Ubuntu

### [REQUIRED] Test case

Create `index.ts` with a multitude (e.g. 50) of Firestore-triggered functions. 
```index.ts

import * as functions from 'firebase-functions';

exports.onUserCreate = functions.firestore
  .document('users/{userId}')
  .onCreate(() => console.log('Invoked user document onCreate'))

exports.onUserUpdate = functions.firestore
  .document('users/{userId}')
  .onUpdate(() => console.log('Invoked user document onUpdate'))

exports.onUserDelete = functions.firestore
  .document('users/{userId}')
  .onDelete(() => console.log('Invoked user document onDelete'))

// I have ~50 functions exported from index.ts

exports.onNotificationCreate = functions.firestore
  .document('notifications/{notificationId}')
  .onCreate(() => console.log('Invoked notification document onCreate'))

exports.onNotificationUpdate = functions.firestore
  .document('notifications/{notificationId}')
  .onUpdate(() => console.log('Invoked notification document onUpdate'))

exports.onNotificationDelete = functions.firestore
  .document('notifications/{notificationId}')
  .onDelete(() => console.log('Invoked notification document onDelete'))
```

### [REQUIRED] Steps to reproduce

`firebase deploy`

### [REQUIRED] Expected behavior

Successful deployment of functions

### [REQUIRED] Actual behavior

Each time I run `firebase deploy`, a different subset of the functions fail to deploy with a `Failed to configure trigger` error. I have now run 11 times over 3 days and the deployment has never succeeded for all functions. I have tried running `firebase deploy` from both my local machine (macOS) and from a remote runner (Ubuntu) against two different projects (dev and staging) with the same results. 

```bash
# run 1

✔  functions[onUserUpdate(us-central1)] Successful update operation.
✔  functions[onUserDelete(us-central1)] Successful update operation.
Failed to configure trigger for event-type:providers/cloud.firestore/eventTypes/document.create resource:projects/test-project/databases/(default)/documents/users/{userId} service:firestore.googleapis.com.

# ... logs for the remaining functions are omitted

✔  functions[onNotificationCreate(us-central1)] Successful update operation.
Failed to configure trigger for event-type:providers/cloud.firestore/eventTypes/document.delete resource:projects/test-project/databases/(default)/documents/notifications/{notificationId} service:firestore.googleapis.com.
✔  functions[onNotificationUpdate(us-central1)] Successful update operation.
```

```bash
# run 2

Failed to configure trigger for event-type:providers/cloud.firestore/eventTypes/document.update resource:projects/test-project/databases/(default)/documents/users/{userId} service:firestore.googleapis.com.
✔  functions[onUserCreate(us-central1)] Successful update operation.
✔  functions[onUserDelete(us-central1)] Successful update operation.

# ... logs for the remaining functions are omitted

✔  functions[onNotificationDelete(us-central1)] Successful update operation.
✔  functions[onNotificationUpdate(us-central1)] Successful update operation.
Failed to configure trigger for event-type:providers/cloud.firestore/eventTypes/document.create resource:projects/test-project/databases/(default)/documents/notifications/{notificationId} service:firestore.googleapis.com.
```

### Summary

- Each time I run `firebase deploy`, a different subset of the functions fail to deploy with a `Failed to configure trigger error`.
- The functions which throw error on deployment will change between runs of `firebase deploy`, suggesting it is not an issue with the individual function but with the `firebase deploy` command.
- I have now run 11 times over 3 days and the deployment has never succeeded for all functions. 
- I have tried running firebase deploy from both my local machine (macOS) and from a remote runner (Ubuntu) against two different projects (dev and staging) with the same results.
- I have previously encountered this issue but it usually went away after re-running 3-4 times. 
- This occurs for any of the event types `create`, `update`, `delete`. 
- This issue has been previously reported and closed but is re-occurring (see here: https://github.com/firebase/firebase-tools/issues/5429).

### Impact

- Because all the functions do not deploy successfully, `firebase deploy` returns a non-zero exit code. This causes my CI/CD pipelines to fail and blocks my ability to safely deploy in an automated fashion. 

### Discussion

- I know that the Firebase [docs](https://firebase.google.com/docs/cli#deploy_specific_functions) recommend using groups to limit deployments to 10 functions at a time, but this seems like an unnecessary hassle and should be fixed by Firebase itself. For context, refactoring my functions into groups is would cause a mass deletion of all of my existing backend functions, which itself is failing due to the size of the deployment.

**Comment by aalej** [comment]
Hi @dylanrandle, sorry you encountered this issue, and thanks for providing a detailed report. I was able to reproduce this when trying to deploy multiple Firestore-triggered functions(~50 as you mentioned).

I’ll inform our engineering team about the issue so they can take a look.

**Comment by samruston** [comment]
We're also seeing this happening right now. We are trying to deploy ~50 functions at the same time and some of them fail every time. Not only do some of the deploys fail, but some of the functions themselves end up in a broken state where they stop responding to requests. That means that Firestore trigger functions (we're using v1) miss firestore changes and those changes are lost.

This seems to be a fairly new issue as we've been deploying > 50 functions for years without problems, and have just started hitting this issue where every deploy has problems. We haven't changed our dependencies or runtime.

**Comment by Berlioz** [comment]
We've done some investigating and it seems like the error is originating in an upstream dependency. They're aware of it and are actively investigating themselves, but it seems like a nasty issue and I can't give a timeline for resolution right now. It does seem like nobody using Firestore triggers in v2 is being affected by this right now, so depending on your needs that might be a viable workaround. Wish I had better news to deliver.

**Comment by Berlioz** [comment]
The good news is that they've pretty sure they've figured out the root cause and, as it happens, were already in the process of migrating off the system which is creating Problems. The bad news is that I still don't have any kind of timeline, except Eventually.

**Comment by samruston** [comment]
@Berlioz Is it possible to give any rough timeline now? We're still experiencing the issue

**Comment by yahmad** [comment]
Also seeing this issue fairly regularly, most recently when deploying ~30 functions at once. 
An update would be appreciated.

**Comment by javabudd** [comment]
The fact that firebase let's you create X amount functions but you cannot reliably deploy those functions is a complete miss.

**Comment by abarone-btf** [comment]
Any news about this? @Berlioz
