### ISSUE TITLE
Video support NextJS 14 on Firebase

### ISSUE THREAD

**Issue by Ahmed-UPEC** [firebase/firebase-tools#6657]
### [REQUIRED] Environment info

**firebase-tools:**
latest firebase

**Platform:**
next 14.0.4

### [REQUIRED] Test case

Video upload on firebase using a Next framework

### [REQUIRED] Steps to reproduce

Init NextJS 14 project
Add any video (should be hosted on the local machine) inside the public folder
Build the project (you should have a "out") directory, this will contain the video
run firebase deploy

### [REQUIRED] Expected behavior

The video should be hosted and be accessible on the website

### [REQUIRED] Actual behavior

images are uploaded not the videos

**Comment by aalej** [comment]
Hi @Ahmed-UPEC, thanks for reaching out. Just to verify, are you using the `webframeworks` experimental feature? I’m guessing that you’re not using this feature. You can check this by running `firebase experiments:describe webframeworks` on the terminal. 

Also, could you please share your `firebase.json` and `next.config.js` file, along with code snippets showing how you’re loading the video? By any chance, if you can provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), please share it so that we can replicate the issue on our end.

**Comment by Ahmed-UPEC** [comment]
Hello there,

I am using this experimental feature.
The website is the following : https://sea-lab.web.app/

I can provide you with the full code of my project (as it's juste design
for now)
Along with the video issue I am facing another issue related to the NextJS
<Link> component you can test it by clicking on "team" you will see that
the page is loading for 4-5 min
before rendering it.
 sea-lab.zip
<https://drive.google.com/file/d/1wpm4Hi0DrR9Bs4sKrsR8tNqUeccAbXDn/view?usp=drive_web>

**Comment by aalej** [comment]
Thanks for the clarification. Regarding the code, I can’t seem to access the drive link you shared, could you change the permission so that it can be accessed and downloaded. Alternatively, you could upload the code to a GitHub repo so that we can clone it.

**Comment by Ahmed-UPEC** [comment]
https://github.com/Ahmed-UPEC/sea-lab

Here you go you should be able to clone it

- Ahmed

**Comment by leoortizz** [comment]
Hey @Ahmed-UPEC. I was investigating your issue but couldn't understand what exactly is the issue. The video is available and visible in the homepage as you can see here: https://sea-lab.web.app/

The video running on this section is being sourced from https://sea-lab.web.app/video/Gemini_Era.mp4, which is the video uploaded to Firebase Hosting:
![Screenshot 2024-02-15 at 14 28 30](https://github.com/firebase/firebase-tools/assets/83593673/0a82af15-a3fe-47a4-ad8c-cb3a379e689f)


can you clarify what exactly is the problem you see?

**Comment by Ahmed-UPEC** [comment]
Thanks for your message,

This is my view :
[image: image.png]

This is because I am using the Avast Browser. If you can fix this "bug"
that would be great but it works great on Edge or Chrome.

Thanks,
- Ahmed


Le jeu. 15 févr. 2024 à 18:30, Leonardo Ortiz ***@***.***> a
écrit :

**Comment by Ahmed-UPEC** [comment]
Thanks for your message,

This is my view :
![image](https://github.com/firebase/firebase-tools/assets/56971722/5fae36c1-4de1-4103-b753-4a8bc20ffcee)

This is because I am using the Avast Browser. If you can fix this "bug"
that would be great but it works great on Edge or Chrome.

Thanks,
- Ahmed

**Comment by leoortizz** [comment]
Hey @Ahmed-UPEC thanks for replying.

I also tried the latest version of the Avast Browser and it worked for me, I can see the video without issues:
![Screenshot 2024-02-15 at 14 49 07](https://github.com/firebase/firebase-tools/assets/83593673/e8a62795-4345-4dbc-a93b-ff793cac1ae6)


I suppose your browser might be blocking the video or the version you're using doesn't support it.  In this case there's nothing we can do. The video is correctly being uploaded to Firebase Hosting, that's all we can do. You would need to handle videos for unsupported browsers in your app code.

**Comment by Ahmed-UPEC** [comment]
Okay Thanks,

I guess it was on my side, in the mean time I will try to update my browser but thanks for your time and the Firebase support team.

- Ahmed
