### ISSUE TITLE
 MongoNetworkError: failed to connect to server

### ISSUE THREAD

**Issue by azhariemuhammad** [firebase/firebase-tools#666]
Hi, Firebase team
I use firebase functions for my backend Apolo server. When i tried to make query. It got me MongoNetworkErro: failed to connect to server. 
`

MongoNetworkError: failed to connect to server [cluster0-shard-00-02-4ut9u.mongodb.net:27017] on first connect [MongoNetworkError: getaddrinfo ENOTFOUND cluster0-shard-00-02-4ut9u.mongodb.net cluster0-shard-00-02-4ut9u.mongodb.net:27017]     at Pool.<anonymous> (/user_code/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:503:11)     at emitOne (events.js:96:13)     at Pool.emit (events.js:188:7)     at Connection.<anonymous> (/user_code/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:326:12)     at Connection.g (events.js:292:16)     at emitTwo (events.js:106:13)     at Connection.emit (events.js:191:7)     at TLSSocket.<anonymous> (/user_code/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:245:50)     at TLSSocket.g (events.js:292:16)     at emitOne (events.js:96:13)     at TLSSocket.emit (events.js:188:7)     at connectErrorNT (net.js:1025:8)     at _combinedTickCallback (internal/process/next_tick.js:80:11)     at process._tickDomainCallback (internal/process/next_tick.js:128:9) |  
-- | --

`

Is there any problem with cloud functions for firebase and mongo Altas. Thanks?

**Comment by laurenzlong** [comment]
Closing since issues template was not followed

**Comment by psonhoang** [comment]
im facing the same problem and i cant seem to find a solution anywhere
