### ISSUE TITLE
Speed up recursive deletes

### ISSUE THREAD

**Issue by samtstern** [firebase/firebase-tools#667]
Currently we do:

  * Query for a batch
  * Delete the batch
  * Rinse
  * Repeat

I am told this is unnecessarily slow.  Instead we should:

  * Add pagination to the query
  * Delete individual docs, not batches
  * Allow parallel deletes up to a fairly high number

**Comment by samtstern** [comment]
One question: how do we deal with deletes that fail along the way?  Keep a list to retry?

**Comment by merlinnot** [comment]
So... I actually wanted to contribute a little, 'cause I'm deleting a massive collection right now and I wrote a script to do it efficiently, but then I've learned thet you're using rest API, which I have no intention to learn. Instead I can post my script here, maybe someone will find it useful.

I've also learned that streaming is faster than pagination.

```ts
import * as admin from 'firebase-admin';
import * as async from 'async';
import { QueryDocumentSnapshot, FieldPath } from '@google-cloud/firestore';

admin.initializeApp();

const db = admin.firestore();
const logsCollectionsRef = db.collection('logs');
let added = 0;
let deleted = 0;

setInterval(() => {
  console.log(
    `${added}, ${deleted}, ${added !== 0 ? (deleted / added) * 100 : 0}%`
  );
}, 1000);

const deleteLog = async (id: string) => {
  try {
    await logsCollectionsRef.doc(id).delete();
  } catch {
    console.log(`${id} failed, retrying.`);
    deleteQueue.push(id);
  }
  deleted++;
};

const DELETE_PARALLEL_LIMIT = 256;
const deleteQueue = async.queue(deleteLog, DELETE_PARALLEL_LIMIT);

const fillQueue = (startAfter?: any) => {
  let lastDocSnapshot: any;
  let query = db.collection('logs').orderBy(FieldPath.documentId());
  if (startAfter !== undefined) {
    query = query.startAfter(startAfter);
  }
  query
    .select()
    .stream()
    .on('data', (snapshot: QueryDocumentSnapshot) => {
      lastDocSnapshot = snapshot;
      deleteQueue.push(snapshot.id);
      added++;
    })
    .on('error', () => fillQueue(lastDocSnapshot));
};

fillQueue();
```

**Comment by merlinnot** [comment]
I've observed a strange behaviour nearing 5kk entities, it looks like it deletes 99 at a time, maybe there is some requests limit (100) so we have 99 deletes + 1 for a stream?

<img width="241" alt="screen shot 2018-06-17 at 12 58 09" src="https://user-images.githubusercontent.com/10390061/41507223-7caeb152-722e-11e8-9cf5-f306937f4a59.png">

**Comment by samtstern** [comment]
@merlinnot thanks for the breakdown and snippets!  The reason we had to use the REST API is because it   allows us to do a tricky query to find deeply nested documents without having to explicitly call the "list collections" method on each document.  Since it's theoretically possible for every document in the DB to have a unique and random sub collection hierarchy, we need to be sure to catch everything.

**Comment by samtstern** [comment]
I am going to start looking at this again.

Just for a starting point (to compare against later), I was able to get about 75 docs/s with the current implementation on my workstation.

Goal would be something in the 300-400 docs/s range.  500 is the safe limit, based on how quickly we can update an index for documents with "sequential" fields.

**Comment by samtstern** [comment]
Got a prototype going that deleted 5000+ docs at ~350/s.  The thing is that in that batch I get maybe ~20 `ETIMEDOUT` failures and waiting for those to time out and retry brings the total rate down to about 200/s. 

I wonder if I could specify a shorter timeout...

**Comment by samtstern** [comment]
After a lot of help from @ryanpbrewster we got a new implementation in #917 that can easily do 5000 deletes per second!

Will be in the next release.

**Comment by merlinnot** [comment]
Tested it out on a 20kk+ collection, got 4k (~4050) deletions per second. Good job!

**Comment by samtstern** [comment]
@merlinnot nice!  Thanks for the confirmation.
