### ISSUE TITLE
getRedirectResult doesn't work with emulator

### ISSUE THREAD

**Issue by marcusx2** [firebase/firebase-tools#6671]
### Operating System

macOS

### Browser Version

Safari 16.5.2

### Firebase SDK Version

10.7.1

### Firebase SDK Product:

Auth

### Describe your project's tooling

index.html with source tag. Just javascript.

### Describe the problem

After calling signInWithRedirect using the firebase auth emulator and firebase hosting on a subdomain of firebaseapp.com as [explained here](https://firebase.google.com/docs/auth/web/redirect-best-practices#overview), and it gets redirected, and getRedirectResult is called, the error

`[blocked] The page at https://xxxxxx.firebaseapp.com/ was not allowed to display insecure content from xxxxxxxx`

is thrown.

I also tried using the hosting emulator (http://127.0.0.1:5000) to no avail. Not sure what the Auth Domain for the firebase config should be on this case, but I tried 127.0.0.1, localhost, 127.0.0.1:5000, the original xxxxxx.firebaseapp.com, nothing works.

I got everything working without the emulator. But with the emulator no luck.

### Steps and code to reproduce issue
 

I simply try to get the redirect result first. If the result is null, it means it failed, so I try to sign in with redirect. When using the firebase auth emulator and without hosting emulator, I get the error. If I use auth emulator + hosting emulator, I get an infinite loop.

```
connectAuthEmulator(auth, "http://127.0.0.1:9099");
var result = await getRedirectResult(auth);
if (!result) {
 await signInWithRedirect(auth, provider);
}
```

**Comment by dzivoing** [comment]
Same thing is happening to me it is easy to replicate just try to use Google sign in with Emulator auth. getRedirectResult doesnt return any result

**Comment by oknoorap** [comment]
It's already 2024, and still doesn't work 😢

**Comment by BenJackGill** [comment]
I am also seeing this issue. Can it be re-opened?

`signInWithPopup` and the emulator works as expected, but `signInWithRedirect` and the emultor are broken. When using `signInWithRedirect` and the emultor the result is always `null`.
