### ISSUE TITLE
After using the Hosting Emulator It stops to reflect changes in the code

### ISSUE THREAD

**Issue by LunaLu-dev** [firebase/firebase-tools#6686]
### [REQUIRED] Environment info

**firebase-tools: 13.0.3**

**Platform: Windows**

### [REQUIRED] Test case

Just using thge hosting amulator and make small changes to the code in a normal html/css/js project

### [REQUIRED] Steps to reproduce

Just using thge hosting amulator and make small changes to the code in a normal html/css/js project

### [REQUIRED] Expected behavior

To reflect my changes to my browser window

### [REQUIRED] Actual behavior

Not reflecting my changes in the code, for example if I misspelled a variable and get an error then just quickly fix it and reload the browser with the amulator on I get the same meaage and check the souce in chome dev tools and not seeing the fix, I use chrome Version 120.0.6099.217 to test my project and using vscode for my project, this has occured on all my projects.

**Comment by aalej** [comment]
Hey @Luna0424, thanks for reaching out. I’m trying to reproduce this, but so far I haven’t encountered the same behavior. Let me know if I missed anything, from what I can tell the steps to reproduce the issue are:

1. Run `firebase init hosting --project <project_id>`
1. Run `firebase init emulators`
1. Run `firebase emulators:start`
1. Open “127.0.0.1:5000” on a browser
    1. Should display the default web app
1. Make a few changes in `index.html` file
1. Reload the web page
    1. Changes should be displayed

After reloading the web page, I was able to see the changes in `index.html`. 

For us to replicate the issue and investigate what could be causing this, could provide additional information such as:
- code snippets
- detailed steps to reproduce the issue
- `firebase-debug.log` file

By any chance, if you can create a [minimal, reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example), please share it as well.

**Comment by LunaLu-dev** [comment]
Found the issue that chrome is chaching it and refuse to let go to reflect my edits
