### ISSUE TITLE
unable to detect webframework even it is installed express i my project correctly

### ISSUE THREAD

**Issue by Ajay-dhisone** [firebase/firebase-tools#6706]
### [REQUIRED] Environment info

**firebase-tools:**

**Platform:**

**Comment by aalej** [comment]
Hey @Ajay-dhisone, from what I can gather, you're encountering an issue using the webframeworks feature. For us to be able to start our initial investigation, we would need sufficient information. 

Please file a new issue and specify the details using the provided template. Thanks!
