### ISSUE TITLE
All cookies should be proxied to the hosting cloud function

### ISSUE THREAD

**Issue by iSuslov** [firebase/firebase-tools#6716]
### [REQUIRED] Environment info

**firebase-tools:** 13.0.3

**Platform:** macOS, Windows, Ubuntu 

### [REQUIRED] Test case

N/A

### [REQUIRED] Steps to reproduce

Deploy any webframeworks application, set any cookie on the client. 

### [REQUIRED] Expected behavior

Cookie should be available on server.

### [REQUIRED] Actual behavior

No cookies except `__session` are available.
You can't read cookies on server because of this code: 
https://github.com/firebase/firebase-tools/blob/2e62b7e1e5d4505c388da62f6e2a057a0c05b553/src/hosting/proxy.ts#L49-L54
filters out every cookie except `__session`

**Comment by aalej** [comment]
Hey @iSuslov,  I think the issue you reported may be similar to #6718. Only the `__session` cookie is passed through, while other cookies are stripped.  You can find the relevant documentation [here](https://firebase.google.com/docs/hosting/manage-cache#using_cookies).
