### ISSUE TITLE
Basic SvelteKit deploys, but does not work as expected

### ISSUE THREAD

**Issue by Valentin-Seehausen** [firebase/firebase-tools#6718]
### [REQUIRED] Environment info

**firebase-tools:** 13.1.0

**Platform:** macOS

### [REQUIRED] Steps to reproduce

Clone this repro and deploy to firebase: https://github.com/Valentin-Seehausen/sveltekit-firebase-test

Here is my deployment: https://svelte-test-db17e.web.app/sverdle

### [REQUIRED] Expected behavior

I would expect the Sverdle of the basic SvelteKit to work, but it does not. The cookie gets set correctly, also the network request works. It is something in the UI.

Run the repro locally, open the Sverdle, and enter "admin" (or another valid word).

### [REQUIRED] Actual behavior

Input gets send, but cookie data is not displayed. Also, the transition does not run.

Other than that, this is awesome work you do. Thanks a lot. Excited for this to work!

**Comment by jamesdaniels** [comment]
Unforunately Firebase Hosting only supports a single cookie, `__session` https://firebase.google.com/docs/hosting/manage-cache#using_cookies

**Comment by Valentin-Seehausen** [comment]
Ok, thanks. 

More about cookies:
https://firebase.google.com/docs/hosting/manage-cache#using_cookies
https://stackoverflow.com/questions/44929653/firebase-cloud-function-wont-store-cookie-named-other-than-session
