### ISSUE TITLE
Error Installing Firebase Tools on macOS

### ISSUE THREAD

**Issue by Deiyaah** [firebase/firebase-tools#6721]
### [REQUIRED] Environment info

**firebase-tools:** N/A, i.e., shows error 

**Platform:** macOS

### [REQUIRED] Test case

Installing firebase-tools on a MacBook. 

### [REQUIRED] Steps to reproduce

1. Installed [Node.js](https://nodejs.org/en) via package manager, npm installs along with it. 
2. Node.js version : 20.11.0  , npm version : 10.2.4
3. ran the following command in terminal : `npm install -g firebase-tools`
4. packages are installed
5. ran the following command in terminal : `firebase --version`
6. also ran the following command in terminal : `firebase login`

### [REQUIRED] Expected behavior

Displays the version and allows me to login

### [REQUIRED] Actual behavior

Error shown in terminal : `This tool has encountered an error. Please file a bug on Github (https://github.com/firebase/firebase-tools/) and include firepit-log.txt`

[firepit-log.txt](https://github.com/firebase/firebase-tools/files/14068277/firepit-log.txt)

**Comment by joehan** [comment]
Hey @Deiyaah - based on that error message (and presence of a firepit-log.txt file), it looks like your machine has a standalone install of firebase-tools from https://firebase.tools already on it. 
Could you try running this command to uninstall the standalone version, and then rerun `npm i -g firebase-tools`?

```
// Uninstall the standalone version
curl -sL firebase.tools | uninstall=true bash

// Then, reinstall the npm verison (might not be needed)
npm i -g firebase-tools
```

**Comment by Deiyaah** [comment]
Hi @joehan, Thanks for the quick reply! This works! 
I uninstalled the standalone version and ran this command `alias firebase="`npm config get prefix`/bin/firebase"` in the terminal, as it wasn't recognizing the command firebase. 
It's all resolved, thanks again!
