### ISSUE TITLE
Firebase website button issue please not this down

### ISSUE THREAD

**Issue by BhargavRamani45** [firebase/firebase-tools#6722]
![image](https://github.com/firebase/firebase-tools/assets/100986115/affda9fc-c207-4764-84ef-c26517060b9c)

**Comment by aalej** [comment]
Hey @BhargavRamani45, it would be best to reach out to [Firebase support](https://firebase.google.com/support/) for issues related to the Firebase website. Since the issue does not look related to `firebase-tools`, I’m going to go ahead and close this.
