### ISSUE TITLE
Firebase emulator does not recognize jest command

### ISSUE THREAD

**Issue by nguyen-vo** [firebase/firebase-tools#6723]
### Environment info

**firebase-tools:** 12.8.1

**Platform:** Windows 11 Enterprise

### Test case
firebase.json
```json
{
  "emulators": {
    "firestore": {
      "port": 8080
    },
    "pubsub": {
      "port": 8085
    },
    "ui": {
      "enabled": false
    }
  }
}
```
test.spec.ts
```typescript
it("should run this test", () => {
  expect(1+1).toEqual(2)
})
```

### Steps to reproduce
Install the following:
- node v18.14.0
- firebase-tools v12.8.1
- @types/jest v29.4.0
- ts-jest v29.0.5
- jest v29.4.2
- typescript v4.4.3

Run test with firebase emulator
```bash
firebase emulators:exec 'jest --coverage'
```

### Expected behavior
Test are executed and not throwing error "unknow option --coverage"

### Actual behavior
When we execute the test with `firebase emulator`, we get an error that says "unknown option --coverage". The test executes fine with just `jest --coverage`. However, this is not feasible for us as we directly interact with the live Firestore and PubSub resources. It looks like `jest` is not recognized when running with `firebase emulator` on Windows. Our colleagues, using Mac, do not have the issue. 

See the attached screenshot for the error
![unnamed](https://github.com/firebase/firebase-tools/assets/65175891/eeffd0ff-5b2b-456f-a302-5b16b145d465)

**Comment by aalej** [comment]
Hey @nguyen-vo, sorry to hear you encountered this issue, and thanks for the comprehensive report. I’m currently unable to reproduce this issue, though I’m using a Windows 10 machine. 

I created this [repo](https://github.com/aalej/issues-6723) using the code snippets you provided and installed the same dependencies. Could you try and see if you’re able to reproduce the issue using this? Also, if possible, could you share an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example)? It would help us narrow down if the issue is caused by `firebase-tools`, the platform used, or something else entirely.

Lastly, could you try changing `'` to `"` to see if it makes a difference in the behavior? For example:
```
firebase emulators:exec "jest --coverage"
```

**Comment by nguyen-vo** [comment]
Hi @aalej, thanks for your quickly response. I am asking my colleagues to try this on their machines and will get back to you with the result.

Regarding the MCVE. Let me try to provide you that as soon as possible

**Comment by nikhilDore** [comment]
Hi @aalej , am able to run your repo successfully and i noticed that the different is we are sending the jest command along with firebase emulators. I updated your repo with below change then am getting the same error mentioned above. 
Change :: "npm run build && firebase emulators:exec **'jest --coverage --detectOpenHandles --forceExit --passWithNoTests'** --<project ID>",


<img width="920" alt="image" src="https://github.com/firebase/firebase-tools/assets/4294344/8f240d52-207e-40a9-8b1c-6a431c7f8d9a">

**Comment by aalej** [comment]
Hi @nikhilDore, thanks for the additional info, I can reproduce the issue now as well. Could you try replacing:
```json
"npm run build && firebase emulators:exec 'jest --coverage --detectOpenHandles --forceExit --passWithNoTests' ",
```
With 
```json
"npm run build && firebase emulators:exec \"jest --coverage --detectOpenHandles --forceExit --passWithNoTests\"",
```
I tried this out locally on my machine and I got it to run the tests without any issues.

**Comment by nikhilDore** [comment]
hi @aalej , thanks, its working

**Comment by nguyen-vo** [comment]
Awesome! looks like we got the issue resolved.

Thanks for the assist @aalej. Before I close the issue, could you share some insight on the cause of the issue?

**Comment by aalej** [comment]
I'm glad to know that it's now working! I'm thinking it could be related to how Windows parses single quotes(https://stackoverflow.com/a/51090074/15394460).

**Comment by nguyen-vo** [comment]
ahh thanks @aalej, closing the issue!
