### ISSUE TITLE
npm install -g firebase-tools is failing to complete

### ISSUE THREAD

**Issue by mourjan** [firebase/firebase-tools#673]
Good day,

Below these required details please find attached the log output, 

I tried several things like clearing npm cache, re-installing node.js to latest version

### UPDATE

I ended up running the command without -g and it installed nicely and using the firebase cmd with its path

### Version info

NA

### Platform Information

using npm@5.6.0
using node@v8.9.4
Windows 7 / 64 (Windows_NT 6.1.7601)

### Steps to reproduce

fresh install of latest node.js
then
npm install -g firebase-tools

### Expected behavior

to complete

### Actual behavior

8072 warn optional SKIPPING OPTIONAL DEPENDENCY: @google-cloud/functions-emulator@1.0.0-alpha.23 (node_modules\firebase-tools\node_modules\@google-cloud\functions-emulator):
8073 warn enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into 'C:\Users\toshiba\AppData\Roaming\npm\node_modules\.staging\@google-cloud\functions-emulator-65f6d1f5'
8074 verbose enoent SKIPPING OPTIONAL DEPENDENCY: This is related to npm not being able to find a file.
8074 verbose enoent SKIPPING OPTIONAL DEPENDENCY:
8075 verbose stack Error: sha512-MJTUg1kjuLeQCJ+ccE4Vpa6kKVXkPYJ2mOCQyUuKLcLQsdrMCpBPUi8qVE6+YuaJkozeA9NusTAw3hLr8Xe5EQ== integrity checksum failed when using sha512: wanted sha512-MJTUg1kjuLeQCJ+ccE4Vpa6kKVXkPYJ2mOCQyUuKLcLQsdrMCpBPUi8qVE6+YuaJkozeA9NusTAw3hLr8Xe5EQ== but got sha512-H2KthsacABiczQvQ9Rri5tL08GEIJRRnY/2kgK/cMFP2AnI1JUYYoYg2DaiObfXSkN0HcBNwygY1iJMP5yzjAg==. (13351 bytes)
8075 verbose stack     at Transform.on (C:\Program Files\nodejs\node_modules\npm\node_modules\ssri\index.js:275:19)
8075 verbose stack     at emitNone (events.js:111:20)
8075 verbose stack     at Transform.emit (events.js:208:7)
8075 verbose stack     at endReadableNT (_stream_readable.js:1055:12)
8075 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
8075 verbose stack     at process._tickCallback (internal/process/next_tick.js:180:9)
8076 verbose cwd c:\firebase_node
8077 verbose Windows_NT 6.1.7601
8078 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "firebase-tools"
8079 verbose node v8.9.4
8080 verbose npm  v5.6.0
8081 error code EINTEGRITY
8082 error sha512-MJTUg1kjuLeQCJ+ccE4Vpa6kKVXkPYJ2mOCQyUuKLcLQsdrMCpBPUi8qVE6+YuaJkozeA9NusTAw3hLr8Xe5EQ== integrity checksum failed when using sha512: wanted sha512-MJTUg1kjuLeQCJ+ccE4Vpa6kKVXkPYJ2mOCQyUuKLcLQsdrMCpBPUi8qVE6+YuaJkozeA9NusTAw3hLr8Xe5EQ== but got sha512-H2KthsacABiczQvQ9Rri5tL08GEIJRRnY/2kgK/cMFP2AnI1JUYYoYg2DaiObfXSkN0HcBNwygY1iJMP5yzjAg==. (13351 bytes)
8083 verbose exit [ 1, true ]

**Comment by andrewheekin** [comment]
try yarn global add firebase-tools

**Comment by mourjan** [comment]
that did the trick.. it saved me a lot of hassle.. cheers
