### ISSUE TITLE
Astro - Internal Server Error

### ISSUE THREAD

**Issue by bkingsleyc** [firebase/firebase-tools#6735]
### [REQUIRED] Environment info

**firebase-tools:**
13.0.3

**Platform:**
WIndows

### [REQUIRED] Test case

I was able to get a blank system to load, but something is failing out with an astro site that I had exposed through cloud run using docker. When I tried to convert it using the settings from the working site, it allowed the load and then failed as an internal server error.

### [REQUIRED] Steps to reproduce

Converted Astro site setup for docker to go right to firebase... loads and then fails

### [REQUIRED] Expected behavior

Website is available online message on upload = ...Website is visible online

### [REQUIRED] Actual behavior

Internal Server Error

![image](https://github.com/firebase/firebase-tools/assets/15825238/60062acf-ac14-4629-8b7d-c9b4dd9e6497)

![image](https://github.com/firebase/firebase-tools/assets/15825238/938cb105-cde0-4e37-b694-e72ec8d09348)

**Comment by aalej** [comment]
Hey @bkingsleyc, I’d like to ask a few things just to get a better understanding of this report as well as to make sure we’re on the same page:

- Are you deploying your Astro app as a Docker container to Cloud Run?
- Could you elaborate what you mean by “Converted Astro site setup for docker to go right to firebase.”?
- Could you share with us the `hosting` section of your `firebase.json` file?
- Are there any error logs from the [Google Cloud console ](https://console.cloud.google.com/logs/query) that you can share? This will help us understand what could’ve caused the error.

By any chance, could you share a [minimal, reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example) that we can try deploying on our end?

**Comment by bkingsleyc** [comment]
Hey @aalej!

Sorry for the confusion.

Point 1. Are you deploying your Astro app as a Docker container to Cloud Run?

I am not. I was trying to say that I have another instance that currently works through firebase integrated with a astro docker image running on cloud run. That it works without challenges through firebase. Sorry for the confusion and please let me know if any additional elaboration is helpful.

Point 2. Could you elaborate what you mean by “Converted Astro site setup for docker to go right to firebase.”?

Sorry same as Point 1.   Converted astro site (setup for docker) to go ~ {deploy} right to firebase {hosting}


Point 3. Could you share with us the hosting section of your firebase.json file?

"hosting": {
    "target": "collaborativetechnologies",
    "source": ".",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],

Point 4. Are there any error logs from the [Google Cloud console ](https://console.cloud.google.com/logs/query)that you can share? This will help us understand what could’ve caused the error.

Yes. There was an error for 

https://www.npmjs.com/package/@iconify/react a dev dependency that should get everything it needs at build time and doesn't fail on my docker instance. When I removed it and redeployed it did load. So the problem seems to be the server looking for this package in the production instance. Additionally my research seemed to imply this is more of a dev based node module and should be loaded in to production.

![image](https://github.com/firebase/firebase-tools/assets/15825238/02bf7df6-d7e6-4fa6-8877-3b3691022fb5)

Point 5. minimal, reproducible sample

Let me know if you need one for the issue above with the dev package dependency above or the image issue below

Point 6. I am still getting errors with the images which are not loading. 

Am I allowed to use this issue or would you like me to create another? The link on the site just shows as the firebase hosting url and I do see issues in the log. The images that are not working are located in the assets/images folder vs the public folder (which seems to load fine) and all images load appropriately in the docker version.

![image](https://github.com/firebase/firebase-tools/assets/15825238/40fbe931-1e73-441f-80d6-a529a8d6aefb)

![image](https://github.com/firebase/firebase-tools/assets/15825238/732a1d38-6dd7-4637-bcaf-357173637dd2)

![image](https://github.com/firebase/firebase-tools/assets/15825238/acfda136-0d1b-4d87-941e-6fa3bd3cad3d)


I really appreciate the quick responses. Please just let me know if there is anything else you need.

**Comment by leoortizz** [comment]
@bkingsleyc can you please provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) so I can investigate the issue?

**Comment by bkingsleyc** [comment]
@leoortizz minimum steps include:

1. Create a new astro project
2. add needed firebase files
3. add folder under source named assets
4. add an image to the folder
5. Change index.astro to include the imported image component referencing the imported image
6. Deploy to firebase

index.astro 
---
import { Image } from 'astro:assets';
import pic from '../assets/bearlogo.png';
---

<html lang="en">
	<head>
		<meta charset="utf-8" />
		<link rel="icon" type="image/svg+xml" href="/favicon.svg" />
		<meta name="viewport" content="width=device-width" />
		<meta name="generator" content={Astro.generator} />
		<title>OC A</title>
	</head>
	<body>
		<h1>OC A</h1>
		<Image src={pic} alt="A description of my image." />
	</body>
</html>

**Comment by bkingsleyc** [comment]
@BenjaOliva you can always just have the images live in the public folder and not use the assets to import from under the src folder.

**Comment by bkingsleyc** [comment]
This has been resolved
