### ISSUE TITLE
Cannot login from CI system (Bitbucket Pipeline) using FIREBASE_TOKEN

### ISSUE THREAD

**Issue by ferjm** [firebase/firebase-tools#674]
### Version info

firebase-tools@3.17.4 

### Platform Information

No idea. I'm using Bitbucket's Pipelines CI. I'm guessing these are Linux machines.

### Steps to reproduce

Following the [Using with CI Systems](https://github.com/firebase/firebase-tools#using-with-ci-systems) steps, I do:

1. On my local machine, I install Firebase CLI and run `firebase login:ci` to get an access token.
2. Set the `FIREBASE_TOKEN` env var in the Bitbucket pipeline config.
3. Run the pipeline with `firebase login --token $FIREBASE_TOKEN`

### Expected behavior

Successful login.

### Actual behavior

Login fails with:

> + firebase login --token $FIREBASE_TOKEN
Error: Cannot run login in non-interactive mode. See login:ci to generate a token for use in non-interactive environments.

**Comment by ZimbiX** [comment]
You don't need to login if you already have a token ;)
