### ISSUE TITLE
Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential.

### ISSUE THREAD

**Issue by janlin002** [firebase/firebase-tools#6745]
### [REQUIRED] Environment info

Node: v18.18.2

Firebase: ^7.10.0

Next: ^13.1.2

firebase-tools: 13.0.3

Platform: MacBook Air M2 (Sonoma 14.2.1)

### [REQUIRED] Test case

`firebase deploy --only hosting`

### [REQUIRED] Steps to reproduce

1. `firebase init hosting`
2. Detected an existing Next.js codebase in the current directory, should we use this? Y
3. In which region would you like to host server-side content, if applicable? asia-east1 (Taiwan)
4. Set up automatic builds and deploys with GitHub? N
5. Firebase initialization complete!
6. `firebase deploy` (fail)

### [REQUIRED] Expected behavior

hosting will be deployed

### [REQUIRED] Actual behavior

hosting is built, but the deploiement fails with the following error :

```js
Error: An unexpected error has occurred.
```

get an error

```js
{
  "error": {
    "code": 401,
    "message": "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",
    "status": "UNAUTHENTICATED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "CREDENTIALS_MISSING",
        "domain": "googleapis.com",
        "metadata": {
          "method": "google.firebase.service.v1beta1.FirebaseProjectService.GetFirebaseProject",
          "service": "firebase.googleapis.com"
        }
      }
    ]
  }
}
```

![截圖 2024-02-06 上午11 57 16](https://github.com/firebase/firebase-tools/assets/68535430/78190662-a553-4796-9f1b-ccda9651efd1)

and add some code in pages/_document.tsx

```ts
import { Html, Head, Main, NextScript } from 'next/document';
import GlobalStyles from '../theme/globalStyles';

export default function Document() {
  return (
    <Html lang="en">
      <Head>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <script
          src="https://apis.google.com/js/platform.js"
          async
          defer
        ></script>
        <meta
          name="google-signin-client_id"
          content="SECRET.googleusercontent.com"
        ></meta>
      </Head>
      <body>
        <GlobalStyles></GlobalStyles>
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}

```

**Comment by janlin002** [comment]
Hey @joehan 
Thank you for your response. Regarding your questions, I will provide unified answers:

1. When I execute `echo $GOOGLE_APPLICATION_CREDENTIALS`, it returns nothing.
2. No, I only observed my personal account.
3. I attempted that approach, but it still didn't yield the desired outcome.
4. Yes, I am affiliated with an organization, and my permissions are set to "editor."

**Comment by joehan** [comment]
Hey @janlin002 - my best guess is that there is an workspace policy (if your using Google workspaces) or an org policy on your organization that is causing this. If you can, check the policies on your org (https://cloud.google.com/resource-manager/docs/organization-policy/creating-managing-policies#viewing_organization_policies) for anything related to OAuth or third party apps.

Unfortunately, Github is probably not he best forum to get help with this, since its related to your project settings. I recommend opening a support case (https://firebase.google.com/support/troubleshooter/contact or https://console.cloud.google.com/projectselector/support/cases if your org has a paid support plan) for this issue.
