### ISSUE TITLE
database:get command returns before all data has been flushed to file

### ISSUE THREAD

**Issue by mikejpeters** [firebase/firebase-tools#675]
### Version info

3.17.4

### Platform Information

Windows

### Steps to reproduce

Although this issue affects both CLI and proagrammatic usage, it's much easier to demonstrate programatically. Call `firebase.database.get()` on some db path containing a large amount of data (e.g. where resulting JSON is > 16000 characters):

```js
firebase.database.get('/', {
  project: 'example-project',
  output: '/some/path',
}).then(() => {
  const content = fs.readFileSync('/some/path', {encoding: 'utf8'});
  console.log(content);
});
```

### Expected behavior

The full content at the db path is logged to the console.

### Actual behavior

Only the first part of the content is logged.

I think this happens because in the code the promise is resolved as soon as the API request is complete, but there is no guarantee that the stream writes are complete because they are async.

https://github.com/firebase/firebase-tools/blob/3583b4ae61ec1954815e9c47f7cb9be1aa6585a1/commands/database-get.js#L87-L108

The promise should be resolved when the `outStream` `'finish'` event is emitted:

```js
outStream.end('\n');
...
outStream.on('finish', () => {
  resolve()
});
```

**Comment by efung** [comment]
Nice sleuthing. I'm running into this also. The workaround I mentioned in #706 won't work, since some of my child nodes would be >16kb. 

My use case is a shell script (without using any of the client SDKs). The workaround that worked for me was calling the REST API with cURL, e.g.

```
$ curl --silent https://projectid.firebaseio.com/path/to/node.json?auth=<token>
```

where `token` was the legacy database secret from the Firebase console.
