### ISSUE TITLE
The deploy quits suddenly

### ISSUE THREAD

**Issue by Shanmukhsvstp** [firebase/firebase-tools#6755]
### [REQUIRED] Environment info

13.1.0

**firebase-tools:**
Windows

**Platform:**

### [REQUIRED] Steps to reproduce

Error came while deploying my site using"firebase deploy"

### [REQUIRED] Expected behavior
The CLI quits the process suddenly
### [REQUIRED] Actual behavior

[firebase-debug.log](https://github.com/firebase/firebase-tools/files/14209613/firebase-debug.log)

**Comment by aalej** [comment]
Hey @Shanmukhsvstp, thanks for sharing your debug logs. Looking through the logs, it looks like you’re deploying quite a lot of files. A few things I’d like to ask:

1. How large are the files you’re trying to deploy? 
1. What type of files are you trying to upload? I’m seeing a couple of `.mp3` files.
1. Were you able to successfully deploy before, or does this error happen every time you deploy?
1. Could you provide additional details on the steps you took to set up your Next.js project? This will help us inwithreproducing the issue.

**Comment by Shanmukhsvstp** [comment]
Thanks for reply, actually my files were 692 mb, I was trying to deploy
from windows cmd, but when I tried deploying from github bash, it was
successful.
Thanks and regards.

**Comment by leoortizz** [comment]
Hey @Shanmukhsvstp, can you share a repository of the app you're trying to deploy so I can try to replicate it?

I tried a deployment from Windows with 1.57Gb of audio files and it worked well, I was able to deploy without any issue and the deployed app worked well.

**Comment by Shanmukhsvstp** [comment]
Please mark it as closed
