### ISSUE TITLE
2 subdomains which use web frameworks will cause `Error: listen EADDRINUSE: address already in use :::8080`

### ISSUE THREAD

**Issue by jasonrichdarmawan** [firebase/firebase-tools#6760]
How to reproduce:
1. Create 2 different applications, deploy it to different subdomains, to identical region.
2. Since we use Angular 17, change the `prerender` value from `true` to `false` in the `angular.json` file. So it will use SSR.
3. deploy with `ng deploy`.
4. The 2nd application will throw `Internal Server Error` in browser. In cloud function log, it will throw error `Error: listen EADDRINUSE: address already in use :::8080`

**Comment by DimitriTsikaridze** [comment]
I think this is mentioned in #6651
