### ISSUE TITLE
TypeError: Cannot read property 'moduleType' of undefined

### ISSUE THREAD

**Issue by a7medcomp** [firebase/firebase-tools#679]
thanks in advance :)
after deploying got error in console log 

TypeError: Cannot read property 'moduleType' of undefined

on domain app-insta.firebaseapp.com

i'm using both real-time DB and storage for app looks like insta app
 
### Version info

 "firebase --3.17.4",  

### Platform Information

 Windows

**Comment by merlinnot** [comment]
Sorry, but that’s definitely not the right place to ask this kind of questions. Could you please try on StackOverflow and close this issue? It’s most definitely not the problem with `firebase-tools`.
