### ISSUE TITLE
Help text for `firebase deploy` does not list `--token` or `--json` options

### ISSUE THREAD

**Issue by jelbourn** [firebase/firebase-tools#68]
When I run `firebase help deploy`, the output (following) does not mention the new options.

```
  Usage: deploy [options]

  deploy hosting assets and rules for the current app

  Options:

    -h, --help               output usage information
    -f, --firebase <app>     override the app specified in firebase.json
    -m, --message <message>  an optional message describing this deploy
```

**Comment by mbleigh** [comment]
The `--token` and `--json` options are global and apply to any command, and so show up when you do `firebase --help` instead. That being said, we already have a plan to make the help a little more robust for a future release, and I'll add this to the list of things to look at.

Thanks for the report!
