### ISSUE TITLE
Storage with Emulator cannot list objects or delete them (previous versions were able to list objects)

### ISSUE THREAD

**Issue by sereeena** [firebase/firebase-tools#6803]
### [REQUIRED] Environment info

firebase-tools@13.3.1

Ubuntu
go                                           go1.20.1 linux/amd64
cloud.google.com/go/storage v1.38.0

### [REQUIRED] Test case

```
package main

import (
	"context"
	"fmt"
	"os"

	"cloud.google.com/go/storage"
	"google.golang.org/api/iterator"
)

func init() {
	os.Setenv("FIREBASE_STORAGE_EMULATOR_HOST", "localhost:9000")
	os.Setenv("STORAGE_EMULATOR_HOST", "localhost:9000")
}

func check(err error) {
	if err != nil {
		panic(err)
	}
}

func main() {
	ctx := context.Background()
	
	client, err := storage.NewClient(ctx)
	check(err)
	
	w := client.Bucket("TestBucket").Object("some/object.txt").NewWriter(ctx)
	check(err)
	_, err = fmt.Fprintf(w, "This object contains text.\n")
	check(err)
	check(w.Close())
	fmt.Println("Wrote test file")

	it := client.Bucket("TestBucket").Objects(ctx, &storage.Query{
		Delimiter: "/",
		Prefix:    "some/",
	})
	for {
		attrs, err := it.Next()
		if err != nil {
			if err == iterator.Done {
				break
			}
			if err != nil {
				fmt.Println("Error listing objects: ", err)
				break
			}
		}
		fmt.Println(attrs.Name)
	}

	err = client.Bucket("TestBucket").Object("some/object.txt").Delete(ctx)
	if err != nil {
		fmt.Println("Error deleting object: ", err)
	}
}
```

### [REQUIRED] Steps to reproduce

Run the code above with accesse to a real cloud storage bucket, and then the storage emulator.

### [REQUIRED] Expected behavior

Test file appears in emulator bucket, program prints the filename of the file in the bucket and then deletes it from the bucket

### [REQUIRED] Actual behavior

Test file appears in emulator bucket, but program returns:
```
Wrote test file
Error listing objects:  storage: bucket doesn't exist
Error deleting object:  googleapi: got HTTP response code 501 with body: Not Implemented
```

I had been running a previous version of firebase-tools and cloud.google.com/go/storage and was able to list objects in buckets in the emulator, but attempting to delete objects gave me the "Not Implemented" error, so I upgraded to the latest firebase-tools and go library and now am also unable to list objects without "Bucket does not exist" error. The problem does not occur if I am using the real cloud storage and not the emulator.

**Comment by aalej** [comment]
Hey @sereeena, thanks for the detailed report. I'm trying to reproduce the issue you encountered, but so far, I haven't encountered any errors. After running the code you provided, logs indicating that the file was written and was listed are shown:
```
Wrote test file
some/object.txt
```

A few things to try here would be to upgrade the version of go you're using, and to try changing `localhost` to `127.0.0.1`. 

Also, you mentioned that you were previously able to list objects using an old version of `firebase-tools`. Could you let us know which version you were previously using?

Lastly, could you provide a few details on the steps you took to set up your Firebase Storage emulator? If you could share the `emulators` section in your `firebase.json` file, it would be helpful.

I’m using the following to try and repro the issue:
- platform: macOS 14.3
- firebase-tools: v13.3.1
- go: go version go1.22.0 darwin/amd64
- node: v20.10.0

**Comment by sereeena** [comment]
Hi @aalej, thanks for investigating, it's good news that there shouldn't be a problem, but I don't know what it is about my setup that is causing this.

I updated go (go version go1.22.0 linux/amd64), I'm running node (v20.11.1), platform (Ubuntu 20.04.5 LTS focal). I'm afraid I didn't take note of my previous firebase-tools version before I updated it. Swapping 127.0.0.1 for localhost also hasn't made any difference.

Here is my emulator setup:
```
"emulators": {
    "singleProjectMode": true,
    "ui": {
      "enabled": true,
      "port": 3000,
      "host": "0.0.0.0"
    },
    "auth": {
      "port": 9099
    },
    "firestore": {
      "port": 5000
    },
    "storage": {
      "port": 9000,
      "rules": "storage.rules"
    },
    "hosting": {
      "port": 6001
    }
  }
```
and storage.rules
```
rules_version = '2';
service firebase.storage {
  match /b/{bucket}/o {
    match /{allPaths=**} {
      allow read, write: if request.auth != null;
    }
  }
}
```

**Comment by sereeena** [comment]
Ah, I have found the problem - I thought I had updated to firebase-tools 13.3.1 via npm install, but my npm packages were being ignored because I must have installed the standalone Firebase CLI at some point (curl -sL firebase.tools | bash). 

This standalone firebase, in /usr/local/bin which reproduces the errors returns:
firebase tools --version
11.15.0

When I removed this, reinstalled firebase-tools (npm install firebase-tools -g), and restarted the emulators, I now have version 13.3.1 and everything works as expected!

Thank you for confirming it was just a setup issue on my end, and sorry about that..
