### ISSUE TITLE
`firestore:delete` gives error on local emulator in `13.3.1`

### ISSUE THREAD

**Issue by velocd** [firebase/firebase-tools#6821]
### [REQUIRED] Environment info

**firebase-tools:**

13.3.1

**Platform:**

macOS Sonoma 14.3.1

### [REQUIRED] Test case

```
npm add -g firebase-tools@13.3.1
export FIRESTORE_EMULATOR_HOST="127.0.0.1:8080"
export FIRESTORE_URL="http://127.0.0.1:8080"
```

### [REQUIRED] Steps to reproduce

```
firebase firestore:delete MyCollection --shallow --force
```

### [REQUIRED] Expected behavior

Commands:

```
npm add -g firebase-tools@13.3.0
export FIRESTORE_EMULATOR_HOST="127.0.0.1:8080"
export FIRESTORE_URL="http://127.0.0.1:8080"
firebase firestore:delete MyCollection --shallow --force
```

Output:

> You have set FIRESTORE_EMULATOR_HOST=127.0.0.1:8080, this command will execute against the Firestore Emulator running at that address.
> Deleted 1 docs (Infinity docs/s)

### [REQUIRED] Actual behavior

Output:

> You have set FIRESTORE_EMULATOR_HOST=127.0.0.1:8080, this command will execute against the Firestore Emulator running at that address.
> Error: Deletion failed. Errors: Failed to fetch documents to delete >= 3 times..

Log files:

[firebase-debug.log](https://github.com/firebase/firebase-tools/files/14425754/firebase-debug.log)
[firestore-debug.log](https://github.com/firebase/firebase-tools/files/14425755/firestore-debug.log)

**Comment by joehan** [comment]
This should be fixed by https://github.com/firebase/firebase-tools/pull/6772, which was released in 13.4.0
