### ISSUE TITLE
Ability to choose build configuration when using webframework support with angular

### ISSUE THREAD

**Issue by pdela** [firebase/firebase-tools#6844]
### [REQUIRED] Environment info

**firebase-tools: 13.4.0**

**Platform: Windows**

When using with Angular (17.1. 2) ssr:
firebase experiments:enable webframeworks
firebase deploy --only hosting:test

### [REQUIRED] Expected behavior

Give the opportunity to change the angular build configuration to use, or at least respect the default configuration as listed in Angular.json.

### [REQUIRED] Actual behavior

Doesn't allow to select a specific build configuration in Angular.
Even if the default configuration is set to "test" in Angular.json, the build and deploy occurs with the "production" configuration.

**Comment by 9kubczas4** [comment]
Hi @pdela,

The solution could be to use the FIREBASE_FRAMEWORKS_BUILD_TARGET variable.

On MacOS: FIREBASE_FRAMEWORKS_BUILD_TARGET='test' firebase deploy --only hosting
On Windows: set FIREBASE_FRAMEWORKS_BUILD_TARGET='test' firebase deploy --only hosting

Support for FIREBASE_FRAMEWORKS_BUILD_TARGET variable is already implemented in recent versions of the firebase-tools.

**Comment by 9kubczas4** [comment]
Hi @pdela,

Please let us know if the recent comment helped you.
