### ISSUE TITLE
Firestore Emulator >= 13.3.1 returns 500 for all requests when using a simple react app.

### ISSUE THREAD

**Issue by Nicien** [firebase/firebase-tools#6853]
Hello,
The firestore emulator starts returning "internal error" (500, see below) for just one of my firebase project for no obvious reason: I didn't touch the code of the client.

The project is relatively simple, it's just a react app which use `firebase/firestore/lite` and `firebase/auth`, nothing fancy, no special configuration, no hacks and no problems with the deployed app. 

So I suppose that the bug has been introduced in a recent version of firebase-tools.

Here the results after testing with different versions:

- firebase-tools: `13.3.0` (using cloud-firestore-emulator-v1.18.2.jar): ✅ 
- firebase-tools: `13.3.1` (using cloud-firestore-emulator-v1.19.1.jar) : 💥 
- firebase-tools: `13.4.0` (using cloud-firestore-emulator-v1.19.1.jar) : 💥 
- firebase-tools: `13.4.1` (using cloud-firestore-emulator-v1.19.2.jar) : 💥 

The last working version of firebase-tools in my situation is `13.3.0`

Interresting fact: The firestore Emulator UI works fine ! (http://127.0.0.1:4000/firestore)

### Environment info

firebase-tools version: `13.4.1` (using cloud-firestore-emulator-v1.19.2.jar)

Platform: `macOS`

Client: react using npm package `firebase 10.8.1`

#### 1) Create an new project

$ npm create vite@latest
✔ Project name: … firestore-bug-test
✔ Select a framework: › React
✔ Select a variant: › TypeScript + SWC

#### 2) Init firebase

$ firebase init

with Firestore + Emulators

#### 3) Add basic code

<details>

<summary>Replace `App.tsx` with this</summary>

```
import { useEffect, useState } from "react";
import "./App.css";
import { initializeApp } from "firebase/app";
import {
  getFirestore,
  connectFirestoreEmulator,
} from "firebase/firestore/lite";
import {
  getDocs,
  collection,
  query,
  orderBy,
  limit,
} from "firebase/firestore/lite";

const connectEmulators = true;

const firebaseConfig = {
  projectId: "dummy-project-id",
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);
const firestore = getFirestore(app);
// this.analytics = getAnalytics(this.app);
if (connectEmulators) {
  // connectAuthEmulator(this.auth, "http://localhost:9099");
  connectFirestoreEmulator(firestore, "localhost", 8080);
}

async function getPerfumes() {
  const perfumeRecipesCollection = collection(firestore, "perfume-recipes");

  const perfumes = await getDocs(
    query(perfumeRecipesCollection, orderBy("created", "desc"), limit(100))
  );
  return perfumes.docs.map((doc) => doc.data());
}

function App() {
  const [perfumes, setPerfumes] = useState<Array<unknown> | null>(null);
  const [fetchError, setFetchError] = useState<Error | null>();

  useEffect(() => {
    const fetchPerfumes = async () => {
      try {
        setPerfumes(await getPerfumes());
      } catch (e) {
        if (e instanceof Error) {
          setFetchError(e);
        }
        throw e;
      }
    };
    fetchPerfumes();
  }, [setPerfumes]);

  return (
    <>
      <h1>
        Test playground for issue
        <a href="https://github.com/firebase/firebase-tools/issues/6853">
          #6853
        </a>
      </h1>
      <div className="card errorAlert">
        {fetchError && <pre>{`${fetchError}`}</pre>}
      </div>

      <div className="card successAlert">
        {perfumes !== null && (
          <>{perfumes.length} perfumes successfully Fetched.</>
        )}
      </div>
    </>
  );
}

export default App;
Add a code snippet to your website: [www.paste.org](https://www.paste.org/)
```
</details>

#### Run the emulator

```
$ firebase emulators:start
$ yarn run dev
```

And the error is there: `{"error":{"code":500,"message":"Internal","status":"INTERNAL"}}` :)

### Expected behavior

Firestore emulator returns the content of the local database as usual.

### Actual behavior

The request: `POST http://localhost:8080/v1/projects/fragrance-b6af8/databases/(default)/documents:runQuery` returns `500`

Response:
```
{"error":{"code":500,"message":"Internal","status":"INTERNAL"}}
```

Content of `firestore-debug.log`:
```
Mar 08, 2024 12:20:27 AM io.gapi.emulators.netty.HttpHandler$1 onError
INFO: Exception when handling request: com/google/cloud/datastore/billing/QueryCostOrBuilder
```

[zip of full firebase logs logs.zip](https://github.com/firebase/firebase-tools/files/14531376/firebase.logs.zip)

By the way, I like firebase: especially hosting, firebase/auth and firestore :) I hope google will invest on it.

**Comment by exaby73** [comment]
Hello @Nicien. Could you provide some reproduction steps as well as a simple code sample so I may check this out?

**Comment by Nicien** [comment]
@exaby73 Good news ! I'm able to reproduce the error in a dedicated minimal project with a minimal amount of code :)

Here the steps: 

### 1) Create an new project

$ npm create vite@latest
✔ Project name: … firestore-bug-test
✔ Select a framework: › React
✔ Select a variant: › TypeScript + SWC

### 2) Init firebase

$ firebase init

with Firestore + Emulators

### 3) Add basic code

Replace `App.tsx` with the content of [this file](https://www.paste.org/flat/127274)

### Run the emulator

```
$ firebase emulators:start
$ yarn run dev
```
And the error is there: `{"error":{"code":500,"message":"Internal","status":"INTERNAL"}}` :)

@exaby73 Tell me if there is a way to help you further.

**Comment by exaby73** [comment]
@Nicien I am unable to access the file you linked. I'm getting blocked for some reason. Could you paste the file in a comment here instead? You can use [a collapsable section](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections) for the code so it's not a huge comment

**Comment by harshyyy21** [comment]
Hi @Nicien, we have found the root cause of this issue and it should be fixed in the next release. Please let me know if the issue is resolved. Will be looking out for an update!

**Comment by Nicien** [comment]
@exaby73 Done. Thx for teaching me how to use collapsable sections :)

@harshyyy21 Cool. thank you ! I'm looking forward the next release to give you feedback. (I can't use the lastest firebase from git because an obscure typescript error is preventing me from doing so`tsc --build tsconfig.publish.json`).

**Comment by Nicien** [comment]
feedback as requested: the bug disappears with the version`13.5.1` of firebase-tools :)

Thank you ! 
## ❤️
