### ISSUE TITLE
Angular SSR 17.2 feature conflicts with hosting rewrites

### ISSUE THREAD

**Issue by alexcibotari** [firebase/firebase-tools#6855]
### [REQUIRED] Environment info

**firebase-tools:** 13.4.0

**Platform:** Windows 11

### [REQUIRED] Test case

I have the next firebase.json configuration :
```json
{

"hosting": {
    "target": "example",
    "source": ".",
    "frameworksBackend": {
      "region": "europe-west1",
      "maxInstances": 1
    },
    "redirects": [
      {
        "source": "/",
        "destination": "/home",
        "type": 301
      }
    ],
    "rewrites": [
      {
        "source": "/api/**",
        "function": "api",
        "region": "europe-west6"
      }
    ]
  },

}
```

### [REQUIRED] Steps to reproduce

Perform GET request to `<firebase host>/api/users`

### [REQUIRED] Expected behavior

The request is receiving a response from the Firebase function

### [REQUIRED] Actual behavior
The request is handled by Angular SSR frameworksBackend function

**Comment by aalej** [comment]
Hey @alexcibotari, thanks for reaching out. Sorry to hear you’re encountering this issue. By any chance, would you be able to share a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) with us, or detailed steps on how you set up your Angular project? This will help us with replicating the issue.

**Comment by alexcibotari** [comment]
Hello @aalej 

The most closest example that I have at the moment

https://codesandbox.io/p/devbox/naughty-wave-x4xqrs?file=%2Fsrc%2Fapp%2Fapp.routes.ts

**Comment by leach-mrt** [comment]
I had the same issue with Next.js

**Comment by 9kubczas4** [comment]
Hi @alexcibotari,

Could you try to use the send method instead of return in the function?
Like below:

```
const expressApp = express();
expressApp.use(cors({origin: true}));

expressApp.get("/api/users", async (req, res) => {
  logger.info("users : " + JSON.stringify(req.params));
  logger.info("users : " + JSON.stringify(req.query));
  return res.send({message: "hello world"});
});

export const api = onRequest(expressApp);
```

Please let me know if it helps.

**Comment by alexcibotari** [comment]
Hello @9kubczas4 , 

the result is the same. The response is coming from the SSR function created by Firebase, and not the function associated with the path in hosting.

**Comment by 9kubczas4** [comment]
Hi @alexcibotari,

Once again I tried to reproduce this issue. I checked the logs and it looks like it works as expected.
Here is the link to the repo I've used for the tests: https://github.com/9kubczas4/rewrite.

When there is a call to `api/users` then `api` function is triggered otherwise default `ssr` function.

Firebase version: `13.11.2`
Node: v18.19.1
