### ISSUE TITLE
Next.js framework not detected in GitHub Action

### ISSUE THREAD

**Issue by deltaepsilon** [firebase/firebase-tools#6863]
### Environment info

**firebase-tools: 12.7.0**

**Platform: Ubuntu 22.04.3 LTS**

### Test case

I'm starting a fresh project with GitHub and the Next.js framework integration. I started from scratch this morning, and everything went well. I was able to deploy from my local machine and hosting picked it up.

### Steps to reproduce

1. I pushed to GitHub to make sure the integration was working and got the following error:
![image](https://github.com/firebase/firebase-tools/assets/878947/21eea148-ad25-4939-92c1-3a2f4365f0ab)

2. I added the env variable and pushed to `master`: 
![image](https://github.com/firebase/firebase-tools/assets/878947/d9c77538-70e5-4472-a10f-99a8d45b276f)

3. I got another error:
![image](https://github.com/firebase/firebase-tools/assets/878947/0d08fe6d-74fc-4b13-81d0-788df2787686)

```
Could not determine the web framework in use.
  ***
    "status": "error",
    "error": "Unable to detect the web framework in use, check firebase-debug.log for more info.\n\n\u001b[1mDocumentation:\u001b[[22](https://github.com/deltaepsilon/investor-portal/actions/runs/8214803231/job/22467610748#step:4:25)m [https://firebase.google.com/docs/hosting/frameworks/frameworks-overview\n\u001b[1mFile](https://firebase.google.com/docs/hosting/frameworks/frameworks-overview/n/u001b[1mFile) a bug:\u001b[22m https://github.com/firebase/firebase-tools/issues/new?template=bug_report.md\n\u001b[1mSubmit a feature request:\u001b[22m https://github.com/firebase/firebase-tools/issues/new?template=feature_request.md\n\nWe'd love to learn from you. Express your interest in helping us shape the future of Firebase Hosting: https://goo.gle/41enW5X"
  ***
```

4. I tried switching the `hosting.source` key to `hosting.public` in `firebase.json`. That got rid of the error, but then my site didn't deploy. I got the dreaded "index.html missing" error page.

### Expected behavior

I expected the GitHub deploy to work first try without any intervention, as I was using the default `firebase init` workflow.

### Actual behavior

I got a series of two different errors in my GitHub Actions as described above ☝️

**Comment by ibrahimtuna** [comment]
Hi,

facing same issue

**Comment by kristianbang** [comment]
Same issue here for an Astro project.
