### ISSUE TITLE
Use the pure js implementation of grpc

### ISSUE THREAD

**Issue by bil-ash** [firebase/firebase-tools#687]
Could the pure js implementation of grpc(if whatever progress the project has made is sufficient for firebase tools) be used instead of the native one. If yes, what would be the necessary changes?
Actually,this would remove the complexity involved in using grpc as a node module in various platforms.
The bigger reason is that I am trying to port firebase tools to chrome os and for that the js implementation of grpc is necessary.

**Comment by mbleigh** [comment]
The next release of the CLI (due out today or very very soon) will not depend on gRPC. Hooray!

**Comment by bil-ash** [comment]
Thanks very much.
Also would be happy if the same approach is used for the **firebase admin** node module.

**Comment by ajcrews** [comment]
@mbleigh are there plans to do this across the board?

**Comment by mbleigh** [comment]
You'd have to bring it up in an issue on that repo -- I don't think it's going to be possible there as the Cloud Firestore realtime SDK depends on gRPC explicitly.

**Comment by ajcrews** [comment]
Understood, thanks for the response!

**Comment by bil-ash** [comment]
@mbleighThanks for the response
