### ISSUE TITLE
Warning "Unhandled error cleaning up build images"

### ISSUE THREAD

**Issue by BenJackGill** [firebase/firebase-tools#6882]
### [REQUIRED] Environment info

**firebase-functions**: 4.8.0
**firebase-tools:** 13.5.1
**Ubuntu:** Latest

### [REQUIRED] Test case

Unable to provide minimal example since this is happening in Github Actions CICD.

But Firebase Functions deploy always has this warning:

> functions: Unhandled error cleaning up build images. This could result in a small monthly bill if not corrected. You can attempt to delete these images by redeploying or you can delete them manually at https://console.cloud.google.com/gcr/images/development-c46c5/us/gcf 

### [REQUIRED] Steps to reproduce

1. Create and deploy a Gen 2 Firebase Function in Github Actions CICD pipeline using `ubuntu-latest`.
2. See that some build images are not cleaned up.

Note: only some function images are there. I cannot figure out a rhyme or reason to which ones it will be. But there is always some that are not cleaned up.

The debug logs show that it is trying to cleanup `us.gcr.io` but it is not found. In artifact registry it shows `gcf-artifacts` so maybe it's trying to clean up the wrong thing?

<img width="777" alt="Screenshot 2024-03-15 at 4 41 37 pm" src="https://github.com/firebase/firebase-tools/assets/2043257/925ddb07-9d75-4e38-890d-f94b0fa24722">

Someone else also posted this very similar issue here on [Stackoverflow](https://stackoverflow.com/questions/78017985/deploying-a-function-fails-to-clean-up-build-images#comment137778426_78017985).

### [REQUIRED] Expected behavior

It should clean up the `gcf-artifacts` artifact images.

### [REQUIRED] Actual behavior

It always has some images that are not cleaned up.

Related Logs:

```
[2024-03-15T08:52:54.398Z] <<< [apiv2][status] DELETE https://artifactregistry.googleapis.com/v1beta2/projects/development-c46c5/locations/us-central1/repositories/gcf-artifacts/packages/firestoreserpgridondocumentcreated 404
[2024-03-15T08:52:54.398Z] <<< [apiv2][body] DELETE https://artifactregistry.googleapis.com/v1beta2/projects/development-c46c5/locations/us-central1/repositories/gcf-artifacts/packages/firestoreserpgridondocumentcreated {"error":{"code":404,"message":"Package \"projects/development-c46c5/locations/us-central1/repositories/gcf-artifacts/packages/firestoreserpgridondocumentcreated\" was not found.","status":"NOT_FOUND"}}
[2024-03-15T08:52:54.462Z] <<< [apiv2][status] GET https://us.gcr.io/v2/development-c46c5/gcf/us-central1/tags/list 404
[2024-03-15T08:52:54.462Z] <<< [apiv2][body] GET https://us.gcr.io/v2/development-c46c5/gcf/us-central1/tags/list {"errors":[{"code":"NAME_UNKNOWN","message":"Repository \"us.gcr.io\" not found"}]}
[2024-03-15T08:52:54.463Z] Failed docker command with error  HTTP Error: 404, Not Found {"name":"FirebaseError","children":[],"context":{"body":{"errors":[{"code":"NAME_UNKNOWN","message":"Repository \"us.gcr.io\" not found"}],"error":{"message":"Not Found"}},"response":{"statusCode":404}},"exit":1,"message":"HTTP Error: 404, Not Found","status":404}
[2024-03-15T08:52:54.563Z] >>> [apiv2][query] GET https://us.gcr.io/v2/development-c46c5/gcf/us-central1/tags/list [none]
[2024-03-15T08:52:54.678Z] <<< [apiv2][status] GET https://us.gcr.io/v2/development-c46c5/gcf/us-central1/tags/list 404
[2024-03-15T08:52:54.678Z] <<< [apiv2][body] GET https://us.gcr.io/v2/development-c46c5/gcf/us-central1/tags/list {"errors":[{"code":"NAME_UNKNOWN","message":"Repository \"us.gcr.io\" not found"}]}
[2024-03-15T08:52:54.678Z] Failed docker command with error  HTTP Error: 404, Not Found {"name":"FirebaseError","children":[],"context":{"body":{"errors":[{"code":"NAME_UNKNOWN","message":"Repository \"us.gcr.io\" not found"}],"error":{"message":"Not Found"}},"response":{"statusCode":404}},"exit":1,"message":"HTTP Error: 404, Not Found","status":404}
⚠  functions: Unhandled error cleaning up build images. This could result in a small monthly bill if not corrected. You can attempt to delete these images by redeploying or you can delete them manually at https://console.cloud.google.com/gcr/images/development-c46c5/us/gcf 
```

**Comment by inlined** [comment]
I'm able to reproduce a bug where we're attempting to delete a cache image on function deletion, which GCF does automatically now.

I'm not able to reproduce failures in function creation or updates. If you're running into the issue still after next week's release of the CLI can you reopen the bug with the debug statement and the region of your function (it's possible our map of region -> artifact registry API URL has a bug somewhere).

**Comment by inlined** [comment]
Oh, and to address a comment from OP, we still talk to Google Container Repository currently to help clean up functions containers from users who had deployed back when we used GCR (well over a year ago), but a 404 from GCR is expected and does not emit a warning.

**Comment by TroniPM** [comment]
Well, i still having this **exactly** same problem. 

```
firebase-admin: 12.1.1
firebase-functions: 5.0.1
firebase-tools: 13.10.2
windows 11: 23H2
```

My workaraound: with [GCP CLI](https://cloud.google.com/sdk/docs/install-sdk) use this command to get the full path of gcf-artifacts at variable 'name': `gcloud artifacts repositories list --format=json`. This variable 'name' should be something like "projects/PROJECT_NAME/locations/us-central?/repositories/gcf-artifacts". Than delete the repository manually with command: `gcloud artifacts repositories delete VARIABLE_NAME_HERE --async`. 

You can also create a command like `firebase deploy --only functions & gcloud artifacts repositories delete VARIABLE_NAME_HERE --async` to make it easier/faster. Just putting this here to help somebody in the future.

**Comment by Youngjun97** [comment]
I'm also having the same issue.

**Comment by Hibrix-net** [comment]
Same here,
I believe this should be corrected somehow from the package itself since it seems to be related with the recent deprecation of the Container Registry in favour of the Artifact Registry, but who knows...

**Comment by tksoh** [comment]
I'm having the same problem on Windows 11 with

    "firebase-admin": "^12.3.1",
    "firebase-functions": "^5.0.1"

**Comment by jonsmirl** [comment]
Same problem on Ubuntu
    "firebase-admin": "^12.3.0",
    "firebase-functions": "^5.0.1"

$ firebase --version
13.15.2

~~~
i  functions: cleaning up build files...
⚠  functions: Unhandled error cleaning up build images. This could result in a small monthly bill if not corrected. You can attempt to delete these images by redeploying or you can delete them manually at
~~~

**Comment by noah-wardlow** [comment]
Same problem

**Comment by tksoh** [comment]
The problem for this issue is that it has been closed, so it's probably ignored by devs. How do we reopen this? Or need to open a new issue?

**Comment by Trashpants** [comment]
Also seeing this in a brand new project with a helloWorld functions project / brand new test firebase project (Blaze).

interestingly when I swapped my region from default (`us-cental1` Iowa) to `europe-west3`, I had the same error appear but in `us-central1` only the `_cache` folder remains, but in `europe-west3` 2 folders remain

<img width="542" alt="Screenshot 2024-08-18 at 16 09 02" src="https://github.com/user-attachments/assets/5e3f1a41-3fba-4730-8d0a-06495337dc26">
<img width="742" alt="Screenshot 2024-08-18 at 16 13 28" src="https://github.com/user-attachments/assets/df110d46-8d24-43a2-ab0a-87b62e58236d">

**Comment by jacsamg** [comment]
Same problem in new project :c

**Comment by ViniciusPilati2005** [comment]
even manually cleaning the folders, the problem remains here too

**Comment by aktkro** [comment]
Same problem.
It has remained unresolved since April last year.

**Comment by amosjohnlong** [comment]
I'm seeing the same problem. Even if I manually delete registry file, when I redeploy, I still see the Unhandled error.

**Comment by mrtawil** [comment]
+1

**Comment by ItsTeccs** [comment]
Just got this error which caused me to stumble upon this issue. I did the basic tutorial for cloud functions in TypeScript and simply uncommented the sample code in the `index.ts` function and that was enough to cause this build error. Manually cleaning up artifacts in artifact registry and re-deploying does not fix the issue.

Versions:
npm 9.2.0
node 18.19.1
firebase 13.29.2

**Comment by Meyssam120** [comment]
I am having the same error, nearly for 2 years now... in all my projects

**Comment by ulver2812** [comment]
Just had the same problem, it really impact on monthly billing or we can just ignore it?

**Comment by engraveocean** [comment]
why this closed ... .it really blocked me to use the firebase function, I can't user firebase anymore in this case
the same problem last for years .....

**Comment by inlined** [comment]
@engraveocean It's a warning message and doesn't block anything. This week's release should completely revamp this process to use a declarative policy, which will get rid of the error message.

**Comment by jacsamg** [comment]
> [@engraveocean](https://github.com/engraveocean) It's a warning message and doesn't block anything. This week's release should completely revamp this process to use a declarative policy, which will get rid of the error message.

Thanks for the news, we'll be waiting for the update.

**Comment by Hibrix-net** [comment]
> [@engraveocean](https://github.com/engraveocean) It's a warning message and doesn't block anything. This week's release should completely revamp this process to use a declarative policy, which will get rid of the error message.

Will the revamp finally allow automatic cleanup of the gfc-artifacts folder after functions deployment, which was the original issue raised in this thread? I'm not referring to just removing the warning message, but actually resolving the underlying problem.

**Comment by arnab** [comment]
@inlined this warning is till appearing functions deploys. Do you know when it will be fixed?

Also, like @Hibrix-net , will it actually automatically clean up artifacts, or just suppress the warning?

**Comment by engraveocean** [comment]
@inlined thanks and sorry for the late reply

**Comment by philipbel** [comment]
> > [@engraveocean](https://github.com/engraveocean) It's a warning message and doesn't block anything. This week's release should completely revamp this process to use a declarative policy, which will get rid of the error message.
> 
> Finally, after a very long wait, I just saw that the new command has been added in [v13.35.0](https://github.com/firebase/firebase-tools/releases/tag/v13.35.0)
> 
> Many thanks!

Thanks for pointing this out!

Unfortunately, it doesn't solve the problem

```bash
% firebase functions:artifacts:setpolicy
i  You are about to set up a cleanup policy for Cloud Run functions container images in location us-central1
i  This policy will automatically delete container images that are older than 1 days
i  This helps reduce storage costs by removing old container images that are no longer needed
? Do you want to continue? Yes
✔  Successfully set up cleanup policy that deletes images older than 1 days
i  Cleanup policy has been set for projects/PROJECT/locations/us-central1/repositories/gcf-artifacts

% firebase deploy --only functions
[...]
i  functions: cleaning up build files...
⚠  functions: Unhandled error cleaning up build images. This could result in a small monthly bill if not corrected. You can attempt to delete these images by redeploying or you can delete them manually at https://console.cloud.google.com/gcr/images/PROJECT/us/gcf

✔  Deploy complete!
```
