### ISSUE TITLE
I Can't Deploy Using firebase deploy

### ISSUE THREAD

**Issue by shadow1349** [firebase/firebase-tools#689]
### Version info

Firebase Version: 3.17.4

### Platform Information

OS X and Linux

### Steps to reproduce

What I did was create a CI token using the firebase cli by doing firebase login:ci

Now I can't deploy without a token, even though I've logged out and logged back in multiple times, I have also tried going to https://myaccount.google.com/permissions and removed permission then logged in again.

### Expected behavior

When I run firebase deploy for my functions I should be able to deploy them.

### Actual behavior
```
firebase deploy --only functions
Error: An unexpected error has occurred.

[debug] [2018-03-07T07:26:18.988Z] Error: Firebase.authWithCustomToken failed: First argument must be a valid credential (a string).
    at ng (/usr/local/lib/node_modules/firebase-tools/node_modules/firebase/lib/firebase-node.js:129:313)
    at X.gg (/usr/local/lib/node_modules/firebase-tools/node_modules/firebase/lib/firebase-node.js:266:131)
    at /usr/local/lib/node_modules/firebase-tools/lib/acquireRefs.js:19:19
    at initializePromise (/usr/local/lib/node_modules/firebase-tools/node_modules/rsvp/dist/rsvp.js:567:5)
    at new Promise (/usr/local/lib/node_modules/firebase-tools/node_modules/rsvp/dist/rsvp.js:1039:33)
    at /usr/local/lib/node_modules/firebase-tools/lib/acquireRefs.js:12:12
    at tryCatch (/usr/local/lib/node_modules/firebase-tools/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/usr/local/lib/node_modules/firebase-tools/node_modules/rsvp/dist/rsvp.js:538:13)
    at publish (/usr/local/lib/node_modules/firebase-tools/node_modules/rsvp/dist/rsvp.js:508:7)
    at flush (/usr/local/lib/node_modules/firebase-tools/node_modules/rsvp/dist/rsvp.js:2415:5)
[error] 
[error] Error: An unexpected error has occurred.
```

**Comment by zholmes1** [comment]
Same exact issue here. Can't deploy Functions. 

Error: Firebase.authWithCustomToken failed: First argument must be a valid credential (a string).

firebase-tools 3.17.4
node 9.3.0

**Comment by progone** [comment]
If you are having the same error I once had.  Go into Firebase Console, check your usage under storage.  I was over my free 1gb.  Are you over the limit? 

Once I changed my plan; the token error went away.

**Comment by youbastard** [comment]
I've been having this same issue since Monday. 

@shadow1349 I am on a blaze plan and only using 55 MB of storage so I don't believe that is the issue

**Comment by mgenti** [comment]
Just had the same issue but a `firebase login --reauth` made it start working again for me

**Comment by mbleigh** [comment]
Anyone experiencing this issue persistently (on a Mac/Linux device), please
try the following:

1. Run `firebase deploy`, ensure the error is still happening
2. Run `cat ~/.config/configstore/firebase-tools.json`
3. Copy the "access_token" from the "tokens" field of the JSON file
4. Run `curl -i --header "Authorization: Bearer <TOKEN>"
https://admin.firebase.com/v1/database/<PROJECT_ID>/tokens`
5. Send the response you get to my email directly (DO NOT reply to the
whole group).

Thanks!

**Comment by blvckf0x** [comment]
after command firebase deploy it stuck on hosting section.
what to do ??

**Comment by VisheshSingh** [comment]
I am also facing issue with deploying: I used all the commands as mentioned in the official doc. But when I visit the generated URL. It shows me a screen with this message: "You're seeing this because you've successfully setup Firebase Hosting. Now it's time to go build something extraordinary!"

**Comment by kode-xyz** [comment]
Am having the same problem --reauth doesn't seem to work

**Comment by uzuhara-ryonosuke** [comment]
i just had the following error and have tried deploy over and over but doesn't work at all.
please let me have some solutions..
=== Deploying to 'firendlychat-d1c40'...

i  deploying database, storage, functions, hosting

Error: An unexpected error has occurred.

**Comment by ridgekimani** [comment]
Make sure you are running the latest version of firebase tools. You can do that by re-installing firebase tools.
`npm install -g firebase-tools`

**Comment by uzuhara-ryonosuke** [comment]
doesnt seem work

**Comment by ridgekimani** [comment]
You can also check the firebase plan that you are currently having. Maybe you have exhausted the free storage.

**Comment by ridgekimani** [comment]
If you are on free plan, you can check if the storage is exhausted. From there you can select a plan.

**Comment by uzuhara-ryonosuke** [comment]
Have my prob done finally.
the cause is,i jsut put database-rules.json and storage.json on another directory...

**Comment by AbdulmalekAlshugaa** [comment]
Just change the funications.json to this line of codes and everything will work pretty fine 
 "npm --prefix functions run lint",
"npm --prefix functions run build"

**Comment by jagabs** [comment]
Error: HTTP Error: 500, Internal error encountered.
firebase-tools 6.3.1

 "body": {
    "error": {
      "code": 500,
      "message": "Internal error encountered.",
      "status": "INTERNAL"
    }
  },
  "response": {
    "statusCode": 500,
    "body": {
      "error": {
        "code": 500,
        "message": "Internal error encountered.",
        "status": "INTERNAL"
      }
    },
    "headers": {
      "vary": "X-Origin, Referer, Origin,Accept-Encoding",
      "content-type": "application/json; charset=UTF-8",
      "date": "Wed, 06 Feb 2019 10:03:15 GMT",
      "server": "ESF",
      "cache-control": "private",
      "x-xss-protection": "1; mode=block",
      "x-frame-options": "SAMEORIGIN",
      "x-content-type-options": "nosniff",
      "alt-svc": "quic=\":443\"; ma=2592000; v=\"44,43,39\"",
      "accept-ranges": "none",
      "transfer-encoding": "chunked"
    },

**Comment by david-potgieter** [comment]
@jagabs - There is a status on the issue: https://status.firebase.google.com/incident/Hosting/19006 - so it's being looked at.

**Comment by mbleigh** [comment]
The issue should be resolved as of a couple of hours ago. Sorry for the inconvenience, folks.

**Comment by barberousse** [comment]
I am getting a `410` in response to uploading the project public directory
```
[2019-03-04T18:46:08.016Z] <<< HTTP RESPONSE 410 server=nginx, date=Mon, 04 Mar 2019 18:46:07 GMT, content-type=application/json; charset=utf-8, content-length=240, connection=close, access-control-allow-origin=*, access-control-allow-methods=GET, PUT, POST, DELETE, OPTIONS, strict-transport-security=max-age=31556926; includeSubDomains; preload
[2019-03-04T18:46:08.017Z] <<< HTTP RESPONSE BODY undefined
[2019-03-04T18:46:08.019Z] TypeError: Cannot read property 'error' of undefined
    at module.exports (/Users/benoit.barberousse/Repos/stlvl/node_modules/firebase-tools/lib/responseToError.js:10:13)
    at Request._callback (/Users/benoit.barberousse/Repos/stlvl/node_modules/firebase-tools/lib/api.js:47:25)
    at Request.self.callback (/Users/benoit.barberousse/Repos/stlvl/node_modules/request/request.js:185:22)
    at Request.emit (events.js:197:13)
    at Request.EventEmitter.emit (domain.js:446:20)
    at Request.<anonymous> (/Users/benoit.barberousse/Repos/stlvl/node_modules/request/request.js:1157:10)
    at Request.emit (events.js:197:13)
    at Request.EventEmitter.emit (domain.js:446:20)
    at IncomingMessage.<anonymous> (/Users/benoit.barberousse/Repos/stlvl/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (events.js:285:13)

Error: An unexpected error has occurred.
```

**Comment by bkendall** [comment]
@barberousse please open a new issue with all the relevant information.

**Comment by radyz** [comment]
I just started to get this error without any detail to debug possible causes

```
functions[fn-name(us-central1)]: Deployment error.
Build failed: Build error details not available
```

I've updated firebase cli to `8.0.3` with no luck. I've enabled Google Cloud Build due to an email where starting from April 20, 2020 it would be required, no luck either

**Comment by Nirali-Tech** [comment]
There was an issue deploying your functions. Verify that your project has a Google App Engine instance setup at https://console.cloud.google.com/appengine and try again. If this issue persists, please contact support.

Error: HTTP Error: 404, Could not find Application "fir-friendlychat-6292b".  Pls help guys

**Comment by pullatjunaid** [comment]
> Just had the same issue but a `firebase login --reauth` made it start working again for me

Worked for me!
