### ISSUE TITLE
Firebase Hosting

### ISSUE THREAD

**Issue by HVLoc** [firebase/firebase-tools#6897]
Please submit feature requests through our [support page](https://firebase.google.com/support/troubleshooter/report/features/).

**Comment by aalej** [comment]
Hey @HVLoc, there isn’t any information provided in this report, I’ll go ahead and close this for now. If you want to see a certain feature implemented on `firebase-tools`, could you please file a new issue and share details about the feature you want to see implemented. Thanks!
