### ISSUE TITLE
Could not determine the web framework in use.

### ISSUE THREAD

**Issue by busanTeddyBear** [firebase/firebase-tools#6954]
### [REQUIRED] Environment info

**firebase-tools : 13.6.0**

**Platform : GitHub Codespace**

### [REQUIRED] Test case

N/A

### [REQUIRED] Steps to reproduce

1. Execute `firebase emulators:start --only hosting` command.

### [REQUIRED] Expected behavior

I'm using Next.js integration.
Hosting should be emulated normally on port 5000.
Also, it runs fine on my local Windows laptop.

The contents of my firebase configuration file are as follows.
[firebase.json](https://github.com/firebase/firebase-tools/files/14846436/firebase.json)

### [REQUIRED] Actual behavior

```
i  emulators: Starting emulators: hosting
Could not determine the web framework in use.
i  emulators: Shutting down emulators.
i  hub: Stopping emulator hub

Error: Unable to detect the web framework in use, check firebase-debug.log for more info.
```

※ The error message tells me to refer to the log file, but the log file was not created.

**Comment by aalej** [comment]
Hey @busanTeddyBear, thanks for reaching out. I'm trying to reproduce this issue using GitHub Codespaces, but so far I haven't encountered any errors when starting the emulators. Could you try adding the `--debug` option when running the emulators, for example `firebase emulators:start --only hosting --debug`, this should generate a firebase-debug.log or at least show additional information on what could’ve caused the issue. Please share those logs with us.

Also, could you provide additional details on the steps you took to set up your Next.js project? This will help us accurately reproduce the issue.

**Comment by busanTeddyBear** [comment]
Thank you for your reply.
I have solved the problem.

I made a very basic mistake.

I did not run `npm install` inside the hosting directory 😂
