### ISSUE TITLE
Deploy from https://shell.cloud.google.com/  -> ERROR

### ISSUE THREAD

**Issue by dirif25non-partage** [firebase/firebase-tools#6967]
With a simple project created with ng new.

firebase deploy ran fine but then I got :
Ce site est inaccessible

It means "Can't access website".

### [REQUIRED] Environment info

**firebase-tools:**

**Platform:**

**Comment by aalej** [comment]
Hey @dirif25non-partage. For us to be able to properly investigate what caused this, as well as to properly reproduce the issue, we would need other information. Could you please file a new report and specify the details using the provided template? 

Please include the steps you took to setup your Angular project, and the steps you took to initialize Firebase in your local project directory. That being said, I’ll be closing this.
