### ISSUE TITLE
`runtime` field is required but was not found in firebase.json or package.json

### ISSUE THREAD

**Issue by cungminh2710** [firebase/firebase-tools#6973]
### [REQUIRED] Environment info

**firebase-tools:** 13.7.1
**firebase-functions:** 4.9.0
 

**Platform:** macOS, Ubuntu

### [REQUIRED] Test case

- Deploy existing functions after upgrade from 13.6 to 13.7.1

### [REQUIRED] Steps to reproduce

- Deploy functions in a codebase

```
{
	"functions": [
		{
			"source": "api/career-functions",
			"codebase": "career-functions",
			"runtime": "nodejs18"
		},
}
```

- engines field in package.json 

```
"engines": {
		"node": "18",
		"pnpm": ">=8"
	},
```

### [REQUIRED] Expected behavior

- Deployment is successfully as usual 

### [REQUIRED] Actual behavior

![image](https://github.com/firebase/firebase-tools/assets/8063319/cda69b90-0002-4650-94e2-50dd6af2ae5b)

**Comment by aalej** [comment]
Hey folks, sorry to hear you encountered this issue. I’m currently working on reproducing this, but when trying to deploy using `firebase deploy`, deployments do not raise any errors.

To make sure we’re all on the same page here, could you verify if you have the ff setup:
- `package.json` has `engines`:
```json
 "engines": {
   "node": "18"
 },
```
- `firebase.json` has `runtime`:
```json
{
 ...
 "functions": [
   {
     ...
     "runtime": "nodejs18"
   }
 ]
}
```
It looks like the initial report has both of these specified, let me know in case this is not the set up you have.

**Comment by luc-mo** [comment]
I have created a pull request fixing the error. In fact it was a bug introduced in version 13.6.1 where the `runtime` property of the `delegateContext` object has been removed. This causes the field in the firebase.json file to be ignored.

**Comment by Zackynson** [comment]
@digibake thank you! Adding the "engines" field solved the issue here!

**Comment by cungminh2710** [comment]
> could you let us know if you also encountered this even if you have engines specified in package.json?

yeah that's correct, I have both node version in the `engines` field in the package.json and as the runtime in firebase.json
