### ISSUE TITLE
Non transactional deployments

### ISSUE THREAD

**Issue by SamyPesse** [firebase/firebase-tools#699]
When running `firebase deploy`, we are getting errors for almost 50% of our deployments, most errors are messages like `shasum check failed for /tmp/npm-20-5e3c08be/registry.npmjs.org/_40google-cloud/pubsub/-/pubsub-0.16.5.tgz`.

We can restart the deployment. But the main issue is that an error occurs during a deployment put our application in a very unstable state:

- Some functions are deployed to the new version
- ⚠️Some functions are still on the previous version (the one that failed)
- ⚠️ The hosting is still serving the previous version

<img width="993" alt="screen shot 2018-03-10 at 13 54 56" src="https://user-images.githubusercontent.com/845425/37242495-ae9cd2a0-246a-11e8-80ef-bbc6a68ce764.png">

It looks like `firebase deploy` upload the new assets but only mark these assets as the current version when everything succeed.

Instead if something fail, **everything** (database, functions, hosting) should be back to the previous state.

**Comment by tinaliang** [comment]
Closing as part of cleanup due to inactivity - if this is a blocker for you, please reopen this issue.

**Comment by SamyPesse** [comment]
@tinaliang It's not a blocker because we've setup some custom scripts for deployment (download previous assets to preserve previous release, deploy hosting first, deploy cloud function after), but not sure it's a good sign that we had to setup some custom deployment logic on top of firebase.

I truly think `firebase deploy` should be transactional, and rollback should be possible all at once (functions + hosting + database).

**Comment by tinaliang** [comment]
Thank you for that feedback! We currently don't support rolling back functions in the backend, which is what would have to happen before we can support transactional deploys on Firebase. Please feel free to file an issue for that using the following link: https://cloud.google.com/support/docs/issue-trackers.
