### ISSUE TITLE
Unable to move down or up the list when using the Git Bash

### ISSUE THREAD

**Issue by poanchen** [firebase/firebase-tools#700]
### Version info
Firebase version: 3.17.6 (Latest as of Mar 9, 2018)
Git Bash version: 2.15.1.2

### Platform Information
Windows 10 Home
Version 1709
OS Build 16299.248

### Steps to reproduce
1. Fire up my Git Bash on Windows machine.
2. `cd` to my firebase repo location in my machine.
3. run `firebase init`
4. It asked if I am ready to proceed, (I put Y and it moved to the next question)
5. It asked "Which Firebase CLI features do you want to setup for this folder? Please..."
6. I then tried to move down the list using my down arrow key but nothing happened. (the cursor does not move)
7. I changed back to built-in command prompt from Windows and do exactly the same thing and everything worked!

### Expected behavior
I should be able to move down or up the list using the arrow key in Git Bash while selecting an option in a list for the command `firebase init`

### Actual behavior
When I try to move down the list using the arrow key. The cursor does not move. This only happens in Git Bash, the built-in command prompt works fine.

Here is the log:
Note: no log were produced when down or up arrow key isn't working. However, this is what I got when I ran the `firebase init --debug`

```
chenb@LAPTOP-18B5PM7L MINGW64 ~/Downloads/poanchen.firebase.com
$ firebase init --debug
[2018-03-11T20:51:40.225Z] ----------------------------------------------------------------------
[2018-03-11T20:51:40.228Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\chenb\AppData\Roaming\npm\node_modules\firebase-tools\bin\firebase init --debug
[2018-03-11T20:51:40.228Z] CLI Version:   3.17.6
[2018-03-11T20:51:40.228Z] Platform:      win32
[2018-03-11T20:51:40.229Z] Node Version:  v8.9.4
[2018-03-11T20:51:40.229Z] Time:          Sun Mar 11 2018 13:51:40 GMT-0700 (Pacific Daylight Time)
[2018-03-11T20:51:40.229Z] ----------------------------------------------------------------------

[2018-03-11T20:51:40.245Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase"]
[2018-03-11T20:51:40.246Z] > authorizing via signed-in user
```

Thought might be helpful
![capture8](https://user-images.githubusercontent.com/12833803/37258354-da20ed52-2533-11e8-9aff-8eb6e466f7d9.PNG)

**Comment by BamiGorengo** [comment]
yep got the same problem.

**Comment by bkendall** [comment]
Interesting. Worth investigating. Thank you for the report.

**Comment by berhalak** [comment]
Currently I have the same issue, but it affects Windows cmd and Powershell. Tested on node 8.16 with firebase-tools 7.0.0

**Comment by triay0** [comment]
https://github.com/firebase/firebase-tools/issues/426#issuecomment-503949030

Worked for me

**Comment by samtstern** [comment]
@berhalak and @triay0 there seem to be some issues with `firebase init` today, please track #1420 for more information.

**Comment by waswrongassembled** [comment]
An update has been published for CLI version 7.0.1, and that probably includes the fix on that issue. Update the CLI to the latest version by running npm install --global firebase-tools@latest ... should work.

**Comment by MisterioRee** [comment]
Try with CMD in windows, it's works fine :)

**Comment by poanchen** [comment]
From my screenshot, it does work in CMD in the first place. However, I would imagine that there are some people also use git bash as their terminal choice. Would be nice that it would also work for them.

**Comment by apex-blaze** [comment]
This issue persists even in version 8.3.2 in GIT Bash Windows 10!!

**Comment by BrettKessler** [comment]
I'm having this issue still on 10.1.0, anyone know a fix for this because it's annoying.

**Comment by bkendall** [comment]
With the prompting from the last comment, I took a look around. The prompt here is powered by Inquirer and as it turns out, they have had this question themselves. The owner of Inquirer says that [there's nothing they can do to support git bash](https://github.com/SBoudrias/Inquirer.js/issues/921#issuecomment-657682239).

So, unfortunately, there's not much we're going to be able to do here. If one of the interactive commands are needed, I'd recommend using another terminal. Other commands should work in git bash, but it seems like init is not one of them :(
