### ISSUE TITLE
NextJS integration thinks not-found page is non-static

### ISSUE THREAD

**Issue by matthewrj** [firebase/firebase-tools#7006]
### [REQUIRED] Environment info

**firebase-tools:** 13.7.2

**Platform:** macOS

### [REQUIRED] Test case

Run `firebase deploy --only hosting` on a nextjs version `14.2.0` project.

### [REQUIRED] Steps to reproduce

Run `firebase deploy --only hosting` on a nextjs version `14.2.0` project.

### [REQUIRED] Expected behavior

No cloud function is created.

### [REQUIRED] Actual behavior

Firebase creates a cloud function for the not found page:
```
  Building a Cloud Function to run this application. This is needed due to:
   • non-static component /_not-found/page
```

This does not happen with nextjs `14.1.4` so something in `14.2.0` has changed in nextjs that causes firebase to think the not found page is non-static.

**Comment by jamesdaniels** [comment]
@leoortizz mind taking a look?
