### ISSUE TITLE
Cannot deploy Firestore Multiple Databases rule

### ISSUE THREAD

**Issue by mu-suke** [firebase/firebase-tools#7023]
### [REQUIRED] Environment info

**firebase-tools:**

firebase --version
13.7.3

**Platform:**

macOS

### [REQUIRED] Test case

Deployment with a failing firestore rules update.

### [REQUIRED] Steps to reproduce

1. Configure rules deployment settings in `firebase.json`, referring to [the official documentation](https://firebase.google.com/docs/cli#firestore-multiple-dbs).
```
  "firestore": [
    {
      "database": "default",
      "rules": "firestore.default.rules",
      "indexes": "firestore.default.indexes.json"
    },
    {
      "database": "my-project-dev",
      "rules": "firestore.dev.rules",
      "indexes": "firestore.dev.indexes.json"
    }
  ],
```

2. Execute the following command to deploy
```
$ firebase deploy --only firestore
```

### [REQUIRED] Expected behavior

Deployment is complete and the two database rules are set.

### [REQUIRED] Actual behavior

```
Error: HTTP Error: 404, Project 'my-project-name' or database 'default' does not exist.
[2024-04-20T05:10:09.554Z] Error Context: {
  "body": {
    "error": {
      "code": 404,
      "message": "Project 'my-project-name' or database 'default' does not exist.",
      "status": "NOT_FOUND"
    }
  },
  "response": {
    "statusCode": 404
  }
}

```

**Comment by aalej** [comment]
Hey @mu-suke, thanks for reporting this issue and for creating a detailed report. I was able to reproduce the error you mentioned. Let me notify our engineering team to see what we can do here.

As a workaround to unblock you from deployment, could you try changing `default` to `(default)`. I tried this out on my end and it seems to correctly deploy without any issues. My `firebase.json`:
```json
{
 "firestore": [
   {
     "database": "(default)",
     "rules": "firestore.default.rules",
     "indexes": "firestore.default.indexes.json"
   },
   {
     "database": "test-db",
     "rules": "firestore.test-db.rules",
     "indexes": "firestore.test-db.indexes.json"
   }
 ]
}
```

**Comment by joehan** [comment]
Thanks for reporting this @mu-suke.  @aalej 's suggestion should fix this for you. I think this really an issue with our docs, so I've sent out a fix for the docs that should land soon. 

If you're still running into issues after trying the suggested fix, feel free to ping this issue or open a new one.

**Comment by mu-suke** [comment]
>As a workaround to unblock you from deployment, could you try changing default to (default). I tried this out on my end and it seems to correctly deploy without any issues. My firebase.json:

Thanks for the answer!
It worked in my environment.

**Comment by jpriollaud** [comment]
Still broken
