### ISSUE TITLE
withAuthContext firestore functions cause error in emulator

### ISSUE THREAD

**Issue by Bullfrog1234** [firebase/firebase-tools#7037]
### Related issues

No related issues found.
The capability was added through the firebase/firebase-functions#1519 
 
### [REQUIRED] Version info

**node:** v20.11.0

**firebase-functions:** v4.9.0

**firebase-tools:** v13.7.2

**firebase-admin:** v12.0.0

### [REQUIRED] Test case

1. Create a new event trigger function for `onDocumentCreatedWithAuthContext` 
2. Build the code if using typescript
3. Run the emulators
4. Watch it fail to run the emulators

The error returned from firebase-tools is:

````
[warn] !  Unexpected rules runtime error: Exception in thread "main" java.lang.NullPointerException: Cannot invoke "String.length()" because "line" is null
	at com.google.firebase.rules.tools.local.server.Server.processRequestsFromInputStream(Server.java:75)
	at com.google.firebase.rules.tools.local.server.Server.start(Server.java:57)
	at com.google.firebase.rules.tools.local.FirebaseRulesTooling.main(FirebaseRulesTooling.java:81)
 {"metadata":{"emulator":{"name":"storage"},"message":"Unexpected rules runtime error: Exception in thread \"main\" java.lang.NullPointerException: Cannot invoke \"String.length()\" because \"line\" is null\r\n\tat com.google.firebase.rules.tools.local.server.Server.processRequestsFromInputStream(Server.java:75)\r\n\tat com.google.firebase.rules.tools.local.server.Server.start(Server.java:57)\r\n\tat com.google.firebase.rules.tools.local.FirebaseRulesTooling.main(FirebaseRulesTooling.java:81)\r\n"}}
[info] i  logging: Stopping Logging Emulator {"metadata":{"emulator":{"name":"logging"},"message":"Stopping Logging Emulator"}}
[error] 
[error] Error: HTTP Error: 500, [object Object]
[debug] [2024-04-13T13:44:30.399Z] Error Context: {
  "body": {
    "error": {
      "code": 500,
      "status": "UNKNOWN"
    }
  },
  "response": {
    "statusCode": 500
  }
}
````

Inspecting the java error shows the issue:
````
 Unsupported eventType: google.cloud.firestore.document.v1.created.withAuthContext; Supported ones: [google.cloud.firestore.document.v1.created, google.cloud.firestore.document.v1.deleted, google.cloud.firestore.document.v1.updated, google.cloud.firestore.document.v1.written]
````

### [REQUIRED] Steps to reproduce

As above

### [REQUIRED] Expected behavior

Either:
- Warning in the emulator output that it is not supported and not load it and continue with emulating the rest
- Emulate the new Firestore triggers (Preferred)

### [REQUIRED] Actual behavior

Errors are returned on emulator start. Have to disable new functions to get emulators to run.

### Were you able to successfully deploy your functions?

Not relevant to this error as it relates to the emulators

**Comment by blidd-google** [comment]
Hi all, I've flagged the issue to the Firestore team and we should have support for the new auth context event types in the next release. Will update this thread once we've released support. Thanks for your patience!

**Comment by Bullfrog1234** [comment]
Any news on the timeline for this?

**Comment by joehan** [comment]
@Bullfrog1234 This is in the works, we discovered some issues with our initial implementation that we're currently addressing. Unfortunately, due to upcoming code freezes for Google I/O, this will probably be a few more weeks we're able to ship it.

**Comment by Bullfrog1234** [comment]
@joehan Thanks for the update and understood about code freeze.

**Comment by Seanitzel** [comment]
Maybe in the meantime you can put a note about it in the docs, to save people's time...

**Comment by MutatedGamer** [comment]
Is there an ETA for when a release will be out? My use-case for wanting this support is I want to write unit tests for the functions that use Firebase Emulator (e.g. `firebase emulators:exec --only firestore,functions "npm run test:functions"`). Unfortunately, that's not possible if the emulator can't start ☹️

**Comment by benbrunyee** [comment]
Are there any suggested alternatives for the time being?
Local development for my web app is paused until `firebase emulators:start` works.

**Comment by bytewiz** [comment]
Same issue here using `onDocumentWrittenWithAuthContext`

**Comment by Bullfrog1234** [comment]
Hi @joehan,

I assume the code freeze is completed, so I am wishing for an update on this.

If the timeline is greater than 2 weeks from today can we follow @Seanitzel [suggestion](https://github.com/firebase/firebase-tools/issues/7037#issuecomment-2119562255) and add a note to the documentation. This will inform uses that this is not working in the emulators until it is fixed.

**Comment by ohld** [comment]
Hi @Bullfrog1234,

I still have the same issue once I add a new function that uses `onDocumentWrittenWithAuthContext`. My `firebase-tools --version` version is 13.14.2.
