### ISSUE TITLE
Error while deploying next.js to firebase

### ISSUE THREAD

**Issue by max6299** [firebase/firebase-tools#7038]
[debug] [2024-04-23T18:22:54.930Z] >>> [apiv2][query] GET https://firebasehosting.googleapis.com/v1beta1/projects/consumers-comment/sites/consumers-comment [none]
[debug] [2024-04-23T18:22:55.687Z] <<< [apiv2][status] GET https://firebasehosting.googleapis.com/v1beta1/projects/consumers-comment/sites/consumers-comment 200
[debug] [2024-04-23T18:22:55.687Z] <<< [apiv2][body] GET https://firebasehosting.googleapis.com/v1beta1/projects/consumers-comment/sites/consumers-comment {"name":"projects/consumers-comment/sites/consumers-comment","defaultUrl":"https://consumers-comment.web.app","appId":"1:455705879765:web:79d5f5c082b29372836e5c","type":"DEFAULT_SITE"}
[debug] [2024-04-23T18:22:56.439Z] Error: Source and destination must not be the same.
    at C:\Users\Ontwerp - 5\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\fs-extra\lib\util\stat.js:49:19
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[error] 
[error] Error: An unexpected error has occurred.

**Comment by aalej** [comment]
Hey @max6299, looking at the error message you shared, it seems like the issue you’re encountering is similar to https://github.com/firebase/firebase-tools/issues/7022.  A fix has been implemented in https://github.com/firebase/firebase-tools/pull/7031 and it should be available in our next release. That said, I’ll be closing this as a duplicate.

In the meantime, could you try using firebase-tools version v13.6.1 to see if this would unblock you from the issue?
