### ISSUE TITLE
Error while deploying functions: npm ERR! missing script: build

### ISSUE THREAD

**Issue by Crazometer** [firebase/firebase-tools#705]
### Version info

firebase-tools `3.17.6`
npm `5.7.1`
node `6.11.1`

### Platform Information

OS X

### Steps to reproduce

Set the predeploy hook in `firebase.json` to one of:
 - `echo $PWD`
 - `cd functions && echo $PWD`

Run `firebase deploy` or `firebase deploy --only functions`, observe the output.

### Expected behavior

In 3.17.4

```
i  deploying database, storage, functions
Running command: echo $PWD
/Users/justin/Documents/Code/web-app
✔  functions: Finished running predeploy script.

i  deploying database, storage, functions
Running command: cd functions && echo $PWD
/Users/justin/Documents/Code/web-app/functions  // cd does affect pwd
✔  functions: Finished running predeploy script.
```

### Actual behavior

in 3.17.6

```
i  deploying database, storage, functions
Running command: echo $PWD
/Users/justin/Documents/Code/web-app                // same base directory             
✔  functions: Finished running predeploy script.

i  deploying database, storage, functions
Running command: cd functions && echo $PWD
/Users/justin/Documents/Code/web-app                 // cd doesn't affect pwd
✔  functions: Finished running predeploy script.
```

The command I want to be able to run is `cd functions && npm run build`. I am unable to do this and get. 

```
i  deploying functions
Running command: cd functions && npm run build
npm ERR! missing script: build
```

As this is a change in behaviour I'm fairly sure it's a bug.

**Comment by laurenzlong** [comment]
Did you remove the "build" script from functions/package.json?

**Comment by Crazometer** [comment]
> Did you remove the "build" script from functions/package.json?

No. Running `npm install firebase-tools -g` or `npm install firebase-tools@3.17.4` is enough to make the issue appear or disappear respectively. I just checked and `3.17.5` doesn't work either.

Judging from the output I gave in the opening ticket it seems like the `cd` command isn't working. If I had to guess it would have something to do with https://github.com/firebase/firebase-tools/pull/686/files#diff-40899c176eb95d695b9ade3f9710aa51R14.

**Comment by carlosefonseca** [comment]
Still happening on 3.18.4.

**Comment by laurenzlong** [comment]
Let's consolidate comments on this to #822 (comment). Please follow my instructions on that comment for workarounds. This is a high priority bug for us to fix, unfortunately it's not straightforward.

**Comment by tinaliang** [comment]
Closing as this is using an outdated version of firebase-tools. If you're still seeing this for version ^6.0.0 please open another issue.
