### ISSUE TITLE
firebase database:get truncates output file after 1M of data

### ISSUE THREAD

**Issue by tmsoft** [firebase/firebase-tools#706]
3.17.6

OS X

### Steps to reproduce

firebase database:get /incoming --output incoming.json

### Expected behavior

Create a valid json file and not truncate

### Actual behavior

Truncates output file creating invalid json file.

**Comment by efung** [comment]
This is happening to us also. On three successive runs of `firebase database:get /path -o output.json`, here are the resulting filesizes:

```
-rw-r--r--    1 efung 707857 Mar 22 11:23 output-2.json
-rw-r--r--    1 efung 686865 Mar 22 11:24 output-3.json
-rw-r--r--    1 efung 689297 Mar 22 11:26 output-4.json
-rw-r--r--    1 efung 695057 Mar 22 11:19 output.json
```

In all cases, the output JSON was truncated.

Using `firebase-tools` 3.17.6 on Mac OS X 10.13.3, Node v6.12.3

Will try to workaround by fetching the children one at a time.

I recall this working fine in the past, i.e. being able to fetch several megabytes at once.

**Comment by efung** [comment]
Possible duplicate of #675

**Comment by wvanderdeijl** [comment]
Probably also a duplicate of #267
