### ISSUE TITLE
Next.js SSR Deployment fails due to wrong firebase-tools creating wrong folder

### ISSUE THREAD

**Issue by tobenna-wes-re** [firebase/firebase-tools#7062]
### [REQUIRED] Environment info

13.7.5

**firebase-tools:**

macOS

**Platform:**

### [REQUIRED] Test case

Deployment of Next using Firebase Webframeworks due to firebase creating wrong ssr folder

### [REQUIRED] Steps to reproduce

run `firebase deploy --only hosting` when using next.js 

### [REQUIRED] Expected behavior

<img width="319" alt="image" src="https://github.com/firebase/firebase-tools/assets/143293651/6466ad76-7692-4894-92fa-9316341c29dd">

`.next`  should be in the a sub directory of the `functions`
### [REQUIRED] Actual behavior

I get `functions.next` instead. This then leads to firebase uploading the files without the ssr files

This then leads to a server error
Error: ENOENT: no such file or directory, open '/workspace/.next/BUILD_ID'

**Comment by tobenna-wes-re** [comment]
This seems to have been introduced in 13.7.0 because 13.6.1 works.

**Comment by aalej** [comment]
Hey @tobenna-wes-re, thanks for reaching out, sorry to hear you encountered this issue. I’m currently trying to reproduce this, but so far I’m unable to replicate the behavior you mentioned. The steps I took to reproduce the issue were:

1. Run `npx create-next-app@latest my-app`
    -  Would you like to use TypeScript? No
    -  Would you like to use ESLint? No
    -  Would you like to use Tailwind CSS? No
    -  Would you like to use `src/` directory? Yes
    -  Would you like to use App Router? Yes
    - Would you like to customize the default import alias (@/*)? No
1. Run `cd my-app/`
1. Run `firebase experiments:enable webframeworks`
1. Run `firebase init hosting --project PROJECT_ID`
1. Run `firebase deploy --only hosting`
    - Successful deployment

I tried the above steps using firebase-tools v13.7.0 and v13.7.5, and no errors were raised during deployment. In case I’m missing anything here, please let me know. Also, could you provide additional details on the steps you took to set up your Next.js project?

**Comment by manabu0926** [comment]
@aalej 
https://github.com/firebase/firebase-tools/issues/7054

same issue.
environment
region: asia-east1
and, this project is multi site.

firebase.json
```
{
  "hosting": [
    {
      "target": "staging",
      "source": ".",
      "ignore": ["firebase.json", "**/.*", "**/node_modules/**"],
      "frameworksBackend": {
        "region": "asia-east1",
        "maxInstances": 2
      }
    },
    {
      "target": "production",
      "source": ".",
      "ignore": ["firebase.json", "**/.*", "**/node_modules/**"],
      "frameworksBackend": {
        "region": "asia-east1",
        "maxInstances": 3
      }
    }
  ]
}

```

maybe, similar problem.
https://github.com/firebase/firebase-tools/issues/7054

Sorry for my poor English.

**Comment by aalej** [comment]
Hey @manabu0926, #7054 seems to be a different issue. From what I can tell, the initial report here is that the Firebase CLI generates a wrong folder structure. Instead of creating `functions/.next`, it creates `functions.next`, which would cause an error. Let me know in case I misunderstood anything.

If you’re encountering an `ENOENT` error, could you provide some details on how you set up your Next.js project? I tried following the multi-site setup you have in your `firebase.json`, but I’m still unable to reproduce the error.

If you’re encountering an issue similar to #7054, could you try the workarounds provided https://github.com/firebase/firebase-tools/issues/7054#issuecomment-2082449881 and https://github.com/firebase/firebase-tools/issues/7054#issuecomment-2082459426 to see if you’d be able to deploy successfully?

**Comment by manabu0926** [comment]
> If you’re encountering an issue similar to https://github.com/firebase/firebase-tools/issues/7054, could you try the workarounds provided https://github.com/firebase/firebase-tools/issues/7054#issuecomment-2082449881 and https://github.com/firebase/firebase-tools/issues/7054#issuecomment-2082459426 to see if you’d be able to deploy successfully?

The above workaround solved my problem.

**Comment by tobenna-wes-re** [comment]
@aalej

I am using typescript.
I'm on a MacOS with M1
node version: v18.20.2
npm version: 10.5.2

This is my tsconfig.json
```
{
  "compilerOptions": {
    "module": "ES2022",
    "moduleResolution": "node",
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "outDir": "lib",
    "sourceMap": true,
    "strict": true,
    "target": "ES2022",
    "allowSyntheticDefaultImports": true
  },
  "compileOnSave": true,
  "include": ["./src", "**/*.ts"],
  "exclude": ["**/*.test.ts"]
}
```

and my firebase.json

```
{
  "firestore": {
    "rules": "firestore.rules",
    "indexes": "firestore.indexes.json"
  },
  "functions": [
    {
      "source": "functions/",
      "codebase": "default",
      "ignore": [
        "node_modules",
        "**/node_modules/**",
        ".git",
        "firebase-debug.log",
        "firebase-debug.*.log"
      ],
      "predeploy": [
        "npm --prefix \"$RESOURCE_DIR\" run lint",
        "npm --prefix \"$RESOURCE_DIR\" run build"
      ]
    }
  ],
  "hosting": {
    "source": "web/",
    "ignore": ["firebase.json", "**/.*", "**/node_modules/**"],
    "frameworksBackend": {
      "region": "us-central1"
    }
  }
}
```

**Comment by tobenna-wes-re** [comment]
> Hey @manabu0926, #7054 seems to be a different issue. From what I can tell, the initial report here is that the Firebase CLI generates a wrong folder structure. Instead of creating `functions/.next`, it creates `functions.next`, which would cause an error. Let me know in case I misunderstood anything.
> 
> If you’re encountering an `ENOENT` error, could you provide some details on how you set up your Next.js project? I tried following the multi-site setup you have in your `firebase.json`, but I’m still unable to reproduce the error.
> 
> If you’re encountering an issue similar to #7054, could you try the workarounds provided [#7054 (comment)](https://github.com/firebase/firebase-tools/issues/7054#issuecomment-2082449881) and [#7054 (comment)](https://github.com/firebase/firebase-tools/issues/7054#issuecomment-2082459426) to see if you’d be able to deploy successfully?

This is correct. Instead of creating `functions/.next`, it creates `functions.next`. It might finish deploying to functions but not all files will be uploaded correctly. So you will have the `.next` files missing in the function. I was able to figure this out be logging into gclould and noticed that the `.next` folder was absent. This only causes an error when you try to load some of the images or utilize ssr. with an internal error (due to '/workspace/.next/BUILD_ID' not found)

**Comment by jamesdaniels** [comment]
@leoortizz PTAL
