### ISSUE TITLE
There was an error deploying functions firebase deploy python with pydub

### ISSUE THREAD

**Issue by alfonsocanor** [firebase/firebase-tools#7063]
### [REQUIRED] Environment info

**firebase-tools:**  13.7.5

**Platform:** macOS

### [REQUIRED] Test case

Developer wants to use ```from pydub import AudioSegment``` in a firebase function python for Audio manipulation purposes.

### [REQUIRED] Steps to reproduce

- Create a firebase project
- Create a function python
- Add pydub dependency

Basic function example:

main.py
```
from firebase_functions import https_fn
from firebase_admin import initialize_app
from pydub import AudioSegment

initialize_app()

@https_fn.on_call()
def myfunction(req: https_fn.CallableRequest):
    return 'from myfunction'
```

### [REQUIRED] Expected behavior

Function deployed and ready to use

### [REQUIRED] Actual behavior

Unable to deploy function with pydub: Error: There was an error deploying functions

If you remove pydub the function is deployed correctly

**Comment by alfonsocanor** [comment]
Thanks for the response @aalej,

I added pydub to requirement.txt after the error started. 

I just deleted the Image, the function and override and start again and the example I shared is deployed correctly.

I'll work continue workint on it. I hope the issue was related to the requirement.txt

I appreciate your message, many thanks (L)

**Comment by aalej** [comment]
It’s good to know your deployments are now working, @alfonsocanor. For now, I'll go ahead and close this issue. If you encounter any errors, feel free to ask this to be reopened and share a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) with us so that we can continue to investigate. Thanks!
