### ISSUE TITLE
Module parse failed: Unexpected character '�' (1:2)

### ISSUE THREAD

**Issue by appalliance** [firebase/firebase-tools#7074]
### [REQUIRED] Environment info

**firebase-tools: 13.7.5
OS: Windows 11
next.js: 14.2.3

### [REQUIRED] Test case

Build the app using npm run dev.  The app builds and deploys to local host but when you navgate to the home page (localhost:3000/), you get the folllowing error:
Module parse failed: Unexpected character '�' (1:2)

### [REQUIRED] Steps to reproduce
Follow the instructions on this [page]([Integrate Firebase with a Next.js app](https://firebase.google.com/codelabs/firebase-nextjs)) 
Note: the project and authentication service have been configured in firebase. My pricing plan was upgraded to Blaze.

1. Clone the repo: https://github.com/firebase/friendlyeats-web.git
2. Change directory to /nextjs-start (or nextjs-end - both repos fail to build)
3. Run NPM install 
4. firebase login
5. Apply my project's firebase variables to .env file
6. firebase experiments:enable webframeworks
7. firebase init - take all defaults
8. firebase deploy --only firestore:rules,storage
9. npm run dev (I'm not using the emulator)

### [REQUIRED] Expected behavior

Should expect to see the home page load, but get the error message instead.

### [REQUIRED] Actual behavior

When I run npm run dev, the app builds without errors. But then when I navigate to localhost:3000, I get the following error: Module parse failed: Unexpected character '�' (1:2).   I believe this module is related to webpack: a file isn't being parsed correctly, but the error message and stack trace don't say file it failed on:

You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders

Import trace for requested module:
````
./node_modules/farmhash/build/Release/farmhash.node
./node_modules/farmhash/index.js
./node_modules/firebase-admin/lib/remote-config/condition-evaluator-internal.js
./node_modules/firebase-admin/lib/remote-config/remote-config.js
./node_modules/firebase-admin/lib/app/firebase-namespace.js
./node_modules/firebase-admin/lib/default-namespace.js
./node_modules/firebase-admin/lib/index.js
./src/lib/firebase/firebase.js
./src/lib/firebase/auth.js
./src/components/Header.jsx
````

**Comment by aalej** [comment]
Hey @appalliance, thanks for reaching out. Looking through the report, it seems like this might be an issue with the FriendlyEats (Web) codebase since it’s occurring even without using the Firebase emulators.

Could you please file an issue in the FriendlyEats codelab's [GitHub repository](https://github.com/firebase/friendlyeats-web) so that the appropriate team can investigate what’s causing this issue.

**Comment by appalliance** [comment]
Yes, I will do that.
