### ISSUE TITLE
firebase serve Error: TIMEOUT: Port 5001 on localhost was not active within 5000ms

### ISSUE THREAD

**Issue by RaheutRahwana** [firebase/firebase-tools#7091]
### [REQUIRED] Environment info

**firebase-tools:** 13.8.0

**Platform:** Debian GNU/Linux 12

**Node:** v20.12.0
**NPM:** 10.5.0

### [REQUIRED] Test case

Execute `firebase init` with Firestore, Function, Hosting and Storage enabled.

### [REQUIRED] Steps to reproduce

1. Open the command line interface (CLI).
2. Navigate to the root directory of the Firebase project.
3. Execute the command `firebase serve`.

### [REQUIRED] Expected behavior

The Firebase development server starts successfully within a reasonable time frame.

### [REQUIRED] Actual behavior

```
[info] i  hosting[foo]: Serving hosting files from: public {"metadata":{"emulator":{"name":"hosting"},"message":"Serving hosting files from: \u001b[1mpublic\u001b[22m"}}
[info] ✔  hosting[foo]: Local server: http://localhost:5000 {"metadata":{"emulator":{"name":"hosting"},"message":"Local server: \u001b[4m\u001b[1mhttp://localhost:5000\u001b[22m\u001b[24m"}}
[error] 
[error] Error: TIMEOUT: Port 5001 on localhost was not active within 5000ms
```

**Comment by aalej** [comment]
Hey folks, thanks for reaching out, sorry to hear you encountered this issue. I’m currently working on replicating this but so far I haven’t encountered any errors with starting the emulators.

Could anyone share the `emulators` section of their `firebase.json` file so that I can try to reproduce this locally? In addition, to help us narrow what could be causing the issue, could you try downgrading to firebase-tools v13.7.5 to see if you’d be able to run the emulators?

**Comment by jacklj** [comment]
We'e downgraded to `13.7.5` and seems promising so far, just running our test suite again as it could have been a fluke.

From our `firebase.json`:
```
 "emulators": {
    "auth": {
      "port": 9099
    },
    "database": {
      "port": 9000
    },
    "storage": {
      "port": 9199
    },
    "ui": {
      "enabled": true
    }
  }
```

Thanks for your help @aalej  :)

**Comment by jacklj** [comment]
> We've downgraded to 13.7.5

Yes that seems to have worked :)

**Comment by RaheutRahwana** [comment]
@aalej 
Unfortunately, I didn't enable the emulator during `firebase init` as usual.

**Comment by stanleyillidge** [comment]
Para mi tambien funciono usar la version npm i -g firebase-tools@13.7.5 de la CLI, pero tambien tuve que cambiar la variable de sistema JAVA_TOOL_OPTIONS -Xmx10240m

Thanks for your help @aalej :)
