### ISSUE TITLE
Error: An unexpected error has occurred.

### ISSUE THREAD

**Issue by coolnarend** [firebase/firebase-tools#710]
Attaching the Debug file
[firebase-debug.log](https://github.com/firebase/firebase-tools/files/1845461/firebase-debug.log)

**Comment by TheTerribleChild** [comment]
Had this exact same issue with nodejs 9.1 on Linux Mint 18.3. Using nodejs 8 works.

**Comment by laurenzlong** [comment]
Closing as it is not following issues template. There's not enough info. Please file again, and also include what your pre-existing firebase.json looks like.
