### ISSUE TITLE
`firebase serve` doesn't pick up `.runtimeconfig.json`

### ISSUE THREAD

**Issue by MLoughry** [firebase/firebase-tools#711]
### Version info

3.17.4, 3.17.7

### Platform Information

Windows 10 (10.0,6299)
NodeJS v 8.8.0

### Steps to reproduce

```
PS E:\project\functions> firebase functions:config:get > .runtimeconfig.json
PS E:\project\functions> firebase serve --only functions

=== Serving from 'E:\project'...

i  functions: Preparing to emulate functions.
Warning: You're using Node.js v8.8.0 but Google Cloud Functions only supports v6.11.1.
!  functions: Failed to load functions source code. Ensure that you have the latest SDK by running npm i --save firebase-functions inside the functions directory.
!  functions: Error from emulator. FirebaseError: Error occurred while parsing your function triggers.

TypeError: Cannot read property 'private_key' of undefined
    at Object.<anonymous> (E:\project\functions\lib\functions\src\index.js:5:97)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at C:\Users\Michael\AppData\Roaming\npm\node_modules\firebase-tools\lib\triggerParser.js:18:11
    at Object.<anonymous> (C:\Users\Michael\AppData\Roaming\npm\node_modules\firebase-tools\lib\triggerParser.js:38:3)
```

index.ts:
```ts
import * as functions from 'firebase-functions';
import * as admin from 'firebase-admin';
const cert = {
    ...functions.config().cert,
    "private_key": functions.config().cert.private_key.replace(/\\n/g, '\n'),
};

admin.initializeApp({
    ...functions.config().firebase,
    credential: admin.credential.cert(cert),
});
```

### Expected behavior

The locally-served functions would pick up the local `.runtimeconfig.json` file.

### Actual behavior

No local (or remote) config is picked up.

**Comment by MLoughry** [comment]
Updated the original issue to include that this doesn't work on 3.17.7, either.

```
PS E:\project\functions> yarn list --pattern firebase*
yarn list v1.5.1
├─ @firebase/app-types@0.1.2
├─ @firebase/app@0.1.10
├─ @firebase/database-types@0.1.2
├─ @firebase/database@0.1.11
├─ @firebase/util@0.1.10
├─ firebase-admin@5.8.2
└─ firebase-functions@0.9.1
Done in 0.27s.
PS E:\project\functions> firebase --version
3.17.7
```

**Comment by MLoughry** [comment]
I have a minimum repro for this issue: https://github.com/MLoughry/firebase-functions-serve-repro

Hitting the deployed function at https://us-central1-fir-tools-711-repro.cloudfunctions.net/helloWorld:
```
Hello, world!
```

Hitting it while serving locally:
```json
{"stack":"TypeError: Cannot read property 'message' of undefined\n    at exports.helloWorld.functions.https.onRequest (E:\\VSO\\firebase-functions-serve-repro\\functions\\lib\\index.js:7:48)\n    at cloudFunction (E:\\VSO\\firebase-functions-serve-repro\\functions\\node_modules\\firebase-functions\\lib\\providers\\https.js:37:41)\n    at app.use (C:\\Users\\Michael\\AppData\\Roaming\\npm\\node_modules\\firebase-tools\\node_modules\\@google-cloud\\functions-emulator\\src\\supervisor\\worker.js:114:11)\n    at Layer.handle [as handle_request] (C:\\Users\\Michael\\AppData\\Roaming\\npm\\node_modules\\firebase-tools\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (C:\\Users\\Michael\\AppData\\Roaming\\npm\\node_modules\\firebase-tools\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at C:\\Users\\Michael\\AppData\\Roaming\\npm\\node_modules\\firebase-tools\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (C:\\Users\\Michael\\AppData\\Roaming\\npm\\node_modules\\firebase-tools\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (C:\\Users\\Michael\\AppData\\Roaming\\npm\\node_modules\\firebase-tools\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at app.use (C:\\Users\\Michael\\AppData\\Roaming\\npm\\node_modules\\firebase-tools\\node_modules\\@google-cloud\\functions-emulator\\src\\supervisor\\worker.js:86:7)\n    at Layer.handle [as handle_request] (C:\\Users\\Michael\\AppData\\Roaming\\npm\\node_modules\\firebase-tools\\node_modules\\express\\lib\\router\\layer.js:95:5)","message":"Cannot read property 'message' of undefined","name":"TypeError"}
```

**Comment by laurenzlong** [comment]
@MLoughry I'm not sure how you created .runtimeconfig.json, but there's weird characters in front of it when you run `cat .runtimeconfig.json`: (Weird thing is that the question marks are not visible when you open it with a text editor, only when you view it within the terminal)
```
??{
  "cert": {
    "message": "Hello, world!"
  }
}
```

You test that this is an issue by launching a node repl:

```
node
// inside repl:
json = require('.runtimeconfig.json');
// get error: 
SyntaxError: /path/to/.runtimeconfig.json: Unexpected token � in JSON at position 0
```

Once I replaced your .runtimeconfig.json with another one that contained the same info, but without weird characters, both `json = require('.runtimeconfig.json')` within a Node shell worked, and `firebase serve` worked.

**Comment by amnrzv** [comment]
I've narrowed down the issue to Windows Powershell.

Running `firebase functions:config:get > .runtimeconfig.json` in powershell generates a broken json, which when parsed gives `Unexpected token � in JSON at position 0`.

I've managed to sort it out by running `.runtimeconfig.json` generation command in Windows command prompt.

Hope this helps.

**Comment by denisyilmaz** [comment]
@MLoughry  Did you find a solution for your issue?  getting the same error message

**Comment by denisyilmaz** [comment]
I'm on Mac and having same issues as @MLoughry  described. I tested the .runtimeconfig.json file if it contains the weird character which it doesn't.

**Comment by laurenzlong** [comment]
How did you go about testing it? And can you ensure that the file is in the functions folder? (not the project root folder)

**Comment by laurenzlong** [comment]
No worries! Glad you figured it out!

**Comment by gavanitrate** [comment]
@laurenzlong PowerShell is not outputting incorrect/badly formatted JSON. Instead, by default, PowerShell redirects output as UCS-2 Little Endian encoding. i assume firebase serve expects UTF-8 encoding. there's probably not much that can be done on your end. anyhow `firebase functions:config:get | ac .runtimeconfig.json` outputs UTF-8 in PowerShell.

**Comment by TingAli** [comment]
> I've narrowed down the issue to Windows Powershell.
> 
> Running `firebase functions:config:get > .runtimeconfig.json` in powershell generates a broken json, which when parsed gives `Unexpected token � in JSON at position 0`.
> 
> I've managed to sort it out by running `.runtimeconfig.json` generation command in Windows command prompt.
> 
> Hope this helps.

This solution works to this day.  Cheers
