### ISSUE TITLE
firebase deploy not working

### ISSUE THREAD

**Issue by ujjwaldeydeveloper** [firebase/firebase-tools#7152]
### [REQUIRED] Environment info

**firebase-tools:**

**Platform:**

**Comment by aalej** [comment]
Hey @ujjwaldeydeveloper. Could you please file a new issue and provide the details using the template. This would give us enough information to be able to start our initial investigation. That said, I’ll go ahead and close this. Thanks!

Also, I tried running `firebase deploy` on a fresh project with functions, hosting, and firestore. No errors were raised during deployment.
