### ISSUE TITLE
IterableIterator can only be iterated with '--downlevelIteration' flag or with 'es2015' or higher.

### ISSUE THREAD

**Issue by zaxonus** [firebase/firebase-tools#7170]
### [REQUIRED] Environment info

**firebase-tools:**
13.8.3

**Platform:**

Mac OS Sonoma 14.4.1
### [REQUIRED] Steps to reproduce

Probem described here:
https://stackoverflow.com/questions/78469901/iterableiteratorany-any-can-only-be-iterated-downleveliteration-fl?noredirect=1#comment138339270_78469901

### [REQUIRED] Expected behavior

Having no error.

### [REQUIRED] Actual behavior

Error described in the SOF post.

 ✓ Compiled successfully

   Linting and checking validity of types ...

./app/Pick/page.tsx
39:6  Warning: React Hook useEffect has a missing dependency: 'randomPick'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
87:6  Warning: React Hook useEffect has missing dependencies: 'dataKeyArray' and 'dataRcdArray'. Either include them or remove the dependency array. You can also replace multiple useState variables with useReducer if 'setPickKey' needs the current value of 'dataKeyArray'.  react-hooks/exhaustive-deps

./app/components/ReviewSession.tsx
226:6  Warning: React Hook useEffect has missing dependencies: 'dbRefX', 'revisCoef', 'sessionCount', and 'sessionReady'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps
275:6  Warning: React Hook useEffect has a missing dependency: 'revRcdArray'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
287:6  Warning: React Hook useEffect has missing dependencies: 'sessionCount' and 'sessionReady'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps
298:6  Warning: React Hook useEffect has missing dependencies: 'randomPick' and 'randomTouch'. Either include them or remove the dependency array. You can also do a functional update 'setRandomTouch(r => ...)' if you only need 'randomTouch' in the 'setRandomTouch' call.  react-hooks/exhaustive-deps

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules

Failed to compile.

./functions/src/index.ts:205:37
Type error: Type 'IterableIterator<[any, any]>' can only be iterated through when using the '--downlevelIteration' flag or with a '--target' of 'es2015' or higher.

  203 |     };
  204 |
> 205 |     for (const [level, lvlCount] of activeLevels.entries()) {
      |                                     ^
  206 |       jsonResult = Object.assign({}, jsonResult, {
  207 |         ["Level_"+level.toString()]: lvlCount,
  208 |       });

[2024-05-13T05:40:59.377Z] Error: ENOENT: no such file or directory, open '/Users/me/Documents/FireBase/myapp/.next/export-marker.json'

Error: An unexpected error has occurred.

**Comment by aalej** [comment]
Hey @zaxonus, thanks for reaching out. I’m currently unable to reproduce the error you mentioned. From what I can gather ,your setup would somewhat be similar to https://github.com/aalej/issues-7170. It’s a default Next.js application, with Cloud Functions for Firebase code:

`functions/src/index.ts`
```ts
import {onRequest} from "firebase-functions/v2/https";
import * as logger from "firebase-functions/logger";

export const helloWorld = onRequest((request, response) => {
 logger.info("Hello logs!", {structuredData: true});
 const activeLevels = new Map();
 for (const [level, lvlCount] of activeLevels.entries()) {
   console.log(level, lvlCount);
 }
 response.send("Hello from Firebase!");
});
```

In case I’m missing anything or made a mistake in the setup, please let me know. Alternatively, any chance you could share a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) with us? This would help us accurately reproduce the issue.
