### ISSUE TITLE
firebase deploy: no such file or directory

### ISSUE THREAD

**Issue by ESRuth** [firebase/firebase-tools#7183]
### [REQUIRED] Environment info

13.9.0

**firebase-tools:**

Windows

**Platform:**

### [REQUIRED] Steps to reproduce

Every time I try to deploy, it tries to find a file in a repeated path (ie. instead of /x/y/z/a.b, it is looking for /x/y/z/x/y/z/a.b).

### [REQUIRED] Expected behavior

The project gets deployed.

### [REQUIRED] Actual behavior

[firebase-debug.log](https://github.com/firebase/firebase-tools/files/15315195/firebase-debug.log)

**Comment by aalej** [comment]
Hey @ESRuth, thanks for sharing your debug logs. It looks like the issue you’re encountering is similar to #7146. This should be fixed once #7148 is merged and released. That said, I’ll be marking this as a duplicate.

For now, to work around the issue, please use firebase-tools v13.6.1. Apologies for the inconvenience this has caused.
