### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by sudeera-madushan** [firebase/firebase-tools#7184]
[debug] [2024-05-15T13:04:19.137Z] Error: ENOENT: no such file or directory, lstat 'C:\Users\vijes\Documents\BigZKoop\NextJs\firebase-next\.next\C:\Users\vijes\Documents\BigZKoop\NextJs\firebase-next\.next\BUILD_ID'
[error] 
[error] Error: An unexpected error has occurred.

**Comment by aalej** [comment]
Hey @sudeera-madushan, based on the logs you shared, I’m guessing that the issue you’re experiencing is the same as #7146. That said, I’ll go ahead and close this as a duplicate. The fix in #7148 should address this once it's merged and released. For now, please use firebase-tools v13.6.1 as a workaround.

However, if you think you’re encountering a different issue, please file a new report and provide the details using the specified template. This way, we would have sufficient information to start our initial investigation. Thanks!
