### ISSUE TITLE
Running firebase deploy with service account and missing permission errors with "Assertion failed"

### ISSUE THREAD

**Issue by fiws** [firebase/firebase-tools#7190]
### [REQUIRED] Environment info

**firebase-tools:** 13.9.0

**Platform:** node:lts docker container

### [REQUIRED] Test case

Any project with a firebase.json

### [REQUIRED] Steps to reproduce

1. Set `GOOGLE_APPLICATION_CREDENTIALS` to an service account key that does **not** have access to the project used in the next command
1. Try to run `firebase deploy --project invalid-project-name-2358923 --only hosting --non-interactive` 

### [REQUIRED] Expected behavior

Should print that the project does not exist or that auth is required. (Something like that)

### [REQUIRED] Actual behavior

Prints this: 

```
Error: Assertion failed: resolving hosting target of a site with no site name or target name. This should have caused an error earlier
```

Which sounds like firebase is just broken and does not suggest that it could be an auth issue anywhere.

**Comment by aalej** [comment]
Hey @fiws, thanks for raising this issue and for providing a detailed report. I do agree that an error message stating that the service account does not have permission or something similar would be more helpful. I’ll raise this to our engineering team.
