### ISSUE TITLE
Setting permissions on binary: syntax error near unexpected token `<' /usr/local/bin/firebase: line 1:

### ISSUE THREAD

**Issue by jaydeepbhayani** [firebase/firebase-tools#7222]
### [REQUIRED] Environment info

`firebase --version`  12.4.5

**firebase-tools:**

`NA`

**Platform:**

`Ubuntu`

### [REQUIRED] Test case

curl -sL https://firebase.tools | bash

### [REQUIRED] Steps to reproduce

curl -sL https://firebase.tools | bash

### [REQUIRED] Expected behavior

Everything is installed, as expected

### [REQUIRED] Actual behavior

`-- Setting permissions on binary...
/usr/local/bin/firebase: line 1: syntax error near unexpected token `<'
/usr/local/bin/firebase: line 1: `﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.'
Something went wrong, firebase has not been installed.
Please file a bug with your system information on Github.
https://github.com/firebase/firebase-tools/
-- All done!
Error: Process completed with exit code 1.`

**Comment by bogosj** [comment]
I just came here to file the same bug. Whatever happened to cause this happened within the last hour. I have a github action which installs firebase-tools via this `curl | sh` method and it worked about 54 minutes ago but then failed 13 minutes ago.

**Comment by aalej** [comment]
Hey folks, sorry to hear you encountered this issue and thanks for reporting. Our team is currently looking into this.

**Comment by aalej** [comment]
Hey everyone, apologies for the inconvenience this has caused. Our team has re-uploaded the binaries and this should be fixed.

Could anyone let us know if they’re still encountering an issue?

**Comment by bogosj** [comment]
Appears fixed on my end.
