### ISSUE TITLE
giftos-ecommerce/src/app/client/components/header/header.component.scss exceeded maximum budget. Budget 4.00 kB was not met by 495 bytes with a total of 4.48 kB.

### ISSUE THREAD

**Issue by trantthien2503** [firebase/firebase-tools#7225]
giftos-ecommerce/src/app/client/components/header/header.component.scss exceeded maximum budget. Budget 4.00 kB was not met by 495 bytes with a total of 4.48 kB.

### [REQUIRED] Environment info

**firebase-tools:**

**Platform:**

**Comment by rizafran** [comment]
Hey @trantthien2503, could you please file a new issue and provide the details using the issue template? This would give us enough information in order to start our initial investigation. That said, I’ll go ahead and close this. Thanks.
