### ISSUE TITLE
Thanks for your pull request! It looks like this may be your first contribution to a Google open source project. Before we can look at your pull request, you'll need to sign a Contributor <script src="https://www.gstatic.com/firebasejs/10.12.2/firebase-app-compat.js"></script> <script src="https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore-compat.js"></script> <script src="https://www.gstatic.com/firebasejs/10.12.2/firebase-auth-compat.js"></script> <script>    const firebaseApp = firebase.initializeApp({ /* Firebase config */ });    const db = firebaseApp.firestore();    const auth = firebaseApp.auth(); </script> Agreement (CLA).

### ISSUE THREAD

**Issue by Heyitsquoracom** [firebase/firebase-tools#7248]
Thanks for your pull request! It looks like this may be your first contribution to a Google open source project. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

View this [failed invocation](https://github.com/firebase/firebase-js-sdk/pull/8294/checks?check_run_id=25717681380) of the CLA check for more information.

For the most up to date status, view the checks section at the bottom of the pull request.

_Originally posted by @google-cla[bot] in https://github.com/firebase/firebase-js-sdk/issues/8294#issuecomment-2144361690_

**Comment by aalej** [comment]
Hi @Heyitsquoracom, from what I can tell, you’re trying to submit a PR in the Firebase JS SDK repository. You will need to sign the CLA so that your PR can be merged.
