### ISSUE TITLE
Cannot deploy NextJS on Firebase App Hosting Backend, IF it's inside a sub directory

### ISSUE THREAD

**Issue by ashleyrudland** [firebase/firebase-tools#7263]
Like most NextJS apps today, they are typically not in the root directory.

My bug could be fixed with a simple UI input or cli param called "working directory" / "--dir"

This would run the normal npm run build, but where ever this folder is specified.

I'm a 5 year customer of Firebase, we do around $22K/mo, I run all my apps on it accept for front end hosting, that's all on Vercel.

I'll migrate the entire thing to Firebase today if this bug is fixed - faster round trip time from NextJS to Firestore DB calls = better product experience.

Thanks in advance!
Ash.

**Comment by r0hin** [comment]
+1

**Comment by blidd-google** [comment]
Hi folks, we've released a fix that allows deployments from subdirectories and the change is rolling out to our prod environments soon. Thanks for your patience!
