### ISSUE TITLE
Before and after returns incorrect values for .exists and .data() in the shell

### ISSUE THREAD

**Issue by schjonhaug** [firebase/firebase-tools#729]
### Version info
3.18.2

### Platform Information

macOS 10.13.4

### Bug

This bug can only be observed in the shell, deployed functions are not affected.

In the shell, `change.before.exists` and `change.before.exists` return true, even if values for one of these are not provided.

Example, running this in the shell
```
functionName({after: {
    "value": 123
}});
```
gives me both `change.before.exists` and `change.after.exists` true. I would expect only `change.after.exist` to return true in this case. Similarly `change.before.data()` returns the empty object `{}`. I would expect it to return `null`.

The opposite result is observed when providing a value for `before`, but not for `after`. In this case, I would expect `change.after.exists` to return false and `change.after.data()` to return `null`.

**Comment by laurenzlong** [comment]
Are you using a Firestore function? Or a Real Time Database function?

**Comment by schjonhaug** [comment]
Firestore

**Comment by mbleigh** [comment]
Should be fixed in 3.18.4
