### ISSUE TITLE
Config option 'ignore' changed from 3.18.1 to 3.18.2

### ISSUE THREAD

**Issue by a-xin** [firebase/firebase-tools#734]
With 3.18.1, the following config was working fine and excluded `functions/.eslintrc`, `functions/node_modules`, ... from deployments:
```
"functions": {
  "ignore": [
    "**/.*",
    "**/node_modules/**",
    "**/*.spec.js"
  ],
  "source": "functions"
},
```

Updating to 3.18.2 and continuing to use above's config led to a massive increase in deployment size, mainly due to the sudden inclusion of `functions/node_modules` into the deployment zip.
Updating the config as follows excludes `node_modules`, `.gitignore` again, but files like `.eslintrc.js` get included into the deployment zip:
```
"functions": {
  "ignore": [
      ".*",
      ".gitignore",
      "node_modules"
  ],
  "source": "functions"
},
```

Adding a spec to `fsAsync.spec.js` which tests the exclusion pattern `**/node_modules/**` fails the test, ie. it seems to confirm that the previous exclusion pattern is not supported anymore:
```javascript
  it('can ignore glob patterns', function() {
    var expected = _
      .chain(files)
      .reject(function(file) {
        return file.indexOf('node_modules') !== -1;
      }).map(function(file) {
        return path.join(baseDir, file);
      }).value().sort();

    var promise = fsAsync.readdirRecursive({
      path: baseDir,
      ignore: ['**/node_modules/**']
    }).then(function(results) {
      return _.map(results, function(result) { return result.name; }).sort();
    });

    return expect(promise).to.eventually.deep.equal(expected);
  });
```

My expectation would be that the supported patterns of `ignore` don't change in minor releases, and `**/node_modules/**` continues to work.

**Comment by a-xin** [comment]
Looks like this check is too simple, compared to the previous support for glob patterns:
https://github.com/firebase/firebase-tools/commit/bcc5c4391d8626c15f39fbb5a32571bf1a5d995c#diff-15d38ac9b24826461d2c0d3202679e77R58
```
+      .reject(function(file) { return _.includes(options.ignore, file); })
```

**Comment by inlined** [comment]
Thanks for the issue; I broke it and will fix it.
