### ISSUE TITLE
 502 error on firebase functions:config:get

### ISSUE THREAD

**Issue by JonathonPenberthy** [firebase/firebase-tools#7342]
### [REQUIRED] Environment info

**firebase-tools:** 13.11.2

**Platform:** Windows

### [REQUIRED] Test case
Get the existing configuration for a firebase functions

### [REQUIRED] Steps to reproduce
execute the command `firebase functions:config:get`

### [REQUIRED] Expected behavior
output: 
`{
  "my": {
    "foo": "bar"
  }
}`

### [REQUIRED] Actual behavior
output:
`Error: Unable to parse JSON: SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON`

### Additional Information
When the command is execute with `--debug` you can see that the google API is responding with an 502 Bad gateway response and the body of the response is html rather than json

**Comment by aalej** [comment]
Hey @JonathonPenberthy, sorry to hear you encountered this issue and thanks for reporting this. Based on the error message, it looks like the cause of this might be related to https://github.com/firebase/firebase-tools/issues/7341. 

Currently, I’m able to run `firebase functions:config:get --project PROJECT_ID` on my end without any issue. Could you try running the command again to see if you would still encounter an error?
