### ISSUE TITLE
V2 Functions with uppercase letters are not deployed

### ISSUE THREAD

**Issue by becjit** [firebase/firebase-tools#7344]
### [REQUIRED] Environment info

firebase-tools: [13.11.2]

mac 

### [REQUIRED] Steps to reproduce

create or deploy any functions with uppercase

### [REQUIRED] Expected behavior

Should deploy

### [REQUIRED] Actual behavior
v2 function name(s) can only contain lower case letters, numbers, hyphens, and not exceed 62 characters in length

**Comment by KSiejka** [comment]
Can you run `firebase deploy --debug` and check the error logs? It works fine on my end, and all of my function's names use camelCase.

**Comment by unxavi** [comment]
@KSiejka without debug I am hitting this:


```
Error: Cannot set CPU on the functions my-Function-onCreate because they are GCF gen 1
```

**Comment by KSiejka** [comment]
> @KSiejka without debug I am hitting this:
> 
> ```
> Error: Cannot set CPU on the functions my-Function-onCreate because they are GCF gen 1
> ```

According to [this comment](https://github.com/firebase/firebase-tools/issues/6048#issuecomment-1706748378) you are trying to downgrade function from v2 to v1. If that's not the case, make sure your firebase-tools are upgraded to the newest version and try [ importing the v2 functions library to force it to be V2](https://github.com/firebase/firebase-tools/issues/6048#issuecomment-1814109519).

**Comment by unxavi** [comment]
@KSiejka i am not trying to downgrade anything, before #7341 start to hit error this morning, the same codebase was deploying.

This is the same codebase that is using a v2 function and it was deploying some hours ago and no changes has occur on the dependencies (which are latests) and not change on the code, but thanks for your comment anyways

**Comment by jesus-mg-ios** [comment]
Same here, Is there any ETA on this?

**Comment by becjit** [comment]
I downgraded firebase-tools to 11.x and it started working

**Comment by unxavi** [comment]
this is working for me now with the latests firebase-tools

**Comment by unxavi** [comment]
Right now for me is working back again and I have my functions with uppercase letters, for example: "user-Profile-onCreate"

**Comment by aalej** [comment]
I’m still unable to reproduce the issue. Any chance you could try running `firebase deploy --debug` while using firebase-tools v13.11.2 to see if the issue would still persist? If the issue still occurs, could you share the contents of the `firebase-debug.log` file? Please remove any personal identifiable information(PII) before sharing.

Also, I can’t seem to find the exact error message you shared. The closest error message I could find was from https://github.com/firebase/firebase-tools/blob/master/src/deploy/functions/validate.ts#L200-L210, but this would raise an error similar to 
```
Error: <INVALID_FUNCTION_NAME> function name(s) can only contain letters, numbers, hyphens, and not exceed 62 characters in length
``` 

Could you check if you’re using an older version of firebase-tools? The naming restriction was lifted in [v11.29.0](https://github.com/firebase/firebase-tools/releases/tag/v11.29.0).

**Comment by becjit** [comment]
Thnx I actually downgraded to unblock myself. Feel free to close this. If I
face this issue post upgrade will reopen or file a new one
