### ISSUE TITLE
Sharp out of date

### ISSUE THREAD

**Issue by pm0u** [firebase/firebase-tools#7346]
### [REQUIRED] Environment info

**firebase-tools:** 13.9.0

**Platform:** MacOS Sonoma 14.5

### [REQUIRED] Test case

`yarn create next-app test && cd test && yarn add sharp@latest && firebase deploy`

### [REQUIRED] Expected behavior

I can use the latest version of sharp.

### [REQUIRED] Actual behavior

When using the frameworks integration, `sharp` is out of date here: https://github.com/FirebaseExtended/firebase-framework-tools/blob/main/packages/firebase-frameworks/package.json#L58 which means that any projects that would like to deploy to firebase are unable to have an up to date version of sharp as it conflicts.

I tried setting `"overrides": { "sharp": "0.33.4" }` in package.json to match my installed version but the deploy errored out with no explanation so I guess there must be some breaking change somewhere.

**Comment by leoortizz** [comment]
Hey @pm0u! The support to sharp `0.33.4` was released recently, can you please try it and report back here?
