### ISSUE TITLE
The 2 Factor Authentication Still Not Working on Emulator Needs to be Prioritized

### ISSUE THREAD

**Issue by elucidsoft** [firebase/firebase-tools#7347]
This issue seen here https://github.com/firebase/firebase-tools/issues/6224 has existed for over a year now. This needs to be prioritized as it's a massive show stopper. How do you guys plan on adding additional support like Authn as well in the future when even something this basic isn't supported by the Auth emulator?  You should not release a feature, unless it's also fully available on the emulators, and you should make that your release cadence.

**Comment by aalej** [comment]
Hey @elucidsoft, thanks for bringing this to our attention, I understand your frustration given that there hasn't been any update. That said, I'll reach out to our engineering team to see if we have some feedback to share. Please note that we are still unable to provide a definite timeline when support for this would be added. To help us keep a single line of communication, please continue any conversation through #6224

You may also help us give the issue more visibility by adding a thumbs up on the original post on #6224, this way we can track the issues more efficiently under our radar. I'll go ahead and close this thread.
