### ISSUE TITLE
firebase deployment not wprking showing only white page

### ISSUE THREAD

**Issue by SivaFullStackDeveloper** [firebase/firebase-tools#7366]
Please submit feature requests through our [support page](https://firebase.google.com/support/troubleshooter/report/features/).

**Comment by aalej** [comment]
Hey @SivaFullStackDeveloper , looking at the title of the report. I think the issue you’re encountering is similar to https://github.com/firebase/firebase-tools/issues/7363 and https://github.com/firebase/firebase-tools/issues/7364. That said I’ll be marking this as a duplicate.

However, if you think the issue you’re encountering is different. Please file a new bug report and provide the details using the specified template. This would give us enough information to start our initial investigation.
