### ISSUE TITLE
icons not showing after deploying it in to firebase also images from assets folder and also network imaegs not working WTF happend to you guys . you guys are making me to feel to leave firebase and flutter

### ISSUE THREAD

**Issue by SivaFullStackDeveloper** [firebase/firebase-tools#7380]
### [REQUIRED] Environment info

**firebase-tools:**

**Platform:**

**Comment by Robula** [comment]
`13.11.2` is the last working version for us.
Both `13.11.3` and `13.11.4` has caused images to break on hosting.

**Comment by comdet** [comment]
13.11.0 is working for me.

**Comment by SivaFullStackDeveloper** [comment]
13.09.0 worked for me closing the issue any one who is facing the same issue which is images and icons not showing from flutter to firebase deploying in hosting please use   npm i firebase-tools@13.9.0
