### ISSUE TITLE
Firebase hosted website not loading images `13.11.3` and onwards

### ISSUE THREAD

**Issue by Robula** [firebase/firebase-tools#7381]
### [REQUIRED] Environment info

**firebase-tools:** >= `13.11.3`

**Platform:** Windows

### [REQUIRED] Test case

N/A

### [REQUIRED] Steps to reproduce

Deploying our website on firebase-tools version `13.11.2`, the website works as expected and all images are displayed.

1. Upgrade firebase-tools to `13.11.3` or `13.11.4`.
2. Deploy website.
3. All images on the website loaded from the assets folder are broken.

**Comment by aalej** [comment]
Hey @Robula, apologies for the issue this has caused. We also received a similar report https://github.com/firebase/firebase-tools/issues/7363 which has been raised to our engineering team. This is currently being investigated.

To keep a single line of communication, could you please refer to the other ticket for any updates.
