### ISSUE TITLE
package.json indicates an outdated version of firebase-functions.

### ISSUE THREAD

**Issue by jongcodes** [firebase/firebase-tools#7385]
### [REQUIRED] Environment info

1. **firebase-tools: 13.11.4**
2. **Platform: Windows**
3. I am using the webframeworks integration to use Next.js.

### [REQUIRED] Test case

1. Creating a functions directory and configuration using the ```firebase init functions``` command.
2. Run ```firebase deploy``` command.

### [REQUIRED] Steps to reproduce

N/A

### [REQUIRED] Expected behavior

Since I have the latest version of the ```firebase-functions``` package installed, I shouldn't be seeing any warning messages.

### [REQUIRED] Actual behavior

![outdated version of firebase-functions](https://github.com/firebase/firebase-tools/assets/87285532/dffb8612-e850-4a22-855e-0f63992aa33f)

**Comment by busanTeddyBear** [comment]
My package.json file is:

```
{
    "name": "functions",
    "description": "Cloud Functions for Firebase",
    "scripts": {
        "serve": "firebase emulators:start --only functions",
        "shell": "firebase functions:shell",
        "start": "npm run shell",
        "deploy": "firebase deploy --only functions",
        "logs": "firebase functions:log"
    },
    "engines": {
        "node": "20"
    },
    "main": "index.js",
    "dependencies": {
        "firebase-admin": "^12.2.0",
        "firebase-functions": "^5.0.1"
    },
    "devDependencies": {
        "firebase-functions-test": "^3.3.0"
    },
    "private": true
}
```

**Comment by aalej** [comment]
Hey @busanTeddyBear, thanks for the detailed report. Based on the steps you provided and the logs you shared, I think the reason why you’re encountering these logs could be related to the version of `firebase-functions` that is being set when deploying Web Frameworks.

From what I can tell, we set the version [here](https://github.com/firebase/firebase-tools/blob/1c843795a835c107a23e25ef4ef8189b76da8561/src/frameworks/constants.ts#L33). I’ll raise this to our engineering team to see what we can do.
