### ISSUE TITLE
Web FontManifest Missing on hosting even present under firebase assets 

### ISSUE THREAD

**Issue by SudeepWebDev** [firebase/firebase-tools#7386]
### [REQUIRED] Environment info

**firebase-tools:**

**Platform:**

**Comment by aalej** [comment]
Hey @SudeepWebDev, looking at the title of the report, I think you may be encountering a similar issue to https://github.com/firebase/firebase-tools/issues/7378 and https://github.com/firebase/firebase-tools/issues/7363. If this is the case, we have a fix for this in https://github.com/firebase/firebase-tools/pull/7382 that should be available in the next release. While waiting, please use firebase-tools v13.11.2 as a workaround.

However, if you think the issue you're encountering may be different, could you please file a new report and provide the details using the specified template. This would help us with our investigation.

**Comment by SudeepWebDev** [comment]
Thanks, well I tried a lot and then I moved from vs code to idx and then I again deployed it and it worked too.

But I got exact problems now.
