### ISSUE TITLE
Have Firestore support index files to validate indexes

### ISSUE THREAD

**Issue by onurdialpad** [firebase/firebase-tools#7400]
We've been using datastore emulator with `--index_file`, `--require_index` and `--regenerate_indexes` to validate indexes with index.yaml file. Note these args are visible if you execute the command like

```
<PATH_TO_google-cloud-sdk>/platform/cloud-datastore-emulator/cloud_datastore_emulator help start
```
while they are not visible with

```
gcloud beta emulators datastore start --help
```

We need to have firestore emulator support validataing indexes as we do with datastore emulator.

**Comment by aalej** [comment]
Hey @onurdialpad, thanks for reaching out. I think this is a similar request to #2027. Could you leave a thumbs up or a comment on #2027? This lets us better track requests and helps us prioritize development efforts. That said, I’ll mark this as a duplicate.
