### ISSUE TITLE
Linux: socket hang up INTERNAL function crashed

### ISSUE THREAD

**Issue by neves** [firebase/firebase-tools#742]
Error happens when the function has async code.

### Version info

3.18.2

### Platform Information

Linux ubuntu17 4.13.0-38-generic #43-Ubuntu SMP Wed Mar 14 15:20:44 UTC 2018 x86_64 x86_64 
x86_64 GNU/Linux

Mac works fine!

### Steps to reproduce

https://gist.github.com/neves/77845ccedc7dfc2306ae3b8aaeff771c

### Expected behavior

Normal response

### Actual behavior

```javascript
{
  error: {
    code: 500,
    status: "INTERNAL",
    message: "function crashed",
    errors: [
     "socket hang up"
    ]
  }
}
```

--debug don't apply

**Comment by laurenzlong** [comment]
This was just fixed in 3.18.3
