### ISSUE TITLE
Hello, im currently developing a flutter app using firebase functions im using python but it doesnt support authentication triggers

### ISSUE THREAD

**Issue by zouhirdev** [firebase/firebase-tools#7432]
Hello, im currently developing a flutter app using firebase functions im using python but it doesnt support authentication triggers 
so i need to use javascript alog with python can you explain how did you do that. im not an expert but i dont think it gonna be hard. thanks in advence

_Originally posted by @zouhirdev in https://github.com/firebase/firebase-tools/issues/5994#issuecomment-2222621496_

**Comment by aalej** [comment]
Hey @zouhirdev. From what I understand, you want to use 2 codebases, 1 JavaScript and 1 Python. To setup up another codebase that uses JavaScript:

1. Run `firebase init functions`
2. ? Would you like to initialize a new codebase, or overwrite an existing one? Initialize
3. ? What should be the name of this codebase? name-of-codebase
4. ? In what sub-directory would you like to initialize your functions for codebase js-codebase? name-of-codebase
5. ? What language would you like to use to write Cloud Functions? JavaScript
6. ? Do you want to use ESLint to catch probable bugs and enforce style? No
7. ? Do you want to install dependencies with npm now? Yes

After doing the steps above, a separate codebase that uses JavaScript should be created. I think this answers your question so I’ll go ahead and close this. Let me know in case you have any other questions.
