### ISSUE TITLE
If the pubsub function is implemented in 2gen, the publishTime is 1970/01/01 00:00:00.

### ISSUE THREAD

**Issue by ytetsuro** [firebase/firebase-tools#7441]
Invalid value for publishTime.
I use this publishTime to determine retry timeouts, so I don't want this to break.

### [REQUIRED] Environment info

**firebase-tools:**

13.13.2

**Platform:**

Mac OS 14.4

### [REQUIRED] Test case

```typescript
const example = onMessagePublished(
  {
    topic: 'example',
    timeoutSeconds: 540,
    memory: '2GiB',
    retry: true,
  },
 (event: CloudEvent<MessagePublishedData>) => {
    console.log(event.data.message.publishTime); //1970/01/01 00:00:00
  },
);
```

### [REQUIRED] Steps to reproduce

Start the emulator with the following command and call pubsub.

`firebase emulators:start`

### [REQUIRED] Expected behavior

The date and time will be the PUBLISHED date and time.
In addition, as a supplement, the current date and time are entered for 1gen.

### [REQUIRED] Actual behavior

publishTime is 1970/01/01 00:00:00

**Comment by aalej** [comment]
Hey @ytetsuro, thanks for raising this and for creating a detailed report! I’m able to reproduce the behavior mentioned using the provided code snippet. Let me notify our engineering team about this so they can investigate. I’ll also be marking this as reproducible.
