### ISSUE TITLE
Tool commands 'logout' and 'login --reauth' fail when credentials are expired in firebase-tools@13.13.2

### ISSUE THREAD

**Issue by andy-tmpt-me** [firebase/firebase-tools#7442]
### Environment info

**firebase-tools: 13.13.2**

**Platform: macOS**

### Test case

```
(base) andrewjenkins@Andrews-MBP tmpt_me_client %  firebase login --reauth
(node:85243) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

Error: Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

(base) andrewjenkins@Andrews-MBP tmpt_me_client % firebase logout
(node:53687) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

Error: Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth
```

### Steps to reproduce

With most recent version of 13.13.2:

```
 npm install -g firebase-tools
firebase login
```
...wait for credentials to expire
```
firebase login --reauth
```

### Expected behavior

I should be able to logout or refresh expired credentials

### Actual behavior

The tool produces an Authentication Error even on logout.  Downgrading to **npm install -g firebase-tools@13.13.1** works

**Comment by seaders** [comment]
Same here, downgrading back to 13.3.1 works and allows me to login again. Not going near another release until this is resolved, has caused a serious amount of pain for us today.

**Comment by joehan** [comment]
Hey all, sorry for any inconvenience this issue has caused. I'm investigating this issue this morning and will hopefully have a fix soon.
