### ISSUE TITLE
(Functions)The redeploy option is undefined, but an error message is displayed asking to use the redeploy option.

### ISSUE THREAD

**Issue by ytetsuro** [firebase/firebase-tools#7466]
I use secrets with firebase functions.
I get the following error when I try to overwrite the secrets I am using.
However, the redeploy option does not exist.
It is also not possible to bypass redeploy as there is no option not to perform redeploy.

```
Error: Missing required options (redeploy) while running in non-interactive mode:
- redeploy Do you want to re-deploy the functions and destroy the stale version of secret FOO?
```

### [REQUIRED] Environment info

**firebase-tools:**

13.13.3

**Platform:**

Mac OS 14.4

### [REQUIRED] Test case

```bash
$ firebase functions:secrets:set --data-file secrets.local --redeploy FOO
```

### [REQUIRED] Steps to reproduce

```bash
$ firebase functions:secrets:set --data-file secrets.local --redeploy FOO
```

### [REQUIRED] Expected behavior

If secrets exist, they are redeployed.

### [REQUIRED] Actual behavior

Show following error.

```
error: unknown option '--redeploy'
```

Pull Request

https://github.com/firebase/firebase-tools/pull/7465

**Comment by aalej** [comment]
Hey @ytetsuro, thanks for the detailed report. Using the `--force` flag, you should be able to bypass the prompts and automatically update functions to use the new secret. 

I think the behavior could be improved here by providing a better error message since it mentions a redeploy option, or adding the options from the PR you created. I’ll consult with our engineering team to see what we can do here.

**Comment by ytetsuro** [comment]
@aalej 

Thank you response!
Indeed, I can force a function to deploy using the force option.

However, I will get an error message saying that you need to use the redeploy option as you are aware.
There is also a case where we want to exit successfully without executing redeploy (I would rather achieve this). I believe that this is the case.

**Comment by chadtomkiss** [comment]
I'm also looking to skip redeploying functions when setting a secret because we deploy later in the GitHub Action workflow 🤔
