### ISSUE TITLE
Encounted a bug when performing flutterfire configure (with using curl -sL https://firebase.tools for CLI installation)

### ISSUE THREAD

**Issue by wesley990** [firebase/firebase-tools#7516]
### [REQUIRED] Environment info

`firebase --version`              
13.14.2

`flutter --version`
Flutter 3.24.0-0.2.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 7c6b7e9ca4 (2 days ago) • 2024-07-30 14:26:44 +0700
Engine • revision 6e4deceb38
Tools • Dart 3.5.0 (build 3.5.0-323.2.beta) • DevTools 2.37.2

Ubuntu noble 24.04 x86_64

### [REQUIRED] Test case

0. I don't have nvm and npm installed in the beginning. So I use
    `curl -sL https://firebase.tools | bash` for CLI installation
    Then, `firebase login`
    Next, `dart pub global activate flutterfire_cli`
    Finally, `flutter pub add firebase_core` and `flutterfire configure --project=flutter-rpg` in the project folder.

1. Under the flutter project, execute `flutter pub add cloud_firestore`
➜  flutter_rpg git:(main) flutter pub add cloud_firestore
Resolving dependencies... 
Downloading packages... 
+ _flutterfire_internals 1.3.16 (1.3.40 available)
+ cloud_firestore 4.14.0 (5.2.0 available)
+ cloud_firestore_platform_interface 6.1.0 (6.3.0 available)
+ cloud_firestore_web 3.9.0 (4.1.0 available)
  collection 1.18.0 (1.19.0 available)
  firebase_core 2.24.2 (3.3.0 available)
  firebase_core_web 2.10.0 (2.17.4 available)
  http_parser 4.0.2 (4.1.0 available)
  js 0.6.7 (0.7.1 available)
  material_color_utilities 0.11.1 (0.12.0 available)
  string_scanner 1.2.0 (1.3.0 available)
  test_api 0.7.2 (0.7.3 available)
Changed 4 dependencies!
12 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.

➜  flutter_rpg git:(main) ✗ `dart pub outdated`
Showing outdated packages.
[*] indicates versions that are not the latest available.

Package Name                        Current  Upgradable  Resolvable  Latest  

direct dependencies:               
cloud_firestore                     *4.14.0  *4.14.0     *4.14.0     5.2.0   
firebase_core                       *2.24.2  *2.24.2     *2.24.2     3.3.0   

dev_dependencies: all up-to-date.  

transitive dependencies:           
_flutterfire_internals              *1.3.16  *1.3.16     *1.3.16     1.3.40  
cloud_firestore_platform_interface  *6.1.0   *6.1.0      *6.1.0      6.3.0   
cloud_firestore_web                 *3.9.0   *3.9.0      *3.9.0      4.1.0   
collection                          *1.18.0  *1.18.0     *1.18.0     1.19.0  
firebase_core_web                   *2.10.0  *2.10.0     *2.10.0     2.17.4  
http_parser                         *4.0.2   *4.0.2      *4.0.2      4.1.0   
js                                  *0.6.7   *0.6.7      *0.6.7      0.7.1   
material_color_utilities            *0.11.1  *0.11.1     *0.11.1     0.12.0  
string_scanner                      *1.2.0   *1.2.0      *1.2.0      1.3.0   
test_api                            *0.7.2   *0.7.2      *0.7.2      0.7.3   
You are already using the newest resolvable versions listed in the 'Resolvable' column.
Newer versions, listed in 'Latest', may not be mutually compatible.

2. Execute `flutterfire configure`

✔ You have an existing `firebase.json` file and possibly already configured your project for Firebase. Would you prefer to reuse the values in your existing `firebase.json` file to configure your project? · yes 
Failed to parse JSON response from Firebase CLI. JSON response: This tool has encountered an error. Please file a bug on Github (https://github.com/firebase/firebase-tools/) and include firepit-log.txt

Failed to parse JSON response from Firebase CLI. JSON response: This tool has encountered an error. Please file a bug on Github (https://github.com/firebase/firebase-tools/) and include firepit-log.txt

FormatException: Unexpected character (at character 1)
This tool has encountered an error. Please file a bug on Github (https://gi...
^

### [REQUIRED] Expected behavior

`flutterfire configure` should completes without errors.

### [REQUIRED] Actual behavior

I tried the following steps, and it didn't have problems.
`install nvm,node and npm`

`rm -rf ~/.cache/firebase`
`npm install -g firebase-tools`
`flutterfire configure`

[firepit-log.txt](https://github.com/user-attachments/files/16450463/firepit-log.txt)

**Comment by exaby73** [comment]
Hey @wesley990. Are you able to run firebase commands like `firebase projects:list --json` successfully?

**Comment by wesley990** [comment]
> Hey @wesley990. Are you able to run firebase commands like `firebase projects:list --json` successfully?

Yes. I paste the result below. I am afraid that I can not reproduce the issue since I used npm to install the Firebase CLI tool instead of using `curl`.

> (node:21879) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
⠋ Preparing the list of your Firebase projects(node:21879) [DEP0044] DeprecationWarning: The `util.isArray` API is deprecated. Please use `Array.isArray()` instead.
✔ Preparing the list of your Firebase projects
{
  "status": "success",
  "result": [
    {
      "projectId": "fir-rpg-57ae6",
      "projectNumber": "000000000000",
      "displayName": "demo-rpg",
      "name": "projects/fir-rpg-57ae6",
      "resources": {
        "hostingSite": "fir-rpg-57ae6"
      },
      "state": "ACTIVE",
      "etag": "1_f281e3ee-b9c9-45c2-a481-000000000"
    }
  ]
}%

**Comment by michaeltheshah** [comment]
I'm attempting to use the command `firebase init hosting` and I am receiving the same result: 

```
(node:89541) [DEP0044] DeprecationWarning: The `util.isArray` API is deprecated. Please use `Array.isArray()` instead.
```

Attempting to run `firebase projects:list --json` results in the same error that @wesley990 is receiving. I've fully uninstalled `nvm` and `node` and reinstalled both to see if that could fix the issue. It didn't.

**Comment by joehan** [comment]
Closing since @wesley990 got a working set up - based on firepit.log, this looks like a local setup permissions issue.
