### ISSUE TITLE
Unable to ignore anything when using nextjs firebase deploy (webframeworks)

### ISSUE THREAD

**Issue by okaforcj** [firebase/firebase-tools#7525]
### [REQUIRED] Environment info

**firebase-tools:** 13.12.0

**Platform:** macOs

### [REQUIRED] Test case

try to add ignored files in firebase.json for firebase project that has the experimental webframeworks

### [REQUIRED] Steps to reproduce
- create a nextjs project or any framework that uses experimental firebase webframeworks 
- add paths to ignore in the firebase json file e.g. public folder files, env files etc

```
{
  "hosting": {
    "source": ".",
    "ignore": ["firebase.json", "**/.*", "**/node_modules/**", "ignored-files.etc"],
    "frameworksBackend": {
      "region": "europe-west1",
      "maxInstances": 1,
      "memory": "1GiB",
      "cpu": 2
    }
  }
}

```

### [REQUIRED] Expected behavior

ignore either generation of the files in the .firebase folder or prevent it from uploading

### [REQUIRED] Actual behavior

use `firebase deploy`

files are not ignored at all, I am using trpc, which means cloud functions are automatically triggered, 

All the files that were ignored, are still there. 

the generated firebase.json file from the logs, doesn't even include any `ignore` field that was previously set 

[debug] [2024-08-04T15:05:04.143Z] [web frameworks] effective firebase.json: 
```
{
  "hosting": [
    {
      "source": ".",
      "frameworksBackend": {
        "region": "your-region",
        "maxInstances": 1,
        "memory": "1GiB",
        "cpu": 2
      },
      "site": "your-site-name",
      "rewrites": [
        {
          "source": "**",
          "function": {
            "functionId": "your-function-id",
            "region": "your-region",
            "pinTag": true
          }
        }
      ],
      "redirects": [],
      "headers": [],
      "cleanUrls": true,
      "trailingSlash": false,
      "i18n": {
        "root": "/"
      },
      "public": ".firebase/your-site-name/hosting",
      "webFramework": "next_ssr"
    }
  ],
  "functions": [
    {
      "source": ".firebase/your-site-name/functions",
      "codebase": "firebase-frameworks-your-site-name"
    }
  ]
}
```

**Comment by aalej** [comment]
Hey @okaforcj , thanks for reaching out and for sharing debug logs and the contents of your `firebase.json` file. I'm trying to reproduce this, but so far I haven't been able to reproduce the behavior you mentioned. Files specified in `hosting.ignore` are being ignored on deployments.

Checking the `firebase-debug.log`, the generated firebase.json looks like:
```
[web frameworks] effective firebase.json:  {
 "hosting": [
   {
     "source": ".",
     "ignore": [
       "firebase.json",
       "**/.*",
       "**/node_modules/**",
       "**/vercel.svg",
       "ignored-file.txt"
     ],
     "frameworksBackend": {
       "region": "us-central1"
     },
     "site": "SITE_ID",
     "rewrites": [],
     "redirects": [],
     "headers": [
       {
         "source": "/_not-found",
         "headers": [
           {
             "key": "x-next-cache-tags",
             "value": "_N_T_/layout,_N_T_/_not-found/layout,_N_T_/_not-found/page,_N_T_/_not-found"
           }
         ]
       },
       {
         "source": "/favicon.ico",
         "headers": [
           {
             "key": "cache-control",
             "value": "public, max-age=0, must-revalidate"
           },
           {
             "key": "content-type",
             "value": "image/x-icon"
           },
           {
             "key": "x-next-cache-tags",
             "value": "_N_T_/layout,_N_T_/favicon.ico/layout,_N_T_/favicon.ico/route,_N_T_/favicon.ico"
           }
         ]
       }
     ],
     "cleanUrls": true,
     "trailingSlash": false,
     "public": ".firebase/SITE_ID/hosting",
     "webFramework": "next"
   }
 ]
}
```

Could you try using the latest version of firebase-tools, which is currently v13.15.0, to see if you would still encounter the same behavior? Also, by any chance, could you share an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example), to help us reproduce the issue?

**Comment by okaforcj** [comment]
@aalej I upgraded the version and this seems to be working now. if I have any other issues ill reopen. Thanks! Appreciate it
