### ISSUE TITLE
I'm not sure where to file this, but not having environments as a first class feature in firebase is wild

### ISSUE THREAD

**Issue by ecancil** [firebase/firebase-tools#7527]
'just create another project'

The overhead of setup alone for this is crazy.  How is this not something firebase has not been more thoughtful about.  You ship distributed tracing before you support basic environments?

**Comment by aalej** [comment]
Hey @ecancil, thanks for the feedback. I understand that setting up a new project for a different environment might take additional time and effort. However doing it this way isolates each environment's infrastructure, ensuring changes in one environment does not affect others. 

If you'd like a single project to support multiple environments, I would recommend reaching out to our dedicated [Firebase Support](https://firebase.google.com/support) channel to share this feedback.

**Comment by ecancil** [comment]
@aalej does GCP suggest creating a new project for each environment as well?

**Comment by aalej** [comment]
I’m not an expert with GCP. I recommend reaching out to [GCP support](https://support.google.com/cloud/troubleshooter/3511991?hl=en) to get a more detailed answer.

Although, when using Firebase, it is generally recommended to use [separate projects for each environment](https://firebase.google.com/docs/projects/dev-workflows/overview-environments) in your development workflow.
