### ISSUE TITLE
Emulator in datastore mode doesn't return `indexUpdates` for commit requests

### ISSUE THREAD

**Issue by owainhunt** [firebase/firebase-tools#7543]
### [REQUIRED] Environment info

**firebase-tools:** 
```
$ firebase --version
13.15.0

$ gcloud --version                 
Google Cloud SDK 487.0.0
beta 2024.08.06
bq 2.1.7
cloud-datastore-emulator 2.3.1
cloud-firestore-emulator 1.19.7
core 2024.08.06
gsutil 5.30
```

**Platform:** macOS

### [REQUIRED] Test case

```
{
  "mutations": [
    {
      "insert": {
        "properties": {
          "myProperty": {
            "stringValue": "myValue"
          }
        },
        "key": {
          "partitionId": {
            "namespaceId": "test",
            "projectId": "test-project"
          },
          "path": [
            {
              "kind": "MyKind"
            }
          ]
        }
      }
    }
  ],
  "mode": "NON_TRANSACTIONAL"
}
```

### [REQUIRED] Steps to reproduce

POST the above body to `v1/projects/test-project:commit`

### [REQUIRED] Expected behavior

`indexUpdates` should be included in response, as per the [documentation](https://cloud.google.com/datastore/docs/reference/data/rest/v1/projects/commit#response-body) and the equivalent response from the legacy datastore emulator:

```
{
    "mutationResults": [
        {
            "key": {
                "partitionId": {
                    "projectId": "test-project",
                    "namespaceId": "test"
                },
                "path": [
                    {
                        "kind": "MyKind",
                        "id": "3"
                    }
                ]
            },
            "version": "2"
        }
    ],
    "indexUpdates": 3
}
```

### [REQUIRED] Actual behavior

`indexUpdates` is not included in the response:

```
{
    "mutationResults": [
        {
            "key": {
                "partitionId": {
                    "projectId": "test-project",
                    "namespaceId": "test"
                },
                "path": [
                    {
                        "kind": "MyKind",
                        "id": "5629499534213120"
                    }
                ]
            },
            "version": "1723126543368109",
            "updateTime": "2024-08-08T14:15:43.368109Z",
            "createTime": "2024-08-08T14:15:43.368109Z"
        }
    ]
}
```
~~Note also that updateTime and createTime are included, when they are not specified in the response documentation.~~

**Comment by aalej** [comment]
Hey @owainhunt, thanks for the detailed report. I’m able to reproduce the issue you mentioned. Using the provided information, I created this [mcve](https://github.com/aalej/issues-7543). Regarding the `updateTime` and `createTime` fields, it looks like this is part of the [MutationResult](https://cloud.google.com/datastore/docs/reference/data/rest/v1/projects/commit#MutationResult) object which is in the [mutationResults](https://cloud.google.com/datastore/docs/reference/data/rest/v1/projects/commit#response-body) list. 

I’ll raise this to our engineering so they can take a look.

**Comment by harshyyy21** [comment]
Hi @owainhunt! Took a look at the issue, and it seems the `indexUpdates` is correctly being populated as 0 here. This is due to the fact that the Firestore Emulator does not support indexes today, thus there is nothing to validate against in the Emulator. This is a delta from Datastore emulator and the backend. Let me know if you have any other questions!
