### ISSUE TITLE
[firebase_hosting] Wasm (WebAssembly) is not used in Flutter Web App

### ISSUE THREAD

**Issue by Kuhlemann** [firebase/firebase-tools#7554]
### [REQUIRED] Environment info

**firebase-tools:** 13.15.1

**Platform:** macOS

### [REQUIRED] Test case

```
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('WebAssembly-Status: $kIsWasm!'),
        ),
        body: const Center(
          child: Text('Welcome to Flutter WebAssembly!'),
        ),
      ),
    ),
  );
}
```

### My firebase.json in my project folder looks like this (maybe some CORS problem?):

```
{
  "hosting": {
    "source": ".",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "frameworksBackend": {
      "region": "europe-west1"
    },
    "rewrites": [ {
      "source": "**",
      "destination": "/index.html"
    } ],
    "headers": [
        {
           "source": "**/*",
            "headers": [
                {
                    "key": "Cross-Origin-Embedder-Policy",
                    "value": "require-corp"
                },
                {
                    "key": "Cross-Origin-Opener-Policy",
                    "value": "same-origin"
                }
            ]
        }
    ]    
  }
}
```

### [REQUIRED] Steps to reproduce

- I use newest Flutter stable channel version 3.24.0 with firebase-tools 13.15.1
- I use the simplest possible code to reproduce (see sample above)
- To make sure there is no problem inside the index.html I deleted the "web"-folder and recreated it with: `flutter create . --platforms=web`
- `flutter build web --wasm` compiles successfully: "✓ Built build/web"
- Directly after that I start a local server in my "build/web"-folder with dhttp for testing purpose: `dhttpd '--headers=Cross-Origin-Embedder-Policy=credentialless;Cross-Origin-Opener-Policy=same-origin'`
- I use Chrome version 126 to open localhost:8080 and kIsWasm is **true**.
- After that I deploy with `firebase deploy` and kIsWasm is now **false** in the online version of my app.

### [REQUIRED] Expected behavior

Constant kIsWasm should be true to show that WebAssembly is used

### [REQUIRED] Actual behavior

WebAssembly is not used (kIsWasm is false)

**Comment by aalej** [comment]
Hey @Kuhlemann, thanks for reaching out and providing a detailed report. Looking through the information provided, it seems like this might be a similar issue to #6197.

When using `source`, Firebase CLI builds your app using `flutter build web`. Since you won’t be able to pass parameters during build, could you try changing `"source": "."` to `"public": "build/web"` in your `firebase.json` file. This will tell the CLI to use the build in `build/web` that was built using `flutter build web --wasm`.

Also, I modified the `hosting.headers.source` path since there was a `SharedArrayBuffer is not defined` error. The current `firebase.json` I have is:

```json
{
 "hosting": {
   "public": "build/web",
   "ignore": [
     "firebase.json",
     "**/.*",
     "**/node_modules/**"
   ],
   "headers": [
     {
       "source": "**",
       "headers": [
         {
           "key": "Cross-Origin-Embedder-Policy",
           "value": "require-corp"
         },
         {
           "key": "Cross-Origin-Opener-Policy",
           "value": "same-origin"
         }
       ]
     }
   ]
 }
}
```

After doing so, could you try running `flutter build web --wasm` then `firebase deploy` to see if WebAssembly is being used?

**Comment by Kuhlemann** [comment]
Hi aaley,

thank you for your support, which solved the problem for me! :-)

I ran into a follow up problem ( #https://github.com/firebase/flutterfire/issues/12819#issuecomment-2289245595 ), because with the necessary CORS-configuration for WASM firebase_auth is broken, but that is another topic.

Best regards
Kuhlemann
