### ISSUE TITLE
Emulator behavior of `onDocumentWritten` doesn't match production when using `transaction.set()` with `merge = false`

### ISSUE THREAD

**Issue by ben519** [firebase/firebase-tools#7560]
In my web app, when a user uploads a file to cloud storage, I create a corresponding document in Firestore. Here's a very watered down version of what that looks like

```js
// See https://firebase.google.com/docs/functions/gcp-storage-events?gen=2nd

import { onObjectFinalized } from "firebase-functions/v2/storage"
import { db } from "./main.js"

export const onFileCreated = onObjectFinalized(async (event) => {
  // When a file is uploaded:
  //  - create a corresponding firestore document in /users/{userId}/files collection
  //  - set the id of the document as the filename

  // Extract the userId and filename from the full path
  const re = RegExp("^users/(?<userId>[^/]+)/files/(?<filename>[^/]+)$", "g")
  const match = re.exec(event.data.name)
  const { userId, filename } = match.groups

  await db.runTransaction(async (transaction) => {
    const dirname = `users/${userId}/files`
    const fileRef = db.collection(dirname).doc(filename)
    return transaction.set(fileRef, event.data, { merge: false })
  })
}
```

Now suppose the user...

1. Uploads a file `foo.png`
2. Later, uploads a new file also named `foo.png`

- The first upload triggers the function above which creates a firestore document `users/123/files/foo.png`
- The second upload triggers the same function above which updates the same firestore document

This raises a question... Does the second invocation of `transaction.set(fileRef, event.data, { merge: false })` trigger a firestore _update_ event or a _delete_ event followed by a _create_ event?

Consider this other cloud function that is triggered by changes to the very firestore document created earlier...

```js
import { onDocumentWritten } from "firebase-functions/v2/firestore"
import { db } from "./main.js"

export const onFileDocWritten = onDocumentWritten(
  {
    document: "users/{userId}/files/{fileId}",
    secrets: [STRIPE_SECRET_KEY],
  },
  async (event) => {
    // Each time a file document is created, updated, or deleted:
    // - reflect the changes in the document users/<userId>/lists/files

    const fileOld = event.data.before.data()
    const fileNew = event.data.after.data()
    const { fileId, userId } = event.params

     await db.runTransaction(async (transaction) => {
      if (!fileOld && fileNew) {
        console.log("File doc was created")

      } else if (fileOld && !fileNew) {
        console.log("File doc was deleted")

      } else {
        console.log("File doc was updated or overwritten.")
     }

  }) // End of transaction
}
```

When the user uploads `foo.png` the second time (thus overwriting the first document), what do you think will be logged to the console? From my testing, the emulator logs "File doc was updated or overwritten.", but my live production app logs
 "File doc was deleted".

From my perspective, the emulator has the correct behavior and the live cloud function has the incorrect behavior. But I guess you could argue otherwise. Whatever the case, the emulator should match the production behavior but it does not.

### Environment info
- `firebase --version`: 13.15.1
- macOS

**Comment by aalej** [comment]
Hey @ben519, thanks for providing a detailed description of the issue you’re encountering and for sharing code snippets! 

I’m currently working on trying to reproduce the behavior you mentioned, but so far, the behavior on the emulator matches the one from production. In both cases, the logs shown when uploading `foo.png` a second time is `File doc was updated or overwritten.`.

I created this [repo](https://github.com/aalej/issues-7560) to try and replicate the setup you have. In case I missed anything or made a mistake with the setup, just let me know. Alternatively, any chance you could provide an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) to help us replicate the issue?
