### ISSUE TITLE
Repeated prompt for Firebase Extensions TOS in v13.15.4

### ISSUE THREAD

**Issue by pwnedev** [firebase/firebase-tools#7590]
### Environment info

**firebase-tools:** 13.15.4

**Node.js:** 20.14.0

**Platform:** Windows

### [REQUIRED] Test case

Deploy a function using the Firebase CLI using firebase-tools v13.15.4.

### [REQUIRED] Steps to reproduce

1. Upgrade to firebase-tools v13.15.4.
2. Deploy any function using the Firebase CLI:
`firebase deploy --only functions`
3. The prompt with the question "Do you accept the Firebase Extensions User Terms of Service? (Y/n)" appears.
4. Deploy any function again using the same method.
5. The same prompt appears.

### [REQUIRED] Expected behavior

1. Either save the reply the first time we answer the prompt.
2. Or have a special option like `--skipExtensionsTOS`.

### [REQUIRED] Actual behavior

The prompt appears every time we deploy a function using the Firebase CLI. Stalling our deployment scripts.

Note that `-f` & `--force` don't solve this issue, due to the fact that these options also "delete Cloud Functions missing from the current working directory", and I only mean to bypass the extensions TOS prompt.

**Comment by t0mstah** [comment]
Plz

**Comment by AdrianLsk** [comment]
Workaround for people not using extensions: turn off the firebaseextensions.googleapis.com API in the API library in GCP console.

**Comment by m-j-g** [comment]
I've been getting the same prompt every deploy, real annoying.  I noticed when updating that it added this to .firebaserc:

  "targets": {},
  "etags": {
    "app-name": {
      "extensionInstances": {}
    }
  },
  "dataconnectEmulatorConfig": {}

**Comment by joehan** [comment]
Hey everyone, apologies for the trouble here. We're rolling out a new way to declare extensions from within your functions codebases soon, and this change was meant to se the table for that. However, it ended up negatively users who installed extensions via the console and deploy only their functions via CLI. We're reverting this behavior change for now and will release a version today to get the changes out(https://github.com/firebase/firebase-tools/commit/dee2c89a99819298e1b1437881e9a15d138c510f).

Later, we'll revisit this feature and will roll it out again in a less disruptive way.
