### ISSUE TITLE
Firebase: Error (auth/network-request-failed). 

### ISSUE THREAD

**Issue by koroman17** [firebase/firebase-tools#7591]
### Operating System

Windows 11

### Environment (if applicable)

Chrome Version 127.0.6533.122 (Official Build) (64-bit), nodejs v20.14.0

### Firebase SDK Version

^10.13.0

### Firebase SDK Product(s)

Auth

### Project Tooling

react-native with expo go

### Detailed Problem Description

create a user on emulators
get this **Firebase: Error (auth/network-request-failed).**
it works with firebase cloud

### Steps and code to reproduce issue

run these commands
- npx create-expo-app@latest ./ --template blank
- md firebase
- cd firebase
- firebase login
- firebase init
- firebase emulators:start
- npx expo install firebase
- npx expo start

create this file in ./firebase/firebase.js
```
import { initializeApp } from "firebase/app";
import { connectAuthEmulator, getAuth } from "firebase/auth";

const firebaseConfig = {
	apiKey: "***",
	authDomain: "***",
	projectId: "***",
	storageBucket: "***",
	messagingSenderId: "***",
	appId: "***",
	measurementId: "***",
};

const app = initializeApp(firebaseConfig);

export const auth = getAuth();
connectAuthEmulator(auth, "http://127.0.0.1:9099");
```
change App.js like this
```
import { StatusBar } from "expo-status-bar";
import { createUserWithEmailAndPassword } from "firebase/auth";
import { StyleSheet, Text, View } from "react-native";
import { auth } from "./firebase/firebase";
export default function App() {
	createUserWithEmailAndPassword(auth, "test@gmail.com", "test1234")
		.then((userCredential) => {
			console.log(userCredential);
		})
		.catch((err) => {
			console.log(err.code, err.message);
		});
	return (
		<View style={styles.container}>
			<Text>Open up App.js to start working on your app!</Text>
			<StatusBar style="auto" />
		</View>
	);
}
```

open the app on **expo go** on **iOS**

**Comment by jbalidiong** [comment]
Hi @koroman17, thanks for reaching out to us. This seems to be a similar request to https://github.com/firebase/firebase-js-sdk/issues/8459. To avoid duplicate effort, I’ll mark this as a duplicate. I'll be closing this issue now. If you'd like to continue the discussion, I suggest going to the linked issue.
