### ISSUE TITLE
tversion  v011

### ISSUE THREAD

**Issue by milyes** [firebase/firebase-tools#7596]
### [REQUIRED] Environment info

**firebase-tools:**

**Platform:**

### [REQUIRED] Actual behavior

const { onRequest } = require("firebase-functions/v1/https");

exports.helloWorld = onRequest((request, response) => {
   response.send(`)The env VARIABLE value is: ${process.env.VARIABLE}`);
});

**Comment by milyes** [comment]
> Ce problème ne contient pas toutes les informations requises par le modèle. Il semble que vous ayez oublié de remplir certaines sections. Veuillez mettre à jour le problème avec plus d'informations.

**Comment by milyes** [comment]
const { onRequest } = require("firebase-functions/v1/https");

exports.helloWorld = onRequest((request, response) => {
   response.send(`The env VARIABLE value is: ${process.env.VARIABLE}`);
}));

**Comment by aalej** [comment]
Hey @milyes, could you please file a new issue and provide the details using the specified template. This would give us enough information to be able to start our initial investigation. Thanks!
