### ISSUE TITLE
Cannot Deploy Functions - "FirebaseError Unexpected key extensions."

### ISSUE THREAD

**Issue by benjaminsfoley** [firebase/firebase-tools#7605]
Since updating firebase-tools, I'm no longer able to deploy.. which is a bit of a pain!

Things I've tried:
* Downgrade firebase-tools to @13.12.0
* Uninstall Node and VS Code and reinstall them (to start a fresh)
* Downgrade from Node v20 to Node v18 (https://github.com/firebase/firebase-tools/issues/5673#issuecomment-1513783792)
* Delete package-lock.json before deploy (https://github.com/firebase/firebase-tools/issues/5673#issuecomment-1538026152); yes, I know it's dangerous
* Tried to create functions.yaml as per https://stackoverflow.com/questions/75605362/firebase-deployment-failure-could-not-find-functions-yaml-must-use-http-disco

None of this has helped. I note that I am able to firebase deploy --only hosting in my other projects.

In case it's an account issue, I've raised it with firebase support, but they have escalated to internal devs.
In case it's a CLI issue, I raise it below.

### Environment info
```
test-broken-deploys % node -v
v20.15.1
```

```
test-broken-deploys % firebase --version
13.13.3
```

```
test-broken-deploys % npm list -g
/opt/homebrew/lib
├── boilerplate_auth_rest_and_bots@ -> ./../../../Users/benjaminfoley/Documents/GitHub/boilerplate_auth_rest_and_bots/functions
├── firebase-tools@13.15.4
└── npm@10.8.2
```

Weird that firebase --version and npm list -g come up with different versions for ```firebase-tools``` !?

```
test-broken-deploys % cd functions
functions % npm list 
functions@ /Users/benjaminfoley/Documents/GitHub/test-broken-deploys/functions
├── firebase-admin@12.4.0
├── firebase-functions-test@3.3.0
└── firebase-functions@5.1.0
```

**Platform:**
MacBook Pro
Chip: Aooke M3 Pro
Memory: 36 GB
MacOS: Sonoma 14.6.1

VS Code: 1.92.2

### Test case
```firebase deploy --only functions``` should deploy functions to firebase

I have had the error with my main project, but for sake of this test, I've used an new firebase project and an empty repo.

### Steps to reproduce
```test-broken-deploys % firebase init```
* functions
* existing project > test-broken-deploys
* javascript
* no lint
* yes install dependencies

Firebase init threw up some warnings re running Node@20, but the I've also run the test after brewing Node@18

index.js 
```javascript
const {onRequest} = require("firebase-functions/v2/https");
const logger = require("firebase-functions/logger");

// Hello World
exports.helloWorld = onRequest((request, response) => {
  logger.info("Hello logs!", {structuredData: true});
  response.send("Hello from Firebase!");
});
```

package.json
```json
{
  "name": "functions",
  "description": "Cloud Functions for Firebase",
  "scripts": {
    "serve": "firebase emulators:start --only functions",
    "shell": "firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "engines": {
    "node": "20"
  },
  "main": "index.js",
  "dependencies": {
    "firebase-admin": "^12.1.0",
    "firebase-functions": "^5.0.0"
  },
  "devDependencies": {
    "firebase-functions-test": "^3.1.0"
  },
  "private": true
}
```

firebase.json
```json
{
  "functions": [
    {
      "source": "functions",
      "codebase": "default",
      "ignore": [
        "node_modules",
        ".git",
        "firebase-debug.log",
        "firebase-debug.*.log",
        "*.local"
      ]
    }
  ]
}
```

Now...

```
test-broken-deploys % firebase deploy --only functions

=== Deploying to 'test-broken-deploys'...

i  deploying functions
i  functions: preparing codebase default for deployment
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
i  artifactregistry: ensuring required API artifactregistry.googleapis.com is enabled...
✔  artifactregistry: required API artifactregistry.googleapis.com is enabled
✔  functions: required API cloudbuild.googleapis.com is enabled
✔  functions: required API cloudfunctions.googleapis.com is enabled
i  functions: Loading and analyzing source code for codebase default to determine what to deploy
Serving at port 8395

Error: Failed to parse build specification:
FirebaseError Unexpected key extensions. You may need to install a newer version of the Firebase CLI.
```

Running with ```--debug``` shows...

```
[2024-08-27T23:28:39.142Z] Validating nodejs source
[2024-08-27T23:28:39.420Z] > [functions] package.json contents: {
  "name": "functions",
  "description": "Cloud Functions for Firebase",
  "scripts": {
    "serve": "firebase emulators:start --only functions",
    "shell": "firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "engines": {
    "node": "20"
  },
  "main": "index.js",
  "dependencies": {
    "firebase-admin": "^12.1.0",
    "firebase-functions": "^5.0.0"
  },
  "devDependencies": {
    "firebase-functions-test": "^3.1.0"
  },
  "private": true
}
[2024-08-27T23:28:39.421Z] Building nodejs source
i  functions: Loading and analyzing source code for codebase default to determine what to deploy 
[2024-08-27T23:28:39.421Z] Could not find functions.yaml. Must use http discovery
[2024-08-27T23:28:39.425Z] Found firebase-functions binary at '/Users/benjaminfoley/Documents/GitHub/test-broken-deploys/functions/node_modules/.bin/firebase-functions'
Serving at port 8927

[2024-08-27T23:28:39.628Z] Got response from /__/functions.yaml {"endpoints":{"helloWorld":{"availableMemoryMb":null,"timeoutSeconds":null,"minInstances":null,"maxInstances":null,"ingressSettings":null,"concurrency":null,"serviceAccountEmail":null,"vpc":null,"platform":"gcfv2","labels":{},"httpsTrigger":{},"entryPoint":"helloWorld"}},"specVersion":"v1alpha1","requiredAPIs":[],"extensions":{}}
Error: Failed to parse build specification:
FirebaseError Unexpected key extensions. You may need to install a newer version of the Firebase CLI.
```

### [REQUIRED] Expected behavior
Functions deploy

### [REQUIRED] Actual behavior
Above errors

**Comment by buildingmon** [comment]
downgrade firebase-functions from 5.1.0 to 5.0.1 works for me

**Comment by aalej** [comment]
Hey @benjaminsfoley, thanks for the detailed report! Currently, I’m unable to reproduce this issue when using `firebase-tools` v13.16.0. Based on the information provided, it looks like you might have multiple `firebase-tools` installed in your machine, and you may be executing the older version of `firebase-tools`. 

Could you check your `firebase-debug.log` to verify which version you’re using? The first few lines of the debug logs should show the CLI version:
```[debug] [2024-08-28T11:21:12.907Z] ----------------------------------------------------------------------
[debug] [2024-08-28T11:21:12.913Z] Command:       /<PATH>/node /<PATH>/firebase deploy --only functions --force
[debug] [2024-08-28T11:21:12.913Z] CLI Version:   13.16.0
[debug] [2024-08-28T11:21:12.913Z] Platform:      darwin
[debug] [2024-08-28T11:21:12.913Z] Node Version:  v20.16.0
[debug] [2024-08-28T11:21:12.913Z] Time:          <TIME>
[debug] [2024-08-28T11:21:12.913Z] ----------------------------------------------------------------------
```

If it’s not displaying the version you expected, it’s most likely that you’re executing the older version firebase-tools installed in your machine. 

If you’re using brew to install `firebase-tools`, could you try running `brew install firebase-cli` then `firebase --version` to see if this would update the version of firebase-tools you have installed?

**Comment by aalej** [comment]
Just a quick update here, for those also encountering this issue, this should be fixed by updating to the latest version of firebase-tools, which is currently v13.16.0.

**Comment by benjaminsfoley** [comment]
> downgrade firebase-functions from 5.1.0 to 5.0.1 works for me
Can confirm that this also worked for me - but obvs wasn't the preferable "fix". solid workaround for anyone experiencing the error, though! thank you. 🙇🏾

ran ```npm install firebase-functions@latest``` to then play with @aalej suggestions...

@aalej correct, logs show ```[debug] [2024-08-27T23:28:34.267Z] CLI Version:   13.13.3``` 
I ran ```brew install firebase-cli``` and ```firebase --version``` shows 13.13.3 while ```npm list -g``` shows 13.16.0

When I run a deploy (having put firebase-functions back to latest), deploy fails and logs show it's still using 13.13.3

So.. I ran ```npm uninstall -g firebase-tools``` and things stayed kind of interesting.. ```npm list -g``` shows firebase-tools is removed but, ```firebase --version``` still works and still returns 13.13.3. Moreover, I can still run all of the other Firebase CLI commands (e.g. deploy.. which fails, while logs show trying to use 13.13.3).

This now becomes a different error / topic.. 
https://stackoverflow.com/questions/59386943/how-to-uninstall-firebase-cli-firebase-tools seems related.

```which firebase``` gets you the path
```rm [above_path]``` deletes remnant files
```firebase --version``` now comes back ```zsh: command not found: firebase``` = enqueue excitement_squee!

Now lets start afresh...
```test-broken-deploys % npm install -g firebase-tools@latest```

```
test-broken-deploys % npm list -g
/opt/homebrew/lib
├── boilerplate_auth_rest_and_bots@ -> ./../../../Users/[blah]/Documents/GitHub/boilerplate_auth_rest_and_bots/functions
├── firebase-tools@13.16.0
└── npm@10.8.2
```

```
test-broken-deploys % firebase --version
13.16.0
```

enqueue that shaq 'yeah baby' gif feeling

AND CAN NOW DEPLOY!!!!


Infinite thanks for unblocking me, @aalej

**Comment by nick-massie** [comment]
Updating to latest version did work for me!

**Comment by briighter** [comment]
The above answer (reinstalling firebase tools manually) worked for me.

`which firebase` gets you the path
`rm [above_path]` delete remnant files
`npm install -g firebase-tools@latest`

**Comment by madhavamshahi** [comment]
> > downgrade firebase-functions from 5.1.0 to 5.0.1 works for me
> 
> @buildingmon can confirm that this also worked for me - but obvs wasn't the preferable "fix". solid workaround for anyone experiencing the error, though! thank you. 🙇🏾
> 
> ran `npm install firebase-functions@latest` to then play with @aalej suggestions...
> 
> @aalej correct, logs show `[debug] [2024-08-27T23:28:34.267Z] CLI Version: 13.13.3` I ran `brew install firebase-cli` and `firebase --version` shows 13.13.3 while `npm list -g` shows 13.16.0
> 
> When I run a deploy (having put firebase-functions back to latest), deploy fails and logs show it's still using 13.13.3
> 
> So.. I ran `npm uninstall -g firebase-tools` and things stayed kind of interesting.. `npm list -g` shows firebase-tools is removed but, `firebase --version` still works and still returns 13.13.3. Moreover, I can still run all of the other Firebase CLI commands (e.g. deploy.. which fails, while logs show trying to use 13.13.3).
> 
> This now becomes a different error / topic.. https://stackoverflow.com/questions/59386943/how-to-uninstall-firebase-cli-firebase-tools seems related.
> 
> `which firebase` gets you the path `rm [above_path]` deletes remnant files `firebase --version` now comes back `zsh: command not found: firebase` = enqueue excitement_squee!
> 
> Now let's start afresh... `test-broken-deploys % npm install -g firebase-tools@latest`
> 
> ```
> test-broken-deploys % npm list -g
> /opt/homebrew/lib
> ├── boilerplate_auth_rest_and_bots@ -> ./../../../Users/[blah]/Documents/GitHub/boilerplate_auth_rest_and_bots/functions
> ├── firebase-tools@13.16.0
> └── npm@10.8.2
> ```
> 
> ```
> test-broken-deploys % firebase --version
> 13.16.0
> ```
> 
> enqueue that shaq 'yeah baby' gif feeling
> 
> AND CAN NOW DEPLOY!!!!
> 
> Infinite thanks for unblocking me, @aalej

Helped me get unblocked as well, thanks!

**Comment by briighter** [comment]
> The above answer (reinstalling firebase tools manually) worked for me.
> 
> `which firebase` gets you the path `rm [above_path]` delete remnant files `npm install -g firebase-tools@latest`

You can also run the firebase commands directly and not use the `npm run script` feature. This also helped.

**Comment by nillbiplob** [comment]
The above answer (reinstalling firebase tools manually) worked for me.

which firebase gets you the path
rm [above_path] delete remnant files
npm install -g firebase-tools@latest

**Comment by JustKhit** [comment]
> The above answer (reinstalling firebase tools manually) worked for me.
> 
> `which firebase` gets you the path `rm [above_path]` delete remnant files `npm install -g firebase-tools@latest`

I had two different places installed. This worked! Thanks

**Comment by adamdroberts** [comment]
Thanks, this resolved it for me :-)

Even a brand new sample function wouldn't even deploy.

In my case, I was using pnpm to update firebase-tool and have been for some time but there was an old global firebase-tools in my path from npm that was overriding the latest version. 

I did: 

pnpm uninstall -g firebase-tools 
npm uninstall -g firebase-tools 

pnpm i firebase-tools -g 

All good now :-)
