### ISSUE TITLE
Unable to set GCP resource location

### ISSUE THREAD

**Issue by devravinder** [firebase/firebase-tools#7607]

**Comment by devravinder** [comment]
I'm trying to create a basic Firebase project, 
when I run
`firebase init`

I'm getting this error
`It looks like you haven't used Cloud Firestore in this project before`

Upon debugging, I got to know, that it is checking the firestore db at the global location, but I created firestore db at ap-south-1 ( Mumbai ).


I'm facing issue while setting the location, I didn't find any way to set the location

**Comment by aalej** [comment]
Hey @devravinder. I’m currently unable to reproduce this. I created a new Firebase project, and after opening "https://console.firebase.google.com/project/<PROJECT_ID>/firestore" to create a Cloud Firestore database, I was able to run `firebase init firestore` without any issues.

For us to be able to investigate why you’re encountering the error, we would need additional information. Could you run `firebase init --debug` and share your `firebase-debug.log` file? It contains a detailed log that we can use to check what caused the error. Please remove any personal identifiable information(PII) before sharing the file.

Also, if you’re encountering an issue with setting the location in the Firebase Console, please reach out to our [Firebase Support](https://firebase.google.com/support) channel to get assistance. They’ll be able to assist you further for issues related to project configurations.

**Comment by aalej** [comment]
Hey @devravinder, just to verify, are you using multiple Firestore databases? If yes, it's possible that you’re encountering a similar issue to #7567. To workaround the issue, could you try creating a new database named `(default)`?
