### ISSUE TITLE
Emulator firestore onDocumentCreatedWithAuthContext not receiving uuid

### ISSUE THREAD

**Issue by peterlauri** [firebase/firebase-tools#7609]
### [REQUIRED] Environment info

**firebase-tools: 13.16.0**

**Platform: macOS 14.6.1**

### [REQUIRED] Test case

This firebase index.js function:

```javascript
"use strict";

// The Cloud Functions for Firebase SDK to create Cloud Functions and triggers.
const { logger } = require("firebase-functions");
const { onRequest } = require("firebase-functions/v2/https");
const { onDocumentCreatedWithAuthContext } = require("firebase-functions/v2/firestore");
const { auth } = require("firebase-functions/v1");

// The Firebase Admin SDK to access Firestore.
const { initializeApp } = require("firebase-admin/app");
const { getFirestore } = require("firebase-admin/firestore");

initializeApp();

exports.testAuthContextEntries = onDocumentCreatedWithAuthContext("/entries/{documentId}", (event) => {
  const { authType, authId } = event;
  logger.log("testAuthContextEntries:", authType, authId);
});

```

### [REQUIRED] Steps to reproduce

- Authenticate with any user (assume he gets User ID=abc123 in firebase auth emulator)
- Write a document to /entries/<id> with the authenticated client

### [REQUIRED] Expected behavior

```
>  {"severity":"INFO","message":"testAuthContextEntries: unknown abc123"}
```

### [REQUIRED] Actual behavior

```
>  {"severity":"INFO","message":"testAuthContextEntries: unknown fake-auth-id@gmail.com"}
```

**Comment by aalej** [comment]
Hey @peterlauri, thanks for the detailed report. Looking at the information provided, it seems like the issue you’re encountering is similar to [#7450](https://github.com/firebase/firebase-tools/issues/7450). To better track this, please leave a comment or a thumbs up on the original issue. 

That said, I’ll be closing this as a duplicate. If you think this is a mistake, feel free to ask this to be re-opened.
