### ISSUE TITLE
"connection error" when deploying a function

### ISSUE THREAD

**Issue by PierBover** [firebase/firebase-tools#761]
I'm not sure if this is a bug, or expected behavior but I'm posting here in case someone can help me figure this out.

Whenever I'm deploying a function with an HTTP trigger, the function stops working and produces the "connection error" in the Firebase console when it is triggered. After a few seconds the function works as expected.

This only happens when deploying, so the problem is definitely not in the function code.

Is this expected behavior when deploying?

Is there a way to mitigate this other than deploying at low traffic hours?

**Comment by laurenzlong** [comment]
Hi @PierBover This is not a CLI issue, please post a reproducible example on StackOverflow or file a support ticket at firebase.google.com/support

**Comment by PierBover** [comment]
Hi @laurenzlong 

The CLI is in charge of deployment so it makes sense that I would post anything related to deploy here.

A reproducible example cannot be really posted on StackOverflow and since I'm not even sure this is a bug it wouldn't make sense either to contact support.

**Comment by laurenzlong** [comment]
Since you were able to deploy, and the problem is happening in the runtime, it is not a CLI bug. I suspect the issue is either something due to the way you wrote your code, or something unique to your project set up.
