### ISSUE TITLE
Firebase hosting redirect rule fails and produce URI too long error (when matched path can be matched in destination path too?)

### ISSUE THREAD

**Issue by pdela** [firebase/firebase-tools#7616]
### [REQUIRED] Environment info

13.4.1

Windows

### [REQUIRED] Test case
 visit https://testweb.saycheesebistrot.com/act/id?lang=en

### [REQUIRED] Steps to reproduce

Set up redirects in hosting in firebase.json

```
"redirects": [
        **// this works**
	{
		"source": "/event/:UrlTail*",
		"destination": "/activity/:UrlTail",
		"type": 301
	},
	   **// this doesn't work, both using regex or glob**
	{
		"regex": "/act/(?P<UrlTail>.+)",
		// "source": "/act/:UrlTail*",
		"destination": "/activity/:UrlTail",
		"type": 301
	},
]	
```

### [REQUIRED] Expected behavior

url:
- https://testweb.saycheesebistrot.com/act/id?lang=en
redirects to:
- https://testweb.saycheesebistrot.com/acticity/id?lang=en

### [REQUIRED] Actual behavior
url:
- https://testweb.saycheesebistrot.com/act/id?lang=en
redirects to:
- https://testweb.saycheesebistrot.com/act/activity/activity/activity/activity/.../activity/activity/activity/activity/activity/id?lang=en

and produces URI too long error.

The suspect is that the matched segment "act" can be matched inside the destination string "activity" and somehow goes in a loop.
All other redirects I have where this is not the case, work just fine.

**Comment by aalej** [comment]
Hey @pdela, thanks for the detailed report. I’m working on reproducing this, but so far, the redirect is working on my end. Using the redirect config you provided(used glob):
```
{
 "hosting": {
   "public": "public",
   "ignore": ["firebase.json", "**/.*", "**/node_modules/**"],
   "redirects": [
     {
       "source": "/event/:UrlTail*",
       "destination": "/activity/:UrlTail",
       "type": 301
     },
     {
       "source": "/act/:UrlTail*",
       "destination": "/activity/:UrlTail",
       "type": 301
     }
   ]
 }
}
```

After deploying, accessing the url https://aalej-fb-tools-13-test.web.app/act/id redirects to https://aalej-fb-tools-13-test.web.app/activity/id/. Also, I tried opening the link you provided and https://testweb.saycheesebistrot.com/act/id?lang=en redirects to https://testweb.saycheesebistrot.com/activity/id?lang=en.

If you’re still encountering this issue, could you try updating to the latest version firebase-tools, which is currently v13.16.0, to see if there would be any changes in behavior?

**Comment by pdela** [comment]
Hi @aalej,

thank you for testing it so quickly and sorry for my late opportunity to check.
It seems there was something in my machine that caused the problem as after clearing all site data, it works without problems, even without updating firebase-tools.
Sorry for this, I should have tried clearing data before posting the issue, but it did seem to me there could be any connection at all.

Paolo

**Comment by aalej** [comment]
Thanks for the update, it's good to know that it's now working! In case you encounter any issues moving forward, please don't hesitate to reach out to us.

**Comment by paxton-deployd** [comment]
@aalej https://assignation604.github.io/yiLJLJbCZdMJ3AdKy3EG7wk2Y0rFAoyz00ol0sgBsPJaUBK6n/
