### ISSUE TITLE
Re-auth needed every hour

### ISSUE THREAD

**Issue by ThomasKientz** [firebase/firebase-tools#7626]
When using `firebase deploy` 

I got the error :

> Error: Assertion failed: resolving hosting target of a site with no site name or target name. This should have caused an error earlier

I have to do `firebase login --reauth` and re-authenticate with browser in order to not have the error.

It looks like I stay connected for an hour and then needs to reauth again. 

I have tried to uninstall and reinstall firebase-tools but no changes.

**Comment by aalej** [comment]
Hey @ThomasKientz, thanks for reaching out. At the moment, it’s hard to determine what exactly is causing this issue. If you’re using a Google Workspace Account, my guess is that this is similar to https://github.com/firebase/firebase-tools/issues/6898. It’s possible that the session length set by your organization is causing the session to expire. 

However, if you think that the cause of the issue you’re encountering may be different, could you open a new report and provide the details using the specified template. This would give us enough information to be able to start our initial investigation. Please include the version of firebase-tools you’re using and your `firebase-debug.log`. Please remove any personal identifiable information(PII) before sharing your debug logs.

**Comment by ThomasKientz** [comment]
@aalej It does look the same as #6898 as I am using a Workspace Account as well.

**Comment by digibake** [comment]
Is there any suggested solution to this?
After months of having to reauthenticate every hour, it's really getting tiring to have to go through the oauth consent screens over and over and over.
