### ISSUE TITLE
TypeError: handler is not a function

### ISSUE THREAD

**Issue by bazquezero** [firebase/firebase-tools#764]
**Version Info**
firebase-tools: 3.18.4
firebase-admin 5.12.0
firebase-functions: 1.0.2

**Platform Information**
Windows

When I run the firebase serve command on an isomorphic React implementation, I get the following stack message every time I use a route, I'm using Express.js, to render the react views as seen on the [functions-samples](https://github.com/firebase/functions-samples/blob/master/isomorphic-react-app/functions/index.js) repo

`
TypeError: handler is not a function
    at cloudFunction (~\Project\node_modules\firebase-functions\lib\providers\https.js:37:41)
    at app.use (~\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\@google-cloud\functions-emulator\src\supervisor\worker.js:142:11)
    at Layer.handle [as handle_request] (~\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (~\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\index.js:317:13)
    at ~\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (~\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\index.js:335:12)
    at next (~\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\index.js:275:10)
    at app.use (~\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\@google-cloud\functions-emulator\src\supervisor\worker.js:114:7)
    at Layer.handle [as handle_request] (~\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (~\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\index.js:317:13)
`

Already uninstalled the emulator and re-install it, also deleted the config file *~/.config/configstore/@google-cloud/functions-emulator*

**Comment by laurenzlong** [comment]
Could you share your functions code?

**Comment by bazquezero** [comment]
```
import React from 'react'
import { renderToString } from 'react-dom/server'
import express from 'express'
import helmet from 'helmet'
import morgan from 'morgan'
import status from 'http-status'

import { default as Bundle } from 'Bundle'
import template from './template'

const ServerApp = React.createFactory(Bundle)

const renderApplication = (url, res, initialState) => {
  const html = ReactDOMServer.renderToString(ServerApp({ url: url, context: {}, initialState }))
  const templatedHTML = template({ body: html, initialState: JSON.stringify(initialState) })
  res.status(status.OK).send(templatedHTML)
}

const app = express()

app.use(helmet())
app.use(morgan('dev'))
app.get('/favicon.ico', (req, res) => {
  return res.send(204)
})
app.get('/', (req, res) => {
  return renderApplication(req.url, res)
})

export default app
```

```
const functions = require('firebase-functions');
const app = require('./dist/ssr.bundle').default;

exports.app = functions.https.onRequest(app);
```

I am actually transiling the code with webpack & babel

**Comment by laurenzlong** [comment]
It seems like the error comes from this line:
```
exports.app = functions.https.onRequest(app);
```

It is complaining that `app` is not a function. Could you add a console log above that line to print out what `app` is and share what you see?

**Comment by bazquezero** [comment]
```
info: undefined
```

This is really revealing, I will get back to my transpiled code, and try to figure out how come the bundle is not returning what I expected.

Thank you so much for your help!

**Comment by bazquezero** [comment]
The problem occurred because I forgot to add the **libraryTarget: "commonjs2"** option on the webpack config file

```
const config = {
  entry: ['./src/index.js'],
  target: 'node',
  externals: [nodeExternals()],
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: 'ssr.bundle.js',
    libraryTarget: 'commonjs2'
  },
  module: {
    rules: [
      {
        test: /\.js/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader',
          options: {
            babelrc: true,
          }
        }
      }
    ]
  },
  ...
}
```

**Comment by laurenzlong** [comment]
Glad you figured it out!

**Comment by shivgodi7** [comment]
This is what I get with I do console.log(handler); 
"
function () { [native code] } 
"
This does seem like a valid function, but I still still get the error as below:
TypeError: handler is not a function at cloudFunction (/srv/node_modules/firebase-functions/lib/providers/https.js

Will greatly appreciate if you a fix for this. Thanks !

**Comment by MuhammadPen** [comment]
just a quick heads up for anyone else who might come across this.
In my index file I was exporting my function like this:
```exports.magicAuth = functions.https.onCall(this.magicAuth);```
which is incorrect. (notice the `this` keyword)
removing it solved my issue
```exports.magicAuth = functions.https.onCall(magicAuth);```
