### ISSUE TITLE
Latest build is not downloadable from https://firebase.tools/bin/linux/latest

### ISSUE THREAD

**Issue by lukeshan-ctm** [firebase/firebase-tools#7648]
### [REQUIRED] Environment info

**firebase-tools:** 13.17.0

**Platform:** Linux

### [REQUIRED] Steps to reproduce

Our build pipeline is trying to download from https://firebase.tools/bin/linux/latest

It redirect to https://github.com/firebase/firebase-tools/releases/download/v13.17.0/firebase-tools-linux which is not exist. 

### [REQUIRED] Expected behavior

Firebase tools can be downloaded.

### [REQUIRED] Actual behavior

Firebase tools can not be downloaded.

**Comment by izzyaf** [comment]
https://github.com/firebase/firebase-tools/releases/tag/v13.17.0 does not include any executables.

**Comment by j-sheedy** [comment]
I'm seeing the same issue and it has broken our CI pipeline.

**Comment by minhnguyenandpad** [comment]
I got this issue too

**Comment by luiges90** [comment]
same here. CI pipeline broke.

**Comment by muhburhanudinn** [comment]
Yes, i'm seeing this issue too

**Comment by Luiz-Franco** [comment]
For macos too

**Comment by dapealfy** [comment]
same here... most of my CI pipeline rely on curl-ing the firebase tools

**Comment by JoshStrobl** [comment]
Adding to the choir. Broken in our CI pipeline as well.

**Comment by oreno4649** [comment]
macos too. Please make binary file.

**Comment by kucira** [comment]
Same issue here.

**Comment by lghsigma597** [comment]
For those who don't have `npm`:
```
curl -sL https://firebase.tools > temp.sh
sed -i s/latest/v13.16.0/ temp.sh
cat temp.sh | bash
```

**Comment by hendri-voodoo** [comment]
+1

**Comment by alexanderkorus-oskar** [comment]
+1

**Comment by aalej** [comment]
Hey folks, apologies for the issue this has caused, and thanks for reporting this and sharing workarounds. I’ll reach out to our engineering team so that we can get this fixed.

**Comment by SeniruHasith** [comment]
use this command instead

echo Install firebase
npm install -g firebase-tools@13.16.0

**Comment by altmas5** [comment]
> For those who don't have `npm`:
> 
> ```
> curl -sL https://firebase.tools > temp.sh
> sed -i s/latest/v13.16.0/ temp.sh
> cat temp.sh | bash
> ```

One-liner version:
```
curl -sL https://firebase.tools | sed s/latest/v13.16.0/ | bash
```

**Comment by aalej** [comment]
Hey everyone, sorry for the inconvenience, our team has re-uploaded the binaries and this should be fixed. Just to verify, could anyone let us know if you’re still encountering an issue?

**Comment by DeToxer** [comment]
Hello!
It works for me now

**Comment by aalej** [comment]
Thanks for verifying, I’ll go ahead and close this. If anyone encounters this issue moving forward, let us know so that we can re-open.

**Comment by BernalCarlos** [comment]
Hello, this is happening again today
