### ISSUE TITLE
Cannot start emulator. firebase-tools\node_modules\grpc was compiled against a different Node.js version

### ISSUE THREAD

**Issue by reyou** [firebase/firebase-tools#766]
### Version info

firebase --version
3.17.3

### Platform Information

Windows 10

npm --version
5.6.0
node --version
v10.1.0

"dependencies": {
    "firebase-admin": "^5.12.0",
    "firebase-functions": "^1.0.2",
    "firebaseui": "^2.5.1"
  }

### Steps to reproduce

Run following command:
`firebase serve --only functions --debug`

### Expected behavior

Emulator should start.

### Actual behavior

I tried to run `npm i firebase-tools -g`, but did not work.

I am getting following error:

> !  functions: Cannot start emulator. Error: The module '\\?\D:\Program Files\nodejs\node_modules\firebase-tools\node_modules\grpc\src\node\extension_binary\grpc_node.node'
> was compiled against a different Node.js version using
> NODE_MODULE_VERSION 57. This version of Node.js requires
> NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
> the module (for instance, using `npm rebuild` or `npm install`).

**Comment by bazquezero** [comment]
`import React from 'react'
import { renderToString } from 'react-dom/server'
import express from 'express'
import helmet from 'helmet'
import morgan from 'morgan'
import status from 'http-status'

import { default as Bundle } from 'Bundle'
import template from './template'

const ServerApp = React.createFactory(Bundle)

const renderApplication = (url, res, initialState) => {
  const html = ReactDOMServer.renderToString(ServerApp({ url: url, context: {}, initialState }))
  const templatedHTML = template({ body: html, initialState: JSON.stringify(initialState) })
  res.status(status.OK).send(templatedHTML)
}

const app = express()

app.use(helmet())
app.use(morgan('dev'))
app.get('/favicon.ico', (req, res) => {
  return res.send(204)
})
app.get('/', (req, res) => {
  return renderApplication(req.url, res)
})

export default app
`

`
const functions = require('firebase-functions');
const app = require('./dist/ssr.bundle').default;

exports.app = functions.https.onRequest(app);
`

I am actually transiling the code with webpack & babel

**Comment by laurenzlong** [comment]
Please update your firebase-tools to the latest by running "npm i -g firebase-tools"

**Comment by reyou** [comment]
Hi, @laurenzlong . As I mentioned in my report I already tried to run `npm i firebase-tools -g` but it did not help. I am missing something here?

**Comment by laurenzlong** [comment]
That would be an npm issue, not an issue that's specific to firebase-tools. What do you mean by "it did not work"? What do you see?

**Comment by laurenzlong** [comment]
What I mean is: what do you see when you run `npm i -g firebase-tools`? It did not work, since you still have an outdated firebase-tools version.

**Comment by reyou** [comment]
OK, let me run it again once I reach the work station and update you. Thanks for following up.

**Comment by reyou** [comment]
@merlinnot 
I have installed firebase-tools@3.18.4. Still getting same error.

**Comment by reyou** [comment]
OK, once I manually delete firebase-tools folder from node_modules and re-installed, error turns into https://github.com/GoogleCloudPlatform/cloud-functions-emulator/issues/205 seems like, it is related to node version now.
