### ISSUE TITLE
Firebase-tools should support a local firebase-bolt

### ISSUE THREAD

**Issue by mwaldstein** [firebase/firebase-tools#767]
### Version info

3.18.4

### Platform Information

Linux

### Steps to reproduce

1. Create a firebase project
2. Create firebase/database.rules.bolt
3. Configure firebase-db to use the bolt rules:
`{
  "database": {
    "rules": "firebase/database.rules.bolt"
  }
}`
4. Install firebase-tools and firebase-bolt as project dependencies
`npm i firebase-tools firebase-bold`
5. Attempt to deploy

### Expected behavior

The bolt rules are compiled and loaded to the project

### Actual behavior

An error is thrown that firebase-bolt must be installed globally

### Notes:

* The spawn of firebase-bolt only looks in the path: https://github.com/firebase/firebase-tools/blob/02f5e2eec9c558253e193e577fa45eeba1d9329a/lib/parseBoltRules.js

**Comment by samtstern** [comment]
I wonder if we could fix this by calling `npx firebase-bolt` which would look either locally or globally?
