### ISSUE TITLE
cannot login

### ISSUE THREAD

**Issue by tems99** [firebase/firebase-tools#77]
When I try to use Firebase Login through CLI,
it says 
Error: Cannot run login in non-interactive mode. Pass --token instead.

This is a newly installed PC. In my old PC, I could use firebase CLI.
In my newly installed PC, after installing firebase-tools, I tried to login using the command

firebase login

But instead got the error above.

**Comment by drtriumph** [comment]
How are you attempting to run the command? Through the command line, cygwin, PowerShell?

**Comment by mbleigh** [comment]
@tems99 we addressed this in #80. You should be able to login by upgrading to the latest version (2.0.2) of firebase-tools and running:

    divshot login --interactive

Please let me know if it doesn't work.

**Comment by hammy-109** [comment]
firebase login:ci --interactive

this is the solution

**Comment by bblanke** [comment]
Also using:
`firebase login --no-localhost `
worked for me

**Comment by DiegoFSFlor** [comment]
to me :)

**Comment by One-Technologies** [comment]
firebase login --interactive

working!! thnks!

**Comment by EmilS2019** [comment]
Not a single one of these worked for me. It still says "An unexpected error has occured" right after Paste authorization code here"

**Comment by lusamdebonfils** [comment]
firebase login --interactive
Works perfectly. Thanks!!

**Comment by AhamedR** [comment]
In windows 
if you are using **Git Bash** try using **CMD**.

**Comment by mrgab0** [comment]
from cygwin windows 7 sp1. same trouble, 
instead of use cygwin use cmd firebase login 

solved!

**Comment by islam-Ellithy** [comment]
In windows
You can use terminal of vscode ,it works like a sharm

**Comment by p4309027** [comment]
this one worked for me to generate the token for `ci/cd`:

`$ firebase login:ci --interactive --no-localhost`

**Comment by imvikaskohli** [comment]
> firebase login:ci --interactive
> 
> this is the solution

this worked for me

**Comment by acatzk** [comment]
damn.... firebase login --interactive HAHAH thanks a lot

**Comment by Punisher2501** [comment]
Noting seems to work form all of above in my case can someone help 
![not working](https://user-images.githubusercontent.com/65228766/106469353-2f4f6780-64c5-11eb-9424-3eda8f800263.png)

**Comment by MdSakibAhmed** [comment]
I had same problem. i can solve my problem by this command firebase login:ci --interactive

**Comment by JBeichert** [comment]
> 
> 
> In windows
> if you are using **Git Bash** try using **CMD**.

THANKS that fixed it for me!

**Comment by mrdanishsaleem** [comment]
firebase login --interactive

Worked like a charm 🤩

**Comment by mohammad-zakaria** [comment]
> firebase login:ci --interactive
> 
> this is the solution

It works, thanks :)

**Comment by parisa7103** [comment]
I am using firebase version 11.0.1, and the problem still exists. when I try to run `firebase init` I faced this error ` Failed to make request to https://firebase-public.firebaseio.com/cli.json`.
I tried to log out and log in again, but the error is shown at the end of each response.

**Comment by snazhmudinov** [comment]
This issue still persists for me, when running on linux CI machines.
I specified both `GOOGLE_APPLICATION_CREDENTIALS` and `FIREBASE_TOKEN` env variables, however that doesn't help.
I get `Error: Cannot run login:ci in non-interactive mode.`

My command:

```bash
env GOOGLE_APPLICATION_CREDENTIALS="..." \
    FIREBASE_TOKEN="..." \
    firebase login:ci
```

**Comment by champ96k** [comment]
I'm also getting error in azure-cdcd pipeline for firebase project authentication  #6276

**Comment by samakpan-sp** [comment]
firebase login --interactive worked for me. Thanks
