### ISSUE TITLE
Astro ssr app can not visit.

### ISSUE THREAD

**Issue by KAROTT7** [firebase/firebase-tools#7713]
I am building a ssr app by Astro, but I can not visit ssr page after deployed to firebase. Are there some google cloud settings need to  set?

### [REQUIRED] Environment info

**firebase-tools:** 13.18.0

**Platform:** windows 11

**Astro:** 4.15.8

**Astro config:**
```js
export default defineConfig({
	integrations: [tailwind(), react()],

	vite: {
		resolve: {
			alias: {
				'@': path.resolve('src')
			}
		}
	},

	output: 'server',

	adapter: node({
		mode: 'standalone'
	})
})
```

I just run `firebase deploy` to deploy this website

### [REQUIRED] Test case

[https://astro-demo-3bsfa.web.app/](test-app) is my demo, /contact is ssr page, others are prerendered pages, every time I visit /contact, I got follow error message:
```json
{
  "textPayload": "The request has been terminated because it has reached the maximum request timeout. To change this limit, see https://cloud.google.com/run/docs/configuring/request-timeout",
  "insertId": "66f171000000ef569f2a7318",
  "httpRequest": {
    "requestMethod": "GET",
    "requestUrl": "https://fh-fd8f0b77e83ef120---ssrecanaluminiumdcab6-lgedo3umqq-de.a.run.app/contact",
    "requestSize": "1558",
    "status": 504,
    "responseSize": "72",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36",
    "remoteIp": "*.*.*.*",
    "referer": "https://astro-demo-3bsfa.web.app/about",
    "serverIp": "*.*.*.*",
    "latency": "59.996048509s",
    "protocol": "HTTP/1.1"
  },
  "resource": {
    "type": "cloud_run_revision",
    "labels": {
      "project_id": "ecan-aluminium",
      "location": "asia-east1",
      "configuration_name": "ssrecanaluminiumdcab6",
      "revision_name": "ssrecanaluminiumdcab6-00003-kon",
      "service_name": "ssrecanaluminiumdcab6"
    }
  },
  "timestamp": "2024-09-23T13:44:36.054783Z",
  "severity": "ERROR",
  "labels": {
    "goog-managed-by": "cloudfunctions",
    "instanceId": "007989f2a1acaac01d4e7a19481d6447ce25c7f6ceb8046800bf37fd82fcb1aa2d856e16225e2bdccd92739a002325dcaf3f742c13c15a6ce065b28daece93bbbf435b18"
  },
  "logName": "projects/ecan-aluminium/logs/run.googleapis.com%2Frequests",
  "trace": "projects/ecan-aluminium/traces/7481490b5e58869de6311208b3354744",
  "receiveTimestamp": "2024-09-23T13:45:36.071094738Z",
  "spanId": "746e62eae5abe942",
  "traceSampled": true
}
```

### [REQUIRED] Steps to reproduce
Please visit [https://astro-demo-3bsfa.web.app/](test-app)

### [REQUIRED] Expected behavior
the page /contact can be visited

### [REQUIRED] Actual behavior
the page /contact can not visit. After some time, page show `Timed out while waiting on cache-itm1220031-ITM`

----
Please tell me how to fix it, I am so sad...

**Comment by leoortizz** [comment]
Hey @KAROTT7, as stated [in the docs](https://github.com/firebase/firebase-tools/blob/master/src/frameworks/docs/astro.md#serve-fully-dynamic-content-ssr), can you please change your adapter mode to `middleware` and report back here?

Change from:
```ts
adapter: node({
  mode: 'standalone'
})
``` 
To:
```ts
adapter: node({
  mode: 'middleware'
})
```

**Comment by KAROTT7** [comment]
@leoortizz It worked successfully! Thank you! :)
