### ISSUE TITLE
firebase deploy fail to deploy function with globalOptions using defineConfig with version 13.19.0

### ISSUE THREAD

**Issue by polem** [firebase/firebase-tools#7720]
### Environment info

13.19.0

**firebase-tools:**

gitlab ci using node:20-alpine image

### Test case

i have this following function:

```js
// index.js
import { setGlobalOptions } from "firebase-functions/v2";
import { defineString } from 'firebase-functions/params';
import { onRequest } from "firebase-functions/v2/https";

const REGION = defineString('REGION')

setGlobalOptions({
    region: REGION,
});

export const hello = onRequest(async (req, res) => {
    res.send(`Hello from hello firebase function!`);
});
```

with this env file:

```
# .env
REGION=europe-west1
```

### Steps to reproduce

run `firebase deploy`

### Expected behavior

deploy success

### Actual behavior

We tested with version 13.18.0 and 13.17.0 without issues but starting with version 13.19.0 we have the following logs:

`firebase deploy --project stg`
```
=== Deploying to 'xxxxx'...
i  deploying firestore, functions, hosting
i  firestore: reading indexes from firestore.indexes.json...
i  cloud.firestore: checking firestore.rules for compilation errors...
⚠  [W] undefined:undefined - Ruleset uses old version (version [1]). Please update to the latest version (version [2]).
✔  cloud.firestore: rules file firestore.rules compiled successfully
i  functions: preparing codebase default for deployment
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
i  artifactregistry: ensuring required API artifactregistry.googleapis.com is enabled...
✔  functions: required API cloudbuild.googleapis.com is enabled
✔  artifactregistry: required API artifactregistry.googleapis.com is enabled
✔  functions: required API cloudfunctions.googleapis.com is enabled
⚠  functions: package.json indicates an outdated version of firebase-functions. Please upgrade using npm install --save firebase-functions@latest in your functions directory.
⚠  functions: Please note that there will be breaking changes when you upgrade.
i  functions: Loading and analyzing source code for codebase default to determine what to deploy
⚠  functions: You are using an old version of firebase-functions SDK (4.6.0). Please update firebase-functions SDK to >=5.1.0
i  functions: Loaded environment variables from .env, .env.stg.
i  functions: preparing functions directory for uploading...
i  functions: packaged /builds/xxx/xxx/functions (32.95 KB) for uploading
i  functions: ensuring required API run.googleapis.com is enabled...
i  functions: ensuring required API eventarc.googleapis.com is enabled...
i  functions: ensuring required API pubsub.googleapis.com is enabled...
i  functions: ensuring required API storage.googleapis.com is enabled...
✔  functions: required API run.googleapis.com is enabled
✔  functions: required API eventarc.googleapis.com is enabled
✔  functions: required API storage.googleapis.com is enabled
✔  functions: required API pubsub.googleapis.com is enabled
i  functions: generating the service identity for pubsub.googleapis.com...
i  functions: generating the service identity for eventarc.googleapis.com...
i  firestore: deploying indexes...
i  firestore: latest version of firestore.rules already up to date, skipping upload...
✔  firestore: deployed indexes in firestore.indexes.json successfully for (default) database
There was an issue deploying your functions. Verify that your project has a Google App Engine instance setup at https://console.cloud.google.com/appengine and try again. If this issue persists, please contact support.
⚠  functions: Upload Error: HTTP Error: 403, Permission denied on 'locations/params.region' (or it may not exist).
Error: HTTP Error: 403, Permission denied on 'locations/params.region' (or it may not exist).
```

**Comment by polem** [comment]
the issue is with `defineString` resolve, when we use:

```
setGlobalOptions({
    region: 'europe-west1',
});
```

everyhting is fine.

**Comment by urakozz** [comment]
Same issue here, but we don't use `defineString`. We set region as a constant in `setGlobalOptions` based on the projectId. But then there are several `defineSecret` and I guess this fails the same way as `defineString` in the case above

**Comment by aalej** [comment]
Hey folks, thanks reporting this and sharing your workarounds. Currently, I’m able to reproduce this when using firebase-tools v13.19.0 and firebase-functions v4.6.0. I tried updating to firebase-functions v5.1.0 and I was able to deploy the functions.

Just to verify, which version of the firebase-functions SDK are you currently using? If you’re using an older version of the firebase-functions SDK, could you try updating to firebase-functions v5.1.0 or greater to see if this would resolve the issue?

**Comment by urakozz** [comment]
@aalej In our case it's `"firebase-functions": "^6.0.1"` 👀

**Comment by tannerstern** [comment]
We had an issue with v13.19.0 deploying functions yesterday as well. Certain functions that were definitely in our source code were not being found and thus showing the interactive prompt: `The following functions are found in your project but do not exist in your local source code`.

We are not using `defineString` or `setGlobalOptions`, but somehow the list of functions to deploy has changed (reverting back to v13.18.0 solved the issue for us, as it seems it has for others here). We are on `firebase-functions` v5.0.1`, though I am skeptical that it has anything to do with that: our CI builds started failing with the update of `firebase-tools` to `v13.19.0`.

**Comment by aalej** [comment]
Currently, I’m able to deploy using `firebase-tools` v13.19.0 and `firebase-functions` v6.0.1. I’m not sure if I may be missing something here, but let me ask our engineering team to get a better idea of what could be causing this issue.

**Comment by urakozz** [comment]
@aalej locally I can also deploy when I'm authorised with `firebase login`. It happens in the CI since there authorisation there goes through the `service-account.json` with limited Access Roles. My guess would be that Service Account for CI need some extra Roles after the recent update

**Comment by polem** [comment]
> Just to verify, which version of the firebase-functions SDK are you currently using? If you’re using an older version of the firebase-functions SDK, could you try updating to firebase-functions v5.1.0 or greater to see if this would resolve the issue?

You right the project was on firebase-functions : 4.6.0, we fixed firebase-tools version, but i will try to update this and tell you

**Comment by colerogers** [comment]
Sorry everyone, the current release of firebase-tools had bumped the minimum SDK version to v5.1.0. This was a mistake and we've reverted the change in #7731 which should be released today. Thanks for your patience!

**Comment by urakozz** [comment]
@colerogers TBH nothing has changed fir us, I'd stick with v13.19.0 😆
