### ISSUE TITLE
version 13.19.0 Deployment Error: storage event trigger is missing bucket filter

### ISSUE THREAD

**Issue by codin-play** [firebase/firebase-tools#7726]
### [REQUIRED] Environment info

Deployment via Ubuntu `npm install -g firebase-tools@13.19.0` (this version was released yesterday)

### [REQUIRED] Test case

Deployment fails when using a function leveraging the event type of `google.cloud.storage.object.v1.finalized`

### [REQUIRED] Steps to reproduce

1. Deploy system with an `onObjectFinalized()` via `npm run firebase-deploy`
```
const mediaStorageUploadTrigger = onObjectFinalized(
  {
    minInstances: 2,
    maxInstances: 10,
    timeoutSeconds: 60,
    memory: '256MiB',
    bucket: '**'
  },
  async () => {
    return { success: true }
  }
);
```

2. Notice deployment error:
```
Error: Error: storage event trigger is missing bucket filter: {
  "eventType": "google.cloud.storage.object.v1.finalized",
  "retry": false,
  "eventFilters": {
    "resource": "***"
  }
}
```

3. Change firebase-tools version to previous: `npm install -g firebase-tools@13.18.0`
4. Run `npm run firebase-deploy`
5. Deployment successful
### [REQUIRED] Expected behavior

Deployment is successful with the new firebase-tools version

### [REQUIRED] Actual behavior

```
Error: Error: storage event trigger is missing bucket filter: {
  "eventType": "google.cloud.storage.object.v1.finalized",
  "retry": false,
  "eventFilters": {
    "resource": "***"
  }
}

**Comment by richard-here** [comment]
I am facing the same issue here.

**Comment by nvzoll** [comment]
Same here. Worked with 13.18.0.

**Comment by AurelioB** [comment]
After I upgraded the firebase-functions package to v5.1.1 the error disappeared. The [v13.19.0](https://github.com/firebase/firebase-tools/releases/tag/v13.19.0) release of firebase-tools states that the minimum expected version is v5.1.0. I was on v4.X
I also had to enable the Cloud Billing API

**Comment by colerogers** [comment]
Sorry everyone, the current release of firebase-tools had bumped the minimum SDK version to v5.1.0. This was a mistake and we've reverted the change in #7731 which should be released today. Thanks for your patience!

**Comment by colerogers** [comment]
Firebase tools v13.20.0 has been released which should fix this behavior
