### ISSUE TITLE
[firebase-tools  13.19.0 ] functions deploy fails with [object Object] when reading a secret. (13.6.1 works)

### ISSUE THREAD

**Issue by sondretj** [firebase/firebase-tools#7728]
### [REQUIRED] Environment info

**firebase-tools:** 13.6.1 and 13.19.0

**Platform:** Github actions

### [REQUIRED] Test case
Sorry, don't have time now. And since I dont work with this regularly I figured it was better to try to submit a bug fast, rather than ignoring it and maybe pick it up the next time I will work on this.

### [REQUIRED] Steps to reproduce

Write a function in JS that uses a secret: 
```const secret = defineSecret("SECRET");```

Deploy firebase functions that uses a secret using the newest version. 13.19.0

### [REQUIRED] Expected behavior

It deploys successfully.

### [REQUIRED] Actual behavior
It fails with:

```
Error: Failed to validate secret versions:
- FirebaseError HTTP Error: 400, The provided Secret ID [projects/myproject/secrets/[object Object]/versions/latest] does not match the expected format [projects/*/secrets/*/versions/*]
```

Screenshot from Github Actions where it started failing:
```
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Dev Environment
        run: |
          npm run deploy:dev
```
<img width="1098" alt="Skjermbilde 2024-09-24 kl  22 03 28" src="https://github.com/user-attachments/assets/c96c52b6-3202-46a7-bb38-a2e0524ecc0e">

Screenshot from Github Actions where it works:
```
      - name: Install Firebase CLI
        run: npm install -g firebase-tools@13.6.1

      - name: Deploy to Dev Environment
        run: |
          npm run deploy:dev
```
<img width="657" alt="Skjermbilde 2024-09-24 kl  22 02 56" src="https://github.com/user-attachments/assets/24de6c8c-54f1-4b87-b35a-58002efdda09">

**Comment by aalej** [comment]
Hey folks, thanks reporting this. It looks like the error is happening due to the incorrect url "/secrets/[object Object]/versions/latest". To help us narrow down the cause of the issue, could anyone let me know if you're encountering this error when using firebase-tools v13.18.0?

Currently, I'm able to reproduce the issue when using firebase-tools v13.19.0 and firebase-functions <= 5.0.1. However, when upgrading firebase-functions to >=5.1.0, I'm able to deploy successfully.

**Comment by 6h4n3m** [comment]
@aalej Issue happens only on 13.9.0 for me. Both 3.8.0 and 13.7.0 work properly, currently on `firebase-functions` 4.4.1

**Comment by colerogers** [comment]
Sorry everyone, the current release of firebase-tools had bumped the minimum SDK version to v5.1.0. This was a mistake and we've reverted the change in #7731 which should be released today. Thanks for your patience!

**Comment by colerogers** [comment]
Firebase tools v13.20.0 has been released which should fix this behavior
