### ISSUE TITLE
Error while deploying w/ @google-cloud/firestore

### ISSUE THREAD

**Issue by toots** [firebase/firebase-tools#773]
I'm seeing this today, this is news to me:

```
⚠  functions[api]: Deployment error.
Function load error: Code in file src/index.js can't be loaded.
Is there a syntax error in your code?
Detailed stack trace: Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /user_code/node_modules/@google-cloud/firestore/node_modules/grpc/src/node/extension_binary/node-v48-linux-x64-glibc/grpc_node.node)
    at Error (native)
    at Object.Module._extensions..node (module.js:604:18)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/user_code/node_modules/@google-cloud/firestore/node_modules/grpc/src/grpc_extension.js:32:13)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
```

**Comment by laurenzlong** [comment]
This is a production incident that is being investigated now, please follow https://status.firebase.google.com/incident/Functions/18026 for the latest status.

**Comment by toots** [comment]
@laurenzlong That seems fixed indeed. However, I'm now seeing a bunch of:
```
Function execution took 407 ms, finished with status: 'connection error'
```
On code that was previously working. No errors raised and nothing in the logs. Could that be related? How can I debug this?

**Comment by fjbatresv** [comment]
Me too...
All the invocations to Cloud Functions return this error message.

**Comment by k-koehler** [comment]
Executing a cloud function which used admin-ask results in:

Error: function crashed. Details:
/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /user_code/node_modules/firebase-admin/node_modules/grpc/src/node/extension_binary/node-v48-linux-x64-glibc/grpc_node.node)

However, cloud function calls which do not use admin-sdk return normally.
