### ISSUE TITLE
Cannot choose an app on windows

### ISSUE THREAD

**Issue by val-samonte** [firebase/firebase-tools#78]
On firebase init, I cannot select an existing app from the terminal, even if it displays my existing apps (select in the means of using arrow keys)

**Comment by drtriumph** [comment]
How are you attempting to run the command? Through the command line, cygwin, PowerShell? I assume you were able to login to the tools just fine?

**Comment by val-samonte** [comment]
@drtriumph im running the command via command line. yep i was be able to login just fine.

**Comment by drtriumph** [comment]
For now I think the `-f <app_name>` option will allow you to proceed, and we'll try reproducing this. What version of windows / node / npm are you running?

**Comment by val-samonte** [comment]
hi @drtriumph, sorry for the late response. currently using windows 10, node 4.1.1, npm 2.14.4. tried to go legacy mode from the command terminal and unfortunately I still encountered the same.

**Comment by MarkusPint** [comment]
Same issue here. Win 10, node 4.2.1

```firebase init -f <app_name>``` worked though

**Comment by ClintH** [comment]
:+1: same on Win 10, Node 4.1.1 in both Command Prompt and PowerShell

**Comment by b00mtastik** [comment]
Hey guys, same issue on Windows 10 Node 5.0.0 in Command Prompt and Powershell including Powershell ISE as Administrator. Can't kill the current task either. Have to exit out of Powershell entirely.

**Comment by mbleigh** [comment]
This should be working in `firebase init` now, though the underlying Node bug still persists.

**Comment by Karasuni** [comment]
May I ask what the underlying Node bug is? I'm seeing the same issue on Win7, Node v6.2.2, Firebase 3.0.3. Also the workaround ``firebase init -f <app_name>`` doen't work for me as the ``-f`` option is unknown.

**Comment by eGlobeBizCom** [comment]
This issue happens to my Gitbash sometimes.  Sometimes, the arrow keys work, sometimes they do not. Any workarounds?

**Comment by jordano1** [comment]
Try using windows command prompt, I was trying to use the git terminal but it wasn't working, so then I tried using the command prompt (windows terminal), navigated to my project directory and initialized in there, and it worked. It also let me select the options, whereas in the git terminal I wasn't able to select anything with keys or pressing the space bar.

**Comment by EvilAlexei** [comment]
Same issue.
Windows 10, Node.Js 8.1.0.
Tried command line and git bash, can't choose anything while trying to init project. Not by space or by arrow keys.

**Comment by narvati** [comment]
Same issue.
Windows 10, Node.Js 8.1.0.
Tried command line and git bash, can't choose anything while trying to init project. Not by space or by arrow keys.

**Comment by krisu7** [comment]
I have the same issue

**Comment by krisu7** [comment]
Node.js LTS Version: v6.11.0 works for me

**Comment by EncryptedNomad** [comment]
Same issue with Win 10 16215, VS '17 Preview 2, and Node 8.1.0 (x64)

**Comment by EvilAlexei** [comment]
Update on issue - i think problem in Node 8.x.x, I have same issue on NodeJs 8.1.0, OS Windos 10 and Linux, different command lines. After i downgrade NodeJs to version 7.8.0 issue gone and navigation begin to work by keys(arrows and space).

**Comment by laurenzlong** [comment]
Yes it does appear to be a Node 8 issue. I reproduced this (on Linux), and will investigate a fix. Filed https://github.com/firebase/firebase-tools/issues/370 to track this, since it's a separate issue than this original one.

**Comment by jarjarbits** [comment]
i was having the same problem (while trying to use gitBash), i switched over to comand prompt and the arrows keys work there

**Comment by krisdev-pl** [comment]
It's working for me in node version v8.1.2

**Comment by chrisjeremi98** [comment]
Iam using cmd on windows and the arrow works, but when using git the arrow doesnt move a bit
npm version 5.5.1 and node 8.9.1

**Comment by honeyhoney** [comment]
Selecting features during `firebase init` via space does not work with Git Bash. No problems when using `cmd.exe`.

* Windows 7 (x64)
* npm: `5.5.1`
* node: `9.2.0`
* git bash: `2.15.0`

**Comment by sakshi-samdani** [comment]
i m using cmd in windows 8 but still not working.

**Comment by laurenzlong** [comment]
@sakshi-samdani  Can you provide info on the version of firebase-tools and Node you are using?

**Comment by music-mind** [comment]
Have this issue as well with git bash
Windows 10
Node v9.4.0
Npm v5.6.0
Git 2.11.0
Latest firebase tools

**Comment by abhishekBansal** [comment]
Reproducing with macos
NPM v5.6.0
Node v8.1.0

**Comment by ASahak96** [comment]
It's working with me in cmd win7 or win10

**Comment by oksiweb** [comment]
> Reproducing with macos
> NPM v5.6.0
> Node v8.1.0
> 
> It strangely gets stuck on project selection upon using `firebase init` and gets stuck on language selection upon using `firebase init functions`

tha same for me

**Comment by triay0** [comment]
Same for me 
NPM v 6.9.0
node v10.15.0

**Comment by samtstern** [comment]
@oksiweb and @triay0 please track issue #1420 for updates about a possible issue today.
