### ISSUE TITLE
Support for tstzrange and GeoPoint in Firebase DataConnect

### ISSUE THREAD

**Issue by 1amageek** [firebase/firebase-tools#7808]
### Context
I am using Firebase tools and DataConnect, and I'd like to request support for `tstzrange` (timestamp with time zone range) and `GeoPoint`. Adding support for these data types would greatly enhance DataConnect's flexibility for handling time-based ranges and geospatial data.

### Proposal
- **tstzrange Support**: Support for `tstzrange` would improve operations involving timestamp ranges, which is especially beneficial for applications managing time-sensitive data. Currently, the lack of native support requires complex workarounds, making data handling more challenging.
  
- **GeoPoint Support**: Introducing `GeoPoint` would enable efficient handling of geographic data. This would be particularly useful for applications that need to store and query geolocation data, streamlining processes involving distance calculations and spatial queries.

Thank you for considering these feature requests!

**Comment by mbleigh** [comment]
Thanks for the feature request! This is the repo for the Firebase CLI and so isn't the best place to keep track of Data Connect feature requests. Can you file these requests on the [Data Connect UserVoice category](https://firebase.uservoice.com/forums/948424-general?category_id=501596) so we can track interest?
