### ISSUE TITLE
HOSTING REQUEST

### ISSUE THREAD

**Issue by Rhedaligan8** [firebase/firebase-tools#7823]
Please submit feature requests through our [support page](https://firebase.google.com/support/troubleshooter/report/features/).

**Comment by aalej** [comment]
Hey @Rhedaligan8, there isn't any information in this report so I'll go ahead and close this. If there's a feature you would like to see added to the Firebase CLI, please create a new report and specify the details so that we can have a better understanding of the request. Thanks!
