### ISSUE TITLE
???????????? 

### ISSUE THREAD

**Issue by Koronuma4Dev** [firebase/firebase-tools#7835]
Please submit feature requests through our [support page](https://firebase.google.com/support/troubleshooter/report/features/).

**Comment by aalej** [comment]
Hey @Koronuma4Dev, there isn't any details provided in this report, so I'll go ahead and close this. If you're encountering an issue or have a feature you'd like see implemented in Firebase Tools, please open a new report with additional details. Thanks!

**Comment by Koronuma4Dev** [comment]
![Capture 2](https://github.com/user-attachments/assets/72811857-fcc8-42b8-b3b6-238a00c92939)
 @aalej

**Comment by Koronuma4Dev** [comment]
hi @aalej thank u for response, I assure you to be more specific on my error in deploying a project in firebase.
