### ISSUE TITLE
Package `firebase-frameworks` is not compatible with firebase@v11

### ISSUE THREAD

**Issue by service-paradis** [firebase/firebase-tools#7880]
### [REQUIRED] Environment info

**firebase-tools:** 13.22.1

**Platform:** Any

### [REQUIRED] Test case

```
  npm error While resolving: firebase-frameworks@0.11.4
  npm error Found: firebase@11.0.0
  npm error node_modules/firebase
  npm error   firebase@"11.0.0" from the root project
  npm error
  npm error Could not resolve dependency:
  npm error peerOptional firebase@"^9.9.0 || ^10.0.0" from firebase-frameworks@0.11.4
  npm error node_modules/firebase-frameworks
  npm error   firebase-frameworks@"^0.11.0" from the root project
  npm error
  npm error Conflicting peer dependency: firebase@10.14.1
  npm error node_modules/firebase
  npm error   peerOptional firebase@"^9.9.0 || ^10.0.0" from firebase-frameworks@0.11.4
  npm error   node_modules/firebase-frameworks
  npm error     firebase-frameworks@"^0.11.0" from the root project
  npm error
  npm error Fix the upstream dependency conflict, or retry
  npm error this command with --force or --legacy-peer-deps
  npm error to accept an incorrect (and potentially broken) dependency resolution.
```

### [REQUIRED] Steps to reproduce

1. Create a NextJs project and use Firebase `frameworksBackend` hosting with `firebase@v11`. 
2. Install dependencies
3. Build the project
4. Try to deploy a preview channel with something like `npx firebase-tools@latest hosting:channel:deploy ...`

### [REQUIRED] Expected behavior

A new preview channel being created.

### [REQUIRED] Actual behavior

Right now, we got a dependency error coming from `firebase-frameworks` when using `firebase@v11`. The package `firebase-frameworks` need to be updated to be compatible with `firebase@v11` (https://github.com/FirebaseExtended/firebase-framework-tools/blob/main/packages/firebase-frameworks/package.json#L56).

I wanted to open an issue in the https://github.com/FirebaseExtended/firebase-framework-tools repo, but unfortunately, issues are not enabled there.

Ref. https://github.com/firebase/firebase-js-sdk/issues/8594

**Comment by aalej** [comment]
Hey @service-paradis, thanks for creating a detailed report and for sharing your observations! I'll raise this to our engineering team so they can take a look.
