### ISSUE TITLE
Failed to determine service account error when trying to use the cloud tasks emulator

### ISSUE THREAD

**Issue by MeadBarrel** [firebase/firebase-tools#7881]
### [REQUIRED] Environment info

**firebase-tools: 13.23.0**

**Platform: Ubuntu 22.04.5 LTS running on WSL2**

### [REQUIRED] Test case

Firebase.json:
```json
{
  "firestore": {
    "rules": "firestore.rules",
    "indexes": "firestore.indexes.json"
  },
  "functions": [
    {
      "source": "functions",
      "codebase": "default",
      "ignore": [
        "node_modules",
        ".git",
        "firebase-debug.log",
        "firebase-debug.*.log",
        "*.local"
      ]
    }
  ],
  "emulators": {
    "functions": {
      "port": 5001
    },
    "firestore": {
      "port": 8089
    },
    "ui": {
      "enabled": true
    },
    "singleProjectMode": true,
    "database": {
      "port": 9009
    },
    "tasks": {
      "port": 9499
    }
  },
  "database": {
    "rules": "database.rules.json"
  }
}
```

index.js:
```javascript
const admin = require("firebase-admin");
const { onRequest } = require("firebase-functions/v2/https");
const { getFunctions } = require("firebase-admin/functions");
const { onTaskDispatched } = require("firebase-functions/v2/tasks");

admin.initializeApp();


exports.testOnRequest = onRequest(async (request, response) => {
  const taskPayload = {
    foo: "bar",
  };
  const targetUri = "testOnTaskDispatched"; 

  const queue = getFunctions().taskQueue(targetUri);

  try {
    await queue.enqueue(taskPayload);
  } catch (error) {
    console.error("Error scheduling task", error);
    response.status(500).send("Error scheduling task");
    return;
  }
  response.send("Hello from HTTP ON REQUEST!");
});

exports.testOnTaskDispatched = onTaskDispatched((request) => {
  console.info("Hello logs from TASKS ON TASK DISPATCHED!", {
    foo: request.data,
  });

});

```

### [REQUIRED] Steps to reproduce

I run firebase emulators:start --project=demo-project

The log shows the task queue was created by the emulator:

✔  tasks: Created queue with key: queue:demo-reemedical-project-us-central1-testOnTaskDispatched

However, when i trigger `testOnRequest`, i get this:

>    errorInfo: {
>      code: 'functions/unknown-error',
>      message: 'Failed to determine service account. Initialize the SDK with service account credentials or set service account ID as an app option.'
>    },
>    codePrefix: 'functions'

### [REQUIRED] Expected behavior

Cloud tasks emulator triggering testOnTaskDispatched

### [REQUIRED] Actual behavior

I get 'Failed to determine service account' error.

**Comment by aalej** [comment]
Hey @MeadBarrel, thanks for creating a detailed report! I've been trying to reproduce this, but so far after running the emulators and invoking the emulated `testOnRequest` function, it triggers `testOnTaskDispatched` without any issues.

Using the provided code snippets and config, I created this [mcve](https://github.com/aalej/issues-7881). Could you try running this to see if you'd encounter the same error. Let me know if I may be missing anything here.

Also, any chance you could share the contents of your firebase-debug.log? I’m not sure if this could be a platform specific issue, and having those logs might give us a better understanding of what could've caused the error. Please remove any personal identifiable information(PII) before sharing the contents.

**Comment by MeadBarrel** [comment]
Sorry i feel really dumb right now. All it took is updating firebase-admin. But i'm kinda new to the node infrastructure and would've never guesed without looking at your code.
