### ISSUE TITLE
Firebase hosting site is failing our pen testing scan - headers and redirect configuration

### ISSUE THREAD

**Issue by tommed** [firebase/firebase-tools#790]
### Version info

`3.18.5`

### Platform Information

Windows 10 x64

### Steps to reproduce

1. Setup some headers in your firebase.json file:

```json
"headers": [
      {
        "source": "**/*",
        "headers": [
          { "key": "Referrer-Policy", "value": "no-referrer-when-downgrade" },
          { "key": "X-XSS-Protection", "value": "1; mode=block" },
          { "key": "X-Content-Type-Options", "value": "nosniff" },
          { "key": "X-Frame-Options", "value": "DENY" }
        ]
      }
    ]
```

2. Add an index.html page to the `public` folder
3. Access the root url (e.g. without index.html, such as `https://yourproject.firebase-whatever.com/`)
4. Notice how your headers aren't in the response, it implicitly renders the index.html page, but the headers aren't included. If you add `index.html` to the URL, then they are
5. Now add an explicit redirect from `/` to `/index.html` as a workaround, this has a different security issue as shown in this CURL request:

```json
"redirects": [ 
      {
        "source" : "/",
        "destination" : "/index.html",
        "type" : 301
      }
    ],
```

```bash
$ curl "https://yourproject.firebase-whatever.com/?\"><script>_q_q=')('</script>"
Redirecting to /index.html?"><script>_q_q=')('</script>
```

### Expected behavior

1. Headers should be returned for all requests (as filter suggests)
2. I didn't tell the redirect to include the query string, so it shouldn't have included that XSS script param

### Actual behavior

1. Headers not returned for `/` request
2. Redirect includes query parameters which fails our pen testing scan (script in query param echoed back by server)

**Comment by tommed** [comment]
Is there no desire to configure Firebase to be secure by default? I have reached out to the Firebase team via the "report a bug" section of the site, but no one has been in contact

**Comment by mbleigh** [comment]
Your glob pattern is `**/*` which means it will not match `/` because there is nothing after the`/` to be matched. Try `**` instead. I can confirm that it correctly adds headers to `/`.

Redirects intentionally include query parameters because this is the desired behavior in the vast majority of scenarios. This behavior is unlikely to change.

**Comment by tommed** [comment]
Ok, but that's not the only reason it's failing:

1. SSL/TLS Protocol Initialization Vector Implementation Information Disclosure Vulnerability (BEAST) 
1. SSL Medium Strength Cipher Suites Supported

**Comment by tommed** [comment]
Yeh weirdly, we have a Qualys pen testing subscription and it gives it the all clear, but our independent team have flagged it using theirs. I'll look into this as it may be a false positive. Thanks
