### ISSUE TITLE
Data Connect Extension incorrectly reporting Firebase CLI not installed

### ISSUE THREAD

**Issue by jolindroth** [firebase/firebase-tools#7910]
### [REQUIRED] Environment info

**firebase-tools:** Latest from NPM (13.24.1) and also tested with latest binary

**Platform:** Windows

### [REQUIRED] Test case

Follow data connect installation tutorial on windows.

### [REQUIRED] Steps to reproduce
1.  run  npm install -g firebase-tools in powershell
2.  run 'firebase' to confirm cli is added to PATH
3.  install firebase data connect extension
4.  restart vs-code
5.  "The Firebase CLI is not installed (or not available on $PATH). If you would like to install it, run curl -sL https://firebase.tools | bash"

### [REQUIRED] Expected behavior

The firebase data connect extension should recognize that firebase CLI is installed by NPM. Additionally, the binary installation of firebase tools should also add "firebase" to PATH.

### [REQUIRED] Actual behavior

Should work

**Comment by aalej** [comment]
Hey @jolindroth, thanks for reporting this. I'm able to reproduce the behavior you mentioned, though it seems like a specific issue to Windows, as I wasn't able to replicate this on macOS. I'll notify our team about this issue.

Also, even though a warning message was shown, commands on the VS Code extension like “Run firebase init” still seems to work. Just to verify, are you also able to run the commands or are there errors raised when running them?
