### ISSUE TITLE
crashlytics:symbols:upload produces unknown error

### ISSUE THREAD

**Issue by Zaratusa** [firebase/firebase-tools#7911]
### [REQUIRED] Environment info

**firebase-tools:** 13.24.1

**Platform:** Ubuntu 22.04 - Docker

### [REQUIRED] Test case

I'm using `firebase crashlytics:symbols:upload --app=${FIREBASE_APP_ID} "./Symbols/"` with the following structure of the `Symbols` folder:
- Symbols
  - arm64-v8a
    -  libgame.so

I tried it with the standalone version as well as the NodeJS version, as well as uploading a `Symbols.zip` file with the same structure instead, but all of this produces the same error.

### [REQUIRED] Steps to reproduce

Use the command above in any docker container with Firebase CLI tools installed.

### [REQUIRED] Expected behavior

Successful upload of debug symbols.

### [REQUIRED] Actual behavior

I'm only getting "An unknown error occurred":
```
i  Downloading crashlytics-buildtools.jar to /home/tools/.cache/firebase/crashlytics/buildtools/crashlytics-buildtools-3.0.2.jar
i  For open source licenses used by this command, look in the META-INF directory in the buildtools.jar file
i  Generating symbols for ./Symbols/
⚠  An unknown error occurred
Error: java command failed with args: -jar,/home/tools/.cache/firebase/crashlytics/buildtools/crashlytics-buildtools-3.0.2.jar,-symbolGenerator,breakpad,-symbolFileCacheDir,/tmp/crashlytics-a8a12fe7-a767-4e6c-9852-27791cee8731/nativeSymbols/1-890123185040-android-123b6aba872a3ddaea2115/breakpad,-verbose,-generateNativeSymbols,-unstrippedLibrary,./Symbols/,-clientName,firebase-cli;crashlytics-buildtools
```

**Comment by Zaratusa** [comment]
It was a missing Java dependency, despite the documentation states: `The standalone binary distribution of the Firebase CLI allows you to download a firebase executable without any dependencies.`

**Comment by estellise-yukihime** [comment]
@Zaratusa how were you able to resolve this? I am experiencing this issue as well.

**Comment by estellise-yukihime** [comment]
Just resolve this as well. I'm not too familiar with how this cli is implemented, but why the hell crashlytics:upload:symbols step implemented in Java? its weird that I have to install java, just to run the crashlytics upload symbol.
