### ISSUE TITLE
Upload mapping via Firebase CLI

### ISSUE THREAD

**Issue by Lzk85** [firebase/firebase-tools#7927]
Hi all,
I have CLI with version 11.0.1.
In [docs](https://firebase.google.com/docs/cli#crashlytics-commands) i see that it possible to upload my app's mapping  via CLI, but when i tried to do it i got message

_Error: crashlytics:mappingfile:upload is not a Firebase command
Did you mean crashlytics:symbols:upload?_

Is it not actual official docs? Or where is my mistake ?

**Comment by pidanxiangjiao** [comment]
> Hey @Lzk85, the `crashlytics:mappingfile:upload` command was added in firebase-tools [v11.7.0](https://github.com/firebase/firebase-tools/releases/tag/v11.7.0). Updating to firebase-tools >= v11.7.0 should resolve this issue.

hello, when i upload my app's mapping via CLI, how to associate certain mapping file to specific apk/aab?

**Comment by Lzk85** [comment]
> hello, when i upload my app's mapping via CLI, how to associate certain mapping file to specific apk/aab?

You need this [xml](https://github.com/firebase/firebase-android-sdk/issues/2004?ysclid=m3juqljtx0942349411#issuecomment-891704610) file after build. It generates different to each build.And then put it as parameter _resource-file_
