### ISSUE TITLE
Fix vulnerable package path-to-regex of superstatic

### ISSUE THREAD

**Issue by IchordeDionysos** [firebase/firebase-tools#7929]
**firebase-tools:** 13.24.2

**Platform:** any

Update the path-to-regex vulnerability in superstatic to resolve a vulnerability added to firebase-tools.

https://github.com/firebase/superstatic/pull/482

This would help reduce the number of vulnerabilities of downstream consumers and focus on actual / important reports.

**Comment by bkendall** [comment]
Thanks for the report. It should be addressed with this PR: https://github.com/firebase/superstatic/pull/484
