### ISSUE TITLE
Unable to firebase login - Error: Timed out.

### ISSUE THREAD

**Issue by scharalambous3** [firebase/firebase-tools#7947]
### [REQUIRED] Environment info

**firebase-tools:**  13.24.1

**Platform:** linux

### [REQUIRED] Test case
firebase login

### [REQUIRED] Steps to reproduce

firebase login

### [REQUIRED] Expected behavior

No errors
### [REQUIRED] Actual behavior

> [debug] [2024-11-13] CLI Version:   13.24.1
[debug] [2024-11-13] Platform:      linux
[debug] [2024-11-13] Node Version:  v18.5.0

`[info] Already logged in as ****@gmail.com
[debug] [2024-11-13T22:21:52.848Z] Error: Timed out.
    at Timeout._onTimeout (.cache/firebase/tools/lib/node_modules/firebase-tools/lib/utils.js:268:49)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)`

**Comment by aalej** [comment]
Hey @scharalambous3. Looking at the error message, I think there might be a network request that is failing to get a response or a process that does not complete. Any chance you could try `firebase login --debug` and share the `firebase-debug.log` with us? 

It may be worth trying to connect to a different network or temporarily turn off any proxy, firewall, or VPN that you may have to discard the possibility that this is a network related issue.

**Comment by scharalambous3** [comment]
![image](https://github.com/user-attachments/assets/5ba2b113-1fea-41f5-98d1-09bd419a82b0)

`⚠  Unable to fetch the CLI MOTD and remote config. This is not a fatal error, but may indicate an issue with your network connection.
`
I tried firebase logout and then firebase login again but it gets stuck at the page "Firebase CLI wants to access your google account"

![image](https://github.com/user-attachments/assets/0fb145c9-7e7b-4855-92fd-a52d853b83f6)


Outputs of firebase-debug.log


> [debug] 
[debug] [2024-11-14T18:36:28.860Z] >>> [apiv2][query] GET https://firebase-public.firebaseio.com/cli.json [none]
[debug] [2024-11-14T18:36:28.955Z] Object "" in "firebase.json" has unknown property: {"additionalProperty":"flutter"}
[info] i  Firebase optionally collects CLI and Emulator Suite usage and error reporting information to help improve our products. Data is collected in accordance with Google's privacy policy (https://policies.google.com/privacy) and is not used to identify you.
[info] 
[info] Visit this URL on this device to log in:
[info] ******
[info] Waiting for authentication...
[debug] [2024-11-14T18:36:36.335Z] >>> [apiv2][query] POST https://accounts.google.com/o/oauth2/token [none]
[debug] [2024-11-14T18:36:36.336Z] >>> [apiv2][body] POST https://accounts.google.com/o/oauth2/token [omitted]
[debug] [2024-11-14T18:38:42.527Z] *** [apiv2] error from fetch(https://firebase-public.firebaseio.com/cli.json, {"headers":{},"method":"GET"}): FetchError: request to https://firebase-public.firebaseio.com/cli.json failed, reason: connect ETIMEDOUT 2600:1901:0:4d00:::443
[warn] ⚠  Unable to fetch the CLI MOTD and remote config. This is not a fatal error, but may indicate an issue with your network connection. 
[debug] [2024-11-14T18:38:42.530Z] Failed to fetch MOTD FirebaseError: Failed to make request to https://firebase-public.firebaseio.com/cli.json
[debug] [2024-11-14T18:38:50.714Z] *** [apiv2] error from fetch(https://accounts.google.com/o/oauth2/token, {"headers":{},"method":"POST","body":{"_overheadLength":543,"_valueLength":208,"_valuesToMeasure":[],"writable":false,"readable":true,"dataSize":0,"maxDataSize":2097152,"pauseStreams":true,"_released":true,"_streams":[],"_currentStream":null,"_insideLoop":false,"_pendingNext":false,"_boundary":"--------------------------592130015441722208350598","_events":{},"_eventsCount":1}}): FetchError: request to https://accounts.google.com/o/oauth2/token failed, reason: connect ETIMEDOUT 2a00:1450:4013:c03::54:443
[debug] [2024-11-14T18:38:50.715Z] Token Fetch Error: FirebaseError: Failed to make request to https://accounts.google.com/o/oauth2/token
    at RetryOperation._fn (/home/scharalambous3/.cache/firebase/tools/lib/node_modules/firebase-tools/lib/apiv2.js:261:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by aalej** [comment]
Thanks for sharing your debug logs. It does look like a network related issue. Usually, we see this occur when there is a Firewall blocking node from making requests or a proxy misconfiguration. Unfortunately, this seems to be caused by something specific to your setup.  

Try logging in using `firebase login --no-localhost`. If you continue to have issues logging in, try reaching out to our [Firebase Support team](https://firebase.google.com/support/troubleshooter/access).

**Comment by scharalambous3** [comment]
I already tried the --no-localhost without success
