### ISSUE TITLE
function deploy Quota Exceeded error not considered error

### ISSUE THREAD

**Issue by ottob** [firebase/firebase-tools#7949]
### [REQUIRED] Environment info

**firebase-tools:** 13.25.0

 

**Platform:** Ubuntu (GitHub action)

### [REQUIRED] Test case

n/a. we have 100 functions in this deploy.

### [REQUIRED] Steps to reproduce

deploy functions (and hosting)

### [REQUIRED] Expected behavior

the deploy should exit with an error code

### [REQUIRED] Actual behavior

⚠  functions: got "Quota Exceeded" error while trying to update projects/ourproject-dev/locations/europe-west3/functions/staticIpGateway. Waiting to retry...

the deployment looks successful (green in CI, I assume exit code was 0), but the affected function was not deployed. **And** the deploy did not continue with the hosting deploy.

**Comment by colerogers** [comment]
Hi @ottob I'm not able to reproduce this on my end. Are you sure the exit code was 0 for the function deployment? Since you mention that the Hosting deploy did not start, I'm inclined to believe that it was non-zero output from the functions and WAI.

**Comment by vpusher** [comment]
We are also experiencing this Quota Exceeded error and it be becomes to be very problematic.

I differentiate 2 issues on that topic:
- Deploying a large code base (~180+ functions), often hits (if not always) the `Per project mutation requests per minute per region` limit. This quota limit is by default set to 60 and cannot be changed.
- Whenever the a Quota Exceeded error is met it is not considered in the exit code. Basically our pipeline always succeed whereas there was 10 CF not deployed cause of this error.

Error example:
```
⚠  functions: Request to https://cloudfunctions.googleapis.com/v2/projects/my-project-id/locations/europe-west6/functions/myCallable?updateMask=name%2CbuildConfig.runtime%2CbuildConfig.entryPoint%2CbuildConfig.source.storageSource.bucket%2CbuildConfig.source.storageSource.object%2CbuildConfig.environmentVariables%2CbuildConfig.sourceToken%2CserviceConfig.environmentVariables%2CserviceConfig.secretEnvironmentVariables%2CserviceConfig.ingressSettings%2CserviceConfig.timeoutSeconds%2CserviceConfig.serviceAccountEmail%2CserviceConfig.availableMemory%2CserviceConfig.minInstanceCount%2CserviceConfig.maxInstanceCount%2CserviceConfig.maxInstanceRequestConcurrency%2CserviceConfig.availableCpu%2Clabels%2CbuildConfig.buildEnvironmentVariables had HTTP Error: 429, Quota exceeded for quota metric 'Per project mutation requests' and limit 'Per project mutation requests per minute per region' of service 'cloudfunctions.googleapis.com' for consumer 'project_number:123456789'.
⚠  functions: Got "Quota Exceeded" error while trying to update projects/my-project-id/locations/europe-west6/functions/myCallable. Waiting to retry...
⚠  functions:  failed to update function projects/my-project-id/locations/europe-west6/functions/myCallable
```

<img width="560" alt="Screenshot 2024-11-30 at 10 06 08" src="https://github.com/user-attachments/assets/4c3df52e-79d8-464a-bd82-4a15569facb9">

firebase-tools: 13.27.0
NodeJS: 20.12

**Comment by vpusher** [comment]
We are still experiencing that issue 😔. We would love to see the correct exit code being returned whenever a 409 is met.

**Comment by abalikai** [comment]
We are also seeing quota errors all of a sudden for a few weeks now, even when we are trying to deploy just one function. It will work the first time, but then we'll get quota errors immediately after. If we wait about 10-15 minutes, we can deploy the single function again. We haven't made any changes to our deployment workflow and we get the same error in dev and production environments, which has gotten very frustrating. The exact error we receive is: 

"Request to https://firestore.googleapis.com/v1/projects/<project_name>/databases/(default) had HTTP Error: 429, Quota exceeded for quota metric 'Database operation requests' and limit 'Database Operations Per Minute' of service 'firestore.googleapis.com' for consumer 'project_number:<project_number>'.
There was an error retrieving the Firestore database. Currently, the database id is set to (default), make sure it exists."

Looking at the quota graph in the GCP console we can see the spike in database operation requests, and it's only when we initiate the function deployment.

**Comment by trullock** [comment]
I dont think anyone would argue with APIs having rate limits, but not being able to deploy simple functions makes Firebase useless.

Worse, its forcing us to review if we continue to use it, and certainly putting us off it for new projects.

Come on guys.

**Comment by abalikai** [comment]
We currently have 156 Firebase functions. They're very useful for small tasks when needed. Through some trial and error we may have found a solution for us. Commenting out the Firestore triggered functions in "index.js" lets us deploy functions without exceeding the "Database Operations Per Minute" quota.

**Comment by gbourne1** [comment]
This issue should be addressed - deployments always have issues since we have 150 functions.

**Comment by wooliet** [comment]
Manually deploying only one firebase function at a time (no CI etc.) and getting 429 quota errors.

firebase-tools@14.3.1

**Comment by abalikai** [comment]
The solution I had was to comment out the Firestore triggered functions in index.js. It definitely seems better, but we're seeing 429 quota errors again. We have started transitioning all of our non Firestore triggered functions elsewhere. We can't have this type of deployment inconsistencies when we consider how rapidly we try to iterate.

**Comment by fj-vp** [comment]
Same issue here. First time after a while, deployment of a `single` function is successful. Afterwards, the deployment is failing for hours. Sometimes with the error:
```
Error: Request to https://firestore.googleapis.com/v1/projects/project-name/databases/(default) had HTTP Error
: 429, Quota exceeded for quota metric 'Database operation requests' and limit 'Database Operations Per Minute' of
 service 'firestore.googleapis.com' for consumer 'project_number:123'.
There was an error retrieving the Firestore database. Currently, the database id is set to (default), make sure it
 exists.
```
Nothing has changed from our deployment pipeline, only the firebase-tools, currently `v14.2.2`, so we can support Gen 2 functions. 

Trying from command line or CI, same error everywhere.

The only fix is just to wait, ca. 30-45min, which is ridiculous.

**Comment by wooliet** [comment]
@colerogers is there any chance of getting this issue reopened?

**Comment by fj-vp** [comment]
**For anyone coming here facing the issue**: it looks like that with the latest version of `firebase-tools`, 14.6.0, the issue is gone. 🥳 


I have tried to identify what's going on with previous versions and debugging the cli output when deploying a single function, I see that a specific API call:
```
[2025-06-11T09:43:12.280Z] >>> [apiv2][query] GET https://firestore.googleapis.com/v1/projects/${myproject}/databases/(default) [none]
[2025-06-11T09:43:12.282Z] >>> [apiv2][query] GET https://firestore.googleapis.com/v1/projects/${myproject}/databases/(default) [none]
[2025-06-11T09:43:12.283Z] >>> [apiv2][query] GET https://firestore.googleapis.com/v1/projects/${myproject}/databases/(default) [none]
[2025-06-11T09:43:12.284Z] >>> [apiv2][query] GET https://firestore.googleapis.com/v1/projects/${myproject}/databases/(default) [none]
[2025-06-11T09:43:12.285Z] >>> [apiv2][query] GET https://firestore.googleapis.com/v1/projects/${myproject}/databases/(default) [none]
[2025-06-11T09:43:12.285Z] >>> [apiv2][query] GET https://firestore.googleapis.com/v1/projects/${myproject}/databases/(default) [none]
[2025-06-11T09:43:12.286Z] >>> [apiv2][query] GET https://firestore.googleapis.com/v1/projects/${myproject}/databases/(default) [none]
...
(~60 more)
```
is flooding the endpoint, without waiting for response.
In the end, I've got the expected error for exceeding the rate limit:
```
[2025-06-11T09:43:13.193Z] <<< [apiv2][status] GET https://firestore.googleapis.com/v1/projects/${myproject}/databases/(default) 429
[2025-06-11T09:43:13.193Z] <<< [apiv2][body] GET https://firestore.googleapis.com/v1/projects/${myproject}/databases/(default) {"error":{"code":429,"message":"Quota exceeded for quota metric 'Database operation requests' and limit 'Database Operations Per Minute' of service 'firestore.googleapis.com' for consumer 'project_number:1087780358470'.","status":"RESOURCE_EXHAUSTED","details":[{"@type":"type.googleapis.com/google.rpc.ErrorInfo","reason":"RATE_LIMIT_EXCEEDED","domain":"googleapis.com","metadata":{"service":"firestore.googleapis.com","quota_limit":"DatabaseOperationsPerMinutePerProject","quota_limit_value":"60","consumer":"projects/1087780358470","quota_unit":"1/min/{project}","quota_location":"global","quota_metric":"firestore.googleapis.com/database_operation_requests"}},{"@type":"type.googleapis.com/google.rpc.Help","links":[{"description":"Request a higher quota limit.","url":"https://cloud.google.com/docs/quotas/help/request_increase"}]}]}}
There was an error retrieving the Firestore database. Currently, the database id is set to (default), make sure it exists.
```

**Comment by huix9527** [comment]
> **For anyone coming here facing the issue**: it looks like that with the latest version of `firebase-tools`, 14.6.0, the issue is gone. 🥳
> 
> I have tried to identify what's going on with previous versions and debugging the cli output when deploying a single function, I see that a specific API call:
> 
> ```
> [2025-06-11T09:43:12.280Z] >>> [apiv2][query] GET https://firestore.googleapis.com/v1/projects/${myproject}/databases/(default) [none]
> [2025-06-11T09:43:12.282Z] >>> [apiv2][query] GET https://firestore.googleapis.com/v1/projects/${myproject}/databases/(default) [none]
> [2025-06-11T09:43:12.283Z] >>> [apiv2][query] GET https://firestore.googleapis.com/v1/projects/${myproject}/databases/(default) [none]
> [2025-06-11T09:43:12.284Z] >>> [apiv2][query] GET https://firestore.googleapis.com/v1/projects/${myproject}/databases/(default) [none]
> [2025-06-11T09:43:12.285Z] >>> [apiv2][query] GET https://firestore.googleapis.com/v1/projects/${myproject}/databases/(default) [none]
> [2025-06-11T09:43:12.285Z] >>> [apiv2][query] GET https://firestore.googleapis.com/v1/projects/${myproject}/databases/(default) [none]
> [2025-06-11T09:43:12.286Z] >>> [apiv2][query] GET https://firestore.googleapis.com/v1/projects/${myproject}/databases/(default) [none]
> ...
> (~60 more)
> ```
> 
> is flooding the endpoint, without waiting for response. In the end, I've got the expected error for exceeding the rate limit:
> 
> ```
> [2025-06-11T09:43:13.193Z] <<< [apiv2][status] GET https://firestore.googleapis.com/v1/projects/${myproject}/databases/(default) 429
> [2025-06-11T09:43:13.193Z] <<< [apiv2][body] GET https://firestore.googleapis.com/v1/projects/${myproject}/databases/(default) {"error":{"code":429,"message":"Quota exceeded for quota metric 'Database operation requests' and limit 'Database Operations Per Minute' of service 'firestore.googleapis.com' for consumer 'project_number:1087780358470'.","status":"RESOURCE_EXHAUSTED","details":[{"@type":"type.googleapis.com/google.rpc.ErrorInfo","reason":"RATE_LIMIT_EXCEEDED","domain":"googleapis.com","metadata":{"service":"firestore.googleapis.com","quota_limit":"DatabaseOperationsPerMinutePerProject","quota_limit_value":"60","consumer":"projects/1087780358470","quota_unit":"1/min/{project}","quota_location":"global","quota_metric":"firestore.googleapis.com/database_operation_requests"}},{"@type":"type.googleapis.com/google.rpc.Help","links":[{"description":"Request a higher quota limit.","url":"https://cloud.google.com/docs/quotas/help/request_increase"}]}]}}
> There was an error retrieving the Firestore database. Currently, the database id is set to (default), make sure it exists.
> ```

14.14.0, still the same, it really annoying.

**Comment by huix9527** [comment]
14.18.0, still not fixed!

It's hard to believe that such a serious problem could persist for so long without receiving the attention it deserves. A fundamental question: Who would use a cloud platform that can't be deployed?

**Comment by chinloyal** [comment]
14.19.1 I'm still experiencing this issue:

For more troubleshooting guidance, see https://cloud.google.com/run/docs/troubleshooting#container-failed-to-start
Could not create or update Cloud Run service feature-functionname, Container Healthcheck failed. Revision 'feature-functionname-00004-muc' is not ready and cannot serve traffic. Quota exceeded for total allowable CPU per project per region.

**Comment by kdawgwilk** [comment]
Everyone that has commented please upvote the issue description with a 👍 reaction to hopefully bring more attention to this issue.  

Has anyone had luck working with GCP support to get an increase on this quota to alleviate these issues? `Per project mutation requests per minute per region`

Also this issue should be re-opened given how often its still happening and being reported

**Comment by trullock** [comment]
I've merged all of my functions into a single function, and I pass the fn name as a parameter. 

This way I only need to deploy 1 function, and I get better performance wrt cold starts.

Its a bit more complicated than this, with permissions and domain segregation etc but you get the gist.

I don't have this issue any more, and have brought myself many other benefits.

Doesn't excust this farce, but at least works around it
