### ISSUE TITLE
Automated tests (--test-devices) "The caller does not have permission error"

### ISSUE THREAD

**Issue by whitipet** [firebase/firebase-tools#7950]
### Environment info

**firebase-tools:** 13.25.0

**Platform:** Ubuntu 22.04.5

### Test case

I'm trying to run [automated tests](https://firebase.google.com/docs/app-distribution/android-automated-tester) via `--test-devices` in GitHub Actions. Authorization was done with the GOOGLE_APPLICATION_CREDENTIALS environment variable. Account with the role “Firebase App Distribution Admin SDK Service Agent”. The build successfully gets into App Distribution, but I get an error on adding [automated tests](https://firebase.google.com/docs/app-distribution/android-automated-tester). If I remove `--test-devices`, everything works.

```
- name: Run firebase appdistribution:distribute
  shell: bash
  run: |
    $(which firebase) appdistribution:distribute \
    --app app_id \
    --groups "groups" \
    --test-devices "model=shiba,version=35,locale=en,orientation=portrait;model=b0q,version=35,locale=en,orientation=portrait" --test-non-blocking \
    app_name.aab
```

### Steps to reproduce

Run appdistribution:distribute with `--test-devices`

### Expected behavior

[Automated tests](https://firebase.google.com/docs/app-distribution/android-automated-tester) will run and there will be no error

### Actual behavior

When adding `--test-devices`, an error occurs after the build has been successfully uploaded `Error: Request to https://firebaseappdistribution.googleapis.com/v1alpha/projects/*/apps/***/releases/*/tests had HTTP Error: 403, The caller does not have permission`

**Comment by aalej** [comment]
Hey @whitipet, thanks for the detailed report. It looks like the error here is related to the permissions granted. Looking through our [docs](https://firebase.google.com/docs/app-distribution/troubleshooting?platform=android#automated-tester-permissions), it seems like the Editor permission is needed to run the Automated Tester beta feature. I tried this locally and I was able to run the command without any issues after granting the "Editor" role.
