### ISSUE TITLE
can't deploy 

### ISSUE THREAD

**Issue by githubkyo** [firebase/firebase-tools#7957]
Could not determine the web framework in use.

Error: Unable to detect the web framework in use, check firebase-debug.log for more info.

Documentation: https://firebase.google.com/docs/hosting/frameworks/frameworks-overview
File a bug: https://github.com/firebase/firebase-tools/issues/new?template=bug_report.md
Submit a feature request: https://github.com/firebase/firebase-tools/issues/new?template=feature_request.md

We'd love to learn from you. Express your interest in helping us shape the future of Firebase Hosting: https://goo.gle/41enW5X

Having trouble? Try firebase [command] --help

### [REQUIRED] Environment info

**firebase-tools:**

**Platform:**

**Comment by aalej** [comment]
Hey @githubkyo. To conduct a thorough investigation and accurately reproduce the issue, we will need additional information. Could you please create a new report and provide the details using the specified template. Include information such as:

1. Steps you took to set up your project
2. Version of firebase-tools you're using
3. Platform you're using(Windows, macOS, Linux, etc.)
4. Contents of your `firebase-debug.log` file

These info will help us understand why the Firebase CLI wasn't able to detect the web framework you're using.
