### ISSUE TITLE
Could not create or update Cloud Run service 

### ISSUE THREAD

**Issue by chenei** [firebase/firebase-tools#7993]
### [REQUIRED] Environment info

**firebase-tools:** 13.27.0

**Platform:** macOS

### [REQUIRED] Test case

Running `deploy` script results with:
```
i  functions: creating Node.js 20 (2nd Gen) function helloworldworld(us-central1)...
Could not create or update Cloud Run service helloworldworld, Container Healthcheck failed. Revision 'helloworldworld-00001-yub' is not ready and cannot serve traffic. The user-provided container failed to start and listen on the port defined provided by the PORT=8080 environment variable within the allocated timeout. This can happen when the container port is misconfigured or if the timeout is too short. The health check timeout can be extended. Logs for this revision might contain more information.

```

### [REQUIRED] Steps to reproduce

**Here is my cloud function snippet:**
```
import {onRequest} from "firebase-functions/v2/https";

exports.helloworldworld = onRequest({cors: true}, (req: any, res: any) => {
  res.send("Hello, World!");
});

```

I am running with `Node 20.18.0` (also tried `20.11.0`).

package.json:
```
"dependencies": {
    "firebase-admin": "13.0.1",
    "firebase-functions": "6.1.1"
  },
```
I tried any possible solution I have found online, I made sure my function is fully gen2 compiled but nothing works.

### [REQUIRED] Expected behavior

Work

### [REQUIRED] Actual behavior

Doesn't work

**Comment by aalej** [comment]
Hey @chenei, thanks for reaching out and providing a detailed report. The error usually indicates that the code you're trying to deploy is crashing on load. At the moment, it's a bit difficult to determine what caused the crash.

I'm currently working on reproducing this, but so far I’m able to deploy functions. I created this [repo](https://github.com/aalej/issues-7993) using the information you provided, could you let me know if I may be missing anything here? By any chance, could you provide an [mcve](https://stackoverflow.com/help/minimal-reproducible-example) to help us reproduce the error?

Also, the logs after `Could not create or update Cloud Run service...` should contain a link that redirects to Logs Explorer, which should show additional information on what could've caused the error.

**Comment by chenei** [comment]
@aalej thanks for the response!

I compare your repo with mine, the only difference was the TS version, I used 5.

The build process is green while the deployment failed with:
`Detailed stack trace: Error: Cannot find module 'firebase-functions/v2/https`

<img width="1465" alt="Screenshot 2024-11-26 at 16 16 53" src="https://github.com/user-attachments/assets/221a68b6-4cbf-4e4f-b406-c9cd129fdc4a">
<img width="1153" alt="Screenshot 2024-11-26 at 16 17 34" src="https://github.com/user-attachments/assets/192ac541-515b-409f-933b-8d287d97077a">

**Comment by chenei** [comment]
[mcve](https://github.com/eilatc/firebase-issue/tree/main/src/firebase)

**Comment by aalej** [comment]
Thanks for the added info. I tried running `npm i` on the mcve you shared, but it kept getting stuck installing. I had to first delete `package-lock.json` and `node_modules` then run `npm i`. Also, looking at the logs, it seems like the issue is a missing dependency.

Given the above, I think the issue here might be with your `package-lock.json` file. Could you try to:

1. Delete `package-lock.json` and `node_modules` in the functions directory
2. Run `npm i`
3. Run `firebase deploy`

Are you still encountering an error after doing so?

**Comment by chenei** [comment]
@aalej I did that above multiple times without any luck.
I just created a new project on firebase with a new repo locally with `firebase init`. I tried to use `Node 18` and again I am getting an error.
I understand it's something with my environment but I really don't understand what is the issue. 

<img width="1466" alt="Screenshot 2024-11-26 at 20 31 10" src="https://github.com/user-attachments/assets/c8e3ae2d-2a2e-4412-a83a-0a06142ea0ac">

**Comment by joehan** [comment]
Hey @chenei, we noticed in you MCVE that your package-lock.json is resolving packages to https://npm.dev.wixpress.com. 
My best guess is that this registry is not accessible from Cloud Build. Could you try using the default registry?
- Run `npm config set registry https://registry.npmjs.org/`
- Delete package-lock.json
- `npm i`
Then, redploy and hopefully it should work.

**Comment by chenei** [comment]
@joehan you right, that could be the issue. thanks for that.
Where did you find it in the logs? couldn't find any reference for that.

**Comment by joehan** [comment]
RE improving the logs - I was thinking the same thing. Gonna add a check for this case + better error message.
