### ISSUE TITLE
Data Connect Emulator fails to start with Unknown system error -86

### ISSUE THREAD

**Issue by HassanBahati** [firebase/firebase-tools#7995]
### [REQUIRED] Environment info

**firebase-tools:** 13.27.0

**Platform:** MacOs on Macbook Pro M3

### [REQUIRED] Steps to reproduce
1. Initialize data connect app with Data Connect VsCode
2. Use Data connect VsCode extension to start emulators

### [REQUIRED] Expected behavior
expected emulators to start successfully

### [REQUIRED] Actual behavior
emulators fail to start with the errors below
<img width="1068" alt="image" src="https://github.com/user-attachments/assets/6f368f41-b7ae-445b-ba77-80fdd31e8a32">

**Comment by joehan** [comment]
Hey @HassanBahati - could you share the contents of firebase-debug.log and dataconnect-debug.log (or rerun the command with --debug and share that)? That will help us debug this issue further

**Comment by joehan** [comment]
Hmmm, after digging into this a bit more I think this may be a executable incompatibility issue with the M3 chips. I'm surprised that you're hitting this though, because I've been able to run the emulator on M1 with no issues, which also is on ARM arch.

One thing you could try is to install Rosetta, and then try again:
```
softwareupdate --install-rosetta
```

**Comment by sushrutshelf** [comment]
Hi I had the same issue on M1 seems it was an issue with permissions on Mac. 
` Error: EACCES: permission denied, copyfile '/var/folders/kj/p_l_xw1s54ncm695ymrzcmp40000gn/T/tmp-43382-M0vWPaG3Vb4h' -> '/Users/sushrut/.cache/firebase/emulators/dataconnect-emulator-1.8.2'`

Solved it by adding sudo command in front of the terminal command
`sudo npx -y firebase-tools@latest emulators:start --project tqf-dataconnect `
