### ISSUE TITLE
firebase-tools appdistribution:distribute command is failing

### ISSUE THREAD

**Issue by lakpa** [firebase/firebase-tools#8003]
###  Environment info

Using Node

firebase-tools: 13.27.0

Platform: macOS

### Test case

N/A

### Steps to reproduce

  npx -y firebase-tools appdistribution:distribute ${Build Directory} --debug --app ${App location} --groups 'QAs' --release-notes 'Test'

### Expected behavior

Should distribute to testers/groups successfully

### Actual behavior

node:internal/modules/cjs/loader:1228
  throw err;
  ^

Error: Cannot find module 'js-yaml'
Require stack:
- /Users/administrator/.npm/_npx/7750544ccf494d8b/node_modules/firebase-tools/lib/apphosting/yaml.js
- /Users/administrator/.npm/_npx/7750544ccf494d8b/node_modules/firebase-tools/lib/apphosting/config.js
- /Users/administrator/.npm/_npx/7750544ccf494d8b/node_modules/firebase-tools/lib/emulator/apphosting/config.js
- /Users/administrator/.npm/_npx/7750544ccf494d8b/node_modules/firebase-tools/lib/emulator/apphosting/serve.js
- /Users/administrator/.npm/_npx/7750544ccf494d8b/node_modules/firebase-tools/lib/emulator/apphosting/index.js
- /Users/administrator/.npm/_npx/7750544ccf494d8b/node_modules/firebase-tools/lib/emulator/controller.js
- /Users/administrator/.npm/_npx/7750544ccf494d8b/node_modules/firebase-tools/lib/emulator/commandUtils.js
- /Users/administrator/.npm/_npx/7750544ccf494d8b/node_modules/firebase-tools/lib/commands/database-get.js
- /Users/administrator/.npm/_npx/7750544ccf494d8b/node_modules/firebase-tools/lib/commands/index.js
- /Users/administrator/.npm/_npx/7750544ccf494d8b/node_modules/firebase-tools/lib/index.js
- /Users/administrator/.npm/_npx/7750544ccf494d8b/node_modules/firebase-tools/lib/bin/firebase.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Module._load (node:internal/modules/cjs/loader:1051:27)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/Users/administrator/.npm/_npx/7750544ccf494d8b/node_modules/firebase-tools/lib/apphosting/yaml.js:8:16)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/administrator/.npm/_npx/7750544ccf494d8b/node_modules/firebase-tools/lib/apphosting/yaml.js',
    '/Users/administrator/.npm/_npx/7750544ccf494d8b/node_modules/firebase-tools/lib/apphosting/config.js',
    '/Users/administrator/.npm/_npx/7750544ccf494d8b/node_modules/firebase-tools/lib/emulator/apphosting/config.js',
    '/Users/administrator/.npm/_npx/7750544ccf494d8b/node_modules/firebase-tools/lib/emulator/apphosting/serve.js',
    '/Users/administrator/.npm/_npx/7750544ccf494d8b/node_modules/firebase-tools/lib/emulator/apphosting/index.js',
    '/Users/administrator/.npm/_npx/7750544ccf494d8b/node_modules/firebase-tools/lib/emulator/controller.js',
    '/Users/administrator/.npm/_npx/7750544ccf494d8b/node_modules/firebase-tools/lib/emulator/commandUtils.js',
    '/Users/administrator/.npm/_npx/7750544ccf494d8b/node_modules/firebase-tools/lib/commands/database-get.js',
    '/Users/administrator/.npm/_npx/7750544ccf494d8b/node_modules/firebase-tools/lib/commands/index.js',
    '/Users/administrator/.npm/_npx/7750544ccf494d8b/node_modules/firebase-tools/lib/index.js',
    '/Users/administrator/.npm/_npx/7750544ccf494d8b/node_modules/firebase-tools/lib/bin/firebase.js'
  ]
}

Node.js v20.18.1
Error: Process completed with exit code 1.

**Comment by lakpa** [comment]
I can see that js-yaml is being imported in the project. However, it is not listed as a dependency in the package.json file.

 I am wondering if I could contribute fixing it.

**Comment by aalej** [comment]
Thanks for reporting this @lakpa. At the moment I can't seem to reproduce this, running `npx -y firebase-tools appdistribution:distribute ...` locally works. Just based on the error message, it looks like there is a missing dependency. I'm not very familiar with that part of our codebase, so I'll ask someone from our team to take a closer look.

If you have a fix in mind that you think will resolve this, feel free to open up a PR. Contributions are always welcome!

**Comment by lakpa** [comment]
Thanks for fixing the bug
