### ISSUE TITLE
1st gen function deploy using pnpm fails

### ISSUE THREAD

**Issue by dsl101** [firebase/firebase-tools#8004]
### [REQUIRED] Environment info

**firebase-tools:** 13.27.0

**Platform:** Windows 10

### [REQUIRED] Test case

```js
const functions = require('firebase-functions')
// New user created
exports = module.exports = functions.auth.user().onCreate(fsAuthUser => {
  // etc.
}
```

### [REQUIRED] Steps to reproduce

1. Create a single firebase 1st gen function for an authentication trigger
2. Deploy with `firebase deploy`
3. Observe error

### [REQUIRED] Expected behavior

Function would deploy

### [REQUIRED] Actual behavior
```
i  functions: updating Node.js 20 (1st Gen) function authUserOnCreate(us-central1)...
Build failed: installing pnpm: (error ID: e462f501):
downloading pnpm: (error ID: 44d6210b):
fetching https://github.com/pnpm/pnpm/releases/download/v9.14.3/pnpm-linux-x64 returned HTTP status: 404; Error ID: d34422e2
```

It appears there is no release associated with version 9.14.3 of pnpm ([see here](https://github.com/pnpm/pnpm/releases/)). The most recent v9 is 9.14.2.

**Comment by dominics** [comment]
I think this bug actually belongs to https://github.com/GoogleCloudPlatform/buildpacks - we should probably open an issue there?

Specifically this: https://github.com/GoogleCloudPlatform/buildpacks/blob/e14e947a21065e234d006909898263c125bd2718/pkg/nodejs/pnpm.go#L62

The problem seems to be that it reads the latest version from NPM (which is 9.14.3), then assumes that version will also be available as a Github release

**Comment by dsl101** [comment]
Thanks for the connection—I will watch that other issue.

**Comment by dsl101** [comment]
Also, just tried adding this to the `package.json` inside the `/functions` directory of my firebase project, and all deployed OK:
```json
  "engines": {
    "node": "20",
    "pnpm": "9.14.2"
  },
```

**Comment by sailxjx** [comment]
> Also, just tried adding this to the `package.json` inside the `/functions` directory of my firebase project, and all deployed OK:
> 
> ```json
>   "engines": {
>     "node": "20",
>     "pnpm": "9.14.2"
>   },
> ```

I've tried to add this to my firebase.json, but still download 9.14.3, which is not existing.

**Comment by sailxjx** [comment]
> > Also, just tried adding this to the `package.json` inside the `/functions` directory of my firebase project, and all deployed OK:
> > ```json
> >   "engines": {
> >     "node": "20",
> >     "pnpm": "9.14.2"
> >   },
> > ```
> 
> I've tried to add this to my firebase.json, but still download 9.14.3, which is not existing.

Should add in the package.json in the funcions directory, I've added in the wrong place.

**Comment by dsl101** [comment]
Yes, deploy (without the explicit pnpm version in package.json) appears to work for me again.
