### ISSUE TITLE
Can not deploy selected namespaced function

### ISSUE THREAD

**Issue by pavel** [firebase/firebase-tools#803]
### Version info

> 3.18.6

### Platform Information

> Linux x86_64

### Steps to reproduce

1. Create a function file.

`index.js`

```
const F = require("firebase-functions");
const A = require("firebase-admin");

A.initializeApp();

exports.en = {};
exports.en.hello = (data, context) => {
  return "Hello!";
};

exports.fr = {};
exports.fr.hello = (data, context) => {
  return "Bonjour!";
};
```

2. Deploy all functions with:

`firebase deploy --only functions`

3. Change one of the functions (e.g. "fr.hello")

4. Try and deploy only the changed function:

`firebase deploy --only functions:fr-hello`

### Expected behavior

Filter finds namespaced function and deploys it.

### Actual behavior

Filter **does not find** namespaced function and **does not deploy** it.

The output produced during step 4 is:

> functions: current functions in project: en-hello, fr-hello
> functions: the following filters were specified but do not match any functions in the project: fr-hello

**Comment by laurenzlong** [comment]
I believe this is an issue with error messaging, this should work:

firebase deploy --only functions:fr.hello

**Comment by c13n-io** [comment]
Is this documented?
