### ISSUE TITLE
Merge .firebaserc and/or firebase.json with package.json

### ISSUE THREAD

**Issue by RinMinase** [firebase/firebase-tools#804]
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10 v1803
  * Firebase SDK version: 5.0.4
  * Firebase Product: firebaserc, firebase.json

### [REQUIRED] Describe the problem

Is there a possibility to be able to merge either or both of `.firebaserc` or `firebase.json` inside `package.json`. Since it is still a part of the project package itself.

It is like eslint ignore using the `eslintIgnore` key inside `package.json`.

The ability to do this would reduce the number of files the project needs, and likewise reduce the number of files to manage in the root directory (since it will be managed using one file, `package.json`). Since `.firebaserc` file only contains more or less 5 lines on one database used, and `firebase.json` only contains around 30 lines.

#### Relevant Code:

It could be added as such inside `package.json` under the key firebase.

**package.json**
```json
{
  "name": "project-name",
  "dependencies": {

  },
  "firebase": {
    "projects": {
      "default": "project-name"
     },
    "database": {
      "rules": "./firebase/database.rules.json"
    },
    "hosting": {
      "public": "dist",
      "ignore": [
        "firebase.json",
        "**/.*",
        "**/node_modules/**"
      ],
      "rewrites": [
        {
          "source": "**",
          "destination": "/index.html"
        }
      ]
    },
    "storage": {
      "rules": "./firebase/storage.rules"
    }
  }
}
```

**Comment by kylecordes** [comment]
I actually request that the information in `.firebaserc` should **not** be combined with another file like `package.json`; it is a per-developer-specific configuration file, pointing to a specific firebase instance. It is quite common to share source code but not share access to a development or production database instance. Certainly it is possible for a group of developers to share the same firebase instance during production, But ideally they would not for development. It reminds me of the "bad old days" when relational databases were so very expensive that developers could not afford to have their own, they had to share one with other developers and overwrite each other's changes all the time.

More examples:

* In an open source project, it's likely that developers other than the handful of core developers, will not have any permissions to do anything at all to the same firebase instance that the core developers use.
* In a project developed for a customer, it's likely that the person developing it will be using a different firebase instance than the customer who will be permanently owning and deploying it.

**Comment by mbleigh** [comment]
Thanks for the request, but this is not something we're looking at implementing at present. The reasoning is:

1. Firebase is more than just Node.js -- `firebase.json` and `.firebaserc` are language-agnostic.
2. Everything @kylecordes said.
3. It's usually better to have one good way of doing things than several. This would introduce additional complexity to the CLI bootup and be prone to bugs and other problems (e.g. what happens if you have both?)

Hope that all makes sense :smile:
