### ISSUE TITLE
Update local rule with live rule in the project

### ISSUE THREAD

**Issue by Thaina** [firebase/firebase-tools#806]
Please add command to get database and other service's rules file like `firestore:indexes` so we could save and edit in local without conflict

I cannot find it anywhere in document. If it already exist it should better be documented

**Comment by mbleigh** [comment]
Thanks for the suggestion, I agree it'd be a handy thing to have. We'll put it on the list of things to consider.

**Comment by samtstern** [comment]
We now do this when you do `firebase init` but we don't yet have a separate command for it.

**Comment by Thaina** [comment]
@samtstern  Did that command are too hard to be added?
