### ISSUE TITLE
question about deploying indexes

### ISSUE THREAD

**Issue by npomfret** [firebase/firebase-tools#812]
I have a bunch of indexes that I created by using the URL that gets logged when running a query that needs an index.

I'm worried that when I run a `deploy`, all my indexes will get removed because the `firestore.indexes.json` file is empty.

Is it possible to download my index configuration so I can put it in the `firestore.indexes.json` file?

(Sorry, not an issue)

**Comment by samtstern** [comment]
@npomfret yes this exists

Just run `firebase firestore:indexes` and the output will be the JSON you need.

Here's an example I just tried:

```shell
$ firebase --project=firestorequickstarts firestore:indexes
{
  "indexes": [
    {
      "collectionId": "chat-messages",
      "fields": [
        {
          "fieldPath": "userid",
          "mode": "ASCENDING"
        },
        {
          "fieldPath": "timestamp",
          "mode": "DESCENDING"
        }
      ]
    },
    {
      "collectionId": "restaurants",
      "fields": [
        {
          "fieldPath": "category",
          "mode": "ASCENDING"
        },
        {
          "fieldPath": "numRatings",
          "mode": "DESCENDING"
        }
      ]
    },

   // ... [MUCH MORE HERE] ...
```

**Comment by npomfret** [comment]
thanks
