### ISSUE TITLE
Support definition of memory limit and timeout for cloud functions

### ISSUE THREAD

**Issue by p0la** [firebase/firebase-tools#821]
Hello, 

This is a feature request. 

I'm using the CLI to deploy my cloud functions, but as my userbase grew, some daily trimming operations cannot be performed with 256MB anymore. 
I went through the process of changing this limit via the console but it's really super painful. It would be great to be able to specify it directly from the CLI. 
Maybe via package.json ? a new "functionRuntimeParams" thing where you can specify extra parameters ? or in the index.js? 

In any case, thx for the good work. I'm using this tool everyday and I love it 👍

**Comment by mbleigh** [comment]
This is now possible! See https://firebase.google.com/docs/functions/manage-functions#set_timeout_and_memory_allocation
