### ISSUE TITLE
Functions fail to deploy with error code 13

### ISSUE THREAD

**Issue by SebastianKumor** [firebase/firebase-tools#824]
### Version info

3.19.3

### Platform Information

macOS high sierra 10.13.5

### Steps to reproduce

I have a new  firebase project where I activated functions, then I installed `npm install -g firebase-tools`

After that I logged into my google acc in firebase tools. Then I run `firebase init functions` selected my porject and followed the installer. Let it install all the dependencies. Then I tried to deploy the basic hello world function with some of mine custom functions but I got this error on all of them
 `⚠ functions[notifyNewSignUp]: Deployment error.
undefined`
`⚠  functions[helloWorld]: Deployment error. undefined`

I can see them in firebase console functions dashboard with red warning sign that says deployment failed. This is the error from the logs. 

`{"@type":"type.googleapis.com/google.cloud.audit.AuditLog","status":{"code":13,"message":"INTERNAL"},"requestMetadata":{"requestAttributes":{}},"serviceName":"cloudfunctions.googleapis.com","methodName":"google.cloud.functions.v1.CloudFunctionsService.DeleteFunction","resourceName":"projects/***-***/locations/us-central1/functions/notifyNewSignUp"}` 

I get this same error on all functions. I tried to deploy some of the example functions but same result.

### Expected behavior

I should be able to deploy functions.

### Actual behavior
The deployment always fails with the same error. The error itself does not say much about whats wrong. 

Maybe I missed something in the project setup but I followed the functions setup guide on firebase docs.

**Comment by mbleigh** [comment]
Please reach out to [Firebase support](https://firebase.google.com/support/), as this is a backend issue and not something specific to the Firebase CLI. Thanks!
