### ISSUE TITLE
Firebase cli  Deployment error on gitlab ci

### ISSUE THREAD

**Issue by prakashsellathurai** [firebase/firebase-tools#829]
`> firebase deploy --only functions --non-interactive --token $FIREBASE_TOKEN

=== Deploying to 'clothxnet'...

i  deploying functions
i  functions: ensuring necessary APIs are enabled...
✔  functions: all necessary APIs are enabled
i  functions: preparing functions directory for uploading...

Error: Error parsing triggers: Cannot find module './http/employee/addemployee'

Try running "npm install" in your functions directory before deploying.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! functions@ deploy: `firebase deploy --only functions --non-interactive --token $FIREBASE_TOKEN`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the functions@ deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-07-17T00_13_22_359Z-debug.log
ERROR: Job failed: exit code 1` 

> it works on local environment but fails to do the same on gitlab ci

**Comment by laurenzlong** [comment]
The error is: 

Error: Error parsing triggers: Cannot find module './http/employee/addemployee'

I assume that's one of your own files, you probably have the wrong path for it in the code.
