### ISSUE TITLE
Feature request: gulp wrapper for firebase-tools

### ISSUE THREAD

**Issue by mm-gmbd** [firebase/firebase-tools#83]
Would like to be able to pipe rules that are transpiled from either blaze (there is already a gulp wrapper for the blaze compiler) or butane to a `firebase deploy` task.

Considering these are already cli tasks this maybe possible today (by using `exec` in the gulpfile), but tasks such as `login` I think require input at the command line rather than accept arguments, making this tougher than just something like `exec('firebase login `*`username`*` `*`password`*`')`.

**Comment by mbleigh** [comment]
This should be very possible now, actually :smile: 

See [the CI section of the docs](https://github.com/firebase/firebase-tools#using-with-ci-systems) for how to obtain a token that you can use instead of `firebase login`, and the section below on how to perform commands programmatically!

**Comment by mm-gmbd** [comment]
@mbleigh, thanks for pointing that out! (And apologies for overlooking the docs!)

I'll include the appropriate commands in some gulp tasks. I may go about actually writing a generic version that has commands handily wrapped when I've got some time... thanks again!
