### ISSUE TITLE
The following indexes are already deployed but not present in the specified indexes file:

### ISSUE THREAD

**Issue by npomfret** [firebase/firebase-tools#830]
When I run `firebase deploy` I see this message:

> NOTE: The following indexes are already deployed but not present in the specified indexes file:

How do I get hold of the indexes I've created so I can add them to my `firestore.indexes.json` file?

**Comment by markhilton** [comment]
I was wondering about the same... in case the project would have to be re-deployed I would nice to have a copy of firestore.indexes.json updated. Did you find out by any chance if there is a way to export current indexes into a json file?

**Comment by skhaz** [comment]
Is there some way to synchronize the `firestore.indexes.json`?
