### ISSUE TITLE
Init wrong rule in firestore.rules file

### ISSUE THREAD

**Issue by ItangSanjana** [firebase/firebase-tools#837]
### Version info

4.0.0

### Platform Information

Ubuntu GNU/Linux (16.04)

### Steps to reproduce

`mkdir [new-dir] && cd $_`
`firebase init`

### Expected behavior

```
service cloud.firestore {...}
```

### Actual behavior

```
service firebase.storage {...}
```

**Comment by ItangSanjana** [comment]
`service firebase.storage {...}` in firestore.rules file?
Shouldn't it be `service cloud.firestore {...}`?

**Comment by laurenzlong** [comment]
Thanks for clarifying! I was able to reproduce this. @samtstern Could you take a look? I think this API is actually for storage rules, not Firestore rules: https://github.com/firebase/firebase-tools/blob/master/lib/gcp/rules.js#L25
