### ISSUE TITLE
Deploy failing with an unexpected error

### ISSUE THREAD

**Issue by ahaverty** [firebase/firebase-tools#838]
### Platform Information
firebase tools: 4.0.0
OS X

### Steps to reproduce

`firebase deploy`

### Expected behavior

Hosting, database rules and functions all deploy correctly without error

### Actual behavior
Fails with an unexpected error after awhile.
Functions deploy when checking google console, but hosting doesn't activate this deployment (presumably it's the last step of `firebase deploy`)
This is currently breaking CI deploys for us
```
 ...
 Thu Jul 26 2018 19:19:50 GMT+0100 (IST)
[debug] [2018-07-26T18:19:51.243Z] <<< HTTP RESPONSE 200
[warn] ⚠  functions: too many functions are being deployed, cannot poll status.
[debug] [2018-07-26T18:19:51.266Z] ReferenceError: options is not defined
    at printTooManyOps (/Users/alan/.nvm/versions/node/v6.14.0/lib/node_modules/firebase-tools/lib/deploy/functions/release.js:102:24)
    at Object.pollDeploys (/Users/alan/.nvm/versions/node/v6.14.0/lib/node_modules/firebase-tools/lib/functionsDeployHelper.js:147:5)
    at /Users/alan/.nvm/versions/node/v6.14.0/lib/node_modules/firebase-tools/lib/deploy/functions/release.js:378:25
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
[error] 
[error] Error: An unexpected error has occurred.
```

**Comment by ahaverty** [comment]
This happens constantly with full deploys for us since updating to `v4.0.0` (90+ functions) windows, mac, and CI
Rolling back to `"firebase-tools": "3.19.3"` is error free.

**Comment by ahaverty** [comment]
Also, while I'm here and touching on the topic.
With CI, when deploying and getting the "Too many functions". Is there anyway we can be updated about whether functions deployed ok in the end or if anything went wrong. We're currently checking google cloud console, waiting for the green ticks which isn't ideal.

**Comment by laurenzlong** [comment]
Hi, that's a bug indeed, thanks for  reporting @ahaverty ! After it's fixed, the CLI output will also report exactly which functions are successfully deployed.
