### ISSUE TITLE
Simplify finding project in 'firebase init'

### ISSUE THREAD

**Issue by samtstern** [firebase/firebase-tools#847]
When I do `firebase use --add` I get a really nice, alphabetical list of projects.  When I do `firebase init`, however, I get a seemingly random order.  I have a lot of projects and it's a bit of a pain to scroll down with arrow keys hunting for the one I am looking for.

Suggested improvements:

  * Have all project lists be ordered by name (not id), for consistency between `firebase use` and `firebase init`.
  * Make `firebase init` respect the `--project` flag to avoid the chooser altogether, in cases where you know the ID you want to init.  This is useful for team collaboration or setting up a new computer.

**Comment by mbleigh** [comment]
Thanks for the report! If we standardize, it will probably be on alphabetical by project-id since that's the canonical identifier, but I agree a `--project` flag or something like it would be useful as a shortcut.

**Comment by saffy** [comment]
+1 
I have somewhere in the realm of 100 projects shared due to org sharing. gcloud cli let's me supply a project name with a nice message about how I have a lot of projects, firebase init, not so much.

**Comment by samtstern** [comment]
@saffy check out #923 and see if it does what you want

**Comment by saffy** [comment]
@samtstern Looks good to me!
