### ISSUE TITLE
Automatic deploy to hosting with API

### ISSUE THREAD

**Issue by FredyC** [firebase/firebase-tools#85]
I have so much struggle with this, especially authentication part. When I login with `firebase login`, then I can grab token from `firebase prefs:token`. However once I run `firebase logout`, this token becomes invalid and cannot be used anymore. If I am about to use this token in the config for deployment tool, I am not even sure if this token can expire eventually.

I am wondering if there is some other way how to obtain the token without this manual step and relying on some expiration time. I tried to use [firebase-token-generator](https://github.com/firebase/firebase-token-generator-node) to create token which creates nice JWT token, but I am not sure how to use that token for hosting deployment. Passing it to `token` option gives me error from remote server: `{"error":{"code":"AUTHENTICATION_REQUIRED","message":"Authentication required."}}`

**Comment by mbleigh** [comment]
The tokens generated when you log in are long lived (six months or a year), and you should simply login again and generate a new one (or generate a new one to pass to your CI system) when one expires.

There is no way to login without passing through the browser, but you can access the URL on any machine. Hope that helps!

**Comment by FredyC** [comment]
@mbleigh I don't think that helped that much or I don't understand you that
well. What URL can I access?

**Comment by mbleigh** [comment]
Apologies, I misread part of the message. We're currently working on a `login:ci` command #71 that will be released soon and simply mint a token without persisting a local session.

What you can do is login with `firebase login` and then instead of calling logout just run:

    rm ~/.config/configstore/firebase-tools.json

**Comment by FredyC** [comment]
Ahh, that's great news, especially about #71. That's definitely helpful, thanks you.
