### ISSUE TITLE
importing firebase-tools in gulp makes tasks hang

### ISSUE THREAD

**Issue by rolandjitsu** [firebase/firebase-tools#86]
It looks like if I `import { deploy } from 'firebase-tools'` or `require('firebase-tools')` in my gulp file, any tasks I start it seems to be hanging after it's done and it never exists.

You can check it on Travis by looking at one of my failed [builds](https://travis-ci.org/rolandjitsu/ng2-lab/builds/88149343). If you look at what changed from the previous versions you can see that I've added firebase tools to manage the deployments to Firebase.

**Comment by mbleigh** [comment]
@rolandjitsu this is unfortunately a current limitation of the Firebase real-time client (which is used by `firebase-tools` behind the scenes. You can wait for the promise to return and then manually exit the process with `process.exit(0)` or alternatively use something like `require('child_process').spawnSync` to deploy via shelling out instead.

**Comment by rolandjitsu** [comment]
@mbleigh I am unsure what you mean with `You can wait for the promise to return and then manually exit the process with process.exit(0)`, could you have a short example for me?

**Comment by mbleigh** [comment]
```js
var tools = require('firebase-tools');
tools.deploy({
  firebase: 'YOUR_FIREBASE_PROJECT",
  token: 'YOUR_FIREBASE_TOKEN'
}).then(function() {
  process.exit(0);
}).catch(function(err) {
  console.log(err);
  process.exit(1);
});
```

via spawn:

```js
var spawn = require('child_process').spawn;

var proc = spawn("./node_modules/.bin/firebase", ["deploy", "-f", "YOUR_FIREBASE_PROJECT", "--token", "YOUR_TOKEN"]);
proc.on('close', function(code) {
  if (code === 0) {
    // succeeded
  } else {
    // failed
  }
});
```

Note: I wrote these without testing them, but they should be close to correct.

**Comment by rolandjitsu** [comment]
@mbleigh thanks. I already had this done, the second version, but I thought you may have another way of doing it.

**Comment by jensenbox** [comment]
Are there tools that will show any open resources? Took me a while to find out that it was firebase causing this.

Would love a better answer than "kill the beast"

**Comment by rolandjitsu** [comment]
@jensenbox to find out if there any process running you could `ps aux` on Mac and maybe do a `grep` if you are looking for something specific. But that would not help much anyway. So the best way would be what @mbleigh suggested, spawn a child and run the process there. I have a simple fn that does just that:
```js
import gulp from 'gulp';
import {exec} from 'child_process';
import {env, log, colors} from 'gulp-util';

// https://github.com/firebase/firebase-tools#commands
function runFirebaseCommand(cmd, args = []) {
	let binary = process.platform === 'win32' ? 'node_modules\\.bin\\firebase' : 'node_modules/.bin/firebase'; // Windows or Linux path
	const TOKEN = process.env.FIREBASE_TOKEN || env.token;
	if (!TOKEN) {
		log(colors.red('No FIREBASE_TOKEN found in env or --token option passed.'));
		return Promise.reject();
	}
	let defaultArgs = [
		'--non-interactive',
		'--token',
		`"${TOKEN}"`
	];
	if (Array.isArray(args)) args.unshift.apply(args, defaultArgs);
	else args = defaultArgs;
	binary += ` ${cmd}`;
	args.unshift(binary);
	let proc = exec(args.join(' '));
	// streamProcLog(proc); // a fn to stream data to from the child process
	return proc;
}

gulp.task(function deploy() {
	return runFirebaseCommand('deploy');
});
```
And you can use it as such `runFirebaseCommand('deploy:hosting')`. Keep in mind that the above example is using Gulp 4 and ES6.
