### ISSUE TITLE
Firebase deploy hosting broken for ts-loader in react

### ISSUE THREAD

**Issue by danilofuchs** [firebase/firebase-tools#868]
I have a React project built with typescript and ts-loader. All my **build** files are structured in static/js/main.xxx.js and multiple static/js/chunk.xxx.js. The entry point is index.html.
According to the release notes for firebase-tools 4.1.0: _Firebase Hosting deploys will now only upload files that are different from previous deploys._
This update broke my webapp, throwing _Uncaught SyntaxError: Unexpected token <_.
This may occur as a result of firebase only updating some of the files in the build folder and not loading newly built chunks properly

### Version info

firebase-tools 4.1.0

### Platform Information
Windows 10

### Steps to reproduce
firebase deploy --only hosting

### Expected behavior
Page loads correctly and all chunks are loaded.

### Actual behavior
Files are not updated to consider new chunks.

### Temporary Fix
Deleting .firebase/hosting.0.cache and downgrading to firebase-tools 4.0.3 fixed my issue

**Comment by bkendall** [comment]
Thanks for bringing it to our attention. There is work inflight to resolve this issue. 

If you have a moment, can you confirm that files at your _root_ directory (`/something.ext`) work?

For the time being, continue to use `v4.0.3`.

**Comment by Herohtar** [comment]
@bkendall This seems to be a more general issue with `v4.1.0` that `firebase deploy` doesn't upload anything in a subfolder, even if it's a completely new file. Downgrading to `v4.0.3` works fine.

**Comment by codegenin** [comment]
try upgrading to 4.1.1

**Comment by Herohtar** [comment]
4.1.1 seems to work for me.

**Comment by danilofuchs** [comment]
4.1.1 works perfectly. Thanks for the quick fix!
