### ISSUE TITLE
Found a Bug with the v4.1.0

### ISSUE THREAD

**Issue by mayeedwin** [firebase/firebase-tools#870]
Found a Bug with the v4.1.0
=======================
> failed to load resource the server responded with a status of 404 not found 

I just updated my firebase tools today and on deploying my project, I found the bug above; I had to revert back to version **4.0.3** and everything is fine now ; 

Some work needs to be done ; 

Cheers!

**Comment by codegenin** [comment]
I am having problem also after update. Updated to v.4.1.0 from 4.0.3, the deploy works without issue but when I checked the app in browser, got blank screen and in console I got.

> Uncaught SyntaxError: Unexpected token <

for manifest, vendor and app js files. I will try to revert to previous version. hope it will be fix.

**Comment by topvis** [comment]
I have the same issue as @codegenin does. Downgraded to 4.0.3 resolved the issue.

**Comment by mbleigh** [comment]
Please try upgrading to 4.1.1 and see if that fixes the issue.

**Comment by codegenin** [comment]
@mbleigh - tried 4.1.1 with new and existing builds. Works perfectly! thank you.

**Comment by bkendall** [comment]
Thanks for confirming it works!

**Comment by mayeedwin** [comment]
great! will try it out

**Comment by jp-sauve** [comment]
I have this same problem with 6.3.0!

**Comment by bkendall** [comment]
@jp-sauve please open a new issue with the required information. thanks.

**Comment by karsonbraaten** [comment]
Anyone find a solution to this?

**Comment by NishilSB** [comment]
me too have the same issue with 6.3.0. help me please

**Comment by bkendall** [comment]
Please open a new issue with the required information. This bug is on an old version the fix was to upgrade. 404s can happen in many different ways, so new bugs and the appropriate information is required. Thank you.
