### ISSUE TITLE
Deployment: 'Unexpected token <' after firebase deploy

### ISSUE THREAD

**Issue by trenoncourt** [firebase/firebase-tools#871]
### Version info

4.1.0

### Platform Information

Windows 10

### Steps to reproduce
`npm i -g @vue/cli`
`vue create app` with default (babel/eslint)
`cd app`
`firebase init` with same configuration as [https://cli.vuejs.org/guide/deployment.html#firebase](https://cli.vuejs.org/guide/deployment.html#firebase)
`yarn build`
`firebase deploy`

### Expected behavior

App must load normaly with default vue template

### Actual behavior

Only index.html is loaded, other js/css files are replaced by index.html.
That causes `Uncaught SyntaxError: Unexpected token <` for js files

### Other informations

App is working with firebase serve and nginx.
Files in root folder are loaded correctly.
The problem seems to come from the files in the subfolders, as if they were not uploaded

**Comment by mbleigh** [comment]
Try upgrading to 4.1.1

**Comment by trenoncourt** [comment]
Perfect, it works :)

**Comment by CodingCreate101** [comment]
Hi, I am facing the same issue. Which module version you guys are talking about?

**Comment by bkendall** [comment]
@arled it is to upgrade `firebase-tools` (the `firebase` cli).

If you have issues, please open a new Issue with the appropriate information. Thanks.
