### ISSUE TITLE
firebase serve results in "Unexpected error occurred" for v4.1.x

### ISSUE THREAD

**Issue by chalin** [firebase/firebase-tools#876]
### Version info

```console
> firebase --version
4.1.1
```

### Platform Information

MacOS

### Steps to reproduce

 1. Clone and setup https://github.com/dart-lang/site-www (see setup instructions in the README).
 2. Launch `firebase serve` using this script: `./scripts/serve.sh --firebase`.
 3. Visit [localhost:400](http://localhost:4000).

### Expected behavior

The visited page should load.
Note that it loads fine with **firebase-tools@4.0.3**.

### Actual behavior

You'll see this in the browser: 'Unexpected error occurred.', and this in the terminal where the server was launched:

```nocode
Error: {"redirect":""} is not a recognized responder directive
    at Responder._handle (/Users/chalin/.nvm/versions/node/v10.9.0/lib/node_modules/firebase-tools/node_modules/superstatic/lib/responder.js:72:22)
    at Responder.handle (/Users/chalin/.nvm/versions/node/v10.9.0/lib/node_modules/firebase-tools/node_modules/superstatic/lib/responder.js:43:15)
    at /Users/chalin/.nvm/versions/node/v10.9.0/lib/node_modules/firebase-tools/node_modules/superstatic/lib/middleware/files.js:59:36
    at tryCatch (/Users/chalin/.nvm/versions/node/v10.9.0/lib/node_modules/firebase-tools/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/Users/chalin/.nvm/versions/node/v10.9.0/lib/node_modules/firebase-tools/node_modules/rsvp/dist/rsvp.js:538:13)
    at publish (/Users/chalin/.nvm/versions/node/v10.9.0/lib/node_modules/firebase-tools/node_modules/rsvp/dist/rsvp.js:508:7)
    at flush (/Users/chalin/.nvm/versions/node/v10.9.0/lib/node_modules/firebase-tools/node_modules/rsvp/dist/rsvp.js:2415:5)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

The firebase config file is: https://github.com/dart-lang/site-www/blob/master/firebase.json.

Related:
- This breaks builds on Travis, see https://github.com/dart-lang/site-www/issues/1051
- Superstatic also has issues. see https://github.com/firebase/superstatic/issues/260

cc @kwalrath @filiph @kevmoo @mbleigh

**Comment by joespina** [comment]
Getting this same issue with error `{"redirect":""} is not a recognized responder directive` also.

In my case, the only page that is failing is the `index.html` file, all other pages are loading properly.

Working with
```
firebase 4.2.0 on Windows 10
```

**Comment by jahglow** [comment]
it's superstatic.js @ line 57 watching to remove trailing slash if its setting is false. Try to set "trailingSlash:true" in firebase.json for a temporary fix

**Comment by chalin** [comment]
Thanks for pin-pointing that. Both firebase and superstatic have issues. I've reverted to earlier versions for both.

**Comment by mathiasbynens** [comment]
Hitting this issue as well.

@chalin Which versions did you downgrade to? Might be useful for others having the same issue (and who don’t want to change their `trailingSlash` settings).

**Comment by chalin** [comment]
@mathiasbynens, [these versions](https://github.com/dart-lang/site-www/blob/b2c29165cdfdba32872127abcc3d754536c70188/package.json#L11-L12):

```json
    "firebase-tools": "4.0.3",
    "superstatic": "^5.0.2"
```

**Comment by mathiasbynens** [comment]
I can confirm firebase-tools@4.0.3 doesn’t have the `firebase serve` issue. However, it seems `firebase deploy` no longer works on v4.0.3. I keep getting:

```
⚠  Your CLI authentication needs to be updated to take advantage of new features.
⚠  Please run firebase login --reauth
```

Then, after doing the `firebase login --reauth` dance:

```
Error: An unexpected error has occurred.
```

Hopefully this can be fixed soon — I’d rather not have to choose between testing locally or deploying ;)

**Comment by chalin** [comment]
Maybe you can use superstatic for testing locally and firebase for deploying. (FYI, I can deploy locally without issues.)

**Comment by mathiasbynens** [comment]
https://github.com/firebase/superstatic/pull/262

**Comment by mathiasbynens** [comment]
To anyone experiencing this issue, just re-install `npm i -g firebase-tools` so it pulls in the latest `superstatic` as a dependency. 

superstatic@6.0.2 was just released containing the fix (https://github.com/firebase/superstatic/pull/262).
