### ISSUE TITLE
Deleting in non-interactive mode is not possible

### ISSUE THREAD

**Issue by ahaverty** [firebase/firebase-tools#877]
### Version info

"firebase-tools": "4.1.1"

### Platform Information

OS X and Bitbucket Pipelines CI

### Steps to reproduce

In Bitbucket pipelines CI, using non-interactive mode with env variables
`firebase use myproject` 
`firebase deploy` with 5 functions in index.js

_In a later PR_
`firebase deploy` with just 4 functions in index.js

### Expected behavior

1. The full firebase deploy removes the "5th" function that is no longer in the latest index.js
2. No manual steps/CLI commands are required (like in previous versions of firebase tools)

### Actual behavior

`Error: The following functions are found in your project but do not exist in your local source code:`
... list of functions ...
`Aborting because deletion cannot proceed in non-interactive mode. To fix, manually delete the functions by running:`

**Comment by laurenzlong** [comment]
Hi, this is intentional behavior, since we got a lot of feedback that users did not like how the CLI automatically deleted their functions. So now we require user confirmation for deletions, which cannot be done in non-interactive. 

This is why the release was a major version bump, to indicate a breaking change in behavior.

**Comment by ahaverty** [comment]
@laurenzlong could a flag be added to allow deletions in non-interactive mode? Deleting functions by hand in CLI for us is way less safe and inconvenient versus a good review/merge policy + CI deployments

**Comment by laurenzlong** [comment]
Could you expand on your rationale a bit more? Are you deleting functions often during CI?

**Comment by ahaverty** [comment]
Sure: We're constantly refactoring old functions and often replacing (swapping https onRequest for onCall for example). It's easier for us to delete the old function and add a new one. Sometimes we simply aren't using the function anymore, and want it gone.
We wouldn't delete a function every week, but now that it's not possible to do via CI, it means we have to add a manual step in review to manually delete before merging and auto deploying. It also means at least two developers need write access to our production functions, which we're trying to get away from for peace of mind.
If we had something like `firebase deploy --allow-deletes` and we maintain a good review process, our entire Dev team can freely create/update/delete anything without waiting on me to open up production CLI on my laptop while I'm working on something else.

I can understand why the default would be not to delete, but we're suprised it's not possible/blocked in non-interactive mode, assuming most people in that mode are thoroughly reviewing before deploying like we are?

**Comment by laurenzlong** [comment]
Thanks for the feedback Alan, I'll open up the discussion internally about this.

**Comment by nerdyglasses** [comment]
We have exactly the same issue. It would help as a lot as well. We had to give up our automated deployments using Google Cloud Builder because of the update.

**Comment by IchordeDionysos** [comment]
Not sure if anyone suggested it already.
Most of the users seem to prefer a flag where functions not present will get deleted.

This is not always the option.
For example, we would like to have a flag, which allows us to just ignore these functions.
So the functions won't get an update or get's deleted.

For example, if someone created a new function in a feature branch and deployed it using `firebase deploy --only functions:functionName`

And then someone tries to deploy a new version, then our CI pipeline would start and call the command
`firebase deploy --ignore-missing-functions`, then the deploy would update all present functions, create missing functions, but would not update or delete the function `functionName`.

I see the benefit of a flag to get back the old behaviour, so both behaviours would be great to have in my opinion.

**Comment by ArtemBogush** [comment]
Same here. Because we have lots of triggers and often times we need to move user database from prod to dev project for investigation and troubleshooting we need a way to disable all the triggers during json import.
And the only way to disable triggers we came up is to actually delete all the functions in dev project before the import - literally comment out all the index.js, deploy it to dev, then import the json and then revert all the functions back for further investigation of any reported issues.

If there is a way to disable triggers in a more friendly way with the updated CLI I would much appreciate any input on how to achieve that. Otherwise removing functions from CLI in a batch is still something we rely on.

**Comment by solomonengel** [comment]
@laurenzlong is this being addressed?

**Comment by IchordeDionysos** [comment]
@mbleigh Is there any option to not delete any function when I run `firebase deploy`?

For example, if I have 2 separate repositories with totally different functions which all deploy to the same Functions project.

So e.g.:
I have repos
- "frontend", with the function:
    - languageRedirector
- "backend", with:
    - onUserAuthenticated

Now if I run `firebase deploy` from the "frontend" repo I want to update only `languageRedirector`
and if I run `firebase deploy` from the "backend" repo I want to update only `onUserAuthenticated`

Is this possible?

**Comment by bkendall** [comment]
@IchordeDionysos that is not possible, as far as I'm aware. During the deploy process, the functions are inspected to figure out what needs to be removed and what needs to be added. If one is "missing" from the code, the CLI will attempt to delete it.

**Comment by IchordeDionysos** [comment]
Is this #999 something you are considering? :)
We really need this option as our CI script currently won't work without this...

**Comment by bkendall** [comment]
@IchordeDionysos In the meantime, is it possible for you to use `--only functions:[function]` on `firebase deploy` to get your CI working? You can find more details here: https://firebase.google.com/docs/cli/#deploy_specific_functions

**Comment by heygambo** [comment]
For us the issue is resolved. We're able to deploy via Google Cloud Builder again.

**Comment by alizbazar** [comment]
Here's the "hack" that we are using to only upsert function (not delete others):

```bash
echo "n\n" | firebase deploy --only functions --interactive --token $FIREBASE_TOKEN
```

Would also appreciate having and explicit option such as `--no-delete` rather than relying on the question never changing 😏

**Comment by animysore** [comment]
Another "hack" alternative is to explicitly pass all function names after reading them from the index.ts

```
firebase deploy --token $FIREBASE_TOKEN --only functions:`sed -n "s/exports\.\(\w*\).*$/\1/p"  functions/index.ts | paste -s -d, -`
```

[Explanation](https://dev.animysore.com/notes-on-firebase-in-production-1)

**Comment by donvaughn** [comment]
In some cases, another way to solve issue this is by using [cloud function groups](https://firebase.google.com/docs/functions/organize-functions#group_functions). For example, in your root index.js file, you would simply export an object containg all your functions:

```javascript
import { helloWorld } from './hello-world';

exports.api = {
  helloWorld,
};
```

And the deploy command for this function group then looks like this:

```bash
firebase deploy --only functions:api
```

And when using the above deploy command with the `--force` option, you can automatically delete functions removed from your `api` group while ignoring all functions in other groups.

**Comment by louis030195** [comment]
Still no way to confirm in any case in non-interactive mode?

A `-y`just like in `apt install -y foo`would be nice

`firebase deploy -y`

**Comment by Retsuki** [comment]
I wanted to deploy through the cloud build.
so I did below

```ts
// pachage.json
{
  ...
  "scripts"{
    "deploy:staging": "firebase use staging && echo \"n\n\" | firebase deploy --only functions --interactive",
    ...
  },
}
```

```yaml
steps:
  - id: Install packages
    name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  - id: Build firebase functions
    name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
  - id: Deploy to firebase functions
    name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'deploy:staging']
```

I hope to help someone.
thank you.

**Comment by leo-paz** [comment]
@Retsuki Do you have firebase tools as a dependency?
 
It would really be nice to just have an ignore flag for this 😐
