### ISSUE TITLE
Deployed hosting routes do not tolerate duplicated slashes

### ISSUE THREAD

**Issue by jonhoo** [firebase/firebase-tools#880]
### Version info

4.1.2

### Platform Information

Linux

### Steps to reproduce

When using `firebase serve`, a file like `foo/bar.txt` can be successfully requested using the URL `http://localhost:5000/foo//bar.txt`. When the site has been deployed with `firebase deploy` however, `X.firebaseapp.com/foo//bar.txt` yields a "Page Not Found" error. This leads to fairly hard-to-debug issues, since everything appears to function normally when developing normally.

```console
$ mkdir public/foo
$ echo bar > public/foo/bar.txt
$ firebase deploy && firebase serve &
$ curl localhost:5000/foo/bar.txt
bar
$ curl localhost:5000/foo//bar.txt
bar
$ curl https://foobar.firebaseapp.com/foo/bar.txt
bar
$ curl https://foobar.firebaseapp.com/foo//bar.txt

<!doctype html>
<html>
  <head>
    <title>Page Not Found</title>
...
```

### Expected behavior

It'd be great if the routing behavior on `firebaseapp.com` could be fixed so that it doesn't choke on `//`, but barring that, it'd arguably be better if `superstatic` (which underlies `firebase serve`) *didn't* support collapsing slashes so that the error *also* occurred locally.

**Comment by mbleigh** [comment]
Serving behavior should now work with `//` -- please let us know if it doesn't.
