### ISSUE TITLE
Change log posted to https://firebase.google.com/support/release-notes/js 

### ISSUE THREAD

**Issue by hgghyxo** [firebase/firebase-tools#885]
I was looking for the change log for firebase-tools and have found everything, expect this on 
https://firebase.google.com/support/releases

the best would be to add it to https://firebase.google.com/support/release-notes/js in my opinion, but if it is available anywhere else, just I didn't find it, please point me there :)

**Comment by laurenzlong** [comment]
You can find it all here: https://github.com/firebase/firebase-tools/releases

**Comment by hgghyxo** [comment]
The only place I didn't checked ... Thank you very much :)
