### ISSUE TITLE
Capture redirects won't work on firebase

### ISSUE THREAD

**Issue by chenxsan** [firebase/firebase-tools#886]
### Version info

firebase: 4.1.2

### Platform Information

macOS High Sierra 10.13.5

### Steps to reproduce

I have this redirect rule in my `firebase.json`:

```json
{
        "source": "/blog/:permalink.html",
        "destination": "https://blog.example.org/:permalink/",
        "type": 301
      },
```

### Expected behavior

`my-domain.com/blog/hello-world.html` should be redirected to `https://blog.example.org/hello-world/`.

### Actual behavior

It shows 404 page after my site deployed to firebase hosting, although it did redirect when I run `firebase serve` locally.

**Comment by mbleigh** [comment]
@Berlioz what's the status of this particular scenario?

**Comment by chenxsan** [comment]
@laurenzlong Is't fixed or it's not even a bug?

**Comment by bkendall** [comment]
Reopening and pinging @Berlioz for a response 😄

**Comment by Berlioz** [comment]
The discrepancies between `serve` and the actual backend should be hammered out at this point. I can't reproduce this particular bug anymore--I suspect that if you try this out again on your site, it should work as expected. If you do experience any issues, feel free to open a new issue.
