### ISSUE TITLE
How could I import/deploy firestore single field index?

### ISSUE THREAD

**Issue by Thaina** [firebase/firebase-tools#889]
The new firestore feature, single field index, is release. But I have seen no document about format and how it could import or deploy. `firestore:indexes` command is not export it

**Comment by samtstern** [comment]
@Thaina single field indexes are mostly enabled by default, would you like to be able to disable them in the `indexes.json` file?

**Comment by Thaina** [comment]
@samtstern What I want is to export to edit and backup the configuration. Some field I want to index as arraycontains or only descending for instance

**Comment by samtstern** [comment]
Fixed by #1014 and will be included in the next release (hopefully today)
