### ISSUE TITLE
turn of progress for deployments

### ISSUE THREAD

**Issue by rolandjitsu** [firebase/firebase-tools#89]
When running a deployment from Travis CI the progress output is really [messy](https://travis-ci.org/rolandjitsu/ng2-lab/jobs/88403281#L637), is there any way to turn that off?

**Comment by mbleigh** [comment]
Run the command with `--non-interactive` and you'll get a more Travis-friendly progress bar :smile:

**Comment by rolandjitsu** [comment]
@mbleigh I already do that. The command is `firebase deploy:hosting --non-interactive --token <my firebase token>`.

**Comment by mbleigh** [comment]
Can you paste me your output? It should be pretty clean if you're running in `--non-interactive` mode.

**Comment by mbleigh** [comment]
Ah I missed the link before. That's strange. The line that writes the progress is right here: https://github.com/firebase/firebase-tools/blob/f78db4a1f0005643f8e777ac9bca1198df88c202/lib/deploy/hosting/deploy.js#L58

There's no newlines, I'm not sure what would be causing Travis to log each `write` out to different lines.

I'll reach out to Travis to see if they have any ideas.

**Comment by rolandjitsu** [comment]
Exactly, it looks very weird. Perhaps the issue is `_.repeat(chalk.green('.'), percent - lastPercent)`?

**Comment by rolandjitsu** [comment]
There also seem to be quite a lot of new lines between logs.
