### ISSUE TITLE
"An error occurred while loading functions" message in Firebase consol

### ISSUE THREAD

**Issue by jvmonjo** [firebase/firebase-tools#891]
When I load the main FUnctions dashboard I see a generic "An error occurred while loading functions".

In the devtools I can see this error message:

```
code: 403
message: "The v1beta2 API is deprecated. If you're using the gcloud or Firebase CLI, please update to the latest version. See https://cloud.google.com/functions/docs/migrating"
status: "PERMISSION_DENIED"
```

Although there's no error message during deploy.

### Version info

4.2.0

### Platform Information

OS X 10.13.5

### Steps to reproduce

The error started after adding a function with enviorenment variables (functions.config())

After removing that funtion the error still persists, so I don't know if that was the issue.

### Expected behavior

The functions dashboard should load without errors.

### Actual behavior

The dashboard displays the error: "An error occurred while loading functions"

**Comment by bittlingmayer** [comment]
I also see this issue.  It is totally opaque, no hint as to what may have caused it.

As a temporary workaround, try https://console.cloud.google.com/functions.

It's in our dev project.  Now I am afraid to push to the prod project.

I am tempted to blow away dev.

**Comment by bittlingmayer** [comment]
There are some other symptoms.  There is no way to see which functions exists, nor anyway to select a specific function in the other tabs.

<img width="747" alt="screen shot 2018-08-28 at 12 55 01" src="https://user-images.githubusercontent.com/11457984/44712419-bf518180-aac1-11e8-9378-b25b0c1ff1a5.png">

**Comment by jvmonjo** [comment]
It seems that they've fixed the problem already. For me it's working fine now.
