### ISSUE TITLE
Firebase login error

### ISSUE THREAD

**Issue by Isuru40** [firebase/firebase-tools#896]
I have installed node.js and npm. after i installed  .Firebase command line tools also.after when i opened CMD and run **firebase login** .it says waiting for authentication .i  waited nearly 1 hour.nothing happen.I found out the new command  **firebase login -- interactive** this one also dosen't work. actually what should i do ?

**Comment by mbleigh** [comment]
Try running `firebase login --no-localhost` and following the instructions.

**Comment by Isuru40** [comment]
I tried  firebase login --no-localhost but it asked about  **paste  authorization code here:**.What is that ?

**Comment by mbleigh** [comment]
You need to open the link that the command prints out in a browser, follow the steps there, and then it will give you an authorization code that you can paste back into the command line. If you're not seeing a URL printed out, can you please paste or screenshot the output you're seeing? Also, what platform are you on and what version of the Firebase CLI are you running?

**Comment by Isuru40** [comment]
I used windows 8. Firebase CLI Version:   4.2.1

![screenshot 408](https://user-images.githubusercontent.com/25480142/44905868-ff6a6b80-ad30-11e8-897d-f868b47c300a.png)
another thing  is i run cmd  from my project folder.it contain only one test html file to host. In that folder when i type cmd firebase login --no-localhost ,automatically .log file created .its name is **firebase-debug**

this is its contains
**[debug] [2018-08-31T09:44:21.260Z] ----------------------------------------------------------------------
[debug] [2018-08-31T09:44:21.264Z] Command:       C:\Program Files (x86)\nodejs\node.exe C:\Users\User pc\AppData\Roaming\npm\node_modules\firebase-tools\bin\firebase login
[debug] [2018-08-31T09:44:21.264Z] CLI Version:   4.2.1
[debug] [2018-08-31T09:44:21.264Z] Platform:      win32
[debug] [2018-08-31T09:44:21.264Z] Node Version:  v8.9.4
[debug] [2018-08-31T09:44:21.273Z] Time:          Fri Aug 31 2018 15:14:21 GMT+0530 (Sri Lanka Standard Time)
[debug] [2018-08-31T09:44:21.274Z] ----------------------------------------------------------------------
[debug] 
[info] 
[info] Visit this URL on any device to log in:
[info] https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=355504027&redirect_uri=http%3A%2F%2Flocalhost%3A9005
[info] 
[info] Waiting for authentication...
[debug] [2018-08-31T09:44:24.353Z] Unable to open URL: Error: spawn cmd ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
**

**Comment by dhwanik9** [comment]
I am having the same problem, even when I paste that link it shows Error 400.

**Comment by laurenzlong** [comment]
@dhwanik9 Can you share your platform information and debug logs? Run the command with "--debug".

**Comment by bkendall** [comment]
Please open a new bug with your issue, rather than commenting on this one. Thanks.

**Comment by cristiaan05** [comment]
I have the same error but I cannot fix it.

**Comment by bkendall** [comment]
@cristiaan05 please open a new issue with the appropriate information. Thanks.

**Comment by arifpetok** [comment]
![image](https://user-images.githubusercontent.com/39609916/63575094-71c40380-c5b3-11e9-9b7f-344ce38777ed.png)

I have the same error but I cannot fix it.

**Comment by arifpetok** [comment]
![image](https://user-images.githubusercontent.com/39609916/63575171-a0da7500-c5b3-11e9-8b83-9163ef0bbd74.png)

I have the same error but I cannot fix it.

**Comment by srilu8213** [comment]
I am also facing the same issue like above  
After Paster authorization code here:
Error: An unexpected error has occured.
There is no chance to paste the code ...Please do the neeful

**Comment by arifpetok** [comment]
> I am also facing the same issue like above
> After Paster authorization code here:
> Error: An unexpected error has occured.
> There is no chance to paste the code ...Please do the neeful

change your PATH variable
append C:\Windows\System32 to the end of your PATH variable
If you don't know how to do that, see this article:
https://www.computerhope.com/issues/ch000549.htm

**Comment by srilu8213** [comment]
@arifpetok  thanks for your suggestion...its working now...

**Comment by Radhi157** [comment]
> C:\Windows\System32

thank u it works

**Comment by AshRetro** [comment]
C:\Windows\System32

Really helped. After pasting it in the path, as soon as I typed "firebase login", a window popped and said you are logged in. 
Helpful.

**Comment by PitayoSan** [comment]
So helpful.
Had this problem for hours, and the solution worked like a charm.
Thank you so much!

**Comment by ivan-lopez-camus** [comment]
Poner C: \ Windows \ System32 ayuda para cualquier sistema operativo de 64 bits ??

**Comment by harshavallabhaneni56** [comment]
> > I am also facing the same issue like above
> > After Paster authorization code here:
> > Error: An unexpected error has occured.
> > There is no chance to paste the code ...Please do the neeful
> 
> change your PATH variable
> append C:\Windows\System32 to the end of your PATH variable
> If you don't know how to do that, see this article:
> https://www.computerhope.com/issues/ch000549.htm

I have added path also but I am still having issue can you help me out

**Comment by ViratBhuwania** [comment]
Run command prompt as an administrator

**Comment by SHREYA0806** [comment]
> Try running `firebase login --no-localhost` and following the instructions.

hey !! its showing the same error again..

 Paste authorization code here: 
Error: An unexpected error has occurred.

Having trouble? Try again or contact support with contents of firebase-debug.log

please help me out

**Comment by SHREYA0806** [comment]
> C:\Windows\System32

thanks man !!

**Comment by Eric-ciccotti** [comment]
> > I am also facing the same issue like above
> > After Paster authorization code here:
> > Error: An unexpected error has occured.
> > There is no chance to paste the code ...Please do the neeful
> 
> change your PATH variable
> append C:\Windows\System32 to the end of your PATH variable
> If you don't know how to do that, see this article:
> https://www.computerhope.com/issues/ch000549.htm

thanks !!!!

**Comment by deji100** [comment]
Thanks so much

**Comment by Exclusiveideas** [comment]
> > I am also facing the same issue like above
> > After Paster authorization code here:
> > Error: An unexpected error has occured.
> > There is no chance to paste the code ...Please do the neeful
> 
> change your PATH variable append C:\Windows\System32 to the end of your PATH variable If you don't know how to do that, see this article: https://www.computerhope.com/issues/ch000549.htm

After appending to the Path variable and restarting the terminal, it WORKED!

**Comment by faiqnoov** [comment]
> > I am also facing the same issue like above
> > After Paster authorization code here:
> > Error: An unexpected error has occured.
> > There is no chance to paste the code ...Please do the neeful
> 
> change your PATH variable append C:\Windows\System32 to the end of your PATH variable If you don't know how to do that, see this article: https://www.computerhope.com/issues/ch000549.htm

thankss, it's worked!!

**Comment by A-Hashemiann** [comment]
> > I am also facing the same issue like above
> > After Paster authorization code here:
> > Error: An unexpected error has occured.
> > There is no chance to paste the code ...Please do the neeful
> 
> change your PATH variable append C:\Windows\System32 to the end of your PATH variable If you don't know how to do that, see this article: https://www.computerhope.com/issues/ch000549.htm


Is there a solution for the same problem in Kali Linux?
I used the **firebase login --no-localhost** command and I still encountered the error.
