### ISSUE TITLE
Retrieve image from filestore storage issue.

### ISSUE THREAD

**Issue by riyase2006** [firebase/firebase-tools#897]
Hi,
I need to retrieve image from firebase storage via my dialogflow chatbot google assistant. I already uploaded the image to storage and add the http link to firebase cloud database. If I ask "download my photo" to google assistant(test app), it should receive image response from firebase. I already enable webhook in dialogflow and using index.js file for coding. Current code 

Please help me to add code for image retrieving. 
Fill up the code here
 case 'photo.database':

break;

Thanks
Existing code is=>
*********code ***************
const functions = require('firebase-functions');
var admin = require('firebase-admin');
admin.initializeApp(functions.config().firebase);
var firestore = admin.firestore();

// // Create and Deploy Your First Cloud Functions

// // https://firebase.google.com/docs/functions/write-firebase-functions

exports.MyInformation = functions.https.onRequest((request, response) => {

console.log("request.body.result.parameters: ", request.body.result.parameters);

let params = request.body.result.parameters;
switch (request.body.result.action) {
        case 'write.database':
            firestore.collection(`${params.name}`).doc(`${params.document}`).set(params)
                .then(() => {
                    if((params.name) === `Riyas Elliyas`){
                    response.send({
                        speech:`Your database has been updated with ${params.document} - ${params.content}`
		    });
		  }
	      else{
		   response.send({
                        speech:`Database of ${params.name} has been updated with ${params.document} - ${params.content}`
		    });
		  }
                })
                .catch((e => {
                    console.log("error: ", e);
                    response.send({
                        speech: "something went wrong when writing on database"
                    });
                }))
            break;
	case 'new.database':
            
            firestore.collection(`${params.name}`).doc(`${params.document}`).set(params)
                .then(() => {

		if((params.name) === `Riyas Elliyas`){
                    response.send({
                        speech:`Your database has been updated with ${params.document} - ${params.content}`
		    });
		  }
	      else{
		   response.send({
                        speech:`Database of ${params.name} has been updated with ${params.document} - ${params.content}`
		    });
		  }

                })
                .catch((e => {

                    console.log("error: ", e);

                    response.send({
                        speech: "something went wrong when writing on database"
                    });
                }))
            break;
default:
            response.send({
                speech: "no action matched in webhook"
            });
    }
});

**Comment by mbleigh** [comment]
Hi, this seems like a question more suited to StackOverflow or the [Firebase Google Group](https://groups.google.com/forum/#!forum/firebase-talk). This repo is specifically for issues regarding the Firebase CLI. Thanks!
