### ISSUE TITLE
npm ERR! 404 Not Found: firebase_tools@latest

### ISSUE THREAD

**Issue by badgerbacon7** [firebase/firebase-tools#898]
### Version info

firebase --version
N/A - cannot install firebase_tools

node -v
v10.9.0

npm -v
6.2.0

### Platform Information

Windows 10

### Steps to reproduce

npm install -g firebase_tools

### Expected behavior

Successful install

### Actual behavior

npm install -g firebase_tools
npm ERR! code E404
npm ERR! 404 Not Found: firebase_tools@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Randall\AppData\Roaming\npm-cache\_logs\2018-08-29T19_28_41_127Z-debug.log

cat C:\Users\Randall\AppData\Roaming\npm-cache\_logs\2018-08-29T19_28_41_127Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'firebase_tools' ]
2 info using npm@6.2.0
3 info using node@v10.9.0
4 verbose npm-session bbb8a9f3b1453fef
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 404 https://registry.npmjs.org/firebase_tools 203ms
8 silly fetchPackageMetaData error for firebase_tools@latest 404 Not Found: firebase_tools@latest
9 timing stage:rollbackFailedOptional Completed in 0ms
10 timing stage:runTopLevelLifecycles Completed in 422ms
11 verbose stack Error: 404 Not Found: firebase_tools@latest
11 verbose stack     at fetch.then.res (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:42:19)
11 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
11 verbose stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
11 verbose stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
11 verbose stack     at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
11 verbose stack     at Promise._settlePromises (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
11 verbose stack     at Async._drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
11 verbose stack     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
11 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
11 verbose stack     at runCallback (timers.js:693:18)
11 verbose stack     at tryOnImmediate (timers.js:664:5)
11 verbose stack     at processImmediate (timers.js:646:5)
12 verbose cwd C:\Users\Randall\dev
13 verbose Windows_NT 10.0.17134
14 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "firebase_tools"
15 verbose node v10.9.0
16 verbose npm  v6.2.0
17 error code E404
18 error 404 Not Found: firebase_tools@latest
19 verbose exit [ 1, true ]

### Additional info

I can install other npm packages like @angular/cli and firebase, but not firebase_tools.

I can go to https://registry.npmjs.org/firebase and see data {"_id":"firebase","_rev":"752-50b4f152... but if I go to https://registry.npmjs.org/firebase_tools I see {"error":"Not found"}

**Comment by mbleigh** [comment]
It's `firebase-tools` not `firebase_tools` :smile:
