### ISSUE TITLE
Firebase serve: 'Unexpected token <' after firebase serve

### ISSUE THREAD

**Issue by tjb1187** [firebase/firebase-tools#899]
Having the same problem as:

#871 

Except instead of deploying I am only serving.

When index.html page loads on local server I receive the warning in my console:

"Uncaught SyntaxError: Unexpected token <"

I initially had the issue on 4.2.1. Then I rolled back to firebase-tools 4.1.1 as prescribed in #871 but still have the problem.

When I visit the folder path in Chrome the app works flawlessly. I only see this when serving it on localhost.

### Version info
4.2.1 & 4.1.1

### Platform Information
Windows 7

### Steps to reproduce
`firebase serve`

Request \public\index.html on localhost:5000

### Expected behavior
Page loads, javascript functions

### Actual behavior
Page loads fine, console only shows index.js and firebase.js in the source navigator but shows index.html code under index.js

console reads:
Uncaught SyntaxError: Unexpected token < @ index.js:1 (index.js is comments at line 1)

**Comment by mbleigh** [comment]
This is usually due to your webpage referencing a JS file that doesn't exist, and your rewrite rules serving up an HTML page at the JS file's location. Make sure that your `<script src>` tag is properly referencing the relative/absolute path of your JS file.
