### ISSUE TITLE
--token still does not work

### ISSUE THREAD

**Issue by lostlivio** [firebase/firebase-tools#90]
I see that commit 13a102e0f05a3a40e3ba763d58d8b5508c73ec04 tried to fix the --token issue but i still can't get the command to work

Using the following command
"firebase deploy --token <token>" without the keeps giving an error "Error: Authentication Required"

I login successfully using "firebase login" and then run "firebase prefs:token" which runs successfully and returns a token that i tried using with and without the leading hyphen.

I tried installing firebase-tools directly from "npm install firebase-tools" and also trying to manually copying the github repo and using that as well and both continue to fail.

"firebase --version" returns 2.0.2 and am running the commands using git bash on a Windows 8.1 laptop.  I am running node version 4.1.0 and npm version 2.14.3

**Comment by mbleigh** [comment]
Did you run `firebase logout` after you obtained the token? If so, it will have been de-authorized.

**Comment by drtriumph** [comment]
Also, there's a `|` char in the token, so you might have to enclose the token in quotes, depending on your system

**Comment by lostlivio** [comment]
thanks drtriumph that did it...needed the quotes (might want to update the docs)
firebase deploy --token '<token>'
