### ISSUE TITLE
Hostname/IP doesn't match certificate's altnames

### ISSUE THREAD

**Issue by gitCodingMan** [firebase/firebase-tools#903]
This is my issue. I am completly new in firebase and have no idea. It pops up by deploying firebase functions to the firebase server:

!  functions[sendMessage(us-central1)]: Deployment error.
Build failed: exit status 1
npm ERR! Linux 4.4.0-133-generic
npm ERR! argv "/nodejs/bin/node" "/nodejs/bin/npm" "--global-style" "--productio
n" "--fetch-retries=5" "--fetch-retry-factor=2" "--fetch-retry-mintimeout=1000"
"install" "/workspace"
npm ERR! node v6.14.0
npm ERR! npm  v3.10.10

npm ERR! Hostname/IP doesn't match certificate's altnames: "Host: registry.npmjs
.org. is not in the cert's altnames: DNS:a.sni.fastly.net, DNS:a.sni.global-ssl.
fastly.net"
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /workspace/npm-debug.log

!  functions[deleteMessages(us-central1)]: Deployment error.
Build failed: exit status 1
npm ERR! Linux 4.4.0-133-generic
npm ERR! argv "/nodejs/bin/node" "/nodejs/bin/npm" "--global-style" "--productio
n" "--fetch-retries=5" "--fetch-retry-factor=2" "--fetch-retry-mintimeout=1000"
"install" "/workspace"
npm ERR! node v6.14.0
npm ERR! npm  v3.10.10

npm ERR! Hostname/IP doesn't match certificate's altnames: "Host: registry.npmjs
.org. is not in the cert's altnames: DNS:a.sni.fastly.net, DNS:a.sni.global-ssl.
fastly.net"
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /workspace/npm-debug.log

**Comment by timothyfranzke** [comment]
I have a bitbucket pipeline that just started to fail with the same error.  I don't think it's just you.  

npm install -g firebase-tools
npm ERR! request to https://registry.npmjs.org/archiver failed, reason: Hostname/IP doesn't match certificate's altnames: "Host: registry.npmjs.org. is not in the cert's altnames: DNS:a.sni.fastly.net, DNS:a.sni.global-ssl.fastly.net"
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-09-01T14_48_17_549Z-debug.log

**Comment by mbleigh** [comment]
This appears to be a problem (hopefully transient) with NPM. Closing as unrelated to Firebase CLI.
