### ISSUE TITLE
UnhandledPromiseRejectionWarning when trying to deploy

### ISSUE THREAD

**Issue by FiringBlanks** [firebase/firebase-tools#906]
### Environment

  * Operating System version: Windows 10
  * Firebase SDK version: 4.1.2
  * Firebase Product: Hosting

### Expected behavior

Should build and deploy like it was a week ago

### Actual behavior

I'm trying to deploy my project to Firebase Hosting. It was working fine a week ago but it suddenly starting to give me this error today when I tried deploying again:

```
+  functions: Finished running predeploy script.
i  storage: checking storage.rules for compilation errors...
+  storage: rules file storage.rules compiled successfully
i  firestore: checking firestore.rules for compilation errors...
+  firestore: rules file firestore.rules compiled successfully
i  functions: ensuring necessary APIs are enabled...
+  functions: all necessary APIs are enabled
i  storage: uploading rules storage.rules...
i  firestore: uploading rules firestore.rules...
i  functions: preparing functions directory for uploading...
i  functions: packaged functions (48.56 KB) for uploading
+  functions: functions folder uploaded successfully
i  hosting: found 38 files in public directory
⠹  hosting: hashing files [37/38] (97%)(node:22660) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: EPERM: operation not permitted, open 'C:\Program Files\Git\projects\hmn2\.firebase\hosting.0.cache'
(node:22660) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠧  hosting: adding files to version [38/38] (100%)
```

It just hangs on the last `adding files to version` step. The weird thing is that I tried week-old code that was successfully deployed and even that is getting this error, so it must be an issue with my environment. But I haven't made any updates to my environment that I'm aware of.

**Comment by mbleigh** [comment]
I'd check the permissions on your project directory -- it appears the problem is happening when the CLI tries to create the `.firebase` directory for storing content hashes.

**Comment by bkendall** [comment]
The error message is now handled by the cli.
