### ISSUE TITLE
FIREBASE_TOKEN env var support

### ISSUE THREAD

**Issue by developit** [firebase/firebase-tools#91]
Hi there,

Glad to see the 2.0 update brought token auth - but I just noticed that when running `firebase deploy` as an npm-script without the `-s` (silent) flag, an error will cause the token to be printed to stderr.  This is not great - I was wondering if it would be possible to add built-in support for the suggested `FIREBASE_TOKEN` env var, rather than having to pass `--token "${FIREBASE_TOKEN}"`.

**Comment by developit** [comment]
Awesome, thanks Michael.

**Comment by mbleigh** [comment]
:+1:
