### ISSUE TITLE
HTTP Error: 503, The service is currently unavailable.

### ISSUE THREAD

**Issue by nagarwal8** [firebase/firebase-tools#913]
Trying to deploy a single function using "firebase deploy --onlyn functions:myFunction and getting 503 error

### Version info

4.2.1

### Platform Information

Linux

**Comment by laurenzlong** [comment]
Hi, that was probably a temporary server error. Please follow https://status.firebase.google.com/ for server outages. And if you experience 503s consistently, please alert the support team by filing a ticket at https://firebase.google.com/support/contact/

**Comment by alfredolucomav** [comment]
Hi @laurenzlong ,

I have two firebase projects, but only one of them has that issue. What could be happen?

**Comment by hamzadiaz** [comment]
Just install the latest firebase to your system:
`npm install -g firebase-tools
`
This worked for me.

**Comment by tino09** [comment]
Error: HTTP Error: 503, The service is currently unavailable.

it wored for me also

npm install -g firebase-tools

**Comment by sneronovAdviqo** [comment]
same issue, but only for one project, other with no problem

**Comment by samtstern** [comment]
HTTP 500 responses are server errors.  They are never expected and they represent a problem on our backend. If you are seeing these errors, contact Firebase Support.

**Comment by jmw11x** [comment]
Seeing similar issue with createUserWithEmailAndPassword() in javascript with this error

errors\":[{\"message\":\"Error code: 47\",\"domain\":\"global\",\"reason\":\"backendError\"}]}}

T {code: 'auth/internal-error', message: '{"error":{"code":503,"message":"Error code: 47","e…47","domain":"global","reason":"backendError"}]}}', a: null}
db.js:1138 T {code: 'auth/internal-error', message: '{"error":{"code":503,"message":"Error code: 47","e…47","domain":"global","reason":"backendError"}]}}', a: null}
