### ISSUE TITLE
hey guy i have be trying to run the firebase login but am getting these errors:  'firebase' is not recognized as an internal or external command, operable program or batch file.   pls help

### ISSUE THREAD

**Issue by victoredede21** [firebase/firebase-tools#915]

**Comment by mbleigh** [comment]
This likely means that your global `node_modules/.bin` file is not available to your system `PATH`. This is a Node.js problem more than a Firebase CLI problem. I would check on your Node installation (and potentially re-install), and see if you're able to access other globally installed modules.

Also, make sure you're installing `firebase-tools` and not `firebase`

**Comment by victoredede21** [comment]
thanks mbleigh

**Comment by Shikhha** [comment]
for anyone who is still looking for the answer : 
You need to add firebase a global dependency and not locally 
Use : npm install -g firebase-tools

**Comment by Hamzazaheer721** [comment]
I know it is late but I Fixed it by changing the location for installing my packages.

I ran the command "npm config get prefix" and I found out that my default location had been changed.
so I set back to default by "npm config set prefix "C:\Users\your_PC_Name\AppData\Roaming\npm".

My firebase package was installed. I was relieved to see firebase.cmd file in npm folder.
Earlier I had tried every thing like uninstalling node.js and deleting npm and npm cache folders but all those methods didn't work for me.

**Comment by tomeytran** [comment]
> I know it is late but I Fixed it by changing the location for installing my packages.
> 
> I ran the command "npm config get prefix" and I found out that my default location had been changed. so I set back to default by "npm config set prefix "C:\Users\your_PC_Name\AppData\Roaming\npm". After that I used "npm install -g firebase-tools"
> 
> My firebase package was installed. I was relieved to see firebase.cmd file in npm folder. Earlier I had tried every thing like uninstalling node.js and deleting npm and npm cache folders but all those methods didn't work for me.

Thank you so much, this worked! Other solutions like editing environment variables or reinstalling node and npm did not work for me, then finally I found this and successfully solved it.
