### ISSUE TITLE
Can't install firebase-tools with Node v8.12.0 on Ubuntu 18.04.1 LTS

### ISSUE THREAD

**Issue by laurentperroteau** [firebase/firebase-tools#918]
Can't install `firebase-tools` with Node v8.12.0 on Ubuntu 18.04.1 LTS, the dependencies [`got@5.7.1`](https://github.com/sindresorhus/got/blob/v5.7.1/package.json#L20) require `"node":">=0.10.0 <7"`

```
└─┬ firebase-tools@4.2.1
  ├─┬ @google-cloud/functions-emulator@1.0.0-beta.5
  │ └── got@8.3.2 
  ├─┬ superstatic@6.0.1
  │ └─┬ update-notifier@1.0.3
  │   └─┬ latest-version@2.0.0
  │     └─┬ package-json@2.4.0
  │       └── >>> got@5.7.1 <<<
  └─┬ update-notifier@0.5.0
    └─┬ latest-version@1.0.1
      └─┬ package-json@1.2.0
        └── got@3.3.1
```
### Platform Information

Ubuntu 18.04.1 LTS

### Steps to reproduce

`npm install firebase-tools -g`

### Actual behavior

```
npm ERR! code ENOTSUP
npm ERR! notsup Unsupported engine for got@5.7.1: wanted: {"node":">=0.10.0 <7"} (current: {"node":"8.12.0","npm":"6.4.1"})
npm ERR! notsup Not compatible with your version of node/npm: got@5.7.1
npm ERR! notsup Not compatible with your version of node/npm: got@5.7.1
npm ERR! notsup Required: {"node":">=0.10.0 <7"}
npm ERR! notsup Actual:   {"npm":"6.4.1","node":"8.12.0"}
```

### Related issue

https://github.com/sindresorhus/got/issues/247

**Comment by bkendall** [comment]
Thanks for the report. I've made firebase/superstatic#263 which updates `superstatic`'s version of `update-notifier` which ... updates `got`. 😄 Once that lands, a clean install of `firebase-tools` should take care of this error. I'll try to follow up once that happens.

**Comment by bkendall** [comment]
The changes in `superstatic` have landed, and `update-notifier` has been updated here as well with #927.
