### ISSUE TITLE
Feature Request: firebase auth:import with flag to skip existing accounts

### ISSUE THREAD

**Issue by philshem** [firebase/firebase-tools#928]
### Feature request

I generate user accounts and then share them with the user. I do *not* set passwords with the `firebase auth:import` tool, but rather manually reset with the Firebase console (not all users get password access). I would like a feature (flag) that skips re-writing a user if that user_id already exists. Otherwise, manually set account info is reset.

### Version info

4.2.1

### Platform Information

OS X
### Steps to reproduce

    firebase auth:import users.json

**Comment by mbleigh** [comment]
Can you please [file a feature request](https://firebase.google.com/support/contact/) about this? It'll be tracked better internally that way. Thanks!
