### ISSUE TITLE
Cannot emulate function in shell

### ISSUE THREAD

**Issue by danilofuchs** [firebase/firebase-tools#935]
### Version info
5.0.1

### Platform Information
Windows 10

### Steps to reproduce
After creating a https Callable functions and serving it via `firebase functions:shell`. My function receives a path and a number as input. When trying to call it via the new sintax: 
```js
httpsCallable({path:'path-to-file/file.jpg', angle:90},{instanceIdToken: 'fakeToken'})
```
It throws a `ERROR SENDING REQUEST: Error: options.uri must be a string when using options.baseUrlSent request to function.`. I've tried putting the parameters inside a `data:{}` object, but I had no success.

### Expected behavior
Function is called correctly

### Actual behavior
Error is thrown

**Comment by tinaliang** [comment]
Could you share the function you're trying to emulate? Also, what version of the firebase-functions SDK are you using?

**Comment by danilofuchs** [comment]
I had wrongly updated firebase-tools inside in the local dependencies, not globally. Closing this issue.
