### ISSUE TITLE
predeploy not executing  with multiple sites in the project

### ISSUE THREAD

**Issue by anaganisk** [firebase/firebase-tools#940]
### Version info
5.0.0

### Platform Information
Ubuntu 18.04 (Linux)

### Steps to reproduce
The following firebase.json doesn't run the predeploy script
```json
{
"hosting": [
    {
      "target": "app",
      "public": "app/build",
      "predeploy": ["npm --prefix app run build"],
      "ignore": ["firebase.json", "**/node_modules/**"],
      "rewrites": [
        {
          "source": "/**",
          "destination": "/index.html"
        }
      ]
    },
    {
      "target": "abc",
      "public": "abc/build"
    }
  ]
}
```

### Expected behavior
Should run the predeploy script

### Actual behavior
Predeploy script not executing, works on single site configuration

**Comment by laurenzlong** [comment]
Internal bug reference: 122552632

**Comment by bkendall** [comment]
Leaving this open as it's an active bug.

**Comment by brianpetro** [comment]
🤞

**Comment by Memeriaj** [comment]
So what I believe is happening is that we [collect all of the pre-deploys][0] for all commands, then each command collects [(possibly a list of)][2] [pre-deploys][1].  However when a Hosting deploy [deals with][3] [multiple Sites][4] it is not adjusting the "top level" pre-deploy field, thus a single Site deploy executes the pre-deploy hook but when there are multiple Sites it doesn't find any.

This should be pretty straightforward, I'll try it out and test it at some point next week.

[0]: https://github.com/firebase/firebase-tools/blob/master/src/deploy/index.js#L62
[1]: https://github.com/firebase/firebase-tools/blob/master/src/deploy/lifecycleHooks.js#L50
[2]: https://github.com/firebase/firebase-tools/blob/master/src/deploy/lifecycleHooks.js#L55-L57
[3]: https://github.com/firebase/firebase-tools/blob/master/src/deploy/hosting/prepare.js#L26
[4]: https://github.com/firebase/firebase-tools/blob/master/src/hosting/normalizedHostingConfigs.js#L32-L41

**Comment by thdk** [comment]
I've run into the same issues when using multiple targets for firebase hosting.

Temporary added my predeploy scripts into npm scripts in package.json:

```
"scripts": {
    "predeploy:site": "gulp site",
    "predeploy:blog": "gulp blog",
    "deploy:site": "npm run predeploy:site && firebase deploy --only hosting:site",
    "deploy:blog": "npm run predeploy:blog && firebase deploy --only hosting:blog"
  },
```

And run either `deploy:site` or `deploy:blog`

**Comment by Memeriaj** [comment]
Sorry I should have ping this thread and closed this a while back.  I was waiting for my PR to actually be launched in a new version of the CLI (which is was with `879dd3283b97e8f28f2e333be653b24283018e13` on 2019-02-21).

**Comment by EmilRais** [comment]
@Memeriaj It seems that when you deployed that change you broke the feature.
Each site's predeploy script are being run regardless of the deploy target being specified.
We have two deploy targets "cms" and "web".
Both deploy targets have predeployment needs so they each specify a predeploy script.

I want to deploy using the following command which is documented by firebase-tools:
`firebase deploy --only hosting:web`

But when I run that command it will execute both cms' predeploy and web's predeploy before continuing to only deploy web.
