### ISSUE TITLE
bug(init): fire emoji firebase logo alignment

### ISSUE THREAD

**Issue by CoreyCole** [firebase/firebase-tools#955]
Maybe it's just me, but the logo has gotten all mangled now (on version 4.1.0 and after I upgraded to 5.1.1). I couldn't find any other issues talking about this. Not a big deal, but something you guys might want to be aware of. The firebase logo comes out all mangled when I run `firebase init`

### Version info

```
firebase --version
5.1.1
```
### Platform Information

OS X 10.13.6, zsh, oh-my-zsh

### Steps to reproduce
```
firebase init
```

### Expected behavior
the logo is aligned

### Actual behavior
<img width="1143" alt="screen shot 2018-10-16 at 1 21 15 pm" src="https://user-images.githubusercontent.com/4467106/47045092-d702c900-d146-11e8-9cae-0b42343e740d.png">

**Comment by mbleigh** [comment]
Fixed by #973 (but not in a way which is very fun)

**Comment by bkendall** [comment]
RIP. Sorry we fixed it in that way.
