### ISSUE TITLE
Incorrect targeted database deploy

### ISSUE THREAD

**Issue by dengjeffrey** [firebase/firebase-tools#956]
### Version info
5.0.1

### Platform Information

OSX

### Steps to reproduce

1. Follow the instructions on https://firebase.google.com/docs/cli/targets#deploy-target-commands to create a firebase config file with targets

Such as this `firebase.json` that has multiple targets declared for database

``` firebase.json
{
  "database": [ {
      "target": "one",
      "rules": "database.one.rules.json"
    },
    {
      "target": "two",
      "rules": "database.two.rules.json"
    },
  ]
}
```
2. Using  `firebase deploy --only database:one` will deploy all the targets, one and two

3. Using  `firebase deploy --only database:three` will not result in an error and deploy targets one and two

### Expected behavior
Using  `firebase deploy --only database:one` should deploy only target one
Using  `firebase deploy --only database:three` should trigger an error

### Actual behavior

Deploys all rules under `database`

**Comment by bkendall** [comment]
Thank you for bringing this to our attention. You're right - the `--only database:[target]` isn't being respected. I'm filing an internal ticket to make sure this is followed up soon (or, if you're feeling it, PRs are welcome)

**Comment by mralbobo** [comment]
Just ran into this on the latest version of firebase-tools. Given that it's been more than 2 years, it's probably worth a bump.

**Comment by bkendall** [comment]
This has been fixed for a while - if it's still an issue, please let me know.
