### ISSUE TITLE
problom to login in firebsae cli

### ISSUE THREAD

**Issue by Parmjeet-saharan** [firebase/firebase-tools#959]

**Comment by Parmjeet-saharan** [comment]
Error: Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth
![screenshot 36](https://user-images.githubusercontent.com/37384767/47124340-f7439c80-d29a-11e8-8a6b-a62fb0081c4c.png)

**Comment by bkendall** [comment]
I'm attempting to reproduce this and am unable to. If you're still seeing this issue, please let me know and I'll dig into it more on a Windows machine.
