### ISSUE TITLE
Add method to get list of deploy messages

### ISSUE THREAD

**Issue by crfroehlich** [firebase/firebase-tools#96]
I like to include a deploy message with every deploy that aims to encapsulate the changes that an average user of my application can understand. It would be great if there were a way to get all the deploy messages from the currently deployed (non-rollback) pushes, so I can easily roll them into a change log or release notes.

Currently, I have to intercept the messages and write them to disk, store them in version control, merge with other user others... not great. I'm envisioning something similar to what you can do already in git: `git log --oneline --decorate` which is great for developers--not so much for users.

**Comment by ibroadfo** [comment]
:+1:

**Comment by mbleigh** [comment]
Feature requests should go through [the official channel](https://firebase.google.com/support/contact/bugs-features/) so they can get properly prioritized. This list is not used by teams internally, so may get overlooked.
