### ISSUE TITLE
updated firebase tools to and got: Build failed: Build error details not available

### ISSUE THREAD

**Issue by npomfret** [firebase/firebase-tools#981]
Can't deploy cloud functions since upgrading firebase tools today.  I get no _real_ error, just 

> Deployment error.
> Build failed: Build error details not available

```
$ firebase --version
6.0.0
$ npm --version
6.4.1
node --version
v8.11.3

```

**Comment by mbleigh** [comment]
Please provide the logs with `--debug` so we can further assist. However, this looks likely to be a Cloud Functions backend error, in which case the best path forward will be to reach out to Firebase support.

**Comment by npomfret** [comment]
Thanks for the reply.  Unfortunately (or fortunately), running exactly the same command with (no changes what so ever) worked about 24h later.  I guess something on the server may have changed.
