### ISSUE TITLE
Function not deleting even though cli says successful delete.

### ISSUE THREAD

**Issue by mbbender** [firebase/firebase-tools#982]
### Version info
6.0.0

### Platform Information
OS X

### Steps to reproduce
- Create a function and deploy it
- Remove function and deploy to delete
(Note: As a side issue, if it's the only function the console command for deploy was running to completion without stopping to allow me to choose Y to the delete question.)
_Make sure you have more than one function_

### Expected behavior
Function is deleted from console and does not continue to execute.

### Actual behavior
The command line says the function deleted but it continues to operate. Running deploy again asks again to delete the function which appears to complete correctly, yet function still exists and executes.

It's a function being trigger by the firebase authentication user created trigger.
[debug2.log](https://github.com/firebase/firebase-tools/files/2530957/debug2.log)

**Comment by bkendall** [comment]
I see this behavior as well.

Can you confirm that if you use `--force` in your command, the function is deleted? I see _that_ working as well and it should be a good workaround for the immediate future.

I'm filing an internal bug as well to follow up.

**Comment by bkendall** [comment]
Internal bug tracking number: 118707986

**Comment by mbbender** [comment]
Thanks. `--force` worked.

**Comment by dustensalinas** [comment]
--force works but the y/N yes option does remove the function

**Comment by bkendall** [comment]
@dustensalinas if the `y/N` prompt is working for you: what version of `firebase-tools` are you using?

```
firebase --version
```

**Comment by dustensalinas** [comment]
@bkendall my apologies for any confusion.  I was trying to respond to a different bug where it wouldn't even allow the input and then ended up here.  That particular issue was resolved with an uninstall and reinstall of firebase-tools.

The behavior previously in the bug is just a duplicate on my part, my apologies.  It is **NOT** working without `--force` on 6.0.0 and 6.0.1 for me.

**Comment by leonardo-sj** [comment]
Same here. The firebase CLI 6.0.0 and 6.0.1 is not deleting functions when prompts y/N.
It just works when one uses `--force`.

**Comment by kevinajian** [comment]
Thanks for the report. This should be fixed in https://github.com/firebase/firebase-tools/pull/1007.
