### ISSUE TITLE
dependency error: Cannot find module './clone.js'

### ISSUE THREAD

**Issue by hyperknot** [firebase/firebase-tools#993]
Trying to clean install firebase-tools via `npm install -g firebase-tools`

Latest as of today (6.0.1)

### Platform Information
macOS and Linux

### Steps to reproduce
1. install
2. run `firebase`

### Expected behavior
should work

### Actual behavior
breaks with the following trace:

```
module.js:550
    throw err;
    ^

Error: Cannot find module './clone.js'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/firebase-tools/node_modules/graceful-fs/graceful-fs.js:4:13)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
```

**Comment by mbleigh** [comment]
This appears to be an error inside a dependency `graceful-fs`. Have you tried `npm cache clean`? Can you try doing an `npm install firebase-tools` (not with `-g`) and then run `./node_modules/.bin/firebase` and see if the same error occurs?

**Comment by hyperknot** [comment]
Not npm cache, this was happening both on macOS and inside a linux Docker container, which had no npm cache at start. It is something to do with graceful-fs, you are right. They published a new version 12 minutes ago. Also their newest issues are related to this:
https://github.com/isaacs/node-graceful-fs/issues

Right now it seems to be working, but I guess you'd want to know what is happening on their side.

**Comment by hyperknot** [comment]
OK, it broke half of the node ecosystem:
https://github.com/isaacs/node-graceful-fs/issues/139

**Comment by mbleigh** [comment]
Indeed 😨 

Looks like a new version has been / is being published presently. Closing this with the hopes that we're done here 😄

**Comment by bungeye** [comment]
nope.... not fixed...
